### ISSUE TITLE
As of nightly 2021-08-25, most macros cause `missing-unsafe` errors

### ISSUE THREAD

**Issue by AaronKutch** [rust-lang/rust-analyzer#10047]
Since some recent nightly (In the past week or two since I've updated), rust-analyzer is almost unusable for me on large codebases because of the number of errors produced.

A program as simple as this one:
```
fn main() {
    dbg!("hello?");
}
```
produces "this operation is unsafe and requires an unsafe function or block"

edit: actually, I don't know if my rust-analyzer is nightly, but I know it was updated just today

**Comment by akhilman** [comment]
I have the same error in rust-analyzer 996300f 2021-09-05 dev

**Comment by bjorn3** [comment]
Your rust-analyzer version is from 15 days ago. Updating it to the latest version should fix the problem.

**Comment by akhilman** [comment]
996300f seems to be latest version provided by rustup nightly toolchain components

**Comment by lnicola** [comment]
Yeah, that's expected. There were some problems updating the `rustup` version. You can keep an eye on https://github.com/rust-lang/rust/pull/88685.

**Comment by bjorn3** [comment]
The rustup version will be updated in https://github.com/rust-lang/rust/pull/88685. If you are lucky it will be included in the next rustc nightly.

**Comment by bionicles** [comment]
somehow this surfaced for me in 2025!

![Image](https://github.com/user-attachments/assets/2885340d-689a-414b-92b7-218d2d23b243)

**Comment by mlp1802** [comment]
My  project is LITTERED with "unsafe" errors for "vec![]". How is this even possible? using today's toolchain but the problem was there for the older nightly toolchain as well.

**Comment by lnicola** [comment]
@mlp1802 [#18842](https://github.com/rust-lang/rust-analyzer/issues/18842).
