### ISSUE TITLE
Macro expansion issue

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust-analyzer#10087]
I'm using ra-version 2021-08-09, and here's my code (using nightly compiler):
```rust
#![feature(decl_macro)]
pub(crate) macro region_forward_label(|$lbl_:lifetime| {$($s: stmt)*} $lbl:lifetime <- ) {
    #[allow(redundant_semicolons, unused_labels, unreachable_code)]
    $lbl : loop {
        $($s)*;
        break;
    }
}

fn main() {
    region_forward_label!{|'lbl| {
        println!("Hello world!");
    }
    'lbl <-
    }
}
```

Currently this compiles fine, but RA is displaying a "expected Statement" error. What's up?
(It has the same issue if using `macro_rules`)

**Comment by wyatt-herkamp** [comment]
I just tested this on `rust-analyzer version: 0.4.1876-standalone (574e23ec5 2024-03-09)`

You might want to try again. I think it might of been solved already.
