### ISSUE TITLE
Generate function assist should infer return type from pattern matches

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust-analyzer#10122]
In this example:

```rust
if let Err(e) = does_not_exist_yet() {
    // do stuff
}
```

it's pretty obvious that `does_not_exist_yet` is supposed to be a function returning a `Result<_, _>`, but rust-analyzer doesn't currently infer this.

**Comment by lowr** [comment]
It seems like we do this now. Could you check if it matches your expectations?

**Comment by jplatte** [comment]
Right, it works in trivial cases. Still doesn't work

- for `async fn`, i.e. `if let Err(e) = does_not_exist_yet().await` generates `async fn run() -> _`
- if the function containing the `does_not_exist_yet()` call is annotated with an attribute (both `#[tokio::main]` and `#[tracing::instrument]` seem to break the analysis somehow)

**Comment by lowr** [comment]
I'm pretty sure we can make the first case work, but not sure about the second one. As you may know, we're generally having hard time dealing with those macros... Thanks for the additional info anyway!

**Comment by Veykril** [comment]
second one is a general issue with assists and something that needs greater re-architecturing, possibly related with the token map rewrite

**Comment by jplatte** [comment]
Since #15012 is merged, should this be close? Or kept it open as a reminder to retry the macro case after the re-architecting has happened (in which case I think `S-actionable` should be removed)?

**Comment by Veykril** [comment]
Attributes break most assists and I'm pretty sure we have a few talking about that specifically already so let's close this.
