### ISSUE TITLE
Syntax error is shown for visibility modifier for tuple inside tuple struct

### ISSUE THREAD

**Issue by alexyarovoy** [rust-lang/rust-analyzer#10223]
After today's update of rust-analyser I started to get errors for code like this:

`pub struct MyTestStruct (pub (String, i32));`

It generates a lot of errors in rust analyzer, starting with "Syntax Error: incorrect visibility restriction".
cargo check or cargo run has no issues with this code.

Changing code to
`pub struct MyTestStruct ((String, i32));`
or
`pub struct MyTestStruct (pub String);`
show no errors.

Seems like rust analyzer can not handle visibility modifier for tuple.

Everything worked fine with last week's update.

**Comment by jonas-schievink** [comment]
This looks like it was caused by https://github.com/rust-analyzer/rust-analyzer/pull/9651, but that was already included in several releases.

It's not hard to fix, but the fix breaks the `in` completion in `pub($0)`.

**Comment by jonas-schievink** [comment]
Pushed a partial fix to https://github.com/jonas-schievink/rust-analyzer/commit/ca55b11018d458ab4114ea19a667be778eef472f

**Comment by Young-Flash** [comment]
seems it has been solve now
![image](https://github.com/rust-lang/rust-analyzer/assets/71162630/24535fbb-786c-410f-b263-750b4f2539d9)
