### ISSUE TITLE
Inline function assist doesn't update `Self`

### ISSUE THREAD

**Issue by Nadrieril** [rust-lang/rust-analyzer#10291]
If I run the inline function assist on the call of `Foo::bar()` in the following:
```rust
struct Foo;

impl Foo {
    fn foo() {}
    fn bar() {
        Self::foo()
    }
}

fn main() {
    Foo::bar()
}
```
I get:
```rust
fn main() {
    Self::foo()
}
```
which fails to compile. I would like to get `Foo::foo()` instead.

PS: much love to this awesome project, y'all have built an excellent tool :heart:

**Comment by Veykril** [comment]
The current implementation is basically just a copy paste of the function body(except for `self` which is properly replaced).
So ye, correcting paths where possible is definitely something the assist should do in general.

**Comment by ice1000** [comment]
Should be closed by my pr :p
