### ISSUE TITLE
Re-exported concat macro causes "failed to resolve macro" error

### ISSUE THREAD

**Issue by NicholasGorski** [rust-lang/rust-analyzer#10300]
Minimal example, reduced from a larger macro:

```rust
pub mod private {
    pub use core::concat;
}

macro_rules! demo {
    ($fmt:expr $(, $($args:tt)*)?) => {{
        // The use of `$crate::private::concat` here causes an error,
        // but unqualified `concat!` does not. They ought to be identical?
        __impl_demo!($crate::private::concat!(": ", $fmt), $($($args)*)?)
    }};
}

macro_rules! __impl_demo {
    ($fmt:expr $(, $($args:tt)*)?) => {{
        // This one doesn't care about which concat is used.
        //
        // However, the use of panic! seems to be necessary; for example,
        // using `println!` works as expected. Weirder, if instead one does
        // `assert!(true, ...)` then *both* expansions below give the error.
        panic!(concat!("prefix", $fmt), $($($args)*)?);
    }};
}

pub fn foo(i: u32) {
    if i == 0 {
        demo!("{}", 1); // A
    }

    if i == 1 {
        demo!(""); // B
    }
}
```

As is, [this is valid code that compiles](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e3b7b8b99751a156ea1e2d0264a4a0a7). However, rust analyzer emits "failed to resolve macro" at expansion B.

Furthermore, as noted one can use `println!` and neither expansion has an error, or switch to `assert!` and get an error at both expansions. In all cases there is no actual error during rustc compilation.

(The use of re-exported `concat` in the private module is to avoid call-site environment pollution in the macro expansion.)

Let me know if this is unclear or if I've made an error along the way. Thanks!

**Comment by jonas-schievink** [comment]
Reduces to:

```rust
mod private {
    pub use core::concat;
}

macro_rules! m {
    () => {
        panic!(concat!($crate::private::concat!("")));
    };
}

fn f() {
    m!();
}
```

Might be caused by a limitation in our `$crate` handling (perhaps we're losing information about the origin crate after passing through `panic`?)

**Comment by XFFXFF** [comment]
Can't reproduce it. 
RA version: [73668334f05c3446b04116ccc3156240d2d8ab19](https://github.com/rust-analyzer/rust-analyzer/tree/73668334f05c3446b04116ccc3156240d2d8ab19) with `cargo xtask install`
![image](https://user-images.githubusercontent.com/30254428/141755764-4eed3a80-ab74-4a14-9a01-087fc3629b92.png)

**Comment by NicholasGorski** [comment]
Hm, strange. I am using v0.2.817 (~1 hour ago at time of writing) and still reproducing the issue. Am I incorrectly updated?

**Comment by jonas-schievink** [comment]
No, I can still repro with both snippets in this thread

**Comment by jonas-schievink** [comment]
Ah, this also reproduces the error:

```rust
#[macro_export]
macro_rules! inner {
    () => {
        ""
    };
}

macro_rules! m {
    () => {
        concat!($crate::inner!())
    };
}

fn f() {
    m!();
}
```

Looks like we just discard the necessary hygiene info for eager macros.

**Comment by jonas-schievink** [comment]
This should also be accepted but isn't:

```rust
#[macro_export]
macro_rules! inner {
    () => {
        ""
    };
}

fn f() {
    concat!(crate::inner!());
}
```
