### ISSUE TITLE
Type inference not working for `Deref`

### ISSUE THREAD

**Issue by sticnarf** [rust-lang/rust-analyzer#10312]
The issue title is not so accurate. It is a bit complex to produce the failure. Any simplification to those traits will make the issue disappear.

```rust
use std::{marker::PhantomData, ops::Deref};

trait Trait1: Trait3 {
    type Assoc: Trait2;
}

trait Trait2
where
    Self: Trait3,
{
}

trait Trait3 {
    type Bytes: Bytes;
}

trait Bytes: Deref<Target = [u8]> {}

struct S<T: Trait1> {
    s: Box<str>,
    _phantom: PhantomData<T>,
}

impl<T: Trait1> S<T> {
    fn f(&self) {
        let s /* &Box<str> */ = &self.s;
        let s /* &{unknown} */ = &**s;
    }
}
```

In the example above, the type of `self.s` is resolved successfully, but it cannot resolve the type of the deref target.

**Comment by flodiebold** [comment]
This might actually be a similar or the same issue as #9990, where Chalk gets confused by unnecessary (for the current goal) clauses in the environment.

**Comment by andylizi** [comment]
I'm not sure this is the same issue, but `Deref` inference is also failing on `Cow<T>`:

![deref_cow](https://user-images.githubusercontent.com/12008103/135874789-1ad2de3e-8ba5-4c5e-9c8e-acd7eb2ffa6c.png)

`str.as_ref().find()` works fine. Switching from `std::borrow::Cow` to a minimal version (copy-pasted from std and removed all but necessary) works fine.

**Comment by lowr** [comment]
Both snippets in this issue seem to work fine today :smile: Closing as completed, but feel free to file a new issue if you're still having similar problems.
