### ISSUE TITLE
`impl` type is shown as `{unknown}` in signature help

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rust-analyzer#10432]
```rust
fn hash(data: impl AsRef<[u8]>) {}

fn test() {
    hash(<|>)
}
```

![image](https://user-images.githubusercontent.com/5961244/135731247-3bb30dc3-b7cd-4725-b8b3-0182e88d26bc.png)

rust-analyzer: 60c5449120659fdef1b716c9e584356accf5e5e3 (current master rn)

**Comment by lnicola** [comment]
I think it's a rendering problem, hover works "fine":

![image](https://user-images.githubusercontent.com/308347/135742838-2f2a9dd8-6207-4bf4-9cc2-2b0bb9893780.png)

**Comment by Veykril** [comment]
I think it is the fact that we substitute type variables in signature views that we get an unknown here.

**Comment by flodiebold** [comment]
Yes, though that's not really useful for impl trait parameters so maybe we should special-case it to display the impl trait type for signature view instead.
