### ISSUE TITLE
Memory Usage (Clears Database) panicks

### ISSUE THREAD

**Issue by MolotovCherry** [rust-lang/rust-analyzer#10444]
Not much to say here,

Running the latest nightly (as of this date), ran the "Memory Usage (Clears Database)" command, and it panicked. Interestingly enough, I ran the "Status" command after this one, and the same error causes it to panick evey time (In fact, as soon as I click "Go to Output" it panicks again endlessly). I think it fails on any command now.

In the end, the only thing that made RA usable again was Restarting the server.

I grabbed the version of RA for you. `rust-analyzer 60c544912 2021-10-03 nightly`

```
thread '<unnamed>' panicked at 'no value set for FileSourceRootQuery(FileId(107))', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.17.0-pre.1\src\input.rs:106:32
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 8:32:29 AM] Request textDocument/codeLens failed.
  Message: server panicked: no value set for FileSourceRootQuery(FileId(107))
  Code: -32603
```
So, I decided to run the Memory Usage command again after it restarted, just to see what happens. It crashed again, same as before. Looks reproducible
```
thread '<unnamed>' panicked at 'no value set for FileSourceRootQuery(FileId(1))', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.17.0-pre.1\src\input.rs:106:32
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 8:39:54 AM] Request textDocument/codeLens failed.
  Message: server panicked: no value set for FileSourceRootQuery(FileId(1))
  Code: -32603 
```

**Comment by lnicola** [comment]
See https://github.com/rust-analyzer/rust-analyzer/issues/9168, but now everything seems to break after running "Memory Usage", which I don't think it used to do at the time.

**Comment by jonas-schievink** [comment]
This is sort of expected behavior, since we want to include memory usage of database inputs in the memory usage calculation. You can fix it by typing something.

Perhaps we should mark developer-only commands somehow, or hide them from normal users if that's possible?
