### ISSUE TITLE
within `asm!` the token "in" highlights like a normal keyword, not like a register specifier.

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-analyzer#10461]
The "in" token should highlight the same as other register specifiers when used inside of `asm!`

![Screenshot 2021-10-04 10 45 33](https://user-images.githubusercontent.com/5456384/135891147-6adc49d2-f200-4aa6-90bb-ed22d8109e6f.png)

(note: it would also be fine if *all* register qualifiers and the `options` entry were highlighted like keywords, as long as it's consistent)

**Comment by jonas-schievink** [comment]
We don't currently have any semantic highlighting for `asm!`, so this is just caused by the built-in grammar. cc https://github.com/rust-analyzer/rust-analyzer/issues/6031
