### ISSUE TITLE
VS Code Extension doesn't work outside of mod.rs in subfolders

### ISSUE THREAD

**Issue by lanodor** [rust-lang/rust-analyzer#10488]
In my subfolders under src/ , for example:
```
src/
    application/
        mod.rs
        engine.rs
    main.rs
    test.rs
```

rust-analyzer only works in main.rs, test.rs and mod.rs, but not in engine.rs. 
main.rs has "mod application"
I tried both "pub mod engine;" and "!include("engine.rs")" inside mod.rs, in neither case I had extension working inside engine.rs

At the start of my engine.rs file, I have 2 dots that displays message: "file not included in module tree". Even though main.rs had "mod application" and and application/mod.rs has "pub mod engine".
And my code compiles with main.rs using stuff defined inside engine.rs with no problem.

is this normal behavior or a bug ?
thanks

**Comment by lnicola** [comment]
I assume you also have a `Cargo.toml` file?

> "!include("engine.rs")"

That's `include!`, but you shouldn't need to do that.

**Comment by lnicola** [comment]
Hmm, it does work for me:

![image](https://user-images.githubusercontent.com/308347/136546214-48476d7f-3dc2-4cbd-8b95-3229c0c65364.png)

![image](https://user-images.githubusercontent.com/308347/136546237-fae71ac8-61aa-4381-92c9-1f47246600c2.png)

**Comment by lanodor** [comment]
It's the version I downlaoded from the Marketplace: "0.2.768"
So I guess it's a bug with my VS Code, I disabled all other extensions but didn't work either .. I'll maybe try reinstalling VS code

**Comment by lanodor** [comment]
I managed to fix it, it was super weird.
First I noticed renaming engine.rs to any other name worked. It just didn't work when it was named "engine.rs", but for ex "enginee.rs" worked. I removed the file and created it again, same issue.
I removed the file, switched to another rust project, switched back and recreated "engine.rs" now it works.
I have no messages in rust analyzer language output

I don't remember renaming "Engine.rs" to "engine.rs" but it is possible I did that mistake. But I just tried that and it did not re introduce the bug. anyway thanks for the help

**Comment by lanodor** [comment]
I did reload the project multiple times before that , disable/reenable extension, , cargo clean etc.. it had no effect.

**Comment by Blyxyas** [comment]
I also had this same problem, I tried with include! and it didn't worked.
If someone is searching for a solution, change whatever you have with

```
#[path = FILE PATH]
mod MODULE;
use MODULE;
```

This worked for me, without doing weird things
