### ISSUE TITLE
Parts of RA re-execute itself, making it unsuitable for use as a library

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/rust-analyzer#10516]
Specifically https://github.com/rust-analyzer/rust-analyzer/blob/ed4b312fa777ebb39ba1348fe3df574c441a485e/crates/rust-analyzer/src/cli/load_cargo.rs#L44-L63

I was surprised, because the comment says "this function is used by external tools that use rust-analyzer as a library" - but it then promptly re-executes RA.

I was able to work around via environment variables in my binary code, but I couldn't find this gotcha documented anywhere (in particular, in ARCHITECTURE.md).

**Comment by flodiebold** [comment]
I suspect the consumers using this function don't enable proc macros. IMO the `rust-analyzer` crate is not _really_ intended as a public interface. But ping @matklad

**Comment by flodiebold** [comment]
Yeah: https://github.com/regexident/cargo-modules/commit/5c71c97a2d5be790392f96e560dc480f0b3383e8
