### ISSUE TITLE
Rustfmt-ify expansion of macro

### ISSUE THREAD

**Issue by emi2k01** [rust-lang/rust-analyzer#10548]
Just like `cargo-expand`, it'd be cool if Rust Analyzer had an option to format the expansion of macros.

**Comment by lilyball** [comment]
Either that, or allow me to run Format Document on the resulting editor. Trying to do so right now gives me a "Cannot edit in read-only editor" error (in VSCode). Probably formatting the initial expansion is better though.

**Comment by Veykril** [comment]
The problem here is that macros don't necessarily expand to something on its own that rustfmt can format(to my knowledge) so this wouldn't always work

**Comment by bjorn3** [comment]
It should be possible to wrap the macro output in for example `fn foo() { ... }` or `fn foo() { let ... = (); }` depending on the context in which the macro expanded and then pass it to rustfmt. Macros never expand to raw tokenstreams.

**Comment by lilyball** [comment]
I did just realize yesterday that the expansion does still include `$crate`, which isn't legal outside of macros, and unfortunately rustfmt cares.

```console
> echo 'fn foo() { $crate::print("Bar"); }' | rustfmt
error: expected expression, found `$`
 --> <stdin>:1:12
  |
1 | fn foo() { $crate::print("Bar"); }
  |            ^ expected expression
```

**Comment by Veykril** [comment]
Mmh ye that is a problem since we can't always replace them with the crate name its referring to since the crate in question isn't necessarily in the nameable dependencies of the current crate. We could replace `$crate` with some special valid identifier, rust rustfmt and then replace them it back in the output again I suppose?

**Comment by lnicola** [comment]
CC https://github.com/rust-analyzer/rust-analyzer/issues/7532
