### ISSUE TITLE
Feature request: `#[cfg(rust_analyzer)]`

### ISSUE THREAD

**Issue by kdy1** [rust-lang/rust-analyzer#10591]
There should be a way to exclude some items from rust analyzer, just like `#[cfg(not(rls))]`.

I need this because https://docs.rs/testing/0.14.1/testing/attr.fixture.html macro expands to an enormous amount of items, and it disturbs writing code.

**Comment by lnicola** [comment]
Strange, that looks like the "incorrect case" diagnostic. We support an `#[allow]` for that, but it doesn't always work.

**Comment by Veykril** [comment]
Isn't the problem here that we try to fix the casing of an identifier generated by a proc-macro?

**Comment by flodiebold** [comment]
I've created #12651, let's close this one.
