### ISSUE TITLE
New assist: "Reorder struct fields to match struct definition"

### ISSUE THREAD

**Issue by agluszak** [rust-lang/rust-analyzer#10620]
I was wondering how to fix the problem with the insertion order when new fields are filled (context: [ERA08](https://www.youtube.com/watch?v=n5LDjWIAByM&t=3825s)). If the fields are correctly ordered at the moment of insertion, it is easy to find the right place for the new field. But what if they aren't? :) We could create a new assist. It would do the following change:

```rust
struct Struct {
    field: String,
    field_added_later: i32,
    other_field: bool,
}

fn main() {
    let test = Struct {
        field: "test".to_string(),
        other_field: true,
        field_added_later: 2,
    };
}
```

->

```rust
struct Struct {
    field: String,
    field_added_later: i32,
    other_field: bool,
}

fn main() {
    let test = Struct {
        field: "test".to_string(),
        field_added_later: 2,
        other_field: true,
    };
}
```

**Comment by Veykril** [comment]
We already have this
