### ISSUE TITLE
Run | Debug duplicates

### ISSUE THREAD

**Issue by ItsNilDev** [rust-lang/rust-analyzer#10626]
On emacs, When I try to write a test something like this: 
```rust
#[test]
fn test_
``` 
Every time I press space a new `Run Test | Debug` appears next to it like this. I think the problem is with `runnables.rs`
![image](https://user-images.githubusercontent.com/61497342/138597614-b859e092-fc47-4d5b-a8b1-bb02290f011a.png)
I'm using rust-analyzer version: `rust-analyzer 2021-10-18`
Is there a way that i can disable this feature on emacs, if it's not fixable?

**Comment by ahmedriza** [comment]
I was trying to turn off the Debug/Run "lens" as it's too distracting, but couldn't find a way to turn off that in emacs (I think the option is not exposed in emacs).  

The only way I've found to turn off this is by turning off lenses altogether, by adding the following to the emacs config file:
```
(setq lsp-lens-enable nil)
```
as documented in https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/

**Comment by Veykril** [comment]
Do you still encounter this problem?
