### ISSUE TITLE
How to enable diagnostics on inactive #[cfg]

### ISSUE THREAD

**Issue by SummerVibes** [rust-lang/rust-analyzer#10661]
e.g.
```
cfg_if! {
    if #[cfg(target_arch = "x86_64")] {
        #[path = "arch/x86_64/mod.rs"]
        mod arch;
        pub use self::arch::special as x86_64;
    } else if #[cfg(any(target_arch = "riscv32", target_arch = "riscv64"))] {
        #[path = "arch/riscv/mod.rs"]
        mod arch;
    }
}
```
I want to enable diagnostics on riscv32 arch mod, but the diagnostics only show on x86_64 arch mod, is there a way to do this? Thanks.

**Comment by indirection42** [comment]
Any updates now?

**Comment by Veykril** [comment]
Set the `rust-analyzer.cargo.target` setting to the target you want analysis for

**Comment by Veykril** [comment]
Additionally, there is now a `rust-analyzer.cargo.cfg` (might have a differnent name, I don't exactly recall it) that can be used for other cfgs.
