### ISSUE TITLE
"Reload required due to source changes of a procedural macro" persists after reload

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust-analyzer#10719]
When changing a proc-macro, the vscode status bar shows rust-analyzer requiring a reload, as shown in the screenshot in #10596. When clicking this status bar item, rust-analyzer seems to do some form of reload, but the warning in the status bar stays there.

cc @Veykril who added the status change

**Comment by Veykril** [comment]
Ye turns out we don't even reload the proc-macros when clicking the status icon which I completely forgot to check 😅 So currently this still needs an editor reload/session restart

**Comment by mrahhal** [comment]
Any update on this? Spent some amount of time trying to figure out why my macro is not working after I renamed it. Seems to be this issue. Renaming it to the old name makes it work again. And only reloading all of vscode makes it pick up the change. Anything I can do to help with this?

**Comment by Blyxyas** [comment]
I just wanted to say that I have the same issue, using the pre-release version `v0.3.1039`. Exactly the same issue just with a hello world macro (Code below)

Am I doing something wrong?
```
use proc_macro::TokenStream;

#[proc_macro]
pub fn hello_world(input: TokenStream) -> TokenStream {
	let s = input.to_string();
	println!("{}", s);
	TokenStream::new()
}
```

**Comment by Veykril** [comment]
Can confirm this is still happening

**Comment by winksaville** [comment]
Still happening for me as of 2022-06-02.
