### ISSUE TITLE
Feature request: Setting to pull import suggestions/autoimports from `core::` not `std::`

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rust-analyzer#10718]
Sorry in advance if I just failed to find the way to do this.

I would like to be able to configure r-a to prefer `core::` for autoimports (err, the import suggestion list, I guess) whenever available, rather than `std::`. It already does this when it knows `#![no_std]` is enabled, but often this is conditional on some feature which happens to be on under the current r-a configuration, but isn't guaranteed to be on in that module, etc.

I would honestly even be fine if this option forced r-a to only ever use `core::` for this and ignore `std::`, since I usually have to put imports from `std::` in some scope or behind a `#[cfg]` anyway.

**Comment by bjorn3** [comment]
I think it makes sense to default to `core::` in case of a conditional `#![no_std]` and only fallback to `std::` if no `core::` path exists in that case.

**Comment by jonas-schievink** [comment]
> I think it makes sense to default to `core::` in case of a conditional `#![no_std]` too and only fallback to `std::` if no `core::` path exists in that case.

This is now implemented in https://github.com/rust-lang/rust-analyzer/pull/12041
