### ISSUE TITLE
Examples have unresolved import errors

### ISSUE THREAD

**Issue by CGMossa** [rust-lang/rust-analyzer#10854]
Error messages are not getting propagated to Rust-analyzer if you have an example in the crate;
Even if using the latest `nightly` rust and rust-analyzer.

If anyone is experiencing this as well, then I'll do some deeper digging in the weekend.
But it is all over the place with me if I use nightly Rust with RA..

**Comment by CGMossa** [comment]
I've made a temporary project and added an example to it. I'm not seeing the same issues with it.
In my project it seemed like not all info, warnings, and errors would propogate;
And I was working on an example at the time.

If I change to `stable` channel in the `rust-toolchain.toml`-file, i.e. so RA is using stable Rust,
then the errors would propogate.

**Comment by Veykril** [comment]
We need a minimal repro for this to be actionable. It's rather unclear what exactly the cause here could be.

**Comment by CGMossa** [comment]
I've found it!

A fresh project with this in the in the `Cargo.toml`, with atleast one dependency, then it doesn't work anymore:

```toml
[profile.dev.package."*"]
opt-level = 2
```

**Comment by CGMossa** [comment]
Anyone knows if this related to any other issue or what might be going on here?

**Comment by lnicola** [comment]
No, can you share an example? My gut feeling is that we're not reloading everything after a `Cargo.toml` change, so the specific thing you posted above doesn't matter.

**Comment by CGMossa** [comment]
I did write that it stops working with the `[profile.dev.package."*"]` and having atleast one dependency.

**Comment by CGMossa** [comment]
I've just checked this again. And it is no longer an issue.
Maybe you need a check for this? For now, I'll just close this.

**Comment by yymm120** [comment]
```
[lib]
crate-type = ["cdylib"]
```
↓
```
unresolved import `sample_server`
use of undeclared crate or module `sample_server`
```

solution: 
```
# [lib]
# crate-type = ["cdylib"]
```

**Comment by ChayimFriedman2** [comment]
@yymm120 I don't think Cargo can depend on a cdylib. You can also output a normal library: `crate-type = ["lib", "cdylib"]`.
