### ISSUE TITLE
VS Code extension installation error: unable to verify the first certificate

### ISSUE THREAD

**Issue by tumluliu** [rust-lang/rust-analyzer#10866]
Hi there, I tried installing rust-analyzer extension via remote SSH in vscode behind a corporate proxy. But it failed with such message:

```
ERROR [11/26/2021, 9:29:50 AM]: Bootstrap error [st [FetchError]: request to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/2021-11-22 failed, reason: unable to verify the first certificate
	at ClientRequest.<anonymous> (/home/me/.vscode-server/extensions/matklad.rust-analyzer-0.2.826/out/main.js:39:48367)
	at ClientRequest.emit (events.js:315:20)
	at TLSSocket.socketErrorListener (_http_client.js:469:9)
	at TLSSocket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)] {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

I have set `http.proxyStrictSSL` to `false` and `http.proxy` properly, and don't have problem with installing other extensions. My git and cargo both work fine from cmdline. Github API (the above url) is reachable as well. What could be the problem here? Thanks a lot in advance!

**Comment by lnicola** [comment]
Does `curl -LO https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/2021-11-22` work for you? Which distro are you using?

**Comment by tumluliu** [comment]
that's a good point. Thank you @lnicola 

What I got is:
```
❯ curl -LO https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/2021-11-22
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

But if I provide the option `--insecure`, the curl command can succeed

**Comment by tumluliu** [comment]
my understanding is the vscode setting `"http.proxyStrictSSL": false` is for this purpose, isn't it?

**Comment by tumluliu** [comment]
> Which distro are you using?
I'm using ubuntu 20.04

**Comment by lnicola** [comment]
I think that might only apply to the network requests performed by Code. We download the server binary ourselves using `node-fetch`.

**Comment by tumluliu** [comment]
> I think that might only apply to the network requests performed by Code. We download the server binary ourselves using `node-fetch`.

oh, interesting to know! Thanks for the info. Then it would be great to have an extension option to disable the ssl checking. Or, is it possible to bypass it by setting some env vars?

**Comment by lnicola** [comment]
Yeah, it's something we should normally fix. We'd like to bundle the server binary with the extension, but we'll probably still need to keep the code for the nightly updates :disappointed:.

**Comment by lnicola** [comment]
You can try setting `NODE_TLS_REJECT_UNAUTHORIZED=0`. You might need to add it to your `.profile` or somewhere.

**Comment by tumluliu** [comment]
> You can try setting `NODE_TLS_REJECT_UNAUTHORIZED=0`. You might need to add it to your `.profile` or somewhere.

It worked like a charm. Many many thanks! I still hope this can be configurable anyway via this extension's settings.

p.s. for googlers who landed here, to solely set `NODE_TLS_REJECT_UNAUTHORIZED=0` is not really sufficient for my case as I was facing this issue in the SSH remote mode. To make it work, I killed all the running `code` or `vscode-server` processes on the remote server, set this var via `export NODE_TLS_REJECT_UNAUTHORIZED=0` (or inject this line to the `.bashrc` or `.zshrc` or `.profile`), then restarted vscode and installed this extension successfully. Now I can enjoy rust-analyzer :) 

Thank you @lnicola for your kind help! I think you can consider closing this ticket if the abovementioned extension setting is not easy to implement very soon. This env var solution is acceptable for me.

**Comment by lnicola** [comment]
i filed #10871, but it's pretty hard to test and probably not ready yet.

> set this var via `export NODE_TLS_REJECT_UNAUTHORIZED=0`

Yeah, that only works locally. For SSH you need to edit one of the dotfiles, and for containers it's pretty easy.

**Comment by tumluliu** [comment]
> I filed #10871, but it's pretty hard to test and probably not ready yet.

really awesome! I can test it by unsetting `NODE_TLS_REJECT_UNAUTHORIZED` from my side. Pls give me a ping when it get merged. But it would be great if there is a `vsix` file that I can try with

**Comment by tumluliu** [comment]
Yes, I will try it tomorrow or on Thursday. Thank you for the info!

from Dr. Lu Liu's mobile device

**Comment by tumluliu** [comment]
@lnicola for some reason, it seems that I could not fetch the nightly build although have set the `"rust-analyzer.updates.channel": "nightly"` config for `user`, `remote` and `workspace` all. Error message was still given by `0.2.834` version:

```
INFO [12/1/2021, 10:13:33 PM]: PersistentState: {
  lastCheck: undefined,
  nightlyReleaseId: undefined,
  serverVersion: '0.2.834'
}
ERROR [12/1/2021, 10:14:39 PM]: [st [FetchError]: request to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/nightly failed, reason: unable to verify the first certificate
	at ClientRequest.<anonymous> (/home/me/.vscode-server/extensions/matklad.rust-analyzer-0.2.834/out/main.js:39:48367)
	at ClientRequest.emit (events.js:315:20)
	at TLSSocket.socketErrorListener (_http_client.js:469:9)
	at TLSSocket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)] {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

could you pls give me some hints how I can ensure the nightly build can be properly picked up? thanks!

**Comment by lnicola** [comment]
Oh wait, you can't download the nightly build like that. Try getting it from the GitHub release page.

**Comment by lnicola** [comment]
https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly

Get the vsix from here and install it using the "Install extension from VSIX" command.

**Comment by tumluliu** [comment]
@lnicola thanks for the hint! I tried with the vsix file you mentioned, but seems still no luck 🤔 

```
ERROR [12/2/2021, 7:43:03 AM]: [st [FetchError]: request to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/nightly failed, reason: unable to verify the first certificate
	at ClientRequest.<anonymous> (/home/me/.vscode-server/extensions/matklad.rust-analyzer-0.3.837/out/main.js:39:48367)
	at ClientRequest.emit (events.js:315:20)
	at TLSSocket.socketErrorListener (_http_client.js:469:9)
	at TLSSocket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)] {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

anything I can check from my side?

**Comment by lnicola** [comment]
@tumluliu can you try again using the latest nightly VSIX from GitHub?

**Comment by tumluliu** [comment]
@lnicola I just did it, but unfortunately still could not run through...

```
DEBUG [12/4/2021, 8:45:32 AM]: Issuing request for released artifacts metadata to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/nightly
DEBUG [12/4/2021, 8:45:32 AM]: Fetching release metadata via proxy: http://x.x.x.x:yyyyy
ERROR [12/4/2021, 8:45:44 AM]: Bootstrap error [mt [FetchError]: request to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/nightly failed, reason: unable to verify the first certificate
	at ClientRequest.<anonymous> (/home/me/.vscode-server/extensions/matklad.rust-analyzer-0.3.839/out/main.js:39:338604)
	at ClientRequest.emit (events.js:315:20)
	at TLSSocket.socketErrorListener (_http_client.js:469:9)
	at TLSSocket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)] {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

**Comment by lnicola** [comment]
I assume you did disable `http.proxyStrictSSL`, right? Oof.

**Comment by tumluliu** [comment]
yes, it's really disabled. Otherwise some other plugin would not be able to get installed. But this setting is only on "remote", not in "user" or "workspace". Could this be related?

<img width="403" alt="vscode" src="https://user-images.githubusercontent.com/1563792/144791700-92fed988-c4c0-4301-b3a7-e94b195db811.PNG">

**Comment by lnicola** [comment]
I fixed one more issue in #10940, which should be included in today's release. But I'll probably have to figure out how to set up an HTTPS proxy to test it properly.

**Comment by lnicola** [comment]
@tumluliu did you get a chance to get test the latest fix? It was included in the last two stable releases, see my comment above.

**Comment by tumluliu** [comment]
@lnicola sorry for the long delay! And thank you so much for your updates. I will try to test the latest version you mentioned. It's now a bit more complex for me though since I have updated my certificate to avoid such issue in general. 
But still, I will find a time to try it. Once again, thank you for your efforts!

**Comment by lnicola** [comment]
@tumluliu don't worry. The latest version doesn't download the server from GitHub (unless you switch to the nightly channel), so this shouldn't be a problem any more. So it's all right if you can't test it.
