### ISSUE TITLE
Add notification for when workspace is ready

### ISSUE THREAD

**Issue by rchl** [rust-lang/rust-analyzer#10888]
I've noticed that some requests can receive an error response when the workspace has not fully loaded yet. For example `rust-analyzer/inlayHints` can receive `waiting for cargo metadata or cargo check` error.

What would be a suggested approach for handling that on the client? Trying the request until it succeeds seems wasteful and hacky.

I'd suggest adding some custom notification per-file sent from the server (maybe `rust-analyzer/workspaceReady`) when the workspace has initialized. Then the client could use that signal to retry requests that failed previously.

**Comment by casey** [comment]
This would be great. I'm using rust analyzer with nvim, and I open and close my editor a lot, so I'm often trying to issue command to rust-analyzer, but it's not ready yet. I'd like to figure out a way to show that rust-analyzer is ready, perhaps in my status bar, which would be simplified by having some kind of notification from rust-analyzer.

**Comment by bjorn3** [comment]
Rust-analyzer already emit a progress notification with the exact amount of crates it has analyzed and the total amount of crates to analyze. In vscode it also has a statusbar segment with the current state. The nvim extension needs to implement the `experimental/serverStatus` notification for that. See https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#server-status
