### ISSUE TITLE
Failed to figure out closure parameter types after itertools call

### ISSUE THREAD

**Issue by inflation** [rust-lang/rust-analyzer#10898]
This code compiles fine, but `rust-analyzer` failed to figure out the type of `a` or `d`, stating `&{unknown}`.

```rust
    Ok(input
        .lines()
        .filter_map(|s| s.parse::<i32>().ok())
        .tuple_windows()
        .filter(|(a, _, _, d)| a < d)
        .count())
```

<img width="634" alt="image" src="https://user-images.githubusercontent.com/2375962/144231988-16864f15-ac24-490b-b3ee-e7377b38297f.png">

**rust-analyzer version**:  2d0db312b 2021-12-01 nightly

**rustc version**: rustc 1.56.1 (59eed8a2a 2021-11-01)

**Comment by lowr** [comment]
It seems this has been fixed and we now infer the types correctly. Feel free to reopen if you still experience the problem.
