### ISSUE TITLE
Provide per-project configuration

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust-analyzer#11010]
My use-case is to not run `cargo` on the whole workspace in a repository I'm working on but only on the single crate that is currently being worked on. Globally this can be configured but I don't think there's per-project configuration (e.g. via some configuration file at the root of the repository).

**Comment by Veykril** [comment]
Currently the only way to do it per project is if your editor supports it(VSCode being one example here that enables this), we would like to have a per project rust-analyzer.toml(or use the metadata section of a Cargo.toml) or similar from what I remember(the idea about this is split over a bunch of issues I think).
