### ISSUE TITLE
Qualify Path Assist

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#11016]
We currently have a `qualify_path` assist that allows one to qualify an *unresolved* identifier, which is an alternative to importing it.

There is no reason not to show this assist on *resolved* identifiers and fully qualify its usage.

**Comment by RagibHasin** [comment]
@Veykril any pointers about how to get around implementing it? I often find myself in need of this feature and also have been interested in hacking on rust-analyzer for a long time.

So if you can point me in the right direction I might be able to implement it.

**Comment by Veykril** [comment]
I am not quite sure myself(would have to look into the matter more), but a few pointers for exploration purposes:
https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_assists/src/handlers/qualify_path.rs is the assist we want to touch

This will call into the following code here at some point https://github.com/rust-analyzer/rust-analyzer/blob/89faff7477e904f6820990f130a3aed72c1d7e6b/crates/ide_db/src/helpers/import_assets.rs#L579-L617
which is a the first problem, we want to not bail out if things are already resolved in this case(but auto-import which uses the same code path here does only want to trigger if these are *not* resolved).
So that has to be adapted to cover the different needs(by maybe pushing the resolution check further back as an example)

Then the second problem you might/will encounter (I am not sure if we handle this the way I think we do) is when we generate an import path for an item, it might be that we just immediately return the sole identifier as it is already in scope.
This happens here https://github.com/rust-analyzer/rust-analyzer/blob/5a7e11f5fbc6cdf7af79afe70a94c78b79e366d2/crates/hir/src/lib.rs#L569-L584

**Comment by RagibHasin** [comment]
To be honest, I have never before worked on such a large codebase. So, it can take some time for me to wrap my head around all the things going around in it. And, also, I might ask a lot of naive questions about various internals, so your patience might get tested at times 😂.

Thanks in advance, though.

**Comment by Veykril** [comment]
No problem, feel free to ask here or on the rust zulip channel.

**Comment by jplatte** [comment]
@Veykril given https://github.com/rust-lang/rust-analyzer/issues/12996#issuecomment-1211710957, this can be closed in favor of the issue that comment is on, right?
