### ISSUE TITLE
Re-run checkOnSave command when .cargo/config.toml changes

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust-analyzer#11024]
When `.cargo/config`[`.toml`] changes, rust-analyzer should rerun its `checkOnSave.command` because things like `rustflags` can be configured through this file.

**Comment by nico-abram** [comment]
Are there any tests for the rust-analyzer crate reload behaviour? Or should this change not add any tests?

**Comment by Veykril** [comment]
We don't have a lot of tests that test r-a in its entirety when it comes to loading projects and the like, so not having a test for that is fine.

**Comment by petr-tik** [comment]
can this generalise to reloading if rust-project.json file changes?
