### ISSUE TITLE
Why rust-analyzer doesn't work in [test] function?

### ISSUE THREAD

**Issue by Wyvern** [rust-lang/rust-analyzer#11066]
```
#[test]
fn test_fn(){
... //rust-analyzer doesn't work here! NO error prompt until you really compile file.
}
```
Is it a bug or a config/setting which should properly toggled?

**Comment by lnicola** [comment]
Does it work with `#[test]`?

**Comment by Wyvern** [comment]
> Does it work with `#[test]`?

It's a typo, fixed it.

**Comment by lnicola** [comment]
It should work, can you make a sample test case?

![image](https://user-images.githubusercontent.com/308347/146768081-af45cf48-c3f2-4592-981f-e0ab592e531a.png)

**Comment by Wyvern** [comment]
Ok. 
Let's put a non-existed function call in test, there's NO error prompt until you run test.
<img width="350" alt="Screen Shot 2021-12-20 at 9 10 59 PM" src="https://user-images.githubusercontent.com/32942/146772738-a405abfc-c4fc-4867-b7fc-6474a746d225.png">
<img width="764" alt="Screen Shot 2021-12-20 at 9 11 46 PM" src="https://user-images.githubusercontent.com/32942/146772750-59c16114-cdb4-4f04-93e9-90683293262e.png">

**Comment by lnicola** [comment]
It's marked as unresolved:

**Comment by Wyvern** [comment]
"checkOnSave" enabled. Furthermore, I also enabled auto-save editing; problem stays.

By the way, rust-analyzer works normally in non-test scope. So, it's definitely the problem specifically to #[test] function.

**Comment by flodiebold** [comment]
Do you have `rust-analyzer.checkOnSave.allTargets` or `rust-analyzer.checkOnSave.target` set?

**Comment by Wyvern** [comment]
I found that this problem not only affect `#[test]` code but also `[[example]]` code file, still not sure how to fix it.

**Comment by nikkolasg** [comment]
I confirm that `--all-targets` need to be enabled. It should probably be enabled by default, there's no reason to avoid showing errors on test.
For reference, my setup on vscode is
```
"rust-analyzer.checkOnSave.overrideCommand": [
        "cargo",
        "+nightly",
        "clippy",
        "--all",
        "--all-targets",
        "--all-features",
        "--message-format=json",
        "--",
        "-D",
        "clippy::all"
    ],
```

**Comment by pitaj** [comment]
I was able to resolve this similar to @nikkolasg but I had to enable checking tests as well:

```
    "rust-analyzer.checkOnSave.overrideCommand": [
        "cargo",
        "+nightly",
        "clippy",
        "--workspace",
        "--all-targets",
        "--all-features",
        "--tests",
        "--examples",
        "--benches",
        "--message-format=json",
    ],
```

**Comment by nobane** [comment]
The setting is now `"rust-analyzer.check.overrideCommand"`

**Comment by davidbarsky** [comment]
Looks like this issue can be resolved.

**Comment by TomzBench** [comment]
i have this issue with my repo also. It seems some projects, the example files will emit lint errors, while other projects will not emit lint errors. 

[here](https://github.com/mrcjkb/rustaceanvim/issues/562) is more details that I originally raised in my IDE, however, it seemed RA related.

I tried changing the override command, and also explicitly adding examples my Cargo.toml file. No luck however.

**Comment by shripadk** [comment]
Had the same issue. The solution is to enable experimental diagnostics mode. My neovim specific lsp config:

  ```
-- snip
["rust_analyzer"] = function()
    require 'lspconfig'.rust_analyzer.setup {
      settings = {
        ["rust-analyzer"] = {
          diagnostics = {
            disabled = "unlinked-file",
            experimental = {
              enable = true,
            },
          },
        },
      },
    }
  end,
-- snip
```

and for VS Code users, I think this should suffice:

```
"rust-analyzer.diagnostics.experimental.enable": true
```

**Comment by TomzBench** [comment]
> Had the same issue. The solution is to enable experimental diagnostics mode. My neovim specific lsp config:
> 
> ```
> -- snip
> ["rust_analyzer"] = function()
>   require 'lspconfig'.rust_analyzer.setup {
>     settings = {
>       ["rust-analyzer"] = {
>         diagnostics = {
>           disabled = "unlinked-file",
>           experimental = {
>             enable = true,
>           },
>         },
>       },
>     },
>   }
> end,
> -- snip
> ```
> 
> and for VS Code users, I think this should suffice:
> 
> ```
> "rust-analyzer.diagnostics.experimental.enable": true
> ```

Thank you - this was bothering me so much. I'm not sure why some projects need this and others do not.
