### ISSUE TITLE
rust-analzyer doesn't report error

### ISSUE THREAD

**Issue by namse** [rust-lang/rust-analyzer#11075]
`cargo check` reports errors but rust-analyzer doesn't.

vs-code with rust-analyzer
![image](https://user-images.githubusercontent.com/3580430/146819136-eb42858e-b8a4-40e9-83d3-79181869f990.png)

`cargo check` result
![image](https://user-images.githubusercontent.com/3580430/146819156-ae39614c-e8ee-4618-83a0-83e1cfa91b65.png)

**rust-analyzer version**: 0add6e95e 2021-12-20 stable

**rustc version**: rustc 1.56.1 (59eed8a2a 2021-11-01)

**Comment by jhgg** [comment]
Perchance, do you have checkOnSave enabled?

**Comment by gtsiam** [comment]
I've run into this too actually, though it was with nightly toolchains: Every time I updated nightly, I had to do `cargo clean` and restart vscode, otherwise I wouldn't see any errors.

**Comment by namse** [comment]
I was expecting rust-analzyer to tell the user why when a check fails.
The biggest problem, I think, is that rust-analyzer doesn't tell me why.
Nowhere does it tell us why rust-analyzer died. How do I know if a check is failing for some reason?

**Comment by namse** [comment]
More info!
I found that rust-analyzer hangs without any error reports if there is a build problem with the crate I added.
I use some internal crates with path import.

I hope rust-analzyer to explain to user, which crate rust-analzyer died while checking with a popup at the bottom right of vscode at least.

**Comment by Veykril** [comment]
You mean a dependency of yours failed to build right? Ye that will prevent cargo from doing anymore error checking in your workspace swallowing the errors. We should probably check if we get diagnostics in non-workspace dependencies and notify the user about that.

**Comment by Veykril** [comment]
Fixed in https://github.com/rust-lang/rust-analyzer/pull/11960
