### ISSUE TITLE
inlay-hints for generic arguments

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#11091]
We should offer the ability to show inlay hints for generic arguments, just like we do for function arguments already.
```rs
fn foo<'a, T, const C: usize>() {}
foo::<'b, u32, 0>()
// should render as something like
foo::<'a: 'b, T: u32, C: 0>()
```
Each of these 3 should have a config flag, with only the const generics one being enabled by default I'd say.

**Comment by bjorn3** [comment]
I think

```rust
foo::<'a = 'b, T = u32, C = 0>()
```

would be nicer.

**Comment by flodiebold** [comment]
Generic parameter names usually aren't that helpful though :grimacing:

**Comment by Veykril** [comment]
Not for lifetimes and type parameters probably, but they can be quite nice for const generics as you just pass them random values sometimes.
