### ISSUE TITLE
Go to definition on overloadable operators

### ISSUE THREAD

**Issue by lunacookies** [rust-lang/rust-analyzer#11105]
As far as I can tell, rust-analyzer already supports operator overloading in type inference, at least. Would it be possible to extend this so using ‘go to definition’ on operators such as `+` and `?` would jump to the corresponding `impl` block?

**Comment by Veykril** [comment]
That should be somewhat doable(probably needs some extra work once we are able to resolve to actual impls of traits for this to also work there), https://github.com/rust-analyzer/rust-analyzer/blob/4ea1f58bf6b3fd5bb59ed583f2ac432e237e1e1e/crates/ide_db/src/defs.rs#L44-L110 is where we probably want to do this resolution which should make this work for most of the ide area.

**Comment by flodiebold** [comment]
Going to the actual impl is blocked on #4558, but making go to definition work for operators could be done right now, as @Veykril described. It would just go to the trait for now. We actually already record the resolution (to the trait method) during type inference, so the IDE code should just be able to look it up in the `method_resolutions`.

**Comment by l1nxy** [comment]
This feature has been implemented by #4558, so maybe we should close this issue.
Any idea? @Veykril @flodiebold
