### ISSUE TITLE
Prebuild windows msvc binary file available on github release pages do not have extension '.exe'

### ISSUE THREAD

**Issue by vksdev** [rust-lang/rust-analyzer#11146]
It confused me for some time. Is it intentional or not. Although it worked fine after adding it.

**Comment by lnicola** [comment]
Yeah, I guess it should be called `rust-analyzer-x86_64-pc-windows-msvc.exe.gz` because GZIP doesn't support file names. But the plan is to switch to ZIP for the Windows binaries, which would solve this.

**Comment by lnicola** [comment]
ZIP files have been available for a long time.
