### ISSUE TITLE
"Extract type as type alias" assist does not work with const generics in array

### ISSUE THREAD

**Issue by DesmondWillowbrook** [rust-lang/rust-analyzer#11197]
**rust-analyzer version**: 0add6e95e 2021-12-20 stable

**rustc version**: rustc 1.57.0 (f1edd0429 2021-11-29)

### Minimal reproducible example:
(using the "Extract type as type alias" while selecting `[T; N]` in `arr: [T; N]`,
#### Original:
```rust
struct Foo<T, const N: usize>
where
    [T; N]: Sized,
{
    arr: [T; N],
}
```

#### After assist:
```rust
type Type<T> = [T; N];

struct Foo<T, const N: usize>
where
    [T; N]: Sized,
{
    arr: Type<T>,
}
```

**Comment by Veykril** [comment]
This is due to https://github.com/rust-analyzer/rust-analyzer/blob/2e33bf23c94e7053eb657d1a318bd1b66cabec95/crates/ide_completion/src/render.rs#L304-L322
