### ISSUE TITLE
no highliting when cmake compilation fails

### ISSUE THREAD

**Issue by lukaz-vaultree-com** [rust-lang/rust-analyzer#11223]
Hi, my code was not highliting the errors and I took entire day to realize it was because the cmake C++ part of the code was failing to compile.

Maybe add this failure info at least on the output?

**Comment by Veykril** [comment]
So in a nutshell what is happening is that a dependency fails to build with an error, and we end up just eating that error without showing the user any such information right?

**Comment by lucas-zee** [comment]
Yes. If the build.rs fails, then nothing is displayed and the error highlighting does not work, which made me unaware of what was happening

**Comment by Veykril** [comment]
So I just checked, if you have a dependency whose build script fails to build r-a does show you a warning status 
![image](https://user-images.githubusercontent.com/3757771/149381331-fcf0e0a9-65c2-481a-b054-a5908939914f.png)

**Comment by jonas-schievink** [comment]
I've noticed that the popup can get so large that it appears under the cursor, which causes VS Code / Electron to immediately hide it again, which then makes it pop up again, using a lot of CPU, so I'm guessing we aren't meant to put that much text in it :)

I'm not really sure how to do better here – we could emit an actual diagnostic and put it in the workspace's `Cargo.toml`, or print it to stderr when the rust-analyzer logo is clicked, but neither seems ideal.

**Comment by bjorn3** [comment]
What about opening a new special page filled by rust-analyzer just like for example the memory stats? Also is it possible for the problems pane to refer to such special page? Or can it only refer to regular source files?
