### ISSUE TITLE
replace_derive_with_manual_impl / Convert to manual ... does not handle renamed or pathed derives properly

### ISSUE THREAD

**Issue by Emilgardis** [rust-lang/rust-analyzer#11246]
```rust
pub mod clone_debug {
    pub use std::fmt::Debug as Clone;
}

#[derive(Clone, clone_debug::Clone<|>)]
pub struct Foo;
```
Convert to manual on last item in derive implements `Clone` and not `Debug`.

Cursor on `clone_debug::` creates `impl clone_debug for Foo`

_Originally posted by @Emilgardis in https://github.com/rust-analyzer/rust-analyzer/issues/10666#issuecomment-955671021_

**Comment by Emilgardis** [comment]
maybe relevant comment
https://github.com/rust-analyzer/rust-analyzer/pull/10847#discussion_r755457264

**Comment by Veykril** [comment]
This now works
