### ISSUE TITLE
Rename only applies on declaration and not on references

### ISSUE THREAD

**Issue by augustocdias** [rust-lang/rust-analyzer#11272]
I've tested it in Neovim and in VSCode and got the same results, so I believe the issue is with rust-analyzer. 

**rust-analyzer version**: rust-analyzer version: db2a7087b 2021-12-13 stable (also happens in rust-analyzer 0f8c96c92 2022-01-10 dev)

**rustc version**: rustc 1.57.0 (f1edd0429 2021-11-29)

When I have functions with certain macros the renames only renames the declaration and not the references:

For example:

```rust
async fn main() {
    let variable = hex::decode("0bd666ccf2c6ae927efd7b151eeb9b88422100f6e688b9e926fc1d2d03b0292e7491216ed39a267d3f8e21531ab83a30c6b0d15ec64fe1e3be00da2e13d5b181").unwrap();
    println!("{}", variable);
```

If I rename the `variable` here it works fine. But in this example bellow it just renames the declaration:

```rust
#[actix_web::main]
async fn main() {
    let variable = hex::decode("0bd666ccf2c6ae927efd7b151eeb9b88422100f6e688b9e926fc1d2d03b0292e7491216ed39a267d3f8e21531ab83a30c6b0d15ec64fe1e3be00da2e13d5b181").unwrap();
    println!("{}", variable);
}
```

**Comment by Veykril** [comment]
Most likely an upmapping issue

**Comment by Veykril** [comment]
Debugging this might be a bit annoying as it involves an attribute and our attribute infra for tests isn't that extensive, but 
the renaming entry point is here(tests also live here), https://github.com/rust-analyzer/rust-analyzer/blob/62a13cce9b6356af0dfeeeb6add3432f0e76a19f/crates/ide/src/rename.rs#L76-L106 which calls into the actual rename infra here(this is what should care about identifiers inside macro invocations specially) https://github.com/rust-analyzer/rust-analyzer/blob/62a13cce9b6356af0dfeeeb6add3432f0e76a19f/crates/ide_db/src/rename.rs which uses the search module to figure out everything the identifier resolves to(this part should be correct I believe) https://github.com/rust-analyzer/rust-analyzer/blob/62a13cce9b6356af0dfeeeb6add3432f0e76a19f/crates/ide_db/src/search.rs

As an example test, here is one that makes use of our attribute test infra https://github.com/rust-analyzer/rust-analyzer/blob/62a13cce9b6356af0dfeeeb6add3432f0e76a19f/crates/ide/src/rename.rs#L1968-L1988
Note that this specific problem might not be visible with `proc_test::identity`

**Comment by Veykril** [comment]
(Note that tests do not know about the standard library so `println` and friends don't work here)

One step first would be to check if putting the cursor on the to be renamed thing makes it highlight all occurences(in VSCode, or using find all references in whatever client), if it doesn't then its a search bug, not a rename bug.

**Comment by augustocdias** [comment]
I guess your hunch about the highlighting is right. It is not highlighting any of the references.

**Comment by Veykril** [comment]
Then the search stuff here https://github.com/rust-analyzer/rust-analyzer/blob/62a13cce9b6356af0dfeeeb6add3432f0e76a19f/crates/ide_db/src/search.rs has a problem somewhere
