### ISSUE TITLE
False `unresolved import` for async runtime `main` macro

### ISSUE THREAD

**Issue by YoshieraHuang** [rust-lang/rust-analyzer#11302]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)

rust-analyzer version: 0add6e95e 2021-12-20 stable

**rustc version**: (eg. output of `rustc -V`)

rustc 1.57.0 (f1edd0429 2021-11-29)

**rust-analyzer extension version**:

0.2.867

Hi, I try to re-export the ` main` and `test` macro of `tokio` in my crate just like this:
```
pub use tokio::{main, test};
```
 `rust_analyzer` warns `unresolved import` for `main` macro but the `test` macro is ok. However, this codes pass `cargo check` and `cargo build`. 

The same issue also happens for `async-std` async runtime.

**Comment by jonas-schievink** [comment]
I think this was brought up before, it's because of the `#[cfg(not(test))]` on the macro
