### ISSUE TITLE
Hover tooltips should always show inferred types

### ISSUE THREAD

**Issue by ChrisEPhifer** [rust-lang/rust-analyzer#11317]
### Background / Problem

In the Haskell Language Server (HLS), hovering over any term in a program displays documentation (if available) and the term's inferred type. In the case of polymorphic terms, both the most-general type _and_ the instantiation of the type at the current term is shown. For example, the saturated type of the term `optional` can be seen at the bottom of the tooltip:

![image](https://user-images.githubusercontent.com/22036533/150027645-73f6453f-61e4-490b-be8e-606700669f9f.png)

In RA, however, there are terms where the only type shown in tooltips is the most-general type; no instantiation of type variables:

![image](https://user-images.githubusercontent.com/22036533/150028881-5b7b6653-0742-4c18-ac03-e6b0d4b4fc3c.png)

(There is nothing but the usual "Go to..." links below the examples seen in the screenshot.)

### Feature Request

It would be lovely if, like HLS, RA could display fully saturated/instantiated types for _every_ term upon hover. This would improve users' ability to reason locally about polymorphic types used in concrete ways; this is especially helpful for deeply-nested data structures using standard library collections in complex ways (such as the application from which I collected the above screenshot.)

My apologies if I somehow managed to duplicate an issue for this feature! Thank you in advance for your thoughts and effort :)

**Comment by Veykril** [comment]
I'll close this issue in favor of https://github.com/rust-lang/rust-analyzer/issues/13394 as that has more details and ideas around this improvement. It's definitely something we want to look into.
