### ISSUE TITLE
`tokio::test` and `ntest::timeout` combination results in macro_error

### ISSUE THREAD

**Issue by badochov** [rust-lang/rust-analyzer#11326]
When given this code:

```
#[tokio::test]
#[ntest::timeout(1000)]
async fn simple_test() {
  println!("Hi");
}
```

rust-analyzer results in `Expected identifier!rust-analyzer(macro-error)`, when this code works well and compiles.

**rust-analyzer version**: `0add6e95e 2021-12-20 stable`

**rustc version**: `rustc 1.56.0 (09c42c458 2021-10-18)`

**Comment by jyn514** [comment]
Another possibly related error: Rust-analyzer errors on this bit of code, even though it compiles fine: https://github.com/cloudflare/boring/blob/5f327aba86aab67af58f0db44e61d5b71b6eb84e/boring/src/x509/mod.rs#L44-L50
```rust
foreign_type_and_impl_send_sync! {
    type CType = ffi::X509_STORE_CTX;
    fn drop = ffi::X509_STORE_CTX_free;

    /// An `X509` certificate store context.
    pub struct X509StoreContext;
}
```
`foreign_type_and_impl_send_sync` is defined as https://github.com/cloudflare/boring/blob/5f327aba86aab67af58f0db44e61d5b71b6eb84e/boring/src/macros.rs#L133-L154:
```rust
macro_rules! foreign_type_and_impl_send_sync {
    (
        $(#[$impl_attr:meta])*
        type CType = $ctype:ty;
        fn drop = $drop:expr;
        $(fn clone = $clone:expr;)*

        $(#[$owned_attr:meta])*
        pub struct $owned:ident;
    )
        => {
            foreign_type! {
                $(#[$impl_attr])*
                $(#[$owned_attr])*
                pub unsafe type $owned: Send + Sync {
                    type CType = $ctype;
                    fn drop = $drop;
                    $(fn clone = $clone;)*
                }
            }
        };
}
```
and `foreign_type!` is https://docs.rs/foreign-types/0.5.0/foreign_types/macro.foreign_type.html.

**Comment by mati865** [comment]
I think this is an upstream `ntest` issue that should be fixed by https://github.com/becheran/ntest/pull/23
