### ISSUE TITLE
Doc comments in macro pattern trigger "unexpected token in input"

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust-analyzer#11351]
The following test compiles and runs just fine with `cargo test`:
```rust
macro_rules! foo {
    (
        ///
        $arg:ident
    ) => {}
}

#[test]
fn sandbox() {
    foo!(a);
}
```

However, rust-analyzer can't expand the macro and reports  "unexpected token in input"

<img width="502" alt="image" src="https://user-images.githubusercontent.com/36276403/151271086-d5fb46ae-bab3-45da-91c0-100c522d253a.png">

**Comment by Veykril** [comment]
This no longer errors
