### ISSUE TITLE
Highlight unresolved derives as `unresolvedReference`

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#11350]
While we can't highlight tokens in random attributes as `unresolvedReference` due to them potentially not being reused in the macro expansion, we can do this for derive attributes specifically as it is a special builtin attribute anyways.

**Comment by TheDoctor314** [comment]
I would like to work on this but I have no idea where to begin. Could you point me in the right direction?

**Comment by Veykril** [comment]
The place for this starts here https://github.com/rust-analyzer/rust-analyzer/blob/9c4e9e46179b638301a2a79b635295f6a36736b1/crates/hir_def/src/nameres/collector.rs#L1355

Then you can just orientate yourself at how `DefDiagnostic`s are handled, it's an enum you'll add a variant to as well from there on it should be fairly similar to the other variants I believe.
