### ISSUE TITLE
add backticks (`) to surrounding pairs when editing doc comments

### ISSUE THREAD

**Issue by laralove143** [rust-lang/rust-analyzer#11381]
the docs follow markdown which allows surrounding with `backticks`, but currently, the text is replaced instead of being surrounded, which is very annoying since this works in other languages

**Comment by Veykril** [comment]
I'm not sure if we can do this conditionally to work just in doc comments

**Comment by laralove143** [comment]
me neither, but even if its allowed globally, is there a big downside to that?

**Comment by kylebarron** [comment]
Any possibility this could be reopened? It's helpful to be able to surround doc text with backticks

**Comment by laralove143** [comment]
for context, this is possible on intellij rust
