### ISSUE TITLE
On typing handler for angle brackets(`<`)

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#11398]
Seems reasonable for us to add an on typing handler that adds a closing `>` where appropriate. IntelliJ has this as well so we can take some inspiration from their implementation here https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/typing/RsAngleBraceHandlers.kt

**Comment by unexge** [comment]
I tried implementing this but corresponding lsp request doesn't allow us to set cursor position I think, so it results:
```rust
type_char(
    '<',
    r#"
fn foo$0() {}
    "#,
    r#"
fn foo<>$0() {}
    "#,
);
```
which I think is a bit annoying 😄 Am I missing something?

**Comment by Veykril** [comment]
I assume you are currently emitting an `insert`ing text edit after the `<` right? You could try doing a replacing one that replaces `<` with `<>` instead

**Comment by unexge** [comment]
Unfortunately it resulted the same, [here](https://github.com/unexge/rust-analyzer/commit/147a84d1fd8d93ae686a698448bba2918255e800) is the code btw

**Comment by Veykril** [comment]
Hmm, ye then I'm not sure. I don't think there is much we can do here?

**Comment by unexge** [comment]
Yes I think so, without proper cursor position this would be annoying rather than useful

**Comment by nemethf** [comment]
Isn't it possible to check whether the client supports rust-analyzer's own snippetTextEdit extension and use that?  Alternatively showDocument request can be used for positioning the cursor, but that cannot be coupled with the textEdit. i.e., it has to be sent independently, which might cause troubles.
