### ISSUE TITLE
out-ot-date loading error of workspace

### ISSUE THREAD

**Issue by doki23** [rust-lang/rust-analyzer#11482]
rust-analyzer version: I pulled the master 2 days ago, and debugged it in my local dev env.
rustc version: 1.58.1
ide: vscode

### reproduction
create a new cargo project with a wrong cargo.toml file like
```
[dependencies]
1
serde_json = "1.0"
```
We'll get an error msg: "rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file".
And remove the character '1' in first line of dependencies making the file correct:
```
[dependencies]

serde_json = "1.0"
```

It still gets the same error msg.

### thoughts
It seems that "Document/didSave" event triggered process of async fetching workspaces which is invoked in task pool, but current_status still return the out-of-date error.

I think if workspace is being fetched,  the GlobalState::fetch_workspace_error should wait until the fetch done, or current_status returns "reloading workspace" instead of an out-of-date error.

**Comment by Siceberg** [comment]
I also encountered a similar situation. After modifying the cargo.toml file or reloading vs code window, the extension has been in the state of fetch metadata

**Comment by Veykril** [comment]
We fixed some stuff regarding the VFS so this should likely be fixed now
