### ISSUE TITLE
ProcMacroSrv executed outside of workspace directory

### ISSUE THREAD

**Issue by mattsse** [rust-lang/rust-analyzer#11518]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: 02904e99a 2022-02-14 stable

**rustc version**: (eg. output of `rustc -V`)
rustc 1.58.1 (db9d1b20b 2022-01-20)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

It seems like during proc-macro expansion in `ProcMacroSrv::expand` the task's current dir is not the workspace directory. 
I'm not sure how to debug this properly but what I suspect is happening is that the cwd and env vars of the `ExpandMacro` are not the workspace and workspace env vars. so that, if a proc-macro that expands depending on `CARGO_MANIFEST_DIR` and expects this path to point to the current workspace, it can generate different token trees for RA inside `ProcMacroSrv`.

**Comment by lnicola** [comment]
I don't think `rustc` guarantees any working directory. But IIUC, this should have been implemented in https://github.com/rust-analyzer/rust-analyzer/pull/11353.

**Comment by mattsse** [comment]
Right, this rather concerns the env var, however the cwd also appears to set to an imported crate. 
and since `CARGO_MANIFEST_DIR` is set to an imported crate and not the current workspace, `Rust Analyzer: Expand macro recursively` shows the code that was expanded while not being in the current workspace.

#11353 seems to be related, but not sure if that's already included in `rust-analyzer version: 02904e9 2022-02-14 stable`?

**Comment by lnicola** [comment]
Yeah, #11353 should be included in that version.

**Comment by Veykril** [comment]
Just looked into this and this seems to work fine?
```rs
#[proc_macro]
pub fn foo(ts: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let ct_env = env!("CARGO_MANIFEST_DIR");
    let rt_env = format!("{:?}", std::env::var("CARGO_MANIFEST_DIR"));
    quote::quote!((#ct_env, #rt_env)).into()
}

```
expands to the same stuff in r-a and rustc. So unless we get more specifics I'll close this for the time being.
