### ISSUE TITLE
Add `proc-macro` semantic token type

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#11529]
We currently have `attribute`, `macro` and `derive` types for highlighting as well as the `attribute` modifier for attribute invocation tokens.

being able to show if a macro call is a proc-macro seems like a good addition, so I believe adding a `procMacro` token type for specifically function like proc-macros seems like a good addition.

The other option would be to add a `procMacro` modifier and tag attributes, derives and function-like proc-macros with it. I feel like this offers less value though, given attributes and derives are always proc-macros anyways.

On another note, given the attribute modifier we may as well want a `macro` modifier that we tag all tokens inside a macro! call with.

**Comment by jhgg** [comment]
i'd be happy to implement this if you can post some brief pointers for how to check if something is a proc macro.

**Comment by Veykril** [comment]
New tags and modifiers go here https://github.com/rust-analyzer/rust-analyzer/blob/a2cc1d6b7b499d6b03436db7fc8053aea72f75ac/crates/ide/src/syntax_highlighting/tags.rs#L17-L85

"kind" highlighting for macros happens here, https://github.com/rust-analyzer/rust-analyzer/blob/a2cc1d6b7b499d6b03436db7fc8053aea72f75ac/crates/ide/src/syntax_highlighting/highlight.rs#L338 given the into call we probably only need to adjust a From impl

Tests are here(with one test testing a huge amount of things, I am planning on splitting these up at some point) https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/syntax_highlighting/tests.rs

Here is the part that tags things with the attribute modifier https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/syntax_highlighting.rs#L380-L386

(note that we currently resolve paths to the proc-macro function quite a lot even if not technically visibile from the current module, that's a bug with our resolver not caring about visibility)
