### ISSUE TITLE
RA is now highlighting / analyzing code with `async-trait` incorrectly...

### ISSUE THREAD

**Issue by dtzxporter** [rust-lang/rust-analyzer#11533]
**rust-analyzer version**: d6ed146a1 2022-02-22 stable
**rustc version**: (eg. output of `rustc -V`) rustc 1.56.0 (09c42c458 2021-10-18)

**relevant settings**: Default, not modified

A few weeks ago, RA started incorrectly labeling syntax that is wrapped in `#[async_trait]`

For example, hovering on a trait function:
![Screen Shot 2022-02-22 at 6 36 37 PM](https://user-images.githubusercontent.com/22282241/155241079-da778115-dafa-4abc-b441-a6a10de48cf6.png)

Hovering on function brackets (which are now the wrong color):
![Screen Shot 2022-02-22 at 7 09 45 PM](https://user-images.githubusercontent.com/22282241/155241145-81ef92c4-b4db-4ae4-8f85-92c07a75743a.png)

Just doing:
```rust
#[async_trait]
pub trait Test {
    async fn test(&mut self) {
        panic!("");
    }
}
```

this used to work properly

**Comment by Veykril** [comment]
This is kind of expected, due to the attribute re-using the spans for its expansion pervasively.

Here is an example of it using the brace tokens span for `unreachable_code` https://github.com/dtolnay/async-trait/blob/master/src/expand.rs#L369

Now this is not that ideal here for hover, but I don't think we are able to do much here as resolving these tokens down to the expansion is intentional.

**Comment by jhgg** [comment]
In the interm however, you can tell rust-analyzer to *not* expand async-trait via the following config:
```json
{
  "rust-analyzer.procMacro.ignored": {
    "async-trait": ["async_trait"]
  }
}
```

**Comment by l-monninger** [comment]
For some reason in VSCode, async_trait does not result in the suppression of "no async trait" errors atm. Is this something people have dealt with in the past? I do not remember this being an issue before.

**Comment by Veykril** [comment]
We now prefer similar kinded tokens on highlighting and hovering. The `async` token is still shown wrong as `async-trait` attaches almost the entire expansion to the `async` keyword except for the one `async` keyword usage it has. So that's not an issue on our side.
