### ISSUE TITLE
Support destructuring assignment

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#11532]
Turns out this is getting [stabilized in 1.59](https://github.com/rust-lang/rust/blob/stable/RELEASES.md#language) (which releases in 2 days 😱) and we can't parse this properly yet. RFC text is here https://github.com/rust-lang/rfcs/blob/master/text/2909-destructuring-assignment.md
This will need some syntax/grammar adjustments.

cc https://github.com/rust-analyzer/rust-analyzer/issues/11454

**Comment by ChayimFriedman2** [comment]
Taking this

**Comment by ChayimFriedman2** [comment]
I'm working on this.

**Comment by ChayimFriedman2** [comment]
I'm working on this.

Oh, this comment was too short...

**Comment by ChayimFriedman2** [comment]
I'm working on this.

**Comment by ChayimFriedman2** [comment]
I'm working on this.

**Comment by ChayimFriedman2** [comment]
Taking this

**Comment by ChayimFriedman2** [comment]
I'm working on this.

**Comment by ChayimFriedman2** [comment]
I'm working on this.

**Comment by ChayimFriedman2** [comment]
Taking this

**Comment by ChayimFriedman2** [comment]
I'm working on this.

**Comment by Veykril** [comment]
Parsing was implemented in #11598, we don't lower this properly yet though.
