### ISSUE TITLE
A test for cast propagation

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-lang/rust-analyzer#11571]
https://github.com/rust-analyzer/rust-analyzer/blob/b86baa709282a07e6678744a31b0d18e51a60504/crates/hir_ty/src/infer/expr.rs#L515

Here it is:

https://user-images.githubusercontent.com/24700207/155874246-7d559b51-5b5c-4738-99d8-e3ca7cd57124.mp4

**Comment by lnicola** [comment]
Unfixed in #14120.
