### ISSUE TITLE
Complete `struct` keyword inside item bodies

### ISSUE THREAD

**Issue by tjx666** [rust-lang/rust-analyzer#11576]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/155889975-5887dcac-d1a3-43c6-a04f-a52511c75920.png">

The complete type like `let` keyword:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/155889997-fdf9aed8-2074-41e8-9039-cb9113dc8629.png">

**Comment by flodiebold** [comment]
Yes, we currently complete the `struct` keyword outside items but not inside, but we should also allow it inside. Same goes for `union` and `enum`. Interestingly, it seems we do complete `trait` and `impl` already.
