### ISSUE TITLE
LSP request timed out: content modified

### ISSUE THREAD

**Issue by tjx666** [rust-lang/rust-analyzer#11587]
Repository: https://github.com/tjx666/study-rust

I just open helloWorld example:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/156038300-9095513b-5533-46bb-aafe-77fd30eaaada.png">

**rust-analyzer version**: 4e72700e3 2022-02-28 nightly

**rustc version**: 1.65.0 insiders

**Comment by Veykril** [comment]
This hasnt popped up since then for anyone and without any additional info its tough to say what went wrong.
