### ISSUE TITLE
Parse Rust code, generate YAML. Parse YAML, modify Rust code.

### ISSUE THREAD

**Issue by SamuelMarks** [rust-lang/rust-analyzer#11596]
How can I use rust-analyzer to do this workflow?

I saw this https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/syntax.md

But a link was broken and the crates it references have gone a couple of years without commits.

Specifically I am writing a new cdd—see [cdd-python](https://github.com/offscale/cdd-python) for the Python one—which, like all CDDs, involves static only code-generation:

  0. From OpenAPI to target language
     - Boilerplate generate if project is non-existent?
  1. From target language to OpenAPI

Notably 0. is to be done: without requiring explicit `#[openapi]` on routes and models; and without a 'generated' directory that is untouchable by the developer.

rust-analyzer seems to be written using Roslyn style red-green trees. This seems similar to how I wrote cdd-python, using the internal [`ast`](https://docs.python.org/3/library/ast.html) library and a custom `cst` library to handle whitespace and comments on merge back-to-file (in-place edits).

Is your project and its dependency too tightly coupled to be useful for this completely different use-case?

Would welcome your insights. Thanks

**Comment by bjorn3** [comment]
The actual concrete syntax tree implemention is called rowan and works outside of rust-analyzer: https://github.com/rust-analyzer/rowan/

> But a link was broken and the crates it references have gone a couple of years without commits.

It references a specific commit which is indeed a couple of years old. You can look at the master branch instead. Note that some crates have been renamed in the mean time. For example ra_syntax is now called [syntax](https://github.com/rust-analyzer/rust-analyzer/tree/master/crates/syntax).

> Is your project and its dependency too tightly coupled to be useful for this completely different use-case?

I believe it is loosely enough coupled to be useful for you. I haven't used rust-analyzer as library myself before though.

**Comment by jonas-schievink** [comment]
Closing, since this was answered.
