### ISSUE TITLE
Setting to disable scope highlighting on hover

### ISSUE THREAD

**Issue by alt-art** [rust-lang/rust-analyzer#11602]
I want to disable the functionality of showing types in scopes on hover, but I don't know where is this configuration.

### From

![image](https://user-images.githubusercontent.com/43281034/156310448-6e1d8561-d8b5-4a5b-b055-823678d7e1f1.png)

### To

![image](https://user-images.githubusercontent.com/43281034/156310543-0b6da007-ff1d-4a91-a746-3aece60f643c.png)

No highlighting on hover.

**Comment by ChayimFriedman2** [comment]
I don't think there is a way to configure that.
