### ISSUE TITLE
Crash on startup "could not find libcore in sysroot path"

### ISSUE THREAD

**Issue by dsyer** [rust-lang/rust-analyzer#11606]
When I open a .rs file the language server tries to start and fails:

```
rust-analyzer failed to load workspace: could not find libcore in sysroot path `/home/vscode/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library`
```

**Comment by dsyer** [comment]
UPDATE: I think I fixed it by running `rustup component add rust-src`. Maybe the extension could do that automatically?

**Comment by bjorn3** [comment]
Rust-analyzer should do that automatically already.

**Comment by flodiebold** [comment]
If we got to the "could not find libcore in sysroot path" error message, [`discover_sysroot_src_dir`](https://github.com/rust-analyzer/rust-analyzer/blob/e949375098623eb0aca221f740f394dcc0d53d93/crates/project_model/src/sysroot.rs#L144) ran successfully, so `/home/vscode/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library` existed, but the `core` directory inside did not. I'm not sure how that would happen though :confused:

**Comment by dsyer** [comment]
Maybe a race condition - it could take a while to download?

**Comment by sheeets** [comment]
I had this issue when vscode installed rust-analyzer when I opened a Rust project. Adding the rust-src like mentioned worked for me.
