### ISSUE TITLE
Signature help request responds with data even after closing bracket

### ISSUE THREAD

**Issue by sudormrfbin** [rust-lang/rust-analyzer#11624]
Signature help request returns with help information even after the cursor has moved past the function call brackets:

![command](https://user-images.githubusercontent.com/23398472/156891445-074853ac-fe53-4519-8ca2-8fefd75b5c53.gif)

I'm implementing signature help for helix edior in https://github.com/helix-editor/helix/pull/1755, and to auto close the help popup the editor sends a signature help request again on common terminating characters like `)` and `;` upon which the server would ideally respond with None, which in turn closes the popup.

---

**rust-analyzer version**: rust-analyzer 17afa2e77 2022-01-24 nightly

**Comment by Veykril** [comment]
Relevant part is here https://github.com/rust-analyzer/rust-analyzer/blob/e8edbb5d6fa43db893fc5eb2a3c75b7b23713919/crates/ide/src/call_info.rs#L42-L54
