### ISSUE TITLE
New assist: add enum variant

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust-analyzer#11635]
![image](https://user-images.githubusercontent.com/1711539/156930805-2f7cd09f-78de-4f48-980d-17f5a2eb165a.png)

It'd be cool if in this situation rust-analyzer realized that that what we want here is not a function, but a new error variant. 

Looking at how generate function works should help with implementing this assist: 

https://github.com/rust-analyzer/rust-analyzer/blob/5b9e46b960c37f04a26742c186e0a26b7bc131b3/crates/ide_assists/src/handlers/generate_function.rs

Note that generate function grew quite complex over time, for learning purposes, you might want to check some of its earlier versions

**Comment by zenofsahil** [comment]
I'd like to take a crack at this.

**Comment by maartenflippo** [comment]
@zenofsahil is this going well for you? This seems like an issue I would enjoy taking on as well, but obviously if you're still working on it I will find another (seems like there are plenty).

**Comment by zenofsahil** [comment]
@maartenflippo Thanks for checking! I was going through the codebase when some other priorities came up. I've been planning on coming back to this but it would be another couple of weeks before I can do that. Please do take it up if you want to work on this. Just let me know if you plan to so I know to check out other issues when I do get the time.

**Comment by maartenflippo** [comment]
Alright then I'll take this up.
