### ISSUE TITLE
[Feature request] Add visualization for captured variables in a closure

### ISSUE THREAD

**Issue by RagibHasin** [rust-lang/rust-analyzer#11646]
The title says it all. An assist or command that highlights all the captures in a closure.

**Comment by HKalbasi** [comment]
Hover of closure now shows the captures, but if it is not enough, we can iterate over `db.closure_info(closure_id).0` and use the `span` field to highlight every captured item.

**Comment by HKalbasi** [comment]
Ah this is actually implemented in #14711
