### ISSUE TITLE
Feature request: converting struct to/from tuple notation.

### ISSUE THREAD

**Issue by vi** [rust-lang/rust-analyzer#11643]
Changing a struct or enum variant between `{}` and `()` notations is rote and repetitive - seems like a job for a bot. I think Rust Analyzer should contains code assists for it.

Before:

```rust
struct Foo { ┃inner: i32 }
fn bar() {
    let e = Foo { inner: 45 };
}
```

After:

```rust
struct Foo(┃i32)
fn bar() {
    let e = Foo(45);
}
```

Reverse conversion should introduce fields like `field0`, `field1`, etc.

**Comment by vi** [comment]
By the way, is it a good idea for Rust Analyzer to have a mode where it shows also unimplemented potential future code assists, which instead of modifying the code just give a Github issue link to vote for?

**Comment by lnicola** [comment]
> By the way, is it a good idea for Rust Analyzer to have a mode where it shows also unimplemented potential future code assists, which instead of modifying the code just give a Github issue link to vote for?

About half of the work is figuring out when to fire an assist, so probably not :-).
