### ISSUE TITLE
Implement inlay hint location links

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#11701]
The inlay hint api allows to split the hints into parts backed by links, we should make use of this.

https://github.com/rust-analyzer/rust-analyzer/blob/5e8515870674983cce5b945946045bc1e9b80200/crates/rust-analyzer/src/lsp_ext.rs#L273-L283

The main difficulty here is that we currently use `HirDisplay` to render the display representation of types which doesn't allow introspection into each part. We probably need a proper type visitor api here.

**Comment by IWANABETHATGUY** [comment]
Hi, since this pr has been landed for a while, what is the progress of go to type definition via a inlayHint

**Comment by bigdogs** [comment]
Hi, Any new progress for this issue? 
BTW. Is this related to the issue that  inlay hint tooltip window is not show up ?

**Comment by IWANABETHATGUY** [comment]
@Veykril , I would like to have a try, would you mind give me some hints?

**Comment by Veykril** [comment]
I'm not sure. as was said in the initial description, we probably need to come up with a proper type visitor API here so we can construct the inlay hint parts correctly. I am not sure how feasible that is yet.
