### ISSUE TITLE
Wrong "Unresolved Import" in crate codepage-437

### ISSUE THREAD

**Issue by Christoph-AK** [rust-lang/rust-analyzer#11711]
When importing CP437-CONTROL from codepage-437 RA shows 'unresolved import'.

Program compiles without problems.

![grafik](https://user-images.githubusercontent.com/72923608/158357925-d1a304d4-307a-4748-a4fb-f21224749c1f.png)

Code: 

```rust
use codepage_437::{BorrowFromCp437, CP437_CONTROL};
fn main() {
    let output_str = String::borrow_from_cp437(&output.stdout, &CP437_CONTROL);
    println!("{output_str}");
}
```

Reference issue: [https://github.com/nabijaczleweli/codepage-437/issues/1](https://github.com/nabijaczleweli/codepage-437/issues/1)

**rust-analyzer version**: rust-analyzer version: 5e8515870 2022-03-14 stable
**rustc version**: rustc 1.59.0 (9d1b2106e 2022-02-23)

Thanks for RA!!!

**Comment by bjorn3** [comment]
Do you have the `rust-analyzer.cargo.runBuildScripts` config set to true? (Should be the default)

**Comment by Christoph-AK** [comment]
@bjorn3 thanks for the quick response. Yes, compiles fine. 

```
connector on  main [!] is 📦 v0.1.0 via 🦀 v1.59.0 
❯ cargo b 
   Compiling getrandom v0.2.5
   Compiling uuid v0.8.2
   Compiling tiberius v0.7.1
   Compiling connector v0.1.0 (C:\Users\local\Desktop\Daten\Programme\connector)
    Finished dev [unoptimized + debuginfo] target(s) in 30.76s

connector on  main [!] is 📦 v0.1.0 via 🦀 v1.59.0 took 31s
❯
```

`rust-analyzer.cargo.runBuildScripts` is set to true.

**Comment by bjorn3** [comment]
Could do "Go to Definition" (F12) on `codepage_437`, then "Go to Definition" on `mod dialect;` and finally check if the `include!()` at the bottom of the file shows an error?

**Comment by Christoph-AK** [comment]
When I reload RA via `Rust Analyzer: Restart Server` sometimes RA manages to find CP437_CONTROL, sometimes it breaks again after a while. Great info, I know 😅
