### ISSUE TITLE
Add support for Meta-Variable Expressions

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-analyzer#11712]
For more information, see https://github.com/rust-lang/rust/issues/83527.

```rust
#![feature(macro_metavar_expr)]

macro_rules! mac {
    ( $($foo:ident)* ) => {
        0 + ${count(foo)}
    };
}

fn main() {
    let n = mac!(a b c);
    assert_eq!(n, 3);
}
```

![Capture d’écran de 2022-03-15 09-58-47](https://user-images.githubusercontent.com/17877264/158383046-946d3daf-f77d-42a2-a399-94d5be65e305.png)

**Comment by c410-f3r** [comment]
I guess at least dollar-dollar will be easy to implement

```rust
macro_rules! foo {
    () => {
        macro_rules! bar {
            ( $$( $$any:tt )* ) => { $$( $$any )* };
        }
    };
}

fn main() { foo!(); }
```

**Comment by c410-f3r** [comment]
Closing in favor of #11952

**Comment by Veykril** [comment]
Ah, I completely forgot about this issue already existing sorry
