### ISSUE TITLE
"Run Doctest" is filtering out the test but running the generated command manually works

### ISSUE THREAD

**Issue by adtennant** [rust-lang/rust-analyzer#11725]
**rust-analyzer version**: 5e8515870 2022-03-14 stable

**rustc version**: rustc 1.58.1 (db9d1b20b 2022-01-20), also rustc 1.59.0 (9d1b2106e 2022-02-23)

**relevant settings**: None, VSCode settings are defaults.

I have a `struct` at the root level of my crate and when I use the "Run Doctest" lens within the impl block I get the following output:
```
Executing task: cargo test --doc --package fpm -- "Foo::bar" --nocapture <

// Compiler output omitted

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s
```

However, if I run `cargo test --doc --package fpm -- "Foo::bar" --nocapture` manually I get the following (which is what I'd expect):
```
running 1 test
test src/lib.rs - Foo::bar (line 4) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.45s
```

MRE:
```
pub struct Foo(i32);

impl Foo {
    /// ```
    /// # use fpm::Foo;
    /// assert_eq!(0, 0)
    /// ```
    pub const fn bar(self, rhs: Foo) -> Option<Foo> {
        unimplemented!()
    }
}
```

**Comment by lnicola** [comment]
This is because of the extra pair of quotes around the test name.

**Comment by lnicola** [comment]
CC @KarlWithK

**Comment by KarlWithK** [comment]
Hmmm, this seems like an IDE problem. So the reason I added the quotes is that with Rust-Analyzer and Neovim, you actually do run these commands through the shell. So I'm unsure how to resolve this as implies coc.vim handles it a bit differently than how your editor does it.

**Comment by lnicola** [comment]
Ah, I thought you tried to copy-paste into a terminal the output shown by Code.

I don't know how it worked in Code pre-#11490, but there is one correct way (*) of representing a command line: as an array, without quoting. We should pass that to the client, and let the client handle the execution, with or without a shell.

(*) at least on Unix

**Comment by ianmarmour** [comment]
> Hmmm, this seems like an IDE problem. So the reason I added the quotes is that with Rust-Analyzer and Neovim, you actually do run these commands through the shell. So I'm unsure how to resolve this as implies coc.vim handles it a bit differently than how your editor does it

Your comment here seems to imply that this isn't a behavioral regression of the tooling and that it's a VSCode or non *nix shell specific problem? While that might be true isn't the inverse also true? Your change was specifically to target a neovim/*nix shell specific interaction. Considering the library is multi-platform I would expect this to be treated as a regression rather then shrugged off as an IDE issue. (also the IDE support is shipped in this library...)

**Comment by lnicola** [comment]
@ianmarmour to be clear, the current issue _is_ a regression.
