### ISSUE TITLE
Unlinked file fix not available if parent is an inline module?

### ISSUE THREAD

**Issue by flodiebold** [rust-lang/rust-analyzer#11754]
1. Add a file in `ide_diagnostics/src/handlers/`.
2. Observe the "unlinked file" diagnostic, but no quickfix.

I haven't looked into this in detail, just wanted to record it before I forget.

**Comment by Veykril** [comment]
This is intentionally not working (for now): https://github.com/rust-analyzer/rust-analyzer/blob/97c7321cfa93973df9a9d0f3d9321a6ab5e5d87f/crates/ide_diagnostics/src/handlers/unlinked_file.rs#L74

**Comment by Veykril** [comment]
This works now
