### ISSUE TITLE
Fix our config format to be more consistent 

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#11790]
As mentioned in https://github.com/rust-analyzer/rust-analyzer/pull/11789

Our configuration keys are somewhat inconsistent, we should go ahead and fixing these inconsistencies, writing down a proper structure of how configurations should look like while allowing extending them without breakage like we are slowly running into it seems.

This will requires us to do one overall change of the config format which may break user configurations but should guard us against having to do this again in the future while not restricting our options.

**Comment by jonas-schievink** [comment]
While we're at it, we should also move `rust-analyzer.experimental.procAttrMacros` to `rust-analyzer.procMacro.enableAttrs` or something, since it's really not experimental anymore.

**Comment by Veykril** [comment]
Thinking about this, this would also allow us to reset all the aliases we have defined for now, in general cleaning up the config mess. on an additional note I wonder if we want to put a proper deprecation system in place, one that allows us to properly work with VSCode for example. The current alias system works pretty bad in it, since vscode only recognizes the one defined in the package.json, which might cause people to set the same thing multiple times through different aliases without knowing it.

**Comment by Veykril** [comment]
Also just a headsup, but I'll fix this stuff up the coming days hopefully, but I plan on breaking things with this when we switch the extension publisher.
