### ISSUE TITLE
rust-analyzer.cargo.features can break running of tests in workspaces

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust-analyzer#11836]
In a workspace with multiple crates, where some have a feature of a certain name but others don't, you may want to set `"rust-analyzer.cargo.features": ["feature-name"]` to have feature-gated code benefit from rust-analyzer's functionality.

However, with that setting, when trying to use RA's "Run test" helper on a test inside a crate without a feature named `feature-name`, RA still passes `--feature feature-name` to Cargo, leading to an error because that feature doesn't exist.

**rust-analyzer version**: bc08b8eff 2022-03-28 stable
**rustc version**: rustc 1.61.0-nightly (c84f39e6c 2022-03-20)

**Comment by smmalis37** [comment]
Bump, this has been a huge pain point for me, would love to see this fixed.
