### ISSUE TITLE
In a match / if-let-some the variable isn't shown

### ISSUE THREAD

**Issue by kristof-mattei** [rust-lang/rust-analyzer#11856]
**rust-analyzer version**: `rust-analyzer version: bc08b8eff 2022-03-28 stable`

**rustc version**: `rustc 1.59.0`

**relevant settings**: VSCode vanilla install.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/864376/160921666-6d984fbc-2726-4211-a709-9e4ff0148b29.png">

Issue: 

In a match / if-let-some the variable isn't shown, see screenshot.

Test repo: https://github.com/kristof-mattei/let-some.git

**Comment by jhgg** [comment]
Rust analyzer does not provide any debugging capability. I think you are probably using CodeLLDB?

**Comment by kristof-mattei** [comment]
@jhgg that's right. I'll report the bug there!
