### ISSUE TITLE
Inconsistent padding on inline hints

### ISSUE THREAD

**Issue by jasonwilliams** [rust-lang/rust-analyzer#11873]
originally raised from https://github.com/microsoft/vscode/issues/146575

Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.67.0-insider (user setup)
Commit: 909602cf04e0fa42528d692676d0d4e15e67bba2
Date: 2022-03-31T11:00:49.798Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

Apologies if this is raised in the wrong place.

Steps to Reproduce:

1. Open https://github.com/boa-dev/boa with Rust Analyzer installed
2. navigate to https://github.com/jasonwilliams/boa/blob/main/boa_engine/src/builtins/typed_array/mod.rs

When the inline hint is on the right of the subject it almost overlaps with the subject itself; I.E there's no spacing between the subject and the hint. When the inline hint is on the left it is fine.

<img width="852" alt="spacing issue" src="https://user-images.githubusercontent.com/936006/161317611-1ef7779b-2f5d-4320-8c35-94ef5c87f335.png">

In the below example I would expect there to be a space between obj and ` :&JsObject`. Also I don't think there needs to be a space between the colon and the `&jsObject` (similar to `message:` below).
<img width="722" alt="spacing issue 2" src="https://user-images.githubusercontent.com/936006/161317884-a3ea24cf-28e3-4d8d-8850-ee9dc8a3f26e.png">

**Comment by Veykril** [comment]
This is intentional as we are mimicking how handwritten rust would look like. You would not seperate the pattern from the colon with a space when writing rust.

**Comment by jasonwilliams** [comment]
> This is intentional as we are mimicking how handwritten rust would look like. You would not seperate the pattern from the colon with a space when writing rust.

I agree with you on that but the grey background makes it look badly styled, like it’s a bug. Is it possible instead to have the colon not part of the grey background and only start the grey background from where the text is?

Otherwise I think I’d prefer if there was a space because it’s quite off putting.

**Comment by Veykril** [comment]
No that is not possible. Your options here are either to make the background transparent or disable `rust-analyzer.inlayHints.renderColons` which removes the colons and adds padding in its place.

**Comment by jasonwilliams** [comment]
CC @jrieken do you know if there’s anyway round this? Or does an issue need to be raised with VSCode around a more flexible background size?

**Comment by flodiebold** [comment]
Let's close this since it's unlikely we'll be able to do anything about it.
