### ISSUE TITLE
Using postfix snippets on expressions containing `'\\'` results in it getting unescaped

### ISSUE THREAD

**Issue by liquidev** [rust-lang/rust-analyzer#11897]
**rust-analyzer version**: 2022-03-28

**rustc version**: rustc 1.61.0-nightly (c5cf08d37 2022-03-30)

Example:
```rs
fn main() {
  let x = '\\'.ok|
}
```
(where `|` is the cursor)
Accepting the suggestion will result in this code:
```rs
fn main() {
  let x = Ok('\')|
}
```
which is invalid syntax.

It also seems that this happens with strings. Other escapes are intact, it's only `\\` that gets mangled.

Also of note is that the escape may be nested in some deeper expression. For instance:
```rs
match x {
  true => '\\',
  false => 'a',
}.ok|
```

**Comment by Jesse-Bakker** [comment]
This is caused by the fact that `\`, `$` and `}` are special tokens in a snippet, which should be escaped. RA returns these in the postfix completion snippet unescaped, causing them to disappear.
