### ISSUE TITLE
Folding ranges for multiline non-block match arm expressions

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#11893]
Given the snippet below,
```rs
match foo {
    bar => {
    },
    baz => some.
        call().
        chain(),
    qux => match foo {
        bar => (),
    },
}
```
we emit a folding range for the match, for the first arms block expression and for the third arms match expression, for consistency we should emit a fold for the entire multine line expression in the second and third arm each.

Note that in the case for the third arm, we should not emit the standard fold for the match expressions block, but for the entire expression.

Relevant source file is https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/folding_ranges.rs

**Comment by harpsword** [comment]
I have some questions 
1. for multine line expression, only omit a fold when this expression is a match arm ?
2. the expected fold result of this example should be 
	```
	match foo <fold block>{
	    bar => <fold block>{
	    }</fold>,
	    baz => some.<fold expr>
	        call().
	        chain()</fold>,
	    qux => match foo { <fold expr>
	        bar => (),
	    }<fold>,
	}</fold>
	```

**Comment by Veykril** [comment]
> for multine line expression, only omit a fold when this expression is a match arm ?

Yes this is specifically meant for match arms where the expression of the arm spans multiple lines and is not a block expression

> the expected fold result of this example should be 

Yes, that looks correct to me 👍

**Comment by harpsword** [comment]
I have several questions.

# 1. there are more "match expression"
i found there are more cases like the match expression in third arm. here is an example,  both the fourth and fifth arms will omit a fold.    

I'm not quite sure if there will be more of this.
```
    match foo {
        bar => {
        },
        non_block => some.
            call().
            chain(),
        qux => match foo2 {
            bar2 => (),
        },
        array_list => [
            1,
            2, 
            3
        ],
        record_expr => StructS {
            a: 5,
        },
    }
```

# 2. what about this fold effect?
I made an example. The code below shows exactly how this is done. For non-block expression in match arm, the start of the fold will be the position before '\n', the end will be the position of ',' if there is a ','.  For match expression in third arm, I specifically use the original fold for comparison.
```
fn main() {
    match foo <fold block>{
        bar => <fold block>{
        }</fold>,
        non_block => some.<fold matcharm>
            call().
            chain()</fold>,
        qux2 => match foo2 <fold block>{
            bar2 => (),
        }</fold>,
        non_block2 => some.<fold matcharm>
            call().
            chain()</fold>
    }</fold>

}</fold>
```

in VS code, before fold:
<img width="282" alt="before fold" src="https://user-images.githubusercontent.com/10148927/162579342-d5d94384-703c-465a-9e8a-77dcd34d6f2c.png">

after fold:
<img width="307" alt="after fold" src="https://user-images.githubusercontent.com/10148927/162579346-98263e87-ed41-44af-8732-6bea07fd1f2a.png">

<fold matcharm>, <fold block> seems  to look similar. So what about we keep the old solution of fold generating for MATCH_EPXR(RECORD_EXPR_FIELD_LIST, and ARRAY_EXPR) in match arm?

**Comment by Veykril** [comment]
Sorry for getting back to this so late, seems I somehow missed the notification!

Regarding 1., yes I think all of those arms (except for the first one?) should have a fold, if we miss out on any we can always add them in later as well so getting all of them right from the get go isn't a necessity!

Regarding 2, that seems fine to me assuming I understood you correctly.
