### ISSUE TITLE
Suggest name for placeholder values based on type

### ISSUE THREAD

**Issue by cameron1024** [rust-lang/rust-analyzer#11892]
When autocompleting some functions, if a parameter is bound via a more complex pattern than just a name, RA autocompletes that parameter as `_`. For example, given:
```rust
struct Foo {
  bar: i32
}

fn example(Foo { bar }: Foo) {
  println!("{bar}");
}
```
If I start typing `example` and autocomplete the function call, the following appears in my editor: `example(_)`. It would be cool if it could convert the type `Foo` into snake case and use that instead, as a "best effort" attempt to guess the variable name.

I guess an alternative would be to expand into: `example(Foo { bar })`, but this seems less useful, and seems like it's exposing something approaching "implementation details" (i.e. what is the pattern that binds to this parameter inside the function).

Would love to hear people's thoughts on this, and if people think it's useful I'd be happy to try to implement this 😁

**Comment by Veykril** [comment]
Ye we deliberately do not show the complex pattern there, using the structs name sounds like a decent idea though 👍 The relevant code path is here https://github.com/rust-analyzer/rust-analyzer/blob/46d7ee68f26285db26b2640f2c07d6332380c756/crates/ide_completion/src/render/function.rs#L131-L139

**Comment by lnicola** [comment]
@cameron1024 I think we can close this, right?

**Comment by cameron1024** [comment]
Yep! Sorry, didn't see your message until now
