### ISSUE TITLE
Support macro metavar expressions

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#11952]
A subset is being stabilized soon https://github.com/rust-lang/rust/pull/95860
RFC https://github.com/rust-lang/rfcs/blob/master/text/3086-macro-metavar-expr.md#dollar-dollar

**Comment by TimNN** [comment]
At least for `$$` the implementation seems to be [pretty straight forward](https://github.com/rust-lang/rust-analyzer/compare/master...TimNN:double-dollar). If there's no-one else currently working on this, I'd like to take a stab at properly implementing the `$$` support. (I still need to verify that the current behavior matches what `rustc` actually does, and especially if multiple levels of nesting behave correctly).

**Comment by Veykril** [comment]
Go ahead!
