### ISSUE TITLE
Consider becoming a verified VS Code publisher

### ISSUE THREAD

**Issue by isidorn** [rust-lang/rust-analyzer#11978]
Hi VS Code PM here 👋 

It would be great if you verify your extension author https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer
More about this process can be found here https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

Let me know if I can help in any way.

**Comment by Veykril** [comment]
We are going to publish the extension under the `rust-lang` publisher in the coming month(s), is that one verified already (I don't know how to check that)?

And since you are here right now I guess I can drop the question here but is it possible to transfer extensions between publishers by any chance? It would be great if we could move the extension the `rust-lang` publisher (and as such keep the great rating we have accumulated over time :) ).

**Comment by isidorn** [comment]
@Veykril great that you will publish under rust-lang. And that one is also not verified 
https://marketplace.visualstudio.com/publishers/rust-lang
So it would be great if you get that one verified :)

Yes, we can move the extension. For that the author of the extension needs to send an email to vsmarketplace@microsoft.com and me inikolic@microsoft.com and we can do the rest.
Keep in mind that moving the extension under a new publisher will:
* break any extension packs that might have that extension - they will need to get updated to take into account the new extension publisher
* break any extension recommendations if that extension is recommended - I can update this on the vscode side
* break any extension dependencies if those extensions depend on the extension being moved

I think for all three you should be good.

fyi last milestone we changed our rust recommendation so we recommend this extension since we think you are doing great work 👏

**Comment by Veykril** [comment]
Oh that is great to hear, I expected moving not to be an option actually so this is great news :)

I'll talk to the relevant people regarding the verification.

**Comment by isidorn** [comment]
Thanks. Has there been any updates?

**Comment by Veykril** [comment]
Oh yes, someone should've sent out the application for verifying rust-lang -> see https://rust-lang.zulipchat.com/#narrow/stream/301329-t-devtools/topic/verify.20the.20.60rust-lang.60.20publisher.20on.20the.20vscode.20marketplace

Regarding the extension move we still have to fix up some things on our side before we want to do that.

**Comment by isidorn** [comment]
@Veykril thanks a lot for doing that!
Feel free to reach out to me in case you hit some issues.

**Comment by Veykril** [comment]
Maybe a stupid question but has the rust-lang publisher been verified? I don't know where this is supposed to be visible on the publisher profile page.

**Comment by lnicola** [comment]
@Veykril yeah:

![image](https://user-images.githubusercontent.com/308347/166945725-7d8149e3-214f-4eea-8234-139be5788e3f.png)

**Comment by Veykril** [comment]
Oh so this is only visible on the extensions pages, not the publisher

**Comment by Veykril** [comment]
Closing then as it has been verified, will get in touch with the people necessary to start the publisher transfer.
