### ISSUE TITLE
Aliases break resolution of qualified variants in patterns

### ISSUE THREAD

**Issue by iDawer** [rust-lang/rust-analyzer#11986]
**rust-analyzer version**:  rust-analyzer version: faaec86ff 2022-04-12 nightly

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

https://github.com/rust-lang/rust-analyzer/blob/13f36e7397065bc77747a4a28f8266f9fe472f8a/crates/hir/src/lib.rs#L3159-L3164
`hir_ty::WhereClause::Implemented` is unresolved:
![q16](https://user-images.githubusercontent.com/7803845/163364851-0e29a146-1336-4319-92ef-17a8b54fa2cf.png)

Minimized:
```rust
mod m {
    pub enum Enum {
        Foo(u8),
    }
    pub type Alias = Enum;
}
fn f() {
    let e = m::Alias::Foo(0);
    let m::Alias::Foo(x) = &e;
}
```

**Comment by jonas-schievink** [comment]
Looks like that's this FIXME:

https://github.com/rust-lang/rust-analyzer/blob/ae68b68d39db1754502fe13e5a11225c9189a3d4/crates/hir_ty/src/infer.rs#L606-L607
