### ISSUE TITLE
textDocument/semanticTokens/etc. GAT failure on latest pre-release

### ISSUE THREAD

**Issue by stijnfrishert** [rust-lang/rust-analyzer#11989]
1. Create an empty binary cargo project with the nightly toolchain
2. Put the following code in main:

```
#![feature(generic_associated_types)]

pub trait Processor {
    type Ctx<'a, const N: usize>;

    fn process<const N: usize>(&mut self, ctx: Self::Ctx<'_, N>);
}

#[derive(Default, Debug)]
pub struct Phasor {
    phase: f32,
}

pub struct PhasorCtx<'a, const N: usize> {
    increments: &'a [f32; N],
    output: &'a mut [f32; N],
}

impl Processor for Phasor {
    type Ctx<'a, const N: usize> = PhasorCtx<'a, N>;

    fn process<const N: usize>(&mut self, ctx: Self::Ctx<'_, N>) {
        for i in 0..N {
            ctx.output[i] = self.phase;
            self.phase += ctx.increments[i];
            if self.phase > 1.0 {
                self.phase -= self.phase as i32 as f32;
            }
        }
    }
}

fn main() {
    println!("Hello, world!");
}
```

I'm getting errors like `textDocument/semanticTokens/full`, `textDocument/semanticTokens/full/delta`, `textDocument/inlayHints` and `textDocument/definition` failed every time I start typing.

I know several GAT issues have already been solved, but I'm working with a pre-release version from 2 days ago. Assuming [this fix](https://github.com/rust-lang/rust-analyzer/pull/11957) already made it in 3 days ago I'm still running into issues and thought this warranted an issue report. :)

**rust-analyzer version**: rust-analyzer version: faaec86ff 2022-04-12 nightly
**rustc version**: rustc 1.61.0-nightly (c84f39e6c 2022-03-20)

**Comment by skyzh** [comment]
A combination of const generics and GAT might be the cause of this issue. My fix only bypasses the case for GAT without const generics 🤣

**Comment by Nugine** [comment]
```rust
pub trait Select {
    type Output<'a, T>
    where
        T: 'a,
        Self: 'a;
    fn select<'a, T>(self, slice: &'a [T]) -> Self::Output<'a, T>
    where
        Self: 'a;
}

impl<const N: usize> Select for [usize; N] {
    type Output<'a, T> = impl Iterator<Item=&'a T> + 'a where T:'a;

    fn select<'a, T>(self, slice: &'a [T]) -> Self::Output<'a, T>
    where
        Self: 'a,
    {
        self.into_iter().map(move |i| &slice[i])
    }
}
```

rust-analyzer 0.0.0 (766c5f086 2022-07-16)
rustc 1.62.0 (a8314ef7d 2022-06-27)
