### ISSUE TITLE
VSCode can't disable inlay hints

### ISSUE THREAD

**Issue by jkelleyrtp** [rust-lang/rust-analyzer#11998]
**rust-analyzer version**: `rust-analyzer version: 7ce3ca5aa 2022-04-15 nightly`

**rustc version**: `rustc 1.60.0 (7737e0b5c 2022-04-04)`

When I set `"rust-analyzer.inlayHints.enable": false`, the inlay hints remain. I would expect inlay hints to disappear. I have this configured to "toggle inlay hints" which seems to do nothing.

**Comment by lnicola** [comment]
Try `editor.inlayHints.enabled`.

**Comment by jkelleyrtp** [comment]
> Try `editor.inlayHints.enabled` and the https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler extension.

Ah this seems to be a result of #11935 - would be nice if the "toggle inlay hints" toggled "editor.inlayHints.enabled" instead.

I'll leave this issue open until docs are updated or behavior is changed to keep things up to date.
