### ISSUE TITLE
"reload required due to source changes of a procedural" alerted error message

### ISSUE THREAD

**Issue by acfuns** [rust-lang/rust-analyzer#12018]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
Extension version: 0.3.1015
**rustc version**: (eg. output of `rustc -V`)
rustc 1.60.0 (7737e0b5c 2022-04-04)
**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
CARGO

This error can occur in any project, even a newly created project.

![image](https://user-images.githubusercontent.com/55129666/163725715-09c38b4e-571e-46b8-b2e6-d8b84dd38081.png)

**Comment by Veykril** [comment]
This has been fixed yesterday, but the latest nightly release failed to publish again so the message should disappear tomorrow.

**Comment by acfuns** [comment]
> 

Thanks for your reply, I see.
