### ISSUE TITLE
Incorrect brace highlighting

### ISSUE THREAD

**Issue by Barugon** [rust-lang/rust-analyzer#12034]
**rust-analyzer version**: both v0.3.1017 and v0.2.1010

**rustc version**: 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: none

Brace highlighting is often wrong.

Here, no braces should be highlighted but, as you can see, there is.
![Screenshot from 2022-04-19 14-43-54](https://user-images.githubusercontent.com/16503728/164107337-a0663c94-5ad7-4d3b-9488-b6f533b6fdfa.png)

Here, the wrong braces are highlighted.
![Screenshot from 2022-04-19 14-49-18](https://user-images.githubusercontent.com/16503728/164107897-693593c2-d849-41c0-ac65-22ddfcb37fc7.png)

**Comment by jonas-schievink** [comment]
I don't think this is our feature, so it might be a VS Code bug
