### ISSUE TITLE
Installation of rust-analyzer fails on OpenBSD

### ISSUE THREAD

**Issue by liar666** [rust-lang/rust-analyzer#12038]
I'm copying my bug report @lsp since no one is responding there...
https://github.com/emacs-lsp/lsp-mode/issues/3224

### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

Hi,

I'm not running one of the "mainstream" OSes: Windows, macOS, Linux. I'm running OpenBSD.

When I open a `.rust` file in Emacs, and run `M-x lsp`, `lsp` package proposes to automatically install the `rust-analyzer` language server.

This process ends up with a not-so-informative error message saying the installation failed.

Fortunately `lsp` tells me where it tries to install the `rust-analyzer` tool, thus looking at this directory (`.emacs.d/.cache/lsp/rust`) I found a 9 bytes `rust-analyzer.xz` file that contains only: 'Not found'.

Going to the `rust-analyzer` page, I discovered that assets are proposed for Windows, macOS & Linux only:
https://github.com/rust-analyzer/rust-analyzer/releases

So I imagined that the automatic installer is working as follows:
- getting the os name through a `uname`-like call,
- downloading the binary asset on the `rust-analyzer` page, by composing its name based on the OS name `rust-analyzer-<OS>`,
- as there is no such file proposed on the `rust-analyzer` assets page, the file ends up containing 'Not found'

As a OpenBSD user, I can understand that no asset is proposed on the `rust-analyzer` page for this OS, but then `lsp` should not try to download it & it should also fail with a more informative error message.

### Steps to reproduce

- Get an OpenBSD machine
- Install Emacs
- Install LSP
- Run `M-x lsp-install-server`
- Accept the installation of `rust-analiyzer`
- Observe that it fails without much explanation of the problem

### Expected behavior

I see two possibilities:

- Simplest: If OS name is not win/mac/linux, then do not attempt to dwl a binary and display an error message asking the user to compile manually the tool and install it in `.emacs.d/.cache/lsp/rust`

- More complicated:  If OS name is not win/mac/linux, then clone/download the sources of `rust-analyzer` and compile them (either assuming that the user has installed `rust` & `cargo` since she is trying to code in Rust, or by displaying an error if these tools are not installed).

### Which Language Server did you use?

lsp-rust

### OS

Linux

### Anything else?

Your Bug Report Template imposes to choose an OS and the list is limited to Win/mac/Lin. As I said, I'm under OpenBSD. Thus I put a random value in this field...

**Comment by jonas-schievink** [comment]
Closing as per the comment above, we don't develop the emacs integration
