### ISSUE TITLE
Profile memory_usage is broken on Mac OS Monterey 

### ISSUE THREAD

**Issue by AlexMikhalev** [rust-lang/rust-analyzer#12039]
I noticed that profile memory_usage doesn't work on Mac, I extracted https://github.com/AlexMikhalev/profile and added simple basic example to illustrate.
```
use profile::memory_usage;
fn main() {

    let before = memory_usage().allocated;
    println!("Before {:?}",before.to_string());
    let result = 2 + 2;
    println!("After {:?}",memory_usage().allocated.to_string());
    assert_eq!(result, 4);
}
```
```
cargo run --example basic
   Compiling profile v0.0.0 (/Users/alexmikhalev/rust_code/profile)
    Finished dev [unoptimized + debuginfo] target(s) in 2.57s
     Running `target/debug/examples/basic`
Before "0b"
After "0b"
```
Works on Linux but doesn't work on Mac, which means caches are not cleaned up from [here](https://github.com/rust-lang/rust-analyzer/blob/34c3e0b0672f8a2bed571b844f1ace6f83f5fae3/crates/ide_db/src/apply_change.rs#L51)

**rust-analyzer version**: rust-analyzer version: 7d6fcbc0b 2021-12-06 stable

**rustc version**: (eg. output of `rustc -V`)
```
rustc -vV
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-apple-darwin
release: 1.60.0
LLVM version: 14.0.0
```

**Comment by lnicola** [comment]
As you can see in [the implementation](https://github.com/AlexMikhalev/profile/blob/main/src/memory_usage.rs#L28-L56=), this feature uses some special memory allocator APIs which are only available on Linux and `jemalloc`. Building with `--feature jemalloc` should make it work.

**Comment by lnicola** [comment]
Note that there are some, potentially obsolete, reasons why we don't build with `jemalloc` by default: https://github.com/rust-lang/rust/issues/36963#issuecomment-252029017=.

**Comment by AlexMikhalev** [comment]
Thank you, building with --features jemalloc works. I would suggest re-visiting building with jmallock support for rust-analyzer, I found cache cleaning in apply_change.rs quite clean and if mac os users don't have cache cleaned it may lead to performance degradation for rust-analyzer users.

**Comment by lnicola** [comment]
You're not supposed to use that command unless you're debugging the memory usage. What do you mean by that?

**Comment by AlexMikhalev** [comment]
Actually, while it runs it produces the same number on Mac - it's a different number between before and after on Linux how it should.
```
cargo run --example basic --features jemalloc
Before "35kb"
After "35kb"
```

**Comment by lnicola** [comment]
Adding two numbers doesn't really allocate anything. What exactly are you trying to do?

**Comment by AlexMikhalev** [comment]
```
    let before = memory_usage().allocated;
    println!("Before {:?}",before.to_string());
    let v: Vec<_> = (1..100000000).collect();
    println!("After {:?}",memory_usage().allocated.to_string());
```
still produces
```
Before "35kb"
After "35kb"
```
same as above two numbers.

**Comment by bjorn3** [comment]
It is possible that the memory allocation is optimized away by LLVM. Try adding `unsafe { std::arch::asm!("", in(reg) &v); }` to ensure LLVM can't remove the allocation.

**Comment by lnicola** [comment]
Did you set the global allocator as in https://github.com/rust-lang/rust-analyzer/blob/master/crates/rust-analyzer/src/bin/main.rs#L20=?
