### ISSUE TITLE
Inlay Hints not working in neovim windows 

### ISSUE THREAD

**Issue by Ivan-Sanchez-Diaz** [rust-lang/rust-analyzer#12047]
rust-analyzer version: rust-analyzer f83dce0a4 dev
I set up my environment with rust-analyzer and neovim and everything works fine except the inlay hints 
maybe I'm missing something very basic
```
lua <<EOF
local nvim_lsp = require'lspconfig'

local opts = {
    tools = { -- rust-tools options
        autoSetHints = true,
        hover_with_actions = true,
        inlay_hints = {
            show_parameter_hints = false,
            parameter_hints_prefix = "",
            other_hints_prefix = "",
        },
    },

    server = {
        settings = {
            ["rust-analyzer"] = {
                checkOnSave = {
                    command = "clippy"
                },
            }
        }
    },
}

require('rust-tools').setup(opts)
EOF
```
![Hnet-image](https://user-images.githubusercontent.com/83692003/164335497-6f7f91e9-536c-4a6f-8377-3c0ab801d5c5.gif)

**Comment by lnicola** [comment]
See https://github.com/simrat39/rust-tools.nvim/issues/175.

**Comment by Ivan-Sanchez-Diaz** [comment]
I already saw the issue but after a few hours trying I couldn't activate the LSP inlay hint :(, I'm new to neovim and I'm learning, any advice?

**Comment by lnicola** [comment]
Download an older RA release (from three weeks ago, maybe?).
