### ISSUE TITLE
Perl and Unix paths on Windows VS Code

### ISSUE THREAD

**Issue by JosuGZ** [rust-lang/rust-analyzer#12049]
I'm having the following problem: I have Perl present on my path and can build a cargo project that needs it (due `openssl-sys`) without a problem.

But when running rust analyzer I keep getting the following:

`This perl implementation doesn't produce Unix like paths`.

I'm not sure whether this might be considered a bug or if there is something that I can configure.

**Comment by JosuGZ** [comment]
It turns out the problem was that I was using the `"rust-analyzer.cargo.target": "arm-unknown-linux-gnueabihf"` setting and that was causing the problem.

**Comment by lnicola** [comment]
Can we close this, then?
