### ISSUE TITLE
panic when open a rust workspace

### ISSUE THREAD

**Issue by charlesxsh** [rust-lang/rust-analyzer#12056]
[Info  - 4:14:22 AM] Connection to server got closed. Server will restart.
thread 'main' panicked at 'index out of bounds: the len is 45 but the index is 99', crates/project_model/src/workspace.rs:762:78
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: project_model::workspace::ProjectWorkspace::to_crate_graph
   4: rust_analyzer::reload::<impl rust_analyzer::global_state::GlobalState>::switch_workspaces
   5: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
   6: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   7: rust_analyzer::main_loop::main_loop
   8: rust_analyzer::run_server
   9: rust_analyzer::main

**Comment by jonas-schievink** [comment]
This was fixed by https://github.com/rust-lang/rust-analyzer/pull/12044 and should be included in the last nightly release (v0.3.1026)
