### ISSUE TITLE
Resolving variable references is not working as expected in function that is annotated with proc macro

### ISSUE THREAD

**Issue by FylmTM** [rust-lang/rust-analyzer#12050]
**rust-analyzer version**: 65fbe0a8d 2022-04-18 stable
**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)
**relevant settings**: -

When annotating function with proc-macro, resolving references inside such a function does not behaves as expected:
* Variable references are no longer highlighted
* Pressing "Go to definition" on variable declaration does not open reference list

In my case, this is `tracing::instrument` proc macro.

Code example:
```rust
struct Struct { field: i32 }


#[tracing::instrument]
fn test_with_instrumentation() {
    let variable = Struct { field: 42 };

    variable.field;
    variable.field;

}

fn test_without_instrumentation() {
    let variable = Struct { field: 42 };

    variable.field;
    variable.field;
}
```

Here how it looks like in function that is not annotated:
![image](https://user-images.githubusercontent.com/626772/164485613-239cde31-3c7e-4bca-8040-0b424129f78d.png)

You can see that I can get a list of references (when executing go to definition on variable declaration) and references are highlighted with gray box.

Here how it looks like in function that is annotated:
![image](https://user-images.githubusercontent.com/626772/164486276-5cef7a50-de70-406f-888c-1e839c96d6a3.png)
Go to definition does nothing, and references are not highlighted.

However if I try go to definition on one of usages, it will jump me to declaration.

I tried to add this configuration in VS Code, but it did not made any difference:
```
    "rust-analyzer.procMacro.ignored": {
        "tracing": [
            "instrument"
        ]
    }
```

**Comment by Veykril** [comment]
```json
    "rust-analyzer.procMacro.ignored": {
        "tracing-attributes": [
            "instrument"
        ]
    }
```
should work as a workaround (the attributes come from `tracing-attributes` not `tracing`, they are just re-exported there)

**Comment by FylmTM** [comment]
Can confirm that this workaround works for me. 🎉 
Thanks! Amazing stuff 🕺
