### ISSUE TITLE
How to config "target_arch"?

### ISSUE THREAD

**Issue by leo-frank** [rust-lang/rust-analyzer#12061]
Thanks for great work of rust-analyzer! Here is a question as a newbie user.

See the code following .

Like i'm using a X86-64 PC, the first cfg is activated. But I'm developing a cross-platform application,  so i need the config of other ISA to be activated, such as aach64.

 I wonder if there is a way for doing this?

```
#[cfg(target_arch = "x86_64")]
#[path = "arch/x86_64/mod.rs"]
mod arch;

#[cfg(any(target_arch = "riscv32", target_arch = "riscv64"))]
#[path = "arch/riscv/mod.rs"]
mod arch;

#[cfg(target_arch = "mips")]
#[path = "arch/mipsel/mod.rs"]
pub mod arch;

#[cfg(target_arch = "aarch64")]
#[path = "arch/aarch64/mod.rs"]
pub mod arch;
```

**Comment by Veykril** [comment]
You can set `rust-analyzer.cargo.target` to a target triple, then r-a should use the corresponding cfgs.

**Comment by leo-frank** [comment]
thanks!

**Comment by KySpace** [comment]
In helix this is to save a `.helix/languages.toml` file, with
```toml
[language-server.rust-analyzer.config]
rust-analyzer.cargo.target = "wasm32-unknown-unknown"
```
