### ISSUE TITLE
rust-analyzer emit `Can't find RawLauguage in module crate::syntax` diagnostic, but `cargo check` works fine

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rust-lang/rust-analyzer#12062]
rust-analyzer version: 65fbe0a8d 2022-04-18 stable

rustc 1.60.0 (7737e0b5c 2022-04-04)
**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

**Comment by IWANABETHATGUY** [comment]
how to reproduce: 
1. `git clone https://github.com/rome/tools`
2. jump to `crates/rome_rowan/src/serde_impls.rs`
3. save the code
![image](https://user-images.githubusercontent.com/17974631/164877753-d9ad804a-19ec-4fe0-81d0-05b1890ba278.png)
4. run `cargo check`

**Comment by IWANABETHATGUY** [comment]
expected behavior:
No false positive diagnostic error emit;

**Comment by bjorn3** [comment]
That error comes from rustc not rust-analyzer. Does `cargo check --workspace --all-targets` work?

**Comment by IWANABETHATGUY** [comment]
> That error comes from rustc not rust-analyzer. Does `cargo check --workspace --all-targets` work?

Yeah , it works too.

**Comment by lnicola** [comment]
Did you set `rust-analyzer.cargo.features` in Code? That module is gated on the `serde1` feature.

**Comment by IWANABETHATGUY** [comment]
> 
![image](https://user-images.githubusercontent.com/17974631/164882528-f6e91f95-898c-4201-bdac-3d25cd605b40.png)
Yeah, should I close that ?

**Comment by lnicola** [comment]
Try `cargo check --all-targets --all-features` and see what happens.

**Comment by IWANABETHATGUY** [comment]
![image](https://user-images.githubusercontent.com/17974631/164882613-0c6e88ff-5dd1-4840-a018-168bb02309f0.png)
Yeah, rustc emit that error

**Comment by IWANABETHATGUY** [comment]
So you mean this should not be a issue about rust-analyzer right? this is a expected behavior

**Comment by lnicola** [comment]
It's expected, since it just shows a compiler error. `RawLanguage` is accessible as `crate::raw_language::RawLanguage`, not `crate::syntax::RawLangage`, maybe it needs to be re-exported.
