### ISSUE TITLE
Incorrect parameter completion type 

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rust-analyzer#12079]
**rust-analyzer version**: https://github.com/rust-lang/rust-analyzer/commit/68694919744709385e168f5812b73e28c513b5d6 (master from some hours ago) 

**rustc version**: rustc 1.62.0-nightly (18f314e70 2022-04-24)

```rust
struct Foo;
impl Foo {
    fn test<V>(&mut self, val: V) {
    }
}

fn sup() {
    Foo.test(<|>)
}
```

rust-analyzer shows the wrong completion parameter type for `val` (for `Foo::test`).  

<img width="366" alt="image" src="https://user-images.githubusercontent.com/5961244/165139812-22d8b200-6383-4b96-a8ab-80c4758808f8.png">

**Comment by lnicola** [comment]
Probably caused by #12063, cc @iDawer
