### ISSUE TITLE
parameter completion are no longer being filtered by the client

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#12073]
```rs
fn foo(foo: u32, bar: u32, baz: u32, qux: u32, ) {}

fn bar(b$0)
```
shows all the parameters here, but the client should be able to filter all but `bar` and `baz` out.
![image](https://user-images.githubusercontent.com/3757771/164989871-fa871b9a-c0ba-48ad-9184-179d9ed336b1.png)

**Comment by rainy-me** [comment]
@Veykril  Sorry but I think this bug was introduced in https://github.com/rust-lang/rust-analyzer/pull/12040. Sadly, I still get the `look_up` wrong😢. https://github.com/rust-lang/rust-analyzer/pull/12040#discussion_r855296429 cc @jonas-schievink 

By changing the `lookup` to `label` or `fmt(label)` seems to resolve the filtering issue while rendering the correct completions. At the same time, I'm still not very clear about what's the expected value for lookup here. Could you point me to some  documentations or info about the lookup behavior?

https://github.com/rust-lang/rust-analyzer/blob/68694919744709385e168f5812b73e28c513b5d6/crates/ide_completion/src/completions/fn_param.rs#L34

btw, the test below will produce the full list even before that PR. Is there a way to test the filtering?

```rust
#[test]
fn filter_param() {
    check(
        r#"
fn foo(foo: u32, bar: u32, baz: u32, qux: u32, ) {}
fn bar(b$0)
}
"#,
        expect![[r#"
            bn qux: u32
            bn foo: u32
            bn baz: u32
            bn bar: u32
            kw ref
            kw mut
        "#]],
    );
}
```

I think it'll be a good idea to enforce the filtering in tests as https://github.com/rust-lang/rust-analyzer/pull/12040#discussion_r855226480 said?

**Comment by Veykril** [comment]
The completion item docs for the lsp layer are here https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem

Specifically our `lookup` translates to the `filterText`.

Sp the lookup string has to contain the identifier that is being completed. Though I am not sure how this plays out with non identifier characters being in there and the docs don't say anything about it so that might be VSCode playing wrong as well.

> I think it'll be a good idea to enforce the filtering in tests as #12040 (comment) said?

We should probably add asserts in tests to check for LSP conformance there.

**Comment by rainy-me** [comment]
The cause of the filtering issue is `lookup` changed to `param.text()` which in fact is the same text for each completion item, as the document for `filterText` says
> When `falsy` the label is used as the filter text for this item.

Just remove the lookup in the `Some` case would be the fix?

**Comment by Veykril** [comment]
Ah the the filter text is set to the parameter that we complete, yes that would explain the weird filtering here. I don't quite see how the original lookup doesn't work though. Or rather I am not sure why the lookup had to be changed at all.

**Comment by Veykril** [comment]
Judging from the LSP docs the lookup should not affect any of this.

**Comment by Veykril** [comment]
I guess one easy fix would be to append the completion to the contents of what the completion text range covers and use that as the lookup? Not too fond of it but that seems like the simplest approach

**Comment by rainy-me** [comment]
Given following code as an example:

```rust
fn f(foo: (), #[baz = "qux"] mut bar: u32) {}
fn g(foo: ()#[baz = "qux"] mut ba$0)
```
- completion text range cover: `ba`
- lookup from add_new_item_to_acc: `mut bar`
- label(whole_param): `#[baz = "qux"] mut bar: u32`
- full completion content: `, #[baz = "qux"] mut bar: u32`
- completion edit range: `#[baz = "qux"] mut ba`
 
> append the completion to the contents of what the completion text range covers

I'm not very sure about why this would be better than using the label itself.

**Comment by Veykril** [comment]
Ah right, I misunderstood, ye the label itself is enough (in which case you can just drop the `lookup_by` I think as it defaults to the label if not set)

**Comment by rainy-me** [comment]
Whether including the type or not is a different decision. Params without type (e.g `#[baz = "qux"] mut bar`) are also suitable for the lookup and their are closer to the behavior before. Some extra calculation are needed though. As you would expect it will enable/disable filtering by the type part. I'm ok with both myself.

---

Another (unrelated) question I had about the completions for fn params is,

https://github.com/rust-lang/rust-analyzer/blob/198c07558094a28bd0e0653f298848070c4b910a/crates/ide_completion/src/completions/fn_param.rs#L33-L36

In which situation would we hit the `None` case? I felt very unlikely when reading through this.

**Comment by Veykril** [comment]
> In which situation would we hit the None case? I felt very unlikely when I read through this.

From a quick glance, never. It's just that we want to avoid unwraps so we use some defaults in these cases even if they won't be hit.

**Comment by rainy-me** [comment]
> From a quick glance, never.

I was asking this as if we use the label as lookup and very unlikely to hit the `None` case, we don't need to bother calculating and passing `lookup: String` to `add_new_item_to_acc`.

**Comment by Veykril** [comment]
Ye we don't need to I think
