### ISSUE TITLE
inlay hint tooltip window is not show up

### ISSUE THREAD

**Issue by bigdogs** [rust-lang/rust-analyzer#12081]
Hi,
As described of title, tooltip window  is not show when mouse hover to the inlay type.
I'm not sure if this is a bug, or I need to enable some feature flag
![image](https://user-images.githubusercontent.com/20614926/165212826-2a362f93-7bba-43d2-b146-073a27f872d6.png)

**Comment by Veykril** [comment]
That is not yet implemented and somewhat depends on https://github.com/rust-lang/rust-analyzer/issues/11701 I think

**Comment by bigdogs** [comment]
emm..  As my understanding, tooltip window for hint type is not a new feature(as the below image).  
![image](https://user-images.githubusercontent.com/20614926/165276112-0554561e-fe9e-4494-aa99-8b19bbb3daef.png)


> That is not yet implemented

Do you mean this feature is disabled ?

**Comment by Veykril** [comment]
No it is not implemented. When you try to hover chaining hints (the inlay hints that come after method chains) the hover goes through as a normal hover, which r-a does fallback for here showing you the hover for the type of the entire expression. Note how the hover tooltip shows a different type than the inlay hint.

**Comment by bigdogs** [comment]
Got it , Thanks

**Comment by Veykril** [comment]
This is now implemented
