### ISSUE TITLE
Auto-Import rewrites already completed word, resulting in broken usage

### ISSUE THREAD

**Issue by Dragonseel** [rust-lang/rust-analyzer#12091]
**rust-analyzer version**: rust-analyzer version: b5d7a712e 2022-04-25 stable

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: I don't know any relevant settings.

I use rust-analyzer in VSCode 1.66.2

Suppose I have following code in `main.rs`. There are no dependencies, and no other code files.

```rust
mod testmod {
    pub fn testfn() -> u8 {
        8
    }
}

fn main() {
    println!("{}", testfn());
}
```
When I now place my curser after the `t` in `testfn()` call in the println - line and press CTRL+SPACE, I get the hint `testfn() (use crate::testmod::testfn)` which is correct. If I now accept this with RETURN, I will end up with following line:
`println!("{}", testfnestfn());`

As you see, the auto-completion hint added the full function name after the cursor, eventhough it was already there.

**Comment by Veykril** [comment]
This is controlled by the client, for vscode specifically you can set `"editor.suggest.insertMode": "replace"` which should give you the behavior you want.

**Comment by Dragonseel** [comment]
Oh. Thank you! That is indead the behavior I wanted.
So many options...
