### ISSUE TITLE
Create rust-analyzer-0.4.0-dev.vsix from source code in editors/code failed

### ISSUE THREAD

**Issue by surechen** [rust-lang/rust-analyzer#12096]
Hello, I try to make rust-analyzer-0.4.0-dev.vsix from [source code](https://github.com/rust-lang/rust-analyzer/releases/tag/2022-04-25) in editors/code. I use following shell command:

```bash
cd editors/code
npm install vsce -g --save vsce
npm install
vsce package
```

After that I get rust-analyzer-0.4.0-dev.vsix and I install it in Vscode.

But I got error information:  

Cannot activate rust-analyzer: bootstrap error:

See the logs in "OUTPUT > Rust Analyzer Client" (should open automatically). To enable verbose logs use { "rust-analyzer.trace.extension": true }

INFO [2022/4/27 19:03:21]: PersistentState: { serverVersion: '0.3.1032' }
INFO [2022/4/27 19:03:21]: Using server binary at rust-analyzer
ERROR [2022/4/27 19:03:21]: Bootstrap error [Error: Failed to execute rust-analyzer --version
	at ES (c:\Users\c00511327\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\main.js:85:2158)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async _S (c:\Users\c00511327\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\main.js:84:2883)
	at async sv (c:\Users\c00511327\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\main.js:84:2714)]

**Comment by lnicola** [comment]
You need a matching language server binary. You can compile and install one using `cargo xtask install`, which will also build and install the VSIX.

**Comment by surechen** [comment]
> You need a matching language server binary. You can compile and install one using `cargo xtask install`, which will also build and install the VSIX.
> 
> https://rust-analyzer.github.io/manual.html#building-from-source

Thanks.
