### ISSUE TITLE
Rename non-kebab case crates to kebab-case

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#12102]
Basically all crates but `rust-analyzer` and `vfs-notify` are currently snake_cased. This is inconsistent and the concensus seems to be in favor of kebab-case for them.

https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/crate.20naming.20conventions

**Comment by randomicon00** [comment]
Hi @Veykril,
Is this up for grabs? First time contributor but I would love to give it a try.

**Comment by lnicola** [comment]
It's yours.
