### ISSUE TITLE
How do I modify rust-analyzer's text color?

### ISSUE THREAD

**Issue by Raj2032** [rust-lang/rust-analyzer#12121]
I am using a third party theme and on top of that I have made my own custom color text theme inside `settings.json` in vscode:

```json
    "editor.tokenColorCustomizations":
    {
        
        "[Bearded Theme Oceanic]": {
            "textMateRules": [
                {
                  "scope": "string.quoted.double.rust",
                  "settings": {
                    "foreground": "#d790f8",
                  }
                }
              ],
            
          }
          

        //"comments": "#1de2769c"
    },
```

However the issue is that because of the extension "rust-analyzer", this hijacks my custom text color theme after it has finished performing analyzing.

I could add this:

```json
"[rust]": {
    "editor.semanticHighlighting.enabled": false
}
```

but then the third party text colors would then be different.

I was wondering if there was a way to modify rust-analyzer's default colors or something?

**Comment by Veykril** [comment]
The semantic highlighting colors r-a emits are listed here https://rust-analyzer.github.io/manual.html#semantic-syntax-highlighting

To change them you have editor the `editor.semanticTokenColorCustomizations` config. An example that will use semantic highlighting to color strings to your color would be the following:

```json
    "editor.semanticTokenColorCustomizations": {
        "rules": {
            "string": "#d790f8"
        }
    },
```

**Comment by Raj2032** [comment]
@Veykril Thanks mate that helps a lot :)

**Comment by Raj2032** [comment]
@Veykril Sorry I am going to ask some questions.

in regards to `macros` when I change the color I can get the `println` bit to change but not the exclamation mark `!`, not sure why this is happening?

In regards to functions, not sure why the this line:

`Example::run(Settings::default()).unwrap();` how come the `run()`, `default()` and `unwrap()` functions are not changing?
