### ISSUE TITLE
Strings are getting the `meta.embedded.asembly` semantic token even when not `asm!`

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust-analyzer#12122]
![image](https://user-images.githubusercontent.com/5992217/166106399-88d0ac45-64e9-4148-812e-bf02efaae7ab.png)

That *probably* shouldn't be there 😄

**rust-analyzer version**: rust-analyzer version: c6995a372 2022-04-30 nightly

**rustc version**: rustc 1.62.0-nightly (082e4ca49 2022-04-26)

**relevant settings**: semantic highlighting on

**Comment by Veykril** [comment]
That seems to be some other extensions of yours. rust-analyzer has no `meta.embedded.assembly` semantic token nor does it supply text mate tokens.
