### ISSUE TITLE
How come the `if` keyword has a different color compared to `fn` keyword?

### ISSUE THREAD

**Issue by Raj2032** [rust-lang/rust-analyzer#12129]
I am currently modifying some of the keywords.

```json
    "editor.semanticTokenColorCustomizations": {
        "rules": {
            //"string": "#87c886",
            "string": "#97b797ff",
            //"boolean": "#ff0000",
            "function":"#3e8ad0ff",
            "macro": "#3e8ad0ff",
            "macroBang": "#3e8ad0ff",
            "method": "#3e8ad0ff",
            "namespace": "#3e8ad0ff",

            //"keyword": "#5BB3B4",

            "boolean": "#b4552d",
        }
    },
```

in vscode if I run `Developer: Inspect Editor Tokens and Scopes` then after inspecting both the `fn` key and `if` words, the `semantic token type` is `keyword`, yet they both have different colors:

![image](https://user-images.githubusercontent.com/29293830/166130257-1701a6c6-beaf-4073-b7fc-709a87880fe2.png)

If I added this line in the `settings.json` file `"keyword": "#5BB3B4",`, it will change both the `fn` and `if` but I don't want it to modify the `if` keyword. Is there a way to not modify the `if` keyword? Maybe if there is a way to specifically mention the `if` keyword's color?

**Comment by jhgg** [comment]
If you want to change the color of the "if" statement, use `"keyword.controlFlow": "#COCOCO"`. Don't forget about the scope *and the modifiers*. 

![image](https://user-images.githubusercontent.com/5489149/166130916-5f8cd351-1d1f-4c50-8258-b54733e7072e.png)

**Comment by Raj2032** [comment]
@jhgg Ah right mate thanks mate :)
