### ISSUE TITLE
Associated type completions in `impl Iterator<$0` should have higher score

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#12140]
The completions we show there are fairly generic and drown out the more targeted associated type completions. Those should have a slightly higher score.

(these completions were implemented in https://github.com/rust-lang/rust-analyzer/pull/9223)

**Comment by flodiebold** [comment]
Actually, the other completions don't make any sense at all in this case, do they? I think we could remove those completions when all type arguments (0 in this case) are specified?

**Comment by Alastair-smith2** [comment]
@jonas-schievink I'm interested in picking this up but just to ensure I understand, it's being said when there's an associated type there should no suggestion (as based on @flodiebold's suggestion)?

**Comment by jonas-schievink** [comment]
Fixing that part is probably more complex. It requires all *other* completions to know that only an associated type, and not an arbitrary type argument is expected.
