### ISSUE TITLE
Signature help in `impl Iterator<$0` is empty, which is misleading

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#12141]
![screenshot-2022-05-03-16:24:54](https://user-images.githubusercontent.com/1786438/166472169-948e1ab4-9d02-4077-bda8-78cbcf9f0451.png)

This is misleading because you can write associated type bindings there. They are order-independent, which complicates this a bit. How do other LSP implementations display order-independent call arguments?

**Comment by Veykril** [comment]
I think we could go with showing them in declaration order with the already typed ones ordered at the start (so basically adjusting the showed order while being typed out)?
