### ISSUE TITLE
rust-analyzer failed to load workspace: "C:\\Users\\admin\\.cargo\\bin" "--version" failed: access denied。 (os error 5)

### ISSUE THREAD

**Issue by jingyuexing** [rust-lang/rust-analyzer#12146]
cargo version: `cargo 1.60.0 (d1fd9fe2c 2022-03-01)`
rustc version: `rustc 1.60.0 (7737e0b5c 2022-04-04)`

each time the plugin is started, it will query a file path for version information
![image](https://user-images.githubusercontent.com/19589872/166653043-479e8862-1fe3-46fc-aa04-c18d32465c4b.png)

**Comment by lnicola** [comment]
Did you set the a `CARGO` or `RUST` environment variable? https://www.aomeitech.com/windows-tips/set-windows-11-environment-variables.html

Do you have any RA-specific settings in Code?

**Comment by jingyuexing** [comment]
I set `CARGO`,The value is the one in the picture , `RUST` no setting

**Comment by lnicola** [comment]
Try removing it.

**Comment by jingyuexing** [comment]
> Try removing it.
thx ,it works , you are my god.
