### ISSUE TITLE
Display trait method documentation string on impl

### ISSUE THREAD

**Issue by Integralist** [rust-lang/rust-analyzer#12147]
👋🏻 

Apologies if this is the wrong project to ask about this. Although I'm mentioning NeoVim LSP specific features I _think_ it would require some form of support within rust-analyzer 🤔 

**Here is the scenario...**

If I have a trait such as:

```rust
pub trait Foo {
    /// Some useful information.
    fn do_something(&self) -> String;
}
```

And I have the following code that implements the trait:

```rust
impl Foo for Bar {
    fn do_something(&self) -> String {
        "example".to_string()
    }
}
```

When my cursor is on the `do_somthing` method it would be useful if executing (and now I'm in the realm of NeoVim's built-in LSP client) `:lua vim.lsp.buf.hover()` would display the doc string from the trait.

My reasoning here is that I inherited a large rust project and there were multiple occasions where the developer had impl blocks for their own custom traits and I just wanted to peek at the details and didn't necessarily want to have to jump into the implementation to read the doc strings. I would use `:lua vim.lsp.buf.hover()` and realise that although there were doc strings defined for the trait methods I couldn't read them unless I actually jumped to the definition and back (e.g. `:lua vim.lsp.buf.definition()`).

If this doesn't seem like a useful thing to support (or indeed this is the wrong place entirely to ask about it) then feel free to close this issue.

Thanks.

**Comment by Veykril** [comment]
This has been implemented

**Comment by rav-en** [comment]
hello, please forgive my simple question, but how do i activate this now?

**Comment by Veykril** [comment]
it should work out of the box.
![image](https://user-images.githubusercontent.com/3757771/214942568-e6c532f5-22d9-43c4-aa72-426f7a424433.png)

**Comment by sjackman** [comment]
@Veykril Could the trait method docstring be displayed as inlay text? so that
```rust
impl Foo for Bar {
    fn do_something(&self) -> String {
        "example".to_string()
    }
}
```
is displayed as
```rust
impl Foo for Bar {
    /// Some useful information.
    fn do_something(&self) -> String {
        "example".to_string()
    }
}
```

**Comment by Veykril** [comment]
Unfortunately not, inlay hints are strictly for interspersing text into a line, not between lines
