### ISSUE TITLE
hover literal integer fallback overflow i32 

### ISSUE THREAD

**Issue by bitgaoshu** [rust-lang/rust-analyzer#12155]
<img width="871" alt="截屏2022-05-05 11 05 16" src="https://user-images.githubusercontent.com/7943146/166859655-6dbc1d39-d361-4be2-a249-b89058203ab6.png">

I think the hover literal is overflow i32. should show ${unknown}

**Comment by flodiebold** [comment]
Whether the literal would fit into an i32 or not [does not have any effect on its type](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8d8afe2606a1834a14c1a00c32c19a37), so this is correct.
