### ISSUE TITLE
Auto Format brakes when there's commented code that would be indented

### ISSUE THREAD

**Issue by jvcmarcenes** [rust-lang/rust-analyzer#12154]
**rust-analyzer version**: 5dce1ff02 2022-05-02 stable
**rustc version**: rustc 1.58.1 (db9d1b20b 2022-01-20)

Using vscode's automatic indent feature causes commented code to indent wrongly

Source code:
```
// this breaks auto-indent:
// fn foo() {
//
// }
```

Expected result when auto indenting:
```
// this breaks auto-indent:
// fn foo() {
//
// }
```

Actual result when auto indenting:
```
// this breaks auto-indent:
// fn foo() {
	//
	// }
```

**Comment by jonas-schievink** [comment]
This happens without `rust-analyzer` installed too, so it's not our bug.
