### ISSUE TITLE
Very big fingerprint, over 9G

### ISSUE THREAD

**Issue by optionals** [rust-lang/rust-analyzer#12156]
**rust-analyzer version**: vscode extension v0.2.1040. rust-analyzer 5dce1ff02 2022-05-02 stable

**rustc version**: rustc 1.59.0

**relevant settings**: None environment variables; macOS 12.3.1. 

just clone https://github.com/mach-kernel/launchk and open it with vscode. and it generated target folder.

biggest file is target/debug/.fingerprint/xpc-sys-f8ce046781d6c49f/output-test-lib-xpc-sys, took about 9G+.

Part of the file content:

`
{"message":"reference to packed field is unaligned","code":{"code":"unaligned_references","explanation":null},"level":"warning","spans":[{"file_name":"/Users/xxx/rust/tool/launchk/target/debug/build/xpc-sys-afbed05153267f4c/out/bindings.rs","byte_start":203611,"byte_end":203677,"line_start":3,"line_end":3,"column_start":203565,"column_end":203631,"is_primary":true,"text":[{"text":"# [repr (C)] # [derive (Copy , Clone , Debug , Default , Eq , Hash , Ord , PartialEq , PartialOrd)] pub struct __BindgenBitfieldUnit < Storage , Align > { storage : Storage , align : [Align ; 0] , } impl < Storage , Align > __BindgenBitfieldUnit < Storage , Align > { # [inline] pub const fn new (storage : Storage) -> Self { Self { storage , align : [] } } }
`

cargo build and cargo check did not generate big the file.

**Comment by flodiebold** [comment]
rust-analyzer does not save anything to disk by itself; these files come from Cargo. It runs `cargo check --all-targets` by default though, so that's probably the difference.

**Comment by optionals** [comment]
> rust-analyzer does not save anything to disk by itself; these files come from Cargo. It runs `cargo check --all-targets` by default though, so that's probably the difference.

thx, I tried cargo check --all-targets and confirm that is the difference.
maybe cargo check --all-targets shoud be included in the template.

**Comment by lnicola** [comment]
>  maybe cargo check --all-targets shoud be included in the template.

Which template?

**Comment by optionals** [comment]
bug issue template.


> > maybe cargo check --all-targets shoud be included in the template.
> 
> Which template?
