### ISSUE TITLE
Where does rust-analyzers gets its colors from?

### ISSUE THREAD

**Issue by Raj2032** [rust-lang/rust-analyzer#12162]
This is my code
![image](https://user-images.githubusercontent.com/29293830/166921583-288fecf6-c642-40ed-b4a9-d6b32a8ba07a.png)

If I have this setting:

```json
    "[rust]": {
        "editor.semanticHighlighting.enabled": false,
        },
```

And in the theme I use this setting:

```json
          "scope":[
             "source",
             "support",
             "constant.character.entity.named",
             "meta.jsx.children",
             "source.lua",
             "text.html.derivative"
          ],
          "settings":{
             "foreground":"#5c86f9ff"
          }
```

As you can see in the image it is deep blue color the word `iced`, but if I enable the setting:

```json
    "[rust]": {
        "editor.semanticHighlighting.enabled": true,
        },
```

Then all of a sudden it becomes a lighter blue the word `iced`.

![image](https://user-images.githubusercontent.com/29293830/166921843-86a43e7d-b1b9-41c3-8851-e356b72f5279.png)

My question is where does the `rust-analyzer` get its colors from the theme? Where does it get that light blue color from, like from which field?

**Comment by Veykril** [comment]
If the theme specifies semantic token colors, that's what are being used. So if the theme has a color for the semantic token type `namespace` it will use that. If it doesn't VSCode will do a fallback mapping which is in part specified by us here https://github.com/rust-lang/rust-analyzer/blob/4b1eb98817ba671f3dd7555dc812dddcc9c8f311/editors/code/package.json#L1354-L1416 and in part by default by vscode https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#predefined-textmate-scope-mappings

So as can bee seen in the default vscode mapping, there is a mapping between `namespace` <-> `entity.name.namespace`, so things that are tagged with the semantic token type `namespace` will apply the `entity.name.namespace` textmate color if it exists.

**Comment by Raj2032** [comment]
@Veykril Thanks mate
