### ISSUE TITLE
What extension should I use?

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/rust-analyzer#12163]
I'm new to Rust.

Should I use this extension or https://marketplace.visualstudio.com/items?itemName=rust-lang.rust for my VS Code?

**Comment by bjorn3** [comment]
RLS which the rust-lang.rust extension uses is being deprecated in favor of rust-analyzer. See [RFC 2912](https://rust-lang.github.io/rfcs/2912-rust-analyzer.html) and https://blog.rust-lang.org/2022/02/21/rust-analyzer-joins-rust-org.html for more information.

**Comment by lnicola** [comment]
https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer

**Comment by frederikhors** [comment]
Can we write this line in Readme.md for future people, please?

An I think on `rust-lang.rust`'s Readme.md too.

**Comment by Veykril** [comment]
I'm hoping to get the move going this month :) (waiting for next week to merge my config PR and for the rust-lang publisher to get verified)
