### ISSUE TITLE
No hover over hints, Go to definition does not work!

### ISSUE THREAD

**Issue by AuroraLantean** [rust-lang/rust-analyzer#12172]
I don't know what happened but 
now after code checking is completed, 
there is no inline types, no hover-over hints(showing only "Loading...")
Go to definition does not work!

**rust-analyzer**: stable release v0.2.1040 and pre-release v0.3.1043

**VS Code**: 1.67.0

**rustc version**: rustc 1.59.0 (9d1b2106e 2022-02-23)

**relevant settings in vscode settings.json**:
  "rust-analyzer.trace.extension": true,
  "rust-analyzer.procMacro.enable": true,
  "rust-analyzer.inlayHints.parameterHints": true,

**Comment by lnicola** [comment]
I suggest disabling `rust-analyzer.trace.extension`, it will massively slow down Code. The other two are already default, so there's no need to set them.

Do you have any errors in Output / Rust Analyzer Language Server?

**Comment by AuroraLantean** [comment]
Ok I have removed all three rust-analyzer settings in vscode settings.json
after reloading the VS Code, there is no error from the Rust Analyzer. RA only gives me some warning about my code. That is all. And the problems remain. please advise. Thanks

**Comment by lnicola** [comment]
Is your project public? Does it still happen in an empty project?

**Comment by lnicola** [comment]
But yeah, hovering over hints isn't working yet: https://github.com/rust-lang/rust-analyzer/issues/11701.

**Comment by AuroraLantean** [comment]
What do you mean by empty project?
My project is not public, but this one below is similar to my project:
Polkadot substrate-parachain-template at https://github.com/substrate-developer-hub/substrate-parachain-template
then checkout polkadot-v0.9.18 tag
After Rust AnalyzerA(cargo check) checking the code in that public repo above... it takes 20 mins to 1 hour time,
then it keeps spinning in the VS Code without stopping!!!??? It seems to be stuck in a loop.
I see no inline types, no hover-over hints(showing only "Loading...")
Go to definition does not work! Please help!

**Comment by lnicola** [comment]
> What do you mean by empty project?

The output of `cargo new foo` or whatever else Rust project you want (like https://github.com/rust-lang/rust-analyzer itself).

>  After Rust Analyzer(cargo check) checking the code in that public repo above... it takes 20 mins to 1 hour time,
> I just disabled RA, shut down VSCode, started it again, then enable RA. RA completed checking the code with no more icon spinning.

It's can be disabled, but we run `cargo check --all-targets` on project load. I just tried to run that on `substrate-parachain-template` and it took 2m 35s on my 5950X.

From what I remember, the Polkadot ecosystem tends to use build scripts in creative ways, which aren't always helpful when you want fast builds. But after loading the project, features more or less work:

![image](https://user-images.githubusercontent.com/308347/167123786-74c5664f-5076-41c5-a56e-b47d1aa7cc30.png)

![image](https://user-images.githubusercontent.com/308347/167123864-c786bfcf-7a39-4928-9e97-433bf20da8f9.png)

**Comment by AuroraLantean** [comment]
@lnicola thank you for your quick reply. After installing rust-analyzer pre-release v0.3.1047, type hints worked, hover over hints worked. when I pressed control key when my mouse cursor was over a function, the underscore appeared. Then when I mouse clicked on it, the Go To Definition was stuck/not working...  and after that, the hover over hints did not work anymore... my computer is a little old... This is very weird... What do you suggest? Overriding Polkadot's build scripts ? Thanks

**Comment by lnicola** [comment]
Does that happen in `substrate-parachain-template`? If so, where? Some places will not work, either because we can't figure out a type, or because we don't support the syntax yet (like the red `T::DbWeight` in my screenshot above).

You can also keep looking for errors in the `Rust Analyzer Language Server` output channel.

> Overriding Polkadot's build scripts ?

That might speed things up, but will probably break some features.

**Comment by AuroraLantean** [comment]
@lnicola yes, I was in ```substrate-parachain-template```, 
```
pub fn do_something()...
			let who = ensure_signed(origin)?;
```
The hover over hint worked when my cursor was above ```ensure_signed()```,
Inside that hover over hint, there were two links: ```Result``` and something else...
when I clicked on the Result link, another rust file opened up.
when I clicked on the other link, it got stuck, and after that, the hover over hints did not work anymore... 
There was no error anywhere I looked. nothing in ```PROBLEM, OUTPUT, or DEBUG CONSOLE``` in the VSCode
Any idea? Thanks

**Comment by lnicola** [comment]
Yeah, that works for me and goes to `~/.cargo/git/checkouts/substrate-7e08433d4c370a21/fc3fd07/primitives/runtime/src/traits.rs:175:12`.

The problem with `rust-analyzer.trace.extension` is that it logs everything, including the semantic token info, and massively slows down Code. That's why I suggested disabling it right from the start.
