### ISSUE TITLE
rust-analyzer.toggleInlayHints command does not work in vscode 1.67

### ISSUE THREAD

**Issue by ivan** [rust-lang/rust-analyzer#12183]
**rust-analyzer version**: 02994dd63 2022-05-06 dev

**rustc version**: rustc 1.62.0-nightly (4c60a0ea5 2022-05-04)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

The `rust-analyzer.toggleInlayHints` command toggles the `editor.inlayHints.enabled` setting between `true` and `false`, but vscode 1.67 does not accept these values; it requires `"on"` or `"off"`. That is, for vscode 1.67, it should do this instead:

```diff
-        const value = !config.get("enabled");
+        const value = config.get("enabled") === "on" ? "off" : "on";
```

(vscode 1.67 also has [`"offUnlessPressed"` and `"onUnlessPressed"`](https://code.visualstudio.com/updates/v1_67#_toggle-inlay-hints), which may appear to obsolete `rust-analyzer.toggleInlayHints`, but actually its own thing is not very good yet because it requires holding down the Ctrl + Alt keys (no toggle), the keys do not appear to be configurable, and they do not work reliably because Alt can take focus to the menu.)

**Comment by ivan** [comment]
Sorry, I'm not sure why I observed that `true` and `false` were not working, but it seems fine now.

**Comment by JensMertelmeyer** [comment]
Hi there.
It seems to work, but that does not change that `true` and `false` are not valid, and VS Code also complains about a boolean not being allowed here. 

I think your issue should not be closed.

**Comment by Veykril** [comment]
Those configs are VSCode's, so this isuee does not lie with us. They replaced the booleans with strings (though the booleans are still accepted I believe even though they error)

**Comment by JensMertelmeyer** [comment]
I am not sure I understand. Of course the config "belongs" to VS code, but the action that modifies the config is `rust-analyzer.toggleInlayHints`

**Comment by Veykril** [comment]
Oh I'm sorry, I misunderstood. Ye then this is a problem on our side. Note that boolean values still work, though they are linted as an error. We are probably enclined to remove the command alltogether though as the new options in VSCode make it kind of obsolete (since it now allows you toggle them via the client).

**Comment by JensMertelmeyer** [comment]
No, please keep it! I don't think it's obsolete 🙃

VS Code only offers an option to hold down two keys to temporarily toggle it. Rust-Analyzer's way of "invoke Action" -> "toggle visibility" is much more comfortable. My poor weak hands get weary from constantly holding down keys on my keyboard. A simple toggle on/off action is much better, once you have hooked it up to a key combination of your choice.
