### ISSUE TITLE
Cursor too narrow with inlay hints in vscodevim normal mode

### ISSUE THREAD

**Issue by corneliusroemer** [rust-lang/rust-analyzer#12180]
I switched on inlay hints after reading about them in the VS code Rust extension docs.

I tried editing around inlay hints, but I got confused about the cursor position.

I use the vim extension.

When I'm in normal mode, the cursor is at the beginning of the type hint only. Importantly, cursor is _not_ blinking on the actual code. The blinking cursor should cover the entire hint, especially including the code character.

See this image as example:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/25161793/167180379-0ab3a735-a732-4e30-a153-72f063359f0e.png">

In actual fact, for editing sake, the cursor is behaving as if it is on the whitespace following the type hint.

It would be clearer where the cursor really is if the whole type hint plus the character following was blinking. Not just an imaginary character at the beginning of the type hint.

Maybe this issue is best addressed to the `vscodevim` or `vscode` repo, but I noticed it in the rust-analyzer repo so wanted to try here first.

**rust-analyzer version**: rust-analyzer version: 5dce1ff02 2022-05-02 stable

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: Using Vim extension (vscodevim) v1.22.2 and having inlay hints switched on

**Comment by lnicola** [comment]
This is how VS Code renders them, we can't do anything about it.

**Comment by flodiebold** [comment]
Let's close this, I'm guessing it should probably be reported to vscodevim.
