### ISSUE TITLE
Disable backtrace when running tests

### ISSUE THREAD

**Issue by jmevel** [rust-lang/rust-analyzer#12191]
Hello,

It seems when using the `Run Tests` or `Run Test` buttons in the text editor, tests are executed with a default `RUST_BACKTRACE=1` resulting in extra information being displayed in the output when encountering an error.

<img width="281" alt="image" src="https://user-images.githubusercontent.com/2572775/167287897-a13c3747-adf6-46a9-a1a9-808488f76ba8.png">

I'd like to completely disable it when running multiple or a single test, as for me all the backtrace information coming from the Rust core is just useless at this point.

Note that I have no `RUST_BACKTRACE` environment variable defined on my machine and running tests from the command line using `cargo test` works as I'm expecting (without the backtrace).

I've looked into the extension's settings but could find no related settings.

Thanks for your answers

**Comment by bjorn3** [comment]
This is probably https://github.com/rust-lang/rust-analyzer/blob/1894473b1973b366ee8d0cfa2c2a4459b1709b9c/crates/rust-analyzer/src/bin/main.rs#L113 which is meant to apply to rust-analyzer itself but gets inherited by child processes too. Try setting `RUST_BACKTRACE` to 0 using the `rust-analyzer.runnableEnv` config.

**Comment by jmevel** [comment]
Thanks for your answer.

I've tried setting it to *empty* since unsetting the `RUST_BACKTRACE` environment variable completely is the official way to deactivate the backtrace but that didn't work.

Your solution is actually working

```json
"rust-analyzer.runnableEnv": {
    "RUST_BACKTRACE": "0"
}
```

Thanks again !

**Comment by andrey-shigantsov** [comment]
Not working for me.

I set it in user & workspace settings of VSCode
```
"rust-analyzer.runnables.extraEnv": {
    "RUST_BACKTRACE": 0,
},
```
