### ISSUE TITLE
Filter and/or de-prioritize trait names in expression context completion

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#12196]
See https://github.com/rust-lang/rust-analyzer/pull/12123#issuecomment-1120659276.

**Comment by Veykril** [comment]
*Only for traits that don't have assoc items though.

**Comment by lnicola** [comment]
It might still make sense to move down traits without associated constants, since it's not that common to invoke methods like that.

**Comment by Veykril** [comment]
I wouldn't be so sure about that, `Default::default()` is very common, `From::from`/`Into::into` also sees some use

**Comment by flodiebold** [comment]
I wonder, it might be nice to automatically complete `Default::default()` etc. for traits like this? I.e. have a completion for the full method call?

**Comment by flodiebold** [comment]
Or maybe we should just complete `Default::$0` instead of `Default` -- that would apply to all traits :thinking:

**Comment by Veykril** [comment]
Ye I think those are some good ideas 👍

**Comment by lnicola** [comment]
Mostly fixed.
