### ISSUE TITLE
Jumping to method with tracing::instrument macro fails

### ISSUE THREAD

**Issue by gcohara** [rust-lang/rust-analyzer#12206]
With the following example

```
use tracing;

fn main() {
    println!("Hello, world!");
    Foo::bar()
}

struct Foo {}

impl Foo {
    #[tracing::instrument]
    fn bar() {}
}
```

attempting to jump to the definition of `bar` using `M-.` in Emacs fails with `No definitions found for: bar`.

However, with the attribute macro removed:
```
use tracing;

fn main() {
    println!("Hello, world!");
    Foo::bar()
}

struct Foo {}

impl Foo {
    fn bar() {}
}
```

this jumps successfully to `bar`.

**rust-analyzer version**: 2022-05-02, installed via HomeBrew

**rustc version**: 1.58.1

Please let me know if any further information would be useful for debugging.

**Comment by lnicola** [comment]
You might have to restart RA/LSP/emacs.

**Comment by flodiebold** [comment]
If it was just a matter of proc macro expansion being disabled, go to definition would still work, wouldn't it? It might be the expansion failing instead for some reason? :thinking:

**Comment by gcohara** [comment]
Restarted Emacs and RA with `lsp-rust-analyzer-experimental-proc-attr-macros` set to `t` but still no luck

**Comment by Veykril** [comment]
Can't repro this either in my VSCode. I assume you are using the latest `tracing` version? As flodiebold said, a disabled expansion shouldn't cause that. So the expansion is most likely failing in some way. Are there any errors in your logs?

**Comment by gcohara** [comment]
It turns out that `lsp-rust-analyzer-proc-macro-enable` was set to `nil`. Setting it to `t` solved it!

Apologies for wasting your time, and many thanks to all of you for being so helpful.
