### ISSUE TITLE
Confused syntax parsing

### ISSUE THREAD

**Issue by Barugon** [rust-lang/rust-analyzer#12217]
**rust-analyzer version**: v0.2.1048 and v0.3.1050

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: defaults

Please see the screenshot below. Syntax parsing seems to get very confused in [this project](https://github.com/Barugon/cota). I suspect that it may be something in the `#[export]` procedural macro that is causing the issue.

![Screenshot from 2022-05-11 16-49-29](https://user-images.githubusercontent.com/16503728/167965894-84b307d6-125e-45ed-a393-04d4e50aaecf.png)

**Comment by lnicola** [comment]
Macro comes from https://github.com/godot-rust/godot-rust/tree/master/impl/proc-macros/src.

It's possible that the macro produces wrong spans for those tokens, we've had issues with other crates before.

You might be able to use `rust-analyzer.procMacro.ignored` as a workaround.

**Comment by Barugon** [comment]
> You might be able to use `rust-analyzer.procMacro.ignored` as a workaround.

Thanks, I'll give that a try.

**Comment by Barugon** [comment]
Adding this to my settings seems to have cleared it up:
```
  "rust-analyzer.procMacro.ignored": {
    "gdnative": [
      "export"
    ]
  },
```

**Comment by jonas-schievink** [comment]
The PR causing this was reverted.

**Comment by Barugon** [comment]
> The PR causing this was reverted.

Thanks. Seems to be working well now.
