### ISSUE TITLE
I saw this error in a minimal project that didn't have a `rustfmt.toml`. I was able to make the errors go away by creating a `rustfmt.toml` and adding an `edition = "2018"` to it.

### ISSUE THREAD

**Issue by amab8901** [rust-lang/rust-analyzer#12232]
I saw this error in a minimal project that didn't have a `rustfmt.toml`. I was able to make the errors go away by creating a `rustfmt.toml` and adding an `edition = "2018"` to it.

_Originally posted by @davidbarsky in https://github.com/rust-lang/rust-analyzer/issues/1959#issuecomment-560549319_

**Comment by amab8901** [comment]
it doesn't work for me. I'm still having the error

**Comment by davidbarsky** [comment]
I can't close this issue, but @bjorn3's suggestion in https://github.com/rust-lang/rust-analyzer/issues/12233#issuecomment-1125302733 is correct. You are on the 2015 edition, not the 2021 edition. The error message you pasted there says:

```
  = help: set `edition = "2021"` in `Cargo.toml`
```

**Comment by flodiebold** [comment]
Duplicate of #12233.
