### ISSUE TITLE
Disabling inlay hints for variables no longer possible (`"rust-analyzer.inlayHints.typeHints.enable": false` does not hide inlay hints for variables)

### ISSUE THREAD

**Issue by KSXGitHub** [rust-lang/rust-analyzer#12240]
**rust-analyzer version**: 2022-05-09

**rustc version**: 1.58.1

**relevant settings**: 

```jsonc
// settings.json
{
  "rust-analyzer.inlayHints.parameterHints.enable": false,
  "rust-analyzer.inlayHints.typeHints.enable": false,
}
```

**Comment by bjorn3** [comment]
The configs got renamed to `rust-analyzer.inlayHints.parameterHints` and `rust-analyzer.inlayHints.typeHints` recently.

**Comment by KSXGitHub** [comment]
Then you guys should update the settings UI. Because it still uses `rust-analyzer.inlayHints.typeHints.enable`.

**Comment by KSXGitHub** [comment]
Anyway, removing `.enable` certainly works. However, the editor marks these settings as Unknown:
![valid config is being marked as unknown](https://user-images.githubusercontent.com/11488886/168288854-a6146027-b9c0-4274-81be-0095bc54a697.png)

The settings UI does not control these either.

**Comment by Veykril** [comment]
That sounds like your server binary and vscode client do not match up.

**Comment by KSXGitHub** [comment]
> That sounds like your server binary and vscode client do not match up.

The binary version is 2022-05-09, and the extension is latest from the VS Code Marketplace.

**Comment by lnicola** [comment]
You should use the built-in server, unless you have a really good reason to use another one.

**Comment by KSXGitHub** [comment]
> You should use the built-in server, unless you have a really good reason to use another one.

I have just disabled `rust-analyzer.server.path`. The version is now `94fa8a653 2022-05-12 nightly`. These keys are still marked as Unknown. Reloading the editor would automatically rename them back to `.enable`.

**Comment by Veykril** [comment]
`.enable` are the correct ones

**Comment by KSXGitHub** [comment]
OK. I'll close this issue now.
