### ISSUE TITLE
Doc links in BuiltinType are broken beacuse not being able to get doc base url

### ISSUE THREAD

**Issue by rainy-me** [rust-lang/rust-analyzer#12250]
**rust-analyzer version**: `rust-analyzer version: 5d5bbec9b 2022-05-09 stable`
**rustc version**: `rustc 1.62.0-nightly (f1f721e64 2022-05-13)`

![image](https://user-images.githubusercontent.com/26110087/168413920-268a1492-beef-44aa-8a53-2e19df5029d5.png)
![image](https://user-images.githubusercontent.com/26110087/168413924-14586651-3ff2-491a-8983-cbe3fed8a75c.png)

The cause of this issue is [`rewrite_url_link`](https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide/src/doc_links.rs#L56) calls `crate_of_def` which [returns `None` if `def` is `BuiltinType`](https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide/src/doc_links.rs#L352-L356) and [makes `crate_of_def` early return](https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide/src/doc_links.rs#L338)). 

I think one possible solution is to pass `famous_defs` from https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide/src/hover.rs#L172-L175 down to `crate_of_def` to resolve BuiltinType to std crate via `famous_defs.std()?`.

Another solution is, since we already found the doc via [`find_std_module`](https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide/src/hover/render.rs#L453), It should be possible to not only return the markup but also the doc owner from `render::definition` than pass it to `render::process_markup` https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide/src/hover.rs#L176-L178 . This approch feels more natural to me but requires much more refactoring existing code.

**Comment by Veykril** [comment]
Looking at this, since `rewrite_url_link` only needs the crate to determine the doc base url, I think we can get by without having to do either of your two options. We can just check if the definition is a builtin type and if it is default the base doc url to `std` (or `core` technically).

**Comment by rainy-me** [comment]
Yes of course special-casing builtin type can fix this with minor impact. As you described, I created https://github.com/rust-lang/rust-analyzer/pull/12346 .
