### ISSUE TITLE
"Generate `Deref` impl" should abbreviate `std::ops::Deref` if already in scope

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#12265]
```rust
use std::ops::Deref;

struct S {
    target$0: u8,
}
```

Applying the "Generate `Deref` impl using `target`" assist generates this:

```rust
impl std::ops::Deref for S {
    type Target = u8;

    fn deref(&self) -> &Self::Target {
        &self.target
    }
}
```

The `std::ops::Deref` is unnecessarily qualified here, just `Deref` would be enough. We have code that can automatically do this, should just be a matter of calling that.

**Comment by jhgg** [comment]
What's the code? Happy to make this fix!

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/blob/master/crates/hir/src/lib.rs#L569-L585
Should be what you need here (you'll first want to fetch `Deref` via `FamousDefs`, then fetch a path via one of those)
