### ISSUE TITLE
Extra space before lifetime apostrophe in macro expansion

### ISSUE THREAD

**Issue by tamaroning** [rust-lang/rust-analyzer#12260]
I try this code:
```rust
use std::marker::PhantomData;

struct Context<'cx> {
    phantom: PhantomData<&'cx ()>
}

macro_rules! trait_a {
    () => {
        trait A<'cx> {
            fn foo(&mut self, cx: &Context<'cx>);
        }       
    };
}

trait_a!();

struct S;

impl<'cx> A<'cx> for S {
    // Cursor is here
}
```
Rust analyzer completes the code as follow:
```rust
    fn foo(&mutself, cx: &Context< 'cx>) {
        
    }
```
I expected a completion like:
```rust
    fn foo(&mut self, cx: &Context<'cx>) {
        
    }
```

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: 5d5bbec9b 2022-05-09 stable

**rustc version**: (eg. output of `rustc -V`)
rustc 1.58.1 (db9d1b20b 2022-01-20)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
none

If this is not a complex issue, I would like to tackle with this.

**Comment by tamaroning** [comment]
@jhgg 
There is also a  needless whitespace prececding lifetime annotations.

**Comment by tamaroning** [comment]
@lnicola 
Is this unnecessary whitespace fixed in PR https://github.com/rust-lang/rust-analyzer/pull/12262 ?

**Comment by lnicola** [comment]
No, but we can't emit perfect code, and an extra space is harmless (it will get fixed on save/auto-format), as opposed to a missing one which causes rustfmt to fail.

**Comment by tamaroning** [comment]
@lnicola 
I understand. thank you.

**Comment by jhgg** [comment]
@lnicola did you mean to re open this?

**Comment by lnicola** [comment]
Yeah, and repurpose it for the space @tamaroning asked about. It might be an easy fix, we can close it if not.

**Comment by tamaroning** [comment]
@lnicola 
I found a invalid completion related to this issue.
Is it better to fix them in one PR?
Anyway I would like to fix an extra space before lifetime apostrophe.

```
use std::marker::PhantomData;

struct Context<'cx> {
    phantom: PhantomData<&'cx ()>
}

macro_rules! trait_a {
    () => {
        trait A<'cx, 'a> {
            fn foo(&mut self, cx: &'a Context<'cx>);
        }       
    };
}

trait_a!();

struct S;

impl<'cx, 'a> A<'cx, 'a> for S {
    // invalid completion
    fn foo(&mutself, cx: & 'aContext< 'cx>) {
        
    }
}
```

**Comment by edwin0cheng** [comment]
I just checked, #12990 fixed all the issues mentioned here. So we could close it.
