### ISSUE TITLE
"Generate `Deref` impl" should also offer generating a `DerefMut` impl

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#12266]
```rust
struct S {
    target$0: u8,
}
```

Here we're offering a "Generate `Deref` impl using `target`" assist. This currently only supports a `Deref` impl though, not a `DerefMut` impl that you might also want.

It should either open a popup where it asks the user (like the "generate getter/setter" assist), or an assist should be offered on the `Deref` impl to generate an identical (except with `&mut` instead of `&`) `DerefMut` impl.

**Comment by jhgg** [comment]
Yeah... I was going to do this but never got around to it lol...
