### ISSUE TITLE
RA doesn't autocomplete function parentheses

### ISSUE THREAD

**Issue by dzdrav** [rust-lang/rust-analyzer#12283]
Since the last update, when suggesting a function/method name, after confirming, RA autocompletes only the name: I have to write out the parentheses myself. Previously RA always completed the whole thing. 

For reference, I'm using VSCode with RA plugin. Also, looking at the RA [changelog](https://rust-analyzer.github.io/thisweek), no such change seems to have been introduced.

I tried setting (as per [this](https://github.com/rust-lang/rust-analyzer/issues/9577) issue)
```json
"rust-analyzer.completion.addCallParenthesis": true
```
which wasn't recognized as a valid setting, as well as 
```json
"rust-analyzer.completion.callable.snippets": `fill_arguments`/``add_parentheses`
```
but none of those changed this behaviour. 

New behaviour wasn't introduced by any configuration change by me. It started on its own since the update.

---

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
```
rust-analyzer version: 94fa8a653 2022-05-12 nightly
```
I'm not sure why it's showing nightly: in VSCode, I've got release channel installed. 

**rustc version**: (eg. output of `rustc -V`)
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
```

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
```json
"rust-analyzer.completion.callable.snippets": `fill_arguments`
```

## NOTE
Switching to pre-release **fixes the problem**: `rust-analyzer version: ce9b174f8 2022-05-17 nightly`, which confirms the regression is present in the current release version

**Comment by Veykril** [comment]
Ye the release version is currently bugged in that VSCode will fetch the old one (there has been a versioning problem), we are looking into fixing this but for the time being I recommend you to use the pre-release version.

**Comment by dzdrav** [comment]
Thanks for the quick response. I'm not using pre-release because format-on-save doesn't work there. 

Didn't consider it for a bug report since it's prerelease and hence less table, but you aren't aware of it, it might be worth reporting as an issue itself.

Also, after removing the extension (and reloading window), re-installing the extension (release) fails in the following way: 

Selecting `install` disappears the button for a moment, then it reappears along with `Reload required`, but the extension sin't installed. Sometimes 404 error may appear in the VSCode popup, but most of the times it doesn't. 

After that, trying to write in the editor results in `command 'rust-analyzer.onEnter' not found` (like [this](https://github.com/rust-lang/rust-analyzer/issues/3212))

Reloading, closing and re-opening VSCode doesn't fix the issue, only reinstalling VSCode. Then I can install via marketplace the release version and it actually gets installed. 

Installing pre-release works (but with the above issue). 

```
Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:39:22.915Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.13.0-41-generic snap
```

**Comment by Veykril** [comment]
`format-on-save` should be working in the prerelease version. Do you have the formatter set in your configuration explicitly? That might be the problem since we changed the publisher of the extension.

**Comment by dzdrav** [comment]
> Do you have the formatter set in your configuration explicitly

You are right, I had modified default formatter based on file type, and 

```json
"[rust]": {
    "editor.defaultFormatter": "matklad.rust-analyzer"
  },
```
wasn't valid anymore, had to change the value to `"rust-lang.rust-analyzer"`
