### ISSUE TITLE
Version output is inconsistent with other tools

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust-analyzer#12280]
This is minor, but I noticed the version output in `rust-analyzer-preview` builds from `rustup` is inconsistent with other tools:

```
$ rustc --version
rustc 1.63.0-nightly (42e1761c7 2022-05-15)
$ cargo --version
cargo 1.63.0-nightly (3f052d8ee 2022-05-12)
$ rust-analyzer --version
rust-analyzer 5d5bbec 2022-05-15 dev
```

* The overall format / field-order doesn't match.
* The commit hash is accurate to the submodule under rust, so that's fine.
* The date is the _build_ date, rather than the commit date. I included cargo above as an example where that's different, as the build is current but the submodule is not updated every day.
* The "dev" string looks like it comes from lack of `RUST_ANALYZER_CHANNEL` in the build script. It's not a big deal, except it also triggers `poke_rust_analyzer_developer`, which we probably don't want in official builds. Maybe rustbuild should set this to "preview" for now, and eventually follow rustc's own channel names.

This may be something to track in #4224.

**Comment by Veykril** [comment]
So to clarify, ideally for the rust-up component build we should provide the following format `rust-analyzer <toolchain-version>-<toolchain-channel> (<commit-hash> <commit-date>)`?

**Comment by lnicola** [comment]
We might as well use that format every time.

**Comment by cuviper** [comment]
Right, I'm suggesting to match the format, but also to make sure the channel is some kind of release, not one that "pokes".

**Comment by Veykril** [comment]
Yes not poking is definitely somethign we'd want. For our dev builds we don't want to show something like `1.63.0-nightly` anyways since these builds aren't really tied to a rust release, so for dev builds we can use some other string here to signal that.
