### ISSUE TITLE
Wrong error and warning underline positions on Windows

### ISSUE THREAD

**Issue by EFanZh** [rust-lang/rust-analyzer#12293]
**rust-analyzer version**: ce9b174f8 2022-05-17 nightly

**rustc version**: 1.60.0 (7737e0b5c 2022-04-04)

I got wrong warning and error underline positions with CRLF line ending source files on Windows:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/2160692/168830543-758467a6-4177-45a8-a5c9-a5ff29e560f7.png">

If I change file line ending to LF, then the underlines are shown at their correct positions:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/2160692/168831640-5472617a-4970-40c6-8eab-a2a9a39a677f.png">

**Comment by Antelope13** [comment]
I am seeing the same thing on Windows. Reverting to v0.3.1054 fixes the issue.

**Comment by griffi-gh** [comment]
same issue

**Comment by bjorn3** [comment]
Maybe caused by https://github.com/rust-lang/rust-analyzer/pull/12190?

**Comment by griffi-gh** [comment]
@bjorn3 Maybe but don't have any non-ascii characters in my code?

**Comment by griffi-gh** [comment]
oh

**Comment by mdegans** [comment]
> Rust-analyzer normalizes crlf into lf when loading source files as required by the rust grammar. I suspect https://github.com/rust-lang/rust-analyzer/pull/12190 didn't account for this

This sounds likely. If I change VsCode's line endings to LF in Windows the squigglies appear in the correct places now. For those stumbling across this, just search (f1) for `eol` , select `Change End of Line Sequence` then `LF`.

**Comment by RReverser** [comment]
Ohh so that's what it is. Glad to hear reverting to previous version helps - before seeing this issue I assumed some local cache was corrupted and tried all possible methods of clean rebuld / restart / etc.

**Comment by codecheck01** [comment]
> Ohh so that's what it is. Glad to hear reverting to previous version helps - before seeing this issue I assumed some local cache was corrupted and tried all possible methods of clean rebuld / restart / etc.
I was thinking the same, I just lost 30 mins of my life...

**Comment by codecheck01** [comment]
I had to revert to version 0.2.1048, this is really breaking my workflow.

**Comment by schungx** [comment]
> This sounds likely. If I change VsCode's line endings to LF in Windows the squigglies appear in the correct places now. For those stumbling across this, just search (f1) for `eol` , select `Change End of Line Sequence` then `LF`.

I believe there is an icon thingie in the status bar at the lower-right of the window.  You press that and it lets you decide what line ending you need for that file.
