### ISSUE TITLE
Solve type of `t.into()` as `U` when `T: Into<U>` is the only `Into` bound for `t: T`

### ISSUE THREAD

**Issue by p-avital** [rust-lang/rust-analyzer#12302]
Hi,

In `zenoh`'s source, a rather common pattern is the use of `fn function<I: Into<Input>>(input: I)` for functions that would typically take `Input`, to simplify user code.

I've noticed that despite `input.into()`'s type being unambiguous to rustc, rust-analyzer fails to resolve its type.

Is there a technical reason for this, or could it be that this just went unnoticed?

Thanks for all the good work :)

**Comment by jonas-schievink** [comment]
This is a known bug: https://github.com/rust-lang/rust-analyzer/issues/5514
