### ISSUE TITLE
go to definition don't work

### ISSUE THREAD

**Issue by caibirdme** [rust-lang/rust-analyzer#12306]
go to definition don't work

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
v0.3.1059

**rustc version**: (eg. output of `rustc -V`)
1.58.1

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
OS: ubuntu 20.0LTS in wsl2
cargo:1.58.0
RUSTUP_HOME & CARGO_HOME not set

others:
when I click rust-analyzer on the bottom of the editor, it shows:
```
Workspaces:
Loaded 792 packages across 1 workspace.

Analysis:
217mb of files
0b of index symbols (0)
10500 trees, 128 preserved
129499 trees, 128 preserved (Macros)
-183mb in total
```
why 0b of index symbols?

**Comment by flodiebold** [comment]
Can you provide more information? In what situation does it not work? Do other features work as expected?

**Comment by caibirdme** [comment]
> Can you provide more information? In what situation does it not work? Do other features work as expected?

Cannot reproduce after rebooting the machine... Closed
