### ISSUE TITLE
mismatched-arg-count lint on macro that impl same name methods

### ISSUE THREAD

**Issue by EluvK** [rust-lang/rust-analyzer#12308]
**rust-analyzer version**:
`rust-analyzer version: 7e95c14ea 2022-05-17 stable`

**rustc version**: 
`rustc 1.63.0-nightly (cd282d7f7 2022-05-18)`

**relevant settings**: 
`OS: Ubuntu 20.04.4 LTS`

I was learning `wasmer` by its [examples](https://github.com/wasmerio/wasmer/blob/master/examples/memory.rs) and came across this lint.
![image](https://user-images.githubusercontent.com/36977935/169263725-285f7374-e1aa-4987-82f3-e2c2552b2774.png)

The [origin macro](https://github.com/wasmerio/wasmer/blob/2.2.1/lib/api/src/sys/native.rs#L126) is complicated so I extract the code and write a simple case to reproduce it : 
``` Rust
#![allow(unused)]
use std::marker::PhantomData;

struct SomeFunc<Args = ()> {
    _phantom: PhantomData<Args>,
}

trait SomeTrait {}
impl SomeTrait for i32 {}
impl SomeTrait for f32 {}

impl<Args> SomeFunc<Args> {
    fn new() -> Self {
        Self {
            _phantom: PhantomData,
        }
    }
}

macro_rules! impl_call {
    (  $( $x:ident ),* ) => {
        #[allow(unused_parens, non_snake_case)]
        impl<$( $x , )*> SomeFunc<( $( $x ),* )>
        where
            $( $x: SomeTrait, )*
        {
            pub fn call(&self, $( $x: $x, )* ) {

            }
        }
    };
}

impl_call!(A1);
impl_call!(A1, A2);

fn main() {
    let f1 = SomeFunc::<i32>::new();
    f1.call(10);

    let f2 = SomeFunc::<(i32, f32)>::new();
    f2.call(10, 10.); // rust analyzer complains: expected 1 argument, found 2
}

```
`cargo run` works fine, but it seems rust-analyzer was confused at `f2.call(...)`.

By chance, I tried to switch the order of `impl_call!` macros into:
``` Rust
impl_call!(A1, A2);
impl_call!(A1);
```

And the lint was gone! it's works just fine.
![image](https://user-images.githubusercontent.com/36977935/169261899-cb5be9a2-ae10-4281-aea3-0abf0b712638.png)

I suppose it might be a 🐞

BTW, I had search the existing issue, this is the closest one #9887 . but I'm not sure if it is the same reason.

**Comment by flodiebold** [comment]
It's likely the same issue as #5441.

**Comment by bitgaoshu** [comment]
<img width="791" alt="截屏2022-05-23 10 14 45" src="https://user-images.githubusercontent.com/7943146/169730761-c13af6db-f816-44f6-b7cc-d9bfb10a78c6.png">

It seems confused between ParenthesizedType and one field Tuple
