### ISSUE TITLE
Cache LSP responses

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust-analyzer#12317]
I often hit an issue like this:
1. I hit "Find all references" on a type / function.
2. Rust-analyzer takes 3-10 seconds to find the references.
3. I get bored and click to another window.
4. Rust-analyzer finishes computing the references.
5. I click back to the window, which dismisses the popup tab.
6. I have to hit "Find all references" again, which takes just as long as the first time.

It would be great for it to be ~instantaneous the second time I recompute the references, since rust-analyzer already has the info available.

**Comment by kjeremy** [comment]
We should support LSP work done progress which would take care of this.

**Comment by lnicola** [comment]
The second run should be instant, AFAICT, since we do cache the intermediate results.

**Comment by jyn514** [comment]
> The second run should be instant, AFAICT, since we do cache the intermediate results.

That is not the behavior I'm seeing. I don't have an open source reproduction, but it takes just as long to run "Go to References" on my struct the second time as it does the first.

**Comment by jyn514** [comment]
I do see this logging in the error console if it matters:
```
[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to run build scripts

error: could not compile `my_crate` due to 2 previous errors
```
Doesn't say what the errors are.

**Comment by lnicola** [comment]
Does `cargo check --all-targets` work?

**Comment by jyn514** [comment]
ah, I added a line of code that didn't compile by accident. I fixed it and I still see the performance issue, as well as the errors in the vscode output tab.

**Comment by lnicola** [comment]
Which errors?

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust-analyzer/issues/12317#issuecomment-1132175640

**Comment by jyn514** [comment]
The fix was to set `rust-analyzer.lru.capacity` to 1024 (up from the default of 128).
