### ISSUE TITLE
destruct struct as the left-hand side of an assignment

### ISSUE THREAD

**Issue by Debonex** [rust-lang/rust-analyzer#12322]
I noticed that we can destruct struct as the left-hand side of an assignment since rust  version 1.59.0. 
https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html
According to that, I wrote a simple demo, but something wrong happened.
![unknown](https://user-images.githubusercontent.com/37174444/169496709-d30750d5-e7df-4613-ab5c-ed0327cfdd20.png)

![unknown2](https://user-images.githubusercontent.com/37174444/169496774-577a56af-7178-47ac-bd85-f237504e1cec.png)

<hr/>

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: 7e95c14ea 2022-05-17 stable
**rustc version**: (eg. output of `rustc -V`)
rustc 1.61.0 (fe5b13d68 2022-05-18)
**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

**Comment by Debonex** [comment]
I've tried rust-analyzer pre-release version and `cargo check` and `cargo test` work with out problem.

**Comment by ruabmbua** [comment]
Seems like the issue starts at parsing.

The RHS of the statement is parsed as a `RecordExpr`, but it should be a `RecordPat`.

**Comment by Veykril** [comment]
No that is correct, destructuring assignments have an expression as the LHS. It's just a subset of expressions that are allowed there.
