### ISSUE TITLE
Closures without block bodies missing return type hint

### ISSUE THREAD

**Issue by NotWearingPants** [rust-lang/rust-analyzer#12321]
With closure return types inlay hints enabled, closures without block bodies don't have a return type hint:

![image](https://user-images.githubusercontent.com/26556598/169421392-533b697c-b06a-43fa-b53a-7268b7bcbb77.png)

Like the original feature request (#11386) said, this should probably be configurable as well, because the hint can look weird without a brace between it and the body (we can add braces along with the hint, but that would be too verbose).

I propose making the setting `closureReturnTypeHints` an enum with `Off`, `OnlyBlock`, `On` (by default `Off` like the current default).

---

**rust-analyzer version**: rust-analyzer version: 7e95c14ea 2022-05-17 stable

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: `"rust-analyzer.inlayHints.closureReturnTypeHints.enable": true`

**Comment by Veykril** [comment]
Ye I think a setting here seems good 👍
