### ISSUE TITLE
Tuple parameters are {unknown}

### ISSUE THREAD

**Issue by Barugon** [rust-lang/rust-analyzer#12331]
**rust-analyzer version**: rust-analyzer version: 7e95c14ea 2022-05-17 stable

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: none

Rust Analyzer gets confused about the tuple parameters in the following code (the logic here is dumb but it's simply to illustrate):

```Rust
fn main() {
    let mut item = None;
    loop {
        if let Some((id, _, _)) = item {
            if id == 1 {
                break;
            }
        }

        item = Some((1, 2.5, String::new()));
    }
}
```

The result is this:

![Screenshot from 2022-05-20 09-19-29](https://user-images.githubusercontent.com/16503728/169570574-ca368cab-7389-41bb-9d5c-1f9da6716f35.png)

**Comment by ruabmbua** [comment]
So somehow the `_` in a pattern matching stops the inference from working on that particular part of the type.

**Comment by Barugon** [comment]
> So it has nothing to do with the loop, its just about a pattern match appearing **before** the first (fully type-resolvable) assignment. It only happens, when tuples are involved (according to my few tests), and when the pattern matching uses the `_` placeholder anywhere. If the pattern matching actually binds the value to an identifier like `_a` there is no problem.

Right. If do this then it works.

```Rust
fn main() {
    let mut item = None;
    loop {
        item = Some((1, 2.5, String::new()));

        if let Some((id, _, _)) = item {
            if id == 1 {
                break;
            }
        }
    }
}
```

**Comment by flodiebold** [comment]
Good catch. I suspect changing
https://github.com/rust-lang/rust-analyzer/blob/84be2eaf99c1c057b401f755f92d22d5896900f2/crates/hir-ty/src/infer/pat.rs#L145
to use `repeat_with(|| self.table.new_type_var())` might be the fix, but I don't have time to test it right now.

**Comment by ruabmbua** [comment]
Tested again the original mentioned code, fixed by https://github.com/rust-lang/rust-analyzer/pull/12355
