### ISSUE TITLE
"rust-analyzer: join lines" no longer works

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust-analyzer#12338]
Noticed that it does nothing since several releases ago, without any panics in the logs. Haven't investigated this yet. Curisous if this reproduces for other VS Code users?

**Comment by Veykril** [comment]
Doesn't seem to work for me either.

**Comment by flodiebold** [comment]
Probably unsurprisingly, it still works in Emacs.

**Comment by Veykril** [comment]
Ye I think its this part here https://github.com/rust-lang/rust-analyzer/blob/01d412f4d7bd7ef21a7e8f0461e9ba3439e3c4bf/editors/code/src/commands.ts#L128-L132, https://github.com/rust-lang/rust-analyzer/commit/bfa2a08da1fb7704cd95eec7111977d5d8f60ddc changed this to an async callback but I don't think that works here

**Comment by lnicola** [comment]
Oof, I think it didn't compile otherwise.

**Comment by lnicola** [comment]
This works:

```diff
diff --git i/editors/code/src/commands.ts w/editors/code/src/commands.ts
index ee8fa2eb5..e50edf776 100644
--- i/editors/code/src/commands.ts
+++ w/editors/code/src/commands.ts
@@ -125,8 +125,9 @@ export function joinLines(ctx: Ctx): Cmd {
                 editor.document
             ),
         });
+        const textEdits = await client.protocol2CodeConverter.asTextEdits(items);
         await editor.edit(async (builder) => {
-            (await client.protocol2CodeConverter.asTextEdits(items)).forEach((edit: any) => {
+            textEdits.forEach((edit: any) => {
                 builder.replace(edit.range, edit.newText);
             });
         });
```
