### ISSUE TITLE
rust-analyzer opens a windows conhost window while running and another for every cargo command it runs 

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust-analyzer#12352]
**rust-analyzer version**: 2022-05-17

**rustc version**: 1.61.0

I am using vim, other LSP servers work fine.

**Comment by jonas-schievink** [comment]
We don't open any windows by ourselves, so I think this is an issue with your setup. rust-analyzer and Cargo do target the console subsystem on Windows, since they're command-line applications, so that might be why Windows opens a console window.
