### ISSUE TITLE
Linux x86_64 pre-release build

### ISSUE THREAD

**Issue by Barugon** [rust-lang/rust-analyzer#12369]
**rust-analyzer version**: v0.4.1067

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: none

Pre-release version of rust-analyzer is no longer available?

![Screenshot from 2022-05-23 15-55-37](https://user-images.githubusercontent.com/16503728/169917840-ad354101-06c8-4fa8-858a-ae0b517bcc9e.png)

**Comment by dacite** [comment]
See [here](https://github.com/rust-lang/rust-analyzer/issues/12367#issuecomment-1135191173). Latest pre-release build (v0.4.1068) fixed this for me as mentioned there
