### ISSUE TITLE
Nested `macro_rules` with `$$` fails to expand

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust-analyzer#12364]
**rust-analyzer version**:  Current HEAD (7be85a5b4)

**rustc version**: `rustc 1.61.0 (fe5b13d68 2022-05-18)` and `rustc 1.63.0-nightly (b2eed72a6 2022-05-22)`

Rust Analyzer fails to expand the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0c8f04d03c12018a1683a4ca4cd124aa)):

```rust
#![feature(macro_metavar_expr)]

macro_rules! outer {
    ($outer_name:ident) => {
        macro_rules! inner {
            ($$inner_name:ident) => {
                impl $outer_name {
                    fn $$inner_name() {}
                }
            };
        }
    };
}

struct Hello;

outer!(Hello);
inner!(world);
```

Replacing the `$$` with singular `$`s fixes the issues (though note that there are macros where the `$$` is necessary). `$$` is close to being stabilized: https://github.com/rust-lang/rust/pull/95860

I've added a test case in https://github.com/TimNN/rust-analyzer/commit/856d689348492c0cccfa36758e8f7d0372f5df3b, which produces the following results:

```plain
$ cargo test -p hir-def nested_double_dollar
    Finished test [unoptimized] target(s) in 0.09s
     Running unittests src/lib.rs (target/debug/deps/hir_def-96fd50c42b79c470)

running 1 test
test macro_expansion_tests::mbe::nested_double_dollar ... FAILED

failures:

---- macro_expansion_tests::mbe::nested_double_dollar stdout ----
thread 'macro_expansion_tests::mbe::nested_double_dollar' panicked at 'called `Result::unwrap()` on an `Err` value: UnresolvedMacro { path: ModPath { kind: Plain, segments: [Name(Text("inner"))] } }', crates/hir-def/src/macro_expansion_tests/mbe.rs:1550:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    macro_expansion_tests::mbe::nested_double_dollar

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 331 filtered out; finished in 0.00s
```

Again, replacing the `$$` with `$` makes the test pass.

**Comment by Veykril** [comment]
We don't support `macro_metvar_expr` yet, https://github.com/rust-lang/rust-analyzer/issues/11952

**Comment by TimNN** [comment]
Ah, thanks for linking the issue! (Didn’t find anything when I was searching for something like “nested macros”, IIRC).
