### ISSUE TITLE
incorrect token mapping in `tokio::test`

### ISSUE THREAD

**Issue by jhgg** [rust-lang/rust-analyzer#12362]
Consider the following code, using `tokio = { version = "1", features = ["full"] }` in `Cargo.toml`

```rust
#[tokio::test]
async fn some_test() {
    let x = 1;
}
```

Here, `let` is has semantic highlighting for `method.library.static`:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/5489149/169893286-fb7ac23e-3c50-4211-a6d0-ecbbbe9da691.png">

Here is the expansion of the macro:

```rust
// Recursive expansion of test! macro
// ===================================

#[::core::prelude::v1::test]
fn some_test() {
    let body = async {
        let x = 1;
    };
    #[allow(clippy::expect_used)]
    tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("Failed building the Runtime")
        .block_on(body);
}
```

When trying to use "go to definition" on `let`, it would appear to map to `new_current_thread`. 

Rust 1.60, and rust-analyzer version: 7be85a5b4 2022-05-23 dev

**Comment by Veykril** [comment]
tokio is re-using the span of the last statement of the block for the runtime builder constructing function. For some reason we are picking that first though.

**Comment by jplatte** [comment]
Anything that one could do to help with this? It's something I stumble on quite frequently (makes for weird syntax highlighting and breaks autocompletion).

**Comment by Veykril** [comment]
A workaround right now is to add the macro to the ignored macros settings. I'm currently working on changes that should fix this in the future (in ~2 months).
```json
    "rust-analyzer.procMacro.ignored": {
        "tokio-macros": [
            "test"
        ]
    },
```
