### ISSUE TITLE
Broken highligting

### ISSUE THREAD

**Issue by hadrizi** [rust-lang/rust-analyzer#12368]
**rust-analyzer version**: `7e95c14ea 2022-05-17 stable`

**rustc version**: `rustc 1.59.0 (9d1b2106e 2022-02-23)`

Errors highlighting got broken for some reason. What's more, Quick Fix inserts code with some weird offset, too.
![image](https://user-images.githubusercontent.com/28650696/169915913-c891c5a4-30e0-429c-bc41-c59fdc0c87a3.png)

Things I tried to fix this:
- disabling the extension
- reinstalling the extension
- reloading language server
- restarting vscode
- switching to pre-release version(didn't work actually, I got `Unfortunately we don't ship binaries for your platform yet.`, however I'm using Windows10 and my workspace is not remote)

**Comment by lukechu10** [comment]
This is a duplicate of https://github.com/rust-lang/rust-analyzer/issues/12293 which is already fixed.

**Comment by lnicola** [comment]
The pre-release version is now out, can you test that?

**Comment by Elogain** [comment]
pre-release "fixed" it, at least for me in vscode

**Comment by hadrizi** [comment]
Yeah, switching to pre-release fixed it.
