### ISSUE TITLE
Better LSP initialization in code-extension

### ISSUE THREAD

**Issue by deeprobin** [rust-lang/rust-analyzer#12375]
Currently the procedure is that we start an executable file as a separate process.
I mean that it gives us uncountable advantages if we do the communication via for example FFI and build a cdylib from the language server.

This gives us on the part of VSCode more control over the Language Server.

Current initialization: https://github.com/rust-lang/rust-analyzer/blob/4ca47b3432061883757ab9456ea2a4e9a33119cd/editors/code/src/main.ts#L245-L298

See https://github.com/node-ffi/node-ffi

**Comment by lnicola** [comment]
That sounds like a lot of work for questionable benefits. Are you thinking this would improve performance?

**Comment by deeprobin** [comment]
@lnicola It's probably not that much work. It is only the initialization of the Language Server. Of course the server runs as usual over the LSP to avoid the FFI overhead.

Personally I found that the whole thing was very flaky and I often had problems, so I suggest this option.

**Comment by kjeremy** [comment]
It's recommended to run the lsp in a separate process. The protocol
overhead is minimum.

**Comment by flodiebold** [comment]
Let's close this since we're unlikely to do this.
