### ISSUE TITLE
Automatically testing own proc-macros for usability with rust-analyzer refactorings

### ISSUE THREAD

**Issue by WorldSEnder** [rust-lang/rust-analyzer#12378]
As part of https://github.com/yewstack/yew/pull/2702 I implemented a more careful handling of `Span`s inside our proc macros that separate usages inside the macro from those that are part of the user-passed macro input. As far as I know, there is no nice way to write integration tests.

Is it possible to script certain refactoring actions - as part of a CI process - against a pre-defined workspace in a test folder, containing a sample rust project, to test the improved UX of my changes above and make sure they don't get reverted in futures commits?

**Comment by jhgg** [comment]
Strictly speaking, you can just write your own LSP client harness that would start up rust-analyzer and apply those actions via the LSP interface and compare the edits produced. I don't know if there is any prior art on this though.

**Comment by flodiebold** [comment]
I wouldn't test specific refactorings, IMO that would be far too brittle. I think a more robust testing approach for proc macros would be to just do expectation testing to check the produced spans for a variety of situations. As long as the spans are correct, you should be able to rely on rust-analyzer (or IntelliJ Rust) to do the right thing.

A library / testing harness that makes this easy would be nice, of course. It's probably not something that's in scope for rust-analyzer itself, though.

**Comment by flodiebold** [comment]
Let's close this since it's IMO not actionable for us.
