### ISSUE TITLE
Weird underlining

### ISSUE THREAD

**Issue by deeprobin** [rust-lang/rust-analyzer#12374]
![grafik](https://user-images.githubusercontent.com/10373452/170044105-b55b1a86-4ff4-41ca-908e-80438715482f.png)

**rust-analyzer version**: rust-analyzer version: 7e95c14ea 2022-05-17 stable

**rustc version**: rustc 1.60.0-nightly (ee5d8d37b 2022-01-17)

**relevant settings**: nothing special

**Comment by bjorn3** [comment]
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/12368 which has been fixed in the latest pre-release.

**Comment by lnicola** [comment]
Already fixed (#12293), try updating to the latest version, or to a pre-release one if that doesn't work.

**Comment by deeprobin** [comment]
Thank you
