### ISSUE TITLE
[feature request] inlay hint tooltips should show "Go to" links for contained types.

### ISSUE THREAD

**Issue by jhgg** [rust-lang/rust-analyzer#12381]
Just like how hovers for variables/functions show "Go to ..." 

<img width="362" alt="image" src="https://user-images.githubusercontent.com/5489149/170154065-5dba5a54-c52f-4d27-8a5d-680ac95d4fd8.png">

Inlay hints tooltips should as well:

<img width="325" alt="image" src="https://user-images.githubusercontent.com/5489149/170154095-a0f52516-7c09-41de-8f2a-3dbbdb085e1c.png">

**Comment by Veykril** [comment]
This works out of the box now that we use the location links feature
