### ISSUE TITLE
Associated methods removed by conditional compilation are not dimmed

### ISSUE THREAD

**Issue by rodrigocfd** [rust-lang/rust-analyzer#12394]
**rust-analyzer version**: 7e95c14ea 2022-05-17 stable

**rustc version**: 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: Windows 10 x64, VSCode 1.67.2

Screenshot:

![dimmed](https://user-images.githubusercontent.com/1283868/170475203-ec30878e-d0ac-44bb-a871-366269ae0237.png)

**Comment by DesmondWillowbrook** [comment]
This seems to be a FIXME.

https://github.com/rust-lang/rust-analyzer/blob/634cfe3d72e785c843ca5d412b12be137b2e14fb/crates/ide-diagnostics/src/handlers/inactive_code.rs#L108-L124

**Comment by DesmondWillowbrook** [comment]
Narrowed down the logic for ignoring the assoc items to https://github.com/rust-lang/rust-analyzer/blob/1883d1f14146959cfa9cdf1ed43e5d1ad013e07e/crates/hir-def/src/data.rs#L475-L484

**Comment by DesmondWillowbrook** [comment]
![image](https://user-images.githubusercontent.com/51814158/183303518-040326cf-9c77-421c-aabf-2b717f57dfce.png)


Turns out this is also the case for enum variants.

**Comment by flodiebold** [comment]
Yes, in general the problem here is passing through diagnostics from the collection step for these things. It's not really complicated, but it needs some plumbing.
