### ISSUE TITLE
Extract module to specific module file (feature request)

### ISSUE THREAD

**Issue by 1Dragoon** [rust-lang/rust-analyzer#12398]
It would be nice if we had the option to re-factor an object by extracting it into an module file rather than only creating a new one. I.e. send it to the requested module, add the use declaration to the crate, and finally move the function and copy its needed use statements (including traits rather than just structs) into the new module file.

Bonus points:
- If the use statements are no longer being used in the source module (because that function was the only one using them,) the use statements are automatically removed
- Option to move functions into another existing module file rather than just a new one
- Allow moving multiple functions at once, only declaring the ones used in the source module as pub(crate) if they aren't already
- structs, enum, and trait definitions as well

**Comment by lnicola** [comment]
There's an assist to move a local module to a file.

**Comment by flodiebold** [comment]
That's #2178.
