### ISSUE TITLE
Assist Idea: Label loop control flow

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#12392]
An assist that inserts a label for a loop and adds the label to all control flow constructs addressing it (that is all `break` and `continue` expressions) would be nice to have I think.

So 
```rs

loop$0 {
    break;
    continue;
    loop {
        break;
        continue;
    }
}
```
would become
```rs

'loop$0: loop {
    break 'loop;
    continue 'loop;
    loop {
        break;
        continue;
    }
}
```

**Comment by XFFXFF** [comment]
I'm working on this :)
