### ISSUE TITLE
vscode rustfmt.extraArgs does not work for `edition`

### ISSUE THREAD

**Issue by LollipopFt** [rust-lang/rust-analyzer#12404]
sorry if this is the wrong place to report, the vscode rust-analyzer extension led me to this repo.

in settings, i have
```json
"rust-analyzer.rustfmt.extraArgs": [
    "--config",
    "max_width=80,use_try_shorthand=true"
]
```
which works.

when i add
```json
"rust-analyzer.rustfmt.extraArgs": [
    "--config",
    "max_width=80,use_try_shorthand=true,edition=\"2021\""
]
```
rustfmt does not work. it also seems that any option which includes a string `\"...\"` in a json string is also not allowed.
how do i add the edition argument?

**Comment by flodiebold** [comment]
You should not need to add the edition; rust-analyzer passes it to rustfmt, unless you're editing a single stand-alone file.

**Comment by LollipopFt** [comment]
unfortunately, i want to have a global config, not create a `rustfmt.toml` each time. @flodiebold do you not have any strings used as part of a value within the vscode config file?

**Comment by bjorn3** [comment]
You can put all settings except the edition in `rustfmt.extraArgs` I think. Only the edition is infered by rust-analyzer from `Cargo.toml` and thus must not be put in `rustfmt.extraArgs`.

**Comment by lnicola** [comment]
It looks like we might be quoting the strings incorrectly, but I'm not sure where:

```
[pid 1339238] execve("/usr/bin/rustfmt", ["rustfmt", "--config", "max_width=80,use_try_shorthand=true,edition=\"2021\"", "--edition", "2021"], 0x559da2c34b50 /* 87 vars */ <unfinished ...>
[...]
[pid 1339238] write(2, "invalid key=val pair: `edition=\"2021\"`", 38) = 38
```

Maybe `strace` is confused, too.

Anyway, you can skip the quotes, they're not needed when using `--config`, or you can use a `rustfmt.toml` file as @flodiebold said:

> You can create a TOML file called rustfmt.toml or .rustfmt.toml, place it in the project *or any other parent directory* and it will apply the options in that file.

**Comment by LollipopFt** [comment]
thank you!
