### ISSUE TITLE
Floating-point literals are displayed as integers

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#12414]
![image](https://user-images.githubusercontent.com/308347/170912614-880b4d1e-426e-42d0-afc5-326d1cc51925.png)

**Comment by jonas-schievink** [comment]
I guess this should use `{:.1}` instead of `{}`:

https://github.com/rust-lang/rust-analyzer/blob/bd06902f90ecc5d411d1743c9cfdbd2bb956e4f5/crates/hir-def/src/expr.rs#L55

**Comment by bjorn3** [comment]
That would force it to print only a single decimal after the comma AFAIK even if there are more.

**Comment by jonas-schievink** [comment]
Ah yeah, we just need `{:?}` instead of `{}`
