### ISSUE TITLE
Good update

### ISSUE THREAD

**Issue by Jzow** [rust-lang/rust-analyzer#12413]
I recently found that when using vscode, rust-analyzer added the function end prompt

**Comment by Jzow** [comment]
Where can I see the updated details and instructions

**Comment by lnicola** [comment]
Sorry, what do you mean?

**Comment by bjorn3** [comment]
You mean https://github.com/rust-lang/rust-analyzer/pull/12244?

**Comment by Jzow** [comment]
@bjorn3 yep

**Comment by Jzow** [comment]
> Sorry, what do you mean?

https://github.com/rust-lang/rust-analyzer/pull/12244
