### ISSUE TITLE
Incorrect type-driven return type completion when there's an existing return type

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#12411]
```rust
fn f() -> ::$0 {}
```

This completes, `core`, `alloc`, `std`, but also `()`, which is wrong.

**Comment by xuhongxu96** [comment]
Looks like fixed by https://github.com/rust-lang/rust-analyzer/pull/12564

**Comment by Veykril** [comment]
Ye, that PR should've fixed this.
