### ISSUE TITLE
`use` completions should complete enums at the start

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#12421]
```rs
enum Foo {}
mod module {}

use $0;
```
We only show `module` here, we should show enums as well since importing variants is more often wanted.

We might just show everything here, but prioritize modules and enums (since you can rename things and its not uncommon to re-export a macro under a different name)

**Comment by yue4u** [comment]
Anything but module is disabled by https://github.com/rust-lang/rust-analyzer/blob/66a842124b52cb005e9dee4605df161badb295e0/crates/ide-completion/src/completions/use_.rs#L104-L113

Show everything seems too noisy to me and I think builtin/prelude type and traits should better be kept excluded.

![image](https://user-images.githubusercontent.com/26110087/172435206-a5ef77be-9d74-4a48-ae7a-ad878d85dd6b.png)

**Comment by Veykril** [comment]
Ye we should only add enums to this after all. It is too noisy otherwise.
