### ISSUE TITLE
Wrapping helper is not interacting well with shorthand struct initialization

### ISSUE THREAD

**Issue by pacak** [rust-lang/rust-analyzer#12423]
Suppose this scenario, code is not well typed, RA suggests "try wrapping the expression in `types::_::_serde::__private::Some`: " (not sure where it gets serde from)

```rust
struct Foo {
    bar: Some(usize)
}

fn foo() {
    let bar = 10;
    let foo = Foo { bar };
}
```

When accepted RA changes code as such:
```rust
fn foo() {
    let bar = 10;
    let foo = Foo { Some(bar) };
}
```

while it should be this instead:
```rust
fn foo() {
    let bar = 10;
    let foo = Foo { bar: Some(bar) };
}
```

**Comment by flodiebold** [comment]
This is a suggestion coming from rustc, so it would need to be reported there. But also, it works correctly for me on Rust 1.61. What's your Rust version?

**Comment by pacak** [comment]
1.60, I guess this can be closed then.
