### ISSUE TITLE
Error Diagnostics appear in the wrong place.

### ISSUE THREAD

**Issue by jokil123** [rust-lang/rust-analyzer#12436]
**rust-analyzer version**: rust-analyzer version: f94fa62d6 2022-05-30 stable

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

**vscode version**: 1.67.2

The hover diagnostics window does not appear in the right place if an error occurs in this type declaration. It appears to be cause by the Future<Output = T> syntax. If this is present all other errors in the type declaraction will also be shifted. The window will always appear at the start or the end of the current block. An error that appears after the type declaration while asigning will however appear at the right place.

![image](https://user-images.githubusercontent.com/46920345/171348035-c617478a-c828-4ac0-9046-4a0be0cdc912.png)

**Comment by lnicola** [comment]
Do you have `rust-analyzer.server.path` set?

**Comment by lnicola** [comment]
Looks like we return a bogus `textDocument/hover` result:

```json
[Trace - 10:26:22] Sending request 'textDocument/hover - (54)'.
Params: {
    "textDocument": {
        "uri": "file:///home/grayshade/Projects/hello/src/main.rs"
    },
    "position": {
        "line": 11,
        "character": 47
    }
}

[Trace - 10:26:22] Received response 'textDocument/hover - (54)' in 1ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```rust\n()\n```"
    },
    "range": {
        "start": {
            "line": 2,
            "character": 10
        },
        "end": {
            "line": 19,
            "character": 1
        }
    }
}
```

**Comment by jokil123** [comment]
okay I found out it can be reproduced even simpler. This also causes this issue;

![image](https://user-images.githubusercontent.com/46920345/171350764-cd3f945e-091d-4c23-8891-f44f0cd592c2.png)

**Comment by lnicola** [comment]
This is unrelated to the compiler error. Even if you disable `checkOnSave` you get:

![image](https://user-images.githubusercontent.com/308347/171351133-be7d14b4-7169-4f3f-8ab5-6e2832b816bf.png)

**Comment by lnicola** [comment]
On the unresolved symbol.

**Comment by Veykril** [comment]
If we can't determine a hover we fallback to the nearest enclosing expression or pattern which in this case is the block expression of the function here https://github.com/rust-lang/rust-analyzer/blob/30672cbf0c13ba81bd507bad91391076a67f5d58/crates/ide/src/hover.rs#L152-L157

So this is unfortunate for when we hover name refs in type position since we'll check something completely unrelated.

We should probably early exit out by returning `None` here https://github.com/rust-lang/rust-analyzer/blob/30672cbf0c13ba81bd507bad91391076a67f5d58/crates/ide/src/hover.rs#L245-L254
when we encounter an `ast::Type`, we might as well add `ast::Item` too just in case.

**Comment by jokil123** [comment]
a (very) crude temporary fix is to surroud the line with curly backets so the error appears somewhat close. You'll at least be able to access the window and scroll down to see the whole error or quick fix if needed.

**Comment by ArchitBhonsle** [comment]
Hi! I just encountered the same issue and would like to help fix it. So I forked this and am pointing to my build of rust-analyzer in my workspace settings. 

I tried @Veykril's suggestion.
> We should probably early exit out by returning `None` here
> 
> https://github.com/rust-lang/rust-analyzer/blob/30672cbf0c13ba81bd507bad91391076a67f5d58/crates/ide/src/hover.rs#L245-L254
> 
> 
> when we encounter an `ast::Type`, we might as well add `ast::Item` too just in case.

But it doesn't seem to fix it. This is what I did:

https://github.com/ArchitBhonsle/rust-analyzer/blob/hover-location-fix/crates/ide/src/hover.rs#L245-L256

I assume there is more to this then?

**Comment by Veykril** [comment]
Ah it doesn't because the functions body is a BlockExpr so it still hits that path

**Comment by Veykril** [comment]
We should also add `ast::Stmt` then I think

**Comment by ArchitBhonsle** [comment]
Doing this doesn't work either.
```
    let expr_or_pat = match_ast! {
        match node {
            ast::Type(_it) => return None,
            ast::Item(_it) => return None,
            ast::Stmt(_it) => return None,
            ast::Expr(it) => Either::Left(it),
            ast::Pat(it) => Either::Right(it),
            // If this node is a MACRO_CALL, it means that `descend_into_macros_many` failed to resolve.
            // (e.g expanding a builtin macro). So we give up here.
            ast::MacroCall(_it) => return None,
            _ => return None,
        }
    };
```

Just as a sanity check I returned `None` from `hover_type_fallback` and sure enough it works as expected. So problem is in `hover_type_fallback` for sure.

I don't understand the `match_ast!` macro but assuming it doesn't break the semantics of `match`, when I `return None` it should return from the whole function right?

Consider the following snippet:
```
fn main() {
    let b: NotImported = "a";
}
```
I `println!`ed the `node` in `hover_type_fallback` before `match_ast!` and whenever I hover on `node` I get:
```
&node = BLOCK_EXPR@10..43
  STMT_LIST@10..43
    L_CURLY@10..11 "{"
    WHITESPACE@11..16 "\n    "
    LET_STMT@16..41
      LET_KW@16..19 "let"
      WHITESPACE@19..20 " "
      IDENT_PAT@20..21
        NAME@20..21
          IDENT@20..21 "b"
      COLON@21..22 ":"
      WHITESPACE@22..23 " "
      PATH_TYPE@23..34
        PATH@23..34
          PATH_SEGMENT@23..34
            NAME_REF@23..34
              IDENT@23..34 "NotImported"
      WHITESPACE@34..35 " "
      EQ@35..36 "="
      WHITESPACE@36..37 " "
      LITERAL@37..40
        STRING@37..40 "\"a\""
      SEMICOLON@40..41 ";"
    WHITESPACE@41..42 "\n"
    R_CURLY@42..43 "}
```
Is this expected?

**Comment by ArchitBhonsle** [comment]
In:
```
fn main() {
    let _a: i3 = 1;
}
```

Hmm... hovering over the `1` gives:
```
[crates/ide/src/hover.rs:245] &node = LITERAL@29..30
  INT_NUMBER@29..30 "1"
```
While hovering on `i3` gives me the same big output as above.

**Comment by Veykril** [comment]
Oh, I was looking at the wrong part of the code, sorry. We need to fiddle with this part here https://github.com/rust-lang/rust-analyzer/blob/30672cbf0c13ba81bd507bad91391076a67f5d58/crates/ide/src/hover.rs#L240-L243|

The `take_while(|it| !ast::Item::can_cast(it.kind()))` to be specific needs to change, we'll have to change that to `!ast::Item::can_cast(it.kind()) || !ast::Type::can_cast(it.kind())`

**Comment by ArchitBhonsle** [comment]
To check what was happening I used `dbg!` all and for this:
```
fn main() {
    let mut _a: NotImported = 1;
}
```
got this:
```
[crates/ide/src/hover.rs:245] &token.parent_ancestors().take_while(|it|
                    !ast::Item::can_cast(it.kind()) ||
                        !ast::Type::can_cast(it.kind())).map(|n|
                (n.kind(), n.text(),
                    ast::Expr::can_cast(n.kind()) ||
                        ast::Pat::can_cast(n.kind()))).collect::<Vec<_>>() = [
    (
        NAME_REF,
        "NotImported",
        false,
    ),
    (
        PATH_SEGMENT,
        "NotImported",
        false,
    ),
    (
        PATH,
        "NotImported",
        false,
    ),
    (
        PATH_TYPE,
        "NotImported",
        false,
    ),
    (
        LET_STMT,
        "let mut _a: NotImported = 1;",
        false,
    ),
    (
        STMT_LIST,
        "{\n    let mut _a: NotImported = 1;\n}",
        false,
    ),
    (
        BLOCK_EXPR,
        "{\n    let mut _a: NotImported = 1;\n}",
        true,
    ),
    (
        FN,
        "fn main() {\n    let mut _a: NotImported = 1;\n}",
        false,
    ),
    (
        SOURCE_FILE,
        "fn main() {\n    let mut _a: NotImported = 1;\n}\n",
        false,
    ),
]
```

But for this:
```
fn main() {
    let mut _a = [1, 2, 3].iter().collect::<NotImported>();
}
```
got this:
```
[crates/ide/src/hover.rs:245] &token.parent_ancestors().take_while(|it|
                    !ast::Item::can_cast(it.kind()) ||
                        !ast::Type::can_cast(it.kind())).map(|n|
                (n.kind(), n.text(),
                    ast::Expr::can_cast(n.kind()) ||
                        ast::Pat::can_cast(n.kind()))).collect::<Vec<_>>() = [
    (
        NAME_REF,
        "NotImported",
        false,
    ),
    (
        PATH_SEGMENT,
        "NotImported",
        false,
    ),
    (
        PATH,
        "NotImported",
        false,
    ),
    (
        PATH_TYPE,
        "NotImported",
        false,
    ),
    (
        TYPE_ARG,
        "NotImported",
        false,
    ),
    (
        GENERIC_ARG_LIST,
        "::<NotImported>",
        false,
    ),
    (
        METHOD_CALL_EXPR,
        "[1, 2, 3].iter().collect::<NotImported>()",
        true,
    ),
    (
        LET_STMT,
        "let mut _a = [1, 2, 3].iter().collect::<NotImported>();",
        false,
    ),
    (
        STMT_LIST,
        "{\n    let mut _a = [1, 2, 3].iter().collect::<NotImported>();\n}",
        false,
    ),
    (
        BLOCK_EXPR,
        "{\n    let mut _a = [1, 2, 3].iter().collect::<NotImported>();\n}",
        true,
    ),
    (
        FN,
        "fn main() {\n    let mut _a = [1, 2, 3].iter().collect::<NotImported>();\n}",
        false,
    ),
    (
        SOURCE_FILE,
        "fn main() {\n    let mut _a = [1, 2, 3].iter().collect::<NotImported>();\n}\n",
        false,
    ),
]
```

**Comment by ArchitBhonsle** [comment]
The above comment (now deleted) has a lot of noise but basically in this case,
```
fn main() {
    let mut _a: NotImported = 1;
}
```
`node` is,
```
[crates/ide/src/hover.rs:254] node.kind() = BLOCK_EXPR
[crates/ide/src/hover.rs:254] node.text() = "{\n    let mut _a: NotImported = 1;\n}"
```

But we still end up highlighting the entire 

On the other hand in
```
fn main() {
    let mut a = [1].iter().collect::<NotImported>();
}
```

we identify this,
```
[crates/ide/src/hover.rs:254] node.kind() = METHOD_CALL_EXPR
[crates/ide/src/hover.rs:254] node.text() = "[1].iter().collect::<NotImported>()"
```

**Comment by ArchitBhonsle** [comment]
Here are the `parent_ancestors()` of `token` and whether they match the current `find` condition,
```
[crates/ide/src/hover.rs:245] &token.parent_ancestors().take_while(|it|
                    !ast::Item::can_cast(it.kind()) ||
                        !ast::Type::can_cast(it.kind())).map(|n|
                (n.kind(), n.text(),
                    ast::Expr::can_cast(n.kind()) ||
                        ast::Pat::can_cast(n.kind()))).collect::<Vec<_>>() = [
    (
        NAME_REF,
        "NotImported",
        false,
    ),
    (
        PATH_SEGMENT,
        "NotImported",
        false,
    ),
    (
        PATH,
        "NotImported",
        false,
    ),
    (
        PATH_TYPE,
        "NotImported",
        false,
    ),
    (
        LET_STMT,
        "let mut _a: NotImported = 1;",
        false,
    ),
    (
        STMT_LIST,
        "{\n    let mut _a: NotImported = 1;\n}",
        false,
    ),
    (
        BLOCK_EXPR,
        "{\n    let mut _a: NotImported = 1;\n}",
        true,
    ),
    (
        FN,
        "fn main() {\n    let mut _a: NotImported = 1;\n}",
        false,
    ),
    (
        SOURCE_FILE,
        "fn main() {\n    let mut _a: NotImported = 1;\n}\n",
        false,
    ),
]
```
Which of these do we ideally want to `find`?

**Comment by jean-santos** [comment]
Hello!
I'd like to have a go at this as my first issue.
