### ISSUE TITLE
completion relevance in enum variant parameters is not computed.

### ISSUE THREAD

**Issue by jhgg** [rust-lang/rust-analyzer#12434]
Consider the following code:

```rust
fn main() {
    takes_bar($0)
    Foo::VariantA($1)
}

enum Bar {
    Baz,
    Qux
}

enum Foo {
    VariantA(Bar)
}

fn takes_bar(bar: Bar) {
}
```

Here, when computing completions for `$0`, we'll get `Bar::Baz` and `Bar::Qux` sorted to the top. However, when computing completions for `$1`, we fall back to sorting completions alphabetically, which exposes `Bar` at some point depending on what's in scope, and also, it does not suggest the variants (`Bar::*`).

**Comment by jhgg** [comment]
Additionally, in some places, the type of completion in the enum variant may be inferred from another location, e.g.:

```
fn qux() -> Result<Bar, ()> {
    Ok($0)
}

fn qux() -> Result<Bar, ()> {
    Ok($0)
}

fn baz() -> Bar {
    $1
}
```

`$0` does not compute relevance properly, whereas `$1` does.

**Comment by jhgg** [comment]
I concur. This looks to be resolved. Not sure by what though :rofl:

**Comment by Veykril** [comment]
There was a recent PR for this for a duplicate issue I believe
