### ISSUE TITLE
Status bar stays red even when Cargo.toml error is resolved

### ISSUE THREAD

**Issue by SludgePhD** [rust-lang/rust-analyzer#12433]
**rust-analyzer version**: 6c9fc4fec 2022-05-29 nightly

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: no relevant settings found

I introduced an error into my `Cargo.toml`, which caused rust-analyzer to indicate an error. When I resolved the error, rust-analyzer became usable again, the tooltip shows "Ready" instead of the error, but the status bar is still colored red:

![screenshot_2022-06-01_00:08:09](https://user-images.githubusercontent.com/96552222/171292589-39caa127-91f1-4457-a315-eb2ac661c30e.png)

**Comment by Veykril** [comment]
We aren't resetting the background color here https://github.com/rust-lang/rust-analyzer/blob/e25cbf85849a48e02701736375c784b3e3e0e3fc/editors/code/src/ctx.ts#L83-L85
