### ISSUE TITLE
RA thinks that a called #[tokio::main] function returns a Future

### ISSUE THREAD

**Issue by kennethuil** [rust-lang/rust-analyzer#12450]
**rust-analyzer version**: f94fa62d6 2022-05-30 stable

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

Cargo.toml:
```
[package]
name = "ra-issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.18", features = ["rt", "rt-multi-thread", "net", "macros"] }
```

main.rs:
```
use std::error::Error;

fn main() {
    // do_something_async is a non-async function that blocks on the tokio runtime
    // It returns a plain Result
    // Rust Analyzer thinks do_something_async returns a Future and puts a red squiggle here
    // but it compiles without errors
    let x: Result<_,_> = do_something_async();
    println!("async result is {:?}",x);
}

#[tokio::main]
async fn do_something_async() -> Result<(), Box<dyn Error + Send + Sync>> {
    println!("async stuff goes here...");
    Ok(())
}
```

**Comment by bjorn3** [comment]
What is your rust-analyzer configuration? Do you have `rust-analyzer.procMacro.enable` set to true? (should be by default)

**Comment by kennethuil** [comment]
"Proc Macro: Enable" is checked (in VSCode).  So is "Proc Macro > Attributes: Enable".  "Proc Macro: Ignored" is empty.  settings.json has no settings overrides in it.

**Comment by flodiebold** [comment]
The tokio::main macro implementation in `tokio-macros` has `#[cfg(not(test))]` on it. Probably adding `tokio-macros` to `rust-analyzer.cargo.unsetTest` will help, I haven't tried it yet though.

**Comment by kennethuil** [comment]
{
    "rust-analyzer.cargo.unsetTest": [
        "core",
        "tokio-macros",
        "tokio_macros"
    ]
}
did not have any effect

**Comment by flodiebold** [comment]
Adding *both* `"tokio"` and `"tokio-macros"` (with the `-`) does it, because the reexport in `tokio` is again `cfg(test)`.

**Comment by flodiebold** [comment]
Fixed by #12599

**Comment by paulkre** [comment]
When is this fix going to be released?

**Comment by bjorn3** [comment]
It should already have been released. Every monday there is a new stable release.

**Comment by anistark** [comment]
Still getting this on VS Code.

**Comment by asllop** [comment]
> Still getting this on VS Code.

Try updating rust, it resolved the problem for me: `rustup update`

**Comment by wtto00** [comment]
I still encountered this error, and I ignore it in VS Code:
```json
"rust-analyzer.diagnostics.disabled": ["unresolved-proc-macro"]
```

**Comment by dtantsur** [comment]
Yeah, I still see it rust.vim too. Just updated rust and rust-analyzer to 1.73.
