### ISSUE TITLE
Files content get deleted when formatting with `#![rustfmt::skip]` attribute

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust-analyzer#12458]
**rust-analyzer version**: rust-analyzer version: f94fa62d6 2022-05-30 stable

**rustc version**: 

```
rustc 1.63.0-nightly (e71440575 2022-06-02)
binary: rustc
commit-hash: e71440575c930dcecac288b7c3536410d688b351
commit-date: 2022-06-02
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.4
```

**code version**:
```
Version: 1.67.2 (system setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Datum: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
Betriebssystem: Windows_NT x64 10.0.22621
```

Execute the following steps to reproduce my issue

```sh
cd $(mktemp -d)
cargo init . --name abc
echo -e '#![rustfmt::skip]\n\nfn main() {}' > src/main.rs
code .
```

wait until rust-analyzer is ready, open `src/main.rs` and then press <kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>f</kbd> for formatting the file. 

**The whole content of the file gets truncated**. I can't reproduce the issue with `rustfmt` itself, so `rustfmt src/main.rs` does nothing (as expected).

**Comment by jhgg** [comment]
This is indeed reproducible with rustfmt, with `cat src/main.rs | rustfmt`

**Comment by jhgg** [comment]
I've bisected this to a regression in rustfmt introduced in: https://github.com/rust-lang/rustfmt/pull/5094

**Comment by jhgg** [comment]
The fix to rustfmt has landed. So we can probably close this out now - it should be fixed by upgrading to a new nightly tool chain at some point in the future.

**Comment by hellow554** [comment]
Thanks for your support! That was quick.
