### ISSUE TITLE
Log entries are not cleaned up when using "Restart server"

### ISSUE THREAD

**Issue by hasali19** [rust-lang/rust-analyzer#12469]
I often use the "Restart server" command to reload rust analyzer when switching between build targets. I noticed that rust analyzer seems to create a new entry in the vscode output view every time the server is restarted. Is something not being cleaned up properly?

![image](https://user-images.githubusercontent.com/10169241/172044304-f44793d3-427a-4ebd-a03f-04c354233d7e.png)

**Comment by Veykril** [comment]
Given you said often and you only reporting this now I assume this is a recent regression?

**Comment by lnicola** [comment]
Not a regression, but make sure to disable tracing if you have it enabled.

**Comment by Veykril** [comment]
This also duplicates the `rust analyzer language server` log, not just the trace

**Comment by hasali19** [comment]
> Given you said you use this often and you are only reporting this now I assume this is a recent regression? And if that's the case are you using the nightly r-a? Wanna make sure whether this might be the request retry PR or not

I use the restart command often, but I don't look at the logs very often so I only noticed it today. I am indeed using nightly.

> Not a regression, but make sure to disable tracing if you have it enabled.

I disabled tracing which stops any output from being shown, but it seems that the entries in the menu are still duplicated.

**Comment by Veykril** [comment]
Ye it seems we don't dispose of/reuse the channels when restarting

**Comment by hasali19** [comment]
Tangentially, when changing the build target (`rust-analyzer.cargo.target`) vscode shows a notification that r-a needs to reload but the button reloads the whole window. That's kind of annoying so I've been manually using "Restart server" which works fine - it seems like the notification should also do that instead.

**Comment by Veykril** [comment]
Ye I think we can downgrade that to a server restart instead
