### ISSUE TITLE
Type mismatch with tuple keys in DefaultHashMap

### ISSUE THREAD

**Issue by danielhuang** [rust-lang/rust-analyzer#12488]
**rust-analyzer version**: rust-analyzer version: 949012016 2022-05-01 dev

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: 
```json
"rust-analyzer.diagnostics.experimental.enable": true,
```

Given the following code:
```toml
defaultmap = "0.5.0"
```
```rs
use defaultmap::DefaultHashMap;

fn main() {
    let mut map = DefaultHashMap::new(0);
    map[(0, 0)] = 1;
}
```
rust-analyzer reports an error:
![image](https://user-images.githubusercontent.com/24739403/172507226-b0ccd534-27a7-4cdc-b0a2-5c3c6d3bc025.png)

**Comment by danielhuang** [comment]
May be related to #12675

**Comment by flodiebold** [comment]
Yeah, this is probably the same problem.

**Comment by danielhuang** [comment]
Fixed along with https://github.com/rust-lang/rust-analyzer/issues/12675
