### ISSUE TITLE
rust-analyzer.completion.callable.snippets =none isn't respected in vscode

### ISSUE THREAD

**Issue by ahicks92** [rust-lang/rust-analyzer#12498]
**rust-analyzer version**: 0.3.1083

**rustc version**: Multiple, on the machine I'm on currently 1.59.0

**relevant settings**: rust-analyzer.completion.callable.snippets 

I'm pretty sure this used to make it so that Rust-analyzer would never add parens when completing functions, but now it doesn't and it's throwing me consistently because I'm blind and I'm using a screen reader.  I definitely used to be able to turn this off, and I am 99% sure this setting was how.  From settings.json:

```
	"rust-analyzer.completion.addCallParenthesis": false,
	"rust-analyzer.completion.addCallArgumentSnippets": false,
```

(which, I am now noticing, sort of implies we used to have and removed `rust-analyzer.completion.addCallParenthesis`, so was this behavior just not copied over? In any case I'm hoping this is an easy fix).

**Comment by Veykril** [comment]
What does the `Show RA version` command print? The setting works fine for me.

**Comment by ahicks92** [comment]
I have:

rust-analyzer version: ad6810e90 2022-06-06 stable

Sorry, I assumed the extension version from the UI was the same thing.

**Comment by Veykril** [comment]
The version from the UI is the client version, the command gives the server version. Both are important to know here (we probably should add that to the issue template) as they can be out of sync depending on the user setups. In your case the server is the correct version though.

Do you have the old settings still in the file? If yes try removing them. Otherwise I don't see what the problem could be from this. Would you mind pasting all your `rust-analyzer` related configs here maybe?

**Comment by ahicks92** [comment]
I'll do some more digging for you tomorrow, I don't have anything sensitive outside the work laptop so I can just give you whatever.  Thanks for the fast response.

**Comment by ahicks92** [comment]
Yeah, looks like removing the old settings works.  I'll try it more on my work laptop today and see if that's a consistent fix for it.  Seems odd that it'd still care about them so maybe still worth fixing that but let's see if it works when I use it for a while first because I just did a 30 second test only.

**Comment by ahicks92** [comment]
Yep. Both set to false on both machines.  Flat out removing fixed it on both machines.
