### ISSUE TITLE
Feature Request: Inverse of `qualify_method_call`

### ISSUE THREAD

**Issue by kpozin** [rust-lang/rust-analyzer#12497]
Sometimes you realize that a fully qualified function call is no longer ambiguous and could be made into a method call instead. A code assist for this change would be helpful.

**Comment by sancho20021** [comment]
Does this assist need to make sure the call isn't ambiguous?
Where should the cursor be located when suggesting the assist, at the function identifier?

**Comment by Veykril** [comment]
Ye I think showing this when its ambiguous is rather pointless so the assist should check that.
I'd say the function identifier is a good choice ye

**Comment by sancho20021** [comment]
Ok, I will try to do this

**Comment by DropDemBits** [comment]
I think #13825 implements this assist, so I think this can be closed now?
