### ISSUE TITLE
Support for Jetbrains Fleet

### ISSUE THREAD

**Issue by Sculas** [rust-lang/rust-analyzer#12491]
[Jetbrains Fleet](https://www.jetbrains.com/fleet/) will be in public preview this year and hopefully release soon after. According to a blog post from Jetbrains about Fleet, it will [support the Language Server Protocol](https://blog.jetbrains.com/fleet/2022/01/fleet-below-deck-part-i-architecture-overview/).
> This smart mode can be powered by a variety of options, including the default  IntelliJ IDEA code-processing engine, **custom analyzers, or even language servers (whether these are based on LSP or not)**.

This should make it possible to port `rust-analyzer` to Fleet.
Is this something that could be looked into in the future?

**Comment by Sculas** [comment]
Jetbrains already has support for Rust in both Fleet and Clion, but Rust in Clion has been quite slow for me in the past, hence I switched over to rust-analyzer. 
> Do you have Fleet?

Sadly, I don't. I wish I got invited 😄

**Comment by acfuns** [comment]
I think fleet supports LSP, and when it's public preview, LSP is directly reused, so people in the community who are interested in fleet can try to make a client plug-in.

**Comment by jhgg** [comment]
My understanding is that fleet already just uses rust-analyzer for rust, and just automatically downloads and starts it when you open a rust file.

**Comment by flodiebold** [comment]
If someone wants to add an entry for Fleet to our manual, that would be welcome. Other than that, I don't think there's anything to do here anyway.
