### ISSUE TITLE
The extension 'rust-lang.rust-analyzer' cannot be installed because it is not compatible with VS Code '1.64.2'.

### ISSUE THREAD

**Issue by Super-long** [rust-lang/rust-analyzer#12496]
Install script failed, Machine version is "Darwin MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0; root:xnu8019.61.5~1/RELEASE_ARM64_T6000 arm64"

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
commid b967f1797cd63ef141c97cf3a4350908c2f68cb0

**rustc version**: (eg. output of `rustc -V`) 
rustc 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

none

**Comment by lnicola** [comment]
Which is true. Can you upgrade to Code 1.67 or at least 1.66?

**Comment by lnicola** [comment]
We can't do anything about this. Please upgrade to a supported version of VS Code.
