### ISSUE TITLE
Feature: Add `Implement trait` assist for `struct`, `enum` etc.

### ISSUE THREAD

**Issue by mylvghb** [rust-lang/rust-analyzer#12500]
This feature already exists in the Intellij Rust plugin, can it be integrated into Rust Analyzer?

![image](https://user-images.githubusercontent.com/35945793/173008601-adc8f38b-cdc0-4a61-b5d7-3d980e7140d4.png)

**Comment by lnicola** [comment]
What does it do?

**Comment by mylvghb** [comment]
@lnicola  You and I don't think alike， here's what I think：

**Steps**

1. The  cursor is positioned on the line of the structure or enum decreation.
   
![image](https://user-images.githubusercontent.com/35945793/173013091-e2e2f397-baa6-4008-8a05-76ce0db18541.png)

2. Click `Implement trait`.

![image](https://user-images.githubusercontent.com/35945793/173013248-43b7f64f-835e-41af-b658-ed8898cab0ef.png)

3. The following code is automatically generated and provides a list of suggested traits

![image](https://user-images.githubusercontent.com/35945793/173015352-42292446-0a9a-4a9c-86e9-466a822003e3.png)

**Comment by lnicola** [comment]
Yeah, that's why I asked what it does. Does it also fill in the required members once you pick a trait from the list?

**Comment by mylvghb** [comment]
> Yeah, that's why I asked what it does. Does it also fill in the required members once you pick a trait from the list?

Yeah, the required members need to be filled.

**Comment by mylvghb** [comment]
**Note**: This feature also applies to generic struct

**Comment by mylvghb** [comment]
**Note:** This feature also applies to generic structs
![image](https://user-images.githubusercontent.com/35945793/173020224-323656c6-60c8-49f4-9550-b903c7c2b379.png)

**Comment by lnicola** [comment]
We can insert the `impl` block, but I don't think we can trigger the completion there.

**Comment by mylvghb** [comment]
> We can insert the `impl` block, but I don't think we can trigger the completion there.

Okay!

**Comment by jhgg** [comment]
> We can insert the `impl` block, but I don't think we can trigger the completion there.

I do wonder though if we can filter completions in this case:
```
impl $0 for T {

}
```

Can we offer completions that are only traits in that position? We don't seem to do that now.

**Comment by Veykril** [comment]
We absolutely can

**Comment by estnml** [comment]
hi ,any progress on this? This would increase DX very much

**Comment by dfireBird** [comment]
It seems this can be now closed with assist implemented in #13592 and completion implemented in #16544.
