### ISSUE TITLE
tracing::instrument on a method disables analysis

### ISSUE THREAD

**Issue by tfreiberg-fastly** [rust-lang/rust-analyzer#12518]
In the following `lib.rs`:
```rust
#[derive(Debug)]
pub struct MyStruct;

impl MyStruct {
    fn method(&mut self) {}

    #[tracing::instrument]
    pub fn instrumented_method(&mut self) {
        self.method();
    }
}

#[tracing::instrument]
pub fn instrumented_fn(s: &mut MyStruct) {
    s.method();
}
```

in `MyStruct::instrumented_method`:
- Go To Definition on `self.method()` doesn't work
- there are no mutability underlines in the function
- there's no autocompletion while typing the body `self.method();`

All these things work in `instrumented_fn`, and go away when removing `#[tracing::instrument]` from `instrumented_method`.
I see the same issues in a non-mutable method (except for the missing mutability underline, obviously).

This bug occurs when using VS Code (stable, up to date), both with proc macro support enabled and disabled (see config at the bottom).

---

**rust-analyzer version**: 0.0.0 (366bd7242 2022-06-12) (also happened with latest stable)

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: 
procMacros are as disabled as possible
```json
{
    "rust-analyzer.procMacro.ignored": {
        "tracing_attributes": [
            "instrument"
        ],
        "tracing": [
            "instrument"
        ]
    },
    "rust-analyzer.procMacro.attributes.enable": false,
    "rust-analyzer.procMacro.enable": false,
}
```

**Comment by flodiebold** [comment]
I can't reproduce this with proc macros enabled. I think there are two issues here:
1. Why does it not work for you when proc macros are enabled? This is probably some kind of setup problem / version mismatch.
2. Why does it not work when proc macros are disabled? This has been previously reported in Zulip, though only for the rustc repo. It seems there's some kind of bug there.

If you enable everything and in particular also remove the `procMacro.ignored`, do you get any errors? Do you have any other settings changed from the default? Can you invoke "Expand macro" on the `tracing::instrument` and does it show anything?

**Comment by tfreiberg-fastly** [comment]
with no rust-analyzer settings in my `settings.json`, I get an `unresolved-proc-macro` error on the `#[tracing::instrument]` attribute on `instrumented_fn`, and no errors but also no analysis in `instrumented_method`.

Expanding the unresolved `instrument` attribute on `instrumented_fn`:
```
Not available
```
Expanding the `instrument` attribute on `instrumented_method`:
```
// Recursive expansion of instrument! macro
// =========================================


```

Yeah I think something's weird... I'll test it on other machines

**Comment by flodiebold** [comment]
Maybe try `cargo clean` / a new project if you haven't already? :thinking:

**Comment by tfreiberg-fastly** [comment]
clearing VS Code cache, extensions (and only reinstalling some of them) and reinstalling VS Code seems to have fixed it.
very weird... I'll try to take more notes about this if it ever happens again
