### ISSUE TITLE
vscode rust-analyzer failed to run build scripts Check the server logs for additional info.

### ISSUE THREAD

**Issue by rickiey** [rust-lang/rust-analyzer#12516]
`rust-analyzer failed to run build scripts Check the server logs for additional info.`

Rust-Analyzer always reports this error, but I can't see server log

**Comment by rickiey** [comment]
![image](https://user-images.githubusercontent.com/34705031/173300395-f97137c9-beca-4cd6-b341-503f4b9687fb.png)

**Comment by Veykril** [comment]
The server log should be accessible to you in VSCode via the OUTPUT tab
![image](https://user-images.githubusercontent.com/3757771/173326189-0e0a00a1-bd2c-493e-b6f4-fdd2e3e6112b.png)

**Comment by rickiey** [comment]
thx
