### ISSUE TITLE
Index-out-of-bounds Error Causes `rust-analyzer` to Panic

### ISSUE THREAD

**Issue by x-52** [rust-lang/rust-analyzer#12526]
# The Problem
Every few minutes, the `rust-analyzer` VSCode extension reports that some form of request failed. It seems to have something to with an index-out-of-bounds error in [line 381 of `crates/hir-def/src/nameres/path_resolution.rs`](https://github.com/rust-lang/rust-analyzer/blob/7db73875ac0d9280ae93b14232249d9c1496583a/crates/hir-def/src/nameres/path_resolution.rs#L381).

`rust-analyzer`'s output for one such error is [available here](https://pastebin.com/kS6sHXQR). I'll post a reproducible example as soon as possible.

# System Information
**`rust-analyzer` Version**: `rust-analyzer version: ad6810e90 2022-06-06 stable`
**`rustc` Version**: `rustc 1.61.0 (fe5b13d68 2022-05-18)`
**Operating System**: macOS Monterey 12.4 (x86_64)
**Modified `rust-analyzer` Settings**:

- `"rust-analyzer.checkOnSave.command": "clippy"`

**Comment by Veykril** [comment]
This is a known issue, restarting your r-a should fix it. This can happen when you make changes to your Cargo.toml

**Comment by x-52** [comment]
Ok, thanks.
