### ISSUE TITLE
Proc macro server crashed

### ISSUE THREAD

**Issue by lythesia** [rust-lang/rust-analyzer#12527]
Just use serde's derive macro and leads to

RA output:
```
memory allocation of 140607273619940 bytes failed
[ERROR rust_analyzer::reload] proc macro server crashed: server exited
[ERROR rust_analyzer::reload] proc macro server crashed: failed to write request: Broken pipe (os error 32)
[ERROR rust_analyzer::reload] proc macro server crashed: failed to write request: Broken pipe (os error 32)
...
```

rust-analyzer 0.0.0 (366bd7242 2022-06-12) (which is auto-installed by vscode extension)
rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24)

I think it's not dup with #12495 because I was using quite old rustc version

**Comment by lnicola** [comment]
We only support one set of nightlies per release cycle, those that match what ends up in stable. Can you upgrade to a different one?

**Comment by lythesia** [comment]
Thanks for responding!
I'm working with rust-sgx-sdk which requires specific (old) version of rust toolchain
So may I downgrade rust-analyzer to make it work with proc macro again?

**Comment by lythesia** [comment]
I downgraded RA to v0.3.1083, and it seems to work well now.
Thanks again and close it.

**Comment by lnicola** [comment]
To expand, the interface between the compiler (or RA) and proc macros changes every now and then. We support stable 1.48 and stable 1.49, but some 1.49 nightlies will be compatible with 1.48, and some with 1.49 (and maybe some with neither, when there are multiple changes during a release cycle). But we can't test every nightly, and we'll use the 1.49 ABI even for those 1.49 nightlies that are still using the 1.48 ABI.

>  I'm working with rust-sgx-sdk which requires specific (old) version of rust toolchain

I think they've upgraded to newer nightlies, but unfortunately it still doesn't work on stable. Of course, that doesn't mean it's easy for you to upgrade.

> I downgraded RA to v0.3.1083, and it seems to work well now.

See https://github.com/rust-lang/rust-analyzer/issues/12525#issuecomment-1154151381.
