### ISSUE TITLE
Rust analyzer marks proc macros as errors

### ISSUE THREAD

**Issue by saadjhk** [rust-lang/rust-analyzer#12538]
**rust-analyzer version**: `v0.3.1091`

**rustc version**: `rustc 1.61.0 (fe5b13d68 2022-05-18)`

When using `IntEnum` proc macro rust analyzer gives the error:

proc macro `IntEnum` not expanded rust-analyzer [unresolved-proc-macro](https://rust-analyzer.github.io/manual.html#unresolved-proc-macro)

**Comment by tommyip** [comment]
Same here. Seems to be introduced in `v0.3.1091` as I don't get it in `v0.3.1083`.

rustc version: `rustc 1.63.0-nightly (490324f7b 2022-05-26)`

**Comment by bjorn3** [comment]
@tommyip Try updating rustc. There was a proc macro abi breaking change on nightly recently
 You are using a rustc version from before this change, while rust-analyzer attempts to use the abi from after this change.

**Comment by tommyip** [comment]
> @tommyip Try updating rustc. There was a proc macro abi breaking change on nightly recently
> You are using a rustc version from before this change, while rust-analyzer attempts to use the abi from after this change.

Fixed after updating rustc to `rustc 1.63.0-nightly (1f34da9ec 2022-06-14)`. Thanks @bjorn3.

**Comment by bjorn3** [comment]
@saadjhk uses stable rustc which is unaffected by the abi breaking change that was the problem for @\tommyip.

**Comment by dreamerlzl** [comment]
Same problem with rust-analyzer 2022-06-06, rustc 1.63.0-nightly (b31f9cc22 2022-06-15)

**Comment by flodiebold** [comment]
@dreamerlzl you need a newer version of rust-analyzer to get support for this rustc nightly.

**Comment by eexsty** [comment]
Install the latest version of rust-analyzer. If you are using VSCode, download the `.vsix` file in releases and install it by using the `Extensions => Install from VSIX` feature, since it seems to be not available in the marketplace yet.

**Comment by flodiebold** [comment]
As far as I can tell, the pre-release in the marketplace is from yesterday and does contain the relevant commits.

**Comment by flodiebold** [comment]
@eexsty Are you using VSCode or VSCodium?

**Comment by eexsty** [comment]
> @eexsty Are you using VSCode or VSCodium?

VSCode

**Comment by dreamerlzl** [comment]
> @dreamerlzl you need a newer version of rust-analyzer to get support for this rustc nightly.

Thank you flodiebold! That's the latest version one can get from homebrew(I am using mac).
I tried with the latest release rust-analyzer 0.0.0 (7322a982f 2022-06-16), still a similar error encountered:

![image](https://user-images.githubusercontent.com/28644777/174260871-74f37163-3ae2-4df9-8e05-1349bc294662.png)

**Comment by Veykril** [comment]
The diagnostics log isn't relevant.
Can you set the `RA_LOG` env var for the server to `"warn,project_model=info"` and paste your logs?

**Comment by dreamerlzl** [comment]
@Veykril Hi, thanks for your guide! However, after setting the env var, I can't find any useful info from the log. Could you please give some hint? The log itself is too long to put it here.

**Comment by Veykril** [comment]
There should definitely be useful information in those logs now, why is it too long? This shouldn't be logging too much

**Comment by brianbruggeman** [comment]
I use a number of proc macros (e.g. `serde::{Serialize,Deserialize}`, `rstest`, `clap`, etc.) and they've all been flagged as not expanded because the proc macro is not found over the past week.

(CMD + SHIFT + P: Show RA Version)
rust-analyzer version: 0.0.0 (7322a982f 2022-06-16)

I did not see a convenient way to set RA_LOG, but I did try `RA_LOG="warn,project_model=info" code .`  I saw a number of these in the `Output > Rust Analyzer Language Server` window:
```[WARN mbe::expander::transcriber] expand_tt in repeat pattern exceed limit => MetaTemplate(```

I've included one example below:
```
[WARN mbe::expander::transcriber] expand_tt in repeat pattern exceed limit => MetaTemplate(
    [
        Leaf(
            Punct(
                Punct {
                    char: '#',
                    spacing: Alone,
                    id: TokenId(
                        14,
                    ),
                },
            ),
        ),
        Subtree {
            tokens: MetaTemplate(
                [
                    Leaf(
                        Ident(
                            Ident {
                                text: "cfg",
                                id: TokenId(
                                    16,
                                ),
                            },
                        ),
                    ),
                    Subtree {
                        tokens: MetaTemplate(
                            [
                                Leaf(
                                    Ident(
                                        Ident {
                                            text: "feature",
                                            id: TokenId(
                                                18,
                                            ),
                                        },
                                    ),
                                ),
                                Leaf(
                                    Punct(
                                        Punct {
                                            char: '=',
                                            spacing: Alone,
                                            id: TokenId(
                                                19,
                                            ),
                                        },
                                    ),
                                ),
                                Leaf(
                                    Literal(
                                        Literal {
                                            text: "\"use_std\"",
                                            id: TokenId(
                                                20,
                                            ),
                                        },
                                    ),
                                ),
                            ],
                        ),
                        delimiter: Some(
                            Delimiter {
                                id: TokenId(
                                    17,
                                ),
                                kind: Parenthesis,
                            },
                        ),
                    },
                ],
            ),
            delimiter: Some(
                Delimiter {
                    id: TokenId(
                        15,
                    ),
                    kind: Bracket,
                },
            ),
        },
        Var {
            name: "i",
            kind: None,
            id: TokenId(
                22,
            ),
        },
    ],
)
ExpandCtx {
    bindings: Bindings {
        inner: {
            "i": Fragment(
                Tokens(
                    Subtree(
                        SUBTREE $
                          PUNCH   # [alone] 4294967295
                          SUBTREE [] 4294967295
                            IDENT   doc 4294967295
                            PUNCH   = [alone] 4294967295
                            LITERAL " A type alias for `Box<Sink + Send>`" 178
                          IDENT   pub 179
                          IDENT   type 180
                          IDENT   BoxSink 181
                          PUNCH   < [alone] 182
                          IDENT   T 183
                          PUNCH   , [alone] 184
                          IDENT   E 185
                          PUNCH   > [alone] 186
                          PUNCH   = [alone] 187
                          PUNCH   : [joint] 188
                          PUNCH   : [alone] 189
                          IDENT   std 190
                          PUNCH   : [joint] 191
                          PUNCH   : [alone] 192
                          IDENT   boxed 193
                          PUNCH   : [joint] 194
                          PUNCH   : [alone] 195
                          IDENT   Box 196
                          PUNCH   < [alone] 197
                          IDENT   Sink 198
                          PUNCH   < [alone] 199
                          IDENT   SinkItem 200
                          PUNCH   = [alone] 201
                          IDENT   T 202
                          PUNCH   , [alone] 203
                          IDENT   SinkError 204
                          PUNCH   = [alone] 205
                          IDENT   E 206
                          PUNCH   > [alone] 207
                          PUNCH   + [alone] 208
                          PUNCH   : [joint] 209
                          PUNCH   : [alone] 210
                          IDENT   core 211
                          PUNCH   : [joint] 212
                          PUNCH   : [alone] 213
                          IDENT   marker 214
                          PUNCH   : [joint] 215
                          PUNCH   : [alone] 216
                          IDENT   Send 217,
                    ),
                ),
            ),
        },
    },
    nesting: [
        NestingState {
            idx: 65536,
            hit: false,
            at_end: false,
        },
    ],
}
```

**Comment by Veykril** [comment]
Those `mbe::expander::transcriber` errors aren't relevant for proc-macros, those are macro_rules errors.

The logs with that env var set should contain some `info` logs that states what proc-macros have been loaded, those would be of interest (basically all the logs coming from `project_model`)

**Comment by Veykril** [comment]
Ah, okay we've seen this pop up for a few people already, see https://github.com/rust-lang/rust-analyzer/issues/12494#issuecomment-1156649399. (Note the error isn't really new, the diagnostic is just more visible now).

**Comment by dreamerlzl** [comment]
I install the latest version (6.17) and my vscode works fine, but my neovim lsp still fails.
In my nvim lsp log `~/.cache/nvim/lsp.log`, I really don't find anything useful...
BTW, I am using intel mac.

**Comment by Veykril** [comment]
Heads up, https://github.com/rust-lang/rust-analyzer/pull/12584 fixed an issue where we potentially did misdiagnose *derive helpers* as being unresolved specifically.

@dreamerlzl your snippet seems to be hit by this, so the next release should fix your problem.

**Comment by KaoImin** [comment]
> Heads up, #12584 fixed an issue where we potentially did misdiagnose _derive helpers_ as being unresolved specifically.
> 
> @dreamerlzl your snippet seems to be hit by this, so the next release should fix your problem.

The problem still occurs after updated the latest release today.

**Comment by Veykril** [comment]
Then there is a set up problem for you, can you set the `RA_LOG="warn,project_model=info"` env var for the server (for example via the `rust-analyzer.server.extraEn` setting) and post the entire `Rust-Analyzer Server Log` after your rust-analyzer has finished loading your project?

**Comment by veber-alex** [comment]
I am also still seeing the issue with VSCode and the latest nightly extension.
![image](https://user-images.githubusercontent.com/29788806/174652750-c7a74412-b100-4d81-983d-b4173c4c794d.png)

Log shows just this:
```
[INFO project_model::build_scripts] Running build scripts: "cargo" "check" "--quiet" "--workspace" "--message-format=json" "--all-targets"
[INFO project_model::build_scripts] /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck_derive-1.1.0: BuildScriptOutput { cfgs: [], envs: [], out_dir: None, proc_macro_dylib_path: Some(AbsPathBuf("/home/alex/projects/playground/target/debug/deps/libbytemuck_derive-d25dd7be040f083d.so")) }
[INFO project_model::build_scripts] /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.39: BuildScriptOutput { cfgs: [Atom("use_proc_macro"), Atom("wrap_proc_macro"), Atom("proc_macro_span")], envs: [], out_dir: Some(AbsPathBuf("/home/alex/projects/playground/target/debug/build/proc-macro2-03a6d138363ec831/out")), proc_macro_dylib_path: None }
[INFO project_model::build_scripts] /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.98: BuildScriptOutput { cfgs: [], envs: [], out_dir: Some(AbsPathBuf("/home/alex/projects/playground/target/debug/build/syn-b89e8b27c76020c5/out")), proc_macro_dylib_path: None }
[INFO project_model::build_scripts] /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-macros-1.8.0: BuildScriptOutput { cfgs: [], envs: [], out_dir: None, proc_macro_dylib_path: Some(AbsPathBuf("/home/alex/projects/playground/target/debug/deps/libtokio_macros-2fb0ecd2fb1cbd4b.so")) }
```

**Comment by flodiebold** [comment]
That's #12450, you can add `"tokio"` and `"tokio-macros"` to `rust-analyzer.cargo.unsetTest` as a workaround.

**Comment by Veykril** [comment]
Probably?

**Comment by flodiebold** [comment]
#12599

**Comment by ryo33** [comment]
@brianbruggeman Is it resolved? I have the same issue.

**Comment by flodiebold** [comment]
@ryo33 Make sure you have installed the aarch64 versions of both VSCode and Rust.

**Comment by ryo33** [comment]
@flodiebold Thanks!

**Comment by brianbruggeman** [comment]
@ryo33 Not as far as I can tell.  Just to make sure I was running an apple silicon binary, I uninstalled VSCode and Rust and then reinstalled explicit apple silicon binaries.  I then reinstalled Rust Analyzer and I still see the same kinds of problems.  From a DX perspective, it's sorta broken (I get real errors and then false positives):  I don't know what the real errors are until I actually run a compile.  It's not hard to find the real errors and fix them, but I can no longer glance at my file list and find the problem files.

**Comment by flodiebold** [comment]
@brianbruggeman If you're still getting `incompatible architecture` errors, there has to be an x86 binary involved somewhere. Do you have `rust-analyzer.server.path` set? What does `rustc -vV` and `rustup toolchain list` say?

**Comment by brianbruggeman** [comment]
@flodiebold Thank you.  My toolchain was defaulting to x86.  After setting to arm and reloading, everything appears as expected.

Also for the curious:

```
    "rust-analyzer.server.path": null
```

```
rustup toolchain list
stable-aarch64-apple-darwin (default)
stable-x86_64-apple-darwin
nightly-2021-12-19-x86_64-apple-darwin
nightly-2022-01-01-x86_64-apple-darwin
nightly-x86_64-apple-darwin
1.56.0-x86_64-apple-darwin
```

```
rustc -vV
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: aarch64-apple-darwin
release: 1.61.0
LLVM version: 14.0.0
```

**Comment by flodiebold** [comment]
@wangjia184 You're somehow running an x64 rust-analyzer. You need to install the arm64 version.

**Comment by AnderUstarroz** [comment]
> rustc -vV

@wangjia184 How did you manage to solve this? I am using a Mac M1 but running `rustc -vV` shows:

```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-apple-darwin
release: 1.63.0
LLVM version: 14.0.5
```
and `rustup toolchain list`

```
stable-x86_64-apple-darwin (default)
1.62-x86_64-apple-darwin
```
Can I get the arch64 version somehow using `rustup` ?

**Comment by flodiebold** [comment]
@AnderUstarroz something like `rustup install stable-aarch64-apple-darwin && rustup default stable-aarch64-apple-darwin` should do it.

**Comment by AnderUstarroz** [comment]
Thanks to both of you @flodiebold , @wangjia184
That fixed the issue, I have no macros errors anymore.
