### ISSUE TITLE
Does RA not support centos7?

### ISSUE THREAD

**Issue by jiangbo** [rust-lang/rust-analyzer#12546]
env:

1. github codespace
2. centos7 docker image

When I enter the codespace, RA prompts me that activation failed. The OUTPUT displays `rust-analyzer --version` failed.

![ra](https://user-images.githubusercontent.com/14179422/173972254-a76e450c-da48-4115-9657-57b68efed17a.PNG)

**Comment by bjorn3** [comment]
The binaries built on rust-analyzer's CI are built against a glibc version newer than that of Cent OS. You will need to either build rust-analyzer from source or use the rust-analyzer-preview rustup component available on nightly. (this corresponds to the latest stable rust-analyzer review)

**Comment by jiangbo** [comment]
It still doesn't seem to work.

![nightly](https://user-images.githubusercontent.com/14179422/174010850-7a3b3e07-030f-4bbd-9cc6-86ebd0ba171a.PNG)

**Comment by lnicola** [comment]
You need to set `rust-analyzer.server.path` to `~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer`.

**Comment by jiangbo** [comment]
Thank you, solved perfectly.
