### ISSUE TITLE
Opening VSCode with RA in a Rust mono repo causes entire system to hang for multiple minutes

### ISSUE THREAD

**Issue by leehambley** [rust-lang/rust-analyzer#12552]
**rust-analyzer version**: v0.3.1091

**rustc version**: (eg. output of `rustc -V`)

**relevant settings**: Using VSCode in an SSH remote to a local VM to which practically my entire laptop (M1) resources are dedicated. 8 CPUs and 10GiB RAM.

---

Opening VSCode in our monorepo causes my laptop to lock-up, and when it eventually recovers (20 mins) then practically none of VSCode's features work, no inline lint/clippy, no tooltips for hovering definitions, and inter-references, etc.

Assuming here that this is responsible:

![image](https://user-images.githubusercontent.com/18952/174037675-fc447de6-9cdf-4cae-802f-58c262e250fc.png)

Opening any Rust file then changes this to something like:

![image](https://user-images.githubusercontent.com/18952/174037822-e327129e-0b4c-4b97-a266-66c0f273b594.png)

The VM practically never recovers from this state:

![image](https://user-images.githubusercontent.com/18952/174038559-6e23ad3b-d5e4-4739-a670-2124db4f42f1.png)

The project is a mono repo containing about 5 separate Rust projects (not in a workspace) and one of those five contains workspace crates (it's a "common" package with different workspace crates in different feature groups)

I'd like some way to limit the active number of rustc/analyzer/etc that this extension is using, as I can't see another way around this.

**Comment by flodiebold** [comment]
Currently I think your options are:
 - open a specific subfolder, not the whole monorepo
 - use the `rust-analyzer.linkedProjects` setting to specify only the projects you want to work on
 - disable `rust-analyzer.checkOnSave.enable` to disable running `cargo check` on all projects; this might be where most of the load comes from. It will mean you don't see many diagnostics and have to run `cargo check` yourself, but all other features like completion, goto def etc. will still work. You can configure a command in VSCode to run `cargo check` instead. You could also just try running `cargo check` for all projects in the terminal before opening the workspace; if the settings match, that should speed up the initial check a lot.
 - if disabling `checkOnSave` isn't enough, turning `rust-analyzer.cachePriming.enable` might help as well; it means RA will not eagerly try to analyze all projects, and instead only do that when needed for a particular command. This might increase the latency of the first few commands you run.

**Comment by flodiebold** [comment]
OK, let's close this then since there's nothing else we can do here right now.
