### ISSUE TITLE
rust-analyzer failed to run build scripts Check the server logs for additional info.

### ISSUE THREAD

**Issue by WvvvWv** [rust-lang/rust-analyzer#12553]
**rust-analyzer version**: v0.3.1091

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: windows 11  vscode.

I don't know what happened or how to fix it.

After I comment out the dependencies, I'm back to normal.

![1655372616572](https://user-images.githubusercontent.com/40822202/174042697-262662ef-17c3-468e-a5ac-aff00df01a68.png)

**Comment by flodiebold** [comment]
In the "Output" view, there should be a "Rust Analyzer Language Server" entry. Does it contain anything?

**Comment by WvvvWv** [comment]
> 在“输出”视图中，应该有一个“Rust Analyzer Language Server”条目。它包含任何东西吗？

Sorry, the error I got is only the one in the above screenshot, and I didn't see other errors. At first I thought it was a problem with the cargo mirror source, until I cleared the cache of the previous source mirror, he still had this problem.

**Comment by WvvvWv** [comment]
> In the "Output" view, there should be a "Rust Analyzer Language Server" entry. Does it contain anything?

Sorry, the error I got is only the one in the above screenshot, and I didn't see other errors. At first I thought it was a problem with the cargo mirror source, until I cleared the cache of the previous source mirror, he still had this problem.

**Comment by WvvvWv** [comment]
Guys, I think I have found the cause of the problem, the reason is the problem of msvc and gnu, rust defaults to msvc, and my machine is gnu, the problem was solved when I reinstalled rust and changed the default msvc to gnu, I hope it can too help you.

**Comment by chemsky** [comment]
Find another scenario: if you use ‘x86_64-pc-windows-gnu’ and do not install mingw64, you will see the same problem.

> rust-analyzer failed to run build scripts Check the server logs for additional info.

The RA output box of VS code will also print the following errors:

> [ERROR rust_analyzer::lsp_utils] rust-analyzer failed to run build scripts
> error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
> ...

Solution:

This problem can be solved by downloading mingw64 and configuring the bin directory into the environment variable of windows.

**Comment by monchin** [comment]
it's strange that i use wsl2 but meet the same error

**Comment by TuZhengzhou** [comment]
> Find another scenario: if you use `x86_64-pc-windows-gnu` and do not install `mingw64`, you will see the same problem.
> 
> > rust-analyzer failed to run build scripts Check the server logs for additional info.
> 
> The RA output box of VS code will also print the following errors:
> 
> > [ERROR rust_analyzer::lsp_utils] rust-analyzer failed to run build scripts
> > error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
> > ...
> 
> Solution:
> 
> This problem can be solved by downloading mingw64 and configuring the bin directory into the environment variable of windows.

thanks a lot! After adding the bin directory into the environment variable of windows, I restarted vscode and found the problem been solved.
