### ISSUE TITLE
Unable to get runnableEnv with vscodium on ubuntu

### ISSUE THREAD

**Issue by mvvvv** [rust-lang/rust-analyzer#12559]
Hi, I want to set RUST_LOG env variable when launching or debugging my code under vscodium.

So I wrote this in settings.json 
`    "rust-analyzer.runnableEnv": [
        {
            "env": {
                "RUST_LOG": "trace"
            }
        }
    ],`

or this 
`    "rust-analyzer.runnableEnv":
        {   
                "RUST_LOG": "trace"
         },` 

The variable is never set. Any idea how to do this ?

**Comment by lnicola** [comment]
Are you sure? It appears to work for me:

![image](https://user-images.githubusercontent.com/308347/174276844-401254ea-e69a-4d6e-8d46-d542e3334405.png)

![image](https://user-images.githubusercontent.com/308347/174276947-4a3b581a-761a-448c-97b3-13d68d56535c.png)

How did you install the extension in VSCodium? I don't remember any recent fixes related to this, but it would be useful to mention the version you're on.

**Comment by mvvvv** [comment]
snap codium v 1.68.1

**Comment by lnicola** [comment]
How did you install rust-analyzer?

**Comment by mvvvv** [comment]
from extensions panel I have v0.2.853

**Comment by lnicola** [comment]
That's from December, you can download a VSIX from https://github.com/rust-lang/rust-analyzer/releases/tag/2022-06-13.

**Comment by mvvvv** [comment]
Same problem with v0.3.1091

**Comment by mvvvv** [comment]
` Paramètres (109)
Nom	Description	Par défaut
rust-analyzer.cargoRunner	Custom cargo runner extension ID.	null
rust-analyzer.runnableEnv	
Environment variables passed to the runnable launched using Test or Debug lens or rust-analyzer.run command.

null
rust-analyzer.server.path	
Path to rust-analyzer executable (points to bundled binary by default).

null
rust-analyzer.server.extraEnv ...`

**Comment by flodiebold** [comment]
How do you actually run your program? `runnableEnv` only works if you use rust-analyzer's run functionality, not if you e.g. use another code runner extension or a custom run configuration.

**Comment by mvvvv** [comment]
You're perfectly right and gave me the solution. I falsely thought that run/debug links in the code refers to F5/CTRL+F5. I'm happy to have both ways to test. Thanks a lot.
