### ISSUE TITLE
Autocomplete/Hints randomly not working

### ISSUE THREAD

**Issue by brxken128** [rust-lang/rust-analyzer#12566]
I've had this issue for a while now, and I'll try to be as descriptive as I can.

Within a function, autocomplete sometimes completely stops working (it says "no suggestions"). I'm using only `rust-analyzer` for Rust, and VSCode. This issue has persisted across multiple installs of both VSCode, and Void Linux. I also had the issue on Fedora 36.

The issue seems to happen randomly, but the easiest way I can reproduce it is by bringing more than one error into scope.

Here's some example code:

```rust
pub fn x() -> Result<()> {
    let x = Instant::now();
    let _ = test(v1, v2, v3)?;
    let x_duration = x.elapsed();
    logger.success(format!(
        "Success",
        x_duration.as_secs_f32()
    ));
}
```

Under normal circumstances, selecting the end of `Instant` and hitting ctrl+space would bring the menu up, offering to import `std::time::Instant` - but it doesn't.

It also sometimes happens just randomly, either showing "no suggestions", or relaying a list of my variable names to me.

Using rust-analyzer `7322a982f 2022-06-16` (I'm not too sure where to find a version string)

**Comment by Veykril** [comment]
What r-a version are you using?

**Comment by brxken128** [comment]
I don't think so - I have had the issue for a while. I'm currently writing code and it seems to be getting worse, but I'm not too sure how.

Are there any logs that could be useful?

**Comment by brxken128** [comment]
Forgive the fact that it's a screenshot, there is an awful lot of code involved.

This is within `main()`, and `match` statements (used for `clap`'s builder API)

![Screenshot](https://user-images.githubusercontent.com/77554505/174356168-f8b03726-07f3-40e3-ae3d-5845f2ea776a.png)

**Comment by Veykril** [comment]
Are you still having this problem?

**Comment by brxken128** [comment]
> Are you still having this problem?

Yes sadly - I opened VSCode yesterday and saw similar issues.

**Comment by Veykril** [comment]
Ah, wait this is actually reproducible for me, that is trying to ask for completions in a path qualifier (not sure what I did wrong earlier in my testing).

**Comment by brxken128** [comment]
Thank you!
