### ISSUE TITLE
I'm missing a name for my package... even though it's there?

### ISSUE THREAD

**Issue by CalinZBaenen** [rust-lang/rust-analyzer#12569]
## Details
**rust-analyzer version**: `rust-analyzer version: 0.0.0 (7322a982f 2022-06-16)`  
**rustc version**: `rustc 1.58.1 (db9d1b20b 2022-01-20)`  
**relevant settings**: `$CARGO = "" | $CARGO_HOME = "" | $RUSTUP_HOME = ""`  
**code editor**: VSCode.  
**hardware**: x86_64  
**software**: Linux (Arch).

## Cargo Manifest
This is the my `Cargo.toml` file for the library as of reporting this bug:
```toml
[package]
description = "A library for easily lexing strings."
edition = "2021"
version = "1.0.0"
name = "lex-rs"

[lib]
path = "./src/lib.rs"
```
It's set up how I've seen it set up before in some libraries and similar to the way I've set up my executable projects.

## Comprehension
I am trying to work on a Rust version of my (misnamed) JavaScript library, [ParseJS](https://github.com/CalinZBaenen/ParseJS). So I started exactly the steps for that, make new directory, add `Cargo.toml`, add `src` folder, start writing `Cargo.toml`'s boilerplate and move on to the actual code.  
At least I thought it would play out that way until I got this strange message that's kind of vague:
```
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/calin/Projects/LexRs/lex-rs/Cargo.toml, cargo 1.58.0 (f01b232bc 2022-01-19): Failed to run `"cargo" "metadata" "--format-version" "1" "--manifest-path" "/home/calin/Projects/LexRs/lex-rs/Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error: error: failed to parse manifest at `/home/calin/Projects/LexRs/Cargo.toml`

Caused by:
  missing field `name` for key `package`
```
And previously it was giving me some other error that "Having a `[lib]` section in `Cargo.toml` is not allowed." for whatever reason it may not be (even though all crates have a `[lib]` section).

## Gripe
This is personally a little upsetting since due to [`rust-analyzer`](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer) thinking my Cargo file is incorrect it refuses to do syntax highlighting in the file-tree I opened.

**Comment by Veykril** [comment]
Does running `cargo metadata --manifest-path "/home/calin/Projects/LexRs/lex-rs/Cargo.toml"` manually fail?

**Comment by CalinZBaenen** [comment]
@Veykril Yes, it fails.

From VSCode's terminal (which reports me as being in the `lex-rs` directory):
```
error: failed to parse manifest at `/home/calin/Projects/LexRs/Cargo.toml`

Caused by:
  missing field `name` for key `package`
```
From my Window Manager (XFCE4)'s command line:
```
error: failed to parse manifest at `/home/calin/Projects/LexRs/Cargo.toml`

Caused by:
  missing field `name` for key `package`
```

**Comment by Veykril** [comment]
Then the problem does not lie with rust-analyzer but somewhere else with your setup and cargo. Do other cargo commands work like `cargo check`?

**Comment by CalinZBaenen** [comment]
@bjorn3
```toml
[[bin]]
name = "lex-rs-test"
path = "./src/main.rs"

[package]
edition = "2021"
version = "1.0.0"

[dependencies]
lex-rs = { path="../lex-rs" }
```

**Comment by CalinZBaenen** [comment]
@Veykril Running `cargo check` "works" but yields the same error.  
And as @bjorn3 suspected, it may have to do with `LexRs/Cargo.toml` (`LexRs` being the parent of `lex-rs`), but I find that weird since I feel like they should be treated as separate projects in this instance, especially since I open `lex-rs` through "Open With > VSCode".

**Comment by bjorn3** [comment]
That `Cargo.toml` you posted is indeed missing a name field. All cargo packages are required to have one.

**Comment by CalinZBaenen** [comment]
@bjorn3 Ah, I see now.  
It's still weird that it can't stay within the scope of `lex-rs/` though. \:\/  
Is there any way I can manipulate or force it within that scope without "erroring" out?

**Comment by bjorn3** [comment]
I don't think do. If the `Cargo.toml` file in the parent directory is valid and not a workspace, cargo should ignore it though.
