### ISSUE TITLE
Diesel traits / methods are not resolved properly.

### ISSUE THREAD

**Issue by oslac** [rust-lang/rust-analyzer#12589]
- **rust-analyzer version**: `rust-analyzer version: 0.0.0 (427061da1 2022-06-19)`
- **rustc version**: `rustc 1.63.0-nightly (bb8c2f411 2022-06-19)`
- **relevant settings**: None.

**Issue**: Rust-Analyzer fails to resolve some methods when using the Diesel ORM library. These would be the [eq](https://docs.diesel.rs/diesel/expression_methods/trait.ExpressionMethods.html#method.eq) in `diesel::ExpressionMethods` and [execute](https://docs.diesel.rs/diesel/query_dsl/trait.RunQueryDsl.html#method.execute) in `diesel::RunQueryDsl` as far as I can tell.

Example is available here: https://github.com/oslac/ra-diesel-traits

![Screenshot from 2022-06-20 16-07-43](https://user-images.githubusercontent.com/59695828/174612405-1560e026-9781-4c17-aed1-a907dca09a86.png)

![Screenshot from 2022-06-20 16-07-26](https://user-images.githubusercontent.com/59695828/174612424-dd7d04ae-2d9c-443f-8173-83f5f0b40b05.png)

**Expected**: that RA properly resolves the traits / methods.

**Comment by bjorn3** [comment]
Does https://github.com/oslac/ra-diesel-traits/blob/fa1b4e62ba5abf4df7847f2fe8c1cf545e9faea8/src/schema.rs#L1 get expanded or does rust-analyzer show an error for it?

**Comment by bmisiak** [comment]
Database connectors are tricky for rust-analyzer. https://github.com/rust-lang/rust-analyzer/issues/6833#issuecomment-765486673

**Comment by QuadraticKid** [comment]
Issue is still present on [2022-09-19](https://github.com/rust-lang/rust-analyzer/releases/tag/2022-09-19) and [nightly](https://github.com/rust-lang/rust-analyzer/releases/tag/nightly). 
[This issue](https://github.com/rust-lang/rust-analyzer/issues/12100) was previously referenced, and is now merged; however it appears to have not been the solution.

**Comment by longsleep** [comment]
This problem seems to happen pretty much for every Diesel dsl lines. 

```rust
        let mut result = users::table
            .select(User::as_select())
            .filter(users::username.eq(username))
            .load::<User>(&mut db)?;
```

The `result` variable type is `{unknown}`.

![gnome-shell-screenshot-a0fom0](https://user-images.githubusercontent.com/1667797/214058210-c8715631-cd7b-4f8e-857a-22e520ca7a88.png)

**Comment by Veykril** [comment]
This works with the latest master branch of diesel, cause was their proc-macros using 2015 name resolution which r-a does not support currently

**Comment by weiznich** [comment]
@Veykril  It's fine to close these issues, but you probably want to link them to an root issue for 2015 style name resolution, because that's an actual bug/missing feature in rust-analyzer.

**Comment by QuadraticKid** [comment]
Issue still present on nightly, even building off of diesel's master branch. (Tests per diesel-rs/diesel [4b2ebca](https://github.com/diesel-rs/diesel/tree/4b2ebca2ddb25f08bf9107869f064f5774efbb83))

Tested with diesel's [examples](https://github.com/diesel-rs/diesel/blob/2.0.x/examples/mysql/getting_started_step_3/src/bin/show_posts.rs) on schema dsl operations- the first operation resolves successfully (filter), however everything after that fails.

**Comment by Veykril** [comment]
New one sounds better

**Comment by weiznich** [comment]
I submitted https://github.com/rust-lang/rust-analyzer/issues/14607
