### ISSUE TITLE
`derivative` crate: proc macro `derivative` not expanded

### ISSUE THREAD

**Issue by cyqsimon** [rust-lang/rust-analyzer#12607]
```rust
use derivative::Derivative;
#[derive(Derivative)]
#[derivative(Debug)]
struct Foo {}
```

![error](https://user-images.githubusercontent.com/28627918/174714558-71a968d6-41c5-4c64-ab78-985ce24770df.png)

`cargo check` and `cargo build` both pass.

**rust-analyzer version**: 427061da1 2022-06-19

**rustc version**: I tested both `rustc 1.61.0 (fe5b13d68 2022-05-18)` & `rustc 1.63.0-nightly (5750a6aa2 2022-06-20)`

---

Possibly-related issue: #12582

**Comment by flodiebold** [comment]
Fixed by #12599, I think:
```rust
#[cfg_attr(not(test), proc_macro_derive(Derivative, attributes(derivative)))]
pub fn derivative(input: TokenStream) -> TokenStream {
```
