### ISSUE TITLE
Hanging on "Roots scanned" in Neovim but not vscode

### ISSUE THREAD

**Issue by jrmoulton** [rust-lang/rust-analyzer#12613]
rust-analyzer ad6810e90 2022-06-08 dev

rustc 1.63.0-nightly (b2eed72a6 2022-05-22)

I'm running rust analyzer inside of neovim and I am getting an issue similar to #8161 where rust analyzer is hanging on "Roots Scanned". This happens inside of neovim but it doesn't happen when I open the project inside of VSCode. 

This also doesn't happen inside of most of my rust projects. It's happening using the [esp-idf-template](https://github.com/esp-rs/esp-idf-template) for an embedded project. 
I've gone through the troubleshooting guide but I haven't found any more useful information. Any other tips on how else can I debug what is going on here?

**Comment by jrmoulton** [comment]
@andoriyu I am on an M1 mac

**Comment by andoriyu** [comment]
> @andoriyu I am on an M1 mac

If you open RA process in activity monitor you will see which files it's scanning. It's not stuck, it's just very slow.


I had to change RA config to explicitly exclude certain directories for it to stop doing that by adding dirs to `rust-analyzer.files.excludeDirs`. 

Folder in my case was `.direnv` and was scanning entire `nixpkgs` repository.

**Comment by jrmoulton** [comment]
Ahhh yeah that is whats happening. Ok I should be able to figure it out then. Thanks!

**Comment by yanshay** [comment]
I face the same issues with Neovim and esp-idf projects. Roots scanned never ends. I couldn't figure out how to solve this. 
Any solutions?

**Comment by SethFalco** [comment]
> I had to change RA config to explicitly exclude certain directories for it to stop doing that by adding dirs to `rust-analyzer.files.excludeDirs`.

I had a similar issue while trying to set up development for [GNOME Fractal](https://gitlab.gnome.org/GNOME/fractal) in Visual Studio Code.

Configuring `rust-analyzer.files.excludeDirs` was the solution for me, which I wrote the following config:

```json
{
  "files.watcherExclude": {
    "**/_build": true,
    "**/.classpath": true,
    "**/.dart_tool": true,
    "**/.factorypath": true,
    "**/.flatpak-builder": true,
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/.idea": true,
    "**/.project": true,
    "**/.scannerwork": true,
    "**/.settings": true,
    "**/.venv": true,
    "**/node_modules": true
  },
  "rust-analyzer.files.excludeDirs": [
    "_build",
    ".dart_tool",
    ".flatpak-builder",
    ".git",
    ".gitlab",
    ".gitlab-ci",
    ".gradle",
    ".idea",
    ".next",
    ".project",
    ".scannerwork",
    ".settings",
    ".venv",
    "archetype-resources",
    "bin",
    "hooks",
    "node_modules",
    "po",
    "screenshots",
    "target"
  ]
}
```

**Comment by GuillaumeLagrange** [comment]
Sorry to bother people on this old issue.

How would one identify files that are not excluded but should on linux (i.e the activity monitor from macOS is not available) ?

On a large repo, I am currently experiencing a ~3 seconds freeze in nvim but not in vscode
The only feedback I get is the number/progress of the scans (in my case 1k6+) from enabling debug logging in nvim.

**Comment by charypar** [comment]
This may not be related, but just in case - I was seeing similar behaviour with rust-analyzer in NeoVim on macOS, and it was down to how the LSP configuration was constructed and an interaction betwen the recommended configuration of [hrsh7th/cmp-nvim-lsp](http://github.com/hrsh7th/cmp-nvim-lsp) and RA's behaviour when file watching is not available (?).

Detailed report on a [relevant issue](https://github.com/hrsh7th/cmp-nvim-lsp/issues/44#issuecomment-2096368152) in cmp-nvim-lsp, but the quick fix was to ensure `workspace.didChangeWatchedFiles.dynamicRegistration` was enabled. See the issue for config snippets.

**Comment by ulchie** [comment]
> This may not be related, but just in case - I was seeing similar behaviour with rust-analyzer in NeoVim on macOS, and it was down to how the LSP configuration was constructed and an interaction betwen the recommended configuration of [hrsh7th/cmp-nvim-lsp](https://github.com/hrsh7th/cmp-nvim-lsp) and RA's behaviour when file watching is not available (?).
> 
> Detailed report on a [relevant issue](https://github.com/hrsh7th/cmp-nvim-lsp/issues/44#issuecomment-2096368152) in cmp-nvim-lsp, but the quick fix was to ensure `workspace.didChangeWatchedFiles.dynamicRegistration` was enabled. See the issue for config snippets.

Thank you so much for posting this! This just finally did it! I was getting so tired of using VSCode but my codebase was always stuck in Neovim until I enabled dynamicRegistration. I can't thank you enough for posting.

**Comment by wonrax** [comment]
Changing the `dynamicRegistration` to `true` doesn't help in my case though. I always have to remove the `node_modules` (it's a monorepo) so that rust analyzer won't hang on `Roots scanned`. With the same config, my WSL setup doesn't have this problem.

**Comment by KShivum** [comment]
I'm getting the same root scanned issue. It seems like adding the .devenv directory is not working for me.
