### ISSUE TITLE
`#[target_feature = "..."]` completion is incorrect

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#12616]
We complete `#[target_feature = "..."]`, but this form is not accepted. The correct form is `#[target_feature(enable = "...")]`.

**Comment by Veykril** [comment]
Relevant part is here https://github.com/rust-lang/rust-analyzer/blob/6fc5c3cd2117a29981ba9b7cef8a51c1d6804089/crates/ide-completion/src/completions/attribute.rs#L332-L336

**Comment by Veykril** [comment]
Yes
