### ISSUE TITLE
"Registering progress handler for token rustAnalyzer/Roots Scanned failed." error when second .rs file is opened as detached file

### ISSUE THREAD

**Issue by HadiKhan-dev** [rust-lang/rust-analyzer#12612]
**rust-analyzer version**:  rust-analyzer version: 0.0.0 (6fc5c3cd2 2022-06-20)

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

When I start VS code and load the first .rs file RA works perfectly fine. However as soon as I open a second .rs file I get the error: `Registering progress handler for token rustAnalyzer/Roots Scanned failed.` with the output 

> [Error - 00:56:37] Registering progress handler for token rustAnalyzer/Roots Scanned failed.
Error: Progress handler for token rustAnalyzer/Roots Scanned already registered
	at Object.onProgress (/home/hadikhan/.vscode/extensions/rust-lang.rust-analyzer-0.4.1100-linux-x64/out/main.js:29:2259)
	at Og.onProgress (/home/hadikhan/.vscode/extensions/rust-lang.rust-analyzer-0.4.1100-linux-x64/out/main.js:34:53972)
	at new yp (/home/hadikhan/.vscode/extensions/rust-lang.rust-analyzer-0.4.1100-linux-x64/out/main.js:34:6846)
	at r (/home/hadikhan/.vscode/extensions/rust-lang.rust-analyzer-0.4.1100-linux-x64/out/main.js:36:27492)
	at qn (/home/hadikhan/.vscode/extensions/rust-lang.rust-analyzer-0.4.1100-linux-x64/out/main.js:3:8777)
	at Bn (/home/hadikhan/.vscode/extensions/rust-lang.rust-analyzer-0.4.1100-linux-x64/out/main.js:3:6621)
	at Immediate._onImmediate (/home/hadikhan/.vscode/extensions/rust-lang.rust-analyzer-0.4.1100-linux-x64/out/main.js:3:6534)
	at processImmediate (node:internal/timers:464:21)

At this point RA gets stuck permanently on: `Roots Scanned: 0/0` with two copies of this notification existing in the notification pop-up menu.

**Comment by Veykril** [comment]
IS this inside a workspace or are you opening two files just like that without any workspace//folders opened?

**Comment by HadiKhan-dev** [comment]
The two files are in their own projects (with their own Cargo.toml) but I'm not using a workspace specifically. I open the file by pressing open in VSCode, going to the Cargo crate folder, going into src and clicking on main.rs/lib.rs etc.

**Comment by HadiKhan-dev** [comment]
Actually, wait, the rust-analyzer not starting issue was due to me not adding the projects to the workspace members, that has been fixed now and so it's working when I open the cargo workspace rather than just opening files directly.

**Comment by HadiKhan-dev** [comment]
The problem still exists if I open the files without opening a workspace.

**Comment by Veykril** [comment]
Okay so at least we know its a problem with our detached file loading then, thanks for investigating.

**Comment by HadiKhan-dev** [comment]
Np, thanks for letting me know the fix.

**Comment by adsick** [comment]
I have it (`Roots Scanned: 0/0 with two copies of this notification existing in the notification pop-up menu.`)too, but everything else seems fine.

**Comment by lnicola** [comment]
@adsick are you also opening random Rust files (as opposed to cargo projects or workspaces)?

**Comment by adsick** [comment]
@lnicola nope, now simply reloaded VS Code and it's gone :)

**Comment by benjirewis** [comment]
Sort of unrelated but may help someone. `rust-analyzer` through `coc-rust-analyzer` on neovim was hanging on `Roots Scanned 0/0` indefinitely for me. I just reran `rustup-init` and things started working.

**Comment by Veykril** [comment]
The roots scanned message not disappearing should be fixed now, so I'll close this for now.
