### ISSUE TITLE
Improve usability for "make variable mut" suggestion

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust-analyzer#12618]
With code like

```rust
let v = vec![];
// ....
v.push(123);
```

RA suggests that I make `v` `mut` (which I expect!). However, in order to apply the suggestion, I have to navigate to the space between `let` and `v`, at which point it's no faster than typing it myself.

When I used to use RLS, I could press `Cmd-.` *at the point of use* (`v.push`) and have it apply the suggestion *to the declaration place*. Could RA do this as well? It'd be a great quality of life improvement IMO.

*Originally posted [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/suggestion.20for.20.22make.20variable.20mut.22).*

**Comment by flodiebold** [comment]
Related #8449, though this one would be just about providing the rustc suggestion in more places. I think we used to do this, but changed it because it led to some problems?

**Comment by camelid** [comment]
Yeah, I think as long as RA can see the type signature of the called function (including if it's in a trait), it should be fairly straightforward to determine if there's mutation (famous last words...).

**Comment by flodiebold** [comment]
We already keep track of autorefs / derefs. I think there's a bit of a tricky part with keeping track where we "need mut" during inference so that everything in `&mut foo.bar[baz].qux` gets marked as mutable; especially with `Index` vs. `IndexMut` and `Deref` vs. `DerefMut`.

**Comment by HKalbasi** [comment]
Native diagnostic is implemented in #14232. The suggestion for rustc diagnostic still only works on declaration but I think the native diagnostic is good enough that fixing rustc suggestion doesn't worth the effort.
