### ISSUE TITLE
Shortcut for wrapping-unwrapping dbg! macro around selection

### ISSUE THREAD

**Issue by Nevsden** [rust-lang/rust-analyzer#12622]
I am not sure, if this already exists, and if so, would be very eager to find out. But could it be possible for this extension to provide a shortcut for tag wrapping? Especially in the case of putting lots of dbg!() around faulty code, this could be a big time saver.

Cheers.

**Comment by Nevsden** [comment]
Thank you so much, with the help of your information is was able to stumble upon this vast number of code actions!!

Could you explain, how to use the assist for removal of the `dbg!()` macro? I am trying to figure it out, but are not used to use the code actions.

**Comment by XFFXFF** [comment]
![image](https://user-images.githubusercontent.com/30254428/175436926-b008f6f1-ff4a-4777-a024-82cad834c80d.png)
If you use vscode, you can click on 💡 to trigger the assist.    
You can also use the "quick fix" shortcut  
![image](https://user-images.githubusercontent.com/30254428/175437163-dec398b5-249e-45e5-ad97-1af8e3c59485.png)
