### ISSUE TITLE
`#[non_exhaustive]` enum variants are not completed in the defining crate

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#12624]
```rust
pub enum Exh {
    #[non_exhaustive]
    Variant,
}

fn f() {
    Exh::$0;
}
```

This does not complete `Variant`, but should, since constructing it within the defining crate is perfectly fine (only downstream crates are affected by `#[non_exhaustive]`.

**Comment by Veykril** [comment]
Relevant code is here https://github.com/rust-lang/rust-analyzer/blob/6fc5c3cd2117a29981ba9b7cef8a51c1d6804089/crates/ide-completion/src/render/variant.rs#L70-L86
