### ISSUE TITLE
`cfg` completions are duplicated many times

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#12623]
![screenshot-2022-06-23-14:29:02](https://user-images.githubusercontent.com/1786438/175298780-90abc39c-7b54-4b9b-88ec-c54466439dad.png)

I'm assuming this is because cfg flags may be set with mulitple values, eg. `target_has_atomic = "ptr"` and `target_has_atomic = "8"` may both be set at once. However, our completions don't actually complete that part of the directive. Perhaps they should, or if not (since it's reasonable to write cfgs that are inactive) they should be deduplicated.

**Comment by Veykril** [comment]
Relevant code is here https://github.com/rust-lang/rust-analyzer/blob/6fc5c3cd2117a29981ba9b7cef8a51c1d6804089/crates/ide-completion/src/completions/attribute/cfg.rs#L37-L40
