### ISSUE TITLE
Shortcuts to run a runnable in Run Test / Debug popup

### ISSUE THREAD

**Issue by DXist** [rust-lang/rust-analyzer#12637]
When I use VSCode, go to a test function and see a popup suggesting to run a test/benchmark/binary at the current cursor location, I would like to run a runnable with given index in the popup list via VS Code extension command and configure shortcut for it (in VSCodeVim settings).

I'm mostly interested in running test under cursor since it's done way more often than debugging, benchmarking or running binary.

And I'd like to be able to rerun the same runnable task via another extension command and shortcut from editor tab without popup.

**Comment by flodiebold** [comment]
There is a "Show CodeLens Commands For Current Line" command that will allow you to choose one of the code lenses ("Run Test" / "Debug" etc.) and run it. There's also the "Rust Analyzer: Run" command. Do either of these serve your purpose?

**Comment by DXist** [comment]
@flodiebold , thank you for the hint! "Show CodeLens Commands For Current Line" works for me good enough.

I wish it worked within the scope of whole test function or it could be possible to rerun this task after new iteration of changes in the test function or the tested code. But I could open 2 editor groups side by side - one to keep the line with the codelens annotations and another one to change the code.

The "Rust Analyzer: Run" command shows options to run tests for whole module or package. It's an option but sometimes I want to focus on a single test.

**Comment by flodiebold** [comment]
I think "Rust Analyzer: Run" also allows you to run a single test if your cursor is inside it :thinking: 
![2022-06-26-155445_651x506_scrot](https://user-images.githubusercontent.com/906069/175817596-52cfc2e3-2612-44ca-8d3c-b358f23d9965.png)

**Comment by DXist** [comment]
I double checked on [another project](https://github.com/DXist/sparse_linear_assignment) but don't see a single test run option.

I use VSCode Insiders (
Version: 1.69.0-insider (Universal)
Commit: 0b74e15affc1b44a5b7cd671dd0a02d3ed6d51a7
Date: 2022-06-15T05:20:12.417Z (1 wk ago))
<img width="1254" alt="Снимок экрана 2022-06-26 в 17 25 59" src="https://user-images.githubusercontent.com/828007/175819303-34542278-422f-4a25-8acc-93872a3c800d.png">

**Comment by flodiebold** [comment]
In the project you linked, I think it's because of the `#[generic_tests::define]` macro. I think we expand it without problems, but the connection to the actual test function probably gets lost. Although we do put the code lens on it, so maybe it's just a matter of unifying the logic there.

**Comment by DXist** [comment]
Actually after I saved workspace with this project "Rust Analyzer: Run" command showed options for single test run.
