### ISSUE TITLE
core::arch::wasm32 intrinsics doesn't show in autocomplete

### ISSUE THREAD

**Issue by harisraharjo** [rust-lang/rust-analyzer#12632]
I tried to import wasm32 with
`use core::arch::wasm32`
 but rust-analyzer didn't pick up the module after 
`arch::`
except 
`asm, global_asm, x64_x86`

**rust-analyzer version**: 0.0.0 (427061da1 2022-06-19)

**rustc version**: 1.61.0 (fe5b13d68 2022-05-18)

**Comment by flodiebold** [comment]
rust-analyzer by default uses the host architecture. If you set `rust-analyzer.cargo.target` to e.g. `wasm32-unknown-unknown`, you will see `core::arch::wasm32`.

**Comment by flodiebold** [comment]
I'll close this, please let us know if you're still having problems.
