### ISSUE TITLE
Can't shadow built-in attributes

### ISSUE THREAD

**Issue by flodiebold** [rust-lang/rust-analyzer#12649]
In the following code:
```rust
use tokio::main;

#[main]
async fn foo() {
}
```
we resolve `main` as the built-in attribute instead of `tokio::main`.

I tried to look into this, but actually failed to understand how we resolve built-in attributes during item collection at all :thinking:

**Comment by flodiebold** [comment]
Aah, we skip them here:
https://github.com/rust-lang/rust-analyzer/blob/6407727ea234a94b31d9a26e5b2771b4ecfcf9cd/crates/hir-def/src/nameres/collector.rs#L1865-L1867
and so never see them later in `resolve_macros`.

**Comment by flodiebold** [comment]
For the M1 system, you need to make sure that you've installed the arm64 toolchain with rustup, by doing something like `rustup toolchain default stable-aarch64`.

**Comment by alfuhigi** [comment]
that fix my issue thanks :) `rustup default stable-aarch64-apple-darwin`

**Comment by lnicola** [comment]
Seems fixed now, at least for `main`.
