### ISSUE TITLE
Can't run test inside a cargo workspace

### ISSUE THREAD

**Issue by GuilhermoReadonly** [rust-lang/rust-analyzer#12658]
Hi !

I am facing some trouble running my unit tests in vscode using the test runner.

First of all i should mention that i am working in a cargo workspace. 
My workspace layout can be observed here: https://github.com/GuilhermoReadonly/mdla

Basically I have a virtual cargo manifest in the root level and then 3 folders containing different part of my project:

├─Cargo.toml
├─mdla-front/
│ ├─Cargo.toml
│ ├─src/
├─mdla-server/
│ ├─Cargo.toml
│ ├─src/
├─mdla-lib/
│ ├─Cargo.toml
│ ├─src/

First issue is that there is no test explorer button when I open the workspace (when I open a sub folder of the workspace directly then it appears):
![image](https://user-images.githubusercontent.com/14791969/176752103-fa531b9d-e90e-4dc0-b1e3-2933b3079040.png)

Weirdly enough I have "Run test" buttons that appears in my source file:
![image](https://user-images.githubusercontent.com/14791969/176752387-8b65c8dc-7918-4acd-bebe-227ca191cc7f.png)

Second issue ; when I click on "Run test" from the previous screenshot, this fail:
![image](https://user-images.githubusercontent.com/14791969/176752712-1731cc5b-8b86-4406-a405-0f138ab679bf.png)

That's weird because when I run my tests manually using "cargo test" there is no issue.

Apparently the task used by vscode is this one:
cargo test --package mdla-server --bin mdla-server -- endpoints::tests --nocapture

So I ran the command used by the test task and indeed it fail with the same error !
```bash
$ cargo test --package mdla-server --bin mdla-server -- endpoints::tests --nocapture
   Compiling mdla-lib v0.1.0 (/home/guilhermo/Documents/git-repos/mdla/mdla-lib)
error: cannot find derive macro `Serialize` in this scope
  --> mdla-lib/src/model.rs:37:17
...
```

If I remove the option "-package mdla-server" and run the command again manually then the test pass again.
```bash
$ cargo test --bin mdla-server -- endpoints::tests --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.10s
     Running unittests (target/debug/deps/mdla_server-2e182e2dd18e0395)

running 5 tests
...
```

So I think my first issue is linked to the second and if I succeed at running the tests then the test explorer button will appears too.

I am not sure if this is a bug or a misconfiguration on my part but honnestly I don't see what is wrong and why the test task add this "-package mdla-server" option to the cargo command...

Thank you for any help on this, this is starting to drive me crazy ;P

PS: 
rust-analyzer version: 0.0.0 (b74e96f50 2022-06-26)
rustc 1.60.0 (7737e0b5c 2022-04-04)

**Comment by Veykril** [comment]
Are you still running into this? (apologies that this seems to have gotten lost)
