### ISSUE TITLE
"received `end` message with no corresponding `begin`" in neovim with LSP

### ISSUE THREAD

**Issue by figurae** [rust-lang/rust-analyzer#12659]
Hi all! I don't even know if this is a rust-analyzer bug, but I keep getting this error when loading or saving any rs file in nvim+LSP after updating rust-analyzer:

![image](https://user-images.githubusercontent.com/89541173/176750029-e18e9384-d6ed-4bf3-9a45-9768bb2bdc02.png)

("received `end` message with no corresponding `begin`")

I'm trying to find out what's wrong, but LSP log is empty. After trying enough times with enough files, a log did appear with some panics ("thread '<unnamed>' panicked at 'range end index 4 out of range for slice of length 0', library\\core\\src\\slice\\index.rs:73:5\n"), but I can't reproduce it, so I think this must have been a random panic.

I tried checking at which commit this error appears and ended up with 32b40ded0f16818918d4a2ca16400526eea369f2 as the last error-free version. 21642a2d85d356d601ee543ff0c7b5d8fb682267 is the first commit with the error, which is really weird because I can't see anything in that commit that could have had any effect on LSP.

**rust-analyzer version**: rust-analyzer 0.0.0 (ce3644694 2022-06-30)

**rustc version**: rustc 1.64.0-nightly (ddcbba036 2022-06-29) (also checked with rustc 1.62.0 (a8314ef7d 2022-06-27))

**OS**: Windows 10 21H2 and up-to-date Manjaro Linux

```
❯❯ src git:(master) 20:02 rust-analyzer analysis-stats .
Database loaded:     904.14ms (metadata 708.93ms; build 90.25ms)
  crates: 1, mods: 1, decls: 1, fns: 1
Item Collection:     2.81s
  exprs: 12, ??ty: 0 (0%), ?ty: 0 (0%), !ty: 0
Inference:           1.16s
Total:               3.97s
```

Steps:
1. `cargo xtask install --server` latest rust-analyzer
2. cargo new project
3. open project with nvim+LSP (minimal init.lua for nvim+Packer: https://pastebin.com/VQNTfLEF), i tried with both nvim 0.7.0 and 0.7.2
4. see error

**Comment by Veykril** [comment]
Only PR I can think of that might've caused this is https://github.com/rust-lang/rust-analyzer/pull/12520

**Comment by Veykril** [comment]
Can you check if https://github.com/rust-lang/rust-analyzer/pull/12660 fixes it?

**Comment by figurae** [comment]
Yup, that fixed it. Thanks!
