### ISSUE TITLE
Request: render math notations in doc prompts

### ISSUE THREAD

**Issue by Banyc** [rust-lang/rust-analyzer#12666]
# Background

Though math notations are not part of the standard syntax of Markdown, they are in fact a widely used additional features supported by a lot of renderers. For instance, [github](https://github.blog/2022-05-19-math-support-in-markdown/).

# Feature request

I want the in-code documentation to render math notations. Currently, they are not recognized in vscode prompts

![image](https://user-images.githubusercontent.com/36535895/176879813-bbe47d9b-ffb8-4958-a542-ff84618ace1f.png)

**Comment by flodiebold** [comment]
Markdown rendering is done by the client, so I don't think there's much we can do here.

**Comment by Banyc** [comment]
@flodiebold Which API in vscode is used? I will create an issue in vscode repo.
