### ISSUE TITLE
rustc: With proc macros disabled, `instrument` functions do not get Ctrl-click and other RA goodness

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#12669]
With the following in my settings
```
    "rust-analyzer.procMacro.enable": false,
    "rust-analyzer.cargo.buildScripts.enable": false,
```
when working on the rustc repo, when I go to a function that has an `instrument` attribute (e.g. `fn operand_projection`), inside that function, RA does not seem to exist -- no types on hover, no Ctrl-click, no inlay hints, nothing.

Enabling proc macros and build scripts fixes that, but I was told this is supposed to work even without proc macros being enabled -- RA could just assume the attribute macro is the identity.

**rust-analyzer version**: rust-analyzer version: 0.0.0 (b74e96f50 2022-06-26)

**rustc version**: rustc bootstrapping

**relevant settings**:
```
{
    "rust-analyzer.checkOnSave.overrideCommand": [
        "python3",
        "x.py",
        "check",
        "--json-output",
        "library/std",
        "compiler/rustc",
    ],
    "rust-analyzer.rustfmt.overrideCommand": [
        "./build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt",
        "--edition=2021"
    ],
    // This also affects proc macros
    "rust-analyzer.cargo.buildScripts.overrideCommand": [
        "cargo",
        "check",
        "-p",
        "rustc_driver",
        "--message-format=json"
    ],
    "rust-analyzer.procMacro.enable": false,
    "rust-analyzer.cargo.buildScripts.enable": false,
    "rust-analyzer.rustc.source": "./Cargo.toml",
}
```

**Comment by flodiebold** [comment]
This is actually easy to reproduce outside rustc:
```rust
use tracing::instrument;
struct Foo;
impl Foo {
    #[instrument]
    fn foo() {
        let xxx = 1;
    }
}
```
DIsabling attribute macros is not enough, it only seems to break when proc macros in general are disabled. We also don't report an unresolved-proc-macro diagnostic for impl items.
