### ISSUE TITLE
proc macro  not expanded: failed to write request: Broken pipe (os error 32)

### ISSUE THREAD

**Issue by artorias1024** [rust-lang/rust-analyzer#12673]
Similar to #10766
<img width="1065" alt="iShot_2022-07-01_23 29 52" src="https://user-images.githubusercontent.com/82564604/176924886-696d92e9-8f4b-4eb3-9a4f-e93876234bfa.png">

<img width="1176" alt="iShot_2022-07-01_23 31 20" src="https://user-images.githubusercontent.com/82564604/176925039-18505936-5fdc-4ac1-bda2-64199231b701.png">

**Comment by artorias1024** [comment]
> CC #12600, but probably with a different error because you're on an even newer compiler.

I'm confused. I tried switching to a lower version of the compiler, but I still get this error

**Comment by lnicola** [comment]
Does it still fail with a 1.62 nightly?

**Comment by artorias1024** [comment]
> Does it still fail with a 1.62 nightly?

1.61 is working !!! Amazing！！
