### ISSUE TITLE
Nested tuples {unknown}

### ISSUE THREAD

**Issue by danielhuang** [rust-lang/rust-analyzer#12675]
**rust-analyzer version**: rust-analyzer version: 0.0.0 (341010268 2022-06-30) (built locally)

also occurs on https://ra-wasm.netlify.app/

**rustc version**: rustc 1.64.0-nightly (7425fb293 2022-06-30)

---

Given the following code:

```rs
use std::collections::HashMap;

fn main() {
    let map: HashMap<_, _> = [((1, 2), 3), ((4, 5), 6)].into_iter().collect();
}
```

rust-analyzer reports:
![image](https://user-images.githubusercontent.com/24739403/176975285-128164b8-07b4-4078-9e5e-9494a95ce079.png)

**Comment by flodiebold** [comment]
Seems we don't consider tuples as implementing `Eq` (or `PartialEq` or `PartialOrd` or possibly more); e.g. `(1i32,).eq()` does not get resolved. (The `HashMap` `FromIterator` impl requires `Eq` for the key.) Probably we have some problem expanding the [macro defining these impls](https://doc.rust-lang.org/src/core/tuple.rs.html#37)?

**Comment by flodiebold** [comment]
Seems we don't like these repeats:
```rust
                $( ${ignore(T)} self.${index()} == other.${index()} )&&+
```

**Comment by Veykril** [comment]
cc https://github.com/rust-lang/rust-analyzer/issues/11952

**Comment by bitgaoshu** [comment]
i think the issue may be about edition. if use 2021, map type is <(i32,i32),i32>. under is unkown. if use before 2021 edition,  cloned after into_iter, it’s ok too. May about feature   array_into_iter_impl.

**Comment by bitgaoshu** [comment]
yeah, my ra is too old

**Comment by bitgaoshu** [comment]
despite ra.  I cannot run the code successfully under edition 2018

**Comment by bitgaoshu** [comment]
i try again. it’s true if change to 2021, it show unkown. but when ra reindex end, add or del some blank line, it changed.

**Comment by bitgaoshu** [comment]
The pic shows what I said.  sth wrong?
![未命名](https://user-images.githubusercontent.com/7943146/177548434-c01388ec-865c-4be5-bc93-e7c656079cbe.jpg)

**Comment by flodiebold** [comment]
Are you using the current Rust version?

**Comment by bitgaoshu** [comment]
rustc 1.61.0 2022 05 18 stable

**Comment by flodiebold** [comment]
I'm using 1.62. This is likely a recent regression.
