### ISSUE TITLE
Renaming `main.rs` to `lib.rs` causes `crate` usages to be replaced with `lib`

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#12684]
We should ignore renames for crate roots and not emit any additional renames in those cases at all.

Relevant code: https://github.com/rust-lang/rust-analyzer/blob/75b22326dad1914c22484ab6672de5cae94f7457/crates/ide-db/src/rename.rs#L169-L233

**Comment by harpsword** [comment]
I tried an example and found no problem. Could you plz provide an example?

**Comment by bjorn3** [comment]
Are you using vscode? I'm not sure if other editors implement the lsp request for handling file renames.

**Comment by Veykril** [comment]
A simple `main.rs` containing just something like
```rs
use crate::foo as bar;
fn foo() {}

```
should cause the issue, VSCode should notify you that r-a wants to make additional changes on the rename from `main.rs` to `lib.rs`
