### ISSUE TITLE
[help please] communicating with the binary directly

### ISSUE THREAD

**Issue by yonip23** [rust-lang/rust-analyzer#12683]
Hello guys!
I'm sorry for the noob question, but I spent several hours trying to communicate directly with the LSP server binary, and just couldn't make it happen :(
Couldn't find any examples / docs on how to do it properly, and read the [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/) over and over.

### Here's what I tried
I got this nice little `main.rs` in a separate project:

```rust
use std::io::{stdin, Write};
use std::process::{Command, Stdio};

fn main() {
    let child = Command::new("rust-analyzer")
        .stdin(Stdio::piped())
        .spawn()
        .unwrap();

    let mut child_stdin = child.stdin.unwrap();
    loop {
        let mut input = String::new();
        stdin().read_line(&mut input).unwrap();

        let length = input.len() - 1;
        let data = format!("Content-Length: {length}\r\n\r\n{input}");
        child_stdin.write_all(data.as_bytes()).unwrap();
        child_stdin.flush().unwrap();
    }
}
```

And I'm sending it these jsons:
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "initialize",
    "params":
    {
        "capabilities":
        {
            "workspaceFolders":
            [
                {
                    "uri": "file:///home/yoni/workspace/lapce",
                    "name": "lapce"
                }
            ]
        }
    }
}

{
    "jsonrpc": "2.0",
    "method": "initialized",
    "params":{}
}
```
(Or in one lines: 
```json
{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"capabilities":{"workspaceFolders":[{"uri": "file:///home/yoni/workspace/lapce","name":"lapce"}]}}}
{"jsonrpc":"2.0","method":"initialized","params":{}}
```
)

And this is the output I get:

![image](https://user-images.githubusercontent.com/67855609/177016726-c70eebe9-b414-4546-8906-8e2a52028c1a.png)

Raw response after the `initialize` request:
```
{"jsonrpc":"2.0","id":1,"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"selectionRangeProvider":true,"hoverProvider":true,"completionProvider":{"triggerCharacters":[":",".","'","("]},"signatureHelpProvider":{"triggerCharacters":["(",",","<"]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{"resolveProvider":true},"documentFormattingProvider":true,"documentRangeFormattingProvider":false,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"=","moreTriggerCharacter":[".",">","{"]},"renameProvider":{"prepareProvider":true},"foldingRangeProvider":true,"declarationProvider":true,"workspace":{"fileOperations":{"willRename":{"filters":[{"scheme":"file","pattern":{"glob":"**/*.rs","matches":"file"}},{"scheme":"file","pattern":{"glob":"**","matches":"folder"}}]}}},"callHierarchyProvider":true,"semanticTokensProvider":{"legend":{"tokenTypes":["comment","keyword","string","number","regexp","operator","namespace","type","struct","class","interface","enum","enumMember","typeParameter","function","method","property","macro","variable","parameter","angle","arithmetic","attribute","attributeBracket","bitwise","boolean","brace","bracket","builtinAttribute","builtinType","character","colon","comma","comparison","constParameter","derive","dot","escapeSequence","formatSpecifier","generic","label","lifetime","logical","macroBang","operator","parenthesis","punctuation","selfKeyword","selfTypeKeyword","semicolon","typeAlias","toolModule","union","unresolvedReference"],"tokenModifiers":["documentation","declaration","definition","static","abstract","deprecated","readonly","defaultLibrary","async","attribute","callable","constant","consuming","controlFlow","crateRoot","injected","intraDocLink","library","mutable","public","reference","trait","unsafe"]},"range":true,"full":{"delta":true}},"inlayHintProvider":{"resolveProvider":true},"experimental":{"externalDocs":true,"hoverRange":true,"joinLines":true,"matchingBrace":true,"moveItem":true,"onEnter":true,"openCargoToml":true,"parentModule":true,"runnables":{"kinds":["cargo"]},"ssr":true,"workspaceSymbolScopeKindFiltering":true}},"serverInfo":{"name":"rust-analyzer","version":"0.0.0 (427061da1 2022-06-19)"}}}[ERROR rust_analyzer] Unexpected error: expected initialized notification, got error: receiving on an empty and disconnected channel

```

After that, the pipe is broken an I can't send any more messages.
Judging by the first response, looks like I'm sending the json rpc correctly (?)

---

Some help with figuring out how to play around with the binary correctly would be much appreciated!
I don't need this specific implementation, so anything that'll let me send requests and get raw responses from the binary will be great.

Thanks guys, and again - sorry for the n00b question 🙂

**Comment by bjorn3** [comment]
I think you need to trim the trailing newline of the message you are sending.

**Comment by yonip23** [comment]
@bjorn3 thank you for the quick reply! Trimming the `\n` at the end did help - now I can get pass the `initialized` notification 🥳 

My loop looks like this now:
```rust
loop {
        let mut input = String::new();
        stdin().read_line(&mut input).unwrap();

        input.truncate(input.len() - 1);
        let length = input.len();
        let data = format!("Content-Length: {length}\r\n\r\n{input}");
        child_stdin.write_all(data.as_bytes()).unwrap();
        child_stdin.flush().unwrap();
        // just for convenience - so that the next input will be on an empty line.
        std::thread::sleep(std::time::Duration::from_millis(200));
        println!();
    }
```

now the same thing happens when I send it my next request: `textDocument/codeLens` - 

```
{"jsonrpc": "2.0","id":2,"method":"textDocument/codeLens","params":{"textDocument": {uri":"file:///home/yoni/workspace/lapce/lapce-data/src/keypress/loader.rs"}}}
[ERROR rust_analyzer] Unexpected error: client exited without proper shutdown sequence
client exited without proper shutdown sequence
```
(I made sure the file exists, and it contain tests so there should be code lens available)

Maybe It has something to do with my `initialize` request? should I send some capabilities?

**Comment by bjorn3** [comment]
Does it print anything else if you set the RUST_LOG env var to `trace`?

**Comment by yonip23** [comment]
Added this line at the beginning of my `main.rs`
```rust
std::env::set_var("RUST_LOG", "trace");
```
Added it to the process spawning as well:
```rust
let child = Command::new("rust-analyzer")
        .env("RUST_LOG", "trace")
        .stdin(Stdio::piped())
        .spawn()
        .unwrap();
```
And added the env var to the JB's run command:
![image](https://user-images.githubusercontent.com/67855609/177206945-eb896227-af38-4985-aa33-2cc93370aba6.png)

Don't see anything else in the log :(

**Comment by flodiebold** [comment]
The env var to set is `RA_LOG`, not `RUST_LOG`.

**Comment by yonip23** [comment]
a ton of debug logs, but after I send the `codeLens` request this is what I get:

```
[DEBUG lsp_server::msg] < {"jsonrpc": "2.0","id":2,"method":"textDocument/codeLens","params":{"textDocument": {uri":"file:///home/yoni/workspace/lapce/lapce-data/src/keypress/loader.rs"}}}    
[DEBUG salsa::runtime] increment_revision()    
[DEBUG salsa::runtime] increment_revision: incremented to R3160    
[ERROR rust_analyzer] Unexpected error: client exited without proper shutdown sequence
client exited without proper shutdown sequence
```

**Comment by yonip23** [comment]
Here's the full debug log, produced by running `cargo run &>> /tmp/ra_log.log` from the terminal in the root folder of my little `main.rs`, and then zipping it
[ra_log.zip](https://github.com/rust-lang/rust-analyzer/files/9041821/ra_log.zip)

**Comment by Veykril** [comment]
`[ERROR rust_analyzer] Unexpected error: client exited without proper shutdown sequence` implies you sent an invalid messages, basically this line here is failing causing the sender of a channel to drop due to the thread exiting
https://github.com/rust-lang/rust-analyzer/blob/e1a8c0b1534f26d4f04df79cfa11fd309365639b/lib/lsp-server/src/stdio.rs#L23

**Comment by Veykril** [comment]
Im not sure either, I'd recommend inserting some debug prints around that place and build r-a with that and then see why it fails to deserialize

**Comment by yonip23** [comment]
Update: I'm stupid 🙂 
There was a missing `"` in my `textDocument/CodeLens` request: it had `uri":` instead of `"uri":`

Now my next issue is that it says that the file is not found, while it very much is found:
```
{"jsonrpc":"2.0","id":2,"error":{"code":-32603,"message":"file not found: /home/yoni/workspace/lapce/lapce-data/src/keypress/loader.rs"}}
```
![image](https://user-images.githubusercontent.com/67855609/178122783-adcd7e3b-13ad-4421-b532-d956492ab48e.png)

Will try to solve it, if you have any idea that'd be great.
Thanks for your attention so far anyway!
