### ISSUE TITLE
The rust-analyzer makes type inferences that the compiler cannot.

### ISSUE THREAD

**Issue by kons-9** [rust-lang/rust-analyzer#12686]
In this code, rustc cannot infer field's type. (Let's leave aside the fact that this code is wrong.)
```
struct Sample {
    field: Vec<Vec<i32>>,
}
fn main() {
    let mut field = Default::default();
    field[0].push(0_i32);
    let _ = Sample { field };
}
```

However, rust-analyzer can infer.

```
struct Sample {
    field: Vec<Vec<i32>>,
}
fn main() {
    let mut field: Vec<Vec<i32>> = Default::default();
    field[0].push(0_i32);
    let _ = Sample { field };
}
```

(This inference is not wrong, but I report it because it behaves differently from the compiler.)

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: 0.0.0 (b74e96f50 2022-06-26)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.62.0 (a8314ef7d 2022-06-27)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

**Comment by flodiebold** [comment]
Rust-analyzer and the compiler work the same here. The type is unknown at the `field[0]` line, and so they both can't resolve the indexing operation and the subsequent `.push()`. You can see that by the fact that go to definition on `push` doesn't work. Rust-analyzer just doesn't emit a "type must be known at this point" diagnostic. The ability to use the later inferred type to suggest as a type annotation and e.g. for completions is a feature.
