### ISSUE TITLE
Can't find reference when `Self` is used to construct a type that takes parameters

### ISSUE THREAD

**Issue by umanwizard** [rust-lang/rust-analyzer#12693]
```
use std::marker::PhantomData;

struct S<T> {
    t: PhantomData<T>,
}

impl<T> S<T> {
    fn new() -> Self {
        Self {
            t: Default::default(),
        }
    }
}

fn main() {}
```

Navigate to the `S` in `struct S` and try to find references. Note that the `Self` constructor later on is not found.

**rust-analyzer version**: latest origin/master

**rustc version**: 1.62.0

**Comment by Veykril** [comment]
The problem is the textual equality here, this should be changed to be done semantically https://github.com/rust-lang/rust-analyzer/blob/c296e777675860164f8e45571efd29c4c08ee7cc/crates/ide/src/references.rs#L270-L286
