### ISSUE TITLE
 When using the gettext macro of the gettext-rs library, it is incorrectly identified as format!

### ISSUE THREAD

**Issue by gmg137** [rust-lang/rust-analyzer#12701]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
> rust-analyzer 0.0.0 (75b22326d 2022-07-03)

**rustc version**: (eg. output of `rustc -V`)
> rustc 1.62.0 (a8314ef7d 2022-06-27)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

**Editors**
> neovim

**Problems encountered**
> When using the gettext macro of the gettext-rs library, it is incorrectly identified as format!.

![截图 2022-07-06 10-01-12](https://user-images.githubusercontent.com/6460323/177451699-d263b453-dd92-4b08-829c-e28912ac371a.png)

**Comment by bjorn3** [comment]
1. That is clippy, not rust-analyzer.
2. `gettext!()` actually uses `format!()` internally.

**Comment by gmg137** [comment]
Sorry, I can't believe I didn't notice.
