### ISSUE TITLE
"unresolved macro `derive`" error with pre-1.47 sysroots

### ISSUE THREAD

**Issue by TonalidadeHidrica** [rust-lang/rust-analyzer#12708]
I guess it happens only when using pre-1.47.   This code gets an "unresolved macro error" at `derive(Clone)`:

```rust
#[derive(Clone)]
struct S;

fn main() {
    println!("Hello, world!");
}
```

```
[rust-analyzer unresolved-macro-call] [E] unresolved macro `derive`
```

At least, this does not happen for rather recent stable.  I am using [this hack](https://github.com/rust-lang/rust-analyzer/pull/10457#issuecomment-947915233) to use 1.42.0 + rust-analyzer, which may be the cause.  This happens only after I updated `rust-analyzer` from 3-weeks-ago-or-so version to the latest one.  Should I give up using rust-analyzer with pre-1.47.0 now or is there a workaround?

**Comment by Veykril** [comment]
Since 3 weeks ago we now properly show this error, before we just didn't show it. So you can just supress the diagnostic given proc-macros didnt work before either for you.

**Comment by TonalidadeHidrica** [comment]
OK, so it's not a digression but it is now honestly confessing what it can't do right?  Then I'll go for `"rust-analyzer.diagnostics.disabled": ["unresolved-macro-call"]`.

**Comment by Veykril** [comment]
Well we don't support rust versions as old as yours, so this not working correctly isn't really unexpected

**Comment by jonas-schievink** [comment]
We don't support Rust versions older than the current stable. Please downgrade rust-analyzer to a version that supports the Rust version you need.
