### ISSUE TITLE
Some functions appear twice in completions

### ISSUE THREAD

**Issue by veber-alex** [rust-lang/rust-analyzer#12703]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: 0.0.0 (fee5555cf 2022-07-05)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.64.0-nightly (2f3ddd9f5 2022-06-27)

![image](https://user-images.githubusercontent.com/29788806/177605037-24163c35-6c73-4932-b3f1-1272dbbb9de0.png)

**Comment by flodiebold** [comment]
The first is the module. It shouldn't show up, since it's private.
