### ISSUE TITLE
Feature request: Magic Number code action

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust-analyzer#12710]
I keep hardcoding certain numbers in my code, because definition of constants in Rust is a chore. I'd be great if rust-analyzer could help and had a code action on numeric literals that turns them into a module-global constant of the right type.

```rust
if flubs > 175 {
}
```

code action on `175` could have "replace with a constant" action, prompt for name (not sure if LSP can do it, Sublime Text extensions can), and generate something like:

```rust
const MAX_FLUBS: u32 = 175;
…
if flubs > MAX_FLUBS {
}
```

**Comment by lnicola** [comment]
If you select the number, there's an `Extract variable` assist, but it doesn't produce a constant.

**Comment by kornelski** [comment]
Yes, dupe #7692
