### ISSUE TITLE
VSCode Tooltip Hiding/moving on mouseover

### ISSUE THREAD

**Issue by SetheenDev** [rust-lang/rust-analyzer#12713]
[discord chatter](https://discordapp.com/channels/273534239310479360/273541522815713281/994611088672948324)
![rust development](https://user-images.githubusercontent.com/93453706/177801193-2442f1bc-991e-46c7-9007-a426f1766a08.gif)

**Comment by Veykril** [comment]
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/12436
