### ISSUE TITLE
`Bad offset` when inserting and removing newlines before a code lens quickly

### ISSUE THREAD

**Issue by K4rakara** [rust-lang/rust-analyzer#12718]
**rust-analyzer version**: `rust-analyzer 1.64.0-nightly (75b2232 2022-07-03)`
**rustc version**: `rustc 1.64.0-nightly (7665c3543 2022-07-06)`
**relevant settings**: I doubt these are really relevant but, `CARGO_HOME=~/.var/app/org.rust-lang.Cargo`, `RUSTUP_HOME=~/.var/app/org.rust-lang.Rustup` (I put all applications that install their own `/opt/foo` like directories in `~/.var/app` because it declutters my home directory.

In VSCode, write the following (make sure to keep the leading and trailing newline):

```rust

extern crate foo;

pub enum Foo {
}

```

In between the `extern crate foo;` and `pub enum Foo {` lines, hold shift and try pressing enter, backspace, enter, backspace, repeatedly, and you should get a "A request has failed" notification. The panic message says something related to a bad range offset. I'm unsure of if this can occur with other items (functions, modules, etc), because I was unable to reproduce it with anything other than `extern crate` and `enum`. I'm guessing this is probably some kind of client synchronization issue, and if its just another case of a larger bug, I apologize.

Lastly, heres [a video](https://youtu.be/RGYeu_-1p_A) of the bug in action.

**Comment by lnicola** [comment]
Good catch, I can confirm this reproduces. I wasn't able following the instructions, but it does happen if I type 2-3 newlines at a time (like in the video) instead of a single one. Holding Shift isn't required.

I think it only worked for you before the enum because of the "0 implementations" lens. Stack trace has:

```
   2: rowan::cursor::SyntaxNode::token_at_offset
   3: ide::goto_implementation::goto_implementation
   4: ide::annotations::resolve_annotation
```

**Comment by lnicola** [comment]
Oh https://github.com/rust-lang/rust-analyzer/issues/4841#issuecomment-1137242644.
