### ISSUE TITLE
Inconsistent diagnostics and actions of `super` modules

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-analyzer#12726]
`super` = super group of a group or "upper" module of a module.

## 1. Mismatch between diagnostic and action

Not sure if they use the same machinery.

![Capture d’écran du 2022-07-08 17-29-54](https://user-images.githubusercontent.com/17877264/178066677-f449f464-5a06-4f8e-a1c5-dc1e6dfe4b05.png)

![Capture d’écran du 2022-07-08 17-30-25](https://user-images.githubusercontent.com/17877264/178066717-8a63b3fe-5597-4cc7-9044-cdbf07f58fb6.png)

Both should probably use the same path.

## 2. Use available import instead of hard-coded paths

More like a suggestion.

![Capture d’écran du 2022-07-08 17-31-08](https://user-images.githubusercontent.com/17877264/178066999-407ffce3-1e1c-4e85-9ac5-ba796d932b73.png)

`use crate::bunch_of_nothing::Foo;` is already declared in the module so the action should append `Bar` instead of issuing `use super::Bar`.

As a side note, relative paths are very cumbersome IMO 🤮

Let me know if any of the above are duplicates.

**Comment by Veykril** [comment]
> 1. Mismatch between diagnostic and action

The diagnostic here comes from rustc, so there is not much for us to do here

> 2. Use available import instead of hard-coded paths

Not sure what you mean with hard-coded here, but the import path style can be controlled via the `rust-analyzer.imports.prefix` setting

**Comment by c410-f3r** [comment]
> > 2. Use available import instead of hard-coded paths
> 
> Not sure what you mean with hard-coded here, but the import path style can be controlled via the `rust-analyzer.imports.prefix` setting

Hehehehe. My bad, I should have researched the existence of a parameter like that. It is a surprise that imports can be flexible after all.

Thank you, @Veykril !
