### ISSUE TITLE
Incorrect formatting of hover action

### ISSUE THREAD

**Issue by BenjaminBrienen** [rust-lang/rust-analyzer#12728]
**rust-analyzer version**: rust-analyzer version: 0.0.0 (75b22326d 2022-07-03)
**rustc version**: rustc 1.64.0-nightly (1517f5de0 2022-07-07)

**relevant settings**: rust-analyzer.hover.actions.references.enable

![image](https://user-images.githubusercontent.com/42162869/178086413-0d6a9da3-11ad-41b6-88f1-c8895c283932.png)

You can see there is a triple underscore `___` between references and `▶︎`. This is caused by the .join() here:
https://github.com/rust-lang/rust-analyzer/blame/995a17fbd9f7cdedfdafec946b1d9e44eff448b4/editors/code/src/client.ts#L61
Is the `___` there for a particular reason, @vsrs ?

**Comment by TheTechn0mancer** [comment]
I don't have write access but I would propose the following change to that function:

```
function renderHoverActions(actions: ra.CommandLinkGroup[]): vscode.MarkdownString {
    const text = actions
        .map(
            (group) =>
                (group.title ? group.title + " " : "") +
                group.commands.map(renderCommand).join(" / ")
        )
        .join(" | ");

    const result = new vscode.MarkdownString(text);
    result.isTrusted = true;
    return result;
}
```

**Comment by Veykril** [comment]
Requires 
```json

    "rust-analyzer.lens.references.method.enable": true,
    "rust-analyzer.hover.actions.references.enable": true,
    ```
to be able to see this behavior.
