### ISSUE TITLE
Rust analyzer failed to load workspace

### ISSUE THREAD

**Issue by shinichihezemans** [rust-lang/rust-analyzer#12725]
I am new to rust and I feel like I am doing something very stupid, but I don't know what.
I installed rust on a new laptop with wsl2 and ubuntu version 22.4.

I can build and run rust code. but the rust-analyzer cannot load the workspace
`[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to load workspace: "cargo" "--version" failed: program not found`
And when I try to format the code
`Request textDocument/formatting failed.
  Message: Failed to spawn "rustfmt"
  Code: -32603 `

I assume, I have forgotten something during setup.

I have tried 
`apt update
apt upgrade
rustup update`

when I run 
`cargo --version`
I get ` cargo 1.62.0 (a748cf5a3 2022-06-08)`

And I can add dependency like `js-sys = "0.3"` and it get's downloaded and compiled, so cargo seems to be working.

What are some troubleshooting steps I can take?

**Comment by lnicola** [comment]
Did you install the extension on the WSL side?

**Comment by shinichihezemans** [comment]
my .bashrc contains `. "$HOME/.cargo/env"` and I start vs code by going to the location in the terminal and typing `code .`.

I believe the extension is installed on the windows side. When I start vs code from windows, the rust-analyzer also shows up.

How do I force the extension to be installed on WSL? There only is the button install and no install on remote WSL.

Although I am worried I am not running vs code on WSL at all. Normally it will in the bottom left corner that is is running on WSL, but is is currently empty.

**Comment by shinichihezemans** [comment]
I have figured it out. 
I forgot to install the remote - WSL extension on the windows side which meant vs code was not running on WSL at all.
Thank you for your help Inicola
