### ISSUE TITLE
changed $CARGO_HOME

### ISSUE THREAD

**Issue by ignamartinoli** [rust-lang/rust-analyzer#12720]
**rust-analyzer version**: 2022-07-04

**rustc version**: 1.62.0

**relevant settings**: as follows.

I wanted to be compliant with the **XDG** specification.
So I added to my `~/.zshenv` the following line

```zsh
export CARGO_HOME="$XDG_DATA_HOME/cargo"
path+=("$CARGO_HOME/bin")
```

removed from `~/.zshenv`

```zsh
. "$HOME/.cargo/env"
```

and just to be sure I changed `~/.local/share/cargo/env` to

```bash
#!/bin/sh
# rustup shell setup
# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"$CARGO_HOME/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="$CARGO_HOME/bin:$PATH"
        ;;
esac
```

and lastly I moved the `~/.cargo/*` directory to `~/.local/share/cargo`.

After that, whenever I open a **Rust** file with **Neovim** and `nvim-lspconfig` I receive the error message

```
LSP[rust_analyzer] rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml file /home/sicro/Code/Rust/example/Cargo.toml. Is rust-src installed?: can't load standard library from sysroot
/usr/lib/rust/1.62.0
(discovered via `rustc --print sysroot`)
try installing the Rust source the same way you installed rustc
```

Did I set the environment poorly or `rust-analyzer` assumes the **Cargo** directory?

**Comment by lnicola** [comment]
> (discovered via `rustc --print sysroot`)

What does that print?

**Comment by lnicola** [comment]
So does that path exist? Who put it there? `which rustc` is that?

**Comment by ignamartinoli** [comment]
> So does that path exists?

Yes, I installed it through the **Gentoo** official repository.

```
sicro@sicro ~ $ ls /usr/lib/rust/1.62.0
bin  lib  libexec  share
```

> `which rustc` is that?

```
sicro@sicro ~ $ which rustc
/usr/bin/rustc
```

**Comment by lnicola** [comment]
Do you have https://packages.gentoo.org/packages/dev-lang/rust installed? We don't assume anything, but we need the Rust standard library source code. It's normally under `$(rustc --print sysroot)/lib/rustlib/src/rust/library`.

I was confused because your `env` file mentioned `rustup`, but you seem to have a system-wide installation (you should pick only one, of course). System-wide installs will work in a pinch, but I'd suggest staying close to the recommended `rustup` workflow.

**Comment by ignamartinoli** [comment]
Basically **Gentoo** (almost) forces you to have https://packages.gentoo.org/packages/dev-lang/rust.
Since it compiles everything from source, if i.e. you have **Firefox** installed, then the OS needs a standard **Rust** compiler as a dependency to build it.
Then, if a user wants, he can have `rustup` also installed to manage multiple toolchains etc., separating user and system installations

That's basically my case

**Comment by bjorn3** [comment]
Did you enable the rust-src use flag of the rust package?

**Comment by lnicola** [comment]
Ah, so you're also using `rustup`? Then you need to make sure you have its shims in `PATH` before the system-wide one.

**Comment by ignamartinoli** [comment]
@lnicola in theory I have it from these lines in my `.zshenv`

```zsh
export CARGO_HOME="$XDG_DATA_HOME/cargo"
path+=("$CARGO_HOME/bin")
export PATH
```

**Comment by lnicola** [comment]
Yeah, but that comes _after_ `/usr/bin`, so we use the system-wide one instead.

**Comment by ignamartinoli** [comment]
I just added the `rust-src` USE flag, normally compiling **Rust** takes a while. As soon as it finishes  I'm reporting back

**Comment by lnicola** [comment]
> I just added the rust-src USE flag, normally compiling Rust takes a while. As soon as it finishes I'm reporting back

That will make RA use the system-wide version of the standard library source code. That's probably not what you want.

Instead, you should set `PATH` properly, e.g. `export PATH=$CARGO_HOME/bin;$PATH`.

**Comment by ignamartinoli** [comment]
@lnicola In which file should I set `export PATH=$CARGO_HOME/bin:$PATH`?

**Comment by ignamartinoli** [comment]
Actually `path+=("$CARGO_HOME/bin")` is a special `zsh` syntactic sugar for `export PATH=$CARGO_HOME/bin:$PATH`.
Nevertheless I tried removing and doing it the classic way.
Do you know if there is a way to check which `rust-analyzer` is being used with recompiling **Rust** from source?

**Comment by lnicola** [comment]
Ah, sorry, then. In this case, why do you get

```
sicro@sicro ~ $ which rustc
/usr/bin/rustc
```

Do you have a `rustc` under `$CARGO_HOME/bin`?

**Comment by ignamartinoli** [comment]
Yup

```
sicro@sicro ~ $ ls $CARGO_HOME/bin
cargo  cargo-clippy  cargo-fmt  cargo-miri  clippy-driver  rls  rustc  rustdoc  rustfmt  rust-gdb  rust-lldb  rustup
```

**Comment by ignamartinoli** [comment]
```
sicro@sicro ~ $ echo $PATH
/home/sicro/.local/share/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/14/bin:/usr/lib/llvm/13/bin:/home/sicro/.spicetify:/home/sicro/.local/bin:/home/sicro/.local/share/cargo/bin
```

The repetition of `/home/sicro/.local/share/cargo/bin` is because I have in `.zshrc` both special and classic PATH syntax

**Comment by ignamartinoli** [comment]
I just ran it and now it says

```
sicro@sicro ~ $ which rustc
/home/sicro/.local/share/cargo/bin/rustc
```

I checked and it's because of this:

Before

```zsh
path+=("$HOME/.spicetify")
path+=("$HOME/.local/bin")
path+=("$CARGO_HOME/bin")
export PATH
```

```
sicro@sicro ~ $ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/14/bin:/usr/lib/llvm/13/bin:/home/sicro/.spicetify:/home/sicro/.local/bin:/home/sicro/.local/share/cargo/bin
```

After

```zsh
path+=("$HOME/.spicetify")
path+=("$HOME/.local/bin")
path+=("$CARGO_HOME/bin")
export PATH

export PATH=$CARGO_HOME/bin:$PATH
```

```
sicro@sicro ~ $ echo $PATH
/home/sicro/.local/share/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/14/bin:/usr/lib/llvm/13/bin:/home/sicro/.spicetify:/home/sicro/.local/bin:/home/sicro/.local/share/cargo/bin
```

I guess `zsh` does the PATH creation operation asynchronously, leading in one case to have `/home/sicro/.local/share/cargo/bin` before `/usr/local/bin`, and in the other case reversed.

**Comment by ignamartinoli** [comment]
For some reason now it works, thanks!
