### ISSUE TITLE
Wrongly getting "file not included in module tree"

### ISSUE THREAD

**Issue by teooliver** [rust-lang/rust-analyzer#12724]
rust-analyzer version:  rust-analyzer 0.0.0 (75b22326d 2022-07-03)
rustc version:  rustc 1.63.0-nightly (a6b8c6954 2022-06-03)

Im getting the message "file not included in module tree" but not sure thats the message we should be getting since the code can access the code from the "root" lib and it actually compiles and works. 

I created a minimal reproducible example here:
https://github.com/teooliver/rust-analyzer-use-lib-bug-report

File in question: 
https://github.com/teooliver/rust-analyzer-use-lib-bug-report/blob/1ca21a8bbe1dad5ec2fdd5fdce32272b76dbb00e/lib-with-bug/src/main.rs#L1

<img width="576" alt="Screen Shot 2022-07-08 at 7 37 13 PM" src="https://user-images.githubusercontent.com/45975624/178052609-dd64df72-9631-4e0e-adad-66e72f7bb950.png">

Running the lib with the error:
```sh
cd lib-with-bug/
cargo run 
```

**Comment by bjorn3** [comment]
I suspect that rust-analyzer only noticed the top-level `Cargo.toml`. You can either point `rust-analyzer.linkedProjects` to both `Cargo.toml` files, or create a cargo workspace containing both crates. https://doc.rust-lang.org/cargo/reference/workspaces.html

**Comment by teooliver** [comment]
Thanks so much @bjorn3, using workspaces fixes the problem, thanks so much for the tip. =)

Here's the fix in case someone else whats to check it out:
https://github.com/teooliver/rust-analyzer-use-lib-bug-report/blob/a596428f6837a0362ed03e84357fdf5217bdea52/Cargo.toml#L10-L11
