### ISSUE TITLE
Error reported over different `Send` and `Sync` ordering

### ISSUE THREAD

**Issue by coreyja** [rust-lang/rust-analyzer#12739]
Hey, first issue over here! Thanks everyone for the hard work put into this tool!

I ran into a small issue where I get an error that the order of `Send + Sync` is 'wrong'. Here is an example error message:
```
expected &(dyn Fn(&GameType) -> ScoreType + Send + Sync), found &(dyn Fn(&GameType) -> ScoreType + Sync + Send)
```
![image](https://user-images.githubusercontent.com/964771/178166348-34d8e942-b8b4-4568-8712-cf1e37905bf0.png)

Notice the only difference being the order of `Send` and `Sync` at the end of each type. This code compiles fine with rustc but rust-analyzer (via nvim for me) is showing this error. Changing the order of `Send` and `Sync` in my code, so each site matches, resolves the error.

Is this intended behavior or a bug?
I fixed my usage, as it makes sense for both sites to have the same ordering! But was midly surprised me that it showed an error, especially when rustc did not.

**Minimal Example**: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ac7efd618222cb33058c459d2d9b98de

**rust-analyzer version**: rust-analyzer 0.0.0 (5342f47f4 2022-07-09)
Also present on the latest (https://github.com/rust-lang/rust-analyzer/tree/2022-07-04) release, both downloaded from Github Releases for arm64 apple

**rustc version**: rustc 1.62.0 (a8314ef7d 2022-06-27)

**relevant settings**: None that I know of

**Comment by veber-alex** [comment]
Minimal repro:
```rust
use std::fmt::Debug;

fn foo(t: &(dyn Debug + Sync + Send)) {}

fn main() {
    let t: &(dyn Debug + Send + Sync) = &1;
    foo(t);
}
```
This actually exposes another bug in the line casting `&1` to a trait object.
```expected &(dyn Debug + Send + Sync), found &i32```
