### ISSUE TITLE
RA doesn't infer types for several methods in a project

### ISSUE THREAD

**Issue by 64kramsystem** [rust-lang/rust-analyzer#12738]
**rust-analyzer version**: `0.0.0 (5342f47f4 2022-07-09)`
**rustc version**: `rustc 1.63.0-nightly (fdca237d5 2022-06-24)`
**relevant settings**: nothing relevant

Hello!

RA doesn't infer types for several methods in a project, in at least one file. This is a Bevy project, so you may be aware of its typical problems :roll_eyes: :grimacing:

The project/file is: https://github.com/64kramsystem/punchy-dev/blob/limit_players_distance/src/movement.rs.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/1595356/178163668-203a2c31-0624-4253-b1b4-60d2c13e2352.png)

**Comment by lnicola** [comment]
Are you using proc macros? They don't work on that nightly (#12600).

**Comment by lnicola** [comment]
Wrt. the version number, did you install RA with `rustup`?

**Comment by 64kramsystem** [comment]
> @64kramsystem are you using proc macros? They don't work on that nightly (#12600).

Hi there! Thanks for your help :smile: This is indeed a problem of using nightly Rust.

The problem happens with the nightly version above, and the current one (`rustc 1.64.0-nightly (38b72154d 2022-07-11)`).

I've switched to stable, and this fixed the problem, so I'm clsoing this (also because, it seems to be a duplicate).

Just for reference, the project does make use of procedural macros, although I'm not sure how they're directly related to the issue (but I don't doubt they are).
