### ISSUE TITLE
Imports deprecated traits, like std::ascii::AsciiExt

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust-analyzer#12756]
Auto-complete for `.to_ascii_*` on `&str` suggests use of the deprecated `AsciiExt` trait, but overlooks inherent `str` methods. 

This is annoying, because use of auto-complete automatically inserts `use  std::ascii::AsciiExt`, which then causes deprecation warnings.

![asciiext](https://user-images.githubusercontent.com/72159/178748624-b609a5d2-5dc7-42e3-b7c0-9e073ef162dc.png)

I think it would be reasonable to never auto-complete or auto-import deprecated items. After all, their authors don't want them used any more. At very least, non-deprecated inherent methods should take priority over a deprecated trait.

----

rust-analyzer 0.0.0 (5342f47f4 2022-07-09)  
rustc 1.62.0 (a8314ef7d 2022-06-27)  
Sublime Text 4126

**Comment by Veykril** [comment]
Are you not getting the inherent completions at all? This seems odd as I get both trait and inherent completions, and the deprecated ones are correctly sorted last ![image](https://user-images.githubusercontent.com/3757771/178750743-d25e7ec0-c2bf-46d1-ada6-287fd9961c8a.png)

**Comment by kornelski** [comment]
I'm not getting any inherent completions in Sublime Text.

I've tried a fresh Cargo project, and this is what I see:

```rust
fn main() {
    "hi".to_a
}
```

![Screenshot 2022-07-14 at 13 43 42](https://user-images.githubusercontent.com/72159/178985197-6a227b3a-50d4-4aa2-ba77-38fd2c4f4ad4.png)

Here's log from the LSP Sublime plugin (1.16.3):

```text
LSP: starting ['/Users/kornel/Library/Caches/Sublime Text 3/Package Storage/LSP-rust-analyzer/rust-analyzer'] in /private/tmp/foo
LSP: rust-analyzer: supported code action kinds: ['', 'quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite']
LSP: rust-analyzer: Supported semantic token types: ['comment', 'keyword', 'string', 'number', 'regexp', 'operator', 'namespace', 'type', 'struct', 'class', 'interface', 'enum', 'enumMember', 'typeParameter', 'function', 'method', 'property', 'macro', 'variable', 'parameter', 'angle', 'arithmetic', 'attribute', 'attributeBracket', 'bitwise', 'boolean', 'brace', 'bracket', 'builtinAttribute', 'builtinType', 'character', 'colon', 'comma', 'comparison', 'constParameter', 'derive', 'dot', 'escapeSequence', 'formatSpecifier', 'generic', 'label', 'lifetime', 'logical', 'macroBang', 'operator', 'parenthesis', 'punctuation', 'selfKeyword', 'semicolon', 'typeAlias', 'toolModule', 'union', 'unresolvedReference']
LSP: rust-analyzer: Supported semantic token modifiers: ['documentation', 'declaration', 'definition', 'static', 'abstract', 'deprecated', 'readonly', 'defaultLibrary', 'async', 'attribute', 'callable', 'constant', 'consuming', 'controlFlow', 'crateRoot', 'injected', 'intraDocLink', 'library', 'mutable', 'public', 'reference', 'trait', 'unsafe']
LSP: rust-analyzer: registering capability: textDocumentSync.save
```

**Comment by flodiebold** [comment]
Do you get inherent methods for other types?

**Comment by kornelski** [comment]
Nope, traits only:
<img width="463" alt="Screenshot 2022-07-15 at 17 24 25" src="https://user-images.githubusercontent.com/72159/179265976-d0a0cae0-fc42-4e41-b1d4-8a6a21bad520.png">

**Comment by flodiebold** [comment]
:confused: Does `"".bytes()` show up? If you write it out, can you invoke "go to definition" on it?

**Comment by kornelski** [comment]
I've discovered this was caused by the "[LSP-rust-analyzer](https://github.com/sublimelsp/LSP-rust-analyzer)" Sublime extension. If I *un*install the extension, rust-analyzer still works with Sublime, and autocomplete works fine.
