### ISSUE TITLE
Avoid analyzing everytime a comment is edited

### ISSUE THREAD

**Issue by Rudxain** [rust-lang/rust-analyzer#12752]
If a block comment is edited, the extension should be able to notice, and prevent itself from doing eager evaluation. When using the extension in VScode, it wastes time and energy analyzing the entire code, even though I only removed 1 char from a comment. It's also distracting, because for **every little change**, the editor loses all implicit annotations and then re-renders them after analyzing the code.

I searched for duplicate issues, but didn't find any

**Comment by Veykril** [comment]
That sounds very odd and not like the behavior most people observe, does this happen in all of your projects for all comments? Do you have any other extensions in VSCode that code interfere with r-a in this regard?

**Comment by Rudxain** [comment]
I now tested with extensions disabled, and again with extensions enabled. The implicit type annotations stay in-place, but it still runs `cargo --check` when I edit comments. It seems the problem with annotations only happens after using the extension for some minutes or hours

**Comment by flodiebold** [comment]
If you change the file and save, `cargo check` will be run, regardless of what you changed. Are you using autosave?

**Comment by Rudxain** [comment]
Tested now w/o AS, the problem is completely gone! Does the extension have a setting to make it interoperate better with AS? Otherwise, I wish this was an official feature

**Comment by flodiebold** [comment]
You can disable checkOnSave and trigger a check when you want to. I'm not sure what else we could do, to be honest.

**Comment by Rudxain** [comment]
I think I'll use both alternatives: disabling/enabling AS for when I need to switch frequently, and disabling `checkOnSave` for when I need longer periods.

I guess the issue can be closed for now
