### ISSUE TITLE
[vscode]Comment couldn't be link if it on impl T.

### ISSUE THREAD

**Issue by huang12zheng** [rust-lang/rust-analyzer#12757]
```rust
/// Look more by [IntoGVKSpec]
impl IntoGVKSpec for KnativeSpec {
...
}
```
[IntoGVKSpec] don't work.
```rust
/// Look more by [IntoGVKSpec]
something not impl IntoGVKSpec
```
[IntoGVKSpec] it work.

version
v0.4.1125(vscode)

**Comment by Veykril** [comment]
The problem is this branch here https://github.com/rust-lang/rust-analyzer/blob/794ecd58a32dfd9fdab0596b181133d4d2ae4b6f/crates/ide/src/doc_links.rs#L190 returning `None`, this might be somewhat tricky to fix

**Comment by Veykril** [comment]
This works now
