### ISSUE TITLE
Rust analyzer can't load file on vscode windows

### ISSUE THREAD

**Issue by nellyisanon** [rust-lang/rust-analyzer#12763]
![Screenshot (41)](https://user-images.githubusercontent.com/57329585/179000708-6c0f5632-b845-457d-a286-83e4730c7f59.png)

Rust analyzer can't load my files because it failed to read Cargo metadata from Cargo.toml file and it also says
--- std error: the 'rustc.exe' binary, normally provided by the 'rustc' component, is not applicable to the 'stable-x86_64-pc-windows-msvc' toolchain

The picture explains it in detail, how can i solve this?

**Comment by nellyisanon** [comment]
@flodiebold please can you check this out?

**Comment by flodiebold** [comment]
Does running `cargo check` or `cargo metadata` in the terminal work? Have you tried the [suggestion](https://users.rust-lang.org/t/rust-analyzer-failed-to-load-workspace/78374/2) in the users forum to reinstall the rustc component?

**Comment by nellyisanon** [comment]
Yes, I tried the suggestion. It works now thanks a lot.
