### ISSUE TITLE
Implement default members implements PartialEq::ne incorrectly

### ISSUE THREAD

**Issue by awused** [rust-lang/rust-analyzer#12779]
rust-analyzer version: rust-analyzer 0.0.0 (https://github.com/rust-lang/rust-analyzer/commit/5342f47f4276641ddb5f0a5e08fb307742d6cdc4 2022-07-09)

rustc version: rustc 1.62.0 (a8314ef7d 2022-06-27)

relevant settings: Neovim with coc-rust-analyzer

I tried `implement default members` on some code by mistake, but got surprising results. Reproduction:

```rust
struct SomeStruct {
    data: Arc<Vec<u8>>,
    field: (u32, u32),
}

impl PartialEq for SomeStruct {
}
```

It will generate this `ne` method:

```rust
impl PartialEq for SomeStruct {
    fn ne(&self, other: &Self) -> bool {
        self.data == other.data && self.field == other.field
    }
}
```

The `implement missing members` works as expected for `eq`

**Comment by lnicola** [comment]
I think this happens around https://github.com/rust-lang/rust-analyzer/blob/4cbf23c192517cfebb0d754987aae95bc683b7a4/crates/ide-assists/src/utils/gen_trait_fn_body.rs#L396, which doesn't seem to actually look at what method it's implementing.
