### ISSUE TITLE
Rust Analyzer doesn't show inlay hints even though they are enabled

### ISSUE THREAD

**Issue by FomalhautGH** [rust-lang/rust-analyzer#12799]
Rust Analyzer doesn't show inlay hints even though they are enabled as you can see in these images:

![Immagine 2022-07-18 150836](https://user-images.githubusercontent.com/74382647/179518277-2505970c-0dfa-44fe-ada1-03e800c1970f.png)
![Immagine 2022-07-18 150916](https://user-images.githubusercontent.com/74382647/179518389-8fc03fb6-62c0-4c5a-a11d-d84969225e61.png)

They stopped working randomly and now I can't turn them back on

**rustc version**: 1.62.0
**rust-analyzer version**: 0.3.1131

**Comment by lnicola** [comment]
Do you have anything in the logs, or in `settings.json`?

**Comment by FomalhautGH** [comment]
> Do you have anything in the logs, or in `settings.json`?

Nope

**Comment by FomalhautGH** [comment]
> Is this the whole source code? Can you reproduce the problem with a newly created Cargo project?

This is not the whole source code, but even with a newly created Cargo project I have this problem, alredy tried this several times

**Comment by lnicola** [comment]
What do you have in the `Rust Analyzer Client` and `Rust Analyzer Language Server` output channels?

![image](https://user-images.githubusercontent.com/308347/179522632-4c8251ca-4a3f-4c3d-8415-e4ad3dd67596.png)

**Comment by FomalhautGH** [comment]
In the `Rust Analyzer Client` I have this:
![otpinlay](https://user-images.githubusercontent.com/74382647/179524376-54ec0f94-f913-4a58-a326-ec2dc4e31450.png)

`Rust Analyzer Language Server` doesn't output anything

Also features like **go to definition** work without any problems

**Comment by lnicola** [comment]
Does the Toggle inlay hints command do anything?

**Comment by CGMossa** [comment]
I'm guessing your settings JSON, either user-wide or workspace wide has a 

```json
"editor.inlayHints.enabled": <true / false>
```

This is caused by the Rust Analyzer enable inlay hints button. This flag is no longer boolean, and should be a string instead.

**Comment by FomalhautGH** [comment]
Oh true, just fixxed it thanks

**Comment by CGMossa** [comment]
Yeah, but this needs to be fixed in Rust Analyzer...
