### ISSUE TITLE
Feature request: enable project auto-detection when linked-projects is set

### ISSUE THREAD

**Issue by martinmr** [rust-lang/rust-analyzer#12801]
I am working on a Tauri app on VSCode which means I have two separate folders with rust code in the directories `src-tauri` and `frontend`. `rust-analyzer` is not working automatically for these two codebases, so that means I have to set up the `linked-projects` manually. But this means I have to add all my projects to this list, even though it's only a couple of projects that have non-standard paths.

It'd be nice to have the option to allow auto-detection and linked projects to work together. This way I could add only two projects to the linked projects list and rely on auto-detection for the rest.

**Comment by flodiebold** [comment]
You can make this a workspace-local setting by putting it into `.vscode/settings.json` (IIRC) in the top folder. Does that solve your problem?

**Comment by martinmr** [comment]
Closing this. If anyone is wondering, creating a Cargo.toml file with the following contents at the top level of my project made the folder discoverable.

```
[workspace]
members = [
    'src-tauri',
]
```
