### ISSUE TITLE
Upcoming proc-macro ABI breakage

### ISSUE THREAD

**Issue by mystor** [rust-lang/rust-analyzer#12806]
The changes in https://github.com/rust-lang/rust/pull/98189 were just approved, and are likely to land soon, which will change the unstable proc-macro bridge ABI. I figured I'd file a bug to let you folks know about the changes earlier, in case it could help us reduce how long nightly+rust-analyzer remains broken for.

After these patches land I don't currently have any more patches posted which will break the ABI, though I'm experimenting with some other performance improvements and tweaks locally which will also lead to ABI breakage.

**Comment by fasterthanlime** [comment]
This can probably be closed as per https://github.com/rust-lang/rust-analyzer/issues/12803#issuecomment-1198366093

(It'll be "fixed for good" on monday, but there _is_ a version of `proc-macro-srv` that supports the latest ABI now).
