### ISSUE TITLE
extension on vscodium

### ISSUE THREAD

**Issue by Davide-Furlani** [rust-lang/rust-analyzer#12816]
I looked for this extension in vscodium and  found only what seems a copy of the original extension. it has the same icon but it's made by matklad, it has 55k download and 3 reviews, the description is "An alternate rust language server to the RLS".
So i decided to download the original extension from vscode marketplace and manually copy its folder to the vscodium extension folder (it worked fine with intellicode and other extensions, so i thought it could work also with this).
But then in vscodium looks like i installed the matklad version and not the original even though i copied the original one. It's working fine but i just want to know the reason of this strange behavior.

**Comment by Davide-Furlani** [comment]
thanks, i did it the way you recommended.

**Comment by lnicola** [comment]
You can also watch https://github.com/rust-lang/rust-analyzer/issues/7284 for OpenVSX support.
