### ISSUE TITLE
Move rust-analyzer from a git submodule to a git subtree

### ISSUE THREAD

**Issue by fasterthanlime** [rust-lang/rust-analyzer#12815]
(Related to: long-term proc macro support plan)

## Before (submodule)

RA is a git submodule [in src/tools](https://github.com/rust-lang/rust/tree/master/src/tools). When a "sync" happens, `rust-lang/rust` is updated to point to a different commit ([example](https://github.com/rust-lang/rust/pull/99176/files)).

The changes suggested in #12803 (use the sysroot `proc_macro` crate) make RA/rustc incompatibilities more visible in that the submodule could then stop building.

Fixing that would involve two PRs:

  * One to `rust-analyzer`, fixing `proc-macro-srv` to follow `proc_macro` bridge changes
  * One to `rust`, bumping `rust-analyzer`

If the sync cycle isn't changed, this means the rust-analyzer RA component could be missing for up to a week, or even more, if the bridge changes haven't been followed in the `rust-analyzer` repo.

## After (subtree)

Just like `clippy`, `rust-analyzer` would be a subtree (also in `src/tools`).

Feature development / bug fixes to RA happen as usual in the `rust-lang/rust-analyzer` repository. These can be synced to `rust-lang/rust` whenever convenient ([clippy->rust example PR](https://github.com/rust-lang/rust/pull/99406)).

Changes to the `proc_macro` bridge are followed in the `rust-lang/rust` repository. These can be synced to `rust-lang/rust-analyzer` whenever convenient ([rust->clippy example commit](https://github.com/rust-lang/rust-clippy/commit/f074034590bdcdfbf31114924df091017097f0fa))

**proc-macro-srv never breaks again** (in the rustup component version of rust-analyzer), because it's immediately fixed as part of any PRs to `rust-lang/rust`.

## Why does this matter?

A PR was _just merged_ to "[add support for the 1.64 ABI](https://github.com/rust-lang/rust-analyzer/pull/12795)", but there's no such thing as "the 1.64 ABI", and it's going to be instabroken, see https://github.com/rust-lang/rust-analyzer/issues/12806.

## Prior art

Similar discussion for rustfmt: https://github.com/rust-lang/rust/issues/82385 (converted to a subtree in [May 2021](https://github.com/rust-lang/rust/pull/82208))

---

Tagging:

  * @mystor who's been making proc_macro bridge changes, to confirm that `rust-lang/rust` folks are happy to keep the `proc-macro-srv` crate up-to-date with bridge changes (pinging other maintainers as needed)
  * @jonas-schievink who's been keeping the "multi ABI support" approach up-to-date by manually vendoring+tuning several copies of the `proc_macro` bridge in the rust-analyzer repo
  * @lnicola who's been doing most of the syncs I've seen in `rust-lang/rust` history
  * @jyn514 who discussed using subtrees [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/rust-analyzer.2312803/near/290046728)
  * @flodiebold, @Veykril, @bjorn3 who interacted with #12803 
  * @oli-obk who offered to connect with clippy folks in case RA folks have any questions about git subtree
  * @cuviper who started work on [getting RA tests to run on rust CI](https://github.com/rust-lang/rust/pull/99444)

**Comment by fasterthanlime** [comment]
## Proposed course of action:

  * S001: Convert `rust-analyzer` to a git subtree, pointing to the exact same revision it does now
  * S002: Tackle #12803 ("sysroot ABI") in the `rust-lang/rust` tree, taking extra care to cfg-gate it properly
  * S003: Sync in both directions, make sure `rust-lang/rust-analyzer` still builds on its own, on stable
  * S004: Discuss next steps required to improve the ergonomics of #12803 further, like:
    * Having the rust-analyzer LSP discover/use the "rustup rust-analyzer component's proc-macro subcommand"
    * Splitting `proc-macro-srv` into its own rustup component
    * Reaching out to IntelliJ Rust folks who currently pull the `proc-macro-srv` crate directly from r-a's git repo

**Comment by lnicola** [comment]
I haven't used subtrees yet, so I don't know how involved the switch would be, but I don't like git submodules very much. So this seems like a good idea, assuming the `rust-lang/rust` contributors are fine with doing the extra work for RA.

But will all breaking changes show up on CI? I'm not sure if the RA tests are being run in `rust-lang/rust`.

**Comment by fasterthanlime** [comment]
> But will all breaking changes show up on CI? I'm not sure if the RA tests are being run in `rust-lang/rust`.

@cuviper has done some work re: that in https://github.com/rust-lang/rust/pull/99444, see also https://github.com/rust-lang/rust-analyzer/issues/12803#issuecomment-1188508339

The intent was to track rust-analyzer status in [rust-toolstate](https://rust-lang-nursery.github.io/rust-toolstate/), but I believe it could be repurposed to run the `proc-macro-srv` tests on rust CI, blocking PR merges until they pass. (More tests could be run, but those are the important ones imho)

**Comment by fasterthanlime** [comment]
> So this seems like a good idea, assuming the `rust-lang/rust` contributors are fine with doing the extra work for RA.

@mystor seemed okay with it "provided it's relatively easy". I don't know about other proc_macro bridge maintainers.

I've done it once myself to get an idea of how much work it is (and @jonas-schievink can confirm/deny). It's mostly:

  * Removing functions that were removed from the bridge interface (in the various traits like FreeFunctions, Span, MultiSpan etc.)
  * Adding functions that were added to the bridge interface (a lot of things in `proc-macro-srv` are stubs right now, so this is relatively easy).
  * Following type/struct shape changes, see [this diff](https://github.com/rust-lang/rust-analyzer/compare/master...fasterthanlime:rust-analyzer:lol-abi#diff-d431bc980e150356de9b0dff1bacead8efac66c8a97c2d0deb6cfd42afae87f4L375-L388) for the recent move from `Group` being an assoc type to it being a struct.

**Comment by fasterthanlime** [comment]
For research purposes, I opened a draft PR on which `rust-analyzer` is a git subtree and `./x.py test rust-analyzer` runs RA tests:

  * https://github.com/rust-lang/rust/pull/99465

It shows how the move would happen. All tests pass through `./x.py test rust-analyzer` except for `tidy::check_merge_commits` — it might not make sense to run that one from the rust copy of rust-analyzer.

I also found clippy's _actual_ git subtree guide, which was immensely helpful (cc @lnicola):

  * https://github.com/rust-lang/rust-clippy/blob/master/book/src/development/infrastructure/sync.md
