### ISSUE TITLE
'Rust Analyzer: Run' command doesn't allow me to do a compile and run?

### ISSUE THREAD

**Issue by apotenza92** [rust-lang/rust-analyzer#12813]
Hi, when I select the 'Rust Analyzer: Run' command in VS Code I see the following, which only allows me to test or check.
![image](https://user-images.githubusercontent.com/53612685/179646487-88edc62f-73fe-4bb2-aec7-ecb80c2f155d.png)

Neither of these perform the same action as pressing the small Play run button above code in the editor, which compiles and then runs the code.
![image](https://user-images.githubusercontent.com/53612685/179646533-05fc7fa1-94f5-42db-a7ff-5f760c997758.png)

How do I perform the Play button version of a 'compile and run' command using the Rust Analyzer commands?

**Comment by apotenza92** [comment]
Not sure why or what I changed, but it's now appearing as a 'run' option...
![image](https://user-images.githubusercontent.com/53612685/179647975-9becbe28-0fa5-4bc7-bc44-b318b2481dec.png)

**Comment by apotenza92** [comment]
I tried re-creating a new project with `cargo new`, and it has happened again… The `Rust Analyzer: Run' doesn't detect any 'run' runnable command, and I haven't figured out what makes it appear as an option.

**Comment by jonas-schievink** [comment]
As per the [manual](https://rust-analyzer.github.io/manual.html#run), the "Run" command "Shows a popup suggesting to run a test/benchmark/binary **at the current cursor location**"
