### ISSUE TITLE
Jump to definition does nothing with cursor on `*=`

### ISSUE THREAD

**Issue by WhyNotHugo** [rust-lang/rust-analyzer#12810]
When the cursor is on operators like `+`, `+=`, `*=`, using the LSP action "jump to definition" does nothing.

It should jump to the definition of `impl Add<X> for Y`, `X` and `Y` depending on the current context too.

This is more of a feature request than a bug; I don't think any other LSP does this, but I it seems perfectly feasible -- especially where Rust where I'm sure this can be inferred.

**Comment by Veykril** [comment]
Hover should ideally also work here
