### ISSUE TITLE
Parsing issues around inline consts in match arms

### ISSUE THREAD

**Issue by fmease** [rust-lang/rust-analyzer#12824]
Syntax support for `#![feature(inline_const)]` was added in #7010 (rust-analyzer/ungrammar#17).
However, r-a fails to parse the following code whereas rustc accepts it:

```rust
fn f() {
    match () {
        () => const { &["--release"] }[..],
        //    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Syntax Error: expected FAT_ARROW
    }
}
```

**rust-analyzer version**: 0.3.1131-standalone (897a7ec4b 2022-07-17)

**rustc version**: rustc 1.64.0-nightly (f8588549c 2022-07-18)

**Comment by Veykril** [comment]
Oh this is a funny one, we parse the block expression, then due to a bug here we consider the expression finished and since its a block there is no need for a comma, so we parse the slice expression as the pattern of the next arm

**Comment by Veykril** [comment]
Interesting, so `const` blocks behave differently from normal blocks and `unsafe` blocks ...

**Comment by Veykril** [comment]
Though these errors aren't parsing errors in rustc, but type inference so I think this is overall a bug in the parser for us. I can see the `const` blocks being special in regards to their return value here to make them more useful I guess.

**Comment by Veykril** [comment]
Ah whoops I was testing it differently by accident

**Comment by Veykril** [comment]
You can go ahead and ask if you'd like

**Comment by fmease** [comment]
The discussion didn't lead to anything we could immediately act on. scottmcm added this issue to the list of unresolved questions on the tracking issue for inline consts (rust-lang/rust#76001). Seems like this r-a issue turns out to be _S-unactionable_?

**Comment by fmease** [comment]
Since rust-lang/rust#105142, `rustc` now correctly parses inline consts as *ExpressionWithBlock* instead of *ExpressionWithoutBlock* making the behavior of rustc & rust-analyzer equal & fixing this issue.
