### ISSUE TITLE
Incorrect "operation requires unsafe block" (regression)

### ISSUE THREAD

**Issue by massimiliano-mantione** [rust-lang/rust-analyzer#12839]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)

rust-analyzer version: 0.3.1131-standalone (897a7ec4b 2022-07-17)

**rustc version**: (eg. output of `rustc -V`)

rustc 1.56.1

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

Nothing relevant, vscode on Linux, but see below about a `rust-toolchain` file.

This is a sort of regression of #5996.
I have a workspace where I lock rust version using a `rust-toolchain` file, to be sure that I use the same one as CI does.

I had the version still locked to `1.56.1`, and now I am affected by #5996.
Downgrading rust-analyzer by one single release, or switching to the prerelease, did not fix the issue.

However, upgrading rust to `1.62.1 (e092d0b6b 2022-07-16)` (putting `1.62.1` in the `rust-toolchain` file) fixes the issue.
I will likely keep the upgrade as a workaround (sooner or later I would have upgraded anyway, and I am in the position to also upgrade the CI Dockerfile).

I am reporting this because I think the expectation is that rust-analyzer works with any rustc version, even older ones, and not just the current one.

**Comment by lnicola** [comment]
I take it you haven't seen the discussion in https://github.com/rust-lang/rust-analyzer/pull/12719?

**Comment by jonas-schievink** [comment]
Our Rust support policy is documented in the [manual](https://rust-analyzer.github.io/manual.html#toolchain):

> Only the latest stable standard library source is officially supported for use with rust-analyzer. If you are using an older toolchain or have an override set, rust-analyzer may fail to understand the Rust source. You will either need to update your toolchain or use an older version of rust-analyzer that is compatible with your toolchain.

Hence, closing.
