### ISSUE TITLE
Syntax Highlighting in attribute macros should consider the node

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#12842]
Highlighting currently just picks the first token mapping it finds and applies that as that is simple and fast. This has the problem that code in attributes may become very chaotic if the spans are used a lot.
See this snippet without the database attribute
![image](https://user-images.githubusercontent.com/3757771/180175866-f5c238f6-428e-42f3-a182-beb7e0e4e696.png)
and here with it (Note the `self` parameter and function name colors changing)
![image](https://user-images.githubusercontent.com/3757771/180175584-0f4b8ed1-197f-448e-b305-301140eebc78.png)

Syntax highlighting should attempt to prioritize a mapping that fits the input node syntactically and only pick a different one if there is no similar node to it.

**Comment by lnicola** [comment]
Looks like we don't resolve `self` here, is that expected?

**Comment by Veykril** [comment]
Yes that is expected, salsa doesn't re-use the token span for the self parameter.
