### ISSUE TITLE
Autocomplete for fields of structs is not working(as expected)

### ISSUE THREAD

**Issue by Rohithcheryala** [rust-lang/rust-analyzer#12857]
**Text Editor**: VS Code 
If I'm typing I field of struct I need self to be autocompleted for me by rust-analyzer, 
Im getting the suggestion as ```self.field``` but after accepting the suggestion it is being replaced by ```field``` (```self``` is missing).

Before:
![lib rs - raytracer  WSL_ Ubuntu  - Visual Studio Code 24-07-2022 00_25_48](https://user-images.githubusercontent.com/66206416/180619173-4841939b-1659-4061-b3a8-2327d9873033.png)

Hint is ```self.length``` and that is correct 
After:
![lib rs - raytracer  WSL_ Ubuntu  - Visual Studio Code 24-07-2022 00_28_12](https://user-images.githubusercontent.com/66206416/180619286-6b80c727-d4e5-46c8-ba89-1e92797b17e5.png)

It's being replaced by ```length``` not ```self.length```.

**rust-analyzer version**: 0.4.1133-standalone (30c4db10a 2022-07-19)

**rustc version**: rustc 1.64.0-nightly (7665c3543 2022-07-06)

**relevant settings**: everything default

**Comment by Veykril** [comment]
We are overwriting the insert text here https://github.com/rust-lang/rust-analyzer/blob/2be00623e4fb1edc6a8a13f1d1c55b3ea093a732/crates/ide-completion/src/render.rs#L135
but forget to account for when the receiver exists, so the label and insert text get out of sync.
