### ISSUE TITLE
VScode Rust analyzer is giving me false positive errors

### ISSUE THREAD

**Issue by alexhallam** [rust-lang/rust-analyzer#12853]
When I run `cargo check` no errors come up, but I have many lines in my code that print output which are all labelled as errors and unsafe. I have restarted Rust-Analyzer in Vscode and I have updated to the pre-release. I see the same problems either way.

![image](https://user-images.githubusercontent.com/9298693/180609693-06094748-ee27-43c2-96bb-eb6b74894b28.png)

**Comment by flodiebold** [comment]
You're probably using a somewhat outdated Rust version; updating to the current stable version should fix this.

**Comment by alexhallam** [comment]
Look like am using Rust 2021 from my cargo.toml. Is there a newer version? A nightly Rust?

**Comment by flodiebold** [comment]
That's the edition. You can tell the version e.g. with `rustc --version`; if you installed Rust with rustup, you can update with `rustup update`. You don't need the nightly version, just a recent stable is enough.

**Comment by alexhallam** [comment]
That did it! thanks!
