### ISSUE TITLE
Rust-analyzer restarts itself many times until it crashes with simple generics example

### ISSUE THREAD

**Issue by ThanosApostolou** [rust-lang/rust-analyzer#12865]
Hello, I'm new to rust but I have this problem:
I experimented with some generics code based on rust-book and rust analyzer seems to restart itself all the time until it crashes.
Error image: https://imgur.com/a/5vYy9uP
My example code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=757ff491be641b38fe838b6aa5691fb7
Rust-analyzer output: https://pastebin.com/nS7encBk

I killed all vs codes and rust-analyzer processes and retried with same outcome. If I comment out my "**fn largest()**" then it works and if I uncommented it does the same.

**rust-analyzer version**:  v0.3.1131

**rustc version**: 1.62.1

**relevant settings**: using simple rustup installation (https://rustup.rs/) without any custom configuration on arch linux

**Comment by Veykril** [comment]
This is most likely similar to https://github.com/rust-lang/rust-analyzer/issues/10932, the `impl ...` type you use trips up r-a when we try to render it

**Comment by lnicola** [comment]
I can't seem to reproduce this.

**Comment by Veykril** [comment]
Likely been fixed when the linked issue got fixed
