### ISSUE TITLE
Feature request: Open docs for symbol should support locally built documentation

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust-analyzer#12867]
Rust-analyzer has a feature to open the docs for the symbol under the cursor, but it always uses docs.rs.
One could be using different versions of crates that aren't on docs.rs, like git dependencies, and also your local crate(s) aren't on docs.rs either.

Open docs should do a best-effort  detection of locally built documentation (usually $TARGET_DIR/doc), and open that if the symbol is available under that, before falling back to docs.rs.

**Comment by Ddystopia** [comment]
Should it generate latest docs if they are not up to date?

**Comment by crumblingstatue** [comment]
That's a good question. Would there be any drawbacks to that behavior?
But I think this can be implemented later, and for now it could just detect whether local documentation exists and use it if available.

**Comment by lnicola** [comment]
Reopening because #14662 didn't add the client support for Code.
