### ISSUE TITLE
nix package dont updating 

### ISSUE THREAD

**Issue by AlePon123** [rust-lang/rust-analyzer#12869]
i trying to update rust-analyzer nix package but it dont updating
![image](https://user-images.githubusercontent.com/72556979/180761488-b41983ee-58c0-4c36-97ca-0bda6b86c712.png)
btw i installed nix 5 days ago

**Comment by lnicola** [comment]
I don't think we maintain any Nix package for RA, so you should try to figure out who does.

**Comment by bjorn3** [comment]
We aren't responsible for the nix package. The nix developers and community are. The latest version should be 2022-07-11 (https://github.com/NixOS/nixpkgs/pull/181088), but maybe that is only on a release channel other than what you are using or something? Not familiar with how nix works. In any case you are more likely to get help from the nix community.

**Comment by AlePon123** [comment]
ok, so i delete nix package and try to build from source with ```cargo xtask install --server```
but on buildindg proc-macro-srv crate its gives me errors 
![image](https://user-images.githubusercontent.com/72556979/180763578-7a94c083-c646-4f73-81f1-9a0cc151a9b4.png)

**Comment by lnicola** [comment]
What does `rustc -V` show?

**Comment by AlePon123** [comment]
> What does `rustc -V` show?

1.60.0

**Comment by lnicola** [comment]
You'll need at least 1.61 to build it. Latest version is 1.62.

**Comment by AlePon123** [comment]
can i update it by rustup?

**Comment by lnicola** [comment]
On Nix? I have no idea.
