### ISSUE TITLE
Test popup run suggestion doesn't show when function is attributed with "Test" within a cfg_attr

### ISSUE THREAD

**Issue by Nader-Sl** [rust-lang/rust-analyzer#12874]
**rust-analyzer version**: 0.3.1131-standalone (897a7ec4b 2022-07-17)

**rustc version**: 1.62.0 (a8314ef7d 2022-06-27)

Each attr on a line:
![Code_cSebNBpthD](https://user-images.githubusercontent.com/157133/180817086-72776d37-24a8-401a-a447-95b0c724d4bf.png)
Within cfg_attr:
![Code_0GhX8Tueub](https://user-images.githubusercontent.com/157133/180816937-a64f7ce6-86d6-43aa-8b33-f1e25e9f480e.png)

**Comment by jonas-schievink** [comment]
Does the second function have another `#[test]` attribute? If not, this is working correctly, because the `test` there is not an attribute, but a cfg flag that applies the `#[named]` attribute only.

**Comment by Nader-Sl** [comment]
> attribute

Right turns out Test is a built-in attribute and we can't seem to do anything about it to be able to inline it in a compound statement like with **proc_macro_attributes**.. 

Are you aware of a way that achieves what the second snippet is meant to do?

**Comment by jonas-schievink** [comment]
I'm not sure what you're trying to do, no

**Comment by Nader-Sl** [comment]
> I'm not sure what you're trying to do, no
 ```
 #[test]#[named] // A less savage 1-liner than this.
 pub fn test(){ ... }
 ```

**Comment by jonas-schievink** [comment]
I don't know, I guess you can make `#[named]` expand to `#[test]` or something?

Since this is not a rust-analyzer bug, closing.
