### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by AlePon123** [rust-lang/rust-analyzer#12872]
@matklad how do you complie rust projects on nix os? From nix-shell?

**Comment by matklad** [comment]
That's out of scope, but I just use nix-packaged rustup (https://github.com/matklad/config/blob/e959d387fe26dba8771b5fd55a740ba3f57c05d6/hosts/default.nix#L79) and otherwise just `cargo build`. I don't generally use `shell.nix` and the link.
