### ISSUE TITLE
[Question] Project-depending config

### ISSUE THREAD

**Issue by TornaxO7** [rust-lang/rust-analyzer#12875]
Hello, is it possible to have something like a `rust-anaylzer.toml` for each individual project to have specifique `rust-analyzer`-settings set like special features and so on? I'm using neovim with lsp-config if this can help.

**Comment by bjorn3** [comment]
For vscode you can put project specific settings inside a .vscode/settings.json in your project directory. As for neovim, I'm not sure it supports anything like this. Maybe you could use conditionals in your neovim config?

**Comment by csmoe** [comment]
It's more like a editor/ide feature, not rust-analyzer.
As for neovim you can load the local settings with https://github.com/neovim/nvim-lspconfig/wiki/Project-local-settings#configure-in-your-personal-settings-initlua

**Comment by TornaxO7** [comment]
Ok, thank you for your answers!
