### ISSUE TITLE
completion not work

### ISSUE THREAD

**Issue by zzwxh** [rust-lang/rust-analyzer#12883]
![图片](https://user-images.githubusercontent.com/102860856/181095768-fa706ef9-0931-43b9-a663-75aa522a9cb6.png)
![图片](https://user-images.githubusercontent.com/102860856/181095834-fcfcf94a-125e-4cd9-a62f-5c18ea8d9f2b.png)
socket.r(ead)  -> works
let a = socket.r(ead) -> not work

**Comment by zzwxh** [comment]
completion not work with Tokio::select{}

**Comment by Xiang929** [comment]
same problem. I can not get completion in tokio::select! and tokio::pin!
rust-anallyzer version: v0.4.1389 nightly
