### ISSUE TITLE
Bug: didn't catch panics

### ISSUE THREAD

**Issue by Banyc** [rust-lang/rust-analyzer#12907]
**rust-analyzer version**: 0.3.1140-standalone (7e2b983fd 2022-07-24)

**rustc version**: rustc 1.62.1 (e092d0b6b 2022-07-16)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

When panicking, the debug session exited without catching the source of panic. But the breakpoint is still working fine. It is on VSCode.

**Comment by lnicola** [comment]
We don't have any support for debugging except pointing your debugging extension (CodeLLDB, Native Debug) in the right direction. Those extensions may or may not have support for catching exceptions when they are thrown.

**Comment by lnicola** [comment]
In CodeLLDB it's these ones, but they don't work for me either:

![image](https://user-images.githubusercontent.com/308347/181693950-354f8e9f-2877-4bdd-b7ba-4740de166a37.png)

Acutally, it doesn't work at all: https://github.com/rust-lang/rust/issues/21102.

**Comment by Banyc** [comment]
@lnicola I have crossposted it to CodeLLDB, and hope this issue can be settled

**Comment by lnicola** [comment]
It's not actually  CodeLLDB either, since neither `lldb`, nor `rust-lldb` work. You might need to put breakpoints on `rust_panic` and `rust_begin_unwind` instead.

**Comment by Banyc** [comment]
@lnicola This issue only happens recently, not a problem before, so I think there is a newly introduced bug somewhere.

**Comment by lnicola** [comment]
Ah, them maybe try compiling with an older Rust version.

**Comment by Banyc** [comment]
# Solution

<img width="289" alt="image" src="https://user-images.githubusercontent.com/36535895/181730145-2dc90a4c-af79-4e10-8264-49aabfbfa657.png">

add the `rust_panic` breakpoint
