### ISSUE TITLE
feature request: deeper display for outline functions

### ISSUE THREAD

**Issue by R3XP** [rust-lang/rust-analyzer#12908]
I think that it would be nice to have the outline go deeper into functions and also show match arms as an entry
![image](https://user-images.githubusercontent.com/30810131/181777601-f664a002-287b-43c4-a537-3480a6d41f20.png)

**Comment by flodiebold** [comment]
I think that would be far too cluttered. The outline is supposed to be an outline, not a complete syntax tree.

**Comment by jonas-schievink** [comment]
Yeah, the outline is just meant to be an item-level outline of the code. What's the use case for making it so detailed? Maybe there's a better way to show the information you're looking for.

**Comment by R3XP** [comment]
I personally just like the feeling of the outline in my react project, where I can easily find functions in the outline even when I just remember the code vaguely (as you can see below) - but it's probably just a personal preference ^^
![image](https://user-images.githubusercontent.com/30810131/182044121-b937d9c6-512f-409f-ae68-0da2f949aaef.png)


about the clutter tho - you could just close the tabs down if you dont want them to clutter the outline afaik

**Comment by lnicola** [comment]
We can (and do) show nested items:

![image](https://user-images.githubusercontent.com/308347/182044232-abbdf4c0-b8d0-46f8-877c-cb181c44a3e9.png)

But I don't think it makes sense to show function calls or match arms. Does that even happen in the screenshot you've posted?

**Comment by R3XP** [comment]
Well yes and no - the useEffect() is a function call, however afaik there are no match statements in react ^^"

**Comment by bjorn3** [comment]
> the useEffect() is a function call

It has a special meaning in react that has non-local effects. The outline doesn't show all function calls for react either.

**Comment by lnicola** [comment]
I don't know much about React, but I imagine JavaScript still has `switch`?

We show items in the outline (functions, traits, structs, impls), but not expressions. I don't think we should include local variables or match arms. Those often look like this:

![image](https://user-images.githubusercontent.com/308347/184314982-f8ddb04c-2cfa-4227-8cd5-60f6d00324db.png)

**Comment by jonas-schievink** [comment]
Closing this as wontfix. As mentioned before, the outline is meant for items, not arbitrarily small syntax like match arms.
