### ISSUE TITLE
hover over associated functions should show the impl block they are defined in

### ISSUE THREAD

**Issue by veber-alex** [rust-lang/rust-analyzer#12917]
consider this code:
```rust
struct Foo<T>(T);

impl<T: Eq> Foo<T> {
    fn new(t: T) -> Self {
        Self(t)
    }
}

fn main() {
    let foo = Foo::new(1.2);
}
```

This doesn't compile because `f64` doesn't implement `Eq`, however the hover and popup that shows for new has no mention of the bound `T: Eq` from the impl block.
It just shows:
```rust
playground::Foo
fn new(t: T) -> Self
```

I think it should also show the impl block definition, as that is an integral part of the functions signature:
```rust
playground::Foo
impl<T: Eq> Foo<T>
fn new(t: T) -> Self
```

**Comment by macovedj** [comment]
Interested in giving this a shot

**Comment by roife** [comment]
I have tried to implement it.

<img width="328" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/17700217/8063a978-0cef-402d-abaf-3a0fd879a1b6">

I’m not quite satisfied with how we present it (it looks a bit cluttered currently). Maybe we should add a user config to control whether the container is displayed. Any suggestions for improvement?

**Comment by roife** [comment]
Or perhaps we can merge the bounds from the container with the bounds from the function itself, for example:

```rust
fn new(t: A) -> Self
where
    A: Eq // from impl
```

```rust
fn new<T>(a: A, b: B) -> Self
where
     T: Default,
     A: Eq, // from impl
     B: Ord, // from impl
```

**Comment by Veykril** [comment]
Rendering where clauses in the impl does look very messy, rendering them after the function looks like the better option I Ithink

**Comment by roife** [comment]
> Rendering where clauses in the impl does look very messy, rendering them after the function looks like the better option I Ithink

Agreed. How about

```rust
impl<A> Foo<A>
fn new<T>(a: A, b: B, c: T) -> Self
where
     T: Default,
     A: Eq, // from impl
     B: Ord, // from impl
```

**Comment by Veykril** [comment]
👍

**Comment by roife** [comment]
![telegram-cloud-photo-size-5-6275829861461376671-x](https://github.com/rust-lang/rust-analyzer/assets/17700217/f8aede48-7c77-47fc-9e19-6e3ba58b2d89)

Should we keep the first line (`impl<A> Foo<A>`) here? It's a bit redundant.

**Comment by Veykril** [comment]
It's not redundant as it clarifies what `A` is (a type parameter), though it does look a bit odd 🤔
