### ISSUE TITLE
Import completion adds use statement for local crate twice

### ISSUE THREAD

**Issue by gampx** [rust-lang/rust-analyzer#12924]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer 0.3.1140-standalone (7e2b983fd 2022-07-24)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.64.0-nightly (87588a2af 2022-07-13)
**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
nvim + coc-rust-analyzer

If I choose completion that uses type from local library, RA adds autoimport twice. When I chose smth from standard library it adds only once, like it should.
<img width="744" alt="image" src="https://user-images.githubusercontent.com/7108559/182200970-3690f4ad-2c74-4354-888b-69a119f11eaf.png">
<img width="616" alt="image" src="https://user-images.githubusercontent.com/7108559/182201053-51700f67-0b48-48bb-a044-7e271307ebb8.png">

**Comment by nyxtom** [comment]
I'm seeing this as well upon importing from auto complete. This only started happening in the last few versions

![image](https://user-images.githubusercontent.com/222763/183460892-b97b0fa6-c75c-4bdd-82ee-11a79a114467.png)

**Comment by Veykril** [comment]
This sounds like a client problem to me (though maybe we did a mistake with some LSP stuff again), since VSCode doesn't have this problem. Will dig around in recent changes to `to_proto`

**Comment by Veykril** [comment]
@nyxtom Which editor are you using? Also nvim + coc-rust-analyzer?

**Comment by nyxtom** [comment]
> @nyxtom Which editor are you using? Also nvim + coc-rust-analyzer?
> 
> I don't see anything that might've changed in r-a that could cause this so I am inclined to say that this might be a client error, assuming something in coc-rust-analyzer has changed.

vim + coc-rust-analyzer v0.65.3

**Comment by nyxtom** [comment]
It only happens on local crate imports

**Comment by nyxtom** [comment]
Actually @Veykril looks like it was an out of date coc.nvim issue. Carry on!

**Comment by Veykril** [comment]
@gampx do you also run an older coc.nvim? Could you check if updating fixes it for you?

**Comment by gampx** [comment]
Problem is gone after updating coc.nvim. Thanks!
