### ISSUE TITLE
Feature Request: Alphanumeric sort of `use ..;`

### ISSUE THREAD

**Issue by elbaro** [rust-lang/rust-analyzer#12925]
rust-analyzer lexicographically sorts the use statements.
When there are numbers in the module names, some might want alphanumeric sorts instead:

```rs
use tree1;
use tree10;  // expects tree2 here
use tree2;
..

use tree9;   // expects tree10 here
```

**Comment by Veykril** [comment]
Do you mean sorting on save? That happens due to rustfmt, not r-a

**Comment by lnicola** [comment]
I imagine flyimport doesn't do this either, does it?
