### ISSUE TITLE
"unresolved extern crate" when importing rustc crates from a locally built toolchain

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#12926]
To reproduce, first locally build a rustc (`./x.py build compiler --stage 2`), then check out [Miri](https://github.com/rust-lang/miri/), configure it for RA as shown below, and open it in vscode. Now open the `src/lib.rs` file. There are errors for `extern crate rustc_middle;` and all the other rustc crate imports: "unresolved extern crate".

A `./miri check` works fine, so the crates do exist, but RA somehow fails to find them.

**rust-analyzer version**:  rust-analyzer version: 0.3.1148-standalone (2b472f668 2022-07-31)

**rustc version**: locally built rustc master

**relevant settings**:
```json
// Place your settings in this file to overwrite default and user settings.
{
    "rust-analyzer.rustc.source": "discover",
    "rust-analyzer.linkedProjects": [
        "./Cargo.toml",
        "./cargo-miri/Cargo.toml"
    ],
    "rust-analyzer.checkOnSave.overrideCommand": [
        "./miri",
        "check",
        "--message-format=json"
    ],
    "rust-analyzer.buildScripts.overrideCommand": [
        "./miri",
        "check",
        "--message-format=json",
    ],
    "rust-analyzer.rustfmt.extraArgs": [
        "+nightly"
    ],
}
```

**Comment by bjorn3** [comment]
`"rust-analyzer.rustc.source": "discover"` doesn't work for linked toolchains as the rust-src component is absent. You need to manually point it to the root `Cargo.toml` of your rust checkout.

**Comment by RalfJung** [comment]
I switch between linked toolchains and downloaded toolchains all the time, so that is not a solution.

Why can't RA auto-discover linked toolchains? Miri for example auto-discovers the rust-src location for both linked and installed toolchains just fine.

**Comment by Explainaur** [comment]
I have the same issue.

**Comment by Veykril** [comment]
I'm not sure how this all works, so I'm just gonna lay out what r-a does right now for discovering. First it checks if `RUST_SRC_PATH` is set, and uses that if it is. Otherwise r-a invokes `rustc --print sysroot` with the containing directory of the workspace toml as the working directory, then checks whether `{sysroot}/lib/rustlib/src/rust/library` exists to use that as the path. What is miri doing differently here, what should we maybe do differently here?

**Comment by RalfJung** [comment]
Yeah `{sysroot}/lib/rustlib/src/rust/library` works for normal toolchains but not for linked toolchains. I can't find where Miri even has that logic, but for a linked sysroot, the folder is `$(rustc --print sysroot)/../../../library`.

**Comment by RalfJung** [comment]
Oh, Miri doesn't have that logic any more since `$(rustc +rustc.2-s1 --print sysroot)/lib/rustlib/src` is a symlink so these things work even without doing something special on the Miri side.

Could R-A be confused by the symlink?

**Comment by Veykril** [comment]
Ah wait, the `rustc` that is being invoked there is not the installed toolchain one right? (well in your case miri but whatever). I imagine that might be the problem then? I'll add some logging for the sysroot stuff that way you should be able to tell what might be going on here (I don't feel like building rustc myself tbh)

**Comment by RalfJung** [comment]
The override in the Miri folder is set to the linked toolchain. So `rustc --print sysroot` in the Miri folder should print the right folder.

The rustc build will take a bit before I can provide logs.

**Comment by Veykril** [comment]
How is the override specified? It might not work for r-a here depending on how you set the override and where

**Comment by RalfJung** [comment]
> How is the override specified? It might not work for r-a here depending on how you set the override and where

`rustup override set`

**Comment by Veykril** [comment]
Added some logging to emit the sysroot and rustc paths being used https://github.com/rust-lang/rust-analyzer/pull/13441

**Comment by RalfJung** [comment]
The RA_LOG you suggested prints this several times
```
[DEBUG project_model::sysroot] Discovering sysroot for /home/r/src/rust/miri
[DEBUG project_model::sysroot] Discovering sysroot by "rustc" "--print" "sysroot"
[DEBUG project_model::sysroot] Checking sysroot: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/src/rust/library
[DEBUG project_model::sysroot] Discovering rustc source for /home/r/src/rust/miri/./Cargo.toml
[DEBUG project_model::sysroot] Discovering sysroot by "rustc" "--print" "sysroot"
[DEBUG project_model::sysroot] Checking for rustc source code: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/rustc-src/rust/compiler/rustc/Cargo.toml
[DEBUG project_model::sysroot] Discovering sysroot for /home/r/src/rust/miri/./cargo-miri
[DEBUG project_model::sysroot] Discovering sysroot by "rustc" "--print" "sysroot"
[DEBUG project_model::sysroot] Checking sysroot: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/src/rust/library
[DEBUG project_model::sysroot] Discovering rustc source for /home/r/src/rust/miri/./cargo-miri/Cargo.toml
[DEBUG project_model::sysroot] Discovering sysroot by "rustc" "--print" "sysroot"
[DEBUG project_model::sysroot] Checking for rustc source code: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/rustc-src/rust/compiler/rustc/Cargo.toml
```
Some of the paths it mentions indeed exist (`/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/src/rust/library`) but others do not (`/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/rustc-src/rust/compiler/rustc/Cargo.toml`).

**Comment by RalfJung** [comment]
So looks like we have to extend whatever code sets up the symlink in `lib/rustlib/src/rust` to also set up the same symlink at `lib/rustlib/rustc-src/rust`?

**Comment by Veykril** [comment]
Ye I would guess so? This is what r-a is doing fwiw https://github.com/rust-lang/rust-analyzer/blob/82ac6f7d4835c5cc27b5be92fee00200dbba43bb/crates/project-model/src/sysroot.rs#L219-L238

Just simply append the path to the sysroot, and I don't think there is much more we can do from our side? Though it's odd, how does rust do this then ...

**Comment by RalfJung** [comment]
Indeed I can confirm that https://github.com/rust-lang/rust/pull/103347 fixes this problem. :)
