### ISSUE TITLE
Rust Analyzer fails to read metadata or cargo fails to lock file (os error 5)

### ISSUE THREAD

**Issue by tomashla** [rust-lang/rust-analyzer#12922]
Hello,
I know there was someone with the same problem, but I was not able to fix it following that conversation.
I usually run into issues with rust regarding os error number 5, it is not only with rust-analyzer.
Usually analyzer fails to read metadata or cargo fails to lock fail cargo.lock. It is probably very primitive error but I am not super skilled, so I am kinda hopeless, thanks for any advise. The error looks like this:

rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file c:\Users\pc\Documents\Rust\activities\Cargo.toml, cargo 1.62.1 (a748cf5a3 2022-06-08): Failed to run `"cargo" "metadata" "--format-version" "1" "--manifest-path" "c:\\Users\\pc\\Documents\\Rust\\activities\\Cargo.toml" "--filter-platform" "x86_64-pc-windows-msvc"`: `cargo metadata` exited with an error: error: failed to lock file: c:\Users\pc\Documents\Rust\activities\Cargo.lock Caused by: Přístup byl odepřen. (os error 5)

**Comment by lnicola** [comment]
Does it happen every time? Can you run `cargo metadata` inside your project?

**Comment by tomashla** [comment]
It did not, but now it does. But I am able to run cargo metadata without any problems.

**Comment by tomashla** [comment]
> For reference google translate gives "Access Denied" as translation for the error message.

Yeah, that is correct, the previous is just written in my native lang.

**Comment by tomashla** [comment]
> Does it happen every time? Can you run `cargo metadata` inside your project?

It did not, but now it does. But I am able to run cargo metadata without any problems.

**Comment by lnicola** [comment]
@tomashla did you end up figuring this out? It might be some AV or other software interfering with `cargo`.

**Comment by tomashla** [comment]
Thank you, in the end, the AV was blocking it - Norton more precisely. I recommend that AV but blocking cargo and my Rust binaries drives me crazy. Nevertheless, thank you for asking.
