### ISSUE TITLE
Feature request: "Stop RA server" VSCode action

### ISSUE THREAD

**Issue by moxian** [rust-lang/rust-analyzer#12936]
Sometimes I open a folder in my VScode to use the latter as a mere text editor, not a fully-fledged IDE.
Sometimes said folder happens to contain `Cargo.toml` and a hefty rust project within, which makes RA spin up, consume CPU and RAM, while providing no benefits for me.

In those situations i wish i could `ctrl+shift+P` -> `Rust Analyzer: Stop server` but that one is not an option presently.

This is a feature request to provide said option. It would - presumably - do the same thing as `Rust Analyzer: Restart server`, but without the "start" part.

**Comment by repi** [comment]
There is nowadays a "rust-analyzer: Cancel running flychecks" that I think is supposed to do this, but I've found it generally doesn't work or takes a long time until it cancels running builds (would expect it to cancel/abort it immediately)

**Comment by Veykril** [comment]
A stop command still seems like a good addition. `Cancel running flychecks` not being immediate is a bit odd though, it certainly should 😕
