### ISSUE TITLE
Wrong type mismatch with `cfg_if!` in function body

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#12940]
This code reports an incorrect "expected `MemoryUsage`, found `()`" type mismatch error:

https://github.com/rust-lang/rust-analyzer/blob/0fe3bcfd3524a023a11c95d0615178e897f72200/crates/profile/src/memory_usage.rs#L28-L55

Might be due to incorrect handling of macros in block tail position.

**Comment by jonas-schievink** [comment]
Reduced to:

```rust
macro_rules! m2 {
    ($($t:tt)*) => {$($t)*};
}

pub fn macrostmts() -> u8 {
    m2! { 0 }

    m2! {}
}
```

The HIR looks like this:

```
fn macrostmts(…) {
    { // macro statements
        0
    }
    { // macro statements
    
    }
}
```

so it seems that an empty `MacroStmts` expression is treated like an empty block, which is wrong.

**Comment by Veykril** [comment]
Might've regressed in https://github.com/rust-lang/rust-analyzer/pull/12668
