### ISSUE TITLE
Non-existent rust-analyzer version bundled in VSCode extension

### ISSUE THREAD

**Issue by leighmcculloch** [rust-lang/rust-analyzer#12954]
**rust-analyzer version**: `0.3.1148-standalone (2b472f668 2022-07-31)`

**rustc version**: `rustc 1.62.1 (e092d0b6b 2022-07-16)`

**relevant settings**: N/A

With the latest VSCode rust-analyzer, the `Show RA Version` command displays a version that is not an officially released version of rust-analyzer. It lists `2b472f668 2022-07-31`, but in the releases page there is no corresponding 2022-07-31 release: https://github.com/rust-lang/rust-analyzer/releases/tag/2022-07-31.

**Comment by Veykril** [comment]
The date of the version command is the date of the commit, not the date the release happened

**Comment by leighmcculloch** [comment]
Interesting. I see now that version `2022-07-31` is release `2022-08-01`.

**Comment by flodiebold** [comment]
Looks lke this has been clarified.

**Comment by lnicola** [comment]
It would be nicer to show the release date, but it's only a cosmetic issue.

**Comment by leighmcculloch** [comment]
Given the git commit hash is visible it is probably not critical to fix, it is just confusing given the release date is used as the version in some places but then that version is not outputted.

**Comment by Veykril** [comment]
This output is of the same form as other rust tools have (cargo, rustfmt, ...) which is why we do it the same way
