### ISSUE TITLE
Turning off "implementations" code lens has gone wild

### ISSUE THREAD

**Issue by atlx** [rust-lang/rust-analyzer#12952]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
rust-analyzer version: 0.3.1148-standalone (2b472f668 2022-07-31)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.57.0 (f1edd0429 2021-11-29)

https://user-images.githubusercontent.com/41349879/183222477-80289dc7-e359-4cef-8182-6bda072f1b44.mp4

**Comment by Veykril** [comment]
I can't reproduce this, so this might be another extension messing with your settings?

**Comment by atlx** [comment]
> 

I went to disable it on settings.json, and it's still up as true on the GUI + it appears on the editor... Hmm.

**Comment by atlx** [comment]
> I can't reproduce this, so this might be another extension messing with your settings?

Just tried disabling all extensions and left only rust-analyzer enabled -- same thing.

**Comment by veber-alex** [comment]
I had this issue in the past.
It's caused by some old rust-analyzer setting in settings.json that keeps reverting the change you do, however I don't remember what it is.
Try commenting out all settings starting with "rust-analyzer" and then disabling the lens via the gui.

**Comment by atlx** [comment]
> I had this issue in the past.
It's caused by some old rust-analyzer setting in settings.json that keeps reverting the change you do, however I don't remember what it is.
Try commenting out all settings starting with "rust-analyzer" and then disabling the lens via the gui.

Resolved itself when I removed some random rust-analyzer settings in `settings.json`.
