### ISSUE TITLE
Incorrect display implementation for assignment operators

### ISSUE THREAD

**Issue by atynagano** [rust-lang/rust-analyzer#12971]
https://github.com/rust-lang/rust-analyzer/blob/90357a9090a88b2f7bc5db5d05cb576680ce2960/crates/syntax/src/ast/operators.rs#L113-L119

Isn't the order reversed?

```rs
 BinaryOp::Assignment { op } => { 
     if let Some(op) = op { 
         fmt::Display::fmt(op, f)?; 
     } 
     f.write_str("=")?; 
     Ok(()) 
 } 
```

**Comment by lnicola** [comment]
I think so. Do you want to file a PR?

**Comment by atynagano** [comment]
I don't know how to do it. If you can, I'll leave it to you.
