### ISSUE TITLE
Request: always import from `core` when possible

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-analyzer#12979]
Now that we no longer need to use `extern crate core` to use paths into the `core` crate, I would like an RA setting to *always* select the `core` path for an item whenever possible. For example, if importing `Debug`, prefer `core::fmt::Debug` to `std::fmt::Debug`.

I often want to develop crates that are fundamentally `no_std`, but use printing during debugging, so I don't actually turn on `no_std` until the moment of publishing, at which point I have to fix any imports that RA made. If RA could just always prefer `core` this would help me.

**Comment by lnicola** [comment]
I thought we actually had some form of auto-detection here. It would be nice to automatically use `core` if the current file already has imports from there.
