### ISSUE TITLE
Information security

### ISSUE THREAD

**Issue by thirdreplicator** [rust-lang/rust-analyzer#12970]
Hi,

  I use nvim (w/ rust-analyzer) and sometimes I might open up a password file on occasion. rust-analyzer doesn't have any need to send my tokens over the network, right?

  Thanks!

**Comment by lnicola** [comment]
It doesn't, but you could still run into a malicious Rust crate that steals your data.

See https://rust-analyzer.github.io/manual.html#privacy.
