### ISSUE TITLE
Feature request: `if x.is_some()` -> `if let Some(_tmp) = x`

### ISSUE THREAD

**Issue by vi** [rust-lang/rust-analyzer#12977]
Before:

```rust
if x.is_┃some() {
    ...
}
```

After:

```rust
if let Some(┃_tmp) = x {
    ...
}

```

**Comment by ice1000** [comment]
I'll take it, it seems useful

**Comment by vi** [comment]
Maybe transformation of `if my_result.is_ok() {` to `if let Ok(_x) = my_result {` should be implemented along the way?

**Comment by Young-Flash** [comment]
@ice1000 hi, would you like to make it? if you have no time, I'd like to try. seems interesting.

**Comment by ice1000** [comment]
> @ice1000 hi, would you like to make it? if you have no time, I'd like to try. seems interesting.

I checked a bit and I found an entire assist too involved. I got too confident about myself after modifying a bit of existing assists. Please give it a shot!
