### ISSUE TITLE
Wrong record completion after match

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#12975]
```rust
enum Enum {
    Var { field: u8 }
}

fn f(e: &Enum) {
    match e$0
}
```

Requesting completions here returns a reasonable result, but then typing a space afterwards results in incorrect `&Enum::Var {...}` and `Enum::Var {...}` completions.

Weirdly, this does not happen when typing a space while no completions are displayed. You have to request them right after the `match` and *then* type space.

**Comment by Veykril** [comment]
We are probably putting the ` {...}` part in the `lookup` field which causes this odd behavior.
