### ISSUE TITLE
feature: Show inline type hint with different font for better visibility

### ISSUE THREAD

**Issue by sehz** [rust-lang/rust-analyzer#12988]
Currently, inline-type hints can be distracting.  It's hard to tell whether it belongs to the actual code.  It would be much better if type hints were shown with a different font or other visibility hints.

**Comment by bjorn3** [comment]
You can set the `editor.inlayHints.fontFamily` config for this. This will change the font for all inlay hints independent of the language, so it for example changes typescript inlay hints too.

**Comment by sehz** [comment]
That works nicely with `Fira Code`.  Closing.
