### ISSUE TITLE
Code action to transform between `foo_or` and `foo_or_else`

### ISSUE THREAD

**Issue by A-Walrus** [rust-lang/rust-analyzer#12983]
The standard library has a bunch of functions with two variants such as `unwrap_or` and `unwrap_or_else`, `ok_or` and `ok_or_else`.
The code action would transform for example:
`a.unwrap_or(calculate(x))` -> `a.unwrap_or_else(|| calculate(x))`
`a.unwrap_or(calculate())` -> `a.unwrap_or_else(calculate)`
and back
`a.unwrap_or_else(|| 5)` -> `a.unwrap_or(5)`

same for the other functions with `or` and `or_else` variants.

clippy currently has lints that warn against these, and suggests fixes, but it would be nice to have a code action for it :)
[clippy::or_fun_call](https://rust-lang.github.io/rust-clippy//master/index.html#or_fun_call)
[clippy::unnecessary_lazy_evaluations](https://rust-lang.github.io/rust-clippy//master/index.html#unnecessary_lazy_evaluations)

**Comment by Austaras** [comment]
Seems like it's impossible to get type arbitrary expression in code action?

**Comment by flodiebold** [comment]
@Austaras what do you mean?

**Comment by Austaras** [comment]
For code like
```rs
let a = Some(1);
a.unwrap_or(2);
```
It doesn't seem to be possible in code assist to know the type of `a` before `unwrap_or`?

**Comment by flodiebold** [comment]
Sure it is, just call `Semantics::type_of_expr` on the node. If you're developing against a unit test, you have to keep in mind though that you don't have the standard library in those tests. For `Option`, you can just add `//- minicore: option` to the top of the test code to get it.
