### ISSUE TITLE
why loading metadata so slow???

### ISSUE THREAD

**Issue by yuyang-ok** [rust-lang/rust-analyzer#12995]
![image](https://user-images.githubusercontent.com/96557710/184078739-0201f8e0-e2c2-43b5-bd39-e659b38e3d7d.png)

**Comment by yuyang-ok** [comment]
rust-analyzer on my local machine always loading metadata,I think it will never finish.

**Comment by lnicola** [comment]
If it's the first time you're opening the project, we call `cargo metadata`, which might need to update the cargo registry. That often takes a couple of minutes.

Try to see if a `cargo` process is running.

**Comment by yuyang-ok** [comment]
thanks , this is slow just because My network is too slow?

**Comment by lnicola** [comment]
No, it's downloading the whole list of crates from a GitHub repository. My network is fast, but I still don't like waiting when it happens.

You can close RA and run `cargo metadata` and/or `cargo check` in a terminal, then try to load the project again.

**Comment by yuyang-ok** [comment]
ok , thanks.

**Comment by lnicola** [comment]
It might also be a build script compiling some native code or something else, I'm not exactly sure when that message gets displayed.

**Comment by yuyang-ok** [comment]
I think it did't compile native code.

**Comment by yuyang-ok** [comment]
looks it running.
~~~
 /home/yuyang/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo check --quiet --workspace --message-format=json --all-targets
~~~
this is slow because of `all-targets` parameter??

**Comment by yuyang-ok** [comment]
cargo check have been run over 10 minutes, looks like it not going to finish.

**Comment by lnicola** [comment]
> this is slow because of all-targets parameter??

No, it's probably slow because GitHub is throttled or blocked in China. Does `cargo check --all-targets` work for you? Are you using a proxy?

**Comment by yuyang-ok** [comment]
`cargo check --all-targets` run outside is also very slow.
I am using proxy.

**Comment by yuyang-ok** [comment]
sometime it's not very slow.sometime very slow.
