### ISSUE TITLE
Complete extern crates in extern crate items

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#13002]
`extern crate $0` we should complete all crates names from the extern crate prelude for the current crate here

**Comment by Spaceface16518** [comment]
I figure this issue is low-priority, so I'm going to try to use it to get into contributing to rust-analyzer.

@rustbot claim

**Comment by Veykril** [comment]
This requires adding a corresponding variant here https://github.com/rust-lang/rust-analyzer/blob/f1b257f4eb4fef74b42fd7135d1cf3884e8b51c9/crates/ide-completion/src/context.rs#L291-L302
constructing it here https://github.com/rust-lang/rust-analyzer/blob/f1b257f4eb4fef74b42fd7135d1cf3884e8b51c9/crates/ide-completion/src/context/analysis.rs#L593-L623 and then adding a new completion module that handles it https://github.com/rust-lang/rust-analyzer/tree/f1b257f4eb4fef74b42fd7135d1cf3884e8b51c9/crates/ide-completion/src/completions

**Comment by jmintb** [comment]
Can I have a go at this issue? :)

**Comment by Veykril** [comment]
go ahead!

**Comment by jmintb** [comment]
I had to focus on uni for a bit, will get back on this now.
