### ISSUE TITLE
Suggestion: show diagnostics above docs in tooltips

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rust-lang/rust-analyzer#13015]
This is what the tooltip looks like when hovering over "Vec":
![image](https://user-images.githubusercontent.com/302938/184505846-c378d904-fe55-4603-9f15-f2a3fe4cc5bc.png)

But when hovering over something underlined with a squiggly, the user is probably interested in this:
![image](https://user-images.githubusercontent.com/302938/184505875-6b2b8526-eeb7-4bda-b8fd-2a4d87583b6c.png)

I suggest to put diagnostics above docs.

And even if the user actually wants to see the docs, error messages are less likely to be extremely long, so there will be less scrolling required.

**Comment by Veykril** [comment]
We can't do anything about that unfortunately, see https://github.com/microsoft/vscode/issues/73120
