### ISSUE TITLE
VSCode "Debug" test cwd is workspace root, not package root for tests

### ISSUE THREAD

**Issue by Crzyrndm** [rust-lang/rust-analyzer#13022]
Setup: https://github.com/Crzyrndm/ra-executing-directory

A package nested in a workspace, the tests (unit + integration) just print `std::env::current_dir()` and then panic (so that the print is always visible)

* `cargo test --no-fail-fast`: prints the package root directory for both unit and integration no matter what directory it is run in
* VSCode "Run test" button: prints the package root directory
* VSCode "Debug" button: prints the _workspace_ root directory

This makes debugging tests that need to load a data file quite awkward

![image](https://user-images.githubusercontent.com/8765278/184589044-c2e34101-4312-4f33-9ab5-3d36c2e0df29.png)

**rust-analyzer version**: rust-lang.rust-analyzer 0.3.1170 (current stable)

**rustc version**: rustc 1.63.0 (4b91a6ea7 2022-08-08)

Tested OS is Windows 10

**relevant settings**:

**Comment by Crzyrndm** [comment]
Disclaimer: I have never used JS/TS so take the following as you will

From what I can tell, the Debug executing directory is set [here](https://github.com/rust-lang/rust-analyzer/blob/c567771605631c786af8b3d21204abad857e04ac/editors/code/src/run.ts#L142) and is unconditionally the workspace/open folder root directory.

This is correct for the basic case (`cargo run -p <package> ...`) but it looks like cargo is localising test execution to the package (which makes sense. Don't won't test pass/fail depending on whether it's in a workspace or not). I haven't tested examples / benchmarks to see if similar package localisation is happening but I can see that being a likely default as well

The [target](https://github.com/rust-lang/rust-analyzer/blob/c567771605631c786af8b3d21204abad857e04ac/editors/code/src/run.ts#L148) appears to be known in the same scope although I don't know if that's package/folder/something else at this point. Presumably whether it's a run/test(/example/benchmark) or not can be obtained from [this](https://github.com/rust-lang/rust-analyzer/blob/c567771605631c786af8b3d21204abad857e04ac/editors/code/src/run.ts#L140)

**Comment by esiegel** [comment]
In addition it doesn't include any of the cargo environment variables that could be used to help normalize a path.  For example, `CARGO_MANIFEST_DIR` is missing
