### ISSUE TITLE
treats nalgebra::DVector::zeros(any number) as "expexted 0 arguments, found 1"

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [rust-lang/rust-analyzer#13033]
stable version of extension

**Comment by lnicola** [comment]
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/5441. You can disable the warning using `rust-analyzer.diagnostics.disabled.

**Comment by H-A-M-G-E-R** [comment]
a false positive

**Comment by H-A-M-G-E-R** [comment]
i found the cause in #5441
