### ISSUE TITLE
Reference autocompletion inserts `&` in wrong place in macros

### ISSUE THREAD

**Issue by flodiebold** [rust-lang/rust-analyzer#13035]
I could have sworn we have a ticket for this, but I couldn't find it.
```rust
// some extra text

enum Foo { Bar }

fn foo(foo: &Foo) {}

fn test() {
    println!("{}", foo(Foo::Ba<|>))
}
```
using the `&Bar` completion here inserts the ampersand in the wrong place.

**Comment by Veykril** [comment]
We had one for attributes, I'd expect us to not even offer these in macros currently
