### ISSUE TITLE
More unknown types in `webrender` after #12993

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#13030]
![image](https://user-images.githubusercontent.com/308347/184688151-272a7319-c8c2-40e2-9827-48355e14826b.png)

I don't know how this happened, but we're reporting more unknown types in the `bitflags!` expansions.

`webrender` is https://github.com/rust-lang/rustc-perf.git at `c52ee623e231e7690a93be88d943016968c1036b`.

EDIT:

Looks like manually expanding that macro makes the errors go away. Repro, note that the second item is needed:

```rust
# bitflags = "1.0"

use bitflags::bitflags;

bitflags! {
    #[repr(C)]
    pub struct FontInstanceFlags: u32 {
        const SYNTHETIC_ITALICS = 1 << 0;
        const SYNTHETIC_BOLD    = 1 << 1;
    }
}
```

Are we choking on `$crate`?

**Comment by lnicola** [comment]
CC @lowr

**Comment by lowr** [comment]
cc #12993

For future reference, we were failing to resolve the `try!()` macro used without escaping in Rust 2015 crates.

**Comment by lnicola** [comment]
Makes more sense than crate. Somehow I missed those in the expansion 😕.
