### ISSUE TITLE
rust-analyzer.cargo.features passed to rustc source

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust-analyzer#13054]
When setting `rust-analyzer.cargo.features` and `rust-analyzer.rustc.source`, the cargo features will be passed to cargo when trying to discover the sources for rustc even though rustc doesn't support the cargo features I want to use for my own project.

**rust-analyzer version**: rust-analyzer version: 0.3.1170-standalone (b6d59f2bb 2022-08-14)

**rustc version**: not relevant

**relevant settings**:

```json
{
    "rust-analyzer.rustc.source": "discover",
    "rust-analyzer.cargo.features": ["unstable-features"],
}
```

```
rust-analyzer failed to load workspace: Failed to read Cargo metadata for Rust sources: Failed to run `"cargo" "metadata" "--format-version" "1" "--features" "unstable-features" "--manifest-path" "/home/gh-bjorn3/.rustup/toolchains/nightly-2022-08-15-x86_64-unknown-linux-gnu/lib/rustlib/rustc-src/rust/compiler/rustc/Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error: error: none of the selected packages contains these features: unstable-features
```

**Comment by Veykril** [comment]
This should be fixed according to https://github.com/rust-lang/rust-analyzer/blob/d9c29afaee6cb26044b5a605e0073fcabb2e9722/crates/project-model/src/workspace.rs#L271-L275
