### ISSUE TITLE
Crashing on a disabled feature

### ISSUE THREAD

**Issue by JosuGZ** [rust-lang/rust-analyzer#13098]
Rust analyzer is crashing with the following mensage from the openssl-src crate:

```
This perl implementation doesn't produce Windows like paths (with backward
slash directory separators).  Please use an implementation that matches your
building platform.
```

I'm getting the same problem when I try to build my project with the "ssl" feature, which enables the ssl features of the dependencies. But without that feature, the code builds fine (with no ssl support). So `cargo build` works with no problem.

Rust Analyzer aparently tries to build the openssl crate anyway.

Features of my project: 

```
[features]
default = []
gpio = []
ssl = ["paho-mqtt/vendored-ssl"]
```

**rust-analyzer version**: rust-analyzer version: 0.3.1178-standalone (a670ff888 2022-08-21)

**rustc version**: rustc 1.62.1 (e092d0b6b 2022-07-16)

**relevant settings**: Nothing relevant, I'm not enabling "all features".

**Comment by bjorn3** [comment]
https://stackoverflow.com/questions/43958861/openssl-perl-configure-mingw-exits-with-error-perl-implementation-doesnt-pro

It seems that if you are using the MinGW target, you have to compile from a MinGW shell for openssl to build. This is an issue in openssl.

**Comment by JosuGZ** [comment]
> https://stackoverflow.com/questions/43958861/openssl-perl-configure-mingw-exits-with-error-perl-implementation-doesnt-pro
> 
> It seems that if you are using the MinGW target, you have to compile from a MinGW shell for openssl to build. This is an issue in openssl.

That is why I have an `ssl` feature which is disabled by default. Cargo build and run work, but RA crashes. I only enable the feature when building from Linux.

**Comment by JosuGZ** [comment]
It turns out that I had this on my workspace:

![image](https://user-images.githubusercontent.com/25986871/186376028-060e474b-37b1-4f99-91fb-3147834bdd84.png)

Apparently the variable has been renamed so it wasn't showing up as modified by the settings UI, but RA was still loading it.

I'm not sure whether this could be considered as bug.

**Comment by Veykril** [comment]
We need to load the old names still for backwards compatability reasons with other clients unfortunately, so there is not much we can do about that

**Comment by JosuGZ** [comment]
I'm closing this then, thanks!
