### ISSUE TITLE
Suggest structure type in enum variant

### ISSUE THREAD

**Issue by enomado** [rust-lang/rust-analyzer#13107]
Lets say we have 

```
pub struct YoloVariant {}

pub enum HH {
    Yolo(YoloVariant),
}

fn brr() {
    let t = HH::Yolo(_|_);
}
```

Expected to have `YoloVariant` in suggestions.

**Comment by jonas-schievink** [comment]
It does get suggested though?

**Comment by flodiebold** [comment]
Not for me, at least. To be clear, I assume we're talking about the full `YoloVariant {}` completion from expected type.

**Comment by jonas-schievink** [comment]
Ah, yeah. The type itself does show up, not the record literal completion.

**Comment by Veykril** [comment]
That should be a second entry

**Comment by enomado** [comment]
same with

`obj.field = |`

I want to get variant here - Some, None, etc
