### ISSUE TITLE
Autoimport assist triggers on parameter names

### ISSUE THREAD

**Issue by flodiebold** [rust-lang/rust-analyzer#13105]
```rust
fn foo(path: &str) {}
```
If I put the cursor on `path`, I get "Import `std::path`" as a suggestion. That probably shouldn't be there.

**Comment by ChayimFriedman2** [comment]
It can be useful if you are about to type a a pattern for the parameter for struct in `std::path`.

**Comment by Veykril** [comment]
The reason why this works here is because of autocompleting patterns, the auto import assist triggering is a side effect from this, I agree that this is probably less useful for the assist.

**Comment by volsa** [comment]
Hi, I'm currently trying to work on this to get a better understanding of the RA codebase but am failing at writing the actual unit test. The test currently looks as follows
```Rust
    #[test]
    fn ignore_parameter_name() {
        check_assist(auto_import, r"fn foo(path$0: &str) {}", r"fn foo(path: &str) {}")
    }
```
which panics with the following error `thread 'handlers::auto_import::tests::ignore_parameter_name' panicked at 'code action is not applicable`. Is `check_assist` the correct function to use here or am I missing something else?

**Comment by Veykril** [comment]
```rs
    #[test]
    fn ignore_parameter_name() {
        check_assist_not_applicable(auto_import, r"
mod foo {
    pub fn bar() {}
}
fn foo(bar$0: &str) {}")
    }
    ```
    should be a test for this

**Comment by volsa** [comment]
Testing your code within VS Code doesn't trigger the assist. Any module in the std library however does, e.g.
![demo](https://user-images.githubusercontent.com/29666622/195985262-e101d914-9d45-4c98-9b48-f79b9bc06717.gif). 

Also I might be confused here but the following test (without any modification to the import logic) already works which shouldn't be the case as the assist in the above GIF triggered? 
```Rust
#[test]
fn ignore_parameter_name() {
    check_assist_not_applicable(auto_import, r"fn foo(string$0: &str) {}");
}
```

**Comment by bjorn3** [comment]
Tests don't include the standard library as dependency by default because it takes way too long to run the test otherwise. Maybe the following reproduces the issue?

```rust
#[test]
fn ignore_parameter_name() {
    check_assist_not_applicable(auto_import, r"
mod std {
    pub mod string {}
}
fn foo(string$0: &str) {}
");
}
```

**Comment by volsa** [comment]
Yes that did the trick, generally speaking the `pub` modifier was missing in Veykrill's example but both tests now seem to work. Thanks for the quick reply!
