### ISSUE TITLE
Memory leak from repeated include macros

### ISSUE THREAD

**Issue by zephryn** [rust-lang/rust-analyzer#13102]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
0.3.1170-standalone (b6d59f2bb 2022-08-14)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.65.0-nightly (0b79f758c 2022-08-18)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
From what I can tell, no custom environment variables are set or anything like that, just using the nightly Rust version mentioned above.

Was toying around with module stuff, accidentally had two `include!()` macros which pointed to the same source file (in this case, `main.rs`) and noticed that the `rust-analyzer` process proceeds to continually consume all the memory it can (about 500MB/second, I'd say) and uses up most of a CPU core's time until either stopped manually or the OS OOM killer attempts to kick in.

This issue was also reproducible every time I had both the include macros present and re-saved the file in VSCodium with the extension present. The memory usage and status commands don't seem to show anything out of the ordinary when checked.

Not much else to it; definitely a silly little mistake on my part, but I imagine this isn't intended/wanted behavior.

**Comment by Veykril** [comment]
So the `include` included itself? Ye that sounds bad, but certainly something we should guard against somehow

**Comment by Veykril** [comment]
We actually do guard against this, and the author seems to be mia so closing
