### ISSUE TITLE
Workspace Symbol function search didnt work until I type _

### ISSUE THREAD

**Issue by enomado** [rust-lang/rust-analyzer#13114]
There is a feature called by `CTRL+T`.

It can find type `UserModel` on `#Model`

But it dont display `user_exact_position` on `#user` until I type `#user_`

First time I though suffix search dont work as well, but `#exact_` is working.  It works even when I type `xa_`

Its great behavior when you get how it works, but frustrating for newcomers, especially its not covered in docs. 

And what about cases when we function dont have underscores in name?

**Comment by evopen** [comment]
try `"rust-analyzer.workspace.symbol.search.kind": "all_symbols"` in vscode settings.json

**Comment by enomado** [comment]
Thank you! closing this. Wish it could be searchable.
