### ISSUE TITLE
Ampersand insert on auto complete

### ISSUE THREAD

**Issue by ktjd123** [rust-lang/rust-analyzer#13111]
**rust-analyzer version**: rust-analyzer version: 0.3.1178-standalone (a670ff888 2022-08-21)

**rustc version**: rustc 1.63.0 (4b91a6ea7 2022-08-08)

1. It added `&` on auto complete.

Code example
```rust
use std::error::Error;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let result = reqwest::get("https://www.google.com").await?.text().await?;

    println!("{:?}", result);

    Ok(())
}
```
If I try to auto complete the `result` on line 7 like below photo,

<img width="695" alt="스크린샷 2022-08-25 18 38 37" src="https://user-images.githubusercontent.com/15044488/186631410-567ad43d-03b3-4ff0-ab6e-bc9b7a01fb9b.png">

It adds `&` to line 4 like below code

```rust
use std::error::Error;

#[tokio::main]
async fn main() -> Resul&t<(), Box<dyn Error>> {
    let result = reqwest::get("https://www.google.com").await?.text().await?;

    println!("{:?}", result);

    Ok(())
}
```

Thank you.

**Comment by Veykril** [comment]
Fixed in https://github.com/rust-lang/rust-analyzer/pull/13092

**Comment by flodiebold** [comment]
Surprising that `&result` would be suggested at all though :thinking:

**Comment by Veykril** [comment]
```rs
{
    $crate::io::_print(std::fmt::Arguments::new_v1(
        &[],
        &[std::fmt::ArgumentV1::new(&(result), std::fmt::Display::fmt)],
    ));
}
```

I think the parentheses might be tripping the expected type up?

**Comment by flodiebold** [comment]
Can you actually reproduce it though? I don't get the `&result` completion, even with `tokio::main` :thinking:

**Comment by Veykril** [comment]
Not for the macro actually no, I get it for my assumption though
![image](https://user-images.githubusercontent.com/3757771/186643035-65def3b6-5200-47c9-9fbe-140765bcf334.png)

**Comment by ktjd123** [comment]
It shows `&result` when I enter `result` to the end.

1. When `resul`.
<img width="736" alt="스크린샷 2022-08-26 02 43 01" src="https://user-images.githubusercontent.com/15044488/186733518-f67e7d91-9e5e-429d-b0d1-b37524d192f1.png">

2. When `result`
<img width="702" alt="스크린샷 2022-08-26 02 44 06" src="https://user-images.githubusercontent.com/15044488/186733650-65bff25a-f7e8-4fc6-8bda-504210b2c99b.png">

Might help 😀

**Comment by flodiebold** [comment]
I tried that, but still didn't see `&result` :confused:

**Comment by ktjd123** [comment]
I checked out nightly version, It doesn't suggest me `&result. So maybe It could be closed I guess. 😀
