### ISSUE TITLE
Allow `go-to-definition` on private function/attribute.

### ISSUE THREAD

**Issue by enomado** [rust-lang/rust-analyzer#13126]
There is a lot of situations where I create some function and forget to make it public, or find some library function and want to see what it does, but I cant with no reason. Then I must go to type, find this function by search. Its inconvenient a bit.

**Comment by st3fan** [comment]
@enomado Can you post a short snippet of code where `go-to-definition` does not work for you? This functionality should work - can you try it again with the most recent version of `rust-analyzer` ?

**Comment by enomado** [comment]
I cant build RA from master,

      npm ERR! semver.simplifyRange is not a function
      
still cant go to definition in pre release version

**Comment by enomado** [comment]
https://user-images.githubusercontent.com/707007/198116801-0901902e-d1eb-4b0d-b3c2-52390c3c0612.mp4

**Comment by enomado** [comment]
I think it is a feature to "save people from using private function seduce". but this behavior is inconvenient
