### ISSUE TITLE
It's too slow to get intellisence in just hello world level project

### ISSUE THREAD

**Issue by tjx666** [rust-lang/rust-analyzer#13135]
Steps:

1. git clone git@github.com:tjx666/study-rust.git
2. open it in vscode in multi-root workspace mode
3. open oop/src/main.rs
4. in my computer, it costs about 30 seconds to get println autocomplete

```
Version: 1.71.0-insider (Universal)
Commit: 35b971c92d210face8c446a1c6f1e470ad2bcb54
Date: 2022-08-26T09:30:57.123Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes
Rust-Analyzer: v0.4.1184
```

https://user-images.githubusercontent.com/41773861/187077804-f23f4217-de26-49c3-87ee-6b9302f1d71d.mov

**Comment by lnicola** [comment]
Can you commit and push `oop`? :-).

**Comment by tjx666** [comment]
> Can you commit and push `oop`? :-).

Ok. I had commt.

**Comment by tjx666** [comment]
It's very strange: I just open oop folder, why this extension load all others folders.

**Comment by lnicola** [comment]
Does it work better after the "Fetching metadata" message goes away? It takes 20 seconds or so.

> It's very strange: I just open oop folder, why this extension load all other folders.

If I open `oop`, it loads fast for me. But if I open the whole Code workspace, it's pretty slow. I think we're mainly calling `cargo metadata` on each of the projects, we could probably do that in parallel.

**Comment by tjx666** [comment]
@lnicola The better solution maybe only load the `oop` workspace. In multi-root workspaces, one workspace should only be load when open the rust file in itself. Because workspaces had nothing relationship between each other.

**Comment by lnicola** [comment]
Yeah, but we don't do that for some reason, I'm not sure why. Ideally, we'd only load `oop` and see if it depends on something else from the same workspace.

**Comment by Veykril** [comment]
Closing this as related issues  have been mentioned / opened that capture the problem more precisely
