### ISSUE TITLE
Excess placeholders in format string cause some errors to be silent

### ISSUE THREAD

**Issue by skondrashov** [rust-lang/rust-analyzer#13130]
**rust-analyzer version**: rust-analyzer version: 0.3.1178-standalone (a670ff888 2022-08-21)

**rustc version**: rustc 1.63.0 (4b91a6ea7 2022-08-08)

```rust
fn main() {
    format!("{}{}", undeclared);
    undeclared;
    type; // <-- red underline
}
```

All 3 lines in `main()` have an error, but only the labeled one shows up for me in VSCode. After removing the `format!` line, the unknown value error properly shows up for `undeclared;`. Moving the lines and adding different errors mostly shows that some error types consistently don't show up near the macro invocation, and others do.

Interestingly, `format!("{}", two, things);` displays the correct errors, so not any placeholder/argument count mismatch causes this. `{:?}` placeholders cause the same issue.

**Comment by jonas-schievink** [comment]
Last time this happened, it was because we were emitting the diagnostics with an empty message string. Maybe that logic has regressed?

**Comment by flodiebold** [comment]
The errors show up fine for me in Emacs.

**Comment by Veykril** [comment]
Ye seems like https://github.com/rust-lang/rust-analyzer/pull/13016 https://github.com/rust-lang/rust-analyzer/pull/13017 doesn't fully work, there are still some cases where VSCode just throws, guess we'll have to move the workaround back into the server and given VSCode doesn't consider this a bug it will have to stay there ...
