### ISSUE TITLE
Deleted file content while formatOnSave

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/rust-analyzer#13132]
```
[coc.nvim] rust-analyzer 0.4.1184-standalone (6bea872ed 2022-08-26)

## versions

vim version: NVIM v0.8.0-dev
node version: v16.15.0
coc.nvim version: 0.0.82-0f70955 2022-08-28 14:08:02 +0800
coc.nvim directory: /home/cheng/.local/share/nvim/plugged/coc.nvim
term: tmux-256color
platform: linux
```

**Comment by GopherJ** [comment]
![Peek 2022-08-28 15-53](https://user-images.githubusercontent.com/33961674/187063927-c42090ce-b32d-470a-8218-422dc74a85a8.gif)

**Comment by bjorn3** [comment]
This is in all likelyhood a rustfmt bug. You can try if `cat /path/to/file.rs | rustfmt` returns a formatted file on stdout or nothing. If the later this is indeed a rustfmt bug and you should open an issue at https://github.com/rust-lang/rustfmt.

**Comment by Veykril** [comment]
That's https://github.com/rust-lang/rustfmt/issues/5519 (this was a bug in the past with rustfmt as well though it was fixed at one point afaik)
