### ISSUE TITLE
Toggle inlay hints is not working

### ISSUE THREAD

**Issue by JosuGZ** [rust-lang/rust-analyzer#13144]
Toggle inlay hints in RA has stopped working for me. Now, it is changing the following setting to an incorrect value:

![image](https://user-images.githubusercontent.com/25986871/187390799-3ef9f6dd-bc8e-42ab-82c3-f379ade064a0.png)

**rust-analyzer version**: 0.3.1186-standalone (e8e598f64 2022-08-28)

**rustc version**: rustc 1.63.0 (4b91a6ea7 2022-08-08)

**relevant settings**: In Keyboard settings (VS Code):

```
    {
        "key": "ctrl+alt+h",
        "command": "rust-analyzer.toggleInlayHints"
    }
```

**Comment by lnicola** [comment]
Which version of Code is that?

**Comment by JosuGZ** [comment]
> Which version of Code is that?

I have checked and it is not the latest, but it is not very old. For some reason is failing to update.

**Comment by lnicola** [comment]
We only support the latest one or two versions of code, and yours is from March or even older.

**Comment by JosuGZ** [comment]
> We only support the latest one or two versions of code, and yours is from March or even older.

Then it would be interesting if RA didn't update if the VS Code version is old. Right now if you have a virtual machine for a project it will break itself after a while :'(

**Comment by lnicola** [comment]
We didn't bump the required version this time, since it works fine, mostly. You should probably disable extension updates if you want it to never change.

**Comment by lnicola** [comment]
The command was removed in #13215.

**Comment by c-git** [comment]
`Rust Analyzer: Toggle Inlay Hints` still shows in the docs here https://code.visualstudio.com/docs/languages/rust but I couldn't find it in VS code and started searching and got to here. I'm new to VS Code so wasn't sure if I was  doing something wrong.

**Comment by lnicola** [comment]
@c-git the command was removed in favour of the native feature of Code: the `on{Until,Unless}Pressed` settings from https://code.visualstudio.com/updates/v1_67#_toggle-inlay-hints. The docs there must be a little outdated.

**Comment by lnicola** [comment]
Filed https://github.com/microsoft/vscode-docs/pull/6061 to update the docs.

**Comment by c-git** [comment]
Thank you, sorry I wasn't clear. I wasn't sure how to update the docs but understood it had been removed. Thank you for doing the docs update.

**Comment by lnicola** [comment]
No worries, I didn't know myself, but there's a big Edit button in the corner, in case you ever need it.
