### ISSUE TITLE
Extension ignores `rust-analyzer` binary in $PATH

### ISSUE THREAD

**Issue by Banyc** [rust-lang/rust-analyzer#13146]
**rust-analyzer version**: `v0.3.1186`

**rustc version**: `rustc 1.63.0 (4b91a6ea7 2022-08-08)`

**relevant settings**: none

```
$ which rust-analyzer
/home/USERNAME/.nix-profile/bin/rust-analyzer
```

```
$ echo $PATH
/home/USERNAME/.nix-profile/bin:/nix/var/nix/profiles/default/bin:...
```

But the notification prompt says:

```
Unfortunately we don't ship binaries for your platform yet.
...
```

I'm using VSCode in a remote server via SSH.

**Comment by lnicola** [comment]
Does setting `rust-analyzer.server.path` work?

**Comment by Banyc** [comment]
@lnicola it does not work and the line in `settings.json` is grayed out.

**Comment by lnicola** [comment]
Do the other `rust-analyzer` preferences show up? It should be there -- on the remote side, of course.

**Comment by Banyc** [comment]
@lnicola sorry! It works when I write the line in the local `settings.json`!

**Comment by lnicola** [comment]
I'm not sure how this works, but you might be editing your local preferences. The extension is supposed to be installed and run on the remote side.
