### ISSUE TITLE
Rust-analyzer failing to find workspace.

### ISSUE THREAD

**Issue by michael-bailey** [rust-lang/rust-analyzer#13152]
# Rust-analyzer failing to find workspace, seems to be executing `.cargo` folder.

Hey! I've been swapping between the original rust language server and rust-analyzer in vscode, due to a persistent issue arising with rust-analyzer.

When i open any rust project in vscode on my mac i get this error:

<img width="451" alt="Screenshot 2022-08-29 at 14 59 49" src="https://user-images.githubusercontent.com/20004939/187218751-ae020eaf-f5b8-4de4-8671-91a857e5bed9.png">

with the output of rust-analyzer saying the exact same message.

> I have rust-analyzer installed on my windows machine which works.

From just looking at the message it looks like it is trying to execute the `.cargo` folder instead of the binary `.cargo/bin/cargo`
This is demonstrated by executing the same command in the terminal

<img width="626" alt="Screenshot 2022-08-31 at 08 10 11" src="https://user-images.githubusercontent.com/20004939/187615818-bc6c8c52-19aa-404b-a20c-df33cf43dc52.png">

I can't seem to find any setting or config to change this behaviour.
I also don't see any other person reporting or having found a fix/workaround for this issue.

Thank you for taking you're time to read through this, and any help is greatly appreciated.

## Version info:
**rust-analyzer** version: 0.3.1186-standalone (e8e598f64 2022-08-28)

**rustc version**: rustc 1.63.0 (4b91a6ea7 2022-08-08)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
CARGO: /Users/michaelbailey/.cargo
RUSTUP_HOME: <Blank>
CARGO_HOME: <Blank>

**Comment by bjorn3** [comment]
The `CARGO` env var needs to point to the cargo executable.

**Comment by lnicola** [comment]
And you don't actually need to set `CARGO` unless you have a non-standard setup.

**Comment by michael-bailey** [comment]
@lnicola What do you mean by that.
I used the official installer script.
Should that have set `CARGO`?

**Comment by lnicola** [comment]
You don't need to set `CARGO` at all.

**Comment by michael-bailey** [comment]
Ok, so i set `CARGO` to `$(which cargo)` (so that it will find the binary) my issue has been solved. I don't know what makes my setup different from the default to require this. 

Thank you for your help with this, it is greatly appreciated!
