### ISSUE TITLE
Debug lens bug

### ISSUE THREAD

**Issue by WladOd** [rust-lang/rust-analyzer#13166]
I  have Ubuntu 20.04 and VSCode with rust-analyzer extension. I've created just a new library with cargo command  and  the provided test  example could be debugged with Debug lens without any problem. Then I just add proc-macro = true to Cargo.toml I am not able to use rust-analyser debug lens on any test in lib.rs anymore. I get:

`error while loading shared libraries: libtest-95a0f3dcb2265cb8.so: cannot open shared object file: No such file or directory
`
is it a bug or some misconfiguration? I raised that question on stackoverflow but there is no good advice there https://stackoverflow.com/questions/73509851/proc-macro-true-breaks-vscode-rust-analyser-debug-lens

**Comment by jonas-schievink** [comment]
This is not caused by rust-analyzer. Running the produced test executable manually also results in that error.

**Comment by bjorn3** [comment]
You need to set `LD_LIBRARY_PATH` to include the path `rustc --print target-libdir` outputs. (Make sure to use the same rustc version as you compile your program with and if you have `rust-analyzer.cargo.target` set, pass this target to rustc too using `--target`.) Cargo does this automatically when you use `cargo run` or `cargo test`, but when running the executable outside of cargo, like necessary for running in a debugger, this doesn't happen automatically.
