### ISSUE TITLE
Too high delay to remove "type shower" when manually setting variable type

### ISSUE THREAD

**Issue by Andrej123456789** [rust-lang/rust-analyzer#13198]
**rust-analyzer version**: 0.3.1194-standalone (67920f797 2022-09-04)

**rustc version**: rustc 1.63.0 (4b91a6ea7 2022-08-08)

I don't know how to explain the best but you can see following video:

https://user-images.githubusercontent.com/83548580/188590137-8a1b6b8f-a837-4725-8c0b-9b95a5e92bd6.mp4

**Comment by Veykril** [comment]
This is a problem with VSCode, see https://github.com/microsoft/vscode/issues/145377

**Comment by Andrej123456789** [comment]
Ok
