### ISSUE TITLE
ENH: Add release notes to release

### ISSUE THREAD

**Issue by corneliusroemer** [rust-lang/rust-analyzer#13191]
When having a look at the latest release I was surprised to find there were no release notes.

https://github.com/rust-lang/rust-analyzer/releases/tag/2022-09-05

This seems to be the rule - a but surprising for such a big project.

Would it be hard to populate the release notes with whatever is in the changelog?

I know the releases are a GitHub feature and not strictly necessary, but since releases get announced to all watchers it would be nice to have the info there.

It seems to exist already here: https://rust-analyzer.github.io/thisweek/2022/08/29/changelog-144.html

![Screenshot_2022-09-05-09-15-54-22_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/25161793/188391192-5002f5c4-662a-440a-b71b-1d248b3c04c4.jpg)

**Comment by lnicola** [comment]
It's not very easy either. The release notes are generated automatically when the release is triggered, then pretty heavily edited. We might be able to insert a link to e.g. https://rust-analyzer.github.io/thisweek/2022/09/05/changelog-145.html, but even that can pose problems with out-of-band releases like https://rust-analyzer.github.io/thisweek/2022/05/17/changelog-129-5.html.

**Comment by corneliusroemer** [comment]
Link would be great.

How often are there out of band releases, and us their put of band nature
evident somewhere in the code base?

If the date is unexpected one could simply not add a link or mention "out
of band" in the notes - and refer to the website more generally rather than
direct at a precise release notes website.

**Comment by lnicola** [comment]
I mean, the GitHub release is published automatically at the moment. There's nothing marking it as "out of band", and I only gave those as a not-obvious example because they tend to break the URL and release numbering.

I'm not saying that this can't be done, but we'd have to change almost everything about how the releases are made.

**Comment by noritada** [comment]
I would like to try to solve this issue.

I checked the following files and understood that GitHub Releases entries are generated in a GitHub Actions workflow along with release binaries and that templates for changelog entries are generated in the local environment.

- [Release Process documentation](https://github.com/rust-lang/rust-analyzer/tree/master/docs/dev#release-process)
- [github-release action](https://github.com/rust-lang/rust-analyzer/tree/master/.github/actions/github-release)
- ["release" workflow](https://github.com/rust-lang/rust-analyzer/blob/master/.github/workflows/release.yaml)
- [xtasks](https://github.com/rust-lang/rust-analyzer/tree/master/xtask)

The simplest solution would be to update the GitHub Releases entry when a new edited changelog entry is pushed to the website repository. Do you have any suggestions?

**Comment by lnicola** [comment]
Sorry for taking so long. I didn't realize that we could update GitHub releases after publishing them, but that's indeed possible: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release.

This could be an extra step, something like `cargo xtask publish-release-notes`, or it could even be done directly from GHA (with more work to match the updated file to the release). The first version might be easier for now, especially given that the original version is AsciiDoc, while GitHub Releases probably use Markdown. There might be some other feature gaps too, like image support.

**Comment by lnicola** [comment]
[As seen on GitHub](https://github.com/rust-lang/rust-analyzer/releases/tag/2022-12-26)
