### ISSUE TITLE
Semantic Highlighting `attribute` modifier missing on some tokens.

### ISSUE THREAD

**Issue by Greatness7** [rust-lang/rust-analyzer#13199]
Previous versions tagged all tokens within attribute macros with an `attribute` modifier (#6599), which allowed the syntax highlighting in these contexts to be influenced separately via user preferences.

This was working correctly as of version `0.3.1178`, but is no longer the case in subsequent releases.

Example:

Previous behavior:
![Untitled-1](https://user-images.githubusercontent.com/12927912/188741937-2cb0eb1c-d421-4e81-a48f-5564781b4a2f.png)

Current behavior:
![Untitled-2](https://user-images.githubusercontent.com/12927912/188741289-4318feae-18e6-4760-bbd0-4b49f75b09f2.png)

**Comment by Veykril** [comment]
This is due to https://github.com/rust-lang/rust-analyzer/pull/13084, we no longer highlight punctuation semantically by default. You'll have to enable the `rust-analyzer.highlighting.semanticHighlighting.punctuation.enable` setting

**Comment by Greatness7** [comment]
> This is due to #13084, we no longer highlight punctuation semantically by default. You'll have to enable the `rust-analyzer.highlighting.semanticHighlighting.punctuation.enable` setting

Adding `"rust-analyzer.semanticHighlighting.punctuation.enable": true` did fix it. Thanks!
