### ISSUE TITLE
Add string reference code action wrong positon, when string generated by `format!()`

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rust-lang/rust-analyzer#13219]
**rust-analyzer version**:
rust-analyzer 0.3.1194-standalone (67920f797 2022-09-04)
**rustc version**: (eg. output of `rustc -V`)
rustc 1.65.0-nightly (2befdefdd 2022-08-06)
**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

**Comment by IWANABETHATGUY** [comment]
Barebone cargo new project
[录屏 2022-09-11 18-26-46.webm](https://user-images.githubusercontent.com/17974631/189522811-e69e08b6-7f9c-42d4-91a2-7be763561cdf.webm)

**Comment by mdx97** [comment]
I'm getting the following `&` insertion when I try the same example as the linked video:
```rust
test&(format!("t"));
```

rust-analyzer version: 0.3.1203-standalone (2e9f1204c 2022-09-11)
rustc 1.65.0-nightly (59e7a308e 2022-09-11)

**Comment by mdx97** [comment]
There seems to be a linear relationship between how long the argument text is and where the ampersand ends up being. Here are some example placements:
```rust
t&est(format!());
tes&t(format!(""));
test&(format!("t"));
test(&format!("ta"));
test(f&ormat!("foo"));
test(format!("supercalifragilisticexp&ialidocious"));
```

**Comment by mdx97** [comment]
The ampersand will be positioned even further back with a longer function name. Even bleeding into the previous line:
```rust
fn ma&in() {
    testing123456789(format!());
}
```

**Comment by mdx97** [comment]
I'll try to dig into this one a bit more tomorrow.

@rustbot claim

**Comment by Veykril** [comment]
The problem is this line https://github.com/rust-lang/rust-analyzer/blob/dbb8fedf8b887adfde3b445f9ec4bdf11da9ae9f/crates/ide-diagnostics/src/handlers/type_mismatch.rs#L75
We just take the text_range of the expression which in this case is inside a macro expanded file so the range is wrong as it isn't the range of the macrocall

**Comment by mdx97** [comment]
Is there any reason you see why we can't just use [this range](https://github.com/rust-lang/rust-analyzer/blob/dbb8fedf8b887adfde3b445f9ec4bdf11da9ae9f/crates/ide-diagnostics/src/handlers/type_mismatch.rs#L65)? I updated the code to use it and the other tests pass, and it works properly when I manually test it with a macro. For some reason my new tests are failing though 🤔 Need to look into that some more.

**Comment by Veykril** [comment]
Oh ye, tha tshould work as well, didn't see that but that should be the range we are interested in in this cast at least.
