### ISSUE TITLE
Problems with proc macro expansions on m1 mac

### ISSUE THREAD

**Issue by hyperswine** [rust-lang/rust-analyzer#13210]
**rust-analyzer version**: 0.4.1198-standalone (4e1a3da8f 2022-09-08)

**rustc version**: rustc 1.64.0-nightly (f8588549c 2022-07-18)

**relevant settings**: m1 mac latest macos

**problem**: proc-macro expansion error with uefi-rs. [Link](https://github.com/hyperswine/Arcboot) to the repo.

![Screen Shot 2022-09-09 at 9 11 36 pm](https://user-images.githubusercontent.com/8978635/189338199-d2c32d14-185a-469f-85c5-865130d85408.png)

**Comment by lnicola** [comment]
You probably need to update to a more recent nighly (from around 29 Jul or so).

**Comment by hyperswine** [comment]
Hmm, still the same problem. I dunno

**Comment by Veykril** [comment]
Which version does your `rust-toolchain.toml` point to, that needs to point to a recent nightly (or one of the last ~4 stable versions)

**Comment by jonas-schievink** [comment]
Closing, since the last comment should answer the question, and OP didn't respond.
