### ISSUE TITLE
Fails to properly handle a destructuring assignment

### ISSUE THREAD

**Issue by nanoqsh** [rust-lang/rust-analyzer#13220]
In a relatively new version of Rust (it seems 1.59.0), you can use a destructuring assignment which allows you to write code like this:
```rust
_ = String::new();
```
while earlier it was necessary to use `let` for this:
```rust
let _ = String::new();
```

RA swears at this, although this is the valid code that [compiles](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=20a1a0ee60943891823dbd360ccbb448) without any errors.
![image](https://user-images.githubusercontent.com/40631392/189563429-a099a173-6546-4e51-b050-8db3f4e1c988.png)

**rust-analyzer version**: rust-analyzer version: db2a7087b 2021-12-13 stable

**rustc version**: rustc 1.63.0 (4b91a6ea7 2022-08-08)

**Comment by lowr** [comment]
rust-analyzer you're using is pretty old. Updating it to the latest version should work.
