### ISSUE TITLE
"Convert `match` to let-else" assist

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#13254]
(let-else will be stable in about 6 weeks from now (Rust 1.65); we should probably not ship this assist before then)

It would be nice to have an assist to rewrite `let` statements with a `match` like the following, to their corresponding `let-else` form:

```rust
let val = match opt {
    Some(it) => it,
    None => return,
};
```
->
```rust
let Some(val) = opt else { return };
```

Criteria for the assist should be:
- `let` statement whose initializer is a `match` expression
- `match` has 2 arms, the first extracts data, the second has a diverging expression

**Comment by matklad** [comment]
We should also adjust existing “convert to early return” assist to use the new syntax

**Comment by jhgg** [comment]
> match has 2 arms, the first extracts data, the second has a diverging expression

Probably should handle:
```rust
let val = match opt {
    None => return,
    Some(it) => it,
};
```

As well.

**Comment by lnicola** [comment]
https://user-images.githubusercontent.com/308347/200244795-545f0465-ec0f-4d8c-8f70-5f08aea99bf0.mp4

**Comment by fmease** [comment]
Ah, I just noticed this issue. It's a duplicate / subset? of #11908.
