### ISSUE TITLE
 How to configure VSCode to parse the code for linux in windows.

### ISSUE THREAD

**Issue by surechen** [rust-lang/rust-analyzer#13266]
My IDE is: VSCode. Use rust-analyzer.
 I want to use VSCode in Windows, but parse the code for linux, as shown in the following figure. How do I configure VSCode please?

![截图](https://user-images.githubusercontent.com/7249331/191208368-2f3701ce-b6f6-4332-b688-6c7afb6962bb.PNG)

**Comment by bjorn3** [comment]
You can set the `rust-analyzer.cargo.target` config option to `x86_64-unknown-linux-gnu` to analyze for this target instead of the host.

**Comment by surechen** [comment]
> You can set the `rust-analyzer.cargo.target` config option to `x86_64-unknown-linux-gnu` to analyze for this target instead of the host.

Very helpful for me. Thank you very much.
