### ISSUE TITLE
Wrong completion results for tuple field access

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rust-analyzer#13271]
**rust-analyzer version**:  5b49745d009634170493a214364261e36228274b (current master)
**rustc version**: `rustc 1.65.0-nightly (c0941dfb5 2022-08-21)`

```rust
fn test() {
    let a = |event: (String, usize)| event.1.<|>; // should show methods of `usize`, instead methods for `String` are shown.
}
```

**Comment by jhgg** [comment]
This is probably #1109
