### ISSUE TITLE
Code actions degradated in last versions

### ISSUE THREAD

**Issue by vikulikov** [rust-lang/rust-analyzer#13274]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/28891532/191768825-d79e41a2-b719-4b0f-9c3b-50097de523b2.png">

There is no button to fill enum variants. But it appears under some circumstances but I cannot realize which. In this example cursor was inside the parenthesis. 

If cursor is above the enum's variable name button appears. But it is not always the case
<img width="778" alt="image" src="https://user-images.githubusercontent.com/28891532/191770387-5f02cdb7-a558-49df-8e9c-43ec4b501afd.png">

rust-analyzer version: 0.3.1212-standalone (187bee0bb 2022-09-19)

rustc 1.63.0 (4b91a6ea7 2022-08-08)

**Comment by lnicola** [comment]
What type does that variable have? Try to hover on it.

**Comment by vikulikov** [comment]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/28891532/191770799-c352cfd8-4d01-4900-87ad-fd4fc1af9bbf.png">
@lnicola

**Comment by vikulikov** [comment]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/28891532/191770943-713a1eed-49fc-4648-b284-f607c85732ca.png">
@lnicola

**Comment by vikulikov** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/28891532/191771309-4c19d5c6-a3ca-4b7d-b49d-707de0f94a5a.png">
<img width="714" alt="image" src="https://user-images.githubusercontent.com/28891532/191771390-faf3fc41-73b1-4f8d-bc90-e91b3abeb3aa.png">

**Comment by vikulikov** [comment]
The problem ocures in a trait implemention under the async_trait macro. I believe this is not a rust_analyzer issue that is why closing it.
