### ISSUE TITLE
overrideCommand JSON format?

### ISSUE THREAD

**Issue by diggyk** [rust-lang/rust-analyzer#13284]
What should the format of the JSON exported by the override command be?  I've got a script that returns JSON and sometimes it works and sometimes it doesn't, so I think all the plumbing is just fine but I think it is occassionally getting a format it doesn't like.

**Comment by lnicola** [comment]
Same as `cargo check --message-format=json` or whatever you're overriding.

**Comment by diggyk** [comment]
Got it.  Thanks.
