### ISSUE TITLE
Intelisense works only in main file

### ISSUE THREAD

**Issue by erikpa1** [rust-lang/rust-analyzer#13283]
Hi yesterday I tried some project in VS code, but I found out rust-analyzer is working only main.rs file, nowhere else:

![image](https://user-images.githubusercontent.com/19526670/191992305-61a1f023-fd8b-4376-9f84-10266485a822.png)

But when I come to any other file than main, code completion won't work.

![image](https://user-images.githubusercontent.com/19526670/191992750-9f20030a-a610-40d7-b3c1-1aacfc5a1289.png)

I also tried to reinstall rust plugin, or switch to prerelease, nothing helped.

**rust-analyzer version**: v0.3.1212

**rustc version**: 1.64.0  (also tried on 1.39 I think)

**Comment by lnicola** [comment]
I'm guessing there's a hint on the first line saying that the file is not included in the project. You need a `mod projects_astorage` declaration in the parent module.

**Comment by erikpa1** [comment]
@lnicola  Nope, intelisense in mod.rs is also not working, any file I create is broken

**Comment by lnicola** [comment]
Do you have a `mod projects` declaration in `databases/mod.rs`?

**Comment by erikpa1** [comment]
Oh, wait you wonna say, if the file isn't moded intelisense will not work? This is interesting IDE behaviour,  like ok, some warning about  file is never included or something, never used function, but disable whole intelisense for that file ???

**Comment by lnicola** [comment]
The file isn't even compiled if you don't declare it as a module. And you do get a warning:

![image](https://user-images.githubusercontent.com/308347/192026793-f09df359-748d-4001-828c-13569f3c056c.png)

**Comment by erikpa1** [comment]
@lnicola  
![image](https://user-images.githubusercontent.com/19526670/192030592-e53f891b-1778-47b7-9683-bfa989c981bd.png)

This means file is not included, I know, I didn't included it, because I created it to prototype first.  But this is still no explanation why intel sense works,....  (not included file should be shown in hierarchy, not disable whole code completion for that file, line no other extension works in this way, c++, react,... I never seen this behaviour and I though its bug. Maybe if this is some behavior authors want, there should be better warning like "This file is not included, intelisense will not work for this file. )

**Comment by bjorn3** [comment]
> not included file should be shown in hierarchy

But it doesn't exist in the module hierarchy. C++ and javascript have a different module system where every file is effectively their own module root. In rust however you have a single crate root per crate and this crate root then can have sub modules. Any file not (indirectly) included from the crate root is ignored by rustc. While it would be possible to pretend that non-includee files are their own crate root, this will still prevent intellisense from working with dependencies and items that are part of the crate in which you intended to include the module.

**Comment by lnicola** [comment]
Arguably, we could tell where these files should be declared as modules: in their parent, according to the disk structure, not as separate crates.

**Comment by erikpa1** [comment]
pycharm rust module has no problem with it,....

**Comment by CaneMandarinesco** [comment]
this 

> > not included file should be shown in hierarchy
> 
> But it doesn't exist in the module hierarchy. C++ and javascript have a different module system where every file is effectively their own module root. In rust however you have a single crate root per crate and this crate root then can have sub modules. Any file not (indirectly) included from the crate root is ignored by rustc. While it would be possible to pretend that non-includee files are their own crate root, this will still prevent intellisense from working with dependencies and items that are part of the crate in which you intended to include the module.

I've recently started programming in rust and this doesn't seem to make complete sense to me, and it wasn't obvious what was the problem.
