### ISSUE TITLE
Feature request: Show inlay type hints for bindings in for loops

### ISSUE THREAD

**Issue by Follpvosten** [rust-lang/rust-analyzer#13294]
I couldn't find this feature requested yet (and also no bug report mentioning it missing), so I'm assuming that either no one thought about it yet or there was some discussion around it that I'm just failing to find; feel free to close this if it's a duplicate.

Currently, with inlay type hints enabled, bindings in for loops don't generate any:

![grafik](https://user-images.githubusercontent.com/22855787/192231410-45676a17-5b43-4340-a109-288adf101841.png)

This feels a bit like an oversight; the equivalent `while let` loop does show the type of the binding:

![grafik](https://user-images.githubusercontent.com/22855787/192231577-742f697c-69fe-4f55-86e3-e7fab34b9448.png)

It would be nice if these type hints could be symmetrical.

**Comment by Veykril** [comment]
We already do emit inlay hints in that position 
![image](https://user-images.githubusercontent.com/3757771/192232180-8a0f4920-b733-459e-b80b-5fd8e3620c7f.png)
So the problem seems to be something else that trips up r-a for you there

**Comment by Follpvosten** [comment]
Interesting; I've checked my settings for anything related and couldn't find it, and I'm running the latest version (just did a reload because of the update). I could switch to pre-release though.

Note that *not a single for loop* shows these hints for me, even in the simplest possible cases:

![grafik](https://user-images.githubusercontent.com/22855787/192232734-4b32fd61-aadb-4404-a58b-5d8210196e2d.png)

So this is *not* because of the the chunks method.

**Comment by Follpvosten** [comment]
Also, hover hints do show the correct type, so it does resolve correctly.

I just updated to the pre release and that didn't change anything either.

**Comment by Follpvosten** [comment]
Alright, it works for a new empty project. So it may be an issue with my workspace setup.

**Comment by Follpvosten** [comment]
I have looked into this a but further and realized it appears to be proc macro related.

This is a project with tokio as the only direct dependency:

![grafik](https://user-images.githubusercontent.com/22855787/192969132-31aba8e1-f1b0-48a6-8310-2b5f62f9c5cb.png)

If you remove the `#[tokio::main]` line, the inlay hint immediately appears.

**Comment by Veykril** [comment]
Apologies I never came back to this, attributes still break some functionality unfortunately. This is known and not really easy to fix for us right now.

**Comment by Veykril** [comment]
Closing as its a known issue with attributes
