### ISSUE TITLE
Duplicate quick fixes

### ISSUE THREAD

**Issue by MariaSolOs** [rust-lang/rust-analyzer#13308]
**rust-analyzer version**: 0.4.1224-standalone (ad752bd52 2022-09-27)

**rustc version**: 1.63.0 (4b91a6ea7 2022-08-08)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

## Repro steps:
1. Inside any `.rs` file, copy the following function:
```
fn plus(x: i32) -> i32 {
    x + 1;
}
```
2. Place your cursor beside the semicolon and see the available quick fixes.
3. The expected result is to see a single suggestion for removing the semicolon, but currently duplicate appears (with the only difference in the casing of course):
<img width="404" alt="image" src="https://user-images.githubusercontent.com/62502207/192926219-81855f29-5c94-4c8e-bd8d-0f573c05d0d5.png">

**Comment by lnicola** [comment]
One of those is from us, one is from rustc. We don't have the infrastructure to ignore duplicate diagnostics.

**Comment by MariaSolOs** [comment]
@lnicola got it, so I guess this is a VS Code issue since it is the one handling all diagnostics sources and listing the results in the lightbulb menu. Unfortunately I don't think there's a straightforward way to recognize duplicate diagnostics, since in this case it is just casing but one could also say that punctuation counts etc. So the issue is way more subtle. 

I'll close this then as not planned :)

**Comment by lnicola** [comment]
Yup. We could look specifically for `E0308` and that suggestion, but I think `rustc` is moving towards localized diagnostic messages, which won't make this very fun.
