### ISSUE TITLE
Go to Definition for method of async_trait leads to incorrect location

### ISSUE THREAD

**Issue by vikulikov** [rust-lang/rust-analyzer#13305]
It shows some structures from std lib somehow related to futures/

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/28891532/192708737-e35147d6-23ad-4268-83f8-c728adad6da1.png">

minimal reproducible piece of code:
```rust

#[async_trait]
trait Foo {
    async fn bar(self); // cmd/ctrl + click on `bar`
}

```

rust-analyzer version: 0.3.1212-standalone (187bee0bb 2022-09-19)

rustc 1.64.0 (a55dd71d5 2022-09-19)

**Comment by jonas-schievink** [comment]
`async-trait` uses the method name's span as the span for the return type, so this seems to be working correctly on our end: https://github.com/dtolnay/async-trait/blob/74cb3274d09bb0502b3e36d5fa5f74ac211a5bc6/src/expand.rs#L291

**Comment by vikulikov** [comment]
Issue was fixed by the async_trait lib author
