### ISSUE TITLE
rust-analyzer.lens.location: above_whole_item causes !!MISSING: command!!

### ISSUE THREAD

**Issue by NekoiNemo** [rust-lang/rust-analyzer#13310]
**rust-analyzer version**: 0.3.1221-standalone
**rustc version**: rustc 1.63.0 (4b91a6ea7 2022-08-08)

**VSCode**:
```
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.9-arch1-1
Sandboxed: No
```

Rest of rust-analyzer **config**:
```
    "rust-analyzer.checkOnSave.command": "clippy",
    "rust-analyzer.completion.privateEditable.enable": true,
    "rust-analyzer.hover.actions.references.enable": true,
    "rust-analyzer.imports.granularity.group": "module",
    "rust-analyzer.imports.prefix": "self",
    "rust-analyzer.inlayHints.closingBraceHints.minLines": 20,
    "rust-analyzer.inlayHints.closureReturnTypeHints.enable": "always",
    "rust-analyzer.inlayHints.reborrowHints.enable": "always",
    "rust-analyzer.lens.references.adt.enable": true,
    "rust-analyzer.lens.references.enumVariant.enable": true,
    "rust-analyzer.lens.references.method.enable": true,
    "rust-analyzer.lens.references.trait.enable": true,
    "rust-analyzer.procMacro.attributes.enable": true,
    "rust-analyzer.references.excludeImports": true,
    "rust-analyzer.restartServerOnConfigChange": true,
    "rust-analyzer.rustfmt.rangeFormatting.enable": true,
```

Without "rust-analyzer.lens.location": "above_whole_item":
![screenshot_1664445803](https://user-images.githubusercontent.com/3595771/193004177-b85e8e03-b7af-4d89-9ad7-4b9e3825611f.png)
With "rust-analyzer.lens.location": "above_whole_item":
![screenshot_1664445838](https://user-images.githubusercontent.com/3595771/193004186-d3cf15c8-16df-49fa-b901-099f262bd66a.png)

**Comment by bjorn3** [comment]
Can you check if rust-analyzer crashed? I generally get those errors when rust-analyzer crashed.

**Comment by NekoiNemo** [comment]
How can i check? The Output (Rust Analyzer Language Server) that guide tells to look into is empty whenever the setting is active or not, and the client output doesn't show any errors.

**Comment by Veykril** [comment]
Then r-a didn't crash. I imagine we forgot to adjust the codelense resolve part, so VSCode asks for a lens resolution for a position where we don't see the lens (because the resolve code expects the lens at a different position).

**Comment by NekoiNemo** [comment]
I see. Any way i can check that to be sure?

**Comment by Veykril** [comment]
I assume the problem is here https://github.com/rust-lang/rust-analyzer/blob/ad752bd52115186ab5ebe2fd27f09867112747c1/crates/ide/src/annotations.rs#L164-L191
`annotation.range.start()` points to the name of the thing normally, but with `above_whole_item` set it now points to the first token which no longer resolves for those IDE functions. We might need to add extra data (the range of the name) to the codelens payload to resolve this
