### ISSUE TITLE
Add #[must_use] to generated `as_` method.

### ISSUE THREAD

**Issue by nitsky** [rust-lang/rust-analyzer#13312]
Generated `as_` methods for enum variants do not have `#[must_use]`, causing clippy to display an error.

<img width="938" alt="Screen Shot 2022-09-29 at 10 47 49 AM" src="https://user-images.githubusercontent.com/492793/193068097-030394c0-695a-4cc1-bf14-fc13cc9e0cd8.png">

**Comment by nitsky** [comment]
Okay, closing. I like using clippy::pedantic because it helps enforce a consistent code style.

**Comment by lnicola** [comment]
It should probably be configurable.

Hello from someone who tried Tangram/ModelFox, BTW!
