### ISSUE TITLE
Loading proc macro dylibs does not work with 1.64

### ISSUE THREAD

**Issue by snowp** [rust-lang/rust-analyzer#13322]
Using rust-analyzer with 1.64 I run into the following

```
proc macro `test` not expanded: Cannot create expander for /private/var/tmp/_bazel_snowp/c1591b76b8a2fcd15b6ff3cd34fdd7da/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/loopsdk__tokio_macros__1_8_0/libtokio_macros-2048780629.dylib: UnsupportedABI
```

This appears to be because 1.64 is not handled in this expression: https://cs.github.com/rust-lang/rust-analyzer/blob/5b7e40014ef172839108af860487fe4209a02135/crates/proc-macro-srv/src/abis/mod.rs?q=UnsupportedABI#L111-L122

Happy to make the change here if we just need to include 1.64 in the 1.63 ABI branch or make it ABI selected for 1.63 and later

**rust-analyzer version**: rust-analyzer version: 0.4.1225-standalone (97f8f4a3d 2022-09-29)

**rustc version**: 1.64

**relevant settings**: Bazel build using the rules_rust rules to generate a rust-project.json

**Comment by bjorn3** [comment]
From 1.64 onwards we use a proc macro server provided by rustc instead of a builtin proc macro server. Bazel will need to tell rust-analyzer where the rustc sysroot is using the respective key in rust-project.json for it to be able to find this proc macro server.
