### ISSUE TITLE
rust-analyzer VSCode extension not set as executable

### ISSUE THREAD

**Issue by B-Teague** [rust-lang/rust-analyzer#13331]
1) Installed opensource code-oss via flatpak.
2) Installed org.freedesktop.Sdk.Extension.rust-stable via flatpak
3) Installed rust-analyzer extension within code

Failed to execute /home/userName/.var/app/com.visualstudio.code-oss/config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu

Fixed by adding permission to rust-analyzer-x86_64-unknown-linux-gnu to be executable.

Should this file be set as executable when the extension is installed?

**rust-analyzer version**: rust-analyzer 0.3.1194-standalone

**rustc version**: rustc 1.63.0

**relevant settings**: 
Operating System: Manjaro Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.5
Kernel Version: 5.15.65-1-MANJARO (64-bit)

Flatpak list
|Name|Application ID|Version|Branch|Installation|
|---|---|---|---|---|
|Code - OSS |com.visualstudio.code-oss|1.71.2|stable|system|
|Freedesktop SDK|org.freedesktop.Sdk|21.08.15|21.08|system|
|Rust stable|org.freedesktop.Sdk.Extension.rust-stable|1.63.0|21.08|system|

**Comment by lnicola** [comment]
This is probably an OpenVSX bug, see #11080. Last time I checked, it was serving a RA version from around October. We do try to publish it there, but we get a server error and there's no-one who can look into it. I'm quite surprised that you're getting `0.3.1194`, that's only 3 weeks old. Did you really install it from the marketplace?

In addition, I suspect that OpenVSX somehow drops the executable bit on that file. It's not their packaging tool -- we publish the same VSIX on the Code Marketplace --, so something must be happening afterwards. We could reset it from the extension, but:

 - that's a workaround for a server-side bug
 - on a server where we can't even publish the extension (so our code change wouldn't even reach users AFAICT)

PS: https://open-vsx.org/extension/matklad/rust-analyzer has 0.2.853.

PPS: Downloading https://marketplace.visualstudio.com/_apis/public/gallery/publishers/rust-lang/vsextensions/rust-analyzer/0.4.1227/vspackage?targetPlatform=linux-x64, the executable flag is indeed set.

**Comment by B-Teague** [comment]
It looks like the rust-stable Sdk Extension is downloading the latest version of the rust-analyzer, so I am wondering if that is where the newer version 0.3.1194 is coming from instead of the rust-analyzer VSCode extension.
[org.freedesktop.Sdk.Extension.rust-stable//21.08](https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable/blob/branch/21.08/org.freedesktop.Sdk.Extension.rust-stable.json)

So maybe this is a Flatpak bug that isn't setting version 0.3.1194 to be executable?
