### ISSUE TITLE
STDIN redirect not working in VS Code

### ISSUE THREAD

**Issue by MariuszCwikla** [rust-lang/rust-analyzer#13334]
According to https://code.visualstudio.com/docs/editor/debugging#_redirect-inputoutput-tofrom-the-debug-target it should be possible to do stdin redirect with `"args": ["<", "path/to/file"]` :

```
{
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug executable 'foo'",
            "cargo": {
                "args": [
                    "build",
                    "--bin=foo",
                    "--package=foo"
                ],
                "filter": {
                    "name": "foo",
                    "kind": "bin"
                }
            },
            "console": "integratedTerminal",
            "args": ["<", "${workspaceFolder}/foo.in"],
            "cwd": "${workspaceFolder}"
        },
```

But when running it (both in release and debug mode), stdin is not redirected. In the terminal window it waits for user's input instead; the file is ignored

**rust-analyzer version**: 0.3.1221-standalone (73ab709b3 2022-09-24)

**rustc version**: 1.64.0

**Comment by Veykril** [comment]
r-a itself has no debugging functionality, so this issue lies with whatever provides the lldb debugger type for you.

**Comment by MariuszCwikla** [comment]
I don't know much about lldb.
But I have found some solution here if anyone is struggling with the same problem https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#stdio-redirection - remove `args` and use `stdio` instead:

```
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug executable 'foo'",
            "cargo": {
                "args": [
                    "build",
                    "--bin=foo",
                    "--package=foo"
                ],
                "filter": {
                    "name": "foo",
                    "kind": "bin"
                }
            },
            "console": "integratedTerminal",
            "stdio": ["${workspaceFolder}/foo.in"],
            "cwd": "${workspaceFolder}"
        },
```

**Comment by Veykril** [comment]
Closing as this is not a r-a issue
