### ISSUE TITLE
Ability to limit scope of rust-analyzer check-on-save feature

### ISSUE THREAD

**Issue by pacak** [rust-lang/rust-analyzer#13346]
# Problem: 

In a big cargo workspace working on anything imported by a bunch of other stiff is unnecessary painful - checking on saving (ni vim) take a long of time (during which I can't run tests because of a lock on the build directory) and I don't really care how other crates are affected until I decide to start working on them.

# Desired solution

Automagically substitute `--package <current>` in `cargo check` / `cargo clippy` options when rust-analyzer calls them on save - current should correspond to a package current file belongs to.

**Comment by jhgg** [comment]
This looks (roughly) same as #12882

**Comment by Veykril** [comment]
Duplicate of #12882
