### ISSUE TITLE
Support autocompletion of cargo environment variables in `env!()`

### ISSUE THREAD

**Issue by kevinushey** [rust-lang/rust-analyzer#13345]
It would be handy if some of the environment variables described in https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates were included as autocompletion candidates within an `env!()` macro invocation.

(The ones that immediately come to mind are `CARGO_PKG_VERSION` and `CARGO_MANIFEST_DIR`, but the others described would IMHO still be useful to see.)

**Comment by Veykril** [comment]
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/12448
