### ISSUE TITLE
Request: sort methods requiring a nightly feature not active in the crate after other methods

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-analyzer#13361]
If you do a complete on `size_of_val`, for example, the list of things it will offer to import is `core::intrinsics::size_of_val`, `core::mem::size_of_val`, and so on. However, the `core::intrinsics` path is unstable, and requires a special nightly feature to use.

It would be much better if the completion options that need a nightly feature show up towards the end of the list. It's extremely rare that a person would want to pick a completion option that requires adding a new nightly feature to the crate.

**Comment by JonathanLindsey** [comment]
Looks like this is a duplicate of #3020. Though that issue proposes to remove unstable completions from the list (which I would prefer or to have a setting).

**Comment by Lokathor** [comment]
Not showing them at all would also be entirely acceptable.

**Comment by lnicola** [comment]
Another idea was to de-prioritize them and add a `#![feature]` when you pick one.
