### ISSUE TITLE
"implement missing members" assist uses incorrect lifetime name

### ISSUE THREAD

**Issue by JoJoJet** [rust-lang/rust-analyzer#13363]
**rust-analyzer version**: `rust-analyzer version: 0.3.1229-standalone (5c28ad193 2022-10-01)`

**rustc version**: `rustc 1.63.0 (4b91a6ea7 2022-08-08)`

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

Given the following code:

```rust
pub trait MyTrait<'lifetime> {
    fn foo(&'lifetime self);
}

impl<'a> MyTrait<'a> for () {

}
```

Using the assist "implement missing members" results in the following:

```rust
impl<'a> MyTrait<'a> {
    fn foo(&'lifetime self) { // this should be &'a self
        todo!()
    }
}
```

**Comment by TheDoctor314** [comment]
I would like to look into this.

**Comment by ponyii** [comment]
"imlement default members", a closely-related assist, doesn't update neither lifetimes nor const params:

```
pub trait Foo<const N: usize> {
    const CONST: usize = N * 4;
}

impl<const AAA: usize> Foo<AAA> for () {
    const CONST: usize = N * 4;             // the assist `N` instead of `AAA`
}
```

**Comment by ponyii** [comment]
one more related problem - default types are not transformed:

```
mod m {
    pub struct S {}

    pub trait Foo<T = S> {
        fn get_n_sq(&self, arg: &T) -> usize { 0 }
    }
}

impl m::Foo for () {
    fn foo(&self, arg: &S) -> usize { 0 }    // generated line with `S` instead of `m::S`
}
```
