### ISSUE TITLE
Request textDocument/inlayHint failed

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#13372]
When working in rustc, I often see an error pop up in the corner which says "Request textDocument/inlayHint failed". I am not entirely sure how to reproduce this, or what it even is talking about. The pop up has a "show output" button, and when I press that button I see a log which ends in

```
[Error - 11:55:04 AM] Request textDocument/inlayHint failed.
  Message: Invalid offset
  Code: -32603 
```

I think I also saw this in Miri, but I am not entirely sure about that.

**rust-analyzer version**: rust-analyzer version: 0.3.1221-standalone

**rustc version**: rustc 1.66.0-nightly (c97d02cdb 2022-10-05)

**relevant settings**:
user settings
```
    "rust-analyzer.lens.enable": false,
    "rust-analyzer.cachePriming.enable": false,
    "rust-analyzer.cargo.buildScripts.useRustcWrapper": false,
    "rust-analyzer.cargo.buildScripts.enable": true,
    "rust-analyzer.procMacro.enable": true,
    //
    "rust-analyzer.diagnostics.disabled": [
        "unlinked-file", // I guess for "normal" projects unlinked files are strange, for me they are common
        "unresolved-module", // https://github.com/rust-lang/rust-analyzer/issues/9173
        "unresolved-extern-crate", // https://github.com/rust-lang/rust-analyzer/issues/12926
        "type-mismatch", // https://github.com/rust-lang/rust-analyzer/issues/1109
    ],
```
workspace settings
```
    "rust-analyzer.rustc.source": "./Cargo.toml",
    "rust-analyzer.linkedProjects": [
        "./Cargo.toml",
    ],
    "rust-analyzer.checkOnSave.overrideCommand": [
        "./x.py",
        "check",
        "--json-output",
        "library/std",
    ],
    "rust-analyzer.rustfmt.overrideCommand": [
        "./build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt",
        "--edition=2021"
    ],
    "rust-analyzer.cargo.buildScripts.overrideCommand": ["false"],
    "rust-analyzer.cargo.buildScripts.enable": false,
    "rust-analyzer.procMacro.enable": false,
```

**Comment by Veykril** [comment]
This is caused by our inlay hint resolve payload not being "versioned", that is a client might ask for a resolve of an inlay hint and change the text content right after/before such that r-a tries to resolve the inlay hint on a different document version.

**Comment by matklad** [comment]
>that is a client might ask for a resolve of an inlay hint and change the text content right after/before such that r-a tries to resolve the inlay hint on a different document version.

To properly assign the blame here, the client is right. For "two-phase lookups" with resolve, it is in genera not possible to guarantee that there are no intervening changes which would invalidated the lookup. That's why:

* for resolve, it is preferable to use ids resilient to changes (eg, for code actions we use `name` of the action, not the position in the action list)
* even with resilient ids, this can fail, which should return a `null` result to the client, it definietly shouldn't crash (well, we should never crash, but we could be  bit obnoxious about the clients in the wrong, but in this case this is a totally normal operation)

**Comment by Doomwhite** [comment]
I have the same problem.

**Comment by lnicola** [comment]
@pascaldanek what's the full error you are getting, and when?

**Comment by pascaldanek** [comment]
@lnicola it seems to be totaly random when I edit Rust code:

```
[Error - 18:25:22] Request textDocument/inlayHint failed.
  Message: Invalid offset
  Code: -32603 
```

PS: I add that since a few days my rust dev experience in vscode has become very slow for a (yet) unknown reason.

**Comment by ShayBox** [comment]
Can this popup be removed or disabled, it's constantly getting in the way, I don't care if it fails because it took too long and got outdated information, it can retry again next save, just stop stacking popups that don't disappear on the screen.
