### ISSUE TITLE
Syntax tree

### ISSUE THREAD

**Issue by sevenzing** [rust-lang/rust-analyzer#13381]
Hello, I need help.

My goal is to get syntax tree of rust program and get **types** of variables, functions and so on. 
As far as I understand, Syntax tree that rust_analyzer gives me doesn't have this info, since Green Node are untyped (https://github.com/rust-lang/rust-analyzer/blob/6c6ae965ba1235b6cbd8299e2959698bd394e80a/docs/dev/syntax.md#greennode)

Also, I wrote this simple code, in order to understand can I get type of variable `bar` in some rust source code:

```rust
use ide::{TextSize, HoverConfig, FileRange, TextRange};

fn main(){
    let text = r#"fn foo(a: String) {}

fn main() {
    let bar = Default::default();
    foo(bar)
}
    "#.to_string();
    let (a, file_id) = ide::Analysis::from_single_file(text);
    
    // let bar = Default::default()
    //     ^
    let cursor = TextSize::from(42);
    let range = FileRange {
        file_id,
        range: TextRange::empty(cursor),
    };

    let hover_config = HoverConfig {
        links_in_hover: true,
        documentation: None,
        keywords: true,
    };
    let hover = a.hover(&hover_config, range).unwrap();
    println!("hover result = {:#?}", hover);
    
}
```

But hover result is `"let bar: {unknown}\n\n"`.

So, I'm just stuck, I don't understand what I'm doing wrong. Could you please help me

**Comment by Veykril** [comment]
As you are running analysis `from_single_file`, there is no standard library known, so `String` and `Default` won't resolve

**Comment by sevenzing** [comment]
Got it, how can I use rust-analyzer as library, so that it will resolve standard library. Should I use crate `hir` ?

**Comment by Veykril** [comment]
You'll have to discover the sysroot (and if you want to also support cargo dependencies then the workspace as well), a lot of that can be found in here I believe https://github.com/rust-lang/rust-analyzer/blob/master/crates/rust-analyzer/src/cli/load_cargo.rs
