### ISSUE TITLE
Debug button doesn't work with `"RUST_BACKTRACE": 0`

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/rust-analyzer#13390]
Sorry if it is duplicate. `Debug` lens on tests fails for me with this message:

```
Could not parse launch configuration: invalid type: integer `0`, expected a string
```

rust-analyzer version: 0.3.1238-standalone

vscode version: VSCodium 1.72.0

codelldb version: 1.8.1

**Comment by HKalbasi** [comment]
Can someone check that if this problem happens always or something is broken with my setup?

**Comment by Veykril** [comment]
Works fine for me

**Comment by HKalbasi** [comment]
Thanks for checking. I found that it will happen only with this config:
```
"rust-analyzer.runnableEnv": {
    "RUST_BACKTRACE": 0,
},
```

**Comment by Veykril** [comment]
using `"0"` probably works
