### ISSUE TITLE
v0.4.1239 linux-x64 won't load in VSCodium (not #11080)

### ISSUE THREAD

**Issue by neildarlow** [rust-lang/rust-analyzer#13398]
After installing this version, the extension reports the following message and doesn't load:

Error: the pattern with the identifier $rustc-run doesn't exist.

**rust-analyzer version**: 0.4.1239

**rustc version**: 1.64.0 (a55dd71d5 2022-09-19)

**relevant settings**: Running in VSCodium 1.72.0

**Comment by lnicola** [comment]
How did you install it? Did previous versions work?

**Comment by neildarlow** [comment]
As it's not on OpenVSX, I download and install from the VSCode Marketplace. Installed via VSCodium Extensions Tab|Install from VSIX... menu option.

Previous versions have installed fine. I tend to check for updates regularly and install them when available. This is the first failure I've experienced.

**Comment by neildarlow** [comment]
I downloaded from the rust-lang Nightly which, coincidently, is at v0.4.1239 and it exhibits the same failure as the download from the VSCode Marketplace.

I installed the extension without any project open. In case it matters, I'm using the org.freedesktop.Sdk.Extension.rust-stable with VSCodium as flatpak but I've not had issues with this setup until now.

**Comment by neildarlow** [comment]
Update v0.4.1244 fixes this issue. Thank you, I will close.

**Comment by lnicola** [comment]
Yeah, I think it was fixed by https://github.com/rust-lang/rust-analyzer/pull/13413.
