### ISSUE TITLE
Duplicate references in wasm_bindgen types

### ISSUE THREAD

**Issue by abseee** [rust-lang/rust-analyzer#13407]
When I issue a `textDocument/references` request on `MyStruct` in [lib.rs](https://gist.github.com/abseee/b0b7685a5807f5864378a015caa947f1#file-lib-rs), I expect 3 references. Instead I get [288](https://user-images.githubusercontent.com/18266269/195561241-22546bd4-e168-4a51-a5c0-4d0235c0e00d.png)! VSCode seems to dedupe these results before surfacing them in the UI but [other editors may not](https://github.com/helix-editor/helix/issues/3351). Dupes are also returned for `MyEnum` and its variants. Non-`wasm-bindgen` tagged types work fine; presumably other macros also trigger this issue but I don't know enough to debug further.

[VSCode <-> Rust analyze trace](https://gist.github.com/abseee/b0b7685a5807f5864378a015caa947f1#file-vscode-rust-analyzer-trace-txt)
[Expanded lib.rs](https://gist.github.com/abseee/b0b7685a5807f5864378a015caa947f1#file-lib-expanded-rs)

**rust-analyzer version**: 0.3.1238-standalone

**rustc version**: rustc 1.63.0 (4b91a6ea7 2022-08-08)

**Comment by vimalk78** [comment]
i just upgraded to latest `master` and this issue is super annoying.
do we know which commit caused this? i would want to revert from latest `master`. Is there a way to de-dup in nvim?

**Comment by vimalk78** [comment]
wow, is this something that editors need to take care of, and fixing it in `rust-analyzer` will cause additional issues?

**Comment by Veykril** [comment]
No, we can easily fix this in r-a, and I think it makes sense to do so as well. Though I would expect clients to dedup this as well.

**Comment by Veykril** [comment]
You are more then welcome to!

**Comment by lnicola** [comment]
That's not right. Prior to that commit, proc macros didn't work on your rustc version.

**Comment by lnicola** [comment]
You can use the expansion output directly if you want to bisect it further.

**Comment by lnicola** [comment]
> Ah I thought VS Code would show a warning if the proc_macros weren't expanded in rust-analyzer.

I think it should print an error in the logs, at least, not sure when that was added. You can check by running `Expand macro`, if that's easy to do from Helix.

> Was I supposed to build r-a with a matching older version of rustc?

No, you need to change your project toolchain (`rustup override` or `rustup default`) to a [supported](https://github.com/rust-lang/rust-analyzer/tree/master/crates/proc-macro-srv/src/abis) version. The RA build version doesn't matter.

**Comment by vimalk78** [comment]
> fix is adding a `.unique()` after this here

i tried adding `tracing::info!()` lines at multiple places in function `find_all_refs` but it didn't seem to get logged

**Comment by lnicola** [comment]
You'll need to do something like https://github.com/rust-lang/rust-analyzer/tree/master/docs/dev#logging (replace `lsp_server` with the module you want).

**Comment by vimalk78** [comment]
i am using `RA_LOG=rust_analyzer=debug  ra-multiplex-server`

`ra-multiplex-server` is from https://github.com/pr2502/ra-multiplex/

**Comment by lnicola** [comment]
Try `ide=debug`.
