### ISSUE TITLE
add type completion

### ISSUE THREAD

**Issue by max397574** [rust-lang/rust-analyzer#13403]
perhaps I just did something wrong (I'm really new to rust)
but it would be really cool if there were completions for the types e.g. in parameters and return values
so in the following code (where `|` is the cursor)
```rust
pub fn test(x: |) -> | {
    let x: | = 
}
```
it would be really cool to have completions like `u8`, `i32` at the three marked cursor positions

**Comment by Veykril** [comment]
This should already be working, are you sure that rust-analyzer is working in your project?

**Comment by max397574** [comment]
looks like it was an issue on my side
