### ISSUE TITLE
Run test / debug not working in VSCode

### ISSUE THREAD

**Issue by Sytten** [rust-lang/rust-analyzer#13404]
**rust-analyzer version**: 0.4.1240

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

It looks like the latest nightly broke the VSCode `Run Test | Debug` integration.
It is working fine on 0.4.1237, let me know if I can provide more logs I didn't find any in the extension host nor the server.
The button is clickable but not doing anything.

**Comment by jonas-schievink** [comment]
Confirmed working in 0.4.1237, broken on 0.4.1239. Likely culprit: https://github.com/rust-lang/rust-analyzer/pull/13367, cc @matklad
