### ISSUE TITLE
lsp_utils error causes build scripts to fail in VS Code

### ISSUE THREAD

**Issue by cbrit** [rust-lang/rust-analyzer#13417]
**rust-analyzer version**: rust-analyzer version: 0.3.1238-standalone (61504c8d9 2022-10-08)

**rustc version**: rustc 1.64.0 (a55dd71d5 2022-09-19)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

VS Code version: Version: 1.72.2

OS: macOS Monterey, 12.5.1

Rust analyzer server output (snipped, more errors from the same macro):

```rust
ERROR rust_analyzer::lsp_utils] failed to run build scripts

error[E0659]: `parse_quote_spanned` is ambiguous
   --> <user path>/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-internal-0.4.28/src/pin_project/derive.rs:865:67
    |
865 |                 proj_generics.make_where_clause().predicates.push(parse_quote_spanned! { span =>
    |                                                                   ^^^^^^^^^^^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of a conflict between a `macro_rules` name and a non-`macro_rules` name from another module
note: `parse_quote_spanned` could refer to the macro defined here
```

**Comment by bjorn3** [comment]
Does `cargo check` work?

**Comment by cbrit** [comment]
> Does `cargo check` work?

Yes it does!

**Comment by lnicola** [comment]
What about `cargo check --all-targets`?

**Comment by cbrit** [comment]
> What about `cargo check --all-targets`?

Seems to work as expected (errors at expected compiler errors). I do now realize the analyzer is working fine on other rust repos which makes me wonder.

**Comment by lnicola** [comment]
No, as you can see, it's a rustc error. I would run cargo clean and nuke my cargo registry clone (it's easy to modify the source code of a crates.io dependency by mistake).

**Comment by cbrit** [comment]
> No, as you can see, it's a rustc error. I would run cargo clean and nuke my cargo registry clone (it's easy to modify the source code of a crates.io dependency by mistake).

Looks like I must have. I had tried `cargo clean` to no avail but `cargo update` seems to have updated the library in question. Thanks for your help.

**Comment by lnicola** [comment]
Well, keep in mind that cargo update won't always help in these cases. What if you're already using the latest version etc.?

**Comment by Lantianyou** [comment]
Having the same issue here :)

**Comment by lnicola** [comment]
@Lantianyou try to do a `cargo clean` and delete your cargo registry.

**Comment by Lantianyou** [comment]
Thank you @lnicola .
