### ISSUE TITLE
Run test / debug cannot find Cargo.toml VSCode 

### ISSUE THREAD

**Issue by Sytten** [rust-lang/rust-analyzer#13434]
The VSCode Run test button is broken with the following error:

```
error: could not find `Cargo.toml` in `/` or any parent directory

 *  The terminal process "cargo 'test', '--', 'dashboard_tests::sometest', '--exact', '--nocapture'" failed to launch (exit code: 101). 
 *  Terminal will be reused by tasks, press any key to close it.
```

This is in workspace environment. It's working on `v0.4.1247`.

**rust-analyzer version**: v0.4.1249

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

**Comment by Geobert** [comment]
I have this as well using v0.4.1252

**Comment by Veykril** [comment]
I believe https://github.com/rust-lang/rust-analyzer/pull/13428 broke this, I'll look into it.
