### ISSUE TITLE
Consider adopting VS Code testing API instead of code lenses

### ISSUE THREAD

**Issue by connor4312** [rust-lang/rust-analyzer#13440]
A while ago, we added the [testing API](https://code.visualstudio.com/api/extension-guides/testing) to VS Code. It would be be a nice and more consistent experience if `rust-analyzer` adopted this API instead of its custom code lenses; I constantly try to use the native keybindings when testing Rust code.

Here's an extension with screenshots to show what the native testing experience looks like: https://marketplace.visualstudio.com/items?itemName=ZixuanChen.vitest-explorer

**Comment by flodiebold** [comment]
Duplicate of #3601
