### ISSUE TITLE
Feature request: `return literal` hint

### ISSUE THREAD

**Issue by Rudxain** [rust-lang/rust-analyzer#13457]
# Equivalents
## JavaScript
```js
const f = (/**@type {boolean}*/ b) => b ? 1 : 0
```
has an auto-generated (inferred) "type-hint signature" (by VSCode)
```ts
const f: (b: boolean) => 1 | 0
```
> instead of the generic
> ```ts
> const f: (b: boolean) => number
> ```

which can be expressed in JSdoc like this
```js
/**
 * @param {boolean} b 
 * @returns {0|1}
 */
const f = b => b ? 1 : 0
```

## Python
```py
def f(b: bool):
	return 1 if b else 0
```
has the inferred type signature (by Pylance)
```py
(function) f: (b: bool) -> Literal[1, 0]
```
> instead of the generic
> ```py
> (function) f: (b: bool) -> int
> ```

which can be expressed explicitly with type annotations and the `typing.Literal` module
```py
from typing import Literal

def f(b: bool) -> Literal[0, 1]:
	return 1 if b else 0
```

## Rust
```rust
fn f(b: bool) -> u8 {
    if b { 1 } else { 0 }
}
```
just shows the generic
```rust
fn f(b: bool) -> u8
```
which I expected to look like this
```rust
fn f(b: bool) -> 1u8 | 0u8
```

This "enum-literal" pseudo-type can be extended to params and vars (in both Py and JS, as explained earlier), and it can work with strings too (`@type {"a" | "b"}` == `Literal["a", "b"]`)

I wish there was a way to use Rust doc-comments in the meantime (while this inference feature is implemented). I know `enum`s exist, but sometimes it's better to emulate them with primitive values

**Comment by jhgg** [comment]
`1u8 | 0u8` is not a valid rust type though. I'm not entirely sure this makes sense for Rust. Whereas Python and TypeScript has a literal type, Rust does not. As such, HIR cannot represent the possibility of this inference, nor do I think it should. 

Personally, I think that literal types are an unfortunate mistake born from the necessity of a type system which has to deal with gradually typing legacy python/javascript codebases. 

In rust, I cannot think of a situation where it is better to emulate an enum with a primitive value.

**Comment by lnicola** [comment]
Yes, this would go against the language design and I don't think we want to do it. It would be pretty confusing for new users. Keep in mind that Rust functions have explicitly-declared types so the body of the function is (mostly) not relevant to type inference.

If you prefer the type system of TypeScript or Python, it's totally fine to use those.

**Comment by Rudxain** [comment]
> `1u8 | 0u8` is not a valid rust type though.

I understand, but that's not the point, it's just an IDE type hint.

> Python and TypeScript has a literal type.

*Kind of.* They don't "really" have it, it's just a finite subset of 1 or more types. `Literal[0, 1]` can be freely used in places that expect `int`, and it will be "coerced" to `int` when doing arithmetic with other `int`s, **even if those `int`s are `Literal`s themselves.**

> I think that literal types are an unfortunate mistake born from the necessity of a type system which has to deal with gradually typing legacy python/javascript codebases.

I agree. Maybe this fits better with dynamically-typed langs?

> In rust, I cannot think of a situation where it is better to emulate an enum with a primitive value.

True, most of the time I would prefer an `enum`. I think the only use would be when migrating an old C/C++ codebase to Rust (yes, I know C has enums, but most old code doesn't use them)

**Comment by Rudxain** [comment]
> this would go against the language design

How?

> It would be pretty confusing for new users.

Most of the time, yes

> Keep in mind that Rust functions have explicitly-declared types so the body of the function is (mostly) not relevant to type inference.

True. I think I should've shown an example with `let`, to better illustrate my point

**Comment by lnicola** [comment]
> How?

Rust already has enums and will probably never get literal types. While we're (intentionally or not) sometimes less strict than the compiler, I don't think we should add as hints something that doesn't exist in the language and, as you admit, would only be useful in very few situations (if ever).

You mentioned C code using integers instead of enums, but it's probably easier to port those as i32s first, then turn them into enums. The compiler can help a lot with that.

**Comment by lnicola** [comment]
See also https://learn.microsoft.com/en-us/archive/blogs/ericgu/minus-100-points for some thoughts about how to pick features to implement.

**Comment by Rudxain** [comment]
> You mentioned C code using integers instead of enums, but it's probably easier to port those as i32s first, then turn them into enums. The compiler can help a lot with that.

Interesting, thanks for the info

**Comment by Rudxain** [comment]
Also thanks for the link!
