### ISSUE TITLE
Trait try not implemented for `_` in `Ok::<_, Infallible>`

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [rust-lang/rust-analyzer#13450]
**rust-analyzer version**: 0.3.1248-standalone (0531aab52 2022-10-16)

**rustc version**: rustc 1.64.0 (a55dd71d5 2022-09-19)

**relevant settings**: Using RA through the rust-analyzer extension in VS code

---

The following code is accepted by `cargo check` and `cargo clippy` but shows error "the trait `Try` is not implemented for `_`" using rust-analyzer:
```rs
use std::convert::Infallible;
use hyper::{service::*, Body, Request, Response};

type Error = Box<dyn std::error::Error + Send + Sync + 'static>;

#[tokio::main]
async fn main() -> Result<(), Error> {
    let addr: std::net::SocketAddr = "[::1]:3000".parse()?;

    hyper::Server::bind(&addr)
        .serve(make_service_fn(|_connection| async {
            Ok::<_, Infallible>(service_fn(handle_request))
        }))
        .await?;

    Ok(())
}

async fn handle_request(_request: Request<Body>) -> Result<Response<Body>, Error> {
    todo!()
}
```

This sample requires `hyper` and `tokio` with feature `full` on both.

Screenshot showing the error:
![https://i.imgur.com/ViNSk4k.png](https://i.imgur.com/ViNSk4k.png)

**Comment by Veykril** [comment]
The diagnostic has been removed again, so current nightly/next monday's stable won't have this issue anymore.
