### ISSUE TITLE
Support for `include!()` macro (e.g. cap'n'proto rust support)

### ISSUE THREAD

**Issue by vlovich** [rust-lang/rust-analyzer#13455]
The way cap'n'proto works is it generates a file from a schema within build.rs. Within your lib.rs you'll do something like:
```
mod example_capnp {
  include!(concat!(env!("OUT_DIR"), "/capnp/example_capnp.rs"));
}
```

However rust-analyzer gives up and doesn't offer any completions for `example_capnp::`. I'm guessing it's because it doesn't know how to handle `include!` (& maybe `env!`?).

**Comment by bjorn3** [comment]
`include!()` and `env!("OUT_DIR")` are supported. If you are having issues, that is likely because the build script failed to run. I believe you can look at the Rust Analyzer Server output channel to see the result of running cargo by rust-analyzer for the purpose of running build scripts.

**Comment by Veykril** [comment]
Closing as this ought to work as expected
