### ISSUE TITLE
Add assist for replacing arithmetic with `wrapping_`, `saturating_` or `checked_` variants

### ISSUE THREAD

**Issue by cameron1024** [rust-lang/rust-analyzer#13452]
I've found myself having to go through and replace a bunch of `x+y` to `x.saturating_add(y)`, except with much more complex expressions.

An assist to do this automatically would be handy to me. IMO, this is useful, and also doesn't pollute the scope too much (it would only be applicable when the cursor is on an arithmetic operator).

I've started work on a PR, but before I get too deep into it, it would be good to have some confirmation that this feature is something that other people think would be good to have :grin:

**Comment by Veykril** [comment]
Sounds reasonable to have in my opinion 👍

**Comment by lnicola** [comment]
Implemented in #13458.
