### ISSUE TITLE
Incorrect type annotation displayed

### ISSUE THREAD

**Issue by nikonthethird** [rust-lang/rust-analyzer#13473]
```rust
struct A(u8);
struct B(A);

fn main() {
    let b = B(A(10));
    let supposed_to_be_u8 = b.0.0;
}
```

This code displays the following incorrect type annotation (`A` instead of `u8`):

![image](https://user-images.githubusercontent.com/15893812/197514603-70c91b17-3d22-4fd1-bb31-cbd7a89a880b.png)

rustc 1.64.0 (a55dd71d5 2022-09-19)
rust-analyzer version: 0.3.1248-standalone

**Comment by bjorn3** [comment]
This may be a duplicate of https://github.com/rust-lang/rust-analyzer/issues/1109. Does `b.0 .0` with the extra space work?

**Comment by nikonthethird** [comment]
Yes, that works, this is a duplicate of the other issue.
