### ISSUE TITLE
could not find `Cargo.toml` in `/path/to/workspace` or any parent directory  - when Rust project is nested

### ISSUE THREAD

**Issue by Dzejkop** [rust-lang/rust-analyzer#13477]
# Steps to reproduce
1. Create an empty directory - `dir1`
2. Within that directory create another directory `dir2`
3. Withing `dir2` initialize a rust project with `cargo init`
4. Open the `dir1` in VSCode
5. Save the `main.rs` file
6. The popup should appear

# Description
Given a workspace structure

```
root_dir:
  project_dir:
    Cargo.toml
    src:
      main.rs
```

When saving a file I'm seeing an error popup with the content `cargo check failed Check the server logs for additional info.`

In the server logs I see this

```
[ERROR flycheck] Flycheck failed to run the following command: "cargo" "check" "--workspace" "--message-format=json" "--all-targets"
[ERROR rust_analyzer::lsp_utils] cargo check failed

Cargo watcher failed, the command produced no valid metadata (exit code: ExitStatus(unix_wait_status(25856))):
error: could not find `Cargo.toml` in `/path/to/workspace` or any parent directory
```

**rust-analyzer version**: `rust-analyzer version: 0.4.1257-standalone (43fb9563b 2022-10-23)`

**rustc version**: `rustc 1.64.0 (a55dd71d5 2022-09-19)`

**Comment by Dzejkop** [comment]
This appears to affect the pre-release version of `rust-analyzer` for VSCode, the release version is not affected

**Comment by Moskize91** [comment]
me too

**Comment by utkarshgupta137** [comment]
This is back today after upgrading to rust 1.66. I'm using Atom btw.
```
(base) [19:05] utkarsh:~ $ /Users/utkarsh/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rust-analyzer --version
rust-analyzer 1.66.0 (69f9c33d 2022-12-12)
(base) [19:05] utkarsh:~ $ rustc --version
rustc 1.66.0 (69f9c33d7 2022-12-12)
```

**Comment by utkarshgupta137** [comment]
This is back today after upgrading to rust 1.66. I'm using Atom on M1 Pro.

```
Default host: aarch64-apple-darwin
rustup home:  /Users/utkarsh/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
1.65-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.66.0 (69f9c33d7 2022-12-12)
```

Reverting to the 1.65 toolchain fixed the issue for me.

**Comment by Veykril** [comment]
Oh great, the latest stable shipped with the rust-analyzer that has this issue ... there isn't much we can do here since we can't patch the component, you'll have to redirect the server binary you are using to either an older rust toolchain or use a manually installedserver.
