### ISSUE TITLE
linking projects doesn't seem to run cargo check in the right directory

### ISSUE THREAD

**Issue by ahicks92** [rust-lang/rust-analyzer#13479]
**rust-analyzer version**: rust-analyzer version: 0.3.1258-standalone

**rustc version**: 1.64

**relevant settings**: rust-analyzer.linkedProjects
I have this in my config:

```
"rust-analyzer.linkedProjects": [
		"src/rust/Cargo.toml"
	],
```

Where `/home/ahicks/repos/backtrace-backend` is the workspace root.  When I save files, we get:

```
[ERROR flycheck] Flycheck failed to run the following command: "cargo" "check" "--workspace" "--message-format=json" "--all-targets"
[ERROR rust_analyzer::lsp_utils] cargo check failed

Cargo watcher failed, the command produced no valid metadata (exit code: ExitStatus(unix_wait_status(25856))):
error: could not find `Cargo.toml` in `/home/ahicks/repos/backtrace-backend` or any parent directory


```

I know that `cargo check` etc. in the target directory work, so I think maybe it's not running in the right working directory?

Thanks.  Hopefully this isn't user error, but I don't think it is.

**Comment by jaredtbates** [comment]
I'm running into this too - this worked a week ago, not sure what specific version.

**Comment by Veykril** [comment]
Can you check if the latest pre-release works? The fix for this unfortunately didn't make it into the stable release

**Comment by ahicks92** [comment]
What do I have to do to try it?

**Comment by lnicola** [comment]
@ahicks92 if you're using Code,

![image](https://user-images.githubusercontent.com/308347/197846479-733e0ddc-5255-4ee3-95c2-1abf29e6537c.png)

**Comment by ahicks92** [comment]
I hate to be annoying but I'm blind. Can you provide a description? I probably don't need much to find it so don't worry about being super precise.

Alternatively just link me docs, heh.

**Comment by lnicola** [comment]
Ah, sorry. Code has an Extensions pane where each extension has a "settings" button which opens a menu with Disable, Uninstall etc. There's a "Switch to Pre-Release Version" option in there. Alternatively, on the extension properties/info page there's a button for that (but I'm not sure about the UI, since I'm not at the computer).

If you can't find it, you can get the VSIX for your platform from GitHub releases. There should be one called "nightly" that's replaced every night.

Hope this helps, if not, please ask for more details. It's not annoying.

**Comment by ahicks92** [comment]
It should.  I guess that button is new--I've had to do other vscode prerelease stuff in the past and it was a pain.  Hopefully I didn't just miss it.

I'll try tomorrow when I have the broken repo in front of me again and report back.

Thanks.

**Comment by lnicola** [comment]
The menu/settings/gear icon in the sidebar has been there for ages. The button on the extension page is relatively new, since about a year ago or a little more.

I can look at the UI now, the latter is located after the Disable and Uninstall buttons.

**Comment by Skipper1931** [comment]
I've been having the same issue. Switching to pre-release seems to have fixed it for me.

**Comment by ahicks92** [comment]
Pre-release also fixed it here.

**Comment by Veykril** [comment]
This should be fixed on the latest stable release now, if you still have this problem please open a new issue with appropriate details (of your project structure and whether it used to work 2 versions ago)
