### ISSUE TITLE
Autocomplete for 'mod' continues to offer old filename options when filename case changes

### ISSUE THREAD

**Issue by FOMX** [rust-lang/rust-analyzer#13483]
Issue: 
The autocomplete for ```mod``` continues to offer previous filenames as options if the filename had its case changed. 

Steps to reproduce:
1. new project with the structure
  │   .gitignore
  │   Cargo.lock
  │   Cargo.toml
  └───src
          lib.rs
          main.rs
          my_Mod.rs // with capital Mod
 2. Test auto complete for ```mod my_Mod.rs```
![image](https://user-images.githubusercontent.com/20251588/197755875-947989a8-0ada-4675-ae14-8878fda7f585.png)
3. rename my_Mod.rs to my_mod.rs. 
4. Test auto complete for ```mod my_mod.rs``` 
![image](https://user-images.githubusercontent.com/20251588/197756024-9aad576e-d082-4a5f-8e5d-c249866ade50.png)
5. Repeat steps 3 to 4 with different file name capitalisations.
![image](https://user-images.githubusercontent.com/20251588/197758893-644ed766-f068-409a-a292-3743ad4a0dfc.png)

Notes: 
Deleting the file and remaking it does not affect the behaviour.
Cargo clean does not affect the behaviour. 
Restarting VSCode does not affect the behaviour.
i'm not sure if this is a vscode or a rust-analyzer issue.

i did notice that in the trace, after i've correctly renamed the file it still shows the old file name:
```
[Trace - 10:10:18 pm] Sending request 'textDocument/codeLens - (88)'.
Params: {
    "textDocument": {
        "uri": "file:///  .....  /hello_world/src/my_Mod.rs"
    }
}
```
**rust-analyzer version**: 0.3.1258-standalone (43fb9563b 2022-10-23))

**rustc version**: rustc 1.64.0 (a55dd71d5 2022-09-19)

**relevant settings**: Nothing specific. Vscode 1.72.2, windows 10.

**Comment by Veykril** [comment]
Ye this is a vscode problem, see https://github.com/rust-lang/rust-analyzer/issues/9581
