### ISSUE TITLE
Broken insert module Quick Fix

### ISSUE THREAD

**Issue by RustyYato** [rust-lang/rust-analyzer#13488]
If I create a new module named `label.rs`, depending on where it is in the file hierarchy, it sometimes doesn't give the correct completion.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/16103364/198122390-485a2d6f-f9e9-4918-847d-729bc4739790.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/16103364/198122698-47ba1364-d511-41d2-a3b0-248142220e5d.png">

Then once I manually insert the correct module declaration, it doesn't give completions inside the module. As if it doesn't recognize the module 

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/16103364/198123351-36b8a6b6-1c3a-4bc4-8a11-ea7b75a5be86.png">

**rust-analyzer version**: `rust-analyzer version: 0.3.1258-standalone (43fb9563b 2022-10-23)`

**rustc version**: `rustc 1.66.0-nightly (57f097ea2 2022-10-01)`

**relevant settings**: N/a

Things I've tried out:

I've tried restarting VSCode and the extension to no avail. Uninstalling and reinstalling rust-analyzer (with a full reload of VSCode in between) also didn't help.
I thought that maybe my nightly Rust version was too old, and updated to `rustc 1.66.0-nightly (bed4ad65b 2022-10-25)`, but that also didn't fix the issue

However when using rust-analyzer version rust-analyzer version: `rust-analyzer version: 0.3.1248-standalone (0531aab52 2022-10-16)` I don't experience this issue. (on both rust versions I tried)

**Comment by Veykril** [comment]
This looks like you the file was called `Label.rs` before, but then got renamed. VSCode caches the capitalization of file names for some reason and therefor tells r-a about the old one instead of the new one. See https://github.com/rust-lang/rust-analyzer/issues/9581, to fix you basically have to figure out where the VSCode cache for this workspace lies and delete that.

**Comment by RustyYato** [comment]
I'll check that out

FYI: Forgot to put this in the main ticket, I'm on mac m1, not windows like the other issues so maybe it's something different?

**Comment by Veykril** [comment]
Ah, mac should also be hit by this. Both windows and mac are case insensitive file systems which is what causes this.

**Comment by RustyYato** [comment]
Oh, I see, and yes that did work thanks! 

VSCode cache can be found on mac here: https://stackoverflow.com/questions/39234428/how-do-you-clear-your-visual-studio-code-cache-on-a-mac-linux-machine

**Comment by RustyYato** [comment]
I'm curious why and older version of r-a worked? Maybe VSCode just didn't use the same cache? 🤔

**Comment by Veykril** [comment]
> Maybe VSCode just didn't use the same cache? 🤔

This I would imagine, but honestly no clue. It's questionable as to why this is a no fix on their side even 😩
