### ISSUE TITLE
missing field position_encoding in initializer of ServerCapabilities

### ISSUE THREAD

**Issue by alessandro-baldassarre** [rust-lang/rust-analyzer#13481]
error during installation of cargo modules:

error[E0063]: missing field position_encoding in initializer of ServerCapabilities

/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_rust-analyzer-0.0.134/src/caps.rs:21:5

**Comment by lnicola** [comment]
What are you doing to get this error?

**Comment by alessandro-baldassarre** [comment]
simply: cargo install cargo-modules

**Comment by lnicola** [comment]
See https://github.com/regexident/cargo-modules/issues/137. You'll have to build it from source in the meanwhile.

**Comment by alessandro-baldassarre** [comment]
ok thanks.

**Comment by lnicola** [comment]
We still need to fix this on our side, reopening to track that.

**Comment by alessandro-baldassarre** [comment]
for information, I added the missing field in the file and it worked

**Comment by lnicola** [comment]
`cargo install --locked cargo-modules` might work, too. It picks up `lsp-types 0.93.1` instead of `0.93.2`.

**Comment by TathagataRoy1278** [comment]
Hopping on here.
When I add ra_ap_rust-analyzer as a dependency to my project
(I have only ra_ap_rust-analyzer as a dependency)

and build it throws an error:

```
error[E0063]: missing field `diagnostic_provider` in initializer of `ServerCapabilities`
  --> /home/troy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra_ap_rust-analyzer-0.0.160/src/caps.rs:25:5
   |
25 |     ServerCapabilities {
   |     ^^^^^^^^^^^^^^^^^^ missing `diagnostic_provider`

For more information about this error, try `rustc --explain E0063`.
The following warnings were emitted during compilation:

warning: Could not find `.git/HEAD` from manifest dir!

error: could not compile `ra_ap_rust-analyzer` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

The problem is that `lsp-types 0.94.1` is being compiled instead of `0.94.0` each time I use cargo build on my project.
In the dependency list it says 
`[dependencies.lsp-types]
version = "=0.94"
features = ["proposed"]`

When I compile ra_ap_rust-analyzer from the source, it compiles without a problem, it is when I add it as a dependency, that the problem occurs.  Is there something I am doing wrong?

**Comment by Veykril** [comment]
Ah, we messed up the version pin. That should be `=0.94.0`, lsp-types is not semver compatible with the `proposed` feature flag set so the latest release broke us.

**Comment by TathagataRoy1278** [comment]
I am new to rust, so pardon the dumb question.
Where does cargo check for the dependencies? I changed the `.cargo/registry/src/index.../ra_ap_rust-analyzer/Cargo.toml` to "=0.94.0" but it was still using 0.94.1 when I was building with RA as a dependency. 

Does cargo check for version numbers from some online registry than from the locally downloaded crates?

Thank you.

**Comment by Veykril** [comment]
You should not touch your cargo registry, you should treat that as immutable. The bug here is on our side not yours. You can get around this by adding `[dependencies.lsp-types] version = "=0.94.1" features = ["proposed"]` to your projects Cargo.toml I believe until we fix it in our crate here.

**Comment by TathagataRoy1278** [comment]
(I guess you meant "=0.94.0")
Thank you so much!

**Comment by serle** [comment]
worked using `cargo install --locked cargo-modules`

**Comment by jaabberwocky** [comment]
Encountered this issue too and it worked using `cargo install --locked cargo-modules` as described above.

**Comment by danielmckinnonanderson** [comment]
Just encountered a similar error 'missing field `diagnostic_provider` in initializer of `ServerCapabilities`' when I ran `cargo install cargo-modules`. I am on Windows 11, rustc version 1.72.0, entire toolchain installed w/ rustup. Running `cargo install --locked cargo-modules` was successful, however.
