### ISSUE TITLE
Question: Reasoning behind not being able to install using cargo?

### ISSUE THREAD

**Issue by melMass** [rust-lang/rust-analyzer#13486]
Hi,

Sorry if it's an overlook, but I was wondering why we can't just `cargo install` RA and get a binary in `~/.cargo/bin`?

Thanks

**Comment by bjorn3** [comment]
You can do `cargo install ra_ap_rust-analyzer` if you want. Note that the auto publishing has broken several times in the past.

**Comment by melMass** [comment]
Ah thanks, that's exactly what I needed!
