### ISSUE TITLE
"Remove unnecessary async" assist should not appear in trait impls

### ISSUE THREAD

**Issue by j-tai** [rust-lang/rust-analyzer#13492]
The `Remove unnecessary async` code assist should not be available inside trait implementations. This is because the async is required to conform to the trait interface, so the async is not "unnecessary".

**Reproduce:**

1. Paste the following code

    ```rust
    trait Trait {
        async fn foo();
    }
    
    impl Trait for () {
        ┃async fn foo() {
    
        }
    }
    ```

    `┃` denotes the cursor location.
2. Press `alt+.` to show code assists

**rust-analyzer version**: 0.3.1258-standalone

**rustc version**: 1.64.0 (a55dd71d5 2022-09-19)

**relevant settings**:

**Comment by weirdsmiley** [comment]
@koka831 are you still working on this?

**Comment by koka831** [comment]
hi @weirdsmiley, I just made a PR(https://github.com/rust-lang/rust-analyzer/pull/13508).
