### ISSUE TITLE
Doc link highlighting not working for private members

### ISSUE THREAD

**Issue by decryphe** [rust-lang/rust-analyzer#13493]
Hello everyone!

For the project I'm working on (a company internal business application), we leverage cargo doc to generate the full code and internal application documentation. To do so, we use the `--document-private-items` switch for `cargo doc` to include everything, as it's not a library/crate to be consumed by another application.

It would be very practical to be able to configure this flag for the tooltips displayed with `rust-analyzer`, e.g. with a configuration option `rust-analyzer.hover.documentation.documentPrivateItems`.

**Comment by flodiebold** [comment]
Hover tooltips don't use cargo doc, and generally already shows docs for private items; can you give an example of what you're expecting to happen that doesn't happen currently?

**Comment by decryphe** [comment]
True, I did describe it wrong. The effect I observe is not in the hover documentation but in the syntax highlighting in doc comments. The hover tooltip will show it as a link regardless of it being a valid link or not.

What I see is that for private items the links are not highlighted when writing them, which would otherwise confirm that they are correct. Here's an example for correct links to documentation in the local scope or in a different crate, respectively:
![Screenshot_20221028_140035](https://user-images.githubusercontent.com/12104091/198582845-e029d899-5741-4169-a598-199406631a97.png)

And for links to private items (the module `mgr` is private, i.e. imported via `mod mgr;`), there is no syntax highlighting for members.
![Screenshot_20221028_140930](https://user-images.githubusercontent.com/12104091/198583953-3b1e248b-11ba-4d27-80f4-5d3e64844c9a.png)

The `ModemManager` struct is defined as such in the module `mgr`:
![Screenshot_20221028_140959](https://user-images.githubusercontent.com/12104091/198584032-b8223ab0-0d0a-408a-9de6-fffe3afbe8e2.png)

And the method I link to is public inside `impl ModemManager`:
![Screenshot_20221028_141038](https://user-images.githubusercontent.com/12104091/198584039-ba20e02e-a097-49b2-bad1-4c9429693397.png)

When building the docs with `cargo doc --document-private-items`, the links are resolved correctly, but the highlighting when writing the documentation is missing. Typos only get obvious after building the docs and checking there for correctness.

**Comment by flodiebold** [comment]
Ok, thanks. Are you sure this is actually related to privacy? From my very limited testing, it seems we don't highlight any links to associated items.

**Comment by decryphe** [comment]
You're probably right, it seems no members (associated items?) get highlighted, as I found in a different place of our codebase, a link to `chrono::Utc::now()`:
![Screenshot_20221028_144216](https://user-images.githubusercontent.com/12104091/198589494-5ed72330-0aef-4eab-9474-fd2840b66554.png)

**Comment by Veykril** [comment]
Yes, assoc items not being resolved in intra-doc-links is known -> https://github.com/rust-lang/rust-analyzer/issues/9694

**Comment by decryphe** [comment]
Okay, then the case is clear and this issue can probably be closed.
