### ISSUE TITLE
Some methods from std library are not being suggested

### ISSUE THREAD

**Issue by denis-caylent** [rust-lang/rust-analyzer#13509]
Hello, I'm having an issue where lots of methods from `std::string::String` is not being suggested, but the code works. If a hover my mouse on the `trim_end()` function, is shows `{unknown}` on the tooltip.

```rust
    let mut confirm = String::new();
    io::stdin().read_line(&mut confirm).unwrap();

    if confirm.trim_end().ne("y") {
        println!("Exiting program.");
        std::process::exit(0);
    }
```

**rust-analyzer version**: `0add6e95e 2021-12-20 stable`

**rustc version**: `rustc 1.64.0 (a55dd71d5 2022-09-19)`

**relevant settings**: Using on VSCode on MacOS

**Comment by lnicola** [comment]
Maybe you can try installing a newer version? You can get a VSIX from GitHub.
