### ISSUE TITLE
Incorrect type of variable when implementing operators by macro

### ISSUE THREAD

**Issue by Tearth** [rust-lang/rust-analyzer#13518]
**rust-analyzer version**: v0.3.1258
**rustc version**: rustc 1.64.0 (a55dd71d5 2022-09-19)

The variable type is incorrectly hinted when the struct operators are implemented by macro.

```rust
use std::ops::Add;
use std::ops::Mul;

pub struct Vec2<T> {
    pub x: T,
    pub y: T,
}

macro_rules! implement {
    ($type:ident) => {
        impl Add for Vec2<$type> {
            type Output = Self;
            fn add(self, rhs: Self) -> Self::Output {
                Self::Output { x: self.x + rhs.x, y: self.y + rhs.y }
            }
        }

        impl Mul<Vec2<$type>> for $type {
            type Output = Vec2<$type>;
            fn mul(self, rhs: Vec2<$type>) -> Self::Output {
                Self::Output { x: self * rhs.x, y: self * rhs.y }
            }
        }
    }
}

implement!(i32);
implement!(u32);

pub fn main() {
    let a = Vec2 { x: 1, y: 2 };
    let b = Vec2 { x: 3, y: 4 };
    let res = 5 * (a + b);
}
```

Incorrect behavior when there are two or more `implement!` calls (`res` should be `Vec2<i32>` instead of `i32`):
![image](https://user-images.githubusercontent.com/26147774/198880099-59126a04-f4dd-4277-b072-0d02551e3287.png)

It does display the correct type only when exactly one `implement!` call is present:
![image](https://user-images.githubusercontent.com/26147774/198880110-746c24dd-ec4b-482a-bebd-50cab952921f.png)

As the desired output, it should always hint `res` as being `Vec2<i32>`.

**Comment by lowr** [comment]
Also happens when you manually implement them. If you specify type of any one of the numbers when you construct `Vec2` (like `Vec { x: 1i32, y: 2 }`), we can correctly infer.

I think this is a problem around integer type variables. Slightly reduced:

```rust
use std::ops::Add;

pub struct Vec2<T>(T, T);

impl Add for Vec2<i32> {
    type Output = Self;
    fn add(self, rhs: Self) -> Self::Output { /* ... */ }
}

impl Add for Vec2<u32> {
    type Output = Self;
    fn add(self, rhs: Self) -> Self::Output { /* ... */ }
}

fn main() {
    let a = Vec2(1, 2);
      //^ Vec<i32>
    let b = Vec2(3, 4);
      //^ Vec<i32>
    let c = a + b;
      //^ {unknown} <- this should be Vec<i32>
}
```
