### ISSUE TITLE
`rust-analyzer` took priority on `provideRenameEdits()` events. 

### ISSUE THREAD

**Issue by TechTheAwesome** [rust-lang/rust-analyzer#13524]
I am sorry if any of these are dumb questions; Its my first time making a vscode extension. 😅 

On my extension to add HTML features for yew `html! {}` macro, I used the client's `middleware` options to register some of the features that would trigger if pointer is within valid macro block. And I used `provideRenameEdits` option to hook into `F2/Rename Symbol` feature.

However, it appears that `rust-analyzer` took priority and in turn, the `provideRenameEdits` of my language client never gets called. Is there a way for my extension to tell rust analyzer to let me handle the html parts? Other features like hover & completion items are correctly called. 

There's more details here:  TechTheAwesome/code-yew-server#1.

**Comment by Veykril** [comment]
We probably need to look into https://code.visualstudio.com/api/language-extensions/embedded-languages for this, that is have some mechanism for other services to register themselves for requests?

**Comment by Veykril** [comment]
I don't see how we would control the priority here

**Comment by lnicola** [comment]
> I used the client's middleware options to register some of the features that would trigger if pointer is within valid macro block

Maybe one of the recent changes affected this?

@TechTheAwesome can you bisect this, either using `git` or the GitHub releases?

**Comment by TechTheAwesome** [comment]
>  can you bisect this, either using `git` or the GitHub releases?

I did a quick `git bisect` and apparently the issue started with this commit 9ad0a8c4673059c22d2f55e14b8ee05f47237f80.
Do note that right now, my extension's rename still not working, but the `provideRenameEdits()` hook is properly called until the above commit.

**Comment by lnicola** [comment]
It looks like we don't always call the `next` handler in our middleware, but I don't know if we're actually intercepting `provideRenameEdits`.

**Comment by TechTheAwesome** [comment]
> It looks like we don't always call the `next` handler in our middleware, but it doesn't seem like we're actually intercepting `provideRenameEdits`.

Update: I have no clue what happens, but trying to bisect again, the latest release now works correctly... Is there a race condition happening for language clients? I changed nothing, just restarted vscode...

**Comment by Veykril** [comment]
I imagine it just depends on what extension registers first

**Comment by TechTheAwesome** [comment]
> I imagine it just depends on what extension registers first

That's what I'd think too, since my extension calls `next` when it's not inside `html! {}`, I suspect `next` then goes fetch rust analyzer's response. But when RA gets called first, it returns prematurely with an error :open_mouth: ?

**Comment by TechTheAwesome** [comment]
One thing is weird, RA seems to skip the command api entirely, and interrupts vscode before it has the chance to reach to the API part. Because the flow should be `F2` /`Rename Symbol` -> Textbox -> API call to the valid language server.  But with RA, its `F2` -> Error from language server. ?

**Comment by lnicola** [comment]
There's a [textDocument/prepareRename](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareRename) request, maybe we're failing that?

> Edit: Is there an easy way to sniff JSON RPC packages? Maybe that'll give us some clue.

Sure, either set `"rust-analyzer.trace.server": "verbose"` or use the `RA_LOG=lsp_server=debug` environment variable.

**Comment by TechTheAwesome** [comment]
> There's a [textDocument/prepareRename](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareRename) request, maybe we're failing that?
Thank you so much for the suggestion, it is indeed the fact that `rust-analyzer` is failing the `prepareRename` call.
This issue is fixed by adding prepareRename to client's middleware. 
Client:
```ts
async prepareRename(document, position, token, next) {
if (!isInsideHTMLRegion(document.getText(), document.offsetAt(position))) {
	return await next(document, position, token);
}
const result = await commands.executeCommand<Range>(
	'vscode.prepareRename',
	vdocUri(document),
	position
);
return result;
},
```
Server: 
```ts
capabilities: {
	renameProvider: {
		prepareProvider: true,
	},
}
```
I'll close this issue for now :) Thanks everyone for your help!

**Comment by lnicola** [comment]
I wonder if we could fix that on our side (by calling `next` if our `prepareRename` call fails).

**Comment by TechTheAwesome** [comment]
> I wonder if we could fix that on our side (by calling `next` if our `prepareRename` call fails).

I think it would still require the middleman extension to implement a `prepareRename` call. So a better way is still for vscode to document this behavior me thinks.
