### ISSUE TITLE
Diagnostic warning despite #[allow(non_snake_case)] and incorrect fix for Greek characters

### ISSUE THREAD

**Issue by vankessel** [rust-lang/rust-analyzer#13521]
**rust-analyzer version**: 0.4.1265-standalone (ba28e19b7 2022-10-29)

**rustc version**: 1.64.0 (a55dd71d5 2022-09-19)

RA doesn't seem to take attributes into account. `#[allow(non_snake_case)]` is hidden behind the tooltip in this photo:

![Screenshot 2022-10-30 191146](https://user-images.githubusercontent.com/10148659/198917575-ee2e2855-febe-4087-8799-953e1abdd9e5.png)

Also, the recommended fix also doesn't change anything. It should suggest lowercase delta, δ. This also happens for the other Greek characters like lamda. I suspect all non-ascii characters with lowercase and uppercase variants suffer from this.

Possibly related:
#8747
#12651

**Comment by lowr** [comment]
We currently don't have a means to handle attributes on expressions/attributes. This is probably to be tracked in #6541.

As for the incorrect fix, that's a distinct problem and should be fixed separately.
