### ISSUE TITLE
Consider on-boarding to Sponsorship

### ISSUE THREAD

**Issue by isidorn** [rust-lang/rust-analyzer#13539]
Hi VS Code PM here 👋 

I noticed you have an Open Collective page https://opencollective.com/rust-analyzer

Consider on-boarding to Extension Sponsorhip https://code.visualstudio.com/api/working-with-extensions/publishing-extension#extension-sponsor

That way the UI in VS Code will directly link to the Open Collective page you have.

**Comment by Veykril** [comment]
The open collective is run by a third party as a separate fund for the project as such we are not allowed to point to it from the official project resources unfortunately.
