### ISSUE TITLE
Any plan to update `rust-analyzer` at crates.io?

### ISSUE THREAD

**Issue by pd4d10** [rust-lang/rust-analyzer#13533]
The `rust-analyzer` package [at crates.io](https://crates.io/crates/rust-analyzer) was published 3 years ago.

Is there any plan to publish it with the latest codebase? So it could be used programmatically.

**Comment by bjorn3** [comment]
You are probably looking for ra_ap_rust-analyzer which is updated weekly.

**Comment by pd4d10** [comment]
> You are probably looking for ra_ap_rust-analyzer which is updated weekly.

Oh, thanks, see it at `.github/workflows/publish.yml`. Closing

BTW, should we mention it somewhere in the documentation?
