### ISSUE TITLE
Is there a way to invert the order clippy/rustc?

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/rust-analyzer#13542]
I'm using this in VSCode `settings.json`:

```json
{
  "rust-analyzer.checkOnSave.command": "clippy",
}
```

it works good.

But I would like to have `rustc` errors before and only after the `clippy` errors/warnings because sometimes `clippy` can take many more seconds than `rustc`.

Is there a way to invert the order?

_Note: I opened https://github.com/rust-lang/vscode-rust/issues/966 too._

**Comment by bjorn3** [comment]
As @lnicola already said on the other issue we never run rustc if you specify clippy. It just so happens that clippy produces a superset of the diagnostics of rustc. If you want to run rustc and then clippy you will probably have to override the command to sonething like `sh -c 'cargo check && cargo clippy'` using `rust-analyzer.checkOnSave.overrideCommand`. Do note that it takes an array, so you did have to do something like `["sh", "-c", "cargo check && cargo clippy"]`.

**Comment by frederikhors** [comment]
So should I ask to clippy's team this? I'm not understanding...

**Comment by bjorn3** [comment]
The following configuration should work to run `cargo check` and then `cargo clippy`. Note that this will give duplicate warnings for warnings produced by rustc itself. If you want clippy to run even if rustc fails, you can replace `&&` with `;`.

```json
{
    "rust-analyzer.checkOnSave.overrideCommand": ["sh", "-c", "cargo check --message-format json --workspace --all-targets && cargo clippy --message-format json --workspace --all-targets"]
}
```

**Comment by frederikhors** [comment]
Thank you very much for this.

But I am convinced that using a custom command does not solve the problem that I think is useful for everyone: given the slowness that can sometimes be during dev, it would be useful to prioritize errors and only then to warnings.

And I think this needs to be done by default.

Can I ask the clippy team, what do you think?

**Comment by bjorn3** [comment]
Running `cargo check` and then `cargo clippy` is slower than running just `cargo clippy` as it is doing twice the amount of work. As such I don't think it should be the default.

**Comment by frederikhors** [comment]
Apparently I can't well explain my idea/request.

You have proposed to use a double command.

I don't know who to ask this, instead:

- I really like `clippy` warnings and errors cause them are vital for a good project;

- sometimes when I'm writing code and save I realize that VSCode shows me the warnings first and only then the errors (using only `"rust-analyzer.checkOnSave.command": "clippy"`);

- instead I would like VSCode to show me the errors IMMEDIATELY and ONLY AFTER the warnings; also because in the meantime - after fixing the errors - it may be that I have already saved the files again.

**Comment by lnicola** [comment]
Does `cargo clippy` show the errors and warnings in the order you want? I doubt so, as it could be compiling multiple crates at once, and there's no point in talking about the order in that case.

> But I would like to have rustc errors before and only after the clippy errors/warnings because sometimes clippy can take many more seconds than rustc.

If you set `rust-analyzer.checkOnSave.overrideCommand` to `clippy`, we run `cargo clippy`. `clippy` includes or somehow uses `rustc`. We certainly don't run `rustc` to show you the errors.

---

You could also try to rely less on `clippy`. You can run it manually once in a while. You can even disable `check` completely and rely on the native diagnostics in RA. Of course, those are more limited (and need a bit of setup), but they work well enough IME.

**Comment by lnicola** [comment]
The idea is that there's no way to control the order in which diagnostics are emitted. If you code has compilation errors, some diagnostics might not even show at all.

The only way to make sure that the errors show up first (as @bjorn3 mentioned) would be to run `cargo check` first, then `cargo clippy`. But that would use quite a bit more CPU than a single `cargo clippy`. It's also not what we want in the long run. Our native diagnostics can run directly on the code you've edited. If you edit a single function, there's usually no need to check for errors in other functions which don't call the one you changed. On the other hand, `cargo clippy` will need to check the whole project, on every file save.
