### ISSUE TITLE
Still unusable comparing to RLS -- cannot go to definition, even declared at the same file

### ISSUE THREAD

**Issue by Mingun** [rust-lang/rust-analyzer#13551]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
0.4.1273-standalone (66900a7e0 2022-11-04)

**rustc version**: (output of `rustc -V`)
rustc 1.65.0 (897e37553 2022-11-02)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
Nothing unusual, never change the defaults.

rust-analyzer cannot go to the definition of any symbol in those file:
https://github.com/tafia/quick-xml/blob/master/src/de/mod.rs

RLS has never had such problems.

**Comment by lnicola** [comment]
https://user-images.githubusercontent.com/308347/200123581-ed14c418-d785-4d96-9713-a6f3ff9d1136.mp4

You need to set `"rust-analyzer.cargo.features": "all"` (or to `["serialize"]`) for it to work.

**Comment by Mingun** [comment]
Thanks, that is solves problem. This means that analysis within one file will not work at all if this file is not in some project? RLS, in my opinion, worked even in this case (not sure and cannot check that now because it is no longer worked).

**Comment by lnicola** [comment]
> This means that analysis within one file will not work at all if this file is not in some project?

Yes. There's even a (pretty subtle) warning:

![image](https://user-images.githubusercontent.com/308347/200124354-fd41d32e-f2c3-4aa1-8b0d-37086bf08cb0.png)

> RLS, in my opinion, worked even in this case

I don't know what RLS did, but I'm not too keen on finding out. We have some support for files outside of a project, but it's pretty poor. In this specific case we could enable all the features, but that won't work in general, since some projects have conflicting features.

**Comment by flodiebold** [comment]
I think treating the file as a stand-alone file would lead to a pretty bad experience anyway. It'd be nice if we could detect that the file is cfg'd out.

**Comment by Mingun** [comment]
Processing of incomplete input is what distinguishes a more-less-working analyzer from a well-working one. At least the following cases could be processed without requiring file to be part of any project and even be a file at all (i.e. it should work in a not saved buffer):
- usage of `std` types
- usage of types declared in that file (buffer)
- (heuristic) usage of types found in surrounding files

**Comment by flodiebold** [comment]
> usage of std types
> usage of types declared in that file (buffer)

Sure. If go to definition in https://github.com/tafia/quick-xml/blob/master/src/de/mod.rs had worked for std types, but not for e.g. `serde`, would you have considered it "usable" though? I doubt it.

> (heuristic) usage of types found in surrounding files

Probably not. Apart from being very complicated to implement, I think there are many situations where this would lead to false positives.

**Comment by Mingun** [comment]
> would you have considered it "usable" though?
Yes. The `serde` part can be covered by heuristic part

> I think there are many situations where this would lead to false positives.

Usually, if you have a file that in not in any project, but stored in project folder, it is referenced to types, defined in that project. So it would be logical to be able to use them as best choice.

The situation with unsaved buffer is similar, except that extension must know, from which buffer the new buffer was created. Explanation: when you press <kbd>Ctrl</kbd>+<kbd>S</kbd> to save the buffer, VSCode will suggest you a folder where to save it. That folder is inherited from the last used buffer that is associated with a file. So, if you open `path/to/file.rs`, then press <kbd>Ctrl</kbd>+<kbd>N</kbd>, the VSCode will suggest `path/to` as a location for saving file. If you then open another file at `path/to/another/file.rs` and press <kbd>Ctrl</kbd>+<kbd>N</kbd>, <kbd>Ctrl</kbd>+<kbd>S</kbd> again, the location to save will be `path/to/another`. That is rationale defaults, and it could be useful if rust-analyzer could use them (or a project, inherited from that locations) to resolve types in unsaved buffer.
