### ISSUE TITLE
Extract to function/variable unescapes '\\'

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [rust-lang/rust-analyzer#13558]
This is similar to #11897, but for extracting to function/variable instead of snippet completion.

**rust-analyzer version**: rust-analyzer 1 (ba28e19b78 2022-10-29)

**rustc version**: rustc 1.62.0-nightly (30f386087 2022-05-05)

**relevant settings**: None, I think

Example:
```
fn main(){
    let a = "\\ $0";
}
```
selecting the enther `let a` line and doing `extract to variable` results in
```
fn main(){
    let var_name = &"\ ";
    let a = var_name;
}
```

I.e., both the `\\` and the `$0` are replaced wrongly.

**Comment by lnicola** [comment]
Fixed in #16467
