### ISSUE TITLE
Go to definition is confused with nested macros

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust-analyzer#13555]
**rust-analyzer version**: `0.4.1273-standalone`

**rustc version**: `nightly-2022-11-04`

When a macro defines another macro, the go to definition hint doesn't point at the original definition of the identifier anymore.

Without the nesting, it correctly points to the identifier in the macro invocation.

This issue comes up in the rustc query system, where go to definition doesn't point at the declaration of the query but at the invocation of the nested query macro instead.

```rust
macro_rules! declare {
    ($name:ident) => {
        macro_rules! nested {
            () => {
                fn $name() {}
            };
        }
    };
}

fn main() {
    uwu();
 // ^^^ Go To Definition here
}

nested! {}
// ^^^^^^^ Points at this invocation

declare! { uwu }
        // ^^^ Instead of this identifier here
```

**Comment by Veykril** [comment]
This now works as exepcted, pointing to the `nested` macro call but also to the `uwu` token in the `declare` call
