### ISSUE TITLE
error[E0658]: `let...else` statements are unstable

### ISSUE THREAD

**Issue by vizvasrj** [rust-lang/rust-analyzer#13562]
error[E0658]: `let...else` statements are unstable
I am compiling rust analyzer and here it cause some problem
[https://rust-analyzer.github.io/manual.html#building-from-source](https://rust-analyzer.github.io/manual.html#building-from-source)

```

└─# cargo xtask install                                                        1 ⨯
    Finished dev [unoptimized] target(s) in 0.26s
     Running `target/debug/xtask install`
$ cargo install --path crates/rust-analyzer --locked --force --features force-always-assert
  Installing rust-analyzer v0.0.0 (/root/Project/whatsapp-webhook/myrust/rust-analyzer/crates/rust-analyzer)
    Updating crates.io index
   Compiling ide v0.0.0 (/root/Project/whatsapp-webhook/myrust/rust-analyzer/crates/ide)
error[E0658]: `let...else` statements are unstable
  --> crates/ide/src/rename.rs:43:13
   |
43 | /             let Some(frange) = sema.original_range_opt(name_like.syntax()) else {
44 | |                 bail!("No references found at position");
45 | |             };
   | |______________^
   |
   = note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `ide` due to previous error
error: failed to compile `rust-analyzer v0.0.0 (/root/Project/whatsapp-webhook/myrust/rust-analyzer/crates/rust-analyzer)`, intermediate artifacts can be found at `/root/Project/whatsapp-webhook/myrust/rust-analyzer/target`
Error: install server

Caused by:
    command exited with non-zero code `cargo install --path crates/rust-analyzer --locked --force --features force-always-assert`: 101
```

**Comment by lnicola** [comment]
You need to use the latest stable toolchain.

**Comment by jhgg** [comment]
> You need to use the latest stable toolchain.

I wonder if we should include a `rust-toolchain` file in r-a git repo, so that cargo will automatically select the correct tool chain to build against?

**Comment by lnicola** [comment]
There's a `rust-version` clause in the manifests, it just wasn't updated (just like a rust-toolchain.toml might not be).  And I personally dislike the latter.

**Comment by Veykril** [comment]
Ye we should just try to update the rust-version when a new release happens, I am not fond of a `rust-toolchain` file either

**Comment by jhgg** [comment]
I am curious why are you not fond of the tool chain file?

**Comment by lnicola** [comment]
I used to accumulate outdated toolchains installed by projects that were using them. That's fine for nightlies, but I don't see how it's better than the `rust-version` field (we're also using the 2021 edition, so a `cargo` that doesn't know about `rust-version` won't know about the edition either).
