### ISSUE TITLE
Include rustc diagnostic ASCII art in popup

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust-analyzer#13574]
Currently rust-analyzer leverages the structured json output from rustc when presenting diagnostics from rustc. This is great because it translates the provided spans into links that people can click to get to the right place, but removes sometimes critical context (from both newcomers and experts alike).

The rustc ASCII art output isn't perfect, and the one provided by the json output doesn't provide formatting information, and VSCode doesn't let us replicate or even improve over it without [writing a full blown webview](https://code.visualstudio.com/api/extension-guides/webview) that would have to handle everything on its own and not be able to pop up in place on hover, **but** we can use the ASCII art, stick it in a codeblock in the current pop up and gain back some of the context back. We might want to only extend the current output, or we could replace everything but the main error message (this could even be configurable).

I think doing this, even if imperfect, is important because it happens way too often that someone comes to one of our support pages asking for help, and when asked to provide the cli output they finally notice that the solution is already provided for them.

CC @Veykril

**Comment by Veykril** [comment]
So unfortunately, diagnostic popups don't permit markdown, but it is rendered in a monospace font so that should be fine. The other problem though is that the handling of rustc diagnostics is a mess (the `Diagnostic` struct we parse from the json has way too many different things that I need to wrap my head around first, like what even are child diagnostics? Why can a diagnostic have multiple primary spans or rather what is the difference between a primary and non primary one) so I wouldn't even know where to attach the original rendered diagnostic message to.
And on another note, the VSCode team has a meeting tomorrow where some of our VSCode troubles will be raised (including the diagnostics troubles, see https://github.com/microsoft/vscode/issues/165810)

**Comment by estebank** [comment]
> So unfortunately, diagnostic popups don't permit markdown, but it is rendered in a monospace font so that should be fine. 

I recall having read the docs some time back that markdown was allowed in popups, but it might have been on custom popups, which I wouldn't want to burden you with trying to get working, this was meant as a "fast an easy" win.

> the json has way too many different things that I need to wrap my head around first

Yeah, it has to encode too much info *and* it wasn't designed, it just grew.

>  what even are child diagnostics? 

note and help blocks.

> Why can a diagnostic have multiple primary spans or rather what is the difference between a primary and non primary one)

The primary spans are those that are underlined in red in the main subdiagnostic (and in cyan or yellow in help, notes and warnings), while the secondary spans are all the ones underlined in color blue. The primary span is where the error actually is, and the others "merely" provide context. There can be more than one primary span because we try to underline as little as possible, so if we have an error of `a` and `b` not being fields in struct `S`, for `S { a, b }` we have two primary spans for `a` and `b` (instead of the whole struct literal).

> And on another note, the VSCode team has a meeting tomorrow where some of our VSCode troubles will be raised (including the diagnostics troubles, see https://github.com/microsoft/vscode/issues/165810)

For that meeting, I would love it if you could show some good example of a complex diagnostic, like a [trait object safety](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=38dfc8a10648ef9b6e224b81d27db64f) or [trait bound](https://twitter.com/ekuber/status/1543311592330108928/photo/2) error to give them context on what our requirements can be.

**Comment by davidbarsky** [comment]
tomorrow's meeting was unfortunately canceled for, uh, reasons, but i'll get that over.

**Comment by Veykril** [comment]
Not like the meeting would solve this immediately anyways, as long as it still happens at some point that's what's important :)
