### ISSUE TITLE
rust-analyzer crashes on Qt Creator 8

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#13575]
> @installgentoo the QtCreator report seems unrelated. Depending on whichever problem you're running into, consider running `cargo check` from the terminal to watch the registry being updated, or filing a new issue whatever panic Qt Creator is running into.

in the latest log that i ran with debug i get
```    "error": {
        "code": -32801,
        "message": "waiting for cargo metadata or cargo check"
    },
```
and then analyzer crashes. Notably everything works on 7, where QtCreator apparently communicated synchronously to the server(or ignored "Initialized" response, i'm not quite sure yet), creator displays a little "cargo check" progress popup. And everything indeed fetches and works.

_Originally posted by @installgentoo in https://github.com/rust-lang/rust-analyzer/issues/10910#issuecomment-1306042191_

**Comment by lnicola** [comment]
@installgentoo my Qt Creator doesn't seem to support Rust or Cargo projects and I don't see any plugin for it. Do you have some tips to get it working? I'll try to take a look tomorrow.

If not, you could use `strace` on the server process to see the panic message.

**Comment by lnicola** [comment]
Ref https://bugreports.qt.io/browse/QTCREATORBUG-27856.

```
[ERROR rust_analyzer] Unexpected error: client exited without proper shutdown sequence"
```

The linked issue says that Qt Creator isn't closing our input.

**Comment by installgentoo** [comment]
![2022-11-08-075818_1920x1056_scrot](https://user-images.githubusercontent.com/2088917/200392376-2587b914-4e23-481e-8b57-38992ddf3e64.png)
you set this in options and rls.sh is just
```
#!/bin/bash
export CARGO_HOME="/_/code/.cache_rust"
export CARGO_TARGET_DIR="/_/code/.cache_rust"
/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rust-analyzer "$@"
```

You can simply add all the files from rust project to new plain-c project, and then "Add all files from directory" by right-clicking on the project name.
![2022-11-08-080036_885x517_scrot](https://user-images.githubusercontent.com/2088917/200392727-c2764b80-2746-4f6b-bfaa-78b549eafbae.png)
![2022-11-08-080148_226x225_scrot](https://user-images.githubusercontent.com/2088917/200392893-51334022-aa4c-4e7c-bd11-88667c57efd4.png)

**Comment by davschul** [comment]
I've attached a log of all messages send between the client and the server.
[rust-analyzer.log](https://github.com/rust-lang/rust-analyzer/files/9970644/rust-analyzer.log)

**Comment by installgentoo** [comment]
Qt people fixed it, might be relevant to parent issue.

**Comment by lnicola** [comment]
Yeah, https://bugreports.qt.io/browse/QTCREATORBUG-27856 seems fixed and points to https://bugreports.qt.io/browse/QTCREATORBUG-28598.
