### ISSUE TITLE
`implement missing members` do not work with async macro

### ISSUE THREAD

**Issue by washanhanzi** [rust-lang/rust-analyzer#13595]
`Implement missing members` right now don't work with async macro, like:

```
#[tonic::async_trait]
impl MyService for Server{}
```
When I delete `async_trait` macro, `implement missing members` properly showed up, but the code is non async, which returns `Pin<Box<>>` 

**rust-analyzer version**: 0.3.1277-standalone (d03c1c87d 2022-11-05)

**rustc version**: 1.65.0 (897e37553 2022-11-02)

**Comment by bjorn3** [comment]
Supporting this correctly would require hard coding support for async_trait as all rust-analyzer sees after the macro expansion of `#[tonic::async_trait]` when defining the `MyService` trait is a non-async method returning `Pin<Box<T>>`.

**Comment by Veykril** [comment]
`rust-analyzer.procMacro.ignored`  on the async trait proc macro should make things work here again. As was stated we can't really to do too much here.
