### ISSUE TITLE
Can we make go-to-def on the `self` arg of a method jump to the Type being impl'ed?

### ISSUE THREAD

**Issue by csmoe** [rust-lang/rust-analyzer#13594]
```rust
struct Foo;

impl Foo {
/*
 too many lines
 ...
*/
  fn bar(&self) {  }
          ^^^^ go-to-def here
}
```
go-to-def should jump to `struct Foo`.

**Comment by Veykril** [comment]
the `self` there is the definition of the `self` local, so the current behavior seems correct to me. I could see `Go to type` going to the impl though, as technically that's where the `Self` type is declared and from there you can usually go to the proper type if so desired. But I am unsure whether we do want to do that

**Comment by csmoe** [comment]
Thanks, `typeDefinition` works for me.
