### ISSUE TITLE
Having custom `core` module in scope breakes builtin `derive(Clone)` macro

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust-analyzer#13600]
## Reproduction code
```rust
mod core {}

#[derive(Clone)]
struct Foo;

fn main() {
    let _ = Foo.clone();
    //          ^^^^^ this method call is not resolved according to rust-analyzer
}
```

## Demo
<img width="400" src="https://user-images.githubusercontent.com/36276403/201229472-411062a8-c940-46b4-8a87-576e169c2d21.gif"></img>

## Other reproductions

The real use case where this happened is in a reexport in our library that wraps the `rusoto` AWS SDK:
```rust
pub use rusoto_core as core;
```

So reexport of modules `as core` also suffer from the same problem.

## Meta

**rust-analyzer version**: rust-analyzer version: 0.3.1277-standalone
**rustc version**: rustc 1.64.0 (a55dd71d5 2022-09-19)

**Comment by jonas-schievink** [comment]
Perhaps this should produce `::core` instead of a plain `core`?

https://github.com/rust-lang/rust-analyzer/blob/599142c34abad1442994947bd1200ce0bc973c54/crates/hir-expand/src/builtin_derive_macro.rs#L154

**Comment by lnicola** [comment]
Yup, this works, but then `tt.token_trees[0]` two lines below will point to the `::` token instead. I couldn't figure out if `quote!` supports a `Subtree` or we need some other way of splicing the whole thing in the expansions.

**Comment by lnicola** [comment]
Fixed by https://github.com/rust-lang/rust-analyzer/pull/16308.
