### ISSUE TITLE
proc macro errors are attached to the wrong location in diagnostics.

### ISSUE THREAD

**Issue by jhgg** [rust-lang/rust-analyzer#13616]
this is a regression of #12657 which was fixed by #12691

Here are some ways to reproduce it, each which seem to map the error span to weird locations:

![image](https://user-images.githubusercontent.com/5489149/201551045-3bb10fbc-da48-40ab-8a57-b8697988f457.png)

```rust
use serde::Deserialize;

fn main() {}

#[derive(Deserialize)]
#[serde(rename_all = "wrong")]
struct Foo {}
```

And from the original issue report:

![image](https://user-images.githubusercontent.com/5489149/201551087-4bf7a1eb-0844-426b-8465-7d23e1cb353d.png)

```rust
#[tokio::main(heck)]
async fn main() {}

fn world() {
    println!("hello");
    println!("hello");
    println!("hello");
    println!("hello");
    println!("hello");
    println!("hello");
    println!("hello");
    println!("hello");
    println!("hello");
}
```

rust-analyzer version: 0.4.1283-standalone
rustc version: 1.65.0 (897e37553 2022-11-02)

**Comment by Veykril** [comment]
We should probably try to make a test for this proc-macro behavior at least 😬 (curious to see what regressed this 🤔)
