### ISSUE TITLE
No way to ignore errors caused by `#[cfg()]`

### ISSUE THREAD

**Issue by JonahPlusPlus** [rust-lang/rust-analyzer#13618]
**rust-analyzer version**: 0.3.1277-standalone (d03c1c87d 2022-11-05)
**rustc version**: rustc 1.65.0 (897e37553 2022-11-02)
**relevant settings**: Not Applicable

## Problem

I have an example, "substantive", that I want to fail if users run with the "procedural" feature. To assure the program fails at compile time, I added the following:

```rust
#[cfg(feature = "procedural")]
compile_error!("Compile without `procedural` feature: `cargo run --example substantive --no-default-features --features detection`");
```

However, "procedural" is a default feature, so rust-analyzer sees this and marks it as an error. I would like some way to ignore this error, without turning off the feature for the entire project.

## Solutions
1. Some sort of attribute, like `#[ra(ignore)]`.
   Pros: Easy to write, inline style
   Cons: RA doesn't have anything like this, to my knowledge, and would take more work to implement.
2. Target-specific settings. Set the features for the example.
   Pros: Gets rid of the error by actually solving the problem.
   Cons: Are these settings defined in Cargo.toml or another file? Cargo.toml makes more sense, but it would still require RA integration.

**Comment by JonahPlusPlus** [comment]
For now, I;m just going to make it `panic!` instead. Not ideal, but removes the error.

**Comment by Veykril** [comment]
You can add features that r-a should enable for its analysis via the `rust-analyzer.cargo.features` config

**Comment by jonas-schievink** [comment]
You can turn off the default features by setting `rust-analyzer.cargo.noDefaultFeatures` to `true`.
