### ISSUE TITLE
thread 'Worker' panicked at 'internal error: entered unreachable code: autoderef not possible for ?109', crates/hir-ty/src/method_resolution.rs:549:21

### ISSUE THREAD

**Issue by ethercflow** [rust-lang/rust-analyzer#13626]
**rust-analyzer version**: version: 0.0.0 (8292dd802 2022-11-15)

**rustc version**:  rustc 1.64.0

**Reproduce step:**
1. git clone https://github.com/tikv/tikv
2. open https://github.com/tikv/tikv/blob/master/components/raftstore/src/store/fsm/apply.rs

Below is the error log:
[err.log](https://github.com/rust-lang/rust-analyzer/files/10026939/err.log)

Thanks!

**Comment by lowr** [comment]
It might've been fixed by #13624. Could you try the latest nightly release and see if the issue persists?

**Comment by ethercflow** [comment]
> It might've been fixed by #13624. Could you try the latest nightly release and see if the issue persists?

It works, thansk!
