### ISSUE TITLE
Implement default memebers should not be applicable in bodies

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust-analyzer#13630]
![Screenshot_20221117_225006](https://user-images.githubusercontent.com/1711539/202576905-e01773e5-6498-4a8f-bf7a-7ac74dded4f0.png)

This feels like a false suggestion: I am in thee middle of a function, I definitely don't want to implement default memebers here.

**Comment by jonas-schievink** [comment]
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/13561, I think

**Comment by lnicola** [comment]
Probably in #13576.
