### ISSUE TITLE
Auto-completion action of match variants is not fired when dealing with arrays

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-analyzer#13643]
Feel free to close if duplicated. Perhaps the action is also not fired with other structures?

```rust
let foo = true;
let bar = true;

// Fires auto-completion
match (foo, bar) {}

// Meh, no action
match [foo, bar] {}
```

**Comment by c410-f3r** [comment]
Closing due to the lack of activity.

**Comment by c410-f3r** [comment]
Closing due to the lack of activity.

I am house-keeping my dashboard closing issues that will probably take time to resolve and are not on my radar any more. If desired, feel free to create another issue.

**Comment by lnicola** [comment]
Sigh, filed #13970.
