### ISSUE TITLE
r-a wrongly suggests to remove a used  function parameter

### ISSUE THREAD

**Issue by dheijl** [rust-lang/rust-analyzer#13645]
r-a v0.4.1290 pre-release, VSCode, Windows, rust 1.65.0

![afbeelding](https://user-images.githubusercontent.com/2384545/202854275-5345a318-eac1-4b3b-a9f7-e9cb72f50d1e.png)

The parameter _server_port_ is clearly used in the following _format!_ macro but r-a does not see this.
I tried to reproduce in a simple test program but could not trigger the error.

**Comment by Veykril** [comment]
That diagnostic comes from rustc, those diagnostics are only updated when you save the file.

**Comment by bjorn3** [comment]
Rustc calls it "unused variable". "Remove unused parameter" comes from rust-analyzer: https://github.com/rust-lang/rust-analyzer/blob/38fa47fd79b38d3ca7665943a93c577d3a9166a8/crates/ide-assists/src/handlers/remove_unused_param.rs#L15-L34

**Comment by Veykril** [comment]
Oh, I thought it a diagnostic and assumed r-a didn't have this since nothing appeared when i tried it locally, nvm then.

**Comment by flodiebold** [comment]
This is #11260
