### ISSUE TITLE
Unable to set sysroot via configuration

### ISSUE THREAD

**Issue by lcheylus** [rust-lang/rust-analyzer#13666]
**rust-analyzer version**: build from sources release 2022-11-21

**rustc version**: rustc 1.65.0

I tried to set specific path for `sysroot` because I use a personal installation for `rust-src` (not installed via `rustup`). But my configuration is not correctly used to discover `sysroot`.

I used **Neovim LSP via lspconfig plugin** to use `rust-analyzer` : 
```
lspconfig.rust_analyzer.setup({
  capabilities = capabilities,

  name = 'rust_analyzer',
  cmd = { 'rust-analyzer', '-v', '--log-file', '/tmp/rust-analyzer.log' },

  filetypes = { 'rust' },

  settings = {
    ["rust-analyzer"] = {
      cargo = {
        sysroot = "<path to rust-src>"
      }
   },
  },
})
```

With `RA_LOG=info` to logs infos, I have these errors :
```
[INFO rust_analyzer::reload] will fetch workspaces cause=startup
[INFO rust_analyzer::config] updating config from JSON: {
  "cargo": {
    "sysroot": "<path to rust-src>"
  }
}
[INFO rust_analyzer::config] updating config from JSON: {
  "cargo": {
    "sysroot": "<path to rust-src>"
  }
}
[INFO project_model::sysroot] adding rust-src component by "rustup" "component" "add" "rust-src"
[INFO rust_analyzer::reload] did fetch workspaces [Err(Failed to find sysroot for Cargo.toml file /home/fox/dev/StyLua.git/Cargo.toml. Is rust-src installed?

Caused by:
    can't load standard library from sysroot
    /usr/local
    (discovered via `rustc --print sysroot`)
    try installing the Rust source the same way you installed rustc)]
[INFO rust_analyzer::reload] will switch workspaces cause=fetched workspace
[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml file /home/fox/dev/StyLua.git/Cargo.toml. Is rust-src installed?: can't load standard library from sysroot
/usr/local
(discovered via `rustc --print sysroot`)
try installing the Rust source the same way you installed rustc
```

According to the logs, my configuration for `sysroot` is correctly set from config but not used to discover `sysroot` : output from `rustc --print sysroot` is used instead as with the default configuration value `discover` for `sysroot`.

**Comment by Veykril** [comment]
Hmm, the only place I can see this happening is if you don't have a cargo project opened, but a detached files workspace instead as we aren't handling the config there. Opened https://github.com/rust-lang/rust-analyzer/pull/13667 to fix that.

Though given the logs you posted it looks like you are in a Cargo workspace hmm

**Comment by lcheylus** [comment]
Yes, I confirm : I tried to use `rust-analyzer` in a workspace with a `Cargo.toml` file, not in a detached files workspace.
