### ISSUE TITLE
Import assist not shown for Lsb0 from bitvec crate

### ISSUE THREAD

**Issue by burjui** [rust-lang/rust-analyzer#13674]
**rust-analyzer version**: rust-analyzer version: 0.4.1297-standalone
**rustc version**: rustc 1.65.0 (897e37553 2022-11-02)

**Cargo.toml:**
```toml
# ...
[dependencies]
bitvec = "1.0.1"
```

**main.rs:**
```rust
use bitvec::view::BitView;

fn main() {
    let x = 0u8;
    x.view_bits::<Lsb0>();
}
```
When I press `Ctrl+.` with the caret at `Lsb0`, VSCode says "no code actions available", but will suggest the "import" and "qualify" assists for `BitView`. If I manually import `Lsb0` (bitvec::order::Lsb0) , RA will work with it just fine - find usages, jump to definition, etc.

**Comment by jonas-schievink** [comment]
Auto-import completion also does not suggest it

**Comment by Veykril** [comment]
This works now
