### ISSUE TITLE
Auto complete for Rust not working

### ISSUE THREAD

**Issue by patfr** [rust-lang/rust-analyzer#13685]
**rust-analyzer version**: rust-analyzer version: 0.3.1293-standalone (26562973b 2022-11-20)

**rustc version**: rustc 1.65.0 (897e37553 2022-11-02)

Steps to reproduce
1. Run cargo new
2. Delete .git folder and .gitignore
3. Auto complete should now only suggest already typed word within the main.rs file

I spent the entirety of yesterday scrolling through page after page on google and issues to try and find either someone with the same issue or a related issue and I found many but not a single one of the solutions present helps as either the setting they say to change no longer seams to exist.

How auto complete behaves
![Screenshot 2022-11-26 162925](https://user-images.githubusercontent.com/56884994/204131625-d40359d8-1539-46f6-b1b7-54c2f41dfe02.png)

Project structure
![Screenshot 2022-11-27 115756](https://user-images.githubusercontent.com/56884994/204131679-78acbf21-0b69-4675-985e-013918222731.png)

**Comment by jonas-schievink** [comment]
rust-analyzer does not look at `.git` and `.gitignore`. Does the server output any errors to the log? Because this definitely works when the toolchain is set up correctly.

**Comment by flodiebold** [comment]
It's not clear from the screenshot whether `compiler` is directly in the folder you opened in VSCode. rust-analyzer only discovers projects at most one level deep; if it's deeper you'll need to configure `rust-analyzer.linkedProjects`.

**Comment by patfr** [comment]
Sorry for the late response didn’t get a notification for some reason but I just managed to find out what the issue is for some reason if you open the a folder as a workspace and the folder contains the project aka what is in the project structure image I showed it doesn’t do auto complete but if you don’t open it as a workspace it works fine
