### ISSUE TITLE
Ability to click through on inlay type hints

### ISSUE THREAD

**Issue by sazzer** [rust-lang/rust-analyzer#13689]
I realise this might well be impossible, but it would be fantastically useful if you could cmnd-click on the inlay type hints that are rendered in the editor as if it was an actual type that was present in the file.

By this, I mean for example:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/66072/204377845-56294e91-8d64-4641-84af-b15f5c81ec24.png">
Being able to click through on the `SdkError` or `AdminGetUserError` types here and have some useful action performed.

For reference, the actual code shown here is:
```
            .await
            .map_err(|err| {
                tracing::warn!(?username, ?err, "Failed to load user");
```

So you can see that these types are *not* present in the actual file but are being rendered by VSCode as extra information.

Cheers

**Comment by bjorn3** [comment]
If you hover over `err` it should show a popup with buttons for each relevant type.

**Comment by sazzer** [comment]
Ok - I didn't know you could do that. That's kinda cool, if a bit fiddly to get just right :)
