### ISSUE TITLE
Fill function arguments

### ISSUE THREAD

**Issue by nielsle** [rust-lang/rust-analyzer#13702]
It could be nice to have a way to fill function arguments

~~~ rust
struct A {}
struct B {}

fn foo (a: A, b: B) {}

fn main() {
    let a = A{};
    let b = B{};
    
    // Press ctrl-. here to fill arguments to get foo(a, b)
    foo();
}
~~~

Perhaps the feature could aim at the simplest case where the function arguments have the same name as local variables. 

PS: My main problem is that I tend to forget the order of my function arguments, so I am mostly interested in adding enough information to make the tool-tip appear in vscode.

**Comment by jonas-schievink** [comment]
You can manually trigger the signature help popup by pressing Ctrl+Shift+Space. You could also remove the parentheses and trigger completion, which fills the arguments with placeholders. I don't think we need another mechanism for this.
