### ISSUE TITLE
Typing `let c = '🐰` causes immediate rust-analyzer crash (before I can type the close quote)

### ISSUE THREAD

**Issue by zackw** [rust-lang/rust-analyzer#13709]
Using rust-analyzer 1.65.0 (897e375 2022-11-02) with emacs lsp-mode and rustic.

Open a brand new .rs file and type

```
pub fn test () {
  let c = '🐰
```

rust-analyzer crashes immediately upon being notified of insertion of the rabbit emoji.  If I add the missing close quote and then restart rust-analyzer, it continues running fine.  If I type first

```
pub fn test () {
   let c = '';
}
```

and then go back and insert the rabbit emoji between the quotes, it doesn't crash.

I have this backtrace in the `*rust-analyzer::stderr*` buffer:

```
Panic context:
> 
version: 1.65.0 (897e375 2022-11-02)
notification: textDocument/didChange

thread 'LspServer' panicked at 'assertion failed: self.is_char_boundary(n)', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/string.rs:1820:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: <alloc::string::String>::replace_range::<core::ops::range::Range<usize>>
   4: rust_analyzer::lsp_utils::apply_document_changes
   5: <<rust_analyzer::global_state::GlobalState>::on_notification::{closure#3} as core::ops::function::FnOnce<(&mut rust_analyzer::global_state::GlobalState, lsp_types::DidChangeTextDocumentParams)>>::call_once
   6: <rust_analyzer::dispatch::NotificationDispatcher>::on::<lsp_types::notification::DidChangeTextDocument>
   7: <rust_analyzer::global_state::GlobalState>::handle_event
   8: <rust_analyzer::global_state::GlobalState>::run
   9: rust_analyzer::main_loop::main_loop
  10: rust_analyzer::run_server
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', lib/lsp-server/src/stdio.rs:29:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**rustc version**: rustc 1.65.0 (897e37553 2022-11-02)

**Comment by lnicola** [comment]
https://github.com/emacs-lsp/lsp-mode/issues/2080

**Comment by zackw** [comment]
Thanks for the pointer to the lsp-mode bug. However, shouldn't rust-analyzer be robust enough that, no matter what kind of nonsense the editor sends it, it won't _crash_?

**Comment by lnicola** [comment]
No, I don't think so. At least it's better to crash earlier than to go on while corrupting the internal state. Think of how many hundreds of impossible to reproduce issues that would cause.

**Comment by zackw** [comment]
I tend to take the position that, whenever program A is talking to program B over a communication channel, program A should _go out of its way_ to ensure that _nothing_ B sends to it can cause it to crash.

I don't know how the LSP server protocol works, but my expectation would be that you could discard the offending message and go on.

**Comment by bjorn3** [comment]
> (Note that this means it shouldn't allow its internal state to be corrupted, either.)

Ignoring this message will cause the internal state to be corrupted as it means that the VFS of the editor and rust-analyzer are now out of sync.

**Comment by lnicola** [comment]
I believe Postel's law has proven to be one of the most damaging things in computing.

> I don't know how the LSP server protocol works, but my expectation would be that you could discard the offending message and go on.

If we discard the edit, our view of the file becomes different from what your see in the editor. Noting will work anymore after that. Completion stops working, hover might only work from time to time, and so on.  How would you expect us to debug every issue filed because of this?

**Comment by zackw** [comment]
There's a difference between "be generous in what you accept" and "no matter how broken your input is, you should not crash."

This particular crash causes the editor to yank input focus away from my file as I'm attempting to type the close quotation mark, demanding that I take notice of the crash and decide whether or not to restart the server.  If I restart the server without typing the close quote first, it will immediately crash again.  This is not a fun user experience.

> If we discard the edit, our view of the file becomes different from what your see in the editor. Nothing will work anymore after that.

Is there _really_ no way to recover? That would strike me as a bug _in the protocol itself_.  Protocols should be designed so that it's possible to resynchronize after one peer sends an incorrect message.

For instance, couldn't you ask the editor to send you the complete file and then count characters yourself? Or something like that?

**Comment by lnicola** [comment]
No, we can't ask for the file contents. We had an undocumented environment variable to disable incremental sync, but I don't know whether it's still available. And even if our state was correct, features would probably not work correctly between a non-BMP character and the end of a line. Again, people will file issues for that.

And generally, no protocol will allow you to drop some bytes of data or change an offset and still work. Why should LSP require everyone to support implement workarounds for buggy clients? And how many different bugs should the designers have anticipated?

I suggest trying eglot or another editor if lsp-mode isn't working well. We shouldn't work around client bugs, as the workaround will end up having their own bugs.

**Comment by zackw** [comment]
It's really bizarre to me that this protocol is so sensitive to number-of-characters counts, but fine, I'll take your word for it that this is unrecoverable.  _It is still wrong to crash._  I claim that under _no circumstances whatsoever_ should it be possible for data coming from outside the program to trigger a panic or equivalent.

Instead, an unrecoverable error should cause the server to generate an error notification _inside the protocol_ -- looking at https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/ , an "InvalidParams" error seems appropriate for this scenario -- and then refuse service for all subsequent requests, without crashing.  That would clearly indicate to users that the problem is on the editor's side.

It's the same sort of thing as if you're writing a web service and the client sends you nonsense.  You don't crash, you send back a 400 Bad Request message and remain up for subsequent requests.  HTTP is stateless, so the analogy isn't perfect, but I hope that it makes my position make more sense to you, at least.

**Comment by bjorn3** [comment]
I believe vscode shows InvalidParams using an error popup. While for crashes it will attempt to restart it and I believe it doesn't show any popup in that case. It does give an error popup if it crashed 5 times in the last 3 minutes though. Restarting can recover from the error in some cases. Rust-analyzer can't distinguish between cases where restarting would fix the issue and cases where it doesn't so choosing the option of crashing unconditionally has the best UX as you don't have to manually restart rust-analyzer (at least in vscode).

**Comment by zackw** [comment]
I cannot even. No. Crashing is never the right UX.

**Comment by bjorn3** [comment]
The only other option that doesn't result in extremely buggy behavior is to stop responding entirely, which is equivalent to a crash from a UX perspective except that a client can't recover from it as it doesn't know that it should attempt to recover from it. According to the LSP spec a client should recover from language server crashes:

> if a client notices that a server exits unexpectedly, it should try to restart the server. However clients should be careful not to restart a crashing server endlessly. VS Code, for example, doesn’t restart a server which has crashed 5 times in the last 180 seconds.

**Comment by zackw** [comment]
I'm baffled that you are willing to work around what's clearly a VSCode bug -- it should have sensible recovery behavior when a LS starts refusing all its requests, and clearly it doesn't -- by making the UX worse for the users of other editors.

**Comment by Veykril** [comment]
How should the client realize that a server is in an inconsistent state, that is at what point should a client think the server is done for, after refusing 5 requests, 10, 15, ...? And I'm curious why do you think that lsp-mode handles this correctly opposed to other clients? Also VSCode is not buggy in this regard, restarting a server when it crashes is, as bjorn3 said, even recommended by the spec.

**Comment by flodiebold** [comment]
An LSP server is not a web service, it does not need to be concerned about requests from untrusted clients. Also, the UX when the server crashes with lsp-mode is fine, the problem is that lsp-mode is being buggy. rust-analyzer already implemented its side of a workaround for this problem by adding UTF8 support in the protocol; the fix here is for lsp-mode to implement UTF8 encoding, or fix its UTF16 support.

> what's clearly a VSCode bug -- it should have sensible recovery behavior when a LS starts refusing all its requests, and clearly it doesn't

No client has such a recovery behavior, because that's not a thing that servers do.

**Comment by matklad** [comment]
FWIW, I think fixing this in the lsp mode should be a couple of lines: 

https://github.com/emacs-lsp/lsp-mode/issues/3344#issuecomment-1320677622

we support utf8 offsets, lsp-mode uses utf8 offsets, the only thing missing is lsp-mode actually telling us to use utf8. I personally wouldn't be against even hard-coding lsp-mode on our side to use utf8, if that's easier to land (I think there's some sort of UA string in the protocol).

**Comment by teor2345** [comment]
> FWIW, I think fixing this in the lsp mode should be a couple of lines:
> 
> [emacs-lsp/lsp-mode#3344 (comment)](https://github.com/emacs-lsp/lsp-mode/issues/3344#issuecomment-1320677622)
> 
> we support utf8 offsets, lsp-mode uses utf8 offsets, the only thing missing is lsp-mode actually telling us to use utf8. I personally wouldn't be against even hard-coding lsp-mode on our side to use utf8, if that's easier to land (I think there's some sort of UA string in the protocol).

I just got a rust-analyzer crash today editing a file with a single multi-byte character in emacs.

If we could hard-code the emacs user-agent in rust-analyzer, that would make it possible for me to edit Rust with multi-byte characters. I know it's not the ideal solution, but the fixes on the emacs-lsp side seem to have stalled:
- https://github.com/emacs-lsp/lsp-mode/issues/2080
- https://github.com/emacs-lsp/lsp-mode/issues/3344

**Comment by lnicola** [comment]
I don't think we want to do that. Have you tried eglot?

**Comment by lnicola** [comment]
For anyone still thinking this is something we should be able to ignore or recover from, there's a great illustrated explanation by @fasterthanlime at https://fasterthanli.me/articles/the-bottom-emoji-breaks-rust-analyzer.

**Comment by zackw** [comment]
I still think it is incorrect for rust-analyzer to panic in this case.  Panic is _exclusively_ for when your program detects a bug in _itself_.  It should never be used to report anything else.  In this case, everyone agrees that emacs lsp-mode sent a bogus protocol message, so the error should be reported in a way that makes it clear that emacs lsp-mode is the program with the bug.

Granted that the lsp protocol is badly designed on multiple levels such that (a) we have this problem in the first place, and (b) there's no good way to report the error _besides_ terminating the server, that still leaves the possibility of, say,

```
use std::process::exit;
eprintln!("Unrecoverable LS protocol error: editor mishandles file offsets for Unicode astral characters");
eprintln!("Please report this as a bug in your editor.  [further helpful suggestions for bug reporting?]");
exit(1);
```

If you made this change people would at least stop reporting this as a bug in rust-analyzer.  (Ideally it would be made _everywhere_ there is currently a panic whose root cause is a protocol error.)

**Comment by zackw** [comment]
No, sorry, I can't agree with that. This is a change you should make _even if_ the lsp-mode bug were to be fixed half an hour from now and magically propagated to every user by tomorrow. "Panic means you have found a bug in the program itself" is a basic user expectation that you should consider on the level of correctness, i.e. _more important than_ performance.

**Comment by fasterthanlime** [comment]
@zackw I understand your point of view. Note that I do not represent the rust-analyzer project and these are just my personal views!

**Comment by zackw** [comment]
... huh, I'm surprised there isn't a `try_replace_range`.  brb filing a feature request on the stdlib.

**Comment by lnicola** [comment]
When this happens, we have no way to tell if it's a buggy client or a real bug in rust-analyzer. My stance is (still) that panicking is the correct thing to do, since there's no way to recover from this.

**Comment by zackw** [comment]
> When this happens, we have no way to tell if it's a buggy client or a real bug in rust-analyzer

Why do you say that?  This case, at least, seems completely cut and dried to me.

**Comment by matklad** [comment]
Crashing in the most obnoxious way here is a deliberate, explicit design decision.

I can see how the people can object to this “misuse” of panics (similarly to how people can object to our use of panicking machinery to implement cancellation). I still believe that panicking is the best practical strategy here to surface the serious issue between client/server communication and apply appropriate social pressure to fix it. Note that rust-analyzer is MIT licensed and easy to build, so maintaining personal patches or fork to fix issues the team disagrees with is explicitly encouraged.

**Comment by lnicola** [comment]
We do incremental sync, as mentioned above. We've had our own share of bugs related to that. Because if this, when we get a position that's in the middle of a character, there's no way to tell if the client is buggy and sent the wrong position, or if it's a bug on our side that caused our view of the file to become desynchronized with that of the client.

And yes, if we ignore the notification (whatever that means), the errors will keep accumulating.

**Comment by matklad** [comment]
Particular issue at hand should be fixed by this pair of PRs

* https://github.com/emacs-lsp/lsp-mode/pull/3958
* https://github.com/rust-lang/rust-analyzer/pull/14141 

My earlier comment 

> FWIW, I think fixing this in the lsp mode should be a couple of lines:

was inaccurate. While the fix on the lsp-mode side is indeed a couple of lines, turns out I was wrong that utf8 is native position encoding for Emacs. It seems like it uses utf32 in the end (would appreciate double-checking from anyone more knowlegable in Emacs ways). So, this also required support for utf32 on rust-analyzer side, which the second PR implements.
