### ISSUE TITLE
What are needed for a client to do to enable autoimport? 

### ISSUE THREAD

**Issue by zbelial** [rust-lang/rust-analyzer#13708]
I use a LSP client I wrote with Emacs, but I found autoimport does not work.  Rust-analyser's document  says autoimport is enabled by default, so it's really wired  and I don't know what to do to make it work.

Any hint?  Thanks. 

My client initilizes rust-analyzer with the following data:

<details>
  <summary>initialize request data</summary>
<pre>
{
  "id": 1,
  "method": "initialize",
  "params": {
    "capabilities": {
      "experimental": {},
      "textDocument": {
        "callHierarchy": {
          "dynamicRegistration": false
        },
        "codeAction": {
          "codeActionLiteralSupport": {
            "codeActionKind": {
              "valueSet": [
                "quickfix",
                "refactor",
                "refactor.extract",
                "refactor.inline",
                "refactor.rewrite",
                "source",
                "source.organizeImports"
              ]
            }
          },
          "dataSupport": false,
          "disabledSupport": false,
          "dynamicRegistration": false,
          "isPreferredSupport": true
        },
        "completion": {
          "completionItem": {
            "commitCharactersSupport": false,
            "deprecatedSupport": false,
            "documentationFormat": [
              "markdown",
              "plaintext"
            ],
            "insertReplaceSupport": false,
            "preselectSupoort": false,
            "resolveSupport": {
              "properties": [
                "documentation",
                "detail"
              ]
            },
            "snippetSupport": true
          },
          "contextSupport": true,
          "dynamicRegistration": false
        },
        "declaration": {
          "dynamicRegistration": false,
          "linkSupport": false
        },
        "definition": {
          "dynamicRegistration": false,
          "linkSupport": false
        },
        "documentHighlight": {
          "dynamicRegistration": false
        },
        "formatting": {
          "dynamicRegistration": false
        },
        "hover": {
          "contentFormat": [
            "markdown",
            "plaintext"
          ],
          "dynamicRegistration": false
        },
        "implementation": {
          "dynamicRegistration": false,
          "linkSupport": false
        },
        "publishDiagnostics": {
          "codeDescriptionSupport": false,
          "dataSupport": false,
          "relatedInformation": false,
          "tagSupport": {
            "valueSet": [
              1,
              2
            ]
          },
          "versionSupport": false
        },
        "rangeFormatting": {
          "dynamicRegistration": false
        },
        "references": {
          "dynamicRegistration": false
        },
        "rename": {
          "dynamicRegistration": false,
          "honorsChangeAnnotations": false,
          "prepareSupport": false
        },
        "signatureHelp": {
          "contextSupport": false,
          "dynamicRegistration": false,
          "signatureInformation": {
            "activeParameterSupport": false,
            "documentationFormat": [
              "markdown",
              "plaintext"
            ],
            "parameterInformation": {
              "labelOffsetSupport": false
            }
          }
        },
        "synchronization": {
          "didSave": true,
          "dynamicRegistration": false,
          "willSave": true
        },
        "typeDefinition": {
          "dynamicRegistration": false,
          "linkSupport": false
        }
      },
      "workspace": {
        "applyEdit": false,
        "configuration": false,
        "executeCommand": {
          "dynamicRegistration": false
        },
        "symbol": {
          "dynamicRegistration": false
        },
        "workspaceEdit": {
          "documentChanges": true,
          "resourceOperations": [
            "create",
            "rename",
            "delete"
          ]
        },
        "workspaceFolders": false
      }
    },
    "clientInfo": {
      "name": "lspce",
      "version": "0.3"
    },
    "initializationOptions": {
      "cargo": {
        "allFeatures": false,
        "autoreload": true,
        "features": "all",
        "loadOutDirsFromCheck": true,
        "noDefaultFeatures": false,
        "runBuildScripts": true,
        "useRustcWrapperForBuildScripts": true
      },
      "completion": {
        "addCallArgumentSnippets": false,
        "addCallParenthesis": true,
        "autoimport": {
          "enable": true
        },
        "postfix": {
          "enable": false
        }
      },
      "diagnostics": {
        "enable": true
      },
      "enableExperimental": false,
      "lens": {
        "enable": false
      },
      "procMacro": {
        "enable": true
      }
    },
    "processId": 313016,
    "rootUri": "file:///tmp/complete"
  }
}
</pre>
</details>

**Comment by lnicola** [comment]
Do the other features work? Can you run it side-by-side with eglot, lsp-mode or Code and compare the traces?

**Comment by flodiebold** [comment]
Autoimport completions require `resolveSupport` for `additionalTextEdits`, which it doesn't look like you're supporting.

**Comment by zbelial** [comment]
Thank you very much @flodiebold . My LSP client works now. I'll close this issue.
