### ISSUE TITLE
Incorrect PartialEq code assist

### ISSUE THREAD

**Issue by digama0** [rust-lang/rust-analyzer#13727]
Given:
```rust
#[derive(PartialEq)]
enum Either<T, U> {
    Left(T),
    Right(U),
}
```

the code assist on `PartialEq` produces the following impl:
```rust
impl<T, U> PartialEq for Either<T, U> {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Left(l0), Self::Left(r0)) => l0 == r0,
            (Self::Right(l0), Self::Right(r0)) => l0 == r0,
        }
    }
}
```
which is wrong in two ways:
1. There are no `PartialEq` bounds on the type arguments
2. There is no `_ => false` fallback case

The first one seems like it might be omitting the bounds either because it is easier to add custom bounds that way or because it's easier to implement, but the second issue seems like it would unequivocally be a bug and I'm surprised it would ever work like this.

**rust-analyzer version**: 0.4.1307-standalone

**rustc version**: rustc 1.66.0-nightly (a6b7274a4 2022-10-10)

**Comment by lowr** [comment]
I think we want to fix the first point too, reopening.
