### ISSUE TITLE
rust analyzer giving bootstrap error on install in vscode

### ISSUE THREAD

**Issue by istupidgirl** [rust-lang/rust-analyzer#13741]
https://stackoverflow.com/questions/74721982/problems-with-rust-analyzer-extension-on-vscode

**Comment by bjorn3** [comment]
What does `~/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1309/server/rust-analyzer --version` show? And does this executable exist?

**Comment by kianfakheriaghdam** [comment]
I did replace my user name with `{user}` and the executable does exist and is strangely outputs `-bash: ./rust-analyzer: No such file or directory` even though it does exist

**Comment by lnicola** [comment]
That's strange, can you try `ldd rust-analyzer`?

**Comment by bjorn3** [comment]
What does `ldd ~/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1309/server/rust-analyzer` show? And `readelf -l ~/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1309/server/rust-analyzer`? Does the file listed after "Requesting program interpreter" in the `readelf` output exist on your system.

**Comment by kianfakheriaghdam** [comment]
`ldd`
```
        linux-vdso.so.1 (0x00007ffc8d37a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9a74bcc000)
        libc.musl-x86_64.so.1 => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9a749a4000)
        /lib/ld-musl-x86_64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007f9a765c1000)
```
`readelf`
```
   00     
   01     .interp 
   02     .interp .dynsym .gnu.version .gnu.version_r .gnu.hash .dynstr .rela.dyn .rela.plt .rodata .gcc_except_table .eh_frame_hdr .eh_frame 
   03     .text .init .fini .plt 
   04     .tdata .ctors .dtors .data.rel.ro .dynamic .got .got.plt 
   05     .tm_clone_table .data .bss 
   06     .tdata .tbss 
   07     .dynamic 
   08     .tdata .ctors .dtors .data.rel.ro .dynamic .got .got.plt 
   09     .eh_frame_hdr 
   10
```

**Comment by bjorn3** [comment]
Looks like you somehow got a rust-analyzer compiled for musl libc on a system running glibc. Did you install it from the vscode marketplace or from a github release?

**Comment by kianfakheriaghdam** [comment]
I installed it from a vsix file

**Comment by lnicola** [comment]
Try `rustup component add rust-src`.

**Comment by kianfakheriaghdam** [comment]
`info: component 'rust-src' is up to date`

**Comment by kianfakheriaghdam** [comment]
Well, it now works.
