### ISSUE TITLE
Documentation weirdness about the `cargo.allFeatures` vs `cargo.features`

### ISSUE THREAD

**Issue by woshilapin** [rust-lang/rust-analyzer#13740]
On a project of mine, I wanted to activate all the features for `rust-analyzer`. I found out this documentation

> rust-analyzer.checkOnSave.features (default: null)
>    List of features to activate. Defaults to rust-analyzer.cargo.features.
>    Set to "all" to pass --all-features to Cargo.

Therefore, I tried doing this

```toml
cargo.features = "all"
```

But it failed with

```
rust-analyzer found 1 invalid config value:
/cargo/features: invalid type: string "all", expected a sequence
```

So I tried

```toml
cargo.features = ["all"]
```

but got this error message

```
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/me/project/Cargo.toml, cargo 1.65.0 (4bc8f24d3 2022-10-20): Failed to run `"cargo" "metadata" "--format-version" "1" "--features" "all" "--manifest-path" "/home/me/project/Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error: error: none of the selected packages contains these features: all
```

(Note: I also tried `cargo.features = "[all]"` for the sake of testing but of course, it doesn't work)

In the end, I found out that the following works

```toml
cargo.allFeatures = true
```

But this property is not documented in the [User Manual](https://rust-analyzer.github.io/manual.html).

Did I miss something, or is the User Manual a bit misleading?

I can try to fix it.

I was under the impression that [these lines](https://github.com/rust-lang/rust-analyzer/blob/e9f60879654307d808d69450a7a731209e8a4131/crates/rust-analyzer/src/config.rs#L107-L109) would need to change, but then, I probably need some kind of build to automatically update [`/docs/user/generated_config.adoc`](https://github.com/rust-lang/rust-analyzer/blob/e9f60879654307d808d69450a7a731209e8a4131/docs/user/generated_config.adoc) and [`/editors/code/package.json`](https://github.com/rust-lang/rust-analyzer/blob/1e6a49a801708a8bcbe429ce03f614a7951bdb11/editors/code/package.json), am I right?

**Comment by flodiebold** [comment]
`allFeatures` is the old way of configuring this, so you probably have an outdated version of rust-analyzer installed.

**Comment by woshilapin** [comment]
I installed `rust-analyzer` via `rustup` but for some reason, it never worked and indeedn, I was using an old version of `rust-analyzer`. Thank you for the quick response. I'm closing the issue.
