### ISSUE TITLE
Rust analyzer stuck at cargo-metadata

### ISSUE THREAD

**Issue by Eason0729** [rust-lang/rust-analyzer#13752]
**rust-analyzer version**: rust-lang.rust-analyzer-0.4.1313

**rustc version**: rustc 1.65.0 (897e37553 2022-11-02)

**relevant settings**: default

after updating, I found rust analyzer(0.4.1313) stuck at cargo-metadata(on htop), and don't show inlay hint, but Rust analyzer(0.4.1310) work.

**Comment by jonas-schievink** [comment]
Could it be that it was just updating the crates.io index? Because that's a git repo with a huge number of commits, that step can take a few minutes. `cargo metadata` is the first Cargo command r-a runs when started, so that's when the index gets updated (if it does get updated at all).

**Comment by Eason0729** [comment]
It could be. Since had only waited for a few minutes then, I would tried that later to see if it solve my problem.

**Comment by lnicola** [comment]
To see how that looks, you can delete `~/.cargo/registry`, then either load the project or run `cargo metadata` in a terminal.

**Comment by Eason0729** [comment]
It was exactly what @jonas-schievink said, It work after a few minutes when index gets updated.
Thank for your help.

**Comment by Veykril** [comment]
It would be nice if we could somehow report progress on that, but I believe `cargo metadata` doesn't hand us any of that information, https://github.com/rust-lang/rust-analyzer/blob/9ed1829f1fb61695c21474361ec23b9976793b73/crates/project-model/src/cargo_workspace.rs#L301-L304
