### ISSUE TITLE
Feature Request: Preview Macro Expansion

### ISSUE THREAD

**Issue by AadamZ5** [rust-lang/rust-analyzer#13760]
I know there are some open issues  about expanding macros in place (#13598, [#5949 (comment)](https://github.com/rust-lang/rust-analyzer/issues/5949#issuecomment-810128667)), but I'm not sure if those are exactly what I'm trying to describe here. I recently was fantasizing about a "preview macro expansion" in IDE that would open the preview pane. I sometimes want to see how the macro is expanded, but I don't want to actually write the expanded macro into my file. I just want to see it for reference. I use VS Code, not sure how other editors would/could implement. 

The preview pane is what you get when you use an action like "Go To References" from the context menu. I think this is also the same functionality as the "Peek" options in VS Code context menu.

Example of the preview pane I'm talking about:
![image](https://user-images.githubusercontent.com/15809427/206920817-4601b9a1-d48e-4eab-81cc-5f887131d800.png)

I think it would be neat to quickly preview the expanded macro in this manner. This could be accessed by a context menu option when right-clicking on a macro. 

Any pointers/tips to investigate how something like this could be implemented? Any current blockers? Thanks!

**Comment by bjorn3** [comment]
The "Rust Analyzer: Expand macro recursively" command shows the macro expansion in a separate editor pane.

**Comment by AadamZ5** [comment]
Just did my due diligence after I posted this and checked out the functionality. I still would enjoy the preview pane, but this is great :)

Closing
