### ISSUE TITLE
Closing brace hint moves cursor to itself, instead of the item's name in vscode

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust-analyzer#13768]
**rust-analyzer version**: 0.4.1318-standalone

Reading the code the `fn name` hint on the `}` should ctrl+click to the function's name, but instead ctrl+click sends me to the closing brace itself...

Not sure if it's a vscode thing or r-a, but still:
![Peek 2022-12-13 19-27](https://user-images.githubusercontent.com/38225716/207382896-eaf5d7a4-663b-4d2e-9980-82355a63c4a2.gif)

**Comment by Veykril** [comment]
This works now
