### ISSUE TITLE
Check-on-save only starts with huge delay when cache priming is disabled

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#13770]
Since some time recently, there is a huge delay of 10-60s between hitting Ctrl-S and RA starting to do the next check-build. Needless to say that slows down the usual development process quite a bit.

This seems to happen in Miri, but not in smaller repos, and not when I disable proc macro support. It also only happens when cache priming is disabled.

**rust-analyzer version**: rust-analyzer version: 0.3.1317-standalone

**rustc version**: rustc 1.68.0-nightly (e1c91213f 2022-12-11)

**relevant settings**:
```
    "rust-analyzer.cachePriming.enable": false,
    "rust-analyzer.cargo.buildScripts.useRustcWrapper": false,

    "rust-analyzer.rustc.source": "discover",
    "rust-analyzer.linkedProjects": [
        "./Cargo.toml",
        "./cargo-miri/Cargo.toml"
    ],
    "rust-analyzer.checkOnSave.overrideCommand": [
        "./miri",
        "cargo",
        "clippy",
        "--all-targets",
        "--message-format=json"
    ],
    // Contrary to what the name suggests, this also affects proc macros.
    "rust-analyzer.cargo.buildScripts.overrideCommand": [
        "./miri",
        "cargo",
        "check",
        "--message-format=json",
    ],
```

**Comment by Veykril** [comment]
Most likely caused by https://github.com/rust-lang/rust-analyzer/pull/13447

**Comment by the-a-man-006** [comment]
Any workaround? The minutes-long-delay completely kills all productivity and I can't tolerate it anymore... Any hope?

**Comment by the-a-man-006** [comment]
```
"rust-analyzer.check.overrideCommand": [
	"cargo",
	"clippy",
	"--workspace",
	"--message-format=json",
	"--all-targets
],
"rust-analyzer.procMacro.enable": false,
"rust-analyzer.diagnostics.enable": false,
"rust-analyzer.checkOnSave.enable": true
```

I do need proc-macro support and build-scripts, but guess would just have to resort to rebuild-proc-macros and build scripts manually or reenable when I frequently need those.
Cargo check seems to be slow for me and hangs for a minute halfway through (on my Windows machine), so resorting to Clippy.

**Comment by RalfJung** [comment]
I haven't seen this issue in a long while, even though cache priming is disabled.

**Comment by Veykril** [comment]
I don't think this should be an issue anymore, we've moved blocking behavior from the handler away
