### ISSUE TITLE
Can't analysis code correctly when using match Ranges of values and @ Bindings at the same time in match arm

### ISSUE THREAD

**Issue by gfgafn** [rust-lang/rust-analyzer#13776]
It can be compile and run correctly, but the extension report an errror.

**rust-analyzer version**: rust-analyzer version:0.3.1317-standalone (21e61bee8 2022-12-10)

**rustc version**: rustc 1.65.0 (897e37553 2022-11-02)

<img width="571" alt="Can't analy code correctly when using match Ranges of values and @ Bindings at the same time" src="https://user-images.githubusercontent.com/87858323/207702298-041cf29b-f97d-438e-a433-0b98a60ff159.png">

**Comment by jonas-schievink** [comment]
Looks like this check is missing the `T![if]` token:

https://github.com/rust-lang/rust-analyzer/blob/95671d53ea3063da5316784af9ef69c71219f320/crates/parser/src/grammar/patterns.rs#L129
