### ISSUE TITLE
"rust-analyzer.linkedProjects" can support "*" to match all folder?

### ISSUE THREAD

**Issue by DLillard0** [rust-lang/rust-analyzer#13778]
I'm using [exercism](https://exercism.org/) to learn Rust. It create many rust project in one folder, I want to use "*" to match all, like this:
```json
{
  "rust-analyzer.linkedProjects": [
    "./rust/*/Cargo.toml"
  ]
}
```
but it don't work now.

**Comment by Veykril** [comment]
Closing in favor for https://github.com/rust-lang/rust-analyzer/issues/8622
