### ISSUE TITLE
Disabling custom syntax highlighting done by rust-analyzer

### ISSUE THREAD

**Issue by crippa1337** [rust-lang/rust-analyzer#13775]
I am wondering if/how it is possible to disable the custom syntax highlighting that the rust-analyzer does in VSCode? It is overwriting my theme which I would like to disable.

For example, using Gruvbox Material, my "let" statements are highlighted with an orange color.
Upon starting rust-analyzer, all "let"'s are turned red.

![image](https://user-images.githubusercontent.com/111508533/207692770-53d3d027-4fdd-4940-9e2d-ccf01a312191.png)

Turns into

![image](https://user-images.githubusercontent.com/111508533/207692874-19514b63-fdc0-441f-ae87-c1d2966831ff.png)

**Comment by bjorn3** [comment]
This is semantic syntax highlighting. It doesn't override your theme, but gives your theme more info to improve syntax highlighting based on semantic analysis. For example it could an identifier specifying a struct different from one specifying an enum. Or underline mutable variables. It seems that your theme doesn't handle it all that well. You can disable it entirely using `"editor.semanticHighlighting.enabled": false`.

**Comment by crippa1337** [comment]
> This is semantic syntax highlighting. It doesn't override your theme, but gives your theme more info to improve syntax highlighting based on semantic analysis. For example it could an identifier specifying a struct different from one specifying an enum. Or underline mutable variables. It seems that your theme doesn't handle it all that well. You can disable it entirely using `"editor.semanticHighlighting.enabled": false`.

You're right. Thank you.
