### ISSUE TITLE
`unsafe` postfix completion on a block expression should not wrap the block

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#13779]
We currently have a `.unsafe` completion that wraps the receiver in an `unsafe {}` block. If this is invoked on a free `{...}` (that is not a block of a control flow structure or another block with an effect-ish label) it should just annotate the block with `unsafe`.

```
// current behavior
foo.unsafe -> unsafe { foo }
{ foo }.unsafe -> unsafe { { foo } }
if x { foo }.unsafe -> unsafe { if x { foo } }
// ideal behavior
foo.unsafe -> unsafe { foo }
{ foo }.unsafe -> unsafe { foo }
if x { foo }.unsafe -> unsafe { if x { foo } }
```

**Comment by russelltg** [comment]
I'll take a peek at this

**Comment by shogohida** [comment]
Hi @Veykril, is this issue still available? I want to work on this if so. 

Which code should I change? I looked for the correct area but there are many `unsafe`s and I don't know which one is correct

**Comment by Veykril** [comment]
As it turns out, r-a doesn't even have an `unsafe` postfix anymore (it was removed in favor of custom snippets) 😬 I think we should bring it back as a normal completion though (to support this special case). The relevant part for implementing this is here https://github.com/rust-lang/rust-analyzer/blob/1afa032f34db45a7018ced2c1a59798139e95bfc/crates/ide-completion/src/completions/postfix.rs#L141-L189
