### ISSUE TITLE
Async functions in sub-crate break formatting

### ISSUE THREAD

**Issue by fmeef** [rust-lang/rust-analyzer#13790]
**rust-analyzer version**:  21e61bee8 2022-12-10

**rustc version**: rustc 1.66.0 (69f9c33d7 2022-12-12)

**relevant settings**: helix editor with default settings

When working with a project composed of multiple local crates added via `lib = { path = "./lib" }` in cargo.toml formatting seems to fail if an async function or an async block is present in the current file. This seems to affect the entire file where async code is present. Running formatting on the topmost crate even when multiple crates are in cargo.toml causes formatting to run correctly. Running `cargo fmt` always works even when rust-analyzer fails to format

I created a minimal reproduction here https://github.com/fmeef/rust-analyzer-format-fail/, attempting to format the lib.rs file in the lib crate results in nothing actually happening.

**Comment by jonas-schievink** [comment]
```
[WARN rust_analyzer::handlers] rustfmt exited with status 1 command="rustfmt" captured_stderr=error[E0670]: `async fn` is not permitted in Rust 2015
```

Are we not passing `--edition 2021` to rustfmt in all cases? Clearly most of the time we are, or you couldn't format `async` code at all. Weird.

**Comment by jonas-schievink** [comment]
Ah, the package in question is a path dependency, but not a workspace member, so `cargo_target_for_crate_root` returns `None`, and we can't determine the edition in use.

Maybe that code should use the crate graph instead of looking at the Cargo workspace info? The crate graph also stores the edition.
