### ISSUE TITLE
"Extract module" assist panics with "assertion failed: check_disjoint_and_sort(indels)"

### ISSUE THREAD

**Issue by SludgePhD** [rust-lang/rust-analyzer#13791]
To reproduce, check out SludgePhD/Pawawwewism@df7b0773554e8f359ed59b72150172b6d97b93e1, open lib.rs and select lines 104-224. Applying the "Extract module" assist then causes a panic.

**Comment by feniljain** [comment]
A MRE should look something like this:

```rust
use std::sync::{Arc, Condvar, Mutex};

$0
struct Promise {
    inner: Arc<i32>,
    state: Mutex<i32>,
    condvar: Condvar,
}
$0
```
