### ISSUE TITLE
auto completion for 'fn' does not work when there is no curly bracket '{ }' on the 'fn' above

### ISSUE THREAD

**Issue by lenardlopez** [rust-lang/rust-analyzer#13802]
VS Code 1.74.1
Rust-analyzer v0.3.1317
Rust 1.65.0

Example below to simulate the issue.
But if I add curly bracket '{ }' on 'fn' 'struct' auto complete works.

![208226362-3b1b66b4-2d2e-421d-9511-0f2ae26fa3cd](https://user-images.githubusercontent.com/95019851/208670311-9d784565-25ab-4d49-9790-fccade6de50d.jpg)

**Comment by dqkqd** [comment]
Hi @Veykril , might I work on this?

I found that adding check for `it.semicolon_token().is_none()` could resolve the problem.
And I think the cases for `Const` and `TypeAlias` also need to be covered.

https://github.com/rust-lang/rust-analyzer/blob/eaed19c5399064393e846ad5dddd7b0b290d2582/crates/ide-completion/src/context/analysis.rs#L681

If it's ok, I could send a PR.

**Comment by Veykril** [comment]
Yes that's correct we need to either check for the body or if that's missing for the semicolon there
