### ISSUE TITLE
error[E0658]: `let...else` statements are unstable

### ISSUE THREAD

**Issue by nikola-bozin-org** [rust-lang/rust-analyzer#13801]
https://github.com/rust-lang/rust-analyzer/issues/13562

This did not work for me. I still get the same error?

Is there anything else i am missing?

Versions:
rustup 1.25.1 (bb60b1e89 2022-07-12)
rustc 1.66.0 (69f9c33d7 2022-12-12

**Comment by flodiebold** [comment]
let-else is stable in 1.66, so if you're getting that error message you can't be compiling with 1.66. Maybe you have a local override, or are running some other cargo binary. Try running `rustc --version` and `cargo --version` inside the rust-analyzer folder if you didn't before.

**Comment by nikola-bozin-org** [comment]
Here are the versions: 
rustc 1.66.0 (69f9c33d7 2022-12-12)
cargo 1.66.0 (d65d197ad 2022-11-15)

I dont override version anywhere, im just using some crate from crates.io, but im not sure if that crate can possibly override the version?

**Comment by flodiebold** [comment]
What do you mean by "I'm just using some crate from crates.io"? The issue you referenced is about compiling rust-analyzer, is that not what you're trying to do?

**Comment by nikola-bozin-org** [comment]
Ohhh, it seems i created issue in wrong section because i used some crates, and those crates contain the error that i referenced. But yes, compilation did not work. 

Do you maybe have any other solutions?

**Comment by nikola-bozin-org** [comment]
Yes, i am running `cargo check` and my `cargo--version` is `cargo 1.66.0 (d65d197ad 2022-11-15)` . Is it possible that crate is overriding version?

**Comment by flodiebold** [comment]
Your project can have a rust-toolchain file that overrides the version, but that would show up in `cargo --version`. Dependencies can't override the compiler they're compiled with, everything gets compiled by the compiler you invoked (unless they're doing some build.rs shenanigans).
