### ISSUE TITLE
Syntax highlighting for `inlined code` in rust docs

### ISSUE THREAD

**Issue by MariaSolOs** [rust-lang/rust-analyzer#13809]
There's already support for highlighting source code in rust docs. It would be great if this could also include the code inside backticks! :)
<img width="450" alt="image" src="https://user-images.githubusercontent.com/62502207/208809970-21df2675-240a-41f6-81d4-e9b4462ed111.png">

**Comment by Veykril** [comment]
The problem with that is that those inline code snippets don't necessarily need to be rust, for code blocks we can assume it as that is what rustdoc defaults to as well, and otherwise people can annotate what language it actually is. Inline code snippets cannot be annotated with a language otoh.

**Comment by MariaSolOs** [comment]
That's fair. Thanks for explaining!
