### ISSUE TITLE
Feature request: "remove `dbg!`" code action

### ISSUE THREAD

**Issue by digama0** [rust-lang/rust-analyzer#13839]
When I am debugging rust code, I often sprinkle `dbg!` liberally, but once the bug has been caught it would be nice to be able to quickly remove all those `dbg!` lines. `println!()` can usually be removed more easily because you can just delete the containing line, but `dbg!` wraps an expression so that involves some syntactic transformation. Suggested behavior:

* The code action is available if the cursor is within the span of `dbg!` (either just those letters or the entire spanned block), by the name "remove this `dbg!`", or if the active selection contains one or more `dbg!` calls in it ("remove `dbg!` in selection").
* For specified `dbg!` calls:
  * `dbg!(a)` is replaced by `a`, and `dbg!(a, b, ...)` is replaced by `(a, b, ...)`
  * (Optional) If this results in a useless statement like `&foo.bar;` then the statement is removed
  * (Optional) If this results in unnecessary references like `(&a).foo()` then these are replaced by `a.foo()`

**Comment by flodiebold** [comment]
This already exists, with pretty much the behavior you're describing.

**Comment by digama0** [comment]
🤦
