### ISSUE TITLE
1.68.0-nightly crashes with unexpected error

### ISSUE THREAD

**Issue by segeljakt** [rust-lang/rust-analyzer#13846]
When creating a blank project, I get the following error which seems to crash RA.
```
[ERROR][2022-12-25 16:19:50] .../vim/lsp/rpc.lua:732    "rpc"    "rust-analyzer"    "stderr"    '[ERROR rust_analyzer] Unexpected error: expected Message::Notification, got: Notification(Notification { method: "workspace/didChangeWorkspaceFolders", params: Object {"event": Object {"removed": Array [Array []], "added": Array [Object {"uri": String("file:///Users/klasseg/Workspace/ra-test"), "name": String("/Users/klasseg/Workspace/ra-test")}]}} })\nexpected Message::Notification, got: Notification(Notification { method: "workspace/didChangeWorkspaceFolders", params: Object {"event": Object {"removed": Array [Array []], "added": Array [Object {"uri": String("file:///Users/klasseg/Workspace/ra-test"), "name": String("/Users/klasseg/Workspace/ra-test")}]}} })\n'
```
Versions:
```
ra-test ❯ rust-analyzer --version
rust-analyzer 1.68.0-nightly (46160e6f 2022-12-24)
```

```
ra-test ❯ nvim --version
NVIM v0.9.0-dev-213+gcc5b7368d-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by klasseg@klasseg-mbp

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-cc5b736/share/nvim"

Run :checkhealth for more info
```

**Comment by segeljakt** [comment]
Hmm, for some reason it sometimes starts working. I don't know what the problem is.

**Comment by MullerLucas** [comment]
I got the same error after using 'PackerSync' (I think, not sure).

I am using nvim + mason + mason-lspconfig to manage my lsp-servers and the problem only occurs when using mason-lspconfig to automatically install rust-analyzer.

If I manually call 'MasonInstall rust-analyzer' or use the rust-analyzer package provided in the Arch-Repos everything works fine.

**Comment by Napuu** [comment]
Getting same error. However, when I start it manually with `:LspStart` after crashing, everything seems to be fine.

**Comment by AlvaroParker** [comment]
Same error. `rust-analyzer 2022-12-26` installed with Mason

**Comment by Veykril** [comment]
These errors are thrown by r-a because it expects the client to send an `initialized` notification but the client is instead sending a `workspace/didChangeWorkspaceFolders`. So the client here seems to be violating the LSP. The LSP defines that the client may not sent any request or notification before sending the `initialized` notification after receiving the response to the `initialize` request https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialized

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/14098 should implement this notification
