### ISSUE TITLE
handle the workspace/didChangeWorkspaceFolders request for other editor

### ISSUE THREAD

**Issue by glepnir** [rust-lang/rust-analyzer#13852]
**rust-analyzer version**:  2022-12-26

**rustc version**:   rustc 1.65.0 (897e37553 2022-11-02)

**relevant settings**:  neovim with nvim-lspconfig

## Problem

open a file in Project A and open open b file in Project B . the `nvim-lspconfig` will send the `rpc.notify('workspace/didChangeWorkspaceFolders', params)` . server should send the `workspace/diagnostic/refresh`.
currently I only found the rust-analyzer handle it in vscode .

## Log

```
[ERROR][2022-12-27 11:40:45] .../vim/lsp/rpc.lua:734	"rpc"	"rust-analyzer"	"stderr"	'[ERROR rust_analyzer::dispatch] unhandled notification: Notification { method: "workspace/didChangeWorkspaceFolders", params: Object {"event": Object {"added": Array [Object {"uri": String("file:///Users/joyce/Workspace/rust-test/consumer-of-needs-nightly"), "name": String("/Users/joyce/Workspace/rust-test/consumer-of-needs-nightly")}], "removed": Array []}} }\n'
```

**Comment by tangiang0812** [comment]
I'm experiencing the same problem. Here is my log:
```
[ERROR][2023-01-03 21:17:59] .../vim/lsp/rpc.lua:733	"rpc"	"rust-analyzer"	"stderr"	'[ERROR rust_analyzer::dispatch] unhandled notification: Notification { method: "workspace/didChangeWorkspaceFolders", params: Object {"event": Object {"added": Array [Object {"name": String("/home/gnaig/Documents/src/rust_book/chapter13"), "uri": String("file:///home/gnaig/Documents/src/rust_book/chapter13")}], "removed": Array []}} }\n'
```

**Comment by Veykril** [comment]
This is an implementation error on the client side, rust-analyzer does not set the https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWorkspaceFolders `workspace.workspaceFolders.supported` server capability nor does it register it dynamically.

**Comment by glepnir** [comment]
@Veykril  thanks so that mean rust-analyzer doesn't support worskpaceFolders?

**Comment by Veykril** [comment]
It currently does not.

**Comment by glepnir** [comment]
thanks for your reply and no problem then close.

**Comment by glepnir** [comment]
another question . does the team want support workspacefolders in future? should i create a feature request for this?
