### ISSUE TITLE
Any way to automatically add .toml files to `rust-analyzer.linkedProjects`?

### ISSUE THREAD

**Issue by NuclearDisco** [rust-lang/rust-analyzer#13855]
For some odd reason, .toml files can only be read by root of the workspace from my understanding. I'm wondering if there is some way to automatically have .toml files added whenever you cargo build a project in a subdirectory.

It's kind of tiring to manually add in the dir of each .toml file so I can get rid of the annoying `rust-analyzer failed to discover workspace` message that keeps popping up

**Comment by Veykril** [comment]
Closing in favor of https://github.com/rust-lang/rust-analyzer/issues/8622
