### ISSUE TITLE
Lifetime elision for generic mutable references with same type parameter.

### ISSUE THREAD

**Issue by javapro108** [rust-lang/rust-analyzer#13879]
When I activated lifetime elision on rust-analyzer in VS-CODE, two &mut T parameters in function signature shows different lifetimes. However, mut T is invariant over T and expect same lifetime of T. 

This can be checked on std::men::swap --> pub fn swap<T>(x: &mut T, y: &mut T) which shows different lifetimes for x and y.

**Comment by Veykril** [comment]
The `T` and its variance has no effect on the lifetimes here, it is correct that the parameters here have two different lifetimes inferred for them, https://doc.rust-lang.org/reference/lifetime-elision.html#lifetime-elision-in-functions

**Comment by javapro108** [comment]
> The `T` and its variance has no effect on the lifetimes here, it is correct that the parameters here have two different lifetimes inferred for them, https://doc.rust-lang.org/reference/lifetime-elision.html#lifetime-elision-in-functions

Thank you for your response. I tried to pass two different lifetimes in std::mem::swap which gave syntax error as expected. My understanding is - if rust allowed different lifetimes for mutable references, it would create safety vulnerability. Which is explained in "The Rustonomicon" dog-cat example -  https://doc.rust-lang.org/nomicon/subtyping.html#variance. 

If there is some kind of example with two mutable references as input to function and and their lifetime dependency, would really help to understand lifetimes constraints.

Here is what I tried.


```
use core::fmt::Debug;

fn with_local_global_mut<'a, 'b, T:Debug>(a: &'a mut T, b: &'b mut T ) {
    // do something with mutable references.. 
}

fn with_global_mut<'g>(g: &'g mut &'g i32) {
    let x :i32 = 32;
    let mut y: &i32  = &x;  // expecting x to live as long as g

    with_local_global_mut(&mut y,       g);
    //                                  (&mut &32, &mut &32)
}

fn main() {
    let a:i32  = 42;
    let mut g:&i32  = &a;
    with_global_mut(&mut g);
}

```

This is the error we get:

> warning: unused variable: `b`
>  --> src/main.rs:3:57
>   |
> 3 | fn with_local_global_mut<'a, 'b, T:Debug>(a: &'a mut T, b: &'b mut T ) {
>   |                                                         ^ help: if this is intentional, prefix it with an underscore: `_b`
> 
> error[E0597]: `x` does not live long enough
>   --> src/main.rs:9:24
>    |
> 7  | fn with_global_mut<'g>(g: &'g mut &'g i32) {
>    |                    -- lifetime `'g` defined here
> 8  |     let x :i32 = 32;
> 9  |     let mut y: &i32  = &x;  // expecting x to live as long as g
>    |                        ^^
>    |                        |
>    |                        borrowed value does not live long enough
>    |                        assignment requires that `x` is borrowed for `'g`
> ...
> 14 | }
>    | - `x` dropped here while still borrowed

**Comment by Veykril** [comment]
If you replace the `with_local_global_mut(&mut y,       g);` line with `std::mem::swap(&mut y, g);` you get the same error, which shows that the elision of `swap` is in fact the same.

**Comment by javapro108** [comment]
I think, I got it. Thank you for your help and interest in this one. I am able to run below example now. Lifetime of reference within T is invariant over T, however different life time of mutable reference to T is allowed.

```
fn with_local_global_mut<'a, 'b, T>(a: &'a mut T, b: &'b mut T) {
    std::mem::swap(a, b); 
}

fn with_global_mut<'m, 'g>(g: &'m mut &'g i32, b: &'g i32 ) {
    let x :i32 = 32;
    //let mut y: &i32  = &x;  // expecting x to live as long as g
    let mut y: &i32  = b;     // this is okay. ref in y(b) lives for g, though life of y is shorter than g.
    with_local_global_mut(&mut y,   g);
    //                   (&mut &32, &mut &32)
}

fn main() {
    let a:i32 = 42;
    let b:&i32 = &52;
    let mut g:&i32  = &a;
    println!("Before call - g: {}", g);
    with_global_mut(&mut g, &b);
    println!("After call - g: {}", g);    
}
```
Thank you so much again!!!

**Comment by javapro108** [comment]
closing this issue..
