### ISSUE TITLE
[Packaging request] Using zip for windows archive 

### ISSUE THREAD

**Issue by MordechaiHadad** [rust-lang/rust-analyzer#13872]
Use `.zip` for rust-analyzer-x86_64-pc-windows-msvc instead of `.gz`
using gz will require downloading some softwares like `WinZip` but I prefer not to and just use windows' explorer.

**Comment by lnicola** [comment]
Yeah, we should do this, but just in case: if you're using VS Code, you don't need to download anything.

**Comment by MordechaiHadad** [comment]
thanks! and nah i don't use VSCode.
