### ISSUE TITLE
use custom linker

### ISSUE THREAD

**Issue by alexzanderr** [rust-lang/rust-analyzer#13880]
hello.

i just want to use custom linker with rust analyzer. is it even possible?

i want specify the linker in the settings. i didnt see any linker settings in rust analyzer settings.

does rust-analyzer use my `~/.cargo/config.toml` ?

if so it should use the linker specified in the global cargo config

any suggestions?

thanks in advance.

**Comment by lnicola** [comment]
RA doesn't really link your program unless you use the debugging features. And if you do, it runs cargo build or test, so it will respect whatever you have as your configuration.

**Comment by alexzanderr** [comment]
is this setting a good way to tell to use custom linker ?
```
rust-analyzer.cargo.extraEnv (default: {})

    Extra environment variables that will be set when running cargo, 
rustc or other commands within the workspace. 
Useful for setting RUSTFLAGS.
```

**Comment by alexzanderr** [comment]
> so it will respect whatever you have as your configuration.

so it will respect `~/.cargo/config.toml` or the `project/.cargo/config.toml`?

**Comment by lnicola** [comment]
It will respect cargo's config.toml, except in specific cases like a Flatpak-sandboxed Code which probably doesn't work anyway.

**Comment by alexzanderr** [comment]
`Ok()`, nice, thanks for response!

**Comment by alexzanderr** [comment]
yes, i can confirm that rust-analyzer respects config, i saw my custom linker the in target folder.
