### ISSUE TITLE
[VSCode] rust-analyzer failed to load workspace: "cargo" "--version" failed

### ISSUE THREAD

**Issue by J-SQReD** [rust-lang/rust-analyzer#13883]
## Summary
After reinstalling my OS, I can no longer get rust-analyzer to properly function. I've tried installing Rust via the `rustup` script and via my Linux distribution's package manager. While Rust works via the terminal either way, using rust-analyzer in VSCode/VSCodium fails.

<img width="339" alt="2023-01-02_20-33" src="https://user-images.githubusercontent.com/39681015/210293282-21c34d89-6720-47a8-842a-2f820487f7c7.png">

## Logs from Output Window
[Rust-Analyzer_Client.txt](https://github.com/rust-lang/rust-analyzer/files/10334061/Rust-Analyzer_Client.txt)

[Rust-Analyzer_Server.txt](https://github.com/rust-lang/rust-analyzer/files/10334064/Rust-Analyzer_Server.txt)

[Rust-Analyzer_Server_Trace.txt](https://github.com/rust-lang/rust-analyzer/files/10334073/Rust-Analyzer_Server_Trace.txt)

## Enviroment
```
Operating System: EndeavourOS
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.1.2-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 16 × Intel® Core™ i7-10875H CPU @ 2.30GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: Dell Inc.
Product Name: XPS 17 9700

rust-analyzer version: 0.4.1349-standalone
rustc 1.66.0 (69f9c33d7 2022-12-12)
cargo 1.66.0 (d65d197ad 2022-11-15)

Version: 1.75.0-insider
Release: 22347
Commit: 11238faea62d570d77afe6edfe05c8b732c44a2b
Date: 2022-12-14T09:46:13.032Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.1.2-zen1-1-zen
Sandboxed: No
```

**Comment by 10ve** [comment]
> Did you try to run Code from the terminal? If you're using a DE and you're setting `RUSTUP_HOME` and/or `CARGO_HOME` in your shell's config, Code is not going to pick them up and rust-analyzer might become confused.

https://github.com/rust-lang/rust-analyzer/issues/11493#issuecomment-1044660677

**Comment by J-SQReD** [comment]
Thank you!
