### ISSUE TITLE
unclear how to pass -Z options to cargo metadata 

### ISSUE THREAD

**Issue by rbtcollins** [rust-lang/rust-analyzer#13888]
We have a private crate registry. This is using a sparse registry, so `cargo metadata` will fail:

```
$ cargo metadata
warning: please specify `--format-version` flag explicitly to avoid compatibility problems
error: failed to get `yyy` as a dependency of package `xxx v0.1.0 (/home/robertc/src/xxx)`

Caused by:
  failed to load source for dependency `yyy`

Caused by:
  Unable to update registry `registry-name`

Caused by:
  usage of sparse registries requires `-Z sparse-registry`
```

From the command line I can run : `cargo +nightly -Z registry-auth -Z sparse-registry metadata` and it produces metadata just fine, but I can't figure out how to tell `rust-analyzer` to both use the `nightly` rustup channel, *and* provide the `-Z` options needed to work.

**rust-analyzer version**: rust-analyzer version: 0.3.1348-standalone

**rustc version**: See above.

**relevant settings**: Nothing special.

**Comment by Veykril** [comment]
r-a currently does not expose a way to modify the `cargo metadata` command it executes, can you specify the flag in `.cargo/config.toml`? That should work

**Comment by kkocdko** [comment]
In `/home/kkocdko/.cargo/config`:

```toml
# [env]
# RUSTC_BOOTSTRAP = "1"
[unstable]
sparse-registry = true
```

**Comment by rbtcollins** [comment]
Thanks
