### ISSUE TITLE
When defining types in a function, `use` statement in `impl` functions causes unrelated type inference to fail

### ISSUE THREAD

**Issue by rben01** [rust-lang/rust-analyzer#13895]
**rust-analyzer version**: 0.3.1334-standalone (74ae2dd30 2022-12-25)

**rustc version**: rustc 1.67.0-nightly

**relevant settings**: None?

# Description

In a particular context, type inference fails and RA does not show the type of a variable assigned to a function's return value. This is caused by the presence of a `use` statement in a function.

# Steps to reproduce

1. Inside an outer function definition...
2. Define one struct, `S1`
3. And give `S1` a method `get_pair(self)` that returns a 2-tuple
4. Define a second struct, `S2`, that contains an instance of `S1`
5. And give `S2` a method that both 1. has a `use` statement and 2. calls `s1.get_pair()`

# Bug

The presence of the `use` statement causes type inference of the return type of `s1.get_pair()` to fail

# Code snippet

As far as I know this snippet is minimal.

```rust
fn f() {
	struct S1;

	impl S1 {
		fn get_one(self) -> i32 {
			0
		}
		fn get_pair(self) -> (i32, i32) {
			(0, 0)
		}
	}

	struct S2 {
		s1: S1,
	}

	impl S2 {
		fn no_fail_1(self) -> i32 {
			use std::path;
			let x = self.s1.get_one(); // let x: i32
			x
		}

		fn no_fail_2(self) -> i32 {
			let pair = self.s1.get_pair(); // let pair: (i32, i32)
			pair.0
		}

		fn fail(self) -> i32 {
			use std::path;
			let pair = self.s1.get_pair(); // let pair: {unknown}
			pair.0
		}
	}
}
```

# Screenshots

<img width="438" alt="image" src="https://user-images.githubusercontent.com/766670/210851222-00a6d6f1-2a5c-4bae-8d5b-c610d4953ee9.png">

<img width="434" alt="image" src="https://user-images.githubusercontent.com/766670/210851225-084a979f-68d8-43eb-97f2-177ffa38078d.png">

**Comment by bvanjoi** [comment]
Maybe it caused by fn can't infer its definition. For example, if we change the content of `S2::no_fail_1` to:

```rust
use std::path;
let x = self.s1.get_one();
1
```

The type of `x` will become `unkonwn`:

![image](https://user-images.githubusercontent.com/30187863/210926895-dd1fb195-8ceb-4485-bf9d-3ea28095ad59.png)

**Comment by lowr** [comment]
Impl items declared in a block are ["otherwise identical in meaning to declaring the item inside a module"](https://doc.rust-lang.org/reference/statements.html#item-declarations) but it seems we're only considering those that are defined in the the nearest ancestor block that contains items. Relevant function is [this](https://github.com/rust-lang/rust-analyzer/blob/80cabf726068187d8686b5ccf37aac484da84904/crates/hir-ty/src/method_resolution.rs#L271-L279).
