### ISSUE TITLE
RA memory usage keeps increase when I coding and don't decrease

### ISSUE THREAD

**Issue by PatchouliG** [rust-lang/rust-analyzer#13902]
## describtion
RA  cost more and more memory when i coding and won't free it until it use up all of memory
I try to restart RA, the memory usage is 1G when restart, but after coding or read code(jump to type definition),the memory usage become to 5G in 1 minute.when i stop coding, memory usage don't change
###  environment
20 rust file, 10 dependencies, 16GB memory , ubuntu 22.04, use vscode remote ,RA version is v0.4.1353(i try other version but is the same )

**Comment by lnicola** [comment]
That seems on the high side, but who knows how much code and how large those dependencies are?

You can currently do two things

 - use the "Measure memory usage" command when it's at 5 GB and post the output here. RA will be a little crashy after that, but you can ignore it or restart with the corresponding command
 - disable cache prefilling (there's a setting). This won't lower the memory usage, but it will grow steadily during use instead of right from the start.

**Comment by PatchouliG** [comment]
![屏幕快照 2023-01-07 下午2 34 56](https://user-images.githubusercontent.com/37369578/211134861-946dddef-5111-4e08-a5cf-b87b2a4f4c3d.png)
Per-query memory usage:
   178mb FileTextQuery
   164mb FileItemTreeQuery
   146mb HygieneFrameQuery
   110mb MacroArgTextQuery
    89mb AstIdMapQuery
    73mb ParseMacroExpansionQuery
    72mb MacroExpandQuery
    59mb InternMacroCallQuery
    56mb MacroDefQuery
    51mb TraitSolveQueryQuery
    49mb CrateDefMapQueryQuery
    47mb BlockDefMapQuery
    41mb SourceRootQuery
    32mb ImplDatumQuery
    31mb InferQueryQuery
    28mb FileSourceRootQuery
    27mb TraitImplsInDepsQuery
    24mb SourceRootCratesQuery
    23mb AttrsQuery
    22mb BodyQuery
    21mb BodyWithSourceMapQuery
    14mb FunctionDataQuery
    11mb GenericParamsQuery
     9mb ExprScopesQuery
     8mb GenericPredicatesQuery
     6mb ImplTraitQuery
     5mb InternFunctionQuery
     5mb ImplSelfTyQuery
     4mb ImplDataQuery
  4016kb TraitEnvironmentQuery
  3924kb AssociatedTyValueQuery
  3599kb ImportMapQuery
  3466kb ParseQuery
  2945kb InternImplQuery
  2259kb TypeAliasDataQuery
  2218kb ReturnTypeImplTraitsQuery
  2199kb TyQuery
  2067kb CallableItemSignatureQuery
  1912kb ValueTyQuery
  1622kb TraitImplsInCrateQuery
  1504kb InternConstQuery
  1385kb LineIndexQuery
  1142kb GenericDefaultsQuery
  1111kb StructDatumQuery
   964kb ModuleSymbolsQuery
   914kb FieldTypesQuery
   865kb GenericPredicatesForParamQuery
   790kb InternTypeAliasQuery
   640kb TraitDatumQuery
   519kb InternTypeOrConstParamIdQuery
   518kb InternCallableDefQuery
   405kb InherentImplsInCrateQuery
   340kb InternStructQuery
   329kb ConstDataQuery
   327kb CrateLangItemsQuery
   309kb CrateGraphQuery
   299kb StructDataQuery
   188kb VariantsAttrsQuery
   182kb LangItemQuery
   132kb FnDefDatumQuery
   111kb TraitDataQuery
   101kb AssociatedTyDataQuery
    85kb EnumDataQuery
    81kb InternClosureQuery
    78kb InternTraitQuery
    68kb InternEnumQuery
    19kb StaticDataQuery
    12kb InternStaticQuery
   4032b InternImplTraitIdQuery
   1136b FieldsAttrsQuery
    816b InternUnionQuery
    608b LibraryRootsQuery
    432b UnionDataQuery
    304b LocalRootsQuery
      0b FieldsAttrsSourceMapQuery
      0b VariantsAttrsSourceMapQuery
      0b AssociatedTyDataQuery
      0b InternTypeOrConstParamIdQuery
      0b LibrarySymbolsQuery
   204mb Remaining

(note: database has been cleared)

**Comment by PatchouliG** [comment]
I know the reason, my vscode installed the history plugin, it backup my source code when I coding.It's ok now after i exclude files in  the backup directory
