### ISSUE TITLE
rust-analyzer conflicts with vscode shortcut keys

### ISSUE THREAD

**Issue by QingyaoLin** [rust-lang/rust-analyzer#13908]
I noticed that the `rust-analyzer` shortcut overlapped with the vscode's shortcut `Ctrl + Shift + m`

![QQ截图20230108221747](https://user-images.githubusercontent.com/83944508/211201205-6dcab2ce-23a3-42c7-b78c-ec9765ba1c41.png)

To solve this problem, try to cancel the shortcut key Settings or set the shortcut key to empty.

**Comment by shogohida** [comment]
Hi guys! I want to work on this so I searched a bit about what I should change. It seems other shortcuts are also the same as VS code. Should I delete or change all of them?

https://github.com/rust-lang/rust-analyzer/blob/master/editors/code/package.json#L270-L282
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf
