### ISSUE TITLE
Don't include quote when renaming lifetimes or labels

### ISSUE THREAD

**Issue by Saecki** [rust-lang/rust-analyzer#13907]
I think it would make sense to strip the quote from the `range_for_rename` of lifetimes and labels, since it is redundant information. Additionally it allows to produce invalid input when accidentally removing the leading quote, triggering the check in `rename_reference` saying `Invalid name <ident> not a lifetime identifier`.

If you agree, I would take a stab at implementing this.

**Comment by Veykril** [comment]
Ye that sounds reasonable to adjust to not include the `'`

**Comment by vasilev-alex** [comment]
@Saecki are you working on this?

**Comment by Saecki** [comment]
> @Saecki are you working on this?

I wanted to, but I don't have time, feel free to take over
