### ISSUE TITLE
Expsoe a way to limit number of completions

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#13911]
Couple of thoughts: 

* Yes, we should limit this server-side. That's a general rule for I think any LSP request -- there's never a need to return more items which can be displayed on a single screen
* [x] We should limit this in the LSP layer **after** we sorted completions in the order of relevance 
* which means that https://github.com/rust-lang/rust-analyzer/issues/7935 is sadly a pre-requisite 

What we can do immediately though, is to make this configurable, and have infinite limit by default.

_Originally posted by @matklad in https://github.com/rust-lang/rust-analyzer/issues/13124#issuecomment-1250253865_

**Comment by MariaSolOs** [comment]
@Veykril could I work on this? :)

If yes, I just want to make sure that my idea matches yours: Since the server changes are pending, for now this could be a setting for the VS Code extension. Or were you thinking of something else?

**Comment by Veykril** [comment]
The immediately workable solution would be to add a limit config and then cap the completion items by that limit here somewhere after we have sorted them https://github.com/rust-lang/rust-analyzer/blob/93c8ae08dd6d4ffdfb1be265e6159274c0f7f72a/crates/rust-analyzer/src/handlers.rs#L806-L831
(so nothing VSCode specific needed)

**Comment by MariaSolOs** [comment]
I see, but then how would the setting be exposed to the user?

**Comment by Veykril** [comment]
Ah sorry, we generate the vscode config from the macro call here https://github.com/rust-lang/rust-analyzer/blob/bbb730a44136d34508cfd4f92d371639d163486a/crates/rust-analyzer/src/config.rs#L57
(via `cargo test -p rust-analyzer)

**Comment by MariaSolOs** [comment]
Got it, thanks a lot for explaining @Veykril <3
I'll start working on it today :)

**Comment by lnicola** [comment]
Implemented in #13986.
