### ISSUE TITLE
This loop never loops

### ISSUE THREAD

**Issue by danieleades** [rust-lang/rust-analyzer#13921]
https://github.com/rust-lang/rust-analyzer/blob/368e0bb32f1178cf162c2ce5f7e10b7ae211eb26/crates/hir-def/src/attr.rs#L254-L266

source: clippy.

After (locally) addressing #13919 and #13920 I see a bunch more useful clippy lints. Squashing clippy lints you don't necessarily care about can in many cases provide visibility of lints you probably do care about.

**Comment by lnicola** [comment]
It looks a bit strange, but it's not clear to me that it actually never ends. I assume we actually hit the `break` most of the time.

**Comment by Veykril** [comment]
That is a snippet using a labeled loop as a label break value block. Since label break value is stabilized now we can replace that

**Comment by danieleades** [comment]
> That is a snippet using a labeled loop as a label break value block. Since label break value is stabilized now we can replace that, that is we can just drop the `loop` keyword there

I think even before stabilisation of that feature it could have just been the return value of an expression, no? "Find, else return".

**Comment by danieleades** [comment]
> It looks a bit strange, but it's not clear to me that it actually never ends. I assume we actually hit the `break` most of the time.

if you don't hit the `break`, then you hit the `return`

**Comment by lnicola** [comment]
Right, I misread the code, sorry (was doing something else at the same time). In that case, I don't see anything wrong here. It doesn't convince me it's a "lint I probably care about".

**Comment by danieleades** [comment]
> Right, I misread the code, sorry (was doing something else at the same time). In that case, I don't see anything wrong here. It doesn't convince me it's a "lint I probably care about".

#13920 is a better example of "a lint you probably care about"
