### ISSUE TITLE
Is this code not recursive?

### ISSUE THREAD

**Issue by danieleades** [rust-lang/rust-analyzer#13920]
Can someone tell me if i'm losing my mind or not.

Looks like this `Display` implementation is delegating to it's own `to_string` method, which is provided by the `Display` trait

see https://doc.rust-lang.org/std/string/trait.ToString.html#impl-ToString-for-T

https://github.com/rust-lang/rust-analyzer/blob/368e0bb32f1178cf162c2ce5f7e10b7ae211eb26/crates/proc-macro-srv/src/abis/abi_1_58/proc_macro/mod.rs#L773-L777

there's a few similar examples

**Comment by danieleades** [comment]
source: with #13862 fixed, clippy doesn't error out early, and instead shows a bunch of new, hard errors related to the above. Whack-a-mole.

Is this a false positive? It looks legit, but this code is 2 years old, so if it really is recursive i don't understand how it wouldn't have been spotted.

It's actually kind of annoying behaviour on clippy's part. With 'warnings' it'll keep on collecting them. With 'errors', one or two errors can hide a whole bunch more. There might be some way around this, potentially by coercing all the default 'error' level lints to 'warning' level lints.

**Comment by lnicola** [comment]
I think we're missing this https://github.com/rust-lang/rust/blob/master/library/proc_macro/src/lib.rs#L1114-L1121. But I'm not surprised that a lot of the code there is never exercised.

**Comment by danieleades** [comment]
this is the part where I ask the maintainers if they're *absolutely sure* they don't want to revisit the clippy policy ;)

**Comment by bjorn3** [comment]
> I think we're missing this https://github.com/rust-lang/rust/blob/master/library/proc_macro/src/lib.rs#L1114-L1121.

Yeah, had to be removed because of specialization not being stable I believe.

**Comment by danieleades** [comment]
What's the best way to resolve this? Shall I just remove the offending methods entirely?

**Comment by lnicola** [comment]
I don't think there's a good solution here. `unimplemented!()` will compile and crash just as well as the current code -- which never happens, presumably because it never runs. I'd either do that or add some clippy suppressions. You can't remove them because it will no longer compile.

In the long run, we'll remove this code. In theory we should only support the latest Rust version or so. At some point we'll only have `abi_sysroot`, which doesn't have this problem.
