### ISSUE TITLE
Yet another "Rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file"

### ISSUE THREAD

**Issue by DanielProg39** [rust-lang/rust-analyzer#13926]
Sorry, I know that similar issues were opened several times (#3118, #3885), but I have no idea about what causes my problem.
This is what notification from rust-analyzer looks like:

> rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/user/projects/fibonacci/Cargo.toml, Some(Version { major: 1, minor: 62, patch: 1 }): Failed to run `"/home/user/.cargo/bin/cargo" "metadata" "--format-version" "1" "--manifest-path" "/home/user/projects/fibonacci/Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error: error: could not execute process `rustc -vV` (never executed) Caused by: No such file or directory (os error 2)

This is just an example, for showcasing I made a repo for that project, you can have a look on Cargo.toml and any other files [here](https://github.com/DanielProg39/Fibonacci-Example-Rust).

**Comment by lnicola** [comment]
> error: could not execute process `rustc -vV`

Sounds like it couldn't run that. How did you install Rust, and do `rustc -vV` and `cargo metadata` work from the VS Code terminal (if you are using VS Code, that is)?

**Comment by lnicola** [comment]
> So here what I got:

Did you run those from _a_ terminal, or from _the_ Code terminal? Does anything change if you run Code from a terminal?

**Comment by lnicola** [comment]
We just run `cargo metadata` with some arguments, if that can't find `rustc`, it's probably not our fault. Most users have problems because their `PATH` doesn't contain `~/.cargo/bin` when they run Code from their DE, while running it from a terminal fixes this. Are you sure you don't have any weird environment variables set? You can try `env | grep -P 'RUST|CARGO'`.

**Comment by DanielProg39** [comment]
> You can try `env | grep -P 'RUST|CARGO'`.

I tried, it returned nothing. I'm confused. I've compiled my programs many times succesfully and never had an issue.
It also could be that I use the Flatpak version of VSCodium and launch it in terminal with `flatpak run com.vscodium.codium`, so it, basically doesn't change anything. It also can be because maybe (I don't remember exactly) I had installed "Rust" add-on previously (I deleted it before installing rust-analyzer). What do you think?

**Comment by lnicola** [comment]
I think we have an issue or two about the Flatpak version. That seems like it could cause problems.

**Comment by DanielProg39** [comment]
Thanks, I will reinstall VSCodium asap and tell you about results

**Comment by DanielProg39** [comment]
Installing VSCodium from .deb repo resolved the problem. Probably an issue is about something with Flatpak
