### ISSUE TITLE
Support repo-relative paths in `rust-analyzer.server.path`

### ISSUE THREAD

**Issue by OmarTawfik** [rust-lang/rust-analyzer#13939]
The VS Code configuration `rust-analyzer.server.path` exists to use a local binary, which is great when testing stuff, and also when using from a dev container. However, it expects a full path, which doesn't work well with version-controlled binaries. For example, if I set it to:

```jsonc
    // relative to VS Code workspace/repo root
    "rust-analyzer.server.path": "bin/rust-analyzer",
```

The extension will fail, printing the following error to `Rust Analyzer Client` VS Code output channel:

```log
INFO [1/12/2023, 7:10:00 PM]: Starting language client
INFO [1/12/2023, 7:10:00 PM]: Using server binary at bin/rust-analyzer
ERROR [1/12/2023, 7:10:00 PM]: Bootstrap error Error: Failed to execute bin/rust-analyzer --version. `config.server.path` or `config.serverPath` has been set explicitly. Consider removing this config or making a valid server binary available at that path.
```

I wanted to propose executing that command relative to the workspace directory, to allow users to specify paths that are relative to the repository they are working on, instead of forcing them to use machine-wide installations.

**Comment by lnicola** [comment]
If you can set `PATH` in your environment, that should also work.

**Comment by OmarTawfik** [comment]
@lnicola .. Thanks for the suggestion! But as it requires changing the environment BEFORE loading VS Code, I'm not sure it would be ideal/as easy for most use cases:

1. It won't work if people are switching between different projects in the same window (open recent/`^R` hotkey for example).
2. It would require much more complex setup in case of running remote containers, or using GitHub workspaces, etc...
3. In some cases, it would defeat the purpose of letting repositories specify their own paths/configs. i.e. if I already know the path to the repository-specific binary (without opening it first), I can already set my machine-local `settings.json`.

**Comment by OmarTawfik** [comment]
I think the fix would come to setting `cwd` in the `spanSync()` call on the following line to the value of `workspace.uri.fsPath`. I assume there are no further security concerns, if we also check the `workspace.isTrusted` flag. Please let me know if I missed something.

https://github.com/rust-lang/rust-analyzer/blob/a119352adab65d0cab25c13ae0fd7676bed7100f/editors/code/src/util.ts#L115-L124

**Comment by bjorn3** [comment]
I think you can set `PATH` using `rust-analyzer.server.extraEnv`, which can be put in the project specific configuration.

**Comment by OmarTawfik** [comment]
@bjorn3 thanks for the suggestion. can you please clarify? something like below won't work, since:

* It won't expand existin `$PATH` values.
* It won't still know how to resolve `${workspaceFolder}`.

```json
 "rust-analyzer.server.extraEnv": {
    "PATH": "$PATH:${workspaceFolder}/bin"
  }
```

**Comment by bjorn3** [comment]
I see, I assumed it would work.

**Comment by Veykril** [comment]
```json
"rust-analyzer.server.path": "${workspaceFolder}/bin/rust-analyzer",
```
should work

**Comment by OmarTawfik** [comment]
@Veykril It does not. See logs below:

```log
INFO [1/19/2023, 2:05:40 PM]: Starting language client
INFO [1/19/2023, 2:05:40 PM]: Using server binary at ${workspaceFolder}/bin/rust-analyzer
ERROR [1/19/2023, 2:05:40 PM]: Bootstrap error Error: Failed to execute ${workspaceFolder}/bin/rust-analyzer --version. `config.server.path` or `config.serverPath` has been set explicitly. Consider removing this config or making a valid server binary available at that path.
```

It has been a while since I worked with VS Code extensions, but my understanding is that VSCode itself does not resolve `${var}` variables in `settings.json` before passing it to extensions. It only does so for `tasks.json`. It also doesn't provide an API for extensions to resolve such variables themselves. So that resolution would have to be implemented on `rust-analyzer` side, or as my initial suggestion, set `cwd` when executing that command to the workspace folder directly.

See this for more information: https://github.com/microsoft/vscode/issues/2809

**Comment by Veykril** [comment]
Ah, apologies, we do support variable substitution (we re-implemented it), but we do it after spawning the server I think. That is, that *should* work but it currently doesn't.

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/blob/6e52c64031825920983515b9e975e93232739f7f/editors/code/src/ctx.ts#L155-L161
Yep, we pull the server path first, then substitute the configs, that's the wrong order.

**Comment by OmarTawfik** [comment]
@Veykril thanks for explaining! I sent #13993 to fix it.
