### ISSUE TITLE
feature request: refactor module file to module directory

### ISSUE THREAD

**Issue by EverlastingBugstopper** [rust-lang/rust-analyzer#13930]
I would love a feature that converts the following tree structure:

```
src/
  module/
    mod.rs
    nested.rs
```

into this tree structure:

```
src/
  module/
    mod.rs
    nested/
      mod.rs
```

**Comment by Young-Flash** [comment]
RA has `move_to_mod_rs` assist already, which resolve this issue.

This issue can be closed, cc @lnicola
