### ISSUE TITLE
Missing dependencies on Android 

### ISSUE THREAD

**Issue by stalek71** [rust-lang/rust-analyzer#13944]
I downloaded rust analyzer version for arm64 and configured helix editor to use it, but it doesn't work because of the missing dependencies in rust analyzer binary. 
Could you build it with static libs instead of dynamic ones?

![Screenshot_20230114-104614](https://user-images.githubusercontent.com/6651025/212467882-eb57db46-411d-4c68-8e83-75be1b03f5df.jpg)

![Screenshot_20230114-111826](https://user-images.githubusercontent.com/6651025/212467887-7f9cb6e8-22ec-4c87-abae-02f4ca307f42.jpg)

**Comment by lnicola** [comment]
What you downloaded is not an Android build. I suggest building from source.

**Comment by stalek71** [comment]
It looks it should work now.
Thanks!

![Screenshot_20230114-122050](https://user-images.githubusercontent.com/6651025/212469510-b3a51c13-d398-4a0c-98de-f4a4d17748d2.jpg)

**Comment by stalek71** [comment]
It's ok so I close the issue.

![Screenshot_20230114-123647](https://user-images.githubusercontent.com/6651025/212470048-516db5d5-0269-42d3-9196-8b7d135db39d.jpg)

**Comment by lnicola** [comment]
Cool, 10 minutes is faster than our CI.

**Comment by d4rkOfficial** [comment]
![Screenshot_2023-01-19-02-06-13-97_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/100008396/213260016-16c673ce-4ea0-4679-9d1a-f4d27cb624da.jpg)

`pkg install rust-analyzer` works!
