### ISSUE TITLE
Rename Symbol doesn't work in function annotated with `#[tokio::main]`

### ISSUE THREAD

**Issue by gimmi** [rust-lang/rust-analyzer#13958]
https://github.com/rust-analyzer/rust-analyzer.github.io/issues/195

**Comment by gimmi** [comment]
@lnicola is right, rename work when removing the `#[tokio::main]` attribute:

![RenameBug](https://user-images.githubusercontent.com/6589/212554613-1e5c8fa3-d015-46e7-8ed8-06d3f088a1f6.gif)

**Comment by lowr** [comment]
Duplicate of #12362 (cc #13614).
