### ISSUE TITLE
RA shows incorrect size and alignment of types

### ISSUE THREAD

**Issue by veber-alex** [rust-lang/rust-analyzer#13959]
![image](https://user-images.githubusercontent.com/29788806/212560205-eb52b954-012f-4f10-8dae-74040d42f60d.png)

**rust-analyzer version**: 0.4.1367-standalone

**rustc version**: rustc 1.68.0-nightly (0b90256ad 2023-01-13)

**Comment by bjorn3** [comment]
Which target are you on?

**Comment by veber-alex** [comment]
size also is incorrect:
![image](https://user-images.githubusercontent.com/29788806/212560496-4f83aae6-6235-471b-8ec1-881ac9db5173.png)

**Comment by veber-alex** [comment]
> Which target are you on?

x86_64-unknown-linux-gnu

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rust-analyzer/issues/13951 seems related.

**Comment by HKalbasi** [comment]
I can't replicate neither this nor #13951 on my system. Can you please provide output of `rustc -Z unstable-options --print target-spec-json`?

**Comment by Veykril** [comment]
We might want to log the loaded spec (by default) fwiw. Also it seems odd that (presumably) the default spec can panic an assertion?

**Comment by veber-alex** [comment]
```json
{
  "arch": "x86_64",
  "cpu": "x86-64",
  "crt-static-respected": true,
  "data-layout": "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128",
  "dynamic-linking": true,
  "env": "gnu",
  "has-rpath": true,
  "has-thread-local": true,
  "is-builtin": true,
  "llvm-target": "x86_64-unknown-linux-gnu",
  "max-atomic-width": 64,
  "os": "linux",
  "position-independent-executables": true,
  "pre-link-args": {
    "gcc": [
      "-m64"
    ]
  },
  "relro-level": "full",
  "stack-probes": {
    "kind": "inline-or-call",
    "min-llvm-version-for-inline": [
      16,
      0,
      0
    ]
  },
  "static-position-independent-executables": true,
  "supported-sanitizers": [
    "address",
    "cfi",
    "leak",
    "memory",
    "thread"
  ],
  "supported-split-debuginfo": [
    "packed",
    "unpacked",
    "off"
  ],
  "target-family": [
    "unix"
  ],
  "target-pointer-width": "64"
}
```

**Comment by HKalbasi** [comment]
Logging it is a good idea and helps replicating possible future bugs.

I can guess why it may panic in case of mismatching specs. std uses some attributes for controlling layout and niche and there are some validity checks for those attributes, which may fail with incorrect target spec. So we might want to disable layout calculation completely instead of using a default target spec.

**Comment by Veykril** [comment]
This should be fixed with https://github.com/rust-lang/rust-analyzer/pull/13966
