### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by tareksander** [rust-lang/rust-analyzer#13954]
**rust-analyzer version**: 0.4.1366-standalone

**rustc version**: rustc 1.66.0 (69f9c33d7 2022-12-12)

**relevant settings**: all defaults

While working in my workspace rust-analyzer takes normally 1-4GB of RAM, but suddenly it started continuously reading files (my drive LED lit up), had high CPU usage and 8+ GB of RAM usage.  
I couldn't get a log as I just killed the process to prevent my computer from freezing (my swap space was already half full and rust-analyzer continued to reserve memory) and I haven't encountered this again, but maybe someone also gets this and the cause gets found.

**Comment by vpochapuis** [comment]
I got a Similar issue using Rust-Analyzer Server with VsCode.

OS: Archlinux
IDE: VsCode

On both
- rust-analyzer version: 0.3.1472-standalone
- rust-analyzer version: 0.4.1476-standalone

![image](https://user-images.githubusercontent.com/75721408/231961156-7e2b18ae-18b0-4f61-ae20-40315b677cc6.png)

This is the "normal" amount of RAM (15G) while working on 1 workspace containing 8 crates I made for work.

However, my total amount of Memory used at time T is 47G (28G RAM + 19G Swap).
When running `pkill rust-analyzer` it drops of 30G at time T+1 before slowly getting back to the previous state (VsCode restarting the server) :

![image](https://user-images.githubusercontent.com/75721408/231962836-9d524868-08a4-4df6-9b89-8362336b3adf.png)
 
So there seems to be more than just the 15G advertised by Gnome process monitor.

And sometimes, if I do a big change in the code, when saving the file with the "format on save" option enabled in VsCode, the Memory usage will increase without stopping until the computer freeze due to both the RAM and Swap being full.

**Comment by lnicola** [comment]
@vpochapuis are you using a Code workspace? Normally we only have two processes, so of you have more, you have multiple instances of Code running, a Code workspace, or they're hung and got started before, but didn't close.

**Comment by lnicola** [comment]
I suggest using a Cargo workspace instead. It won't completely fix the memory usage, especially on certain types of codebases (ahem, blockchain), but it will help a lot as we'll no longer spawn one instance for each crate.

**Comment by vpochapuis** [comment]
I am using a Cargo workspace, which points to the different crates I am using, which are not all in the same folders.

**Comment by lnicola** [comment]
> I am using a code Workspace where i have only the folders of my Rust Crates in there

> I am using a Cargo workspace, which points to the different crates I am using,

I'm not sure I understand, but you might want to look into this if you have more than one rust-analyzer process running (the proc macro expander has a different name these days, but shouldn't use that much memory).

**Comment by vpochapuis** [comment]
My current setup:
Rust:
- Cargo Workspace (setup in a file at the root of our project)

Code:
- 1 window with 1 workspace inside, with each Crate as a Folder opened inside (before I had 1 window for each folder, which was creating lots of instance of Rust-Analyzer, but I stopped doing so, even though I liked the convenience).

Here is the list of Rust related process running:

![image](https://user-images.githubusercontent.com/75721408/231973994-d61f088d-77bf-46ea-91a8-ae3c048cccbf.png)

**Comment by Veykril** [comment]
those proc-macro server instances indicate that you have 8 top level cargo workspaces loaded, not 1. So I believe your high memory usage comes from https://github.com/rust-lang/rust-analyzer/issues/14476

**Comment by vpochapuis** [comment]
I have 1 Cargo workspace file, with 8 members, 2 binary crates and 6 library crates.
I am not sure I understand well the fact that there is several Cargo Workspaces.
Each of those members are opened as a folder in the Code Workspace.

Also, I don't understand why the process advertised Memory is different from the real memory usage.

I am sorry if I didn't explain my situation well previously.

**Comment by Veykril** [comment]
> Each of those members are opened as a folder in the Code Workspace.

Ah sorry I missed this part. *This* is the problem. Code workspaces currently cause each separate folder to be reported as its own workspace to r-a which has a similar effect. (havent investigated whether this is our fault or not, or if there is anything that can be done to prevent this)

**Comment by lnicola** [comment]
You can reduce the memory usage by making a Code workspace that only contains the Cargo workspace (and not the 8 crates), but that leads to an awful IDE experience.

> Also, I don't understand why the process advertised Memory is different from the real memory usage.

Measuring memory usage is not as easy as it sounds: https://elinux.org/Android_Memory_Usage. I suspect that process monitor shows the RSS (the RAM usage, at a first approximation), but not the swap.

**Comment by vpochapuis** [comment]
@lnicola Thanks a lot! Its a chance to have people like you helping the community like this.

Yeah I am more and more being upset with Code workflow..

Everyday I think whether I should try going back to Emacs or Helix and take the time to learn keybindings.
Although, would this setup be less prone to this kind of issues? Is it related to how Code handles Worskpaces, Folders and Projects? Or is it directly related to Rust-Analyzer? 

What is the setup you would recommend ?

**Comment by vpochapuis** [comment]
@Veykril Thanks a lot to you too!

So its an IDE issue...

**Comment by Veykril** [comment]
For the time being I recommend not using code workspaces and just opening the top level cargo workspace directly with VSCode

**Comment by lnicola** [comment]
I think it's mostly a rust-analyzer limitation. You won't get a better experience with Emacs or Helix, but rather a worse one instead.

As Veykril says, you should try to structure the crates so that you're able to open a single directory in Code.

**Comment by vpochapuis** [comment]
@Veykril So using Code and Rust, I can't:
- Open 1 window per crate
- Have 1 Folder per crate in the File browser (Code Workspace)

And I must:
- Open the root project

I wish there was more convenient ways.
But I will do that

**Comment by lnicola** [comment]
> Open 1 window per crate

I'm pretty sure that's going to be a bad idea in any language.

> Have 1 Folder per crate in the File browser (Code Workspace)

I don't know how other language servers handle this, but I wouldn't be surprised if some of them had a similar issue.

**Comment by vpochapuis** [comment]
@lnicola  On emacs you can open a window(`frame` if i remember well) to reflect a buffer from the same session on another screen.
That's what I wanted to emulate a bit, because I liked using different screens while working on big projects,

**Comment by lnicola** [comment]
@vpochapuis if you still have this setup, can you check if it's working better in the latest version?

**Comment by vpochapuis** [comment]
@lnicola Hey ! When we discussed last time I changed to the "Open the root project" solution and removed my setup. However tomorrow at work I could update and set it up again to let you know if there is still the issue!

**Comment by vpochapuis** [comment]
@lnicola It seems to be fixed! Amazing! I only have one instance of rust-analyzer and rust-analyzer-proc-macro-srv per VsCode window. So opening a VsCode Workspace with several folder from the same Rust Workspace doesnt affect RAM usage like before!
Thanks!

**Comment by Veykril** [comment]
Closing as the original issue is not really workable

**Comment by praem90** [comment]
Will this help?
https://www.dgendill.com/posts/programming/2024-01-06-reducing-rust-analyzer-memory-usage.html
