### ISSUE TITLE
Question: How can I identify VSCode versions?

### ISSUE THREAD

**Issue by om4csaba** [rust-lang/rust-analyzer#13967]
How does one identify the versions of this repo to what I got in VSCode?

Currently, I have rust-analyzer v0.3.1361 installed and pending an update to v0.3.1369 on my VSCode. But tags and changelog entries are date-based here and on https://rust-analyzer.github.io/, which is not matching.

Thanks

**Comment by lnicola** [comment]
https://open-vsx.org/extension/rust-lang/rust-analyzer/0.3.1369 works in a pinch (you can see the publishing date), and so does installing or inspecting the VSIX on GitHub. I can confirm that 0.3.1369 is the latest one.

Would you consider this fixed if the GitHub artifact and/or release name contained the version number?

**Comment by om4csaba** [comment]
> Would you consider this fixed if the GitHub artifact and/or release name contained the version number?

Yes, if the release could refer to the VSCode version, that would be great.
For example, a third line after commit, release lines.

**Comment by lnicola** [comment]
Yeah, was planning to add those too in the future. What's harder is to change the versioning scheme. Right now it increments by around 8-10 on each release.

**Comment by om4csaba** [comment]
Thanks for the details.

I figured out the extension version comes from the `${{ github.run_number }}`. But it looks like the changelog (and release) body was written by hand when the new version was only available when the extension was already published.

Here is an idea:

Would you welcome a pull request that replaces `${{ github.run_number }}` with a `date +%Y%m%d`? 

That output a version similar to `20230117`. It is still semver compatible but uses the date-based approach like the release tag.

**Comment by lnicola** [comment]
There's a small problem with that: we have nightly and release (weekly) versions, using the date would cause a conflict between them.

**Comment by om4csaba** [comment]
I understand.

Thanks for taking the time to walk me through this.
