### ISSUE TITLE
rust-analyzer doesn't read [env] values from .cargo/config.toml

### ISSUE THREAD

**Issue by recatek** [rust-lang/rust-analyzer#13976]
I'm using environment variables to configure proc macros that need to open and parse files for generation. When building in cargo, I can set these in the `[env]` block of `.cargo/config.toml`. However, rust-analyzer doesn't read these environment variables, forcing me to duplicate them as settings with `rust-analyzer.server.extraEnv`. 

**rust-analyzer version**: rust-analyzer version: 0.3.1369-standalone
**rustc version**: rustc 1.66.0 (69f9c33d7 2022-12-12)

**Comment by Veykril** [comment]
Two things here, we should fetch the env section via `cargo config get` like we do here https://github.com/rust-lang/rust-analyzer/blob/03f676ed1fa3d9c0b39a8ba629b9cec0a142fe93/crates/project-model/src/cargo_workspace.rs#L522-L525 and then pass these to where we start the proc-macro server. (We should also make sure that `env!` expansion checks these vars).

The other thing is that we should watch the `.cargo/config.toml` for changes and re-fetch the section(s) on change.

**Comment by Veykril** [comment]
The `build.rs` file is run by cargo (which we invoke) so it should be visible there
