### ISSUE TITLE
Feature request: `extraArgs` for `buildScripts` in settings 

### ISSUE THREAD

**Issue by CGMossa** [rust-lang/rust-analyzer#13972]
While trying to achieve something else, and noticed that there is a missing option:

```json
{
"rust-analyzer.cargo.buildScripts.extraArgs" : []
}
```

**Comment by Veykril** [comment]
extra args for build scripts doesn't make too much sense, if you need to change up the arguments you might as well replace the entire command with `overrideCommand`
