### ISSUE TITLE
Cursor in the wrong position on type parameter `<` completion

### ISSUE THREAD

**Issue by GrayJack** [rust-lang/rust-analyzer#13982]
**rust-analyzer version**: rust-analyzer (6862da954 2023-01-18)

**rustc version**: rustc 1.68.0-nightly (333ee6c46 2023-01-18)

**Description:** When typing `<` on places that trigger RA to close it (on generic type parameter places), it is completing with `<$0>` with the cursor after `>`. That makes the user go back, delete `$0`, and then write the type parameter.

**Example:** (`|` is where the cursor is placed)

```rust
struct MyStruct<|(T);
```

completes as:

```rust
struct MyStruct<$0>|(T);
```

**Expected behavior:** After completion, the  being on `$0` selected

**Comment by Veykril** [comment]
That typing completion is known to be buggy, see https://github.com/rust-lang/rust-analyzer/issues/12379
