### ISSUE TITLE
Direct the user to the logs channel when build scripts fail

### ISSUE THREAD

**Issue by OmarTawfik** [rust-lang/rust-analyzer#13995]
For the following notification, when build scripts panic:

> rust-analyzer failed to run build scripts. Check the server logs for additional info.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/15987992/213842758-f5633614-f267-42e6-8756-f403e7961461.png">

It wastes users time and effort to hunt for the correct channel and scroll in it when that happens.

1. Is it possible to reveal that channel when that happens? perhaps by using `LogOutputChannel.show(true)` ([link to API](https://code.visualstudio.com/api/references/vscode-api#LogOutputChannel)).
2. If too disruptive, would it be better to put it behind a VS Code configuration setting (`false` by default)?
3. If too much work/doesn't work well with current settings, can we at least add a button on that notification box to `Show Logs`?

Thanks!

**Comment by Veykril** [comment]
These notifications are done by the language client implementation of VSCode https://github.com/microsoft/vscode-languageserver-node, we can't modify it unfortunately. I'd love to add a button to it, but I keep forgetting about opening an issue upstream about this :)

**Comment by OmarTawfik** [comment]
@Veykril is this the extension point you are talking about?

https://github.com/rust-lang/rust-analyzer/blob/9a6294d7038e7eab00beafdf64ec4aa50a4c66a2/crates/rust-analyzer/src/lsp_utils.rs#L60-L62

Would it be solved by using `lsp_types::request::ShowMessageRequest` instead? It supports specifying user actions: https://docs.rs/lsp-types/latest/lsp_types/request/enum.ShowMessageRequest.html

**Comment by Veykril** [comment]
That is unfortunately not necessarily enough (though thanks for bringing the request up, I was only aware of the notification), that request will render a button, but the button press result will be sent back to the server. For opening the logs we'd need to handle this in the client. There is no way to hook into that handling on the VSCode side though unfortunately -> https://github.com/microsoft/vscode-languageserver-node/blob/56c23c557e3568a9f56f42435fd5a80f9458957f/client/src/common/client.ts#L1045-L1077

I suppose we *could* add an LSP extension for a showLogs notification that the server sends to the client, then we could have an exchange like:
```
server -> client: ShowMessageRequest
client -> server: ShowMessageResponse with `go to output` button clicked
server -> client: ShowLogsNotification
```

**Comment by OmarTawfik** [comment]
Thank you!
