### ISSUE TITLE
Pointer metadata (RFC 2580) is not supported

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/rust-analyzer#13992]
```Rust
#![feature(ptr_metadata)]

use core::ptr::Pointee;

fn main() {
    let x: <[&str] as Pointee>::Metadata = todo!();
    let mut y = x;
    y = 2;
}
```

Rustc accepts the above code but r-a reports a type mismatch between `<[&str] as Pointee>::Metadata` and `i32`. It is probably due magic implementation of `Pointee` trait for types.

**Comment by HKalbasi** [comment]
What is the correct way to approach this? Should it be handled in chalk?

**Comment by Veykril** [comment]
I would imagine this needs chalk support since there exist no actual implementations in source

**Comment by jonas-schievink** [comment]
cc https://github.com/rust-lang/rust/issues/81513
