### ISSUE TITLE
Rust-analyzer not working in VSCode

### ISSUE THREAD

**Issue by Sheepyhead** [rust-lang/rust-analyzer#14018]
**rust-analyzer version**: 0.4.1378-standalone

**rustc version**: rustc 1.69.0-nightly (5e37043d6 2023-01-22)

rust-analyzer is not giving me any errors in vscode despite there being several build errors in the project. I get no errors in any of the outputs either, adding info logging shows me that the server is spitting out maybe 50k lines per second when idle, which I'm not sure whether is an error or not. I'm on arch linux (EndeavourOS), and everything should be freshly updated. I've tried both the release and the pre-release versions of the extension to no avail. 

This is the info line I get: 

`[INFO salsa::derived::slot] solve_goal{goal=UCanonical { canonical: Canonical { value: InEnvironment { environment: Env([]), goal: Implemented(AdtId(StructId(StructId(2321)))<[]>: TraitId(59)) }, binders: [] }, universes: 1 }}: FileItemTreeQuery(HirFileId(3996)): returning memoized value changed at R13439`

**Comment by flodiebold** [comment]
It looks like you're setting `RA_LOG=info` somewhere. That's going to lead to a lot of logging, which will heavily impact performance.

**Comment by Sheepyhead** [comment]
> It looks like you're setting `RA_LOG=info` somewhere. That's going to lead to a lot of logging, which will heavily impact performance.

Yes, I did that to try and get more info because I was getting no error messages. It's part of the troubleshooting guide. In any case it seems to randomly have started working again so I'm going to close this issue, as I can't give any more info about what went wrong

**Comment by lnicola** [comment]
> rust-analyzer version: 0.4.1378-standalone

By the way, if you're using VS Code, there's no need to install `rust-analyzer` from the distro repository.
