### ISSUE TITLE
Bug: Incorrectly labels redundant imports with different crates

### ISSUE THREAD

**Issue by mkhan45** [rust-lang/rust-analyzer#14021]
**rust-analyzer version**: 0.3.1377-standalone

**rustc version**: rustc 1.66.0-nightly

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

Sorry if this has been fixed, I don't have an easy way to upgrade.

In this case, the warning is incorrect; removing the second import makes `ThingA` refer to `Thing::ThingA`:
```rs
enum Thing {
    ThingA,
    ThingB,
}

fn some_func() {
    use Thing::{*, ThingA as A};
    use some_crate::ThingA; // 'the item `ThingA` is imported redundantly
}
```

**Comment by jonas-schievink** [comment]
This isn't our diagnostic, it comes from rustc, so please file this at https://github.com/rust-lang/rust
