### ISSUE TITLE
Regression: checkOnSave.overrideCommand is being ignored

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#14027]
I noticed unexpected rebuilds when working in Miri, and after a lot of debugging came to the conclusion that since a recent update, RA seems to entirely ignore `checkOnSave.overrideCommand`. My config did not change.

I have this set as follows
```rust
    "rust-analyzer.checkOnSave.overrideCommand": [
        "./miri",
        "cargo",
        "clippy",
        "--all-targets",
        "--message-format=json"
    ],
```
`./miri cargo` will always `exit 1`. However, vscode still succeeds with a check build. So clearly something is very wrong here.

**rust-analyzer version**: rust-analyzer version: 0.3.1369-standalone

**rustc version**: rustc 1.69.0-nightly (a5fa99eed 2023-01-22)

**relevant settings**: 
```
    "rust-analyzer.lens.enable": false,
    "rust-analyzer.cachePriming.enable": false,
    "rust-analyzer.cargo.buildScripts.useRustcWrapper": false,
    //
    "rust-analyzer.diagnostics.disabled": [
        "unlinked-file", // I guess for "normal" projects unlinked files are strange, for me they are common
        "unresolved-module", // https://github.com/rust-lang/rust-analyzer/issues/9173
        "type-mismatch", // https://github.com/rust-lang/rust-analyzer/issues/1109
    ],

// Place your settings in this file to overwrite default and user settings.
{
    "rust-analyzer.rustc.source": "discover",
    "rust-analyzer.linkedProjects": [
        "./Cargo.toml",
        "./cargo-miri/Cargo.toml"
    ],
    "rust-analyzer.checkOnSave.overrideCommand": [
        "./miri",
        "cargo",
        "clippy",
        "--all-targets",
        "--message-format=json"
    ],
    // Contrary to what the name suggests, this also affects proc macros.
    "rust-analyzer.cargo.buildScripts.overrideCommand": [
        "./miri",
        "cargo",
        "check",
        "--message-format=json",
    ],
}
```

**Comment by RalfJung** [comment]
Downgrading to rust-analyzer version: 0.3.1348-standalone fixed the issue.

**Comment by Veykril** [comment]
latest stable (`0.3.1377-standalone`) should have this fixed

**Comment by Veykril** [comment]
hmm, maybe? I am not sure, CI says openvsx has been published as well. Anyways it should work on your version as well if you replace `checkOnSave` with `check`, that is `rust-analyzer.check.overrideCommand`

**Comment by RalfJung** [comment]
So both of these will work in the future?

**Comment by Veykril** [comment]
Yes, `checkOnSave` should be a deprecated alias for `check` now, but there was a bug in the handling logic for it that made it not work in all circumstances on that version.

**Comment by lnicola** [comment]
The latest release didn't reach OpenVSX for some reason.

**Comment by RalfJung** [comment]
https://open-vsx.org/extension/rust-lang/rust-analyzer/latest shows the latest version, but vscodium doesn't...

**Comment by lnicola** [comment]
![image](https://user-images.githubusercontent.com/308347/214774733-c199d4ba-5c40-4fce-a5c9-784a48dd2f88.png)

I don't see `0.3.1377` in there. I filed https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2554 on Monday.

**Comment by Veykril** [comment]
This should work again now
