### ISSUE TITLE
The variable type is being determined incorrectly

### ISSUE THREAD

**Issue by AndreySmirnov81** [rust-lang/rust-analyzer#14030]
In the following example, instead of `pub struct FOO`, `pub fn FOO()` is displayed. Also `Go to Definition` jumps to `pub fn FOO()`.

[main.rs.txt](https://github.com/rust-lang/rust-analyzer/files/10508632/main.rs.txt)

![изображение](https://user-images.githubusercontent.com/19325847/214820904-3733973a-3f0d-4a5e-9906-738138a949d6.png)

The problem is observed if a path is specified before `FOO`. There is no such problem in line 14 and 15.

rust-analyzer version: 0.3.1377-standalone (daa0138e4 2023-01-21)

```
>rustup show
...
active toolchain
----------------
stable-x86_64-pc-windows-msvc (default)
rustc 1.66.1 (90743e729 2023-01-10)
```

VS Code 
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: Yes

**Comment by Veykril** [comment]
We are only handling enum variants here https://github.com/rust-lang/rust-analyzer/blob/dd673eea33079a3bf194fad25a6aec2e824e9041/crates/hir/src/source_analyzer.rs#L530-L534

we should also handle the rest

**Comment by AndreySmirnov81** [comment]
![изображение](https://user-images.githubusercontent.com/19325847/214834194-77c8051b-73d2-43b3-8ecc-f81b58ee0469.png)
