### ISSUE TITLE
negative trait bound show incorrectly in vscode outline view

### ISSUE THREAD

**Issue by gftea** [rust-lang/rust-analyzer#14044]
For below codes

```
struct Test;
impl !Unpin for Test {}
```
The outline show `impl Unpin for Test`, without `!`

**rust-analyzer version**: 0.3.1377

**rustc version**: rustc 1.66.0 (69f9c33d7 2022-12-12)

**relevant settings**: default

**Comment by Veykril** [comment]
Relevant code is here https://github.com/Veykril/rust-analyzer/blob/9814d798411a4b1b258c710f86626bd1997e406f/crates/ide/src/file_structure.rs#L157-L177

**Comment by gftea** [comment]
@Veykril , how about change the line

```
Some(t) => {
                      format!("impl {}{} for {}", it.excl_token().map(|x| x.to_string()).unwrap_or_default(), t.syntax().text(), target_type.syntax().text(),)

```
