### ISSUE TITLE
Code folding does not persist after reloading window

### ISSUE THREAD

**Issue by hyperupcall** [rust-lang/rust-analyzer#14052]
## Description

When running the VSCode extension `rust-analyzer`, code folds aren't saved when the windows is refreshed.

## Versions

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

```txt
rust-analyzer version: 0.3.1386-standalone
```

**rustc version**: (eg. output of `rustc -V`)

```sh
$ rustc -V
rustc 1.68.0-nightly (333ee6c46 2023-01-18)
```

## Repro

1. With an empty directory containing the file `main.rs`:

```rs
1 fn main() {
2     let a = "";
3     let b = "";
4 }
5 
```

2. Code fold so that it looks like this:

```rs
1 fn main() { ...
5 
```

3. Reload the Window (<kbd>Ctrl+R</kbd> / `Developer: Reload Window`)

Observe that the code has been unfolded (to what shows in step 1). Without this extension, it properly does not unfold.

**Comment by lnicola** [comment]
Yeah, can you try in another language (C++, Python) with a corresponding extension installed?

**Comment by hyperupcall** [comment]
I performed the same test with both `ms-vscode.cpptools` and `ms-python.python` separately. I could not reproduce the issue - it is only available on with `rust-lang.rust-analyzer`.

The behavior seems inconsistent too. I code-folded a codepath for `match`, and it persisted. But after code-folding a function, and refreshing, code-folding for that `match` codepath no longer persisted.

And, after reloading the browser window, there is always a small delay until the previously-folded code automatically unfolds. That leads me to believe that there is some extension causing this - and the issue goes away after disabling this Rust extension.

**Comment by lnicola** [comment]
@hyperupcall mind saying whether you solved it and how?

**Comment by hyperupcall** [comment]
I have not solved it
