### ISSUE TITLE
`#[tracing::instrument]` breaks refactor-rename and usages, especially on functions with a doc comment

### ISSUE THREAD

**Issue by YaLTeR** [rust-lang/rust-analyzer#14060]
Given this test case with `cargo add tracing`:
```rust
#[tracing::instrument]
fn foo() {
    let a = 123;
    let _ = a + 1;
}

/// This comment breaks it!
#[tracing::instrument]
fn foo_comment() {
    let a = 123;
    let _ = a + 1;
}

struct S;
impl S {
    #[tracing::instrument]
    fn foo_impl() {
        let a = 123;
        let _ = a + 1;
    }
}

fn main() {
    foo();
    foo_comment();
    S::foo_impl();
}
```

Refactor-renaming `a` (from either the declaration or the use) renames only the declaration site, leaving the use unchanged.

Probably relevant: when the cursor is on either of the `a`s, the declaration is highlighted, but the use is not. Going-to-definition from the use works fine, find-usages does not see the use.

Commenting out `#[tracing::instrument]` fixes those issues.

Adding this to the config:
```json
"rust-analyzer.procMacro.ignored": {
    "tracing-attributes": ["instrument"],
},
```
fixes those issues on `foo` and `foo_impl` **but not on `foo_comment`**, and also for some reason does not fix them on `foo_impl` in an actual crate I'm working on.

Screenshot examples, note how the use is highlighted in `foo` and `foo_impl` but not in `foo_comment`:

![Screenshot from 2023-01-30 13-34-44](https://user-images.githubusercontent.com/1794388/215600211-ed55f19b-0ed9-4cf2-8173-a8380fe55a59.png)

![Screenshot from 2023-01-30 13-32-22](https://user-images.githubusercontent.com/1794388/215599831-798c8134-3f69-4305-b5f8-ec1ab2b6cb51.png)

Adding this to config:
```json
"rust-analyzer.procMacro.attributes.enable": false,
```
fixes those issues on all three, but for some reason straight up removes all rust-analyzer functionality on `foo_impl` in an actual crate I'm working on. I don't know what the difference is from this test case, I couldn't reproduce it there. :/

**rust-analyzer version**: 0.3.1386-standalone, has been an issue for a while though

**rustc version**: rustc 1.67.0 (fc594f156 2023-01-24)

**Comment by Veykril** [comment]
This got fixed by the token map rewrite
