### ISSUE TITLE
Unnecessary hint (deref + ref)

### ISSUE THREAD

**Issue by Antosser** [rust-lang/rust-analyzer#14076]
**rust-analyzer version**: 0.3.1386-standalone

**rustc version**: rustc 1.65.0 (897e37553 2022-11-02)

![image](https://user-images.githubusercontent.com/71790328/216167167-cc999bda-910b-41c2-8e41-572db39198a7.png)
In this code rust-analyzer for some reason dereferences the right-hand side and references it again which does absolutely nothing.  
  
![image](https://user-images.githubusercontent.com/71790328/216167488-59d26f02-56d5-4221-9c69-cffdca50ce29.png)
It doesn't do the same thing if I don't specify the type.

**Comment by Veykril** [comment]
This works as intended with type adjustment hints enabled. While this may look like a no-op, this reborrow is actually required to make the following snippet work.
```rust
fn main() {
    let mut num = 32_u32;

    let a = &mut num;
    // let b = a; // replacing the line below with this one will cause a compile error, as it won't force a reborrow
    let b: &mut _ = a;
    *b += 1;
    *a += 1;
}
```

**Comment by Antosser** [comment]
Wdym this reborrow is required? Isn't a hint just a hint that doesn't make any actual changes to the code? I don't understand your point

**Comment by lnicola** [comment]
The dereferencing and referencing again you see in the hint is something the compiler does behind the scenes. It may appear unnecessary, but it's still needed in some cases, and the compiler still does it.

**Comment by Veykril** [comment]
These type adjustment hints show what the compiler does behind the scenes

**Comment by Antosser** [comment]
Alright. I understand that Rust just does that for itself, but the hints are for humans and that hint doesn't add anything useful

**Comment by lnicola** [comment]
It does, it shows there's a weird reborrow thing happening there. These are disabled by default for a reason, most users won be concerned with reborrows and coercions.

**Comment by Antosser** [comment]
For those who read this, this line disables these hints
```json
"rust-analyzer.inlayHints.reborrowHints.enable": "never"
```

**Comment by Veykril** [comment]
Note that reborrow/adjustment hints are disabled by default so you don't need to set that at all. (if that's not the case then that's a bug)
