### ISSUE TITLE
Better links in hover docs

### ISSUE THREAD

**Issue by SyedFasiuddin** [rust-lang/rust-analyzer#14086]
When I hover over some method, struct, module etc I get the following (taking `env` module as example)
```
std
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
mod env
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Inspection and manipulation of the process's environment.

This module contains functions to inspect various aspects such as
environment variables, process arguments, the current directory, and various
other important directories.

There are several functions and structs in this module that have a
counterpart ending in `os`. Those ending in `os` will return an [`OsString`](https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsString.html)
and those without will return a [`String`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html).
```

What I would like to have is this: The links for the references get out of the way so that horizontal space efficiently utilized and it becomes easier to read the docs and look at the links only when needed.
```
std
──────────────────────────────────────────────────────────────────────────────────
mod env
──────────────────────────────────────────────────────────────────────────────────
Inspection and manipulation of the process's environment.

This module contains functions to inspect various aspects such as
environment variables, process arguments, the current directory, and various
other important directories.

There are several functions and structs in this module that have a
counterpart ending in `os`. Those ending in `os` will return an [`OsString`](1)
and those without will return a [`String`](2)
──────────────────────────────────────────────────────────────────────────────────
References:
1: https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsString.html
2: https://doc.rust-lang.org/nightly/alloc/string/struct.String.html
```

**Comment by bjorn3** [comment]
Rust-analyzer sends markdown to the editor except if the editor indicates that it prefers plain text, in which case it strips all markdown. It seems your editor doesn't interpret markdown despite indicating that it does. Which editor do you use?

https://github.com/rust-lang/rust-analyzer/blob/3bc33c7e9f041c5aef69a5c33b3d29d19a341ece/crates/ide/src/hover.rs#L100-L102

**Comment by SyedFasiuddin** [comment]
neovim

**Comment by bjorn3** [comment]
Looks like neovim intentionally requests markdown and then shows it in a floating window with the syntax set to markdown: https://github.com/neovim/neovim/blob/69bb145cea56067e6e82ed0a130a51c0d611e540/runtime/lua/vim/lsp/handlers.lua#L444 By default it seems to pass the markdown through `stylize_markdown` which replaces code blocks with highlighted code: https://github.com/neovim/neovim/blob/69bb145cea56067e6e82ed0a130a51c0d611e540/runtime/lua/vim/lsp/util.lua#L1621 There is an open issue for also handling links in a nicer way: https://github.com/neovim/neovim/issues/20246

**Comment by SyedFasiuddin** [comment]
Oh I see, this seems like an issue with how neovim displays the hover docs and not with the rust analyzer or any other language server for that matter. Should I close this issue?

**Comment by SyedFasiuddin** [comment]
The issue is not related to rust analyzer but is related to how neovim handles the hover docs that it receives neovim/neovim#20246
