### ISSUE TITLE
Possible crash in `rust-project.json` project after #14111

### ISSUE THREAD

**Issue by andrewbanchich** [rust-lang/rust-analyzer#14085]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

```
❯ rust-analyzer --version
rust-analyzer 0.0.0 (f1b257f4e 2023-01-27)
```

Installed from the latest commit `3bc33c7e9f041c5aef69a5c33b3d29d19a341ece` in master.

**rustc version**: (eg. output of `rustc -V`)

`rustc 1.67.0 (fc594f156 2023-01-24)`

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

When opening projects in Emacs using `lsp-mode` and `rust-analyzer`, the server starts up, I can see flycheck diagnostics, but after a few seconds I get

`Server rust-analyzer:6427 exited (check corresponding stderr buffer for details). Do you want to restart it? (y or n)`

The `*Messages*` buffer shows:

```
LSP :: Connected to [rust-analyzer:7609/starting REDACTED].
LSP :: rust-analyzer:7609 initialized successfully in folders: (REDACTED)
LSP :: rust-analyzer has exited (abort trap: 6)
user-error: Beginning of history; no preceding item [2 times]
Server rust-analyzer:7609 exited (check corresponding stderr buffer for details). Do you want to restart it? (y or n) n
Invalid preview key: [67108910]
```

`*rust-analyzer::stderr*` shows:

```
Error: Custom { kind: InvalidData, error: Error("unknown variant `ApiVersionCheck`, expected `ListMacros` or `ExpandMacro`", line: 1, column: 18) }

Process rust-analyzer stderr finished
```

The server IO log buffer has a bunch of:

```
[Trace - 06:08:54 PM] Received response 'nil - (17)' in 0ms.
Result: {
  "code": -32800,
  "message": "canceled by client"
}
```

## Context

I did several things to try to figure out what was causing this and found:

- This crash only happens with projects internal to my company. If I pull the `rust-analyzer` repo or any other public Rust repo, everything works without issue. My company uses a custom build tool, so this made me wonder if it was something related to that. However...
- I opened the same internal projects using VS Code and RA and everything worked without issue.
- I opened the internal projects in Helix with RA and RA crashed.

This has been happening since the beginning of the week (probably Monday).

Also, the log

```
Error: Custom { kind: InvalidData, error: Error("unknown variant `ApiVersionCheck`, expected `ListMacros` or `ExpandMacro`", line: 1, column: 18) }
```
only appeared today. Since Monday, the `*rust-analyzer::stderr*` buffer previously showed:

```
Process rust-analyzer stderr finished
```

and no other information.

**Comment by Veykril** [comment]
> This has been happening since the beginning of the week (probably Monday).

If this is the case that error message is irrelevant as that has only been merged today, and that error message is somewhat expected atm.

**Comment by andrewbanchich** [comment]
Yep! Just wanted to provide the exact error I got today.

**Comment by andrewbanchich** [comment]
> I also tried doing a git reset --hard to a commit from several weeks ago, and one to a month ago, and installed those using cargo xtask install --server, but RA still crashed.

I think maybe this crash was caused by something else, so please disregard that.

I went through some older tags and installed each, and noticed that they do make everything work again. `2023-01-16` is the latest tag which works, and `2023-01-23` is what starts exhibiting the crashing behavior.

**Comment by andrewbanchich** [comment]
More specifically, [`daa0138e4c159d5753e41a447201b6191437276e`](https://github.com/rust-lang/rust-analyzer/tree/daa0138e4c159d5753e41a447201b6191437276e) crashes but [`9a6294d7038e7eab00beafdf64ec4aa50a4c66a2`](https://github.com/rust-lang/rust-analyzer/tree/9a6294d7038e7eab00beafdf64ec4aa50a4c66a2) works.

**Comment by lnicola** [comment]
That's strange. Can you also give 1afa032f34db45a7018ced2c1a59798139e95bfc a try?

**Comment by YuanYuYuan** [comment]
I can confirm that this bug disappeared using the latest commit 1d32a7b7c66450c792dafe162b229d40ab6a1cc8.

**Comment by andrewbanchich** [comment]
Just pulled master at `1d32a7b7c66450c792dafe162b229d40ab6a1cc8` and it is still crashing and showing:

```
Error: Custom { kind: InvalidData, error: Error("unknown variant `ApiVersionCheck`, expected `ListMacros` or `ExpandMacro`", line: 1, column: 18) }

Process rust-analyzer stderr finished
```

@lnicola `1afa032f34db45a7018ced2c1a59798139e95bfc` does work for me.
@YuanYuYuan `1d32a7b7c66450c792dafe162b229d40ab6a1cc8` does not work and produces the same errors.

**Comment by Veykril** [comment]
Ah wait, I think I know what might be going on here. Does `lsp-mode` shut down the server if the server prints to stderr? That would explain the behavior here since that error is in fact reported to stderr.

**Comment by flodiebold** [comment]
No, logs go to stderr as well and they're fine, don't they?

**Comment by andrewbanchich** [comment]
> The `unknown variant ApiVersionCheck` message should not appear in [1d32a7b](https://github.com/rust-lang/rust-analyzer/commit/1d32a7b7c66450c792dafe162b229d40ab6a1cc8), as it didn't exist until [6133e27](https://github.com/rust-lang/rust-analyzer/commit/6133e27b836efd04176d9381e1ae02038be01284), so I'm not sure what's supposed to be happening.

GitHub says [`1d32a7b`](https://github.com/rust-lang/rust-analyzer/commit/1d32a7b7c66450c792dafe162b229d40ab6a1cc8) is from yesterday while [`6133e27`](https://github.com/rust-lang/rust-analyzer/commit/6133e27b836efd04176d9381e1ae02038be01284) is from four days ago. Am I misunderstanding something?

**Comment by lnicola** [comment]
@andrewbanchich sorry, I copy-pasted the wrong SHA. I meant daa0138e4c159d5753e41a447201b6191437276e, because you said:

> More specifically, [daa0138e4c159d5753e41a447201b6191437276e](https://github.com/rust-lang/rust-analyzer/tree/daa0138e4c159d5753e41a447201b6191437276e) crashes but [9a6294d7038e7eab00beafdf64ec4aa50a4c66a2](https://github.com/rust-lang/rust-analyzer/tree/9a6294d7038e7eab00beafdf64ec4aa50a4c66a2) works.

**Comment by lnicola** [comment]
@YuanYuYuan the message is fine, but it should be only a cosmetic issue. Is it causing other problems?

**Comment by YuanYuYuan** [comment]
The full story is I originally use the rust-analyzer installed via the package manager. I use Arch Linux and its latest version is 2023-02-06, hence I spot the same error and that's why I reach here. Then I try to install it either from rustup (2023-01-24) or building from git (the latest commit). Now we have confirmed that the error occurred between these [two]( https://github.com/rust-lang/rust-analyzer/issues/14085#issuecomment-1420019881).

To answer your question, I'm using rust-analyzer in Neovim with its built-in LSP. This error doesn't cause any panic. It just complains about some errors. That's my case. Hope this would help. 🙂

**Comment by lnicola** [comment]
It's not real problem, but it might still be annoying in other clients. Can you show a screenshot?

**Comment by lnicola** [comment]
@YuanYuYuan, yeah, if it doesn't show up in NVim, you can safely ignore it.

**Comment by andrewbanchich** [comment]
> @andrewbanchich sorry, I copy-pasted the wrong SHA. I meant [daa0138](https://github.com/rust-lang/rust-analyzer/commit/daa0138e4c159d5753e41a447201b6191437276e), because you said:
> 
> > More specifically, [daa0138e4c159d5753e41a447201b6191437276e](https://github.com/rust-lang/rust-analyzer/tree/daa0138e4c159d5753e41a447201b6191437276e) crashes but [9a6294d7038e7eab00beafdf64ec4aa50a4c66a2](https://github.com/rust-lang/rust-analyzer/tree/9a6294d7038e7eab00beafdf64ec4aa50a4c66a2) works.

@lnicola To clarify, it crashes, but only displays `Process rust-analyzer stderr finished`. It does not display the proc macro error message.

From my initial post:

> This has been happening since the beginning of the week (probably Monday).
> Also, the log

> > Error: Custom { kind: InvalidData, error: Error("unknown variant `ApiVersionCheck`, expected `ListMacros` or `ExpandMacro`", line: 1, column: 18) }

> only appeared today. Since Monday, the *rust-analyzer::stderr* buffer previously showed:

> > Process rust-analyzer stderr finished

> and no other information.

I don't think the crashes are due to the proc macro work.

**Comment by alexmoon** [comment]
I'm seeing the same error in VS code:

rust-analyzer version: 0.3.1394-standalone (0b32b65ca 2023-02-05)
rustc 1.66.1 (90743e729 2023-01-10)

The rust analyzer language server output shows the error immediately upon loading any rust project.

**Comment by lnicola** [comment]
@alexmoon do you have any issues besides that error?

**Comment by alexmoon** [comment]
Yes, I'm not getting any errors reported by rust-analyzer; though it looks like that's only affecting one of my projects so it may be an unrelated issue.

**Comment by lnicola** [comment]
It's unrelated to @andrewbanchich's crash, which is unrelated to the error message in the issue title.

**Comment by andrewbanchich** [comment]
@lnicola Feel free to change title to clarify this.

**Comment by lnicola** [comment]
The error in the issue title should be fixed with https://github.com/rust-lang/rust-analyzer/pull/14111.

The suspected regression from https://github.com/rust-lang/rust-analyzer/pull/14001 reported by @andrewbanchich (which only seems to happen in a private repo, and when using Helix but not VS Code, and involves a `rust-project.json` project) seems harder to diagnose. Can you try to reproduce it in a new project with a similar structure?

**Comment by andrewbanchich** [comment]
> when using Helix but not VS Code

@lnicola This is happening in Emacs, which is my main editor. I only mentioned Helix because I was trying to figure out if there was something wrong with my Emacs config or Emacs' `lsp-mode`. Since it is also happening in Helix, that makes VS Code the odd one out. I would assume that the VS Code extension uses its own `rust-analyzer` installation instead of just looking for it in your PATH (I could be wrong) so my assumption is that this is a bug in RA and that VS Code is just using a different version of RA that doesn't have the bug.

> and involves a `rust-project.json` project

I'm not familiar with that file and don't see it in any of my projects.

**Comment by lnicola** [comment]
> I would assume that the VS Code extension uses its own rust-analyzer installation instead of just looking for it in your PATH (I could be wrong) so my assumption is that this is a bug in RA and that VS Code is just using a different version of RA that doesn't have the bug. Both Emacs and Helix just look for rust-analyzer in your PATH.

We're using the same binaries you can find on GitHub Releases. If you built from a recent commit, it shouldn't matter.

> I'm not familiar with that file and don't see it in any of my projects.

> All of the projects using our internal build tool have the same structure as standard cargo projects.

Ah, then I don't know how that works. `rust-project.json` is mostly an alternative to `Cargo.toml` which RA loads when there's no `Cargo.toml`. Bazel, Buck and friends use it.

**Comment by andrewbanchich** [comment]
I tried `master` again just now and everything is working. Not sure what the issue was. I also upgraded to macOS Ventura, so I'm not sure if that affected anything.
