### ISSUE TITLE
Inlay hint with padding look weird

### ISSUE THREAD

**Issue by NoahELE** [rust-lang/rust-analyzer#14088]
**rust-analyzer version**: 0.3.1386-standalone (f1b257f4e 2023-01-27)

**rustc version**: rustc 1.67.0 (fc594f156 2023-01-24)

**relevant settings**: 
```json
{
  "editor.inlayHints.enabled": "on",
  "editor.inlayHints.padding": true,
}
```

![image](https://user-images.githubusercontent.com/49080986/216769489-b2801bcc-b4ae-4cf3-b4ee-ea4fcaa36344.png)

The inlay type hint for `String` has no round padding on right side, while the `i32` type hint looks normal.

**Comment by Veykril** [comment]
that looks like a VSCode rendering bug, not something rust-analyzer is responsible for.
