### ISSUE TITLE
Folding region markers in language-configuration.json aren't the ones used by the server

### ISSUE THREAD

**Issue by MariaSolOs** [rust-lang/rust-analyzer#14089]
**rust-analyzer version**: 0.3.1386-standalone (f1b257f4e 2023-01-27)

**rustc version**: rustc 1.69.0-nightly (c8e6a9e8b 2023-01-23)

So this might be a feature request, but there's still a buggy mismatch.

The [markers given in `language-configuration.json`](https://github.com/rust-lang/rust-analyzer/blob/3bc33c7e9f041c5aef69a5c33b3d29d19a341ece/editors/code/language-configuration.json#L36-L40) say that regions prefixed with something like `//      #region`
should have a folding range, but the server actually only allows `// region:`:
- https://github.com/rust-lang/rust-analyzer/blob/3bc33c7e9f041c5aef69a5c33b3d29d19a341ece/crates/ide/src/folding_ranges.rs#L11-L12
- https://github.com/rust-lang/rust-analyzer/blob/3bc33c7e9f041c5aef69a5c33b3d29d19a341ece/crates/ide/src/file_structure.rs#L192

So either the markers in `language-configuration.json` should truly say what the server supports, or the server should be more flexible regarding this prefix.

**Comment by Veykril** [comment]
Are these even used at all if the language server emits folding ranges itself? I would assume not (but yes we should still unify the syntax here by adjusting the `language-configuration.json`)

**Comment by MariaSolOs** [comment]
@Veykril based on what the [VS Code docs say](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding), it seems like the result from `textDocument/foldingRange` overrides what the language configuration says.

**Comment by sumbad** [comment]
Hello, is there any plan to support `// #region` syntax on the server?
