### ISSUE TITLE
Unresolved import fix introduces invalid code

### ISSUE THREAD

**Issue by Vannevelj** [rust-lang/rust-analyzer#14113]
I have the following import statement:

```rs
use aws_sdk_s3::{ByteStream, Client, Region};
```

This worked for an older version of the s3 crate but after updating the type is moved. The quick fix says

> consider importing this struct instead: `aws_sdk_s3::types::ByteStream;

When applied, it results in this invalid code:

```rs
use aws_sdk_s3::{aws_sdk_s3::types::ByteStream;
, Client, Region};
```

**rust-analyzer version**: 0.3.1394-standalone (0b32b65ca 2023-02-05)

**rustc version**: rustc 1.67.1 (d5a82bbd2 2023-02-07)

**Comment by Veykril** [comment]
this looks like you tried applying a quickfix from a rustc diagnostic after having modified the file without resaving again.

**Comment by Vannevelj** [comment]
Ah I didn't realise it was rustc instead of RA, I'll close the defect then. I don't think it's related to an unsaved file though, I have the same issue after saving all files and reopening VSCode
