### ISSUE TITLE
panics upon encountering 🥺

### ISSUE THREAD

**Issue by jjl** [rust-lang/rust-analyzer#14115]
sidenote: i spent several minutes wondering why rust-analyzer was so old, since it reports 2021. i upgraded it and the output changed and it still reports 2021. that's pretty unhelpful.

Repro:

```
fn main() {
    // 🥺
    println!("Hello, world!");
}
```

from a saved file, adding a space to the line with the emoji is enough to trigger it.

```
Panic context:
> 
version: a274ae384 2021-06-14 dev
notification: textDocument/didChange

thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/alloc/src/string.rs:1690:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/panicking.rs:50:5
   3: alloc::string::String::replace_range
   4: rust_analyzer::lsp_utils::apply_document_changes
   5: core::ops::function::FnOnce::call_once
   6: rust_analyzer::dispatch::NotificationDispatcher::on
   7: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
   8: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   9: rust_analyzer::main_loop::main_loop
  10: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process rust-analyzer stderr finished

```

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

**rustc version**: (eg. output of `rustc -V`)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**Comment by lnicola** [comment]
How did you install it? Which editor, OS, distro, what does `which rust-analyzer` show, which settings do you have?

**Comment by jjl** [comment]
i see we're at the "it's not a bug, you're holding it wrong" stage already, what a speedrun.

since i was just linked to https://github.com/rust-lang/rust-analyzer/issues/13709 where you show a similarly dismissive attitude, i'm not going to play today. have fun being unable to deal with emoji.

**Comment by lnicola** [comment]
#13709 is specific to `lsp-mode`, which I don't know if you're using. We've had other issues like this one, but if yours is saying it's from 2021, it's most likely from 2021, so you should look into where you're running the binary from. I'm sorry if this seems dismissive, but it wasn't my intention.

**Comment by jjl** [comment]
"i upgraded it and the output changed and it still reports 2021" is the relevant part of the first message.

i did obviously look into why it appeared to be so and i've concluded that rust-analyzer doesn't update its version much because it's in the rustup-managed place and doing a rustup update updated it and then the output format changed so it clearly wasn't the old version.

while i don't deny there might be a bug in lsp-mode (yes, i'm using it), crashing immediately is not actually very helpful.

**Comment by lnicola** [comment]
> i did obviously look into why it appeared to be so and i've concluded that rust-analyzer doesn't update its version much because it's in the rustup-managed place

I'm not even sure we had RA in `rustup` in 2021, can you paste the output of `rustc -Vv` and `which rust-analyzer`?

> while i don't deny there might be a bug in lsp-mode (yes, i'm using it), crashing immediately is not actually very helpful.

We can't do anything else. The client is practically corrupting our view of the file. We can't guess that it's happening. Maybe you can try the change in https://github.com/emacs-lsp/lsp-mode/issues/3344#issuecomment-1320677622 (I don't know if you can edit the installed version) with an _up-to-date_ RA and report there if it works. It might improve the chances of a fix being merged.

**Comment by jjl** [comment]
```
❯ rustc -Vv
rustc 1.69.0-nightly (8996ea93b 2023-02-09)
binary: rustc
commit-hash: 8996ea93b6e554148c4286e62b613f12a3ee505c
commit-date: 2023-02-09
host: x86_64-unknown-linux-musl
release: 1.69.0-nightly
LLVM version: 15.0.7

❯ which rust-analyzer
/home/james/.cargo/bin/rust-analyzer
```

i will try the lsp-mode fix, but there really has to be a better way than just panicking. it's a comment, who cares if you have the wrong data for it? just ignore the update or move it to the nearest character boundary or literally anything but panic. i grant that will not fix all of the cases (and could for example leave documentation showing as stale) but sorry, it's 2023 and you should generally expect bad input and deal with it as best you can rather than just give up and dismiss anyone opening bugs because you gave up.

and uh, completely ignoring all of that, the error message could have been *waaaaay* more helpful, maybe something like "your lsp client has sent us an invalid edit that seems to occur at a non-character boundary (maybe you have used emoji and it doesn't understand them?)" . i would have loved to have gotten a warning about that. i don't know if there's a warning mechanism in lsp? could you have emitted something that lsp-mode might have flagged to me with a helpful error rather than having to go find the error buffer for the crash?

**Comment by lnicola** [comment]
> `/home/james/.cargo/bin/rust-analyzer`

That might be a source build (e.g. `cargo xtask install --server`). `rustup` doesn't have a `rust-analyzer` stub in its latest version. `rustup which rust-analyzer` will show you the real path, but that will still be older than our binaries on GitHub.

> it's a comment, who cares if you have the wrong data for it?

Take a look at [this](https://github.com/rust-lang/rust-analyzer/issues/12234) (genuine) bug report. It's not just emoji, and trying to ignore these updates will cause the errors to accumulate.

> but sorry, it's 2023 and you should generally expect bad input

We deal with it by reporting the error instead of corrupting the state and crashing 5 minutes later in a much more obscure way. There is no "just ignore it" or "don't respond to the request but keep working" or "VS Code is buggy because it handles with restarting the server just fine, but lsp-mode isn't buggy even though it doesn't conform to the LSP".

**Comment by jjl** [comment]
> We deal with it by reporting the error

No, you deal with it by reporting *an* error.  Sod it, i'm not playing any more

**Comment by lnicola** [comment]
If you want to see this fixed, consider helping by testing one or both of these fixes:

 - https://github.com/emacs-lsp/lsp-mode/issues/3344#issuecomment-1320677622
 - https://github.com/yyoncho/lsp-mode/commit/aac9b6a10611ce9fcb4c9fe272f2835f0b6bb210

I don't understand why you're upset at RA for crashing when the client is sending non-obvious bogus data, but you don't mind `lsp-mode` causing it.

**Comment by jjl** [comment]
i'm not upset at RA, i said it was unhelpful. i'm upset at how you've handled this thread, being dismissive throughout, selectively quoting me and ignoring half of what i've written. if you don't see why people might reasonably be upset by that, i can't help you.

**Comment by Veykril** [comment]
You were asked proper questions such that we can help you figure out why your rust-analyzer build is outdated and *you* were the one immediately dismissing those as unnecessary, yet you feel the need to be this disrespectful nevertheless. Let's lock this as you don't seem to be interested in getting any help.
