### ISSUE TITLE
Diagnostic helps should map to available code actions

### ISSUE THREAD

**Issue by MariaSolOs** [rust-lang/rust-analyzer#14121]
Consider the following code:
```rust
fn main() {
    let v = vec![0, 3, 1];
    if v.is_sorted() {
        println!("v is sorted!");
    }
}
```

Because the code uses the nightly-only `is_sorted` API, the following diagnostic appears:
```
error[E0658]: use of unstable library feature 'is_sorted': new API
  --> sorted/tests/progress.rs:16:10
   |
16 |     if v.is_sorted() {
   |          ^^^^^^^^^
   |
   = note: see issue #53485 <https://github.com/rust-lang/rust/issues/53485> for more information
   = help: add `#![feature(is_sorted)]` to the crate attributes to enable
```

Despite the help note being a very likely thing that the user would like to do next, it isn't included as a possible code action (at least in VS Code, IDK about other editors):
<img width="461" alt="image" src="https://user-images.githubusercontent.com/62502207/218237952-55da6857-c191-486f-8826-d06e6d9eabf1.png">

I'm not sure if this is a bug or a feature request, but nonetheless I think that such "help" should be listed as a possible quick fix.

**Comment by flodiebold** [comment]
This depends on rustc providing the change as a structured fix; presumably it's not doing that in this case.

**Comment by lnicola** [comment]
We offer quick fixes for diagnostics marked as machine-applicable. I think the right solution here would be for us to recognize the unstable features. Until then, the compiler should also offer a fix to insert the attribute at the top of the file.

But I don't think we should put random help notes in the quick fix menu. They would be mostly useless anyway: the note doesn't say where that attribute should be added, and you don't want it where at the error location.
