### ISSUE TITLE
Crate badges are shown as broken links when hovering

### ISSUE THREAD

**Issue by MariaSolOs** [rust-lang/rust-analyzer#14129]
**rust-analyzer version**: 0.3.1394-standalone (0b32b65ca 2023-02-05)

**rustc version**: 1.69.0-nightly (c8e6a9e8b 2023-01-23)

Several popular crates include badges in their library descriptions (e.g. [`quote`](https://docs.rs/quote/1.0.23/quote/index.html)):
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/62502207/218274576-eebd5637-bae5-498f-b0fd-7c49edc7a91d.png">

However, these show up as broken links when hovering over the path in VS Code:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/62502207/218274529-467c160f-417c-486d-bd67-55c326d46f2f.png">

I'm not completely sure if this is their bug or RA's, but it seems like it is unclear what the right MD syntax for displaying these would be.

**Comment by lnicola** [comment]
```json
    "contents": {
        "kind": "markdown",
        "value": "\n```rust\nextern crate semver\n```\n\n---\n\n[![github](https://img.shields.io/badge/github-8da0cb?style=for-the-badge&labelColor=555555&logo=github)](https://github.com/dtolnay/semver) [![crates-io](https://img.shields.io/badge/crates.io-fc8d62?style=for-the-badge&labelColor=555555&logo=rust)](https://crates.io/crates/semver) [![docs-rs](https://img.shields.io/badge/docs.rs-66c2a5?style=for-the-badge&labelColor=555555&logoColor=white&logo=data:image/svg+xml;base64,PHN2ZyByb2xlPSJpbWciIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDUxMiA1MTIiPjxwYXRoIGZpbGw9IiNmNWY1ZjUiIGQ9Ik00ODguNiAyNTAuMkwzOTIgMjE0VjEwNS41YzAtMTUtOS4zLTI4LjQtMjMuNC0zMy43bC0xMDAtMzcuNWMtOC4xLTMuMS0xNy4xLTMuMS0yNS4zIDBsLTEwMCAzNy41Yy0xNC4xIDUuMy0yMy40IDE4LjctMjMuNCAzMy43VjIxNGwtOTYuNiAzNi4yQzkuMyAyNTUuNSAwIDI2OC45IDAgMjgzLjlWMzk0YzAgMTMuNiA3LjcgMjYuMSAxOS45IDMyLjJsMTAwIDUwYzEwLjEgNS4xIDIyLjEgNS4xIDMyLjIgMGwxMDMuOS01MiAxMDMuOSA1MmMxMC4xIDUuMSAyMi4xIDUuMSAzMi4yIDBsMTAwLTUwYzEyLjItNi4xIDE5LjktMTguNiAxOS45LTMyLjJWMjgzLjljMC0xNS05LjMtMjguNC0yMy40LTMzLjd6TTM1OCAyMTQuOGwtODUgMzEuOXYtNjguMmw4NS0zN3Y3My4zek0xNTQgMTA0LjFsMTAyLTM4LjIgMTAyIDM4LjJ2LjZsLTEwMiA0MS40LTEwMi00MS40di0uNnptODQgMjkxLjFsLTg1IDQyLjV2LTc5LjFsODUtMzguOHY3NS40em0wLTExMmwtMTAyIDQxLjQtMTAyLTQxLjR2LS42bDEwMi0zOC4yIDEwMiAzOC4ydi42em0yNDAgMTEybC04NSA0Mi41di03OS4xbDg1LTM4Ljh2NzUuNHptMC0xMTJsLTEwMiA0MS40LTEwMi00MS40di0uNmwxMDItMzguMiAxMDIgMzguMnYuNnoiPjwvcGF0aD48L3N2Zz4K)](https://docs.rs/semver)\n\n<br>\n\nA parser and evaluator for Cargo's flavor of Semantic Versioning.\n\nSemantic Versioning (see <https://semver.org>) is a guideline for how\nversion numbers are assigned and incremented. It is widely followed within\nthe Cargo/crates.io ecosystem for Rust.\n\n<br>\n\n# Example\n\n```rust\nuse semver::{BuildMetadata, Prerelease, Version, VersionReq};\n\nfn main() {\n    let req = VersionReq::parse(\">=1.2.3, <1.8.0\").unwrap();\n\n    // Check whether this requirement matches version 1.2.3-alpha.1 (no)\n    let version = Version {\n        major: 1,\n        minor: 2,\n        patch: 3,\n        pre: Prerelease::new(\"alpha.1\").unwrap(),\n        build: BuildMetadata::EMPTY,\n    };\n    assert!(!req.matches(&version));\n\n    // Check whether it matches 1.3.0 (yes it does)\n    let version = Version::parse(\"1.3.0\").unwrap();\n    assert!(req.matches(&version));\n}\n```\n\n<br><br>\n\n# Scope of this crate\n\nBesides Cargo, several other package ecosystems and package managers for\nother languages also use SemVer: RubyGems/Bundler for Ruby, npm for\nJavaScript, Composer for PHP, CocoaPods for Objective-C...\n\nThe `semver` crate is specifically intended to implement Cargo's\ninterpretation of Semantic Versioning.\n\nWhere the various tools differ in their interpretation or implementation of\nthe spec, this crate follows the implementation choices made by Cargo. If\nyou are operating on version numbers from some other package ecosystem, you\nwill want to use a different semver library which is appropriate to that\necosystem.\n\nThe extent of Cargo's SemVer support is documented in the *[Specifying\nDependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html)* chapter of the Cargo reference."
    },
    "range": {
        "start": {
            "line": 0,
            "character": 13
        },
        "end": {
            "line": 0,
            "character": 19
        }
    }
}
```

**Comment by lnicola** [comment]
I guess like Code doesn't render images in Markdown. It does support HTML tags and we could replace them, but :shrug:.

**Comment by MariaSolOs** [comment]
@lnicola I can try fixing this. Do you have any recommendations of which code I should tweak :) ?

**Comment by lnicola** [comment]
No, not really. The entry point should be https://github.com/rust-lang/rust-analyzer/blob/c29a00457a45238c4195481f02d748a74d8dfb26/crates/ide/src/hover.rs#L87. You can see we use a Markdown parser to keep only the text if there's no client support. We also use it to rewrite the links in https://github.com/rust-lang/rust-analyzer/blob/c29a00457a45238c4195481f02d748a74d8dfb26/crates/ide/src/hover.rs#L256.

**Comment by Veykril** [comment]
We should probably do this transformation in the VSCode extension code though I think? https://github.com/rust-lang/rust-analyzer/blob/646f97385709fab31db2f10661125c0bbbda6b7c/editors/code/src/client.ts#L153-L187

**Comment by lnicola** [comment]
Yeah, that makes sense if we're working around a Code bug. I wonder what other editors do.

**Comment by MariaSolOs** [comment]
Yeah... Now I'm wondering if this should be a VS Code change, since [their docs](https://code.visualstudio.com/api/references/vscode-api#MarkdownString) say that they support CommonMark and this is a valid MD image.

I'll create an issue there. If it regarded as not a bug/backlogged, I can work on a workaround for RA.

**Comment by MariaSolOs** [comment]
Alright so for security reasons, arbitrary SVGs aren't showed on hover in VS Code. It sounds like switching to PNGs should work, but then that would be up to each doc writer and not RA.
Thoughts?

**Comment by HKalbasi** [comment]
Couldn't vscode whitelist a safe subset of svg?

**Comment by lnicola** [comment]
I'm inclined to chalk this up as a client issue. We give it well-formed Markdown, it's up to the client to choose whether to render it.

**Comment by MariaSolOs** [comment]
@lnicola Agreed. I'll close this then (huge *sigh* though :/ ).
