### ISSUE TITLE
Rename refactoring produce syntactically incorrect code

### ISSUE THREAD

**Issue by bazhenov** [rust-lang/rust-analyzer#14137]
**rust-analyzer version**: rust-analyzer version: 0.3.1394-standalone (0b32b65ca 2023-02-05)

**rustc version**: rustc 1.67.1 (d5a82bbd2 2023-02-07)

**relevant settings**: N/A

Consider following code:

```rust
struct Value {
    inner: u8,
}

#[tokio::main]
async fn main() {
    let value = Value { inner: 1 };
    let Value { inner } = value;
    println!("{}", inner);
}
```

If I'm trying to rename `inner` local variable on last line (`println!("{}", inner);`) I get broken code:

```rust
struct Value {
    inner: u8,
}

#[tokio::main]
async fninner: value() {
    let value = Value { inner: 1 };
    let Value { inner } = value;
    println!("{}", inner);
}
```

This happens wherever I use struct unpack syntax or `match`-statement. In both cases rust-analyzer reports incorrect `TextEdit` offsets back to IDE (vscode).

The problem seems to be related to #9403 and #13388 because manifest itself only in presence of `#[tokio::main]` or `#[tokio::test]` proc macro.

**Comment by bazhenov** [comment]
If surrounding function _is not annotated_ with `[tokio::main]` everything work correctly and `ide_db::rename::rename_reference()` creates two `TextEdit`s – one from `source_edit_from_references()` another one from `source_edit_from_def()`. It makes sense. When renaming such a trivial case we need to change two places in sources files.

But in presence of `[tokio::main]` some basic mechanism is broken. Like for example rust-analyzer can't rename even local variable in following code:

```rust
#[tokio::main]
async fn main() {
    let f = 2;
    println!("{}", f);
}
```

In this example when trying rename  variable `f`, rust-analyzer correctly rename definition (`source_edit_from_def()`), but unable to find reference to a variables (`source_edit_from_references()`). This line produce empty `usages` – 

https://github.com/rust-lang/rust-analyzer/blob/a6603fc21d50b3386a488c96225b2d1fd492e533/crates/ide-db/src/rename.rs#L288

**Comment by Veykril** [comment]
This is a known bug with proc-macros for r-a. r-a currently fails to properly handle macros re-using spans.

**Comment by bazhenov** [comment]
I wonder if there is a practical way it can be solved in general case? Proc macro can rewrite a `TokenStream` in any way. But r-a should somehow map tokens in the source file to tokens after proc-macro expansion. Is this even possible?

**Comment by Veykril** [comment]
This will be fixed once https://github.com/rust-lang/rust-analyzer/issues/9403 is implemented.
For now you can set
```json
    "rust-analyzer.procMacro.ignored": {
        "tokio-macros": [
            "main"
        ]
    },
```
in your settings to get around this mostly

**Comment by Veykril** [comment]
This works now
