### ISSUE TITLE
VSCode: Error: `rustup could not choose a version of cargo to run`

### ISSUE THREAD

**Issue by hasezoey** [rust-lang/rust-analyzer#14139]
I had upgraded to vscode 1.75.1 (from 1.74.3) and now `rust-analyer` (the vscode extension) seems to not be able to run rust anymore

Full Error (from `Rust Analyzer Language Server`):
```txt
[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to load workspace: "cargo" "--version" failed, exit status: 1
stderr:
error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
```

when manually running the commands:
```sh
$ rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

$ cargo --version
cargo 1.67.1 (8ecd4f20a 2023-01-10)
```

the toolchain was not changed between the update

rust-analyzer (vscode) 0.3.1402
vscode: 1.75.1 (does not happen on 1.74.3)

vscode config (also same as before):
```json
{
	"[rust]": {
		"editor.defaultFormatter": "rust-lang.rust-analyzer"
	},
	"rust-analyzer.debug.openDebugPane": true,
	"rust-analyzer.rustfmt.extraArgs": [
		"+nightly"
	]
}
```

Note: downgrading to vscode 1.74.3 again will not error

**Comment by bjorn3** [comment]
What does `rustup show` output?

**Comment by hasezoey** [comment]
```sh
$ rustup show 
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/hasezoey/.local/rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```

**Comment by bjorn3** [comment]
Are you running vscode in flatpak or some other sandbox? There shouldn't be any difference between `cargo --version` as invoked by rust-analyzer and as invoked manually by you.

**Comment by hasezoey** [comment]
> Are you running vscode in flatpak or some other sandbox?

installed via pacman from the AUR (`https://aur.archlinux.org/visual-studio-code-bin.git`)

like i said, rust-analyzer works in vscode 1.74.3, but not in 1.75.1

**Comment by hasezoey** [comment]
> And do you have a rust-toolchain[.toml] file in the current project or somewhere above?

no i dont

> Does it work if you run Code form a terminal?

weirdly, yes it does, when run via `code` or `code .`, but not when run through KDE's application menu, which has the following settings:
![kde_code_app](https://user-images.githubusercontent.com/10911626/218450211-d3437ff4-ac3a-4773-9d6e-faf2b398e4cb.png)
(same settings as in 1.74.3)

Additional info, in the cli the following environment variables are present:
```txt
RUSTUP_HOME=/home/hasezoey/.local/rustup
CARGO_HOME=/home/hasezoey/.local/cargo
```
but it worked without in vscode 1.74.3

**Comment by lnicola** [comment]
Yeah, you'll want to set those variables in a proper way. I like to use `~/.config/environment.d`.

**Comment by hasezoey** [comment]
creating a file that sources cargo's env for the current environment worked and fixed the issue, it is just weird that it is suddenly required in the upgrade from 1.74.3 to 1.75.1

the following are the commands i used:
```sh
$ cat - <<EOF | tee ~/.config/plasma-workspace/env/cargo_rust.sh
#!/bin/sh

source ~/.local/cargo/env
EOF
$ chmod +x ~/.config/plasma-workspace/env/cargo_rust.sh
```

**Comment by hasezoey** [comment]
actually, may previous comment did not fix the issue

**Comment by hasezoey** [comment]
this time for real, the following worked this time with `environment.d`, i dont know why the previous `plasma-workspace/env` did not work for this, whereas it works for other things like firefox, ssh agent, sdl, gtk

```sh
$ cat - <<EOF | tee ~/.config/environment.d/cargo_rust.conf
RUSTUP_HOME=$HOME/.local/rustup
CARGO_HOME=$HOME/.local/cargo
EOF
```
(and then reload systemd, by either rebooting or logging out, killing `systemd --user` and then logging back in)

**Comment by lnicola** [comment]
I don't know how you were setting them before, but this has nothing to do with RA. Maybe the VS Code launcher script changed, or something.

**Comment by GDYendell** [comment]
I had a similar issue and the reason was that I am using antidot to tidy up dotfiles in my home directory, which moves the rustup config from `$HOME/.rustup` - this is the default I believe - to `$XDG_DATA_HOME/rustup`. If I moved it back then rust-analyser started working again.

The cause of the problem was I was running `antidot init` in `.bashrc` to configure the moved config files, but the same thing was not taking affect for vscode - unless it was run from a terminal where it was already set.

The fix was to move `antidot init` from `.bashrc` to `.profile`.

Also not sure what changed as this has worked until recently.

**Comment by hasezoey** [comment]
@GDYendell maybe you need to set / modify the `RUSTUP_HOME` (and or `CARGO_HOME`) environment variable?
mine is set to `/home/hasezoey/.local/rustup` and works perfectly without extra configuration

**Comment by GDYendell** [comment]
Yeah you are correct, sorry I wasn't clear. `antidot init` is what sets all the environment variables for things it has moved, it just wasn't being done early enough for it to take affect for vscode. It is now working correctly :)
