### ISSUE TITLE
Freeze when a procedural macro uses println!()

### ISSUE THREAD

**Issue by ob** [rust-lang/rust-analyzer#14136]
If a procedural macro uses `println!()` (which I know it shouldn't do), I get a complete lockup of VSCode where it won't take keyboard input anymore and I have to "Reload Window" to fix it. 

It happens when editing the code that calls the procedural macro that calls `println!()` so in the [sample repo](https://github.com/ob/rust-sample) it happens when you change the call to `sample_macro!()`, for instance putting the `"Hello world!"` string in a new line.

In the bottom status bar, `cargo check` seems to be spinning infinitely. Note that _before_ editing the macro call and causing the freeze, `rust-analyzer` and everything else appears to be running normally.

This is on macOS 13.2 (22D49).

**repro repo**: https://github.com/ob/rust-sample

**rust-analyzer version**: rust-analyzer version: 0.4.1399-standalone (8011029d3 2023-02-10)

**rustc version**: rustc 1.67.0 (fc594f156 2023-01-24)

**relevant settings**: no env vars, fairly standard rust setup via rustup

**Comment by Veykril** [comment]
No hands for me with this
