### ISSUE TITLE
False positive error can't find crate for `test` despite check.allTargets unset

### ISSUE THREAD

**Issue by ekliptik** [rust-lang/rust-analyzer#14155]
`"rust-analyzer.check.allTargets": false` is insufficient to avoid ``error[E0463]: can't find crate for `test` `` in a no_std project with a custom build of the Rust toolchain.

+ `rust-analyzer 1.67.0-dev (72d0f607166 2023-02-08)`
+ same version `cargo` and `rustc`
+ VS Code extension installed from official version `rust-lang.rust-analyzer-0.4.1404@linux-x64.vsix`

Please suggest additional information that I could provide. `cargo check` works just fine with this custom toolchain, so the extension must be calling `cargo test` or something similar, which is why I tried setting `rust-analyzer.check.allTargets` to `false` as per #11982

**Comment by tgiannak** [comment]
I ran into the same problem in a no_std project. Searching for `--all-targets` shows https://github.com/rust-lang/rust-analyzer/blob/f1e51afa450ecf352c1f01fc5a5b6d10792e3779/crates/rust-analyzer/src/handlers.rs#L748-L753 in the code which includes `--all-targets` in an invocation to `cargo check` without consulting the setting.

The code for FlyCheck does respect the setting: https://github.com/rust-lang/rust-analyzer/blob/f1e51afa450ecf352c1f01fc5a5b6d10792e3779/crates/flycheck/src/lib.rs#L327-L329

This spot also doesn't respect the setting, but I can't tell if it is related: https://github.com/rust-lang/rust-analyzer/blob/f1e51afa450ecf352c1f01fc5a5b6d10792e3779/crates/project-model/src/build_scripts.rs#L75
