### ISSUE TITLE
rust-analyzer failed to load workspace! 

### ISSUE THREAD

**Issue by LPL-hacker** [rust-lang/rust-analyzer#14163]
After I installed the plug-in, I opened my project path, but the following error occurred and rust was unable to jump

`rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol/Cargo.toml, Some(Version { major: 1, minor: 64, patch: 0 }): Failed to run `"cargo" "metadata" "--format-version" "1" "--manifest-path" "/home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol/Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error: error: failed to write /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol/Cargo.lock Caused by: failed to open: /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol/Cargo.lock Caused by: Permission denied (os error 13)`
![WX20230216-114006@2x](https://user-images.githubusercontent.com/28689058/219262623-8d0c3675-2ca5-4c63-96c3-a2e8ee54b343.png)

**Comment by LPL-hacker** [comment]
The ide I use is vscode

**Comment by lnicola** [comment]
> Caused by: failed to open: /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol/Cargo.lock
> Caused by: Permission denied (os error 13)

Do you have some unusual setup (sandbox or wrong permissions on that file or an ancestor)?

**Comment by LPL-hacker** [comment]
For example, I was in the /home/lpl/project directory where rust-analyzer is available. I changed the directory to /home/lpl/project-temp and repulled my project code. Errors in rust-analyzer in this directory cannot be jumped.

**Comment by LPL-hacker** [comment]
> > cargo metadata exited with an error: error: failed to write /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol/Cargo.lock
> > Caused by: failed to open: /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol/Cargo.lock
> > Caused by: Permission denied (os error 13)
> 
> Do you have some unusual setup (sandbox or wrong permissions on that file or an ancestor)?

For example, I was in the /home/lpl/project directory where rust-analyzer is available. I changed the directory to /home/lpl/project-temp and repulled my project code. Errors in rust-analyzer in this directory cannot be jumped.

**Comment by lnicola** [comment]
> where rust-analyzer is available

What does this mean, that it's working? It should be "available" (if maybe not working correctly) in any directory, because the Code extension knows where to load it from.

> I changed the directory to /home/lpl/project-temp and repulled my project code.

So it works now? Do you have working completion and hover?

> Errors in rust-analyzer in this directory cannot be jumped.

Why?

**Comment by LPL-hacker** [comment]
> > where rust-analyzer is available
> 
> What does this mean, that it's working? It should be "available" (if maybe not working correctly) in any directory, because the Code extension knows where to load it from.
> 
> > I changed the directory to /home/lpl/project-temp and repulled my project code.
> 
> So it works now? Do you have working completion and hover?
> 
> > Errors in rust-analyzer in this directory cannot be jumped.
> 
> Why?

No, There is no jump in either directory now, but rust-analyzer does not display errors in the original directory, but in the new directory
![WX20230216-151812@2x](https://user-images.githubusercontent.com/28689058/219294920-70befa83-81c2-4cb6-a9bc-7f3fe003d22c.png)

**Comment by lnicola** [comment]
Can you check the permissions on those?

```
$ ls -ld /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol/Cargo.lock /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp /home/smyl/lpl/wingfuzz-tool-protocol /home/smyl/lpl /home/smyl
```

That command is for the original path, you'll need to replace or add `project-temp` is a couple of places.

**Comment by LPL-hacker** [comment]
> Can you check the permissions on those?
> 
> ```
> $ ls -ld /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol/Cargo.lock \
>          /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol \
>          /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp \
>          /home/smyl/lpl/wingfuzz-tool-protocol \
>          /home/smyl/lpl
> ```
> 
> That command is for the original path, you'll need to replace `wingfuzz-tool-protocol` or add `project-temp` in a couple of places.

![WX20230216-152624@2x](https://user-images.githubusercontent.com/28689058/219296535-b3801f68-9c3e-44ec-9466-9f3006aa3c09.png)

**Comment by LPL-hacker** [comment]
> Can you check the permissions on those?
> 
> ```
> $ ls -ld /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol/Cargo.lock \
>          /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol \
>          /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp \
>          /home/smyl/lpl/wingfuzz-tool-protocol \
>          /home/smyl/lpl
> ```
> 
> That command is for the original path, you'll need to replace `wingfuzz-tool-protocol` or add `project-temp` in a couple of places.

So far it seems that rust-analyzer is unable to open the cargo.lock file with root permission, so how do I solve this problem

**Comment by lnicola** [comment]
Yeah, those are kinda' broken. Usual permissions would be `755 (drwxr-xr-x)` for directories and `644 (-rw-r--r--)` for regular files. You `Cargo.lock` in there is owned by `root` and you can't update it.

You should at least `sudo chown smyl: /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol/Cargo.lock`.

**Comment by LPL-hacker** [comment]
> Yeah, those are kinda' broken. Usual permissions would be `755 (drwxr-xr-x)` for directories and `644 (-rw-r--r--)` for regular files. You `Cargo.lock` in there is owned by `root` and you can't update it.
> 
> You should at least `sudo chown smyl: /home/smyl/lpl/wingfuzz-tool-protocol/wingfuzz-tool-protocol-temp/wingfuzz-tool-protocol/Cargo.lock`.
> 
> I assume you've done a `sudo cargo build` at some point. That's a bad idea and will cause issues, but keep in mind we can't help with those (there are other resources for learning about Unix filesystem permissions).

So far, it is back to normal. Thank you very much for your help
