### ISSUE TITLE
confusing macro expansion for asm!

### ISSUE THREAD

**Issue by sethp** [rust-lang/rust-analyzer#14177]
The ability to recursively expand macros is wonderful, and I find myself using it quite often to "see" what a particular construct is doing. So far, it's been great (it's so useful I often find myself looking for it under the inline context menu and have to remind myself it's in the command palette), but today I ran into this expansion of [a macro from the riscv crate](https://github.com/rust-embedded/riscv/blob/620c5bf225557dce465785571195a5c76a7bfa5a/src/register/mstatus.rs#L212):

![screenshot of an expansion for the read_csr_as! macro with a `loop` block highlighted](https://user-images.githubusercontent.com/241129/219958238-c2352f60-60ed-4d93-a089-d0ec8113ee78.png)

The highlighted loop block in the middle looks like it's the result of expanding [this part of the `read_csr!` macro](https://github.com/rust-embedded/riscv/blob/620c5bf225557dce465785571195a5c76a7bfa5a/src/register/macros.rs#L10
):

```rust
#[cfg(riscv)]
() => {
    let r: usize;
    core::arch::asm!(concat!("csrrs {0}, ", stringify!($csr_number), ", x0"), out(reg) r);
    r
}
```
via this rust-analyzer notion of what `asm!` represents: https://github.com/rust-lang/rust-analyzer/blob/a6603fc21d50b3386a488c96225b2d1fd492e533/crates/hir-expand/src/builtin_fn_macro.rs#L299-L302

The question I was hoping to answer by expanding the macro was approximately "what are the semantics of reading the mstatus register here?", and while `{loop{}};` is a syntactically valid way to spell `!` it is, in this case, shadowing the actual `csrrs` instruction that's populating the `r` local.

From the git history, I infer that this is largely because macro expansion is doing at least triple duty here: in addition to providing me with visibility into the system, it's being used internally both for syntax highlighting and diagnostics (and probably also completion?). I can't speak to the other builtin macros, but for `asm!` (and `global_asm!`) in particular, that would seem to set an extremely high bar for rust-analyzer: in addition to being a full Rust lsp implementation, fully implementing `asm!` would require embedding an architecture-dependent language server implementation for each possible rustc target.

Instead, I think I would have preferred that the expansion handle the `concat!` and `stringify!` but leave the `asm!` and so end up looking something like this:

```rust
let r: usize;
core::arch::asm!("csrrs {0}, 0x300, x0", out(reg) r);
r
```

but, if leaving the macro un-expanded is impossible for Reasons (as I suspect it may be), then I would have still found it less confusing to find something like:

```rust
let r: usize;
{
    ///! expanded from
    ///!     core::arch::asm!(concat!("csrrs {0}, ", stringify!($csr_number), ", x0"), out(reg) r);
    /// internal to rust-analyzer only, this represents `!` (divergence) as a substitute for the above assembly semantics
    loop {}
};
r
```

What do you think?

**rust-analyzer version**: `rust-analyzer version: 0.3.1394-standalone`

**rustc version**: `rustc 1.69.0-nightly (2d14db321 2023-02-15)`

**relevant settings**: N/A

**Comment by Veykril** [comment]
Yes, we should not expand certain builtin macros in the expand view here, notably we should skip expanding all builtins except for `stringify`, `cfg`, `core_panic`, `std_panic`, `concat`, `concat_bytes`, `include`, `include_str`, `include_bytes`, `env` and `option_env`

**Comment by Veykril** [comment]
We should skip the expansion here https://github.com/rust-lang/rust-analyzer/blob/d6d735e6f20ef78b16a79886fe28bd69cf059504/crates/hir/src/semantics.rs#L315-L320 by identifying what the macro file id belongs to, then add a few tests here https://github.com/rust-lang/rust-analyzer/blob/d6d735e6f20ef78b16a79886fe28bd69cf059504/crates/ide/src/expand_macro.rs

**Comment by ishanjain28** [comment]
hi @veykril I would like to work on this but I am a little lost. How do I figure out if a macro is a built in?

In a similar `Macro2Id` object there are calls like `.attrs("rustc_builtin_macro")` to check for this but I couldn't find this attribute on built in macros in the `MacroCall` object. I am not sure how to do this ?

My approach was going to be, 

1. Lookup if a macro is a built in
2. if it is a built in, Do a linear search on a allow list and return None if the macro is not on the allowed list.

**Comment by Veykril** [comment]
If you have a `Macro2Id` you can do `matches!(it.lookup(db.upcast()).expander, MacroExpander::BuiltIn(m) if m.is_asm())` to check it

**Comment by ishanjain28** [comment]
@veykril I don't have `Macro2Id` in this part of the code. I have `MacroCall`. I have difficulty figuring out the way to know if it's a builtin from `MacroCall`. :sweat_smile:

**Comment by Veykril** [comment]
In the code I linked above the `sa.expand` give you back a `MacroFileId` which allows you to fetch info for that macro call via `db.lookup_intern_macro_call(file_id.macro_call_id)`, there the `def` field has the interesting bits about the macro definition

**Comment by Veykril** [comment]
the `MacroDefId` (`def` field) already has helper methods so we would want one for the asm macros there as well

**Comment by ishanjain28** [comment]
Thank you so much! I will start working on this right away

**Comment by ishanjain28** [comment]
hey @veykril, I wrote a patch here https://github.com/rust-lang/rust-analyzer/compare/master...ishanjain28:rust-analyzer:filter_builtin_macro_expansion but I am still confused about a few things.

1. I was looking at writing tests. IIUC, `asm!()` expansion should return `None` and `include_str`(or some other allowed macro) expansion should return the expanded macro. I don't know how to write tests for this yet but I'll figure it out
2. The patch itself looks ugly or not quite right to me. Is there a better way to get Macro name?

**Comment by Veykril** [comment]
1. tests should go into https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide/src/expand_macro.rs, note that by default test fixtures do not have access to the standard library, you will have to make use of `minicore` annotations for the macros you want to use. https://github.com/rust-lang/rust-analyzer/blob/master/crates/test-utils/src/minicore.rs
2. You should match on the contained expanders directly within the (MacroDefKind you are matching on), those are enums that you can match on instead of having to go through the names https://github.com/rust-lang/rust-analyzer/blob/fa486e694e1fe7774f20350bb15ff933f670dc3c/crates/hir-expand/src/builtin_fn_macro.rs#L23-L31 https://github.com/rust-lang/rust-analyzer/blob/fa486e694e1fe7774f20350bb15ff933f670dc3c/crates/hir-expand/src/builtin_fn_macro.rs#L110-L142
