### ISSUE TITLE
link not working

### ISSUE THREAD

**Issue by Ethan-000** [rust-lang/rust-analyzer#14170]
hi

https://web.stanford.edu/~mlfbrown/paper.pdf this link in [architecture.md](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/architecture.md) is not working for me.

I'm wondering is it the same as this one? https://mlfbrown.com/paper.pdf

**Comment by Veykril** [comment]
@matklad

**Comment by lnicola** [comment]
Inter-Process Communication

**Comment by matklad** [comment]
Yup, that one! @Ethan-000 do you want to send a PR with a fixed link ^^?
