### ISSUE TITLE
Disable Inlay Hints

### ISSUE THREAD

**Issue by coffeebe4code** [rust-lang/rust-analyzer#14196]
"rust-analyzer.inlayHints.typeHints.enable": false,
  "rust-analyzer.inlayHints.parameterHints.enable": false,
  "rust-analyzer.inlayHints.chainingHints.enable": false

I have those three settings but somehow there are still some inlay hints.

The inlay hint is after an impl block, it just repeats the impl.

Are there any other inlay hints?
Is there a setting to disable them entirely?

**Comment by coffeebe4code** [comment]
![image](https://user-images.githubusercontent.com/78776922/221085694-dc6c0bf5-4d43-4389-bde2-d1b0c5c2158c.png)
Still there, and I get a warning that is not a valid json property in coc config

`Property editor.inlayHints.enable is not allowed.`

**Comment by coffeebe4code** [comment]
I realized this is in rust-analyzer now and not coc rust analyzer.

either coc or rust-analyzer just stops working in a project with two large dependencies, so I might just be done down this path. I'll try vscode to see if this works, or ill go back to cargo watch as my intellisense.

**Comment by lnicola** [comment]
>  Still there, and I get a warning that is not a valid json property in coc config

Right, I don't know how to disable them there. We have `rust-analyzer.inlayHints.closingBraceHints.enable` for those, I guess.

> either coc or rust-analyzer just stops working in a project with two large dependencies

Please file a new issue with more details.
