### ISSUE TITLE
How to know when being built with rust-analyzer?

### ISSUE THREAD

**Issue by MabezDev** [rust-lang/rust-analyzer#14206]
We have [a build script that](https://github.com/esp-rs/esp-hal/blob/bfa1bd901e2b23db3ecebf9e356d43f097c77683/esp-hal-common/build.rs#L12) indicates to a user only one chip feature should be enabled (yes, I know cargo features are supposed to be additive, but real life gets in the way :D). The problem is that RA can't build the project and displays a really annoying error popup. Ideally, we'd like to cfg away doing the check in the build.rs when RA is building/checking the project.

Are there any cfg's that RA sets that can we use already? Is this something you would accept as a PR? Is there a better way to go about this?

**Comment by lnicola** [comment]
I take it you're setting `"rust-analyzer.cargo.features": "all"`? We don't enable all features by default.

But no, this isn't possible currently, and it might be annoying for people compiling their project from the terminal.

**Comment by lnicola** [comment]
One janky way to detect `"rust-analyzer.cargo.features": "all"` is to define an extra feature that does nothing except letting your build script know that yes, someone is intentionally building the crate with all features enabled.

**Comment by MabezDev** [comment]
Thanks for the workarounds, works well enough for me :).
