### ISSUE TITLE
Rust analyzer reports `missing structure fields` when field is an `Option`

### ISSUE THREAD

**Issue by githubsands** [rust-lang/rust-analyzer#14201]
**1. rust-analyzer version:** [latest version from homebrew ](https://formulae.brew.sh/formula/rust-analyzer)

**2. rustc version:** 1.66.1  
 
**3. issue**
`func missing_fields` ([code](
https://github.com/rust-lang/rust-analyzer/blob/27239fbb58a115915ffc1ce65ededc951eb00fd2/crates/ide-diagnostics/src/handlers/missing_fields.rs#L31)) should check if field is wrapped in an `Option` before assuming a field is missing.

**Comment by lnicola** [comment]
Can you show a code example that triggers this? I suspect it's not as simple as it might appear.

**Comment by githubsands** [comment]
```
impl TwitterController {
    fn new() -> TwitterController {
        Self {
            id: NumericId::new(twitter_id),
            api: create_twitter_api(),
        }
    }
    fn store_tweets() {}
}

```

**Comment by githubsands** [comment]
<img width="603" alt="Screen Shot 2023-02-23 at 11 39 18 AM" src="https://user-images.githubusercontent.com/26752232/221000135-9c4c1b19-ecc2-4682-98e3-8e4ad6d12d4c.png">

**Comment by HKalbasi** [comment]
The error is correct, you can't actually compile that code.

**Comment by githubsands** [comment]
Yes  you can.

**Comment by lnicola** [comment]
You want `Self { id: twitter_id, api: create_twitter_api(), ..Default::default() }`. The code as you've written it doesn't compile.
