### ISSUE TITLE
Possible spoofing / name clash with rust-analyzer.vs Visual Studio plugin

### ISSUE THREAD

**Issue by Tastaturtaste** [rust-lang/rust-analyzer#14219]
I just came across a [plugin for Visual Studio with the name rust-analyzer.vs](https://marketplace.visualstudio.com/items?itemName=kitamstudios.RustAnalyzer&ssr=false#overview) while looking for Rust support for Visual Studio. The link to the extension was posted in this official ticket https://developercommunity.visualstudio.com/t/native-rust-support/517130. 

The plugin is very new and does not acknowledge rust-analyzer proper in any way. I have not looked into possible license / copyright issues. 
Their public github repo is here: https://github.com/kitamstudios/rust-analyzer.vs

If this is in any way related to this official rust-analyzer for vs code it would be nice to show this fact somehow. As it is I don't trust this plugin and wanted to make you aware of it.

**Comment by lnicola** [comment]
We recommend VS plugins [in the manual](https://rust-analyzer.github.io/manual.html#visual-studio-2022). They were added in #14012 and #14072, but we don't vouch for them, like we don't vouch for any other plugins except for the VS Code one.

**Comment by Tastaturtaste** [comment]
Ok, thank you for the info. I guess this issue can be closed then. I do find the name very unfortunate and potentially misleading though.
