### ISSUE TITLE
RA panicks when trying to get autocomplete on structs

### ISSUE THREAD

**Issue by saifalushi1** [rust-lang/rust-analyzer#14212]
rustc version: 1.67.1
RA version: v0.3.1410
IDE: vscode

when trying to use autocomplete with dot notation on structs RA panicks and does not give the expected fields.

![image](https://user-images.githubusercontent.com/78934157/221436614-f78a68dc-d01a-405a-9b21-09ec6a259def.png)

**Comment by HKalbasi** [comment]
Can you please copy the stack trace from the output here?

**Comment by saifalushi1** [comment]
> Can you please copy the stack trace from the output here?

unfortunately, I restarted my pc and when I reopened my code auto-complete was working and I could not reproduce the issue again.  I will continue to try to reproduce it and if I succeed I will post the stack trace

**Comment by Veykril** [comment]
Let's close this as there is no way for us to figure out what went wrong here then
