### ISSUE TITLE
“Fill struct fields” produced type instead of value for field of slice reference type

### ISSUE THREAD

**Issue by kpreid** [rust-lang/rust-analyzer#14228]
Start with:

```rust
struct Foo {
    things: &'static [Option<i32>],
}

fn test() {
    Foo {};
}
```

Put the cursor on `Foo {}` and invoke “Fill struct fields”. The result will be

```rust
fn test() {
    Foo { things: &[Option<i32>] };
}
```

which is a syntax error because of the angle brackets, and a semantic error even if the element type has no parameters, because it is placing a type where an expression is expected. This seems to happen for any field of type `&[T]` or `&mut [T]`. It does not happen for `Box<[T]>` or other things I tried.

I think that instead it should fill an empty slice.

**rust-analyzer version**: `0.4.1420-standalone (7f01ae877 2023-02-28)`

**rustc version**: `rustc 1.67.1 (d5a82bbd2 2023-02-07)`

**relevant settings**: `"rust-analyzer.assist.expressionFillDefault": "default",`

**Comment by roife** [comment]
Unable to reproduce the error, I think this issue may have already been fixed. The latest result is as follows:

```rust
struct Foo {
    things: &'static [Option<i32>],
}

fn test() {
    Foo { things: todo!() };
}
```
