### ISSUE TITLE
Passing wrong flag in piped program causes panic

### ISSUE THREAD

**Issue by stefanos82** [rust-lang/rust-analyzer#14227]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

`rust-analyzer` version: `rust-analyzer 0.3.1418-standalone`

**rustc version**: (eg. output of `rustc -V`)

`rustc` version: `rustc 1.63.0`

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

`CARGO` and `RUSTC` are located in `/usr/bin`; I have installed them via `nala` in GNU / Debian testing 64-bit.

**Issue**: I'm trying to setup `rust-analyzer` so I can use it with Vim 9 and I have noticed a weird behavior, it would partially work.

I have decided to investigate and noticed a weird behavior:

```
$ rust-analyzer diagnostics
flag is required: `path`
```

Upon investigation on this specific issue, I accidentally caused a panic in `rust-analyzer`; the reason is I passed a mistyped flag in piped program `jq` which caused it to panic.

```
$ RUST_BACKTRACE=full rust-analyzer --print-config-schema | jq --color
jq: Unknown option --color
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1009:9
stack backtrace:
   0:     0x55cb902e807e - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55cb902e807e - std::backtrace_rs::backtrace::trace_unsynchronized::h2292bca8571cb919
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cb902e807e - std::sys_common::backtrace::_print_fmt::h9c461f248e4ae90d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55cb902e807e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55cb8f2c89ce - core::fmt::write::h032658c119c720d7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0x55cb902e3695 - std::io::Write::write_fmt::h299fc90dfae41c0d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0x55cb902e7e55 - std::sys_common::backtrace::_print::heb70d25df9937e3f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55cb902e7e55 - std::sys_common::backtrace::print::had745c0a76b8b521
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55cb902e9c9f - std::panicking::default_hook::{{closure}}::h1ea782cdfa2fd097
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0x55cb902e9a14 - std::panicking::default_hook::h1cc3af63455a163c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0x55cb902ea323 - std::panicking::rust_panic_with_hook::h5cafdc4b3bfd5528
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:     0x55cb902ea0d6 - std::panicking::begin_panic_handler::{{closure}}::hf31c60f40775892c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
  12:     0x55cb902e85ac - std::sys_common::backtrace::__rust_end_short_backtrace::h28a5c7be595826cd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55cb902e9e12 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:     0x55cb8f1b8e23 - core::panicking::panic_fmt::h8fa27a0b37dd98b7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:     0x55cb902e2ce7 - std::io::stdio::print_to::h75426d195875dd5a
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/stdio.rs:1009:9
  16:     0x55cb902e2ce7 - std::io::stdio::_print::he20294a7ec6321a5
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/stdio.rs:1075:5
  17:     0x55cb90284383 - rust_analyzer::main::h6ef9e45b634ba2d6
  18:     0x55cb9028bf63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1a49ae689f9a9e33
  19:     0x55cb90296519 - std::rt::lang_start::{{closure}}::hdbb8d31d82beb6ca
  20:     0x55cb902da368 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfa1c3687c9a20bb8
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:606:13
  21:     0x55cb902da368 - std::panicking::try::do_call::h0497133ebe1341e5
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  22:     0x55cb902da368 - std::panicking::try::h6c3de05c7ca5d07f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  23:     0x55cb902da368 - std::panic::catch_unwind::h969058ecb5334b30
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  24:     0x55cb902da368 - std::rt::lang_start_internal::{{closure}}::h0de6d98cafb42a58
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:48
  25:     0x55cb902da368 - std::panicking::try::do_call::h77301dcf43953993
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  26:     0x55cb902da368 - std::panicking::try::h45b05523a2fe135a
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  27:     0x55cb902da368 - std::panic::catch_unwind::hd95cea544b2b9bd2
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  28:     0x55cb902da368 - std::rt::lang_start_internal::hd16e6ff7bf05a444
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:20
  29:     0x55cb90287575 - main
  30:     0x7f232b3b618a - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  31:     0x7f232b3b6245 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:381:3
  32:     0x55cb8f289dea - _start
  33:                0x0 - <unknown>
```

So, my first issue - if can be answered in this issue of course - is how to fix the `flag is required`?

Then the next question would be, is this an expected behavior from `rust-analyzer` when something goes wrong?

Please advice; I'm newcomer in Rust language in general, I'm trying to learn it.

**Comment by lnicola** [comment]
> So, my first issue - if can be answered in this issue of course - is how to fix the flag is required?

`rust-analyzer diagnostics .` or `rust-analyzer diagnostics /path/to/the/project`. But I suggest going for one of the Vim plugins listed under https://rust-analyzer.github.io/manual.html#vimneovim instead of trying to hard-wire something. The main feature of RA is the LSP implementation, and LSP already has native support for diagnostics. You **do not** need to run `rust-analyzer diagnostics` to see the errors in your project.

> Then the next question would be, is this an expected behavior from rust-analyzer when something goes wrong?

It's not RA, but any Rust program that doesn't specifically handle it:

![image](https://user-images.githubusercontent.com/308347/222124832-610a50da-9a16-418a-864d-2ed32d9c6bc8.png)

The issue is that the standard output is piped to `jq`. If `jq` doesn't like something and quits, the program can no longer write to the standard output. If you're using `println!` and friends, this results in a panic. I think this is mostly expected, and not an indicator of a bug.

**Comment by stefanos82** [comment]
I am using https://github.com/maralla/completor.vim as my LSP plugin and works just fine with other LSP-s so far.

I have set it up and could not see why RA would not auto-complete anything, apart from minor exceptions that would decide to do so for words such as `use`, for example.

The reason I tried the various commands with RA is so I could isolate the weird behavior so I could figure out how to make it work.

I don't use Neovim and even with https://github.com/prabirshrestha/vim-lsp the behavior was the same, nothing changed at all.

**Comment by lnicola** [comment]
We should support classic Vim using either ALE or `vim-lsp`. Make sure you're testing in a new project (the result of `cargo new foo`) as opposed to something like Rustlings, which has a non-standard layout.

If you want to do a basic smoke test, try `rust-analyzer analysis-stats .`. For the code above I get:

```
Database loaded:     712.62ms, 126minstr (metadata 621.05ms, 7683kinstr; build 45.55ms, 2487kinstr)
  crates: 1, mods: 1, decls: 1, fns: 1
Item Collection:     3.88s, 41ginstr
  exprs: 10, ??ty: 0 (0%), ?ty: 0 (0%), !ty: 0
Inference:           1.50s, 14ginstr
Total:               5.38s, 55ginstr
```

**Comment by stefanos82** [comment]
Here are my results:

```
stefanos@debian:hello_cargo [main]$ rust-analyzer analysis-stats .
Failed to create perf counter: Operation not permitted (os error 1)
[ERROR project_model::workspace] Failed to find sysroot for Cargo.toml file /home/stefanos/development/TheRustProgrammingLanguage/projects/hello_cargo/./Cargo.toml. Is rust-src installed? e=can't load standard library from sysroot
/usr
(discovered via `rustc --print sysroot`)
try installing the Rust source the same way you installed rustc
Failed to create perf counter: Operation not permitted (os error 1)
Database loaded:     2.24s (metadata 258.42ms; build 1.98s)
Failed to create perf counter: Operation not permitted (os error 1)
  crates: 1, mods: 1, decls: 1, fns: 1
Item Collection:     335.09µs
Failed to create perf counter: Operation not permitted (os error 1)
  exprs: 1, ??ty: 0 (0%), ?ty: 0 (0%), !ty: 0
Inference:           337.08µs
Total:               727.92µs
```

Clearly my system (GNU / Debian) is too strict with `perf` and I usually use it with `sudo` command.

**Comment by lnicola** [comment]
perf is not a problem, but this one is:

```
[ERROR project_model::workspace] Failed to find sysroot for Cargo.toml file /home/stefanos/development/TheRustProgrammingLanguage/projects/hello_cargo/./Cargo.toml. Is rust-src installed?
can't load standard library from sysroot /usr (discovered via `rustc --print sysroot`)
```

What does `rustc --print sysroot` print, and how did you install it?

**Comment by stefanos82** [comment]
I have mentioned how I installed it in the initial issue; path is `/usr`, at least that is what `rustc --print sysroot` returns.

**Comment by lnicola** [comment]
Right, sorry. `apt install rust-src` (or nala?) and it might start working.

But generally I would advise against using the Debian rustc. It tends to be old, and Rust libraries often want to use newer features. The Debian Rust is mostly there for building Debian packages that require Rust, not for general usage.

**Comment by stefanos82** [comment]
Oh, so Rust is on a bleeding edge development cycle, not a stable one?

If that's the case, I won't be using it until it becomes stable enough.

**Comment by lnicola** [comment]
> apt install rust-src (or nala?) and it might start working.

Just tested in a Debian 11 container. The directory layout is a bit weird but, surprisingly, it worked.

> Oh, so Rust is on a bleeding edge development cycle, not a stable one?

Rust has a 6 weeks release cycle, and only the latest version is supported. It's stable in the sense that existing code keeps working (with exceptions that are well-documented) and also stable in the sense that changes aren't merged in a hurry to catch the upcoming release.

But if you expect a 3 or 5 year release cycle, no, it's probably not going to happen soon.

**Comment by shadowcat-mst** [comment]
@stefanos82 rust handles backwards compatibility perfectly well and has a concept and policy called "editions" that makes things clear and predictable, but the rustc version shipped with debian is a snapshot intended to be the version of rust that things debian packages were built against.

Since in the end rustc produces a static binary, wanting a recent version of the compiler at build time whether for features or bugfixes is not in any way a stability issue.

debian picking a version of rustc for a particular stable release and ensuring the .debs of rust projects they provide are built against that rustc is entirely sensible, but rust-analyzer is fairly deeply tied to the compiler so you're going to want to make sure you have contemporary versions of the two one way or another.

No edges were made to bleed in the making of this reality.
