### ISSUE TITLE
Preview content duplication (VSCode)

### ISSUE THREAD

**Issue by adsick** [rust-lang/rust-analyzer#14226]
![image](https://user-images.githubusercontent.com/24528839/222117139-5308278c-ec09-4ff0-9d48-064c5e23a6fc.png)
I'm not sure if it is RA's problem, but think I have to report it here.
to reproduce hold Ctrl and hover on a static/const definition (note, sometimes it does not duplicates)

**Comment by Veykril** [comment]
ctrl hovering makes VCode render the text of the definition the thing you are hovering resolves to in addition to the hover message sent by the server, which in this case is the same. So I wouldn't consider this a bug
