### ISSUE TITLE
bootstrap error

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#14242]
I have the same bootstrap error with rust analyzer.
I am not an IT guy... might be a proxy issue? or that the vs-code version is kept fixed from the organization?

Here the full log, thank you in advance:
ERROR [3/3/2023, 18:05:22]: Bootstrap error [Error: Failed to execute c:\Users\mySelf\.vscode\extensions\rust-lang.rust-analyzer-0.4.1422-win32-x64\server\rust-analyzer.exe --version
	at Xv (c:\Users\mySelf\.vscode\extensions\rust-lang.rust-analyzer-0.4.1422-win32-x64\out\main.js:83:4925)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async ba.getOrCreateClient (c:\Users\mySelf\.vscode\extensions\rust-lang.rust-analyzer-0.4.1422-win32-x64\out\main.js:96:2023)
	at async ba.start (c:\Users\mySelf\.vscode\extensions\rust-lang.rust-analyzer-0.4.1422-win32-x64\out\main.js:96:2936)
	at async X_ (c:\Users\mySelf\.vscode\extensions\rust-lang.rust-analyzer-0.4.1422-win32-x64\out\main.js:100:1948)
	at async G_ (c:\Users\mySelf\.vscode\extensions\rust-lang.rust-analyzer-0.4.1422-win32-x64\out\main.js:100:763)
	at async E._activate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8224)
	at async E._waitForDepsThenActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8166)
	at async E._initialize (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:7530)]
INFO [3/3/2023, 18:07:58]: Extension version: 0.4.1422
INFO [3/3/2023, 18:07:58]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: true },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  restartServerOnConfigChange: false,
  typing: {
    continueCommentsOnNewline: true,
    autoClosingAngleBrackets: { enable: false }
  },
  diagnostics: {
    previewRustcOutput: false,
    useRustcErrorCode: false,
    disabled: [],
    enable: true,
    experimental: { enable: false },
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  assist: { emitMustUse: false, expressionFillDefault: 'todo' },
  cachePriming: { enable: true, numThreads: 0 },
  cargo: {
    autoreload: true,
    buildScripts: {
      enable: true,
      invocationLocation: 'workspace',
      invocationStrategy: 'per_workspace',
      overrideCommand: null,
      useRustcWrapper: true
    },
    extraEnv: {},
    features: [],
    noDefaultFeatures: false,
    sysroot: 'discover',
    sysrootSrc: null,
    target: null,
    unsetTest: [ 'core' ]
  },
  checkOnSave: true,
  check: {
    allTargets: true,
    command: 'check',
    extraArgs: [],
    extraEnv: {},
    features: null,
    invocationLocation: 'workspace',
    invocationStrategy: 'per_workspace',
    noDefaultFeatures: null,
    overrideCommand: null,
    targets: null
  },
  completion: {
    autoimport: { enable: true },
    autoself: { enable: true },
    callable: { snippets: 'fill_arguments' },
    limit: null,
    postfix: { enable: true },
    privateEditable: { enable: false },
    snippets: {
      custom: {
        'Arc::new': {
          postfix: 'arc',
          body: 'Arc::new(${receiver})',
          requires: 'std::sync::Arc',
          description: 'Put the expression into an `Arc`',
          scope: 'expr'
        },
        'Rc::new': {
          postfix: 'rc',
          body: 'Rc::new(${receiver})',
          requires: 'std::rc::Rc',
          description: 'Put the expression into an `Rc`',
          scope: 'expr'
        },
        'Box::pin': {
          postfix: 'pinbox',
          body: 'Box::pin(${receiver})',
          requires: 'std::boxed::Box',
          description: 'Put the expression into a pinned `Box`',
          scope: 'expr'
        },
        Ok: {
          postfix: 'ok',
          body: 'Ok(${receiver})',
          description: 'Wrap the expression in a `Result::Ok`',
          scope: 'expr'
        },
        Err: {
          postfix: 'err',
          body: 'Err(${receiver})',
          description: 'Wrap the expression in a `Result::Err`',
          scope: 'expr'
        },
        Some: {
          postfix: 'some',
          body: 'Some(${receiver})',
          description: 'Wrap the expression in an `Option::Some`',
          scope: 'expr'
        }
      }
    }
  },
  files: { excludeDirs: [], watcher: 'client' },
  highlightRelated: {
    breakPoints: { enable: true },
    exitPoints: { enable: true },
    references: { enable: true },
    yieldPoints: { enable: true }
  },
  hover: {
    actions: {
      debug: { enable: true },
      enable: true,
      gotoTypeDef: { enable: true },
      implementations: { enable: true },
      references: { enable: false },
      run: { enable: true }
    },
    documentation: { enable: true, keywords: { enable: true } },
    links: { enable: true }
  },
  imports: {
    granularity: { enforce: false, group: 'crate' },
    group: { enable: true },
    merge: { glob: true },
    prefer: { no: { std: false } },
    prefix: 'plain'
  },
  inlayHints: {
    bindingModeHints: { enable: false },
    chainingHints: { enable: true },
    closingBraceHints: { enable: true, minLines: 25 },
    closureReturnTypeHints: { enable: 'never' },
    discriminantHints: { enable: 'never' },
    expressionAdjustmentHints: { enable: 'never', hideOutsideUnsafe: false, mode: 'prefix' },
    lifetimeElisionHints: { enable: 'never', useParameterNames: false },
    maxLength: 25,
    parameterHints: { enable: true },
    reborrowHints: { enable: 'never' },
    renderColons: true,
    typeHints: {
      enable: true,
      hideClosureInitialization: false,
      hideNamedConstructor: false
    }
  },
  interpret: { tests: false },
  joinLines: {
    joinAssignments: true,
    joinElseIf: true,
    removeTrailingComma: true,
    unwrapTrivialBlock: true
  },
  lens: {
    debug: { enable: true },
    enable: true,
    forceCustomCommands: true,
    implementations: { enable: true },
    location: 'above_name',
    references: {
      adt: { enable: false },
      enumVariant: { enable: false },
      method: { enable: false },
      trait: { enable: false }
    },
    run: { enable: true }
  },
  linkedProjects: [],
  lru: { capacity: null },
  notifications: { cargoTomlNotFound: true },
  numThreads: null,
  procMacro: {
    attributes: { enable: true },
    enable: true,
    ignored: {},
    server: null
  },
  references: { excludeImports: false },
  runnables: { command: null, extraArgs: [] },
  rustc: { source: null },
  rustfmt: {
    extraArgs: [],
    overrideCommand: null,
    rangeFormatting: { enable: false }
  },
  semanticHighlighting: {
    doc: { comment: { inject: { enable: true } } },
    operator: { enable: true, specialization: { enable: false } },
    punctuation: {
      enable: false,
      separate: { macro: { bang: false } },
      specialization: { enable: false }
    },
    strings: { enable: true }
  },
  signatureInfo: { detail: 'full', documentation: { enable: true } },
  workspace: {
    symbol: { search: { kind: 'only_types', limit: 128, scope: 'workspace' } }
  }
}

_Originally posted by @Vincenzocr in https://github.com/rust-lang/rust-analyzer/issues/12876#issuecomment-1453849736_

**Comment by lnicola** [comment]
Let's continue here so we don't spam everyone in that other issue.

> @lnicola it says: "rust_analyzer.exe" not recognized a as an internal or external command, an executable program or batch file

It's `rust-analyzer --version`, with `-`, not `_`.

**Comment by Vincenzocr** [comment]
@lnicola it says: . the programm is blocked by group criteria. for additional informations, contact system administrator
that's probably why... but other vs code extensions behave well.. another thing is that I cannot update vs code version... it's kept fixed by my organization

**Comment by lnicola** [comment]
Yeah, I don't know how that's configured, but if `cargo` and Rust work for you, you might be able to build from source (`cargo xtask install --server`) and `rust-analyzer.server.path` in VS Code.

**Comment by Vincenzocr** [comment]
it says error: no such command: `xtask`
Did you mean `test`?

        View all installed commands with `cargo --list`


I confirm that rust and cargo works from command line. I can build correctly

**Comment by lnicola** [comment]
It will work if you clone this repository and run it there.

**Comment by Vincenzocr** [comment]
I solved the issue! I specified the "rust-analyzer.server.path" as you suggested! thank you very much :D!
Cheers!

**Comment by Vincenzocr** [comment]
oh, I am sorry. The rust-analyzer debugger does not work (the Run works instead"
pptools client: couldn't create connection to server.

Error: spawn UNKNOWN
	at ChildProcess.spawn (node:internal/child_process:413:11)
	at Object.spawn (node:child_process:720:9)
	at c:\Users\myself\.vscode\extensions\ms-vscode.cpptools-1.14.4-win32-x64\dist\main.js:70168:46
	at async LanguageClient.createConnection (c:\Users\myself\.vscode\extensions\ms-vscode.cpptools-1.14.4-win32-x64\dist\main.js:61163:28)
	at async LanguageClient.start (c:\Users\myself\.vscode\extensions\ms-vscode.cpptools-1.14.4-win32-x64\dist\main.js:60709:32)

I have ms-vscode.cpptools-1.14.4-win32-x64 /bin folder and the cpptools.exe inside.. do you know how to set it explicitly?
thank you in advance

**Comment by lnicola** [comment]
We don't handle the debugging. It might be the same group policy preventing you from running some programs. Nothing we can do in that case.

**Comment by Vincenzocr** [comment]
ok, I will contact the system administrator. thank you again! best!

**Comment by lnicola** [comment]
Or you can skip the debugger altogether. They tend to be less useful in Rust (and C and C++) than in other languages.
