### ISSUE TITLE
Fix up our pattern type inference and enable pattern type mismatch diagnostic

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14250]
We are currently only reporting type mismatches for expressions, in an attempt to enable them for patterns I noticed we still have a bunch of mismatches in patterns. Let's fix that!

We seem to have 178 mismatches on the repo itself right now, https://rust-analyzer.github.io/metrics/.

Similar issue to https://github.com/rust-lang/rust-analyzer/issues/8961

**Comment by HKalbasi** [comment]
It did got fixed in #14732 and later PRs. We now have 0 mismatches on self, and the diagnostic is re-enabled.
