### ISSUE TITLE
Unresolved `unwrap` method on `axum::Server`

### ISSUE THREAD

**Issue by OLoKo64** [rust-lang/rust-analyzer#14264]
**rust-analyzer version**: v0.3.1426
**rustc version**: rustc 1.67.1 (d5a82bbd2 2023-02-07)

**relevant settings**: None

### This started occurring after updating to the [latest version](https://rust-analyzer.github.io/thisweek/2023/03/06/changelog-171.html).

When defining a server in Axum with:
```rs
#[tokio::main]
async fn main() {
    // build our application with a single route
    let app = routes::get_app();

    info!("Starting server on http://localhost:{}", PORT);
    // run it with hyper on localhost:3000
    let addr = SocketAddr::from((ADDR_IPV4, PORT));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}
```
Rust Analyzer says: 
> no method `unwrap` on type `<Server<AddrIncoming, IntoMakeService<Router<(), Body>>, Exec> as IntoFuture>::Output`rust-analyzer (unresolved-method)

![image](https://user-images.githubusercontent.com/49915167/223172355-65ad7989-574d-4743-989e-c6cf51e89880.png)

This is strange as the app builds correctly with `cargo build` without any warnings. Same in Clippy.
This examlpe follows the Axum docs: https://docs.rs/axum/0.6.10/axum/#example

**Comment by Veykril** [comment]
Ah, we should probably silence the warning on unresolved projections as well.

**Comment by yfbmg** [comment]
Same problem, on the latest version, v0.3.1426, and when I back to the v0.3.1418, it disappeared.

**Comment by griffi-gh** [comment]
Similar issue with shipyards  `IntoIter` trait 
![изображение](https://user-images.githubusercontent.com/45996170/223279522-e000a86f-3876-4051-883d-e571dd806f1f.png)

**Comment by yameizi001** [comment]
It seems that the v0.4.1427 version has fixed this problem. If you are using VS Code, you can [switch to the pre-release version] and try it again.

**Comment by MogamiTsuchikawa** [comment]
I faced the same problem and was able to solve it by making it a pre-release version. https://twitter.com/MogamiTsuchikaw/status/1633083159964450825

**Comment by joelawm** [comment]
I had a similar issue and updating to pre-release also fixed it!

**Comment by sickill** [comment]
Had similar issue with Warp framework, switching VS Code extension to pre-release version (v0.4.1432) fixed it for me.

**Comment by OLoKo64** [comment]
Update: The new version `v0.3.1435` fixed the issue for me.

I plan to close this issue by the end of the day, when I manage to test a bit more.

**Comment by lnicola** [comment]
The diagnostics were marked as experimental in #14267, they will no longer trigger unless you enable them.
