### ISSUE TITLE
No method on type

### ISSUE THREAD

**Issue by griffi-gh** [rust-lang/rust-analyzer#14269]
**rust-analyzer version**: rust-analyzer version: 0.4.1425-standalone (0a956ec93 2023-03-05)

**rustc version**: rustc 1.70.0-nightly (7820b62d2 2023-03-05) 
 
**relevant settings**: Using lld as linker (linker = "rust-lld.exe")

---

After updating RA extension, compiler and dependencies of my game I started getting these errors
```
no method `iter` on type `View<Camera, _>
no method `iter` on type `View<Camera, _>`
no method `iter` on type `(&View<MainPlayer, _>, &View<Transform, _>)`
```

![VSCodium_SMpiKusosT](https://user-images.githubusercontent.com/45996170/223280659-2402558b-3737-473b-9d7d-17882d2d4af1.png)

Where `iter` method is provided by `IntoIter` trait from `shipyard` (`shipyard::IntoIter`)  
(Crate: `shipyard = { git = "https://github.com/leudz/shipyard", rev = "eb189f66", features = ["thread_local"] }`)

*Crate builds and runs just fine.*

Method is visible in auto-complete:

![VSCodium_5kiBR4aOeq](https://user-images.githubusercontent.com/45996170/223280871-4ce5479b-7474-4c11-98ab-47e15545775b.png)

**Comment by griffi-gh** [comment]
There's a pr that marks them as experimental:
https://github.com/rust-lang/rust-analyzer/pull/14267

**Comment by leudz** [comment]
Additional info: `View`'s second generic is a const generic.

**Comment by eldyer** [comment]
I can confirm this problem on rustc 1.68.0 with rust-analyzer 0.4.1432.

**Comment by lnicola** [comment]
The version released today disables this warning by default.

**Comment by svix-jplatte** [comment]
I just ran into (something like) this, albeit with `"rust-analyzer.diagnostics.experimental.enable": true`. Should this not be left open, even if it requires that flag to trigger?

**Comment by lnicola** [comment]
@svix-jplatte can you try with a nightly / pre-release version? The flag is still required.

**Comment by svix-jplatte** [comment]
Yes, the flag is required (I am on nightly) but wouldn't it be nice to still have an open issue to track fixing the bug (and taking the diagnostic out of the experimental group)?

**Comment by lnicola** [comment]
These all depend on switching to the new trait solver (which is already available in nightly, if you want to test it). Without a reproducer it's probably not worth keeping it open since the new solver will probably fix a whole bunch of issues, and introduce new and exciting ones instead.

**Comment by svix-jplatte** [comment]
Okay, I'll open a new issue with an example that reproduces on nightly then.

**Comment by ChayimFriedman2** [comment]
@svix-jplatte Note that if you're using rustup nightly, the new trait solver is not there yet.

**Comment by svix-jplatte** [comment]
Huh? Are you talking about rustc+new-trait-solver or RA+new-trait-solver? I'm exclusively talking about the latter, context being I noticed an issue in one of nightly RA's built-in [experimental] diagnostics.

**Comment by ChayimFriedman2** [comment]
r-a+new solver. If you get your r-a from rustup and you're using nightly, the new solver is not there yet until there will be a sync, so even if it reproduces don't create an issue.

**Comment by svix-jplatte** [comment]
Ah no, I'm not getting RA from rustup, I'm getting it as part of the VSCode extension from open-vsx.org.

**Comment by ShoyuVanilla** [comment]
I guess our nightly build hasn't been released with the next-gen trait solver either yet, as https://github.com/rust-lang/rust-analyzer/releases/tag/nightly says the released revision is https://github.com/rust-lang/rust-analyzer/commits/b2a58b8c6eff3c3a2c8b5c70dbf69ead78284194 , which doesn't contain next-gen trait solver PR

**Comment by svix-jplatte** [comment]
Okay, I'll check my code sample again tomorrow then :)

edit: Latest RA does not exhibit the bug I saw!
