### ISSUE TITLE
Replace `check_expect` test functions that assert by debug equality

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14268]
We have a bunch of test fixtures which currently assert outputs via the debug representation of things. These are annoying as the debug representation can change in many ways (even by just upgrading the compiler version which did happen in the past). We should get rid of those and replace them with better expected output.

An example of such a function is the following here https://github.com/rust-lang/rust-analyzer/blob/a360fab9a36a20046fed4c6e9b863c52c7578de0/crates/ide/src/inlay_hints.rs#L541-L546

**Comment by Urhengulas** [comment]
The three PRs should solve this issue
