### ISSUE TITLE
Latest stable (3.1426) is marking up diesel code with false positive errors.

### ISSUE THREAD

**Issue by Randall-Coding** [rust-lang/rust-analyzer#14274]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
3.1426 on Vscode, and Ubuntu 20.04 (and 22.04)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.69.0-nightly (4507fdaaa 2023-02-18)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
All defaults

**The Problem**

Yesterday I noticed a lot of diesel code (diesel 1.4.5) is being marked up in rust-analyzer as being in error that never was before.  It also compiles just fine, so the issue seems to just be on the rust-analyzer side of things flagging false positives.

Specifically it happens with functions that are called on diesel columns such as `<column>.eq()` and `<column>.desc()`  and also on `<query>.execute()`

This error only shows up after opening up the particular file in the editor.  Prior to that the error does not get flagged in vscode if I merely have the project open.   

**Errors**
> no method `eq` for type `channel_id`     

^ where channel_id can be any column name

> no method `execute` on type `InserStatement<table, <&NewTransfer as Insertable<table>>::Values, Insert, NoReturningClause>`

**Actions Taken**

I've downgraded the version of rust-analyzer to 3.1418 to resolve this issue in the mean time.

**Comment by NexRX** [comment]
I see this is fresh and I can also verify the same thing is happening to me.

**Comment by lnicola** [comment]
The problematic diagnostics were disabled by default in #14267. You can install the pre-release version now, or wait until Monday.

@Veykril do you think it's worth keeping these issues open?

**Comment by Veykril** [comment]
I'd say let's keep this open until the next stable release, afterwards there is probably no gain from having it open.

**Comment by jtomaspm** [comment]
Hey I'm new to rust and this was driving me crazy, What i found most weird is when i try to compile and run it does without problems. 
I'm running:
- rustc 1.70.0-nightly (8a73f50d8 2023-03-11)
- diesel  "2.0.1"
