### ISSUE TITLE
Wrong type deduction for Vec::last().unwrap() expression

### ISSUE THREAD

**Issue by jbuckmccready** [rust-lang/rust-analyzer#14270]
**Reproduction:**
In this repository: https://github.com/jbuckmccready/cavalier_contours, in this commit, file, and line number: https://github.com/jbuckmccready/cavalier_contours/blob/08200b5b9856eb030266db0a57700830a39b3ff5/cavalier_contours/src/polyline/internal/pline_offset.rs, the type deduced by rust-analyzer is wrong. rust-analyzer shows the expression `raw_offset_segs.last().unwrap()` to be a `PlineVertex<{unknown}>` but it is actually a `RawPlineOffsetSeg<T>`. cargo check and build work as expected.

**Additional info:**
Older versions of rust-analyzer also get the type wrong (which is why I made this issue), but latest version now also shows an error (beyond the red text highlight and false auto completion) related to this pull request: https://github.com/rust-lang/rust-analyzer/pull/14267.

**rust-analyzer version**: rust-analyzer version: 0.3.1426-standalone (0a956ec93 2023-03-05)

**rustc version**: 1.67.1

**Comment by lnicola** [comment]
The version released today disables this warning by default.
