### ISSUE TITLE
New assist suggestion - `.mutex` and `.arcmutex`

### ISSUE THREAD

**Issue by cameron1024** [rust-lang/rust-analyzer#14272]
Currently there are a bunch of postfix suggestions (e.g. `expr.box<complete>` -> `Box::new(expr)`, `expr.arc<complete>` -> `Arc::new(expr)`)

I'd like to add:
 `.mutex` to wrap the expression in `Mutex::new(<expr>)`
 `.arcmutex` to wrap the expression in `Arc::new(Mutex::new(<expr>))`

A separate but related suggestion is to add these sorts of assists to types as well as expressions. It would be really nice to be able to write:
```rust
struct Foo {
  bar: Bar.arc<completion>
}
```
to convert it to `bar: Arc<Bar>`. Though that might belong in a separate issue

Some possible drawbacks are:
 - perhaps we don't want to encourage `Arc<Mutex<T>>` as it may lead beginners to think this is "the way to escape the borrow checker". Personally, this doesn't seem hugely concerning to me - nothing about the existence of `.arcmutex` suggests to a beginner that it is an easy way to avoid borrow checker issues
 - `.arcmutex` is arguably redundant, since you could use `.mutex<completion>.arc<completion>` - though to me, having a separate `.arcmutex` is advantageous because:
   - it's a common pattern
   - it avoids a common pitfall of getting it the wrong way round (i.e. `.arc<completion>.mutex<completion>` which would create a `Mutex<Arc<T>>`

What do people think about this? If it sounds good, I can try to work on a PR

**Comment by Veykril** [comment]
Postfix type compeltions are already tracked in https://github.com/rust-lang/rust-analyzer/issues/4360
Regarding the proposed mutex and arcmutex, r-a supports custom snippet configurations https://rust-analyzer.github.io/manual.html#user-snippet-completions 

We would rather not add new builtin postfix completions as these can be quite annoying since they appear for all expressions usually.

**Comment by antonilol** [comment]
what about `.deref`? missing this one and i think it belongs next to `.ref` and `.refm`,
