### ISSUE TITLE
Action "Convert match to let-else" causes error (when an `|` pattern is involved)

### ISSUE THREAD

**Issue by izik1** [rust-lang/rust-analyzer#14290]
Consider this example:
```rs
enum Foo {
    A(u32),
    B(u32),
    C(String),
}

fn foo(foo: Option<Foo>) -> Result<u32, ()> {
    let value = match foo {
        Some(Foo::A(it) | Foo::B(it)) => it,
        _ => return Err(()),
    };

    Ok(value)
}
```

anywhere in the `let` statement, `Convert match to let-else` is available (which is fine).
However, when applying the action the following code is generated:
```rs
enum Foo {
    A(u32),
    B(u32),
    C(String),
}

fn foo(foo: Option<Foo>) -> Result<u32, ()> {
    let Some(Foo::A(value) | Foo::B(it)) = foo else { return Err(()) };
}
```
Namely, the first instance of `it` being bound, it got properly renamed to `value`, but the _second_ time `it` was bound (and presumably any after, although I haven't tested that) `it` was _not_ renamed to `value`, and so, 2 instances of `variable `{x}` was not bound in all patterns` (where `x` is either `value` or `it`) occurred.

I also tried this with un-nested `|` patterns, and that still errored.

**rust-analyzer version**: rust-analyzer version: 0.4.1428-standalone (ecc32c2f8 2023-03-07)
 
**rustc version**: rustc 1.67.1 (d5a82bbd2 2023-02-07) (shouldn't matter)

**relevant settings**: available upon request (I don't know what's relevant here)

**Comment by HKalbasi** [comment]
Is it a nightly regression?

**Comment by Veykril** [comment]
No, this behavior was already there before your PR, see https://github.com/rust-lang/rust-analyzer/blame/a360fab9a36a20046fed4c6e9b863c52c7578de0/crates/ide-assists/src/handlers/convert_match_to_let_else.rs#L104

It never handled multiple binding declarations.

**Comment by HKalbasi** [comment]
Ah, that's good.

@rustbot claim
