### ISSUE TITLE
Change command ran by rust-analyzer(cargo check) on save with (cargo check -r)

### ISSUE THREAD

**Issue by ayush-india** [rust-lang/rust-analyzer#14294]
I am working on a project in which i always have to run release mode but when i use ra in neovim with nvim-lspconfig. I always run's **cargo check** in debug mode and when i mannually invoke **cargo check -r** it rebuilds the project which is time consuming. 

So, what i want to have is that when i save a change rather that cargo check (ran by rust-analyzer) i want it to run cargo check -r.

Thanks for the help in advance and also for making such a great language.

**Comment by lnicola** [comment]
> I always run's cargo check in debug mode and when i mannually invoke cargo check -r it rebuilds the project which is time consuming.

This should only happen once (the first time). If everything gets rebuilt every time, you might have some other problem, like a different set of `RUSTFLAGS`.

**Comment by ayush-india** [comment]
@lnicola yes this happens (cargo check from nvim-lspconfig) only once but this resuults in debug and release dirs in target folder.
Which takes a lot of space.
What i wanted it that cargo check has a -r flag on it which will be usefull in saving some space
