### ISSUE TITLE
Alignment is misreported for type containing usize

### ISSUE THREAD

**Issue by GoldsteinE** [rust-lang/rust-analyzer#14314]
On this code:
```rust
struct Foo {
    _x: usize,
}

fn main() {
    dbg!(std::mem::align_of::<Foo>());
}
```

hovering `Foo` says that its align is 4 on x86_64 Linux, despite it actually being 8.

![image](https://user-images.githubusercontent.com/12019211/224276260-44a01671-a72f-438c-8f23-95eb96f43644.png)

**rust-analyzer version**: 
```
rust-analyzer 1.68.0-nightly (61a415b 2023-01-12)
```

**rustc version**: 
```
rustc 1.68.0-nightly (61a415be5 2023-01-12)
```

**Comment by GoldsteinE** [comment]
Oops, possibly duplicate of #13959

**Comment by lnicola** [comment]
Yeah, if you can, please try with a binary from GitHub Releases.

**Comment by GoldsteinE** [comment]
Yep, no longer reproduces after update, sorry.

**Comment by lnicola** [comment]
Keep in mind that the RA in `rustup` will generally lag a bit behind upstream.
