### ISSUE TITLE
vscod  rust-analyzer report error

### ISSUE THREAD

**Issue by Yakumo-Yukari** [rust-lang/rust-analyzer#14324]
rust-analyzer   v0.3.1426
rustc 1.68.0
axum  0.6.10

err:

no method `unwrap` on type `<Server<AddrIncoming, IntoMakeService<Router<(), Body>>, Exec> as IntoFuture>::Output`

![1678499364733](https://user-images.githubusercontent.com/12076232/224458532-f7c31fa7-2770-481d-b2a7-ff36c2b80af5.png)

**Comment by Veykril** [comment]
Fixed in the next version, see https://github.com/rust-lang/rust-analyzer/issues/14259#issuecomment-1464738829
