### ISSUE TITLE
Unable to detect `unwrap` method

### ISSUE THREAD

**Issue by shenghui0779** [rust-lang/rust-analyzer#14322]
- `axum` README
<img width="446" alt="image" src="https://user-images.githubusercontent.com/67535398/224454994-cb239b62-0194-490b-b1ca-de03d614b61e.png">

- vscode
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/67535398/224455025-2ce150dd-31ee-4798-b45b-0ad1d97b195a.png">

Note: Old version has no problem.

**Comment by Veykril** [comment]
Fixed in the current nightly, see https://github.com/rust-lang/rust-analyzer/issues/14259#issuecomment-1464738829
