### ISSUE TITLE
when I'm debugging,I Can't step into std library and sometimes showing asm

### ISSUE THREAD

**Issue by xzbdmw** [rust-lang/rust-analyzer#14330]
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/97848247/224532932-03241599-b70a-45ed-90ce-f08c921dd64f.png">
<img width="742" alt="image" src="https://user-images.githubusercontent.com/97848247/224532945-581ad2dd-f520-4c55-bc82-65e5450cbe53.png">
Does anyone happen to know why? I've searched extensively but unfortunately found no answer. Thank you so much!
**rust-analyzer version**:  0.3.1426-standalone (0a956ec93 2023-03-05)

**rustc version**: rustc 1.66.1 (90743e729 2023-01-10)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**Comment by xzbdmw** [comment]
My codelldb version is 1.9.0, and don't have a launch.json in my project

**Comment by xzbdmw** [comment]
codelldb #204  fixed

**Comment by lnicola** [comment]
For the record, we don't have anything to do with the debugging experience. In general, you'll find Rust a bit worse than C++, and much worse than managed languages like Java.
