### ISSUE TITLE
Disk is 100% occupied and makes WSL hang

### ISSUE THREAD

**Issue by jaques-sam** [rust-lang/rust-analyzer#14346]
Type: <b>Bug</b>

After some time working on a rust project within a Docker (running on latest Ubuntu WSL2 using Docker Desktop from Windows) , the amount of virtual memory used is 20 GB, the Windows "System" program is using up to 500 MB/s of disk usage. I must run it in a Docker as well. It's the only running docker at that moment. WSL hangs, docker hangs, the system gets very unresponsive. The only way to solve it is to restart WSL.

Extension version: 0.3.1435
VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.61GB (2.23GB free)|
|Process Argv|--folder-uri vscode-remote://attached-container%2B7b22636f6e7461696e65724e616d65223a222f636f6e6665726f2d63616d2d646576227d/confero-cam-compositor --crash-reporter-id a600019d-bd7e-43dd-90e1-cc76e1ab0a4c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container sjaques/confero-cam-dev:vscode1 (confero-cam-dev)|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2+|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|Memory (System)|7.57GB (4.77GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30677850
pythonb192cf:30669361
funwalk2cf:30682975

```

</details>

**Comment by lnicola** [comment]
How large is your project?

If you close Code, go to the project directory and run `cargo clean`, then `cargo check`, what's the disk usage like?

**Comment by jaques-sam** [comment]
Hi Inicola, thanks for your comment
It is pretty big...
```sh
✦ ⬢ [Docker] ❯ du -h --max-depth=1 | sort -hr                                                    
1.9G    .
1.8G    ./target
9.2M    ./.git
3.0M    ./director
400K    ./compositor
312K    ./viscartspsrc
216K    ./assets
116K    ./docs
60K     ./elements
24K     ./audiosource
16K     ./.vscode
12K     ./scripts
8.0K    ./docker
```

**Comment by lnicola** [comment]
Yes, but does it also make your computer run slowly?

**Comment by jaques-sam** [comment]
Most of the time it's not. But happens on certain moments that the rust-analyzer is doing a `cargo check`. Typically the issue happens between 1 to 4 hours, so I have this almost twice a day that the amount of system resources being used is of the charts. So it's hard to say the reproduction steps...

**Comment by jaques-sam** [comment]
After running a week without Rust-analyzer, I see the same issue. So, sorry to interrupt ;-)
