### ISSUE TITLE
Potential regression issue on variable mutability requirements within a loop

### ISSUE THREAD

**Issue by RylBlue** [rust-lang/rust-analyzer#14344]
May have some regression news.

Getting a rust-analyzer error that a variable needs to be mut even when it does not. Was not getting this error before tonight. Code compiles without issues.

![Incorrect_Error](https://user-images.githubusercontent.com/36209726/224889523-fafc0dc4-9e77-4bf6-8865-82a4af98faa1.PNG)

When the "pointer_data" variable is made mut, a warning is correctly displayed.

![Warning_If_mut](https://user-images.githubusercontent.com/36209726/224889544-ab082316-0af7-4b2a-b7cf-513d497c12a7.PNG)

**rust-analyzer version**: rust-analyzer version: 0.3.1435-standalone (f1e51afa4 2023-03-12)

**rustc version**: 1.67.0

**relevant settings**: Everything's basically a default Windows 10 VSCode install, comment with any additional requests for info

**Comment by Veykril** [comment]
Looks like we missed that its not needed for initializing uninitialized variables
