### ISSUE TITLE
Unknown type in basic `hyper` code

### ISSUE THREAD

**Issue by lowr** [rust-lang/rust-analyzer#14369]
This is not really a rust-analyzer bug but a chalk bug, nevertheless filing this here to make it known and so we have an open issue to point to.

Below is a modified example from [hyper tutorial](https://hyper.rs/guides/0.14/server/hello-world/). Note that some of the functions have been removed for hyper 1.0, so make sure to use hyper 0.14.x to reproduce.

```rust
use std::convert::Infallible;
use std::net::SocketAddr;
use hyper::{Body, Request, Response, Server};
use hyper::service::{make_service_fn, service_fn};

async fn hello_world(_req: Request<Body>) -> Result<Response<Body>, Infallible> { todo!() }

async fn test() {
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));

    let make_svc = make_service_fn(|_conn| async {
        Ok::<_, Infallible>(service_fn(hello_world))
    });

    let server = Server::bind(&addr).serve(make_svc);
      //^^^^^^ `Server<AddrIncoming, MakeServiceFn<closure>, Exec>`
      //       this type *does* implement `Future<Output = hyper::Result<()>>`
    let result = server.await;
      //^^^^^^ {unknown}, because chalk **disproves** `Server<_, _, _>: Future`.
}
```

cc #13450, #14264, #14322, #14324, I believe they are all caused by this issue.

**rust-analyzer version**: rust-analyzer version: 0.0.0 (b4d7ea0692f 2023-03-14)

**rustc version**: rustc 1.68.0 (2c8cc3432 2023-03-06)

**relevant settings**: none

**Comment by Throne3d** [comment]
It looks like the other issues linked here were closed, and I can't reproduce this locally - the inference for `result` seems to be `Result<(), Error>`, not `{unknown}`, for me locally. Is this still a problem on recent versions of RA?

![image](https://github.com/user-attachments/assets/0dd44048-0288-44b9-8cac-cb6fa12b3d0d)

**Comment by lnicola** [comment]
Indeed, this seems to work now (`hyper = { version = "0.14", features = ["http1", "server", "tcp"] }`).
