### ISSUE TITLE
proc macro `command` not expanded

### ISSUE THREAD

**Issue by OTheNonE** [rust-lang/rust-analyzer#14372]
I'm using Tauri to build my project, and in src-tauri/src/main.rs, i recieve this error from the rust-analyzer:

![image](https://user-images.githubusercontent.com/57041901/226093752-e4eb8a07-d9f5-4199-8db7-7b0f36dad5d8.png)

With the error message:
`proc macro `command` not expanded: Cannot create expander for my_project_folder\src-tauri\target\debug\deps\tauri_macros-90d2600cbc12f965.dll: unsupported ABI `rustc 1.62.1 (e092d0b6b 2022-07-16)``

**rust-analyzer version**: rust-analyzer version: 0.3.1435-standalone (f1e51afa4 2023-03-12)

**rustc version**: rustc 1.68.0 (2c8cc3432 2023-03-06)

**Comment by lnicola** [comment]
We don't support Rust 1.62 any more. You can use an older version of RA or upgrade to a newer compiler. If you think you're on 1.68, check for a rust-toolchain file, or try a clean build.

**Comment by OTheNonE** [comment]
Updating Rust 1.62 to 1.68 solved the problem.
