### ISSUE TITLE
Type inference issue in Diesel

### ISSUE THREAD

**Issue by AJTJ** [rust-lang/rust-analyzer#14374]
Type inference is not happening correctly, all the time, when using Diesel.

for example, with:
```rs
use trading_bot::schema::users::dsl::*;
let x = users.select(OutUser::as_select()).load(&mut conn);
```
for this, `x` is clearly of type `Result<Vec<OutUser>, Error>`, but rust-analyzer is identifying it as "unknown".
<img width="487" alt="Screenshot 2023-03-18 at 10 46 14 AM" src="https://user-images.githubusercontent.com/29932896/226120927-9a066046-1b03-4bc9-ac54-d364b7173867.png">

I have a feeling that rust-analyzer is probably struggling with how the generics are being created in diesel.

I really like rust-analyzer as a project. Is there something I can help with?

rust-analyzer version: 0.4.1438-standalone (924d277f3 2023-03-15)
rustc 1.69.0-nightly (31f858d9a 2023-02-28)

**Comment by Veykril** [comment]
Assuming its possible with your project but can you check whether using the master branch of diesel fixes this issue for you? I believe this is due to their proc-macros using an old edition which r-a struggles with.

**Comment by weiznich** [comment]
Yes this specific case should be worked around by https://github.com/diesel-rs/diesel/pull/3564

**Comment by weiznich** [comment]
This is not fixed as shown by https://github.com/rust-lang/rust-analyzer/issues/14607

**Comment by lowr** [comment]
Let's close this one in favor of #14607. Thanks for the initial report!
