### ISSUE TITLE
Nested markdown fenced code blocks in doc comments aren't renedered properly

### ISSUE THREAD

**Issue by garlicbreadcleric** [rust-lang/rust-analyzer#14383]
I have the following code:

```rust
enum BlockElement {
  // ...

  /// Fenced code block.
  ///
  /// # Examples
  ///
  /// `````markdown
  /// ```
  /// code block
  /// ```
  ///
  /// ```rust
  /// code block
  /// ```
  /// `````
  FencedCodeBlock {/* ... */},

  // ...
}
```

I expect the doc comment to be rendered as (screenshot from rustdoc output):

<img width="982" alt="image" src="https://user-images.githubusercontent.com/112731564/226365009-4af49483-f8eb-433a-90ad-8eff04d20007.png">

But instead when I hover over `FencedCodeBlock` in VS Code I get this:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/112731564/226364750-cdb816e5-da30-44cf-a235-f22ae8dee3ac.png">

Or when triggering auto-completion in Helix:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/112731564/226365578-c8058ca1-a41e-461e-b5af-a31266b20893.png">

**rust-analyzer version**: 0.3.1435-standalone (f1e51afa4 2023-03-12)

**rustc version**: 1.70.0-nightly (7b4f48927 2023-03-12)

**relevant settings**: I don't think there are any

**Comment by lnicola** [comment]
CC #13815

**Comment by AndreasBackx** [comment]
This is supported as of #15032.

<img width="497" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/1593486/b676940d-a485-40d6-af22-e0381d62b58a">

**Comment by lnicola** [comment]
Supported in VS Code, we don't have any Markdown support otherwise. Closing this anyway, since that's a wider issue.
