### ISSUE TITLE
unresolved reference for trait associated type

### ISSUE THREAD

**Issue by jhgg** [rust-lang/rust-analyzer#14393]
I'm not sure the best title for this issue, so feel free to rename:

Consider the following code:

```rust
trait Foo {
    type Bar;
    fn baz() -> Self::Bar;
}

enum BarEnum {
    Qux { x: u32 },
    Tup(),
    Reg,
}

impl BarEnum {
    fn method() -> Self {
        Self::Tup()
    }
}

impl Foo for String {
    type Bar = BarEnum;

    fn baz() -> Self::Bar {
        Self::Bar::Qux { x: 1 };
        //    ^^^  ^^^   ^
        //   unresolved

        Self::Bar::Tup();
        //    ^^^
        //    unresolved

        Self::Bar::Reg;
        //    ^^^
        //    unresolved

        Self::Bar::method()
        //    ^^^
        //    unresolved
    }
}
```

When referring to `BarEnum` as `Self::Bar`, rust-analyzer seems to be unable to resolve. Here is a screenshot with a red semantic token.

![image](https://user-images.githubusercontent.com/5489149/227003203-a3fd423a-51c0-46d0-abdb-07a4e8bf120a.png)

This breaks autocomplete, and also stuff like rename symbol, for example renaming `BarEnum::Qux`, does not cause  `Self::Bar::Qux` to be renamed. Additionally renaming `type Bar` also does not rename where its unresilved.

`Self::Bar` only becomes unresolved after you type `::` after it:

![Code_-_Insiders_7kJhB66akj](https://user-images.githubusercontent.com/5489149/227003629-24225947-8df5-4e1a-9e17-04e25897f059.gif)

**rust-analyzer version**:  rust-analyzer version: 0.4.1445-standalone

**rustc version**: rustc 1.66.1 (90743e729 2023-01-10)

**Comment by Veykril** [comment]
All of these resolve now
