### ISSUE TITLE
Run through WSL

### ISSUE THREAD

**Issue by FallBackITA27** [rust-lang/rust-analyzer#14392]
Rust Analyzer does not work when Cargo is installed through WSL.

**Comment by lnicola** [comment]
How are you installing and running RA?

**Comment by lnicola** [comment]
Did you install it on the Windows or WSL side? And what error are you getting?

**Comment by bjorn3** [comment]
Are you using the WSL extension to work inside the WSL vm or did you open the fs exported to the windows side (I believe at `\\wsl$\`. In the later case rust-analyzer will run on Windows and fail to find the rustc installed in WSL. In the former case rust-analyzer will run inside WSL too.

**Comment by FallBackITA27** [comment]
I did install it on the Windows side given the VSC installation itself is on Windows. I did not know there was a WSL extension and I'll look into it. Thanks.
