### ISSUE TITLE
Support doc(alias)-based completion

### ISSUE THREAD

**Issue by hecatia-elegua** [rust-lang/rust-analyzer#14406]
To put it simply, I have some funny named registers like `PORTPMSC` but want to give them real names, in this case something like `PortPowerManagementStatusControl` (not exactly, but you get the idea).
```rust
doc(alias("PORTPMSC"))
struct PortPowerManagementStatusControl { ... }
```
Sometimes the name of the thing and its abbreviation in a specification is completely different though, so code completion will only work with the name in code, but I would like people to be able to use the spec abbreviations as well.

To get to the point: Where would I need to start looking to implement this? I.e. where in this repo is the code-completion handled and where the attribute parsing or generally attribute info?

**Comment by hecatia-elegua** [comment]
https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-completion/src/completions/type.rs I assume somewhere in here for the code completion aspect?

**Comment by Veykril** [comment]
That sounds great to have, not 100% sure how to add this though.
So I think what we probably want to do the following:
https://github.com/rust-lang/rust-analyzer/blob/82ec4586f1a43112ba22645e9c88edf08994843e/crates/ide-completion/src/context.rs#L494-L504
Here we want to check for aliases of the `def`, and if we find any invoke the callback with the aliases as well. You should be able to figure out how to handle the attribute part by checking how that function already handles the doc(hidden) stuff, but if you run into problems there feel free to ask

**Comment by hecatia-elegua** [comment]
I'm about halfway there, but turning the alias into a Name sounds wrong, see:
https://github.com/rust-lang/rust-analyzer/blob/82ec4586f1a43112ba22645e9c88edf08994843e/crates/hir-expand/src/name.rs#L66-L71

**Comment by Veykril** [comment]
Hm, right the alias is a string here, not an ident. Let's just cheat here like we are already in collector here to create an arbitrary  name, https://github.com/rust-lang/rust-analyzer/blob/82ec4586f1a43112ba22645e9c88edf08994843e/crates/hir-def/src/nameres/collector.rs#L90C76-L93

(and put an appropriate FIXME on that as well)

**Comment by hecatia-elegua** [comment]
Apparently I don't understand how to debug this with just printing or the trace crate at all, will get back to this tomorrow.
Maybe I should put tests somewhere first and try with those like it says in the dev docs

**Comment by Veykril** [comment]
writing a test and then print debugging that test is usually easier (and faster)

**Comment by Veykril** [comment]
Right, the name used is what will be inserted ... I don't think there is currently any precedent to simple name completions completing to a different name than listed.

The `->`  idea isn't too great, I think that might be confusing to some people and it might also clutter, we could do something similar to what we do with trait items though, 
![image](https://user-images.githubusercontent.com/3757771/228223342-98975feb-a9e1-4720-b9b8-f091da232f98.png)
here we do `cmp (as Ord)`, so maybe something like `PortPowerMa... (alias PORTPMSC)`?

**Comment by hecatia-elegua** [comment]
Ok, I'm nearly there, but I need ScopeDef or some other way to get the attribute information.
If I understand correctly, I should not be calling my stuff in `process_all_names` anymore, but somewhere else, probably `src/render/literal/fn render`, which funnels it to `src/item/Builder.build`. `ModuleDef` can get attrs as well.
Any pointers?

**Comment by Veykril** [comment]
Only `ModuleDef`s can have relevant attributes here (which `ScopeDef` delegates to). I'm not quite sure how to handle this right now, but we do still want to do something in `process_all_names` since we do want to show completions for both the normal name but also for the alias. So we somehow need tosignal completions called in `process_all_names` that the name we pass is an alias and not the name that is actually in scope right now, so that the logic can render the completion lookup with the alias but not insert the alias.

**Comment by hecatia-elegua** [comment]
Ugh, so all callsites of `process_all_names` need to handle this? I hoped this would not be the case... well, I'll try to hack it together for now. Thanks

**Comment by Veykril** [comment]
Unfortunately yes, I am not happy with how that currently works either. But I can't really think of a better way to do that right now.

**Comment by hecatia-elegua** [comment]
Oh, this is nice.
![alias for ord](https://user-images.githubusercontent.com/108802164/228487014-acf088c5-c875-4786-babe-693b76dccb00.png)
Only thing which should maybe be fixed is that I can write "alias" and it shows completions for all doc-aliases. The usual "as Trait" and "use ..." do filter this somehow, maybe that's a frontend-thing?
Though some don't:
![use highlighting](https://user-images.githubusercontent.com/108802164/228489175-5538ceab-570a-47bd-966a-fbad36ab7b3b.png)
I'll push up a PR without fixing that, as it's a minor bug.

**Comment by hecatia-elegua** [comment]
Actually, I can solve that! Should I?
So people don't step over their toes, we should remove the default lookup value:
https://github.com/rust-lang/rust-analyzer/blob/a486f3404884a664b71dfdf01fd6208fe56902b7/crates/ide-completion/src/item.rs#L421-L424
https://github.com/rust-lang/rust-analyzer/blob/a486f3404884a664b71dfdf01fd6208fe56902b7/crates/ide-completion/src/item.rs#L360-L362
This looks a lot like they thought these values don't interact.

**Comment by Veykril** [comment]
Just a note, VScode highlights the matches very weirdly, in `RefUnwindSafe (use ...)` its not the uise that is matching the typed characters but the Ref***U***nwind***S***af***e***. So typing `use` will actually not cause lookups for those, its just vscode rendering it like that due to the casing.

You are correct here though that for the `(as ...)` and your new alias completions this happens since the lookup isn't set up there (if I am not mistaken). So fixing that would be good :)

**Comment by hecatia-elegua** [comment]
Thank you. I could extend the PR with function/field aliases and the bug fix, though maybe keeping it a bit smaller is better.

**Comment by Veykril** [comment]
Let's keep that for a follow up 👍
