### ISSUE TITLE
Proc Macro Expansion with a `rust-project.json` Regressed with #14405

### ISSUE THREAD

**Issue by davidbarsky** [rust-lang/rust-analyzer#14417]
**rust-analyzer version**: rust-analyzer version: 0.0.0 (f85fc2850 2023-03-26) (I'm building from source.)

**rustc version**: (eg. output of `rustc -V`): rustc 1.68.1 (8460ca823 2023-03-20)

**relevant settings**: I'm using this with a `rust-project.json` sourced from Buck. I can't provide a minimal reproduction at the moment.

Hi! This is not particularly urgent issue, but I've noticed that procedural macro expansion has regressed when used with a rust-project.json since #14405 (this issue does not exist with #14404). This manifests with the error:

```
> `proc macro `Serialize` not expanded: No proc-macros present for crate`
```

However, rust-analyzer still correctly identifies the source crate, `_serde_derive_1.0.152`. 

I haven't fully tracked down the issue, but I've noticed that in [`hir-def/src/nameres/collector.rs`](https://github.com/rust-lang/rust-analyzer/blob/90340b71ad0b640c344a0c6ef6d7da8a6673d762/crates/hir-def/src/nameres/collector.rs) the `CrateId` for `serde_derive` in `db.crate_graph()` is 27, but in `db.proc_macros()`, `serde_derive` has a `CrateId` of 16. I'll dig into this more tomorrow.

**Comment by Veykril** [comment]
Ah, I know why I think. We only set the proc-macros if build scripts have run, otherwise we overwrite it for a better diagnostic which obviously causes problems in case of `rust-project.json` which usually skips the build script step

**Comment by Veykril** [comment]
Okay there seem to be two bugs here, the id mismatch (which conveniently has a difference of 11 which is exactly the number of sysroot crates r-a knows about :) ) and us not loading proc-macros when build-scripts don't run.

**Comment by Veykril** [comment]
Okay I found the id mismatch bug I think, will push out a PR for that

**Comment by Veykril** [comment]
The relevant part there is here https://github.com/rust-lang/rust-analyzer/blob/b99d5eb97315faca04a33bae40bd2fb809ba9d46/crates/rust-analyzer/src/reload.rs#L450-L463

Note that we only call `self.fetch_proc_macros_queue.request_op(cause, proc_macro_paths);` in the `same_workspaces` branch which only happens when `switch_workspaces` is called without changing workspaces, which only occurs from build scripts being finished building. The reason for that is better diagnostics when proc-macros arent loaded yet (but will be). There is probably a better way to handle that though.

**Comment by davidbarsky** [comment]
Resolved by https://github.com/rust-lang/rust-analyzer/pull/14419.

**Comment by davidbarsky** [comment]
> The relevant part there is here https://github.com/rust-lang/rust-analyzer/blob/b99d5eb97315faca04a33bae40bd2fb809ba9d46/crates/rust-analyzer/src/reload.rs#L450-L463
> 
> 
> 
> Note that we only call `self.fetch_proc_macros_queue.request_op(cause, proc_macro_paths);` in the `same_workspaces` branch which only happens when `switch_workspaces` is called without changing workspaces, which only occurs from build scripts being finished building. The reason for that is better diagnostics when proc-macros arent loaded yet (but will be). There is probably a better way to handle that though.

Thanks for pointing this out—I'll play around with this bit and see if I can make this a little better in the process.
