### ISSUE TITLE
Autocomplete not working on modules in folders

### ISSUE THREAD

**Issue by Zatarita** [rust-lang/rust-analyzer#14414]
I've tried googling/searching around for a solution, and I feel like it might be something stupid. I feel since I don't see any other issues like this though I might be doing something wrong, and if I am I'm sorry for wasting time 😞 

For some reason any time I have a mod.rs defined in a separate folder, autocomplete just stops working. Everything else works fine (error checking, syntax highlighting, etc), but autocomplete doesn't. The program compiles fine, and finds the external mod.rs in the folder; however, in order to write my code with autocomplete I have to use my main.rs/lib.rs file, and copy it over at the end. This gets kinda cluttered and confusing in larger projects

my current project for example:
![image](https://user-images.githubusercontent.com/51307516/227792663-76f4da87-3c81-4315-92bb-1ffe6e45ca6c.png)

Then when I load into the mod.rs and try to do a use statement I don't get any useful autocomplete features.
(no "std::fs")
![image](https://user-images.githubusercontent.com/51307516/227793176-8fef71d3-3676-4137-b7f1-ebe60f6a0fbc.png)
(No "String")
![image](https://user-images.githubusercontent.com/51307516/227793111-dc80307d-850b-40e0-81da-8d7637f2f7c1.png)
(No "None")
![image](https://user-images.githubusercontent.com/51307516/227793133-f21a88e2-12bc-478e-b494-03ee76730c54.png)

Am I doing something wrong?
I tried switching to the nightly build, and checking the settings; however, I've had no luck.

**Comment by Veykril** [comment]
Given the three dots at the start of the screenshots of your `mod.rs` I assume that r-a fails to figure out where the module belongs to (that should be an unlined file diagnostic). Now why that happens I can't really tell, do you have anything special in your `Cargo.toml` that may affect the project layout?

If on windows, was the `definition` folder previously named `Definition` (or the `mod.rs` `Mod.rs`?

**Comment by Zatarita** [comment]
🤔  I'm not quite sure if it was capitalized.
I know the mod definition in main got auto completed to capital, so that may be possible.
Is it maybe a caching issue?

**Comment by Veykril** [comment]
VScode caches filenames which breaks things on windows since its a case-insensitive filesystem, so you'll need to clear the vscode cache for your workspace
https://github.com/rust-lang/rust-analyzer/issues/13488 https://github.com/rust-lang/rust-analyzer/issues/13483

**Comment by Zatarita** [comment]
That's annoying 😞 
thank you, that makes a lot of sense. I was reading stuff about that, but I didn't think it related to my issue as I've had it in a few of my projects.

Another reason in my list of reasons to move away from windows.

Thank you, I appreciate your time.
