### ISSUE TITLE
`linker 'cc' not found` on x86_64-unknown-none target

### ISSUE THREAD

**Issue by kennystrawnmusic** [rust-lang/rust-analyzer#14420]
Although running cargo from the command line builds [my project](https://github.com/kennystrawnmusic/cryptos) with no issues whatsoever, RA's automatics aren't seeing it that way. Instead, RA throws `error: linker cc not found` when attempting to check on save, despite the command line building everything successfully.

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

rust-analyzer version: 0.4.1450-standalone

**rustc version**: (eg. output of `rustc -V`)

rustc 1.70.0-nightly (db0cbc48d 2023-03-26)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

`RUSTUP_HOME` and `CARGO_HOME` both set to `/opt/rust` in `/etc/bash.bashrc`

Content of `.vscode/settings.json`:

```json
{
    "rust-analyzer.check.targets": ["x86_64-unknown-none"],
    "rust-analyzer.check.allTargets": false,
    "rust-analyzer.restartServerOnConfigChange": true,
    "rust-analyzer.check.extraArgs": [
        "--bins"
    ],
    "rust-analyzer.server.extraEnv": {
        "RUSTUP_HOME": "/opt/rust",
        "CARGO_HOME": "/opt/rust",
        "PATH": "/opt/rust/bin:$PATH"
    }
}
```

**Comment by bjorn3** [comment]
Does it work if you replace `$PATH` in your config with the output of `echo $PATH`?

**Comment by kennystrawnmusic** [comment]
> Does it work if you replace `$PATH` in your config with the output of `echo $PATH`?

Yes it does. Closing. Only issue with hardcoded paths though is that they differ from host to host; will have to open a new issue to deal with that.
