### ISSUE TITLE
thread 'Worker' has overflowed its stack

### ISSUE THREAD

**Issue by tomm2000** [rust-lang/rust-analyzer#14421]
This code crashes rust-analyzer. (`thread 'Worker' has overflowed its stack`)

```rust
pub enum Tree {
  Node(TreeNode),
  Leaf(TreeLeaf),
}

pub struct TreeNode {
  pub depth: usize,
  pub children: [Box<Tree>; 8]
}

pub struct TreeLeaf {
  pub depth: usize,
  pub data: u8
}

pub fn test() {
  let tree = Tree::Leaf(
    TreeLeaf {
      depth: 0,
      data: 0
    }
  );
}
```

The issue seems to be with the creation of the tree, commenting out the body of the `test` function stops the error from occurring.

rust-analyzer version (VS-code): v0.3.1451

also tried pre-release version: v0.4.1450, the error still occurs.

**Comment by Veykril** [comment]
@HKalbasi this seems to be a MIR problem
