### ISSUE TITLE
Fat arrow is not handle correctly

### ISSUE THREAD

**Issue by KamilDuljas** [rust-lang/rust-analyzer#14447]
**rust-analyzer version**: 0.4.1454-standalone (17e31b7d3 2023-03-29)

**rustc version**: 1.68.0 (2c8cc3432 2023-03-06)

Proposal Rust-Analyzer is the changing of thin arrow to thin arrow

![image](https://user-images.githubusercontent.com/87798948/228779349-048f750b-9106-467b-a4a8-cbae6a38bc41.png)

**Comment by lnicola** [comment]
The suggestion is not from rust-analyzer, but from rustc, and it is in fact correct, if something misleading.

The message is not "use `->` instead of `->`", but rather "use `->` instead: `->`". What happens is that we display the rustc message, then the suggested replacement.

**Comment by KamilDuljas** [comment]
Yes, indeed. After added, I understood the thing... but it is really missleading.

**Comment by lnicola** [comment]
I think displaying the replacement is useful in some cases, but I couldn't find one.
