### ISSUE TITLE
rust-analyzer failed to load workspace

### ISSUE THREAD

**Issue by SirSharanChakradhar** [rust-lang/rust-analyzer#14462]
**ERROR**: [ERROR rust_analyzer::main_loop] FetchWorkspaceError:
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/sharan/rust/apr1/Cargo.toml, Some(Version { major: 1, minor: 68, patch: 2 }): Failed to run `cd "/home/sharan/rust/apr1" && "cargo" "metadata" "--format-version" "1" "--manifest-path" "/home/sharan/rust/apr1/Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error:     Updating crates.io index
error: failed to select a version for the requirement `neo4j = "^4.0.0"`
candidate versions found which didn't match: 0.0.0
location searched: crates.io index
required by package `apr1 v0.1.0 (/home/sharan/rust/apr1)`

~ I knew neo4j to be neo4rs yet dont solve the problem.

**rust-analyzer version**: 0.3.1451

**rustc version**: rustc 1.68.2 (9eb3afe9e 2023-03-27) (Arch Linux rust 1:1.68.2-1)

![Screenshot_2023-04-01-12-34-11_2256x1504](https://user-images.githubusercontent.com/40011522/229260083-9e45edc0-d053-4d40-a75b-0829135bda36.png)

**Comment by flodiebold** [comment]
So does running `cargo check` in your workspace work, or give the same error?

**Comment by ginkcode** [comment]
I got the same error on MacOS recently. Looks like after updating VSCode.
This is the Cargo.toml in the project:
```toml
[workspace]

members = ["ohcl", "common"]
```

And hitting this issue:
```
[ERROR rust_analyzer::main_loop] FetchWorkspaceError:
rust-analyzer failed to load workspace: cd "/ohcl" && "cargo" "--version" failed: No such file or directory (os error 2)
```

**Comment by SirSharanChakradhar** [comment]
Deleting /home/$user/.cargo and running cargo update worked.

**Comment by spektom** [comment]
I had non-existent linked project inside `<project dir>/.vscode/settings.json`.
Once this file was deleted, everything returned back to normal.

**Comment by ferruccio** [comment]
I had a non-existant project in settings.json too. However deleting the file did not help. I finally resolved the issue by switching from the pre-release version of rust-analyzer to the release version (v0.3.1463).

Also, I only saw this problem editing remote projects using the Remote SSH extension. Never with local projects.
I've also only seen this on macOS, but not on Linux.

**Comment by ginkcode** [comment]
I encountered this issue with local project.
Not sure what is causing exactly and non of above suggestion works.
I have to clone the project to another directory and the issue is gone, quite weird.

**Comment by joe733** [comment]
I'm getting a similar error:

```rs
[ERROR rust_analyzer::main_loop] FetchWorkspaceError:
rust-analyzer failed to load workspace: cd "/home/us-er/.../my-project" && "cargo" "--version" failed: No such file or directory (os error 2)
```

Whereas when I run via VSCode, It works just fine:

```console
$ cargo check
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
```

> Probably related: #14477 #14492 #14740
