### ISSUE TITLE
type-mismatch with async fn's + ? operator

### ISSUE THREAD

**Issue by jhgg** [rust-lang/rust-analyzer#14479]
minimal repro:

```rust
async fn foo() -> Result<(), ()> {
    Ok(())
}

async fn bar() -> Result<(), ()> {
    let x = foo().await?;
    Ok(x)
 // ^^^^^ type-mismatch: expected impl Future<Output = {unknown}>, found Result<(), {unknown}>
}
```

rust-analyzer version: 0.4.1460-standalone
rustc 1.66.1 (90743e729 2023-01-10)

I think this is a rather recent regression. It seems to first appear in nightly 0.4.1457 - so this is probably a broken window?

**Comment by Veykril** [comment]
LIkely has regressed with https://github.com/rust-lang/rust-analyzer/pull/14461

**Comment by jplatte** [comment]
I also get `expected impl Future<Output = {unknown}>, found impl Future<Output = {unknown}>` inside an async function for an expression that doesn't involve any futures..

Probably related.

![Screenshot_2023-04-04_114815](https://user-images.githubusercontent.com/951129/229754644-0bc03a0f-07e7-4ec7-baaa-64db6ab6360d.png)

**Comment by HKalbasi** [comment]
Every async function with `?` operator is affected.
