### ISSUE TITLE
rustup component add rust-analyzer says it is up to date, but according to the releases page here it is not

### ISSUE THREAD

**Issue by AddictArts** [rust-lang/rust-analyzer#14484]
As the title says this is very confusing. I believe rust-analyzer is not up to date, but rustup update does not update it, or at least that I can see.

```shell
~> rustup run stable rust-analyzer --version
rust-analyzer 1.68.2 (9eb3afe9 2023-03-27)
```

The latest stable is 4-2-23

There are no docs on updating either. I'm not in the VSCode, or Neovim, vim situation. So, those docs and others are not helpful. I'm in the helix camp, which doesn't have a mention.

**Comment by lnicola** [comment]
You can get an up-to-date binary from GitHub Releases.

**Comment by flodiebold** [comment]
The rustup version lags behind a bit. You'll have to either wait until it's updated, download a release from the releases page manually, or build it yourself.

**Comment by AddictArts** [comment]
Thanks @lnicola and @flodiebold. I was following the manual install, specifically the `rustup` way. I think for me the confusion is there is no mention of how to actually update from an existing manual install, either from source, binary, or `rustup`. I'll wait and see if `rustup update` picks it up next time since it lags behind.

For anyone else who ends up here, just copying the binary and `.pdb` from the zip into your `.rustup` folder following the docs where is it installed worked. Thanks again.

**Comment by lnicola** [comment]
If you install it with `rustup`, you can update with `rustup update`, but that will give you very slow (~months old) updates.

If you download a binary from GitHub, you can put it anywhere in `PATH` (like `~/.cargo/bin` or `%USERPROFILE%\.cargo\bin`), and update it when you want.

I don't recommend replacing anything that `rustup` installed.
