### ISSUE TITLE
Feature request: autofill trait impls

### ISSUE THREAD

**Issue by the-jasoney** [rust-lang/rust-analyzer#14502]
Let's say I have the trait
```rs
trait MyTrait {
	fn foo() -> u32;
	fn bar() -> i64;
	fn baz() -> f64 {
		0.15
	}
}
```

and I want to implement it for some struct `MyStruct`. Right now, I have to fill out the functions one-by-one, which can be tedious for larger traits. What I suggest is to autofill a trait implementation with functions returning `todo!()`, like this:

```rs
impl MyTrait for MyStruct {
	fn foo() -> u32 {
		todo!()
	}
	fn bar -> i64 {
		todo!()	
	}
	// `baz()` does not need to be autofilled as it already has a default implementation
}
```

**Comment by Veykril** [comment]
We already have an assist for filling the required functions (and one for filling the default implemented functions as well)

**Comment by hecatia-elegua** [comment]
Just as a quick answer which might not work for your editor/setup:
```rust
impl MyTrait for MyStruct {
    $0
}
```
with $0 being the cursor: in vscode, press ctrl+. for showing quick fix, then enter
