### ISSUE TITLE
 Failed to read Cargo metadata from Cargo.toml file /Cargo.toml

### ISSUE THREAD

**Issue by vilinski** [rust-lang/rust-analyzer#14507]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
rust-analyzer version: 0.3.1463-standalone

**rustc version**: (eg. output of `rustc -V`)
rustc 1.68.2 (9eb3afe9e 2023-03-27)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
nothing is set

MacOS Ventura 13.3
M1 Max 32GB
There are no problems in local rust repos.
But this workspace is opened over ssh connections. The rust-analyser is installed.
Is it possible that Cargo.toml path is wrong? I is shown as /Cargo.toml, but really it is under /home/username/workspace/reponame/Cargo.toml

```
[ERROR rust_analyzer::main_loop] FetchWorkspaceError:
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /Cargo.toml, Some(Version { major: 1, minor: 68, patch: 2 }): Failed to run `cd "/" && "cargo" "metadata" "--format-version" "1" "--manifest-path" "/Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error: error: manifest path `/Cargo.toml` does not exist
```

**Comment by lnicola** [comment]
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/14480. Can you install a nightly version (there's an option on the extension page) and then remove `rust-analyzer.linkedProjects` from your settings?

**Comment by vilinski** [comment]
that worked.
closing as a duplicate of #14480
