### ISSUE TITLE
Sort items by trait definition assist is too applicable

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14515]
```rs
trait Trait {
    fn func() {}
    fn func2() {}
}

impl Trait for () {
    fn func2() {
        $0
    }
    fn func() {}
}
```
with the cursor at $0, the assist is being shown which is noisy. We should make it only trigger on the impl header and signatures of the associated items, not their bodies.

**Comment by Veykril** [comment]
relevant code is here https://github.com/rust-lang/rust-analyzer/blob/3dd17bcfc3d0e4d4e0c711828887d6f31602e415/crates/ide-assists/src/handlers/reorder_impl_items.rs#L45-L94

**Comment by ClSlaid** [comment]
May I pick this as my first contribution to rust tools?

**Comment by Veykril** [comment]
go ahead!
