### ISSUE TITLE
Sort methods alphabetically assist is too applicable

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14516]
```rs
struct S;
impl S {
    fn func2() {
		$0 bar $0
	}
    fn func() {}
}

```
With the cursor at from the first to the second $0 (effectively a selection), the sort methods alphabetically assist triggers, we should only make it trigger when the selection is within the impl header or in the signature of one of the associated items, not their bodies.

**Comment by Veykril** [comment]
relevant code is here https://github.com/rust-lang/rust-analyzer/blob/3dd17bcfc3d0e4d4e0c711828887d6f31602e415/crates/ide-assists/src/handlers/sort_items.rs#L84-L109

**Comment by DropDemBits** [comment]
Issue seems to have been double-posted

**Comment by Veykril** [comment]
No these assists are 2 different ones
