### ISSUE TITLE
Find all references, exclusing test configuration

### ISSUE THREAD

**Issue by chamons** [rust-lang/rust-analyzer#14530]
I often want to find the usages of a references, but for some APIs there can be many more usages in test code than elsewhere.

As rust's default is to place test code in the same file, it can be difficult to determine which usages are which without expanding each instance.

In C#, it is relatively simple to work around this by excluding folders or unload test projects.

Would it be possible to add either a new "Find all non-test references", or a project setting to exclude refernces in a test Cfg scope?

**Comment by chamons** [comment]
I have some interest in this and would be willing to spend some time implementing it if it's found acceptable.

**Comment by Veykril** [comment]
We have something similar for imports already here https://github.com/rust-lang/rust-analyzer/blob/01120f1213ad928de7300a8acf9f41bed72d0422/crates/rust-analyzer/src/config.rs#L443
So you can likely take inspiration from that to add another config but for test things (though I believe this will be trickier to do properly)

**Comment by kurotych** [comment]
Hi, @chamons Did you have any chance to find a solution? I struggle with the same issue.

**Comment by Young-Flash** [comment]
I'll try working on this

**Comment by chamons** [comment]
I have not found a solution nor time to work on this.

**Comment by chamons** [comment]
Thank you @Young-Flash for running this down!

I'm super excited for this. ❤️

**Comment by Young-Flash** [comment]
you can try it out at the next nightly release and give some feedback :)
