### ISSUE TITLE
Auto-completion for enums in associated types

### ISSUE THREAD

**Issue by sayaks** [rust-lang/rust-analyzer#14543]
If i create an associated type like this:

```rs
trait MyTrait {
    type Enum;
}

enum MyEnum {
    AVariant,
    BVariant,
    CVariant,
}

struct MyStruct();

impl MyTrait for MyStruct {
    type Enum = MyEnum;
}
```

If i do this:

```rs
let a = <MyStruct as MyTrait>::Enum::_;
```

I don't get any auto-completion suggesting all the variants of this enum.

**Comment by lowr** [comment]
Thanks for the report! This is actually a duplicate of #14393 so let me close this issue in favor of that.
