### ISSUE TITLE
symbol index ignores doc aliases

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14557]
We should handle doc aliases somewhere around here https://github.com/rust-lang/rust-analyzer/blob/dd5c3c30b6379a92d69e964327cf97963a6d6143/crates/hir/src/symbols.rs#L129-L195

We don't seem to have testing infra for this functionality per se, so it would be good to add that as well for https://github.com/rust-lang/rust-analyzer/blob/dd5c3c30b6379a92d69e964327cf97963a6d6143/crates/ide-db/src/symbol_index.rs

(On a side note, it seems odd to me that this is implemented in `hir` and not in `ide-db`)

**Comment by hecatia-elegua** [comment]
Is this relevant to #14513 ?

**Comment by Veykril** [comment]
No they are different things, the symbol index is used for symbol search, completions or rather autoimport completions go through a different machinery (import_map)

**Comment by hecatia-elegua** [comment]
Ah, it's that symbol search feature. Good to know
