### ISSUE TITLE
Rust analyzer complaining 3 to 4 times of the same error in vs code

### ISSUE THREAD

**Issue by Cyberphinx** [rust-lang/rust-analyzer#14552]
**rust-analyzer version**: v0.3.1472

**rustc version**: 1.68.2

**Visual Studio Code version**: 1.77.2

**OS**: Fedora 37

![Screenshot from 2023-04-11 23-49-16](https://user-images.githubusercontent.com/88593809/231443072-b235e0f1-2e81-4776-92c0-f874797da6fa.png)

![Screenshot from 2023-04-12 09-52-58](https://user-images.githubusercontent.com/88593809/231443188-899c183f-2a75-4b17-8a8b-ef9cb6708f6b.png)

![Screenshot from 2023-04-12 09-55-54](https://user-images.githubusercontent.com/88593809/231443192-47d71670-16ce-4b14-93cd-acefe365f5c7.png)

**Comment by Veykril** [comment]
Are you using vscode workspaces in some way here? I recall issues with that because it effectively registers the cargo workspace multiple times for rust-analyzer

**Comment by Cyberphinx** [comment]
I have solved this as I found out that cargo.toml was added multiple times in the settings.json file under .vscode.
