### ISSUE TITLE
proc macro `Serialize` not expanded: server is built without sysroot support

### ISSUE THREAD

**Issue by antonilol** [rust-lang/rust-analyzer#14554]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
0.3.1472-standalone
Code OSS from archlinux repos, version: 1.77.1-1

**rustc version**: (eg. output of `rustc -V`)
rustc 1.63.0 (4b91a6ea7 2022-08-08)
(controlled by a rust-toolchain file)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
None

title, this happens with proc macros Serialize and Deserialize from serde_derive 1.0.159

![image](https://user-images.githubusercontent.com/49868160/231525473-a57dc591-dc57-4787-b646-7a57a5762c93.png)

**Comment by lnicola** [comment]
We no longer support proc macro expansion in toolchains older than 1.64.

**Comment by Jake-Jensen** [comment]
rust-analyzer version: 0.3.1472-standalone

rustc version: rustc 1.65.0

relevant settings: None

Same issue, different macro. 

![image](https://user-images.githubusercontent.com/15312520/232242936-8f6bbeca-b12b-4d00-b05f-64983bbc72c3.png)

**Comment by anks333** [comment]
use this "rust-analyzer.diagnostics.disabled": ["unresolved-proc-macro"]

**Comment by flodiebold** [comment]
That does not fix the problem, only hide it. @Jake-Jensen what does `ls $(rustc --print sysroot)/libexec` say?

**Comment by antonilol** [comment]
on <= 1.63.0 i have no `rust-analyzer-proc-macro-srv`, does it not exist or is it not supported anymore for those versions so it got removed?

```
$ ls .rustup/toolchains/*/libexec
.rustup/toolchains/1.63.0-x86_64-unknown-linux-gnu/libexec:
cargo-credential-1password

.rustup/toolchains/1.64.0-x86_64-unknown-linux-gnu/libexec:
cargo-credential-1password  rust-analyzer-proc-macro-srv

.rustup/toolchains/stable-x86_64-unknown-linux-gnu/libexec:
cargo-credential-1password  rust-analyzer-proc-macro-srv
```

will symlinking the 1.64 version to the 1.63 version work? (probably not lol)

**Comment by lnicola** [comment]
It didn't exist in that form before 1.64. You can try a symlink, but you should consider upgrading.

**Comment by lnicola** [comment]
@Jake-Jensen are you using the Arch Linux `rust` package?

**Comment by Jake-Jensen** [comment]
That was a default Ubuntu 22.04.x LTS install, with Rust and associated packages installed via https://rustup.rs/ script, with nighly toolchain selected.

**Comment by bigduu** [comment]
![image](https://github.com/rust-lang/rust-analyzer/assets/18681616/a6386a3b-2ef0-4f2d-b433-ccf558adfd33)
![image](https://github.com/rust-lang/rust-analyzer/assets/18681616/7f260978-68d6-4ebe-a7c2-0b6241efd7da)
My rust is 1.7.1 version, still face the same issue

**Comment by lnicola** [comment]
@bigduu feel free to file a new issue, making sure to include the information requested in the template.
