### ISSUE TITLE
Unable to click into `include!`'d sources; possibly spurious `need-mut` lint

### ISSUE THREAD

**Issue by davidbarsky** [rust-lang/rust-analyzer#14562]
I'm trying out 14561—it's wonderful to be able to get definitions from protoc-generated code!—but unfortunately, I'm getting a bunch of `need-mut` errors from rust-analyzer at https://github.com/facebook/buck2/blob/f9e261bc956d48f587bfe6777b4de84ec1898bdc/app/buck2_data/src/lib.rs#L161.

(this could be a nightly toolchain-related thing or a prost-related thing; I haven't diagnosed this yet). I'm encountered two issues:

1. I can't click into the `include!`'d code. I'm guessing this might be followup work, but it'd be nice!
2. [`need-mut`](https://rust-analyzer.github.io/manual.html#need-mut) might be spurious, since `rustc` is seemingly fine with it.
   1. This might be related to prost more than anything.

**rust-analyzer version**: rust-analyzer version: 0.0.0 (901c8a425 2023-04-13)

**rustc version**: (eg. output of `rustc -V`) rustc 1.69.0-nightly (c8e6a9e8b 2023-01-23) (it's a `RUSTC_BOOTSTRAP`. long story.)

**Comment by Veykril** [comment]
> I can't click into the `include!`'d code. I'm guessing this might be followup work, but it'd be nice!

If you mean not having any ide features in the included file, that's to be expected. Handling those as proper input will require https://github.com/rust-lang/rust-analyzer/issues/9403 and even with it, it's not 100% certain we'll be able to support that.

> [need-mut](https://rust-analyzer.github.io/manual.html#need-mut) might be spurious, since rustc is seemingly fine with it.

Would be great if you could figure out a repro that causes it if it's not too much work

**Comment by HKalbasi** [comment]
> though I think we don't currently honor the corresponding rustc allow lint

That is for `unused-mut`, as `need-mut` is a hard error in rustc, so it is always a bug.

@davidbarsky my r-a doesn't work on buck2 repository, should I run something to generate `rust-project.json`?

**Comment by davidbarsky** [comment]
> That is for `unused-mut`, as `need-mut` is a hard error in rustc, so it is always a bug.

gotcha.

> @davidbarsky my r-a doesn't work on buck2 repository, should I run something to generate rust-project.json?

You shouldn't need to—I'd suggest `cd`ing into `app/buck2_data/` and opening rust-analyzer there. Cargo should _just work_, as that's how I was able to discover this issue in the first place.

(I'm working on open-sourcing the tool that generates the `rust-project.json`. I'll let you know when it's out; it'll be under the buck2 repo.)

**Comment by HKalbasi** [comment]
Minimized:
```Rust
fn x() {
    let x = &mut 2;
    || *x = 5;
}
```

**Comment by Veykril** [comment]
Ah, those are unique immutable borrows https://doc.rust-lang.org/stable/reference/types/closure.html#unique-immutable-borrows-in-captures
