### ISSUE TITLE
`relevant_parmas_and_where_clauses` is dangling

### ISSUE THREAD

**Issue by jsoref** [rust-lang/rust-analyzer#14567]
https://github.com/rust-lang/rust-analyzer/blob/2c251a7e2bdd44120f900063bc1809c1475a7372/crates/ide-assists/src/handlers/generate_function.rs#L896

It was introduced in #14065 in https://github.com/rust-lang/rust-analyzer/commit/3edde6fcc1506d5c1bf7c74e42defaa44423595c#diff-e36280c9e19413d3eab3f92468e2cd3a9798708843c568a8b6f7a184b5d6c129R881

I can't figure out what it's trying to say.

**Comment by lnicola** [comment]
`fn_generic_params` or `filter_unnecessary_bounds`, I suspect.

**Comment by lowr** [comment]
That's former name of `params_and_where_preds_in_scope()`, apparently I forgot to update the comment when I renamed that function. Sorry for the confusion!

**Comment by jsoref** [comment]
The typo of `params` is probably why the rename failed here.

I might have time to bundle this into a PR today...
