### ISSUE TITLE
CodeLens showing up as !!MISSING: command!! in VS Code

### ISSUE THREAD

**Issue by MariaSolOs** [rust-lang/rust-analyzer#14568]
**rust-analyzer version**: 0.4.1476-standalone (2c251a7e2 2023-04-13)

**rustc version**: 1.70.0-nightly (ec2f40c6b 2023-03-30)

In VS Code Insiders (version 1.78.0-insider, commit c9df8ee8e8c316f38dcc75a894ba150024ce3718), code lenses have the wrong label as shown below, and clicking on them also results in an error notification:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/62502207/231948297-07da9d91-81de-4e78-a211-f1b924a0b684.png">
<img width="519" alt="image" src="https://user-images.githubusercontent.com/62502207/231948673-c9ad33da-0a41-4c5d-a738-76586c437433.png">

So far I've only been able to see this in implementation lenses, the ones for tests seem to be working fine.

**Comment by Veykril** [comment]
Caused by https://github.com/rust-lang/rust-analyzer/pull/14559, we use the file version of the wrong file

**Comment by MariaSolOs** [comment]
@Veykril oops sorry for the duplicate!

**Comment by Veykril** [comment]
no duplicate here, just something I realized looking at the PR after this issue

**Comment by MariaSolOs** [comment]
I'm unsorry then lol.
