### ISSUE TITLE
Parameter hints render incorrectly with colon typed

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14595]
```rs
fn f(x:) {
    let y: i32 = x;
}
```
![image](https://user-images.githubusercontent.com/3757771/232537565-1c7dbab6-2a9a-430a-afb8-b9a65959d0b4.png)

Same for closures of course. We should render the hint without the colon after the colon, not in front.

**Comment by Milo123459** [comment]
I would like to work on this. Where is the code located for inlay hints? It is not in the editors/code directory, so I'm not sure as I presumed this was a client thing, not a server thing

**Comment by Veykril** [comment]
Here https://github.com/rust-lang/rust-analyzer/blob/2feabc4dc462644287372922928110eea4c60ca7/crates/rust-analyzer/src/to_proto.rs#L434-L518 and here https://github.com/rust-lang/rust-analyzer/blob/2feabc4dc462644287372922928110eea4c60ca7/crates/ide/src/inlay_hints/bind_pat.rs#L20-L75

**Comment by Milo123459** [comment]
so if there is a colon, tell it to render afterwords?

**Comment by Veykril** [comment]
yes, if the colon is there, we want to render the hint after the colon without the colon in the hint
