### ISSUE TITLE
Errors being returned that are not actually valid

### ISSUE THREAD

**Issue by breqdev** [rust-lang/rust-analyzer#14612]
Hi there!

I'm running into an issue with rust-analyzer giving me red squiggles for code that actually has no errors. I have the following function:

<details>
<summary>Code</summary>

```rust
    fn draw_rom_location(ui: &mut egui::Ui, active: bool, input: &mut String, value: &mut u16) {
        egui::Frame::none()
            .stroke(egui::Stroke::new(
                2.0,
                if active {
                    egui::Color32::RED
                } else {
                    egui::Color32::BLACK
                },
            ))
            .show(ui, |ui| {
                let response = ui.add(
                    egui::TextEdit::singleline(input)
                        .font(egui::TextStyle::Monospace)
                        .desired_width(30.0)
                        .frame(false),
                );

                if response.gained_focus() {
                    *input = "".to_string();
                }

                if response.lost_focus() {
                    if ui.input().key_pressed(egui::Key::Enter)
                        || ui.input().key_pressed(egui::Key::Tab)
                    {
                        *value = u16::from_str_radix(input, 16).unwrap_or(0);
                    }

                    *input = format!("{:04X}", value);
                }
            });
    }
```

</details>

This specific closure is being highlighted as an error:

<img width="702" alt="Screenshot 2023-04-19 at 10 31 57 PM" src="https://user-images.githubusercontent.com/13875971/233242577-dce86f09-2e0b-43ef-9e13-b253c7351cbd.png">

The error given is "cannot mutate immutable variable `value`", but `value` is a `&mut u16` (and accepting the quick fix suggestion just gives me a warning about "variable does not need to be mutable"):

<img width="702" alt="Screenshot 2023-04-19 at 10 32 56 PM" src="https://user-images.githubusercontent.com/13875971/233242690-5dc9b677-a1d7-44bf-889f-eed6ef6b7e81.png">

**`cargo check` or `cargo build` builds the project with no errors.**

The issue does not occur after downgrading to version 0.3.1472-standalone (01120f121 2023-04-07).

**rust-analyzer version**: 0.3.1481-standalone (bab80dae4 2023-04-16)

**rustc version**: Tested on both rustc 1.67.0 (fc594f156 2023-01-24) and rustc 1.68.2 (9eb3afe9e 2023-03-27)

**relevant settings**: None changed from defaults

**Comment by HKalbasi** [comment]
Thanks for the report. Can you please minimise the problem? It would be great if the reproduction doesn't have dependencies. I will look at it when I find a computer.

**Comment by HKalbasi** [comment]
Minimized:
```Rust
fn draw_rom_location(value: &mut u16) {
    || {
        *value = 2;
        &value;
    };
}
```

**Comment by Veykril** [comment]
On a second note, its weird the entire closure gets underlined instead of just `value` no?

**Comment by HKalbasi** [comment]
Yes, it's bad. It is worse than what I initially thought.
