### ISSUE TITLE
Add cargo xtask uninstall option

### ISSUE THREAD

**Issue by embeddedpenguin** [rust-lang/rust-analyzer#14638]
I'd really like an option to uninstall the same way install was run so I know for sure rust-analyzer and all dependencies (especially npm modules) are removed.  In the meantime, what is the proper way to uninstall rust-analyzer and all of its dependencies when installed through `cargo xtask install`? Can I just remove ~/.cargo/bin/rust-analyzer and then remove the rust-analyzer repo? Or does it touch files in other locations as well?

**Comment by Veykril** [comment]
`cargo uninstall rust-analyzer` should work I believe, https://doc.rust-lang.org/cargo/commands/cargo-uninstall.html (just removing the binary should be fine as well I imagine)

**Comment by lnicola** [comment]
The npm modules stay under the source checkout, you can just delete them if you want.

> Can I just remove ~/.cargo/bin/rust-analyzer and then remove the rust-analyzer repo? Or does it touch files in other locations as well?

You can uninstall the Code extension from Code itself.

**Comment by embeddedpenguin** [comment]
> `cargo uninstall rust-analyzer` should work I believe, https://doc.rust-lang.org/cargo/commands/cargo-uninstall.html (just removing the binary should be fine as well I imagine)

Gotcha. Didn't realize it was added as an actual cargo package like that. Thanks
