### ISSUE TITLE
Complete callable fields when used in a method call position

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14656]
```rs
struct S {
    field: fn()
}

S { field: || {} }.fi$0()
```
Here we should complete the field (as if it was a method call) and automatically wrap the receiver in a pair of parens to fix up the call:
```rs
struct S {
    field: fn()
}

(S { field: || {} }.field)($0)
```

**Comment by dfireBird** [comment]
I assume this issue is free to work on, right? I've created a [Zulip discussion thread](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Complete.20callable.20fields.20issue.20.2314656) for it as well.
