### ISSUE TITLE
rust-analyzer still active when it should be uninstalled

### ISSUE THREAD

**Issue by comblock** [rust-lang/rust-analyzer#14650]
rust-analyzer kept giving me the error "can't find crate for `test`" but in my .vscode/settings.json even when I set check.allTargets to false and unsetTest for my crate as well as extraArgs ["--target", "arch.json"]

source:

```rs
// main.rs
#![no_std]
#![no_main]

use core::panic::PanicInfo;

#[cfg(not(test))]
#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}


#[no_mangle]
pub extern "C" fn _start() -> ! {
    loop {}
}
```

```jsonc
// settings.json
{
    "rust-analyzer.check.extraArgs": ["--target", "arch.json"],
    "rust-analyzer.check.allTargets": false,
    "rust-analyzer.cargo.unsetTest": [
        "core", "my_crate_name"
    ]
}
```

```jsonc
// arch.json
{
    "llvm-target": "x86_64-unknown-none",
    "data-layout": "e-m:e-i64:64-f80:128-n8:16:32:64-S128",
    "arch": "x86_64",
    "target-endian": "little",
    "target-pointer-width": "64",
    "target-c-int-width": "32",
    "os": "none",
    "executables": true,
    "linker-flavor": "ld.lld",
    "linker": "rust-lld",
    "panic-strategy": "abort",
    "disable-redzone": true,
    "features": "-mmx,-sse,+soft-float"
}
```

So, I uninstalled the vscode extension and planned to reinstall it, but rust-analyzer was (and is) still checking my code and giving the same error, even though it is uninstalled (it's also checking the code in other projects, it appears as though it is still installed somehow). I checked the vscode extensions folder and I couldn't find rust-analyzer. I did find a binary named rust-analyzer in /usr/bin but I think that's just part of rustup because when I execute `rust-analyzer` in a terminal it gives me this error: `error: 'rust-analyzer' is not installed for the toolchain 'stable-x86_64-unknown-linux-gnu'`. 

I'm on opensuse linux (tumbleweed).

note: Before I uninstalled rust-analyzer, I verified it was reading the settings.json by setting cargo features to "all", which rust-analyzer did respect.

**rust-analyzer version**: I don't know

**rustc version**: rustc 1.71.0-nightly and rustc 1.69.0

**relevant settings**: can be found in settings.json

**Comment by lnicola** [comment]
What do you mean it's still checking? Can you post a screenshot of the extensions panel and of the errors you're getting?

**Comment by Veykril** [comment]
Note that uninstalling an extension from VSCode does not deactivate said extension until the VSCode instance has been closed.

**Comment by lnicola** [comment]
Are you sure that's not your Cargo extension? I don't have experience with it.

**Comment by comblock** [comment]
> Are you sure that's not your Cargo extension? I don't have experience with it.

Yeah that was it, apparently it checks the code using cargo check or something. 
Sorry for wasting everyone's time.
