### ISSUE TITLE
Watch for `Cargo.toml` changes without editor dependency

### ISSUE THREAD

**Issue by ModProg** [rust-lang/rust-analyzer#14669]
While ra in vs-code does watch for changes, e.g. from `cargo add`, this does not work in all other editors (e.g. neovim).

Would it be possible for rust-analyzer to watch for file changes on its own, or is that a problem due to the introduced platform specific behavior?

**Comment by Veykril** [comment]
This seems to be a client issue I think? If the client is used for file watching then we only see what it reports so it needs to watch for these outside changes itself.

**Comment by lnicola** [comment]
We have a server-side file watcher (`rust-analyzer.files.watcher`), but I think it used to be somewhat buggy.

**Comment by Veykril** [comment]
That one is only used if the client wants us to (or I think if the client gives us both options, we opt for the client watcher), don't quite remember. But given this works with VSCode but not rust-tools.nvim this seems to be a client watcher issue.

**Comment by ModProg** [comment]
Well rust-tools.nvim is just a wrapper around https://github.com/neovim/nvim-lspconfig, so the problem would be neovim's lsp client implementation not doing it correctly?

**Comment by ModProg** [comment]
I found an issue, claiming this to be added in the latest version: https://github.com/neovim/neovim/issues/16078.

What would be the setting to make ra do the watching `rust-analyzer.files.watcher` only lists the default=client at https://rust-analyzer.github.io/manual.html

**Comment by lnicola** [comment]
`"server"` should work.

**Comment by lnicola** [comment]
Nothing to do here, closing.
