### ISSUE TITLE
"Go to References"/"Find All References" incorrectly doesn't return any references on remote VS Code

### ISSUE THREAD

**Issue by davidbarsky** [rust-lang/rust-analyzer#14685]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>): a rust-analyzer built from `62c81d62932c458e23975191ecc124916be0b35e`, but it appears in older versions.

**rustc version**: (eg. output of `rustc -V`): rustc 1.69.0 (84c898d65 2023-04-16)

**relevant settings**: 
- VS Code is running on a remote Linux dev server.
- VS Code 1.75 (I know...), but also exists in VS Code 1.71.

**Description**

Hi! This bug report isn't really actionable at this time, but I'm opening in order to write down my notes and ask for pointers to better find a minimal reproduction/root cause. Anyways: I've found a case where "Go to References" does not return any results despite rust-analyzer having all other IDE functionality (Go to Definition, inlay hints, semantic highlighting, etc.) working correctly. Here are some details that I'm confident about in my debugging
- This issue exists for both Cargo and Buck-based versions of the project (there's a tool that generates a Cargo.toml from a `BUCK` file; some people still use it). The project is a decently sized Cargo workspace. As far as I'm aware, there is no meaningful difference between the Cargo-based version of Buck-based version of the project.
- The same issue _does not_ exist on a fully local instance of rust-analyzer on my Mac for the same project.
- The usage site missed by Go to References/Find All References has a correctly functioning Go To Definition that links back to where the symbol was defined.
- The symbol in question is an inherent method on a struct.

I haven't tested any other editors to confirm if its VS Code giving rust-analyzer bad information at startup.

Do you have any tips for me to debug this issue/create a minimal reproduction? 

(cc: @VladimirMakaev, who has reported this issue to me.)

**Comment by Veykril** [comment]
Fwiw go to definition is a bad comparison, definition look up is really simple (we always know where something was defined), while reference search requires to us to look through all files that *might* have uses of the symbol.

Overall this sounds very odd though and I can't even imagine what could be causing this in the server itself.

**Comment by davidbarsky** [comment]
> Fwiw go to definition is a bad comparison, definition look up is really simple (we always know where something was defined), while reference search requires to us to look through all files that might have uses of the symbol.

yeah, very fair. it was more to demonstrate what felt like the dual of reference search was working properly.

> Overall this sounds very odd though and I can't even imagine what could be causing this in the server itself.

Yeah, I was really surprised to get this report because it goes against _everything_ I know about how rust-analyzer works, let alone my expectations when using it. The reason I've spent time looking in the server itself is that the results themselves appear to be empty when I wrap some key values in a `dbg!`:

```
[crates/ide/src/references.rs:79] &usages = UsageSearchResult {
    references: {},
}
[crates/rust-analyzer/src/handlers.rs:1031] &refs = [
    ReferenceSearchResult {
        declaration: Some(
            Declaration {
                nav: NavigationTarget {
                    file_id: FileId(
                        2514,
                    ),
                    full_range: 815..1001,
                    focus_range: 876..903,
                    name: "set_command_template_values",
                    kind: Function,
                    description: "pub fn set_command_template_values(&mut self, values: HashMap<String, String>)",
                    docs: Documentation(
                        "Override the existing command template values",
                    ),
                },
                is_mut: false,
            },
        ),
        references: {},
    },
]
```

**Comment by Veykril** [comment]
Sounds odd, usually what r-a does is load up all relevant source files into memory and then deal with those to avoid doing i/o afterwards. Any file updates then are usually reported by the file watcher which is either the server or the client / text document change notifications from the client.

**Comment by davidbarsky** [comment]
> Sounds odd, usually what r-a does is load up all relevant source files into memory and then deal with those to avoid doing i/o afterwards.

Yeah, that's been my understanding and experience so far, and it lines up with my experience.

For what it's worth, I was wrong about it being related to Eden or the issue existing _across_ Cargo/rust-project.json projects. It turned out that I was accidentally loading the `rust-project.json` when I thought I was loading the output of `cargo metadata`. In retrospect, when I said "I moved an impacted project out of an Eden-backed folder and "Go to References"/"Find All References" started working again", those features only started working because I using a Cargo-based build, not a Buck-based build!

I think the _actual_ issue is that, under the hood, [rust-project](https://github.com/facebook/buck2/tree/main/integrations/rust-project) emits a separate `-unitttest` target/crate in the `rust-project.json`. For instance, here's a portions of the `rust-project.json` (with the dependencies section elided because it's not interesting or relevant):

```json
{
      "display_name": "fdb-buck-test",
      "root_module": "/home/dbarsky/fbsource/fbcode/hermetic_infra/fdb/fdb-buck-test/src/lib.rs",
      "edition": "2021",
      "deps": [],
      "is_workspace_member": true,
      "cfg": [
        "test"
      ],
      "env": {},
      "is_proc_macro": false
    },
    {
      "display_name": "fdb-buck-test-unittest",
      "root_module": "/home/dbarsky/fbsource/fbcode/hermetic_infra/fdb/fdb-buck-test/src/lib.rs",
      "edition": "2021",
      "deps": [],
      "is_workspace_member": true,
      "cfg": [
        "test"
      ],
      "env": {},
      "is_proc_macro": false
    },
```

I'm guessing the I reported issue stems from the fact that both these separate crates have the same root module (which, from `rustc`'s perspective, they very well might?), but I don't think that rust-analyzer's happy about that. How do y'all handle this case in with Cargo-based targets (especially those that have test deps)? Do you just combine the two "crates" into one, including their respective dependencies?

**Comment by Veykril** [comment]
We keep them separate, but most IDE features only consider the first crate (or rather, first module) in the crate graph for a given file when mapping file id to module currently.

**Comment by Veykril** [comment]
That is basically anything that uses https://github.com/rust-lang/rust-analyzer/blob/0d5773e04e2433fb7e5f08514426d2d5ce399427/crates/hir/src/semantics.rs#L465-L467

**Comment by Veykril** [comment]
and https://github.com/rust-lang/rust-analyzer/blob/0d5773e04e2433fb7e5f08514426d2d5ce399427/crates/hir/src/semantics/source_to_def.rs also quite often picks the first only

**Comment by davidbarsky** [comment]
> > We keep them separate, but most IDE features only consider the first crate (or rather, first module) in the crate graph for a given file when mapping file id to module currently.
> 
> gotcha. i'll try merging and/or skipping targets with `-unittest` with them and report back shortly. Thanks so much for your help and pointers.

skipping past the `-unittest` targets made find-all-refs work, thankfully. I'll close this out since it's not really a bug on rust-analyzer's end.
