### ISSUE TITLE
unresolved-method of impl IntoIterator<Item=...> as return type

### ISSUE THREAD

**Issue by boozook** [rust-lang/rust-analyzer#14680]
**rust-analyzer version**: 0.4.1493-standalone (237ffa399 2023-04-27)

**rustc version**: rustc 1.70.0-nightly (84dd17b56 2023-04-14)

<img width="1104" alt="Screenshot 2023-04-29 at 02 58 02" src="https://user-images.githubusercontent.com/888526/235266997-ac95239e-d5e3-4c4a-86db-92b7147be4ab.png">

Unfortunately I can't isolate it right now, but _probably_ that will be easy:
- use `cargo` crate
- create `config = cargo::util::config::Config::default()`
- create `workspace = cargo::core::workspace::Workspace::new(&manifest_path, &*config)`
- call this with `workspace.members()`, e.g.: `filter_packages_with_metadata(workspace.members())`
Something like this. 🙄

<details> 
  <summary>Code from screenshot</summary>

```rust
fn filter_packages_with_metadata<'i, I: Iterator<Item = &'i Package> + 'i>(iter: I) -> Vec<(PackageId, toml::Value)> {
	filter_packages_with_metadata_iter(iter).into_iter().collect()
}

fn filter_packages_with_metadata_iter<'i, I>(iter: I) -> impl IntoIterator<Item = (PackageId, toml::Value)> + 'i
	where I: Iterator<Item = &'i Package> + 'i {
	iter.filter_map(|p| {
		    p.manifest()
		     .custom_metadata()
		     .map(|meta| {
			     meta.as_table()
			         .map(|t| t.get("my-metadata"))
			         .flatten()
			         .map(|meta| (p.package_id(), meta))
		     })
		     .flatten()
	    })
	    .filter_map(|(id, v)| toml::Value::try_from(v).ok().map(|v| (id, v)))
}
```

</details>

**Comment by lowr** [comment]
This is a chalk issue. Minimum repro:

```rust
fn foo() -> impl IntoIterator<Item = ()> {
    []
}

fn test() {
    let v: Vec<_> = foo().into_iter().collect();
                  //^^^^^^^^^^^^^^^^^^^^^^^^^^^ unresolved method
}
```

**Comment by Veykril** [comment]
Fixed by https://github.com/rust-lang/chalk/pull/795
