### ISSUE TITLE
analyzing in not-saved file

### ISSUE THREAD

**Issue by hvlxh** [rust-lang/rust-analyzer#14699]
the errors are shown when the file was saved, it is good receiving the errros when we changing than receiving the errors after saving it and have to fix them again!
![Record_2023_05_01_17_17_07_79](https://user-images.githubusercontent.com/91016099/235447881-4e797043-792c-4f4c-9ff7-ec511986d1fc.gif)

**Comment by hvlxh** [comment]
also the errors stay up even if i fixed it until i saved the file

**Comment by lnicola** [comment]
We can't update those without running `cargo check`, and we only run it on save. You can set up auto-saving, but it's usually not worth the trouble.

**Comment by hvlxh** [comment]
wait i am still opening this though, there is no problem with that alternative solution too.

I am pretty sure vscode can give the current changes even if it is not saved. so you can use `cargo check` with gained code and show the result!

**Comment by lnicola** [comment]
We have our own diagnostics (the more interesting ones disabled by default) that run when typing. But we don't want to run `cargo check` on every keystroke: #3107.
