### ISSUE TITLE
Incorrect use of impl trait with generic will cause the language server to crash

### ISSUE THREAD

**Issue by TuDouNi92** [rust-lang/rust-analyzer#14691]
### Reproduce:
```
use std::ops::Add;
fn add(x:impl Add){

}
//'Add' trait which is missing generic like<T>
//This will cause rust-analyzer to crash
```
Corrected syntax:
```
use std::ops::Add;
fn add(x:impl Add<T>){
}
//rust-analyzer goes normally
```
### Language server log:
```
thread 'Worker' has overflowed its stack
[Info  - 1:00:19 PM] Connection to server got closed. Server will restart.

thread 'Worker' has overflowed its stack
[Info  - 1:45:36 PM] Connection to server got closed. Server will restart.

thread 'Worker' has overflowed its stack
[Info  - 1:45:52 PM] Connection to server got closed. Server will restart.

thread 'Worker' has overflowed its stack
[Info  - 1:46:09 PM] Connection to server got closed. Server will restart.

```
**rust-analyzer version**:v0.3.1489 

**rustc version**: 1.69.0 (84c898d65 2023-04-16)

**Comment by HKalbasi** [comment]
Can't reproduce. Does it happen for you with that example in an empty project?

**Comment by Veykril** [comment]
They might've hovered the parameter in which case this is a known stackoverflow (there is an issue for that somewhere)

**Comment by lowr** [comment]
Yeah I can reproduce the crash by hovering on `x`. #10932?

FWIW, the first code isn't incorrect -- it's perfectly valid code since `Add`'s only generic parameter has default type.

**Comment by Veykril** [comment]
Yep that is it,
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/10932
