### ISSUE TITLE
"error: 'rust-analyzer' is not installed for the toolchain 'nightly-x86_64-unknown-linux-gnu'\n"

### ISSUE THREAD

**Issue by Rainff9f58ff178** [rust-lang/rust-analyzer#14708]
im using neovim ,and meet this error 
```
[ERROR][2023-05-02 12:44:51] .../vim/lsp/rpc.lua:734	"rpc"	"rust-analyzer"	"stderr"	"error: 'rust-analyzer' is not installed for the toolchain 'nightly-x86_64-unknown-linux-gnu'\n"
```
what's wrong

**Comment by lnicola** [comment]
You didn't install it: https://rust-analyzer.github.io/manual.html#rustup.

Keep in mind that the version in rustup is lagging behind upstream. You can get a binary from GitHub, put it somewhere in `PATH` and use that if you want.

**Comment by Rainff9f58ff178** [comment]
thank you
