### ISSUE TITLE
rust-analyzer panic when trying to access a non-existence member in a struct

### ISSUE THREAD

**Issue by rilysh** [rust-lang/rust-analyzer#14709]
**rust-analyzer version**: 0.3.1498-standalone

**rustc version**: rustc 1.69.0 (84c898d65 2023-04-16)

**relevant settings**: N/A

In a small project, I'm using `reqwest` crate with `async` functionality. If I create a custom struct for response payload, RA panics when I try to get a non-existence member into that existing member scope.

For example,
```rs
pub struct MyStruct {
    ok: bool,
    text: String
}
```
Now in this struct, if I try to access `ok` with `<Request>.await.ok.<non_existence_member>` RA will panic in the background.

A complete example of this.
```rs
use serde::{Serialize, Deserialize};

#[derive(Default, Debug, Serialize, Deserialize)]
pub struct MyStruct {
    ok: bool,
    description: String
}

#[tokio::main]
async fn main() -> () {
    let url = "https://my_url.tld";
    let req = reqwest::get(url)
        .await
        .unwrap()
        .json::<MyStruct>()
        .await
        .unwrap();

    println!("{}", req.ok);
   // Now try to access req.ok.<anything>
}
```
Panic log:
 <details>
  <summary>Panic log</summary>
<code>
version: 0.3.1498-standalone
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/rilysh/Desktop/telkite/src/main.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 20,
            character: 1,
        },
    },
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', crates/hir-expand/src/ast_id_map.rs:141:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: hir_expand::InFile<hir_expand::ast_id_map::FileAstId<N>>::to_node
   4: hir_expand::MacroCallKind::arg
   5: <hir_expand::db::MacroArgTextQuery as salsa::plumbing::QueryFunction>::execute
   6: salsa::runtime::Runtime::execute_query_implementation
   7: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   8: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
   9: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  10: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  11: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  12: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  13: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  14: salsa::derived::slot::MemoRevisions::validate_memoized_value
  15: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  16: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  17: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  18: salsa::derived::slot::MemoRevisions::validate_memoized_value
  19: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  20: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  21: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  22: salsa::derived::slot::MemoRevisions::validate_memoized_value
  23: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  24: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  25: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  26: salsa::derived::slot::MemoRevisions::validate_memoized_value
  27: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  28: salsa::derived::slot::Slot<Q,MP>::read
  29: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  30: <DB as hir_ty::db::HirDatabase>::inherent_impls_in_crate::__shim
  31: hir_ty::method_resolution::incoherent_inherent_impl_crates
  32: salsa::runtime::Runtime::execute_query_implementation
  33: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  34: salsa::derived::slot::Slot<Q,MP>::read
  35: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  36: <DB as hir_ty::db::HirDatabase>::incoherent_inherent_impl_crates::__shim
  37: <DB as hir_ty::db::HirDatabase>::incoherent_inherent_impl_crates
  38: hir_ty::method_resolution::def_crates
  39: hir_ty::method_resolution::iterate_inherent_methods
  40: hir_ty::method_resolution::iterate_method_candidates_with_autoref::{{closure}}
  41: hir_ty::method_resolution::iterate_method_candidates_dyn
  42: hir_ty::method_resolution::lookup_method
  43: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  44: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  45: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  46: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  47: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  48: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  49: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  50: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  51: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  52: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  53: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  54: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  55: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  56: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  57: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  58: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  59: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  60: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  61: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  62: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
  63: hir_ty::infer::infer_query
  64: salsa::runtime::Runtime::execute_query_implementation
  65: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  66: salsa::derived::slot::Slot<Q,MP>::read
  67: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  68: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  69: <DB as hir_ty::db::HirDatabase>::infer_query
  70: hir_ty::db::infer_wait
  71: <DB as hir_ty::db::HirDatabase>::infer
  72: hir::source_analyzer::SourceAnalyzer::new_for_body
  73: hir::semantics::SemanticsImpl::analyze_impl
  74: hir::semantics::SemanticsImpl::type_of_pat
  75: ide::inlay_hints::bind_pat::hints
  76: ide::inlay_hints::hints
  77: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  78: std::panicking::try
  79: rust_analyzer::handlers::handle_inlay_hints
  80: std::panicking::try
  81: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 1:13:17 AM] Request textDocument/inlayHint failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
</code>
</details>

**Comment by hecatia-elegua** [comment]
> crates/hir-expand/src/ast_id_map.rs:141:58

https://github.com/rust-lang/rust-analyzer/blob/60f4b3e26e8656bbe8b65530e237e3907c9565f3/crates/hir-expand/src/ast_id_map.rs#L141

**Comment by lnicola** [comment]
This no longer panics:

![image](https://github.com/user-attachments/assets/175a1037-1967-4dd8-8e60-cc0a3daab7e1)
