### ISSUE TITLE
Consider replacing `std::sync::Arc` usages with an `Arc` implementation that has no weak support

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14717]
We use `Arc`s a lot, but never make use of the weak count so it might be beneficial to use a slimmer Arc (for our attribute handling it might even be more beneficial to employ a `ThinArc`).

**Comment by lnicola** [comment]
A prototype of this (which doesn't include the Chalk database part because it's external) seems to save a whooping 2 MB RAM.
