### ISSUE TITLE
Can't disable sysroot loading

### ISSUE THREAD

**Issue by Zapeth** [rust-lang/rust-analyzer#14721]
**rust-analyzer version**: build from sources release 2023-04-17
**rustc version**: rustc 1.69.0
**lsp-client version**: helix-editor 23.03

For the [`rust-analyzer.cargo.sysroot` config option](https://github.com/rust-lang/rust-analyzer/blob/a7168a8c6fc84bbaadb75c6fd7e345ef1103b96e/crates/rust-analyzer/src/config.rs#L115-L121) it says `Unsetting this disables sysroot loading.`

However, setting it to `null`, `""` or `false` has no effect, rust-analyzer still tries to load the sysroot library sources from `rust-analyzer.cargo.sysrootSrc`.

And looking at the [parsing code](https://github.com/rust-lang/rust-analyzer/blob/a7168a8c6fc84bbaadb75c6fd7e345ef1103b96e/crates/rust-analyzer/src/config.rs#L1153-L1168) I'm not even sure if its possible to disable the sysroot loading (unless I'm missing something thats not immediately obvious)

**Comment by Veykril** [comment]
From what I can tell it respects the config here though

**Comment by Zapeth** [comment]
True, how would one "unset" a value then via config then? Whatever value I set, its apparently still interpreted as `Some(String)` instead of `None` (unless the client sends it incorrectly)

**Comment by Veykril** [comment]
depends on your client, but in vscode setting it to plain `null` should work.

**Comment by Zapeth** [comment]
Thanks for verifying, I'll look around in other places then
