### ISSUE TITLE
rust analyzer fail to start 

### ISSUE THREAD

**Issue by sehz** [rust-lang/rust-analyzer#14740]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

rust-analyzer version: 0.3.1498-standalone (3a27518fe 2023-04-30)

**rustc version**: (eg. output of `rustc -V`)

rustc -V
rustc 1.69.0 (84c898d65 2023-04-16)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

Getting this error message:
```
[ERROR rust_analyzer::main_loop] FetchWorkspaceError:
rust-analyzer failed to load workspace: cd "/git/infinyon/fluvio/./crates/fluvio-mv" && "cargo" "--version" failed: No such file or directory (os error 2)

```

**Comment by lnicola** [comment]
Is `/git` a real path? Does it work if you run Code from a terminal?

**Comment by sehz** [comment]
closing as it's working again
