### ISSUE TITLE
Closure capture calculated incorrectly for non-binding match

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14754]
The following closures capture x by value both
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4044e24fa1cffb795c2dd03239eb5fb2)
```rs
fn main() {
    let c: fn() = {
        let x = 1;
        || {
            let _ = x;
        }
    };
    let c: fn() = {
        let x = 1;
        || match x {
            _ => println!("Hello World!"),
        }
    };
}
```
yet we recognize the first as non capturing and the second as capturing by ref.

**Comment by HKalbasi** [comment]
This is really strange: if I print the size of closures, it shows 0 for both of them ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7e36ea665c441fd8158fc021ba342174))

**Comment by Veykril** [comment]
Ah, I guess the coercion logic sees the captures "by syntax" rather by semantics? Nevertheless there is an error on our side since the second one captures for us when it shouldn't then.

**Comment by HKalbasi** [comment]
> Ah, I guess the coercion logic sees the captures "by syntax" rather by semantics?

Makes sense.

> though i suppose that comes from our match checking logic which is slightly flawed in general I think?

No IIRC I didn't implement the match part of the capturing logic at all :)
