### ISSUE TITLE
Support c"..." literals

### ISSUE THREAD

**Issue by enderger** [rust-lang/rust-analyzer#14751]
**rust-analyzer version**: Commit a4966c9

**rustc version**: 2023-05-05

**relevant settings**: None

Recently, RFC3448 introduced the c"..." syntax for string literals. Rust-analyzer needs to be updated to support this.

**Comment by lnicola** [comment]
Can you link to the RFC?

**Comment by lnicola** [comment]
https://github.com/rust-lang/rfcs/pull/3348

**Comment by lowr** [comment]
This is blocked on rustc_* crates autopublish; we need up-to-date rustc_lexer to support the new literal.

**Comment by lowr** [comment]
Implemented in #14837 :tada:
