### ISSUE TITLE
rust-analyzer somehow forces cargo to recompile lots of depedencies

### ISSUE THREAD

**Issue by Fabus1184** [rust-lang/rust-analyzer#14756]
Whenever I use rust-analyzer via the vscode extension, running cargo on the same project will recompile lots of dependencies every time after rust-analyzer is run. I thought this may be due to rust-analyzer and cargo having different versions and therefore having to rebuild incompatible dependencies, but even after I set the Rust Analyzer Language Server Path to the install location of rust-analyzer by rustup it did show the correct version but still kept recompiling dependencies. Is there something I missed or is this a bug?

**Comment by lnicola** [comment]
This usually happens because of some environment variables like `RUSTFLAGS` that are set up differently in a shell. You can use `cargo build -v` to see the reason for rebuilding.

> even after I set the Rust Analyzer Language Server Path to the install location of rust-analyzer by rustup

Don't do that.

**Comment by Fabus1184** [comment]
Nice, thank you! It was PKG_CONFIG_PATH that was different.
