### ISSUE TITLE
Add tool to convert final expression in function to `let` binding

### ISSUE THREAD

**Issue by ElectrifyPro** [rust-lang/rust-analyzer#14753]
In idiomatic Rust code, the final expression that is being returned from a function will be written like so, without a `return` and semicolon:

```rs
impl Parse for Unary {
    fn parse(input: &mut Parser) -> Result<Self, Error> {
        Self::parse_as_expr(input)
    }
}
```

If I want to modify the function to for example, print the value of the expression, or perform extra work on it, I must convert the expression to a `let` binding myself:

```rs
impl Parse for Unary {
    fn parse(input: &mut Parser) -> Result<Self, Error> {
        let expr = Self::parse_as_expr(input);
        println!("{:#?}", expr);
        // parse more unary expressions
        expr
    }
}
```

Of course, it is easy to do myself. I am currently accomplishing this with a macro in my editor. However, it would be much nicer to have this tool provided by rust-analyzer.

**Comment by HKalbasi** [comment]
You can select the thing, and use `Extract into variable` assist. For the printing case you can also use the `dbg!` macro.

**Comment by ElectrifyPro** [comment]
Thanks for the help. I didn't realize there were more ways to call `codeaction` in my editor.
