### ISSUE TITLE
Derive Debug fails for unsized structs

### ISSUE THREAD

**Issue by ForrestOfBarnes** [rust-lang/rust-analyzer#14768]
**rust-analyzer version**: 0.3.1506-standalone

**rustc version**: 1.69.0

**relevant settings**: N/A

```rust
#[derive(Debug)]
struct Foo([u8])
```

This compiles correctly, but rust-analyzer thinks the derive macro contains an error: "expected &dyn Debug, found &[u8]". Oddly, derive macros for Eq, PartialEq, Ord, and PartialOrd, all function correctly.

**Comment by Veykril** [comment]
Underlying issue is https://github.com/rust-lang/rust-analyzer/issues/11847

**Comment by ForrestOfBarnes** [comment]
Thank you, I'll close this then.

**Comment by HKalbasi** [comment]
I think this one is different. `&[u8]` is not coercible into `&dyn Debug` since `[u8]` is unsized, but `&&[u8]` is coercible. Rustc uses double reference for last field, we should either do the same or use double reference always which I think is harmless.
