### ISSUE TITLE
VSCode Rust dependencies view is shown even for non-Rust workspaces.

### ISSUE THREAD

**Issue by pJunger** [rust-lang/rust-analyzer#14760]
**rust-analyzer version**: 0.3.1506-standalone

**rustc version**: rustc 1.69.0 (84c898d65 2023-04-16)

# Problem

In contrast to the e.g. `rust-analyzer` button in the status bar, the `RUST DEPENDENCIES` view is shown even when there's no Rust related files in the workspace.

**Comment by Veykril** [comment]
Looks like we are missing a `"when": "inRustProject"` clause here https://github.com/rust-lang/rust-analyzer/blob/4c5fd19ee5734992344827b11c0d0e864b020b25/editors/code/package.json#L1974-L1977
