### ISSUE TITLE
Variables not changed using restart in vscode's debug mode

### ISSUE THREAD

**Issue by hvlxh** [rust-lang/rust-analyzer#14762]
Works when stopping it and starting it again but not by restarting

https://user-images.githubusercontent.com/91016099/236775238-46cb5820-88c3-4422-9b5d-83b9253e36d8.mp4

**Comment by hvlxh** [comment]
hard to fix? why no response?

**Comment by HKalbasi** [comment]
Debug functionality is provided by [Codelldb](https://github.com/vadimcn/codelldb) so I think you should report this there.
