### ISSUE TITLE
'rust-analyzer' is not installed for the toolchain 'stable-aarch64-apple-darwin'

### ISSUE THREAD

**Issue by samgj18** [rust-lang/rust-analyzer#14776]
I installed 'rust-analyzer' via curl command shown in the website:

`curl https://sh.rustup.rs -sSf | sh`

All I can get in my laptop is:

`error: 'rust-analyzer' is not installed for the toolchain 'stable-aarch64-apple-darwin'`

**rustc version**: 
```
rustc version
error: couldn't read version: No such file or directory (os error 2)

error: aborting due to previous error
```

I have a M1 Pro, not sure why is not working, please let me know if there could be something else that I could add for better debugging.

**Comment by lnicola** [comment]
You can get a binary from GitHub releases. What you installed is the compiler, not rust-analyzer.

Which editor are you planning to use?

**Comment by samgj18** [comment]
Hey I'm using neovim, which relies on rust-analyzer. It was working fine before, but after updating with `rustup` I started getting this error.

**Comment by lnicola** [comment]
rustup has a shim that asks you to install the component. Make sure the location where you put rust-analyzer is before rustup in PATH.

**Comment by samgj18** [comment]
That did the trick! Thanks a lot @lnicola

**Comment by aconchillo** [comment]
The solution is to actually install the `rust-analyzer` component with:

```
rustup component add rust-analyzer
```

If you run 

```
rustup component list
```

it will show you that rust-analyzer is actually not installed. As @lnicola says, the binary that's in `.cargo/bin/rust-analyzer` it's just a shim that tells you to run that command.

**Comment by lnicola** [comment]
> The solution is to actually install the rust-analyzer component

I don't recommend doing that. You'll get very, very old version. I suggest downloading it from GitHub Releases.

**Comment by aconchillo** [comment]
> > The solution is to actually install the rust-analyzer component
> 
> I don't recommend doing that. You'll get very, very old version. I suggest downloading it from GitHub Releases.

Oh, I didn't know that! I was originally compiling from source but then ran `rustup update` and I got a message saying that `rustup` was not managing `rust-analyzer` so I went ahead and used the component. I guess I should have stayed with the one I was compiling.

Thank you for clarifying @lnicola !

**Comment by lnicola** [comment]
Yeah. To explain, first of all, any sync downstream will go through the usual Rust release trains, meaning it's going to be more than a month and a half old when it comes out.

Then, we sometimes don't actually do the sync, for various reasons (lack of time, changes downstream that make r-a only work with nightly toolchains etc.).

**Comment by gmelodie** [comment]
light bikeshed:

> it's going to be more than a month and a half old when it comes out.

Doesn't seem that old to me. Is there an automated way of getting it from the releases page? How do you guys keep up with the newest releases?

**Comment by neilyio** [comment]
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> wasm/src/lib.rs:1:1
  |
1 | #![feature(async_fn_in_trait)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by shmerl** [comment]
Unfortunately, rust's pre-defined `env` file that's supposed to be sources has such kind of PATH setting:

```
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="/home/myuser/.local/bin/rust/bin:$PATH"
```

That basically borks for me the ability to have $HOME/.local/bin to be first. Unless I tweak this file.

**Comment by JakubStiburek** [comment]
For anyone using Neovim with Mason. All I had to do to fix this was to install rust-analyzer with Mason.

**Comment by t0r0X** [comment]
> The solution is to actually install the `rust-analyzer` component with:
> 
> ```
> rustup component add rust-analyzer
> ```
> 
> If you run
> 
> ```
> rustup component list
> ```
> 
> it will show you that rust-analyzer is actually not installed. As [@lnicola](https://github.com/lnicola) says, the binary that's in `.cargo/bin/rust-analyzer` it's just a shim that tells you to run that command.

@aconchillo 
2025: thanks for this hint!!

I've installed `rustup` with Homebrew (macOS), and also got the error:
```
$ rust-analyzer --version 
error: Unknown binary 'rust-analyzer' in official toolchain 'stable-aarch64-apple-darwin'.
```

After adding component `rust-analyzer` with `rustup`, it worked and the versions were in sync:
```
$ rustup component add rust-analyzer
info: downloading component 'rust-analyzer'
info: installing component 'rust-analyzer'

$ rust-analyzer --version
rust-analyzer 1.92.0 (ded5c06c 2025-12-08)

$ rustc --version
rustc 1.92.0 (ded5c06cf 2025-12-08)
```
