### ISSUE TITLE
Go to definition doesn't work for trait implementations for structs inside function bodies

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/rust-analyzer#14782]
```Rust
trait T {
    type Ty;
    fn foo() -> Self::Ty;
}

fn f() {
    struct X {}
    impl T for X {
        type Ty = i32;
        fn foo() -> i32 {
            5
        }
    }
    let t = X::foo();
}
```

In this example r-a sees method, and can infer that the type of `t` is `i32`, but go to definition on `foo` will go to the trait function, not the impl one.

**Comment by Veykril** [comment]
In general, IDE features like these interacting with impls should be aware of block impls for the cursor position.

**Comment by Veykril** [comment]
We cannot consider all block implementations, for that we would need to look into all bodies which goes against the lazy analysis strategy we employ in r-a.

**Comment by Veykril** [comment]
(Note cursor position in this case would be identifier we are invoking this go to on)

**Comment by HKalbasi** [comment]
> We cannot consider all block implementations, for that we would need to look into all bodies which goes against the lazy analysis strategy we employ in r-a.

This case is allowed in https://github.com/rust-lang/rfcs/pull/3373 so we should support it, but I think it is possible to do it without breaking laziness.

> for resolving thefoo in X::foo we should consider impls in the surrounding block and all ancestors (which I relaly thought we already do?)

I guess we do it in method resolution, but not in the `lookup_impl_method` function.

**Comment by Veykril** [comment]
Indeed, it looks like `lookup_impl_method` is losing the local context, that is the block its used in, so we need to thread that through somehow.
