### ISSUE TITLE
disable/filter cargo check diagnostics

### ISSUE THREAD

**Issue by adamse** [rust-lang/rust-analyzer#14798]
The `unused_code` diagnostic drives me crazy when writing something new, too many useless annotations.

I made a patch to filter `cargo check` diagnostics here: https://github.com/adamse/rust-analyzer/commit/42a52ce2f8e50a395070dab885ac566e57b955a4
(I've extended the existing `rust-analyzer.diagnostics.disabled`  setting to also apply to `cargo check`.)

If the project is interested in this feature I would be happy to upstream it.

**Comment by HKalbasi** [comment]
Doesn't disabling "check on save" work for you?

**Comment by HKalbasi** [comment]
Doesn't disabling "check on save" work for you?

**Comment by adamse** [comment]
No, that doesn't sound like what I want. I just want to disable a subset of them in my editor.

**Comment by HKalbasi** [comment]
Ah I see. I think it make sense to make it upstream, but under a separate config (so that ignoring, for example `unused-mut` of r-a doesn't remove the rustc one)
