### ISSUE TITLE
How should `rust-analyzer` handle multiple subdirectories with differing Rust toolchain requirements?

### ISSUE THREAD

**Issue by str4d** [rust-lang/rust-analyzer#14796]
I'm contributing to an embedded project that has this structure:
```
crates/                 # Crates for the embedded platform
    foo/                # Library crate
        src/            # Works fine on stable
        Cargo.toml
    bar/                # Library crate
        src/            # Works fine on stable
        Cargo.toml
    .cargo/             # Overrides to build crates for the target platform by default
        config.toml     # Requires nightly: contains a -Z option in a rustflags setting
    Cargo.toml          # Workspace containing `foo` and `bar` crates
    rust-toolchain.toml # Pins a nightly toolchain
tools/                  # Support tools to be run on the host
    src/                # Works fine on stable
    Cargo.toml
.vscode/
    settings.json       # Where I can configure rust-analyzer
rustfmt.toml
```

I have Rust installed via `rustup`, and I use VSCode with the `rust-analyzer` plugin. When I open the project's root, `rust-analyzer` correctly detects the two subdirectories and gives me IDE support for them. However, it uses the stable toolchain, which immediately causes errors of the following form:
```
[ERROR rust_analyzer::main_loop] FetchWorkspaceError:
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /path/to/repo/crates/Cargo.toml, Some(Version { major: 1, minor: 69, patch: 0 }): Failed to run `cd "/path/to/repo/crates" && "cargo" "metadata" "--format-version" "1" "--all-features" "--manifest-path" "/path/to/repo/crates/Cargo.toml" "--filter-platform" "thumbv7em-none-eabihf"`: `cargo metadata` exited with an error: error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C target-cpu=cortex-m4 -C panic=abort -C debuginfo=0 -C opt-level=z -C embed-bitcode=yes -C lto=yes -C 'link-args=--script=flipperzero-rt.ld --Bstatic --relocatable --discard-all --strip-all --lto-O3 --lto-whole-program-visibility' -Z no-unique-section-names=yes --target thumbv7em-none-eabihf --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler
```

I can work around this by adding the following option to `.vscode/settings.json`, which causes my IDE to check the entire repository against nightly:
```
"rust-analyzer.server.extraEnv": {
    "RUSTUP_TOOLCHAIN": "nightly"
}
```

However, is there anything better that could be done here? Could `rust-analyzer` pay attention to the toolchain overrides that should be applying within a given subdirectory, in the same way that it does detection that Rust projects exist within subdirectories at all? `cargo` itself only applies overrides based on the current working directory (`cd crates/ && cargo check` works fine, but `cargo check --manifest-path crates/Cargo.toml` does not), so the current `rust-analyzer` behaviour is as if the IDE's project root is always the CWD. But the existence of a `rust-toolchain.toml` file in a subdirectory seems like a pretty clear user signal that they don't want that behaviour.

**Comment by Veykril** [comment]
This is odd? The error even states that `cargo` was executed in `/path/to/repo/crates` as the working dir, so it should just pick the nightly toolchain as specified by the toolchain overwrite

**Comment by str4d** [comment]
LOL good point, I didn't even notice that while privacy-editing the error message.

Is `rust-analyzer` maybe loading its environment from `rustup` on start based on the CWD, and then subprocesses are inheriting that instead of going back to `rustup`?

**Comment by Veykril** [comment]
It shouldn't be. We generally invoke cargo so that overrides are honored properly. (Note that we invoke plain `cargo`, not a specific executable from the toolchain).

Are you starting the server (your text editor starting the server that is) from an environment where `RUSTUP_TOOLCHAIN` is set to stable perhaps?

**Comment by str4d** [comment]
Aha, that was it! I had `RUSTUP_TOOLCHAIN: stable` in my VSCode's user config (probably from long ago when `rust-analyzer` had a much harder time dealing with repositories that had `rust-toolchain` set to an old MSRV, and this was the recommended fix). Removed that and everything works great now. Thanks!
