### ISSUE TITLE
Please add support for rustfmt's group_imports

### ISSUE THREAD

**Issue by boaz-chen** [rust-lang/rust-analyzer#14806]
https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#group_imports

Specifically, the one I'm missing the most is the ["One"](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#One%5C%3A) option.

Thanks!

**Comment by Veykril** [comment]
You can set this via `rust-analyzer.imports.granularity.group` already, though the `one` style is not supported yet https://github.com/rust-lang/rust-analyzer/issues/11361
