### ISSUE TITLE
Some keywords are not being highlighted

### ISSUE THREAD

**Issue by DaniPopes** [rust-lang/rust-analyzer#14817]
I don't know if this is actually a bug, but certain keywords like `const`, `struct`, `fn` etc are not being highlighted / italicized. This has been the case for `pre-release` versions in VSCode for the past few weeks, while the `release` version hasn't changed.

The only difference between the screenshots below is the version, all the settings are the same (semantic highlighting is enabled).

**rustc version**: rustc 1.71.0-nightly (ce5919fce 2023-05-15)

**server stopped / no extension**:

![image](https://github.com/rust-lang/rust-analyzer/assets/57450786/aa08f3e7-6029-4be1-9d7b-fee94e03fdc8)

**rust-analyzer release version**: 0.3.1506-standalone

![release](https://github.com/rust-lang/rust-analyzer/assets/57450786/9bb382ae-d32b-4d36-9d84-88eb3b7f23b1)

**rust-analyzer pre-release version**: 0.4.1510-standalone

![image](https://github.com/rust-lang/rust-analyzer/assets/57450786/34f39706-de5d-48dc-8e1d-e92b5ccd9e54)

**Comment by Veykril** [comment]
Ye I noticed this too, we now honor the `augmentsSyntaxTokens` capability https://github.com/rust-lang/rust-analyzer/pull/14777, but as it turns out the VSCode text mate grammar is not that great. Was thinking of what we can do here but I think we just need to disable it for now again.

**Comment by HKalbasi** [comment]
Somehow unrelated, but this also breaks highlighting for `ra_fixture`.

**Comment by Veykril** [comment]
That I already fixed (but the releases haven't gone out for that due to the marketplace token being expired)

**Comment by HKalbasi** [comment]
Aha, thanks! I use my own builds, probably my branch is outdated.

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/14795 shouldve fixed it
