### ISSUE TITLE
Wrong gray-color type position in variable definitions on generic this function

### ISSUE THREAD

**Issue by enomado** [rust-lang/rust-analyzer#14833]
I guess it should be
let mut acc **:T** = start
but result is
let mut **:T** acc = start

```
pub fn accumulate_vec_inplace<'a, T>(arr: &mut Vec<T>, start: T)
where
    T: Zero,
    T: Add<T>,
    T: Clone,
{
    let mut acc = start;
    for x in arr {
        acc = acc + x.clone();
        *x = acc.clone();
    }
}
```
![Screenshot_2023-05-18_04-31-26](https://github.com/rust-lang/rust-analyzer/assets/707007/2b1ef253-8875-4e19-9354-8b508d4cfbff)

**Comment by enomado** [comment]
rust-analyzer
v0.4.1518
Pre-Release

**Comment by Veykril** [comment]
Fixed by https://github.com/rust-lang/rust-analyzer/pull/14818
