### ISSUE TITLE
[ERROR hir_ty::mir::lower] MIR lower implementation bug: unsized temporaries

### ISSUE THREAD

**Issue by Wuelle** [rust-lang/rust-analyzer#14831]
```rust
#[derive(Default)]
pub struct Foo {
    bar: [u8
}
```
When editing this piece of code (trying to complete the first fields type), rust analyzer starts to complain:
```
[ERROR hir_ty::mir::lower] MIR lower implementation bug: unsized temporaries
```
This is from an (otherwise empty) crate inside a workspace, I can't minimize it further right now.

**rust-analyzer version**: `rust-analyzer version: 0.3.1506-standalone`

**rustc version**: `rustc 1.71.0-nightly (e77366b57 2023-05-16)`

**relevant settings**: None that I am aware of.

**Comment by HKalbasi** [comment]
I think this is fixed in #https://github.com/rust-analyzer/rust-analyzer/pull/14808
