### ISSUE TITLE
Make metrics parallel

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/rust-analyzer#14853]
If I understand correctly, we run `analysis-stats` in a single thread, so we can probably run metrics for different repositories in separate processes to make it faster (it currently takes ~50 minutes, but `analysis-stats` on self is ~15 minute).

**Comment by Veykril** [comment]
That is assuming the CI runner has multiple cores available which I would not necessarily expect

**Comment by lnicola** [comment]
They have 2 cores. We could also run them in different jobs.

**Comment by mattbonnell** [comment]
New here so apologies if I misconstrue anything.

This seems a simple enough change, we would want to parallelize [these `Metrics::measure_analysis_stats[_self]` calls](https://github.com/rust-lang/rust/blob/4e4f0417aa190bec347c53a147ca1cd134a832f6/src/tools/rust-analyzer/xtask/src/metrics.rs#L40-L44).

How would we want to set the level of parallelism? Should we use something like https://docs.rs/num_cpus/latest/num_cpus/ make it configurable, or just hard-code it in a constant?

**Comment by HKalbasi** [comment]
@mattbonnell I think going with separate jobs is better, as cpu cores on CI machines are limited. But in process parallelizing is also better that the current state. And for in process parallelizing, using `num_cpus` is fine (std also has something similar IIRC?).

**Comment by mattbonnell** [comment]
> @mattbonnell I think going with separate jobs is better, as cpu cores on CI machines are limited. But in process parallelizing is also better that the current state. And for in process parallelizing, using `num_cpus` is fine (std also has something similar IIRC?).

Got it. For splitting into multiple jobs, we could add a `target` flag to the `metrics` xtask to support analyzing only a specific target. If not supplied, behavior would remain the same as now.

https://github.com/rust-lang/rust-analyzer/blob/2f1b7cedcf5044ba620646c6758bbb99f46b8d95/xtask/src/flags.rs#L44-L46
```
        cmd metrics {
            optional --dry-run
            /// Either 'self' or one of the `rustc-perf` benchmarks: 'ripgrep', 'webrender', 'diesel/diesel'
            optional --target name: String
        }
```

and then we'd break the `metrics` CI job into 4 separate jobs, one for each target. Thoughts? Not sure about wording of the doc comment

**Comment by HKalbasi** [comment]
That looks good to me. We may also need another job to aggregate the result from those 4 jobs.

**Comment by mattbonnell** [comment]
> We may also need another job to aggregate the result from those 4 jobs.

 Can you clarify what you mean by aggregate here, and the approach you have in mind to do so, if you have one?

**Comment by HKalbasi** [comment]
At the end of the metrics task, the `to_json` function builds a json file including the result for all targets, and then push it into the metrics repository. Building that json is not possible if the jobs are separated, so probably each job needs to store its result in a file, and another job downloads those artifacts and builds that json and push it into the metrics repository. Another approach would be not adding the aggregator job, but each task update the repository for their own part (which needs to deal with `git push` race conditions), or changing the metrics repository to read results from separate files.

**Comment by lnicola** [comment]
The trouble with the metrics is that we store the results in a [newline-delimited JSON file](https://raw.githubusercontent.com/rust-analyzer/metrics/master/metrics.json), so we can display them in the [dashboard](https://rust-analyzer.github.io/metrics/). Each run has a single line in the JSON, so it's pretty hard to update, as HKalbasi just said.

**Comment by lnicola** [comment]
This seems prone to race conditions. I'd try uploading the results to GitHub Actions (there's a way to pass data between jobs), merging them at the end, and finally pushing to that git repository.

**Comment by lnicola** [comment]
Ah, all right then. I'm not sure we want to add serde to xtask, but we could make it a different binary (that's only used for this).
