### ISSUE TITLE
Activate all features in Emacs

### ISSUE THREAD

**Issue by dannywillems** [rust-lang/rust-analyzer#14854]
Hi,
I try to activate the compilation with all features enabled in emacs.
I found for VSCode which is:
```
➜  User: cat settings.json 
{
    "window.zoomLevel": 2,
    "rust-analyzer.cargo.features": [
        "features_to_enable"
    ]
}
➜  User: pwd
/home/user/.config/Code/User
```

But I cannot find:
- how to do the same for emacs
- activate all features instead of one by one

Can someone help please?

**Comment by dannywillems** [comment]
Found lsp-rust-features in https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-rust.el#L186. Setting to "all" seems ok. Let's see.

**Comment by flodiebold** [comment]
Yeah, that should do it.
