### ISSUE TITLE
Deriving PartialOrd causes error "this operation is unsafe and requires an unsafe function or block"

### ISSUE THREAD

**Issue by KSXGitHub** [rust-lang/rust-analyzer#14864]
![screenshot](https://github.com/rust-lang/rust-analyzer/assets/11488886/c4b26494-bc91-483f-9d57-15eb7ebd7000)

**rust-analyzer version**: 0.3.1506-standalone

**rustc version**: rustc 1.64.0 (a55dd71d5 2022-09-19)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**Comment by Veykril** [comment]
See https://github.com/rust-lang/rust-analyzer/issues/14766#issuecomment-1541401296

Either upgrade to 1.69 or if that is not an option install an older rust-analyzer (preferably one from around when 1.64 released).
