### ISSUE TITLE
How does rust-analyzer locate source code?

### ISSUE THREAD

**Issue by MoGuGuai-hzr** [rust-lang/rust-analyzer#14879]
To my understanding, rust-analyzer is configured to read codes from `root_dir/src`, as well as the `member_dirs` specified in `root_dir/Cargo.toml`.

However, I recently discovered that rust-analyzer is also capable of parsing codes from `root_dir/src-tauri` in the tauri project, even in the absence of a `Cargo.toml` file in the root directory.

So, where will rust-analyzer search for codes?

**Comment by Veykril** [comment]
r-a runs `cargo metadata` which reports source locations for all crates of the workspace.

**Comment by MoGuGuai-hzr** [comment]
> r-a runs `cargo metadata` which reports source locations for all crates of the workspace.

My project structure is as follows.
```
project
├── dist
│   └── index.html
└── src-tauri
    ├── Cargo.lock
    ├── Cargo.toml
    ├── build.rs
    ├── icons
    ├── src
    ├── target
    └── tauri.conf.json
```

The output of `project> cargo metadata` shows an error message `"could not find Cargo.toml in '/project' or any parent directory"` and running the same command in `src-tauri` directory produces the expected output.

However, the ra command works correctly in the `project` directory. Even if `cargo metadata` did not obtain output, it seems that ra can still function properly.

**Comment by lnicola** [comment]
Setting `rust-analyzer.linkedProjects` might work, as per #14899.

**Comment by MoGuGuai-hzr** [comment]
> ~Setting `rust-analyzer.linkedProjects` might work, as per #14899.~
> 
> I think we run `cargo metadata` next to `Cargo.toml`.

RA is functioning perfectly normal, I am just curious as to why it is able to detect code under `src-tauri`.

**Comment by MoGuGuai-hzr** [comment]
Oh, I get it. Thank you. I thought RA can only work in the root directory, but I misunderstood.
