### ISSUE TITLE
Unknown type with `option_env` macro

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/rust-analyzer#14885]
```Rust
let x = option_env!("CI");
   //^ {unknown}
```
The strange part is that if I use `inline macro` assist, it will work (after manually replacing `$crate` with `core`):
```Rust
let x = core::option::Option::None:: < &str>;
  //^ Option<&str>
```

**Comment by Veykril** [comment]
`option_env` is an eager macro and as we come to know `$crate` resolution fails for those rn. SO we should just replace that with `::core` again for now
