### ISSUE TITLE
Extract into const

### ISSUE THREAD

**Issue by yoav-lavi** [rust-lang/rust-analyzer#14886]
Hey, I think a useful action for `&'static str` would be "Extract into const":

```rust
let opt_env_var = std::env::var("SOME_ENV_VAR").ok();
```

➜ Extract into const 

```rust
const SOME_ENV_VAR: &str = "SOME_ENV_VAR";

let opt_env_var = std::env::var(SOME_ENV_VAR).ok();
```

Suggested behavior: 

```rust
const {SCREAMING_SNAKE_CASE_STR_CONTENT}: &str = {str_content};

/* previous location ➜ */ {SCREAMING_SNAKE_CASE_STR_CONTENT}
```

- The name could either be the `&'static str` content or a generic placeholder. The content is beneficial since it may reduce the amount of times the `const` needs to be renamed, but it's less likely to be correct for longer content.
- Not 100% sure if it should be moved to the root scope or to the top of the current scope
- Could be extended to all literals with different rules for naming

Thanks for your consideration!

**Comment by yoav-lavi** [comment]
Looks like this may be a duplicate of  #7692

**Comment by lnicola** [comment]
Closing in favor of #18679.
