### ISSUE TITLE
Document that `rustup component add rust-analyzer` just works?

### ISSUE THREAD

**Issue by amosnier** [rust-lang/rust-analyzer#14882]
Quite a positive request I suppose, but although the official documentation does not seem to say that (or am I bad at searching?), it would seem like

`rustup component add rust-analyzer`

after a fresh install just works. Maybe it would be worth clearly documenting it, instead of letting people wonder which package they should download or whether they should build from source.

**Comment by lnicola** [comment]
It's already documented in the manual. But I suggest avoiding it, since you'll get a version that's months old and doesn't get any bug fixes.

In addition, most people will probably use the Code extension, which comes with a compatible server.

**Comment by amosnier** [comment]
I see. Thanks. Not using Code myself. I'll download the latest release then. Closing.

**Comment by amosnier** [comment]
Sorry, but I'm not sure @lnicola's recommendation was the best approach after all. With the current official Rust distribution release, I get a non-working `rust-analyzer`  binary under `.cargo/bin` from the fresh installation. The fact that it does not work is in fact not an issue in itself, it is basically by design: it will work as soon as I run `rustup component add rust-analyzer`. However, if I do a manual installation of `rust-analyzer`, for instance under . local/bin as recommended, that will typically not work, because `.cargo/bin` really insists on being first in my `PATH`.

For now, I will just use the `rustup` version of `clang-analyzer` , which seems to be in line with the toolchain, i.e. at the time of writing one month-old.

I reopen, since since I guess some other users might run into the same issue. Maybe some clarifications would be useful.

**Comment by lnicola** [comment]
> However, if I do a manual installation of rust-analyzer, for instance under . local/bin as recommended, that will typically not work, because .cargo/bin really insists on being first in my PATH.

We should document this issue, but the user will have to set up `PATH` correctly. We can't do anything about this, except maybe asking the `rustup` team to change the behavior of the shim, which I doubt they'll be open to.

> For now, I will just use the rustup version of clang-analyzer , which seems to be in line with the toolchain, i.e. at the time of writing one month-old.

It's from the 20th of March, and currently can't be updated.

**Comment by emadbaqeri** [comment]
I've solved this issue by adding rust-analyzer to my toolchain using `rustup component add rust-analyzer`

**Comment by lnicola** [comment]
@emadbaqeri which issue did you have? The version in rustup is once again very old and I don't recommend using it.

**Comment by emadbaqeri** [comment]
> @emadbaqeri which issue did you have? The version in rustup is once again very old and I don't recommend using it.

I should have comment this in an other page, I do have lots of tabs open :)

**Comment by coffeebe4code** [comment]
> It's already documented in the manual. But I suggest avoiding it, since you'll get a version that's months old and doesn't get any bug fixes.
> 
> In addition, most people will probably use the Code extension, which comes with a compatible server.

Is this still the case? I would prefer not to download and install a binary, set up paths, when i can use the rust toolchain and make it "just work"

**Comment by lnicola** [comment]
The syncs are more regular these days. You can install a nightly toolchain and use it only for r-a.

**Comment by rvdende** [comment]
vscode rust-analyzer was getting stuck, but after running `rustup component add rust-analyzer` it seems much better now.
