### ISSUE TITLE
Add option to change hexadecimal size display to decimal

### ISSUE THREAD

**Issue by liquidev** [rust-lang/rust-analyzer#14918]
I just updated to rust-analyzer `0.4.1531-standalone (f6e3a87bf 2023-05-27)` and noticed that the size numbers when you hover over a type are now in hexadecimal:

```rs
struct RectData // size = 0x14, align = 0x4
```

I find decimal numbers much easier to read, and would like a setting that allows you to change the format back to what it used to be.

**Comment by HKalbasi** [comment]
I think there should be a config variable for each item (size, align, and offset) with options hex, decimal, both, and nothing. And for the default I think the following works:
* size = both
* align = nothing (who care about align?)
* offset = hex
