### ISSUE TITLE
Parse only a part of the sourcefile

### ISSUE THREAD

**Issue by TathagataRoy1278** [rust-lang/rust-analyzer#14922]
Sorry if an issue already exists, I could not find it.

If I only have a part of a file like a let expression,

`let a = 10;`

And I just want it to return me a SyntaxNode with LET_EXPR type, is there any specific function I can call to do that instead of using SourceFile::parse which parses a whole file.
Until now I have just been enclosing the nodes with "fn main() {  ...  }" so that it parses as a source file.

The Show Syntax Tree command gives me a partial syntax tree, but from my knowledge extracts it after running SourceFile::parse on the file, and also how it does not run on non .rs files.

Thank you for the help!

**Comment by lnicola** [comment]
I think it's fine to enclose it with a function or closure if you know that the code is supposed to be a statement. "Only a part" is poorly-defined without that knowledge: what does `T` parse to?

**Comment by TathagataRoy1278** [comment]
I am sorry, what would be a better way to phrase it?

It is not limited to expressions, it can be any part of a rust code, just has to be a valid non-terminal.


If I understand you properly, `: T` parses into a SyntaxNode or a SyntaxElement.

**Comment by lnicola** [comment]
Ok, I guess it wasn't the best example, but still:

```rust
trait Tr : T {} // NAME followed by TYPE_BOUND_LIST with TYPE_BOUND and PATH

fn foo(x: T) {} // NAME followed by PATH
```

So `: T` can be parsed differently, depending on where it shows up. It's not a stand-alone piece of code.

You seem to think that we should special-case and support parsing a stand-alone statement like `let a = 10;`.

**Comment by TathagataRoy1278** [comment]
Thank you!

I did not mean to ask for a special case support. 
I just wanted to know if there is a "right" or idiomatic way for parsing standalone statements, instead of what I have been doing(wrapping things in a function), but it does make sense for rust-analyzer to not have it as it is a vscode extension and it always deals with complete files. I was just curious if the `syntax` crate had any special functions for doing that as I could not find them there.

Thanks again!

**Comment by lnicola** [comment]
No, I don't think so, but I think what you're doing right now is probably the best approach because it puts the code in the correct context.
