### ISSUE TITLE
Support for GOTO def from *inside* files included with `include!` macro?

### ISSUE THREAD

**Issue by cmyr** [rust-lang/rust-analyzer#14937]
so as of https://github.com/rust-lang/rust-analyzer/pull/14561, goto definition will now correctly locate tokens defined in a file that is included with the `include!` macro. This is wonderful.

Now there is the natural follow-up: would it be possible to have goto work *within* the generated file?

I can see some ways that this is complicated. In particular, there is potentially an `N->1` relationship between `include!` invocations and their targets, which means that there could be different sets (of possibly overlapping) symbols in scope for a given included file. I would imagine that any possible implementation of this would need to be limited to the case where any single file is only included from a single other file.

So... I'm really not sure how feasible this is, but it seems at least like something that would be nice to have eventually.

**Comment by hehaoqian** [comment]
I also want this feature. If "go to definition" is used on `include!` macro,
VSCode should open the included file, instead of where `include!` is defined.
This also needed to handle `env!("OUT_DIR")` inside `include!`
