### ISSUE TITLE
Autocomplete/hover broken for struct

### ISSUE THREAD

**Issue by pickx** [rust-lang/rust-analyzer#14940]
in `Cargo.toml`:
```
[dependencies]
tower-lsp = "0.19.0"
```
in `main.rs`:
```rust
fn main() {
    tower_lsp::Server::$0
}
```
...no suggestions are given for `struct Server`. if a proper function call is used, for example
```rust
//...
tower_lsp::Server::new(a, b, c);
```
then even after the code successfully compiles, hover is broken for `new()`.

**EDIT**: when specifying the types, suggestions still don't work, but hover/jump to definition do work after typing the function name.
for example,
```
[dependencies]
tower-lsp = "0.19.0"
tokio = { version = "1.28.2", features = ["io-util", "net"] }
```
```rust
tower_lsp::Server::<tokio::io::ReadHalf<tokio::net::TcpStream>, tokio::io::WriteHalf<tokio::net::TcpStream>, tower_lsp::ClientSocket>::$0
```

**rust-analyzer version**: 0.3.1533-standalone (505fd09f9 2023-05-28)

**rustc version**: 1.69.0

**Comment by lowr** [comment]
We're running into the same chalk bug as #14369. This should be fixed by rust-lang/chalk#792.

**Comment by lnicola** [comment]
@lowr should we ping jackh726 on that chalk PR?

**Comment by lowr** [comment]
I was particularly not really comfortable with pinging people (yes, I'm aware of that convo on zulip), but meanwhile that PR got merged finally! Now things are blocked on syn 2 upgrade I guess?

**Comment by Throne3d** [comment]
It looks like the chalk MR was merged here, and I can't reproduce this issue locally - is this still an issue on recent versions of RA?

![image](https://github.com/user-attachments/assets/6b596eb8-120d-4882-b7a5-ed7ec4e9e689)

**Comment by pickx** [comment]
@Throne3d 
> It looks like the chalk MR was merged here, and I can't reproduce this issue locally - is this still an issue on recent versions of RA?

thanks for the ping! 
I re-tested this and you're right. the first release where I could get `Server::new` to appear in the suggestions (and also simultaneously fixed the hover issue), is [2023-07-03](https://github.com/rust-lang/rust-analyzer/releases/2023-07-03). the changelist mentions #15185 which I guess could be what fixed this?

anyway, closing as already fixed.
