### ISSUE TITLE
trying to include! from another workspace doesn't support autocompletion nor seeing function declarations 

### ISSUE THREAD

**Issue by crwn1337** [rust-lang/rust-analyzer#14946]
**rust-analyzer version**: rust-analyzer version: 0.3.1533-standalone (505fd09f9 2023-05-28)

**rustc version**: rustc 1.70.0 (90c541806 2023-05-31)

**relevant settings**: everything is at default

autocomplete doesn't work:
![image](https://github.com/rust-lang/rust-analyzer/assets/38888474/ef2c5c0c-6d28-4219-92be-ab92c999061b)

but it does correctly identify when a function exists:
![image](https://github.com/rust-lang/rust-analyzer/assets/38888474/04c994ec-bb12-4d4a-b480-bad17545fb20)
![image](https://github.com/rust-lang/rust-analyzer/assets/38888474/efaba5a2-372c-4ce0-9278-1d3389aa681a)

trying to see the function declaration doesn't work as well:
![image](https://github.com/rust-lang/rust-analyzer/assets/38888474/86dabed4-1768-4328-8be4-3304368b62d5)

minimal reproducible example:
[test-rs.zip](https://github.com/rust-lang/rust-analyzer/files/11634067/test-rs.zip)

**Comment by Veykril** [comment]
Same root cause as https://github.com/rust-lang/rust-analyzer/issues/9173
