### ISSUE TITLE
Incorrect type inference for `fang::AsyncQueue`

### ISSUE THREAD

**Issue by affanshahid** [rust-lang/rust-analyzer#14954]
**rust-analyzer version**: 0.3.1533-standalone (505fd09f9 2023-05-28)

**rustc version**: 1.70.0 (90c541806 2023-05-31)

**relevant settings**: No special settings

Ran into a strange issue when using https://github.com/ayrat555/fang. In the following screenshot, RA seems to detecting the type of `task` as never (`!`), the code however, compiles just fine. The type of `self.task_queue` is `std::Arc<fang::AsyncQueue<fang::NoTls>>`. 

<img width="396" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/17955210/36a36c03-f8f5-4170-a424-d6173e74899d">

Not a big deal, just wanted to point it out.

**Comment by lowr** [comment]
@affanshahid #15000 may have fixed this issue. Can you try the latest nightly release and see if it correctly infers types?

**Comment by affanshahid** [comment]
Yes, can confirm it works correctly on nightly

**Comment by lowr** [comment]
Thanks for confirming, glad it worked!
