### ISSUE TITLE
Hiding of code lines (`#`) doesn't work when calling a function

### ISSUE THREAD

**Issue by xxshady** [rust-lang/rust-analyzer#14958]
https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#hiding-portions-of-the-example

**rust-analyzer version**: 0.4.1538-standalone (7f3bfc6ae 2023-06-02)

**rustc version**: 1.69.0

<img width="500px" src="https://github.com/rust-lang/rust-analyzer/assets/54737754/4fbef756-e995-450b-b7d0-2084cd670960" />

**Comment by lowr** [comment]
https://github.com/rust-lang/rust-analyzer/blob/9d5c34a80e37984b422cf0370654ed393db73c70/crates/rust-analyzer/src/to_proto.rs#L410-L415

We're currently returning the documentation as-is. We need to format the documentation here; see for example [here][hover] for how we format docs for other IDE functionalities.

[hover]: https://github.com/rust-lang/rust-analyzer/blob/9d5c34a80e37984b422cf0370654ed393db73c70/crates/rust-analyzer/src/to_proto.rs#L1393-L1403
