### ISSUE TITLE
Wacky color highlighting caused by declarative macro inside another declarative macro in VS Code

### ISSUE THREAD

**Issue by Pieresqi** [rust-lang/rust-analyzer#14964]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

`0.3.1533-standalone`
`0.4.1539-standalone`

**rustc version**: (eg. output of `rustc -V`)

`rustc 1.69.0`
`rustc 1.70.0`

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

default by `cargo new XXXX`

**Report**
Wacky color highlighting caused by declarative macro inside another declarative macro in VS Code.

Expected(?) (before rust-analyzer loaded) result:
![ok](https://github.com/rust-lang/rust-analyzer/assets/109971558/cb5bdba1-fa67-4da5-8360-c263d013a518)

Actual result:
![err](https://github.com/rust-lang/rust-analyzer/assets/109971558/6db4d379-a802-4f3d-bc9a-3a4b8fbae037)

Code:
```
let bol = true;

    // minimal reproduction
    let _ = format!("{}", {
        format!("");
        bol 
    },);

    let _ = format!(
        "{}{}{}",
        // ok
        if bol { "beep" } else { "boop" },
        // broke here
        format!("beep"),
        // broken :(
        if bol {
            "beep"
        } else {
            match bol {
                true => "beep",
                false => "boop",
            }
        }
    );

```

**Comment by Veykril** [comment]
This is https://github.com/rust-lang/rust-analyzer/issues/14841
