### ISSUE TITLE
"Bootstrap Error" in 0.3.1541, regression from 0.3.1533

### ISSUE THREAD

**Issue by gabiganam** [rust-lang/rust-analyzer#14981]
I'm using the extension on an AL2 machine, with ldd (GNU libc) 2.26.
Latest version 0.3.1541 fails with:

Bootstrap error [Error: Failed to execute /home/user/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1541-linux-x64/server/rust-analyzer --version
/home/user/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1541-linux-x64/server/rust-analyzer: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/user/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1541-linux-x64/server/rust-analyzer)

Rolled back to 0.3.1533 and it's working fine.

**Comment by lnicola** [comment]
The binaries are built in a pretty outdated Ubuntu 18.04 container. It looks like they upgraded to GLIBC 2.27 recently.

I suggest building from source instead.

**Comment by lnicola** [comment]
We now require GLIBC 2.31, see #16793.
