### ISSUE TITLE
faulty code highlighting - format!("inside of {}", format!(""))

### ISSUE THREAD

**Issue by jdato** [rust-lang/rust-analyzer#14983]
rust-analyzer version: 0.3.1541-standalone (2f1b7cedc 2023-06-04)

rustc 1.69.0 (84c898d65 2023-04-16)

expected:
```rust
fn q() {
    format!("{}{}",
        if true { "some text, " } else { "some other text, " },
        format!("some answer within 2. format, {} to {}, {}",
            1, 10,
            format!("some answer within 2. format, {} to {}, {}",
                1, 10, format!(""),
            ),
        ),
    );
}
```

actual with rust-analyzer enabled:
![image](https://github.com/rust-lang/rust-analyzer/assets/22294144/8bfa56aa-867a-4bb0-922d-256a85ebd5ad)

actual with rust-analyzer disabled:
![image](https://github.com/rust-lang/rust-analyzer/assets/22294144/3ccb7e51-dd02-4b66-84f9-4c778c761030)

**Comment by lnicola** [comment]
I think this is the same as #14841.

**Comment by Veykril** [comment]
It is
