### ISSUE TITLE
[Feature Request] Generate trait from impl

### ISSUE THREAD

**Issue by Alonely0** [rust-lang/rust-analyzer#14987]
First of all, I wouldn't mind contributing to RA and implementing this by myself if someone guides me.
It is common when prototyping to, instead of creating a trait and implementing it, to just implement the methods on the first struct that requires the trait; and when prototyping is over, to turn it all into a trait and a trait impl. This is because when changing function signatures, you have to (at least) change them in two different places, which can become tedious and slow down development, especially when generics are involved.

My idea is to have a feature that allows you to convert the functions inside an impl block into a trait, and then just change the impl block declaration to implement the trait.

For example, with an initial code of:

```rs
struct Foo(f64);

impl Foo {
    fn add(&mut self, x: f64) {
        self.0 += x;
    }
    // etc
}

```

After applying the helper, it would become:

```rs
struct Foo(f64);

trait Bar {
    fn add(&mut self, x: f64);
    // etc
}

impl Bar for Foo {
    fn add(&mut self, x: f64) {
        self.0 += x;
    }
    // etc
}

```

**Comment by alibektas** [comment]
I would be more than happy to do it.
