### ISSUE TITLE
"Unwrap on a `None` value" when expanding incomplete macro invocation

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#15002]
This unwrap can fail when the macro input is malformed:

https://github.com/rust-lang/rust-analyzer/blob/085a3112ae9e11c0cdfbcbc3413919fe9e39e8d2/crates/hir-expand/src/builtin_fn_macro.rs#L284

This happened in proprietary code so I can't provide an example, sadly.

**Comment by jonas-schievink** [comment]
Looks like you may be able to repro it with a `tracing::event!` invocation that takes key-value arguments

**Comment by Veykril** [comment]
```rs
format_args!(x =);
```
panics for me
