### ISSUE TITLE
Inconsistent expression adjustment hints

### ISSUE THREAD

**Issue by zhaoyangwuuuu** [rust-lang/rust-analyzer#15018]
**rust-analyzer version**: rust-analyzer version: 0.3.1541-standalone

**rustc version**: rustc 1.70.0 (90c541806 2023-05-31)

Please see the attached video. The hover text from the expression adjustment hints appears differently each time the cursor hovers over it.
https://github.com/rust-lang/rust-analyzer/assets/11637049/1e1f89f4-7af6-4fa2-be0e-f0ff34b0d2bc

**Comment by Veykril** [comment]
You are hovering over the `(` hint first which has no tooltip, then you move your cursor from that to the adjustment hint but vscode does not change the tooltip hover for inlay hints if you hover from inlay hint to inlay hint without going over a non inlay hint part in the buffer. That's VSCode behavior, nothing we can change there.
