### ISSUE TITLE
Cannot Expand Procedural Macros

### ISSUE THREAD

**Issue by HTG-YT** [rust-lang/rust-analyzer#15042]
**rust-analyzer version**: rust-analyzer 0.4.1550-standalone (1f1fe81f0 2023-06-12)

**rustc version**: rustc 1.72.0-nightly (df77afbca 2023-06-12)

Loading a project with usage of procedural macros results in an error saying "incompatible API versions" between procedural macro server and rust-analyzer.

![image](https://github.com/rust-lang/rust-analyzer/assets/39023054/bcc2a053-6ef0-4e66-8838-13b4dd4c720d)

**Comment by HTG-YT** [comment]
Let me check the logs from Fleet. One sec -

**Comment by HTG-YT** [comment]
(Sorry, I posted the wrong version string)

**Comment by HTG-YT** [comment]
> Are you using a `rust-toolchain` file? These should be in sync: https://github.com/rust-lang/rust/blob/master/src/tools/rust-analyzer/crates/proc-macro-api/src/msg.rs#L18.

I am not using the `rust-toolchain` file.

**Comment by Veykril** [comment]
`rust-analyzer 0.4.1550-standalone (1f1fe81f0 2023-06-12)` should be using version 2, so something doesn't add up here, https://github.com/rust-lang/rust-analyzer/blob/1f1fe81f0/crates/proc-macro-api/src/msg.rs#L20

**Comment by lnicola** [comment]
It really looks like you're running an older rust-analyzer binary.

**Comment by HTG-YT** [comment]
Seems like so - when I looked into Task Manager, Fleet isn't actually running the rust-analyzer from the location as I expected.

**Comment by ryanavella** [comment]
Leaving this here for anyone else with the same issue.

I was using a specific version of rust-analyzer that was patched for my OS, and things worked fine for a while until I ran `rustup update`. The solution was to run `rustup component add rust-analyzer` and then point my IDE to this new binary instead.
