### ISSUE TITLE
Failed to read Cargo metadata from rustc source

### ISSUE THREAD

**Issue by aryan-debug** [rust-lang/rust-analyzer#15046]
I am working on the Rust compiler and was trying to set up the compiler, but rust-analyzer decided to stop working for some reason. I followed the rust dev guide and I do have a `settings.json` file in `.vscode`.

This is the error message:
``` [ERROR project_model::workspace] Failed to read Cargo metadata from rustc source at /home/Aryan/Documents/projects/rust/./Cargo.toml e=Failed to run `"/home/Aryan/.cargo/bin/cargo" "metadata" "--format-version" "1" "--manifest-path" "/home/Aryan/Documents/projects/rust/./Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"` ```

I also have cargo in PATH:
❯ ```echo $PATH```
```/home/Aryan/eww/target/release:/home/Aryan/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin:/home/Aryan/.spicetify:/home/Aryan/pipes.sh```

**Comment by Veykril** [comment]
It should say more as to why the command failed, but I think I know the problem. Iirc the rust repo is using some unstable cargo feature in one of the Cargo.tomls now, so our `cargo metadata` call fails if you are on a stable toolchain

**Comment by lnicola** [comment]
```
  the cargo feature `public-dependency` requires a nightly version of Cargo, but this is the `stable` channel
```

**Comment by lnicola** [comment]
I guess you can try `rustup default nightly`.

**Comment by aryan-debug** [comment]
I did, but I still get the same error.
```
rustup default nightly
```
```
info:` using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.72.0-nightly (7820972f8 2023-06-10)

info: note that the toolchain 'stable-x86_64-unknown-linux-gnu' is currently in use (directory override for '/home/Aryan/Documents/projects/rust')
```

For some reason, it still says the same thing: 
```
the cargo feature `public-dependency` requires a nightly version of Cargo, but this is the `stable` channel`
```

**Comment by Veykril** [comment]
> info: note that the toolchain 'stable-x86_64-unknown-linux-gnu' is currently in use (directory override for '/home/Aryan/Documents/projects/rust')

**Comment by aryan-debug** [comment]
I restarted it, but still the same issue. The command you mentioned says the same thing that @Veykril pasted.

**Comment by aryan-debug** [comment]
Nope

**Comment by Veykril** [comment]
You have a directory override active

**Comment by aryan-debug** [comment]
I will just send an imgur link. Here, https://imgur.com/a/xvNjQzn

**Comment by Veykril** [comment]
cyclic errors are a known problem, especially in the rust compiler workspace. You can ignore them they shouldnt cause too many problems.

That error youve shown there Ive got no idea about, you might wanna ask about that on the rust-lang zulip

**Comment by aryan-debug** [comment]
Gotcha. I will do that and post the solution here in case someone runs into the same issue. Thanks for your help and time!

**Comment by Veykril** [comment]
Closing this as the rustc workspace has a bunch of issues, should be resolved once rust-project.json is implemented for bootstrap
