### ISSUE TITLE
Extract Module to (an existing) File in another directory

### ISSUE THREAD

**Issue by Mathijs-Bakker** [rust-lang/rust-analyzer#15059]
## Extract Module
There is the 'Extract Module to File' action. It extracts the module in an existing file (or creates a new one) in the same directory as the original file.
It would be nice to have some kind of refactoring solution that adds the option to **Extract Module to File in an other Directory.**

Maybe there's an other way to do this, but I could not find any solution.

## Example behavior

When you have a file structure like this:
```
main.rs
└ my_dir
    └ foo.rs
```

And in _main.rs_ you have the module named qux,
which needs to be extracted to _my_dir/foo.rs_
```
fn main() {}

mod qux {
   fn bar() {
      // ...
   }
}
```

Which results in my_dir/foo.rs:
```
fn bar() {
   // ...
}
   
fn qux() {
   // ...
}
```

**Comment by TheBlckbird** [comment]
+1

**Comment by flodiebold** [comment]
If I understand this correctly, it's "Move item", #2178.
