### ISSUE TITLE
rust-analyzer can invoke build scripts with `RUSTC_BOOTSTRAP=1`, wreaking havoc on feature detection

### ISSUE THREAD

**Issue by SludgePhD** [rust-lang/rust-analyzer#15057]
**rust-analyzer version**: 0.3.1541

**rustc version**: rustc 1.70.0 (90c541806 2023-05-31)

**relevant settings**:
- `"rust-analyzer.cargo.buildScripts.useRustcWrapper": false,`

Some crates (for instance anyhow and thiserror) determine whether they are being built by a supported nightly compiler by performing a trial compilation in their build script (think autotools). It seems like rust-analyzer will invoke build scripts while having `RUSTC_BOOTSTRAP` set (perhaps only under some circumstances), which makes those crates think they can use nightly features.

This appears to "work" in rust-analyzer, and "poisons" the build cache with the build script output. A later `cargo run` in the terminal will then reuse the build script output, and build the crate in question *without* having `RUSTC_BOOTSTRAP` set, leading to errors like this:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/sludge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.71/src/lib.rs:214:32
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/sludge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.71/src/lib.rs:214:61
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                                             ^^^^^^^^^^^
```

This has previously been reported in https://github.com/dtolnay/thiserror/issues/192 as affecting users that have `rust-analyzer.cargo.buildScripts.useRustcWrapper` *enabled* (the default), while I have it *disabled*, so it seems that the setting may be a red herring and doesn't matter.

**Comment by loynoir** [comment]
Got same error when `dtolnay/thiserror` and `dtolnay/anyhow` in dependency tree.

At the same time, I use `sccache`.

Try below does not working.

- `"rust-analyzer.cargo.buildScripts.useRustcWrapper": false`

**Then**

- disable RA

- `cargo clean`

- build

Now seems working correctly.

**Comment by lnicola** [comment]
This should have been fixed in #12973 / #13010. `anyhow` works fine for me. Which versions are you using, and does it happen in a new project?

**Comment by loynoir** [comment]
Yes, recent project, maybe 1~2 weeks.

**Comment by lnicola** [comment]
It works fine for me without changing any settings. Are you sure you're not running a very old version of RA? And please try in an empty project.

**Comment by loynoir** [comment]
RA `v0.3.1705`.

**Comment by Veykril** [comment]
This should be fixed?

**Comment by txase** [comment]
This issue isn't fixed yet. I posted PR #16621 to fix it.
