### ISSUE TITLE
`HasSource::source` should be infallible

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15088]
None of the implementations ever return `None`, so it should not return an option either. https://github.com/veykril/rust-analyzer/blob/9476fdaaa96323800b43c528e59617b14908d6a2/crates/hir/src/has_source.rs#L23

**Comment by tetsuharuohzeki** [comment]
I would like to take this.

However, `HasSource::source` has been changed to return `Option` once in #6913. 
Was the motivation in #6913 outdated?

**Comment by Veykril** [comment]
Oh, I forgot about that. Hmm having it return an `Option` does make sense then given we might want to support rlibs someday

**Comment by tetsuharuohzeki** [comment]
@Veykril I open https://github.com/rust-lang/rust-analyzer/pull/15140 to add why we use `Option` for `HasSource::source`
