### ISSUE TITLE
wrong negative integer constant preview (on hover)

### ISSUE THREAD

**Issue by antonilol** [rust-lang/rust-analyzer#15096]
**rust-analyzer version**: 0.4.1558-standalone

**rustc version**: rustc 1.70.0 (90c541806 2023-05-31)

**relevant settings**: None

```rust
const A: i64 = i32::MIN as i64;
```

![image](https://github.com/rust-lang/rust-analyzer/assets/49868160/0b388703-e979-4614-ab00-8c2a3fac8027)

`A` is -2147483648 (i32::MIN), but then as a i64, but this does not change the value because i64 can hold all values i32 can

**Comment by dfireBird** [comment]
I took a shot at debugging this and found the source. Would it be okay if I open a PR for the fix (and discuss any changes to fix if I'm wrong)?

**Comment by HKalbasi** [comment]
It would be great!
