### ISSUE TITLE
Delegate trait impl assist does not subsitute generic params

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15108]
Okay, this mostly looks good but there is one thing that we should fix still, which can be seen in your second gif (im not talking about the unstable thing being proposed). We forget to account for the substituted generics. Example:
```rs
struct S { f: Foo<i32>$0 }

struct Foo<U>(U);

trait T<U> {
    type Ty;
    fn f(self) -> Self::Ty;
}
impl<U> T<U> for Foo<U> {
    type Ty = U;
    fn f(self) -> Self::Ty {
        self.0
    }
}

```
Current assist would generate the following which is invalid
```rs
impl<U> T<U> for S {
    type Ty = <Foo<U> as T<U>>::Ty;
    fn f(self) -> Self::Ty {
        <Foo<U> as T<U>>::f(self.f) // type error, `<Foo<U> as T<U>>::f` expects a value of type `Foo<U>`, but here we give it a `Foo<i32>`
    }
}
```
It should instead generate this:
```rs
impl T<i32> for S {
    type Ty = <Foo<i32> as T<i32>>::Ty;
    fn f(self) -> Self::Ty {
        <Foo<i32> as T<i32>>::f(self.f)
    }
}
```

_Originally posted by @Veykril in https://github.com/rust-lang/rust-analyzer/pull/14948#pullrequestreview-1492858502_

**Comment by ponyii** [comment]
I'll write a patch
