### ISSUE TITLE
lsp-server 7.1 pins serde to old version

### ISSUE THREAD

**Issue by ogoffart** [rust-lang/rust-analyzer#15107]
The recent release of lsp-server 7.1 pins the version of its serde dependency:

https://github.com/rust-lang/rust-analyzer/blob/85493dfdb045ce78db78c6d50e8015bdb442cc62/lib/lsp-server/Cargo.toml#L12

via 

https://github.com/rust-lang/rust-analyzer/blob/85493dfdb045ce78db78c6d50e8015bdb442cc62/Cargo.toml#L97-L98

This may causes problem in upstream crates that uses newer version of serde directly or indirectly.

The comment mention syn1 vs. syn2 duplication, but lsp-server is not impacted by that as it only depends on syn through serde. So it would be better then not to use serde as a workspace dependency.

(And btw, this pinning is not effective because rust-analyzer depends on syn2 anyway via chalk-derive.
I'd say pinning in Cargo.toml is not the right way to pin crate for this reason, it should be done in Cargo.lock)

**Comment by Veykril** [comment]
The lib crates being connected to workspace dependencies is definitely a mistake (especially now that we treat them separate anyways)
