### ISSUE TITLE
Outer line docs italicises entire code block

### ISSUE THREAD

**Issue by the-emerald** [rust-lang/rust-analyzer#15111]
**rust-analyzer version**: rust-analyzer version: 0.4.1560-standalone

**rustc version**: rustc 1.70.0 (90c541806 2023-05-31)

**relevant settings**: None

Adding a outer line doc (`///`) to an enum, struct, and function italicises the entire code block.

![image](https://github.com/rust-lang/rust-analyzer/assets/12746683/22b60053-9643-44e8-bace-5099b63bc024)
![image](https://github.com/rust-lang/rust-analyzer/assets/12746683/ec97c7c6-0b8d-46a9-829b-c9784a17d40c)

![image](https://github.com/rust-lang/rust-analyzer/assets/12746683/2e446564-026b-4c36-9aca-1227ec022ef7)
![image](https://github.com/rust-lang/rust-analyzer/assets/12746683/10623324-0012-4cc8-81c7-e484e42a99e8)

![image](https://github.com/rust-lang/rust-analyzer/assets/12746683/8c857984-3195-40d9-b8c1-7c0db09dc01a)
![image](https://github.com/rust-lang/rust-analyzer/assets/12746683/1f748a1a-44e6-49f6-91ce-241ea536bb32)

**Comment by lnicola** [comment]
Doesn't seem to be noticeable with the default theme, can you run Inspect Editor Tokens and Scopes on the enum name with and without the comment?

I get:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/f847f7a5-30c7-4550-b383-c3e1826d9c9d)

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/b8a2450a-c519-40a3-ac11-4e37135a5658)

vs.

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/34f40ea1-f2ec-4f3e-8d4e-6262f7fce7db)

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/ac03db17-c064-4495-b79d-838ca96afc65)

**Comment by lnicola** [comment]
Looks like it's the Markdown injection agani.

**Comment by the-emerald** [comment]
![image](https://github.com/rust-lang/rust-analyzer/assets/12746683/4625b428-26bc-40c2-9bad-727e197024c8)
![image](https://github.com/rust-lang/rust-analyzer/assets/12746683/bffd8944-719a-4707-8a9d-1619e2cfe629)


Also noticed this, which sounds like Markdown issues:
![image](https://github.com/rust-lang/rust-analyzer/assets/12746683/6785a1de-b09b-4d2b-a2eb-4705fa4f7e14)

**Comment by Ruthenic** [comment]
Getting this same issue, except slightly worse because it also colors all the code in the comment color
![image](https://github.com/rust-lang/rust-analyzer/assets/53356436/e490f2ac-25ff-4a34-98a1-4eaef61e7ded)

Theme is [Sonokai](https://marketplace.visualstudio.com/items?itemName=sainnhe.sonokai)
rust-analyzer version is `1.72.0-nightly (065a1f5d 2023-06-21)`
rust-analyzer VSC extension version is `v0.4.1560` (pre-release)

**Comment by Ruthenic** [comment]
Rolling back to extension ver. `v0.4.1559` makes it work fine so it's probably something between then and v0.4.1560
![image](https://github.com/rust-lang/rust-analyzer/assets/53356436/7e1f23c1-7621-4d75-abff-16480b3fffff)

**Comment by lnicola** [comment]
Yeah, it was https://github.com/rust-lang/rust-analyzer/pull/14866.

**Comment by Veykril** [comment]
This regressed with https://github.com/rust-lang/rust-analyzer/pull/15102
