### ISSUE TITLE
Only initial /// is highlighted in doc comments

### ISSUE THREAD

**Issue by charlespierce** [rust-lang/rust-analyzer#15114]
As of the most recent release version of RA, I'm seeing the syntax highlighting for doc comments being broken. Rather than the full comment being colored the "comment" color, only the initial `///` is, and the comment itself is in the standard foreground color. Additionally, VS Code generic highlighting like parentheses matching is applying to the comment text.

![Screenshot 2023-06-22 at 1 10 18 PM](https://github.com/rust-lang/rust-analyzer/assets/18537342/009bbae9-8125-46e6-9844-0ee744ae219a)

**rust-analyzer version**: Multiple
* 0.3.1557-standalone (cd3bf9fe5 2023-06-18)
* 0.4.1560-standalone (85493dfdb 2023-06-21)
* 0.4.1559-standalone (2d64a0aa6 2023-06-20)
* 0.4.1550-standalone (1f1fe81f0 2023-06-12)

Note: This does _not_ happen on the previous release version `0.3.1549-standalone (d567091f4 2023-06-11)` nor on pre-release version `0.4.1548-standalone (d567091f4 2023-06-11)`

**rustc version**: rustc 1.68.2 (9eb3afe9e 2023-03-27)

**relevant settings**: None that I'm aware of

**Comment by lnicola** [comment]
This looks different, but is the same as #15111.

**Comment by charlespierce** [comment]
I thought it might be when looking, however the discussion in that issue indicated that rolling back to `0.4.1559` fixed it, which wasn't the case for me (I had to go back to `0.3.1549` or `0.4.1548` to fix it). If it is the same root cause just a different manifestation then happy to follow that issue for a full resolution!

**Comment by Veykril** [comment]
Yep, this regressed with https://github.com/rust-lang/rust-analyzer/pull/15102
