### ISSUE TITLE
Auto-complete didn't work inside proc macro .

### ISSUE THREAD

**Issue by nurmohammed840** [rust-lang/rust-analyzer#15122]
See: https://github.com/dtolnay/syn/issues/1472

**Comment by flodiebold** [comment]
With a function-like proc macro, rust-analyzer has no idea that the tokens inside are supposed to be code, so it can't do any error recovery. And syn will just fail to parse the incomplete code `num.`, and the proc macro won't return anything, so rust-analyzer has no way of knowing what to do with it. See also #7402. You can make this proc macro work by not parsing the input, and just passing it through. Or if you need to analyze it somehow, you need an error-resilient parser.

**Comment by nurmohammed840** [comment]
I think you misunderstood, The code is not incomplete,  and the macro do return valid code, with span preserved.

**Comment by flodiebold** [comment]
When you're writing
```rust
fn main() {
    code!({
        let num = 42;
        num. ???  // No code completion ☹️
    });
}
```
the code is incomplete and not a valid expression, so `syn::parse_macro_input!(input)` fails.

**Comment by nurmohammed840** [comment]
I re-implemented my proc-macro with a more IDE friendly, which solved this problem.
