### ISSUE TITLE
autoimport does nothing when importing trait that is `as _` imports

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15128]
```rs
mod foo {
    pub trait Foo {
        fn f(self) {}
    }
    impl Foo for () {}
}
use self::foo::Foo as _;
fn f<X: Foo$0>() {
    ().foo();    
}

```

**Comment by mohsen-alizadeh** [comment]
What is the expected behavior in this example?

**Comment by Veykril** [comment]
We should drop the `as _` part when requesting the import

**Comment by dfireBird** [comment]
Is this issue being worked on? If not can I work on it?

**Comment by lowr** [comment]
@dfireBird Go for it! You can use `@.rustbot claim` (without the period ofc) to assign yourself to this issue if you'd like.

**Comment by dfireBird** [comment]
Oh Thanks. But I'm not sure If I'll be able to solve it so I don't want to claim without sure.
I have a question the correct behavior on this (see code below) cursor position should remove `as _` from the already written `use` right?
 ```rust
 mod foo {
    pub trait Foo {
        fn f(self) {}
    }
    impl Foo for () {}
}
use self::foo::Foo as _;
fn f<X: Foo$0>() {
    ().foo();    
}
```

**Comment by lnicola** [comment]
Yes, that's exactly what https://github.com/rust-lang/rust-analyzer/issues/15128#issuecomment-1606743395 says.

**Comment by dfireBird** [comment]
@lnicola Sorry I was confused, that's why I asked the question to clarify, but thanks for confirming.
