### ISSUE TITLE
RUSTUP_HOME is ignored in VS code extension

### ISSUE THREAD

**Issue by DziubanMaciej** [rust-lang/rust-analyzer#15124]
I'm using a custom `RUSTUP_HOME` location and it seems to be ignored by the VSCode extension. I set the env variable in my `.profile` and I can see it being loaded in VSCode terminal. However, rust-analyzer tries to use default location `$HOME/.rustup`. It creates the directory (which I don't want) and fails to find toolkits:

![image](https://github.com/rust-lang/rust-analyzer/assets/23078999/01f88778-4088-422a-a1cc-ad8bbbaee229)
![image](https://github.com/rust-lang/rust-analyzer/assets/23078999/af9be686-0fec-4518-a4d0-6672507f5d48)

**rust-analyzer version**: 0.3.1557-standalone

**rustc version**: rustc 1.69.0 (84c898d65 2023-04-16)

**relevant settings**: `$RUSTUP_HOME` or `$CARGO_HOME`

**Comment by bjorn3** [comment]
The shell program that runs in the terminal executes `.profile`. This does not mean that vscode itself started up with it. You can try using htop and selecting the rust-analyzer process and finally press <kbd>e</kbd> to list all environment variables rust-analyzer runs with. Can you check if `RUSTUP_HOME` is included in this?

**Comment by DziubanMaciej** [comment]
> The shell program that runs in the terminal executes .profile. This does not mean that vscode itself started up with it. 

I am aware, but initially the env was not set in the VSCode terminal at all (I was setting it in `.xinitrc`). It started to show up, when I moved it to `.profile`, so I assumed that's what I was supposed to do.

> You can try using htop and selecting the rust-analyzer process and finally press e to list all environment variables rust-analyzer runs with. Can you check if `RUSTUP_HOME` is included in this?

Oh, I didn't know extensions run in separate processes. Thank you for pointing this out, `RUSTUP_HOME` indeed isn't set for `rust-analyzer` process. Do you know why? Where do I have to set this env, so it works?

**Comment by bjorn3** [comment]
It looks like you can set them in `~/.pam_environment` in `KEY=value` format. You will need to logout and login again for it to take effect.

**Comment by DziubanMaciej** [comment]
Okay, the key point is to logout and login again... VSCode seems to be caching variables in `~/.profile` somewhere, so changes are ignored during application restart. Although, `~/.pam_environment` does not work. `~/.profile` does work, but you have to logout and login for it to take effects. Thanks!
