### ISSUE TITLE
private visibility is shown in autocompletion

### ISSUE THREAD

**Issue by asyncci** [rust-lang/rust-analyzer#15134]
I have `pub(self) fn function() {}` in module named `becoding` , and autocomplete in outer files shows that function .
![image](https://github.com/rust-lang/rust-analyzer/assets/116139249/870d6ab3-4cf6-4d69-b7a5-e251a9b1edd8)
but the error is ok 
![image](https://github.com/rust-lang/rust-analyzer/assets/116139249/f8b43af1-3f8c-46f5-af88-f545bc7aabd3)

But when it comes to `pub(in crate::becoding)fn function(){}` , autocomplete hides that function .
![image](https://github.com/rust-lang/rust-analyzer/assets/116139249/d9cb2cff-c9cf-41fc-aa01-4416b54b1116)
![image](https://github.com/rust-lang/rust-analyzer/assets/116139249/18ae7102-34e6-4432-9d91-33edf30da5a9)

**Comment by petr-tik** [comment]
@asyncci Can you please help me reproduce your failure. 

I recreated a test case from your screenshots here

https://github.com/rust-lang/rust-analyzer/compare/master...petr-tik:rust-analyzer:n15134_hide_private_from_autocomplete

but I am not seeing `i_should_be_hidden`, which is equivalent to your `bencoding::function`. 

What is the name of the file where function and function2 are defined? Are they nested in a module?

**Comment by petr-tik** [comment]
@asyncci hey would appreciate if you could build rust-analyzer from my PR branch and test drive it in your project. 

When I tried it, only the public function were offered as completions, so I would appreciate if I missed anything

**Comment by asyncci** [comment]
> @asyncci hey would appreciate if you could build rust-analyzer from my PR branch and test drive it in your project. 
> 
> 
> 
> When I tried it, only the public function were offered as completions, so I would appreciate if I missed anything

Yes of course, but I’m not at home currently , probably in two-three days

**Comment by asyncci** [comment]
Now it works correctly    
```main.rs```:
![image](https://github.com/rust-lang/rust-analyzer/assets/116139249/0f47b3f3-67d9-47af-896c-d8437dc6997b)
```decoder.rs```:
![image](https://github.com/rust-lang/rust-analyzer/assets/116139249/1a2d425b-2c64-4d93-9d00-e2f7b4eac4f9)
 Thanks ! Sorry for delay.
