### ISSUE TITLE
Extremely frustrating loss of window focus 500-1000ms after saving file.

### ISSUE THREAD

**Issue by sarahkittyy** [rust-lang/rust-analyzer#15156]
**rust-analyzer version**: rust-analyzer version: 0.3.1566-standalone (4a2ceeff0 2023-06-25)

**rustc version**: rustc 1.70.0 (90c541806 2023-05-31)

**relevant settings**: N/A

I am writing code, in rust, and I hit save, and then a bit later, the editor just loses focus. It's once every maybe 30 seconds, and I can't seem to reliably reproduce it. I have to click back into the window every time and it's ridiculously frustrating.

I have disabled all extensions except rust-analyzer, and it happens. I don't know if it's rust-specific or just happens with any language. It's completely random and inexplicable. The whole editor window drops focus, not just the text editor (indicated by the top bar changing color).

It seems to happen particularly when typing something that isn't valid rust code, maybe it has something to do with cargo check or semantic highlighting?

I cannot seem to replicate this with the C++ extension.

Here is a video of the issue happening with only rust-analyzer installed. You can see the window title bar changing color, indicating focus lost.

https://user-images.githubusercontent.com/31551546/248588662-9a177d22-4696-4808-b391-e80e9e123657.mp4

**Comment by sarahkittyy** [comment]
Replicating this is very inconsistent. Here are some more videos of this same issue occuring, this time with my full range of extensions installed.

https://user-images.githubusercontent.com/31551546/248589628-9e371d5d-b26a-4560-bd62-4411c8716d02.mp4
https://user-images.githubusercontent.com/31551546/248589627-cbd1004b-8890-4f72-8952-ddad3b1cc8b8.mp4

**Comment by sarahkittyy** [comment]
More footage of the bug occuring, this time with my whole range of extensions installed (doesn't make a difference)

https://user-images.githubusercontent.com/31551546/248589628-9e371d5d-b26a-4560-bd62-4411c8716d02.mp4
https://user-images.githubusercontent.com/31551546/248589627-cbd1004b-8890-4f72-8952-ddad3b1cc8b8.mp4

**Comment by sarahkittyy** [comment]
I have so many videos in which I try to replicate the bug by doing dozens of permutations of:
- Reloading window
- Writing invalid code and saving.
- Running cargo check.
- Deleting lines that error and saving.

And it only happens sometimes. It's completely inconsistent. I swear it knows I'm recording it. If I actually try to get any work done it's going to start happening every other save. I'm being gaslit by vscode.

![image](https://github.com/rust-lang/rust-analyzer/assets/31551546/9e680136-da62-4329-829b-5451689adc35)

**Comment by sarahkittyy** [comment]
Here it is again, way after the save.
https://github.com/rust-lang/rust-analyzer/assets/31551546/975ff48e-be92-4b27-a2e6-3ad3ea507d4d

**Comment by Veykril** [comment]
This sounds like a vscode issue. r-a doesn't have any special logic that would change the focus of any ui elements

**Comment by yannick818** [comment]
I have had the same problem for a few days now. It occurs after saving.

**Comment by Veykril** [comment]
Sounds like something else is stealing your window focus, as Ive written before, this is not a r-a issue, there is nothing within r-a that would fiddle with the window focus
