### ISSUE TITLE
Assists are broken

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15176]
Since today I am unable to use any of our assists, none of them trigger (except for diagnostic quickfixes)

**Comment by Veykril** [comment]
Looks like we are always panicking in `rust_analyzer::handlers::request::handle_code_action`

**Comment by Veykril** [comment]
Found the cause https://github.com/rust-lang/rust-analyzer/pull/15101/files#r1247491229

**Comment by lnicola** [comment]
[These](https://github.com/rust-lang/rust-analyzer/pull/15101/files#diff-54643fb127864af46d85f797ed28bab413a5b6769969ea4d36b6b885ad2f203aR2040) also look iffy, I think?

**Comment by Veykril** [comment]
I might've been tired when doing that review ... @alibektas I fixed the main unwrap problem in https://github.com/rust-lang/rust-analyzer/pull/15177
Could you clean up the remaining unwraps from your recent PR?

**Comment by alibektas** [comment]
Sorry. On it now.
