### ISSUE TITLE
When loading workspaces fails, tell the user if the `linkedProjects` config is set

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15171]
Currently when someone has the `linkedProjects` config set and their workspace fails to load (due to the config pointing to non-existing paths or similar), the user will just get confused as r-a doesn't tell them anything else. We should tell them loud and clear that it is most likely a misconfiguration of the `linkedProjects` config causing them problems.

**Comment by stupendoussuperpowers** [comment]
could you clarify what you expect the error message to be/what you see currently?

for me, I see the following when it fails to load a `linkedProject` from the settings, which does point to a failure and a suggestion with it - 

```[ERROR rust_analyzer::config] failed to load linked project: project root must point to Cargo.toml or rust-project.json: /home/../../.\Cargo.toml```

**Comment by stupendoussuperpowers** [comment]
will submit a pull request for this.

**Comment by bccf3** [comment]
[let path = self.root_path.join(it);](https://github.com/rust-lang/rust-analyzer/blob/2f6961aaaf65cff82e43ca9171fd7a824a7d81ca/crates/rust-analyzer/src/config.rs#L937C18-L937C18)
I change the line above to this: 
```rust
      let path = self.root_path.join(it.to_str().unwrap().replace("\\", "/"));
```
has resolved the problem. But it seems not  the best solution
