### ISSUE TITLE
Surprisingly high resource consumption after closing editor that spawned rust-analyzer process

### ISSUE THREAD

**Issue by erikkrieg** [rust-lang/rust-analyzer#15187]
I'm on an M1 MacBook using rust-analyzer with nvim and it is configured by [rust-tools](https://github.com/simrat39/rust-tools.nvim). I have recently noticed that that after closing my editor the rust-analyzer process continues and consumes a surprisingly large amount of CPU  and "energy impact" (kinda opaque MacOS system metric that acts as a proxy for a process' impact on the battery).

I noticed this in a rust template project that only has rust source files from `cargo init`. So a super small project. At the time of writing I was on this commit of my rust template project: https://github.com/erikkrieg/rust-template/tree/8932ed073a1872f1d988f99dafecceab58dfffe8

I'm not sure whether the issue has to do with the version of rust-analyzer I am using, the `rust-tools` plugin for nvim, or maybe even the rust-analyzer package in the [Nixpkgs registry!?](https://github.com/NixOS/nixpkgs). If there are suggestions for how I might help better identify the potential source of the problem I'd gladly perform additional diagnostics!

## While nvim was still running
Seeing ~4-5% CPU usage.  Even at this point the "energy impact"  for rust-analyzer was more than 10x the next highest process. While the editor was open I also noted fseventsd significantly increasing in resource consumption.
<br>
<img width="561" alt="Screenshot 2023-06-30 at 5 25 59 PM" src="https://github.com/rust-lang/rust-analyzer/assets/10244162/e6ccc3e0-d24a-4d93-b768-f1fddef36041">
<br>
<img width="994" alt="Screenshot 2023-06-30 at 5 26 29 PM" src="https://github.com/rust-lang/rust-analyzer/assets/10244162/f00db0e5-6c5e-47fd-9ff4-ccc85a21a116">

## After exiting nvim
When nvim closed I experienced roughly a 3x increase in CPU usage and more than 2x increase in "energy impact" (although fsevents resource usage was greatly reduced).  I also noted that the `rust-analyzer-pr` process had stopped once I quit nvim.
<br>
<img width="549" alt="Screenshot 2023-06-30 at 5 27 26 PM" src="https://github.com/rust-lang/rust-analyzer/assets/10244162/0d7d61df-9d1a-4fff-a17b-c6ff3449e80c">

**Screenshot from `btop`**
<img width="992" alt="Screenshot 2023-06-30 at 5 27 53 PM" src="https://github.com/rust-lang/rust-analyzer/assets/10244162/e77782c4-c100-4fa3-9702-4b6ea5496350">

---

**rust-analyzer version**: `2023-06-05`

**rustc version**: rustc 1.70.0 (90c541806 2023-05-31)

**relevant settings**:
- System: 2021 M1 MacBook Pro 
- [Nix devshell configuration](https://github.com/erikkrieg/rust-template/blob/8932ed073a1872f1d988f99dafecceab58dfffe8/flake.nix)
- [Neovim LSP config with rust-tools](https://github.com/erikkrieg/envim/blob/298661d20f91080b5ffcb3624169cfa73aac22e9/nvim/after/plugin/lsp.lua#L39-L49)

**Comment by irh** [comment]
I think this might be related to [this neovim bug](https://github.com/neovim/neovim/issues/23291). I followed the suggested workaround of disabling LSP file watching and it seems to have helped.

**Comment by erikkrieg** [comment]
Which comment on that issue describes the workaround you tried?

And to confirm, you were able to reproduce what I encountered and then observed the suggested remediation resolve the problem?

**Comment by irh** [comment]
The workaround is [described here](https://github.com/neovim/neovim/issues/23291#issuecomment-1686709265): set `capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = false` in your LSP capabilities.

I had high `fseventsd` CPU usage, sluggish rust-analyzer performance, and neovim would regularly hang on exit, so I thought I had the same issue as yours, apologies for the noise if it turns out to be something else.

**Comment by erikkrieg** [comment]
Whether this is part of the problem I encountered or not I think that this is good context. It describes part of what I was seeing. For this issue the real problem I was trying to point to was what was happening _after_ closing nvim: which was that the rust-analyzer process continues to run and use significantly more CPU than while nvim was still running.

> neovim would regularly hang on exit

I didn't personally see this. Did you notice whether or not rust-analyzer continued running for you even after closing nvim?

**Comment by irh** [comment]
It would be running (sometimes I'd notice multiple instances) while neovim was trying to exit, and I would have to kill the process. I didn't see rust-analyzer hanging around after neovim fully exited.

**Comment by erikkrieg** [comment]
I believe that this was related to certain folders being analyzed that should not have been. I haven't had this issue since excluding some of those folders: https://github.com/erikkrieg/envim/blob/main/nvim/lua/plugins/lsp/servers/init.lua#L19-L24

In my case, the biggest issue was `.direnv`, which contains symlinks to very large directories and even circular symlinks.

Since I haven't seen the issue since making this change, I'm going to close this.
