### ISSUE TITLE
Hover on constants should render the display/debug impl if available

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15188]
Might be a crazy idea but I'll take the bitflags crate as an example here (although we fail to calculate the layout for it in const eval due to the projection used I believe, pasting the expansion and fixing that up makes it work):
```rs
bitflags::bitflags! {
    #[derive(Default, Debug, Clone, Copy)]
    pub(crate) struct TypeVariableFlags: u8 {
        const DIVERGING = 1 << 0;
        const INTEGER = 1 << 1;
        const FLOAT = 1 << 2;
        const FOO = TypeVariableFlags::FLOAT.bits() | TypeVariableFlags::INTEGER.bits();
    }
}
```

Hovering `FOO` renders (again `<layout-error>` currently) the following:
```rs
hir_ty::infer::unify::x
const Foo: TypeVariableFlags = TypeVariableFlags(InternalBitFlags(3))
```
which is obviously not that useful, meanwhile the debug implementation would render as:
```
TypeVariableFlags(INTEGER | FLOAT)
```

Noticed this in a project of mine that works with bitflags where our hover is practically useless 
![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/d5595af0-f96f-4d3a-9572-d4bc904a1c5e)

**Comment by Veykril** [comment]
cc @HKalbasi maybe you already had this idea in your head yourself :^) Would be good to know if we can pursue this in the (near) future or not as I think this would be very useful

**Comment by HKalbasi** [comment]
I think it is very doable now. We just need to run this:
```Rust
::core::fmt::format(::core::fmt::Arguments::new_v1(
        &[""],
        &[::core::fmt::ArgumentV1::new(&(THE_CONST), ::core::fmt::Debug::fmt)],
    ));
```
And show its result. The only challanges are:
* There is no body containing that code, so we need to manually call the interpreter internals (it won't be much problem I think)
* Changes in the fmt infrastructure can break us. We can use the current displayer as a fallback, and those changes will break us in other ways anyway.

We also need something similar for displaying panic messages I think.

I can do this, but this looks like a good opportunity for increasing the "bus factor" of mir, maybe?

**Comment by Veykril** [comment]
I'm fine with trying to tackle this myself (once I have time, I'm currently somewhat occupied with things).

We should fallback to our current approach no matter what if we have problems running the debug/display implementation.
