### ISSUE TITLE
thread 'Worker' panicked (mir/eval/shim)

### ISSUE THREAD

**Issue by grovesNL** [rust-lang/rust-analyzer#15182]
**rust-analyzer version**: 0.4.1571-standalone (f96442aa9 2023-06-30)

**rustc version**: 1.70.0 (90c541806 2023-05-31)

**relevant settings**: unsure if the settings are related, but I do specify `"rust-analyzer.cargo.extraEnv"` to set `RUSTFLAGS` to match the ones in my `.cargo/config.toml`

Hi all!

When running rust-analyzer on a larger project, I run into the following error consistently while rebuilding proc macros from external crates (serde-derive, borsh) that are used as derives on some of my types:

> thread 'Worker' panicked at 'range end index 8 out of range for slice of length 4', crates\hir-ty\src\mir\eval\shim.rs:522:53

I tried multiple versions of rust-analyzer and had a similar problem. After this some proc macros don't expand, so it makes it difficult to use rust-analyzer in general because it cascades through my project.

I don't have a small repro outside of my project right now, but I can work on trying to create one if it's not clear how this panic could happen.

**Comment by HKalbasi** [comment]
Do you work on a 32bit target?

**Comment by grovesNL** [comment]
One of the crates in the workspace targets `wasm32-unknown-unknown` while the rest target `x86_64-pc-windows-msvc`

**Comment by grovesNL** [comment]
For what it's worth I'm also ok with specifying the target so that only `x86_64-pc-windows-msvc` is checked by rust-analyzer, but I'm not sure if something like `"rust-analyzer.cargo.target": "x86_64-pc-windows-msvc"` in the workspace settings would be enough to avoid rust-analyzer re-running `cargo check` while I do regular complete workspace builds (including the wasm crate, so both targets).
