### ISSUE TITLE
Can't run rust-analyzer on centos 7

### ISSUE THREAD

**Issue by bigdogs** [rust-lang/rust-analyzer#15201]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
seems `rust-analyzer` build with a higher glibc version than `rustc`, and it can't run on centos 7. it would be greate that rust-anaylzer use the same ci environment with the `rustc` project 
```
[root@localhost server]# ./rust-analyzer 
./rust-analyzer: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./rust-analyzer)
./rust-analyzer: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./rust-analyzer)
./rust-analyzer: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./rust-analyzer)
```

**rustc version**: (eg. output of `rustc -V`)
```
[root@localhost server]# rustc --version
rustc 1.70.0 (90c541806 2023-05-31)
```

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**Comment by bjorn3** [comment]
You can either use the version of rust-analyzer from rustup or build it yourself. The versions built in this repo are compiled on ubuntu 18.04 which has a newer glibc version than centos 7 and as such don't run on centos 7. See also https://github.com/rust-lang/rust-analyzer/issues/13103
