### ISSUE TITLE
IntelliJ Support

### ISSUE THREAD

**Issue by WeetHet** [rust-lang/rust-analyzer#15214]
So, basically IntelliJ supports LSP now, yay! (source: https://blog.jetbrains.com/idea/2023/06/intellij-idea-2023-2-eap-7/#LSPsupportforplugindevelopers). Considering that, why not make a plugin for it, so we could have a diverse support for Rust in JetBrains ecosystem. I suppose it would require relatively low maintenance

**Comment by HKalbasi** [comment]
We currently don't support any editor other than vscode, and I guess a full rust plugin for jetbrains will probably also deal with the debugging and building functionalities, so it wouldn't be very small. So I think this would be better to be handled as a community third party project similar to other editors. On the other hand, jetbrains probably has more users than vim, emacs, sublime, ... combined, it might mean something.

**Comment by Veykril** [comment]
We only plan on doing official support for vscode, that won't change any time. The bandwidth required to support more (let alone support intellij) is too much.

**Comment by flodiebold** [comment]
(Additionally, providing a plugin for IntelliJ would be a particular waste of time since a plugin with much better integration than LSP can provide already exists.)

**Comment by WeetHet** [comment]
Yeah sure, closing this then. Maybe in the future someone creates this
