### ISSUE TITLE
thread 'Worker' panicked (hir-def/item_tree)

### ISSUE THREAD

**Issue by grovesNL** [rust-lang/rust-analyzer#15215]
**rust-analyzer version**: 0.4.1576-standalone (45272efec 2023-07-03)

**rustc version**: 1.70.0 (90c541806 2023-05-31)

**relevant settings**: n/a

I copied an existing test file, renamed it, then saved it. The output in rust-analyzer was:

> thread 'Worker' panicked at 'attempted to access data of empty ItemTree', crates\hir-def\src\item_tree.rs:174:28

Relevant call stack:
>    5: <hir_def::AssocItemLoc<N> as hir_def::src::HasSource>::source
   6: hir_def::body::Body::body_with_source_map_query
   7: salsa::runtime::Runtime::execute_query_implementation
   8: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_def::db::ExternCrateDeclDataQuery>>
   9: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since

**Comment by Veykril** [comment]
Likely salsa invalidation issue as that panic should be unreachable
