### ISSUE TITLE
Significant lag and spamming `[ERROR hir_ty::mir::borrowck] Terminator should be none only in construction`

### ISSUE THREAD

**Issue by oxalica** [rust-lang/rust-analyzer#15238]
To reproduce:
Use neovim/coc.nvim to open [this file](https://github.com/oxalica/nil/blob/495c5999280cdc66095542888cc1b758b608f036/crates/nil/src/server.rs) under repo root. VSCodium also reproduces.

Wait a few seconds after fully indexed, then you'll find:

- Significant lag for all request, including completion, file saving, hovering and etc.
- Spamming log (>5MiB/s) of `[ERROR hir_ty::mir::borrowck] Terminator should be none only in construction`. 
- \>100% CPU stress on both `rust-analyzer` and `node` (coc.nvim). Likely to be caused by the log spamming.

After a quick glance, there seems to be only one root error being emitted again and again. That error entry itself is ~6500 lines, see [this gist](https://gist.github.com/oxalica/38b0a29122dca19ac7c9d5cf27ebf752). Seems #15058 magnifies the original issue.

cc @HKalbasi 

**rust-analyzer version**: 2023-07-03

**rustc version**: 1.70.0

**relevant settings**: Set `CARGO_TARGET_DIR` to a fresh empty directory, aka. already `cargo clean`ed.

**Comment by oxalica** [comment]
Bisected to 3c878250747ded437c2244871c243f10e23fcdda. :thinking:

**Comment by HKalbasi** [comment]
Did you also experienced the lag in the Codium? I opened your project in Codium but while my logs was spammed, I didn't had lag. #15245 addresses the underlying problem but if the lag problem is not specific to the neovim, we may want to decrease the size of log.

**Comment by oxalica** [comment]
> Did you also experienced the lag in the Codium?

It's also a bit laggy but not as worse as coc.nvim. Not sure if they would be interested in handling the abnormal amount of logging.

Anyway, it's fixed on `master` now for me. Thanks for the quick fix.
