### ISSUE TITLE
"Apply De Morgan's Law" on `_ = !a && (b);` generates invalid code

### ISSUE THREAD

**Issue by DropDemBits** [rust-lang/rust-analyzer#15240]
Applying the assist as follows:
```rs
fn main() {
    _ = !a &&$0 (b);
}
```
Generates the following code:
```rs
fn main() {
    !(!_ || a || !(b));
}
```

A similar issue occurs when you start with `_ = !a ||$0 (b);` instead.

---

**rust-analyzer version**: rust-analyzer version: 0.3.1575-standalone (ff485b63b 2023-07-02)

**rustc version**: rustc 1.70.0 (90c541806 2023-05-31)

**relevant settings**: *Not Applicable*

**Comment by alibektas** [comment]
#15410 should have closed this one too. Can you mark this as resolved @Veykril ?
