### ISSUE TITLE
Hovering over THREAD_RNG_KEY in rand crate causes memory allocation error

### ISSUE THREAD

**Issue by CrazyboyQCD** [rust-lang/rust-analyzer#15274]
**rust-analyzer version**: rust-analyzer version: 0.3.1583-standalone (ff1563483 2023-07-09)

**rustc version**: rustc 1.73.0-nightly (8ca44ef9c 2023-07-10)

**relevant settings**: default

In the rand crate, the following code snippet is causing an error when hovering over the ```THREAD_RNG_KEY``` variable:
```
thread_local!(
    // We require Rc<..> to avoid premature freeing when thread_rng is used
    // within thread-local destructors. See #968.
    static THREAD_RNG_KEY: Rc<UnsafeCell<ReseedingRng<Core, OsRng>>> = {
        let r = Core::from_rng(OsRng).unwrap_or_else(|err|
                panic!("could not initialize thread_rng: {}", err));
        let rng = ReseedingRng::new(r,
                                    THREAD_RNG_RESEED_THRESHOLD,
                                    OsRng);
        Rc::new(UnsafeCell::new(rng))
    }
);
```
The error message is
```
memory allocation of 3458764513820541405 bytes failed
[Info  - 13:17:44] Connection to server got closed. Server will restart.
true
```

**Comment by lnicola** [comment]
As a workaround, you can use an older nightly until this is fixed.

**Comment by HKalbasi** [comment]
I added a memory limit to the mir eval recently so this should be fixed. Can you try the r-a on the master branch? (Latest nightly also contains the commit I think)

**Comment by CrazyboyQCD** [comment]
> I added a memory limit to the mir eval recently so this should be fixed. Can you try the r-a on the master branch? (Latest nightly also contains the commit I think)

The error is gone after switching to the preview version, thx
