### ISSUE TITLE
binary (rust-analyzer-proc-macro-srv.exe) is flagged as trojan by windows defender :P

### ISSUE THREAD

**Issue by whatakey** [rust-lang/rust-analyzer#15278]
Of course, this must be a false positive.

![Untitled](https://github.com/rust-lang/rust-analyzer/assets/126112966/1b0a46a7-4320-4ff0-ad57-2bd38437fbbf)

opening an issue here because on windows, defender automatically quarantines that binary which might harm RA's functionality.

**Comment by brandon-reinhart** [comment]
Can confirm. Same detection result. In my case it automatically quarantined rust-analyzer-proc-macro-srv.exe.

**Comment by lnicola** [comment]
That's part of the Rust toolchain. It's a false positive, but there's probably nothing we can do about it.

**Comment by lnicola** [comment]
It looks like you could submit the file to Microsoft for further analysis: https://learn.microsoft.com/en-us/microsoft-365/security/intelligence/submission-guide. I'm not running Windows, buy maybe you could try it?

**Comment by lnicola** [comment]
Not much we can do about this, and it's probably more of a T-infra issue.
