### ISSUE TITLE
RA panics with file

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [rust-lang/rust-analyzer#15298]
The attached main.txt, pasted into main.rs in a default `cargo new --bin` project causes RA to panic (tested with VSCodium on mac and VS Code on windows). I apologize in advance for the ugly code :)

(these are the versions that I tested on Mac. I don't know the exact version my friend (who tested on windows) was using, but it's likely fairly recent))
**rust-analyzer version**: rust-analyzer version: 0.3.1583-standalone (ff1563483 2023-07-09)

**rustc version**: rustc 1.70.0 (90c541806 2023-05-31)

example:
[main.txt](https://github.com/rust-lang/rust-analyzer/files/12065567/main.txt)

more minimized example:
[main.txt](https://github.com/rust-lang/rust-analyzer/files/12066168/main.txt)

<details>
<summary>panic backtrace</summary>
<br>

```rs

Panic context:
> publish_diagnostics

thread 'Worker' panicked at 'Bad range: node range 35..137, range 246..251', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rowan-0.15.11/src/cursor.rs:786:13
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rowan::cursor::SyntaxNode::covering_element
   3: hir_expand::ExpansionInfo::map_token_up
   4: hir_expand::ascend_call_token
   5: hir_expand::ascend_node_border_tokens
   6: hir_expand::InFile<&rowan::api::SyntaxNode<syntax::syntax_node::RustLanguage>>::original_file_range_opt
   7: hir_expand::InFile<&rowan::api::SyntaxNode<syntax::syntax_node::RustLanguage>>::original_file_range
   8: hir::semantics::SemanticsImpl::diagnostics_display_range
   9: ide_diagnostics::adjusted_display_range
  10: ide_diagnostics::handlers::type_mismatch::type_mismatch
  11: ide_diagnostics::diagnostics
  12: std::panicking::try
  13: ide::Analysis::diagnostics
  14: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  15: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  16: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

</details>

**Comment by The-Minecraft-Scientist** [comment]
I managed to reduce this pretty significantly by trial and error, I’ll upload the new file as soon as I can

**Comment by lowr** [comment]
#15248 may have fixed this. Can you try the latest release (2023-07-17, v0.3.1591) and see if the panic persists?

**Comment by The-Minecraft-Scientist** [comment]
will do!

**Comment by The-Minecraft-Scientist** [comment]
Closing this as fixed! Latest Rust-Analyzer no longer panics with my file. Thanks!

**Comment by lnicola** [comment]
Closing for real :grinning:.

**Comment by pacak** [comment]
I'm getting a similar looking stack trace in 1.72.0 (5680fa1 2023-08-23)

**Comment by pacak** [comment]
[sample.tar.gz](https://github.com/rust-lang/rust-analyzer/files/12570879/sample.tar.gz)

removing `match item {` on line 183 causes the crash.

[crash.log](https://github.com/rust-lang/rust-analyzer/files/12570881/crash.log)
