### ISSUE TITLE
Flycheck generate wrong command

### ISSUE THREAD

**Issue by sonk33** [rust-lang/rust-analyzer#15294]
when i create my very first project - by command -> `cargo new MyProject`
and open the project by vs code
rust-analyzer show my that he has an warning
`[ERROR flycheck] Flycheck failed to run the following command: cd "/home/user/MyProject" && "cargo" "Clippy" "--workspace" "--message-format=json-diagnostic-rendered-ansi" "--manifest-path" "/home/user/MyProject/Cargo.toml" "--all-targets" `
when i try to run the command this result appeared
```
cd "/home/user/MyProject" && "cargo" "Clippy" "--workspace" "--message-format=json-diagnostic-rendered-ansi" "--manifest-path" "/home/user/MyProject/Cargo.toml" "--all-targets" 

error: no such command: `Clippy`
 Did you mean `clippy`?

```
my os : debian 12
i install rust by command : `curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh`
with default settings
rustc --version: rustc 1.71.0 (8ede3aae2 2023-07-12)

**Comment by lnicola** [comment]
Check out your user or project VS Code settings and replace `Clippy` with `clippy`.

**Comment by sonk33** [comment]
thank you [lnicola](https://github.com/lnicola) the problem solved 
There was this option
 "rust-analyzer.checkOnSave.command": "Clippy"
that was causing the problem
