### ISSUE TITLE
How to properly set rust-analyzer settings in kate?

### ISSUE THREAD

**Issue by prez** [rust-lang/rust-analyzer#15305]
Say I want to change `"rust-analyzer.check.allTargets"` to `false`.
The [kate docs](https://docs.kde.org/stable5/en/kate/kate/kate-application-plugin-lspclient.html#:~:text=vary%0Aexec%20myserver-,LSP%20Server%20Configuration,-Each%20particular%20LSP) seem to suggest that the contents of `~/.config/kate/lspclient/settings.json` should look like this:

```json
{
    "servers": {
        "rust": {
            "settings": {
                "rust-analyzer": {
                    "check": {
                        "allTargets": false
                    }
                }
            }
        }
    }
}
```

But unfortunately, I'm getting `"[ERROR rust_analyzer::main_loop] failed to fetch the server settings: ResponseError { code: -32601, message: "workspace/configuration", data: None }"`

I have tried 

```json
{
    "servers": {
        "rust": {
            "settings": {
                "rust-analyzer.check.allTargets": false
            }
        }
    }
}
```

too, to no avail. Looking at the debug output with `RA_LOG="rust_analyzer=info"` does not work nicely because kate limits the scrollback buffer in the LSP Server "Output" window, with no way to change that.

This would be really great to have documented here, so hopefully others facing the same issue can find an answer. Information about this particular editor/language server combination is nonexistent on the internet, and the way of configuring LSP Server settings in Kate changed recently.

**Comment by alibektas** [comment]
Did you check our [manual](https://rust-analyzer.github.io/manual.html#kate-text-editor) ? If you believe that there are outdated infos in our manual, we would be delighted to see this mentioned in a new issue or even better as a PR.

The error code you are getting indicates ` MethodNotFound`, this is not supposed to happen by a mere adding of a key-value pair to a json config file, you may want to check which portion of this configuration dict is sent to the LSP Server. A good place to start could be [Kate's own way of handling RA](https://github.com/KDE/kate/blob/2c9122a6d54bf0f8445d8666b3c236a7d3702d9b/addons/lspclient/settings.json#L188).

As we do not offer a first class support for Kate I don't think that there is much to do on our side except to accept Kate specific infos for our manual.

**Comment by alibektas** [comment]
So I spent some time looking into this. Here are some observations :

1. Server requests configurations , Kate cannot generate a proper response. Hence -32601 error code.
1. `settings` is not accepted as a key , but initalizationOptions are.

Whatever the cause is it has something to do with this key. Documentation is explicit enough about what the key should be a the link with the title similar to `here is how another text editor does the same thing` is somewhat misleading. Please let me know once you are able to resolve this issue. I want to add your solution to our manual so that others can benefit from it.

**Comment by alibektas** [comment]
The way you set this in VSCode differs from that in Kate. I still believe tho that the `settings` is the key you need. Why don't you check in Kate's codebase how the json file is parsed? 

One more thing : From how I understood it, `settings.json` file literally overrides ( and some other methods merely extend )  the file where `servers` dictionary is located in.  This sounds to me like you have to copy everything related to rust to your settings file. That includes path etc. as well but it is just my interpretation, could be wrong.

**Comment by lnicola** [comment]
I think the correct structure is:

```json
{
    "check": {
        "allTargets": false,
    }
}
```

and you can try wrapping that inside `initalizationOptions` or `settings`.

**Comment by lnicola** [comment]
I've verified that the following works when placed into the User Server Settings section:

```json
{
    "servers": {
        "rust": {
            "initializationOptions": {
                "cachePriming": {
                    "enable": false
                },
                "check": {
                    "allTargets": false
                },
                "checkOnSave": false
            }
        }
    }
}
```

`settings` doesn't seem to work, perhaps because Kate doesn't support `workspace/configuration` (we don't seem to check for that capability).
