### ISSUE TITLE
Cannot infer type for type-state pattern with disabled proc-macro

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [rust-lang/rust-analyzer#15311]
**rust-analyzer version**: rust-analyzer version: 0.3.1591-standalone
**rustc version**: rustc 1.71.0-nightly (f5559e338 2023-04-24)
**relevant settings**:
```json
{
    "window.zoomLevel": 1,
    "editor.accessibilitySupport": "off",
    "rust-analyzer.procMacro.enable": false
}
```

how to reproduce?
```
git clone https://github.com/StackOverflowExcept1on/rust-analyzer-issue.git
cd rust-analyzer-issue
code .
```

default settings: (`"rust-analyzer.procMacro.enable": true`)
![image1](https://github.com/rust-lang/rust-analyzer/assets/109800286/0a073a16-e293-4729-aa87-6ac125a8e63b)

with `"rust-analyzer.procMacro.enable": false`:
![изображение](https://github.com/rust-lang/rust-analyzer/assets/109800286/25921a8b-15a3-41de-8f5c-e26fd117a068)

**Comment by lnicola** [comment]
Disabling proc macros will prevent the `Decode` and `Encode` derives from working, but these are used in the bounds of `for_reply_as` and `execute`. So it's expected that we fail to resolve `execute`.

That said, why are you disabling them?

**Comment by StackOverflowExcept1on** [comment]
@lnicola mostly for working with substrate dependencies (to speed up project loading)

**Comment by StackOverflowExcept1on** [comment]
Can we just mark that the `Output` type implements `Encode`, `Decode` instead of executing the proc macro?  In that case it would work.

**Comment by lnicola** [comment]
No, a derive macro could do anything. It doesn't have to implement a trait.

How long does it take to load with them enabled, and how do you know it finished?

**Comment by StackOverflowExcept1on** [comment]
You are probably right, derive can implement more than 1 trait
