### ISSUE TITLE
Rust analyzer can not infer the return type of futures::stream::iter

### ISSUE THREAD

**Issue by ThatNerdUKnow** [rust-lang/rust-analyzer#15337]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
`rust-analyzer version: 0.3.1599-standalone (99718d0c8 2023-07-22)`

**rustc version**: (eg. output of `rustc -V`)
`rustc 1.71.0 (8ede3aae2 2023-07-12)`

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
This is a fresh install of rust on a new laptop. These ought to be their default variables, and I never seem to be able to get these to print in my terminal no matter what I try

In a project I'm working on, I'm needing to turn an iterator into a stream which will turn each element of the iterator into a future which will all execute concurrently. I ended up finding the `stream::iter` function in the `futures` crate. The documentation shows the following example:

```rs
use futures::stream::{self, StreamExt};

let stream = stream::iter(vec![17, 19]);
assert_eq!(vec![17, 19], stream.collect::<Vec<i32>>().await);
```

which I adapted to
```rs
use futures::stream::{self, StreamExt};

#[tokio::main]
async fn main() {
    let stream= stream::iter(vec![17, 19].into_iter());
    assert_eq!(vec![17, 19], stream.collect::<Vec<i32>>().await);
}
```

The type hint provided by rust-analyzer returns `{unknown}`

I also tried explicitly annotating the type of stream:
```rs
use futures::stream::{self, StreamExt};

#[tokio::main]
async fn main() {
    let stream: stream::Iter<std::vec::IntoIter<i32>> = stream::iter(vec![17, 19].into_iter());
    assert_eq!(vec![17, 19], stream.collect::<Vec<i32>>().await);
}
```
with the same results.

the weird part is that this program will compile and run just fine. I don't get so much as a warning from clippy about it. I'm stumped on what to do

**Comment by ThatNerdUKnow** [comment]
nothing special going on in my project, what I shared is all that there is since I was experimenting with trying to understand the stream api

**Comment by lnicola** [comment]
Which version of the `futures` crate is that? You can check with `cargo tree`.

**Comment by ThatNerdUKnow** [comment]
cargo tree
cl_indexer v0.1.0 (C:\Users\brand\repos\courtlistener\cl_indexer)
├── futures v0.3.28
│   ├── futures-channel v0.3.28
│   │   ├── futures-core v0.3.28
│   │   └── futures-sink v0.3.28
│   ├── futures-core v0.3.28
│   ├── futures-executor v0.3.28
│   │   ├── futures-core v0.3.28
│   │   ├── futures-task v0.3.28
│   │   └── futures-util v0.3.28
│   │       ├── futures-channel v0.3.28 (*)
│   │       ├── futures-core v0.3.28
│   │       ├── futures-io v0.3.28
│   │       ├── futures-macro v0.3.28 (proc-macro)
│   │       │   ├── proc-macro2 v1.0.66
│   │       │   │   └── unicode-ident v1.0.11
│   │       │   ├── quote v1.0.32
│   │       │   │   └── proc-macro2 v1.0.66 (*)
│   │       │   └── syn v2.0.27
│   │       │       ├── proc-macro2 v1.0.66 (*)
│   │       │       ├── quote v1.0.32 (*)
│   │       │       └── unicode-ident v1.0.11
│   │       ├── futures-sink v0.3.28
│   │       ├── futures-task v0.3.28
│   │       ├── memchr v2.5.0
│   │       ├── pin-project-lite v0.2.10
│   │       ├── pin-utils v0.1.0
│   │       └── slab v0.4.8
│   │           [build-dependencies]
│   │           └── autocfg v1.1.0
│   ├── futures-io v0.3.28
│   ├── futures-sink v0.3.28
│   ├── futures-task v0.3.28
│   └── futures-util v0.3.28 (*)
├── reqwest v0.11.18
│   ├── base64 v0.21.2
│   ├── bytes v1.4.0
│   ├── encoding_rs v0.8.32
│   │   └── cfg-if v1.0.0
│   ├── futures-core v0.3.28
│   ├── futures-util v0.3.28 (*)
│   ├── h2 v0.3.20
│   │   ├── bytes v1.4.0
│   │   ├── fnv v1.0.7
│   │   ├── futures-core v0.3.28
│   │   ├── futures-sink v0.3.28
│   │   ├── futures-util v0.3.28 (*)
│   │   ├── http v0.2.9
│   │   │   ├── bytes v1.4.0
│   │   │   ├── fnv v1.0.7
│   │   │   └── itoa v1.0.9
│   │   ├── indexmap v1.9.3
│   │   │   └── hashbrown v0.12.3
│   │   │   [build-dependencies]
│   │   │   └── autocfg v1.1.0
│   │   ├── slab v0.4.8 (*)
│   │   ├── tokio v1.29.1
│   │   │   ├── bytes v1.4.0
│   │   │   ├── mio v0.8.8
│   │   │   │   └── windows-sys v0.48.0
│   │   │   │       └── windows-targets v0.48.1
│   │   │   │           └── windows_x86_64_msvc v0.48.0
│   │   │   ├── num_cpus v1.16.0
│   │   │   ├── parking_lot v0.12.1
│   │   │   │   ├── lock_api v0.4.10
│   │   │   │   │   └── scopeguard v1.2.0
│   │   │   │   │   [build-dependencies]
│   │   │   │   │   └── autocfg v1.1.0
│   │   │   │   └── parking_lot_core v0.9.8
│   │   │   │       ├── cfg-if v1.0.0
│   │   │   │       ├── smallvec v1.11.0
│   │   │   │       └── windows-targets v0.48.1 (*)
│   │   │   ├── pin-project-lite v0.2.10
│   │   │   ├── socket2 v0.4.9
│   │   │   │   └── winapi v0.3.9
│   │   │   ├── tokio-macros v2.1.0 (proc-macro)
│   │   │   │   ├── proc-macro2 v1.0.66 (*)
│   │   │   │   ├── quote v1.0.32 (*)
│   │   │   │   └── syn v2.0.27 (*)
│   │   │   └── windows-sys v0.48.0 (*)
│   │   │   [build-dependencies]
│   │   │   └── autocfg v1.1.0
│   │   ├── tokio-util v0.7.8
│   │   │   ├── bytes v1.4.0
│   │   │   ├── futures-core v0.3.28
│   │   │   ├── futures-sink v0.3.28
│   │   │   ├── pin-project-lite v0.2.10
│   │   │   ├── tokio v1.29.1 (*)
│   │   │   └── tracing v0.1.37
│   │   │       ├── cfg-if v1.0.0
│   │   │       ├── pin-project-lite v0.2.10
│   │   │       └── tracing-core v0.1.31
│   │   │           └── once_cell v1.18.0
│   │   └── tracing v0.1.37 (*)
│   ├── http v0.2.9 (*)
│   ├── http-body v0.4.5
│   │   ├── bytes v1.4.0
│   │   ├── http v0.2.9 (*)
│   │   └── pin-project-lite v0.2.10
│   ├── hyper v0.14.27
│   │   ├── bytes v1.4.0
│   │   ├── futures-channel v0.3.28 (*)
│   │   ├── futures-core v0.3.28
│   │   ├── futures-util v0.3.28 (*)
│   │   ├── h2 v0.3.20 (*)
│   │   ├── http v0.2.9 (*)
│   │   ├── http-body v0.4.5 (*)
│   │   ├── httparse v1.8.0
│   │   ├── httpdate v1.0.2
│   │   ├── itoa v1.0.9
│   │   ├── pin-project-lite v0.2.10
│   │   ├── socket2 v0.4.9 (*)
│   │   ├── tokio v1.29.1 (*)
│   │   ├── tower-service v0.3.2
│   │   ├── tracing v0.1.37 (*)
│   │   └── want v0.3.1
│   │       └── try-lock v0.2.4
│   ├── hyper-tls v0.5.0
│   │   ├── bytes v1.4.0
│   │   ├── hyper v0.14.27 (*)
│   │   ├── native-tls v0.2.11
│   │   │   └── schannel v0.1.22
│   │   │       └── windows-sys v0.48.0 (*)
│   │   ├── tokio v1.29.1 (*)
│   │   └── tokio-native-tls v0.3.1
│   │       ├── native-tls v0.2.11 (*)
│   │       └── tokio v1.29.1 (*)
│   ├── ipnet v2.8.0
│   ├── log v0.4.19
│   ├── mime v0.3.17
│   ├── native-tls v0.2.11 (*)
│   ├── once_cell v1.18.0
│   ├── percent-encoding v2.3.0
│   ├── pin-project-lite v0.2.10
│   ├── serde v1.0.175
│   │   └── serde_derive v1.0.175 (proc-macro)
│   │       ├── proc-macro2 v1.0.66 (*)
│   │       ├── quote v1.0.32 (*)
│   │       └── syn v2.0.27 (*)
│   ├── serde_urlencoded v0.7.1
│   │   ├── form_urlencoded v1.2.0
│   │   │   └── percent-encoding v2.3.0
│   │   ├── itoa v1.0.9
│   │   ├── ryu v1.0.15
│   │   └── serde v1.0.175 (*)
│   ├── tokio v1.29.1 (*)
│   ├── tokio-native-tls v0.3.1 (*)
│   ├── tower-service v0.3.2
│   ├── url v2.4.0
│   │   ├── form_urlencoded v1.2.0 (*)
│   │   ├── idna v0.4.0
│   │   │   ├── unicode-bidi v0.3.13
│   │   │   └── unicode-normalization v0.1.22
│   │   │       └── tinyvec v1.6.0
│   │   │           └── tinyvec_macros v0.1.1
│   │   └── percent-encoding v2.3.0
│   └── winreg v0.10.1
│       └── winapi v0.3.9
├── thirtyfour v0.31.0
│   ├── async-trait v0.1.72 (proc-macro)
│   │   ├── proc-macro2 v1.0.66 (*)
│   │   ├── quote v1.0.32 (*)
│   │   └── syn v2.0.27 (*)
│   ├── base64 v0.13.1
│   ├── chrono v0.4.26
│   │   ├── num-traits v0.2.16
│   │   │   [build-dependencies]
│   │   │   └── autocfg v1.1.0
│   │   ├── serde v1.0.175 (*)
│   │   ├── time v0.1.45
│   │   │   ├── libc v0.2.147
│   │   │   └── winapi v0.3.9
│   │   └── winapi v0.3.9
│   ├── cookie v0.16.2
│   │   ├── percent-encoding v2.3.0
│   │   └── time v0.3.23
│   │       ├── itoa v1.0.9
│   │       ├── time-core v0.1.1
│   │       └── time-macros v0.2.10 (proc-macro)
│   │           └── time-core v0.1.1
│   │   [build-dependencies]
│   │   └── version_check v0.9.4
│   ├── fantoccini v0.19.3
│   │   ├── base64 v0.13.1
│   │   ├── cookie v0.16.2 (*)
│   │   ├── futures-core v0.3.28
│   │   ├── futures-util v0.3.28 (*)
│   │   ├── http v0.2.9 (*)
│   │   ├── hyper v0.14.27 (*)
│   │   ├── hyper-rustls v0.23.2
│   │   │   ├── http v0.2.9 (*)
│   │   │   ├── hyper v0.14.27 (*)
│   │   │   ├── log v0.4.19
│   │   │   ├── rustls v0.20.8
│   │   │   │   ├── log v0.4.19
│   │   │   │   ├── ring v0.16.20
│   │   │   │   │   ├── spin v0.5.2
│   │   │   │   │   ├── untrusted v0.7.1
│   │   │   │   │   └── winapi v0.3.9
│   │   │   │   │   [build-dependencies]
│   │   │   │   │   └── cc v1.0.79
│   │   │   │   ├── sct v0.7.0
│   │   │   │   │   ├── ring v0.16.20 (*)
│   │   │   │   │   └── untrusted v0.7.1
│   │   │   │   └── webpki v0.22.0
│   │   │   │       ├── ring v0.16.20 (*)
│   │   │   │       └── untrusted v0.7.1
│   │   │   ├── rustls-native-certs v0.6.3
│   │   │   │   ├── rustls-pemfile v1.0.3
│   │   │   │   │   └── base64 v0.21.2
│   │   │   │   └── schannel v0.1.22 (*)
│   │   │   ├── tokio v1.29.1 (*)
│   │   │   └── tokio-rustls v0.23.4
│   │   │       ├── rustls v0.20.8 (*)
│   │   │       ├── tokio v1.29.1 (*)
│   │   │       └── webpki v0.22.0 (*)
│   │   ├── mime v0.3.17
│   │   ├── serde v1.0.175 (*)
│   │   ├── serde_json v1.0.103
│   │   │   ├── indexmap v2.0.0
│   │   │   │   ├── equivalent v1.0.1
│   │   │   │   └── hashbrown v0.14.0
│   │   │   ├── itoa v1.0.9
│   │   │   ├── ryu v1.0.15
│   │   │   └── serde v1.0.175 (*)
│   │   ├── time v0.3.23 (*)
│   │   ├── tokio v1.29.1 (*)
│   │   ├── url v2.4.0 (*)
│   │   └── webdriver v0.46.0
│   │       ├── base64 v0.13.1
│   │       ├── bytes v1.4.0
│   │       ├── cookie v0.16.2 (*)
│   │       ├── http v0.2.9 (*)
│   │       ├── log v0.4.19
│   │       ├── serde v1.0.175 (*)
│   │       ├── serde_derive v1.0.175 (proc-macro) (*)
│   │       ├── serde_json v1.0.103 (*)
│   │       ├── time v0.3.23 (*)
│   │       ├── unicode-segmentation v1.10.1
│   │       └── url v2.4.0 (*)
│   ├── futures v0.3.28 (*)
│   ├── http v0.2.9 (*)
│   ├── log v0.4.19
│   ├── parking_lot v0.12.1 (*)
│   ├── serde v1.0.175 (*)
│   ├── serde_json v1.0.103 (*)
│   ├── serde_repr v0.1.15 (proc-macro)
│   │   ├── proc-macro2 v1.0.66 (*)
│   │   ├── quote v1.0.32 (*)
│   │   └── syn v2.0.27 (*)
│   ├── stringmatch v0.4.0
│   │   └── regex v1.9.1
│   │       ├── aho-corasick v1.0.2
│   │       │   └── memchr v2.5.0
│   │       ├── memchr v2.5.0
│   │       ├── regex-automata v0.3.3
│   │       │   ├── aho-corasick v1.0.2 (*)
│   │       │   ├── memchr v2.5.0
│   │       │   └── regex-syntax v0.7.4
│   │       └── regex-syntax v0.7.4
│   ├── thirtyfour-macros v0.1.1 (proc-macro)
│   │   ├── proc-macro-error v1.0.4
│   │   │   ├── proc-macro-error-attr v1.0.4 (proc-macro)
│   │   │   │   ├── proc-macro2 v1.0.66 (*)
│   │   │   │   └── quote v1.0.32 (*)
│   │   │   │   [build-dependencies]
│   │   │   │   └── version_check v0.9.4
│   │   │   ├── proc-macro2 v1.0.66 (*)
│   │   │   ├── quote v1.0.32 (*)
│   │   │   └── syn v1.0.109
│   │   │       ├── proc-macro2 v1.0.66 (*)
│   │   │       ├── quote v1.0.32 (*)
│   │   │       └── unicode-ident v1.0.11
│   │   │   [build-dependencies]
│   │   │   └── version_check v0.9.4
│   │   ├── proc-macro2 v1.0.66 (*)
│   │   ├── quote v1.0.32 (*)
│   │   └── syn v1.0.109 (*)
│   ├── thiserror v1.0.44
│   │   └── thiserror-impl v1.0.44 (proc-macro)
│   │       ├── proc-macro2 v1.0.66 (*)
│   │       ├── quote v1.0.32 (*)
│   │       └── syn v2.0.27 (*)
│   ├── tokio v1.29.1 (*)
│   ├── url v2.4.0 (*)
│   └── urlparse v0.7.3
├── tokio v1.29.1 (*)
└── tokio-stream v0.1.14
    ├── futures-core v0.3.28
    ├── pin-project-lite v0.2.10
    └── tokio v1.29.1 (*)

**Comment by Veykril** [comment]
Are you still having this problem?

**Comment by ThatNerdUKnow** [comment]
on my current setup `rustc 1.77.1`, no
