### ISSUE TITLE
When "enable_imports_on_the_fly" is true, show methods from unimported traits on dot completions.

### ISSUE THREAD

**Issue by NoudZandbergen** [rust-lang/rust-analyzer#15334]
## Problem

Right now I have autoimports enabled on vscode, but on dot completions, I can only see methods for traits that are already imported.

![image](https://github.com/rust-lang/rust-analyzer/assets/29511931/89be0900-ec3b-4c1a-93a1-e0cd16bf9912)

However, when I start typing something, only then will it actually look for imports it could make.

![image](https://github.com/rust-lang/rust-analyzer/assets/29511931/d9e0271c-15f7-445a-8c28-db1c62ba1c1f)

<details>
<summary>Why is that a problem?</summary>

This means that I have to know what to type for available methods to show up. I can guess various things and have a chance of finding what I need, but I really would prefer a nice overview of all the possibilities that are available to me.

Otherwise I have to resort to documentation, but sometimes there might be other methods on a type that aren't actually implemented by the library that provides the documentation.
For example, I might have an extra impl block for that type in another crate that I made.
</details>

## Suggestion
So, I think it should be possible to see all methods on a type that are available through imports when you have "autoimport" enabled (enable_imports_on_the_fly == true). Perhaps there could be an extra setting that turns this on or off.

All the methods that can be imported should be shown at the bottom of the completions. Bonus points if the completions can contain collapsible sections for all the traits it can import, and then put the method completions in those collapsible sections like so:

![image](https://github.com/rust-lang/rust-analyzer/assets/29511931/748d1af2-0778-48e7-8c67-9713352d05dd)

<details>
<summary>My attempt at implementing this</summary>

```rs
// crates/ide-completion/src/completions/dot.rs
fn complete_methods(
    ctx: &CompletionContext<'_>,
    receiver: &hir::Type,
    mut f: impl FnMut(hir::Function),
) {
	let mut seen_methods = FxHashSet::default();
	// Only show these suggestions with autoimports enabled
	if ctx.config.enable_imports_on_the_fly {
		receiver.iterate_method_candidates_with_traits(
			ctx.db,
			&ctx.scope,
			// Replace the following line with something that acquires all
			//  traits added to the receiver by any of the crates available.
			// As far as I'm aware, traits_in_scope() will only list
			//  the traits that are already imported.
			// Note that doing it just like this will probably mean that the completions
			//  aren't sorted by whether something is already imported or not...
			&ctx.traits_in_scope(),
			Some(ctx.module),
			None,
			|func| {
				if func.self_param(ctx.db).is_some() && seen_methods.insert(func.name(ctx.db)) {
					f(func);
				}
				None::<()>
			},
		);
	} else {
		receiver.iterate_method_candidates_with_traits(
			ctx.db,
			&ctx.scope,
			&ctx.traits_in_scope(),
			Some(ctx.module),
			None,
			|func| {
				if func.self_param(ctx.db).is_some() && seen_methods.insert(func.name(ctx.db)) {
					f(func);
				}
				None::<()>
			},
		);
	}
}
```

</details>

**Comment by lowr** [comment]
We already have this feature. As you can see in your first image, we suggest `as_handle` as a completion candidate which will import the `AsHandle` trait upon selection. However, it is true that we don't show all possible candidates. This is because we put a [limit] on the initial search for trait candidates to import to avoid expensive computations, which halts the search before we reach the `Read` trait in particular.

The limit is currently fixed, but I think we can make it configurable, even let the users choose "no limit" for it if desired.

[limit]: https://github.com/rust-lang/rust-analyzer/blob/b64e5b3919b24bc784f36248e6e1f921ee7bb71b/crates/ide-db/src/imports/import_assets.rs#L487

**Comment by Urhengulas** [comment]
> The limit is currently fixed, but I think we can make it configurable, even let the users choose "no limit" for it if desired.

The limit you are talking about is removed by https://github.com/rust-lang/rust-analyzer/pull/16268, isn't it?
