### ISSUE TITLE
`rust-analyzer` fails to load the workspace partially

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rust-analyzer#15341]
Since a few days `rust-analyzer` started to fail loading test-only parts of my workspace with the following message that constantly pops up as soon as I touch those test files:

<img width="445" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/8193155/ce779dfc-0739-4922-8732-ff0c3e794dc3">

Additionally it constantly creates the following file in `.vscode/settings.json`:
(Although this `settings.json` file does not even help with the problem.)

```json
{
    "rust-analyzer.linkedProjects": [
        "./Cargo.toml"
    ]
}
```

This is a huge issue for me because I can no longer test and debug individual test files.
The whole IDE experience for my tests is gone. I reported this only now since I hoped the problem would resolve itself quickly.

The project with which I am experiencing this issue is: https://github.com/paritytech/wasmi
And in particular I am currently working on this branch: https://github.com/paritytech/wasmi/tree/rf-engine-regmach

It is important to note that the non-test related parts of the workspace seem to load fine.

**Comment by lnicola** [comment]
Which parts? IDE features work fine for me in `crates/wasmi/tests/e2e/v1/func.rs`, for example.

**Comment by lnicola** [comment]
We enable `cfg(miri)` since https://github.com/rust-lang/rust-analyzer/pull/15284.

**Comment by Robbepop** [comment]
Unfortunately `miri` is far too slow to check those tests in a practical amount of time, therefore we disabled `miri` for quite some time. Only recently did it become a problem - which makes sense given that #15284 is only roughly 2 weeks old.
In CI we check `miri` passes all enabled tests, and since the tests in the `regmach` directory were impractical to execute via `miri` we had to disable them. Obviously being able to run those tests on `miri` would be ideal, yet we do not have the required super computer. :D

**Comment by lnicola** [comment]
It's a bit more work, but you can ignore individual tests with e.g. `#[cfg_attr(miri, ignore)]`. That PR enables us to interpret more of the standard library code, which will become more and more important for IDE features.

**Comment by Robbepop** [comment]
> It's a bit more work, but you can ignore individual tests with e.g. `#[cfg_attr(miri, ignore)]`. That PR enables us to interpret more of the standard library code, which will become more and more important for IDE features.

Hmmm, indeed a lot of work given that there are well over a 1000 tests but on a second thought probably also the way conditional tests like these should actually have been handled in the first place. 🤔 Thanks!

**Comment by lnicola** [comment]
> indeed a lot of work given that there are well over a 1000 tests

https://github.com/paritytech/wasmi/pull/744 might do it, I didn't test.

We might also add a `cfg(rust_analyzer)` in the future, but I can't promise it.

**Comment by Robbepop** [comment]
Solution for the issue found. Thanks to @lnicola for the help!
