### ISSUE TITLE
Hashmap method not found

### ISSUE THREAD

**Issue by vikulikov** [rust-lang/rust-analyzer#15340]
<img width="738" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/28891532/f96412cd-ef4d-4ff3-ba3a-7373efcdc48b">

rust-analyzer 1.71.0 (8ede3aae 2023-07-12)
rustc 1.71.0 (8ede3aae2 2023-07-12)

cargo check does not find this error. and project is being built successfully

**Comment by vikulikov** [comment]
.cargo/config.toml
```toml
[build]
rustflags = ["--cfg", "tokio_unstable"]

```

lspconfig in neovim
```lua
        local capabilities = require('cmp_nvim_lsp').default_capabilities()
        lspconfig.rust_analyzer.setup {
            capabilities = capabilities,
            settings = {
                ['rust-analyzer'] = {
                    files = {
                        excludeDirs = { "target" }
                    },
                    workspace = {
                        symbol = {
                            search = {
                                limit = 3000
                            }
                        }
                    },
                    procMacro = {
                        enable = true
                    },
                    diagnostics = {
                        enable = true,
                        disabled = { "unresolved-proc-macro" },
                        enableExperimental = true,
                    },

                },
            },
        }

```
nothing special.

The project is not new and the error occures in several different functions but with similar hashmap type

**Comment by vikulikov** [comment]
Oh, it's from `enableExperimental = true` setting. whithout this setting diagnostics are valid

**Comment by lnicola** [comment]
Can you try in a new project, so we're sure it's not something specific to that one? Also, a `rustup component remove rust-src; rustup component add rust-src` won't hurt, just in case you've edited one of the source files by mistake (it happens pretty often).

I also use `rust-analyzer.diagnostics.experimental.enable`. The easiest way to check is `gd` or whatever on `insert`.

**Comment by vikulikov** [comment]
- new project with `enableExperimantal=true`
<img width="995" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/28891532/2ed9607f-bea7-4449-ae17-cc7a89c26787">

- reinstalled rust-src
<img width="1020" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/28891532/296add2e-a0d3-4da7-86d6-64f73a6eb0ed">

`Go to definition` on insert not working also

**Comment by vikulikov** [comment]
In vscode by the way I'm not getting this error

**Comment by lnicola** [comment]
What if you configure Code to use the `rustup` version? You can set `rust-analyzer.server.path` to the output of `rustup which rust-analyzer`.

**Comment by lnicola** [comment]
Thanks, so it's the `rustup` version that's broken. I can reproduce and it seems fixed in the beta and nightly toolchains. We've been more diligent with downstream merges lately (the `rustup` version lags a lot when we update it regularly, and even more when we don't), so I'm not inclined to spend more time on this.

**Comment by vikulikov** [comment]
Ok, thanks for the quick help. Will move to the standalone version
