### ISSUE TITLE
Use of struct that uses #[serde_as] is not recognized

### ISSUE THREAD

**Issue by HighCommander4** [rust-lang/rust-analyzer#15355]
**rust-analyzer version**: 0.3.1599
**rustc version**: 1.66.1

In the following code:

```rust
#[macro_use(Deserialize)]
extern crate serde_derive;

use std::collections::HashMap;
use serde_with::serde_as;

#[serde_as]
#[derive(Deserialize)]
struct Waldo {
  #[serde_as(as = "Vec<(_, _)>")]
  location: HashMap<String, String>
}

fn foo(w: Waldo) -> () {}
```

Usages of the struct `Waldo`, such as the one in the signature of `foo` on the last line, are not recognized (they do not get the correct semantic highlighting, and go-to-def on the use does not take you to the struct definition).

**Comment by Veykril** [comment]
This works fine for me, what is the expansion of the `serde_as` attribute for you? (by invoking r-a's expand macro recursively feature)

**Comment by HighCommander4** [comment]
> This works fine for me, what is the expansion of the `serde_as` attribute for you? (by invoking r-a's expand macro recursively feature)

I get the following expansion when invoking the command on either of the `serde_as` tokens:

```
// Recursive expansion of serde_as macro
// ======================================

::core::compile_error! {
  "expected identifier, found keyword `as`"
}
```

though it's not clear to me from this where things go wrong.

**Comment by florianjuesten** [comment]
I still face this issue. Is there any update on this? :)

**Comment by Veykril** [comment]
Can you set up a small repo with a reproducer? As I said earlier I do not encounter this problem for the provided snippet.

**Comment by Veykril** [comment]
Also `rustc version: 1.66.1` is a bit old, that might cause issues with r-a as well. We generally do not attempt to support older rustc versions currently, so maybe try updating your rust toolchain or downgrading the rust-analyzer version you are usin to somethin from around that version's release date.

**Comment by HighCommander4** [comment]
> Also `rustc version: 1.66.1` is a bit old, that might cause issues with r-a as well. We generally do not attempt to support older rustc versions currently, so maybe try updating your rust toolchain or downgrading the rust-analyzer version you are usin to somethin from around that version's release date.

You're right, upgrading the compiler from 1.66 to 1.71 fixed the issue!

Is there a way to know what rustc versions a rust-analyzer version is compatible with, so I can avoid upgrading one more eagerly than the other?

**Comment by Veykril** [comment]
Picking a r-a release from around when the stable rust version you want to use should usually work, so for 1.66 for example which released on 2022-12-15, https://github.com/rust-lang/rust-analyzer/releases/tag/2022-12-19 should work
You can see all release tags on https://github.com/rust-lang/rust-analyzer/tags

**Comment by Veykril** [comment]
I'll close this then, as this issue comes from an older toolchain which we currently do not support on the latest r-a versions
