### ISSUE TITLE
include! macro behaviors differently between rust-analyzer and standard library

### ISSUE THREAD

**Issue by YUCLing** [rust-lang/rust-analyzer#15365]
https://github.com/rust-lang/rust-analyzer/issues/7846 fixed this issue before, but not completely. It seems like if the path inside `include!` macro is not static, rust-analyzer is still unable to handle it properly.

I've created a [minimal reproduction](https://github.com/YUCLing/rust-analyzer-include-issue-repro) for this issue.

**rust-analyzer version**: 0.3.1607-standalone (429a3816a 2023-07-30)

**rustc version**: rustc 1.71.0 (8ede3aae2 2023-07-12)

**relevant settings**: none

**Comment by Veykril** [comment]
The highlighting is wacky for some reason but the expansion works fine for me
![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/86847040-f10b-4e14-9971-729d09f3543c)

**Comment by YUCLing** [comment]
Oh, it's a bit different from the original issue, the expansion works, but the rust-analyzer is unable to resolve the module.

**Comment by YUCLing** [comment]
This doesn't work for me all the time, also tried versions from weeks ago and 1yr ago, still not working.

**Comment by YUCLing** [comment]
Tested with `rust-analyzer version: 0.3.2220-standalone (27e824fad4 2024-12-15)`. This works properly now.
