### ISSUE TITLE
Import suggestions within a function call should use function argument types to prioritize suggestions

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-analyzer#15384]
Say we've got some AtomicUsize, and we call `fetch_add` with `1` and `Ordering` (not yet imported), and then press Ctrl+Space at the `[HERE]` position

```rust
NEXT_STR_ID.fetch_add(1, Ordering[HERE])
```

Currently, it suggests `core::cmp::Ordering` as the top result, and then `core::sync::atomic::Ordering` after that. While the `core::cmp::Ordering` is perhaps used more commonly overall, or it just sorts earlier alphabetically, since the argument type of the second argument of `fetch_add` actually matches one of the suggestions already in the list (the atomic ordering type), that suggestion should get top priority.

**Comment by Veykril** [comment]
I suppose we aren't actually prioritizing by type for importing completions yet

**Comment by jmintb** [comment]
Can I work on this? :)

**Comment by Veykril** [comment]
Go ahead!

**Comment by lnicola** [comment]
The quick fix still suggests `std::cmp::Ordering`, do we leave this open or file a new one?

**Comment by Veykril** [comment]
Does it still not prioritize the right one? Then we can leave this open

**Comment by lnicola** [comment]
![image](https://github.com/rust-lang/rust-analyzer/assets/308347/b531d92e-a938-4066-bfa0-4c5e4cbc74f6)

**Comment by Veykril** [comment]
Oh I missed that you meant the quickfix, not the completion. The quickfix should probably get a separate issue, as it currently doesn't do any priority checks I think?
