### ISSUE TITLE
Newly emitting `non_snake_case` warnings on output of derive macro

### ISSUE THREAD

**Issue by spencerwilson** [rust-lang/rust-analyzer#15394]
**rust-analyzer version**: rust-analyzer 0.3.1599-standalone (99718d0c8 2023-07-22)

**rustc version**: rustc 1.69.0 (84c898d65 2023-04-16)

## Expected behavior

For a given rustc lint (e.g., [`non_snake_case`](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html?highlight=non_snake_case#non-snake-case)), `cargo check` and rust-analyzer report the same set of warnings/errors for that lint. If one of them reports a violation, the other does, too.

## Actual behavior

In my project,
- `cargo check` reports no issues ✅ 
- `rust-analyzer 0.3.1591-standalone (d82451103 2023-07-16)` reports no issues ✅ 
- `rust-analyzer 0.3.1599-standalone (99718d0c8 2023-07-22)` reports warning instances of the rustc lint `non_snake_case` ❌ 

## Details

In my scenario I have a build.rs that generates a source file, which elsewhere I inline via [`tonic::include_proto!`](https://docs.rs/tonic/0.9.2/tonic/macro.include_proto.html). For each instance in the generated code of `#[derive(::prost::Message)]`, the newer rust-analyzer gives the following warning:
```
Function `ScalarWrapper` should have snake_case name, e.g. `scalar_wrapper`
```
The only occurrence of that identifier in the `prost-derive` source tree is here: https://github.com/tokio-rs/prost/blob/468c80cd343321d5d4b361febbeec832ab5228b6/prost-derive/src/field/mod.rs#L145-L153

Sorry, I won't have time in the next couple weeks to make a minimal repro. Hopefully this is enough info to give some ideas. Please let me know if there are any simple steps I can perform to help debug. Oh and if this is actually _expected_ behavior, that's fine too, I can look into getting it resolved in prost-derive then.

**Comment by spencerwilson** [comment]
Workaround for VS Code users: Set the following type of thing in in VS Code settings:
```json
{
  "rust-analyzer.server.path": "/path/to/rust-analyzer-aarch64-apple-darwin-2023-07-16"
}
```

**Comment by lowr** [comment]
I believe this is the same issue as #15344. Closing as a duplicate, but thanks for the report!

For anyone interested, the warning seems to originate in [this `TokenStream`](https://github.com/tokio-rs/prost/blob/468c80cd343321d5d4b361febbeec832ab5228b6/prost-derive/src/field/scalar.rs#L232-L234).

**Comment by huntc** [comment]
Other than the [path to an older RA](https://github.com/rust-lang/rust-analyzer/issues/15394#issuecomment-1666311884) are there any other workarounds? My workspace has become a sea of yellow. :-( Thanks for any pointers. I did go looking at the RA project also.
