### ISSUE TITLE
Failed to discover workspace

### ISSUE THREAD

**Issue by cisaacson** [rust-lang/rust-analyzer#15402]
I have been using rust-analyzer with VS Code for a long time with no issues. Now I am getting `Failed to discover workspace` in a window that has a non-rust project open. Is there any way to limit rust-analyzer to just the projects that use rust?

**Comment by lnicola** [comment]
It's already supposed to activate only in Rust projects, but there is one existing issue where someone has the same problem. Maybe try checking if it happens in every project or if there's something that triggers it.

**Comment by Veykril** [comment]
Are there any rust files in your project? If not then this might be another vscode extension activating rust-analyzer

**Comment by cisaacson** [comment]
I checked, there were no rust files in this project at all. I closed the project window, restarted VS Code and in the process VS Code updated. Now it is no longer happening. I think this was a regression in VS Code in the version I hda. I'll close the issue, thanks for the quick help.
