### ISSUE TITLE
Better debugging support for variables

### ISSUE THREAD

**Issue by erenturkm** [rust-lang/rust-analyzer#15407]
Hi,

I am relatively new to Rust, coming from C# and Visual Studio. I am using the rust-analyzer v0.3.1615 inside Visual Studio Code 1.80.2 Current variables support seems lot to be desired and slowing me down so much so that I had to come up with specific structs that converts these types to observable ones inside debuging window.

Examples:
This is how I see enum variables, I was hoping to see enum1 and the current value of the enum not all possibilities.
enum1
&nbsp;&nbsp;&nbsp;&nbsp;Variant0:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Value {_0:true}
&nbsp;&nbsp;&nbsp;&nbsp;Variant1:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Value:{_0:""}
 
I have a similar situation with Paths and OsStrs where I cant see the value:
path1: {length 5}
&nbsp;&nbsp;&nbsp;&nbsp;<When expanded>   length:5

I am hoping there is a way to see them, if not when are we planning to address this?

Thanks in advance

**Comment by lnicola** [comment]
Generally, C# in VS and Java will have the best debugging experience out of all languages. Native ones will never compete to that, although VS at least has Edit and Continue for C++.

There are three components here:

 - rust-analyzer only triggers the debugging extension
 - the debugging extension is an interface over a native debugger like cdb, gdb or lldb
 - the native debugger generally won't understand high-level language idioms
 - the program itself can contain debugger-specific visualizer scripts or pretty-printers to improve the debug-printing experience, e.g. https://rust-lang.github.io/rfcs/3191-debugger-visualizer.html

You can find some open issues about this, like https://github.com/rust-lang/rust/issues/111868, https://github.com/rust-lang/rust/issues/43334, https://github.com/rust-lang/rust/issues/48462 or https://github.com/rust-lang/rust/issues/36503.

But rust-analyzer has nothing to do with debugging, so it's out of scope for us.

**Comment by erenturkm** [comment]
Thanks for the explanation, I think we need to provide a beginner friendly version of which package/project is responsible for the different developer experiences in Rust at high level with links to drill down further. Since this is provided by a single source in .NET. it can easily be mistaken to be a single package doing everything. Maybe I missed, do we have such a documentation?

**Comment by lnicola** [comment]
> Since this is provided by a single source in .NET. it can easily be mistaken to be a single package doing everything.

We suggest installing a debugging extension if one is not available, perhaps you already had one or missed the implications.

> Maybe I missed, do we have such a documentation?

[The manual](https://rust-analyzer.github.io/manual.html) doesn't specifically mention this, but it's so large it would be easy to miss anyway. But improvements are welcome, if you're thinking of something specific in mind.
