### ISSUE TITLE
rust-analyzer in neovim is attached but no completion

### ISSUE THREAD

**Issue by pingpong71** [rust-lang/rust-analyzer#15404]
I have installed rust-analyzer via mason.nvim.
`rust-analyzer 0.3.1607-standalone`

When I run :LspInfo I can see that I am working in a rust file, and that the LSP is attached to the buffer.  I am not seeing any function completion when working in the file.  

If I run :!rust-analyzer I get the following error:
`Error: expected initialize request, got error: receiving on an empty and disconnected channel`

My configuration for rust-analyzer looks like this:
```
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities
local lspconfig = require("lspconfig")
local util = require "lspconfig/util"

lspconfig.rust_analyzer.setup({
  on_attach = on_attach,
  capabilities = capabilities,
  filetypes = {"rust"},
  root_dir = util.root_pattern("Cargo.toml"),
  settings = {
    ['rust_analyzer'] = {
      cargo = {
        allFeatures = true,
      },
    },
  },
})
```

I have run `cargo init` so i do have the Cargo.toml file in my project root.  I am confused why I am seeing this error.

**Comment by lnicola** [comment]
That configuration looks fine, as far as I can tell. Do other features like `Go to definition` work?

> If I run :!rust-analyzer I get the following error: Error: expected initialize request, got error: receiving on an empty and disconnected channel

I don't think you're supposed to run it like that. The server is invoked by the LSP client, not by _you_.

**Comment by pingpong71** [comment]
Interesting follow up.  I think my neovim config was correct.  I'm running on ubuntu, and had installed rust and cargo via apt.  I removed them, and installed rustup via the rust documentation.  Then `rustup toolchain install stable` and everything just started working as expected.  

Closing this issue.

**Comment by lnicola** [comment]
Did you also install `rust-src`?

**Comment by lnicola** [comment]
We need the standard library source code, so you have to install it (using rustup or apt, depending on how you installed the compiler).

**Comment by pingpong71** [comment]
@lnicola Thank you for the explanation.  At least I know exactly why it was failing.

**Comment by amanuel2** [comment]
@lnicola How do you give rust-analyzer source code for custom libraries, or other non std libraries?  Does it automatically get it when you cargo install a new lib? (very new to rust so this might be dumb)

**Comment by lnicola** [comment]
@amanuel2 you don't cargo install a new library, that's only for binaries and installs them for your user, not project.

You use cargo add for libraries or add them to your Cargo.toml, and rust-analyzer finds them automatically, even with path dependencies.

**Comment by wwdz540** [comment]
I try this command :
```
rustup component add rust-analyzer
```
then ok

**Comment by No0ne003** [comment]
I have the same problem I delete rust by `rustup self uninstall` and install it from rustup.rs but it still doesn't work when I try to write on rust file it show this error 
![Image](https://github.com/user-attachments/assets/d99f9309-a39c-4428-928b-2d0ae7d45de3)
