### ISSUE TITLE
Rust analyzer incorrectly uses "CamelCase" instead of "PascalCase".

### ISSUE THREAD

**Issue by lindhe** [rust-lang/rust-analyzer#15414]
The analyzer incorrectly suggest that I shoulod use "CamelCase" for the variants in my Enum. I already use camel case, just not the same variant of camel case as Rust expects. Since the term camel case  is not clear about the initial letter, it would be better to use a more well defined term such as "PascalCase" or "UpperCamelCase".

![Screenshot from 2023-08-08 14-37-00](https://github.com/rust-lang/rust-analyzer/assets/7773090/098cf644-6dbf-4baf-90f3-b17ada371126)

[Camel case on Wikipedia](https://en.wikipedia.org/wiki/Camel_case) (bold emphasis is mine):

> The format indicates the first word starting with **either case**, then the following words having an initial [uppercase](https://en.wikipedia.org/wiki/Uppercase) letter.
> […]
> The more specific terms Pascal case and upper camel case refer to a joined phrase where the first letter of each word is capitalized, **including the initial letter of the first word**.

See also this table of [examples of letter case on Wikipedia](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Examples_of_multiple-word_identifier_formats).

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

[Mason](https://github.com/williamboman/mason.nvim) reports `rust-analyzer` 2023-08-07.

**rustc version**: (eg. output of `rustc -V`)

```console
$ rustc -V                                                                                                       1 ↵
rustc 1.71.1 (eb26296b5 2023-08-03)
```

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

Not sure, nothing I've set explicitly at least. I run NeoVim with [rust-lang/rust.vim](https://github.com/rust-lang/rust.vim) and[ `rust_analyzer` for lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#rust_analyzer) installed via [Mason](https://github.com/williamboman/mason.nvim).

**Comment by lindhe** [comment]
I guess we can discount NeoVim in this equation. I just realized I get the same warning from running `cargo check`:

![Screenshot from 2023-08-08 14-41-05](https://github.com/rust-lang/rust-analyzer/assets/7773090/40695b36-3eab-4fb0-a4e8-0ef2a9c25015)

**Comment by tadeokondrak** [comment]
See https://github.com/rust-lang/rfcs/pull/2389 for the naming decision for rustc. Is there an error that uses "camel case" when it should use "upper camel case"?

**Comment by lindhe** [comment]
Yeah, looks like I lost that argument five years ago. No reason to keep this open then, until the day I have the t time and energy arguing with programming language maintainers. :confused:

**Comment by lnicola** [comment]
Since it might not be obvious, you're seeing the `rustc` diagnostic, which we don't control. `rust-analyzer` has its own, inconsistent, diagnostic:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/0ed62073-a964-4d02-a07a-6188c91c697f)
