### ISSUE TITLE
Comment/Uncomment block of code

### ISSUE THREAD

**Issue by goradata** [rust-lang/rust-analyzer#15442]
Hi,

We have this functionaly in Visual Studio and generally find that it would be very useful in Rust analyzer, if this is not possible already (or if this is possible with something else):
1) You select a block of rust code (Generally implementation of a function)
2)  You select comment Code,
3)  Inserts necessary comments on each line to comment out for the given selection.

It should also work in reverse.

**Comment by flodiebold** [comment]
This is generally provided by the editor, for example "Toggle Line Comment" (Ctrl+/) in VSCode.

**Comment by goradata** [comment]
Excellent, thanks
