### ISSUE TITLE
Traits no longer show up in VSCode workspace symbol search

### ISSUE THREAD

**Issue by cart** [rust-lang/rust-analyzer#15444]
**rust-analyzer version**: 0.3.1615-standalone

**rustc version**: 1.71.0

**relevant vscode settings**

```json
// relevant fields from settings.json
"rust-analyzer.imports.prefix": "crate",
"rust-analyzer.cargo.buildScripts.enable": true,
"rust-analyzer.procMacro.enable": true,
"rust-analyzer.inlayHints.parameterHints.enable": false,
"rust-analyzer.inlayHints.chainingHints.enable": false,
"rust-analyzer.inlayHints.maxLength": 15,
"rust-analyzer.imports.group.enable": false,
"rust-analyzer.check.features": "all",
```

**vscode version**:  1.81.1

**OS**: Debian Sid

Traits are no longer showing up for me in workspace symbol search. For example in the `serde` repo, if I search for `Serialize`, I only get non-trait results:

![image](https://github.com/rust-lang/rust-analyzer/assets/2694663/ef3a4c78-22ef-41b8-9f3d-b94309a19eb5)

I've observed this in every repo I try (`bevy`, `bevy_proto`, etc). This used to work fine, but recently it has stopped working.

**Comment by Veykril** [comment]
Very odd, it does not seem to be all traits, but most of them ...
