### ISSUE TITLE
run test/debug not visible for rstest

### ISSUE THREAD

**Issue by goradata** [rust-lang/rust-analyzer#15459]
Hi,

Vscode details are given below
`
Version: 1.81.1 (system setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22000
`
inside the integration tests.rs file, there are several test cases. run test/debug buttons are available for [test] but not visible for [rstest] as seen below. Please note, there is a run tests/debug at the top of the module which runs/debugs all tests. cargo test also works.
![rstesterror](https://github.com/rust-lang/rust-analyzer/assets/40225523/f927017d-169f-47dc-a8cb-66e2f5956d73)

**Comment by florianjuesten** [comment]
Hi :) I am currently facing the same problem. Why was this issue closed? Could you point me to a solutions? 😊 thx!

**Comment by erenturkm** [comment]
The problem is not related to rust-analyzer. It happens intermittently on my Vscode. Either close/open or resize the vscode window.

**Comment by DanielJoyce** [comment]
If I import rstest::rstest as test, then it works

Otherwise I don't see the run test hint for a rstest test.

**Comment by DanielJoyce** [comment]
This seems to have broken recently.
