### ISSUE TITLE
Stuck at roots scanning in vscode, and memory usage increase over time

### ISSUE THREAD

**Issue by Eason0729** [rust-lang/rust-analyzer#15460]
![rust](https://github.com/rust-lang/rust-analyzer/assets/30045503/e1e298f3-8aef-4b80-bcb4-8a47cf421522)

I noticed a huge memory consumption of rust anaylzer after recent update, it even cause oom after minutes of use.

In addtion, I noticed a lot of rust-analyzer process(with different pid), they use most(about 70%) of the memory on the system.

Is it normal?

I have Intel i5-1240p, with 16GB of memory on fedora 38(kde spin).

```
[]$ rustc -V
rustc 1.70.0 (90c541806 2023-05-31)
```

rust-analyzer version: rust-analyzer version: 0.3.1623-standalone

**Comment by Eason0729** [comment]
I just downgraded to rust-analyzer ``version: 0.3.1557-standalone(2023-06-19)``, the problem seems to be gone.

**Comment by lnicola** [comment]
Can you compare the memory usage in the two versions when running `rust-analyzer analysis-stats .` on your project? Or, if it's the same, can you try to bisect?

**Comment by lnicola** [comment]
> I noticed a lot of rust-analyzer process(with different pid), they use most(about 70%) of the memory on the system.

It's a single process with multiple threads, you can configure htop to hide those.

**Comment by Eason0729** [comment]
> > I noticed a lot of rust-analyzer process(with different pid), they use most(about 70%) of the memory on the system.
> 
> It's a single process with multiple threads, you can configure htop to hide those.

It is pgid (not pid), sorry for that.

Is it normal that vscode extension open three of them?

In htop, I have killed three processes. Usually, I would expect to kill processes with same pgid when you kill one of them.

**Comment by Veykril** [comment]
There will be one process per vscode window which is the main language server (the one that consumes a lot of memory), then there are is one additional process per workspace which is proc-macro server, that one should consume far less memory though (maybe around a megabyte).

**Comment by Eason0729** [comment]
0.3.1557-standalone
```
Database loaded:     2.21s, 463minstr (metadata 442.46ms, 51minstr; build 1.63s, 26minstr)
  crates: 5, mods: 40, decls: 1182, bodies: 996, adts: 113, consts: 26
Item Collection:     11.65s, 113ginstr
Body lowering:       974.39ms, 8668minstr                                                           
  exprs: 19512, ??ty: 113 (0%), ?ty: 239 (1%), !ty: 0                                               
  pats: 4761, ??ty: 0 (0%), ?ty: 46 (0%), !ty: 0
Inference:           86.65s, 545ginstr
MIR lowering:        3.23s, 14ginstr
Mir failed bodies: 136 (13%)
Data layouts:        13.01ms, 68minstr
Failed data layouts: 1 (1%)
Const evaluation:    790.06µs, 5995kinstr
Failed const evals: 0 (0%)
Total:               102.52s, 681ginstr
```
---
0.3.1623-standalone
```
Database loaded:     1.89s, 418minstr (metadata 329.83ms, 51minstr; build 1.42s, 13minstr)
  item trees: 28
Item Tree Collection: 13.64ms, 160minstr
  crates: 5, mods: 40, decls: 1182, bodies: 996, adts: 113, consts: 26
Item Collection:     11.05s, 107ginstr
Body lowering:       935.81ms, 8175minstr                                                           
  exprs: 19512, ??ty: 58 (0%), ?ty: 230 (1%), !ty: 0                                                
  pats: 4761, ??ty: 0 (0%), ?ty: 46 (0%), !ty: 0
Inference:           56.57s, 357ginstr
MIR lowering:        1.35s, 8028minstr
Mir failed bodies: 112 (11%)
Data layouts:        7.90ms, 60minstr
Failed data layouts: 1 (1%)
Const evaluation:    35.63ms, 263minstr
Failed const evals: 0 (0%)
Total:               69.96s, 481ginstr
```

**Comment by Veykril** [comment]
Ah sorry, you need to pass the `memory-usage` flag as well 😅, that is `rust-analyzer analysis-stats . --memory-usage`

(Also woah, thats quite a difference in inference time)

**Comment by lnicola** [comment]
I know it doesn't work on all platforms, but we should probably always measure the memory usage.

**Comment by Eason0729** [comment]
0.3.1557-standalone
```
Database loaded:     1.62s, 423minstr, 171mb (metadata 341.31ms, 51minstr, 1272kb; build 1.13s, 13minstr, 128kb)
  crates: 5, mods: 40, decls: 1182, bodies: 996, adts: 113, consts: 26
Item Collection:     12.76s, 113ginstr, 568mb
Body lowering:       1.06s, 8669minstr, 30mb                                                        
  exprs: 19512, ??ty: 113 (0%), ?ty: 239 (1%), !ty: 0                                               
  pats: 4761, ??ty: 0 (0%), ?ty: 46 (0%), !ty: 0
Inference:           90.93s, 570ginstr, 330mb
MIR lowering:        2.45s, 15ginstr, 14mb
Mir failed bodies: 136 (13%)
Data layouts:        8.31ms, 68minstr, 490kb
Failed data layouts: 1 (1%)
Const evaluation:    553.81µs, 6006kinstr, 29kb
Failed const evals: 0 (0%)
Total:               107.22s, 707ginstr, 943mb
```
---
0.3.1623-standalone
```
Database loaded:     1.58s, 453minstr, 171mb (metadata 338.16ms, 51minstr, 1308kb; build 1.10s, 28minstr, 125kb)
  item trees: 28
Item Tree Collection: 14.03ms, 160minstr, 1526kb
  crates: 5, mods: 40, decls: 1182, bodies: 996, adts: 113, consts: 26
Item Collection:     11.25s, 107ginstr, 574mb
Body lowering:       952.96ms, 8175minstr, 40mb                                                     
  exprs: 19512, ??ty: 58 (0%), ?ty: 230 (1%), !ty: 0                                                
  pats: 4761, ??ty: 0 (0%), ?ty: 46 (0%), !ty: 0
Inference:           68.94s, 437ginstr, 361mb
MIR lowering:        1.89s, 11ginstr, 14mb
Mir failed bodies: 112 (11%)
Data layouts:        8.48ms, 60minstr, 506kb
Failed data layouts: 1 (1%)
Const evaluation:    34.20ms, 263minstr, 2879kb
Failed const evals: 0 (0%)
Total:               83.10s, 565ginstr, 995mb
```

**Comment by Eason0729** [comment]
I haven't bisect,yet(I just learned that there is a bisect function for vscode extension). However, I managed to reproduce the problem.

I noticed that rust analyzer stuck a root scanned: 343/344, and memory usage increase steadily over time.

Does that show the problem?

![Screenshot_20230815_193609](https://github.com/rust-lang/rust-analyzer/assets/30045503/ef3d04dd-4441-41fe-8204-546116d60484)

I would try to bisect extension later.

**Comment by Eason0729** [comment]
I did the bisect and it show that the rustlang.rust-analyzer is the extension causing the problem.

The vscode extension stuck at ``roots scanned: 343/344``, and auto completion doesn't work, it's not just the memory usage unusual.

What else can I do to revealed the problem?

**Comment by lnicola** [comment]
By bisection I meant downloading various releases from GitHub (you can get either the VSIX or the binary, if `analysis-stats` reproduces the issue, which it doesn't appear to), to see which release introduced the problem. Then you could also bisect on the git repository, but it's a little more complex.

The extension bisection feature in Code is different, it helps you identify problematic extensions without disabling them one by one.

**Comment by Eason0729** [comment]
Sorry, I had not been active on github for a week.

I am running native vscode(the one from vscode copr).

In addition, I will be busy for next four days, after that, I will try it.

**Comment by Eason0729** [comment]
<details>
<summary>output</summary>
<br>
<code>Per-query memory usage:
   101mb  25987 FileItemTreeQuery
    97mb   7914 FileTextQuery
    72mb   9321 HygieneFrameQuery
    49mb  23222 MacroArgNodeQuery
    47mb    149 CrateDefMapQueryQuery
    18mb  32504 AttrsQuery
    17mb    645 DeclMacroExpanderQuery
    17mb  25995 AstIdMapQuery
    14mb   2776 ParseQuery
    13mb  23243 ParseMacroExpansionQuery
    12mb  23243 MacroExpandQuery
     8mb    183 ExpandProcMacroQuery
     6mb  26143 InternMacroCallQuery
     5mb  41253 InternImplQuery
     4mb   8868 ImplDataWithDiagnosticsQuery
  3611kb      1 CrateGraphQuery
  3281kb  25039 InternFunctionQuery
  3039kb    345 SourceRootQuery
  1882kb   8868 ImplDataQuery
   964kb   7914 FileSourceRootQuery
   766kb   6791 InternConstQuery
   678kb   4886 InternStructQuery
   594kb   4229 InternTypeAliasQuery
   305kb      2 CrateLangItemsQuery
   164kb     85 EnumDataWithDiagnosticsQuery
   161kb   1119 InternTraitQuery
   146kb     85 EnumDataQuery
   144kb      6 BlockDefMapQuery
   132kb      6 BodyWithSourceMapQuery
   117kb   1206 InternMacroRulesQuery
   110kb    985 InternEnumQuery
    97kb      0 ImplDatumQuery
    64kb      0 CallableItemSignatureQuery
    64kb      0 AssociatedTyDataQuery
    56kb      0 InternTypeOrConstParamIdQuery
    56kb     73 GenericParamsQuery
    49kb      2 LineIndexQuery
    43kb     88 InternExternBlockQuery
    37kb      1 ProcMacrosQuery
    36kb      1 TraitImplsInCrateQuery
    32kb      1 InternTraitAliasQuery
    32kb      0 VariantsAttrsSourceMapQuery
    32kb      0 ValueTyQuery
    32kb      0 FunctionVisibilityQuery
    32kb      0 InherentImplsInBlockQuery
    32kb      0 FnDefDatumQuery
    32kb      0 FieldsAttrsQuery
    32kb      0 ConstEvalDiscriminantQuery
    32kb      0 LayoutOfAdtQuery
    30kb      0 FieldVisibilitiesQuery
    16kb     43 ImplTraitQuery
    10kb    198 TraitDataWithDiagnosticsQuery
     9kb     62 InternProcMacroQuery
     8kb      0 TraitAliasDataQuery
     5kb     42 InternMacro2Query
     5kb    241 InternStaticQuery
     4kb     43 ImplSelfTyQuery
   3440b      2 SourceRootCratesQuery
   2784b      1 LibraryRootsQuery
    688b      6 InternBlockQuery
    544b      0 ConstParamTyQuery
    416b      1 Macro2DataQuery
    240b      1 LocalRootsQuery
      0b      0 StructDataQuery
      0b      0 StructDataWithDiagnosticsQuery
      0b      0 ConstDataQuery
      0b      0 StaticDataQuery
      0b      0 ExprScopesQuery
      0b      0 FieldsAttrsSourceMapQuery
      0b      0 ImportMapQuery
      0b      0 ConstVisibilityQuery
      0b      0 CrateSupportsNoStdQuery
      0b      0 InferQueryQuery
      0b      0 MirBodyQuery
      0b      0 ConstEvalQuery
      0b      0 GenericPredicatesForParamQuery
      0b      0 GenericPredicatesQuery
      0b      0 IncoherentInherentImplCratesQuery
      0b      0 TraitImplsInBlockQuery
      0b      0 TraitImplsInDepsQuery
      0b      0 InternCallableDefQuery
      0b      0 StructDatumQuery
      0b      0 FnDefVarianceQuery
      0b      0 AdtVarianceQuery
      0b      0 AssociatedTyValueQuery
      0b      0 ModuleSymbolsQuery
    -16b      0 UnionDataQuery
    -16b      0 TargetDataLayoutQuery
    -32b      0 TypeAliasDataQuery
   -560b      0 TraitDatumQuery
   -27kb      4 FunctionDataQuery
   -27kb      6 BodyQuery
   -31kb      0 ReturnTypeImplTraitsQuery
   -32kb      0 ProcMacroDataQuery
   -32kb      0 FieldTypesQuery
   -32kb      0 InternGeneratorQuery
   -32kb      0 UnionDataWithDiagnosticsQuery
   -32kb    198 TraitDataQuery
   -32kb      0 InternClosureQuery
   -32kb      0 InternImplTraitIdQuery
   -36kb      5 TraitEnvironmentQuery
   -38kb      0 BorrowckQuery
   -42kb      0 LibrarySymbolsQuery
   -44kb     43 VariantsAttrsQuery
   -56kb     30 GenericDefaultsQuery
   -59kb      2 LangItemQuery
   -70kb      0 TraitSolveQueryQuery
   -71kb      0 ProgramClausesForChalkEnvQuery
  -179kb      1 InherentImplsInCrateQuery
  -306kb     20 TyQuery
 -1038kb     14 InternUnionQuery
 -1178kb      0 MacroRulesDataQuery
 -1221kb      0 InternLifetimeParamIdQuery
   513mb        Remaining

(note: database has been cleared)
</code>
</details>

**Comment by Eason0729** [comment]
I encounter another similar issue(and found the solution).

Although I can't reproduce it on project(because I can't find the git commit it happened), I think that might be related.

The root cause of that issue is symlink to `~/Documents`, the workspace root reside somewhere under `~/Documents`.

## Solution

Edit the `.vscode/settings.json`
```json
{
    "files.watcherExclude": {
        "path/to/dir/**": true
    },
    "rust-analyzer.files.excludeDirs": [
        "path/to/dir"
    ]
}
```
