### ISSUE TITLE
Change letter case for submodule file name make this file invisible for Intellisense/rust-analyzer

### ISSUE THREAD

**Issue by ndbn** [rust-lang/rust-analyzer#15467]
Project structure:
> main.rs
> /testmod
> /testmod/mod.rs
> 

Add into **main.rs**:
`mod testmod;
fn main() {
    testmod::Notworks::Notworks();
}
` 

Create file **/testmod/Notwork.rs** with some code (i32 is added as Intellisense hint for q ! ):
`pub fn notworks() {
  println!("Im work!");
  let q: i32 = 1;  
}`

Add into /testmod/mod.rs
`pub mod Notworks;`

Now project can be build and all works.

But I press F2 on file **/testmod/Notwork.rs** and rename it to **/testmod/notwork.rs**, just change letter case. VsCode/Extention ask me to refactor, all seems good
testmod::notworks::notworks(); at **main.rs**
pub mod notworks; at **/testmod/mod.rs**

and no more intellisense in **notwork.rs**
`pub fn notworks() {
  println!("Im work!");
  let q = 1; 
}`

No more Ctrl+Space hints, no type hints and others.

How I tried to solve:
Downgrade to lower rust-analyzer versions
Disable all other extentions
Restart rust-analyzer server
Restart VSCode
Restart PC

Only renaming file **notwork.rs** bring back Intellisense into it.

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
rust-analyzer version: 0.3.1623-standalone (2fbe69d11 2023-08-12)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.71.1 (eb26296b5 2023-08-03)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**Comment by lnicola** [comment]
Same as https://github.com/rust-lang/rust-analyzer/issues/9947, probably.

**Comment by ndbn** [comment]
It helps https://github.com/microsoft/vscode/issues/12448#issuecomment-655001292
