### ISSUE TITLE
MIR eval got very slow between rustc 1.72.0-nightly (8c74a5d27 2023-06-14) and rustc 1.72.0-nightly (114fb86ca 2023-06-15)

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#15498]
https://github.com/rust-lang/rust-analyzer/pull/15494#issuecomment-1687429493

**Comment by HKalbasi** [comment]
It is probably hanging, and reaching the execution limit. Making the offending const a function and running it using `Interpret test` can probably tell more.

**Comment by lnicola** [comment]
I tried

```rust
#[test]
fn foo() {
    const VS_CODES: &[&str] = &["code", "code-exploration", "code-insiders", "codium", "code-oss"];
}
```

and it actually passes, first time (after a project load) in 1 s, then right away, but there might be some caching involved.

**Comment by HKalbasi** [comment]
I meant:
```rust
#[test]
fn foo() {
    &["code", "code-exploration", "code-insiders", "codium", "code-oss"];
}
```
But I think it wouldn't work as well, and the problem is related to the debug rendering.

**Comment by lnicola** [comment]
That one passes instantly. Does `analysis-stats` invoke the `Debug` impl somehow?

**Comment by HKalbasi** [comment]
Yes it uses the same code path that hover uses, which tries to run `Debug` impls on evaluated constants.

**Comment by Veykril** [comment]
Oh that does not sound good, given 1.72 moves to stable soon ...

**Comment by HKalbasi** [comment]
It is hitting `execution limit exceeded` on `format > format_inner > estimated_capacity > sum`. I still didn't figured out why it is looping. If an emergency fix is needed, we can either decrease `const EXECUTION_LIMIT: usize = 10_000_000;` to make it bail out faster, or disable `Debug` rendering by commenting out `if let Ok(s) = mir::render_const_using_debug_impl(db, self.id, &c) {` in the `render_eval` function.
