### ISSUE TITLE
Invalid suggestion: inlining question mark operator into incompatible closure

### ISSUE THREAD

**Issue by coding-quizzer** [rust-lang/rust-analyzer#15497]
**rust-analyzer version**: 0.3.1631-standalone

**rustc version**: rustc 1.71.1 (eb26296b5 2023-08-03)

**bug**: rust analyzer suggests inlining an expression with the question mark operator inside a closure that does not return an option or result

 
![Closure_inlining_question_mark_operator](https://github.com/rust-lang/rust-analyzer/assets/96356498/97184528-be11-4721-96b7-375739537bc0)

Taking the suggestion results in this code, which is invalid, since the closure returns an i8.
![Closure_inlining_question_mark_correction](https://github.com/rust-lang/rust-analyzer/assets/96356498/070dbc10-9a2a-4dbc-8954-b3cfa1f47e54)

**Comment by lnicola** [comment]
This is probably fine. The assists aren't guaranteed to generate compilable code, and we can't do better here.

**Comment by Veykril** [comment]
We *could* look through the initializer for control flow expressions and disable the assist accordingly. Whether that's useful is another question. Note that these are not "suggestions", they are refactorings which may be useful or not on a subjective case by case basis.

**Comment by coding-quizzer** [comment]
Ok, I just noticed this behavior and wanted to point it out. Thank-you for responding!
