### ISSUE TITLE
Rust-analyzer depends on anymap 1.0.0-beta.2

### ISSUE THREAD

**Issue by gigaroby** [rust-lang/rust-analyzer#15500]
This appears to be unmaintained and contain soundness issues: https://rustsec.org/advisories/RUSTSEC-2021-0065.html.

See also https://github.com/chris-morgan/anymap/issues/37

**Comment by lnicola** [comment]
Looks like the soundness issue was fixed in the version we're using. It might be nice to move off `anymap`, but it doesn't seem terribly urgent.

**Comment by Veykril** [comment]
We should move off of it I think, it's easy enough to self implement this, especially since we don't need the entire API surface either

**Comment by shogo-nakano-desu** [comment]
Hi, can I try to work on this issue?

**Comment by lnicola** [comment]
@shogo-nakano-desu go ahead!

**Comment by lnicola** [comment]
Port added in #15618.

Now we're not going to know about any `anyhow` CVEs, but they're still going to affect us :grimacing:.
