### ISSUE TITLE
Terminal link provider includes backquote in file path

### ISSUE THREAD

**Issue by kriswuollett** [rust-lang/rust-analyzer#15518]
It is not possible to click on links like the following in the Rust Analyzer Language Server output window because the file path includes the trailing backquote, e.g.,:

    /Users/kris/Code/some-project/Cargo.toml`

As seen in:

```
Caused by:
  failed to parse manifest at `/Users/kris/Code/some-project/Cargo.toml`
```

**vscode version**: 1.81.1

**rust-analyzer version**: 0.3.1631-standalone (83b3ba1b8 2023-08-19)

**rustc version**: rustc 1.71.1 (eb26296b5 2023-08-03)

**relevant settings**: N/A

**Comment by kriswuollett** [comment]
<img width="262" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/1834192/f2d80c40-1a10-41d2-a7d9-7f1ed2a36da7">

**Comment by Veykril** [comment]
Sounds like a vscode issue to me

**Comment by kriswuollett** [comment]
Wasn't sure if there was a possibility/responsibility that an extension's output window should be customized for link handling, see: https://github.com/microsoft/vscode/blob/42ce7b7a2eeaa102ee40605a446174fce71c285a/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkProviderService.ts#L22-L35:

```typescript
	registerLinkProvider(linkProvider: ITerminalExternalLinkProvider): IDisposable {
		const disposables: IDisposable[] = [];
		this._linkProviders.add(linkProvider);
		this._onDidAddLinkProvider.fire(linkProvider);
		return {
			dispose: () => {
				for (const disposable of disposables) {
					disposable.dispose();
				}
				this._linkProviders.delete(linkProvider);
				this._onDidRemoveLinkProvider.fire(linkProvider);
			}
		};
	}
```

**Comment by kriswuollett** [comment]
Also if possible, it could lead to a feature request to add links to source for items like the library source code in a panic:

```
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'unsupported character `')'`', library/proc_macro/src/lib.rs:982:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
```

**Comment by kriswuollett** [comment]
> Sounds like a vscode issue to me

Yes, see comments in linked vscode issue above. Basically output windows are implemented differently from the terminal ones. Closing this issue.
