### ISSUE TITLE
Please honor #[allow(unused_braces)] directive

### ISSUE THREAD

**Issue by JRAndreassen** [rust-lang/rust-analyzer#15526]
rust-analyzer version: 0.3.1641-standalone (144526c90 2023-08-28)
rustc 1.72.0 (5680fa18f 2023-08-23)

Minimum reproducible:
```rust
#[allow(unused_imports, unused_braces)]
pub use core::{
    default
};


fn main() {
    println!("Goodbye cruel world!");
}

```

**Comment by JRAndreassen** [comment]
@HKalbasi ...
Sweet.. 
 Thanks

**Comment by HKalbasi** [comment]
@JRAndreassen You're welcome. Please report if you had any other problems with rust-analyzer. They are not always fixed this fast, but they are helpful.
