### ISSUE TITLE
Feature request: assist to convert between `x.into()` and `T::from(x)`

### ISSUE THREAD

**Issue by Kmeakin** [rust-lang/rust-analyzer#15539]
`x.into()` is easier to write, but `T::from(x)` is less ambiguous/easier to read. Would be nice to have an assist for doing this automatically

**Comment by Veykril** [comment]
Hmm, I think ideally this would be covered by just our inline function assist since the change here is actually just the `into` function's body. The assist does not work here though (presumely because of generics or something else)

**Comment by flodiebold** [comment]
Also it's not very discoverable to have to realize that inline function will do this 😅

**Comment by Veykril** [comment]
That is a convincing point 😅
