### ISSUE TITLE
is there a way to make completion docs show generics & where clauses in the signature?

### ISSUE THREAD

**Issue by vxpm** [rust-lang/rust-analyzer#15538]
currently, completion docs look like the following:
![image](https://github.com/rust-lang/rust-analyzer/assets/59714841/db1385bf-fecb-453f-8deb-11fa7c974afa)

i'd really like to be able to see declaration of generics and where clauses in the signature, akin to hover docs:
![image](https://github.com/rust-lang/rust-analyzer/assets/59714841/57b45e1a-c7d1-43de-8188-dc6fdc04cf07)
(images from neovim - however, vscode is essentially the same)

is there any way to configure rust-analyzer to do this?

**Comment by vxpm** [comment]
i've tried my hand at implementing this, with the following result:
![image](https://github.com/rust-lang/rust-analyzer/assets/59714841/d8bbc0d3-54c4-4a9f-9c53-09ff1019ecf8)

changes are in [my fork](https://github.com/vxpm/rust-analyzer). i'm not sure if this is an acceptable feature (or an acceptable implementation), should i open a pull request?

**Comment by veber-alex** [comment]
You should probably open a PR, I don't think anyone will look at the code otherwise.
I for one would love to have this improvement!

**Comment by vxpm** [comment]
done :)
