### ISSUE TITLE
When clicked on a type inference, it automatically populates it (regression)

### ISSUE THREAD

**Issue by cybersoulK** [rust-lang/rust-analyzer#15535]
make this feature opt in. 
it's not a useful feature, and the times i misclick it is very often and has a negative effect on productivity

**Comment by cybersoulK** [comment]
it looks like a vscode feature and not RA, so i will close

**Comment by cybersoulK** [comment]
i am reopening because i am not sure. Please someone enlighten who is responsible for this feature.
https://github.com/microsoft/vscode/issues/191868

**Comment by lnicola** [comment]
It's a LSP inlay hint that we fill in:

```json
/**
	 * Optional text edits that are performed when accepting this inlay hint.
	 *
	 * *Note* that edits are expected to change the document so that the inlay
	 * hint (or its nearest variant) is now part of the document and the inlay
	 * hint itself is now obsolete.
	 *
	 * Depending on the client capability `inlayHint.resolveSupport` clients
	 * might resolve this property late using the resolve request.
	 */
	textEdits?: [TextEdit](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit)[];
```

It's currently not possible to disable the edits, but you can completely disable the type hints.

**Comment by Veykril** [comment]
This very much feels like an editor setting to me as I don't see a scenario where one would want to disable this for one specific language extension only.

**Comment by cybersoulK** [comment]
Until this day, i keep seeing code that i didn't intent to be there in my code base. This has to be fixed...
<img width="661" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/102260392/839dcf8b-2335-4711-9c4e-11b565ab13a5">

**Comment by Veykril** [comment]
It did not automatically get added. You (accidentally) double clicked the hint which inserts it. That is a vscode feature (for language servers that support it), so this should be toggleable via a config by VSCode itself.

**Comment by cybersoulK** [comment]
no idea who is responsible, but i am still waiting for the vscode issue here as well: https://github.com/microsoft/vscode/issues/191868

i know i misclicked at some point, but i am not completely retarded, this happens very often in my workflow and there is no way i can stop it.

**Comment by lnicola** [comment]
> Note that edits are expected to change the document so that the inlay hint (or its nearest variant) is now part of the document and the inlay hint itself is now obsolete.

We're doing exactly what the spec says, and clearing the redo stack is a VS Code bug.
