### ISSUE TITLE
Warning `incorrect-ident-case` does not respect Rust flags in `.cargo/config.toml`

### ISSUE THREAD

**Issue by mkoncek** [rust-lang/rust-analyzer#15530]
**rust-analyzer version**: `$ rpm -q rust-analyzer`
`rust-analyzer-1.71.0-1.fc38.x86_64`

**rustc version**: `rustc 1.71.1 (eb26296b5 2023-08-03) (Fedora 1.71.1-1.fc38)`

**relevant settings**: `.cargo/config.toml` with the following content
```toml
rustflags = [
	"-A", "non_camel_case_types",
	"-A", "non_upper_case_globals",
	"-A", "dead_code",
	"-A", "unused_must_use",
	"-A", "non_snake_case",
]

rustdocflags = [
	"-A", "non_camel_case_types",
	"-A", "non_upper_case_globals",
	"-A", "dead_code",
	"-A", "unused_must_use",
	"-A", "non_snake_case",
]
```
Write the following code:
```rust
struct Foo_bar {}
const foo: i8 = 0;
```
In both lines, `rust-analyzer` complains (`incorrect-ident-case`) even though `rustflags` are set. I believe it should respect `.cargo/config.toml`.
I noticed a similar bug: https://github.com/rust-lang/rust-analyzer/issues/10980

**Comment by lnicola** [comment]
We generally try to honor `#[allow]`, but don't parse `.cargo/config.toml`.

**Comment by mkoncek** [comment]
I know that `clangd` does read files like `compile_commands.json` and `compile_flags.txt`.
I believe it wouldn't be out of place if `rust-analyzer` tried to read the config file and adjust its reports to be more consistent with the flags used by `rustc`.

**Comment by Veykril** [comment]
We can fetch the rustflags via `cargo -Z unstable-options config get rustflags`, though it is unfortunate that we would have to parse that output in general

**Comment by mkoncek** [comment]
If you decide to pursue this, please try not to depend on nightly features or `rustup`, it would be nice if it worked with distro-packaged versions of rust toolchains.

**Comment by lnicola** [comment]
We already use `-Zunstable-options --print cfg`, among other things. As for distro toolchains, my advice is to only use them to build distro packages, not for development. We nominally support only the latest stable.

**Comment by mkoncek** [comment]
I am ok with it. I want *any* way of storing some file with project-specific settings for rust-analyzer. I just thought that config.toml could be used for that purpose.

**Comment by Veykril** [comment]
We'll soon have a `rust-analyzer.toml` which would fit that purpose, so I agree let's close this as not planned
