### ISSUE TITLE
Primitive do not have copy trait

### ISSUE THREAD

**Issue by Red44** [rust-lang/rust-analyzer#15536]
**rust-analyzer version**: rust-analyzer 1.71.0

**rustc version**: rustc 1.71.0 (8ede3aae2 2023-07-12)

This copy:
```rust
fn copy_it(shut_copy: &mut bool){
    *shut_copy = !*shut_copy;
}
```
Results in: Cannot Move
It looks like, there is no knowledge, about the copy trait, that primitive types normally derive.

**Comment by HKalbasi** [comment]
I can't reproduce this.

**Comment by lnicola** [comment]
Can't reproduce it either, but it did at the time. Probably fixed at some point, please file a new issue if you run into something similar.

**Comment by Red44** [comment]
Thank you, guys, for looking into this. This is miss reported by me. This falls under [intellij-rust](https://github.com/intellij-rust/intellij-rust).
