### ISSUE TITLE
Go to definition in the description of variable or something equivalent

### ISSUE THREAD

**Issue by Ddystopia** [rust-lang/rust-analyzer#15579]
Often, I find myself in a scenario where I have a line of code like this:

```rust
let var = fn();
```

In various situations, I need to navigate to the definition of the type of var for tasks such as modifying it or gaining a better understanding of its fields. Currently, I have two somewhat cumbersome options:

1. Copy-Paste from Rust Analyzer's Type Display: I copy the type that editor displays in a window and then manually annotate the variable with the type to be able to `go_to_definition`, like so:
  `let var: MyType = fn();`
window:
![image](https://github.com/rust-lang/rust-analyzer/assets/63151578/e44f73de-5b84-4312-8d65-9cbd0c577ceb)

2. Scrolling/Searching Through Editor to find the definition

 I was wondering if there might be a more user-friendly solution to this situation. Ideally, I'd like to be able to invoke a "go_to_definition" action on the type displayed in editor's window. I understand that this might be technically challenging, but I believe it could significantly improve the developer experience.

But may be there could be developed another alternative? I could take responsibility to write a PR, if thing like I want doesn't clash with rust-analyzer's philosophy and it is possible to implement - as far as I know lsp does not have access to that window (in Neovim and VSCode's equivalent).

Thank you

**Comment by Veykril** [comment]
VSCode already has this
![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/45b9fec8-be33-4bfe-88b2-1dfc0edc4da8)

But this is an LSP extension so other clients (or rather rust LSP extensions for other clients) would need to implement that specifically

**Comment by Ddystopia** [comment]
> VSCode already has this ![image](https://user-images.githubusercontent.com/3757771/266660732-45b9fec8-be33-4bfe-88b2-1dfc0edc4da8.png)
> 
> But this is an LSP extension so other clients (or rather rust LSP extensions for other clients) would need to implement that specifically

Ok, thank you
