### ISSUE TITLE
Hover documentation example is cut off incorrectly

### ISSUE THREAD

**Issue by Awpteamoose** [rust-lang/rust-analyzer#15576]
**rust-analyzer version**: 0.3.1649-standalone (2df30e1e0 2023-09-03)

**rustc version**: rustc 1.72.0 (5680fa18f 2023-08-23)

**relevant settings**: n/a

In neovim (with coc-rust-analzyer):
![](https://i.imgur.com/YydWC2y.png)

In vs code (with rust-analyzer extension):
![](https://i.imgur.com/lhkZNfQ.png)

Actual documentation [i32::div_euclid](https://doc.rust-lang.org/std/primitive.i32.html#method.div_euclid):
![](https://i.imgur.com/eaSuING.png)

**Comment by Veykril** [comment]
That's due to https://github.com/rust-lang/rust-analyzer/issues/8092
