### ISSUE TITLE
🐛 False positive: Parentheses around attribute input values

### ISSUE THREAD

**Issue by pcgeek86** [rust-lang/rust-analyzer#15588]
### Summary

The Rust compiler requires parentheses around expressions for attribute inputs, under certain circumstances.

This compiles:

```rust
use clap::Args;

#[derive(Args)]
struct Register {
    #[arg(default_value_t = ("Cheyenne".to_string()))]
    name: String,
}
```

This does not compile:

```rust
use clap::Args;

#[derive(Args)]
struct Register {
    #[arg(default_value_t = "Cheyenne".to_string())]
    name: String,
}
```

**Note**: Make sure that clap dependency is installed. `cargo add clap@4.4.2 --features=derive`.

Notice how the extra parentheses are **required** in this circumstance. However, Rust Analyzer throws a warning, saying that the parentheses are **not** necessary.

<img width="774" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/466713/68539e57-d768-4351-a193-1c0fefacf152">

<img width="1202" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/466713/6ecd3d55-2c4c-42f4-9af7-f462d963c64c">

**rust-analyzer version**: `v0.3.1649`

**rustc version**: `rustc 1.72.0 (5680fa18f 2023-08-23)`

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

* Ubuntu Server 22.04 LTS (remote SSH)
* VSCode latest 1.81.1 on Windows 11
* Remote SSH extension connected to Linux server

**Comment by Veykril** [comment]
that diagnostic comes from rustc, not from rust-analyzer
