### ISSUE TITLE
rustfmt override no longer works as a relative path

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#15595]
I'm afraid https://github.com/rust-lang/rust-analyzer/pull/15564 has caused new problems... rustfmt doesn't work in the rustc workspace at all any more. The override is
```
    "rust-analyzer.rustfmt.overrideCommand": [
        "./build/host/rustfmt/bin/rustfmt",
        "--edition=2021",
    ],
```
and now this is interpreted relative to the directory the file is in, which of course does not work.
```
[Error - 2:59:01 PM] Request textDocument/formatting failed.
  Message: Failed to spawn cd "/home/r/src/rust/rustc.3/compiler/rustc_middle/src/mir" && "./build/host/rustfmt/bin/rustfmt" "--edition=2021"
  Code: -32603 
```

Probably this could be fixed by having RA do `workspace_dir.join(rustfmt_path)` so that it doesn't rely on a relative directory any more.

**rust-analyzer version**: rust-analyzer version: 0.3.1657-standalone

**Comment by davidbarsky** [comment]
Crap, I'm sorry about that. I'll put up a PR and test it against rustc. I'll proceed under the assumption that I'll need to bootstrap `rustc`?

**Comment by RalfJung** [comment]
You just need to check out rustc and open it in vscode + RA with the config [suggested in the dev guide](https://rustc-dev-guide.rust-lang.org/building/suggested.html#configuring-rust-analyzer-for-rustc), and try to format some files.
