### ISSUE TITLE
respect file created by other tools

### ISSUE THREAD

**Issue by ShuiRuTian** [rust-lang/rust-analyzer#15603]
Reproduce steps:
1. create an empty project, with a module file like tmp.rs
2. in root file(main.rs or lib.rs), write `mod tmp`;
3. open project with VSCode, no error
4. in terminal, create another module, like `cp ./tmp.rs ./tmp2.rs`
5. in root file, write `mod tmp2`;
6. You would find it reports an error `unresolved module, can't find module file: tmp2.rs or...`

Open the file tmp2.rs in VSCode would load the module.

And I found that 
- RA does respect change/deletion from other tools
- once we opened tmp2.rs file once, then RA respects creation with steps 4-6 after we delete tmp2.rs

Maybe this is a bug of VSCode? Not sure...

**Comment by Veykril** [comment]
You can try setting `"rust-analyzer.files.watcher": "server"` in your config and check if that fixes it. If that's the case then this is a bug in VSCode's file watcher.

**Comment by ShuiRuTian** [comment]
It's indeed resolved.

Interesting, just our of curious, did we get into trouble with VSCode's file watcher? Then RA has a server mode.

**Comment by king-11** [comment]
Reported the same to relevant `vscode` lead
