### ISSUE TITLE
Expand `macro_rules!` macro with “correct” delimiter

### ISSUE THREAD

**Issue by ModProg** [rust-lang/rust-analyzer#15608]
Often times, when a `macro_rules!` macro is normally used with, e.g., brackets (`Token![...]`) this delimiter is also used in the `macro_rules!` definition:
[syn/tokens.rs](https://github.com/dtolnay/syn/blob/5e3f55e684b7e33424b9f551105463418b196eb4/src/token.rs#L847-L947):
```rs
macro_rules! Token {
    [abstract]    => { $crate::token::Abstract };
    [as]          => { $crate::token::As };
    [async]       => { $crate::token::Async };
// ...
}
```

Therefor, I propose to use the delimiter used in the `macro_ruels!` definition for completions.

One caveat is, that one macro might be defined with different brackets, in that case, I propose to either fall back to the current behavior, use the first or most frequent one. But I think it would be fine to only change the behavior for macro definitions where one kind of delimiters is used consistently.

**Comment by Veykril** [comment]
Note that we already parse a macro's doc comments for usages of the macro, so if the doc comment uses it like `Toke![...]` then we will complete with those brackets. Your idea would be nice to apply as well I think, but its a bit more difficult as we don't record what arms matched currently.

**Comment by Veykril** [comment]
On second thought, I think it could be rather confusing if the arm can change the chosen bracing here, so the doc heuristic should be good enough imo

**Comment by ModProg** [comment]
> On second thought, I think it could be rather confusing if the arm can change the chosen bracing here, so the doc heuristic should be good enough imo

That's why I proposed to only decide on one, either by:
1. taking the one of the first arm
2. taking the predominant one, i.e., if there are two arms with `[]` and one with `()` use `[]`
3. only change the delimiter if all arms use the same delimiter
