### ISSUE TITLE
How to adjust max line length for formatting?

### ISSUE THREAD

**Issue by tim-ufer** [rust-lang/rust-analyzer#15617]
I've been using rust-analyzer with the helix editor which work well together but I can't find any options for adjusting the hard-wrap threshold when formatting my files with rust-analyzer. I tried various editor-based settings but they only effect soft-wrapping the view, not the file itself.
Is there some hidden config option I missed in the manual or should this become a feature request?

**Comment by lnicola** [comment]
Create a `rustfmt.toml` file, set https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=width#max_width, then enable "format on save" in your editor.

**Comment by tim-ufer** [comment]
> Create a `rustfmt.toml` file, set https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=width#max_width ~, then enable "format on save" in your editor~.

Thank you, that solved it!
