### ISSUE TITLE
#[cfg_attr(rust_analyzer, allow(dead_code))] does not work

### ISSUE THREAD

**Issue by smalis-msft** [rust-lang/rust-analyzer#15612]
**rust-analyzer version**: 0.3.1657-standalone (326f37ef1 2023-09-10

**rustc version**: rustc 1.72.0 (5680fa18f 2023-08-23)

Based on https://github.com/rust-lang/rust-analyzer/pull/15528 I assumed this would be possible. My code currently has a `rust_analyzer_fix` feature we've defined and been using for this purpose, and after trying to replace the feature with `cfg(rust_analyzer)` this was the only thing that didn't transition cleanly.

Repro code: 
lib.rs:
```rust
#[cfg_attr(rust_analyzer, allow(dead_code))]
fn foo() {}
```

What I see:
![image](https://github.com/rust-lang/rust-analyzer/assets/137308034/accc283b-645e-4773-93ae-755587ed6448)

**Comment by Veykril** [comment]
that diagnostic comes from rustc, `rust_analyzer` is not set for `cargo checks` we invoke though, its only set for r-a's own analysis

**Comment by smalis-msft** [comment]
Should it be set? This is a lint ultimately being surfaced by rust-analyzer. As a user I don't particularly care about the mechanism, only that I've asked rust-analyzer to disable this lint and it isn't. Feels weird to me.

**Comment by Veykril** [comment]
r-a invoking cargo check yields the same results as what you get when invoking it manually which is what I would expect. Additionally, if we were to set the cfg for the cargo invocation that would ultimately cause rebuilds whenever you have r-a invoke checks and you building your project yourself.

**Comment by flodiebold** [comment]
Maybe this shows that adding the `rust_analyzer` cfg was a bad idea in the first place :grimacing: But the main intention, I think, for the cfg was to be able to configure out parts of the code for RA's own analysis. It's not a general "when looking at code in the IDE" toggle.

**Comment by smalis-msft** [comment]
Personally I feel like changing `cfg(feature = "rust_analyzer_fix")` (with said feature enabled in the r-a config) to `cfg(rust_analyzer)` should be equivalent, and in this case it isn't. I understand why, and our feature works perfectly fine for us for now so we're not unable to use r-a or anything, but it's unfortunate that there's this discrepancy.

**Comment by Veykril** [comment]
> Maybe this shows that adding the `rust_analyzer` cfg was a bad idea in the first place 😬 But the main intention, I think, for the cfg was to be able to configure out parts of the code for RA's own analysis. It's not a general "when looking at code in the IDE" toggle.

I was very reluctant to add it in general because it felt like a bad idea, but it's kind of required because of how bad r-a works in certain scenarios currently... My idea was for it to always be an escape hatch really.

> Personally I feel like changing `cfg(feature = "rust_analyzer_fix")` (with said feature enabled in the r-a config) to `cfg(rust_analyzer)` should be equivalent, and in this case it isn't. I understand why, and our feature works perfectly fine for us for now so we're not unable to use r-a or anything, but it's unfortunate that there's this discrepancy.

If they were equivalent then there would be no point in even having `rust_analyzer` as a default cfg in the first place. The entire idea behind it was to only exist for r-a's analysis.
