### ISSUE TITLE
Unhelpful message when not using value from a loop break

### ISSUE THREAD

**Issue by not-holar** [rust-lang/rust-analyzer#15622]
```rust
loop {
    break Some(1);
}
```
Rust-analyzer underlines `Some(1)` in angry squigglies and says
 ```
  mismatched types
  expected unit type `()`
          found enum `Option<{integer}>`
 ```
It might not be too hard to figure what the issue is in such a simple example as the above, but when you have multiple levels of nesting with complex layered types, this can quickly become a source of frustration as it sends you on a chase of misdirection

It instead saying something along the lines of
 ```
  loop value is never used so break
  expected unit type `()`
          found enum `Option<{integer}>`
 ```
would be much more helpful

---

**rust-analyzer version**: 0.3.1657-standalone (326f37ef1 2023-09-10)
**rustc version**: 1.72.0 (5680fa18f 2023-08-23)
**relevant settings**: all default

**Comment by not-holar** [comment]
is this the correct place to report or should i instead go to rust directly?

**Comment by Veykril** [comment]
Given the `{integer}` I assume this is a rustc diagnostic that r-a renders inline so you probably want to report that in rust-lang/rust.
