### ISSUE TITLE
Missing Auto Completion / IntelliSense for from_utf8() on str

### ISSUE THREAD

**Issue by Zercerium** [rust-lang/rust-analyzer#15629]
```rust
use std::str;
fn main() {
   str:: //no auto completion for from_utf8()
   std::str:: //auto completion works
}
```
no auto completion / IntelliSense for `from_utf8()` for example

**rust-analyzer version**: 0.4.1663-standalone

**rustc version**: rustc 1.72.0 (5680fa18f 2023-08-23)

**Comment by lnicola** [comment]
This is now working:

![image](https://github.com/user-attachments/assets/39bf9931-dff7-4ce3-80e2-045d50b92c5f)
