### ISSUE TITLE
`request handler panicked: Can't find MACRO_CALL@90..97 in AstIdMap`

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust-analyzer#15634]
In this code

```rs
struct Foo;

macro_rules! Fooo {
    () => { Foo }
}

trait Trait<T> {
    type Ty: Trait<T>;
}

impl Trait<Fooo!()> for () {
    // <<--- “Implement missing members”
}

fn main() {
    println!("Hello, world!");
}
```
I’m executing `Implement missing members` quick fix at the location indicated.

Error message:
```
request handler panicked: Can't find MACRO_CALL@90..97 in AstIdMap:
[SyntaxNodePtr { kind: STRUCT, range: 0..11 }, SyntaxNodePtr { kind: MACRO_RULES, range: 13..52 }, SyntaxNodePtr { kind: TRAIT, range: 54..95 }, SyntaxNodePtr { kind: IMPL, range: 97..132 }, SyntaxNodePtr { kind: FN, range: 134..178 }, SyntaxNodePtr { kind: TYPE_ALIAS, range: 75..93 }, SyntaxNodePtr { kind: MACRO_CALL, range: 108..115 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 144..178 }, SyntaxNodePtr { kind: MACRO_CALL, range: 150..175 }]
```

---

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
```
rust-analyzer version: 0.3.1665-standalone
```

**rustc version**: (eg. output of `rustc -V`)
```
rustc 1.74.0-nightly (65ea825f4 2023-09-18)
```

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
_(I don’t think these are relevant)_

**Comment by Veykril** [comment]
probably similar issue to https://github.com/rust-lang/rust-analyzer/issues/10388 (we really need a type hir mapping, otherwise this will keep happening wth type macros i reckon)
