### ISSUE TITLE
Selecting `*x` in `&mut *x` to `Extract into variable` causes semantic differences before and after the operation

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust-analyzer#15638]
```rust
fn main() {
    let mut n = 2;
    let refm_1 = &mut n;
    let refm_1_new = &mut *refm_1; // borrow `refm_1` to `refm_1_new`
    *refm_1_new += 1;
    assert_eq!(n, 3);

    // Extract into variable `*refm_1`
    let mut n = 2;
    let refm_1 = &mut n;
    let mut var_name = *refm_1; // copy
    let refm_1_new = &mut var_name; // ref mut copied
    *refm_1_new += 1;
    assert_eq!(n, 2);
    assert_eq!(var_name, 3);
}
```

**rust-analyzer version**: `rust-analyzer 1.72.0-nightly (fe7454bf 2023-06-19)`

**rustc version**: `rustc 1.72.0-nightly (fe7454bf4 2023-06-19)`

**relevant settings**: NO_SETTINGS

**Comment by Veykril** [comment]
What would be the expected outcome here? The only other thing we could is turn it into the following instead:
```rs
    let mut n = 2;
    let refm_1 = &mut n;
    let mut var_name = &mut *refm_1;
    let refm_1_new = &mut *var_name;
   // ...
 ```
 I suppose?

**Comment by A4-Tacks** [comment]
> What would be the expected outcome here? The only option here is to turn it into the following instead:
> 
> ```rust
>     let mut n = 2;
>     let refm_1 = &mut n;
>     let mut var_name = &mut *refm_1;
>     let refm_1_new = &mut *var_name;
>    // ...
> ```
> 
> I suppose?.

Can the analyzer prompt an error when operating here? Because it seems unreasonable to operate here

**Comment by Veykril** [comment]
What's the benefit of disallowing this here? Maybe you want to extract it and then modify the extracted part for some reason. `Extract into variable` strikes me as an assist that should always be applicable for expressions.
