### ISSUE TITLE
A feature-toggle in the Rust plugin for VSCode

### ISSUE THREAD

**Issue by WUST-mengqinyu** [rust-lang/rust-analyzer#15643]
Similar to what JetBrains' Rust plugin provides
<img width="196" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/45025194/7bf89d0e-7aa3-4b5b-b531-57aace2686eb">

**Comment by itsyaasir** [comment]
Hey, I actually needed this feature as well and I decided to make a separate [vscode extension](https://github.com/itsyaasir/rust-feature-toggle) for this. I hope the rust-analyzer team can implement this but in the meantime, this can be helpful.
