### ISSUE TITLE
Small bug with semantic highlighting in vscode

### ISSUE THREAD

**Issue by ghashy** [rust-lang/rust-analyzer#15640]
**rust-analyzer version**: 0.3.1665

**rustc version**: 1.72.1 (d5c2e9c34 2023-09-13)

Hello! I found a small bug with semantic highlight in vscode. In my theme there are white variables and light-green types. When I added a macro before function, the function's return type lost it's right color. I inspected editor's tokens and scopes and figured out that with macro token of return type changes from `enum` to `variable`:

https://github.com/rust-lang/rust-analyzer/assets/109857267/3f2536c4-7a37-43ad-a305-7d26af2eda2b

Return type token without macro:
<img width="687" alt="Screenshot 2023-09-20 at 18 36 09" src="https://github.com/rust-lang/rust-analyzer/assets/109857267/dcce875e-b771-4bb1-a622-a09262334503">

Return type token with macro:
<img width="827" alt="Screenshot 2023-09-20 at 18 36 33" src="https://github.com/rust-lang/rust-analyzer/assets/109857267/e058c5d8-6a3b-49b7-8008-3a7884005d8b">

**Comment by Veykril** [comment]
This is expected if you are re-using the spans for other tokens in the expansion
