### ISSUE TITLE
No definition found for `identifier` when referenced from module located in function

### ISSUE THREAD

**Issue by AndreySmirnov81** [rust-lang/rust-analyzer#15654]
After `Go to Definition`

![изображение](https://github.com/rust-lang/rust-analyzer/assets/19325847/3700e071-3c6d-4e7c-a7a0-86d845803d08)

rust-analyzer 0.3.1665
VS Code 1.82.2
rustc 1.72.0

**Comment by lnicola** [comment]
Fixed by #16679
