### ISSUE TITLE
Completions for macros in `#[macro_use(...)]` of extern crate/mod declaration

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15657]
```rs
#[macro_use($0)]
extern crate foo;
```
we should be completing the exported macros of the `foo` crate here.
Likewise for modules
```rs
#[macro_use($0)]
mod foo;
#[macro_use($0)]
mod bar { ... }
```

**Comment by Veykril** [comment]
(assigned to myself to reserve for euro-rust's impl room tomorrow)
We'll have to add a new arm to the match here https://github.com/rust-lang/rust-analyzer/blob/8a2331450a2fa269aa60818b224a2beaef7d7198/crates/ide-completion/src/completions/attribute.rs#L49-L70
and create a corresponding submodule in `crates/ide-completion/src/completions/attribute/macro_use.rs`.

Then we'll need to figure out what the attribute we are completing in is actually attached to. For that we need to add a new field here https://github.com/rust-lang/rust-analyzer/blob/8a2331450a2fa269aa60818b224a2beaef7d7198/crates/ide-completion/src/context.rs#L370-L374 of type [`ModuleDef`](https://github.com/rust-lang/rust-analyzer/blob/8a2331450a2fa269aa60818b224a2beaef7d7198/crates/hir/src/lib.rs#L275) and populate it here appropriately https://github.com/rust-lang/rust-analyzer/blob/8a2331450a2fa269aa60818b224a2beaef7d7198/crates/ide-completion/src/context/analysis.rs#L257-L262 

Then in the newly created completions module we'll have to check if the definition the attribute is attached to is a module or extern crate and fetch the exported macros for that from there.

**Comment by unexge** [comment]
Seems like arguments to `#[macro_use]` are not allowed for modules. This [fails](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b5a592b9c0224c462e22e7001f59db53):
```rust
#[macro_use(foo)] // <- error: arguments to `macro_use` are not allowed here
mod inner {
    macro_rules! foo {
        () => {};
    }
}

fn main() {}
```

We should just autocomplete if `#[macro_use]` is applied to `extern crate`
