### ISSUE TITLE
No definition found for `const` when referenced from match pattern by range

### ISSUE THREAD

**Issue by AndreySmirnov81** [rust-lang/rust-analyzer#15653]
After `Go to Definition`

![изображение](https://github.com/rust-lang/rust-analyzer/assets/19325847/080cd310-9c9a-4d22-80e9-f0b2dba65d5e)

**rust-analyzer version**: 0.3.1665-standalone (05666441b 2023-09-17)
**rustc version**: 1.72.0 (5680fa18f 2023-08-23)

**Comment by roife** [comment]
The node type of `A` in the pattern is `ast::Name` rather than `ast::NameRef`, so r-a does not consider `A` to be a use and does not look for its type. Can we distinguish whether a variable in a pattern is a use or a new binding?

**Comment by Veykril** [comment]
We already do https://github.com/rust-lang/rust-analyzer/blob/4ee0dbdc04dce735a048a7bb8005e7ab495592fe/crates/ide-db/src/defs.rs#L385-L387, range patterns are a bit weird though so we might not consider them for some reason in https://github.com/rust-lang/rust-analyzer/blob/4ee0dbdc04dce735a048a7bb8005e7ab495592fe/crates/ide-db/src/defs.rs#L409
