### ISSUE TITLE
Failed to load `Cargo.toml`in WSL

### ISSUE THREAD

**Issue by shevernitskiy** [rust-lang/rust-analyzer#15673]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) v0.3.1673 (in wsl)

**rustc version**: (eg. output of `rustc -V`)  1.72.1 (d5c2e9c34 2023-09-13)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

---

When I open project in WSL, rust-analyzer failed to load `Cargo.toml` with this output:
```sh
[ERROR rust_analyzer::config] failed to load linked project: project root must point to Cargo.toml or rust-project.json: /mnt/e/programming/rust/dfint-hook-rs/.\Cargo.toml
```
Project structure
<img width="196" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/28886342/68e946ed-d24e-46e9-831a-887c256886af">

The same project on win works fine, rust-analyzer found `Cargo.toml` successfully.

**Comment by Mr-Pine** [comment]
For anyone finding the issue later on:
The problem is that on Windows the `Cargo.toml` location is saved as `.\Cargo.tome` which isn't a valid path on Linux, removing the `.\` fixes it for Linux

**Comment by justinburrill** [comment]
Adding on to the previous comment, this can be changed under the local .vscode/settings.json:
{
  "rust-analyzer.linkedProjects": [
    "Cargo.toml"                        (not ".\Cargo.toml")
  ],
}
