### ISSUE TITLE
No case diagnostics for module names

### ISSUE THREAD

**Issue by AndreySmirnov81** [rust-lang/rust-analyzer#15678]
**rust-analyzer version**: 0.3.1673

**rustc version**: 1.72.0 (5680fa18f 2023-08-23)

**VS Code version**: 1.82.2

![изображение](https://github.com/rust-lang/rust-analyzer/assets/19325847/9d7543d3-07e7-4586-9e23-cfc900586e19)

**The result of `Quick Fix`:**
![изображение](https://github.com/rust-lang/rust-analyzer/assets/19325847/462f9253-4b5b-4f0f-becd-b4c49999b1e2)

**Comment by lnicola** [comment]
Try "Rename to Sss", the other one comes from `rustc`.

**Comment by AndreySmirnov81** [comment]
@lnicola 

For some reason, `Rename to ...` is not offered for modules.

![изображение](https://github.com/rust-lang/rust-analyzer/assets/19325847/93c15816-ecc6-477d-98db-f7bba48a164d)

Result:
![изображение](https://github.com/rust-lang/rust-analyzer/assets/19325847/2fa1b6b0-42a9-40d1-84fc-83e866531dd2)

**Comment by lnicola** [comment]
Yeah, that's a real bug.
