### ISSUE TITLE
Wrong "cannot mutate immutable variable `array` (E0384)"

### ISSUE THREAD

**Issue by xxshady** [rust-lang/rust-analyzer#15670]
**rust-analyzer version**: 0.4.1674-standalone (d3cc3bc00 2023-09-25)

**rustc version**: 1.72.0 (5680fa18f 2023-08-23)

rust-analyzer complains about "immutable variable", but rustc [compiles this code without issues](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cc8b0dc5315b9bc75d6caa9e5faa85d4)

<img src="https://github.com/rust-lang/rust-analyzer/assets/54737754/bdb74f8d-e192-4772-8ff0-e069542080dc" width="400px"/>

However this doesnt cause any issues:

<img src="https://github.com/rust-lang/rust-analyzer/assets/54737754/330ffeb3-fc5b-49ef-a700-25ced3a9ff12" width="400px"/>

**Comment by xxshady** [comment]
Probably related to https://github.com/rust-lang/rust-analyzer/issues/14463 and https://github.com/rust-lang/rust-analyzer/issues/14612

**Comment by HKalbasi** [comment]
Can't reproduce this. Does it happen in a standalone project? Also your playground link is empty.

**Comment by lnicola** [comment]
Yeah, it doesn't even trigger for me on:

```rust
    fn repro<'a>(&'a self, idx: usize) {
        let array = &mut self.array;
        array[idx] = 1;
    }
```

**Comment by xxshady** [comment]
> Can't reproduce this. Does it happen in a standalone project? Also your playground link is empty.

Oh, I'm sorry: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cc8b0dc5315b9bc75d6caa9e5faa85d4

**Comment by lnicola** [comment]
Can't reproduce, does it still show up if you restart Code?

**Comment by xxshady** [comment]
I opened project where I reproduced it now I can't 😐

**Comment by xxshady** [comment]
rust-analyzer version: 0.4.1674-standalone (d3cc3bc00 2023-09-25)

**Comment by xxshady** [comment]
Same RA version

**Comment by xxshady** [comment]
I'm closing issue then xd

**Comment by xxshady** [comment]
First time I reproduced it after I opened this folder in vscode: https://github.com/rust-in-action/code/blob/25f2e2277cbd527ab8bf5e8b68a17672215874f3/ch5/ch5-cpu3

rust-analyzer showed errror on this line: https://github.com/rust-in-action/code/blob/19c4349758b57bdb233e186746bfec03ad9ea88d/ch5/ch5-cpu3/src/main.rs#L51

**Comment by lnicola** [comment]
Still can't reproduce. I opened just that directory.

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/8b21154d-c122-41af-8b46-bee9730c71a1)

I do get errors at the bottom of the file because of the syntax errors in `main`, but nothing else changes if I fix them.

**Comment by xxshady** [comment]
Then there is no issue xd

**Comment by lnicola** [comment]
Well, you seem to have one, but I have no idea why.

**Comment by xxshady** [comment]
> I opened project where I reproduced it and now I can't 😐

Sorry for confusion, I can't reproduce it anymore either

**Comment by xxshady** [comment]
Maybe it was caching issue or something like that

**Comment by lnicola** [comment]
If it happens again, take a look at the Output panel, there are two RA channels there. Maybe you'll find something.

**Comment by mati865** [comment]
I have encountered the same issue in some FFI code.
Reduced example:
![image](https://github.com/rust-lang/rust-analyzer/assets/1174646/a14d5f0b-04c2-45e1-8c06-a3eb526b90f3)

code:
```rust
pub struct A {}
pub unsafe fn foo(a: *mut A) {
    let b = || -> *mut A { &mut *a };
    let _ = b();
}
```
playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6ac27c26e10eb46113dc10e88d939c60

**Comment by lnicola** [comment]
This got closed by mistake, but feel free to open a new issue if needed, xxshady.
