### ISSUE TITLE
Import assist for traits on unresolved trait item should offer importing anonymously

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15684]
That is in the following case
```rs
// foo.rs
trait Foo {
    fn f(&self) {}
}
impl Foo for u32 {}
// main.rs
mod foo;
fn main() {
    0u32.foo$0();
}
```
We should show the general ``Import `crate::foo::Foo` `` as well as a ``Import `crate::foo::Foo as _` `` that imports the trait without bringing the name of it into scope.

**Comment by Veykril** [comment]
(assigned to myself to reserve for euro-rust's impl room tomorrow)
What needs to be done is roughly the following:

https://github.com/rust-lang/rust-analyzer/blob/8a2331450a2fa269aa60818b224a2beaef7d7198/crates/ide-assists/src/handlers/auto_import.rs#L91
Here we are fetching the `ImportAssets` which describe what kind of thing we want to import, it contains an `ImportCandidate` :
https://github.com/rust-lang/rust-analyzer/blob/8a2331450a2fa269aa60818b224a2beaef7d7198/crates/ide-db/src/imports/import_assets.rs#L26-L37

Leveraging that info we need to add additional import groups that will offer an `_` import here 
https://github.com/rust-lang/rust-analyzer/blob/8a2331450a2fa269aa60818b224a2beaef7d7198/crates/ide-assists/src/handlers/auto_import.rs#L129-L146

To able to add the `as _` part to the inserted use item, we need to modify the `insert_use` function and have it set the rename component appropriately here https://github.com/rust-lang/rust-analyzer/blob/8a2331450a2fa269aa60818b224a2beaef7d7198/crates/ide-db/src/imports/insert_use.rs#L177-L179

It's probably easiest to split out the function into two, one for the previous behavior, one for the underscore behavior and then have those wrap a function that takes an extra param to not having to edit all the current call sites of the function.

**Comment by Young-Flash** [comment]
I'd like to have a try.

> It's probably easiest to split out the function into two, one for the previous behavior, one for the underscore behavior and then have those wrap a function that takes an extra param to not having to edit all the current call sites of the function.

But how could we have a new function with  an extra param without edit other call of `insert_use`? There's not something like  default param in Rust.

**Comment by Young-Flash** [comment]
> But how could we have a new function with an extra param without edit other call of insert_use? There's not something like default param in Rust.

oh maybe I got it.
```rust
pub fn insert_use(scope: &ImportScope, path: ast::Path, cfg: &InsertUseConfig) {
    insert_use_with_alias_option(scope, path, cfg, None);
}

pub fn insert_use_as_alias(scope: &ImportScope, path: ast::Path, cfg: &InsertUseConfig) {
    let alias = ...;
    insert_use_with_alias_option(scope, path, cfg, alias);
}

fn insert_use_with_alias_option(scope: &ImportScope, path: ast::Path, cfg: &InsertUseConfig, alias: Option<ast::Rename>)
```
