### ISSUE TITLE
Rust Analyzer Not Working in VSCode for Mac x86 with MacOS Sonoma 14.0

### ISSUE THREAD

**Issue by michaeld96** [rust-lang/rust-analyzer#15699]
Hi! 

I updated my Mac to the new OS, and went to write some more Rust code and I realized VSCode was not properly debugging files.

I kept getting 
```
Console is in 'commands' mode, prefix expressions with '?'.
Launching: /Users/user/Desktop/test/target/debug/test
Launched process 2219
Process exited with code -1.
```

My program is just a simple "hello world" just to see if I could isolate my problem.

I usually just hit `Debug` when Rust Analyzer is running. Like this 
<img width="154" alt="Screenshot 2023-10-02 at 12 08 43 AM" src="https://github.com/rust-lang/rust-analyzer/assets/44264982/127bcfd7-476e-4ba0-98db-ffc33922061d">

Now when I hit it, I keep getting this error. My code compiles, I've ran `cargo run` and `cargo test` and compile just fine.

Now, I notice that Rust Analyzer is this nasty color and it just says `Failed to spawn one or more proc-macro servers`.
<img width="141" alt="Screenshot 2023-10-01 at 11 28 36 PM" src="https://github.com/rust-lang/rust-analyzer/assets/44264982/b33543da-b082-4ba3-9f23-7263710065e9">

Things that I've tried:
* Reinstalling Rust.
* Reinstalling Rust Analyzer
* updated Xcode.
* Restarted VSCode and Computer

Any help would greatly be appreciated! 

```[tasklist]
### Tasks
```

**Comment by yurixander** [comment]
I can confirm; I am having the same problem under the same situation. The debug button is no longer working; I am getting the same debug console output as you. I am using Sonoma 14.0

**Comment by Veykril** [comment]
Is the hover not saying why server spawning failed? Can you go to a proc-macro / attribute invocation in your code and check if that is showing an error (as a diagnostic there)?

**Comment by michaeld96** [comment]
I hover over it in VSCode and it states `Failed to spawn one or more proc-macro servers`.

When I go to the Output tab, it has nothing on it. 
<img width="1435" alt="Screenshot 2023-10-02 at 8 35 56 AM" src="https://github.com/rust-lang/rust-analyzer/assets/44264982/fdd50a40-d92d-4d48-b2b7-49ef01bcb2eb">

I went t the proc-macro / attribute and there seems to be no error there. I included the screenshot below:
<img width="607" alt="Screenshot 2023-10-02 at 8 40 04 AM" src="https://github.com/rust-lang/rust-analyzer/assets/44264982/ef03d834-847d-4312-b139-443a39fdae9d">

Also, I tried to make a new Rust project wth just "Hello World!" and I am getting the same issue
<img width="1025" alt="Screenshot 2023-10-02 at 8 42 07 AM" src="https://github.com/rust-lang/rust-analyzer/assets/44264982/5000b5fb-3666-4b57-a7c4-188e9421322e">

**Comment by michaeld96** [comment]
I fixed the rust analyzer issue. I had two version of rust on my system, one from homebrew the other from rustup. Still cannot debug, but this seems to be a VSCode issue.

**Comment by michaeld96** [comment]
I am going to reopen this because when I try `rust-analyzer: Debug` I get the following:

<img width="1792" alt="Screenshot 2023-10-05 at 1 11 45 PM" src="https://github.com/rust-lang/rust-analyzer/assets/44264982/d6e631b1-c6b4-4421-8d38-a327e6384453">

I have built my project with `cargo build` and it runs successfully. 

```
/Users/michael/Desktop/teest/target
michael@Michaels-MacBook-Pro-100 target % ls
CACHEDIR.TAG    debug
```

So I am confused on why it cannot find a debug target?

**Comment by SomeoneToIgnore** [comment]
To notice, I use Sonoma and everything works for me:
![Screenshot 2023-10-06 at 11 36 03](https://github.com/rust-lang/rust-analyzer/assets/2690773/3694589b-f179-4c65-a41b-1e48d5888319)

so there has to be more details in the issue to make it actionable.
I use latest r-a nightly, CodeLLDB extension for the debugger support and regular `latest` rustc (1.73.0) coming from rustup.

**Comment by michaeld96** [comment]
I have noticed another thing, when I run the normal debugger, I am getting 
```
Warning: codelldb.cargo tasks are unavailable in the current environment.

Warning: codelldb.cargo tasks are unavailable in the current environment.
```
I did up on the message `Warning: codelldb.cargo tasks are unavailable in the current environment.` and people were saying to download Cargo by panicbit and this usually solved their issue, and it did not for me.

I have rustc 1.7.3, the newest version of rust-analyzer, and most up to date LLDB.

I haven't touched my configurations with VSCode, so that is why I am so confused.

**Comment by yurixander** [comment]
I am also still experiencing the same issue. I have rustc 1.73.0, pre-release version of rust-analyzer, and all extensions updated. I haven't gotten any warnings as far as I've noticed, however, only just debugging won't run and it exits with an error code just like you. It was working fine before upgrading to Sonoma, not sure what changed.

**Comment by michaeld96** [comment]
nice, that was my stackoverflow post too, haha!

**Comment by chinchaun** [comment]
this fixed my issue too

> I am also still experiencing the same issue. I have rustc 1.73.0, pre-release version of rust-analyzer, and all extensions updated. I haven't gotten any warnings as far as I've noticed, however, only just debugging won't run and it exits with an error code just like you. It was working fine before upgrading to Sonoma, not sure what changed.
> 
> I should also note that when I use lldb manually via the command line, it places breakpoints and runs correctly. Even if I install a fresh copy of visual studio code insiders, with just rust-analyzer and codelldb, the issue persists.
> 
> **Update**: After deleting `~/.vscode/extensions/vadimcn.vscode-lldb-1.10.0/lldb/bin/debugserver`, the issue seems to be resolved. It is now debugging properly. [(source)](https://stackoverflow.com/questions/77218022/why-is-my-debugger-in-vscode-not-working-with-rust-after-mac-update-to-sonoma-14)

**Comment by agatekartik** [comment]
> I am also still experiencing the same issue. I have rustc 1.73.0, pre-release version of rust-analyzer, and all extensions updated. I haven't gotten any warnings as far as I've noticed, however, only just debugging won't run and it exits with an error code just like you. It was working fine before upgrading to Sonoma, not sure what changed.
> 
> I should also note that when I use lldb manually via the command line, it places breakpoints and runs correctly. Even if I install a fresh copy of visual studio code insiders, with just rust-analyzer and codelldb, the issue persists.
> 
> **Update**: After deleting `~/.vscode/extensions/vadimcn.vscode-lldb-1.10.0/lldb/bin/debugserver`, the issue seems to be resolved. It is now debugging properly. [(source)](https://stackoverflow.com/questions/77218022/why-is-my-debugger-in-vscode-not-working-with-rust-after-mac-update-to-sonoma-14)

The answer worked for me too, thank you! :-)

An observation (now seemingly logical, in hindsight): the debugger worked fine if I was debugging remotely i.e. code on a linux box and remote debugging via Mac/VSCode/LLDB - only local Mac src code always resulted in the above symptom
