### ISSUE TITLE
rust-analyzer cannot be used when using ssh

### ISSUE THREAD

**Issue by xiaocijun** [rust-lang/rust-analyzer#15716]
On vscode, when using ssh to connect to  docker, macros cannot be completed.(img:ubuntu20.4)
When using ssh to connect to ubuntu18.04-wsl2, all instructions cannot be completed.
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.73.0 (cc66ad468 2023-10-03)
**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
[ERROR rust_analyzer::config] failed to find any projects in [AbsPathBuf("/home/xiaoci")]
[ERROR rust_analyzer::main_loop] FetchWorkspaceError:
rust-analyzer failed to discover workspace
[ERROR rust_analyzer::main_loop] FetchWorkspaceError:
rust-analyzer failed to discover workspace

**Comment by xiaocijun** [comment]
I have solved this problem, please refer to the   [LINK](https://github.com/rust-lang/rust-analyzer/assets/60111278/80fc53a2-93ac-4712-b3b3-20cc2c92c9d0)

**Comment by lnicola** [comment]
That sounds related to the way you're opening the project.

> [ERROR rust_analyzer::config] failed to find any projects in [AbsPathBuf("/home/xiaoci")]

Looks like you're opening your home directory. You should open the only project instead (the directory with `Cargo.toml`).

**Comment by xiaocijun** [comment]
> That sounds related to the way you're opening the project.
> 
> > [ERROR rust_analyzer::config] failed to find any projects in [AbsPathBuf("/home/xiaoci")]
> 
> Looks like you're opening your home directory. You should open the only project instead (the directory with `Cargo.toml`).

In ssh of vscode, it seems that there is no way to set the path. Is there any solution?
