### ISSUE TITLE
Constant crashes, enormous unintelligible errors

### ISSUE THREAD

**Issue by mattfbacon** [rust-lang/rust-analyzer#15717]
**rust-analyzer version**: rust-analyzer 1.72.1 (d5c2e9c 2023-09-13)

**rustc version**: rustc 1.72.1 (d5c2e9c34 2023-09-13)

**relevant settings**: I'm using neovim 0.9.2. My RA config is:

```lua
rustfmt = {
	extraArgs = { '+nightly' },
},
checkOnSave = {
	command = 'clippy',
	allTargets = true,
},
cargo = {
	features = 'all',
},
inlayHints = {
	bindingModeHints = { enable = true },
	closureReturnTypeHints = { enable = 'with_block' },
	lifetimeElisionHints = { enable = 'always' },
	reborrowHints = { enable = 'always' },
	typeHints = {
		hideClosureInitialization = true,
	},
},
```

The crash contents are in this gist (extracted from Neovim LSP log): https://gist.github.com/mattfbacon/7db63d707cdfdc6192aae4f406c9d41a

**Comment by mattfbacon** [comment]
Still broken on neovim 0.9.4, rust-analyzer 1.73.0 (cc66ad4 2023-10-03), rustc 1.73.0 (cc66ad468 2023-10-03)

**Comment by Veykril** [comment]
That's https://github.com/rust-lang/rust-analyzer/issues/5366
