### ISSUE TITLE
Very limited autocomplete

### ISSUE THREAD

**Issue by rsalmei** [rust-lang/rust-analyzer#15711]
Hi,

Please, why is the autocomplete so very limited like this? Is this correct? Is this intended??

I want to autocomplete `Ipv6Addr`, I push `I` (upper i):
<img width="614" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/6652853/67b94d43-ba1d-4ad6-99b6-4d14637dc1a7">
Yep, there are only these 17 entries. I push `p`:
<img width="614" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/6652853/ff2720c0-8ec2-4fdb-bad9-f4499f09cd85">
Now there isn't any... I push `v`:
<img width="614" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/6652853/8043d7e4-84ef-46ab-a003-062da027225c">

Now it suddenly finds these two. It's very weird (and worrying, I must be missing A LOT of suggestions).
Why didn't these two entries come on the very first suggestions? They do contain upper I after all.
Why does `Ip` return nothing?
Is there some configuration I could change to get all the entries at once?

Thank you.

**rust-analyzer version**: rust-analyzer version: 0.3.1681-standalone (0840038f0 2023-09-30)
**rustc version**: rustc 1.72.0 (5680fa18f 2023-08-23)

**Comment by flodiebold** [comment]
Suggestions for names that aren't imported yet (that add a `use` statement) are only provided if there are at least three characters to match. Otherwise the completion list would get huge and slow.

**Comment by Veykril** [comment]
I wonder, we could maybe do mere prefix matching for importing completions with <3 characters? That should limit the completions pretty well and gives intuitive results I think?

**Comment by rsalmei** [comment]
> Suggestions for names that aren't imported yet (that add a `use` statement) are only provided if there are at least three characters to match. Otherwise the completion list would get huge and slow.

Thanks, I see.
But I wonder if that list would really be huge and slow... Jetbrains' Rust plugin does bring a huge list with a single upper I, and instantaneously, including the `Ipv6Addr`:
<img width="1004" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/6652853/1ee28a2d-18c4-4bbb-bcee-95d5945570b9">

**Comment by Veykril** [comment]
Ideally we'd do the same, but it's just not currently feasible with how do things.

**Comment by rsalmei** [comment]
May I ask why? Because they use Kotlin+Java, and we use Rust after all...
Anyway, this PR of yours will surely improve things a lot!! Thank you very much.

**Comment by Veykril** [comment]
Different architecture, having to align with the LSP and because our completions are currently just not very efficient

**Comment by rsalmei** [comment]
I see, it is not performance the problem. Thanks, man.

**Comment by rsalmei** [comment]
Please @Veykril, when is this going to be released?
It didn't make both the changelogs 202 and 203 already.
