### ISSUE TITLE
Cargo check runs continously preventing compiling of project

### ISSUE THREAD

**Issue by SudhirProg** [rust-lang/rust-analyzer#15723]
Type: <b>Bug</b>

Create a GTK4 project.
Create five modules to generate GUI for the project
rust-analyzer runs continuously and never ends, preventing the project from being built.
Does not affect small projects with just one source file.
Running build and run in terminal runs successfully.
This bug renders VS Code unusable.

Extension version: 0.3.1681
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (1.99GB free)|
|Process Argv|--crash-reporter-id 567a904d-1a66-4314-a0ef-9ca8c2f725dc|
|Screen Reader|no|
|VM|31%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30839829
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
pythonmhint1:30842940
dsvsc015:30845448

```

</details>

**Comment by lnicola** [comment]
Does it really run continuously, or does it recompile too much each time you save a file? Can you try running `cargo clean` with VS Code closed?

**Comment by SudhirProg** [comment]
I can confirm cargo check runs continuously. I have run cargo clean outside of VS Code and this still happens. Last night, I left ide for half an hour and cargo check was still running. I will run cargo clean again and then load it into VS Code. Does not happen if there is only one source file. Sudhir. On 7 Oct 2023 09:09, Laurențiu Nicola ***@***.***> wrote:
Does it really run continuously, or does it recompile too much each time you save a file? Can you try running cargo clean with VS Code closed?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
On 7 Oct 2023 09:09, Laurențiu Nicola ***@***.***> wrote:
Does it really run continuously, or does it recompile too much each time you save a file? Can you try running cargo clean with VS Code closed?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
On 7 Oct 2023 09:09, Laurențiu Nicola ***@***.***> wrote:
Does it really run continuously, or does it recompile too much each time you save a file? Can you try running cargo clean with VS Code closed?

**Comment by SudhirProg** [comment]
Sadly, I have run cargo clean with VS Code closed and the problem persists. I now find it impractical to use VS Code for developing applications and have to rely on Rust Rover until this is fixed.

**Comment by SudhirProg** [comment]
Will this be addressed as VS Code is unusable for Rust development? I have to use Rust Rover instead.

**Comment by SudhirProg** [comment]
Cargo check runs continuously even if the check on save is disabled. I have now given up on using VS Code for developing Rust as Rust Rover is fast superior. Very disappointing this issue cannot be solved. Please close this issue as I am no longer tracking it.
