### ISSUE TITLE
auto-publishing runs out of disk space

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#15732]
https://github.com/rust-lang/rust-analyzer/actions/runs/6452854701/attempts/1

I think `cargo workspaces publish` rebuilds common dependencies for each published crate.

**Comment by Veykril** [comment]
Could be due to difference in `default` features (of dependencies) being enabled for the crates maybe?

**Comment by Veykril** [comment]
Though why is this happening now? 🤔

**Comment by lnicola** [comment]
It's been happening for a couple of weeks now, I think since we added `rustc-dependencies`.

**Comment by lnicola** [comment]
Actually, no, it might be since earlier. I'm not sure.

> Could be due to difference in default features (of dependencies) being enabled for the crates maybe?

That would only rebuild some of the crates. Look for "Compiling libc" in [this log](https://github.com/rust-lang/rust-analyzer/actions/runs/6376505483/job/17303615950) to see what I mean. As if it's building them independently, outside the workspace.

**Comment by pksunkara** [comment]
I haven't checked this deeply, but wouldn't `cargo publish` command always compile freshly? or am I misunderstanding how it works?

**Comment by lnicola** [comment]
To be honest, I have no idea.

**Comment by pksunkara** [comment]
Looks like yes, it does. https://github.com/rust-lang/cargo/issues/4109

**Comment by lnicola** [comment]
Ah, good find. Then I guess we can close #137?

**Comment by pksunkara** [comment]
> Error: The operation was canceled.

I see the above error message in the run you started. Any reason why it was assumed to be related to disk space?

I see that `timeout-minutes` is not specified for the workflow, so it can't be that.

**Comment by lnicola** [comment]
Oh yeah, I just cancelled it so we don't publish anything today. But you can see in the logs that a lot of crates have been built multiple times.

**Comment by lnicola** [comment]
Worked around in #15783: https://github.com/rust-lang/rust-analyzer/actions/runs/6577778965/job/17870142380.
