### ISSUE TITLE
rustfmt dosen't work

### ISSUE THREAD

**Issue by shanliangdeYWJ** [rust-lang/rust-analyzer#15738]
rust-analyser: v0.3.1689
vscode: v1.83.0

rustc:1.74.0
cargo:1.74.0

system: mac m1 v12.5

Problem description:
I installed these software, configured. argo/bin and. argo/env, and then opened rusdlings using vscode. I configured the format to use rust-analyzer and saved the active format. After modifying the code, I pressed cmd+s, but there was no formatting. I don't know why, what should I do?

**Comment by Veykril** [comment]
Did you run the rustlings setup? There is a step described in the repo that needs to be run when intending to use rust-analyzer

**Comment by shanliangdeYWJ** [comment]
> Did you run the rustlings setup? There is a step described in the repo that needs to be run when intending to use rust-analyzer

I run it:

```
./.devcontainer/setup.sh
```

And then it seems that after downloading rustlings and formatting it, it still hasn't worked

**Comment by mo8it** [comment]
You should manually run `rustlings lsp` for older Rustlings versions for the language server to work and provide formatting.

This is not needed in the new version 6 of Rustlings. The language server works out of the box.

The issue can be closed :)
