### ISSUE TITLE
The hint that marks the unused mut got bad when features using.

### ISSUE THREAD

**Issue by pointertobios** [rust-lang/rust-analyzer#15750]
As this image:
![img](https://github.com/rust-lang/rust-analyzer/assets/84652600/fef05b0f-ff10-458c-838c-f5c3cedbe13a)
The mut ref is used in this feature, but it still hints `warning: variable does not need to be mutable`.

**Comment by lnicola** [comment]
The warning is correct. You need to set `"rust-analyzer.cargo.features": ["sample"]` or `"rust-analyzer.cargo.features": "all"` for that line to exist.  Even the compiler will warn there otherwise.

**Comment by pointertobios** [comment]
I did have set this option

**Comment by lnicola** [comment]
![image](https://github.com/rust-lang/rust-analyzer/assets/308347/90507326-84ed-4c82-90a9-457ccca21065)

Can't reproduce, not even with `rust-analyzer.checkOnSave` enabled. Are you seeing `rustc`'s version of the warning, or ours? They have the same message, but one says `rustc` and the other says `rust-analyzer(unused_mut)`. And did you set `rust-analyzer.check.overrideCommand`?

**Comment by pointertobios** [comment]
Thank you so much. After editing overrideCommand it disappeared.

**Comment by lnicola** [comment]
But you shouldn't need to edit `overrideCommand`, unless you already had it set before. If you had it set in order to use Clippy, you can do set `"rust-analyzer.check.command": "clippy"` instead.

**Comment by pointertobios** [comment]
Thank you, I set it correctly now.
