### ISSUE TITLE
explain negative memory usage of RA

### ISSUE THREAD

**Issue by Eason0729** [rust-lang/rust-analyzer#15759]
I am trying to find problem that prevent root scan from ending.

And I try the first button(memory usage) below.

![image](https://github.com/rust-lang/rust-analyzer/assets/30045503/7b213706-c8bc-4a62-91d5-c6e006a95329)
<details open>
<summary>Output</summary>
<pre>
Per-query memory usage:
    20mb   1459 FileTextQuery
  1323kb      1 CrateGraphQuery
   601kb    144 SourceRootQuery
   214kb   1459 FileSourceRootQuery
    97kb      0 ConstEvalQuery
    96kb      0 TargetDataLayoutQuery
    96kb      0 InherentImplsInCrateQuery
    95kb      0 BorrowckQuery
    95kb      0 InternTraitAliasQuery
    64kb      0 InternTypeOrConstParamIdQuery
    64kb      0 FunctionDataQuery
    64kb      0 InferQueryQuery
    64kb      0 MirBodyQuery
    64kb      0 ConstEvalDiscriminantQuery
    64kb      0 UnionDataQuery
    64kb      0 CrateLangItemsQuery
    64kb      0 FieldVisibilitiesQuery
    64kb      0 InternMacro2Query
    63kb      0 ProcMacroDataQuery
    63kb      0 CrateSupportsNoStdQuery
    63kb      0 ImplDatumQuery
    42kb      1 ProcMacrosQuery
    35kb      0 ParseMacroExpansionQuery
    32kb      0 ValueTyQuery
    32kb      1 LibraryRootsQuery
    32kb      0 InternTraitQuery
    32kb      0 VariantsAttrsSourceMapQuery
    32kb      0 LangItemQuery
    32kb      0 TyQuery
    32kb      0 GenericDefaultsQuery
    32kb      0 TraitSolveQueryQuery
    32kb      0 FileItemTreeQuery
    32kb      0 TypeAliasDataQuery
    32kb      0 Macro2DataQuery
    32kb      0 FunctionVisibilityQuery
    32kb      0 ImplSelfTyQuery
    32kb      0 InternImplQuery
    32kb      0 InternBlockQuery
    32kb      0 InternProcMacroQuery
    31kb      1 LocalRootsQuery
    31kb      0 HygieneFrameQuery
    31kb      0 UnionDataWithDiagnosticsQuery
    31kb      0 CallableItemSignatureQuery
    31kb      0 ReturnTypeImplTraitsQuery
    31kb      0 InternUnionQuery
    31kb      0 InternConstQuery
   1040b      0 ParseQuery
    864b      0 InternMacroRulesQuery
    832b      0 BodyWithSourceMapQuery
    816b      0 DeclMacroExpanderQuery
     16b      0 ProgramClausesForChalkEnvQuery
      0b      0 SourceRootCratesQuery
      0b      0 MacroArgNodeQuery
      0b      0 EnumDataQuery
      0b      0 EnumDataWithDiagnosticsQuery
      0b      0 ImplDataQuery
      0b      0 ImplDataWithDiagnosticsQuery
      0b      0 TraitDataWithDiagnosticsQuery
      0b      0 TraitAliasDataQuery
      0b      0 ConstDataQuery
      0b      0 StaticDataQuery
      0b      0 BodyQuery
      0b      0 GenericParamsQuery
      0b      0 VariantsAttrsQuery
      0b      0 FieldsAttrsQuery
      0b      0 ImplTraitQuery
      0b      0 GenericPredicatesForParamQuery
      0b      0 TraitEnvironmentQuery
      0b      0 TraitImplsInCrateQuery
      0b      0 TraitImplsInBlockQuery
      0b      0 TraitImplsInDepsQuery
      0b      0 FnDefDatumQuery
      0b      0 FnDefVarianceQuery
      0b      0 AdtVarianceQuery
      0b      0 ModuleSymbolsQuery
      0b      0 LineIndexQuery
      0b      0 InternEnumQuery
      0b      0 InternExternBlockQuery
    -16b      0 InherentImplsInBlockQuery
   -816b      0 ExpandProcMacroQuery
   -816b      0 StructDataQuery
   -816b      0 InternClosureQuery
   -832b      0 CrateDefMapQueryQuery
   -832b      0 BlockDefMapQuery
   -832b      0 StructDataWithDiagnosticsQuery
   -832b      0 FieldTypesQuery
   -832b      0 LayoutOfAdtQuery
   -848b      0 MacroRulesDataQuery
   -848b      0 GenericPredicatesQuery
   -912b      0 InternFunctionQuery
   -28kb      0 MacroExpandQuery
   -31kb      0 InternStructQuery
   -31kb      0 InternTypeAliasQuery
   -31kb      0 ExprScopesQuery
   -31kb      0 InternStaticQuery
   -32kb      0 ConstParamTyQuery
   -32kb      0 AssociatedTyDataQuery
   -32kb      0 TraitDataQuery
   -32kb      0 InternGeneratorQuery
   -32kb      0 TraitDatumQuery
   -32kb      0 AssociatedTyValueQuery
   -32kb      0 StructDatumQuery
   -32kb      0 IncoherentInherentImplCratesQuery
   -32kb      0 InternCallableDefQuery
   -63kb      0 LibrarySymbolsQuery
   -63kb      0 AstIdMapQuery
   -63kb      0 InternMacroCallQuery
   -64kb      0 InternLifetimeParamIdQuery
   -64kb      0 InternImplTraitIdQuery
   -64kb      0 AttrsQuery
   -95kb      0 ConstVisibilityQuery
   -95kb      0 FieldsAttrsSourceMapQuery
  -127kb      0 ImportMapQuery
  2266mb        Remaining

(note: database has been cleared)
</pre>
</detail>

rust-analyzer version: 0.3.1689-standalone

```bash
❯ rustc -V
rustc 1.73.0 (cc66ad468 2023-10-03)
```

How can memory usage be negative?

Is that related to my problem that prevent root scan from ending?

**Comment by Eason0729** [comment]
<details>
<summary> another output</summary>
<pre>
Per-query memory usage:
    79mb  30608 FileItemTreeQuery
    76mb  10940 HygieneFrameQuery
    65mb   4891 FileTextQuery
    54mb  28142 MacroArgNodeQuery
    52mb    133 CrateDefMapQueryQuery
    31mb  76995 AttrsQuery
    16mb  30635 AstIdMapQuery
    13mb  39027 ImplDataWithDiagnosticsQuery
    12mb  45968 GenericParamsQuery
    12mb  39026 ImplTraitQuery
    12mb   2649 ParseQuery
    12mb  28146 ParseMacroExpansionQuery
     7mb  28146 MacroExpandQuery
     7mb  68484 InternFunctionQuery
     7mb  39026 ImplSelfTyQuery
     6mb    596 DeclMacroExpanderQuery
     5mb  31489 InternMacroCallQuery
     5mb  40801 InternImplQuery
     5mb  39027 ImplDataQuery
  3651kb    125 TraitImplsInCrateQuery
  2684kb    141 ExpandProcMacroQuery
  1973kb      1 CrateGraphQuery
  1835kb   6915 GenericDefaultsQuery
  1538kb      0 InternLifetimeParamIdQuery
  1324kb   8329 InternTypeAliasQuery
  1046kb   5803 TyQuery
   425kb     12 CrateLangItemsQuery
   332kb      1 InternCallableDefQuery
   245kb   1168 InternTraitQuery
   179kb    242 InternStaticQuery
   163kb    155 GenericPredicatesForParamQuery
   162kb      0 InferQueryQuery
   160kb    361 BodyQuery
   148kb    997 InternMacroRulesQuery
    63kb      1 InternTraitAliasQuery
    61kb     27 InternProcMacroQuery
    58kb      0 TraitImplsInDepsQuery
    54kb      7 GenericPredicatesQuery
    41kb      0 FnDefVarianceQuery
    40kb    346 InternBlockQuery
    38kb     95 InternExternBlockQuery
    25kb      0 InternImplTraitIdQuery
    25kb      0 IncoherentInherentImplCratesQuery
   1760b      0 MirBodyQuery
  -1328b      0 CrateSupportsNoStdQuery
   -11kb      0 InherentImplsInCrateQuery
   -11kb      1 TraitEnvironmentQuery
   -21kb      1 LibraryRootsQuery
   -22kb     45 InternMacro2Query
   -32kb      0 InherentImplsInBlockQuery
   -37kb      0 TraitImplsInBlockQuery
   -56kb    926 InternEnumQuery
   -57kb      0 ConstVisibilityQuery
   -65kb      0 LibrarySymbolsQuery
   -68kb  16345 InternConstQuery
   -86kb     24 LangItemQuery
   -87kb      0 BorrowckQuery
   -95kb      0 FunctionVisibilityQuery
  -116kb      0 ConstEvalDiscriminantQuery
  -163kb      0 InternTypeOrConstParamIdQuery
  -193kb      0 FieldsAttrsQuery
  -194kb      4 TraitDatumQuery
  -196kb      0 InternClosureQuery
  -203kb      0 ImportMapQuery
  -222kb      0 ProgramClausesForChalkEnvQuery
  -234kb    165 VariantsAttrsQuery
  -269kb      1 ExprScopesQuery
  -272kb      0 VariantsAttrsSourceMapQuery
  -322kb      0 AssociatedTyValueQuery
  -367kb      1 ProcMacrosQuery
  -387kb    142 SourceRootQuery
  -507kb      0 ConstEvalQuery
  -569kb      0 AssociatedTyDataQuery
  -611kb      5 TraitSolveQueryQuery
  -643kb      0 FieldVisibilitiesQuery
  -738kb      0 FnDefDatumQuery
  -876kb      0 AdtVarianceQuery
  -980kb     43 InternUnionQuery
 -1062kb      1 StructDatumQuery
 -1104kb      0 FieldsAttrsSourceMapQuery
 -1151kb      1 LineIndexQuery
 -1422kb   6158 InternStructQuery
 -1625kb   4891 FileSourceRootQuery
 -1678kb      0 ImplDatumQuery
 -1701kb      2 ValueTyQuery
 -1714kb      0 InternGeneratorQuery
 -1778kb      0 ModuleSymbolsQuery
 -1861kb    361 BodyWithSourceMapQuery
 -1992kb      0 UnionDataQuery
 -2001kb      0 UnionDataWithDiagnosticsQuery
 -2032kb      2 SourceRootCratesQuery
 -2099kb      1 LocalRootsQuery
 -2163kb      0 ConstDataQuery
 -2337kb      0 StaticDataQuery
 -2339kb      0 TraitAliasDataQuery
 -2622kb    604 ConstParamTyQuery
 -2629kb      0 StructDataWithDiagnosticsQuery
 -2915kb      0 StructDataQuery
 -3072kb    346 BlockDefMapQuery
 -3634kb    362 TraitDataWithDiagnosticsQuery
 -3730kb    201 EnumDataQuery
 -3781kb    201 EnumDataWithDiagnosticsQuery
 -3930kb      0 ProcMacroDataQuery
 -3997kb      2 FunctionDataQuery
    -4mb      0 MacroRulesDataQuery
    -4mb     76 TypeAliasDataQuery
    -4mb    362 TraitDataQuery
    -4mb      0 Macro2DataQuery
   -32mb      9 TargetDataLayoutQuery
   -36mb      1 ReturnTypeImplTraitsQuery
   -36mb      0 LayoutOfAdtQuery
   -37mb      0 CallableItemSignatureQuery
   -38mb      0 FieldTypesQuery
  1364mb        Remaining

(note: database has been cleared)
</pre>
</details>

**Comment by Veykril** [comment]
I assume you are on windows in which case this is expected. Windows doesn't really allow us to measure memory nicely so it sometimes reports a memory increase when freeing query storages. We should probably put a note to the output for windows builts, the command really only works on non windows r-a binaries.

**Comment by Eason0729** [comment]
I am on Fedora 38, so I believe it's not the case.

**Comment by Veykril** [comment]
Well, could be that Fedora doesn't let one query memory usage too well either in that case. We rely on `mallinfo2` on linux systems unless r-a is compiled with jemalloc.

**Comment by lnicola** [comment]
I don't think it's specific to Fedora. I remember running into this on Arch, but there's nothing special about them.

I don't get the same output, but I can make it show negative usage for some queries by running Memory Usage twice in a row.

**Comment by Eason0729** [comment]
Thanks, I get it (it probably unrelated to the problem I am trying to work out) and I will close this issue.
