### ISSUE TITLE
Dynamic File Inclusions in Microsoft's crate

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust-analyzer#15768]
## 📝 **Overview**

Hi,

Many people are facing this issue with other IDEs / extensions for Rust and I have used the same template to report here. Note that I am using latest version of `rust-anaylzer` from `vscode` plugin store and latest version of Rust from official website on Windows 11 latest version and I have tried on various Windows builds.

While venturing into Windows kernel development, I've hit a snag with rust-analyzer. It seems to be having a hard time recognizing certain imports from the `wdk-sys` crate. Digging deeper, I've pinpointed the potential culprits:

- The dynamic inclusion `include!(concat!(env!("OUT_DIR"), "/ntddk.rs"));` in [ntddk.rs](https://github.com/microsoft/windows-drivers-rs/blob/main/crates/wdk-sys/src/ntddk.rs).
  
- The similar inclusion `include!(concat!(env!("OUT_DIR"), "/types.rs"));` in [types.rs](https://github.com/microsoft/windows-drivers-rs/blob/main/crates/wdk-sys/src/types.rs).

These dynamic file inclusions seem to be tripping up rust-analyzer.

## 🎯 **What I Expected**

I anticipated rust-analyzer to seamlessly suggest and detect all the imports from `wdk-sys` as I delve into Windows kernel code.

## 🚫 **Reality Check**

A good portion of the `wdk-sys` imports remain elusive. This forces a manual intervention, making the coding process less smooth.

## 🔄 **Reproduction Steps**

1. Initiate a new Rust project targeting Windows kernel development.
2. Try importing various modules or functions from `wdk-sys`.
3. Realize the lack of many suggestions or detections by rust-analyzer.

## 💡 **Insights**

The `include!` method used by `wdk-sys` for including generated files might be the stumbling block. A tweak in rust-analyzer's parsing logic might better cater to such dynamic inclusions.

## 💌 **A Quick Note**

Kudos to the rust-analyzer team for their stellar work. This minor oversight doesn't diminish the tool's overall excellence.

**Warm regards**,

**Comment by lnicola** [comment]
Do those files happen to be very, very large?

**Comment by Juggle4247** [comment]
Yes, they are very large as far as I can see.

**Comment by lnicola** [comment]
Can you try this?

https://github.com/rust-lang/rust-analyzer/issues/15335#issuecomment-1650343862

**Comment by lnicola** [comment]
Hi. The JetBrains issue is unrelated, since their implementation is completely different from rust-analyzer.

I installed the WDK, but the crate doesn't seem to find it, probably because I don't have the SDK installed. I tried to install the SDK, but it hangs at 11% with "Acquiring Windows SDK for [something]", without doing any network transfer.

In the meanwhile, do you have a small sample showing the problem? My memory of the WDK is... rusty.

**Comment by lnicola** [comment]
Hey @Juggle4247, there's a new nightly coming up in about 10 minutes, would you mind giving it a try?
