### ISSUE TITLE
`replace_is_method_with_if_let_method` should reuse binding or function name instead of `_tmp`

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#15765]
It might be nice to convert `if foo.is_some()` to `if let Some(foo) = foo` and `if foo().is_some()` to `if let Some(foo) = foo()`. If the seems weird, I think it makes more sense for methods.

CC @Young-Flash

**Comment by Young-Flash** [comment]
> Functionality for that already exists here fwiw https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-assists/src/utils/suggest_name.rs

`suggest_name::for_variable()` apply over `foo.is_some()` and `foo().is_some()` will get `var_name` and `foo`, the former isn't expectation but the latter is. here want the former be `foo` too, is there a existing api to check whether a `Expr` is variable(`foo`)? 

If it's a variable, we can use [receiver](https://github.com/rust-lang/rust-analyzer/blob/6572ec8d94c83f8cc6afe0069269abeddc37c25e/crates/ide-assists/src/handlers/replace_is_method_with_if_let_method.rs#L37) directly, if not, we apply `suggest_name::for_variable()` over the `Expr`.

**Comment by Young-Flash** [comment]
tried match [receiver](https://github.com/rust-lang/rust-analyzer/blob/6572ec8d94c83f8cc6afe0069269abeddc37c25e/crates/ide-assists/src/handlers/replace_is_method_with_if_let_method.rs#L37) to get a proper variable name with the following:
```rust
let var_name = if let ast::Expr::PathExpr(path_expr) = receiver.clone() {
    path_expr.path()?.to_string()
}
else {
    suggest_name::for_variable(&receiver, &ctx.sema)
};
```
for both `foo.is_some()` and `foo().is_some()` we can get the expectation result. I will make a PR next if this is ok.
