### ISSUE TITLE
variable arguments in println! macro are not indexed

### ISSUE THREAD

**Issue by yjlcoder** [rust-lang/rust-analyzer#15777]
**rust-analyzer version**: v0.3.1697

**rustc version**: 1.68.2 (9eb3afe9e 2023-03-27)

**relevant settings**: default settings

I'm aware of #11296 and #11503, but this is a different issue.

In the latest version, variable arguments in `println!` macro are not indexed or referenced.

![Screenshot from 2023-10-17 20-17-09](https://github.com/rust-lang/rust-analyzer/assets/14989893/1746efe2-c62f-490a-83fe-aebdbd000f9a)

It works previously. The last working version is 0.3.1649-standalone.

![Screenshot from 2023-10-17 20-18-26](https://github.com/rust-lang/rust-analyzer/assets/14989893/844b5f63-fa05-4f13-bc37-d93155af9eef)

**Comment by Veykril** [comment]
Hmm, this still works fine for me?

**Comment by lnicola** [comment]
@yjlcoder I don't know which change could have caused this, but I suggest staying on the older version if you can't upgrade to a newer toolchain. We don't support versions that old.

**Comment by yjlcoder** [comment]
I updated rust version to latest and it works fine now. Tysm for the help!
