### ISSUE TITLE
Please update rust-analyzer in rust-lang/rust

### ISSUE THREAD

**Issue by gigaroby** [rust-lang/rust-analyzer#15776]
Hi,
we (at Google) are building the rust toolchain (`rust-lang/rust`) and its components in a custom way (https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds?branch=master). I am currently trying to get rust-analyzer to build but I ran into an issue with the `ra-ap-...` crates. It seems like a feature recently landed to allow us to build rust-analyzer fully in-tree (https://github.com/rust-lang/rust-analyzer/commit/f4704bc8ae92d150b2801e391692d9503f0c6126) but this hasn't made its way into `rust-lang/rust`.

Would it be possible to sync the rust-analyzer version in rust-lang/rust to that in rust-lang/rust-analyzer? I'm happy to do this myself but I haven't figured out how this is done.

**Comment by lnicola** [comment]
There's currently a problem related to publishing the `ra-ap_` crates, but I'll have a fix tomorrow or so.

Regarding the sync, last time I tried it didn't work for some reasons we didn't understand. I'll try again soon.

**Comment by gigaroby** [comment]
Hi @lnicola, any updates to share? I am happy to help if there's anything I can do.

**Comment by hlopko** [comment]
Fantastic, thank you for pushing this forward!

**Comment by lnicola** [comment]
With https://github.com/rust-lang/rust/pull/117985, the subtree is currently up-to-date. Thank you for your patience.

**Comment by hlopko** [comment]
Thank you so much @lnicola!
