### ISSUE TITLE
Local doc open doesn't directly link to methods

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust-analyzer#15773]
main.rs
```rust
/// A foo struct
pub struct Foo;

impl Foo {
    /// A bar function
    pub fn bar(&self) {

    }
}

fn main() {
    let f = Foo;
    // |
    // V
    f.bar();
}

```
Right clicking on `bar` in `f.bar()` and selecting "Open docs" opens `struct.Foo.html`, and not `struct.Foo.html#method.bar`.
Opening remote docs.rs docs doesn't have this problem.

**rust-analyzer version**: 0.3.1697-standalone

**rustc version**: rustc 1.75.0-nightly (42b1224e9 2023-10-15)

**Comment by EliasHolzmann** [comment]
Works for me (rust-analyzer version: 0.4.1718-standalone, rustc version: rustc 1.75.0-nightly (a2f5f9691 2023-11-02)).

I guess your behavior is somehow environment related – I tested with Firefox (119) as well as Chromium (119 as well, as luck would have it), it works perfectly well on both browsers for me. However, I'm on Arch Linux – are you on another distribution or Mac/Windows?

**Comment by crumblingstatue** [comment]
I'm using Arch Linux as well, with Firefox 119.
I can still reproduce it.
However, I'm using the OSS version of VSCode, which still only has RA `0.3.1713-standalone`, which might be a factor.

**Comment by EliasHolzmann** [comment]
Hmm... I tested on vscodium 1.75.1 (yes, I should probably upgrade that...) and run the pre-release version of rust-analyzer (`0.3.1713-standalone` is the current release version). However, I get the same behavior with VSCode 1.84.0 (installed via the [`code`](https://archlinux.org/packages/extra/x86_64/code/) package) running `0.3.1713-standalone`... That's the same setup you use, I believe.

I'm currently out of ideas. Would you be willing to debug this on your machine? If yes:
1. Clone this repo
2. Open it in vscode
3. To install dependencies:
   ```bash
   $ cd editors/code
   $ npm ci
   ```
4. Open `editors/code/src/commands.ts` and set a breakpoint on line 953 (directly after `const doclinks = ...`)
5. Open the "Run and Debug" sidebar, select "Run Extension (Debug Build)" and hit the Run button
6. Grab yourself a coffee or something – this rebuilds the Rust side too, so it takes a few minutes. (There is also the Run Configuration "Run Installed Extension" which should rebuild the extension only while using the installed language server, but I wasn't able to get that working).
7. When the build is done, a second vscode window with "[Extension Development Host]" in the title bar should open.
8. Open your example file, wait for rust-analyzer to initialize, and select "Open docs" on `bar`. The breakpoint should be triggered.
9. Inspect the contents of the local variable `doclinks` – does `doclinks.local` end with `#method.bar` (like `doclinks.web` does)?

**Comment by crumblingstatue** [comment]
It indeed ends with `#method.bar`.
My guess is it's vscode's `openExternal` that doesn't work correctly.
I tried using `xdg-open` directly, and it indeed ignores `#` fragments for local files.
It could be that `openExternal` is using `xdg-open` on my system.

**Comment by crumblingstatue** [comment]
Yes, it's indeed using `xdg-open`.
Looks like the `generic_open` function of `xdg-open` removes `#` fragments somehow.
I'm going to close this, as it's not a bug with rust-analyzer.

**Comment by crumblingstatue** [comment]
I (half-jokingly) [made a xdg-open replacement in Rust](https://github.com/crumblingstatue/rusty-open) to solve this problem for myself.
