### ISSUE TITLE
`impl<T: Deref<Target = impl Trait>>`

### ISSUE THREAD

**Issue by cavemanloverboy** [rust-lang/rust-analyzer#15772]
```
rust-analyzer version: 0.4.1696-standalone (6572ec8d9 2023-10-15)
rustc 1.73.0 (cc66ad468 2023-10-03)
```

It seems any use of an `impl<T: Deref<Target = impl Trait>>` on some struct does not show methods even when using an appropriate `T`. Consider the following minimal repro:
```rust
use std::ops::Deref;

fn main() {
    let foo: Foo<&u8> = Foo::new(&42_u8);
    foo.foobar();
    foo.baz();
}

trait Bar {
    fn bar(&self);
}
impl Bar for u8 {
    fn bar(&self) {}
}

struct Foo<F> {
    foo: F,
}

impl<F> Foo<F> {
    fn new(foo: F) -> Foo<F> {
        Foo { foo }
    }
    fn baz(&self) {}
}

impl<F: Deref<Target = impl Bar>> Foo<F> {
    fn foobar(&self) {
        self.foo.deref().bar()
    }
}
```

This compiles [(playground link)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8796dd9df3fde5b673e6b17602ea1cda). However, the method list I see does not include `foobar`, despite the bounds being satisfied.
<img width="589" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/93507302/7d85847e-0f79-43ca-a78e-35e992978650">

**Comment by Austaras** [comment]
A symmetry example
```rs
use std::ops::Deref;

fn main() {
    let foo: Foo<&u8> = Foo::new(&42_u8);
    foo.foobar();
    foo.baz();
}

trait Bar {
    fn bar(&self);
}
// impl Bar for u8 {
//    fn bar(&self) {}
// }

struct Foo<F> {
    foo: F,
}

impl<F> Foo<F> {
    fn new(foo: F) -> Foo<F> {
        Foo { foo }
    }
    fn baz(&self) {}
}

impl<B: Bar, F: Deref<Target = B>> Foo<F> {
    fn foobar(&self) {
        self.foo.deref().bar()
    }
}
```
Despite `u8` doesn't impl `Bar`, `foobar` still appears in completion list.
