### ISSUE TITLE
ThreadIntent in thread pool for XNU kernal

### ISSUE THREAD

**Issue by Kangaxx-0** [rust-lang/rust-analyzer#15774]
For me, the `ThreadIntent` is implemented for XNU only, and this infra does not work for other platforms, is this a correct understanding, or I do miss some contexts :)

**Comment by lnicola** [comment]
I think it's correct according to [this](https://github.com/rust-lang/rust-analyzer/blob/master/crates/stdx/src/thread/intent.rs). Windows also has an API, but it's not implemented. I don't think Linux does.
