### ISSUE TITLE
find references doesn't see through destructuring

### ISSUE THREAD

**Issue by tamird** [rust-lang/rust-analyzer#15781]
Consider this strawman:
```rust
struct Foo {
  a: usize,
  b: usize,
}

impl Foo {
  fn mutate(&mut self) {
    let Self { a, b } = self;
    *a += *b;
  }
}
```
"find references" through `a` on the struct doesn't find `a` in `*a += *b`.

**Comment by HKalbasi** [comment]
I think the current behavior is correct and the `a` in `*a += *b` is another independent local variable with the same name as field. Should find reference show `x` in this example?

```Rust
  struct Foo {
    a: usize,
    b: usize,
  }
  
  impl Foo {
    fn mutate(&mut self) {
      let Self { a: x, b: y } = self;
      *x += *y;
    }
  }
```

**Comment by tamird** [comment]
I agree that it's a separate variable. However I also think find reference *should* show `x` in your example; that would make the feature much more useful in code that destructures.

Perhaps this isn't appropriate for find reference and there's another way to find these cases - I don't know enough about LSP to say.

**Comment by Veykril** [comment]
To clarify, the issue is about 
```rs
struct Foo {
  a: usize,
  b: usize,
}

impl Foo {
  fn mutate(&mut self) {
    let Self { a, b } = self;
             // ^ cursor on this a only shows references to the field
    *a += *b;
  }
}
```
right? In which case I agree, if the cursor is on the field of the destructure we should show references to both the field as well as the local being introduced here. It already works the same for constructor shorthands as in `let this = Self { a/* cursor on this a shows fields and the variable being referenced*/, b }`.

**Comment by Veykril** [comment]
Never replied to this, sorry. Anyways, this works as expected as far as I am concerned, the `a` in you `*a` expression is a local variable, a separate entity than the `a` field.
