### ISSUE TITLE
Highlight usages of `static mut` as unsafe

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust-analyzer#15797]
Rust analyzer allows clients to color unsafe operations differently, by adding a tag to the corresponding unsafe tokens (sorry, I don't know the proper lingo). Usages of `mut` statics are currently not highlighted, even though they require `unsafe`.

**Comment by Veykril** [comment]
Don't we already do this? Both the def and use here is marked unsafe for me 
![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/1f977286-04b1-4c2a-8a64-703683b2a718)

Although in code I don't quite grasp where we do this for path accesses, so there is probably some cases we are missing?

**Comment by WaffleLapkin** [comment]
Doesn't seem to work for me:

![2023-11-12_16-57](https://github.com/rust-lang/rust-analyzer/assets/38225716/4fec725f-19ce-48ab-bfa1-cb7eb3a161b8)

But maybe that's an issue with my theme? (rust-analyzer version: 0.4.1728-standalone (5fcf5289e 2023-11-11), theme: matklad.pale-fire v0.4.28)

**Comment by Veykril** [comment]
You can inspect the tags of a token with the `Inspect Editor Tokens And Scopes` command
![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/33920fc0-1e12-4267-b9a4-7b246e573531)
![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/9927e088-0329-4f42-a480-10dd1da3662e)
If it has the given mods there then it might be your theme

**Comment by Veykril** [comment]
Note that modifier rules are not additive, so having a rule that is `*.unsafe` and a `*.mutable` will not necessarily apply both unfortunately which is problably your problem here (hence why my theme has these combinations here https://github.com/Veykril/MuPanda/blob/cd3559e5b2bc0b8c5383d4e781d3adb0b5c1469d/src/languages/rust.yaml#L28-L38)

**Comment by WaffleLapkin** [comment]
Yes, both declaration and usage have `unsafe` modifier, sorry for bothering 😅 

I would also expect `mut` to have the modifier (it's what makes the static unsafe to use after all), but that's more debatable and is not related to the issue here, so I'll close this :)
