### ISSUE TITLE
`diagnostics.disabled` doesn't seem to work

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust-analyzer#15792]
I suspect this has to do with mapping RA's own diagnostics to rustc diagnostics. I've tried adding `no-such-field` / `no_such_field` and `E0559` to `"rust-analyzer.diagnostics.disabled"` but still I run into #14265 (a bug with that diagnostic).

**rust-analyzer version**: 0.4.1704-standalone
**rustc version**: 1.74.0-beta.1 (b5c050feb 2023-10-03)
**relevant settings**: 

```
"rust-analyzer.diagnostics.disabled": [
    "E0559",
    "no_such_field",
    "no-such-field",
    //"type-mismatch",
    //"unused-mut",
],
```

**Comment by jplatte** [comment]
Oh, I found it out! I had a project-specific config that still used the old names. Sorry for the noise. I think the manual could make it clearer that `EXXX` style names are expected nowadays (previous configs just became no-ops when the mapping was added), but at least I don't don't annoyed by these errors anymore. Thanks!

**Comment by lnicola** [comment]
At least in Code, you can see the code next to the error. I don't think anyone knows the codes by heart :slightly_smiling_face:.
