### ISSUE TITLE
Thousands of ripgrep processes crashing VSCode on cargo build

### ISSUE THREAD

**Issue by bconnorwhite** [rust-lang/rust-analyzer#15794]
Running `cargo build` in a separate terminal (or sometimes even just saving a file in VSCode) seems to spawn thousands of ripgrep processes in a loop until VSCode crashes.

If VSCode isn't  open, running `cargo build` / `cargo check` has no issue - CPU usage goes back to 1% once the command completes.

**rust-analyzer version**: 0.3.1705-standalone (10872952c 2023-10-22)

**rustc version**: rustc 1.73.0 (cc66ad468 2023-10-03)

**VSCode version**: Version: 1.83.1

**Comment by lnicola** [comment]
We do not run or use `ripgrep`. VS Code uses it internally for "Find in files".

**Comment by bconnorwhite** [comment]
Interesting, disabling rust-analyzer seems to fix the problem, I'll do some more testing

**Comment by lnicola** [comment]
We use the client-side file watching and I can imagine Code spawning ripgrep to enumerate the files in the project, but you're going to have to investigate this on your side.

Do you have a build script creating thousands of files? Does it happen in every project? Anything special about your disk?

**Comment by bconnorwhite** [comment]
Adding `**/target/**` seems to fix the issue so far
