### ISSUE TITLE
Arrays as struct members causes panic

### ISSUE THREAD

**Issue by nathansizemore** [rust-lang/rust-analyzer#15804]
Example file
```rust
const MAX_ONE_BYTE_PICTURE_ID: i16 = 0x7F; // 7 bits
const MAX_TWO_BYTE_PICTURE_ID: i16 = 0x7FFF; // 15 bits
const NO_SPATIAL_IDX: u8 = 0xFF;
const NO_GOF_IDX: u8 = 0xFF;
const NUM_VP9_BUFFERS: u8 = 8;
const MAX_VP9_REF_PICS: usize = 3;
const MAX_VP9_FRAMES_IN_GOF: usize = 0xFF; // 8 bits
const MAX_VP9_NUMBER_OF_SPATIAL_LAYERS: usize = 8;

const MIN_VP9_SPATIAL_LAYER_LONG_SIDE_LENGTH: usize = 240;
const MIN_VP9_SPATIAL_LAYER_SHORT_SIDE_LENGTH: usize = 135;

pub struct Gof {
    pub num_frames_in_gof: usize,
    pub temporal_idx: [u8; MAX_VP9_FRAMES_IN_GOF],
    pub temporal_up_switch: [bool; MAX_VP9_FRAMES_IN_GOF],
    pub num_ref_pics: [u8; MAX_VP9_FRAMES_IN_GOF],
    pub pid_diff: [[u8; MAX_VP9_REF_PICS]; MAX_VP9_FRAMES_IN_GOF],
    pub pid_start: u16,
}
```

ra version: 2023-10-23
rustc: rustc 1.73.0 (cc66ad468 2023-10-03)
Pop_OS, Emacs

Hovering a cursor anywhere over the array literals breaks the LSP.:

```
Saving file /home/nate/dev/icarus/lib/webrtc/src/video/codecs/vp9/gof.rs...
LSP :: No formatting changes provided
Wrote /home/nate/dev/icarus/lib/webrtc/src/video/codecs/vp9/gof.rs
LSP :: Error from the Language Server: request handler panicked: Can't find CONST_ARG@158..159 in AstIdMap:
[SyntaxNodePtr { kind: USE, range: 153..192 }, SyntaxNodePtr { kind: USE, range: 193..218 }, ...truncated, but should get the point across
lsp-request: request handler panicked: Can’t find CONST_ARG@158..159 in AstIdMap:
```

**Comment by AndreySmirnov81** [comment]
The following simple example is sufficient to reproduce the problem:
```rust
struct T {
    arr: [u8; 16],
}
```
rust-analyzer version: 0.3.1705-standalone (10872952c 2023-10-22)
rustc 1.72.0 (5680fa18f 2023-08-23)

**Comment by HKalbasi** [comment]
I can't reproduce this. Is it reproducible in an empty project on vscode?

**Comment by lnicola** [comment]
I can reproduce it in an empty project. There is a `CONST_ARG` in the AST, but `@25..27`, while the panic messages is about `@156..157`. No macros involved.

**Comment by nathansizemore** [comment]
> I can't reproduce this. Is it reproducible in an empty project on vscode?

Yes, can also do it in VS Code with a blank scratch proj:

![image](https://github.com/rust-lang/rust-analyzer/assets/3423825/be1fcc74-9a0e-4971-8649-4c5bbacd8389)

**Comment by MarSik** [comment]
I believe I hit the same issue: https://github.com/rust-lang/rust-analyzer/issues/15968

**Comment by evertedsphere** [comment]
Same here in Emacs + rust-analyzer.

**Comment by Veykril** [comment]
I can't reproduce this

**Comment by roife** [comment]
Hey, I have locally identified and resolved the bug. The issue stems from an error transformation in the generate_delegate_trait with PathTransform, similar to #14534, but for some unknown reasons, it cannot be reliably reproduced.

Upon investigating generate_delegate_trait, I found numerous implementation issues with code actions, such as lack of support for generic structs and incorrect handling of the Self type. To address these issues, I have rewritten the entire code action and am currently addressing the final few issues. I may submit a pull request within the next day or two.
