### ISSUE TITLE
"request handler panicked" error on "Convert boolean to enum" assist

### ISSUE THREAD

**Issue by ronnodas** [rust-lang/rust-analyzer#15807]
Trying the "Convert boolean to enum" assist on the following code produces the error "request handler panicked: can't resolve local ptr to SyntaxNode: SyntaxNodePtr { kind: NAME_REF, range: 62..69 }":
```rust
struct Struct {
    boolean: bool,
}

fn boolean(x: Struct) {
    let Struct { boolean } = x;
}

fn new_vec() -> Vec<Struct> {
    vec![Struct { boolean: true }]
}
```
I minimized it as much as I could.

**rust-analyzer version**: 0.3.1705-standalone

**rustc version**: rustc 1.73.0 (cc66ad468 2023-10-03)

**relevant settings**: nothing obviously relevant

**Comment by lnicola** [comment]
We're probably mixing the original file with the expansion of `vec!`.

**Comment by rmehri01** [comment]
I was looking through the other assists and also found these similar cases:

`Inline into all callers`
```rust
struct Foo;

fn $0foo() -> Foo {
    Foo
}

fn bar() -> Vec<Foo> {
    let Foo = foo();
    vec![foo()]
}
```

`Promote local to const`
```rust
fn baz() -> Vec<usize> {
    let $0foo = 2;
    vec![foo]
}
```

Should we be attempting to handle these cases as well (by inlining into the macro) or should we just skip over them to avoid panics?
