### ISSUE TITLE
Match check usefulness index out of bounds

### ISSUE THREAD

**Issue by l4l** [rust-lang/rust-analyzer#15808]
**rust-analyzer version**: rust-analyzer 1 (862a3004e9 2023-09-24)
**rustc version**: 1.72.1 (d5c2e9c34 2023-09-13)
**relevant settings**: nothing special
**editor**: helix 23.05

At the editing encountered panic at hir diagnostic:

> thread 'Worker' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/hir-ty/src/diagnostics/match_check/usefulness.rs:371:9

preceded with the following message:

> [ERROR hir_ty::diagnostics::match_check::deconstruct_pat] trying to compare incompatible constructors Single and IntRange(IntRange { range: 1..=1 })

The code doesn't compiles, though syntax check passes. Unfortunately I'm unable to share the code, nor figure out where MRE. The multi-line stacktrace is shrunk by the editor logger, so I'm only able get `stack backtrace:\n` :face_exhaling:

**Comment by l4l** [comment]
I guess the problem happens there:

https://github.com/rust-lang/rust-analyzer/blob/46c395d57090f2ec5784d7fcad57a130911e44f7/crates/hir-ty/src/diagnostics/match_check/usefulness.rs#L431-L441

and probably is_covered_by at least should return false for that case

**Comment by Veykril** [comment]
Do you happen to have an example code snippet that triggers this?

**Comment by iDawer** [comment]
The error says that a pattern's type is not the same as it should be in a matched type. Such type mismatches should had  the whole match check ruled out earlier but on this case it somehow left undetected. Also the error hints that the affecting `match` expression might involve boolean pattern `true`.

@l4l Reproducible example would greatly help here. 
Some basic instructions of extracting the affecting `match` expression could be:
 1) Having the affecting file backed up somehow;
 2) Inside that file, start by halving the content off (bisect) or by removing function bodies until the expression is found.
 3) Extract the expression into it's own function with an input argument of type of it's scrutinee expression.
 4) Strip off items that do not affect reproducibility while checking it still reproduces.
 5) Remove contents of the `match`'s arms.
 5) Include unpublished dependency types used in the expression. Their fields aren't necessary if not matched against.
 6) Rename things you feel can't be published.

**Comment by Veykril** [comment]
Note a similar panic being reported here https://github.com/rust-lang/rust-analyzer/issues/15883

**Comment by Veykril** [comment]
Closing as non-reproducible
