### ISSUE TITLE
Duplicate "remove unnecessary parentheses" code action

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust-analyzer#15801]
```rs
if (true) {}
```

![image](https://github.com/rust-lang/rust-analyzer/assets/47633543/90f89d70-3a64-4067-ae19-acc1d4d162eb)

**rust-analyzer version**: 2023-10-16                                 
**rustc version**: rustc 1.73.0 (cc66ad468 2023-10-03)

**Comment by omertuc** [comment]
One of them is a code assist that rust-analyzer is generating out of the output of a compiler warning (run `cargo check` and you'll see the string "remove *these* parentheses in the warning), rust-analyzer knows how to turn these compiler suggestions into code assists), the other is coming from a built-in rust-analyzer assist to remove parenthesis.

The rust-analyzer one is even broken in some cases:

```rust
fn main() {
    match(true) {}
}
```

Becomes:

```rust
fn main() {
    matchtrue {}
}
```

Which is of-course invalid.

Maybe getting rid of the built-in rust-analyzer assist would be a better idea than trying to fix it?

**Comment by lnicola** [comment]
The built-in diagnostic works on-the-fly, without saving the file. Why should we get rid of it?

**Comment by omertuc** [comment]
Good point, haven't thought of that, thought it was simply redundant

**Comment by omertuc** [comment]
Created a ticket #15844 to address the issue I mentioned
