### ISSUE TITLE
How to silence: Unnecessary braces in use statement 

### ISSUE THREAD

**Issue by NotGovernor** [rust-lang/rust-analyzer#15811]
I'd like to disable this lint:

```
use crate::{ thing::otherthing };
```
Gives a message: `Unnecessary braces in use statement`

I tried using `#![allow(unused_import_braces)]` but it doesn't seem to work for this even though the docs here say it should:

https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unused-import-braces

What am I missing?

**Comment by lnicola** [comment]
You can add it to `rust-analyzer.diagnostics.disabled`.

**Comment by NotGovernor** [comment]
Thanks! I'll do that.

For those reading along you can add `unused_braces` to the setting `rust-analyzer.diagnostics.disabled` to disable this lint.

Though it might still be a good idea for someone with time to take a look at that `#![allow(unused_import_braces)]` issue...
