### ISSUE TITLE
RA fails to compute stack size of HashMap / HashSet

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust-analyzer#15829]
When hovering over a field or type name, I usually get size and align information in VSCode. However, this doesn't work for `HashMap` or types that contain a `HashMap` field.

**rust-analyzer version**: 0.4.1718-standalone
**rustc version**: 1.74.0-beta.1 (b5c050feb 2023-10-03)

**Comment by lnicola** [comment]
This is probably #7637.

**Comment by jplatte** [comment]
Ah, dang. Sounds complicated 😕
