### ISSUE TITLE
Rust Analyzer is only partially working with Esp32 projects on Neovim

### ISSUE THREAD

**Issue by yanshay** [rust-lang/rust-analyzer#15828]
I'm using Neovim (based on LazyVim) for Rust development and with standard projects everything work properly including Rust Analyzer.

When I work with Esp-Idf embedded projects Rust Analyzer is only partially working:
1. Syntax errors are shown
2. Completion work as well
3. But some errors don't show, for example, in the below code it doesn't show that tt() function is missing. However, it is colored red (signaling there is an error), and if I try to use code action to fix the issue (that I know exists) it knows to suggest adding the function.
```
fn main() {
    esp_idf_svc::sys::link_patches();

    esp_idf_svc::log::EspLogger::initialize_default();

    log::info!("Hello, world!");
    tt();
}
```
If I run cargo check from command line I get the proper error message.

Any ideas what could cause this and/or how can I troubleshoot it?

**Comment by Veykril** [comment]
We don't have diagnostics for name resolution yet, so the red highlighting is the most we do.

**Comment by yanshay** [comment]
> We don't have diagnostics for name resolution yet, so the red highlighting is the most we do.

Not sure I follow - on standard rust, that `tt()` showed up as error in `Neovim`. I assumed that's from rust-analyzer (since that's what's configured in `lsp`). With `esp` it didn't.
It ended up being some dependency that existed in `Cargo.toml`, once I removed it things turned back to working properly.

**Comment by Veykril** [comment]
Oh sorry I misunderstood, so r-a isn't running / outputting cargo check diagnostics. Given your reply, this seems to be https://github.com/rust-lang/rust-analyzer/issues/15647 that you were running into.
