### ISSUE TITLE
Enable analysis of code behind cfg directives

### ISSUE THREAD

**Issue by adrianbrink** [rust-lang/rust-analyzer#15824]
<img width="528" alt="Screenshot 2023-11-02 at 15 23 56" src="https://github.com/rust-lang/rust-analyzer/assets/11320251/7170adec-2a16-4bad-8f22-7dc57062b23b">

Currently this is grayed out and I would like to enable it. However it is unclear how to achieve that.

I've tried to do it via cfgs like described [here](https://users.rust-lang.org/t/how-to-enable-cfgs-in-rust-analyzer/97753). However no one describes how to disable the `dev` flag. 

I've also tried to do it via enabling all features described [here](https://github.com/rust-lang/rust-analyzer/issues/1822). However that flag has been removed.

I've also tried to enable a specific feature via the `features` key described [here](https://rust-analyzer.github.io/manual.html).
```
    "rust-analyzer.cargo.features": [
        "default",
        "!dev"
    ],
```
. However the syntax for disabling `dev` is again completely unclear to me.

This seems like a trivial issue, however I can't find a single stackoverflow thread that describes how to disable a `not feature`. Everyone always explained how to enable a feature, but not how to do the opposite.

Any help would be appreciated.

**Comment by lnicola** [comment]
Is `dev` included in your `default-features`?

**Comment by adrianbrink** [comment]
```
[features]
default = ["std", "abciplus"]
mainnet = [
  "namada/mainnet",
]
dev = ["namada/dev"]
std = ["ed25519-consensus/std", "rand/std", "rand_core/std", "namada/std", "namada_sdk/std"]
# for integration tests and test utilies
testing = ["dev", "namada_test_utils"]

abciplus = [
    "namada/abciplus",
    "namada/tendermint-rpc",
]
```

The entire file is [here](https://github.com/anoma/namada/blob/main/apps/Cargo.toml)

**Comment by lnicola** [comment]
It's probably because `tests` and `benches` enable `namada_apps/testing`. I don't think we can offer more flexibility here.

**Comment by adrianbrink** [comment]
I'm okay with disabling `tests` and `benches`. How would I disable those and disable `dev`?

**Comment by lnicola** [comment]
This is enough:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/eb53d7b8-7718-4719-ae8b-1829c8da7409)

`dev` will be automatically disabled once you do that.

**Comment by adrianbrink** [comment]
But this is what is currently in the files. Should I delete `features = ["testing"]`?

**Comment by lnicola** [comment]
Yeah, sorry, red means deleted in that screenshot.

**Comment by adrianbrink** [comment]
Excluding them works as well, but that causes unrelated html problems. 

Thank you very much :-)
