### ISSUE TITLE
Misleading command name `> rust-analyzer: Expand macro recursively`

### ISSUE THREAD

**Issue by loynoir** [rust-lang/rust-analyzer#15856]
### actual

As far as I found,

- The command name is misleading `> rust-analyzer: Expand macro recursively`

I understand it as expand full file.

### expected

- command name `> rust-analyzer: Expand macro recursively at cursor`

**Comment by lnicola** [comment]
Expanding the full file would be called `Expand macros recursively`.

**Comment by Veykril** [comment]
This command doesnt expand all macros in the current file, but only the one under the cursor (recursively), so this is labeled correctly

**Comment by loynoir** [comment]
I know.

I suggest, add two words `at cursor` to command display name. 

Zero ambiguity.

**Comment by Veykril** [comment]
Fair, I agree we can change it to `Expand macro at cursor recursively` that seems like an improvement.
