### ISSUE TITLE
Cannot infer `OUT_DIR` when workspace root contains symlink

### ISSUE THREAD

**Issue by wasd96040501** [rust-lang/rust-analyzer#15867]
https://github.com/rust-lang/rust-analyzer/blob/11a87c917943dac5a568579f799c2d7458324103/crates/project-model/src/build_scripts.rs#L260-L269

In line 264, because package id from cargo metadata(used by workspace) is different from cargo check(used by build scripts) when root contains symlink. We will "ignore" these package id so that `OUT_DIR` will not be set.

And I will make a PR to fix this.

**Comment by Veykril** [comment]
I don't quite understand the problem here, but isn't this an issue with either `cargo metadata` or `cargo check` then? If they report differing paths here that is

**Comment by wasd96040501** [comment]
Hi @Veykril, it seems to me that `cargo metadata` and `cargo check` follow the same behavior when reporting the path.
Without `--manifest-path`, both commands expand the symlink on the reported path. But when `--manifest-path` is specified, they simply use the path provided in `--manifest-path` without expanding the symlink in the reported path.
The discrepancy arises because we've used `--manifest-path` in `cargo metadata` but not in `cargo check`.

**Comment by Veykril** [comment]
Sounds like we should be using `--manifest-path` in cargo check as well then?
