### ISSUE TITLE
diagnostics of "duplicate item error in rlib" when inspecting std library source code

### ISSUE THREAD

**Issue by DriedYellowPeach** [rust-lang/rust-analyzer#15878]
When I try to read some source about `Option`, rust-analyzer give me this error:
<img width="1074" alt="Screenshot 2023-11-12 at 15 14 23" src="https://github.com/rust-lang/rust-analyzer/assets/49219666/f2638923-43b7-40c5-baff-2a39c282c7b4">

I try to do the same thing on my older computer, which I haven't update rust-analyzer and other rust toolchain for a long time, there is no such error. Hope you guys can help me out

**rust-analyzer version**: `rust-analyzer 0.3.1722-standalone (c1c9e10f7 2023-11-05)`

**rustc version**: `rustc 1.73.0 (cc66ad468 2023-10-03)`

**Comment by lnicola** [comment]
That's not our error, it probably shows up in `cargo build` too. Which settings are you using?

**Comment by DriedYellowPeach** [comment]
> That's not our error, it probably shows up in `cargo build` too. Which settings are you using?
> 
> And did you open the standard library source code directly from disk, or using "Go to definition"?

Thanks for your reply! I use goto definition and I noticed that the root_dir for rust analyzer changed from my project to the toolchain directory, this means my lsp setting is wrong, right? And I tried cargo check in the toolchain core directory , there does have errors, I sort of understand this because when you build the core,you should set aside those pre-built rlib

**Comment by DriedYellowPeach** [comment]
I figure this out, it's my plugin rust-tools.nvim not setting up root_dir correctly, so every time I open the standard library, it just startup a new lsp instance. This problem has been asked more than once in both this repo and rust-tools repo, but rust-tools.nvim seems no longer maintained, so if you are using the rust-tools to setup rust analyzer, this duplicate items diagnostics will occur. And sorry for the bothering.
