### ISSUE TITLE
Using a different partitoning in `base_db::input::SourceRoot`

### ISSUE THREAD

**Issue by alibektas** [rust-lang/rust-analyzer#15888]
:wave: I have been working on #13529 and (indirectly) on #15741 ( as a matter of fact there should have been a "toml support for rust-analyzer issue". In order for both of these features to be implemented there needs to be a map ( and its inv. )  that maps `SourceFile`s ( so essentially a `FileId` ) to its corresponding (most of the time the closest) `Cargo.toml`/`RA.toml` file. I believe that this should be handled when we get to partition a `Vfs` into `SourceRoot`s. Based on my poor observation we partition with the intention to group as many files as possible into the same `FileSet`. I want to change that in such a way that `Cargo.toml`/`RATOML` files are used as anchors to a `SourceRoot` , meaning that if you encounter , say , a `Cargo.toml` you would know that this is a new `SourceRoot`. This change would enable me to map a `FileId` to the `FileId` of its corresponding `SourceRoot`, as in

```rust
srid = SourceDatabaseExt::file_source_root(db, file_id)
sr = SourceDatabaseExt::source_root(db, srid)
cargo_file_id = sr.cargo_toml_id()  // Option<FileId>
```  

I cannot see any other way of doing this so I wanted to get community's opinion on this.

**Comment by Veykril** [comment]
Can't you just store the `FileId` of the cargo.toml inside the `SourceRoot`? That aside, why do you need such a mapping?

**Comment by Veykril** [comment]
> Can't you just store the `FileId` of the cargo.toml inside the `SourceRoot`?

Answer is yes after some discussion in DMs
