### ISSUE TITLE
rust-analyzer error [ERROR rust_analyzer::main_loop] FetchWorkspaceError: rust-analyzer failed to discover workspace

### ISSUE THREAD

**Issue by Inarizxc** [rust-lang/rust-analyzer#15890]
![Снимок экрана 2023-11-14 164321](https://github.com/rust-lang/rust-analyzer/assets/128096405/3f7476ea-40c0-4fd9-baff-b28c13a41d69)
![Снимок экрана 2023-11-14 164423](https://github.com/rust-lang/rust-analyzer/assets/128096405/e77d28bb-66ff-4d06-9336-a158215d1aed)

**Comment by alibektas** [comment]
Can you open your project on the `\app` directory and check if you still get the same error?

**Comment by Inarizxc** [comment]
> Можете ли вы открыть свой проект в `\app` каталоге и проверить, по-прежнему ли вы получаете ту же ошибку?

![Снимок экрана 2023-11-14 165456](https://github.com/rust-lang/rust-analyzer/assets/128096405/2ff5b5cf-364d-4bd8-adcc-cf0cd63b9b10)

**Comment by alibektas** [comment]
Нет, это не то, что я имел в виду. Я имею в виду, что вам следует открыть свой VSCode в dev/rust/app, а не в dev. В корне вашего проекта вы должны увидеть «Cargo.toml».

**Comment by Inarizxc** [comment]
> Нет, это не то, что я имел в виду. Я имею в виду, что вам следует открыть свой VSCode в dev/rust/app, а не в dev. В корне вашего проекта вы должны увидеть «Cargo.toml».

Thank you, I did what you said and the error is no longer there.
