### ISSUE TITLE
Contrary to `AsRef`, elements referenced with `Borrow` are ignored.

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-analyzer#15914]
Hints or renames don't work with elements behind `Borrow`/`BorrowMut` because they are ignored.

![Capture d’écran du 2023-11-16 17-19-08](https://github.com/rust-lang/rust-analyzer/assets/17877264/77382d3b-9d58-473d-bbed-44382ca1abbe)

On the other side, `AsRef` which is a very similar trait, have its referenced element correctly interpreted.

![Capture d’écran du 2023-11-16 17-18-33](https://github.com/rust-lang/rust-analyzer/assets/17877264/aacefd10-b05d-41aa-b84a-caba075b366e)

**Comment by c410-f3r** [comment]
Closing due to inanition.

**Comment by flodiebold** [comment]
Likely a duplicate of #5514 anyway.
