### ISSUE TITLE
Many unnecessary allocations in path resolution

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust-analyzer#15924]
https://github.com/rust-lang/rust-analyzer/blob/bc978217b32cd10abd140bec1724a218f43629fb/crates/hir-def/src/nameres/path_resolution.rs#L187-L193

This does a bunch of string formatting on the happy path. According to my dhat analysis (opening rust-lang/rust with RA running in dhat and then waiting for a few minutes (it is very slow)), this accounts for 13% of the allocated blocks inside rust-analyzer. I don't think it uses much memory, but it's probably quite slow. I don't think my analysis is necessarily representative of normal usage, as it only really captured startup, but it still seems pretty relevant.

![image](https://github.com/rust-lang/rust-analyzer/assets/48135649/88c0b70f-2f03-46fd-817e-f4e0bfa50cc1)

**rust-analyzer version**: current master bc978217b32cd10abd140bec1724a218f43629fb

**rustc version**: 1.76.0-nightly, doesn't matter

**relevant settings**: the recommended settings for rust-lang/rust, provided there in `src/etc/rust_analyzer_settings.json`

**Comment by Veykril** [comment]
We can just remove those, they were added to aid in debugging https://github.com/rust-lang/rust-analyzer/issues/10084 which we now consider an undeterministic bug of salsa, so they don't really help anymore
