### ISSUE TITLE
"unexpected argument: "rustc""

### ISSUE THREAD

**Issue by mg** [rust-lang/rust-analyzer#15928]
Hi

I am trying to get rust-analyzer working. I don't have rust globally installed on my system but I have it installed in a Nix devshell environment. Both rust-analyzer and rustc are in path, but rust-analyzer is not able to find it.

<img width="1010" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/1972/887770e1-370c-41d5-9899-4c3d75855c5e">

Is there an environment variable I can set to direct rust-analyzer to replace `rustc`with a more direct `/nix/store/r4gkv40ymggj3qbrxhji2y9294r31ahl-rust-default-1.74.0/bin/rust`? If that is possible I can easily configure this correctly in my flake.nix file that sets up the whole environment for me.

**Comment by lnicola** [comment]
Why are you running `rust-analyzer rustc`? What do you expect it to do? RA is not supposed to replace `cargo`, nor `rustc`.

**Comment by mg** [comment]
I was misunderstanding how the whole thing works, and had set RUSTC_WRAPPER to rust-analyze in the VSCode settings. Sorry about the time waste and thank you for responding.

**Comment by lnicola** [comment]
If you manage to get a working setup, feel free to file a PR for the manual in order to atone for your mistake.
