### ISSUE TITLE
Keep diagnostics at least until new ones are available

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust-analyzer#15934]
[This is something something I reported first in my text editor (helix)](https://github.com/helix-editor/helix/issues/8858) but [I was told this is actually rust-analyzer's behavior, and thus can't be fixed there](https://github.com/helix-editor/helix/issues/8858#issuecomment-1817805032).

> I'm working on a large Rust project. I make some refactoring changes that break existing callers. I hit `:w` and CPU's temperature rapidly increases. I wait and wait... I get over 9000 errors.
> 
> I fix some in one file and `:w`. LSP makes my laptop fan go jet engine mode again. I wait. I could be fixing some other errors already, because I know there's still plenty off them, but my text editor has already reset the previous list and `<space>D` shows an empty diagnostics picker. Bummer. I need to wait for the new diagnostics to arrive.
> 
> I wish previous LSP diagnostics were available for longer. At least until new LSP run completes or start returning something actionable again. 

I was told this is because:

> It's just that RA immidietly discards all checkOnSave diagnostics on save and therefore sends an empty list.

I'm not all that versed in LSP details, but I guess what I'm asking for is RA not sending that empty list, until it knows that project doesn't have any diagnostics.

This would be a biggest QA improvement in my workflow I can think of.

**Comment by Veykril** [comment]
We clear the check diagnostics here https://github.com/rust-lang/rust-analyzer/blob/255eed40c45fcf108ba844b4ad126bdc4e7a18df/crates/rust-analyzer/src/main_loop.rs#L640-L642 and set them here https://github.com/rust-lang/rust-analyzer/blob/255eed40c45fcf108ba844b4ad126bdc4e7a18df/crates/rust-analyzer/src/main_loop.rs#L489-L492

it might just suffice to move the clear away from the `DidStart` handling in front of the loop where we set the diagnostics now.

**Comment by matthri** [comment]
Hi, 
first of all many thanks for the information you already provided :D 

I was digging around in the code based on your instructions and a few questions have come up. 
Removing the diagnostics clearing from here
https://github.com/rust-lang/rust-analyzer/blob/255eed40c45fcf108ba844b4ad126bdc4e7a18df/crates/rust-analyzer/src/main_loop.rs#L640-L642
I have understood, what I'm not sure is where to move the diagnostics clearing. 

You suggested to add the clearing here 
https://github.com/rust-lang/rust-analyzer/blob/255eed40c45fcf108ba844b4ad126bdc4e7a18df/crates/rust-analyzer/src/main_loop.rs#L489-L492
which as far as I can tell processes the `native` diagnostics whereas the previous location handles the `flycheck` diagnostics. 
Therefore I wondered if the diagnostics clearing should instead get moved here
https://github.com/rust-lang/rust-analyzer/blob/255eed40c45fcf108ba844b4ad126bdc4e7a18df/crates/rust-analyzer/src/main_loop.rs#L620-L623
where the flycheck messages get processed and the diagnostics added.

My second question is if you have an idea how to automatically test this behavior or if there is an already existing test.

**Comment by Veykril** [comment]
Right thats for native ones. The problem with clearing it where you proposed is that if multiple checks are running, we'll clear everything but the last one. I guess the easiest way would be to set a flag in `GlobalState` when running `run_flycheck` and in the place you linked, if the flag is set, unset it and clear the native diagnostics. That way if `run_flycheck` kicks off multiple it should still work out right.

**Comment by Veykril** [comment]
> My second question is if you have an idea how to automatically test this behavior or if there is an already existing test.

Not, I don't think we have any tests for this at all. I'd just say pick a big project (like r-a itself), edit some random crates with errors and check whether things work as expected.
