### ISSUE TITLE
Cargo check in visual studio code is blocking

### ISSUE THREAD

**Issue by fansehep** [rust-lang/rust-analyzer#15937]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

`20231113-1`

**rustc version**: (eg. output of `rustc -V`) `rustc 1.74.0 (79e9716c9 2023-11-13)`

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

I use `rust-analyzer` plugin in `vscode`, when i edit some file, the `rust-analyzer` will auto execute `cargo check`, What struck me as odd was it was blocking here.

**Comment by lnicola** [comment]
What is it blocking? Another `cargo check` run from the terminal?

You can disable the execution of `cargo check` if you want.

**Comment by fansehep** [comment]
> What is it blocking? Another `cargo check` run from the terminal?
> 
Seems no other process execute `cargo check`. Blocking on `cargo check`. And never finish it.

> You can disable the execution of `cargo check` if you want.

If i disable it, Can `rust-analyzer` work normally?

**Comment by lnicola** [comment]
We run three things:

 - `cargo metadata` to get project structure information; this can be somewhat slow, and depends on the network
 - `cargo check` to run the build scripts and compile proc macros; you can disable this, but won't get proc macro support
 - `cargo check` to show diagnostics

If `cargo metadata` and `cargo check --all-targets` work in the terminal, they should work in a RA started from that terminal.

**Comment by fansehep** [comment]
> We run three things:
> 
> * `cargo metadata` to get project structure information; this can be somewhat slow, and depends on the network
> * `cargo check` to run the build scripts and compile proc macros; you can disable this, but won't get proc macro support
> * `cargo check` to show diagnostics
> 
> If `cargo metadata` and `cargo check --all-targets` work in the terminal, they should work in a RA started from that terminal.

After i execute `cargo check --all-targets`, I found it was blocking on compiling some binary files. Seems very very slow. I know the reasons why he blocking on. Some binary files was C++ ffi binding. I guess that because the `C++` lib compile.
Really thanks for @lnicola . ❤️

**Comment by lnicola** [comment]
Yeah, that sometimes happen. You can also disable `--all-targets` in the settings if you want.

**Comment by fansehep** [comment]
> Yeah, that sometimes happen. You can also disable `--all-targets` in the settings if you want.

I also found that when i use vscode to `restart` or `stop` the `rust-analyzer`, the `RA` will not stop running. So this is also a blocking reason.

**Comment by lnicola** [comment]
It should stop, but perhaps we don't handle the case when `cargo metadata` or `cargo check` is still running.
