### ISSUE TITLE
rust-analyzer shows thousands of rustc errors but running the build command on the terminal works fine

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#15942]
Since somewhat recently, RA shows >1800 errors in src/tools/miri in the rustc workspace, even though Miri builds perfectly fine. The errors all claim that various types from rustc cannot be found.
```
cannot find type `AllocId` in this scope
not found in this scope
cannot find type `MemoryKind` in this scope
not found in this scope
cannot find type `ImmTy` in this scope
not found in this scope
```

Running the same build command inside vscode in the terminal, everything succeeds just fine -- so it looks very much like this is caused by how RA invokes the build command. The same command still worked last week or so (I don't exactly remember when I used vscode in rustc the last time).

rustc itself builds just fine, it is only Miri where it shows errors.

**rust-analyzer version**: 0.3.1740-standalone

**rustc version**: bootstrap beta

**relevant settings**:
```
{
    "rust-analyzer.linkedProjects": [
        "Cargo.toml",
        "src/bootstrap/Cargo.toml",
    ],
    "rust-analyzer.check.invocationLocation": "root",
    "rust-analyzer.check.invocationStrategy": "once",
    "rust-analyzer.check.overrideCommand": [
        "./myx",
        "check",
        "--json-output",
        "library/std",
        "compiler/rustc", "src/tools/miri",
    ],
    "rust-analyzer.rustfmt.overrideCommand": [
        "${workspaceFolder}/build/host/rustfmt/bin/rustfmt",
        "--edition=2021",
    ],
    "rust-analyzer.rustc.source": "./Cargo.toml",
    "rust-analyzer.cargo.sysrootSrc": "./library",
    "rust-analyzer.cargo.extraEnv": {
        "RUSTC_BOOTSTRAP": "1"
    },
    // These just make everything way too slow.
    "rust-analyzer.cargo.buildScripts.enable": false,
    "rust-analyzer.procMacro.enable": false,
    // Some diagnostics don't work properly here
    "rust-analyzer.showUnlinkedFileNotification": false,
    "rust-analyzer.diagnostics.enable": false, // without proc macros, there's just too many false positives
    //
    "files.watcherExclude": {
        "*rustc*/src/llvm-project/**": true,
        "*rustc*/build/**": true,
    },
    "files.exclude": {
        "src/llvm-project/**": true,
        "build/**": true
    },
}
```

**Comment by RalfJung** [comment]
Actually this is caused by a rustc update, not an RA update... when I go back in the rustc history to before https://github.com/rust-lang/rust/pull/116828, everything is fine. I still have no idea what is actually going on though.

**Comment by RalfJung** [comment]
I have tried adding `"rust-analyzer.cargo.buildScripts.useRustcWrapper": false`, it does not make a difference.

**Comment by RalfJung** [comment]
I am getting similar behavior in stdarch: just checking out https://github.com/rust-lang/stdarch/, setting the rustup override to nightly, and opening the project in RA leads to thousands of errors. However, `cargo check` on the terminal works just fine. I tried changing the RA config but it did not help:
```
{
    "rust-analyzer.linkedProjects": [
        "./crates/core_arch/Cargo.toml"
    ],
    "rust-analyzer.cargo.buildScripts.enable": false,
    "rust-analyzer.procMacro.enable": false,
    "rust-analyzer.cargo.buildScripts.useRustcWrapper": false,
}
```

**Comment by Veykril** [comment]
You can run r-a with `RA_LOG` set to "flycheck=debug`, then triggering the cargo check through r-a will make it log the command invoked. In VSCode you can set that in the `rust-analyzer.server.extraEnv` config
```json

    "rust-analyzer.server.extraEnv": {
        "RA_LOG": "flycheck=debug",
    }
```

**Comment by RalfJung** [comment]
Where should it put those logs? In the "RA language server" output, all I can see is a ton of "cyclic deps" messages.

**Comment by Veykril** [comment]
That's where it should log those whenever you trigger the check

**Comment by Veykril** [comment]
You will have to restart the server fwiw

**Comment by RalfJung** [comment]
Yes, I even reloaded the vscode window. Nothing. Ctrl-F "fly" in the output window shows no results.

**Comment by RalfJung** [comment]
Oh, dang, sorry. I added this to the wrong `extraEnv`. I didn't realize there are multiple of them.

**Comment by RalfJung** [comment]
Now I am seeing something:
```
[INFO flycheck] Spawning flycheck id=0 workspace_root=AbsPathBuf("/home/r/src/rust/rustc.2")
[DEBUG flycheck] will restart flycheck command=cd "/home/r/src/rust/rustc.2" && RUSTC_BOOTSTRAP="1" "./myx" "check" "--json-output" "library/std" "compiler/rustc" "src/tools/miri"
[DEBUG flycheck] did  restart flycheck command="cd \"/home/r/src/rust/rustc.2\" && RUSTC_BOOTSTRAP=\"1\" \"./myx\" \"check\" \"--json-output\" \"library/std\" \"compiler/rustc\" \"src/tools/miri\""
```

However, even `RUSTC_BOOTSTRAP="1" ./myx check miri` works fine on the terminal...

But indeed if I run `"./x.py" "check" library/std compiler/rustc src/tools/miri` I sometimes get all these errors on the terminal as well now. If I then run `./x.py check miri`, that succeeds. If I then run `"./x.py" "check" library/std compiler/rustc src/tools/miri`  again it succeeds as well.

So this is probably a bootstrap bug.

**Comment by RalfJung** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/118129. Thanks for the debugging help!
