### ISSUE TITLE
Run rust-analyzer on the rustc test suit

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/rust-analyzer#15947]
Rust-analyzer supports several diagnostics, running it against the rustc ui tests and checking the equivalency of them (we don't have equal error messages and spans, but even checking the count of errors will probably work) can help a lot in discovering rare edge case bugs in the analysis and diagnostics logic I think.

We can start having them in metrics (as it will probably have many fails at the start) and later moving them into the CI if there were near zero problems and it was fast to check.

**Comment by Veykril** [comment]
Tbh, I don't think that's worth it currently. We could do it for a select subset of diagnostics (ui tests), but given the general lack of diagnostics r-a has in regards to typeck and name resolution I don't think we gain a lot from this as it stands. 

> ... and later moving them into the CI if there were near zero problems and it was fast to check.

That's never gonna be fast, in fact I would not be surprised if this doubled CI time in general. There are *a lot* of ui tests in rustc and afaik all of them depend on std (this might be wrong)?
