### ISSUE TITLE
Add warning about mistyped numeric literals

### ISSUE THREAD

**Issue by Bobulous** [rust-lang/rust-analyzer#15948]
(If this feature has already been requested, please point me to it. I couldn't find anything using the search terms that came to mind.)

I'm using [Helix](https://docs.helix-editor.com/) and LSP with rust-analyzer, and chased around a bug for ten minutes yesterday before realising I'd typed something stupid:

`let match_count = 0_32;`

Only after adding a bunch of `println` lines did I realise that my counter was actually starting with a value of 32 instead of the zero I intended, and that what I'd meant to type was this:

`let match_count = 0_u32;`

Is it possible to add a warning to rust-analyzer so that it highlights suspicious use of the underscore in numeric literals? I'm not aware of any locale that uses a separator before the last one or two digits of numbers, so I don't think that a warning about numbers ending `_8`, `_16`, `_32`, or `_64` would irk users with genuine use cases. Does anyone know of a locale which has a legitimate use for a separator like this? Are there other (non-locale) reasons to avoid adding such a warning to rust-analyzer?

**Comment by lnicola** [comment]
I think it's legitimate in base 16. And I suspect some users will complain if we emit warnings on code that compiles without any. Today, this would be better suited for clippy.

**Comment by HKalbasi** [comment]
And clippy already has lint against this.

**Comment by Bobulous** [comment]
Yes, someone made me aware earlier today that clippy has nice warnings about this. Problem is that I use clippy after getting the code to work, once it's time to tidy things up. I don't tend to think of clippy while in the middle of writing code and trying to get unit tests to pass. (Do other people run clippy frequently while in the middle of writing new code?)

**Comment by p-avital** [comment]
> Yes, someone made me aware earlier today that clippy has nice warnings about this. Problem is that I use clippy after getting the code to work, once it's time to tidy things up. I don't tend to think of clippy while in the middle of writing code and trying to get unit tests to pass. (Do other people run clippy frequently while in the middle of writing new code?)

I configured my rust-analyzer to use clippy instead of check by default.

It's fast enough that I never wait on it (at least, not more than check), and I prefer solving the issues incrementally than in huge discouraging batches.

We actually fail the CI in all Zenoh projects if clippy's not fully happy with our code.

Ever since I've become aware of the `clippy::missing_{safety/panic/error}_docs`, I've been enabling them systematically in my projects: it makes making good docs so much easier.

**Comment by Bobulous** [comment]
Ah, I did not realise that rust-analyzer could be told to use clippy on top of `cargo check`.

By creating a languages.toml file in my `~/.config/helix/` directory and adding the following:

```
[language-server.rust-analyzer.config.check]
command = "clippy"
```

the Helix editor now warns if I type something daft like `let zero = 0_32`. Which is exactly what I was hoping for.

So I'm closing this comment. Sorry for the wild goose chase.
