### ISSUE TITLE
Diagnose trait impl items that don't exist in the implementing trait

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15958]
And offer a quickfix to add the corresponding trait item to the trait

**Comment by Young-Flash** [comment]
hi, I am thinking about "add the corresponding trait item to the trait", we could get `hir::Trait` when we construct that diagnostic, but how could we get the corresponding `ast::Trait` to add some trait item into it? search in the codebase but can't find some related internal api to do that(I still not familar enough with internal api in RA), any suggestion?
