### ISSUE TITLE
Test functions using rstest are detected as tests but don't appear in the Run panel

### ISSUE THREAD

**Issue by YPares** [rust-lang/rust-analyzer#15966]
When using the rstest crate, every function annotated by #[rstest] is detected as being a test by rust-analyser and the `Run Test | Debug` buttons do appear on top of the function. But when having the cursor inside the fn and doing `> rust-analyzer: Run`, the individual function I'm on does not show in the panel. No problem with fns annotated with just #[test].

**rust-analyzer version**: 0.3.1740-standalone (255eed40c 2023-11-17)

**rustc version**: 1.74.0 (79e9716c9 2023-11-13)

**Comment by DanielJoyce** [comment]
On latest, I don't see the Run Test | Debug on rstest annotated functions at all.

**Comment by DanielJoyce** [comment]
stable-x86_64-unknown-linux-gnu unchanged - rustc 1.75.0 (82e1608df 2023-12-21)

Rust analyzer plugin version: v0.3.1815

**Comment by Young-Flash** [comment]
it works well for me

![image](https://github.com/rust-lang/rust-analyzer/assets/71162630/b058fc45-f240-4093-beeb-163d51b9926d)
