### ISSUE TITLE
No feedback from Rust Analyzer in multi-Cargo workspace VS Code workspace

### ISSUE THREAD

**Issue by djc** [rust-lang/rust-analyzer#15974]
In a VS Code workspace containing multiple Cargo workspaces, I'm currently not getting any feedback from Rust Analyzer/VS Code for my code, in the sense that no squigglies appear in the editor tab. This definitely worked on Friday.

I see status bar items churning (indexing all the dependency crates), but then no problems appear in the output and the "Rust Analyzer Language Server" window remains empty). Making a change will see a really quick "cargo check" item in the status bar, which then disappears without signaling problematic code.

Not sure if there is an issue with my setup here? It seems to work fine in smaller VS Code workspaces (that just have a single Cargo workspace), so maybe there's something specific to this setup that got broken?

**rust-analyzer version**: 0.3.1748-standalone (237712fa3 2023-11-26)

**rustc version**: rustc 1.74.0 (79e9716c9 2023-11-13)

**relevant settings**: VS Code

**Comment by Veykril** [comment]
The only change that could be relevant here would be https://github.com/rust-lang/rust-analyzer/pull/15754 but there is not much more we can tell without knowing the structure of the project(s)

**Comment by djc** [comment]
The problem seems to have solved itself for now -- which always makes me worrry that I don't understand why things don't work, but I guess it doesn't make sense to spend much more time on it. The crate I was looking at is a leaf crate (with no other crates depending on it) so it makes it feel unlikely that deduplication could be an issue?

**Comment by Veykril** [comment]
Well if its gone again then the root issue here is probably older yes. I don't think that PR shouldve caused this either but its the only relevant change in terms of touching workspace stuff in r-a recently
