### ISSUE TITLE
Feature Request: Navigate to Super/Crate Root

### ISSUE THREAD

**Issue by Zeenobit** [rust-lang/rust-analyzer#15977]
This is a request for a command to navigate from current file into `super` (i.e. parent `mod.rs`), or to crate root (`lib.rs` or `main.rs`).

This would be extremely helpful when writing related code across multiple sibling modules, allowing the user to quickly switch between parent and children.

I tried looking to see if this feature already exists, but I couldn't find anything. Apologies in advance if it does!

**Comment by lnicola** [comment]
`rust-analyzer: Locate parent module` in VS Code.

**Comment by Zeenobit** [comment]
Thank you!

It might be more ergonomic to rename the command to "Locate super module", just to be in parity with keyword `super` (it never occurred to me to search for "parent"). Otherwise, I'm ok with closing this issue.

**Comment by lnicola** [comment]
`super` is the keyword that refers to the parent module, and the latter is what [the reference](https://doc.rust-lang.org/reference/items/use-declarations.html?search=parent%20module) uses. I don't think we should change it.

There's also a Easter egg, triggering it on `lib.rs` or `main.rs` will open `Cargo.toml`, which is not a module, but..
