### ISSUE TITLE
stuck while loading analyzer

### ISSUE THREAD

**Issue by jyC23333** [rust-lang/rust-analyzer#15975]
![image](https://github.com/rust-lang/rust-analyzer/assets/110331827/9217e45c-63e4-4352-ab94-b38392568135)
![image](https://github.com/rust-lang/rust-analyzer/assets/110331827/6e4c946d-0385-459a-b6a7-1d1fa8bd2b3c)

 I can't use the extension on my SSH server, but it works well on my local computer.

**Comment by lnicola** [comment]
Did you run `rustup component add rust-src`?

**Comment by jyC23333** [comment]
@lnicola It works now! Thanks so much.
