### ISSUE TITLE
error[E0308]: mismatched types  `PgConnectOptions` and `PgConnectOptions` have similar names, but are actually distinct types

### ISSUE THREAD

**Issue by 2001lwy** [rust-lang/rust-analyzer#15982]
error[E0308]: mismatched types
   --> reservation\src\manager.rs:75:4
    |
75  |    #[sqlx_database_tester::test(pool(variable = "migrated_pool",migrations = "../migrations"))]
    |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |    |
    |    expected `PgConnectOptions`, found a different `PgConnectOptions`
    |    arguments to this function are incorrect

Cargo.toml
[dependencies]
async-trait = "0.1.74"
chrono = { version = "0.4.31", features = ["serde"] }
project = { version = "0.1.0", path = "../project" }
sqlx = { version = "0.7.3", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
thiserror = "1.0.48"

[dev-dependencies]
sqlx-database-tester = { version = "0.4.2", features = ["runtime-tokio"] }
tokio = { version = "1.21.2", features = ["full"] }

**Comment by lnicola** [comment]
Does `cargo test` work?

**Comment by 2001lwy** [comment]
> `sqlx-database-tester 0.4.2` depends on `sqlx 0.6.0`, which is incompatible with your `sqlx 0.7.3`.

The cargo test cannot pass when sqlx is 0.7.3. I changed it to 0.6.3 and it passed, but this version is a bit old. Versions above 0.7.0 cannot pass the cargo test.

**Comment by 2001lwy** [comment]
> You can either use `sqlx 0.6` or stop using `sqlx-database-tester`. We can't do much about it.
OK, thank you for your answer
