### ISSUE TITLE
High Memory USAGE

### ISSUE THREAD

**Issue by korayakpinar** [rust-lang/rust-analyzer#16002]
Type: <b>Bug</b>

Just use bisect..

Extension version: 0.3.1748
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Connection to 'wsl+ubuntu' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.86GB (1.84GB free)|
|Process Argv|--disable-extensions --remote=wsl+Ubuntu --crash-reporter-id a86e9265-88f1-4f82-853f-15d186c2229f|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+ubuntu' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30909684

```

</details>

**Comment by lnicola** [comment]
Not sure what you mean. What's using a lot of memory and how much?

**Comment by korayakpinar** [comment]
![WhatsApp Görsel 2023-12-02 saat 15 49 02_c2da5e46](https://github.com/rust-lang/rust-analyzer/assets/64989538/2c5f7768-585a-4702-bb67-c7300465e10f)
This is just WSL on idle. Here is memory usage of wsl + vscode:
![WhatsApp Görsel 2023-12-02 saat 15 49 42_7f293ce4](https://github.com/rust-lang/rust-analyzer/assets/64989538/164753b3-357f-4b66-a73f-4944b6266632)
And memory usage of wsl + vscode + rust-analyzer:
![WhatsApp Görsel 2023-12-02 saat 15 50 56_db3ccd95](https://github.com/rust-lang/rust-analyzer/assets/64989538/b3c24f3d-a3d3-4632-a365-09398023da6c)

**Comment by lnicola** [comment]
Not really, it only shows a 2.1 GB difference, which is reasonable. And to measure it properly, you should use `htop` in WSL, not in Task Manager.

Are you working on a Rust project? How large is it? Is is public?
