### ISSUE TITLE
the bounded rust-analyzer.exe requires Microsoft Visual C++ Redistributable

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust-analyzer#16006]
toolchain version:
```
Default host: x86_64-pc-windows-gnu
rustup home:  ...\.rustup

stable-x86_64-pc-windows-gnu (default)
rustc 1.74.0 (79e9716c9 2023-11-13)
```
version:
```
rust-analyzer 0.3.1748-standalone (237712fa3 2023-11-26)
```
before installing Microsoft Visual C++ Redistributable:
```
Bootstrap error [Error: Failed to execute ...\.vscode\extensions\rust-lang.rust-analyzer-0.3.1748\server\rust-analyzer.exe --version
```
after installing Microsoft Visual C++ Redistributable:
works well

rust-analyzer installed using rustup does not require  Microsoft Visual C++ Redistributable installation.

**Comment by lnicola** [comment]
Yeah, I meant that the -gnu toolchain might still be built with -msvc, though it seems unlikely.

@zzwxh are you using VS Code?

**Comment by bjorn3** [comment]
It may be possible to switch from msvcrt to ucrt which microsoft has added to windows vista and up using an update. I don't know how exactly to do this though.

**Comment by lnicola** [comment]
Maybe https://doc.rust-lang.org/rustc/platform-support/pc-windows-gnullvm.html, but it doesn't look particularly tempting.
