### ISSUE TITLE
rust-analyzer.diagnostics.enabled=false does not suppress "textDocument/publishDiagnostics"

### ISSUE THREAD

**Issue by fommil** [rust-lang/rust-analyzer#16005]
**rust-analyzer version**: `rust-analyzer 1.74.0 (79e9716c 2023-11-13)`

**rustc version**: `rustc 1.74.0 (79e9716c9 2023-11-13)`

**relevant settings**: 

started from emacs with

```
  (add-to-list 'eglot-server-programs
               '((rust-ts-mode rust-mode) .
                 ("rust-analyzer"
                  :initializationOptions
                  (:checkOnSave "false" :diagnostics (:enable "false")))))
```

Originally started as a thread on https://users.rust-lang.org/t/disable-diagnostics-in-rust-analyzer/103323/4 but I think I'm hitting a bug.

By setting `rust-analyzer.diagnostics.enable = "false"` I do not expect to receive any diagnostics at any time.

However, I'm getting lots of stuff. e.g.

```
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/fommil/Projects/aoc2023/src/bin/day2.rs" :diagnostics
                [(:range
                  (:start
                   (:line 25 :character 9)
                   :end
                   (:line 25 :character 9))
                  :severity 1 :code "syntax-error" :codeDescription
...
```

This is having a big impact on performance when trying to write Rust code on a very low end ARM64 based system (I have a Pinebook, but it would be the same on any low end machine such as a Raspberry Pi or, in the Intel world, a converted Chromebook).

Notably, `:source "rustc"` in the diagnostic.

Possibly relevant, this is happening at least when I'm triggering a completion, at which point the code is almost certainly not syntactically valid because I'm in the middle of typing! I have disabled pretty much everything so it's not happening when I am simply navigating around, but I am ALSO getting it on save and since I've set `checkOnSave` I wouldn't expect that at all and implies that not only is rustc sending diagnostics but `cargo check` is as well.

**Comment by lnicola** [comment]
It works for me on VS Code. Maybe you need to set those to `nil` instead of `"false"`.

**Comment by fommil** [comment]
@lnicola ok, `:json-false` works for me, that wasn't obvious from reading the docs. It would be good if the json parser supported string literals for booleans, but now that I know I'm unlikely to encounter this again.

**Comment by lnicola** [comment]
I found it in the `eglot`. We can improve the manual, but I don't think we should make the deserialization more lax.
