### ISSUE TITLE
Container Name for impl  functions

### ISSUE THREAD

**Issue by jimmyhmiller** [rust-lang/rust-analyzer#16015]
When a doing `workspace/symbols` functions inside an impl lack a container name. You can see this from the following tests:

https://github.com/rust-lang/rust-analyzer/blob/e402c494b7c7d94a37c6d789a216187aaf9ccd3e/crates/ide-db/src/symbol_index.rs#L413-L415

https://github.com/rust-lang/rust-analyzer/blob/e402c494b7c7d94a37c6d789a216187aaf9ccd3e/crates/ide-db/src/test_data/test_symbol_index_collection.txt#L529-L555)

It would be great to have that container name of "Struct". I was able to locally get this feature working by replacing

https://github.com/rust-lang/rust-analyzer/blob/e402c494b7c7d94a37c6d789a216187aaf9ccd3e/crates/hir/src/symbols.rs#L238-L243

The implementation I am not 100% sure about was:

```rust
    fn collect_from_impl(&mut self, impl_id: ImplId) {
        let impl_data = self.db.impl_data(impl_id);

        let mut impl_name = None;
        impl_data.self_ty.walk(&mut |ty| {
            if let hir_def::type_ref::TypeRef::Path(path) = ty {
                impl_name = path
                    .mod_path()
                    .and_then(|mod_path| mod_path.as_ident())
                    .and_then(|ident| ident.as_text())
            }
        });

        self.with_container_name(impl_name, |s| {
            for &assoc_item_id in &impl_data.items {
                s.push_assoc_item(assoc_item_id)
            }
        })
    }
```
    
I wanted to create this issue first before putting out a PR to make sure that there isn't some reason this functionality was left off. I'm building my own editor which uses rust-analyzer and I would personally find this very useful.

**Comment by Veykril** [comment]
`impl_data.self_ty.display(db)` should suffice (from the `HirDisplay` trait). As to why we are only considering the module as a container I am not sure, depends on where that information is used.
