### ISSUE TITLE
Debugging tests via VSCode Code Lens fails

### ISSUE THREAD

**Issue by fnuecke** [rust-lang/rust-analyzer#16010]
**rust-analyzer version**: 0.3.1756-standalone (e402c494b 2023-12-01)
**rustc version**: 1.74.0 (79e9716c9 2023-11-13)
**cargo version**: 1.74.0 (ecb9851af 2023-10-18)
**os**: Windows 11 Version 10.0.22631 Build 22631
**additional vs code extensions**: cpptools

**Reproduction steps**
- Open a new directory in VSCode.
- Run `cargo init` in the directory.
- Open main.rs and add an empty test.
- Click the "Debug" Code Lens option on the test function or test module.

**Details**

Sample main.rs:
```rust
fn main() {
    println!("Hello, world!");
}

#[cfg(test)]
mod tests {
    #[test]
    fn test() {}
}
```

Attempting to run a test in debug configuration leads to the following error:
![image](https://github.com/rust-lang/rust-analyzer/assets/514903/198ed081-9b7a-4614-a003-d65608d8fe47)
(Dialog box with error "Invalid 'cwd' value 'H:\Projects\test-debug\Cargo.toml'. The directory name is invalid.")

Output in vscode's debug output for the generated launch configuration:
```
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
Launching debug configuration:
{
  "type": "cppvsdbg",
  "request": "launch",
  "name": "test-mod tests",
  "program": "H:\\Projects\\test-debug\\target\\debug\\deps\\test_debug-53b7fdbe7fc8a241.exe",
  "args": [
    "tests",
    "--nocapture"
  ],
  "cwd": "H:\\Projects\\test-debug\\Cargo.toml",
  "sourceFileMap": {},
  "env": {
    ...
  }
}
```

Manually putting this into launch.json results in the same error.  Removing the trailing "\\\\Cargo.toml" from the "cwd" setting solves the issue.

Output of `cargo test --message-format=json --no-run`:
```
> cargo test --message-format=json --no-run
{"reason":"compiler-artifact","package_id":"test-debug 0.1.0 (path+file:///H:/Projects/test-debug)","manifest_path":"H:\\Projects\\test-debug\\Cargo.toml","target":{"kind":["bin"],"crate_types":["bin"],"name":"test-debug","src_path":"H:\\Projects\\test-debug\\src\\main.rs","edition":"2021","doc":true,"doctest":false,"test":true},"profile":{"opt_level":"0","debuginfo":2,"debug_assertions":true,"overflow_checks":true,"test":true},"features":[],"filenames":["H:\\Projects\\test-debug\\target\\debug\\deps\\test_debug-53b7fdbe7fc8a241.exe","H:\\Projects\\test-debug\\target\\debug\\deps\\test_debug-53b7fdbe7fc8a241.pdb"],"executable":"H:\\Projects\\test-debug\\target\\debug\\deps\\test_debug-53b7fdbe7fc8a241.exe","fresh":true}
{"reason":"build-finished","success":true}
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
```

Notably, the returned `manifest_path` uses backslashes as path separator.

Digging into how the launch configurations are generated, it looks like rust-analyzer currently assumes paths will always use slashes, since it [tries to strip the trailing "/Cargo.toml"](https://github.com/rust-lang/rust-analyzer/blob/e402c494b7c7d94a37c6d789a216187aaf9ccd3e/editors/code/src/toolchain.ts#L77C75-L77C77) (note the slash).

If this can alternatively be solved by adjusting my configuration somewhere, guidance would be highly appreciated.

**Comment by Rampagy** [comment]
I've never use typescript before, but based on a quick search it appears that the `.replace()` method can use regular expressions.

Would this work?
https://regex101.com/r/T91UQI/3

**Comment by lnicola** [comment]
Can anyone install the pre-release version (there's a button in VS Code) and check if this is now working?

**Comment by codewing** [comment]
I had the same/similar issue with LLDB and this is now resolved with the pre-release version 🎉

**Comment by fnuecke** [comment]
Can also confirm the issue is fixed in the pre-release version.  Thanks a lot for the quick fix!
