### ISSUE TITLE
Items Linking rendering in doc comments is not sufficient

### ISSUE THREAD

**Issue by TieWay59** [rust-lang/rust-analyzer#16021]
![image](https://github.com/rust-lang/rust-analyzer/assets/40034603/465bddce-705c-44af-bb69-72a80c75ea6d)

The problem is these doc links are not rendered as expected. This has caused me to think about whether I'm doing wrong in some aspect, but it seems RA still does not support this syntax right? Correct me if I'm wrong about it.

**rust-analyzer version**: 0.4.1757-standalone (2d66f6df2 2023-12-04)

**rustc version**: rustc 1.74.0 (79e9716c9 2023-11-13)

**relevant settings**: N/A (idk what is related for now)

**Comment by Veykril** [comment]
Will be fixed by https://github.com/rust-lang/rust-analyzer/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by TieWay59** [comment]
Thank you @Veykril, I'll follow it.
