### ISSUE TITLE
`ra_ap_sourcegen` should probably not be a published crate

### ISSUE THREAD

**Issue by jlapeyre** [rust-lang/rust-analyzer#16029]
`crates/sourcegen` is used by rust analyzer from the workspace, not from the published version.

In fact, the published crate isn't useful for anything because it contains a hardcoded (relative) path:

https://github.com/rust-lang/rust-analyzer/blob/afc1ae1aa30f55395180ad770cc99c8fb1052338/crates/sourcegen/src/lib.rs#L197-L202

I actually use sourcegen for a different project. I just copied the crate to my workspace after I discovered it is not useful when installed via cargo.

It's my understanding is that none of the rust analyzer crates are guaranteed to work as libraries. But in fact, in the case of `sourcegen` it is guaranteed *not* to work for anything, including r-a (unless it's in the workspace).

Wouldn't it be better, less misleading and noisy if the crate were not published at all? At least, continuing to autopublish it seems at best not useful.

**Comment by Veykril** [comment]
Yep, this one is just missing a `publish = false`, it was never intended to be published
