### ISSUE TITLE
about the basic usage and operation of Structural Search and Replace

### ISSUE THREAD

**Issue by stuser88** [rust-lang/rust-analyzer#16020]
The ssr described in the following manual cannot be performed on my VSCode 1.73.1, rust-analyzer v0.3.1566.
https://rust-analyzer.github.io/manual.html#structural-search-and-replace

// BEFORE
String::from(foo(y + 5, z))

// AFTER (expected but nothing happened)
String::from((y + 5).foo(z))

// With
rust-analyzer: Structural Search Replace
(foo($a, $b)) ==>> (($a).foo($b))

So, tried the following very simple code, but nothing happened also.
Could someone in the know please tell me how to do it?

#[test]
fn rassr() {
    let x = 1;
    let y = 2;
    let z = add_two_args(x, y);  // Before
    assert_eq!(z, as_is(x + y));
}

fn add_two_args(a: i32, b: i32) -> i32 {
    a + b
}

fn as_is(a: i32) -> i32{
    a
}

// Before
add_two_args(x, y)

// After (expected but nothing happened also)
as_is(x + y)

// With
(add_two_args($a, $b)) ==>> (as_is($a + $b))

![rassr01](https://github.com/rust-lang/rust-analyzer/assets/79188189/42da5664-1679-471d-af76-3c8e1b642f1c)

**Comment by lnicola** [comment]
Easy-peasy, `foo($a, $b) ==>> ($a).foo($b)`.

**Comment by stuser88** [comment]
to Veykril:
    Thank you very much for your quick and internal information.
    Using Inicola's information above as a reference, I successfully used the following format.
    (successed simply with:)  add_two_args($a, $b) ==>> as_is($a + $b)
    Sorry for the trouble.

to Inicola:
    Easy-peasy lemon squeezy.
    I learned the outermost parentheses were not needed.
    Sorry for the trouble, too.
