### ISSUE TITLE
Completion type match calculations for function items should consider the signature compatability

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#16053]

**Comment by jmintb** [comment]
I am up for working on this :)

**Comment by Veykril** [comment]
Okay, so the bigger picture here would be to have `type_match` consider coercions I think (which should fix this technically). But that seems a lot more tricky to get right, so instead we should just have `compute_type_match` consider `FnDef`s and the like specially which we can do via `Type::as_callable` I think. Roughly, we just need to check whether both types are "callables" and then match them according to the callables instead.

**Comment by Veykril** [comment]
@jmintb I'm sorry, I just realized that was roughly what you were doing in your commit already (how embarassing) 😅 I think I misread something there yesterday when fixing up the PR. Can you just re-implement that part as a new PR (and maybe put the actual equivalence check logic behind a function in `Callable`?

**Comment by jmintb** [comment]
No worries, I will do as you suggest :)

**Comment by Veykril** [comment]
Fixed in https://github.com/rust-lang/rust-analyzer/pull/16136
