### ISSUE TITLE
Panic on inner attributes in presence of unresolved crate

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/rust-analyzer#16063]
This code:
```Rust
#[macro_use]
extern crate doesnotexist;

mod _test_inner {
    #![empty_attr]
}
```
Panics:
```
thread 'Worker' panicked at crates/hir/src/lib.rs:1010:21:
cannot find attribute #0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/core/src/panicking.rs:72:14
   2: hir::precise_macro_call_location
   3: hir::emit_def_diagnostic_
   4: hir::Module::diagnostics
   5: ide_diagnostics::diagnostics
   6: std::panicking::try
   7: ide::Analysis::with_db
   8: ide::Analysis::assists_with_fixes
   9: rust_analyzer::handlers::request::handle_code_action
  10: std::panicking::try
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
```
I investigated a bit, and it seems the problem is that `AttrDocCommentIter` does not iterate over inner attributes, since inner attributes are not direct children of the item.

What is the best way to fix this? Making `AttrDocCommentIter` iterate over descendants instead of children doesn't look great performance-wise, iterating over the node that might contain inner attributes is the solution I think but makes the code a bit ugly. Also, how inner attributes work at all? It seems the responsible code for detecting attributes (both inner and outer) is the `AttrDocCommentIter` which is broken. But inner attributes work, for example `#![doc]` will appear in the hover, so maybe we can drop `AttrDocCommentIter` in favor of reusing that code.

**Comment by Veykril** [comment]
How does this panic? It works fine for me if I paste this somewhere.

Anyways, the attribute queries already handle this discrepancy, so `#precise_macro_call_location` should just do the same imo or whatever is causing the panic here

**Comment by HKalbasi** [comment]
It panics for me if I paste it inside the r-a itself. No query fails and there is no error notification on vscode, but the server restarts and log appears.

**Comment by Veykril** [comment]
Ah it happens to me as well now, odd, Anyways, `precise_macro_call_location` should be fixed by just using `hir_expand::attrs::collect_attrs` instead
