### ISSUE TITLE
hover paniced

### ISSUE THREAD

**Issue by pfwang80s** [rust-lang/rust-analyzer#16097]
> Panic context:
> 
> version: 0.3.1766-standalone (457b966b1 2023-12-10)
> request: textDocument/hover HoverParams {
>     text_document: TextDocumentIdentifier {
>         uri: Url {
>             scheme: "file",
>             cannot_be_a_base: false,
>             username: "",
>             password: None,
>             host: None,
>             port: None,
>             path: "/Users/pengfei.wang/log-server/controller-core/src/lib.rs",
>             query: None,
>             fragment: None,
>         },
>     },
>     position: Position(
>         Position {
>             line: 59,
>             character: 20,
>         },
>     ),
>     work_done_progress_params: WorkDoneProgressParams {
>         work_done_token: None,
>     },
> }
> 
> thread 'Worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/line-index-0.1.0-pre.1/src/lib.rs:148:35:
> invalid offset
> stack backtrace:
>    0: _rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::option::expect_failed
>    3: rust_analyzer::lsp::to_proto::range
>    4: rust_analyzer::lsp::to_proto::location_from_nav
>    5: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
>    6: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
>    7: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
>    8: rust_analyzer::handlers::request::handle_hover
>    9: std::panicking::try
>   10: core::ops::function::FnOnce::call_once{{vtable.shim}}
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> [Error - 1:56:48 PM] Request textDocument/hover failed.
>   Message: request handler panicked: invalid offset
>   Code: -32603

**Comment by wyatt-herkamp** [comment]
[https://github.com/rust-lang/rust-analyzer/issues/12715#issuecomment-1850253444](https://github.com/rust-lang/rust-analyzer/issues/12715#issuecomment-1850253444)  
  
I am getting the same thing.
