### ISSUE TITLE
Auto create file

### ISSUE THREAD

**Issue by zuobaoquan** [rust-lang/rust-analyzer#16111]
There was a code action to auto create file for non-exist module. It was so convenient.

mod foo;

**Comment by zuobaoquan** [comment]
It is simple to reproduce. (Win11, Parallel Desktop 19.1.1, macOS 14.1.2)

<img width="1040" alt="Screenshot 2023-12-13 at 17 59 55" src="https://github.com/rust-lang/rust-analyzer/assets/740504/abc7ba85-651b-4095-b9dc-8c3009d5a172">

**Comment by Veykril** [comment]
![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/eae71a29-d22e-4c76-b942-95cd0bd6b1d3)
what rust-analyzer version are you using? (running the `Show RA version` command)

**Comment by zuobaoquan** [comment]
rust-analyzer version: 0.3.1766-standalone (457b966b1 2023-12-10)

It is a simple local project (C:\projects\xx). I has been for some time. I just tried run vscode as admin, it also failed.

Version: 1.85.0 (user setup)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by zuobaoquan** [comment]
I just tried VSCode Inside on my machine, it worked.

**Comment by zuobaoquan** [comment]
Thanks for your time! I have addressed the issue. It was caused by the setting:

```
"rust-analyzer.diagnostics.enable": false,
```
