### ISSUE TITLE
Formatting for trailing whitespace failed on comment separated multi-line expression

### ISSUE THREAD

**Issue by JonnyTischbein** [rust-lang/rust-analyzer#16116]
I ended up with the following code, which will fail to format.
```rust
fn main() {
    let x = 1234 
        // important command!
        + 567;
    println!("x: {}", x);
}
```
The code compiles and runs correctly, as does autocompletion.

Cargo is also unable to format this code:
```
❯ cargo fmt
error[internal]: left behind trailing whitespace
 --> /tmp/testing_rust/src/main.rs:2:2:17
  |
2 |     let x = 1234 
  |                 ^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

The problem does not occur and the formatting works if I move the comment out of the multiline addition.
```rust
fn main() {
    // important command!
    let x = 1234 
        + 567;
    println!("x: {}", x);
}
```

I can see that this may not be good code style, but it should not cause the file formatting to fail.

**rust-analyzer version**: 2023-12-11 (Mason)

**rustc version**:  1.73.0-nightly (28eb857b9 2023-08-12)

**relevant settings**:  none

**Comment by Veykril** [comment]
This is a [rustfmt](https://github.com/rust-lang/rustfmt/) issue, not a rust-analyzer one.
