### ISSUE TITLE
RA enable miri by default and cannot disable it

### ISSUE THREAD

**Issue by huang-jl** [rust-lang/rust-analyzer#16122]
I am reading codes of rust-vmm project, there is a code snippet like in the following:

```rust
 #[cfg(not(miri))]
if addr == libc::MAP_FAILED {
    return Err(Error::Mmap(io::Error::last_os_error()));
}

#[cfg(miri)]
if self.size == 0 {
    return Err(Error::Mmap(io::Error::from_raw_os_error(libc::EINVAL)));
}
```

Note that there are both `cfg(miri)` and `cfg(not(miri))`.

However, I found that PR #15284 has enabled `cfg(miri)` in analysis by default.

Currently my editor deactivates all the code blocks annotated with `#[cfg(not(miri))]`, and I do not know how to activate those blocks or disable `cfg(miri)`.

<img width="1020" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/49710099/58813c30-9246-4b22-b548-e2f29b3d912e">

Is there any possible  method in RA to activate code blocks with `#[cfg(not(miri))]`?

**Comment by mccolljr** [comment]
I just ran into this as well - I don't mind this as a default, but it would be nice to have an escape hatch.

**Comment by huang-jl** [comment]
@mccolljr I think currently there is no way to activate the lsp functionality on those blocks with `#[cfg(not(miri))]`. It is inconvenience for me at least.

**Comment by mbyt** [comment]
I just ran into this as well.
