### ISSUE TITLE
"{N} Implementations" hint is repeated 

### ISSUE THREAD

**Issue by landaire** [rust-lang/rust-analyzer#16157]
When examining a struct generated with ouroboros, the hint specifying the number of implementations is repeated as shown in this screenshot:

![CleanShot 2023-12-18 at 14 42 52@2x](https://github.com/rust-lang/rust-analyzer/assets/1313522/f060db62-6a5f-4e6b-84df-8cbb5dc8abcc)

To reproduce, clone ouroboros:

```
$ git clone https://github.com/joshua-maros/ouroboros
```

Then view one of the examples in `examples/src/lib.rs`.

I think this probably surfaces as a side effect of the crate's code generation, but clicking any of the repeated "implementations" hints shows exactly the same data.

**rust-analyzer version**: 

```
rust-analyzer version: 0.4.1772-standalone (21b06c1be 2023-12-15)
```

**rustc version**:

```
rustc 1.76.0-nightly (5facb422f 2023-11-28)
```

**Comment by rben01** [comment]
In the attached screenshot, is it repeated 8 times (once per implementation)?

**Comment by landaire** [comment]
It seems to be repeated infinitely based on editor width. In my own project where I first noticed it, there are 9 implementations but I counted at least 9. This video shows it a bit better

https://github.com/rust-lang/rust-analyzer/assets/1313522/43528a9b-13d2-4f42-bc0b-a67decfcb0f1

**Comment by Young-Flash** [comment]
seems not infinitely repeated for all case

![image](https://github.com/rust-lang/rust-analyzer/assets/71162630/0288af54-f807-4f59-98b0-471f244a24dd)

**Comment by Veykril** [comment]
Cause is most likely that the struct name's span is being reused for a bunch of other ADT defs / trait definitions. A bit weird that such an impl here affects all of them though, anyways t his is a new bug from the span map rewrite I imagine. We should probably only check for the same identifier mapping here.
![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/ad9b7fb3-6ee7-4321-837e-9d0272312d2b)

**Comment by landaire** [comment]
@Veykril thanks for taking a look and for the the quick fix!
