### ISSUE TITLE
Can't find own Internal "core" module with no_std

### ISSUE THREAD

**Issue by MaxGraey** [rust-lang/rust-analyzer#16166]
I guess it relate to this issue: https://github.com/rust-lang/rust-analyzer/issues/13600
But in a slightly different context.

Project structure:
```
src/
├─ core/
│  └─ mod.rs
└─ lib.rs
```
where `lib.rs` contain:
```rs
#![no_std] // it's important!

pub mod ..
pub mod core; // <- analyzer can't find this module
```
And analyzer can't find this module. Error message:
```
unresolved module, can't find module file: core.rs, or core/mod.rs
rust-analyzer[E0583](https://doc.rust-lang.org/stable/error_codes/E0583.html)
```

Although the diagnostics of the Rust compiler itself does not see any problems in it and checks and compile it.
If you rename the module everything is fine, respectively the problem is in the name of the module itself, which is apparently perceived as a global core module.

**rust-analyzer version**: latest (nightly)

**Comment by Young-Flash** [comment]
can't reproduct on latest nightly, am I missing something?
![image](https://github.com/rust-lang/rust-analyzer/assets/71162630/2003fab8-dc6f-4254-9e11-d614d21680c3)

**Comment by MaxGraey** [comment]
Hmm, It seems to be fixed after the restart lang server. Try to rename / refactor `core` to something different and revert it back. Maybe it'll trigger issue. Anyway, it doesn't seem to be that big of a problem, so I'm closing the issue. Thank you for pointing out this problem
