### ISSUE TITLE
Add README.md to line-index crate

### ISSUE THREAD

**Issue by homersimpsons** [rust-lang/rust-analyzer#16180]
I recently came across https://crates.io/crates/line-index, but the page looks rather empty.

The short-description explains a bit what is the purpose of this crate:
> Maps flat `TextSize` offsets to/from `(line, column)` representation

But I think a README.md file explaining what is the purpose of this crate and how to use it may help contributors and other people using it.

Crate source: https://github.com/rust-lang/rust-analyzer/tree/master/lib/line-index

**Comment by lnicola** [comment]
Good idea, do you want to file a PR?

**Comment by homersimpsons** [comment]
> do you want to file a PR?

I would like to fill a PR, but does not really know anything about this crate.

If you don't have time to create it, I will dig a bit in the code to understand and document it.
