### ISSUE TITLE
Auto-publishing fails because of the `toolchain` crate

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#16194]
I don't see anything wrong, but...

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/3f8dea7a-7d28-4dab-b0db-0eba260d75ea)

**Comment by pksunkara** [comment]
Hmm... I don't have any idea what's happening here. I guess that this proc-marco-test should not be excluded from workspace members, if it depends on a workspace member.

**Comment by Veykril** [comment]
Why is it even considered for auto-publishing? It should not be published given its set `publish = false`.

**Comment by Veykril** [comment]
Anyway, that crate can probably be included again (and just the `imp` crate excluded as before). Can't recall why I changed that.
