### ISSUE TITLE
VSCode: Importing module autocompletes preceding characters instead of replacing

### ISSUE THREAD

**Issue by f-pazos** [rust-lang/rust-analyzer#16193]
When I press `cmd+i` to select an import for a struct/module I've already typed out, VSCode will insert the entire object name before the cursor instead of replacing/ignoring the name that is already in the text. 

For example, if I try to select the correct import with my cursor like this: `PathB|uf`, hitting enter will complete preceding word, ignoring what comes after the cursor: `PathBufuf`

This behavior happens whether I import by clicking on the popup modal, or selecting with the keyboard and hitting enter. I usually use Vim, although I've disabled it to record the example.

I'm on MacOS Sonoma 14.2, although this has happening since before I updated. 

Issue appears to happen both on the nightly and stable releases of Rust Analyzer. I tried uninstalling and reinstalling the extension, and the issue is still there.

https://github.com/rust-lang/rust-analyzer/assets/12696506/293ca7ea-3a0c-4d76-be9d-a0b8585293a6

## About Visual Studio Code Output
Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 23.2.0

**Comment by Young-Flash** [comment]
seems it's a vscode issue. 

![image](https://github.com/rust-lang/rust-analyzer/assets/71162630/d44c5ea4-037b-4aff-89be-ee7df4568efb)

when I try "ctrl+i" on TypeScript code, similar thing happen

![show](https://github.com/rust-lang/rust-analyzer/assets/71162630/ca473dab-ce0c-4d56-afd5-c7c5a03dde44)

if you try RA quickfix, it works well

![assist](https://github.com/rust-lang/rust-analyzer/assets/71162630/c80f6e6b-fd68-40ad-9481-d182373ec27a)

**Comment by Veykril** [comment]
It's not a bug, there is a VSCode setting for this behavior, I don't recall the name right now. (it's a general lsp feature, so not r-a specific)

**Comment by f-pazos** [comment]
Ah, good to know. I tried repro-ing with Go but it looks like the extension handles auto-imports differently. I'll look around and reach out to the VSCode team for help if I still can't figure it out.

**Comment by Veykril** [comment]
The setting is `"editor.suggest.insertMode": "replace"`, the default is `"insert"` which is the behavior you are observing here.
