### ISSUE TITLE
Manual textDocument/onTypeFormatting request not working

### ISSUE THREAD

**Issue by weilbith** [rust-lang/rust-analyzer#16192]
Hey 👋🏾 

I currently try to play around with the [on type formatting](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_onTypeFormatting) feature. The goal is to implement some integration into the NeoVim editor. The `rust-analyzer` is one of the few servers I know which support this feature. I looked at the [manual](https://rust-analyzer.github.io/manual.html#on-typing-assists) and also inspected the server capabilities for the `documentOnTypeFormattingProvider` sent by the analyzer./

Taking the example of the linked manual with this code in a clean project (just `cargo intit .`):

```rust
fn main() {
  let greeting = "Hello, World"
}
```

If I now make a request to the analyzer for the `textDocument/onTypeFormatting` with the following parameter, the response is simply empty.

```json
{
  "textDocument": {
    "uri": "file:///tmp/tmp.r8oeV3GkOw/foo/src/main.rs"
  },
  "position": {
    "character": 17,
    "line": 1
  },
  "ch": "=",
  "options": {
    "insertSpaces": true,
    "tabSize": 4
  }
}
```

What am I doing wrong? How can I get a response with a `TextEdit` that adds the semicolon?

**Comment by Veykril** [comment]
You probably want to sent that request with the source text missing the `=`, that is
```rs
fn main() {
  let greeting  "Hello, World"
}
```

**Comment by weilbith** [comment]
Thanks for the quick reply! 😃

Okay, that is interesting. I couldn't try it yet (mobile only).

Here is a short excerpt from the specification for the parameter:

```typescript

interface DocumentOnTypeFormattingParams {
	// ...

	/**
	 * The position around which the on type formatting should happen.
	 * This is not necessarily the exact position where the character denoted
	 * by the property `ch` got typed.
	 */
	position: Position;

	/**
	 * The character that has been typed that triggered the formatting
	 * on type request. That is not necessarily the last character that
	 * got inserted into the document since the client could auto insert
	 * characters as well (e.g. like automatic brace completion).
	 */
	ch: string;

   // ...
}
```

I read this like the request parameter should be allowed to be a little "squishy" and it is expected that more typing is happening. 

How would I be expected to implement this now? Do I have to intercept users inputs and filter every (character matching) keystroke through the server with such a request? 🤔

Thanks for the help! 🙏

**Comment by weilbith** [comment]
Okay, so I tried your idea without the `=` sign in the buffer, but with the same request. Still nothing. I tried to vary the `position` a little, but no luck. 
Am I completely off here? 🤔

**Comment by Veykril** [comment]
Unsure what could be going wrong here then, might be good to add some debug prints in the on type formatting handlers then

**Comment by weilbith** [comment]
I enabled trace logging in VSCode to see what message it sends to the rust-analyzer, just to realize it works for me now. I seriously don't know what I have changed in-between. 😑 

I'm sorry! Thank you very much for the help anyhow. 🙏🏾
