### ISSUE TITLE
The behavior of the `Self` type in the `Extract struct from enum variant` option is not as expected

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust-analyzer#16197]
The behavior of the `Self` type in the `Extract struct from enum variant` option is not as expected

## Source code
```rust
enum Foo {
    Bar { node: Box<Self> },
    Nil,
}

fn main() {}
```

in line2 column5 use `Extract struct from enum variant`

```rust
struct Bar{ node: Box<Self> }

enum Foo {
    Bar(Bar),
    Nil,
}

fn main() {}
```

## Expected
```rust
struct Bar { node: Box<Foo> }

enum Foo {
    Bar(Bar),
    Nil,
}

fn main() {}
```

**rust-analyzer version**: `rust-analyzer 1.74.0 (79e9716c 2023-11-13)` or `rust-analyzer 1.77.0-nightly (bf8716f1 2023-12-24)`

**rustc version**: `rustc 1.74.0 (79e9716c9 2023-11-13)` or `rustc 1.77.0-nightly (bf8716f1c 2023-12-24)`

**relevant settings**: NONE

**Comment by Young-Flash** [comment]
should check `GenericArg` at
https://github.com/rust-lang/rust-analyzer/blob/85fb463fc586594925f05fc8e285b1568f98f41a/crates/ide-assists/src/handlers/extract_struct_from_enum_variant.rs#L128-L134

I'll take a try, @rustbot claim
