### ISSUE TITLE
proc-macro server's api version (3) is newer than rust-analyzer's (2)

### ISSUE THREAD

**Issue by ogcatt** [rust-lang/rust-analyzer#16198]
**rust-analyzer version**: v0.4.1567-standalone

**rustc version**: rustc 1.77.0-nightly (d6d7a9386 2023-12-22)

**relevant settings**: none

Using leptos with nightly rust. Installed both standard release and pre-release of this package in vscode and both give me this error:

`[ERROR rust_analyzer::reload] Failed to run proc-macro server from path /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/libexec/rust-analyzer-proc-macro-srv, error: Custom { kind: Other, error: "proc-macro server's api version (3) is newer than rust-analyzer's (2)" }`

This happens on the `#[component]`, `view!` and `style!` macros in leptos.

Any help would be appreciated.

**Comment by lnicola** [comment]
> rust-analyzer version: v0.4.1567-standalone

Latest version is 0.4.1783. At one per day, yours seems rather old.

**Comment by mankinskin** [comment]
Update your vs code version to see latest extension versions

**Comment by ogcatt** [comment]
I am using open-vsx (in vscodium), I wonder if that is the issue

**Comment by ogcatt** [comment]
![image](https://github.com/rust-lang/rust-analyzer/assets/119142199/9bebb7be-630d-4cfd-9145-324b617bf300)
Ok this may be a bug on my end let me see

**Comment by ogcatt** [comment]
Ok, for some reason my vscodium was severely out of date. Updated and I can now install the latest vers.
