### ISSUE TITLE
build err/fail

### ISSUE THREAD

**Issue by Shane-XB-Qian** [rust-lang/rust-analyzer#16216]
not sure if you had noticed following build err, surprised it was there some weeks.. :smile:

```log
   Compiling proc-macro-api v0.0.0 (/home/shane/foo/crates/proc-macro-api)
warning: unknown lint: `private_bounds`
   --> crates/hir-expand/src/files.rs:103:9
    |
103 | #[allow(private_bounds)]
    |         ^^^^^^^^^^^^^^ help: did you mean: `trivial_bounds`
    |
    = note: `#[warn(unknown_lints)]` on by default

   Compiling lsp-types v0.95.0
   Compiling lsp-server v0.7.4
   Compiling lsp-server v0.7.5 (/home/shane/foo/lib/lsp-server)
   Compiling project-model v0.0.0 (/home/shane/foo/crates/project-model)
error[E0445]: private trait `FileIdToSyntax` in public interface
   --> crates/hir-expand/src/files.rs:104:1
    |
83  | trait FileIdToSyntax: Copy {
    | -------------------------- `FileIdToSyntax` declared as private
...
104 | impl<FileId: FileIdToSyntax, T> InFileWrapper<FileId, T> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private trait

For more information about this error, try `rustc --explain E0445`.
warning: `hir-expand` (lib) generated 1 warning
error: could not compile `hir-expand` (lib) due to previous error; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
```

**rust-analyzer version**: 
rust-analyzer 0.0.0 (255eed40c 2023-11-17)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.70.0 (90c541806 2023-05-31)

**Comment by lnicola** [comment]
We don't really support building with old compiler versions.

**Comment by Shane-XB-Qian** [comment]
> old compiler versions

um, you mean rustc? which version it should be?

**Comment by lnicola** [comment]
1.74, maybe?

**Comment by Shane-XB-Qian** [comment]
ok, thanks. 
but seems a bit sensitive, 1.75 compiled not sure why it looked functional nothing (get nothing msg from lsp server), 
but change to 1.74, worked fine, donot know if you can repro it, but anyway 1.74 worked fine.

**Comment by lnicola** [comment]
As long as it builds, the version should make no difference, so there must have been something wrong with your setup.

The binaries on GitHub Releases and in the VS Code extension are always built using stable.

**Comment by Shane-XB-Qian** [comment]
ok, but no idea, i was just saying the result:
- 1.70 build failed like ticket description;
- then using stable which is now 1.75, build ok, but get nothing (no msg from lsp server);
- then build another project with 1.74, build ok, worked ok, then turn to build this again, then build ok, worked ok.

**Comment by lnicola** [comment]
> then using stable which is now 1.75, build ok, but get nothing (no msg from lsp server);

I understood, but that shouldn't be the case.
