### ISSUE TITLE
No actions for proc macro traits

### ISSUE THREAD

**Issue by marcfir** [rust-lang/rust-analyzer#16214]
Traits generated with a proc macro do not support actions like `Implement missing members`

**rust-analyzer version**: 0.3.1782
**rustc version**: rustc 1.77.0-nightly
**relevant settings**:
   * rust-analyzer.procMacro.enable: true

**Comment by marcfir** [comment]
I found out that it works.
The problem is that when you change code in a macro, the rust-analyzer macro server is not automatically rebuilt. You have to start `Rebuild Proc Macros` manually.

**Comment by Veykril** [comment]
Starting monday, r-a should autorebuilt them on next file save. I'll close this then
