### ISSUE TITLE
better error recovery for `USE_TREE_LIST` parsing

### ISSUE THREAD

**Issue by Young-Flash** [rust-lang/rust-analyzer#16227]
currently a syntax error in `USE_TREE_LIST` will make the rest parsing incorrectly.

![image](https://github.com/rust-lang/rust-analyzer/assets/71162630/6fc55bb0-b22f-42fc-b15b-e6f7f41f79b4)

**Comment by lnicola** [comment]
CC https://github.com/rust-lang/rust-analyzer/pull/4680
