### ISSUE TITLE
After upgrading to v0.3.1791 "Go to definition" moves me to the first line of `impl` instead of the method name

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/rust-analyzer#16229]
**rust-analyzer version**: v0.3.1791

**rustc version**: rustc 1.74.1 (a28077b28 2023-12-04)

After upgrading to v0.3.1791 "Go to definition" moves me to the first line of `impl` instead of the method name.

**Comment by frederikhors** [comment]
The code is complicated... I cannot right now create a complete reproduction. Sorry.

**Comment by frederikhors** [comment]
I noticed the problem is occurring when I use `#[async_trait::async_trait]` on `impl`s.

So, with macros maybe?

**Comment by Veykril** [comment]
Yes the macro is most likely the cause, the mapping out of the proc-macro most likely goes to the call site for some reason, that should suffice to investigate.

**Comment by Veykril** [comment]
It is already on the nightly r-a (pre-)release, otherwise it will release on the stable release on monday.

**Comment by jayjose1** [comment]
still open for node runner
