### ISSUE TITLE
Completion for output of proc macro that depends on external file doesn't update when external file is modified.

### ISSUE THREAD

**Issue by basro** [rust-lang/rust-analyzer#16243]
I've implemented a proc macro that generates a struct with fields that depend on the content of an external file.

At first rust analyzer correctly executes the proc macro and I get completion for the fields of the struct.
However, if I modify the contents of the external file in a way in which the struct fields would change, the completion infromation gets stuck in the initial execution and never updates to reflect the changes made to the external file.

On the other hand, squiggly line errors will correctly reflect the changes in the external file upon saving any .rs file.

My questions:
1. Is there any way in which I can make my proc macro work properly with RA and have it update the completion information upon save like errors do?
2. If (1) is not possible then is there a way to tell RA to reevaluate the proc macros in a crate? (Using VSCode)

**Comment by Veykril** [comment]
rust-analyzer caches the expansions of proc-macros (we are required to do this for architectural reasons), this won't change. So right now there isn't really anything you can do here aside from touching the macro call to make r-a re-execute it. There is a nightly API that would allow tracking the file https://doc.rust-lang.org/proc_macro/tracked_path/index.html but that is also not yet implemented in rust-analyzer.

**Comment by Veykril** [comment]
You can use the following setting to have r-a ignore certain proc-macro expansions:
```json

    "rust-analyzer.procMacro.ignored": {
        "proc-macro-crate": ["proc-macro-name"]
    },
```
