### ISSUE TITLE
Rust analyzer not highlighting conditional complication branches if cfg is given by build.rs

### ISSUE THREAD

**Issue by publicqi** [rust-lang/rust-analyzer#16244]
**rust-analyzer version**: 0.3.1791-standalone (9db515503 2024-01-01)

**rustc version**: rustc 1.76.0-nightly (87e1447aa 2023-11-30)

**relevant settings**: N/A

<img width="1430" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/56060664/9dfd2517-7a1f-49f7-a8f1-1fbe7dba58ce">

As shown in the screenshot, build.rs will output `cargo:rustc-cfg=feature="foo"`, which will set the feature of `foo`. Therefore, line 2 and 3 should be highlighted.

**Comment by Veykril** [comment]
You need to restart the server currently or issue a proc-macro rebuild for changes in the build script to take effect. It works for me then.

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/16247 should help out here, this case shouldnt need server restarting afterwards
