### ISSUE TITLE
'No such associated item' when using some structs which derived the 'Default' trait in the crate 'wgpu'

### ISSUE THREAD

**Issue by zerodegress** [rust-lang/rust-analyzer#16295]
**rust-analyzer version**: rust-analyzer version: 0.4.1797-standalone (f595e60b6 2024-01-06)

**rustc version**: rustc 1.74.0 (79e9716c9 2023-11-13)

**relevant settings**: no

![图片](https://github.com/rust-lang/rust-analyzer/assets/60560055/a9ec7e9b-44cc-4a2b-8802-17ee766b834c)
![图片](https://github.com/rust-lang/rust-analyzer/assets/60560055/5e7a3be2-39c4-4e9c-b81f-75e97e9baab6)

Just like these pictures showed.It is confusing that the cargo check is ok but RA not.
The only used dependency is wgpu@0.17.

![图片](https://github.com/rust-lang/rust-analyzer/assets/60560055/a523df64-6edc-480a-8888-0f4cd352b371)

**Comment by Veykril** [comment]
`wgpu` has `core` module/import alias which trips us up in the derives here since we are still lacking hygienic name resolution.

**Comment by lnicola** [comment]
https://github.com/rust-lang/rust-analyzer/issues/13600 and probably others.

**Comment by alshdavid** [comment]
Does this share the same cause? https://github.com/RustCrypto/hashes/issues/529

**Comment by lnicola** [comment]
@alshdavid I don't think so, but we have a bunch of type inference issues with the RustCrypto crates. That one is probably https://github.com/rust-lang/rust-analyzer/issues/15242.

**Comment by Veykril** [comment]
Hmm, actually, I just realized we should be able to use `$crate` correctly now, since that hygiene is (or should be) correctly implemented.
