### ISSUE TITLE
Change "extract variable" to allow extracting literals, not just expressions.

### ISSUE THREAD

**Issue by camercu** [rust-lang/rust-analyzer#16305]
Suppose I had a statement like so:

```rust
let result = some_complicated_computation(arg1, arg2, arg3, "annoyingly long literal of text");
```

I'd like to be able to put my cursor inside the str literal (or a numeric literal) and have the option to run a refactoring code action to extract the literal into a variable. The result of running this on the previous example would be:

```rust
let var_name = "annoyingly long literal of text";
let result = some_complicated_computation(arg1, arg2, arg3, var_name);
```

The refactoring can improve readability or set the code up for further refactorings (like moving the variable to a parameter/field).

Currently when I try to do this (in VSCode), I get no such option.

**Comment by Young-Flash** [comment]
https://github.com/rust-lang/rust-analyzer/pull/15809 should resolve this, what's your RA version?

![demo](https://github.com/rust-lang/rust-analyzer/assets/71162630/3d9bff7f-2c44-4998-b36c-64dcef6aab7d)

**Comment by camercu** [comment]
Closing issue. Resolved
