### ISSUE TITLE
VFS takes too much memory

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#16301]
Now arguably this is also a fault of the bevy crate depending on `4` versions of the `windows` crate, but a bare bevy project consumes 800mb of memory just for us to hold the entire source in memory in the VFS (without any windows source files its ~`90mb`. This is beyond excessive, especially when you realize that this is doubled once we put the source into salsa in a normalized form! We definitely need to rethink our strategy here.

**Comment by lnicola** [comment]
Not even compressing individual files will help here, that won't get us more than 50% off.

**Comment by Veykril** [comment]
Yes this is tricky. Assuming we can't do anything for the normalized files in salsa for the time being, we can at least drop the unnormalized files from the VFS for non workspace members I think. The only purpose they have is for processing `DidChangeTextDocument` notifications which can have diffs, but for library files, they shouldnt really ever change so incurring IO when processing an event for such a file should be fine. That would get rid of a big chunk of memory waste here at least (~35-40%).
