### ISSUE TITLE
Should rust-analyzer say something when a bool is not used

### ISSUE THREAD

**Issue by Aym3nJ** [rust-lang/rust-analyzer#16332]
Hello,
This is my first issue ever, so i will try to keep it short..
The Rust-analyzer always mention it when there's a code that is "unused" but when you put a `false;` or `true;` in any line and its not useful  (except if i don't know what the use case of that will be) nor rust-analyzer  nor the compiler say anything.
Thank you

**Comment by Young-Flash** [comment]
IMO, `false;` (or `true;`) is an expr stmt in term of AST, some expr may with some side effect, like the following `test();`:

```rust
fn main() {
    test();
}

fn test() {
    println!("hello");
}
```

**Comment by Aym3nJ** [comment]
> IMO, `false;` (or `true;`) is an expr stmt in term of AST, some expr may with some side effect, like the following `test();`:
> 
> ```rust
> fn main() {
>     test();
> }
> 
> fn test() {
>     println!("hello");
> }
> ```

but it's useless in this case:
```rust
fn main() {
    true;
}
```

is it not?

**Comment by Young-Flash** [comment]
it is. Should matching among `Expr` to deal with this case(`Literal(Literal)`)

https://github.com/rust-lang/rust-analyzer/blob/ae6e73772432cfe35bb0ff6de6fdcfa908642b67/crates/syntax/src/ast/generated/nodes.rs#L1607

**Comment by Aym3nJ** [comment]
> it is. Should matching among `Expr` to deal with this case(`Literal(Literal)`)
> 
> https://github.com/rust-lang/rust-analyzer/blob/ae6e73772432cfe35bb0ff6de6fdcfa908642b67/crates/syntax/src/ast/generated/nodes.rs#L1607

Ah i see , Thank you for your time, have a nice one
