### ISSUE TITLE
Getting proc macro not expanded: No proc-macros present for crate rust-analyzer (unresolved-proc-macro) on macos

### ISSUE THREAD

**Issue by kt390256** [rust-lang/rust-analyzer#16331]
rust-analyzer version: rust-analyzer version: v0.3.1799 ([https://github.com/rust-lang/rust-analyzer/commit/9db515503f11bda7812cdfb9c2839f70f4cb1fdd 2024-01-01](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-01-08))

OS: MacOS 14.2.1 (23C71)

rustc version: rustc 1.75.0 (82e1608df 2023-12-21)

relevant settings: none
![Screenshot 2024-01-09 at 5 43 16 PM](https://github.com/rust-lang/rust-analyzer/assets/28064695/807cf0d3-c81d-4463-81ed-34680c7f88ee)
![Screenshot 2024-01-09 at 5 46 32 PM](https://github.com/rust-lang/rust-analyzer/assets/28064695/25df6dce-58fe-47c8-ad6e-f87dfd9488c5)

Any effort will be appreciated!

**Comment by Veykril** [comment]
Have you tried clearing your target dir? I've seen this error happen when upgrading my toolchain from time to time (not quite sure why that error specifically happens then).

**Comment by Systemcluster** [comment]
I'm seeing the same error since ~2 weeks ago with Rust nightly (currently `rustc 1.77.0-nightly (6ae4cfbbb 2024-01-17)`). Deleting the `target` directory doesn't help.

In my case it errors on a `#[cfg_attr(feature = "std", derive(thiserror::Error))]` with `proc macro 'feature' not expanded: No proc-macros present for crate` at `feature = "std"`.

There's no output in the "Rust Analyzer Language Server" logs.

**Comment by stjepangolemac** [comment]
Also happening to me when deriving `clap::Parser` in the Helix editor. There's nothing interesting in the logs.

**Comment by Veykril** [comment]
There has been a breaking change in cargo afaik that breaks package ids which `cargo metadata` does not handle correctly. This should be fixed by the next rustc nightly.

**Comment by martinlindhe** [comment]
Thanks, @Veykril. I had this too for a little while, and updating nightly to `rustc 1.77.0-nightly (88189a71e 2024-01-19)` fixes it for me.

**Comment by shitcodebykaushik** [comment]
It happing now tooo.  And i am getting lost in searching the  the solution.

**Comment by Veykril** [comment]
Please open a new issue and fill out the template, including what operating system you are on and what error(s) you are getting

**Comment by mthmcalixto** [comment]
try 

settings.json:
```json
{
    "rust-analyzer.procMacro.enable": true
}
```

**Comment by modecode22** [comment]
> try
> 
> settings.json:
> 
> ```json
> {
>     "rust-analyzer.procMacro.enable": true
> }
> ```

Thanks

**Comment by flodiebold** [comment]
> try
> 
> settings.json:
> 
> ```json
> {
>     "rust-analyzer.procMacro.enable": true
> }
> ```

That won't fix it. This setting is true by default, and it being disabled wouldn't lead to the original error.

**Comment by bionicles** [comment]
same issue 
![image](https://github.com/user-attachments/assets/53ba7d11-7e46-4dae-98c3-61867e2fc842)

**Comment by Anatoly03** [comment]
![Image](https://github.com/user-attachments/assets/15468075-f91a-4a60-ae35-28126911d9d5)

Related?

**Comment by ChayimFriedman2** [comment]
@Anatoly03 This is a different problem. Please open a new issue, and include a minimal reproducible example (if you can) and rust-analyzer's logs (available on VSCode under Output->Rust Analyzer Language Serve).
