### ISSUE TITLE
rust analyzer thinks function body including `{` and `}` is an expression

### ISSUE THREAD

**Issue by antonilol** [rust-lang/rust-analyzer#16344]
**rust-analyzer version**: 0.4.1801-standalone

**rustc version**: rustc 1.75.0 (82e1608df 2023-12-21)

**relevant settings**: None

```rust
fn function() -> i32 {
    42
}
```
when selecting the `{` and hovering over it the whole `{ 42 }` part gets highlighted
![image](https://github.com/rust-lang/rust-analyzer/assets/49868160/952c373d-020f-4ef1-967b-d4b11f4798a3)

previously (i wanted to report this with this issue but found out it got fixed already) an assist would show up for functions with an empty body that have a `Result<(), _>` return type saying 'wrap in Ok(...)', this would wrap the braces of the function resulting in something like
```rust
fn function() -> Result<(), ()> Ok({ })
```
which (of course) causes syntax errors
just naming this here because i think it is related and might help with finding the cause and fixing it

**Comment by Veykril** [comment]
Technically the function body is just a block expression, it's just that only a block expression is valid as a function body, so hovering here showing this is not really considered a bug (unlike the wrap in ok quickfix which you mentioned). Thanks for raising that though 👍
