### ISSUE TITLE
Roots Scan Stuck - ahash

### ISSUE THREAD

**Issue by andre-di** [rust-lang/rust-analyzer#16382]
**rust-analyzer version**: 0.4.1809-standalone (03336460f 2024-01-16)

**rustc version**:  rustc 1.77.0-nightly (098d4fd74 2024-01-16)

**relevant settings**:
``` settings.json
{
    "rust-analyzer.linkedProjects": [
        ".\\Cargo.toml"   
    ],
    "rust-analyzer.check.command": "clippy",
    "rust-analyzer.server.extraEnv": { "RA_LOG": "info" }
}
```

Hi. My main problem is that rust analyzer seems to be stuck when scanning ```target\debug\build\ahash-feb304a413e0bcb2\out```

Notification
```
Roots Scanned: 0/329: target\debug\build\ahash-feb304a413e0bcb2\out
```

The other messages are for the same file the only difference is that it is in the .cargo/registry folder.

I have tried updating rust with rustup upgrade
Updated crate versions in my projects. 
I have tried different versions of rust-analyzer. Does not seem to make any difference other than that preview version gives information about where it is stuck.

No warnings or errors shown in the output from the language server.

**Comment by Veykril** [comment]
Yep noticed this as well, note that this is solely a stuck progress message. r-a itself works fine.

**Comment by andre-di** [comment]
For me r-a does not seem to work.

**Comment by Veykril** [comment]
That's an unrelated issue. Might be r-a having difficulties with one of those macros or type inference.
