### ISSUE TITLE
Can't stop cargo check

### ISSUE THREAD

**Issue by thewh1teagle** [rust-lang/rust-analyzer#16392]
I use `rust-analyzer` rarely because it works very slow for me.
When rust-analyzer server is stopped, every time I save something it runs `cargo check` in `vscode`
Even when the settings of `check_on_save` is false [here](https://github.com/thewh1teagle/vibe/blob/main/.vscode/settings.json)
Also, even when it's running, I can't stop `cargo check` in genreral.

**rust-analyzer version**: 0.3.1807

**rustc version**: rustc 1.75.0 (82e1608df 2023-12-21)

**relevant settings**: `settings.json` available in  [vibe](https://github.com/thewh1teagle/vibe)

**Comment by Veykril** [comment]
There is no way for r-a to invoke `cargo check` when the server is stopped as the server is the process that invokes it.

**Comment by thewh1teagle** [comment]
@Veykril 
You absolutely right. it was `Cargo` extension!

**Comment by lnicola** [comment]
Are you using the Rust Extension Pack? I wonder how many people are running cargo check twice without knowing. It's not a problem on small to medium projects, but still.

**Comment by Veykril** [comment]
We should probably check if the extension is installed and `checkOnSave` is set. Similar to how we warned about the old rust extension.

**Comment by thewh1teagle** [comment]
@lnicola 
It's a real problem even on small projects.
It was very annoying to use `r-a` + `cargo`. It slowed down my entire PC because it's similar to `cargo build`
So almost every save, change etc... I had slowness.
Now I turned off `r-a` and disabled `cargo check` on save in both `r-a` and `cargo` extensions and finally I can move faster.
Now I turn on `r-a` only when working with new crates to learn them faster.

@Veykril 
I think it worth checking if `cargo` extension already run it. not sure why we need `cargo check` and if it really ran twice, but I guess that anyway worth not even trying to run if already.

**Comment by thewh1teagle** [comment]
Does it possible to disable `r-a` to run when I open the project? and start only manually when I need?

**Comment by Young-Flash** [comment]
> Does it possible to disable `r-a` to run when I open the project? and start only manually when I need?

do you mean 

![image](https://github.com/rust-lang/rust-analyzer/assets/71162630/a26d4f98-c901-4456-98ae-de1d4e3aff04)

**Comment by Young-Flash** [comment]
> We should probably check if the extension is installed and `checkOnSave` is set. Similar to how we warned about the old rust extension.

I'd like to try working on it

**Comment by thewh1teagle** [comment]
> > Does it possible to disable `r-a` to run when I open the project? and start only manually when I need?
> 
> do you mean
> 
> ![image](https://private-user-images.githubusercontent.com/71162630/297937062-a26d4f98-c901-4456-98ae-de1d4e3aff04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDU2MzUsIm5iZiI6MTcwNTY0NTMzNSwicGF0aCI6Ii83MTE2MjYzMC8yOTc5MzcwNjItYTI2ZDRmOTgtYzkwMS00NDU2LTk4YWUtZGUxZDRlM2FmZjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MjIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMmQ5MTZiOTlkMTUwODc1MjFhOTMzMmNhZTdjMWRlNWJjYmViMTdhYWRhYWQ5OWU1NzBlZWI2MTQwNmNlMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nwf8C4XkJuHjhVG_iqJIB_DEFhHp8wMLjgUa6BWVwWI)

No.
`r-a` should store the state on the disk if the server should start or not.
And then if I stopped the server and reopened vscode it shouldn't start automatically.

**Comment by lnicola** [comment]
As you must already know, you can disable and enable it per VS Code workspace, which is similar to that.

If it feels too slow, you can also try to disable cache priming in the settings. It won't make it any faster, but projects will appear to take less time to load.

It might also be interesting to see why it's so slow. I've never used Tauri, is there any difference between how it behaves on the UI code and the rest?

**Comment by thewh1teagle** [comment]
> As you must already know, you can disable and enable it per VS Code workspace, which is similar to that.
> 
> If it feels too slow, you can also try to disable cache priming in the settings. It won't make it any faster, but projects will appear to take less time to load.
> 
> It might also be interesting to see why it's so slow. I've never used Tauri, is there any difference between how it behaves on the UI code and the rest?

I see, thanks for the point about workspace setting in vscode.
I think that a setting like `rust-analyzer.autoStart` is simplez useful and effective

**Comment by thewh1teagle** [comment]
> As you must already know, you can disable and enable it per VS Code workspace, which is similar to that.
> 
> If it feels too slow, you can also try to disable cache priming in the settings. It won't make it any faster, but projects will appear to take less time to load.
> 
> It might also be interesting to see why it's so slow. I've never used Tauri, is there any difference between how it behaves on the UI code and the rest?

I think that r-a became slow to me since I started split my projects into multiple workspaces, and also tauri has many dependencies, and another special thing with tauri is "hot reload" everytime you save it recompile so There's a race between `cargo check` and checks from r-a and the regular build

**Comment by lnicola** [comment]
Yeah, `cargo check` and `cargo build` should block each other. If you run `cargo check` twice, one will run and the other one will wait until it's ready, the complete more or less instantly.

Anyway, I disable `cargo check` and enable the experimental diagnostics, which takes care of that. But I guess even that is too slow for you?

**Comment by thewh1teagle** [comment]
@lnicola 
I didn't experimented with different settings, I'll try.
All I can say is since I disabled `r-a` and `cargo` extension my builds finally much faster and very lighter!
