### ISSUE TITLE
Rust analyzer does not respects project-level clippy directives?

### ISSUE THREAD

**Issue by acidnik** [rust-lang/rust-analyzer#16419]
I have a line in my `main.rs`:
`#![allow(clippy::redundant_field_names)]`
This way, when I run `cargo clippy` I don't see warnings about redundant field names

But RA shows me the notice anyway, both in neovim and vs code

Is this a bug or a feature? Is there a way to disable some clippy rules for whole project so that RA respects that?

**Comment by alibektas** [comment]
:wave: Could you share more context? Maybe a repro if you can?

**Comment by alibektas** [comment]
I believe that the person reported this issue has mistakenly taken a rust-analyzer native lint as one of clippy's own lint, as we also have a `redundant_field_name`. As such there is nothing wrong with our `flycheck`. The user may disable native diagnostics by declaring `rust-analyzer.diagnostics.disabled`.
