### ISSUE TITLE
rust-analyzer cannot trigger auto-complete in attribute macro

### ISSUE THREAD

**Issue by 3Xpl0it3r** [rust-lang/rust-analyzer#16418]
as title desribe rust-analyzer cannot trigger auto-complete in attribute macro, but in rustrover ide is ok; Im not sure is rust-analyzer doesn't support or lost some config item in my rust-analyzer configure;
## rust-analuzer version
```bash
/Users/l0calh0st/Workspace/rustexample/rust-analyzer/target/release/rust-analyzer
```

## rust-analyzer config
```lua
		["rust-analyzer"] = {
			assist = {
				importGranularity = "module",
				importEnforceGranularity = true,
				importPrefix = "self",
			},
			cargo = {
				loadOutDirsFromCheck = true,
				autoreload = true,
				allFeatures = true,
			},
			procMacro = {
				attributes = { enable = true },
				enable = true,
			},
			runnables = {
				use_telescope = true,
			},
			inlayHints = {
				chainingHints = {
					enable = true,
				},
				closureReturnTypeHints = {
					enable = true,
				},
				expressionAdjustmentHints = {
					enable = true,
				},

				typeHints = {
					enable = true,
				},
			},
		},

```

## in rustrover ide is ok 
![image](https://github.com/rust-lang/rust-analyzer/assets/62287907/a10fabde-3da4-4a33-b896-98c646a77117)

**Comment by Veykril** [comment]
Hmm, I'm confused as to how RustRover makes this work, the expansion of the macro for the given snippet errors out, not re-using the `aut` identifier in any sensible way. So there isn't really much for r-a to do here. I wonder if RustRover special cases this derive? (Something we won't be doing)
