### ISSUE TITLE
Macro expansion not always reflecting macro code changes

### ISSUE THREAD

**Issue by loganmzz** [rust-lang/rust-analyzer#16430]
**rust-analyzer version**: `0.3.1815-standalone`

**rustc version**: `1.71.1 (eb26296b5 2023-08-03)`

**relevant settings**: N/A

I'm currently developing a derive macro using VS Code.

When I encounter an issue regarding generation or generated code, I use VS Code feature provided by rust-analyser to expand the macro. In the first time of debugging, expanded code is fine.
Then, I fix or update macro code, but re-expanding macro doesn't reflect modifications, re-showing the previously expanded code.

**Comment by matthiasg** [comment]
I do not get this to work at all. The code expands fine with `cargo expand`, but the command always shows an untouched output.

is there some cache ?

**Comment by Veykril** [comment]
The cache are the built proc-macros. starting next version saving a proc-macro source file should rebuilt the proc-macros automatically
