### ISSUE TITLE
There is no suggestion for clone methods and no type inference for the the cloned variables

### ISSUE THREAD

**Issue by twhice** [rust-lang/rust-analyzer#16432]
**rust-analyzer version**: rust-analyzer version: 0.3.1815-standalone (d410d4a2b 2024-01-21)

**rustc version**: rustc 1.75.0 (82e1608df 2023-12-21)

**relevant settings**:none

while im using burn crate(version = "0.11.1", features = ["wgpu"]),there is something strange

here is the code
```
use burn::{backend::Wgpu, tensor::Tensor};

fn main() {
    let x = Tensor::<Wgpu, 1>::from_data([]);
    let y = x.clone();
}
```

![image](https://github.com/rust-lang/rust-analyzer/assets/97959381/31ad1c3d-c648-493b-ba55-8abdae144020)

there is no suggestion for the clone method

![image](https://github.com/rust-lang/rust-analyzer/assets/97959381/77485a5f-00e9-4424-a4da-b8a0b569ab5c)

and no type inference for y

but the code is ok to build&run, and ra-server gives no log

so... why?

**Comment by twhice** [comment]
maybe i should use `ones_like` mehod instead of `clone`?

**Comment by lnicola** [comment]
Slightly minimized:

```rust
#[derive(Clone)]
pub struct Tensor<K = Float>
where
    K: TensorKind<Wgpu>,
{
    primitive: K::Primitive<1>,
}

fn foo(t: Tensor) {
    let _x = t.clone();
}
```

It works with `primitive: <Float as TensorKind<Wgpu>>::Primitive<1>`.

**Comment by twhice** [comment]
> Slightly minimized:
> 
> ```rust
> #[derive(Clone)]
> pub struct Tensor<K = Float>
> where
>     K: TensorKind<Wgpu>,
> {
>     primitive: K::Primitive<1>,
> }
> 
> fn foo(t: Tensor) {
>     let _x = t.clone();
> }
> ```
> 
> It works with `primitive: <Float as TensorKind<Wgpu>>::Primitive<1>`.

![image](https://github.com/rust-lang/rust-analyzer/assets/97959381/67e3ee26-749a-48f6-87c1-126c2449f767)
