### ISSUE TITLE
GitHub release changelog number misinterpreted as issue reference

### ISSUE THREAD

**Issue by Marcono1234** [rust-lang/rust-analyzer#16455]
The description of the GitHub releases under https://github.com/rust-lang/rust-analyzer/releases uses the format
```
= Changelog #{changelog_n}

...
```

The problem is that GitHub misinterprets this `#<number>` as issue / PR reference, which is quite confusing:
![Changelog screenshot](https://github.com/rust-lang/rust-analyzer/assets/11685886/aa42f3c5-d26f-4a62-befb-4f74e24fdaf9)

It seems escaping the `#` with a `\` has no effect (at least not in the preview), so maybe it would be best to simply omit the `#` (or add a zero-width space or similar between)?

**Comment by Young-Flash** [comment]
how about No.218?

**Comment by lnicola** [comment]
How about we strip it off? It makes sense to have it on https://rust-analyzer.github.io/thisweek/2024/01/29/changelog-218.html, but not on the GitHub Releases page.

**Comment by Young-Flash** [comment]
Is the related setting here?
https://github.com/rust-lang/rust-analyzer/blob/e4146af29494768b0075e2fea2a56b699b0f9141/xtask/src/release/changelog.rs#L82-L84

**Comment by lnicola** [comment]
No, it's around https://github.com/rust-lang/rust-analyzer/blob/e4146af29494768b0075e2fea2a56b699b0f9141/xtask/src/publish.rs#L10-L11.

**Comment by Marcono1234** [comment]
Has a decision made yet how this should be solved?
Would it be fine to just perform a regex `^Changelog #` to `Changelog ` replacement? (though the xtask project here seems to have no regex dependency yet)

**Comment by lnicola** [comment]
We should strip off that line (we probably don't need `regex` though).

**Comment by Marcono1234** [comment]
@lnicola, I have tried to implement this now in #17165.
