### ISSUE TITLE
add_derive and add_impl do not respect current indentation

### ISSUE THREAD

**Issue by theotherphil** [rust-lang/rust-analyzer#1645]
```
mod foo {
    struct Bar {}
}
```

`add_impl` produces

```
mod foo {
    struct Bar {}

impl Bar {

}
}
```

I'll try and fix this.

Edit: a bit of failed grepping and the label on this issue https://github.com/rust-analyzer/rust-analyzer/issues/1191 suggest this might be less easy than I imagined.

**Comment by Veykril** [comment]
This is generally tracked in https://github.com/rust-lang/rust-analyzer/issues/1191
