### ISSUE TITLE
Incorrectly formatting away labels on match arms.

### ISSUE THREAD

**Issue by AryaveerSR** [rust-lang/rust-analyzer#16488]
**rust-analyzer version**:  0.4.1829-standalone (0113bc938 2024-02-03)

**rustc version**:  rustc 1.74.0 (79e9716c9 2023-11-13)

**Description**: Rust analyzer incorrectly formats away labels on match arms. The following code:
```rust
fn main() {
    let f = || match "f" {
        "f" => 'a: {
            if true {
                break 'a;
            }
            ..
        }
        _ => {}
    };
}
```
is formatted into:
```rust
fn main() {
    let f = || match "f" {
        "f" => {
            if true {
                break 'a;
            }
            ..
        }
        _ => {}
    };
}
```
which is certainly not ideal because `'a` label no longer exists.
PS: The closure and stuff is included as it shows a use-case where you'd actually be wanting to break with labels inside a match. It also happens to be how I stumbled upon this

**Comment by lnicola** [comment]
Can't reproduce, even with `cargo +1.74 fmt`. We format the code by running `rustfmt`.

**Comment by AryaveerSR** [comment]
![Recording 2024-02-04 at 23 17 40](https://github.com/rust-lang/rust-analyzer/assets/51504825/202fe6d8-095b-47b6-b7e2-9dd758ed185b)

**Comment by lnicola** [comment]
Well, it's clearly not our bug, but I still don't know why it happens only for you.
