### ISSUE TITLE
std::thread::LocalKey not found

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust-analyzer#16486]
**src/main.rs**
```rust
fn main() {
    let _key: std::thread::LocalKey<i32> = todo!();
}
```
**completion list**
```
3       std::thread::
  Thread factory,      Builder
~ which can be used    JoinHandle
~ in order to          Parker
~ configure the        Result
~ properties of        Scope
~ a new thread.        ScopedJoinHandle
~                      Thread
~ Methods can be       ThreadId
~ chained on it in     available_parallelism() (alias available_concurrency, hardware_concurrency, num_cpus)~ fn() ->
~ order to             current()~ fn() -> Thread
~ configure it.        imp
~                      panicking()~ fn() -> bool
~ The two              park()~ fn()
~ configurations       park_timeout(…)~ fn(Duration)
~ available are:       park_timeout_ms(…)~ fn(u32)
~                      scope(…)~ fn(F) -> T
~   * name:            sleep(…)~ fn(Duration)
~ specifies an         sleep_ms(…)~ fn(u32)
~ associated name      spawn(…)~ fn(F) -> JoinHandle<T>
~ for the thread       yield_now()~ fn()
```
run `cargo check` 0 warnings, 0 errors

patch `~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs`
```diff
196,203c196,197
< cfg_if::cfg_if! {
<     if #[cfg(test)] {
<         // Avoid duplicating the global state associated with thread-locals between this crate and
<         // realstd. Miri relies on this.
<         pub use realstd::thread::{local_impl, AccessError, LocalKey};
<     } else {
<         #[stable(feature = "rust1", since = "1.0.0")]
<         pub use self::local::{AccessError, LocalKey};
---
> #[stable(feature = "rust1", since = "1.0.0")]
> pub use self::local::{AccessError, LocalKey};
205,211c199,203
<         // Implementation details used by the thread_local!{} macro.
<         #[doc(hidden)]
<         #[unstable(feature = "thread_local_internals", issue = "none")]
<         pub mod local_impl {
<             pub use crate::sys::common::thread_local::{thread_local_inner, Key, abort_on_dtor_unwind};
<         }
<     }
---
> // Implementation details used by the thread_local!{} macro.
> #[doc(hidden)]
> #[unstable(feature = "thread_local_internals", issue = "none")]
> pub mod local_impl {
>     pub use crate::sys::common::thread_local::{thread_local_inner, Key, abort_on_dtor_unwind};
```
**use rust-analyzer Expand macro**
```rust
// Recursive expansion of cfg_if!! macro
// ======================================

#[stable(feature = "rust1", since = "1.0.0")]
pub use self::local::{AccessError, LocalKey};
pub use realstd::thread::{local_impl, AccessError, LocalKey};
#[doc(hidden)]
#[unstable(feature = "thread_local_internals", issue = "none")]
pub mod local_impl {
    pub use crate::sys::common::thread_local::{abort_on_dtor_unwind, thread_local_inner, Key};
}

```

After the patch, the behavior was as expected, but it seems that this issue cannot be reproduced well

OS: `Linux Acer-Lrne 6.5.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 06 Sep 2023 21:01:01 +0000 x86_64 GNU/Linux`

**rust-analyzer version**: rust-analyzer 1.75.0 (82e1608 2023-12-21) and rust-analyzer 1.78.0-nightly (b11fbfb 2024-02-03)

**rustc version**: rustc 1.75.0 (82e1608df 2023-12-21) and rustc 1.78.0-nightly (b11fbfbf3 2024-02-03)

**relevant settings**: NONE

**Comment by Veykril** [comment]
This is a known issue as rust-analyzer can't analyze the standard libraries crates-io dependencies by default, so the cfg-if  macro is unresolved and hence not expanded. You can fix this by either somehow introducing cfg-if into your dependency graph which will make r-a hackily inject it into the standard library dependencies or enable the experimental `rust-analyzer.cargo.sysrootQueryMetadata` config which allows r-a to analyze said dependencies (though it will write and delete a lock file in your sysroot)

**Comment by lnicola** [comment]
#7637

If `rust-analyzer.cargo.sysrootQueryMetadata` works for you, we can probably close this.

**Comment by A4-Tacks** [comment]
> #7637
> 
> If `rust-analyzer.cargo.sysrootQueryMetadata` works for you, we can probably close this.

It seems that this doesn't work. I need to introduce cfg-if dependencies in my own project to solve all of this
