### ISSUE TITLE
The function contains macro_rules for macro_export cannot be found in `crate::`

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust-analyzer#16490]
**src/main.rs**
```rust
fn main() {
    #[macro_export]
    macro_rules! foo {
        () => {
            1
        };
    }
    let _m = crate::foo!();
    let _n = crate::bar();
    // crate::
    //      bar()~
    //      main()~
}
fn bar() -> i32 {
    #[macro_export]
    macro_rules! bar {
        () => {
            3
        };
    }
    crate::bar!()
}
```

**rust-analyzer version**: `rust-analyzer 1.74.0 (79e9716c 2023-11-13)` and `rust-analyzer 1.77.0-nightly (bf8716f1 2023-12-24)`

**rustc version**: `rustc 1.74.0 (79e9716c9 2023-11-13)` and `rustc 1.77.0-nightly (bf8716f1c 2023-12-24)`

**relevant settings**: NONE

**Comment by Veykril** [comment]
This pattern is intentionally not supported as this requires rust-analyzer to look into all function bodies for name resolution. (the pattern being a `macro_export` that leaks outside of the function body. Additionally this pattern might error in a future rust edition https://github.com/rust-lang/rust/issues/120363
