### ISSUE TITLE
"Generate getter" doesn't handle `DerefMut`

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#16495]
Similar to #16487.

**Comment by ShoyuVanilla** [comment]
I think that this shouldn't be implemented for some types like `String` (which implements `AsMut<str>`) and `Vec<T>` (which implements `AsMut<[T]>` because non-deref_mut-ed, plain mutable references like `&mut String` and `&mut Vec<T>` provide more functionalities - e.g. `drain()` -

**Comment by Veykril** [comment]
That's a good point. I don't think this makes sense to do in general? Mutable references to the non-derefed target most often have a bigger useful API surface than the mutable ref to the deref target, unlike shared references.

**Comment by lnicola** [comment]
TIL `String::as_mut`.

Okay, let's close this until someone actually wants it.
