### ISSUE TITLE
"Go to declaration" is wrong term

### ISSUE THREAD

**Issue by safinaskar** [rust-lang/rust-analyzer#16494]
Steps to reproduce:
- Install fresh vscode
- Install rust-analyzer
- Open some Rust project
- Click anywhere in Rust source using right mouse button

You will see menu with items "Go to definition" and "Go to declaration". But Rust doesn't have concepts of definition and declaration, as opposed to C++!

I use recent debian linux sid amd64, vscode insiders 1.87, rust-analyzer pre-release 0.4.1830. The bug is not reproducible on https://ra-wasm.netlify.app/

**rust-analyzer version**: 0.4.1830-standalone

**rustc version**: 1.75.0

**relevant settings**: (nothing special)

**Comment by lnicola** [comment]
We actually have [different implementations](https://github.com/rust-lang/rust-analyzer/blob/a607e1b04b9263fa29e6000532e83f0526478440/crates/ide/src/lib.rs#L428-L458) for these: https://rust-analyzer.github.io/manual.html#go-to-declaration.

> This is the same as Go to Definition with the following exceptions:
> - outline modules will navigate to the mod name;
> item declaration - trait assoc items will navigate to the assoc item of the trait declaration opposed to the trait impl
> - fields in patterns will navigate to the field declaration of the struct, union or variant

**Comment by safinaskar** [comment]
Okay, I understood. But ideally names of menu items should depend on kind of symbol we clicked. I. e. if we clicked on invocation of trait's function, menu should have "Go to implementation" and "Go to declaration"

**Comment by lnicola** [comment]
We don't control the contents of the menu, and it would be unfortunate if right-clicking didn't work until the project was loaded.

**Comment by safinaskar** [comment]
> We don't control the contents of the menu

The very fact that rust-analyzer doesn't control this menu is a bug. I will report it. Where I should report it? To vscode?

**Comment by lnicola** [comment]
Code works with any LSP server, including clangd. A server can say that it doesn't support some of those at all, or it can implement them as well as it can.

The same thing will happen in C++ if you use them on a local variable or an inline function. The language extension will probably have similar heuristics like going to the declaration if the implementation is unavailable.

I don't see any way to solve this "bug" that wouldn't make the user experience worse.

**Comment by safinaskar** [comment]
Okay, so this is wired to LSP protocol, right? I will then report bug to LSP specification. LSP should provide way for language server to control count of menu items and their names! (And if language server is not yet initialized, then, of course, the menu simply should not have items such as "Go to definitions", instead the menu should just have items, which can be implemented without language server, such as "Copy")

**Comment by lnicola** [comment]
That would mean Code wouldn't be able to show the menu before the server replied, which could reasonably take a second or so depending on what other requests are running.

This would make things worse for everyone, for the dubious benefit of hiding some options that work anyway. I often use "Go to definition" regardless of what's there, and I think the C++ extension switches between definition and implementation. Fixing this bug would break that kind of usage.

**Comment by safinaskar** [comment]
> which could reasonably take a second or so

This can happen if user's computer is slow or under heavy load. But in this case user experience is already degraded! And many other things already are slow. So this will just add yet another thing, which works slowly. I don't think this is so bad.

Even if you think that menu should appear instantly, then I have such solution: just immediately open menu with items, such as "Copy" and show rotating circle instead of items, such as "Go to definition". When the server responds, the circle should be replaced with items, such as "Go to definition".

You may say that replacing menu items on the fly is hard to implement. Yes. I don't know how to implement this. But big multinational company, such as Microsoft, which worth 400 billions of dollars, certainly can implement this, if it really wants.

You may say that this will likely mean that vscode cannot use platform-provided native popup menu abstraction, and they will have to create their own popup-like thing. And that will mean that many new lines of code should be written. Yes, possibly. So, what? Gigantic multinational company Microsoft can afford this.

You may say that vscode is based on Electron, and Electron doesn't provide such feature. Well, I'm nearly sure vscode uses its own fork of Electron. So, yes, possibly Microsoft will have to heavily modify their Electron fork. But, again, so what? Microsoft can afford this.

> Fixing this bug would break that kind of usage

There should exist action "Go to something" (i. e. "go to definition, if this is possible, or go to declaration, if this is possible, anyway, just go to something"), which always works (of course, if language server is initialized, and cursor is on symbol, not, say, on number), and which could be bind to some shortcut, but which will be hidden from menu.

So, for your use case you will simply bind this action to some shortcut, and just press this shortcut when you want.

But menu should have actions, which are reasonable for this symbol, i. e. the menu should depend on symbol.

Current vscode behavior simply looks absolutely illogical. This looks like a bug. For example, in Rust the menu always have item "Go to type definition", even if you clicked not at type

**Comment by flodiebold** [comment]
The right place to report this would be VSCode, but I wouldn't get my hopes up that they will do something about it.
