### ISSUE TITLE
Flip assist for `+` in trait bounds

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#16522]
We currently have a very nice flip comma assist which flips the left and right hand syntax of a comma, we should extend that to be applicable for trait bounds, ie `dyn Foo + 'bar` should allow flipping on the plus to get `dyn 'bar + Foo`

**Comment by evertedsphere** [comment]
It looks like there already is a `flip_trait_bound` assist, it's just missing a test that checks that it works with trait objects.

**Comment by Veykril** [comment]
Right we do have that, hmm wonder why it didn't work when I tried it then 🤔
