### ISSUE TITLE
Disable code Action for clippy::needless_return

### ISSUE THREAD

**Issue by aminya** [rust-lang/rust-analyzer#16542]
Rust-analyzer has started to give code action suggestions for removing `return` from my code despite me allowing `clippy::needless_return` via `#![allow(clippy::needless_return)]`. 

In my coding style, I do not like my `returns` to be implicit, and I don't really align with the push to force not using return statements in the Rust tooling (e.g. Clippy, Rust-analyzer, etc).

Could you add an option to remove this code action, or respect the clippy configuration enabled at the module level?

**rust-analyzer version**:   0.4.1838-standalone

**rustc version**: rustc 1.75.0-nightly (42b1224e9 2023-10-15)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

The offending feature:

https://github.com/rust-lang/rust-analyzer/pull/16460

**Comment by lnicola** [comment]
Unfortunately, I don't think we respect `#[allow(clippy::needless_return)]` yet, but in VS Code you can disable it using:

```json
{
    "rust-analyzer.diagnostics.disabled": [
        "needless_return"
    ]
}
```

**Comment by Veykril** [comment]
Our filtering for diagnostic level attributes is somewhat broken wrt to macros, that is a known issue.

**Comment by lnicola** [comment]
It should respect `#[allow(clippy::needless_return)]`, but `tokio::main` doesn't even seem to expand to that. It only has `#[allow(clippy::expect_used, clippy::diverging_sub_expression)]` for me.

**Comment by Veykril** [comment]
Might be that `needless_return` doesn't trigger on macro expansions with clippy

**Comment by lnicola** [comment]
No, I think it's something kind of heuristic:

```rust
// no warning
fn main() {
    return tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("Failed building the Runtime")
        .block_on(async {});
}

// warning
fn main() {
    return tokio::runtime::Runtime::new()
        .expect("Failed building the Runtime")
        .block_on(async {});
}
```

**Comment by lnicola** [comment]
I suspect it's this check: https://github.com/rust-lang/rust-clippy/blob/d2f76f7/clippy_lints/src/returns.rs#L378-L381.

**Comment by Veykril** [comment]
Oh, that's probably due to temporaries? (Then we most likelyneed that as well)

**Comment by lnicola** [comment]
Yeah: https://github.com/rust-lang/rust-clippy/blame/48b4aea/clippy_lints/src/returns.rs#L19-L20

> **Known problems:** If the computation returning the value borrows a local variable, removing the `return` may run afoul of the borrow checker.

Sounds like a limitation of Clippy itself (it's too conservative here), but we probably want to match it anyway.

**Comment by arnfaldur** [comment]
Is there any way to disable this behavior?

**Comment by lnicola** [comment]
@arnfaldur see my comment at the top.

**Comment by SergSpice** [comment]
Why is this is even in the code?, one of the things that I hate about Go linter and ESLint is that they force you to have a code style that is horrendous, I think the whole "needless_return" is an overreach, I haven't even been able to remove this in my Neovim config, and is not like I have an old soul and I'm not open to new things, it's because my project now is full of warnings, and this doesn't even makes sense, is a fricking macro:
<img width="594" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/24253382/bc30cf87-d165-4ffe-8043-76ee2de76642">

**Comment by leelhn2345** [comment]
> Why is this is even in the project?, one of the things that I hate about Go linter and ESLint is that they force you to have a code style that is horrendous, I think the whole "needless_return" is an overreach, I haven't even been able to remove this in my Neovim config, and is not like I have an old soul and I'm not open to new things, it's because my project now is full of warnings since I updated the version, and this doesn't even makes sense, is a fricking macro!!!!: <img alt="image" width="594" src="https://private-user-images.githubusercontent.com/24253382/310001191-bc30cf87-d165-4ffe-8043-76ee2de76642.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjE2MzYsIm5iZiI6MTcwOTYyMTMzNiwicGF0aCI6Ii8yNDI1MzM4Mi8zMTAwMDExOTEtYmMzMGNmODctZDE2NS00ZmZlLTgwNDMtNzZlZTJkZTc2NjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA2NDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNTRhMjUyMzczNmZhYzM0NGNmYTBhY2NiZDg1MDBkY2U0MTExZWNmNzRhODIxNDZlNjIwNjdjMmU0N2U1OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hvviPtDgrq4eGtMNKkYdKgyODdTZweO95gb6CtnUjfw">

until there's a permanent change to this,
you can configure rust analyzer to disable the warning with this.

```lua
          ["rust-analyzer"] = {
            diagnostics = {
              disabled = {
                "needless_return",
              },
            },
          }
```

the lua code is from rustacean.nvim plugin, but i believe the settings should be similiar to other lsp plugins.

**Comment by nilehmann** [comment]
> Why is this is even in the project?, one of the things that I hate about Go linter and ESLint is that they force you to have a code style that is horrendous, I think the whole "needless_return" is an overreach, I haven't even been able to remove this in my Neovim config, and is not like I have an old soul and I'm not open to new things, it's because my project now is full of warnings since I updated the version, and this doesn't even makes sense, is a fricking macro!!!!: 

I was going to be snarky and then realized you are fellow countryman and now I'm conflicted.

**Comment by Veykril** [comment]
The lint shouldn't trigger by default anymore next release until opted-in, 676455f

**Comment by conradogarciaberrotaran** [comment]
It has to be released right?
If so, would you update this: https://github.com/mason-org/mason-registry/blob/main/packages/rust-analyzer/package.yaml
or let me know to do it myself.

Thanks!

**Comment by lnicola** [comment]
It will be released on Monday, or you could use the nightly (I've triggered a build now, should finish in about 15 minutes). We don't own `mason-registry`, but you can probably download a binary and replace it manually.

**Comment by conradogarciaberrotaran** [comment]
I'll create a PR when it's released.

Thanks :)

**Comment by lnicola** [comment]
I imagine they might not want to use nightlies, so it's probably fine to wait until Monday.

**Comment by conradogarciaberrotaran** [comment]
mason-registry's versions are auto updated :)
https://github.com/mason-org/mason-registry/commit/696a25ac8b255a656e69bc8c4b3d58220aa46cfa

**Comment by good-gamedev** [comment]
> ```json
> {
>     "rust-analyzer.diagnostics.disabled": [
>         "needless_return"
>     ]
> }
> ```

Didn't work for me on VSCode and clippy 0.1.79 (129f3b99 2024-06-10). Are there other solutions?

**Comment by gamedev-pnc** [comment]
#![allow(clippy::needless_return)] -- works in clippy 0.1.80.
Thanks!

**Comment by Ritzier** [comment]
```rust
default_settings = {
    checkOnSave = {
        allFeatures = true,
        command = "clippy",
        extraArgs = { "-- -A clippy::needless_return" },
    }
}
```

For my configuration just add an extra agrument
