### ISSUE TITLE
Semantic highlighting mistakenly highlights constants as variables

### ISSUE THREAD

**Issue by uloco** [rust-lang/rust-analyzer#16551]
**rust-analyzer version**: rust-analyzer 1.76.0 (07dca489 2024-02-04)

**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04)

**relevant settings**: running in neovim builtin lsp with lspconfig setup as described in _User Manual_ docs.

Rust-analyzer mistakenly highlights constants as variables instead of constants.
When I disable rust-analyzer lsp and only use treesitter the  highlighting for constants gets colored correctly.
This is not specific to a theme and happens with multiple ones.

**Comment by Veykril** [comment]
Do you have an example where this is not the case? Constants are appropriately tagged for me 
![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/7763f484-38da-4f0e-9849-0c2b0b40b1e8)

**Comment by uloco** [comment]
It works in vscode but does not with neovim lsp

**Comment by uloco** [comment]
The problem is semantic token type: variable. it should be constant not variable. textmate scopes are correct. as you can see

**Comment by uloco** [comment]
I'm testing this right now: https://github.com/SLMT/rust-snake/blob/master/src/main.rs, const BACK_COLOR: Color = [0.204, 0.286, 0.369, 1.0];

**Comment by Veykril** [comment]
> The problem is semantic token type: variable. it should be constant not variable. textmate scopes are correct. as you can see

Not, the correct lsp kind for this is `variable.constant`. There is no const type in the standard lsp types, only the constant modifier. The server here is working as intended so if you don't want semantic tokens you should check how to configure neovim lsp to not make use of them.

**Comment by uloco** [comment]
Oh I see, ty. I guess neovim lsp changed something here. closing
