### ISSUE TITLE
Incorrect "cannot move `&mut ()` out of reference" error

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#16564]
```rs
fn main() {
    let x = (&(&mut (),)).0 as *const ();
}
```
This compiles

**Comment by ShoyuVanilla** [comment]
Does this still occur? It seems somehow fixed - `rust-analyzer 1.78.0-nightly (3b1717c0 2024-03-10)`, `rust-analyzer 1.76.0 (07dca489 2024-02-04)`

**Comment by Veykril** [comment]
Still reproduces for me

**Comment by ShoyuVanilla** [comment]
Thank you. I'll test again with different settings 🤔

**Comment by Veykril** [comment]
Ah you need to enable experimental diagnostics for this one I think

**Comment by ShoyuVanilla** [comment]
Oh, didn't know that 😅 Thanks!
