### ISSUE TITLE
RA didn't recognize the 'commands.rs' module

### ISSUE THREAD

**Issue by nurmohammed840** [rust-lang/rust-analyzer#16571]
If we want to create a modules at `commands.rs` using code action (quick fix), RA create  a file called `Commands.rs` and not `commands.rs`

```rs
mod commands;
```

Even though I renamed it, RA didn't recognize the `commands.rs` module, like it doesn't exist.

- rust-analyzer version: `0.3.1839`

**Comment by lnicola** [comment]
Probably #9947.
