### ISSUE TITLE
r-a reports proc-macro sources have changed when opening a proc-macro source file

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#16580]
Opening a file reports a DidOpenTextDocument notification, as we no longer keep track of vfs contents we don't recognize this as a no-op, always recording opening as a modification triggering the proc-macro source dirty marking logic.

**Comment by wleslie** [comment]
I think I remember merely hovering over a proc macro invocation also triggering this. Will update if I can reproduce.
