### ISSUE TITLE
rust-analyzer + stdarch = 4k errors

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#16592]
To reproduce, check out https://github.com/rust-lang/stdarch/ and open it with RA. I am getting about 4k errors, and they are all the same:
```
error: custom attribute panicked
   --> crates/core_arch/src/x86_64/avx512f.rs:794:5
    |
794 |     #[simd_test(enable = "avx512f")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: TARGET environment variable should be set for rustc (e.g. TARGET=x86_64-apple-darwin cargo test): NotPresent
```

Running `cargo check` on the terminal works fine though, so this seems to be an RA thing.

I tried playing with the settings, but this did not help:
```
    "rust-analyzer.cargo.buildScripts.enable": false,
    "rust-analyzer.procMacro.enable": false,
    "rust-analyzer.cargo.buildScripts.useRustcWrapper": false,
```

**rust-analyzer version**: rust-analyzer version: 0.3.1839-standalone

**rustc version**: rustc 1.78.0-nightly (a84bb95a1 2024-02-13)

**relevant settings**: Happens with default settings

**Comment by RalfJung** [comment]
Ah turns out I can reproduce this outside of RA with `cargo check --all-targets`. So adding this helps:
```
"rust-analyzer.check.allTargets": false,
```
So doesn't seem to be an RA issue after all (Cc @Amanieu FYI, the fact that `cargo check --all-targets` fails on stdarch will be tripping up plenty of people)

**Comment by Amanieu** [comment]
Unfortunately this is needed because proc macros are not given information about the current target triple.
