### ISSUE TITLE
Doc comments are not automatically continued with a leading `///` on new-line

### ISSUE THREAD

**Issue by IceTDrinker** [rust-lang/rust-analyzer#16602]
**rust-analyzer version**: rust-analyzer version: 0.3.1850-standalone in VSCode

**rustc version**: rustc 1.78.0-nightly (2bf78d12d 2024-02-18)

**relevant settings**: nothing notable

It appears that pressing enter when writing a doc comment now stops adding the leading `///`, I think it used to and it was only an issue when terminating a doc comment and not at every line (where the leading `///` was always added instead of not being added). Feels like today's update brought the breakage but could be older.

I did not see recent mentions of that issue in the tracker, if one already exists I missed it and this one can likely be closed.

Cheers

**Comment by Young-Flash** [comment]
should be a regression, v0.3.1839 works

**Comment by IceTDrinker** [comment]
rustdoc inject ? which somehow overrides some stuff that was not overriden before ?

A really wild guess, I don't know the internals of the analyzer and vs code, but I noticed that the edition mode seemed to have changed for doc comments, where the text was white before turning green and the headings were set in bold.

If the rust doc injection overrides the management of the /// and does not inject it then it could be a reason I guess, hard to tell from the diff, maybe a bisect would help but it does not show commits, only changed files

**Comment by Veykril** [comment]
Its most likely the rustdoc injection

**Comment by Young-Flash** [comment]
cc https://github.com/rust-lang/rust-analyzer/issues/16253#issuecomment-1884212742

**Comment by RalfJung** [comment]
> the text was white before turning green

Indeed, not only does the `///` insertion no longer work, typing comments also behaves strangely now where they are black for a few seconds before turning green. It's quite jarring and distracts from focusing on the text I am writing.

**Comment by Veykril** [comment]
I figured this would cause issues yet again, so let's roll that back. If people want that kind of injection they can make it a separate extension instead until rust-analyzer get's native semantic highlighting support for doc comments.

**Comment by IceTDrinker** [comment]
The white text itself does not bother me, was just a hint something changed in the rustdoc stuff, the missing /// is a bit of an annoyance though, and I get those are not easy problems

**Comment by Veykril** [comment]
>  the missing /// is a bit of an annoyance though,

is easy to fix, but flickering highlighting is a no go and just a result of textmate grammar injection and semantic highlighting I believe

**Comment by IceTDrinker** [comment]
Ok, you guys know better what you want and can accept, the temp white highlights don’t seem like a breaker

**Comment by RalfJung** [comment]
I do find the color change quite irritating and actively distracting.
