### ISSUE TITLE
From version `2024-02-19` VS Code hangs on `building proc-macros: app_name`

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/rust-analyzer#16605]
After upgrading from 2024-02-12 version to 2024-02-19 on my Windows PC and after a `cargo clean` VS Code hangs on:

`building proc-macros: app_name`

**rustc version**: `rustc 1.76.0 (07dca489a 2024-02-04)`

**Comment by Veykril** [comment]
This will need more info to be reproducible. Anything interesting in the logs? Any specific crates that this happens with?

**Comment by Veykril** [comment]
Closing as duplicate of https://github.com/rust-lang/rust-analyzer/issues/16614
