### ISSUE TITLE
The cursor is at the param type annotation instead of the param itself, showing with a method call

### ISSUE THREAD

**Issue by asuper0** [rust-lang/rust-analyzer#16610]
**rust-analyzer version: 0.4.1843-standalone (b9b0d29b8 2024-02-15)
**rustc 1.74.1 (a28077b28 2023-12-04)

![rust-analyze-bug-report](https://github.com/rust-lang/rust-analyzer/assets/41113804/2462ce41-a5c7-4b1d-b346-39a78293972f)

With the code above, when I place the cursor to param value `100`, it displayed at the annotaion `element`. If I press "delete" key, then the head char '1' of "100" would be deleted.

I suggest to make the cursor show at the true position, that is char '1' of the value "100", not a fake param name "element".

**Comment by Young-Flash** [comment]
“element” is inlay hint, maybe your cursor mode misleading you?

![image](https://github.com/rust-lang/rust-analyzer/assets/71162630/00de3319-d167-419e-b990-b9f4b590b03e)

**Comment by Veykril** [comment]
This is a vscode UX issue, so you are better off raising that there
