### ISSUE TITLE
Heavy memory usage

### ISSUE THREAD

**Issue by allsey87** [rust-lang/rust-analyzer#16611]
**rust-analyzer version:** 0.3.1850-standalone

**rustc version**: 1.78.0-nightly (8ace7ea1f 2024-02-07)

**relevant settings**: Using linkedProjects in vscode to specify two projects, a workspace with 4 members and a standalone crate.

Rust analyzer is idle at the moment, however, it is consuming nearly 20% of system memory (24 GB + 1 GB swap), that seems... excessive :D
```
PID   USER      PR   NI  VIRT    RES  SHR S  %CPU %MEM  TIME+   COMMAND                                
49427 mallwri+  20   0   5468700 4.5g 236 S  0.0  19.3  3:19.57 rust-analyzer
```

**Comment by flodiebold** [comment]
How large are the projects? How many and how large are the dependencies (e.g. how many lines does Cargo.lock have)?
