### ISSUE TITLE
There seems to be an issue with the cache of the plugin, but this situation occurs randomly.

### ISSUE THREAD

**Issue by eighteen-k-gold-malow** [rust-lang/rust-analyzer#16633]
There seems to be an issue with the cache of the plugin, but this situation occurs randomly.  

I have defined a variable for Rc<RefCell<XX>, and the next time I use it, x.as_ref(). borrow() seems to have no problem.  

I mistakenly wrote x.as_ref(). borrow() as the x.borrow() plugin, which will not report an error at this time.  

At this point, manually delete the target directory and execute cargo clean&&cargo build, which will also compile normally.  

But the next day when I open the project, there will be a bunch of errors

**Comment by Veykril** [comment]
That seems to be a `cargo` caching issue from the sounds of it

**Comment by lnicola** [comment]
Closing, since there's not enough information to do anything about this.

But if `cargo clean` fixes it, it's probably not us. I think one way to cause an issue is tu run a `git pull` while r-a (or a plain `cargo check`) is building the project.
