### ISSUE TITLE
recompiling happens with no code changes due to rust analyzer

### ISSUE THREAD

**Issue by Redhawk18** [rust-lang/rust-analyzer#16640]
On Linux in Neovim when opening a project it starts rust analyzer, and without changes or writes to any files. `cargo build` will partially recompile the project even though it was completely finished before. 

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</ kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) : 2024-2-19

**rustc version**: (eg. output of `rustc -V`): rustc 1.75.0 (82e1608df 2023-12-21)

**Comment by awused** [comment]
I use a separate global target directory just for rust-analyzer and I've noticed it's been recompiling more and running much slower recently. Not sure if it was this week's update or last week's update.

**Comment by mschnell1** [comment]
Supposedly related: 
Here on Windows... Rust analyzer v0.3.1850

I have a small projecrt (just a single file) that a tree of uses 248 crates from crate.io plus an additional crate that is `git cloned` frim github. 

Every time when starting `VSCode `, rust analyzer take about 20 minutes to scan the code. (BTW.: Is there any way to prevent rust analyzer from scanning all available source files ? ) 

Regarding rather often rust analyzer starts a long scanning process for no obvious reason (e. g. saving main.rs with no or no relevat modification). And after this when doing `cargo build` anout 100 creates are re-compiled. Seemingly ruist analyzer modifies some file dates and confuses the build/make algorithm.

**Comment by mschnell1** [comment]
BTW; (off topic) I switched to rustc 1.78.0-nightly (397937d81 2024-02-22) (which is said to compile much faster) and the scanning seems a much faster.

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/16621 will most likely fix this. If this is still the case with the next release please re-open this issue / open a new one.

**Comment by awused** [comment]
On my end I wasn't even compiling my code outside of rust-analyzer, since rust-analyzer has its own separate target_dir. I think rust-analyzer was conflicting with itself running clippy.

**Comment by Veykril** [comment]
Oh, I imagine you are using the specific target dir config? From the looks of it that is only being used for running `check`/`clippy`, not for build-scripts/proc-macros! So that will invalidate things still

**Comment by Veykril** [comment]
Okay I still think #16621 will fix that. As stated in that PR, r-a was invoking `cargo rustc -- ...` which will trigger a build, we were not passing the target dir override to that so it could likely cause a rebuild when r-a starts up. That was fixed in the PR now so presumably that should fix this for you as well. Please check once that is released.

**Comment by awused** [comment]
I've just got this in my coc-settings.json, I think it should be affecting everything rust-analyzer runs.

```
"rust-analyzer.cargo.extraEnv": {
  "CARGO_TARGET_DIR": "/cache/rust-analyzer"
},
```

**Comment by Veykril** [comment]
Setting the env var  `CARGO_LOG=cargo::core::compiler::fingerprint=info` and running a cargo command like `cargo build` should tell you why its rebuilding (if the command does a rebuild).
