### ISSUE TITLE
thread 'Worker' panicked at ra-ap-rustc_pattern_analysis-0.37.0/src/constructor.rs:947:63

### ISSUE THREAD

**Issue by edg-l** [rust-lang/rust-analyzer#16656]
**rust-analyzer version**: Tried show RA version but doesnt work, on vscode extension manager it shows v0.4.1857

**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

rust-analzer constantly crashes

```
thread 'Worker' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra-ap-rustc_pattern_analysis-0.37.0/src/constructor.rs:947:63:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
   3: ra_ap_rustc_pattern_analysis::constructor::ConstructorSet<Cx>::split
   4: ra_ap_rustc_pattern_analysis::usefulness::compute_exhaustiveness_and_usefulness
   5: ra_ap_rustc_pattern_analysis::usefulness::compute_match_usefulness
   6: hir_ty::diagnostics::expr::BodyValidationDiagnostic::collect
   7: hir::DefWithBody::diagnostics
   8: hir::ModuleDef::diagnostics
   9: hir::Module::diagnostics
  10: ide_diagnostics::diagnostics
  11: std::panicking::try
  12: ide::Analysis::assists_with_fixes
  13: rust_analyzer::handlers::request::handle_code_action
  14: std::panicking::try
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
```

**Comment by Wilfred** [comment]
FWIW we're seeing this too, and it's our most common crash in the latest rust-analyzer release. I think it's the unwrap here: https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_pattern_analysis/constructor.rs.html#943

```
            ConstructorSet::Variants { variants, non_exhaustive } => {
                let mut seen_set = index::IdxSet::new_empty(variants.len());
                for idx in seen.iter().map(|c| c.as_variant().unwrap()) {
                    seen_set.insert(idx);
                }
```

**Comment by Veykril** [comment]
cc @Nadrieril

**Comment by Nadrieril** [comment]
I see. Does either of you have a code example that triggers the crash? It's likely a pattern-match expression with a type error

**Comment by Nadrieril** [comment]
A fix is in motion: https://github.com/rust-lang/rust/pull/121735

**Comment by lnicola** [comment]
For anyone running into this, note that it will only be fixed after `ra-ap_rustc_pattern_analysis` gets published [on Subday](https://github.com/rust-analyzer/rustc-auto-publish/blob/aa6aee5e952693454c53684f1b798e6b58021cae/README.md), and we upgrade bump our dependency on it.

**Comment by Nadrieril** [comment]
Oops yeah, I didn't intend for bors to close this
