### ISSUE TITLE
rust-analyzer version 0.3.1850 spinning arrows for rust-analyzer and Fetching never stops

### ISSUE THREAD

**Issue by g3blv** [rust-lang/rust-analyzer#16653]
I've been using rust-analyzer for a few months in VSCodium on Flatpak. The spinning arrows at the bottom of the screen never stops for **rust-analyer** and **Fetching** after upgrading to 0.3.1850. Downgrading to 0.3.1839 and behaviour reverts to normal (spinning for a while)

**rust-analyzer version**: rust-analyzer version: 0.3.1850-standalone

**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04)

**Comment by Veykril** [comment]
Fixed in latest pre-release
