### ISSUE TITLE
error: linking with `cc` failed: exit status: 1   |   = note: LC_ALL="C" after installing rust-analyzer

### ISSUE THREAD

**Issue by woheme-c** [rust-lang/rust-analyzer#16659]
When I run the script (cargo run) or build the script (cargo build) without the rust-analyzer there is no error. When I start the analyzer, let him process till the end a error occures:

error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH ...

**rust-analyzer version**: v0.3.1850

**rustc version**: rustc 1.73.0

**relevant settings**: cargo 1.73.0

**Comment by Veykril** [comment]
Your text editor is most likely running in a different environment than your terminal then. You either need to set relevant env vars your build script needs for your text editor session or add them to the `rust-analyzer.server.extraEnv` config.
