### ISSUE TITLE
Inline into all callers panic

### ISSUE THREAD

**Issue by Alexendoo** [rust-lang/rust-analyzer#16660]
It's reproducible, but not very minimal:

```bash
git clone https://github.com/rust-lang/rust-clippy.git
cd rust-clippy
git checkout 64054693eb35cd0b80d3eee598f723a2b2df2e8f

mkdir .vscode
echo '{ "rust-analyzer.rustc.source": "discover" }' > .vscode/settings.json

code . --goto clippy_utils/src/lib.rs:1311:10
```

Use the `Inline into all callers` assist on `get_parent_node`, it fails with the message:

```
request handler panicked: can't resolve SyntaxNodePtr { kind: CALL_EXPR, range: 6..32 } with SOURCE_FILE@0..16468
```

**rust-analyzer version**: rust-analyzer version: 0.3.1850-standalone (68c506fd6 2024-02-19)

**rustc version**: rustc 1.78.0-nightly (3406ada96 2024-02-21), x86_64-pc-windows-msvc

**Comment by roife** [comment]
I think the problem is due to `clippy_utils/src/lib.rs:2185` which calling `get_parent_node` in the `matches!` macro, triggering the error `can't resolve SyntaxNodePtr` when this line is expanding.

@Veykril Can we handle this situation? Or just ignore the function calls inside macro parameters.

**Comment by Veykril** [comment]
Ignoring would probably be best unless it can be trivially fixed
