### ISSUE TITLE
Go to definition doesn't work in deno_ast

### ISSUE THREAD

**Issue by marvinhagemeister** [rust-lang/rust-analyzer#16672]
Steps to reproduce:

1. Clone https://github.com/denoland/deno_ast
2. Open any rust file, like `src/transpiling/jsx_precompile.rs` at line 892
  ```rs
      let child_expr = self.serialize_jsx_children_to_expr(&el.children);
                                      ^cursor is here
   ```
4. Move cursor to any function call or method and run go to definition (cmd+click on mac) -> Nothing happens

LSP traces:

```log
[Trace - 23:45:40] Sending request 'textDocument/definition - (81)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/marvinhagemeister/dev/github/deno_ast/src/transpiling/jsx_precompile.rs"
    },
    "position": {
        "line": 891,
        "character": 38
    }
}

[Trace - 23:45:40] Received response 'textDocument/definition - (81)' in 3ms.
Result: []
```

I can click on any identifier in any rust file and nothing happens. Go to definition never works in this project. It does work for me in other projects though. There is no project specific vscode settings involved.

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) 0.3.1850-standalone (68c506fd6 2024-02-19)

**rustc version**: (eg. output of `rustc -V`) 1.75.0 (82e1608df 2023-12-21)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`) None are set

**Comment by Veykril** [comment]
You will need to enable the corresponding cfgs for r-a here https://github.com/denoland/deno_ast/blob/main/src/lib.rs#L6-L20 via `    "rust-analyzer.cargo.features": ["feature", ...]` or enable all via `"rust-analyzer.cargo.features": "all"`. Otherwise r-a will not consider those modules as part of the crate graph.

**Comment by marvinhagemeister** [comment]
Oh I didn't know about that. Setting `"rust-analyzer.cargo.features": "all"` works. Thanks for responding 👍
