### ISSUE TITLE
Proc macros not working on new install of rustup and rust-analyzer stable and pre-release

### ISSUE THREAD

**Issue by z-targz** [rust-lang/rust-analyzer#16688]
rust-analyzer version: v0.3.1860 (and pre-release)

`[ERROR rust_analyzer::reload] Failed to run proc-macro server from path /home/chase/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/libexec/rust-analyzer-proc-macro-srv, error: Custom { kind: Other, error: "proc-macro server's api version (3) is newer than rust-analyzer's (2)" }`

rust version:
```
$ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.76.0 (07dca489a 2024-02-04)`
```

I get the same error on the pre-release version as well.

Can't find any info anywhere about this error.

**Comment by z-targz** [comment]
This issue is fixed by updating to v0.3.1860

**Comment by jonaspleyer** [comment]
I am having exactly the same bug but updating my IDE did not work unfortunately.
I am using neovim with the latest version of `rust-analyzer` from the Arch extra repo.
```
$ pacman -Qi rust-analyzer
Name            : rust-analyzer
Version         : 20240311-1
Description     : Rust compiler front-end for IDEs
Architecture    : x86_64
URL             : https://rust-analyzer.github.io/
Licenses        : Apache-2.0  MIT
Groups          : None
Provides        : None
Depends On      : gcc-libs  rust-src
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 25.89 MiB
Packager        : Orhun Parmaksız <orhun@archlinux.org>
Build Date      : Mon 11 Mar 2024 10:10:05 CET
Install Date    : Tue 12 Mar 2024 00:21:54 CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```
```
$ pacman -Qi neovim
Name            : neovim
Version         : 0.9.5-2
Description     : Fork of Vim aiming to improve user experience, plugins, and GUIs
Architecture    : x86_64
URL             : https://neovim.io
Licenses        : custom:neovim
Groups          : None
Provides        : vim-plugin-runtime
Depends On      : libluv  libtermkey  libuv  libvterm>0.1.4  luajit  msgpack-c  tree-sitter  unibilium
Optional Deps   : python-pynvim: for Python plugin support (see :help python)
                  xclip: for clipboard support on X11 (or xsel) (see :help clipboard) [installed]
                  xsel: for clipboard support on X11 (or xclip) (see :help clipboard)
                  wl-clipboard: for clipboard support on wayland (see :help clipboard) [installed]
Required By     : neovim-lsp_signature  neovim-lspconfig  neovim-nvim-treesitter  nvim-packer-git  vim-latexsuite
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 25.11 MiB
Packager        : Daniel M. Capella <polyzen@archlinux.org>
Build Date      : Thu 11 Jan 2024 23:35:06 CET
Install Date    : Tue 12 Mar 2024 00:01:05 CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by davidbarsky** [comment]
@jonaspleyer what version of rustc do you have?

**Comment by jonaspleyer** [comment]
```
$ rustc --version
rustc 1.76.0 (07dca489a 2024-02-04)
```

**Comment by daniel-abramov** [comment]
@jonaspleyer, how do you use `rust_analyzer` from Neovim? Do you manage your extensions with `mason-lspconfig`? If so, don't forget that `mason` would download a local version stored in `~/.local/share/nvim/mason/bin/` (or similar). You can run `:LspInfo` in Neovim to check where your `rust_analyzer` is located. If so, run `:LspInstall rust_analyzer` or simply re-install/update your `rust_analyzer`. Hope this helps!

**Comment by jonaspleyer** [comment]
Thanks @Veykril and @daniel-abramov it was totally my fault. I have installed rust-analyzer via mason and updating that fixed it as well. Thanks so much!

**Comment by Eli-Pinchover** [comment]
here is rust program:
#![allow(unused)]
mod codec;

use std::net::SocketAddr;
use std::time::Duration;

use anyhow::Context;
use bitcoin::p2p::message::{NetworkMessage, RawNetworkMessage};
use bitcoin::p2p::message_network::VersionMessage;
use bitcoin::p2p::{Address, ServiceFlags};
use bitcoin::Network;
use clap::Parser;
use codec::BitcoinCodec;
use futures::{SinkExt, StreamExt, TryFutureExt};
use rand::Rng;
use tokio::net::TcpStream;
use tokio::time::error::Elapsed;
use tokio::time::timeout;
use tokio_util::codec::Framed;

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// The address of the node to reach to.
    /// `dig seed.bitcoin.sipa.be +short` may provide a fresh list of nodes.
    #[arg(short, long, default_value = "165.22.213.4:8333")]
    remote_address: String,

    /// The address of this local node.
    /// This address doesn't matter much as it will be ignored by the bitcoind node
    #[arg(short, long, default_value = "0.0.0.0:0")]
    local_address: String,
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    init_tracing();
    let args = Args::parse();

    let remote_address = args.remote_address
        .parse::<SocketAddr>()
        .context("Invalid remote address")?;
    let local_address = args.local_address
        .parse::<SocketAddr>()
        .context("Invalid local address")?;
    let mut stream: Framed<TcpStream, BitcoinCodec> = connect(&remote_address).await?;

    Ok(perform_handshake(&mut stream, &remote_address, local_address).await?)
}

async fn connect(remote_address: &SocketAddr) -> Result<Framed<TcpStream, BitcoinCodec>, Error> {
    let connection = TcpStream::connect(remote_address).map_err(Error::ConnectionFailed);
    // Most nodes will quickly respond. If they don't, we'll probably want to talk to other nodes instead.
    let stream = timeout(Duration::from_millis(500), connection)
        .map_err(Error::ConnectionTimedOut)
        .await??;
    let framed = Framed::new(stream, BitcoinCodec {});
    Ok(framed)
}

/// Perform a Bitcoin handshake as per [this protocol documentation](https://en.bitcoin.it/wiki/Protocol_documentation)
async fn perform_handshake(
    stream: &mut Framed<TcpStream, BitcoinCodec>,
    peer_address: &SocketAddr,
    local_address: SocketAddr,
) -> Result<(), Error> {
    let version_message = RawNetworkMessage::new(
        Network::Bitcoin.magic(),
        NetworkMessage::Version(build_version_message(peer_address, &local_address)),
    );

    stream
        .send(version_message)
        .await
        .map_err(Error::SendingFailed)?;

    while let Some(result) = stream.next().await {
        match result {
            Ok(message) => match message.payload() {
                NetworkMessage::Version(remote_version) => {
                    tracing::info!("Version message: {:?}", remote_version);

                    stream
                        .send(RawNetworkMessage::new(
                            Network::Bitcoin.magic(),
                            NetworkMessage::Verack,
                        ))
                        .await
                        .map_err(Error::SendingFailed)?;

                    return Ok(());
                }
                other_message => {
                    // We're only interested in the version message right now. Keep the loop running.
                    tracing::debug!("Unsupported message: {:?}", other_message);
                }
            },
            Err(err) => {
                tracing::error!("Decoding error: {}", err);
            }
        }
    }

    Err(Error::ConnectionLost)
}

#[derive(Debug, thiserror::Error)]
enum Error {
    #[error("Connection failed: {0:?}")]
    ConnectionFailed(std::io::Error),
    #[error("Connection timed out")]
    ConnectionTimedOut(Elapsed),
    #[error("Connection lost")]
    ConnectionLost,
    #[error("Sending failed")]
    SendingFailed(std::io::Error),
}

fn build_version_message(
    receiver_address: &SocketAddr,
    sender_address: &SocketAddr,
) -> VersionMessage {
    /// The height of the block that the node is currently at.
    /// We are always at the genesis block. because our implementation is not a real node.
    const START_HEIGHT: i32 = 0;
    /// The most popular user agent. See https://bitnodes.io/nodes/
    const USER_AGENT: &str = "/Satoshi:25.0.0/";
    const SERVICES: ServiceFlags = ServiceFlags::NONE;

    let sender = Address::new(sender_address, SERVICES);
    let timestamp = chrono::Utc::now().timestamp();
    let receiver = Address::new(&receiver_address, SERVICES);
    let nonce = rand::thread_rng().gen();
    let user_agent = USER_AGENT.to_string();

    VersionMessage::new(
        SERVICES,
        timestamp,
        receiver,
        sender,
        nonce,
        user_agent,
        START_HEIGHT,
    )
}

pub fn init_tracing() {
    use tracing::level_filters::LevelFilter;
    use tracing_subscriber::prelude::*;
    use tracing_subscriber::EnvFilter;

    let env = EnvFilter::builder()
        .with_default_directive(LevelFilter::INFO.into())
        .with_env_var("RUST_LOG")
        .from_env_lossy();

    let fmt_layer = tracing_subscriber::fmt::layer()
        .compact()
        .with_file(true)
        .with_line_number(true)
        .with_thread_ids(false)
        .with_target(false);
    tracing_subscriber::registry()
        .with(fmt_layer)
        .with(env)
        .init();
}perform a code review on the project. 

List what you like about it and what you don't.
Describe how easy to read and how maintainable this code is.
Mention where the code isn't very idiomatic, ergonomic or reliable. 
Suggest fixes and adjustments (no need to actually fix these, just suggest the fixes).
Treat it like a pull request.

**Comment by tripti-agarwal** [comment]
I am running into a similar issue when installing verus with rust-analyzer in VS Code. I do have a latest version of VS code

**Comment by sladg** [comment]
Running `rustup update` solved the issue for me

**Comment by hexavik** [comment]
Reloading the editor (for both VSCode and Zed) solved the issue.

**Comment by hexavik** [comment]
May I know the version of both Rust and the editor?

**Comment by sajshuai** [comment]
It may be a problem with the project directory permissions. I changed it to 777 and the problem was solved.

**Comment by RobinWragg** [comment]
I am also having this problem, fully updated.
macOS Sonoma 14.1.1
Vscode 1.100.2
rustc 1.87.0
rust-analyzer 0.3.1975

**Comment by AlejandroFNadal** [comment]
Yep, I was using Packer and Mason and running both updates as well as rustup update fixed the issue

**Comment by hades** [comment]
I had the same problem with extension version v0.4.2322 in VSCodium. I solved it by installing a standalone rust-analyzer binary:

```
$ rustup component add rust-analyzer
```

and setting the server path to the system component in the extension settings:

```
    "rust-analyzer.server.path": "/usr/lib/rustup/bin/rust-analyzer"
```

**Comment by purpl3Himself** [comment]
> I had the same problem with extension version v0.4.2322 in VSCodium. I solved it by installing a standalone rust-analyzer binary:
> 
> ```
> $ rustup component add rust-analyzer
> ```
> 
> and setting the server path to the system component in the extension settings:
> 
> ```
>     "rust-analyzer.server.path": "/usr/lib/rustup/bin/rust-analyzer"
> ```

Also worked for me perfectly.
for: rustc 1.91, rustup 1.28.2 stable-x86_64-pc-windows-msvc, in VSCodium-v1.92.2
I dont know about async_trait, because it happened to not work for me after some version of rust-analyzer, or rustc, OR BOTH hahahahah the thing is: This perfectly worked to me.

**Comment by ChayimFriedman2** [comment]
@hades Could it be that VSCodium failed to update rust-analyzer for you?

**Comment by ChayimFriedman2** [comment]
@hades Your rust-analyzer version is way too old. Could it be that VSCodium failed to update it?

**Comment by hades** [comment]
> [@hades](https://github.com/hades) Your rust-analyzer version is way too old. Could it be that VSCodium failed to update it?

Indeed! Thanks for the pointer. Turns out I was running an old vscodium version, which wasn't compatible with the new releases of rust-analyzer.
