### ISSUE TITLE
Investigate why Autoref doesn't work with Minicore/Tests

### ISSUE THREAD

**Issue by davidbarsky** [rust-lang/rust-analyzer#16685]
- `impl ForeignTrait for LocalStruct` and `impl ForeignTrait for &LocalStruct` provide completions on `let t = &TestStruct` in _both_ tests and a running binary.
- `impl ForeignTrait for &LocalStruct` only provides completions for provide completions on `let t = TestStruct` in a running binary. 
    - This makes me think that there's a bug in `minicore`—or that I might not be understanding some important details—because this behavioral split reproduces with and without my filtering changes.

_Originally posted by @davidbarsky in https://github.com/rust-lang/rust-analyzer/pull/16555#discussion_r1503046156_

**Comment by HKalbasi** [comment]
Doesn't adding more minicore flags help? Maybe `minicore: deref` is not enough? Supporting `minicore: *` could help in these situations.

**Comment by Veykril** [comment]
Hmm, actually that test can't work can it? Autoref only applies at most once, but for the call to be valid in that example we need to have a double reference, once for the receiver and once for the impl self type. So if we start from a `TestStruct` receiver we will only walk up to `&TestStruct` which is still not a valid callee for the impl 

```rs
impl foo::TestTrait for &TestStruct {
    fn some_method(&self) {}
}
```
as that needs a receiver of `&&TestStruct`

**Comment by davidbarsky** [comment]
Oh, I think you're right: I think the lack of syntax highlighting in the fixture blinded me to the fact that _even without my changes_ in #16555, the following does not get completions for `some_method`.

```
struct TestStruct;

impl crate_b::TestTrait for &TestStruct {
    fn some_method(&self) {}
}

#[test]
fn test() {
    let t = TestStruct;
    t.$0
}
```

There's no bug in minicore.
