### ISSUE TITLE
Parentheses inside Strings are considered when colouring parentheses/brackets, screwing up all colours on the line

### ISSUE THREAD

**Issue by MoistPyro** [rust-lang/rust-analyzer#16711]
**rust-analyzer version**: 0.3.1860-standalone (5346002d0 2024-02-25)

**rustc version**: 1.74.1

**code snippet to reproduce**: 
```rust
let x = "lorum ip (s) um";
x.split(" ")
  .take_while(|s| !s.contains("("))
  .collect();
```
visual bug when a parentheses is inside a string.
First parentheses turns red, while colour-coding for all others is screwed up.
Parentheses inside Strings and strs should not be considered when colouring brackets.

**Comment by ShoyuVanilla** [comment]
This would be related to vscode or tree-sitter, depending on your text editor

**Comment by Veykril** [comment]
^

rust-analyzer is not responsible for coloring matching parentheses, that's a text editor feature
