### ISSUE TITLE
Constant crashing due to "unexpected synthetic: SyntheticSyntax"

### ISSUE THREAD

**Issue by ThomasMiz** [rust-lang/rust-analyzer#16712]
A few days ago, rust-analyzer started behaving a bit weird and taking longer than usual. Today it's been crashing nonstop all day, I even uninstalled everything and re-installed with rustup, and the behavior persisted. At one point today every character I typed caused another worker thread panic message.

I have tried to create a minimum reproducible example, but this odd behavior seems to follows no God, much less listens to mortals. I am using VS Code, I've tried adding `"rust-analyzer.trace.server": "verbose"` and `"rust-analyzer.cargo.extraEnv": {"RA_LOG": "info", "RUST_BACKTRACE": "full" }` to `settings.json` but even after a restart this seemed to have no effect. Still, I have captured the [stderr output into a file here](https://github.com/rust-lang/rust-analyzer/files/14441983/stderr.txt).

This file holds the output of around an hour of usage. It seems to be particularly angry about me using the `Result` enum, multiple of the crashes were when typing `Result::`something.

If there's anything else I can provide to help, do let me know! Thank you! 😊

rustc version: 1.76.0 (07dca489a 2024-02-04)
rust-analyzer version: 0.3.1860-standalone (5346002d0 2024-02-25)

**Comment by Young-Flash** [comment]
Fixed in https://github.com/rust-lang/rust-analyzer/pull/16684, try the lastest nightly release

**Comment by ThomasMiz** [comment]
> Fixed in #16684, try the lastest nightly release

Excellent! Should I close this issue?

**Comment by Young-Flash** [comment]
let's close if it does fixed

**Comment by ThomasMiz** [comment]
Sure! I'm on nightly now, I'll let you know how it goes. It's definitely behaving better than before 😅
