### ISSUE TITLE
Linting Problem with Proc-Macro on public vs private functions

### ISSUE THREAD

**Issue by arpadav** [rust-lang/rust-analyzer#16721]
**rust-analyzer version**: rust-analyzer version: 0.3.1860-standalone

**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04

**relevant settings**: None

**repository link**: [crosstalk](https://crates.io/crates/crosstalk)

**description**

I have a procedural macro, that implements a trait on-the-fly for a struct<T>, where T is an enum. When calling the macro, I implement the trait and return the struct<T>.

However, rust-analyzer linting does not recognize the functions of struct<T> being called IFF they are ***public***. If they are private, then the code does not compile, but rust-analyzer suddenly performs correct linting.

**code snippet to reproduce**: 
```rust
// in src/lib.rs
pub struct UnboundedCommonNode<T> {
    pub node: InnerUnboundedCommonNode<T>,
}
impl <T> UnboundedCommonNode<T> 
where
    T: Eq + Hash + Copy + Clone + PartialEq,
    InnerUnboundedCommonNode<T>: PubSub<T>,
{
    pub fn new () -> Self {
        Self { node: InnerUnboundedCommonNode::<T>::new() }
    }

    // THIS IS PUBLIC
    pub fn publisher<D: 'static>(&mut self, topic: T) -> Result<Publisher<D, T>, Box<dyn std::error::Error>> {
        self.node.publisher(topic)
    }

    // THIS IS PUBLIC
    pub fn subscriber<D: Clone + Send + 'static>(&mut self, topic: T) -> Result<Subscriber<D, T>, Box<dyn std::error::Error>> {
        self.node.subscriber(topic)
    }

    // ...
}
```

Then the result is:

![image](https://github.com/rust-lang/rust-analyzer/assets/34720962/44498c51-8739-440b-9be8-6e4a2eeee98c)

If I remove the `pub` from any function (not `new`):

![image](https://github.com/rust-lang/rust-analyzer/assets/34720962/339c6e44-7900-4198-afe1-2294572a5356)

Now it lints properly, but then I get errors where it can't compile (as expected), since it can't access these private functions.

**Comment by lnicola** [comment]
I assume the macro is `crosstalk::unbounded!`, as called in `~main.rs`, but I don't see the `publisher` and `subscriber` methods on `UnboundedCommonNode` -- they're in the `PubSub` trait.

**Comment by arpadav** [comment]
> I assume the macro is `crosstalk::unbounded!`, as called in `~main.rs`, but I don't see the `publisher` and `subscriber` methods on `UnboundedCommonNode` -- they're in the `PubSub` trait.

Sorry about that, the repo should be updated by now: [https://github.com/arpadav/crosstalk/blob/main/src/lib.rs](https://github.com/arpadav/crosstalk/blob/main/src/lib.rs)

**Comment by lnicola** [comment]
I see. This has nothing to do with macros, then. However, we don't support local implementations of traits (cf. https://github.com/rust-lang/rfcs/blob/master/text/3373-avoid-nonlocal-definitions-in-fns.md). Rewriting it as

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/ef7a08f4-c71c-4fc4-bf77-9e3149b37da3)

makes it work, I think we treat anonymous constants in a special way.

**Comment by arpadav** [comment]
@lnicola what I am returning from the macro is essentially what you have written, where it is a scope where the trait is implemented, and it creates the node.

the macro expansion is identical to your result, however, instead of the TODO's, it actually implements it accordingly. This is why I am confused, because if it is exactly the same semantically, why does it work without the macro but not with? I am aware that this manual way works, but that defeats the whole point of what I was trying to do with the macro — reduce the boilerplate and implement the trait for a specific enum, so that each branch of the enum is tied to a buffer of a certain type. the macro does this matching in [https://github.com/arpadav/crosstalk/blob/1e8dd5b3a6c42110b829b97d7114644f3a339af9/crosstalk-macros/src/lib.rs#L343](https://github.com/arpadav/crosstalk/blob/1e8dd5b3a6c42110b829b97d7114644f3a339af9/crosstalk-macros/src/lib.rs#L343) 

rust compiles fine, but I find it bizarre that rust-analyzer is able to successfully assign types when there is an error because the function is not found, but it fails when it is compiled correctly

**Comment by arpadav** [comment]
@lnicola and FYSA I understand why the local / in-function impl's are not incentivized. I did not necessarily want to do it this way either, but I did not seem to have a choice

**Comment by lnicola** [comment]
> the macro expansion is identical to your result

It's not. The macro expands to:

```rust
    let mut node = {
        impl crosstalk::PubSub<TopicZoo> for crosstalk::InnerUnboundedCommonNode<TopicZoo> {
            // ...
        }
        crosstalk::UnboundedCommonNode::<TopicZoo>::new()
    };
```

The difference being that we support `const _: () = { impl .. for .. {} };` explicitly. Even `const _C: () = { ... }` is not supported.

> I find it bizarre that rust-analyzer is able to successfully assign types when there is an error because the function is not found

It doesn't. It fails to resolve `crosstalk::UnboundedCommonNode::<TopicZoo>::new()` because of the `InnerUnboundedCommonNode<T>: PubSub<T>` constraint, because the `impl PubSub<TopicZoo> for InnerUnboundedCommonNode<TopicZoo> ` is not visible, because it's in an inner block. If you change the macro to avoid that block, for example:

```rust
crosstalk::unbounded! {
    TopicZoo::Topic1 => Vec<u32>,
    TopicZoo::Topic2 => String,
    TopicZoo::Topic3 => Vehicle,
    TopicZoo::Topic4 => HashMap<&str, Vec<Vehicle>>,
    TopicZoo::Topic5 => Color,
}

fn main() {
    let mut node = crosstalk::UnboundedCommonNode::<TopicZoo>::new();
}
```

, then everything works:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/f55492db-0c9b-4617-b62a-0f86f72c66a2)

**Comment by arpadav** [comment]
This makes sense... I appreciate your responses. And I agree, as a user that does seem more friendly. I'll likely rename my macro to either `init` or `impl` and then call it like you have, with some additional refactoring. This does solve the linting issue as well as makes things clearer. Thanks a bunch!

Could close this if there are no plans for local impl's to be visible by rust-analyzer, since now I see more clearly why it is discouraged from a user perspective
