### ISSUE TITLE
VsCode Setting: Continue Comments on Newline not working anymore

### ISSUE THREAD

**Issue by yzobus** [rust-lang/rust-analyzer#16720]
Working with v0.3.1860. Pre-Release Version also tested. Vscode 1.87

When hitting return in a doc-comment, the newline does not start with the respective pre-fix, but is empty. 
Sadly I am not sure anymore in which version before  this feature worked.

**Comment by Young-Flash** [comment]
https://github.com/rust-lang/rust-analyzer/pull/16695 should fix this, try the lastest nightly release
