### ISSUE TITLE
Possible Incompleteness

### ISSUE THREAD

**Issue by YichiZhang0613** [rust-lang/rust-analyzer#16734]
In rust-analyzer-master/crates/hir-expand/src/name.rss, I think the code should check text.len() <= 22 as comments mentioned before use text to avoid possible incompleteness.
```rust
/// Shortcut to create inline plain text name. Panics if `text.len() > 22`
    const fn new_static(text: &'static str) -> Name {
        Name::new_text(SmolStr::new_static(text))
    }
```

**Comment by lnicola** [comment]
No, it's shouldn't check, since it's fine to panic for strings known at compile-time. But the comment is outdated anyway, since we no longer panic in that case.
