### ISSUE TITLE
vscode outline cant diff private or public function of rust code

### ISSUE THREAD

**Issue by q2333gh** [rust-lang/rust-analyzer#16736]

**Comment by lnicola** [comment]
What do you mean? Anyway, we don't do diffs.

**Comment by q2333gh** [comment]
![image](https://github.com/rust-lang/rust-analyzer/assets/32679742/b67d317f-46bf-4ad7-b161-803b8abd5618)
I mean the different icon of  private function and public function. 
This is InteliJ IDE  look like : 
![image](https://github.com/rust-lang/rust-analyzer/assets/32679742/e9b6dbf3-6d94-48b2-bd56-a532a03546b1)

**Comment by Young-Flash** [comment]
we may could attch a `tokenModifier` to identify `public` or `private`, however, even we do that it still a editor level feature to show the diff icon, or, some extentsion could also make it possible.

**Comment by q2333gh** [comment]
> rust-analyzer has `tokenModifier` to identify `public`, however, it still a editor level feature to show the diff icon, or, some extentsion could also make it possible.

Thanks~ i got it . the display diff icon work should vscode itself do .

**Comment by cherio-corro** [comment]
This would be a very useful feature. Most evolved IDEs have it.
