### ISSUE TITLE
rust-analyzer does not call correct cargo binary

### ISSUE THREAD

**Issue by Taowyoo** [rust-lang/rust-analyzer#16754]
# Problem

On VSCode, at latest stable release which just been released within 24 hours `v0.3.1868`

The extension or maybe `rust-analyzer` does not call `cargo` in path. It always calls `$HOME/.cargo/bin/cargo` 

I have custom toolchain in different folder with cargo installed, I add that cargo to path with `direnv` so when calling `cargo` in command line it will call that `cargo` first instead of the default installed one under ``$HOME/.cargo`.

# Expect behavior

I assume the `rust-analyzer` should call the `cargo` in folders at front of the PATH system variable.

# Temporary solution

I solve the issue by rollback the VSCode extension to `v0.3.1860`

**Comment by lnicola** [comment]
https://github.com/rust-lang/rust-analyzer/pull/16665

**Comment by Veykril** [comment]
Well that's a nice conflict of interests we have here now

**Comment by Taowyoo** [comment]
Thank you for quick response.
