### ISSUE TITLE
Rust Analyzer broken on pre-release and stable v0.3.1868

### ISSUE THREAD

**Issue by weezy20** [rust-lang/rust-analyzer#16783]
`cargo check` is running fine but RA isn't. 
Logs: 
```sh
2024-03-08T08:40:08.690129Z ERROR flycheck: Flycheck failed to run the following command: CommandHandle { program: "cargo", arguments: ["check", "--message-format=json-diagnostic-rendered-ansi", "--target-dir:/tmp/rust-analyzer-check"], current_dir: Some("/home/abhishek/w/pop-cli") }
```
**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04)

![image](https://github.com/rust-lang/rust-analyzer/assets/15669111/1bcce205-5d2a-4aa8-af5b-2b2672898b11)

**Comment by lnicola** [comment]
Does it work if you run Code from the terminal?

**Comment by lnicola** [comment]
Never mind that, what did you set `rust-analyzer.cargo.targetDir` to?

**Comment by weezy20** [comment]
@lnicola Nothing. here's my `settings.json`: 

```json
 {
     "rust-analyzer.showUnlinkedFileNotification": false
 }
```

**Comment by lnicola** [comment]
What about your VS Code (not workspace) settings?

**Comment by weezy20** [comment]
@lnicola So I found this:
```json
"rust-client.engine": "rust-analyzer",
"rust-analyzer.check.overrideCommand": [
        "cargo",
        "check",
        "--message-format=json-diagnostic-rendered-ansi",
        "--target-dir:/tmp/rust-analyzer-check"
    ],
```

**Comment by lnicola** [comment]
Yeah, `--target-dir:/tmp/rust-analyzer-check` is wrong, it even says so in your screenshot. You can use `rust-analyzer.cargo.targetDir`, split that argument, or replace `:` with `=`.

**Comment by weezy20** [comment]
`    "rust-analyzer.cargo.targetDir": "/tmp/rust-analyzer-check",` did it. Thanks for your help @lnicola . Appreciate it
