### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by Thomblin** [rust-lang/rust-analyzer#16803]
Type: <b>Bug</b>

Remote Extension host terminated unexpectedly 3 times within the last 5 minutes.

I get this error repeatedly. Extension bisect did not help to figure out if another extension is causing troubles. I am using WSL2, it worked well until a few weeks ago

Extension version: 0.3.1868
VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'wsl+debian' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (0.77GB free)|
|Process Argv|--crash-reporter-id 19e9ee34-150f-4a8b-8194-4e65e0b51411|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+debian' could not be established
</details>

**Comment by lnicola** [comment]
> Remote Extension host terminated unexpectedly 3 times within the last 5 minutes.
> Connection to 'wsl+debian' could not be established

And it works if you disable RA?

**Comment by Thomblin** [comment]
I am sorry. I thought RA is the only extension that is creating problems (well it is for a Rust project). If I launch a Go project and disable RA I see the same error. So this is something WSL or VS Code related I think.

**Comment by 122qweswd** [comment]
It seems that I've met the same situation and have no idea how to continue using the extension. So I wonder if you have any further suggestions or temporary operations dealing with the problem?

**Comment by lnicola** [comment]
@122qweswd which Linux distro are you on?

**Comment by 122qweswd** [comment]
> @122qweswd which Linux distro are you on? And do other extensions work?

I'm using Ubuntu 22.04, installed through wsl2 in windows10

**Comment by Thomblin** [comment]
@122qweswd It works again for me. However I do not really know why. I stopped and updated wsl, but I am not sure if that helped. Actually I then installed another wsl distro (alpine), which does not work either, but finally it works again with Debian. I doubt that installing another distro did any good, but many one of many restarts after updating wsl did ...

**Comment by lnicola** [comment]
Anything else in the logs when this happens? I'd file it against VS Code, since there's almost no way we can cause the extension host to crash.

**Comment by lnicola** [comment]
https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports might help investigating this.

**Comment by 122qweswd** [comment]
> https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports might help investigating this, if you encounter it again.

I tried the method before, and at least in my case, this is not useful since no 'crash' happened. 

By the way, I had read trace level log in developer tools and got a report similar to "vscode logs" of this issue: https://github.com/microsoft/vscode/issues/203807
