### ISSUE TITLE
Feature Request: Support Eclipse Theia IDE

### ISSUE THREAD

**Issue by mydoghasfleas** [rust-lang/rust-analyzer#16806]
I installed the [rust-analyzer plugin from open-vsx.org](https://open-vsx.org/extension/rust-lang/rust-analyzer) in the [Eclipse Theia IDE](https://github.com/eclipse-theia/theia) on Windows 10 and opened a Rust project.

After trying to start rust-analyzer the IDE gives the following message:

```
Unfortunately we don't ship binaries for your platform yet.
You need to manually clone the rust-analyzer repository and run cargo xtask install --server to build the language server from sources.
If you feel that your platform should be supported, please create an issue about that [here](https://github.com/rust-lang/rust-analyzer/issues) and we will consider it.
```

In VS Code it works fine.

Can you please make rust-analyzer work for Eclipse Theia as well?

**Comment by lnicola** [comment]
Do you happen to have a 32-bit version of Theia? What if you download the VSIX and install it manually?

**Comment by mydoghasfleas** [comment]
I'm not sure how to check. There is only one link for the latest version for Windows on the Theia website. The Help > About page in the app also does not give a clue as to whether it's 32 or 64 bit.

I think I'll close this issue and raise this with the Theia community instead. I mean, if it works for VS Code, it should work for Theia, right?

**Comment by lnicola** [comment]
32-bit apps (used to) have a star in the Details tab of Task Manager. It might be a column now, not sure.

But you can still try to download and install the VSIX. Theia and Code aren't 100% compatible, so it's not guaranteed that it will work. I think at one point, Theia was based on a very old version of Code, so some APIs might not be available.
