### ISSUE TITLE
Did you stop supporting Intel Mac?

### ISSUE THREAD

**Issue by ShikiSuen** [rust-lang/rust-analyzer#16816]
Today I started using VSCode to open a RustRover project to see how it works.
But the rust analyzer complaints as follows:

> Apologies: The current environment is built on an unsupported host platform! The CN-EN bilingual service is only released for Windows_x64, GNU/Linux_x64, and Mac ARM64(M1 & M2...). We suggest you to switch the environment to continue your project.
>
> Source: rust-analyzer(CN)

![image](https://github.com/rust-lang/rust-analyzer/assets/3164826/f07a8555-97e5-40aa-9b2d-a08feaf23915)

**Comment by ShikiSuen** [comment]
Oh... It looks like a non-official extension.
Closing this issue for now.
<img width="471" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/3164826/ea2a3633-1bfc-4c61-85d6-f59ba001ee3d">

**Comment by lnicola** [comment]
Yes, that's https://github.com/rust-doc/RustAnalyzerCN. It's not really open source and we don't exactly know what's in there.
