### ISSUE TITLE
`"editor.formatOnType": true` (vscode) behaves weirdly with calls (and attributes on calls)

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust-analyzer#16848]
**rust-analyzer version**: 0.4.1881-standalone (14558af15 2024-03-14)

**relevant settings**: `"editor.formatOnType": true` 

**code snippet to reproduce**: 
```rust
fn main() {
    f();

    #[allow(unreachable_code)]
    g();
}
```

If I type `{` before `f();` nothing happens (well, except the `{` that was typed, obv). If I type `{` before `g();` a matching `}` is added but not where I'd expect:

```rust
fn main() {
    {f();

    #[allow(unreachable_code)]
    {g}();
}
```

This is what I would expect to see instead:

```rust
fn main() {
    { f() };

    #[allow(unreachable_code)]
    { g() };
}
```

**Comment by Veykril** [comment]
Relevant code is here https://github.com/rust-lang/rust-analyzer/blob/0dd89d7ee7800c53dc10cec941c4e740562d54df/crates/ide/src/typing.rs#L105-L189

**Comment by roife** [comment]
For the first issue, I found that it is intentional not to insert brackets automatically when the expression is used as a statement.

https://github.com/rust-lang/rust-analyzer/blob/0dd89d7ee7800c53dc10cec941c4e740562d54df/crates/ide/src/typing.rs#L178-L181

For the second point, the attributes are parsed as part of the call-expr, resulting in strange behavior.

```
            EXPR_STMT@28..63
              CALL_EXPR@28..62
                ATTR@28..54
                  POUND@28..29 "#"
                  L_BRACK@29..30 "["
                  META@30..53
                    PATH@30..35
                      PATH_SEGMENT@30..35
                        NAME_REF@30..35
                          IDENT@30..35 "allow"
                    TOKEN_TREE@35..53
                      L_PAREN@35..36 "("
                      IDENT@36..52 "unreachable_code"
                      R_PAREN@52..53 ")"
                  R_BRACK@53..54 "]"
                WHITESPACE@54..59 "\n    "
                PATH_EXPR@59..60
                  PATH@59..60
                    PATH_SEGMENT@59..60
                      NAME_REF@59..60
                        IDENT@59..60 "g"
                ARG_LIST@60..62
                  L_PAREN@60..61 "("
                  R_PAREN@61..62 ")"
```

Maybe we should identify attributes before inserting.

**Comment by WaffleLapkin** [comment]
>  If it's a statement in a block, we don't know how many statements should be included 

I'm not sure I understand the reasoning here. Why don't we wrap just the whole expression in a statement? If the user wants more, they can move things inside the braces.

> For the second point (`g()`), the attributes are parsed as part of the call-expr, resulting in strange behavior.

Uh, that's fun. I guess a parsing which would make more sense is to have "attribute expr" which would wrap the call expr. But ig that would make things hard elsewhere, because to check attributes you'd have to go outwards...

**Comment by roife** [comment]
> If the user wants more, they can move things inside the braces.

Hmm... That makes sense.

> I guess a parsing which would make more sense is to have "attribute expr" which would wrap the call expr.

I'm not sure. Perhaps we can also directly hack here: if it is identified that the front part of expr is attr, we consider it as inserting `{}` around the entire expr (excluding the `attr` part).
