### ISSUE TITLE
Build script build is run with `--all-targets` even if `rust-analyzer.check.allTargets` is false

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#16859]
This is easily confirmed by checking out [hashbrown](https://github.com/rust-lang/hashbrown/) and trying to work on it with stable while also using
```
{
    "rust-analyzer.cargo.buildScripts.useRustcWrapper": false,
    "rust-analyzer.check.allTargets": false
}
```
It is understandable that `allTargets: false` is needed, since `cargo check --all-targets` fails on stable on hashbrown. (Though this default can be quite confusing when one doesn't know about this toggle.)

But with the configuration above I would then expect RA to work fine on hashbrown, and yet it still tries to build the benchmarks:

```
2024-03-17T10:08:52.660154Z ERROR rust_analyzer::main_loop: FetchBuildDataError:
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> benches/insert_unique_unchecked.rs:3:12
  |
3 | #![feature(test)]
  |            ^^^^


error: aborting due to 1 previous error


For more information about this error, try `rustc --explain E0554`.

error: could not compile `hashbrown` (bench "insert_unique_unchecked") due to 2 previous errors
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> benches/bench.rs:5:12
  |
5 | #![feature(test)]
  |            ^^^^


error: aborting due to 1 previous error


For more information about this error, try `rustc --explain E0554`.

error: could not compile `hashbrown` (bench "bench") due to 2 previous errors


```

**rust-analyzer version**: `rust-analyzer version: 0.3.1877-standalone`

**Comment by Veykril** [comment]
The problematic line is here https://github.com/rust-lang/rust-analyzer/blob/dd11328bb3e34e245de595d140dc91b3b458707f/crates/project-model/src/build_scripts.rs#L86-L89

Presumably it should suffice to replace that by emitting `--lib` and `--bins` which should be equivalent for our purposes according to https://github.com/rust-lang/cargo/blob/69726309bf12443a618643cc86125ef60dcbecfb/src/doc/man/generated_txt/cargo-check.txt#L110-L112.

Though now I wonder, this would probably imply that any build deps of dev-dependencies would no longer be built (as we omitted all dev binaries), leaving r-a with missing information there 🤔 I guess the simplest solution for now would be to add a `rust-analyzer.cargo.allTargets` setting that toggles the flag above.

**Comment by poliorcetics** [comment]
I'll try to send an MR for this soon
