### ISSUE TITLE
Test Explorer: Only supports unit tests (of main crate)

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust-analyzer#16874]
The test explorer seems to only work for the unit tests of the main crate. While all other tests are shown, it's not possible to run them. This includes unit tests of other crates in the workspace, as well as integration tests in general.

![image](https://i.imgur.com/JjOfxra.gif)

**rust-analyzer version**: 0.4.1884-standalone (b6d1887bc 2024-03-17)

**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04)

**relevant settings**:
```json
"rust-analyzer.testExplorer": true,
```

**repository link**: https://github.com/LiveSplit/livesplit-core

**Comment by HKalbasi** [comment]
I looked at this a bit, and found out that the problem of not running integration tests is a bug, and if you expand each integration test manually it will run it. But the problem of not running unit tests in other crates is bigger. Currently, it is assumed that a single `cargo test` will run all tests in a workspace, which is false in your project. Is there any single cargo command that can run all of your tests?

**Comment by CryZe** [comment]
![image](https://github.com/rust-lang/rust-analyzer/assets/1451630/244f9566-b536-4b8f-9302-a204fa480527)

`cargo test --workspace` seems to work. Or `--package the-crate` for an individual crate.

What's surprising is that the rest of rust-analyzer (the test code lenses and co.) can run these tests just fine. I assume the code is not (properly?) shared between both aspect of rust-analyzer?

**Comment by HKalbasi** [comment]
Yes the code sharing here is less than ideal, but here it wouldn't help much as with the code lenses there were no way to run all tests at the same time, so there were no command emitting `--workspace`.

**Comment by CryZe** [comment]
Thank you so much :)
