### ISSUE TITLE
RA fails to find proc-macro dylibs in multi-workspace repo

### ISSUE THREAD

**Issue by svix-jplatte** [rust-lang/rust-analyzer#16898]
Recently, I noticed a lot of these errors from rust-analyzer:

```
proc macro `DeriveEntityModel` not expanded: proc macro crate is missing dylib
```

… at first I thought it was related to using nightly with a bunch of customizations, but I tried to narrow it down and it looks like it's actually because my main work codebase is a repo with multiple cargo workspaces: https://github.com/svix/svix-webhooks

Whenever I open a file in there that uses a third-party derive macro (e.g. `bridge/svix-bridge/src/config/mod.rs`), I get that error on it. Hope it's reproducible.

**rust-analyzer version**: 0.4.1888-standalone (6fce1d71d 2024-03-19)
**rustc version**: 1.76.0 (07dca489a 2024-02-04)

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/16899 should fix this I think

**Comment by svix-jplatte** [comment]
Yeah, issue is gone in today's nightly. Thanks for the extremely fast response! :blue_heart:
