### ISSUE TITLE
How could I use the extra flag `-W clippy::pedantic` if I use `clippy` as my check command?

### ISSUE THREAD

**Issue by dataCobra** [rust-lang/rust-analyzer#16910]
Hello,

as the title already says I'm trying to get the extra flag working with `clippy` as my check command.

I checked both manuals but couldn't find a solution. I've already tried using the `extraArgs` option which doesn't work.

Maybe I'm doing something wrong here or I use the extra flag wrong.

Help is really appreciated.

**Comment by alibektas** [comment]
> Hello,
> 
> as the title already says I'm trying to get the extra flag working with `clippy` as my check command.
> 
> I checked both manuals but couldn't find a solution. I've already tried using the `extraArgs` option which doesn't work.
> 
> Maybe I'm doing something wrong here or I use the extra flag wrong.
> 
> Help is really appreciated.

Can you share the related part of your configuration file? 

It should normally work.

**Comment by Veykril** [comment]
setting `extraArgs` to `["--". "-W", "clippy::pedantic"]` should work I think, otherwise you can try `rust-analyzer.check.overrideCommand` and override the full command instead.

**Comment by dataCobra** [comment]
Here is the configuration I did with `nvim-lspconfig` in lua:
```
  -- Setup rust-language-server
  require'lspconfig'.rust_analyzer.setup{
    capabilities = capabilities,
    on_attach = on_attach,
    settings = {
        ['rust-analyzer'] = {
            check = {
                command = "clippy",
                extraArgs = {"-- -Wclippy::pednatic"},
            }
        }
    },
  }
```

The error LspLog shows me looks like this:
```
[ERROR][2024-03-21 16:24:12] .../vim/lsp/rpc.lua:734    "rpc"   "/home/datacobra/.cargo/bin/rust-analyzer"      "stderr"        '[ERROR flycheck] Flycheck failed to run the following command: CommandHandle { program: "cargo", arguments: ["clippy", "--workspace", "--message-format=json", "--manifest-path", "/bigdata/datacobra/Projects/Rust/minigrep/Cargo.toml", "--all-targets", "-- -Wclippy::pedantic"], current_dir: Some("/bigdata/datacobra/Projects/Rust/minigrep") }\n'
```

**Comment by dataCobra** [comment]
> setting `extraArgs` to `["--". "-W", "clippy::pedantic"]` should work I think, otherwise you can try `rust-analyzer.check.overrideCommand` and override the full command instead.

I've just tested it with your hint, but this doesn't work either.

I haven't tried `overrideCommand` because I don't want to change the whole command when there might be a better way.

**Comment by lnicola** [comment]
Or you might want a clippy.toml, we have an example in this repo.

**Comment by dataCobra** [comment]
I assume the `current_dir` part is the issue.

I'll check the configuration in the Cargo.toml.

Thanks.

**Comment by Veykril** [comment]
Note that your configuration has a typo in it "pednatic"

**Comment by dataCobra** [comment]
> Note that your configuration has a typo in it "pednatic"

This is now a bit embarrassing.

That seems to be the issue and the whole 2 hours I didn't see the typo...

**Comment by dataCobra** [comment]
Okay, it was the typo... I'm sorry for wasting your time. :see_no_evil: 

Everything works now as expected.

Thanks for the heads up. :+1:
