### ISSUE TITLE
Endless error notifications

### ISSUE THREAD

**Issue by kryptan** [rust-lang/rust-analyzer#16923]
Rust analyzer shows infinite stream of errors:

https://github.com/rust-lang/rust-analyzer/assets/11528855/752bbbf8-f442-4986-aff3-49bb8f8dffa1

 "Go to output" and "Turn Off Notifications" buttons do not work.

I have `showRequestFailedErrorNotification` set to false:

![screen](https://github.com/rust-lang/rust-analyzer/assets/11528855/ef49300b-b8e4-4256-857d-f23413be2338)

Exiting  VSCode didn't work, I had to kill it.

This is a very small private project but I have large `windows` crate as a dependency. Rust analyzer in general is very slow for this project, I believe because of the `windows` crate.

```toml

[dependencies]
hidapi = "1"

[dependencies.tokio]
version = "1"
features = ["macros", "net", "rt", "sync", "time"]

[dependencies.windows]
version = "0.54"
features = [
    "implement",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_Media_Audio",
    "Win32_Media_Audio_Endpoints",
    "Win32_UI_Shell_PropertiesSystem",
]
```

**rust-analyzer version**:  rust-analyzer version: 0.3.1885-standalone (b6d1887bc 2024-03-17)

**rustc version**: rustc 1.79.0-nightly (1388d7a06 2024-03-20)

**Comment by Veykril** [comment]
This is fixed by https://github.com/rust-lang/rust-analyzer/pull/16905, I kicked off a new nightly release that should be available in an hour or two
