### ISSUE TITLE
rust-analyzer doesn't recgonize package and package's content when adding it after workspace has done loaded

### ISSUE THREAD

**Issue by timelessnesses** [rust-lang/rust-analyzer#16922]
When developing with rust-analyzer, I always get this kind of problem where if I added new package through `cargo add`, rust-analyzer will never detect the package's existence so I can't get types from it. The only workaround for me is to just reload the workspace itself so I can get the types from the rust-analyzer

https://github.com/rust-lang/rust-analyzer/assets/59832159/ed3aaf7b-6ed8-4022-a266-38f1dd099b59

**Comment by lnicola** [comment]
Can you try with the nightly version?

**Comment by timelessnesses** [comment]
> Can you try with the nightly version?

Sorry for late response, but now the issue is actually resolved when using Nightly (Pre-release in VSCode) including add and removing packages. Thanks!
