### ISSUE TITLE
There is no task provider registered for tasks of type "cargo" for VSCode workspace, again

### ISSUE THREAD

**Issue by CrendKing** [rust-lang/rust-analyzer#16949]
I'm experiencing the exact same issue as https://github.com/rust-lang/rust-analyzer/issues/9093, but in the latest version. The previous 0.3.1885 does not have issue.

**rust-analyzer version**: 0.3.1896

**rustc version**: 1.77.0 stable

**Comment by eduarddejong** [comment]
Same here.
Using the same Rustc and Analyzer version.

Using VSCodium on Linux.

I didn't change anything in my project configuration, today it does not build using Ctrl+Shift+B or explicitly entering "Run: Tasks" -> "rust: cargo build"

However, clicking the "Run", "Debug" and "Run Tests" hyperlinks shown inside the code editor above main and tests _does_ still work and also F5 to start debugging (which I have configured to launch with LLDB).
So it seems quite specifically related to the cargo build  task.

**Comment by pbl-pw** [comment]
Same too.

**Comment by Paperback** [comment]
Likewise, experiencing this issue :(

**Comment by lnicola** [comment]
> The previous 0.3.1885 does not have issue.

Are you sure? I get the same error in v0.3.1868 and v0.3.1885.

**Comment by ldericher** [comment]
Same issue, vscode with RA 0.3.1896 (on Linux 6.5.0-26), no issue on 0.3.1885

**Comment by lnicola** [comment]
Can anyone bisect this?

**Comment by ldericher** [comment]
> Can anyone bisect this?

Hmmm … now I've built a binary to check, but how do I use it with my VSCode?

**Comment by lnicola** [comment]
`cargo xtask install` will install it to `~/.cargo/bin` and also install the Code extension. You'll need to restart Code to make sure it's using the new one (i.e. don't trust "Reload window").

**Comment by ldericher** [comment]
```
2e109c7da8fb5b4adc809f30035472512e7ac7cd is the first bad commit
commit 2e109c7da8fb5b4adc809f30035472512e7ac7cd
Author: Wilfred Hughes <wilfred@meta.com>
Date:   Wed Mar 13 16:46:57 2024 -0700

    refactor: Use a single CLI args array rather than a separate subcommand field

 editors/code/src/run.ts   |  4 +---
 editors/code/src/tasks.ts | 20 ++++++++++----------
 2 files changed, 11 insertions(+), 13 deletions(-)
```

This refers to commit 2e109c7da8fb5b4adc809f30035472512e7ac7cd, but someone deeper involved should take it from here, I know nothing about the vscode extension API.

**Comment by Wilfred** [comment]
Thanks for the ping, I'll take a look. Sorry about this.

**Comment by Wilfred** [comment]
OK, this is an issue with how tasks are defined, because they're a user-facing API through tasks.json or `.code-workspace`.

If you need a workaround right now and can't downgrade, you can define your task as a `shell` command:

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"command": "cargo build",
			"problemMatcher": [
			  "$rustc"
			],
			"group": "build",
			"label": "my example cargo build task"
		  }
	]
}
```

**Comment by Wilfred** [comment]
I think there's another issue with the task declaration in package.json, it doesn't allow `cwd` at all. That looks like a pre-existing problem though.

**Comment by Barugon** [comment]
Still broken in `v0.3.1906`.

**Comment by Veykril** [comment]
The fix got merged today so it will land on next monday (or tomorrow for the nightly / 0.4 version)

**Comment by sandersaares** [comment]
I confirm that the prerelease version currently available fixes the issue for me. Thanks for fast action!

**Comment by Veykril** [comment]
Will close this then, thanks for confirming!

**Comment by Coi-l** [comment]
This started happening to me yesterday. I upgraded to the pre-release version but it is still broken for me there.

**Comment by Veykril** [comment]
Do you have an example task? The one posted here worked for me after this change

**Comment by kryptan** [comment]
I have bindings for commands like `workbench.action.tasks.runTask|rust: cargo build` using the 'Shortcut Menu Bar' extension and they stopped working in v0.3.2002. Downgrading to v0.3.1995 fixes the issue.
