### ISSUE TITLE
VSCode tasks not generating

### ISSUE THREAD

**Issue by ilmai** [rust-lang/rust-analyzer#16943]
Since the update earlier today, none of the cargo tasks in my VSCode tasks.json files are being recognized. Tasks log in VSCode is full of errors like this:

```
Error: The cargo task detection didn't contribute a task for the following configuration:
{
    "label": "rust: cargo build debug",
    "type": "cargo",
    "command": "build",
    "problemMatcher": [
        "$rustc"
    ],
    "group": "build"
}
The task will be ignored.
```

The same thing happens on two different computers in all of the projects I tested. The issue is resolved by downgrading to the previous version (0.3.1885).

**rust-analyzer version**: 0.3.1896

**rustc version**: 1.77.0

**Comment by obsgolem** [comment]
I am not positive, but this running this in the debugger it looks like it might be due to https://github.com/rust-lang/rust-analyzer/commit/4422a90b1106065146d0f3f6d0aa86c212753c10.

**Comment by StewMcc** [comment]
still reproduces in rust-analyzer version: v0.4.1897 (pre-release) fwiw

**Comment by SVilgelm** [comment]
See https://github.com/rust-lang/rust-analyzer/issues/16949
