### ISSUE TITLE
Configured tasks not showing up in `v0.3.1896`

### ISSUE THREAD

**Issue by Barugon** [rust-lang/rust-analyzer#16950]
Configured tasks in vscode are not showing up using rust-analyzer `v0.3.1896`. They work fine in the previous version, `v0.3.1885`

**rust-analyzer version**: 0.3.1896-standalone

**rustc version**: 1.77.0

**Comment by brogdonm** [comment]
I am seeing the same thing. I am unable to run any cargo-based tasks from VS Code with version `v0.3.1896`. Reverting to `v0.3.1885` allows me to run cargo-based tasks from VS Code again.

**Comment by lnicola** [comment]
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/16949.
