### ISSUE TITLE
RA sends relative glob patterns even when the LSP client does not allow it

### ISSUE THREAD

**Issue by nemethf** [rust-lang/rust-analyzer#16955]
Commit fe28e470cdf7d864fb69411e780b1e9791d6742a introduces relative glob patterns but it does not check whether the LSP client supports it.   Rust-analyzer should only use relative patterns if the client has a relativePatternSupport in its [DidChangeWatchedFilesClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#didChangeWatchedFilesClientCapabilities).

It is debatable whether this is a serious regression in nightly and it's important to fix it before the next release.  For me, it is.

CC: @Veykril

**Comment by Veykril** [comment]
Ah, that is indeed problematic. I was not aware of this being opt-in via capabilities.

**Comment by poliorcetics** [comment]
I'll take this
