### ISSUE TITLE
Request textDocument/semanticTokens/full/delta failed, panic at lookup_impl_assoc_item_for_trait_ref

### ISSUE THREAD

**Issue by frxstrem** [rust-lang/rust-analyzer#16958]
With this simple program on the current rust-analyzer pre-release VS code extension, I get an error every time I save the file:

```rust
// [dependencies]
// serde = "=1.0.197"

use serde::de::value::*;

fn f<'de, T: serde::Deserialize<'de>>() {
    T::deserialize(BoolDeserializer::<Error>::new(false));
}
```

The argument of `T::deserialize` doesn't seem to matter, in this case I put something that successfully compiles, but putting a non-existent value or even no argument gives the same error.

The error from rust-analyzer is this:

```
thread 'Worker' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-ir-0.96.0/src/lib.rs:1679:47:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:144:5
   3: core::option::unwrap_failed
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/option.rs:1978:5
   4: hir_ty::method_resolution::lookup_impl_assoc_item_for_trait_ref
   5: hir_ty::method_resolution::lookup_impl_method_query
   6: salsa::Cycle::catch
   7: salsa::derived::slot::Slot<Q,MP>::execute
   8: salsa::derived::slot::Slot<Q,MP>::read
   9: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  10: <DB as hir_ty::db::HirDatabase>::lookup_impl_method::__shim
  11: <DB as hir_ty::db::HirDatabase>::lookup_impl_method
  12: hir::source_analyzer::SourceAnalyzer::resolve_impl_method_or_trait_def
  13: hir::source_analyzer::SourceAnalyzer::resolve_path
  14: ide_db::defs::NameRefClass::classify
  15: ide::syntax_highlighting::highlight::name_like
  16: ide::syntax_highlighting::traverse
  17: ide::syntax_highlighting::highlight
  18: salsa::Cancelled::catch
  19: rust_analyzer::handlers::request::handle_semantic_tokens_full_delta
  20: std::panicking::try
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 4:01:09 PM] Request textDocument/semanticTokens/full/delta failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
```

While there are other issues with the same error message, my problem seems to have a separate backtrace (panicking in `hir_ty::method_resolution::lookup_impl_assoc_item_for_trait_ref`) which is why I've created a new issue for it. It also does not seem to occur on the current stable rust-analyzer release, so it seems to be a newly introduced bug.

---

**rust-analyzer version**:  0.4.1899-standalone (pre-release)

**rustc version**: rustc 1.77.0 (aedd173a2 2024-03-17)

**relevant settings**: none (I was able to reproduce it in a clean GitHub Codespace)

**Comment by lnicola** [comment]
Caused by https://github.com/rust-lang/rust-analyzer/pull/16805 CC @dfireBird

**Comment by lnicola** [comment]
This is annoying. `rust-analysis analysis-stats --run-all-ide-things .` doesn't catch it, while `rust-analyzer scip .` and `rust-analyzer lsif .` do. But they're too slow to run on CI.

**Comment by lnicola** [comment]
Minimized:

```rust
pub trait Deserialize<'de> {
    fn deserialize();
}

fn f<'de, T: Deserialize<'de>>() {
    T::deserialize();
}
```

**Comment by lnicola** [comment]
> Does the scip and lsif run on rust-analyzer repos?

I think they're too slow, but don't worry about that, since we have the minimized case. I have a pending PR to add highlighting to `--run-all-ide-things` , which does find this crash. But it's not very useful now, of course.
