### ISSUE TITLE
Labels stop loading halfway through a long command

### ISSUE THREAD

**Issue by SushiiZ** [rust-lang/rust-analyzer#16956]
Type: <b>Bug</b>

As mentioned, I'm coding for a game and there are commands with a lot of arguments, these are properties for a hitbox, and halfway through the command, it just stops loading labels, this didn't used to happen so I'm not sure what could be causing this

![image](https://github.com/rust-lang/rust-analyzer/assets/51277271/b7d0179c-5caf-40a6-b012-b52b2c28e192)

Extension version: 0.4.1082
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13980HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.77GB (41.42GB free)|
|Process Argv|--crash-reporter-id abd25931-125d-49b3-b8dc-1a9335f6f22c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30996667
jchc7451:30973076
gee8j676:30988843
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by Coolsonickirby** [comment]
For future reference, to load more than 25 characters, you need to change the `rust-analyzer.inlayHints.maxLength` value from 25 to null (or w/e character limit you want)

**Comment by Veykril** [comment]
What the issue here is about is about a stupid decision VSCode made that just strips hint that cause the line to go beyond a certain hardcoded length. Its not cponfigurable so nothing can be done about that
