### ISSUE TITLE
Type inlays are not clickable anymore (since 2024-03-24 release)

### ISSUE THREAD

**Issue by jeremychone** [rust-lang/rust-analyzer#16962]
**rust-analyzer version**: 0.3.1896-standalone (6f6b03f9d 2024-03-24)
**rustc version**: rustc 1.77.0 (aedd173a2 2024-03-17)
**OS**: MacBook Pro M3 Max

## Problem:

With this week's release `2024-03-24`, the type inlays are not clickable anymore.

![image](https://github.com/rust-lang/rust-analyzer/assets/74671/a5c66860-2604-479c-85ba-2d6a029dfd5c)

For example, in this simple use case, the "String" type inlay is not clickable and not underlined on mouseover. (see the previous version below)

## Works on the previous version:

Just by downgrading to last week's version, `rust-analyzer version: 0.3.1885-standalone (b6d1887bc 2024-03-17)`,
it works fine:

![image](https://github.com/rust-lang/rust-analyzer/assets/74671/f6a2de8a-1b1c-4bc8-858b-55f3fa2e9ecd)

The `String` type becomes underlined on mouseover and is clickable with `Option Click` to drill down to the type.

## Code snippet to reproduce:

```rust
let hello = "World".to_string();
```
And toggle type inlays

**Comment by lnicola** [comment]
Possibly https://github.com/rust-lang/rust-analyzer/pull/16822.

**Comment by Veykril** [comment]
Yes that is caused by that PR, I forgot to open an issue for that (as I noticed that earlier this week)

**Comment by Veykril** [comment]
Bonus: We should have tests for the resolve step :)
