### ISSUE TITLE
Implement missing members produces invalid syntax

### ISSUE THREAD

**Issue by jprochazk** [rust-lang/rust-analyzer#16985]
**rust-analyzer version**: 1.79.0-nightly (8df7e72 2024-03-30)

**rustc version**: rustc 1.79.0-nightly (8df7e723e 2024-03-30)

**code snippet to reproduce**: 
```rust
struct Test {
    value: u32,
}

impl Default for Test {
    // Place cursor here and use the "implement missing members" action
}
```

The result is:
```rust
struct Test {
    value: u32,
}

impl Default for Test {
    fn default() -> Self {
        Self { value: Default::default() \}
    \}
}
```

The `\` characters are syntax errors:
```
$ cargo check
    Checking ra-backslash-repro v0.1.0 (/home/jp/dev/ra-backslash-repro)
error: unknown start of token: \
  --> src/main.rs:11:42
   |
11 |         Self { value: Default::default() \}
   |                                          ^

error: unknown start of token: \
  --> src/main.rs:12:5
   |
12 |     \}
   |     ^

error: could not compile `ra-backslash-repro` (bin "ra-backslash-repro") due to 2 previous errors
```

**Comment by roife** [comment]
Are you using nvim?

Might be similar to #16867.

See https://github.com/rust-lang/rust-analyzer/issues/16867#issuecomment-2009391788.

**Comment by jprochazk** [comment]
I'm using VSCode:
```
$ code --version
1.83.0
e7e037083ff4455cf320e344325dacb480062c3c
x64
```

**Comment by roife** [comment]
What are the versions of your rust-analyzer server (check using `rust-analyzer: Show RA version`) and client (check in the VSCode extension)?

This issue should have been fixed in #16781 and #16782. I couldn't reproduce this issue on the latest master branch. Maybe you can try upgrading r-a.

**Comment by jprochazk** [comment]
I'm running `v0.4.1904` of the VSCode extension, I reported the issue after only trying on the latest nightly (written in OP under `rust-analyzer version`).

I just built https://github.com/rust-lang/rust-analyzer/commit/e4a405f877efd820bef9c0e77a02494e47c17512 (latest master at the time of writing) locally and configured the VSCode extension to use it (via `rust-analyzer.server.path` in `.vscode/settings.json`). The notification produced by `Show RA Version` shows:
```
rust-analyzer version: 0.0.0 (e4a405f87 2024-03-31)
```

And the issue persists, same output as in the OP.

**Comment by roife** [comment]
I still can't reproduce it. I guess it might be related to your rust-analyzer configuration? This is very strange.

**Comment by jprochazk** [comment]
I can no longer reproduce the issue either... After testing the extension locally (via `launch.json`) and confirming that that works, I tried using the bundled version of RA, which worked fine... And then I went back to using the nightly binary (installed via rustup), which also works now. 🤷

**Comment by roife** [comment]
Restarting and reinstalling always fix everything!🙈
