### ISSUE TITLE
`#[doc ="..."]` comments no longer allow escaped newlines

### ISSUE THREAD

**Issue by siefkenj** [rust-lang/rust-analyzer#16980]
In rust-analyzer `rust-analyzer version: 0.3.1885-standalone (b6d1887bc 2024-03-17)` in vscode, when writing a doc comment

```
#[doc = "\n\nThis is a \"quote\".\n\nFoo"]
fn main() {}
```
hovering over `main()` shows the doc comment as expected, with newlines. However, in rust-analyzer `rust-analyzer version: 0.3.1896-standalone`, while the quote characters display correctly, literal `\n` (backslash n) tokens appear in the tooltip.

**Comment by roife** [comment]
It might be caused by [#16909](https://github.com/rust-lang/rust-analyzer/pull/16909).
