### ISSUE TITLE
`E0308` for Unit as Associated Type in a function that returns the Associated Type.

### ISSUE THREAD

**Issue by m-rph** [rust-lang/rust-analyzer#16987]
**What I saw**:
```
expected <UnitVariableCollector as Visitor<'tcx>>::Result, found ()rust-analyzer[E0308](https://doc.rust-lang.org/stable/error_codes/E0308.html)
```

**What I expected**: Nothing

**Why did I expect that**: The program compiles. The trait has associated type Result, which is set to unit / `()`.

**rust-analyzer version**: rust-analyzer version: 0.4.1904-standalone (f5a925014 2024-03-29)

**rustc version**: rustc 1.79.0-nightly (1388d7a06 2024-03-20)

**editor or extension**: VSCode / v0.4.1904 (pre-release)

**relevant settings**: ?

**repository link (if public, optional)**: https://github.com/rust-lang/rust-clippy/blob/005b05f441b3082e9923e44f9dedcf416b1288e7/clippy_lints/src/unit_types/let_unit_value.rs#L114-L124

**code snippet to reproduce**: 
```rust
struct UnitVariableCollector {
    id: HirId,
    spans: Vec<rustc_span::Span>,
}

impl UnitVariableCollector {
    fn new(id: HirId) -> Self {
        Self { id, spans: vec![] }
    }
}

impl<'tcx> Visitor<'tcx> for UnitVariableCollector {
    fn visit_expr(&mut self, ex: &'tcx Expr<'tcx>) -> Self::Result {
        if let ExprKind::Path(QPath::Resolved(None, path)) = ex.kind
            && let Res::Local(id) = path.res
            && id == self.id
        {
            self.spans.push(path.span);
        }
        rustc_hir::intravisit::walk_expr(self, ex);
    }
}
```

**Comment by Veykril** [comment]
This is due to the use of assoc type defaults here https://github.com/rust-lang/rust/blob/3d5528c287860b918e178a34f04ff903325571b3/compiler/rustc_hir/src/intravisit.rs#L221 which iirc we can't support without the new trait solver.

The diagnostic will be silenced by https://github.com/rust-lang/rust-analyzer/pull/16968

**Comment by roife** [comment]
This issue has been resolved in #16968, so it can be closed now.

**Comment by RalfJung** [comment]
I see a similar issue that does not involve a defaulted associated type; can I expect that to be the same problem?
```
expected <Result<{unknown}, InterpErrorInfo<'static>> as Try>::Output, found ()
```
That's for [this code here](https://github.com/rust-lang/miri/blob/708b115bb3297bc601e986d86af42103ff773f69/src/shims/unix/foreign_items.rs#L598-L605). Notice the lack of a semicolon in the first arm. (That's an accident but rustc accepts it.)

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/16968 will silence that error as well. Unsure what the problem there for the `{unknown}` is
