### ISSUE TITLE
Code action to make all members of a struct `pub`

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang/rust-analyzer#16984]
I am not sure whether this is the right place to request this, but I'd like to have a code action to make all members of a type `pub` (or cycle through visibility `pub`, `pub(crate)`, `pub(mod)`, `pub(super)` or something like that or even code actions for each visibility... :thinking: ).

Please don't hesitate to close this and point me to a better location if this is not the place to request this! :heart: :+1:

**Comment by alibektas** [comment]
It is indeed the right place to raise this! 
However, I can achieve the same thing by selecting an impl block and find&replacing all the visibility constraints to whatever I want, so it makes me think whether such an assist is really necessary.

**Comment by matthiasbeyer** [comment]
You mean by the normal find&replace functionality of the editor?
But how would you do that if there is no `pub` or variant of that? Simply replacing the beginning of the line does obviously not work because of attributes or comments.

**Comment by alibektas** [comment]
Maybe I am wrong but I imagine : I would find all the `fn` keywords in the selected impl block. Go one word backward and then do whatever modifications needed. BTW I am not really questioning if we want this assist, I think someone more senior than me should eventually decide this.

**Comment by alibektas** [comment]
Sorry I don't know why I focuswd on just functions and methods. I see your point now and it is valid 👍

**Comment by matthiasbeyer** [comment]
You are completely right for associated functions, but the issue was about members of a struct, not about the impl block of a type!

**Comment by alibektas** [comment]
Oh I see my bad, I directly thought about `impl`s whereas you actually meant fields of a struct.

**Comment by Veykril** [comment]
I don't think this is too useful to have, one can always use multi cursors and put those on all field names to edit things at once instead). We already have a really big list of assists so we gotta keep the maintenance burden in mind (and the user facing list of applicable assists growing too large).

Additionally ideally VSCode would support invoking same assists on all cursor positions which would allow the cycling on visiblities (we already have an assisst to go from pub to pub(crate) and vice versa)
