### ISSUE TITLE
Wrong lifetime in type inlay hints

### ISSUE THREAD

**Issue by NichtsHsu** [rust-lang/rust-analyzer#16993]
**rust-analyzer version**: 0.4.1907-standalone

**rustc version**: rustc 1.79.0-nightly (805813650 2024-03-31)

**editor or extension**: VSCode with extension v0.4.1907 (pre-release)

**relevant settings**:

**repository link (if public, optional)**:

**code snippet to reproduce**: 
```rust
struct Ref<'a, T>(&'a T);

fn new<T>(r: &T) -> Ref<'_, T> {
    Ref(r)
}

fn main() {
    let i = 0;
    let r = new(&i);
}
```

![image](https://github.com/rust-lang/rust-analyzer/assets/35688135/85a327fb-e62b-46f1-935e-3c01d91ff36a)

RA hints that the type of `r` is `Ref<'static, i32>`, but the lifetime of `&i` should not be `'static`.

**Comment by Veykril** [comment]
We haven't implemented lifetime elision yet

**Comment by Veykril** [comment]
Will be fixed by https://github.com/rust-lang/chalk/pull/809 (in the sense that we won't show `'static` but `'{unkown}`
