### ISSUE TITLE
IntelliSense not working inside thread_local!

### ISSUE THREAD

**Issue by mzurs** [rust-lang/rust-analyzer#16991]
I recently encountered an issue while formatting variables inside thread_local! macro, but before that formatter is working fine.
Also, I am unable to import pub static variables to other modules. The problem is formatting is not working inside thread_local! macro, such as multiple variables are not aligned on default formatting. Also on hover to variable doesn't show any definitions, etc. But formatting works outside macro.The public variables I defined inside macro are not able to show when tried to call in other modules like IntelliSense is not working. Besides this, the program compiles successfully.

**rust-analyzer version**: v0.3.1906

**rustc version**:  rustc 1.75.0 (82e1608df 2023-12-21)

**code snippet to reproduce**: 
```rust

use std::cell::RefCell;
thread_local! {
    pub static FOO: RefCell<u32> = RefCell::new(1);

static BAR: RefCell<f32> = RefCell::new(1.0);
}

FOO.with(|foo| assert_eq!(*foo.borrow(), 1));
BAR.with(|bar| assert_eq!(*bar.borrow(), 1.0));
```

**Comment by Veykril** [comment]
You'll need to set `"rust-analyzer.cargo.sysrootQueryMetadata": true,` or have a `cfg-if` (transitive) dependency in your project for this to work (though the latter seems broken rn). (its a weird std gimmick we need to work around currently)
