### ISSUE TITLE
hover a struct can't show its whole definition,but hover a enum can

### ISSUE THREAD

**Issue by ChimeWu** [rust-lang/rust-analyzer#17009]
![截图 2024-04-04 11-17-11](https://github.com/rust-lang/rust-analyzer/assets/85327271/d603f78e-558a-4403-aa2c-b7e2d8bd8c23)
![截图 2024-04-04 11-16-31](https://github.com/rust-lang/rust-analyzer/assets/85327271/7a694d84-6b44-4907-a2bb-e399a2775234)

**Comment by Veykril** [comment]
On that note we probably want a setting for enum variants as well

**Comment by roife** [comment]
And currently, we don't display the fields of the struct by default. Perhaps we could set a default value for it (for example, 8)? So that users will discover this feature.

**Comment by ChimeWu** [comment]
Thank you for your help! I'm a student and I'm learning rust , rust-analyzer helps me a lot,thank you::smile::

**Comment by ChimeWu** [comment]
> Currently, we don't display the fields of the struct by default. Perhaps we could set a default value for it (for example, 8)? So that users will discover this feature.
> 
> And considering that we can implement this simultaneously for both enum, and union, should we combine them into a single setting?

大佬，萌新求带

**Comment by roife** [comment]
> 大佬，萌新求带

It's recommended to use English for GitHub Issues discussions to keep things clear and inclusive. For discussions regarding off-topic or private matters, please communicate via email. Thanks!
