### ISSUE TITLE
Cyclic dependency in rust?

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust-analyzer#17015]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
```
$ rust-analyzer --version
rust-analyzer 1.79.0-nightly (4fd4797 2024-04-03)
```
**rustc version**: (eg. output of `rustc -V`) nightly, commit 4c6c6298664fff9f3549f05ba2b689bcd30b0fc7

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)
```
nvim --version
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1693350652

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/bjqr6vi3q0f8iy4ncv1z8vl81bzkjq0r-neovim-unwrapped-0.9.4/share/nvim
"

```
**relevant settings**: running on NixOS

**repository link (if public, optional)**: https://github.com/rust-lang/rust

I'm gettting this error:
```
[START][2024-04-04 17:05:07] LSP logging initiated
[ERROR][2024-04-04 17:05:07] .../vim/lsp/rpc.lua:734	"rpc"	"rust-analyzer"	"stderr"	"2024-04-04T15:05:07.511930Z ERROR project_model::workspace: cyclic deps: rand(Idx::<CrateData>(459)) -> libc(Idx::<CrateData>(376)), alternative path: libc(Idx::<CrateData>(376)) -> rustc_std_workspace_core(Idx::<CrateData>(100)) -> core(Idx::<CrateData>(91)) -> rand(Idx::<CrateData>(459))\n2024-04-04T15:05:07.511946Z ERROR project_model::workspace: cyclic deps: rand_core(Idx::<CrateData>(461)) -> getrandom(Idx::<CrateData>(323)), alternative path: getrandom(Idx::<CrateData>(323)) -> cfg_if(Idx::<CrateData>(236)) -> rustc_std_workspace_core(Idx::<CrateData>(100)) -> core(Idx::<CrateData>(91)) -> rand(Idx::<CrateData>(459)) -> rand_chacha(Idx::<CrateData>(460)) -> rand_core(Idx::<CrateData>(461))\n"
```

**Comment by Veykril** [comment]
See https://github.com/rust-lang/rust-analyzer/issues/14167, you can ignore that (we should probably downgrade that to a wrning nowadays)
