### ISSUE TITLE
Tests dont show up when using additional proc macro.

### ISSUE THREAD

**Issue by t-moe** [rust-lang/rust-analyzer#17011]
I have an integration test which looks as follows:

```rust
#![no_std]
#![no_main]

#[cfg(test)]
#[embedded_test::tests]
mod tests {
    #[test]
    fn test_a() {
        assert!(true)
    }

   #[test]
    fn test_b() {
        assert!(false)
    }
}
```

With the line `#[embedded_test::tests]` in place, rust analyzer wont show "Run Tests | Debug".
As soon as I remove the line, it works as expected.

I'm the author of [embedded-test](https://crates.io/crates/embedded-test).  
Since this used to work before, I'm now unsure whether this broke because of a change on my side (embedded-test lib) or a recent change in rust anaylzer.  To me it looks like this is due to a recent change in rust-analyzer since the buttons also disappear when using the macro provided by [defmt-test](https://crates.io/crates/defmt-test)

Can you point me to the relevant parts of the rust analyzer source code (that decides whether it is a test or not) ? 
EDIT: probably https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide/src/runnables.rs ?

Thank you

rust-analyzer version: 0.3.1906-standalone
rustc 1.79.0-nightly (88c2f4f5f 2024-04-02)

**Comment by Veykril** [comment]
Ah, the tests macro (at least for `defmt`) expands to things that no longer contain `#[test]` attributes which is why this no longer shows, the heuristic for test like attributes was removed. Curios how running cargo test still invokes the exported custom main there 🤔

**Comment by t-moe** [comment]
> Curios how running cargo test still invokes the exported custom main there 🤔

The idea is that you set up a cargo runner (e.g. something like "probe-rs run"), which will download the elf file..
Furthermore you have to set `harness=false` for the test in your Cargo.toml.

After flashing, when the MCU boots, it will then call the exported main function and run the tests in order.

**Comment by t-moe** [comment]
I'll try whether I can fix this on my end by emitting `#[::core::prelude::v1::test]` from my macro, similar to how tokio does it for their test macro.

**Comment by Veykril** [comment]
That would be one way, but I'll try adding something that considers exported mains inside cfg(test) modules to be test functions, as that looks like a test for a custom runner

**Comment by t-moe** [comment]
> but I'll try adding something that considers exported mains inside cfg(test) modules to be test functions

That would be great. I'm a bit hesitant with emitting the `#[test]` attribute from my macro, since it will cause weird compiler errors when the user forgets to set `harness=false`.
