### ISSUE TITLE
Access is denied (os error 5) with Option

### ISSUE THREAD

**Issue by StevenHu1988** [rust-lang/rust-analyzer#17028]
Rust Version: rustc 1.77.1 (7cf61ebde 2024-03-27)

![image](https://github.com/rust-lang/rust-analyzer/assets/6611493/648ff223-d782-4056-bb53-3839eb0eda53)
When I build code with options , it always shows the following error
![image](https://github.com/rust-lang/rust-analyzer/assets/6611493/9296ac66-94c7-4ef3-997f-d7df4724453c)
it can cargo build but the cargo run always show me the  **Access is denied. (os error 5)**

and if I removed the Option, both of the Cargo build and Cargo run were worked
![image](https://github.com/rust-lang/rust-analyzer/assets/6611493/6021bd81-e259-4ce6-9265-1acd8cc869e5)

**Comment by l1nxy** [comment]
It's a RustRover-related issue in JetBrains' production, not related to rust-analyzer.
