### ISSUE TITLE
Smart enter for doc comments only works sometimes

### ISSUE THREAD

**Issue by schuelermine** [rust-lang/rust-analyzer#17026]
**rust-analyzer version**: rust-analyzer 1.79.0-nightly (9d79cd5 2024-04-05)

**rustc version**: (eg. output of `rustc -V`) rustc 1.79.0-nightly (9d79cd5f7 2024-04-05)

**editor or extension**: VSCodium 1.87.2, r-a extension v0.3.1850

**relevant settings**: none

[Screencast from 2024-04-07 15-57-56.webm](https://github.com/rust-lang/rust-analyzer/assets/48802534/4ffa78ae-00a7-4477-9ba1-c263a88a3a54)

**Comment by Young-Flash** [comment]
upgrade to latest fix this
