### ISSUE TITLE
Public re-exports do not appear in code completion

### ISSUE THREAD

**Issue by misaka10987** [rust-lang/rust-analyzer#17042]
**rust-analyzer version**: v0.3.1916

**rustc version**: 1.76.0

**editor or extension**: VSCodium

**relevant settings**: None

**code snippet to reproduce**: 

crate-a/lib.rs
```rust
pub fn add(a:i32,b:i32)->i32{
    a+b
}
```

crate-b/lib.rs
```rust
pub use crate_a::add as my_add;
```

crate-b/some.rs
```rust
fn xxx(){
    // type my_add here and there is no completion or auto-import.
}
```

**Comment by misaka10987** [comment]
Also, there is a notice says "consider importing this function through its public re-export: `use crate::my_add;`" in the "Quick fix" option, but it will suggest you import `crate_a::add` instead of `crate::my_add` when clicked.

**Comment by lnicola** [comment]
That's a rustc message, does `cargo check` actually work?

**Comment by misaka10987** [comment]
> That's a rustc message, does `cargo check` actually work?

Yes an error[E0425]: cannot find function `my_add` in this scope is produced as expected
