### ISSUE TITLE
I suspect the current crate "indexing" is off by one

### ISSUE THREAD

**Issue by dspyz-matician** [rust-lang/rust-analyzer#17049]
It seems like a change was recently made to our rust workspace which causes one of the crates to take an extremely long time to index (~60s) and does so _every_ time I reload VSCode or change a Cargo.toml. I think the dependency which shows up at the bottom of VSCode as "Indexing" is not actually the one it's currently indexing. I suspect that it's actually reporting the last dependency to _finish_ indexing and then whatever the true culprit is that's taking so long goes by too fast for me to see when it finally finishes.

![Screenshot from 2024-04-10 15-44-58](https://github.com/rust-lang/rust-analyzer/assets/100452635/c05b349b-1e22-4ee5-ad7a-1be314365560)

(Also, AFAICT there's no way to see what the "+ 4 more" are; clicking on it does not show them)

**rust-analyzer version**:

rust-analyzer version: 0.3.1916-standalone

**rustc version**:

rustc 1.76.0 (07dca489a 2024-02-04)

**editor or extension**:

VSCode

**relevant settings**:

I don't think any of these are relevant
```
    "rust-analyzer.cargo.features": [<lots of workspace-specific features>],
    "rust-analyzer.cargo.extraArgs": [],
    "rust-analyzer.check.allTargets": true,
```

**code snippet to reproduce**: 
Unknown

**Comment by Veykril** [comment]
That is correct, we seem to send the notification update for finished jobs, not when starting one https://github.com/rust-lang/rust-analyzer/blob/a5feb4f05f09adca661c869b1bf2324898cbaa43/crates/rust-analyzer/src/main_loop.rs#L272-L314

**Comment by dspyz-matician** [comment]
@Veykril Thanks for investigating this and confirming.

Any chance there is an easy fix? Also, is there a way right now I can find out which crate is the culprit?

**Comment by dspyz-matician** [comment]
I was wrong about this. It's reporting the correct crate. `kiss3d` _is_ the thing that was being slow
