### ISSUE TITLE
`This rust file does not belong to a loaded cargo project` but is false

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/rust-analyzer#17043]
From the latest stable version or the second one, when I open a big project in VSCode and it starts RA I get a message:

```
This rust file does not belong to a loaded cargo project. It looks like it might belong to the workspace at /c:/project/Cargo.toml, do you want to add it to the linked Projects?
```

Which is not true since the file belongs to the workspace.

It seems just an error due to the slow time it takes to start.

**Comment by frederikhors** [comment]
It happens mostly when VSCode first open file is a very long one (11k LOC and more).

**Comment by Veykril** [comment]
This is known, I'll try to look into it next week (I'm rather busy this week)

**Comment by Veykril** [comment]
The notification has been disabled for now, the false trigger was mainly us loading the project while the files weren't yet loaded yet cc https://github.com/rust-lang/rust-analyzer/issues/17373
