### ISSUE TITLE
Resolve external preludes for modules inside blocks

### ISSUE THREAD

**Issue by roife** [rust-lang/rust-analyzer#17057]
The original issue was closed by the bot 😅, but we need to resolve this problem.

              Looks like we fail to resolve the extern prelude in local modules in block modules, it works fine if the `mod cs` is at the top-level (not nested inside a function or anything)

```rs
fn main() {
    mod f {
        use core as _;
    }
}
```

              here `core` does not resolve

_Originally posted in https://github.com/rust-lang/rust-analyzer/issues/17032#issuecomment-2043238776_

**Comment by roife** [comment]
Sorry... I open the issue with `reference it in new issue`, and am unable to add the `bug` label to this issue.

----------

I added `self.inject_prelude();` in https://github.com/rust-lang/rust-analyzer/blob/07ae540f4e1e22141cb7409fd84eaba3343a6055/crates/hir-def/src/nameres/collector.rs#L367-L384, removed https://github.com/rust-lang/rust-analyzer/blob/07ae540f4e1e22141cb7409fd84eaba3343a6055/crates/hir-def/src/nameres/path_resolution.rs#L473-L477 and https://github.com/rust-lang/rust-analyzer/blob/07ae540f4e1e22141cb7409fd84eaba3343a6055/crates/hir-def/src/nameres/path_resolution.rs#L518-L521

This resolves the issue, but I don't understand what "so that blocks can properly shadow them" means.

**Comment by Veykril** [comment]
The shadowing is about stuff like

(assuming a `core` entry in the extern prelude)
```rs
fn f() {
   mod core {
       pub fn foo () {}
   }
   core::foo();
}
```

This should look into the local module, not the prelude.

**Comment by roife** [comment]
It seems that it can be resolved correctly with the modifications above:

<img width="338" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/17700217/3e6eacb5-c582-472c-9cd3-3d3a0aaa4f20">

**Comment by Veykril** [comment]
The problem with that approach might be that it fails for nsted block def maps
```rs
fn foo() {
    mod core { mod mem { fn drop<T>(_: T) {} } }
    {
        use self as _; // forces a block def map here
        core::mem::drop(0); // should resolve to the local item, not the prelude one
    }
}

```
