### ISSUE TITLE
Type Infer Issue

### ISSUE THREAD

**Issue by Jianqoq** [rust-lang/rust-analyzer#17060]
<img width="484" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/120760306/5888f33e-0ab3-4514-8e0a-94853a1ca8c8">

I am using the lastest version of `rust-analyzer`, but I also tried old version, all doesn't work, it shows `{unknow}` type. When I use insert explicit type, it becomes `let _a: Arc<Mutex<i32>, _> = Arc::new(Mutex::new(1));`, I found that Arc has `A: Allocator = Global`, rust analyzer is trying to infer this type.
`pub struct Arc<T: ?Sized,  #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global>`
Is there a way to not do it? When the project get large, it can't do type inferencing and auto complete well

**Comment by Jianqoq** [comment]
The issue is fixed. This bug happens when I use Rust 1.75, after I upgraded to 1.77, it fixed.

**Comment by Veykril** [comment]
Then let's close this. We don't support older stable releases
