### ISSUE TITLE
In VS Code, rust-analyzer prefers postfix completions over methods/traits

### ISSUE THREAD

**Issue by davidbarsky** [rust-lang/rust-analyzer#17077]
Just as a heads up, as of #17073, postfix completions/helpers are showing up first in VS Code. With a rust-analyzer built at c0371309b40181baadda50f5fe6649f219be15d0, these are the completions I'm getting:

<img width="1357" alt="Screenshot 2024-04-15 at 11 23 34 AM" src="https://github.com/rust-lang/rust-analyzer/assets/2067774/74974783-8108-4592-bb8c-7d40c922415c">

With a rust-analyzer built at af728741de6ad74517f34053efae864d7d75ac5d, I'm getting the postfix completions first:

<img width="1357" alt="Screenshot 2024-04-15 at 11 25 57 AM" src="https://github.com/rust-lang/rust-analyzer/assets/2067774/db0c88cb-12bc-4c6e-af59-e930d3fae0ca">

I'm not sure how intentional that is, but it certainly feels a bit like a bug to me.

_Originally posted by @davidbarsky in https://github.com/rust-lang/rust-analyzer/issues/17073#issuecomment-2057135351_

**Comment by davidbarsky** [comment]
Note that adding `"editor.snippetSuggestions": "bottom"` to the settings brought back the prior behavior, but I'm not sure it's a good idea to users to make that change.

**Comment by roife** [comment]
Is this because VS Code considers `1.ok` to be a better match for `1.` than `oxxf` (some fns)? 🤔

**Comment by roife** [comment]
r-a would calculates a "score" based on various factors and converts it into `sort_text`.

But it is quite strange because I found that the score for `borrow()` is `15` while the score for `box` is `13`, yet `box` ranks higher.

**Comment by pascalkuthe** [comment]
VSCode does not follow the spec and both filters and sorts incomplete completion lists based on text score (and most servers including ra rely on that to some degree so every other client is forced to follow this non-standard behavior if we dont want broken completions). 



I am not sure you can do much about this server side if sorttext is already set correctly.

**Comment by pascalkuthe** [comment]
Thus will probably not be a huge problem once you typed one or two characters since then the real completions will have a better textual score. So you could just hide postfix completions when there is a trigger char

**Comment by davidbarsky** [comment]
> VSCode does not follow the spec and both filters and sorts incomplete completion lists based on text score (and most servers including ra rely on that to some degree so every other client is forced to follow this non-standard behavior if we dont want broken completions). The real fix would for vscode to comply with the LSP spec.

That's unfortunately a common situation, but that's not really something we can do in the next week.

> Thus will probably not be a huge problem once you typed one or two characters since then the real completions will have a better textual score. So you could just hide postfix completions when there is a trigger char (after `.` and `::`)

I think you underestimate how much of an issue this might be, especially given that people would write a single dot completion to determine what methods are available to them. Given that VS Code is the _primary_ supported editor of rust-analyzer, we'll need to find a workaround.

**Comment by pascalkuthe** [comment]
I meant to hide postfix completions like `ok` after trigger chars. That would allow scrolling trough available methods without seeing the postfix snippets.

Once you start actually typing text we can show them again because then the score of whatever you are looking for will be higher then postfix matches.

**Comment by davidbarsky** [comment]
> I meant to hide postfix completions like ok after trigger chars. That would allow scrolling trough available methods without seeing the postfix snippets.

That _could_ work, but I'm not sure how you're proposing to distinguish a trigger character for postfix completions versus a method completions (I'm thinking of some postfix snippets like `.match`).

The alternative I'm considering is to change behavior in scoring by editor—special case VS Code.

**Comment by pascalkuthe** [comment]
> That could work, but I'm not sure how you're proposing to distinguish a trigger character for postfix completions versus a method completions (I'm thinking of some postfix snippets like .match).

Afaim postfix completions (like `.ok`, `.match`,...) only show up after periods right now. The PR that regressed this made RA include the text before the period (and the period itself) in the filter text. So I thought you could simply check if:

* filterText contains a period
* the completion trigger position is immieditly after a period

If both are true the completion is not send to the client. 

If this solution works without side-effects that would be ideal since it would be editor agnostic. 

> The alternative I'm considering is to change behavior in scoring by editor—special case VS Code.

As far as I can tell the problem here is that vscode does uncofigurable and incorrect client side scoring so I don't think you would be able to do editor specific scoring on the server side.

This could also be just an issue with the ra side scoring/sort text but if I understand the comment above correctly (which matches with what I found recently looking trough the vscode codebase). Vscode always does client side scoring even when you disabled it by marking the completion as incomplete.

**Comment by davidbarsky** [comment]
> Afaim postfix completions (like `.ok`, `.match`,...) only show up after periods right now. The PR that regressed this made RA include the text before the period (and the period itself) in the filter text. So I thought you could simply check if:
>
> - filterText contains a period
> - the completion trigger position is immieditly after a period
> 
> If both are true the completion is not send to the client.

From my testing, this seems to effectively disable [postfix/magic completions](https://rust-analyzer.github.io/manual.html#magic-completions) entirely, especially since there isn't any other way to activate them beyond dot completions.

In reference to your [prior comment](https://github.com/rust-lang/rust-analyzer/issues/17036#issuecomment-2056614180) about the LSP specification, I'm not sure I agree with your interpretation for the following reasons:
- The phrasing of "[t]he range of the edit must be a single line range and it must contain the position at which completion has been requested" appears to _only_ be in reference to the primary `textEdit` on [CompletionItem](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem), _not_ `additionalTextEdits`.
- Similarly, the constraint of "the range of the edit" does not appear on [`TextEdit`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit), which makes me think the aforementioned range/position constraint is _only_ applicable to `CompletionItem::textEdit`, not `TextEdit`s in general.
- The documentation for `additionalTextEdits` says "[a]dditional text edits should be used to change text unrelated to the current cursor position", with imports being a cited as an example. However, adding a `&mut` before a `.` also fits the definition of "unrelated", albeit more tenuously. Therefore, I think rust-analyzer has the latitude to be more liberal with its usage of `additionalTextEdits` because of the distinction between "should" and "must", despite the difficulties with multi-cursor edits.

> As far as I can tell the problem here is that vscode does uncofigurable and incorrect client side scoring so I don't think you would be able to do editor specific scoring on the server side.

The approach I had in mind was to gate the behavior introduced in #17073 by the editor name, but that feels like a nightmare to test/maintain. I have no love lost for VS Code, but the behavior _is_ technically configurable by the end-user, just not language servers. Regardless, I think it's problematic to require end-users to make a change to their editor in order to return to behavior that they're used to, which is why I'm personally inclined to revert #17073.

**Comment by davidbarsky** [comment]
Anyways, I was talking @Wilfred about VS Code's autocomplete/intellisense, and he pointed out that it is *very* good about finding applicable completions even if you mistype a portion of your what you expect to be autocompleted, and I think a portion of that magic-when-it-works experience is them factoring in the starting point of a line range. Moving the range to start *prior* to the cursor is probably getting VS Code to prioritize those completions more because they might be using that as a proxy for "the user is in the middle of writing a long method, so we should suggest that".
