### ISSUE TITLE
feat: Lsp option to disable inlay hint filtering

### ISSUE THREAD

**Issue by JustLinuxUser** [rust-lang/rust-analyzer#17084]
For some reason only some (I think always one) of function parameters have associated inlay hint
![image](https://github.com/rust-lang/rust-analyzer/assets/75628709/a3219a53-d843-4665-be4b-f4032274c758).
As far as I know this is not a neovim bug, I have tried inspecting the lsp requests/responses, and am having the same issue. Why?

**Comment by lnicola** [comment]
There are some heuristics like hiding the hints if the argument is a variable or field with the same name as the function parameter.

**Comment by JustLinuxUser** [comment]
Is there any way I can disable them?
I am currently making a neovim plugin to show inlay_hints at the end of the line, and it would be really good if I could enable all hints (at least for function params)

**Comment by JustLinuxUser** [comment]
Not a good idea prob
