### ISSUE TITLE
what's wrong ??

### ISSUE THREAD

**Issue by bell152** [rust-lang/rust-analyzer#17082]
analyzer doesn't seem to recognize the cargo.toml file format, but the program works fine in the terminal.

<img width="851" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/11853380/5df7a4a8-b50b-4b66-8591-8f8ff63bc60a">

**Comment by bell152** [comment]
2024-04-16T02:17:51.955694Z ERROR rust_analyzer::main_loop: FetchWorkspaceError:
rust-analyzer failed to load workspace: Failed to load the project at /Users/martin/Downloads/workspace/rust/yew-bootstrap/Cargo.toml: Failed to read Cargo metadata from Cargo.toml file /Users/martin/Downloads/workspace/rust/yew-bootstrap/Cargo.toml, Some(Version { major: 1, minor: 75, patch: 0 }): Failed to run `cd "/Users/martin/Downloads/workspace/rust/yew-bootstrap" && RUSTUP_TOOLCHAIN="/Users/martin/.rustup/toolchains/stable-aarch64-apple-darwin" "/Users/martin/.cargo/bin/cargo" "metadata" "--format-version" "1" "--manifest-path" "/Users/martin/Downloads/workspace/rust/yew-bootstrap/Cargo.toml" "--filter-platform" "aarch64-apple-darwin"`: `cargo metadata` exited with an error: error: failed to parse manifest at `/Users/martin/Downloads/workspace/rust/yew-bootstrap/Cargo.toml`

Caused by:
  virtual manifests must be configured with [workspace]

**Comment by Veykril** [comment]
Did you somehow configure your toml files as rust files in vscode? The error log you posted implies your workspace is set up incorrectly / opened weirdly

**Comment by frederikhors** [comment]
Not rust-analyzer fault here. Please close this issue, @bell152.
