### ISSUE TITLE
Revamp how we render type layout information in hover messages

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#17097]
See 

> For the record, clangd render it in this way: ![image](https://private-user-images.githubusercontent.com/45197576/322705280-67b5e8d4-56dd-4c9a-9951-057c0d412db4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzIxOTMsIm5iZiI6MTcxMzQzMTg5MywicGF0aCI6Ii80NTE5NzU3Ni8zMjI3MDUyODAtNjdiNWU4ZDQtNTZkZC00YzlhLTk5NTEtMDU3YzBkNDEyZGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA5MTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYjYwYjEzYjJhNzI3YjRlMGViYTExMmRkMTJmNzMwZjAyZWQ3ZTgzNzg4NzU5M2MyMmNjNjI0OWRlZThlYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8KmCYrsuOeC-sgR96QVIethIRkbTmkUevn9LVuLUNbY)
> 
> It is enabled by default, but only appears in definition hover, not in usage hover.

as an example of what we *could* do. This is more of a design issue than anything else (though honestly speaking I like our comment approach more ...)

**Comment by lnicola** [comment]
Linked screenshot, since the JWT expired:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/63b92f05-8e32-45c0-83ae-ad9422bb2143)

To me,  #17096 seems like the more important thing. As long as it's only in the definition, we can even go wild and include the field layout info:

```rust
// size = 8, align = 4
#[repr(C)]
struct S {
    x: i32, // size = 4
    y: i8,   // size = 1
    // _padding: [u8; 3] // size = 3
}
```

**Comment by davidbarsky** [comment]
I think I'd be happy with showing this information on the _definition_ alone. It avoids some of the annoying questions around configuration that most users won't touch.
