### ISSUE TITLE
When rename filename, the analyzer doesn't work.

### ISSUE THREAD

**Issue by ktjd123** [rust-lang/rust-analyzer#17109]
**rust-analyzer version**: rust-analyzer version: 0.3.1924-standalone (5dbe3fe75 2024-04-14)

**rustc version**: rustc 1.77.2 (25ef9e3d8 2024-04-09)

**editor or extension**: VSCode v0.3.1924

Hi when change name of existing file to lowercase, the rust-analyzer seems to stop and doesn't work anymore.

ex-> Abc.rs -> abc.rs.

No more code suggestions and else.

Thank you and always appreciate your works.

**Comment by flodiebold** [comment]
There is a bug in VSCode with changing the case of filenames on Windows. IIRC you have to at least restart VSCode to work around it, there's nothing we can do.

**Comment by Veykril** [comment]
Restarting doesn't even help, you need to clear the cache of the project https://github.com/rust-lang/rust-analyzer/issues/9581

**Comment by ktjd123** [comment]
@flodiebold Thank you. I'm currently using Mac but I get that this is VSCode bug.

**Comment by flodiebold** [comment]
I guess it occurs on all case-insensitive file systems.
