### ISSUE TITLE
can't load standard library from sysroot

### ISSUE THREAD

**Issue by Avrimuskom** [rust-lang/rust-analyzer#17113]
Windows 10 x64
Rust 1.77.2
MS VS Code 1.88.1
After install rust analyzer view error
![Безымянный](https://github.com/rust-lang/rust-analyzer/assets/166137154/84fb107f-7520-4edc-a528-237526cb26e7)

```

**Comment by Avrimuskom** [comment]
can't load standard library from sysroot

C:\Program Files\Rust stable MSVC 1.77

(discovered via `rustc --print sysroot`)

try installing the Rust source the same way you installed rustc

**Comment by Avrimuskom** [comment]
Solved:
Need open file setting.json in dir C:\Users\%User%AppData\Roaming\Code\User\settings.json
My example
C:\Users\AveN\AppData\Roaming\Code\User\settings.json
and change  "rust-analyzer.cargo.sysroot": null on
"rust-analyzer.cargo.sysroot": "C:/Users/%User%/.rustup/toolchains/stable-x86_64-pc-windows-msvc"
on my example "rust-analyzer.cargo.sysroot": "C:/Users/AveN/.rustup/toolchains/stable-x86_64-pc-windows-msvc"
![image](https://github.com/rust-lang/rust-analyzer/assets/166137154/34596312-7be2-4c22-b404-2a79110b1b94)

**Comment by Veykril** [comment]
That sounds like your rust installation is a bit weird, given we should auto discover the sysroot just fine usually

**Comment by Avrimuskom** [comment]
first I installed via RUSTUP-INIT.EXE (64-BIT)
then https://static.rust-lang.org/dist/rust-1.77.2-x86_64-pc-windows-msvc.msi

**Comment by BekManBekov1974** [comment]
> Solved: Need open file setting.json in dir C:\Users%User%AppData\Roaming\Code\User\settings.json My example C:\Users\AveN\AppData\Roaming\Code\User\settings.json and change "rust-analyzer.cargo.sysroot": null on "rust-analyzer.cargo.sysroot": "C:/Users/%User%/.rustup/toolchains/stable-x86_64-pc-windows-msvc" on my example "rust-analyzer.cargo.sysroot": "C:/Users/AveN/.rustup/toolchains/stable-x86_64-pc-windows-msvc" ![image](https://private-user-images.githubusercontent.com/166137154/324173921-34596312-7be2-4c22-b404-2a79110b1b94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NzI1NTMsIm5iZiI6MTcxNjY3MjI1MywicGF0aCI6Ii8xNjYxMzcxNTQvMzI0MTczOTIxLTM0NTk2MzEyLTdiZTItNGMyMi1iNDA0LTJhNzkxMTBiMWI5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQyMTI0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTE0MjRiMDk2OWZkOWQ5OGRlMmQ5ZGE0ODEyYzFjYTA0MmM1MjJjOTUyMzI2MjQ0N2UyNWUzMzU0NjQxOWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x8pDsshQlI1r-1tIlPMFuDaendkK_kTSlIxsxMr7cH8)

It works for me. Thanks so much!!!

**Comment by rrrrigel** [comment]
> Solved: Need open file setting.json in dir C:\Users%User%AppData\Roaming\Code\User\settings.json My example C:\Users\AveN\AppData\Roaming\Code\User\settings.json and change "rust-analyzer.cargo.sysroot": null on "rust-analyzer.cargo.sysroot": "C:/Users/%User%/.rustup/toolchains/stable-x86_64-pc-windows-msvc" on my example "rust-analyzer.cargo.sysroot": "C:/Users/AveN/.rustup/toolchains/stable-x86_64-pc-windows-msvc" ![image](https://private-user-images.githubusercontent.com/166137154/324173921-34596312-7be2-4c22-b404-2a79110b1b94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDk1MzMsIm5iZiI6MTcyMjg0OTIzMywicGF0aCI6Ii8xNjYxMzcxNTQvMzI0MTczOTIxLTM0NTk2MzEyLTdiZTItNGMyMi1iNDA0LTJhNzkxMTBiMWI5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQwOTEzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODQwZGY5YzczNDllMjMzM2U3YTU5MTAyM2YyM2M4OTE4NjAwNzA0MDliYjE4NmY4ODJlMTA4MzgxOTlmMTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zk8vGi3TI3Hen4yDAgI5PFx2zIyEHkj2U6s7hS5ijMg)

Thanks!

**Comment by rngadam** [comment]
Same error on Ubuntu 22.04.4 LTS, fixed by installing rust-src package:
```
sudo apt install rust-src
```

**Comment by lsignac** [comment]
Same on arch linux. Fixed with `pacman -S rust-src`

**Comment by daiyongxuan** [comment]
> Same on arch linux. Fixed with `pacman -S rust-src`

It works for me, Arch WSL2, thanks!

**Comment by Crispy13** [comment]
`rustup component add rust-src`

worked for me.

**Comment by Phascolarctos** [comment]
### Solution
1. get rust-src target url from [channel-rust-stable.toml](https://static.rust-lang.org/dist/channel-rust-stable.toml)
2. download rust-src 
3. copy directory **src** to rustlib directory
4. example below
 - > rustc --print sysroot
- > from: D:\EnvDev\rust-src\lib\rustlib
- > to: D:\EnvDev\Rust\lib\rustlib

**Comment by atellou** [comment]
On my Mac, running `rustup update` and reopening the vscode window worked

**Comment by hurlebouc** [comment]
Hi,
The new version 0.3.2308 introduce regression in regard of find std sources: I use nix to provide rust environment, and it worked before this version. Here is my nix configuration:

default.nix
```nix
 let
   npins = import ./npins;
   system = builtins.currentSystem;
   pkgs = import npins.nixpkgs { inherit system; config = {}; overlays = []; };
   build = pkgs.callPackage ./build.nix {};
   HOME = builtins.getEnv "HOME";
   PROJECT_ROOT = builtins.toString ./.;
 in
 {
   build = build;
   shell = pkgs.mkShell {
     inputsFrom = [ build ];
     packages = [
      
        pkgs.git
      
        pkgs.rustfmt
      
        pkgs.nixpkgs-fmt
      
     ];
     
     RUST_SRC_PATH = "${pkgs.rustPlatform.rustLibSrc}";
     
   };
 }
```

build.nix
```nix
{ lib, rustPlatform, nix-gitignore }:

let
  cargo = fromTOML (builtins.readFile ./Cargo.toml);
in

rustPlatform.buildRustPackage {
  pname = cargo.package.name;
  version = cargo.package.version;

  src = nix-gitignore.gitignoreSource [".git" ".gitignore" "*.nix"] ./.;

  cargoLock = {
    lockFile = ./Cargo.lock;
  };
}
```

shell.nix
```nix
(import ./.).shell
```

**Comment by AveNRU** [comment]
On Rust 1.85 for WIndows 1.85 need set path on C:\Users\<User name>\AppData\Roaming\Code\User\settings.json :

  "rust-analyzer.cargo.sysrootSrc": null,

**Comment by AscendLiu** [comment]
> Same on arch linux. Fixed with `pacman -S rust-src`

it OK

Operating System: Arch Linux 
KDE Plasma Version: 6.3.3
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.2
Kernel Version: 6.13.7-zen1-1-zen (64-bit)
Graphics Platform: Wayland

**Comment by alshdavid** [comment]
Fedora 42 user here, toolchain is 1.89.0, using zsh as my shell.

I installed Rust via the normal rustup script and have this issue. I install Rust into `$HOME/.local/rust` and I add this to my `.zshrc` and `.bashrc`:

```bash
export RUSTUP_HOME="$HOME/.local/rust/rustup"
export CARGO_HOME="$HOME/.local/rust/cargo"
export PATH="$HOME/.local/rust/cargo/bin:$PATH"
```

This problem has never occured for me before.

Resolution was adding this to my `settings.json`

```json
"rust-analyzer.server.extraEnv": {
  "CARGO": "/home/dalsh/.local/rust/cargo/bin/cargo",
  "RUSTC": "/home/dalsh/.local/rust/cargo/bin/rustc"
},
"rust-analyzer.cargo.sysroot": "/home/dalsh/.local/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu"
```

**Comment by yassine-safraoui** [comment]
I had this issue on Windows, turns out it was because I installed rust with scoop which keeps installation local to user only, uninstalling rust and installing it with WinGet fixed the issue for me.
