### ISSUE TITLE
VSCode extension fails to run checks

### ISSUE THREAD

**Issue by ilmai** [rust-lang/rust-analyzer#17127]
Latest version fails to run checks with the following error in logs (paths censored):

```
Caused by:
  process didn't exit successfully: `/home/***/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1932-linux-x64/server/rust-analyzer /home/***/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/clippy-driver /home/***/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: Unrecognized option: 'keep-going'
```

This error was from WSL but a similar error is produced on Windows and Mac. The error is fixed by installing the previous version 0.3.1924. This happens on all projects I tested with, regardless of if they have a build script or not.

**rust-analyzer version**: 0.3.1932

**rustc version**: 1.77.2

**editor or extension**: VSCode
```

**Comment by ilmai** [comment]
I don't. `cargo check --keep-going` works normally in the terminal.

**Comment by Veykril** [comment]
What toolchain versions do you have installed in WSL, what toolchain versions do you have installed locally? Looks like r-a is picking the wrong one somehow

**Comment by ilmai** [comment]
Windows:
stable-x86_64-pc-windows-msvc (default)
beta-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

WSL:
stable-x86_64-unknown-linux-gnu (default)

**Comment by Veykril** [comment]
is your windows stable version older? (I just wanna check what toolchain r-a might try to be running on, we should really make it print that somewhere). I assume our toolchain selection somehow makes it use your windows toolchain instead of the WSL one

**Comment by ilmai** [comment]
Both are 1.77.2

**Comment by IWANABETHATGUY** [comment]
As a workaround, you could downloaded the latest `rust-analyzer` https://github.com/rust-lang/rust-analyzer/releases/tag/2024-04-22,  and override the old one,

**Comment by ilmai** [comment]
Just tried the latest version, 0.3.1950. I still have the same issue but I noticed new information has been added to the popup: 
![image](https://github.com/rust-lang/rust-analyzer/assets/3365471/52e482ed-bcaa-40b0-90cb-63dfbda27a68)

**Comment by jeiroa** [comment]
I have the same issue @ilmai commented above. I noticed it is happening since the previous version of rust-analyzer.

Attached you can see the same error message when I hover over rust-analyzer tab at the bottom of VSCode IDE:
![snapshot](https://github.com/rust-lang/rust-analyzer/assets/12732000/4301677a-9314-4415-9658-9ccf4a0a0079)

**rust-analyzer version**: 0.3.1950
**rustc version**: 1.78.0
**editor or extension**: VSCode 1.89.1
**OS**: Ubuntu 22.04 LTS (Linux x64 5.15.0-106 generic)

**Comment by ilmai** [comment]
I updated to the latest version yesterday and this seems to be fixed
