### ISSUE TITLE
Can't infer type correctly

### ISSUE THREAD

**Issue by Jianqoq** [rust-lang/rust-analyzer#17123]
<img width="573" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/120760306/d4661c67-ee0a-4556-9f98-edf048d7d9d4">

rustc 1.77.2
rust analyzer-version(release): 0.3.1932, 0.3.1924, 0.3.1916, 0.3.1914, 0.3.1906 all failed

0.3.1896 works.

**Comment by Veykril** [comment]
What crates are involved here? That is where does `Tensor` come from and is arange a trait function (trait from same or different crate?) or inherent?

**Comment by Jianqoq** [comment]
The Tensor is from my own project, the arange method is a trait method. Tensor and the trait are defined in different crate.

**Comment by Veykril** [comment]
Then we'll need to see the relevant source parts here or we won't be able to deduce the issue

**Comment by Jianqoq** [comment]
https://github.com/Jianqoq/FastTensor, you can see error in `src/main.rs`

**Comment by detrumi** [comment]
> https://github.com/Jianqoq/FastTensor, you can see error in `src/main.rs`

The repo gives a 404 now
