### ISSUE TITLE
non-exhaustive pattern: `&mut _` not covered rust-analyzer E0005 when using make_static from static_cell

### ISSUE THREAD

**Issue by dragonnn** [rust-lang/rust-analyzer#17129]
**rust-analyzer version**: rust-analyzer version: 0.3.1932-standalone and 0.4.1933-standalone

**rustc version**: 1.79.0-nightly (7f2fc33da 2024-04-22)

**editor or extension**: VSCode extension version v0.3.1932 and v0.4.1933 (pre-release)

**relevant settings**: no extra variables/settings are set as far I can tell

**repository link (if public, optional)**: [rust_analyzer_make_static_bug](https://github.com/dragonnn/rust_analyzer_make_static_bug)

**code snippet to reproduce**: 
```rust
#![feature(type_alias_impl_trait)]
#![feature(impl_trait_in_assoc_type)]

use static_cell::make_static;

fn main() {
    println!("Hello, world!");

    let buff: &mut Vec<u8> = make_static!(Vec::new());
}
```

When doing some embedded programming (but it does happen on std too) I am getting since about a month errors ```non-exhaustive pattern: `&mut _` not covered rust-analyzer E0005``` from rust-analyzer every time I use `make_static!` macro from [static_cell](https://crates.io/crates/static_cell) (needs nightly feature). They are no errors show by cargo check and the code compiles and runs fine. This is persitent through multiple nightly rustc version and happens both on stable and pre-release version of rust-analyzer. Attached trace log from ra

[trace.log](https://github.com/rust-lang/rust-analyzer/files/15075427/trace.log)

In Rust Analyzer Language Server tab in the Output tab I see too this:
```
2024-04-23T10:40:07.264531Z ERROR hir_ty::diagnostics::match_check::pat_analysis: Unexpected type for `Struct` constructor: !OpaqueTy#0<[]>
```
With does pop only when make_static! is used in the project.
As far I can tell this error is only reported when the file using `make_static!` is open. If I am editing another file in the project and main.rs is closed it isn't show up red, they are no errors in error tab and the  Rust Analyzer Language Server tab is silent.

**Comment by Veykril** [comment]
`type_alias_impl_trait` isn't implemented yet https://github.com/rust-lang/rust-analyzer/issues/13824

**Comment by Sycrosity** [comment]
Is there any workaround for this? I tried to allow it using `#![allow(non_exhaustive_omitted_patterns)]` but even that doesn't change this error - can it only be fixed by #13824?

**Comment by yanshay** [comment]
Did anyone find a workarounds to this? I'm also developing for embedded and have multiple cases where this shows.

**Comment by ChayimFriedman2** [comment]
You can disable this error (but that means you won't get it even when it's correct of course). Include it in `rust-analyzer.diagnostics.disabled`.

**Comment by dragonnn** [comment]
currently make_static! macro is broken on nightly completely so I recommend moving away from it anyway and create your StaticCell by hand.
