### ISSUE TITLE
Analyzer displays {error} for lifetime inferred hint

### ISSUE THREAD

**Issue by hjamieson** [rust-lang/rust-analyzer#17141]
While writing some tests to learn about rust lifetimes, I ran into this odd case where the analyzer displays {error} for how the lifetime is being inferred by the compiler:

```rust
struct Foo<'a, T> {
    d: &'a [T]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn foo_test() {
        let data = [15; 8];
        let foo_i32: Foo<'{error}, i32> = Foo{d: &data};
        assert!(foo_i32.d.len()== 8);
    }
}
```

I've had some feedback and I would think it should be `: foo<_, i32>` .

I'm pretty new to rust, so this might be correct, but all other indications are that this code is valid.  Is this a bug?``

**Comment by hjamieson** [comment]
I should mention:
**rust-analyzer**
v0.3.1932

**vscode:**
Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:43:08.196Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

**Comment by lnicola** [comment]
Fixed in https://github.com/rust-lang/rust-analyzer/pull/17134, it now looks like this:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/2e834511-4757-4b59-bff2-afb871e5174d)
