### ISSUE TITLE
Incorrect analysis of std::ffi::CString in rust-analyzer v0.3.1940

### ISSUE THREAD

**Issue by Aobanana-chan** [rust-lang/rust-analyzer#17169]
**rust-analyzer version**: v0.3.1940

**rustc version**: 1.77.1

**editor or extension**: VSCode

**code snippet to reproduce**: 
```rust
use std::ffi::CString;

fn main() {
    let _s = CString::new("test");
}

```
When I create a new instance of std::ffi::CString, the variable type analysis incorrectly shows "unknown".
![image](https://github.com/rust-lang/rust-analyzer/assets/25476118/5009e63c-25a6-42fa-ab21-995360a5434c)

This problem is resolved when I revert to version v0.3.1932 of rust-analyzer. 
![image](https://github.com/rust-lang/rust-analyzer/assets/25476118/b784aa14-bbed-4504-938b-25aad519a0bd)

**Comment by lnicola** [comment]
Caused by #17151.

**Comment by prajwalch** [comment]
Same issue with me in `rust-analyzer-v0.3.1940`
