### ISSUE TITLE
quick fix only applies one half of the proposed fix from clippy, wont compile anymore after doing the quick fix

### ISSUE THREAD

**Issue by antonilol** [rust-lang/rust-analyzer#17163]
**rust-analyzer version**: rust-analyzer version: 0.4.1939-standalone

**rustc version**: rustc 1.77.0 (aedd173a2 2024-03-17)

**editor or extension**: code OSS (open core of vscode)

**relevant settings**: i use cargo clippy instead of cargo check, to get clippy suggestions in the editor, this is relevant for reproducing this

**code snippet to reproduce**: 
```rust
fn main() {
    let a;
    let b = 0;
    a = b;
    let _ = a;
}
```

apply one of the the two parts from the suggested quick fix

this is not a clippy bug, auto-fixing it with clippy will apply both parts

**Comment by roife** [comment]
Possibly related to rust-lang/rust#53934. Currently, the JSON from the compiler (as well as Clippy) is unable to differentiate between 'single diagnostics containing multi-spans' and 'multiple mutually exclusive diagnostics'. Consequently, r-a is also unable to distinguish them.

Perhaps we should wait for the upstream to fix it first.

**Comment by roife** [comment]
I believe https://github.com/rust-lang/rust-clippy/pull/12777 has fixed it.

**Comment by antonilol** [comment]
i can't confirm this has been fixed, but there could be an error in my setup
```
$ cargo clippy --version
clippy 0.1.80 (791adf7 2024-05-21)
```
my default is stable, but i have a `rust-toolchain.toml` that sets it to nightly

the quick fix menu also only shows one of the two parts:
![image](https://github.com/rust-lang/rust-analyzer/assets/49868160/3a989ba1-b484-461a-8fcd-23c773da6f0a)

**Comment by roife** [comment]
> the quick fix menu also only shows one of the two parts:

The PR has been merged into Clippy, but it hasn't been merged upstream yet.

**Comment by antonilol** [comment]
> The PR has been merged into Clippy, but it hasn't been merged upstream yet.

oh ok, is there a use to clippy nightly releases then?

**Comment by Veykril** [comment]
The clippy component in the rustup toolchain is whatever was synced back into rust-lang/rust last. They don't do it every day.

**Comment by antonilol** [comment]
oh right i see, thanks for clarifying, i found [this](https://github.com/rust-lang/rust/commit/72d8d8d9f91122c59601b52c7f495f4e4dc50e29) merge there, which includes the pr that closed this
