### ISSUE TITLE
Getting proc macro not expanded: No proc-macros present for crate rust-analyzer (unresolved-proc-macro) on macos

### ISSUE THREAD

**Issue by installgentoo** [rust-lang/rust-analyzer#17178]
https://github.com/rust-lang/rust-analyzer/issues/16331

Is now in stable 1.78

**Comment by installgentoo** [comment]
> Please fill out the issue template information, there is a reason we have that there

just reopen the linked issue for stable

**Comment by Veykril** [comment]
Closing in favor of https://github.com/rust-lang/rust-analyzer/issues/17231 as that has actual information
