### ISSUE TITLE
Conditional methods don't get suggested by Rust Analyzer

### ISSUE THREAD

**Issue by nvzqz** [rust-lang/rust-analyzer#17189]
**rust-analyzer version**: 0.3.1940-standalone (f216be4a0 2024-04-27)

**rustc version**:

```
rustc -Vv
rustc 1.77.2 (25ef9e3d8 2024-04-09)
binary: rustc
commit-hash: 25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04
commit-date: 2024-04-09
host: aarch64-apple-darwin
release: 1.77.2
LLVM version: 17.0.6
```

**editor or extension**: VSCode

**code snippet to reproduce**:

```rust
#[divan::bench]
fn my_benchmark(bencher: divan::Bencher) {
    bencher.bench(|| {/* ... */});
}
```

It used to be that methods like [`bench`](https://docs.rs/divan/latest/divan/struct.Bencher.html#method.bench) or [`with_inputs`](https://docs.rs/divan/latest/divan/struct.Bencher.html#method.with_inputs) + [`bench_values`](https://docs.rs/divan/latest/divan/struct.Bencher.html#method.bench_values) would be suggested by Rust Analyzer. This no longer works.

`Bencher` uses a similar pattern to:
```rust
struct Container<A>(A);

impl<A: Fn()> Container<A> {
    fn invoke(&self) {
        (self.0)()
    }
}
```

**Comment by Veykril** [comment]
cc @davidbarsky I assume that this might be caused by your changes

**Comment by alshdavid** [comment]
[Repro](https://github.com/alshdavid-scratch/rust-analyzer-no-bench-prompt)

Marking my benchmark as `#[bench]` or `#[divan::bench]` results in no "run benchmark" prompt appearing.

<img width="583" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/12656294/da11a133-3b9f-45f2-a6b5-0abce8cfdb58">

Rust Analyzer Version `v0.3.1958`
Rust Version `1.78.0`
Vscode Version `1.89.1`

**Comment by davidbarsky** [comment]
I also thought it might be related to #16555, but I don't think it is. I commented out out the `trait_candidates.retain` block and only got `.counter` suggested. It might be something else.

**Comment by Veykril** [comment]
This seems to work again now, why? I don't know but there have been a few fixes to both method search and trait bound constructions so likely something in there fixed this
