### ISSUE TITLE
Rust analyzer always complains about diesel source code

### ISSUE THREAD

**Issue by thanh2k5vn** [rust-lang/rust-analyzer#17197]
Hi,
I'm not sure why rust analyzer complains about diesel source code (I'm using latest diesel install by homebrew)
Step to reproduce : 
- Clone https://github.com/diesel-rs/diesel
- Open project with Helix / VsCode and wait for the rust analyzer run 
- Rust analyzer complains about things 
![image](https://github.com/rust-lang/rust-analyzer/assets/145553981/7f985030-7d6b-4f7c-9931-d566874d9b3e)

- Run cargo check 
![image](https://github.com/rust-lang/rust-analyzer/assets/145553981/34b3f0ba-1cf5-425a-9147-07d3d7287f12)

Thanks so much

**Comment by Veykril** [comment]
Those look like cargo check diagnostics if I see that right, do you have any feature config set in rust analyzer?

**Comment by thanh2k5vn** [comment]
No, I'm really new to rust, so I use the default configs for rust analyzer.

**Comment by thanh2k5vn** [comment]
Problem solved by deleting the repo and reclone it. Closing the issue. Thanks so much for taking your time.
