### ISSUE TITLE
Show docs on a function with attribute macro show signature of an expanded item inside the function

### ISSUE THREAD

**Issue by mrnossiom** [rust-lang/rust-analyzer#17205]
**code snippet to reproduce** (repro link below): 
```rust
#[tracing::instrument]
fn foobar() {
	// ↑↑ Hover or trigger docs on `foobar`

	// See how it shows:
	// `let __tracing_attr_fake_return: ()`
	// instead of function signature
	// `fn foobar()`
}
```

I would expect to see the function signature of `fn foobar` but I have the signature of `tracing`'s macro let variable.

![image](https://github.com/rust-lang/rust-analyzer/assets/43814157/bf02929d-8750-499b-8ba3-b7f50d230bd1)

You can check macro expansion here : https://github.com/mrnossiom/ra-show-docs-macro/blob/main/expansion.rs

# Meta

- **rust-analyzer version**: `rust-analyzer 1.77.1 (7cf61eb 2024-03-27)`
- **rustc version**: `rustc 1.77.1 (7cf61ebde 2024-03-27)`
- **editor or extension**: just plain LSP with `helix 24.3 (2cadec0b)`
- **relevant settings**: (none?)
- **repro link**: https://github.com/mrnossiom/ra-show-docs-macro

**Comment by mrnossiom** [comment]
I have checked the behavior as of today with `rust-analyzer 1.83.0 (90b35a6 2024-11-26)`.

Now the function name and documentation appears at the top but all documentation for all the items inside the expansion are also appended to the bottom making the panel very verbose and not as much readable as it could be.

It this something actually wanted, or just a bug?
I'll close accordingly.

**Comment by Veykril** [comment]
This works as intended, we can't tell whats "internal" and what is meant to be exposed by proc-macros (that's where hygiene would come in but the relevant parts are unstable), so we have heuristics going on to sort things (like the hover docs) by how useful (we think) they are. We can't really improve on this unfortunately.
