### ISSUE TITLE
Implement missing members introduces a \ before the curly braces of functions of a trait

### ISSUE THREAD

**Issue by vaporif** [rust-lang/rust-analyzer#17219]
Implementing trait inserts `\}` at the end 
```
impl Add for Vec3 {
    type Output;

    fn add(self, rhs: Self) -> Self::Output {
        todo!()
    \}
}
```

Seems like regression of https://github.com/rust-lang/rust-analyzer/issues/16607

Works fine on `1.77.2`

**rust-analyzer version**: rust-analyzer 1.78.0 (9b00956e 2024-04-29)

**rustc version**: rustc 1.78.0 (9b00956e5 2024-04-29)

**editor or extension**: neovim standard mason setup

**relevant settings**:  n/a

**Comment by lnicola** [comment]
Can you test using a binary downloaded from GitHub instead of the rustup version?

**Comment by roife** [comment]
Might be similar to https://github.com/rust-lang/rust-analyzer/issues/16867.

**Comment by Veykril** [comment]
Also make sure to update your editor stuff (editor itself, and lsp integration if separate)

**Comment by alexniver** [comment]
same issue on `archlinux`, `neovim`, `mason`

```
rustc 1.79.0 (129f3b996 2024-06-10)
rust-analyzer 1.79.0 (129f3b9 2024-06-10)
```
```
impl Default for RenderResource {
    fn default() -> Self {
        Self { state: Default::default(), pos_to_render_arr: Default::default() \}
    \}
}

```

**Comment by roife** [comment]
> same issue on `archlinux`, `neovim`, `mason`
> 
> 
> 
> ```
> 
> rustc 1.79.0 (129f3b996 2024-06-10)
> 
> rust-analyzer 1.79.0 (129f3b9 2024-06-10)
> 
> ```
> 
> ```
> 
> impl Default for RenderResource {
> 
>     fn default() -> Self {
> 
>         Self { state: Default::default(), pos_to_render_arr: Default::default() \}
> 
>     \}
> 
> }
> 
> 
> 
> ```

See https://github.com/rust-lang/rust-analyzer/issues/16867#issuecomment-2009391788, it is likely an issue on the neovim-side.

**Comment by alexniver** [comment]
> > same issue on `archlinux`, `neovim`, `mason`
> > ```
> > 
> > rustc 1.79.0 (129f3b996 2024-06-10)
> > 
> > rust-analyzer 1.79.0 (129f3b9 2024-06-10)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 
> > impl Default for RenderResource {
> > 
> >     fn default() -> Self {
> > 
> >         Self { state: Default::default(), pos_to_render_arr: Default::default() \}
> > 
> >     \}
> > 
> > }
> > ```
> 
> See [#16867 (comment)](https://github.com/rust-lang/rust-analyzer/issues/16867#issuecomment-2009391788), it is likely an issue on the neovim-side.

em..., according to  https://github.com/rust-lang/rust-analyzer/issues/16867

 https://github.com/neovim/neovim/pull/25611  should fix this issue. this PR is merged to Neovim `0.10.0`
 
my neovim now is `0.10.0`, this issue doesn't fix.
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
Run "nvim -V1 -v" for more info
```

should I file a issue to neovim?

**Comment by alexniver** [comment]
I did some research on this issue, 

neovim version: `0.11 dev`

```
rustc 1.79.0 (129f3b996 2024-06-10)
rust-analyzer 1.79.0 (129f3b9 2024-06-10)
```

when i choose `implement missing member`, 
neovim run `client.request(ms.codeAction_resolve, action, function(err, resolved_action)`, return `resolved_action`
```
{
  edit = {
    documentChanges = { {
        edits = { {
            insertTextFormat = 2,
            newText = "\n    $0fn default() -> Self {\n        Self {  \\}\n    \\}\n",
            range = {
              ["end"] = {
                character = 24,
                line = 11
              },
              start = {
                character = 24,
                line = 11
              }
            }
          } },
        textDocument = {
          uri = "file:///home/zhulin/dev/rust/test/test_any/src/main.rs",
          version = 0
        }
      } }
  },
  kind = "quickfix",
  title = "Implement missing members"
}
```

is  `resolved_action`  generated by rust-analyzer?  `newText` not right here.

**Comment by roife** [comment]
> I did some research on this issue,
> 
> neovim version: `0.11 dev`
> 
> ```
> rustc 1.79.0 (129f3b996 2024-06-10)
> rust-analyzer 1.79.0 (129f3b9 2024-06-10)
> ```
> 
> when i choose `implement missing member`, neovim run `client.request(ms.codeAction_resolve, action, function(err, resolved_action)`, return `resolved_action`
> 
> ```
> {
>   edit = {
>     documentChanges = { {
>         edits = { {
>             insertTextFormat = 2,
>             newText = "\n    $0fn default() -> Self {\n        Self {  \\}\n    \\}\n",
>             range = {
>               ["end"] = {
>                 character = 24,
>                 line = 11
>               },
>               start = {
>                 character = 24,
>                 line = 11
>               }
>             }
>           } },
>         textDocument = {
>           uri = "file:///home/zhulin/dev/rust/test/test_any/src/main.rs",
>           version = 0
>         }
>       } }
>   },
>   kind = "quickfix",
>   title = "Implement missing members"
> }
> ```
> 
> is `resolved_action` generated by rust-analyzer? `newText` not right here.

It seems that the 'implement missing members' works correctly in v0.11.0-dev+0e3e1e6. Could you check if the issue might be due to your plugins or the distribution you are using?

**Comment by alexniver** [comment]
> > I did some research on this issue,
> > neovim version: `0.11 dev`
> > ```
> > rustc 1.79.0 (129f3b996 2024-06-10)
> > rust-analyzer 1.79.0 (129f3b9 2024-06-10)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > when i choose `implement missing member`, neovim run `client.request(ms.codeAction_resolve, action, function(err, resolved_action)`, return `resolved_action`
> > ```
> > {
> >   edit = {
> >     documentChanges = { {
> >         edits = { {
> >             insertTextFormat = 2,
> >             newText = "\n    $0fn default() -> Self {\n        Self {  \\}\n    \\}\n",
> >             range = {
> >               ["end"] = {
> >                 character = 24,
> >                 line = 11
> >               },
> >               start = {
> >                 character = 24,
> >                 line = 11
> >               }
> >             }
> >           } },
> >         textDocument = {
> >           uri = "file:///home/zhulin/dev/rust/test/test_any/src/main.rs",
> >           version = 0
> >         }
> >       } }
> >   },
> >   kind = "quickfix",
> >   title = "Implement missing members"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is `resolved_action` generated by rust-analyzer? `newText` not right here.
> 
> It seems that the 'implement missing members' works correctly in v0.11.0-dev+0e3e1e6. Could you check if the issue might be due to your plugins or the distribution you are using?

Very Sorry! My bad! I still use a plugin called `rust-tools` which  has been archived, after I switch to `rustaceanvim` everything works Ok! Thanks for your help!

**Comment by vaporif** [comment]
@alexniver Indeed. This was not an issue of rust-analyzer, rather my nvim distribuitiom (lvim). changing from rust-tools to rustaceanvim does indeed fix the issue
