### ISSUE TITLE
'Run All Tests' option off-screen when many test cases

### ISSUE THREAD

**Issue by CoenraadS** [rust-lang/rust-analyzer#17223]
**rust-analyzer version**: v0.3.1958

**rustc version**:  rustc 1.78.0 (9b00956e5 2024-04-29)

**editor or extension**:  VSCode 1.89.1

When having a test with many cases, it is impossible to run them all due to the length of the lens. It would be nice it 'Run All Tests' is the first lens option. Also the order of the lens doesn't follow the order of the cases.

```rust
#[cfg(test)]
mod test_example {
    use rstest::*;

    #[rstest]
    #[case(1)]
    #[case(2)]
    #[case(3)]
    #[case(4)]
    #[case(5)]
    #[case(6)]
    #[case(7)]
    #[case(8)]
    #[case(9)]
    #[case(10)]
    #[case(11)]
    #[case(12)]
    #[case(13)]
    #[case(14)]
    #[case(15)]
    #[case(16)]
    #[case(17)]
    #[case(18)]
    #[case(19)]
    #[case(20)]
    fn test(#[case] foo: i32) {}
}

```

![image](https://github.com/rust-lang/rust-analyzer/assets/5593825/949949f0-7ac7-4203-a895-25f0da08647c)

**Comment by aquirdTurtle** [comment]
Hmm, this seems to still be a problem
