### ISSUE TITLE
`std::fs::write` inside of proc-macro breaks intellisense

### ISSUE THREAD

**Issue by xxshady** [rust-lang/rust-analyzer#17234]
**rust-analyzer version**: 0.3.1958-standalone (5bf2f85c8 2024-05-09)

**rustc version**: 1.77.2

**editor or extension**: VSCode

**code snippet to reproduce** (UPDATED, again): 
```rust
#[proc_macro_attribute]
pub fn repro(_: TokenStream, input: TokenStream) -> TokenStream {
    let crate_name = env!("CARGO_PKG_NAME");
    std::fs::write(format!("{crate_name}/repro"), "").unwrap();
    input
}
```

<details>
  <summary>demo</summary>
  bugged:<br>
  <img src="https://github.com/rust-lang/rust-analyzer/assets/54737754/b11d3f42-5a76-449e-a1f1-ed116a8c4c3e"><br>
  not bugged:<br>
  <img src="https://github.com/rust-lang/rust-analyzer/assets/54737754/ac181ab9-1a5b-424f-b2b2-ecf0ec514c19">
</details>

**Comment by Veykril** [comment]
This works fine for me with and without the fs access

**Comment by flodiebold** [comment]
It's a bad idea in general, though.

**Comment by xxshady** [comment]
> This works fine for me with and without the fs access

@Veykril updated repro, for some reason it only happens when file is created inside of some directory

**Comment by Veykril** [comment]
will check later, but is the macro perhaps panicking on your system for some reason? (that is is it hitting the unwrap) Cause then this is expected

**Comment by xxshady** [comment]
no, its not panicking

**Comment by Veykril** [comment]
Are you sure it doesn't? Because it does for me 
![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/d19033c0-7457-4441-aee4-19a40d17f866)

**Comment by xxshady** [comment]
are you on linux? because i'm on windows, i updated repro again xd, old one stopped reproducing for me

https://github.com/rust-lang/rust-analyzer/assets/54737754/248a94e8-122a-4c44-842b-04ced29e07f2

**Comment by Veykril** [comment]
I am on windows as well, can you enable the setting `"rust-analyzer.diagnostics.experimental.enable": true,`? Just realized that macro errrors are still gated so you wont see proc-macros panic by default (we should change that)

**Comment by xxshady** [comment]
oh, i see, yes, it was panic in proc-macro

![image](https://github.com/rust-lang/rust-analyzer/assets/54737754/a549c6cb-ff4e-4897-a94e-a1118b4dea3f)

but why i can still see (some?) panics without enabling this experimental setting?

![image](https://github.com/rust-lang/rust-analyzer/assets/54737754/3223f6ab-0a36-4f71-a8f6-dc96dab7c240)

**Comment by Veykril** [comment]
The latter one comes from rustc that we just display inline as part of running cargo check on save

**Comment by xxshady** [comment]
ah, so proc-macro runs two times in workspace workdir, and in crate workdir, thats why file was creating
