### ISSUE TITLE
Autocomplete suggestions failing in examples

### ISSUE THREAD

**Issue by jprochazk** [rust-lang/rust-analyzer#17245]
**rust-analyzer version**: `rust-analyzer version: 0.3.1958-standalone`

**rustc version**: `rustc 1.78.0 (9b00956e5 2024-04-29)`

**editor or extension**: VSCode, rust-analyzer `v0.3.1958`

**relevant settings**: -

**repository link**: https://github.com/jprochazk/tvm/tree/ra-repro

**code snippet to reproduce**: 

This unfortunately does not repro in a fresh project, and I haven't been able to reduce it any further.

The relevant code snippet is:
```rust
fn main() {
    use std::time::Instant;

    Instant
    //     ^
    //     type `::` here
}
```

The relevant files are:
- https://github.com/jprochazk/tvm/blob/ra-repro/examples/test.rs
- https://github.com/jprochazk/tvm/blob/ra-repro/src/asdf.rs

Both files contain the same snippet. I would expect r-a to immediately display code suggestions, including e.g. `Instant::now`, but in the case of `examples/test.rs`, it does not show anything. Typing `::` as suggested and forcing suggestions via ctrl+space displays a "Loading..." tooltip, and according to the rust analyzer server trace, the request seems to hang:

(I waited 5 seconds here then cancelled it)
```
[Trace - 11:18:10 AM] Sending request 'textDocument/completion - (750)'.
Params: {
    "textDocument": {
        "uri": "file:///home/jp/dev/tvm/examples/test.rs"
    },
    "position": {
        "line": 3,
        "character": 13
    },
    "context": {
        "triggerKind": 1
    }
}


[Trace - 11:18:15 AM] Sending notification '$/cancelRequest'.
Params: {
    "id": 750
}


[Trace - 11:18:15 AM] Received response 'textDocument/completion - (750)' in 4811ms. Request failed: canceled by client (-32800).
```

The following sequence of actions also seems relevant:
1. type `::` - nothing
2. ctrl+space - infinite `Loading...` appears
3. escape - request is cancelled
4. type `n` - some suggestions appear
5. delete `::n`, and save the file
6. type `::now` - no suggestions at any point

**Comment by kilpkonn** [comment]
Do you have `term search` enabled?
Might be fixed by https://github.com/rust-lang/rust-analyzer/pull/17203

**Comment by jprochazk** [comment]
I tried setting `rust-analyzer.completion.termSearch.enable` to both `true` and `false`, and neither seems to have made a difference.

**Comment by jprochazk** [comment]
I tried this again today, and can no longer reproduce the issue. It seems like _something_ fixed it between when I posted the issue and now, but I unfortunately don't have the bandwidth to track down the exact change that fixed it for me 😅.

I can confirm that `rust-analyzer.completion.termSearch` still makes no difference either way, though.
