### ISSUE TITLE
Macro metavar `length` got renamed to `len`

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#17242]
See https://github.com/rust-lang/rust/pull/124987, we need to do the same

**Comment by lnicola** [comment]
I guess this is https://github.com/rust-lang/rust-analyzer/blob/6524922b1b1cfdf16d1e08785dec03f352f693a2/crates/mbe/src/parser.rs#L348, but should we wait until 1.80 is released?

**Comment by Veykril** [comment]
Well, it is still unstable and fortunately the standard library doesn't use this one so I don't think there is any value in waiting on it? (though we could temporarily support both)

**Comment by randomicon00** [comment]
Hi @Veykril  & @lnicola, I am back I have more free time to contribute to rust-analyzer. I would like to work on it!

**Comment by Veykril** [comment]
Go ahead!

**Comment by lnicola** [comment]
Fixed in #17242.
