### ISSUE TITLE
When hover docs, don't show the examples section for integers

### ISSUE THREAD

**Issue by ameknite** [rust-lang/rust-analyzer#17266]
**rust-analyzer version**: 0.4.1960-standalone (c0732c9f0 2024-05-14)

**rustc version**: rustc 1.78.0 (9b00956e5 2024-04-29)

**editor or extension**:  VSCode
```
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:32.757Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

**code snippet to reproduce**: 
```rust
// add your code here
fn main() {
    let _ = 1i32.abs();
}
```

Examples:
![Screenshot 2024-05-20 at 13 36 45](https://github.com/rust-lang/rust-analyzer/assets/104745335/10657275-15c9-42e1-ad65-3ba307548a97)
![Screenshot 2024-05-20 at 13 40 39](https://github.com/rust-lang/rust-analyzer/assets/104745335/446a203d-abf0-404c-81e4-b99bfac4af13)

**Comment by alibektas** [comment]
:wave: Duplicate #8092
