### ISSUE TITLE
Is there a way to make debugger to use std::fmt::Debug for showing variables?

### ISSUE THREAD

**Issue by 0xorial** [rust-lang/rust-analyzer#17276]
pretty annoying to have to click on ">" every time while there are debug formatters for many many types available...

**Comment by lnicola** [comment]
No, we don't implement debugging. That's done by e.g. GDB together with a debugging extension you have installed.

**Comment by 0xorial** [comment]
Thank you for quick response! By chance could you please outline how this should be done by GDB/extension? since they don't have knowledge of rust, they wouldn't know about anything rust-specific, so I imagine there should be some kind of extension to an extension? But I have too little knowledge of the ecosystem unfortunately...

**Comment by davidbarsky** [comment]
I can't comment on gdb, but lldb has a notion of a [`TypeSystem`](https://lldb.llvm.org/cpp_reference/classlldb__private_1_1TypeSystem.html#details) that allows different languages to hook into. In LLDB, while Rust piggybacks on Clang's `TypeSystem`, Swift defines its own `TypeSystem` that calls into the Swift compiler for debugging purposes. While it'd be possible to write something similar for Rust (lldb would call into Miri, as an example), there are two tricky details: 
- from a maintenance perspective, someone's going to need to keep the Rust `TypeSystem` up-to-date in the llvm monorepo. Figuring out the build bootstrapping process and resolving the circular dependency graph between rustc and llvm is possible, but it's hard work.
- A `TypeSystem` implementation needs to be in sync with the version of rustc the binary was compiled with, so ongoing synchronization effort would be needed to ensure the binaries produced by rustc could be debugged by lldb.
