### ISSUE TITLE
Long "Loaded workspaces" list results in cut-off command shortcuts

### ISSUE THREAD

**Issue by Skgland** [rust-lang/rust-analyzer#17286]
![image](https://github.com/rust-lang/rust-analyzer/assets/3877590/bc4a822b-a443-410b-af65-19b693f3a0d1)
compared to
![image](https://github.com/rust-lang/rust-analyzer/assets/3877590/c1f991b7-6523-45c2-8239-022989eb38f0)

Notice that the first image is missing the three options after "Reload Workspace".

**rust-analyzer version**:  0.3.1958-standalone

**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04)

**editor or extension**: VSCode (v0.3.1958)

**Comment by Veykril** [comment]
Heh I just finished a PR that removes that info again here https://github.com/rust-lang/rust-analyzer/pull/17287
