### ISSUE TITLE
Rust Analyzer Support for Pulsar Edit editor (IT IS LSP COMPATIBLE)

### ISSUE THREAD

**Issue by penguintheguy** [rust-lang/rust-analyzer#17290]
Hello maintainers, im a newbie in rust. I have used the ide-rust extention for atom in atom's fork called pulsar-edit. It works. But it seems outdated, can you bring the extention to pulsar-edit ???

Please?

**Comment by penguintheguy** [comment]
Or kinda help me making one?

**Comment by Veykril** [comment]
We only maintain the vscode extension as a reference implementation, anything else is out of scope as we do not have the resources for maintaing an extgension for every editor out there.

**Comment by penguintheguy** [comment]
ok
