### ISSUE TITLE
Autoimport not working with IDXGISwapChain1::cast

### ISSUE THREAD

**Issue by nxcy** [rust-lang/rust-analyzer#17293]
**rust-analyzer version**:
0.3.1958-standalone (5bf2f85c8 2024-05-09)

**rustc version**:
1.78.0 (9b00956e5 2024-04-29)

**editor or extension**: 
VSCode 1.89.1 (user setup)
Windows_NT x64 10.0.22631

**code snippet to reproduce**: 
```rust
fn create_dxgi_swapchain(
    factory: &IDXGIFactory6,
    command_queue: &ID3D12CommandQueue,
    hwnd: HWND,
) -> Result<IDXGISwapChain3> {
    unsafe {
        let x = factory.CreateSwapChainForHwnd(
            command_queue,
            hwnd,
            &DXGI_SWAP_CHAIN_DESC1 {
                Format: DXGI_FORMAT_R8G8B8A8_UNORM,
                SampleDesc: DXGI_SAMPLE_DESC {
                    Count: 1,
                    Quality: 0,
                },
                BufferUsage: DXGI_USAGE_RENDER_TARGET_OUTPUT,
                BufferCount: 2,
                SwapEffect: DXGI_SWAP_EFFECT_FLIP_DISCARD,
                ..Default::default()
            },
            None,
            None,
        )?;
        x.cast()
    }
}
```
![图片](https://github.com/rust-lang/rust-analyzer/assets/166065857/be956fa3-a1f0-46ee-8459-6dff607ba554)

**Comment by davidbarsky** [comment]
This isn’t sufficient information for us to reproduce (I don’t know what crate defines `IDXGIFactory6`…), but try installing a nightly rust-analyzer (or waiting for Monday’s stable release) to get https://github.com/rust-lang/rust-analyzer/pull/17270.
