### ISSUE TITLE
type inference fails when using matching on an `Option` using `.into()` on an `impl Into<Option<T>>`

### ISSUE THREAD

**Issue by databasedav** [rust-lang/rust-analyzer#17307]
**rust-analyzer version**: 0.3.1975-standalone

**rustc version**: rustc 1.78.0 (9b00956e5 2024-04-29)

**editor or extension**: VSCode 1.89.1

**code snippet to reproduce**: 
```rust
// let x: {unknown}
fn f1<T>(x_option: impl Into<Option<T>>) {
    if let Some(x) = x_option.into() {
        x;
    }
}

// let x: {unknown}
fn f2<T>(x_option: impl Into<Option<T>>) {
    match x_option.into() {
        Some(x) => { x; },
        _ => ()
    };
}

// let x: T
fn f3<T>(x_option: impl Into<Option<T>>) {
    if let Some(x) = Into::<Option<T>>::into(x_option) {
        x;
    }
}

```
i'm expecting `f1` and `f2` to give me `let x: T` like `f3` does, but instead i get `let x: {unknown}`

also `f1` and `f2` compile regardless

**Comment by ChayimFriedman2** [comment]
Dup of https://github.com/rust-lang/rust-analyzer/issues/5514.
