### ISSUE TITLE
Import Quick fix should sort items from the current workspace before items from external crates

### ISSUE THREAD

**Issue by joshka** [rust-lang/rust-analyzer#17303]
In ratatui, performing the `Import <type>` quick fix on Color shows: color_eyre::owo_..., another color_eyre import, ratatui::style::Color, then a crossterm import. The order that I want always is current crate types first, then alphabetical. The sort order seems pretty random right now.

<img width="362" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/381361/df041474-e57d-4543-a262-b4ea20a1e56d">

Why? Ctrl+., Enter Enter should be muscle memory

Even better might be to add an extra quick fix if there are crate imports that match as well as external imports: e.g.:
<img width="322" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/381361/c49e4b90-2598-4767-8e0a-29c9acbd612f">
Should have the same option to 'ratatui::style::Color` as this does:
<img width="502" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/381361/42f4aeae-fde1-4fff-961a-ac3f24002221">

Why? Different UI modality (menu vs popup) for the same action (add an import from this crate). They should be the same where possible to make muscle memory / defaults just work. Right now the popup is jarring as there's no general way to guess if you're going to hit one or the other until you actually view the result (assuming your hands are typing ahead rather than responding to what you see on the screen).

Does this sound like a reasonable heuristic? Is "one of the imports is in this workspace" something that can be determined while getting the list of valid imports?

**Comment by mathew-horner** [comment]
There are heuristics that handle the sort order, but in terms of preference for your code it seems to stop at the crate boundary. ([link](https://github.com/rust-lang/rust-analyzer/blob/b32f181f477576bb203879f7539608f3327b6178/crates/ide-assists/src/handlers/auto_import.rs#L273-L279)) It probably makes sense to make preference for workspace items somewhere between crate and std?

**Comment by joshka** [comment]
It took me a minute to work out why my example for this was not picking up the same crate logic. This code was in an example, so it's not in the same crate technically.
