### ISSUE TITLE
Auto find correct trait for missing functions for structs

### ISSUE THREAD

**Issue by kodmanyagha** [rust-lang/rust-analyzer#17311]
Hi, I have an important question. We need import some traits for activating some functions. Let me explain the situation with an example. Let us look that code:

```rust
let result = sqlx::query("SELECT * FROM users").fetch_all(&pool).await?;
let result = result
    .iter()
    .enumerate()
    .map(|(index, row)| {
        // In here I'm getting error because I didn't import `sqlx::Row` crate on the top
        let id: i32 = row.get(0);
        id
    })
    .collect::<Vec<i32>>();
```

When I add `use sqlx::Row;` myself on the top than I can use `get()` function. So my question is that: why rust-analyzer doesn't suggest the correct trait. Isn't it possible finding the correct trait? Thanks.

**Comment by davidbarsky** [comment]
What version of rust-analyzer are you using? This should be working properly if you're using Monday's release.
