### ISSUE TITLE
Always `Fetching: metadata`, resulting in `Blocking waiting for file lock on package cache`

### ISSUE THREAD

**Issue by ayangweb** [rust-lang/rust-analyzer#17324]
<img width="293" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/75017711/db9348d3-8bc2-4825-9608-1fff423749cc">

<img width="403" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/75017711/ea581900-4d74-4c65-86e5-f402d829822e">

The extension keeps spinning around, causing a `Blocking waiting for file lock on package cache`.

For this problem, I have tried various things that I have searched for on the internet, none of which have solved the problem!

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

<img width="935" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/75017711/133e00df-d1f6-4189-be1d-ec98fe2b1b40">

**rustc version**: (eg. output of `rustc -V`)

`rustc 1.78.0 (9b00956e5 2024-04-29)`

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)

`VSCode`

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

**code snippet to reproduce**: 
```rust
// add your code here
nothing
```

**Comment by lnicola** [comment]
Can you access GitHub? It's possible that we're not picking up the proxy settings.

**Comment by ayangweb** [comment]
> Can you access GitHub? It's possible that we're not picking up the proxy settings.

It seems to be a problem with the terminal agent, after some reconfiguration on my part it works fine!

**Comment by ayangweb** [comment]
> > Can you access GitHub? It's possible that we're not picking up the proxy settings.
> 
> It seems to be a problem with the terminal agent, after some reconfiguration on my part it works fine! Thanks
