### ISSUE TITLE
Not loading environment variables when building via launch.json

### ISSUE THREAD

**Issue by RobinWragg** [rust-lang/rust-analyzer#17331]
If I build my project from scratch by starting a debug session (using the default autogenerated launch.json), DYLD_FALLBACK_LIBRARY_PATH is not defined so the build fails (opencv requires that it is set in order to find libclang.dylib on macOS).

I have defined DYLD_FALLBACK_LIBRARY_PATH in my VSCode settings.json like this:
```
{
    "rust-analyzer.cargo.extraEnv": {
        "DYLD_FALLBACK_LIBRARY_PATH": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib",
        "PKG_CONFIG_PATH": "/opt/homebrew/opt/opencv/lib/pkgconfig"
    },
    "rust-analyzer.server.extraEnv": {
        "DYLD_FALLBACK_LIBRARY_PATH": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib",
        "PKG_CONFIG_PATH": "/opt/homebrew/opt/opencv/lib/pkgconfig"
    }
}
```

And I have also defined it in my ~/.zshenv file, to allow the project to build outside of VSCode. Neither of these approaches fix the issue.

Note that I can run `cargo build` in the VSCode terminal just fine. The issue is I can't build from scratch via the launch.json.

Thank you for your time.

rust-analyzer version: 0.3.1975-standalone (5bf2f85c8 2024-05-09)

rustc 1.78.0 (9b00956e5 2024-04-29)

editor: VSCode 1.89.1

**Comment by lnicola** [comment]
See https://rust-analyzer.github.io/manual.html#setting-runnable-environment-variables.

**Comment by RobinWragg** [comment]
@lnicola thanks but that doesn't work either.

**Comment by Veykril** [comment]
Youl'' need to set those in `"rust-analyzer.runnables.extraEnv":` as well right now

**Comment by RobinWragg** [comment]
@Veykril yes, that hasn't worked either. Same result.

**Comment by pr0mixe** [comment]
Same issue here. Trying to debug a rust bin with LLDB. launch.json looks like:
```
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug executable 'mixer-service'",
            "cargo": {
                "args": [
                    "build",
                    "--bin=mixer-service",
                    "--package=mixer-service"
                ],
                "filter": {
                    "name": "mixer-service",
                    "kind": "bin"
                }
            },
            "args": [],
            "cwd": "${workspaceFolder}"
        },
.....
```
Debugging starts and works, but the env variable defined in `settings.json` doesn't exist for that launch...

**Comment by Veykril** [comment]
Okay I found the issue, we do in fact not prepare the env when launching through a json task, I misread the code last time

**Comment by Veykril** [comment]
Okay nevermind, the problem is that rust-analyzer is not the one launching the debug task. It is `lldb` that does it so we have no control over the environment
