### ISSUE TITLE
unable to recognize the workspace in a tauri project

### ISSUE THREAD

**Issue by Iovans** [rust-lang/rust-analyzer#17355]
<img width="1222" alt="Screenshot 2024-06-06 alle 22 21 34" src="https://github.com/rust-lang/rust-analyzer/assets/53220110/efc99da6-ea99-4816-97ac-dd46d8669142">

**Comment by Veykril** [comment]
How does the project structure look like? This is lacking any useful information

**Comment by Iovans** [comment]
![Uploading Screenshot 2024-06-07 alle 16.00.42.png…]()
Sorry, here is the Project structure

**Comment by Iovans** [comment]
<img width="2048" alt="Screenshot 2024-06-07 alle 16 00 42" src="https://github.com/rust-lang/rust-analyzer/assets/53220110/c361bc72-af43-407f-ab45-aed9eae17716">
Sorry, here is the image with the structure of the project

**Comment by Veykril** [comment]
Hmm, that's odd, a cargo project one level deep should be autodiscovered 🤔 Did you open the folder as is, or is this a vscode workspace? Generally you can work around this by setting the `linkedProjects` config to your `Cargo.toml` in a vscode `settings.json` otherwise.

```json
    "rust-analyzer.linkedProjects": ["./src-tauri/Cargo.toml"],
// or this, unsure what your paths here are
    "rust-analyzer.linkedProjects": ["./App/src-tauri/Cargo.toml"],
````

**Comment by Iovans** [comment]
I opened using vscode normally,thank you i will try if that solution would work

**Comment by Iovans** [comment]
Didn't work, the error keeps showing
