### ISSUE TITLE
-32603: Invalid offset

### ISSUE THREAD

**Issue by Aaron-Ochieng** [rust-lang/rust-analyzer#17357]
How do i get rid of -32603: invalid offset from rust analyser?? Every time i start typing the error keeps popping up.
![Screenshot at 2024-06-07 13-48-32](https://github.com/rust-lang/rust-analyzer/assets/90903627/96127c35-6b5a-4102-848d-62cde7aa26c6)

**Comment by Veykril** [comment]
What language server client are you using, what is the rust-analyzer version?

**Comment by Aaron-Ochieng** [comment]
> What language server client are you using, what is the rust-analyzer version?

It doesn't display the version when run "rust-analyzer --version".

![Screenshot at 2024-06-07 20-26-46](https://github.com/rust-lang/rust-analyzer/assets/90903627/aacac6e3-7152-42ec-a0a9-48e2745978e7)

**Comment by Veykril** [comment]
Well, how did you get rust-analyzer specifically then (it is not shipped with the rust toolchain by default)? Did your editor / lsp client install it? What editor / lsp client is it? We'll need more info here to help. It seems likely to me that this is an editor issue as VSCode doesn't seem to have this problem.

**Comment by Veykril** [comment]
Also do the logs say anything? A backtrace would be good

**Comment by Aaron-Ochieng** [comment]
> Well, how did you get rust-analyzer specifically then (it is not shipped with the rust toolchain by default)? Did your editor / lsp client install it? What editor / lsp client is it? We'll need more info here to help. It seems likely to me that this is an editor issue as VSCode doesn't seem to have this problem.

I guess rust-analyser installed via mason has all of these error squiggles. Vscode works just fine. Let me redo the configuration. Thanks😊

**Comment by chaozwn** [comment]
> > Well, how did you get rust-analyzer specifically then (it is not shipped with the rust toolchain by default)? Did your editor / lsp client install it? What editor / lsp client is it? We'll need more info here to help. It seems likely to me that this is an editor issue as VSCode doesn't seem to have this problem.
> 
> I guess rust-analyser installed via mason has all of these error squiggles. Vscode works just fine. Let me redo the configuration. Thanks😊



> > Well, how did you get rust-analyzer specifically then (it is not shipped with the rust toolchain by default)? Did your editor / lsp client install it? What editor / lsp client is it? We'll need more info here to help. It seems likely to me that this is an editor issue as VSCode doesn't seem to have this problem.
> 
> I guess rust-analyser installed via mason has all of these error squiggles. Vscode works just fine. Let me redo the configuration. Thanks😊

Have you solved your problem？I have same problem.

**Comment by Aaron-Ochieng** [comment]
> > > Well, how did you get rust-analyzer specifically then (it is not shipped with the rust toolchain by default)? Did your editor / lsp client install it? What editor / lsp client is it? We'll need more info here to help. It seems likely to me that this is an editor issue as VSCode doesn't seem to have this problem.
> > 
> > 
> > I guess rust-analyser installed via mason has all of these error squiggles. Vscode works just fine. Let me redo the configuration. Thanks😊
> 
> > > Well, how did you get rust-analyzer specifically then (it is not shipped with the rust toolchain by default)? Did your editor / lsp client install it? What editor / lsp client is it? We'll need more info here to help. It seems likely to me that this is an editor issue as VSCode doesn't seem to have this problem.
> > 
> > 
> > I guess rust-analyser installed via mason has all of these error squiggles. Vscode works just fine. Let me redo the configuration. Thanks😊
> 
> Have you solved your problem？I have same problem.

What I did wrong was adding mason configuration to lazyvim. 
By default lazyvim comes with mason configuration already. I deleted the configuration, and also the rust analyzer in .cargo/bin directory. Did MasonInstall rust_analyzer and the problem was fixed.
