### ISSUE TITLE
`#[tracing::instrument]` impedes assists, parameter hints on annotated function

### ISSUE THREAD

**Issue by davidbarsky** [rust-lang/rust-analyzer#17363]
Reproduction:

```rust
#[tracing::instrument]
fn test() {
    let string = String::from("hello").replace("hello", "goodbye");
    let string = String::from("goodbye").replace("goodbye", "goodbye");
}
```

Cargo.toml:

```
[package]
name = "instrument-breaks-extract-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.40"
```

Highlighting `let string = String::from("hello").replace("hello", "goodbye");` with `#[tracing::instrument]` provides the "extract into variable" and "replace let with if let" assists. If I comment out `#[tracing::instrument]`, I get the "extract into variable", "extract into function", "replace with if let", and "insert explicit type `String`" assists.

The presence of `#[instrument]` also prevents the parameter name inlay hints on `String::replace` from rendering. With `#[instrument]`, `from:` and `to:` are missing, but they reappear once I remove `#[instrument]`.

**Comment by Wilfred** [comment]
Sounds similar to #16422?

**Comment by davidbarsky** [comment]
Oh, it does, yeah. I'll consolidate and mark this as a duplicate.
