### ISSUE TITLE
rust-analyzer thinks a file is unlinked when it is not

### ISSUE THREAD

**Issue by Speak2Erase** [rust-lang/rust-analyzer#17386]
**rust-analyzer version**: rust-analyzer version: 0.3.1992-standalone [/home/lily/.vscode/extensions/rust-lang.rust-analyzer-0.3.1992-linux-x64/server/rust-analyzer]

**rustc version**: rustc 1.77.0-nightly (11f32b73e 2024-01-31)

**editor or extension**: VSCode, ext version v0.3.1992

**relevant settings**: n/a

**repository link**: https://github.com/Speak2Erase/Luminol/tree/tilemap-optimizations

Honestly not sure what causes this, but while working on `crates/graphics/src/primitives/mod.rs` rust-analyzer would disable intellisense and grey out the entire file, because it is not included in the crate hierarchy. If I downgrade to the version from last week, this doesn't happen anymore
![image](https://github.com/rust-lang/rust-analyzer/assets/54482069/f146fe70-0624-4684-9f44-456e53301d16)

If I add some random gibberish to cause an error in the file, running `cargo run` will error:
![image](https://github.com/rust-lang/rust-analyzer/assets/54482069/31fdde5f-2365-4c18-b2f2-d3963de3b632)

It also doesn't highlight the mod statements in the containing module:
![image](https://github.com/rust-lang/rust-analyzer/assets/54482069/319c8947-f4d2-4756-b13f-450579406a3e)

rust-analyzer also refuses to format the file (and because I have format on save enabled) this means I can't save this file.

**Comment by Veykril** [comment]
You are likely running into https://github.com/rust-lang/rust-analyzer/issues/17378 which locks up discovery of everything. Can you try the latest nightly release? (switching to pre-release in vscode)

**Comment by lnicola** [comment]
This seems fixed for me, but please double-check. A stable release is also available now, no need to switch to nightly.

**Comment by Speak2Erase** [comment]
This does seem fixed now! Although I did notice RA grey out text while it was restarting

**Comment by lnicola** [comment]
Yup, that's normal. Thanks for testing!
