### ISSUE TITLE
cargo runnables no longer work

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#17402]
It seems that after this PR, the tests have stopped running.

```
 *  Executing task: cargo cargo test --package sqruff-lib --lib -- rules::layout::LT13::tests::test_fail_leading_whitespace_comment --exact --show-output 

error: no such command: `cargo`

        View all installed commands with `cargo --list`
        Find a package to install `cargo` with `cargo search cargo-cargo`
```

_Originally posted by @gvozdvmozgu in https://github.com/rust-lang/rust-analyzer/issues/16840#issuecomment-2162227412_

**Comment by davidbarsky** [comment]
should be fixed by #17407.

**Comment by yiyue-reimu** [comment]
have a look of [this](https://github.com/opensound-org/cargo-cargo)

**Comment by basdirks-purple** [comment]
> have a look of [this](https://github.com/opensound-org/cargo-cargo)

That's hilarious. Nice workaround 😂

**Comment by CryZe** [comment]
This still reproduces as of `v0.4.2024 (pre-release)`.

**Comment by Veykril** [comment]
Huh? Indeed its broken again, but I don't recall us changing anything at all since and it definitely did work again ...

**Comment by Veykril** [comment]
On a quick glance https://github.com/rust-lang/rust-analyzer/blob/1b283db47f8de1412c851c92bb4ce4ef039ff8ff/editors/code/src/tasks.ts#L90  is likely the issue

**Comment by Veykril** [comment]
Turns out i misunderstood parts of the tasks API which caused weird problems (tasks working in some workspaces but not in others)
