### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by evrensen467** [rust-lang/rust-analyzer#17408]
Hi, I was wondering why rust-analyzer uses up so much RAM, maybe a defect on my system, or any option to reduce it? I write javascript, python and swift a lot and their lsp process have never been flagged to use much RAM so I think there is something wrong with rust-analyzer, I noticed how it takes gigabytes of RAM after opening semi large projects and worse when I try to contribute to larger open source rust projects which makes my computer overall become very slow and unresponsive. Example, opening up https://github.com/zed-industries/zed takes about 3gb of RAM and keeps increasing the longer I have it open.

**Comment by davidbarsky** [comment]
I'll close this as a duplicate, but there were previous discussions about rust-analyzer's memory usage. This one might be the most relevant: https://github.com/rust-lang/rust-analyzer/issues/14956.
