### ISSUE TITLE
Completion for `pub(crate)` should add whitespace automatically

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust-analyzer#17428]
```rust
pub(crate) struct Plane {
    $0
    pub(crate) position: v64,
    pub(crate) normal: v64,
}
```

completing `pub(crate)` in this position gives

```rust
pub(crate) struct Plane {
    pub(crate)$0
    pub(crate) position: v64,
    pub(crate) normal: v64,
}
```

It would be better to give instead

```rust
pub(crate) struct Plane {
    pub(crate) $0
    pub(crate) position: v64,
    pub(crate) normal: v64,
}
```

That is, with a space

**Comment by roife** [comment]
We can also add space automatically after `unsafe` kw.

**Comment by matklad** [comment]
Yeah, it might make sense to audit all keyword completions for similar issues.

You can use `return` as an example — IIRC, it smartly decides between `return;$0` and `return $0` based on the type of the current function.
