### ISSUE TITLE
Extensions produce warning "invalid config values", which not related to any User settings

### ISSUE THREAD

**Issue by fatihaziz** [rust-lang/rust-analyzer#17421]
**rust-analyzer version**: v0.3.1995

**rustc version**: rustc 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: VSCode 1.90.1 (2024-06-11) Electron 29.4.0

**relevant settings**: All default (i reset all settings to default, i have confirm it on my `%USER%/.vscode/settings.json` and on my `%WORKSPACE%/.vscode/settings.json`)

**repository link (if public, optional)**: -

**reproduce**: 
1. Disable all extensions
2. Install latest rust-analyzer on vscode marketplace v0.3.1995
3. open any rust project
4. on the `rust-analyzer` taskbar got warning,
![image](https://github.com/rust-lang/rust-analyzer/assets/23287658/b98f48a0-5a10-41ce-8dee-81323948cc00)
```
invalid config values:

completion/enable/postfix/completion/enable/for/all: unexpected field

diagnostics/collect/infer/profiles: unexpected field

diagnostics/unresolved-imports: unexpected field

lens/indexing/deps: unexpected field

lens/indexing/method/refs: unexpected field

salsa/use/pretty/backtraces: unexpected field
```

**current solution**:
1. installing version: v0.3.1983 seems don't have this issue.

**Comment by fatihaziz** [comment]
> Are you sure there is not `.vscode/settings.json` file in any of the folders you have opened?

yes i'm sure, i will create a repo for this please wait

**Comment by fatihaziz** [comment]
Ohh i found the problem, 
its because of my rust-analyzer.toml
```
[diagnostics]
collect_infer_profiles = false
unresolved-imports = "error"

[salsa]
use_pretty_backtraces = false

[completion.enable_postfix_completion]
enable_for_all = false

[lens.indexing]
method_refs = false
deps = false
```

removing the file fix the issue. Sorry about this

**Comment by Veykril** [comment]
We do not which is why I figured there had to be some configuration file somewhere still

**Comment by fatihaziz** [comment]
> We do not which is why I figured there had to be some configuration file somewhere still (we should add where the config errors are coming from to the message)

is PR or changes about it already made? if not maybe i can contribute

**Comment by lnicola** [comment]
No, I don't think anything has changed.
