### ISSUE TITLE
renaming `self` should work outside of methods

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust-analyzer#17427]
```
pub fn dot(self, rhs: v64) -> f64 {
    self.x * rhs.x + self.y * rhs.y + self.z * rhs.z
}
````

This code is erroneous, as it is outside the impl. It should still be possible to rename `self` here:

```
pub fn dot(lhs: _, rhs: v64) -> f64 {
    lhs.x * rhs.x + lhs.y * rhs.y + lhs.z * rhs.z
}
```

**Comment by roife** [comment]
I find this useful when refactoring or moving functions. I will implement this feature within the next few days.
