### ISSUE TITLE
2024-06-10 break `test_log::test` macro

### ISSUE THREAD

**Issue by plusls** [rust-lang/rust-analyzer#17453]
**rust-analyzer version**: 2024-06-10

**rustc version**: rustc 1.81.0-nightly (8fcd4dd08 2024-06-18)

**editor or extension**: vscode

**relevant settings**: None
**repository link (if public, optional)**: None
**code snippet to reproduce**: 
```rust
// add your code here
fn main() {
    println!("Hello, world!");
}

fn ttt() -> String {
    String::new()
}

#[cfg(test)]
mod tests {
    use super::*;
    use test_log::test;

    #[test(tokio::test)]
    async fn test_ttt() {
        let a = ttt();
    }
}
```

Since rust analyzer 2024-06-10(0.3.1992)，it can not show the var type of a:

![image](https://github.com/rust-lang/rust-analyzer/assets/23459592/9a2a3bcb-2752-4ba9-ba40-dd5bb9769575)

And in rust analyzer 2024-06-03(0.3.1983)，it works

![image](https://github.com/rust-lang/rust-analyzer/assets/23459592/b778d794-11f6-44e8-b8f8-f5840d8867b6)

**Comment by roife** [comment]
The problem might be associated with #17004.
