### ISSUE TITLE
Incorrect macro parsing error

### ISSUE THREAD

**Issue by wackazong** [rust-lang/rust-analyzer#17465]
**rust-analyzer version**: v0.4.2004 (pre-release)

**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04)

**editor or extension**: VSCodium rust-analyer prerelease

**repository link (if public, optional)**: https://github.com/dtolnay/syn/issues/1684

**code snippet to reproduce**: 
See repo

Problem: RA reports an error of the macro, but the code compiles just fine on the command line.

**Comment by lnicola** [comment]
What error do you get, "missing ,"?

**Comment by Diggsey** [comment]
I've started getting an error, "expected `,`" on `format!` macros too...

**Comment by lnicola** [comment]
https://github.com/rust-lang/rust-analyzer/issues/17463

**Comment by wackazong** [comment]
I get expected ``,`` as well

**Comment by lnicola** [comment]
I've triggered a new nightly release, you can try it in about 15 minutes. But I suspect it's going to fix this issue.

**Comment by lnicola** [comment]
New release is out, you can get it from GitHub or the VS Code Marketplace.

**Comment by wackazong** [comment]
Ok, works for me. Thanks. I will leave the issue open for @Diggsey to confirm.
