### ISSUE TITLE
No definitions found, for only specific symbols

### ISSUE THREAD

**Issue by bjackman** [rust-lang/rust-analyzer#17476]
**rust-analyzer version**: `rust-analyzer 1.79.0 (129f3b9 2024-06-10)` / `rust-analyzer 1.79.0 (129f3b9 2024-06-10)`
**rustc version**: `rustc 1.79.0 (129f3b996 2024-06-10)`

**editor or extension**: VSCode 1.90.1

**relevant settings**: I believe I have no custom settings other than what's visible in the `.vscode/` checked into the linked repo. My user-level VSCode settings has only these lines that contain "rust":

```
	"rust-analyzer.trace.extension": true,
	"rust-analyzer.trace.server": "verbose"
```

**repository link (if public, optional)**: https://github.com/bjackman/local-ci/blob/575b715667c56eb582844f22a0b19f737942da25/src/test.rs#L469

**to reproduce**: 

- `cargo clean` (in terminal)
- `cargo build && cargo test` to generate builds for test and non-test configs
- Start fresh VSCode
- open src/test.rs, go-to-definition on the `TestOutcome` type referenced on line 477 -> it works
- On line 469 above, go-to-definitions on the `set_revisions` method referenced on line 469 -> it fails. Language server trace shows:

```
[Trace - 2:19:16 PM] Sending request 'textDocument/definition - (86)'.
Params: {
    "textDocument": {
        "uri": "file:///home/brendan/src/local-ci/src/test.rs"
    },
    "position": {
        "line": 468,
        "character": 10
    }
}


[Trace - 2:19:16 PM] Received response 'textDocument/definition - (86)' in 1ms.
Result: []
```

**Comment by Veykril** [comment]
Cause for that is the `test_log` attribute, this is fixed in the latest nightly version / next monday
