### ISSUE TITLE
Duplicate method completion from custom snippets

### ISSUE THREAD

**Issue by chenyukang** [rust-lang/rust-analyzer#17485]
<img width="623" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/230646/443a7ceb-9d45-46fc-8464-abdde3892873">

I noticed there is an option `rust-analyzer.completion.snippets.custom` for this:

https://github.com/rust-lang/rust-analyzer/blob/2fd803cc13dc11aeacaa6474e3f803988a7bfe1a/docs/user/generated_config.adoc#L356

But I manually set `rust-analyzer.completion.snippets.custom` an empty `{}`, these duplicated completions still come out.

**Comment by Veykril** [comment]
@alibektas I suspect the config changes might not clear the custom snippets?

**Comment by chenyukang** [comment]
I just found this config will remove those duplicated "Put the expression into an `Arc`":

```json
"rust-analyzer.completion.postfix.enable": false,
```

**Comment by amdRyzen5600X** [comment]
how to remove duplicates without disabling snippets from rust-analyzer
