### ISSUE TITLE
Hovering over numeric literals should show their type

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust-analyzer#17484]
It would be great if when displaying type info ("hover action"?) for a literal value, such as a function argument, its inferred type would be display along whatever else RA chooses to show.

For example, in the screenshot below `db.list_fuzzy_duplicates()` takes a `u16` parameter. Looking at the code, I can see that it takes a numeric value, but I can't see of what type. I wanted to refactor this out to make the constant/literal value a variable, but I had to look at the function declaration to see the type of the argument; I expected that this information would be revealed in the info for the literal argument as well:

![image](https://github.com/rust-lang/rust-analyzer/assets/606923/d3a7d9aa-2366-404d-93bf-77676fe8cdb7)

**Comment by roife** [comment]
I believe we’ve already implemented this feature. Could you check which version of the rust-analyzer you’re using?

<img width="401" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/17700217/4d3c2bde-9583-4987-94fd-f2033d3fccd2">

**Comment by Veykril** [comment]
Right I fixed this already in https://github.com/rust-lang/rust-analyzer/pull/17220 (wasn't sure if I actually fixed it or was planning to earlier)

**Comment by mqudsi** [comment]
Ah, I missed that PR by just a couple of days! My rust-analyzer is the nightly build from 2024-05-07. Time to update!

(and thank you very much)
