### ISSUE TITLE
No completions offered after async keyword

### ISSUE THREAD

**Issue by MariaSolOs** [rust-lang/rust-analyzer#17500]
_This issue is a follow-up of #17452_

**rust-analyzer version**: Using Neovim, so the version released in 2024-06-24.

**rustc version**: (eg. output of `rustc -V`) 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable) Neovim, but the issue also repros in VS Code.

**Reproduction steps**:
1. In a Rust file type `async f`.
2. Request completions.
3. Notice how there are no completions from rust-analyzer, while the expectation is for items like `fn` to be provided.

**Comment by roife** [comment]
In addition to `async`, we should also take into account `extern` and `const`, as well as the `default` and `try` which might be stable in the future.
