### ISSUE TITLE
Type inference breaks for types with generic lifetimes and generic type parameters with default values 

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust-analyzer#17515]
**rust-analyzer version**: `0.3.2011-standalone`
**rustc version**: `rustc 1.78.0 (9b00956e5 2024-04-29)`
**extension**:  VSCode extension `v0.3.2011`

# Reproduction

Paste the following code into `main.rs`
```rust
struct Blackjack<'a, T = bool> {
    state: &'a T,
}

impl<'a, T> Blackjack<'a, T> {
    fn method(self) {
        let _ = self.state;
    }
}

fn make_blackjack<'a>() -> Blackjack<'a> {
    Blackjack { state: &true }
}

fn main() {
    let blackjack = make_blackjack();
    blackjack.method();
}
```

# Expected

I expected rust-analyzer to resolve the `.method()` invocation correctly and highlight it as yellow according to my semantic tokens highlighting config.

# Actual

You may see that `method()` method symbol is unresolved. Here is how it looks in my VSCode. I configured unresolved symbols semantic token type to be displayed in pale-red. You may see that the lifetime parameter of the struct is inferred to be `{unknown}`. I suppose this is the reason why `.method()` is unresolved.

<img src="https://github.com/rust-lang/rust-analyzer/assets/36276403/f24bc051-aaab-40c1-af00-ab50ff498c50" width=500>

# Well-formed variation

If you remove the `T = bool` default value of the generic parameter on the struct definition and pass `bool` explicitly then all is fine. 

<img src="https://github.com/rust-lang/rust-analyzer/assets/36276403/3e21a1aa-0934-4579-bb8f-0cfd543d6ad1" width=500>

**Comment by flodiebold** [comment]
Hm, this works in older RA versions, so I guess it might have been broken with the lifetime inference work. @dfireBird

**Comment by Veykril** [comment]
This is https://github.com/rust-lang/rust-analyzer/issues/17075, I'm already looking into it
