### ISSUE TITLE
Thread Worker panicked at invalid offset. Request textDocument/completion failed

### ISSUE THREAD

**Issue by kanpov** [rust-lang/rust-analyzer#17550]
Can't even give you exact code to reproduce, this simply **happens every several minutes** on RA v0.3.2020 when actively editing code

```thread 'Worker' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/line-index-0.1.1/src/lib.rs:111:35:
invalid offset
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::option::expect_failed
   4: rust_analyzer::lsp::to_proto::range
   5: rust_analyzer::lsp::to_proto::text_edit
   6: rust_analyzer::lsp::to_proto::completion_items
   7: rust_analyzer::handlers::request::handle_completion
   8: std::panicking::try
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 9:19:59 PM] Request textDocument/completion failed.
  Message: request handler panicked: invalid offset
  Code: -32603 ```

**Comment by kanpov** [comment]
Literally am just editing code, this simply happens. And frequently

**Comment by kanpov** [comment]
Working on the following codebase: https://github.com/kanpov/lhf

**Comment by Veykril** [comment]
Does this happen in a specific file in that project?

**Comment by kanpov** [comment]
> Does this happen in a specific file in that project?

No, simply happens all the time, I'll try to pinpoint whether the frequency depends on the file being edited

**Comment by Veykril** [comment]
I don't get any panics when typing in that project. What rust-analyzer version are you using? any configs changed from the defaults?

**Comment by kanpov** [comment]
> I don't get any panics when typing in that project. What rust-analyzer version are you using? any configs changed from the defaults?

0.3.2020, nothing changed aside from clippy being autorun on save (format on save vscode option). The issue only pops up when actively editing and refactoring for several minutes straight

**Comment by kanpov** [comment]
Oh, and @Veykril this specific file seems to be a much more frequent source: https://github.com/kanpov/lhf/blob/master/src/ssh_russh/event_receiver.rs

**Comment by kanpov** [comment]
Pure speculation-wise my first and very vague guess (which is probably wrong), is that this might have something to do with the `#[async_trait]` procmacro?

**Comment by kanpov** [comment]
Diagnostics if they're of any use:
```
                                     ......             kanpov@localhost
     .,cdxxxoc,.               .:kKMMMNWMMMNk:.         ----------------
    cKMMN0OOOKWMMXo. A        ;0MWk:'      ':OMMk.      OS: openSUSE Tumbleweed 20240628 x86_64
  ;WMK;'       'lKMMNM,     :NMK'             'OMW;     Host: B450 AORUS PRO
 cMW;             WMMMN   ,XMK'                 oMM.    Kernel: Linux 6.9.6-1-default
.MMc             ''^*~l. xMN:                    KM0    Uptime: 4 days, 3 hours, 29 mins
'MM.                   .NMO                      oMM    Packages: 3163 (rpm), 7 (flatpak)
.MM,                 .kMMl                       xMN    Shell: bash 5.2.26
 KM0               .kMM0' .dl>~,.               .WMd    Display (M34WQ): 3440x1440 @ 144Hz
 'XM0.           ,OMMK'    OMMM7'              .XMK     DE: KDE Plasma 6.1.1
   *WMO:.    .;xNMMk'       NNNMKl.          .xWMx      WM: KWin (X11)
     ^ONMMNXMMMKx;          V  'xNMWKkxllox0NMWk'       WM Theme: Breeze
         '''''                    ':dOOXXKOxl'          Theme: Breeze (Dark) [QT], Breeze-Dark [GTK2], Breeze [GTK3]
                                                        Icons: breeze-dark [QT], breeze-dark [GTK2/3/4]
                                                        Font: Noto Sans (10pt) [QT], Noto Sans (10pt) [GTK2/3/4]
                                                        Cursor: breeze (24px)
                                                        Terminal: yakuake 24.05.1
                                                        Terminal Font: Hack (11pt)
                                                        CPU: AMD Ryzen 7 2700X (16) @ 3.70 GHz
                                                        GPU: NVIDIA GeForce RTX 3090 Ti [Discrete]
                                                        Memory: 19.47 GiB / 31.29 GiB (62%)
                                                        Swap: Disabled
                                                        Disk (/): 24.83 GiB / 168.81 GiB (15%) - btrfs
                                                        Disk (/home): 52.61 GiB / 307.48 GiB (17%) - xfs
                                                        Local IP (amn0): 10.8.1.8/32 *
                                                        Locale: en_US.UTF-8
```

**Comment by Veykril** [comment]
There is likely macros involved somehow. Though it is very confusing that you are saying this just happens anywhere

**Comment by kanpov** [comment]
> There is likely macros involved somehow. Though it is very confusing that you are saying this just happens anywhere

Well this codebase takes extensive use of async_trait, so it may be that. Plus the file I linked is where it happens not just once per several hours, but much more frequently

**Comment by kanpov** [comment]
@Veykril In this file: https://github.com/kanpov/lhf/blob/master/src/ssh_russh/event_receiver.rs
When trying to replace `session`, which is an unused variable, with `_session` according to the hint given by RA, the panic is **always** triggered.

**Comment by kanpov** [comment]
Yes, the first time a `_` is placed before an unused variable (the following times are likely cached so nothing happens), this exact panic is triggered

**Comment by Veykril** [comment]
Okay with that I can reproduce it
