### ISSUE TITLE
Feature request: Go to definition should be read-only when going outside workspace

### ISSUE THREAD

**Issue by TethysSvensson** [rust-lang/rust-analyzer#17569]
I often edit files in `~/.cargo/registry` by accident, because I thought I was in a local copy of a crate.

Vscode [has support for](https://github.com/microsoft/vscode/pull/181708) marking files as read-only (and other editors probably do as well). It would be nice mark files outside the current workspace as read-only by default, or otherwise introduce a small speedbump to prevent accidental editing of these files.

As a bonus extra feature, perhaps it should be possible to white-list certain paths outside the workspace, so they would also open in read-write mode.

**Comment by Veykril** [comment]
We can't really do much here, the language server protocol has nothing that allows us to tell the client that the file is readonly. And on the VSCode side readonly files are configured by a setting, I don't like rust-analyzer modifying the settings of a user too much, especially if we do it automatically. 

We could offer a command maybe / put a button the landing page that adds the appropriate entry to the setting.

For context, the following config will make the standard libraries of all toolchains as well as all your crates-io libraries readonly
"files.readonlyInclude": {
    "**/.cargo/registry/src/**/*.rs": true,
    "**/lib/rustlib/src/rust/library/**/*.rs": true,
},

**Comment by TethysSvensson** [comment]
I did not know those two settings existed. I agree that they prevent most accidental edits.

I think it would be a really nice service if rust-analyzer somehow made the users aware of this setting/helped them enable it, though I don't have an opinion on how to do this.

**Comment by lnicola** [comment]
I guess we could also show a notification here: "you're editing a file under `~/.cargo`, you really don't want that".
