### ISSUE TITLE
Strange inlay hints for auto-Deref

### ISSUE THREAD

**Issue by GoldsteinE** [rust-lang/rust-analyzer#17574]
**rust-analyzer version**: rust-analyzer 0.3.2029-standalone (latest release on the time of writing)

**rustc version**: rustc 1.81.0-nightly (6be96e386 2024-07-09)

**editor or extension**: NVIM v0.10.0

**relevant settings**:

```lua
local lspconfig = require('lspconfig')
lspconfig.rust_analyzer.setup {
  settings = {
    ['rust-analyzer'] = {
      inlayHints = {
	expressionAdjustmentHints = {
          enable = "reborrow",
	}
      },
    },
  },
}
```

**code snippet to reproduce**: 
```rust
pub fn c<'b>(cow: &'b Cow<'_, str>) -> Cow<'b, str> {
    Cow::Borrowed(cow)
}
```

Currently rust-analyzer shows the following hint:

```rust
Cow::Borrowed(*&&cow)
//            ^^^ hint
```

or, in postfix mode,

```rust
Cow::Borrowed(cow.*.&.*)
//               ^^^^^^ hint
```

I think they’re semantically different (prefix hint shows borrow-borrow-deref, whereas postfix hint shows deref-borrow-deref) and they’re also both incorrect: I think the proper sequence here is deref-deref-borrow, so `&**cow` and `cow.*.*.&`.

<details>
<summary>
Indeed, replacing <code>cow</code> with <code>*&*cow</code> gives a type error, and replacing it with <code>*&&cow</code> produces even more inlay hints:
</summary>

```
error[E0308]: mismatched types
   --> src/main.rs:6:19
    |
6   |     Cow::Borrowed(*&*cow)
    |     ------------- ^^^^^^ expected `&str`, found `Cow<'_, str>`
    |     |
    |     arguments to this enum variant are incorrect
    |
    = note: expected reference `&str`
                    found enum `Cow<'_, str>`
```

and

```rust
Cow::Borrowed(&****&&cow)
//            ^^^^ hint
```

respectively
</details>

while replacing it with `&**cow` works and doesn’t produce any inlay hints (as expected).

Is this a bug or am I missing something about how expression adjustment hints are supposed to work?

**Comment by GoldsteinE** [comment]
I’ve played with it a bit more and it seems to not be stable: I’ve gotten at least one `**&cow` hint (incorrect, doesn’t compile) and at least one correct `&**cow` hint.

**Comment by Veykril** [comment]
Hmm, I do get the correct sequence 🤨 
![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/744d30a3-2312-470f-b887-479f56913e88)
Though I am on `rustc 1.81.0-nightly (9c3bc805d 2024-06-27)` so maybe something funky happened on lang items?

**Comment by Veykril** [comment]
> I’ve played with it a bit more and it seems to not be stable: I’ve gotten at least one `**&cow` hint (incorrect, doesn’t compile) and at least one correct `&**cow` hint.

That sounds really weird

**Comment by Veykril** [comment]
Sounds like it might be an nvim issue with inlay hints targeting the same ranges?

**Comment by GoldsteinE** [comment]
That might be true, I’ll try to reproduce in another editor.

**Comment by GoldsteinE** [comment]
VSCodium always shows correct `&**`, so it’s probably related to Neovim. I’ll try to write a basic LSP server that reproduces the issue without rust-analyzer. Given that LSP spec guarantees the order of inlay hints:

> If multiple hints have the same position, they will be shown in the order they appear in the response.

it’s probably an issue on Neovim side.

Thanks for helping to debug this and sorry for a misfiled issue.
