### ISSUE TITLE
When I write down `unsafe impl Sync for ...`, I get an error `unsafe impl for safe trait`, Is this a bug?

### ISSUE THREAD

**Issue by Seng-Jik** [rust-lang/rust-analyzer#17589]
My rust installation was installed from **msys2** through `pacman -S mingw-w64-x86_64-rust`.

<img width="432" alt="image" src="https://github.com/user-attachments/assets/f20804d9-ae5f-4423-a7f5-c54220c59d9f">
<img width="475" alt="image" src="https://github.com/user-attachments/assets/c095c3d8-a915-4301-817f-594950255b90">

This error info is so confusing, because trait Sync and Send is an unsafe trait, and I can compile this code correctly.

**Comment by lnicola** [comment]
In my Rust version (1.80-beta.5), `Sync` is defined as `pub unsafe auto trait Sync`. But the diagnostic comes up, only to go away after a second or two. Does "Go to definition" work for you on `Sync`?

**Comment by Seng-Jik** [comment]
![image](https://github.com/user-attachments/assets/fcf9a14c-6300-4915-8e30-ad9c45a17eb7)

"Go to deinition" is not working.

> In my Rust version (1.80-beta.5), `Sync` is defined as `pub unsafe auto trait Sync`. But the diagnostic comes up, only to go away after a second or two. Does "Go to definition" work for you on `Sync`?

**Comment by Veykril** [comment]
are other items from the standard library prelude resolving? Does go to definition work on the `println`? Is the rust-analyzer status bar item yellow / saying anything when you hover it? It looks like we are failing to find the sysroot.

**Comment by lnicola** [comment]
I suspect `mingw-w64-x86_64-rust` doesn't include `rust-src`.

**Comment by Seng-Jik** [comment]
![image](https://github.com/user-attachments/assets/2cad959a-cf3d-4996-a5bb-31ba7a2907a2)

After I installed `mingw-w64-x86_64-rust`, it works fine.
