### ISSUE TITLE
Support for `+ use<..>` `precise_capturing` syntax

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust-analyzer#17598]
We're planning to stabilize `#![feature(precise_capturing)]` ahead of Rust 2024 (in all editions).  This feature allows one to write:

```rust
fn captures<'a: 'a, 'b: 'b, T>() -> impl Sized + use<'b, T> {}
//                                  ~~~~~~~~~~~~~~~~~~~~~~~
//                          This opaque type does not capture `'a`.

fn outlives<'o, T: 'o>(_: T) {}

fn caller<'o, 'a, 'b: 'o, T: 'o>() {
    //        ~~
    //        ^ Note that we don't need `'a: 'o`.
    outlives::<'o>(captures::<'a, 'b, T>());
}
```

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&code=%23%21%5Bfeature%28precise_capturing%29%5D%0A%23%21%5Ballow%28unused%29%5D%0A%0Afn+captures%3C%27a%3A+%27a%2C+%27b%3A+%27b%2C+T%3E%28%29+-%3E+impl+Sized+%2B+use%3C%27b%2C+T%3E+%7B%7D%0A%2F%2F++++++++++++++++++++++++++++++++++~~~~~~~~~~~~~~~~~~~~~~~%0A%2F%2F++++++++++++++++++++++++++This+opaque+type+does+not+capture+%60%27a%60.%0A%0Afn+outlives%3C%27o%2C+T%3A+%27o%3E%28_%3A+T%29+%7B%7D%0A%0Afn+caller%3C%27o%2C+%27a%2C+%27b%3A+%27o%2C+T%3A+%27o%3E%28%29+%7B%0A++++%2F%2F++++++++~~%0A++++%2F%2F++++++++%5E+Note+that+we+don%27t+need+%60%27a%3A+%27o%60.%0A++++outlives%3A%3A%3C%27o%3E%28captures%3A%3A%3C%27a%2C+%27b%2C+T%3E%28%29%29%3B%0A%7D%0A%0Afn+main%28%29+%7B%7D%0A)

That is, it allows for the precise capturing of generic parameters in RPIT-like impl Trait opaque types (the initial [stabilization](https://github.com/rust-lang/rust/pull/127672) will require all in scope type and const parameters to be included in the `use<..>` bound; see the [stabilization report](https://github.com/rust-lang/rust/pull/127672#issue-2406639114) for other restrictions).  We need this to stabilize so that we can stabilize the Lifetime Capture Rules 2024 ([RFC 3498](https://github.com/rust-lang/rfcs/blob/master/text/3498-lifetime-capture-rules-2024.md)) in Rust 2024.  These are lang team priority items for the Rust 2024 edition.

Currently r-a gives errors about this syntax:

```rust
fn captures<'a: 'a, 'b: 'b, T>() -> impl Sized + use<'b, T> {}
//                                              ~   ~~ ~  ~ ^ Syntax Error: expected an item
//                                              |   |  |  ^ Syntax Error: expected BANG
//                                              |   |  |  ^ Syntax Error: expected `{`, `[`, `(`
//                                              |   |  ^ Syntax Error: expected an item
//                                              |   ^ Syntax Error: expected SEMICOLON
//                                              ^ Syntax Error: expected a block
```

The earliest this syntax could conceivably stabilize is with Rust 1.82, which will branch on 2024-08-30 and will be released on 2024-10-17.

Tracking:

- https://github.com/rust-lang/rust/issues/123432

**Comment by Veykril** [comment]
Given we dont really handle opaque types wrt to their generic captures fully anyways I reckon it ought to be enough for us to merely add the parsing here for starters

**Comment by Veykril** [comment]
Relevant parser function is here https://github.com/rust-lang/rust-analyzer/blob/e9afba57a5a8780285f530172e3ceea1f9c7eff7/crates/parser/src/grammar/generic_params.rs#L141-L186

**Comment by winstxnhdw** [comment]
I’ll give this a go :)
