### ISSUE TITLE
Sponsoring a developer

### ISSUE THREAD

**Issue by bkchr** [rust-lang/rust-analyzer#17596]
Hey,
I'm looking for a developer who is actively contributing to rust-analyzer or interested in doing so. It would be nice to find someone who could help to improve rust-analyzer support for [polkadot-sdk](https://github.com/paritytech/polkadot-sdk/). If someone is interested, we could speak about how to sponsor this and the exact details.

**Comment by Young-Flash** [comment]
what do you mean by improving rust-analyzer support for [polkadot-sdk](https://github.com/paritytech/polkadot-sdk/)?

**Comment by lnicola** [comment]
Note that if the Polkadot codebase is as I remember it, most of the issues stem from limitations in `chalk`, which will be replaced with the new trait solver in the future.

**Comment by bkchr** [comment]
> what do you mean by improving rust-analyzer support for [polkadot-sdk](https://github.com/paritytech/polkadot-sdk/)?

We are quite heavily using traits and code generation using proc/declarative macros. The code base is also quite big. All these things together often lead to auto completions being slow or not present at all. Probably most of the work would be performance improvements, but I did not look into rust analyzer and what actually is going on.



> Note that if the Polkadot codebase is as I remember it, most of the issues stem from limitations in `chalk`, which will be replaced with the new trait solver in the future.

If this is the case. Maybe helping on integrating this sounds like a good start :)
