### ISSUE TITLE
Missing path verification in `vfs::file_set::FileSet::resolve_path`

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#17599]
```rs
include!("C:/hello.rs");
```
panics

**Comment by alibektas** [comment]
Path verification is indeed missing but I still cannot reproduce a panic. Any insights on what I may be missing?

**Comment by Veykril** [comment]
Ah this might only be a problem on windows specifically

**Comment by Veykril** [comment]
Actually I cant reproduce this anymore 🤔
