### ISSUE TITLE
Cargo watcher failed, the command produced no valid metadata (exit code: ExitStatus(unix_wait_status(25856)))

### ISSUE THREAD

**Issue by CesGalaxy** [rust-lang/rust-analyzer#17608]
**rust-analyzer version**: rust-analyzer version: 0.3.2037-standalone

**rustc version**: rustc 1.73.0 (cc66ad468 2023-10-03) (built from a source tarball)

**editor or extension**: VSCode (Google IDX, it uses Nix) | rust-analyzer v0.3.2037

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**repository link (if public, optional)**: [My project repo. I don't think it will help.](https://github.com/CesGalaxy/lubalia)

**r-a output error**: 
```
2024-07-16T13:18:45.135155Z ERROR rust_analyzer::main_loop: FetchBuildDataError:
error: the `--keep-going` flag is unstable, pass `-Z unstable-options` to enable it
See https://github.com/rust-lang/cargo/issues/10496 for more information about the `--keep-going` flag.


2024-07-16T13:18:46.133305Z ERROR flycheck: Flycheck failed to run the following command: CommandHandle { program: "/usr/bin/cargo", arguments: ["check", "--workspace", "--message-format=json-diagnostic-rendered-ansi", "--manifest-path", "/home/user/lubalia/Cargo.toml", "--keep-going", "--all-targets"], current_dir: Some("/home/user/lubalia") }, error=Cargo watcher failed, the command produced no valid metadata (exit code: ExitStatus(unix_wait_status(25856))):
error: the `--keep-going` flag is unstable, pass `-Z unstable-options` to enable it
See https://github.com/rust-lang/cargo/issues/10496 for more information about the `--keep-going` flag.
```

**Comment by Veykril** [comment]
You need to upgrade your rust toolchain or use an older rust-analyzer, we no longer support rust versions older than 1.74

**Comment by lnicola** [comment]
If you can't upgrade, you can give `rust-analyzer.cargo.buildScripts.overrideCommand` a try, or keep using an old release of r-a.

**Comment by DanielJoyce** [comment]
Well the docs in the overrideCommand for vscode need to be updated 

The default example given does not include --keep-going.

**Comment by gorgos** [comment]
```json
"rust-analyzer.cargo.buildScripts.overrideCommand": [
  "cargo",
  "check",
  "--quiet",
  "--workspace",
  "--message-format=json",
  "--all-targets"
]
```

This did not change anything for me btw. I've also played around with `invocationStrategy` + `invocationLocation` without any effect.
