### ISSUE TITLE
Unable to find definition for `hashbrown`

### ISSUE THREAD

**Issue by fishincat** [rust-lang/rust-analyzer#17606]
I have describe this at stackoverflow: https://stackoverflow.com/questions/78754358/vscode-rust-analyzer-can-not-find-definition-of-hashbrown

here is my code:

**main.rs**

```
use std::collections::HashMap;

fn main() {
    let _ = HashMap::<i32, i32>::new();
    println!("Hello, world!")
}
```

**Cargo.toml**

```
[package]
name = "world_hello"
version = "0.1.0"
edition = "2021"

[dependencies]
```

rust-analyzer version is: **v0.3.2037** (actually no version works)

`rust version`
```
Default host: x86_64-apple-darwin
rustup home:  /Users/fishincat/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-2023-12-28-x86_64-apple-darwin
nightly-2024-01-26-x86_64-apple-darwin
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.77.2 (25ef9e3d8 2024-04-09)
```

`rustup component list --installed`
```
cargo-x86_64-apple-darwin
clippy-x86_64-apple-darwin
rust-docs-x86_64-apple-darwin
rust-src
rust-std-x86_64-apple-darwin
rustc-x86_64-apple-darwin
rustfmt-x86_64-apple-darwin
```

**my problem is:**

When I jump to the definition of HashMap:
```
...
use hashbrown::hash_map as base;
...

pub struct HashMap<K, V, S = RandomState> {
    base: base::HashMap<K, V, S>,
}
```
I can not go deep to the definition of base(hashbrown), it shows:
```
No Definition found for hashbrown
```

how to solve this?

  [1]: https://i.sstatic.net/zOytnWT5.jpg

**Comment by fishincat** [comment]
![Uploading 20240716-194643.jpeg…]()

**Comment by fishincat** [comment]
![20240716-194643](https://github.com/user-attachments/assets/1bbfad2e-e6e1-44de-bb91-c6dc2a4233e9)

**Comment by Veykril** [comment]
You will have to enable the `"rust-analyzer.cargo.sysrootQueryMetadata": true,` config for this to work, but note that this means r-a will create and delete a lockfile in your toolchain's sysroot when you start a rust-analyze session. This is due to shortcoming in cargo

**Comment by fishincat** [comment]
@Veykril I don't know why "rust-analyzer.cargo.sysrootQueryMetadata" doesn't work any more.
![image](https://github.com/user-attachments/assets/e42cd80a-57c6-4bd5-99f7-e9edcba0ef4d)

**Comment by fishincat** [comment]
Rustc toolchain was updated to 1.80.1. It's this the problem?
![image](https://github.com/user-attachments/assets/151a3e2f-35c2-4665-a9bb-5aebab8b3979)

**Comment by lnicola** [comment]
See https://github.com/rust-lang/rust-analyzer/pull/17795. I think it will start working again in 1.82.

**Comment by Veykril** [comment]
Sorry I was a bit eager with dropping that flag 😅 Any toolchain version 1.82 and beyond will work (so you could use the current beta now as well I think)

**Comment by fishincat** [comment]
![Uploading image.png…]()

**Comment by fishincat** [comment]
> @fishincat wait, so does it work in 1.83.0-nightly (bd53aa3bf 2024-09-02)?

YES

**Comment by lnicola** [comment]
We actually try to run `rustup component add rust-src`, I don't know why it doesn't work.

**Comment by Veykril** [comment]
> We actually try to run `rustup component add rust-src`, I don't know why it doesn't work.

We don't run that for explicit sysroot paths, only when set to `discover`

**Comment by fishincat** [comment]
> > We actually try to run `rustup component add rust-src`, I don't know why it doesn't work.
> 
> We don't run that for explicit sysroot paths, only when set to `discover`

So is there any way to fix this?

**Comment by lnicola** [comment]
Remove `rust-analyzer.cargo.sysroot` from your settings or run `rustup +nightly component add rust-src`.

**Comment by fishincat** [comment]
> Remove `rust-analyzer.cargo.sysroot` from your settings or run `rustup +nightly component add rust-src`.
Yes, It works.
You guys are really magician!
