### ISSUE TITLE
Rust analyzer stopped working for all projects

### ISSUE THREAD

**Issue by annethereshewent** [rust-lang/rust-analyzer#17613]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) 
v 0.3.2029

**rustc version**: (eg. output of `rustc -V`)
1.70.0

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)
VSCode, rust-analyzer version 3.2037

Hi,

Rust-analyzer stopped working for me today for all my projects, I get the following error in my console:

```
2024-07-17T00:29:15.414870Z ERROR rust_analyzer::main_loop: FetchBuildDataError:
error: the `--keep-going` flag is unstable, and only available on the nightly channel of Cargo, but this is the `stable` channel
```

I am not using a nightly build, and I haven't done anything differently. Rust-analyzer just stopped working for me randomly, and now won't work. I see in the error message that it says the feature is available in a nightly build only, but I've never had to use a nightly build to use rust-analyzer so I'm not sure what's going on. Any help would be appreciated!

**Comment by lnicola** [comment]
See https://github.com/rust-lang/rust-analyzer/issues/17608.
