### ISSUE TITLE
Type hover/tooltip links always link to outer-most type

### ISSUE THREAD

**Issue by seritools** [rust-lang/rust-analyzer#17628]
![image](https://github.com/user-attachments/assets/5d0ba57a-009f-4dac-8ba7-7f853d58e47c)

When clicking `String` or `Global` in this info tooltip/hover UI, it always goes to `Vec`. Generally, it seems to go to the "outer-most" type instead of the one you clicked. This is of course especially annoying when looking at something with an inferred type ^^

**rust-analyzer version**: `rust-analyzer version: 0.4.2040-standalone (a62ea0a59 2024-07-17)`

**rustc version**: `rustc 1.79.0 (129f3b996 2024-06-10)`

**editor or extension**:

```plain
Version: 1.92.0-insider (user setup)
Commit: 65a6a2f783dbc87fb3b1408c6a9b3e8d455a60a2
Date: 2024-07-18T05:04:30.247Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100
```

**code snippet to reproduce**: 
```rust
pub struct Foo {
    pub bar: Vec<String>,
}
```

and hover over `bar`

**Comment by roife** [comment]
🤔 It works fine for me.

![未命名](https://github.com/user-attachments/assets/294b521c-a62b-4a31-9698-0b8787e15a3f)

**Comment by seritools** [comment]
🤔 that's weird. It's been broken for me for quite some time. In fact, it's broken for me even on the stable r-a extension version. :s

**Comment by roife** [comment]
I don't know what happened, but now I can also reproduce this bug now. 🫠

**Comment by Veykril** [comment]
Assuming the bug is only a couple weeks old it might be due to https://github.com/veykril/rust-analyzer/commit/ff07caa9de1a553d8572d9bf523e292858ee44d8

**Comment by Veykril** [comment]
Oh ye thats it 🤦 We overwrite the global for every link so only the last one persists. That global ought to track an array of links which gets overwritten on the next hover, not when rendering a command
