### ISSUE TITLE
Show associated items in trait's hover

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust-analyzer#17624]
Right now only the name and bounds are shown of a Trait. It's very useful to hover a struct and get the field names, so in the same way I think it's useful to have this.

```rust
1. Go to 858 implementations
───────────────────────────────────────────────────────────────────────
core::iter::traits::iterator

pub trait Iterator {
  type Item;
  fn next() -> Option<Self::Item>:
  ...
}
```
───────────────────────────────────────────────────────────────────────
A trait for dealing with iterators.

This is the main iterator trait. For more about the concept of iterators
...
```

**Comment by Veykril** [comment]
There is a `hover.show.traitAssocItems` config that allows you to toggle this behavior
