### ISSUE TITLE
Shadowing macro from `std` doesn't work

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust-analyzer#17623]
Take the following code as an example.

**code snippet to reproduce**: 
```rust
macro_rules! vec {
    ($elem:expr; $n:expr) => (std::vec![::core::convert::Into::into($elem); $n]);
    ($($x:expr),* $(,)?) => (std::vec![$(::core::convert::Into::into($x)),* ]);
}

fn main() {
    let actual: Vec<String> = vec!["foo", "bar", "baz"];
    assert_eq!(actual, ["foo", "bar", "baz"]);
}
```
RA can't understand that this local `vec` macro shadows the macro from `std`. The code compiles fine with `rustc` though.

![image](https://github.com/user-attachments/assets/1fba24dc-9508-4434-89f5-27414df34e17)

# Meta
**rust-analyzer version**: rust-analyzer version: 0.3.2037-standalone [/home/veetaha/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.2037-linux-x64/server/rust-analyzer]

**rustc version**: `rustc 1.79.0 (129f3b996 2024-06-10)`

**editor or extension**: VSCode

**Comment by roife** [comment]
I find that if I comment out `assert_eq`, then `vec` will correctly resolve to the local one.

**Comment by Veykril** [comment]
We don't resolve macros correctly when there is shadowing happening with textual macro scopes, there is a bunch of related issues https://github.com/rust-lang/rust-analyzer/issues/7084 https://github.com/rust-lang/rust-analyzer/issues/14862

Our macro name resolution is generally not working correctly in this regard

**Comment by Veykril** [comment]
This works now
