### ISSUE TITLE
Lack of autocompletion and other features in loops

### ISSUE THREAD

**Issue by laurmaedje** [rust-lang/rust-analyzer#17629]
In the example below, rust-analyzer (partially) fails to provide autocomplete, go-to-definition, etc. Specifically:

- In the while loop, `self.` is completed, but there is no autocompletion on `s.`
- In the for loop, nothing is completed, no matter whether on `self` or on `s`.

**rust-analyzer version**: 0.3.2037-standalone (e9afba57a 2024-07-14)

**rustc version**: rustc 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: VSCode, extension version v0.3.2037

**code snippet to reproduce**: 
```rust
struct Foo {
    val: u32,
}

impl Foo {
    fn while_loop(&self) {
        let mut iter = ["s"].into_iter();
        while let Some(s) = iter.next() {
            self.val;
            let _ = s.len();
        }
    }

    fn for_loop(&self) {
        for s in ["s"] {
            self.val;
            let _ = s.len();
        }
    }
}
```

**Comment by laurmaedje** [comment]
Can't reproduce the problem on a coworker's machine. I tried disabling all of my rust-analyzer configuration in VS Code, but it didn't help. I also use non-standard target dirs (one global one for rustc, and one global one for rust-analyzer), but disabling that didn't seem to help either.

**Comment by lnicola** [comment]
Do you get the right types for `iter` and `s`?

![image](https://github.com/user-attachments/assets/5b675210-d235-4191-86b8-e20abc7050b6)

What does "Go to definition" do on `into_iter`, and is your colleague also using 1.79?

**Comment by laurmaedje** [comment]
The types are largely broken as well. 

<img width="470" alt="image" src="https://github.com/user-attachments/assets/02912ed2-ffd0-4c17-8c46-fd001e8df29a">

Go to definition on `into_iter` works in the while loop. If I add it to the for loop as well, it doesn't work there.

My colleague is also on 1.79.

**Comment by Veykril** [comment]
Something looks wrong with the `Iterator` part for you, given the `Some(s)` doesn't even have a type hint either. Did you maybe accidentally edit your standard library sources? Can happen when looking through them and editing them won't break builds on your machine as the standard library is used as a pre-compiled library.

**Comment by laurmaedje** [comment]
That must have been it! I reinstalled my stable toolchain and now it works. Thank you!
