### ISSUE TITLE
Improve automatic name selection for "Extract into variable" on `from()` calls

### ISSUE THREAD

**Issue by kpreid** [rust-lang/rust-analyzer#17631]
```rust
// Stubs for demo
struct Foo {}
struct Bar {}
impl From<Foo> for Bar {
    fn from(_: Foo) -> Self {
        Bar {}
    }
}
fn do_something(_: Bar) {}

// Code of interest
fn main() {
    let foo = Foo {};
    do_something(Bar::from(foo));
    //           ^^^^^^^^^^^^^^ select this and extract into variable
}
```

The result of extraction is:

```rust
    let from = Bar::from(foo);
    do_something(from);
```

A better result would be:

```rust
    let bar = Bar::from(foo);
    do_something(bar);
```

`.into()` calls also currently produce variables named `into`, but that might be more trouble to fix; I don't know.

rust-analyzer version: 0.3.2037-standalone (e9afba57a 2024-07-14)

**Comment by lnicola** [comment]
This happens in https://github.com/rust-lang/rust-analyzer/blob/7011094/crates/ide-assists/src/utils/suggest_name.rs#L135.

**Comment by Lampese** [comment]
@kpreid How do you think it would be better to handle this situation?
```rust
use std::slice::Iter;

struct Foo;

impl From<Foo> for fn(&Iter<'_, i32>) -> *mut i32 {
    fn from(_: Foo) -> Self {
        todo!()
    }
}
``

**Comment by Fancyflame** [comment]
@Lampese I guess what he wants is that if Self is a path type, the variable name is the type name, otherwise fall back to `from`.
But personally, I think it is not conducive to unified management.

**Comment by kpreid** [comment]
Yes. Things like this can never be perfect; they can only handle common cases better.

Speaking of common cases, here's another one not using the `From` trait at all:

```rust
struct Foo {}
struct Bar {}
impl Bar {
    pub fn from_foo(_: Foo) -> Self {
        Self {}
    }
}
fn do_something(_: Bar) {}

fn main() {
    let foo = Foo {};
    do_something(Bar::from_foo(foo));
    //           ^^^^^^^^^^^^^^^^^^ select this and extract into variable
}
```

This generates the variable name `from_foo`, but, similarly, `bar` would usually be better. Since `from_*` constructor functions are part of Rust idiom, I think it would be good if rust-analyzer recognized those too, in the same way. That is, if there is a call of the syntactic form `*::$1::from_*(*)` or `*::$1::from(*)`, and `$1` is a type name, then `$1` should be (snake-cased and) used as the suggested variable name. No need to care whether the `From` trait is involved at all.

**Comment by joshka** [comment]
`with_` seems like a reasonable addition to this to be handled in the same way as `from_`
