### ISSUE TITLE
Rename `editor.action.triggerParameterHints` and `editor.action.rename` command capabilities

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#17644]
Same goes for the `"editor.action.triggerParameterHints",` capability. Thanks for calling that out I think we should move those over to `rust-analyzer.*` or similar. The names are based on the equivalent vscode commands but we should clearly not use the exact same names for those.

_Originally posted by @Veykril in https://github.com/rust-lang/rust-analyzer/issues/17587#issuecomment-2240955692_

**Comment by joshka** [comment]
https://github.com/rust-lang/rust-analyzer/pull/17647
