### ISSUE TITLE
Rust-analyzer is unable to format a file.

### ISSUE THREAD

**Issue by Ethanol48** [rust-lang/rust-analyzer#17648]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

rust-analyzer version: rust-analyzer version: 0.3.2037-standalone [/home/ethanol/.vscode/extensions/rust-lang.rust-analyzer-0.3.2037-linux-x64/server/rust-analyzer]

**rustc version**: (eg. output of `rustc -V`)

`rustc -V` :  `rustc 1.79.0 (129f3b996 2024-06-10)`

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)

VSCode.

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
`echo $CARGO $RUSTC $RUSTUP_HOME $CARGO_HOME`: `empty output`

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

**steps to reproduce**: 
In a VSCode installation in Manjaro Linux.
Install Rust toolchain, all tools are available in $PATH.
Install rust-analizer extention in VSCode.
Format a file.

When doing these steps I get this error in the VSCode output:

```
[Error - 12:58:43 PM] Request textDocument/formatting failed.
  Message: rustfmt exited with:
                           Status: exit status: 1
                           stdout: 
                           stderr: error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed

  Code: -32900 
```

**More context**
rustfmt is in my $PATH, and accesible from the terminal and works normally

**Comment by lnicola** [comment]
Anything like `rust-analyzer.rustfmt.overrideCommand` in your Code settings?

**Comment by Ethanol48** [comment]
I'm not sure, if I have to set this setting my self, I haven't done it, but I have to confirm

**Comment by Ethanol48** [comment]
Ok, I found the problem, I was using this setting: `rust-analyzer.rustfmt.extraArgs": ["+nightly"]`
and it was giving me this error for not having this installed? I'm not sure if I have it installed but maybe the error should be more explicit.

Eliminating this line resolved the problem.

**Comment by lnicola** [comment]
The error is pretty clear:

    toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed

It comes from `rustfmt` (well, from the shim), not us.

You can install the toolchain, add the `rustfmt` component and rock it like that.
