### ISSUE TITLE
Random capitalisation when using module

### ISSUE THREAD

**Issue by Why-not-now** [rust-lang/rust-analyzer#17654]
When I was creating a new file using the name "nucleus.rs" and used "`mod nucleus`", the quick fix suggested to use "`mod Nucleus`" and did not register my file to already be linked.
I am not too sure how to recreate this issue, cloning the repository into another location does not cause this issue.

Error:
![image](https://github.com/user-attachments/assets/8e23366d-2a12-4a1f-a595-40c1e2056d4b)
![image](https://github.com/user-attachments/assets/3e41a8d8-864a-4d57-97f5-0844bbcdc9da)

Fix suggested:
![image](https://github.com/user-attachments/assets/4cbd7133-a55b-4d63-a9cd-54143c41f384)

Directory structure:
![image](https://github.com/user-attachments/assets/7bfff66a-aaa5-44e3-94a2-37fb5faa29ac)

**rust-analyzer version**: 0.3.2037-standalone

**rustc version**: rustc 1.77.2

**editor or extension**: VSCode v0.3.2037

**relevant settings**: NIL

**Comment by Veykril** [comment]
Are you on windows and had a `Nucleas.rs` file before in this workspace? Then that's a known vscode bug where it caches the case of the file incorrectly reporting the wrong paths to rust-analyzer.

**Comment by Why-not-now** [comment]
Yeah I think so.
