### ISSUE TITLE
Incorrect brace highlighting when using character constants in generic const variables

### ISSUE THREAD

**Issue by Qix-** [rust-lang/rust-analyzer#17669]
> Prefacing this by saying I'm not entirely sure r-a is to blame here. I couldn't find where the syntax highlighting was coming from, so this might be a VSCode issue. Just let me know and I can move the issue over there if need be.

**rust-analyzer version**: rust-analyzer version: 0.3.2037-standalone

**rustc version**: rustc 1.80.0-nightly (804421dff 2024-06-07)

**editor or extension**: VSCode 1.91.1

**relevant settings**: Nothing unusual.

**repository link (if public, optional)**: N/A

**code snippet to reproduce**: 
```rust
#[derive(Default)]
struct Foo<const C: u8>;

fn foobar() {
    let c: Foo<b'}'> = Default::default();
}
```

This is [valid](https://godbolt.org/z/7ceMKveYx) rust that breaks syntax highlighting.

The constant can either be `b'}'`, which results in this incorrect highlighting (final `}` is red, indicating error):

![image](https://github.com/user-attachments/assets/7e554be9-9ecd-46d9-8049-ebadcabbd204)

or `b'{'` (initial `{` is red):

![image](https://github.com/user-attachments/assets/f5365220-fd09-47b5-bd6c-ed2f6b573e04)

Further, the constant itself is highlighted as though it is part of the syntax and not part of a character constant.

In the simple example it's a bit innocuous but in the larger codebase I initially found this in it started to really get confusing as small, subtle highlighting issues started to cascade through the bits under the constant.

**Comment by Veykril** [comment]
`rust-analyzer` does set the `colorizedBracketPairs` language configuration but I am not aware of any way to tell VSCode in what contexts not to consider these unfortunately

**Comment by Qix-** [comment]
FWIW it appears all character constants are being parsed incorrectly here, regardless of them being `{` or `}`.

![image](https://github.com/user-attachments/assets/37640593-76c3-4911-b8af-aadbb9b5a745)

**Comment by Veykril** [comment]
As in their color is incorrect? Can you put the cursor on one of those incorrect lit characters, run the `Inspect Editor Tokens and Scopes` command and paste the output?

**Comment by Qix-** [comment]
All taken from https://github.com/oro-os/qdb/blob/9496bd17903f23a64ef077e07124a72eff6bcdae/src/gdb.rs:

Incorrect:
![image](https://github.com/user-attachments/assets/3cb43919-94e3-4345-8daf-46745dee0054)

Correct:
![image](https://github.com/user-attachments/assets/8f03feed-13a6-48b5-9b13-1e12d7b5d264)

Incorrect:
![image](https://github.com/user-attachments/assets/4044145b-727b-4da9-864d-02ffe18f81b4)

Incorrect:
![image](https://github.com/user-attachments/assets/6c4ca456-8f66-4762-8584-2ad78e3d3223)

Incorrect:
![image](https://github.com/user-attachments/assets/df68827b-4b76-4162-97db-5cb0c79cd7a9)

**Comment by Veykril** [comment]
Ah, do you have semantic highlighting disabled? Then this is a VSCode issue, rust-analyzer does not ship with a textmate grammar so this is likely a bug with vscode's textmate grammar

**Comment by Qix-** [comment]
I don't think I've explicitly disabled it but yeah it appears to be an issue with the textmate grammar. I'll open an issue over there, then :)

Thanks for investigating either way!
