### ISSUE TITLE
rust-analyzer ignores linkedProjects after version 0.4.2040

### ISSUE THREAD

**Issue by Szybet** [rust-lang/rust-analyzer#17664]
**rust-analyzer version**: 0.4.2042 (and all above this version)

**rustc version**: rustc 1.82.0-nightly (92c6c0380 2024-07-21)

**editor or extension**: vscode, rust-analyzer version: 0.4.2044-standalone

**relevant settings**: my .vscode/settings.json uses the following options: rust-analyzer.linkedProjects, rust-analyzer.checkOnSave.allTargets, rust-analyzer.cargo.noDefaultFeatures, rust-analyzer.check.command

Basically, every version after 0.4.2040 doesn't work, at all. There are no relevant logs to it, nothing. Rust analyzer still shows warnings at the problems tab, but nothing in the editor itself shows up, no tips, no "go to declaration" buttons are working. 

I tried cargo cleaning all directories of all project, purging ~/.rustc and ~/.cargo, nothing. The only difference in the working rust analyzer version is that the ram usage is a bit higher, around a GB

**Comment by Szybet** [comment]
Someone suggested me that it simply ignores the setting rust-analyzer.linkedProjects because it creates the target directory only in the root directory, which may be the true cause of all of it, so I changed the tittle of the issue

**Comment by Veykril** [comment]
@davidbarsky

**Comment by fw-cc** [comment]
I am experiencing similar with this new version, code generated and included in the project is not being indexed in this recent update where it was before.

When viewing generated files I am also not being warned that the project is unindexed (unsure whether this behavior is intended).

I have written [an example](https://github.com/fw-cc/ra-build-index-error) (possibly overkill) of how this manifests with files generated by the [rust-protobuf](https://crates.io/crates/protobuf) crate.

rust-analyzer version: 0.3.2045

rustc version: rustc 1.79.0 (129f3b996 2024-06-10)

editor or extension: vscode, rust-analyzer version: 0.3.2045

relevant settings: "rust-analyzer.notifications.unindexedProject": true

**Comment by davidbarsky** [comment]
Right, okay:

1. For @fw-cc's issue, I tested against their minimal reproduction (thank you for providing it! it's not overkill and is *incredibly* helpful when debugging) and determined that https://github.com/rust-lang/rust-analyzer/pull/17650 is the cause, not https://github.com/rust-lang/rust-analyzer/pull/17246. I'll work on fixing that, as simply readding the previous match guard breaks the newly added test. `fw-cc`: you also don't need to enable `"rust-analyzer.notifications.unindexedProject": true`; that has been superseded by [#17246](https://github.com/rust-lang/rust-analyzer/pull/17246) and will be removed by https://github.com/rust-lang/rust-analyzer/pull/17395 later today.
2. I am unable to reproduce @Szybet's issue by setting `rust-analyzer.linkedProjects` to different Cargo.toml's in a Cargo workspace—I am seeing IDE functionality continue to work. Can you try providing a minimal reproduction of the behavior you're seeing?

**Comment by fw-cc** [comment]
Ah apologies for reporting it here and thank you very much for your work on these issues, glad the reproduction helped!

**Comment by ObsidianMinor** [comment]
@davidbarsky #17660 fixed this regression.
![image](https://github.com/user-attachments/assets/956a4a42-4c1e-480e-89f1-fc9e78eade5d)

**Comment by davidbarsky** [comment]
> @davidbarsky #17660 fixed the regression reported by @fw-cc.
> 
> ![image](https://github.com/user-attachments/assets/956a4a42-4c1e-480e-89f1-fc9e78eade5d)

I missed that PR, sorry about that!

**Comment by alex-haven** [comment]
Hello 👋 
We faced the same issue this morning, and fixed it by updating our paths from relative to absolute using the `${workspaceFolder}` variable:
```
"rust-analyzer.linkedProjects": [
-        "my-workspace/Cargo.toml",
+        "${workspaceFolder}/my-workspace/Cargo.toml",
]
```

**Comment by matthew-levan** [comment]
> Hello 👋 For @Szybet's issue, we faced the same thing this morning, and fixed it by updating our paths from relative to absolute using the `${workspaceFolder}` variable:
> 
> ```
> "rust-analyzer.linkedProjects": [
> -        "my-workspace/Cargo.toml",
> +        "${workspaceFolder}/my-workspace/Cargo.toml",
> ]
> ```

Unfortunately using `${workspaceFolder}` to declare absolute paths did not work for me on `macos-aarch64` with `v0.144.4`.

**Comment by andrewkmin** [comment]
Like @matthew-levan, I'm also running `macos-aarch64`. In my `.vscode/settings.json`, I tried to use both my standard linked projects path as well as the `${workspaceFolder}` fix, but to no avail. Using rust 1.71. Rolling back to `0.4.2037` restores functionality.

Appreciate the work y'all are doing and let me know if there's any more information I could provide.

**Comment by JosiahParry** [comment]
I am also encountering this issue today.

**Comment by matthew-levan** [comment]
Update: I used absolute paths (that don't rely on interpolation, i.e. `${workspaceFolder}`) and it works now.

**Comment by mcmah309** [comment]
I also randomly started encountering this issue on all versions I tried today (`0.4.2054 (pre-release)`,  `0.4.2037`, `0.3.2037`, `0.3.2053`, `0.3.2029`, `0.3.2020`) while using vscode.

project.workspace
```json
{
	"settings": {
		"rust-analyzer.linkedProjects": [
			"path/to/project/Cargo.toml",
                       ...
		],
	}
}
```
I switched using a `Cargo.toml` for the entire project
```toml
[workspace]
members = [
    "path/to/project",
    ...
]
```
> Note for paths in a workspace `Cargo.toml`, the ending `Cargo.toml` should not be added.

On `0.3.2053` everything seemed to work fine with this change.

**Comment by momotofu** [comment]
This fixed it for me:

```json
"lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "linkedProjects": ["/Users/my-username/path/to/Cargo.toml"]
      }
    }
  }
  ```

**Comment by Veykril** [comment]
@davidbarsky any updates on this? This does look like a rather annoying problem (just ran into this with the default rust-lang/rust config)

**Comment by davidbarsky** [comment]
> @davidbarsky any updates on this? This does look like a rather annoying problem (just ran into this with the default rust-lang/rust config)

I wasn't able to reproduce it (I'm still unable to...), but I realized that I made `ManifestOrProjectJson` take an `AbsPathBuf` instead of a `Utf8PathBuf`, which I think explains this regression. I'll put up a PR fixing this.

**Comment by davidbarsky** [comment]
Opened https://github.com/rust-lang/rust-analyzer/pull/17750.
