### ISSUE TITLE
proc-macro not expanded

### ISSUE THREAD

**Issue by ChimeWu** [rust-lang/rust-analyzer#17677]
![截图 2024-07-23 11-46-39](https://github.com/user-attachments/assets/fcdbd347-416c-4718-9ce3-4033a36b59d8)

**Comment by lnicola** [comment]
Do you get a warning icon in the status bar?

**Comment by ChimeWu** [comment]
![image](https://github.com/user-attachments/assets/5a27da96-c60a-47ec-aa45-e8edeb941829)

**Comment by lnicola** [comment]
You should upgrade to a newer toolchain, see #17662.

**Comment by ChimeWu** [comment]
thank you! solved. my toolchain was 1.72.0, it's too old
