### ISSUE TITLE
[VSCode] Request textDocument/semanticTokens/full/delta failed.

### ISSUE THREAD

**Issue by wmeints** [rust-lang/rust-analyzer#17678]
Rust analyzer panics when I open a code file. Resulting in the following error message in the output window:

```
[Error - 10:36:46 AM] Request textDocument/semanticTokens/full/delta failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
```

I tried reopening VSCode and editing a different file to see if the problem is specific to my code. I ended up with the same result in multiple files. 

**rust-analyzer version**: 

rust-analyzer version: 0.3.2045-standalone (4afe0d539 2024-07-21)

**rustc version**: (eg. output of `rustc -V`)

rustc 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: 

VSCode Version: 1.91.1 (user setup)
Extension Version: v0.3.2045

**relevant settings**: 

None

**Comment by Veykril** [comment]
Either needs a reproduction case or a backtrace for us to be able to do anything here

**Comment by wmeints** [comment]
I switched to the prerelease version of the extension `rust-analyzer version: 0.4.2046-standalone (329adb5ab 2024-07-22)`. And that version runs without any issues.
