### ISSUE TITLE
Regression: not autocompleting from files in `OUT_DIR` folder

### ISSUE THREAD

**Issue by amg98** [rust-lang/rust-analyzer#17684]
**rust-analyzer version**: 2024-07-22

**rustc version**: 1.79.0

**editor or extension**: Neovim

**relevant settings**: using default settings

**code snippet to reproduce**: 
https://github.com/amg98/gdextrust-repro

In latest rust analyzer version (2024-07-22) autocomplete is not working for source files generated in build time (e.g. located in `OUT_DIR` folder). Downgrading to version 2024-07-15 fixes the issue, so there should be a regression in latest version. Use the repo above to reproduce the issue (the  `Sprite2D` struct won't autocomplete in latest version, but it does in previous version)

**Comment by davidbarsky** [comment]
This has already been fixed by https://github.com/rust-lang/rust-analyzer/pull/17660; please consider using nightly until Monday's stable release if this is a blocker.
