### ISSUE TITLE
Don't use `--workspace` for build scripts

### ISSUE THREAD

**Issue by themighty1** [rust-lang/rust-analyzer#17696]
Please provide a config similar to `rust-analyzer.check.workspace` but for build scripts.
I need to be able to run only the build script of the current package and not the build scripts of the workspace deps. 

In my specific case, I have a workspace member A which is supposed to be compiled for "wasm32-unknown-unknown", whereas the rest of the workspace should be compiled to the native arch.

I'm already using ```"rust-analyzer.check.workspace": false``` but I still get errors from workspace build scripts.

**Comment by themighty1** [comment]
Seems like this PR was meant to do just what I asked https://github.com/rust-lang/rust-analyzer/pull/16510

But I empirically established that `--workspace` still gets passed to build scripts even with "rust-analyzer.check.workspace": false

**Comment by themighty1** [comment]
using rust=analyzer `0.3.2037-standalone` from vscode 1.91.1

**Comment by Veykril** [comment]
The config there serves a different purpose, mainly that of checking speed. Omitting the `--workspace` flag in buildscript wouldn't make sense, as then we will simply not run build-scripts and not build proc-macros for the project making r-a pretty much useless.

**Comment by themighty1** [comment]
ok, thanks for clarifying.
