### ISSUE TITLE
rust-analyzer loading one core forever

### ISSUE THREAD

**Issue by RocketRide9** [rust-lang/rust-analyzer#17694]
**rust-analyzer version**: rust-analyzer 1.79.0 (129f3b9 2024-06-10)

**rustc version**: rustc 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: Helix

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
These environment variables aren't set.

**repository link (if public, optional)**: it's a gnome app template from Builder with updated dependencies and added `lemmy_client` dependency: https://github.com/RocketRide9/for_ra_bug_report

**Description**: When using Helix, rust-analyzer loads one core forever. I found similar issue: https://github.com/rust-lang/rust-analyzer/issues/10715 , but it isn't very similar: i can run `cargo check` in separate terminal tab and it returns result almost instantly. I tried closing everything related to rust and running `rust-analyzer analysis-stats .`, but it never finishes. While RA is spinning, `cargo check` works fine in separate tab.

**Comment by alibektas** [comment]
Problem seems to be the rust-analyzer.sh file you have. Commenting the config key `rust-analyzer.server.path` in your `.vscode/settings.json` seems to solve the issue.

**Comment by Veykril** [comment]
Might also be https://github.com/rust-lang/rust-analyzer/issues/14522 or https://github.com/rust-lang/rust-analyzer/issues/8161
