### ISSUE TITLE
Lifetime causes associated type return value to fail to resolve

### ISSUE THREAD

**Issue by abrenneke** [rust-lang/rust-analyzer#17703]
**rust-analyzer version**: 0.3.2037-standalone (e9afba57a 2024-07-14)

**rustc version**: rustc 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: VS Code, extension version: 0.3.2045

**relevant settings**: N/A?

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

**code snippet to reproduce**: 
```rust
#![allow(dead_code)]
struct Container<T>(pub T);

trait Parse<T> {
    type Parsed;
}

impl<T> Parse<T> for Container<T> {
    type Parsed = T;
}

struct Value(usize);

// This one doesn't work
impl Value {
    pub fn parse<'a, T>(&self) -> T::Parsed
    where
        T: Parse<usize>,
    {
        unimplemented!()
    }
}

// This one does work
fn do_parse<'a, T>(_val: &usize) -> T::Parsed
where
    T: Parse<usize>,
{
    unimplemented!()
}

fn repro() {
    let value = Value(42);

    // {unknown}
    let val = value.parse::<Container<usize>>();
    let _43 = val + 1;

    // usize
    let val2: usize = value.parse::<Container<usize>>();
    let _43 = val2 + 1;

    // usize
    let val3 = do_parse::<Container<usize>>(&42);
    let _43 = val3 + 1;
}
```

Above is the most minimal I've been able to reduce the problem I'm running into. For some reason, the value of `val` is `{unknown}`, even though `cargo check` correctly validates it as a `usize`.

The key part is that the `'a` lifetime in the parse function (which isn't even used!) is what causes the value to be unresolved. Somehow.

**Comment by ShoyuVanilla** [comment]
I haven't bisected yet, but it seems to be fixed - `rust-analyzer 1.80.0 (05147895 2024-07-21)`
<img width="779" alt="issue_" src="https://github.com/user-attachments/assets/5f524c97-139b-4d97-a0e8-c00fb4f8bbb4">

**Comment by Veykril** [comment]
yep that was fixed

**Comment by abrenneke** [comment]
Bisected to #17747
