### ISSUE TITLE
Issue loading type data for arrow_array::ArrowPrimitiveType

### ISSUE THREAD

**Issue by Throne3d** [rust-lang/rust-analyzer#17704]
**rust-analyzer version**: `rust-analyzer version: 0.3.2045-standalone`

**rustc version**: `rustc 1.80.0 (051478957 2024-07-21)`

**editor or extension**: VSCode, extension version v0.3.2045

**relevant settings**: I specifically noticed this because it flagged as an error under `"rust-analyzer.diagnostics.experimental.enable": true`, but it seems to present, just more subtly, with all my rust-analyzer configs disabled: rust-analyzer doesn't seem to provide meaningful completions for the type when imported at this path.

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

I first noticed this with the `hash_one` method call when getting started looking at the Apache Datafusion codebase: rust-analyzer won't provide completion and documentation hovers for this `hash_one` method call (and, with the experimental diagnostics enabled, says the hash_one method doesn't exist, even though it passes `cargo check`): https://github.com/apache/datafusion/blob/fab7e238e8559bdb2e4e0449354f7efeccbc07a7/datafusion/common/src/hash_utils.rs#L118

**code snippet to reproduce**:

I think this is a successful (though a bit weird) minimization:
```rust
// [dependencies]
// arrow-array = "52.1.0"
fn func1<T>()
where T: arrow_array::ArrowPrimitiveType<Native = i16>,
{
    println!("{}", T::default_value());
}

fn main() {
    func1::<arrow_array::types::Int16Type>();
}
```

Here, this passes `cargo check` fine, and successfully compiles and outputs `0` when run, but shows no documentation hover for `T::default_value()` and (when enabled) the experimental check shows that the associated item doesn't exist. Based on the output of `analysis-stats`, I think something's going wrong with "MIR failed bodies" or "Body lowering" in rust-analyzer, but I couldn't investigate that in more detail:

```
$ ./rust-analyzer analysis-stats . 2>&1 | grep -v "perf counter"
Database loaded:     264.04ms, 12mb (metadata 159.28ms, 178kb; build 18.25ms, 10kb)
  item trees: 1
Item Tree Collection: 254.94µs, 33kb
  crates: 1, mods: 1, decls: 2, bodies: 2, adts: 0, consts: 0
Item Collection:     2.70s, 162mb
Body lowering:       328.05ms, 51mb
  exprs: 48, ??ty: 2 (4%), ?ty: 2 (4%), !ty: 0
  pats: 0, ??ty: 0 (100%), ?ty: 0 (100%), !ty: 0
Inference:           349.40ms, 11mb
MIR lowering:        920.54µs, 17kb
Mir failed bodies: 1 (50%)
Data layouts:        85.00ns, 0b
Failed data layouts: 0 (100%)
Const evaluation:    57.00ns, 0b
Failed const evals: 0 (100%)
Total:               3.38s, 225mb
```

Referencing the type as `arrow_array::types::ArrowPrimitiveType` instead of `arrow_array::ArrowPrimitiveType` seems to solve completions, documentation hovers, and the experimental diagnostic, so I think there's something about the import path (maybe import depth?) - `arrow_array` seems to `pub use array::*`, which itself has `use crate::types::*` (not public) and `pub use primitive_array::*`, the latter of which has `pub use crate::types::ArrowPrimitiveType` with the final `pub trait ArrowPrimitiveType` definition. Maybe there's some conflict due to the public and non-public imports of the same type here? Here's the analysis-stats output I get with the `::types::` path that RA provides hints for:

```
$ ./rust-analyzer analysis-stats . 2>&1 | grep -v "perf counter"
Database loaded:     208.97ms, 12mb (metadata 103.67ms, 178kb; build 18.08ms, 10kb)
  item trees: 1
Item Tree Collection: 222.25µs, 35kb
  crates: 1, mods: 1, decls: 2, bodies: 2, adts: 0, consts: 0
Item Collection:     2.63s, 162mb
Body lowering:       298.56ms, 51mb
  exprs: 48, ??ty: 0 (0%), ?ty: 0 (0%), !ty: 0
  pats: 0, ??ty: 0 (100%), ?ty: 0 (100%), !ty: 0
Inference:           329.07ms, 11mb
MIR lowering:        9.59ms, 40kb
Mir failed bodies: 0 (0%)
Data layouts:        168.00ns, 0b
Failed data layouts: 0 (100%)
Const evaluation:    55.00ns, 0b
Failed const evals: 0 (100%)
Total:               3.26s, 225mb
```

Please let me know if there's anything else I can do to help reproduce this!

**Comment by Veykril** [comment]
This has been reported before https://github.com/rust-lang/rust-analyzer/issues/14902, liekly caused by the globe exports 14930

**Comment by Throne3d** [comment]
Ooh, I see - sorry about the duplicate here!

It seems like the rustc behavior is expected based on https://github.com/rust-lang/rust/issues/95420, but I'm not entirely sure what the final logic is (last import takes precedence?) to know how to improve this here. Would reopening #14930 and trying to update it for the latest code make sense? Are there other plans to change the import resolution code like mentioned in https://github.com/rust-lang/rust-analyzer/pull/14930#issuecomment-1678639373?

**Comment by Veykril** [comment]
Well its obviously a bug we ought to fix, rebasing the PR would likely be fine, the changes aren't too big (though I do agree with the author there that the changes don't look great).

**Comment by Throne3d** [comment]
I've opened #17715 to hopefully solve this! I'm not at all familiar with the project's codebase, but I read through the contributing guide and development docs, then tried understanding the code and tests before pushing the change. I'm also in the Zulip if there's anything that would be useful to discuss there, but hopefully this is a quick win =)
