### ISSUE TITLE
Quick fix removing lifetime param not remove comma

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust-analyzer#17727]
**rust-analyzer version**: rustc 1.80.0 (051478957 2024-07-21)

**rustc version**: rust-analyzer 1.80.0 (05147895 2024-07-21)

**editor or extension**: Vim 9.1 coc-rust-analyzer

**code snippet to reproduce**: 
```rust
type Result<T> = std::result::Result<T, ()>;

fn foo() -> Result<'static, ()> { Ok(()) }

fn main() { }
```

**use quick fix**:
```rust
type Result<T> = std::result::Result<T, ()>;

fn foo() -> Result<, ()> { Ok(()) }

fn main() { }
```

**expect**:
```rust
type Result<T> = std::result::Result<T, ()>;

fn foo() -> Result<()> { Ok(()) }

fn main() { }
```

**Comment by Veykril** [comment]
That quickfix comes from `rustc`, so its a compiler bug that its proposed change does not include the `,` in the removal

**Comment by A4-Tacks** [comment]
Should I forward this issue to rustc?

**Comment by Veykril** [comment]
Yes that would be good
