### ISSUE TITLE
Use `` Generate impl for `Foo` `` excess backslash

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust-analyzer#17724]
**rust-analyzer version**: rust-analyzer 1.80.0 (05147895 2024-07-21)

**rustc version**: rustc 1.80.0 (051478957 2024-07-21)

**editor or extension**: Vim 9.1 coc-rust-analyzer

**relevant settings**: NONE

**code snippet to reproduce**: 
```rust
trait Ptr {
}

struct Foo<P>(P);

fn main() { }
```

input `` Generate impl for `Foo` `` on `Foo` into
```rust
trait Ptr {
}

struct Foo<P>(P);

impl<P> Foo<P> {\}

fn main() { }
```

about #16607

**Comment by Veykril** [comment]
This is a bug in your editor, try updating it it has likely been fixed there already
