### ISSUE TITLE
What about make 'inlay hints' default to 'offUnlessPressed'

### ISSUE THREAD

**Issue by diverger** [rust-lang/rust-analyzer#17721]
The current display style for the type inlay hints is too similar to the real type defines. And this feature is default on. Sometimes this brings some confusions. How about make it default off, and show them when necessary?

**Comment by alibektas** [comment]
If you are VSCode user you can set this through editor's settings. We generally want to have a feature visible to the user to make it more easily discoverable.

**Comment by diverger** [comment]
Yes, 

I'm a VSCode user. But a newbie to Rust and learning Rust. This indeed make me confused at first time. I can't distinct which is my code, and which is the 'virtual code' generated by this extension. I even thought this is a feature built into 'rust' itself. :) 

Just a suggestion.
