### ISSUE TITLE
type inference, inlayhint, and autocomplete no longer working for hecs world.get() ref since version 0.3.2029+

### ISSUE THREAD

**Issue by jestarray** [rust-lang/rust-analyzer#17734]
**rust-analyzer version**: rust-analyzer version: 0.3.2045-standalone [/home/a/.vscode-oss/extensions/rust-lang.rust-analyzer-0.3.2045-linux-x64/server/rust-analyzer]

**rustc version**: rustc 1.80.0 (051478957 2024-07-21)

**editor or extension**:  vscode on linux(have not tested on windows yet)

**code snippet to reproduce**: 
```rust
use hecs::{Entity, World};
fn main() {
    let mut world = hecs::World::new();
    let entity = world.spawn((0.0,));
    if let Ok(f) = world.get::<&mut f32>(entity) {
        dbg!(f);
    };
}

```
deps:
```toml
//Cargo.toml
[dependencies]
hecs = "0.10"
```
**Latest working working version: v0.3.2020**
![image](https://github.com/user-attachments/assets/7ecf4f83-5b3a-4786-b533-2afd4b43b09c)

Any version above `0.3.2020` does not show the inlayhint, typeinference, and autocomplete methods for the given type as shown above.
hecs info:
https://docs.rs/hecs/latest/hecs/struct.World.html#method.get
https://docs.rs/hecs/latest/hecs/trait.ComponentRef.html#associatedtype.Ref

**Comment by Veykril** [comment]
Typing ` world.get::<'_, &mut f32>(entity)` makes it work so we are messing up some indices here probably.

**Comment by Veykril** [comment]
```rs

fn main() {
    // fails
    let x = S.foo::<&()>();
    // works
    let x = S::foo::<&()>(&S);
}

struct S;

impl S {
    pub fn foo<'a, T: Trait<'a>>(&'a self) -> T::Proj {
        loop {}
    }
}

struct Wrap<'a, T>(T);
trait Trait<'a> {
    type Proj;
}
impl<'a, T> Trait<'a> for &'a T {
    type Proj = Wrap<'a, T>;
}

```
