### ISSUE TITLE
rust-analyzer fails with "error: config value `env` is not set"

### ISSUE THREAD

**Issue by shanebishop** [rust-lang/rust-analyzer#17739]
**rust-analyzer version**: 0.3.2053-standalone

**rustc version**: rustc 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: VSCode

**relevant settings**: `RUSTC_WRAPPER="$HOME/.cargo/bin/sccache"`

**repository link (if public, optional)**:

**code snippet to reproduce**: N/A

**environment**: WSL 2, Ubuntu 22.04 x86_64

### Error

When I open my workspace in VSCode, rust-analyzer doesn't show any red underlines for syntactically incorrect code. When I look at the output of rust-analyzer in the OUTPUT tab, I see this:
> 2024-07-29T18:56:36.485666Z ERROR Failed to discover cargo config env: cd "/home/shane/src/redacted" && RUSTC_BOOTSTRAP="1" RUSTUP_TOOLCHAIN="/home/shane/.rustup/toolchains/stable-x86_64-unknown-linux-gnu" "/home/shane/.cargo/bin/cargo" "-Z" "unstable-options" "config" "get" "env" failed, exit status: 101
> stderr:
> error: config value `env` is not set
>
>
> Stack backtrace:
>    0: anyhow::error::<impl anyhow::Error>::msg
>    1: project_model::utf8_stdout
>    2: project_model::env::cargo_config_env
>    3: project_model::workspace::ProjectWorkspace::load
>    4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
>    5: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
>    6: core::ops::function::FnOnce::call_once{{vtable.shim}}
>    7: std::sys_common::backtrace::__rust_begin_short_backtrace
>    8: core::ops::function::FnOnce::call_once{{vtable.shim}}
>    9: std::sys::pal::unix::thread::Thread::new::thread_start
>   10: \<unknown\>
>   11: \<unknown\>

In case it is relevant, here is the `Cargo.toml` in the root of my workspace:
```toml
[workspace]
resolver = "2"
members = [ "hydra", "li_engine", "lich"]
exclude = [ "c_library_bindings" ]

[profile.release]
opt-level = "z"
strip = true
lto = true
#codegen-units = 1
```

**Comment by SebastianTianying** [comment]
I am having the same error. seems like an issue with the latest update. Installing previous versions in VSCode fixed it for me.

**Comment by Systemcluster** [comment]
As a workaround you can simply add an empty `env` section to your `.cargo/config.toml`:

```toml
[env]
```

**Comment by alibektas** [comment]
Caused by #17697

**Comment by martin-fs** [comment]
I tried the `[env]` workaround and it didn't seem to fix things for me: the "config value env is not set" errors went away, but I couldn't navigate my source, even after restarting the server and VSCode a couple of times. I switched to a version from a month ago and things started working again immediately. 🤷

**Comment by alibektas** [comment]
> I tried the `[env]` workaround and it didn't seem to fix things for me: the "config value env is not set" errors went away, but I couldn't navigate my source, even after restarting the server and VSCode a couple of times. I switched to a version from a month ago and things started working again immediately. 🤷

Would you mind sharing some details ? rustc version rust-analyzer version etc. I am trying to come up with a test case but couldn't make that happen :)

**Comment by alibektas** [comment]
I am working on this until someone who knows what they are doing takes over :smiley:

**Comment by alibektas** [comment]
This is more than enough. Thanks!

**Comment by alibektas** [comment]
I can also confirm that the problem is elsewhere. I can reproduce the error but everything works just fine. Without a repro it is hard for me track it down. Sorry!

**Comment by Veykril** [comment]
Note this error is harmless. The only reason this happens now is that we log the failure case unconditionally which we shouldn't do. Likely suffices to turn the tracing span from error to debug

**Comment by Veykril** [comment]
> I tried the `[env]` workaround and it didn't seem to fix things for me: the "config value env is not set" errors went away, but I couldn't navigate my source, even after restarting the server and VSCode a couple of times. I switched to a version from a month ago and things started working again immediately. 🤷

That's a different issue then

**Comment by jhunterkohler** [comment]
I'm having essentially the same issue with the extension. When I tried adding the `[env]` variable to `~/.cargo/config.toml`, the error stopped being displayed in the extension output. However, the output was then completely empty, and no intellisense worked. So, I can only assume that there is some other issue here, but I don't know if its related.

**Comment by ievr** [comment]
Having same issue on Win10 VSCode as well. 
(Thank you for the bug report as it saved me a lot of time.)

**Comment by sirasistant** [comment]
[This repository](https://github.com/AztecProtocol/aztec-packages) is also affected by this issue. I cannot navigate the source on the last release (or prerelease) channel version, but I can in v0.3.2037

**Comment by alibektas** [comment]
This issue will be closed but for those of you who can't use some of the rust-analyzer features. This is **not** related to that. I will be looking into what the actual cause for that is elsewhere. I will be posting a reference to the issue once I figured out the main cause. :wave:

**Comment by Veykril** [comment]
For dep cycles see https://github.com/rust-lang/rust-analyzer/issues/14167
