### ISSUE TITLE
`None` treated like variable name in Option match

### ISSUE THREAD

**Issue by lewoberst** [rust-lang/rust-analyzer#17759]
**rust-analyzer version**: rust-analyzer 0.3.2053-standalone

**rustc version**: rustc 1.79.0

**editor or extension**: neovim v0.9.5 (rust-analyzer installed by mason plugin, running on a debian stable installation)

**code snippet to reproduce**: 
```rust
fn main() -> Result<(), ()> {
    let v = Some(false);                                                                             
    let _i = match v {
        Some(true) => 1,
        Some(false) => 2,
        None => 3,
    };
    Ok(())
}
```

"Variable `None` should have snake_case name, e.g. `none` [non_snake_case]" in line 6.

rust-analyzer prints that as a warning message for every `Option` match, also if `None` occurs within tuples. It doesn't make any sense to me. Other than that, rust-analyzer seems to be working fine as far as I can tell.

**Comment by lnicola** [comment]
Can't reproduce, does "Go to Definition" on `Some` work?

**Comment by lewoberst** [comment]
I assume you mean "Go to definition" on `None`? Doesn't move the cursor, no (and neither on `Some`).

![image](https://github.com/user-attachments/assets/d9659485-7ffc-4c45-bd29-d4544b2dafe2)

**Comment by lnicola** [comment]
Sounds like you might be missing `rust-src`, can you check?

**Comment by lewoberst** [comment]
You are right and installing `rust-src` manually fixed it.

I would have expected rust-analyze to complain in a more direct, obvious way though. Also the documentation states "rust-analyzer will attempt to install it automatically", this did either not happen or not work and rust-analyzer wouldn't complain.

Should handling of that error be improved? Otherwise this issue can be closed. Thanks for helping out.

**Comment by cxw620** [comment]
I met with the same issue though with `rust-src` installed, and I fix it by adding the following to env:

```sh
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
```

From: https://gist.github.com/dearmark/90a7da8904111466b8b2c47d1678485b

**Comment by lnicola** [comment]
> Also the documentation states "rust-analyzer will attempt to install it automatically", this did either not happen or not work

We run `rustup component add rust-src`, and it works fine for me. You didn't mention how you installed Rust. But Debian 12 doesn't come with 1.79. Did you use the standalone installer?

> Should handling of that error be improved?

We should report that, see https://github.com/rust-lang/rust-analyzer/blob/c9109f23de57359df39db6fa36b5ca4c64b671e1/crates/project-model/src/sysroot.rs#L479:

![image](https://github.com/user-attachments/assets/026275a5-1f0c-4187-96c5-0048b7a49c34)

But I think that's using an LSP extension, so it might not work with other clients. I'll file this as a follow-up issue.

> I met with the same issue though with rust-src installed, and I fix it by adding the following to env:

We do the same thing at https://github.com/rust-lang/rust-analyzer/blob/c9109f23de57359df39db6fa36b5ca4c64b671e1/crates/project-model/src/sysroot.rs#L436, you shouldn't need to do anything.

**Comment by lnicola** [comment]
@ferologics does your project have a `rust-toolchain.toml` file? Does it happen in a new project?

**Comment by lnicola** [comment]
What does `rust-toolchain.toml` contain, and does that toolchain have `rust-src` installed?

**Comment by Crispy13** [comment]
> the issue does not reproduce in a fresh project cargo crate. i went ahead and reinstalled my toolchain, now the issue is gone. so maybe something went wrong during the first update. thanks for the quick followup [@lnicola](https://github.com/lnicola)

I have the same issue. 
Would you tell me how to solve it?

`rustup toolchain uninstall stable`
`rustup toolchain install stable`

is this it?

**Comment by lnicola** [comment]
` rustup toolchain install stable --component rust-src`

**Comment by xiaomin1123** [comment]
I have the same issue. After I re-installed resutup toolchain and rust-src, the problem is not fixed.
![Image](https://github.com/user-attachments/assets/2a898616-2e80-48f4-ac6a-7998f7632a3d)
 Here's my enviroment,

Rustc: 1.82.0
Rustup-toolchain: stable-x86_64-pc-windows-gnu
Editor: Vscode + rust-analyzer v0.3.2172

The default sysroot src of rust-analyzer
![Image](https://github.com/user-attachments/assets/0cd561f6-5679-4de6-b633-76e87b937df3)

I tried to edit the path but it didn't help. I don't see any error/warning from rust analyzer client/server. Is there a way to figure out if rust-analyzer loads the rustlib correctly?

**Comment by lnicola** [comment]
@xiaomin1123 do you have a `rust-toolchain.toml` file? Does it work in a new project? Does "Go to definition" work on `String`?

**Comment by xiaomin1123** [comment]
No, there's no rust-toolchain.toml in the project. It didn't work in new project either.

I created a new project as below,
![Image](https://github.com/user-attachments/assets/12ac46bb-e4fb-4c5a-87ec-5fab42d94a40)

The status of rust_analyzer
![Image](https://github.com/user-attachments/assets/0b477348-ebef-4777-ab1f-694342522f7c)

And the code,
![Image](https://github.com/user-attachments/assets/fd19dea6-453d-4db5-950c-97cab0c941ee)

It says variable x is type unknown and  None is not a type,

![Image](https://github.com/user-attachments/assets/7944b0db-6628-4cee-9dca-7357f94054f3)
![Image](https://github.com/user-attachments/assets/fe2a6635-e999-4548-b4d9-34d4e02375f2)

**Comment by xiaomin1123** [comment]
And "go to definition" not work on String, I can not click on a String to pop out code definition page. When I click at println!, it will open macros.rs, but there's no response when click at String
![Image](https://github.com/user-attachments/assets/a614779c-236c-4c88-b049-4c5532ce08ec)

**Comment by tdomhan** [comment]
I have the same problem in VSCode using rust nightly (rustc 1.84.0-nightly (143ce0920 2024-11-10). There is no `rust-toolchain.toml`.

**Comment by lnicola** [comment]
@tdomhan did you try `rustup component add rust-src`?

**Comment by tdomhan** [comment]
Yeah, rust-src was already there as a component. This must be related to the nightly version as:
```
  "rust-analyzer.server.extraEnv": {
    "RUSTUP_TOOLCHAIN": "stable" 
  },
```
resolved the issue for me.

**Comment by xiaomin1123** [comment]
In this post [](https://github.com/rust-lang/rust-analyzer/issues/18455), it mentioned rustc 1.82 stdlib needs extra dependencies to let rust analyzer to work properly. But I still don't find a way to let cargo download them.

**Comment by flodiebold** [comment]
This should do the trick if you want the stdlib dependencies to be downloaded in advance:
```sh
cd $(rustc --print sysroot)/lib/rustlib/src/rust/library && __CARGO_TEST_CHANNEL_OVERRIDE_DO_NOT_USE_THIS=nightly cargo metadata
```
But RA will do this automatically, so it should only be useful if you need to automatically download everything you need to work offline.

**Comment by xiaomin1123** [comment]
@flodiebold Thank you for the suggestion. I downloaded the metadata of std library failed. It requires a nightly version. Does it mean I need to install a nightly toolchain?

![Image](https://github.com/user-attachments/assets/32c99fe3-90c0-477d-aa29-707b7559cbec)
![Image](https://github.com/user-attachments/assets/6db0d87b-293b-4499-9569-832ab9e23640)

It's cuased by the 'public dependency' feature required by std.
![Image](https://github.com/user-attachments/assets/55ef430d-7346-4791-9c6b-77c0e4037bf8)

**Comment by xiaomin1123** [comment]
After I installed nightly toolchain nightly-x86_64-pc-windows-gnu and updated metadata by `Cargo +nightly metadata`, now RA works.
![Image](https://github.com/user-attachments/assets/e6296ab3-ed0f-4188-951a-7559bf8d661d)

So, RA needs nightly version support?

**Comment by darichey** [comment]
You must set `__CARGO_TEST_CHANNEL_OVERRIDE_DO_NOT_USE_THIS=nightly`

**Comment by xiaomin1123** [comment]
Uh, got it. Thank you.

**Comment by davidmpc** [comment]
> 如果您希望提前下载 stdlib 依赖项，那么这应该可以解决问题：
> 
> cd $(rustc --print sysroot)/lib/rustlib/src/rust/library && __CARGO_TEST_CHANNEL_OVERRIDE_DO_NOT_USE_THIS=nightly cargo metadata
> 但是 RA 会自动执行此操作，因此只有当您需要自动下载离线工作所需的一切时它才有用。



> This should do the trick if you want the stdlib dependencies to be downloaded in advance:
> 
> cd $(rustc --print sysroot)/lib/rustlib/src/rust/library && __CARGO_TEST_CHANNEL_OVERRIDE_DO_NOT_USE_THIS=nightly cargo metadata
> But RA will do this automatically, so it should only be useful if you need to automatically download everything you need to work offline.

After I upgraded Rust, rust-analyzer couldn't resolve String and closure parameters in my VS Code, so it can't jump to some definitions. This command solved the problem.

**Comment by Crispy13** [comment]
> This should do the trick if you want the stdlib dependencies to be downloaded in advance:
> 
> cd $(rustc --print sysroot)/lib/rustlib/src/rust/library && __CARGO_TEST_CHANNEL_OVERRIDE_DO_NOT_USE_THIS=nightly cargo metadata
> But RA will do this automatically, so it should only be useful if you need to automatically download everything you need to work offline.

I don't know why, but `rustup component remove rust-src && rustup component add rust-src` did not work, but this worked.

**Comment by tamird** [comment]
I'm seeing this in the Linux kernel `macros` crate (but not elsewhere). e.g. [this line](https://github.com/torvalds/linux/blob/9946eaf552b194bb352c2945b54ff98c8193b3f1/rust/macros/module.rs#L18).

My [rust-project.json](https://gist.github.com/tamird/d2c54d6bfcf0e841d670c5430689142e). Note I'm using an out of tree build, which might be a contributing factor.

**Comment by ChayimFriedman2** [comment]
@tamird It looks like `macros` doesn't have a dependency on `core`.

**Comment by youngjin-create** [comment]
> Yeah, rust-src was already there as a component. This must be related to the nightly version as:
> 
> ```
>   "rust-analyzer.server.extraEnv": {
>     "RUSTUP_TOOLCHAIN": "stable" 
>   },
> ```
> 
> resolved the issue for me.

Thanks. I also encountered this issue exclusively in VS Code, and `cargo check` worked just fine. Adding this to my `.vscode/settings.json` resolved the problem for me.

**Comment by therealdannzor** [comment]
Encountered on [zed](https://github.com/zed-industries/zed) `0.176.3` on macOS `15.3.1` M3 Pro, using `rust-analyzer`. 

Been having this bug bugging me for a week or so now.

**Comment by dankirkham** [comment]
Encountered on neovim 0.9.5 on Ubuntu 24.04 using rust-analyzer, with [coc-rust-analyzer](https://github.com/fannheyward/coc-rust-analyzer) 0.81.0

**Comment by cxw620** [comment]
This issue has come back since the rencent RA and Rust nightly version, any idea?

RA: 0.4.2437
rustc 1.88.0-nightly (d7ea436a0 2025-04-24)
