### ISSUE TITLE
End of central directory record signature not found. Either not a zip file, or file is truncated.

### ISSUE THREAD

**Issue by alanwilter** [rust-lang/rust-analyzer#17760]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
0.4.2057

**rustc version**: (eg. output of `rustc -V`)
rustc 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)

VScode 

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:46.768Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

I can't install pre-release version `0.4.2057`, Vscode log shows:
`End of central directory record signature not found. Either not a zip file, or file is truncated.`

**Comment by lnicola** [comment]
Works fine for me, how did you install it? Using the Code UI, or by downloading the VSIX?

![image](https://github.com/user-attachments/assets/a3205231-f68d-4fe1-beb6-cc34c9ad0d99)

**Comment by alanwilter** [comment]
At first, I was just trying to "Update". Then I removed and installed the release version via VScode Extension tab:
<img width="802" alt="Screenshot 2024-08-01 at 11 14 02" src="https://github.com/user-attachments/assets/b0f27ce3-7811-487e-bf1c-7d591099faad">
Now, if I try the "Switch to pre-release", I get that error. Until `v0.4.2056` it was all fine.
However, when I tried to install from the `vsix` file, the issue disappeared.
I think we can close this ticket then.

**Comment by lnicola** [comment]
Not sure what to say, https://marketplace.visualstudio.com/_apis/public/gallery/publishers/rust-lang/vsextensions/rust-analyzer/0.4.2057/vspackage?targetPlatform=darwin-arm64 looks like a valid archive:

> No errors detected in compressed data of rust-lang.rust-analyzer-0.4.2057@darwin-arm64.vsix.
