### ISSUE TITLE
(New?) Panics inside of Chalk

### ISSUE THREAD

**Issue by davidbarsky** [rust-lang/rust-analyzer#17767]
**rust-analyzer version**: rust-analyzer version: 0.0.0 (f149dc5029 2024-08-01) [/Users/dbarsky/.cargo/bin/rust-analyzer]

**rustc version**: (eg. output of `rustc -V`): rustc 1.82.0-nightly (28a58f2fa 2024-07-31)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable): VS Code, but also occurs when running `rust-analyzer scip`.

I've been seeing [some panics in rust-analyzer recently](https://gist.github.com/davidbarsky/24b6144a9831466e17f586d86df128af) but I don't have a minimal reproduction yet. What's _especially_ weird is that opening the [same file](https://github.com/facebook/buck2/blob/77136e97444ec3cbcd3d166a6e12d0a615490fa4/app/buck2_bxl/src/bxl/starlark_defs/type_names.rs#L4) with the same rust-analyzer binary only causes panics when used with `rust-project.json`, not Cargo.

Any tips for figuring out what's causing the crash? I imagine I'd want to log the type/trait that causes this crash, but anything beyond that?

**Comment by davidbarsky** [comment]
I'm seeing the crash on a closed-sourced, CXX-using type called "IdentityRef". Its (simplified) definition is:

```rust
pub type IdentityRef<'a> = &'a ffi::OpaqueIdentity;

mod ffi {
    #[namespace = "infrasec::authorization"]
    extern "C++" {
        #[cxx_name = "Identity"]
        type OpaqueIdentity;
    }

    #[namespace = "rust::identity"]
    unsafe extern "C++" {
        include!("common/rust/identity/identity.h");

        type Identity = crate::identity::Identity;
        type IdentityRef<'a> = crate::identity::IdentityRef<'a>;
    }
}
```

I'm _little_ suspicious of https://github.com/rust-lang/rust-analyzer/pull/17530.

**Comment by Veykril** [comment]
> What's especially weird is that opening the [same file](https://github.com/facebook/buck2/blob/77136e97444ec3cbcd3d166a6e12d0a615490fa4/app/buck2_bxl/src/bxl/starlark_defs/type_names.rs#L4) with the same rust-analyzer binary only causes panics when used with rust-project.json, not Cargo.

This does sound very odd

**Comment by davidbarsky** [comment]
> > What's especially weird is that opening the [same file](https://github.com/facebook/buck2/blob/77136e97444ec3cbcd3d166a6e12d0a615490fa4/app/buck2_bxl/src/bxl/starlark_defs/type_names.rs#L4) with the same rust-analyzer binary only causes panics when used with rust-project.json, not Cargo.
> 
> 
> 
> This does sound very odd

I figured it out: the Cargo-powered build is a subset of the Buck-powered build, as the Buck-powered build pulls in a bunch of closed-source, [cxx](https://cxx.rs/)-using Rust libraries that bind to C++ libraries. I have _extremely_ high confidence that something in the (closed source, but relatively simple...) aforementioned `Identity` library is the cause of the crash here.

**Comment by darichey** [comment]
I found a minimal repro for this one, it's the extern types:
```
extern "C" {
    type Foo<T>;
}

fn f() -> Foo {}
```
