### ISSUE TITLE
Misinterpreting second generic as argument type in method

### ISSUE THREAD

**Issue by s7tya** [rust-lang/rust-analyzer#17764]
When a struct's method has two generics and an unused lifetime specifier, if Option<SomeType> is provided as the second generic value and the actual argument has the same type as SomeType, rust-analyzer mistakenly treats the second generic as the argument type, causing an error.

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) 
0.3.2053-standalone (fd74511f3 2024-07-28)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.80.0 (051478957 2024-07-21)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)
v0.3.2053

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))
https://github.com/rust-lang/rustc-perf/blob/753d3025846407730ef3ab461e7d9fb06cff9336/database/src/pool/postgres.rs#L778

**code snippet to reproduce**: 
```rust
struct A;

impl A {
    pub fn func<'a, I, T>(&self, _: I) {}
}

fn main() {
    A {}.func::<_, Option<i32>>(5);
}
```

**Comment by Veykril** [comment]
This likely got fixed by https://github.com/rust-lang/rust-analyzer/pull/17747

**Comment by s7tya** [comment]
Ahh, I didn't notice that. Thank you so much!
