### ISSUE TITLE
missing expander rust-analyzer (macro-error)

### ISSUE THREAD

**Issue by LakhsmikanthD** [rust-lang/rust-analyzer#17777]
Hey Team, 

I have started noticing a `missing expander` error in VSCode’s Rust Analyzer since August 2nd, which was not an issue before. The code compiles without any problems. Could you help me fix this error?

VS code settings

```
	"settings": {
		"rust-analyzer.server.path": "~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer",
		"rust-analyzer.diagnostics.disabled": [
			"unresolved-proc-macro"
		],
		"rust-analyzer.cargo.buildScripts.overrideCommand": [
			"makers",
			"check",
			"--message-format=json"
		]
	},
```

**Example code:**

```
use async_trait::async_trait;

#[async_trait]
pub trait MyAsyncTrait {
    async fn do_something(&self, value: u32) -> String;
}

pub struct MyStruct;

#[async_trait]
impl MyAsyncTrait for MyStruct {
    async fn do_something(&self, value: u32) -> String {
        tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
        format!("Processed value: {}", value)
    }
}

#[tokio::main]
async fn main() {
    let my_struct = MyStruct;
    let result = my_struct.do_something(42).await;
    println!("{}", result);
}
```

![Screenshot 2024-08-03 at 2 46 19 PM](https://github.com/user-attachments/assets/3205c952-a94e-43b5-83c4-aaf42d6fff92)

**Comment by Veykril** [comment]
what is `makers`

**Comment by LakhsmikanthD** [comment]
> what is `makers`

https://sagiegurari.github.io/cargo-make/api/makers/index.html
https://github.com/sagiegurari/cargo-make

**Comment by Veykril** [comment]
So, this error is a bit odd. It basically means your build step didn't return any proc-macros, so likely your `makers` thing there is not doing what cargo would be doing / reporting.

I also don't think this is a new issue for you given you had "unresolved-proc-macro" diagnostics disabled, which were the diagnostic before (that diagnostic got merged into the one you see now)

**Comment by LakhsmikanthD** [comment]
> So, this error is a bit odd. It basically means your build step didn't return any proc-macros, so likely your `makers` thing there is not doing what cargo would be doing / reporting.
> 
> I also don't think this is a new issue for you given you had "unresolved-proc-macro" diagnostics disabled, which were the diagnostic before (that diagnostic got merged into the one you see now)
> 
> Edit: yes, if I set the build command to `echo` which does nothing but succeed I also get the `missing expander` error, so your `makers` invocation here is the problem. I don't know cargo make so I can't help you with that.

I updated the `rust-analyzer.cargo.buildScripts.overrideCommand` from `makers` to `cargo`, and the issue is resolved.

**Comment by etheriord** [comment]
Got the same problem, currently going through the tutorial on Bevy 0.10.0, yesterday everything was fine, today while it compiles, the #[derive(Component)] lines were red, and after restarting VSC, also the structs below became red. I reverted to 1 month old version and now again only the "derive" lines are red. Restarted VSC again, no change.

**Comment by nole2701** [comment]
> Got the same problem, currently going through the tutorial on Bevy 0.10.0, yesterday everything was fine, today while it compiles, the #[derive(Component)] lines were red, and after restarting VSC, also the structs below became red. I reverted to 1 month old version and now again only the "derive" lines are red. Restarted VSC again, no change.

some of my derive lines have always been red but they worked anyways so it was just annoying to look at. But as of today everything became red so that was actually annoying. Had to revert.

**Comment by Veykril** [comment]
Please open a new issue with the concrete errors you are getting and any relevant configurations set

**Comment by renatoliveira** [comment]
rustc at 1.73 and following the example of the [`clap` crate](https://docs.rs/clap/latest/clap/) also results in this issue. Literally copying the sample code in that project's page shows the error described in this issue.
