### ISSUE TITLE
Complete type name as local name in pattern position

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#17780]
```rs
struct Directory {}
let $0 = Directory {};
```
I feel like proposing `directory` would be quite helpful at times.

That is, when completing a (top level) pattern binding and the corresponding type is an ADT (after stripping references), we should propose a lower snake cased version ADTs name.

**Comment by roife** [comment]
Should we complete within the `match` arms? Although it seems a bit odd for me (i.e. suggesting `e` here):

```rust
enum E { A, B }
let e: E;
match e {
  $0
}
```

**Comment by Veykril** [comment]
I'd say `let` statements and params make the most sense for this

**Comment by roife** [comment]
We can reuse `ide_assist::utils::suggest_name`. Would it be ok if I move it to the `hir` crate so that all `ide-xxx` crates can use it?

**Comment by Veykril** [comment]
you can move it into `ide-db` which all of them access
