### ISSUE TITLE
Unable to resolve path for rust-analyzer, but ok for rust !

### ISSUE THREAD

**Issue by Alphapage** [rust-lang/rust-analyzer#17790]
Hello,
I'm trying to run .nrs file which is "nano" rust: a kind of subset of rust with limited syntax.

```
#[path = "./nanors/nano.nrs"]
mod nano;
```

The problem is that rust-analyzer failed to discover the file path probably because of the file extension and I get `unresolved module, can't find module file` error, but it is running perfectly if I compile into rust.
If I replace the extension with `.rs`, I get intellisense in vscode.

Why doesn't rust-analyzer follow rust compiler ? It must accept any filepath extension like rust and parse the file as usual.
I use the last rust-analyzer version in vscode and the last rust version.

Thank you in advance for your answers.

**Comment by davidbarsky** [comment]
It's a an easy solution to only accept perform IDE functionality on `.rs` files; we'd prefer not opportunistically parse the code as Rust.

**Comment by Veykril** [comment]
For context, this is a shortcoming of our VFS which only loads up `.rs` and `.toml` files right now
