### ISSUE TITLE
Build cache invalidated due to differences in `PATH` environment variable

### ISSUE THREAD

**Issue by frozenlib** [rust-lang/rust-analyzer#17807]
When the build script is executed, there is a difference in the `PATH` environment variable depending on whether it is invoked from:

**When invoked from Windows Terminal, VSCode Terminal, or VSCode's `tasks.json`:**
The `PATH` environment variable has `C:\Program Files\PowerShell\7` added at the beginning.

**When invoked from rust-analyzer in VSCode:**
The `PATH` environment variable does not have `C:\Program Files\PowerShell\7` added at the beginning.

Due to this difference, the build script that sets `cargo:rerun-if-env-changed=PATH` is having its cache invalidated, leading to slower builds.

I confirmed that this issue occurs with the `zstd-sys` crate, but since the `cc` crate, which is used by this crate, is the one setting `rerun-if-env-changed`, I believe other crates using the `cc` crate might be experiencing the same problem.

----
**rust-analyzer version**: 0.3.2062-standalone (c9109f23d 2024-08-04) 

**rustc version**: rustc 1.80.0 (051478957 2024-07-21)

**editor or extension**: VSCode 1.92.0 ( rust-analyzer extesnion v0.3.2062)

```
Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z (5 days ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

**code snippet to reproduce**: 

1. Initialize the project with `cargo init` and add the following content to `Cargo.toml`:

```toml
[dependencies]
zstd = "0.13.2"
```

2. Build the project by running `cargo build` from the VSCode terminal.

3. Add a comment to `main.rs`, making it look like this:

```rust
fn main() {
    println!("Hello, world!");
    // This is a comment
}
```

4. Place the cursor before the beginning of the comment line, and press `Ctrl+Space` to display the completion suggestions from rust-analyzer.

5. Next, run `cargo build --verbose` from the VSCode terminal to rebuild the project.

As shown below, a change in the `PATH` environment variable is detected, invalidating the `zstd-sys` cache, resulting in an unnecessary rebuild.

```
Fresh jobserver v0.1.32
Fresh cc v1.1.7
Fresh pkg-config v0.3.30
Dirty zstd-sys v2.0.13+zstd.1.5.6: the env variable PATH changed
Compiling zstd-sys v2.0.13+zstd.1.5.6
...
```

If the rust-analyzer extension is disabled, changing `main.rs` and running `cargo build --verbose` will not cause `zstd-sys` to be rebuilt.

```
Fresh jobserver v0.1.32
Fresh cc v1.1.7
Fresh pkg-config v0.3.30
Fresh zstd-sys v2.0.13+zstd.1.5.6
...
```

**Comment by Veykril** [comment]
Sounds like we have an env mismatch between the env that we spawn the server with and the env that a task is run with within VSCode, though this specific difference is a bit odd

**Comment by milenkovicm** [comment]
I can confirm the same behaviour on macos as well, setting `"rust-analyzer.checkOnSave": false` helps with the issue.

**Comment by Veykril** [comment]
Is this a new regression here? If yes can you tell since which release, this week?

**Comment by Veykril** [comment]
> The `PATH` environment variable has `C:\Program Files\PowerShell\7` added at the beginning.

This is also rather weird, r-a never adds to the `PATH` ...

**Comment by milenkovicm** [comment]
It looks like regression, also note the issue is not present on linux

**Comment by lnicola** [comment]
Did you configure Code to use PSH as the terminal?

**Comment by milenkovicm** [comment]
it might not be PATH related, for me it looks like variable state is not preserved. it get triggered by https://github.com/gyscos/zstd-rs/blob/d698082588384693d4dfe726676187c8213c1b19/zstd-safe/zstd-sys/build.rs#L249

**Comment by lnicola** [comment]
@milenkovicm where did you set `ZSTD_SYS_USE_PKG_CONFIG`?

**Comment by milenkovicm** [comment]
> @milenkovicm where did you set `ZSTD_SYS_USE_PKG_CONFIG`?

no

**Comment by milenkovicm** [comment]
ok, the issue might be that I had extra variables in my settings.json

```
// "rust-analyzer.cargo.extraEnv": {
//   "MACOSX_DEPLOYMENT_TARGET": "X"
// },
// "rust-analyzer.check.extraEnv": {
//   "MACOSX_DEPLOYMENT_TARGET": "X"
// },
// "rust-analyzer.server.extraEnv": {
//   "MACOSX_DEPLOYMENT_TARGET": "X"
// },
```

removing them from configuration does not trigger re-build ...

**Comment by cry-inc** [comment]
I am also affected by this, because of a dependency to the ring crate, which also rebuilds when PATH changes.

For me the problem goes away when disabling rust-analyzer, but since thats not an option I tried and found an workaround: Just tell it to use a different build folder. I did this by adding this entry to the VS Code settings.json:

    "rust-analyzer.server.extraEnv": {
        "CARGO_TARGET_DIR": "./target_ra"
    }

This will of double the amounts builds and build files on disk, but it seems to the conflicts between the rust-analyzer builds and the normal terminal builds.

**Comment by frozenlib** [comment]
> Is this a new regression here? If yes can you tell since which release, this week?

I'm not sure when this issue first started occurring.
As a test, I specified an older version of the executable (`rust-analyzer version: 0.3.1791-standalone (9db515503 2024-01-01)`) in the `rust-analyzer.server.path` setting in VSCode's `settings.json`, but the cache was still invalidated in the same way.

> Did you configure ~Code~ Terminal to use PSH as the shell?

The rebuild occurred when using PowerShell in both Windows Terminal and VSCode's terminal.

After trying other situations, it appears that rebuilds occur between the following groups, while no rebuilds occur within the same group:

*A*
- `cargo build` in Command Prompt on Windows Terminal
- rust-analyzer in VSCode launched using the same method as that Windows Terminal
- rust-analyzer in VSCode launched from that Windows Terminal

*B*
- `cargo build` in PowerShell on Windows Terminal
- rust-analyzer in VSCode launched from that Windows Terminal

*C*
- `cargo build` in VSCode's Command Prompt terminal
- `cargo build` in VSCode tasks with `"type": "process"`

*D*
- `cargo build` in VSCode's PowerShell terminal
- `cargo build` in VSCode tasks with `"type": "shell"`

It appears that PowerShell changes the `PATH` environment variable.
Although the `PATH` environment variables for "A and C" and "B and D" seem to be the same when VSCode and Windows Terminal are launched in the same way, it's unclear why the cache is still invalidated.

**Comment by Veykril** [comment]
Ye this sounds like a powershell issue to me, not really rust-analyzer. The problem here is your cargo commands and VSCode not sharing the same environment (due to powershell modifying it).

You could probably set
```json

    "rust-analyzer.cargo.extraEnv": {
        "PATH": "C:\Program Files\PowerShell\7;${env:PATH}"
    },
```
in your vscode settings, that might be an easy fix for you here

**Comment by milenkovicm** [comment]
I don't use powershell, nor windows, but the issue is there, the issue is gone when I remove env variables from `extraEnv` (even the env variable is set in profile for all shells. 

is there a chance that when RA runs `cargo check` it starts the shell without reading `.profile` ?

**Comment by frozenlib** [comment]
> ```
> "rust-analyzer.cargo.targetDir": true
> ```
> 
> This will of double the amounts builds and build files on disk, but it seems to solve the conflicts between the rust-analyzer builds and the normal terminal builds.

I also noticed that using that setting made incremental builds much smoother.

> You could probably set
> 
> ```json
>     "rust-analyzer.cargo.extraEnv": {
>         "PATH": "C:\Program Files\PowerShell\7;${env:PATH}"
>     },
> ```
> 
> in your vscode settings, that might be an easy fix for you here


The `${env:PATH}` wasn't expanding in the build script, so I copied the output of `echo ${env:PATH}` from the VSCode PowerShell terminal and pasted it directly into the `PATH` property of `rust-analyzer.cargo.extraEnv`.

This allowed sharing the cache with `cargo build` run in Windows Terminal's PowerShell (launched the same way as VSCode). However, it still didn't share the cache with `cargo build` run in VSCode's PowerShell terminal .

**Comment by Veykril** [comment]
curious, do rebuilds happen if you build in powershell and then in a plain cmd? (spawned outside powershell of course) In general I don't see a way for r-a to avoid this, the issue is effectively that your build environments for r-a and outside r-a (so its on you to fix that in some way unfortunately)

**Comment by frozenlib** [comment]
After running `cargo build` in PowerShell and then running `cargo build` in Command Prompt, a rebuild did occur. Indeed, this seems more like an issue with PowerShell or VSCode rather than with rust-analyzer.

According to [this comment](https://github.com/PowerShell/PowerShell/issues/24090#issuecomment-2267527201), PowerShell's behavior of modifying the `PATH` environment variable is now unnecessary and is causing other issues, with potential fixes being considered. If this is resolved, the rebuild problem might also go away.

For now, I'll use `"rust-analyzer.cargo.targetDir": true`.

Thank you very much.

**Comment by FlorianDevPhynix** [comment]
I solved this issue for myself by using a custom console profile in vscode with an environment variable that activates code in the PowerShell `$profile`, which then removes the path added by PowerShell.

```json
"terminal.integrated.profiles.windows": {
	"Cargo": {
		"source": "PowerShell",
		"icon": "gear",
		"overrideName": true,
		"env": {
			// forces Path env variable to not be changed by anyone
			"DontChangePath": ""
		}
	}
}
```

```powershell
if (-not (Test-Path env:DontChangePath)) {
	# any code that modifies the Path variable should go here
} else {
	# remove Powershell path from variable
	$Environment = [Environment]::GetEnvironmentVariable("Path")
	foreach ($path in ($Environment).Split(";")) {
		if ($path -like "*C:\Program Files\PowerShell\7*") {
			# remove path from variable
			$Environment = $Environment.Replace(($Path + ';') ,"")
		}
	}
	$Env:Path = $Environment
}
```
This solved the whole issue for me.
Always removing the PowerShell path is not recommended though because it could break some applications that rely on it or cause some bad behavior with PowerShell.
