### ISSUE TITLE
Generate function implementation stub, from function call

### ISSUE THREAD

**Issue by pcgeek86** [rust-lang/rust-analyzer#17804]
Sometimes when I'm writing Rust code, I call a function that doesn't yet exist. 

It might be a nice (low priority) feature, to have an option to `Generate Function Implementation` that generates a function stub, using the known input types.

For example, let's say I "call" this non-existent function:

```rust
get_total(8u8, 10u8).await;
```

I get an error from Rust Analyzer saying:

> cannot find function `operation_list_objects` in this scope

The Rust Analyzer extension could generate a stub for that function, so that I can jump to it and fill out the function body.

```rust
async fn get_total(v1: u8, v2: u8) {
  todo!("Fill out function body");
}
```

It's a small workflow enhancement, but an idea I thought of while working on an application.

**Comment by Veykril** [comment]
There is an assist/code action on the identifier for this, though arguably that ought to be a diagnostic quickfix (the diagnostic itself is currently marked experimental though)
![image](https://github.com/user-attachments/assets/7699f5de-d6d4-4bad-a8b6-5f63feb4dcf5)
