### ISSUE TITLE
inactive-code incorrectly applied when #![cfg(os)] is used in module file

### ISSUE THREAD

**Issue by chris-oo** [rust-lang/rust-analyzer#17817]
I have a minimal repro of this issue here: https://github.com/chris-oo/ra-inactive-code-repro

Essentially, if a module file is cfg gated with `#![cfg(windows)]` or any OS that you're not currently targeting, rust-analyzer incorrectly marks the whole _parent_ file as greyed out with the inactive code warning instead of just marking the module as greyed out. It also marks the module that should be inactive as not greyed out, but with no type completions. 

<img width="541" alt="image" src="https://github.com/user-attachments/assets/5066619c-15f0-4fca-af3a-0bba69bf0fbc">

This code does compile with rustc and runs as expected. It seemed to repro with both release and pre-release versions.

Pictured RA version: v0.4.2064 (pre-release)
Rust version: 1.80

**Comment by chris-oo** [comment]
It does seem like you can not hit this issue if you instead use `#[cfg(windows)]` where the module is defined, instead of `#![cfg(windows)]` at the top of the module file. It seems like somehow `#![cfg(windows)]` is getting propagated to the parent instead of the local module?

**Comment by Veykril** [comment]
Likely regressed in https://github.com/veykril/rust-analyzer/commit/9cbafa2d498d028f501843ad3bfc2d62bb105797

**Comment by Veykril** [comment]
Yep https://github.com/rust-lang/rust-analyzer/commit/9cbafa2d498d028f501843ad3bfc2d62bb105797#diff-3cb35c45ff5d9609122d5bc02989d082a2ed0937b08015c1ba839153a58505b8R1952-R1957 this now marks the whole parent tree accidentally, instead of the module

**Comment by chris-oo** [comment]
Thanks for the fast turnaround!
