### ISSUE TITLE
Isn't the async trait a quick fix for missing implement?

### ISSUE THREAD

**Issue by Mang-Joo** [rust-lang/rust-analyzer#17826]
<img width="939" alt="image" src="https://github.com/user-attachments/assets/c2d615d2-892e-4c8a-8888-5e2d72dcf032">

The async_trait annotation does not cause code referrals.
However, a quick fix is to unattach the async_trait.

<img width="924" alt="image" src="https://github.com/user-attachments/assets/609cb56d-57ec-4612-985c-d91222eec101">

Is this not possible?

**Comment by ShoyuVanilla** [comment]
The `async_trait` is a proc macro, so automatically modifying the macro's input to obtain certain output is not so trivial 🤔

**Comment by Veykril** [comment]
We can't reasonably support this as the macro modifies both the trait as well as the trait impl here.
