### ISSUE TITLE
How to disable "rust-analyzer failed to discover workspace"

### ISSUE THREAD

**Issue by wugifer** [rust-lang/rust-analyzer#17820]
When I open a Rust project with VS Code, everything works fine.

When I open a non-Rust project with VS Code, rust-analyzer throws the error: "rust-analyzer failed to discover workspace". I understand what this means, but for a non-Rust project, this error is meaningless, and the red error message is too prominent.

Is there a switch to suppress this error message, so that it works normally after finding Cargo.toml, and quietly exits if it doesn't find it?

thanks

**Comment by wugifer** [comment]
just an empty project.

![image](https://github.com/user-attachments/assets/3533eacc-79a2-4627-a600-457e03a5608a)

![image](https://github.com/user-attachments/assets/97e9185f-25cd-45d2-96e6-0af34764794f)

**Comment by Veykril** [comment]
This sounds like some other extension of yours is starting up rust-analyzer, as the activation events shouldn't trigger it in an empy folder. Likely some extension is fetching all task kinds which activates all your extensions (this is a vscode bug that vscode doesnt wanna fix)

**Comment by wugifer** [comment]
plugin status: Activated by onTaskType:cargo event: 6ms

**Comment by lnicola** [comment]
Which other extensions do you have?

**Comment by wugifer** [comment]
> Which other extensions do you have?

chinese langguage, CodeGeeX, LaTeX, Prettier - Code formatter, Python, Ruff, UnoT, Vue

**Comment by wugifer** [comment]
set / clear this option, not work
![image](https://github.com/user-attachments/assets/5bc0084d-1de8-4cc1-9d0e-8363833d0f28)

**Comment by lnicola** [comment]
Try disabling CodeGeeX and restarting Code.

**Comment by wugifer** [comment]
> Try disabling CodeGeeX and restarting Code.

not work

**Comment by wugifer** [comment]
disable all, except rust analyzer, chinese language, not work.

this is result of run "Developer: Show Running Extensions"

![image](https://github.com/user-attachments/assets/36138cf0-1ef1-424f-8ea5-21b95a3e1c6b)

**Comment by lnicola** [comment]
CC #15068

I don't understand why you have so many extensions if you've disabled all of them.

**Comment by wugifer** [comment]
update to vscode insiders 1.93.0, work fine. thanks!
