### ISSUE TITLE
Pass `--bin` to `cargo check` when a binary is changed

### ISSUE THREAD

**Issue by mo8it** [rust-lang/rust-analyzer#17829]
I marked this as important because it affects Rust beginners and I don't want them to get a bad expression while learning with Rustlings. It causes Rustlings to freeze for a long time because Rust-Analyzer blocks Cargo.

The issue is described here with a video: https://github.com/rust-lang/rustlings/issues/2071

I was able to reproduce it in VS-Code in a Windows 10 VM (probably not a Windows problem, didn't test on Linux).

You don't even need to have Rustlings running in the background to see how Rust-Analyzer rebuilds everything on every file save:
- Initialize Rustlings with `rustlings inti`
- Open VS-Code in the generated `rustlings/` directory
- Wait for Rust-Analyzer to be done
- Open a file and trigger a save
- See that Rust-Analyzer **rebuilds all 188 binaries!**

~It looks like an issue in the Rust-Analyzer VS-Code plugin because it doesn't happen in Helix in the same VM.~

The effect probably became more dramatic after I added `--keep-going` in https://github.com/rust-lang/rust-analyzer/pull/17561

**Comment by Veykril** [comment]
Which rust-analyzer version are you using with your helix setup? (wanna make sure whether its vscode specific or your helix r-a is just too old)

**Comment by Veykril** [comment]
Also running ` CARGO_LOG=cargo::core::compiler::fingerprint=info` with the appropriate cargo check command after r-a presumably invalidated the build would be good, that will tell what the cause of the invalidations is

**Comment by mo8it** [comment]
I used Rust-Analyzer as the component installed by `rustup` for the stable channel. But your comment made me check that version and it is indeed an older one from May. So the change in https://github.com/rust-lang/rust-analyzer/pull/17561 isn't applied yet. VS-Code has a recent version of Rust-Analyzer. So I made the `beta` channel the default which has a recent version of Rust-Analyzer. Then I also saw this issue in Helix. So it is **not a VS-Code problem**.

---

I disabled Rust-Analyzer and ran `CARGO_LOG=cargo::core::compiler::fingerprint=info cargo check` after saving a file. It showed the following for all exercises but the one changed:

```
0.146508600s  INFO prepare_target{force=false package_id=exercises v0.0.0 (C:\Users\vm\rustlings) target="intro2"}: cargo::core::compiler::fingerprint: fingerprint dirty for exercises v0.0.0 (C:\Users\vm\rustlings)/Check { test: false }/TargetInner { name: "intro2", doc: true, ..: with_path("C:\\Users\\vm\\rustlings\\exercises/00_intro/intro2.rs", Edition2021) }
   0.146615600s  INFO prepare_target{force=false package_id=exercises v0.0.0 (C:\Users\vm\rustlings) target="intro2"}: cargo::core::compiler::fingerprint:     dirty: FsStatusOutdated(Stale)
```

The one changed showed a changed timestamp which is expected.

I don't see why Rust-Analyzer thinks that everything is invalid.

**Comment by mo8it** [comment]
Maybe there is no invalidation problem here. When I run `cargo check` in the VM, it takes about 10 seconds too because of the 188 binaries.

@Veykril Does Rust-Analyzer run `cargo check` without specifying a binary every time a binary changes? If yes, then that is the problem. It should only run `cargo check --bin BINARY_NAME`.

**Comment by Veykril** [comment]
Ye I think you are right, there is no invalidation here. By default we run check with `--workspace`, try setting `rust-analyzer.check.workspace` to false, that should fix this I then I think

**Comment by mo8it** [comment]
I just tried setting `rust-analyzer.check.workspace` to `false` in Helix and VS-Code but it didn't help. Its documentation says that it passes `-p` instead of `--workspace`. But Rustlings is one package with 188 binaries. We need some option to pass `--bin`, not `-p`.

**Comment by Veykril** [comment]
(Though that will require some bigger changes to the flychecking infra unfortunately)

**Comment by alibektas** [comment]
> @alibektas Since you assigned yourself: Did you already start working on it? I wanted to try implementing it myself and start tomorrow if you don't mind. Otherwise, I would be happy to review (if my review counts).

@mo8it I tried one or two things myself but I don't really have anything concrete atm. If you want to implement it yourself I have nothing against it. But let me also offer that I can try getting it done today and if I can't you can take over. How does that sound?

**Comment by mo8it** [comment]
@alibektas Sounds good! I won't be able to start before tomorrow night anyway ;)

**Comment by alibektas** [comment]
@mo8it :wave: I happened to solve this issue while working on a similar one. I want to honor my promise and let you submit the PR, but if you don't have anything ready yet, I could make the PR instead. Let me know what you think.

**Comment by mo8it** [comment]
Nice! No, go ahead. I didn't find time for it 😅
