### ISSUE TITLE
Whole project recompiles when vscode relaunch

### ISSUE THREAD

**Issue by thewh1teagle** [rust-lang/rust-analyzer#17834]
**rust-analyzer version**: rust-analyzer version: 0.3.2062-standalone (c9109f23d 2024-08-04) [/Users/user/.vscode/extensions/rust-lang.rust-analyzer-0.3.2062-darwin-arm64/server/rust-analyzer]

**rustc version**:rustc 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: Vscode

**relevant settings**: 

```json
    "rust-analyzer.cargo.extraEnv": {
        "FFMPEG_DIR": "${workspaceFolder}\\desktop\\src-tauri\\ffmpeg",
        "OPENBLAS_PATH": "${workspaceFolder}\\desktop\\src-tauri\\openblas",
        "CLBlast_DIR": "${workspaceFolder}\\desktop\\src-tauri\\clblast"
    }
```

**repository link (if public, optional)**: https://github.com/thewh1teagle/vibe

As the title says, when relaunching vscode it recompile / index almost the entire project. it's heavy and takes time. Can we skip it if few moments ago I already compiled it?

It happens in any rust project on windows / macos

**Comment by lnicola** [comment]
Does it recompile the code every time you launch Code, or after building from a terminal? How do you set those environment variables in the terminal, and why are you using Windows paths on MacOS?

**Comment by thewh1teagle** [comment]
> Does it recompile the code every time you launch Code

Everytime I launch. I don't know if it compile or just indexing. it does something heavy for a while. on macOS / WIndows no matter which project. I can work on a project, close and reopen vscode then wait for a minute.



> and why are you using Windows paths on MacOS?

That's another issue. I need these paths so build.rs script will work and the project compiles. cross platform project.
If the paths are unix it doesn't work on Windows. and I didn't found a way to set cross platform configuration for that.
So I just kept Windows config for now.

**Comment by lnicola** [comment]
> Everytime I launch. I don't know if it compile or just indexing. it does something heavy for a while. on macOS / WIndows no matter which project.

Does it say anything in the status bar?

> So I just kept Windows config for now.

Changing those (by starting Code vs. building in the terminal) will probably trigger a recompile. You should write a batch file that sets the variables and runs Code or Command Prompt, and remove those from the Code settings.

**Comment by thewh1teagle** [comment]
> Does it say anything in the status bar?
> 
> >

I think that it doesn't compile maybe it just indexing but it takes a lot of time (big project). can it cache it so if I relaunch vscode it won't reindex it?
