### ISSUE TITLE
Commit 733cb1e64 breaks `imports.preferNoStd`

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust-analyzer#17840]
Commit 733cb1e645708faf3742991bf39a7ba4a3938387 ("Optimize `find_path` for sysroot library search some more") breaks the [`rust-analyzer.imports.preferNoStd`](https://rust-analyzer.github.io/manual.html#rust-analyzer.imports.preferNoStd) behavior.

That is, with that option set, and that commit applied, writing:

```rust
fn main() {
    let _ = Pin<tab><enter>
}
```

...produces:

```rust
use std::pin::Pin;

fn main() {
    let _ = Pin
}
```

...rather than:

```rust
use core::pin::Pin;

fn main() {
    let _ = Pin
}
```

The commit reverts cleanly, and reverting the commit on `master` fixes the behavior.

cc @Veykril

**Comment by Veykril** [comment]
This does complete the `std` path for me though
![image](https://github.com/user-attachments/assets/b89795b0-0df5-46dc-af3b-24d730893f0b)

**Comment by Veykril** [comment]
Given `#![no_std]` in a crate makes it work it looks like the config is not being honored to me for some reason
