### ISSUE TITLE
RA doesn't honor `Cargo.toml` `edition`

### ISSUE THREAD

**Issue by Rudxain** [rust-lang/rust-analyzer#17852]
**rust-analyzer version**: 1.80.0 (0514789 2024-07-21)

**rustc version**: 1.80.0 (051478957 2024-07-21)

**editor or extension**: [hx 24.7 (079f5442)](https://github.com/helix-editor/helix/releases/tag/24.07), AppImage

**relevant settings**: `None`?

**repository link (if public, optional)**: `None`

**code snippet to reproduce**: 
`src/main.rs`:
```rust
fn main() {
    std::env::set_var("", "");
}
```
`Cargo.toml`:
```toml
[package]
name = "tmp"
version = "0.1.0"
edition = "2021"
```

**description**: RA shows a diagnostic that's valid for Edition 2024 "this operation is unsafe and requires an `unsafe` function or block (`E0133`)", but not for 2021. `cargo check` is successful

**Comment by Veykril** [comment]
We don't have `#[rustc_deprecated_safe_2024]` implemented

**Comment by Rudxain** [comment]
I've been thinking, and this bug could be considered a "hacky feature", since it serves as a warning that some code might be undefined-behavior. However, this sort of warnings would be appropriate from Clippy, not RA

**Comment by Veykril** [comment]
The bug here is simply that we dont have the attribute implemented that marks an unsafe function as safe in editions < 2024. So we consider this function unsafe in all editions right now even though its not

**Comment by thalesfragoso** [comment]
Have this regressed somehow? I started getting error diagnostics with the latest r-a from the vscode extension.

**Comment by ChayimFriedman2** [comment]
This should not have regressed. Are you sure the edition is set correctly?

**Comment by thalesfragoso** [comment]
I can reproduce with the OP code using the latest version from the extension. If I use the r-a binary provided by rustup (1.91.1) with e.g. helix, then I don't get the diagnostic.

I'm not sure, but I think this started this week, I use the same code-base in a weekly basis and it started showing the diagnostic now.

**Comment by ChayimFriedman2** [comment]
You're right, it did regress. Probably some stupid mistake on the attribute rewrite.

**Comment by ChayimFriedman2** [comment]
https://github.com/rust-lang/rust-analyzer/pull/21244
