### ISSUE TITLE
Incorrect parameter names preview when tuple destructuring is involed.

### ISSUE THREAD

**Issue by your-diary** [rust-lang/rust-analyzer#17858]
**rust-analyzer version**: `rust-analyzer 1.80.0 (05147895 2024-07-21)`

**rustc version**: `rustc 1.80.0 (051478957 2024-07-21)`

**editor or extension**: Vim ([coc-rust-analyzer](https://github.com/fannheyward/coc-rust-analyzer))

**code snippet to reproduce**: cited from #4960:
```rust
fn main() {
    let range = (3, 5);
    test_1(range);
}

fn test_1((start_range, end_range): (u32, u32)) {
    println!("{} - {}", start_range, end_range);
}
```

## Actual

The popup documentation window shows the parameter name as `_`. This information is *completely useless* and I'm always forced to jump to the definition just to see the correct parameter name.

![2024-08-12_17_21_26](https://github.com/user-attachments/assets/a89e93ba-a4c5-49f3-89bb-961c0afb5740)

The situation becomes far more worse when two or more tuple destructurings are involed:

```rust
pub fn unchecked_move_forward(
    &self,
    (i, j): (usize, usize),
    (h_exclusive, w_exclusive): (usize, usize),
) -> (usize, usize) {
```

In this case, I get confused which is which.

![2024-08-12_17_37_41](https://github.com/user-attachments/assets/4aac09c2-7633-4251-ae73-c96845e32295)

## Expected

The popup documentation window shows the parameter name as `(start_range, end_range)` or anything meaningful.

**Comment by roife** [comment]
> render the HIR pattern tree for this

Can we reuse this function to render the pattern tree?

https://github.com/rust-lang/rust-analyzer/blob/08c7bbc2dbe4dcc8968484f1a0e1e6fe7a1d4f6d/crates/hir-def/src/body/pretty.rs#L522

**Comment by Veykril** [comment]
We probably could but we'd need to make it configurable in that it doesn't emit multiline renders for patterns here
