### ISSUE TITLE
Attributes like #![allow(non_camel_case_types)] not recognized in files included using `include!()` macro

### ISSUE THREAD

**Issue by NessajCN** [rust-lang/rust-analyzer#17874]
**rust-analyzer version**: 0.4.2071-standalone [/home/nessaj/.vscode/extensions/rust-lang.rust-analyzer-0.4.2071-linux-x64/server/rust-analyzer]

**rustc version**: rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**editor or extension**: VSCode 1.92.1, rust-analyzer v0.4.2071 (pre-release)

**relevant settings**: 

**repository link (if public, optional)**: 

**code snippet to reproduce**: 
```rust
// src/lib.rs
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
include!("./xx.rs");
```

```rust
// src/xx.rs
pub type __u_char = ::std::os::raw::c_uchar;
```

After #17863 has been applied it seemed r-a did not recognize the following attributes correctly in lib.rs that using include!() macro:
```rust
// src/lib.rs
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
include!("./xx.rs");
```

Warnings like `Type alias __u_char should have CamelCase name, e.g. UChar` still popped up in included files like xx.rs ablove.

**Comment by ChayimFriedman2** [comment]
This is fixed now, probably since https://github.com/rust-lang/rust-analyzer/pull/18099.
