### ISSUE TITLE
allow non_camel_case_types not respected in submodule

### ISSUE THREAD

**Issue by kzhui125** [rust-lang/rust-analyzer#17883]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

**rustc version**: 

rust-analyzer version: 0.3.2070-standalone (0daeb5c0b 2024-08-10) 

rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**editor or extension**: 

VSCode 1.92.1

**code snippet to reproduce**: 

src/lib.rs

```rust
#[allow(dead_code, non_camel_case_types)]
pub mod t1;
```

src/t1.rs
```rust
type f1 = i32;
```

<img width="554" alt="image" src="https://github.com/user-attachments/assets/082153a2-96d6-4859-8802-725479883d8d">

**Comment by lnicola** [comment]
CC #9803.

**Comment by maia-s** [comment]
I get this too. `cargo`/`rustc` does respect the allow, so this is a rust-analyzer bug

rust-analyzer version: 0.3.2104-standalone (08c7bbc2d 2024-09-06)

**Comment by ChayimFriedman2** [comment]
Oh this should be fixed now with my rewrite of lint handling (https://github.com/rust-lang/rust-analyzer/pull/18099).
