### ISSUE TITLE
rust-analyzer completes `r#gen` even before edition 2024

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-lang/rust-analyzer#17895]
In edition 2024, the `gen` keyword is reserved. So rust-analyzer completes `gen` as `r#gen`.

However, it does that even when the crate edition is less than 2024, which creates a weird symbol (`r#gen`) where it is not really needed. Since edition 2024 is still unstable, this means the common case becomes worse for the non-common (yet) case.

**rust-analyzer version**: 0.3.2070-standalone (0daeb5c0b 2024-08-10)

**rustc version**: rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**editor or extension**: VSCode

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**code snippet to reproduce**: 
```rust
fn gen() {}

fn foo() {
    gen<|>
}
```
Trigger completion and choose `gen()`. It completes as `r#gen()`.

**Comment by ChayimFriedman2** [comment]
Turns out the same problem exists on hover (although it is less severe there, since it is not actual code written):

![image](https://github.com/user-attachments/assets/46beec94-bc04-4cd9-b572-75065ea1ded0)

@rustbot label +A-hover

**Comment by lnicola** [comment]
Yeah, I suspect it's everywhere. Implement trait members probably has the same issue.

**Comment by ChayimFriedman2** [comment]
@rustbot claim

This will require some invasive changes, but let's see if I can do it.

**Comment by ChayimFriedman2** [comment]
This... is larger than I thought. So, before I continue, I want to ask:

@lnicola (and other rust-analyzer maintainers), are you OK with a PR that in order to fix this (admittedly pretty marginal), will touch a lot of rust-analyzer parts? I'm talking about 30 files changed and this number is rising.

**Comment by ShoyuVanilla** [comment]
> This... is larger than I thought. So, before I continue, I want to ask:
> 
> @lnicola (and other rust-analyzer maintainers), are you OK with a PR that in order to fix this (admittedly pretty marginal issue), will touch a lot of rust-analyzer parts? I'm talking about 30 files changed and this number is rising.

Though I'm not a maintainer but IMHO I think that this is not too marginal issue because as Rust may introduce more features as time goes on and many keyword be made. So, we might need edition aware name escaping for new keywords from time to time and resolving this issue might be a general methodology for such routine work or implementation case reference at least.

And 30+ file changes seems not too much if necessary 😄

P.S. There is an unfinished PR #16173 that implementing gen block feature in r-a FYI

**Comment by ChayimFriedman2** [comment]
@ShoyuVanilla The question is, do we need to support editing on old or unstable editions? If not, the fix is trivial: just not escape keywords that are not part of the current stable edition. It will continue to be trivial for next editions. And this is not like this issue makes it impossible to write code on unstable/old editions: just few manual changes may be needed. Only if we need to fully support old/unstable editions, a full fix (edition-dependent escaping) is needed. Which begs the question, is it worth the complexity?

**Comment by ShoyuVanilla** [comment]
Oh, I understand. It looks like more complicated decision choice than I thought (waiting for someone to give a proper answer)😅
I prefer the later, personally, but maintainers might thing diffently 🤔

**Comment by Veykril** [comment]
> The question is, do we need to support editing on old or unstable editions?

We do need to support multiple editions unfortunately as that can have impacts on name resolution for libraries, `gen` for example will likely break all `rand` crate versions people depend on once edition 2024 is set to the default as it has `gen` named functions. This touching a bunch of places to be fixed isn't really problematic (and what I would expect), making the parser edition aware touched half the code base as well (which also introduced this problem as I forgot about name escaping not being edition aware).

**Comment by ChayimFriedman2** [comment]
@Veykril Escaping won't have an impact on name resolution, it will only show up in completions etc.. And admittedly, that's a small problem (we will complete `r#` unnecessarily on old editions, and keywords which are invalid syntax on newer editions).

**Comment by Veykril** [comment]
Right, the name resolution stuff was fixed by the parser changes. Well I guess using the current edition is fine then for now

**Comment by ChayimFriedman2** [comment]
@Veykril So you don't want a big PR, only PR excluding `gen` until edition 2024 is stabilized?

**Comment by Veykril** [comment]
Well, the big PR would properly fix things which is preferable, but it's fine to just do the simple thing for now as that fixes it for the most part for users (unless they work in a crate of a differing edition for some reason). So either seems fine to me

**Comment by Veykril** [comment]
Turns out I'm about to land the simple fix here as I needed to rewrite stuff with our syntax kind which demands the edition check for `is_keyword`

**Comment by ChayimFriedman2** [comment]
I actually went the proper fix path :sweat_smile:

Does that mean you are no longer interested in that?

**Comment by Veykril** [comment]
Oh no please go ahead and do the proper fix if you are working on that :)

**Comment by Veykril** [comment]
Now I wonder though, wouldn't it make more sense to do the escaping when the name is used? Given the escaping depends on the edition it feels like that would make more sense as something that's named `gen` only needs escaping in places that has edition 2024 or higher for example 🤔

**Comment by ChayimFriedman2** [comment]
@Veykril This is exactly what I do in my (in the works) patch.

**Comment by ChayimFriedman2** [comment]
Submitted PR after few hours :) #17905.
