### ISSUE TITLE
Make openDocs more flexible

### ISSUE THREAD

**Issue by dmyyy** [rust-lang/rust-analyzer#17892]
openDocs is really useful - unfortunately the docs aren't always hosted on docs.rs. It would be nice to be able to

- open locally built docs
- custom urls - i.e. docs for Bevy's next release are hosted [here](https://dev-docs.bevyengine.org/). It would be nice to be able to point there when working with Bevy main

**Comment by Veykril** [comment]
If you have built the docs locally I think we should already be opening the local ones (with VSCode at least).
