### ISSUE TITLE
r-a cannot resolve sizes and aligns of some structs.

### ISSUE THREAD

**Issue by QuarticCat** [rust-lang/rust-analyzer#17935]
**rust-analyzer version**: 0.3.2078-standalone

**rustc version**: rustc 1.80.1

**editor or extension**: VSCode 1.92.2

**relevant settings**: none

**code snippet to reproduce**: 
```rust
struct Foo {}

struct Bar {
    handler: Option<std::thread::JoinHandle<()>>,
}
```

 Hover on `Foo`, there's a hint: `// size = 0, align = 0x1`.

While hover on `Bar`, there's no such hint.

**Comment by Veykril** [comment]
This will work starting with `1.82.0` toolchains, this is a problem within the standard library thats fixed there
