### ISSUE TITLE
rust-analyzer.cargo.unsetTest is gone, what should I use as a substitute?

### ISSUE THREAD

**Issue by vittorius** [rust-lang/rust-analyzer#17957]
Some time [ago](https://github.com/rust-lang/rust-analyzer/issues/7225#issuecomment-1068948001), there was an option to disable the "`test` feature by default". Now it seems to be gone.
Is there any alternative way to disable the `test` feature? My primary goal is to disable it for my main crate in order to get rid of the errors highlighted throughout the codebase while my mocks (covered by `#[cfg(test)]`) are still incomplete.

**Comment by iceHtwoO** [comment]
My fix for now is to downgrade to v0.3.1924, but I would be happy to hear if there is an alternative option. Config was removed with this PR: https://github.com/rust-lang/rust-analyzer/pull/16726

**Comment by srgsanky** [comment]
I used the following command to downgrade to a version of rust-analyzer that works correctly with unsetTest. 1.79.0 and above starts ignoring unsetTest.

```bash
rustup default 1.78.0 && rustup component add rust-analyzer
```

**Comment by Ten0** [comment]
I used to unset test on not all crates, only some of them. It doesn't seem like the referenced commit (adding `rust-analyzer.cfg.setTest`) solves this use-case of the previous feature.
