### ISSUE TITLE
Failed to load workspace when launching via `cursor` instead of `cursor .`

### ISSUE THREAD

**Issue by rikhuijzer** [rust-lang/rust-analyzer#17953]
**rust-analyzer version**: 0.3.1958-standalone

**rustc version**: rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**editor or extension**: Cursor (VSCode) with extension version 0.3.1958

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

When I open the Cursor editor via the terminal via `cursor .` (same as `vscode .`) in a specific project directory, `rust-analyzer` works.

However, when I open the Cursor editor without specifying the workspace via `.`, then `rust-analyzer` fails even though my folders show the same project as it would be `cursor .`. The error is

```
2024-08-24T17:36:51.874219Z ERROR rust_analyzer::main_loop: FetchWorkspaceError:
rust-analyzer failed to load workspace: Failed to load the project at /Users/rik/git/xxx/Cargo.toml: Failed to query rust toolchain version at /Users/rik/git/xxx, is your toolchain setup correctly?: cd "/Users/rik/git/xxx" && "cargo" "--version" failed: No such file or directory (os error 2)
```

So the weird thing here is that the correct file is specified in the command, but still it fails. Possibly related is that my default shell is `fish`. If I copy the command, it shows an error:

```fish
$ ~/g/xxx (main)> cd /Users/rik/git/xxx/ & cargo --version
cargo 1.80.1 (376290515 2024-07-16)

fish: Job 1, 'cd /Users/rik/git/rrcf/ &' has ended
```

So that `rust-analyzer` fails makes sense, but then why does it succeed when using `cursor .`?

It is possible that this behavior is as expected. Feel free to close the issue if so. I couldn't find any useful tip while searching for 20 minutes so I thought it would probably be good to write this down somewhere.

**Comment by lnicola** [comment]
Just to make sure, are you starting `cursor` from the terminal, or from a menu entry / shortcut?

**Comment by rikhuijzer** [comment]
> Just to make sure, are you starting `cursor` from the terminal, or from a menu entry / shortcut?

Good question. It looks like if I start it via the MacOS spotlight search, then it fails and if I start from the terminal, then it works.

@truell20, maybe this is a known issue at your side?

**Comment by lnicola** [comment]
> If your editor can’t find the binary even though the binary is on your $PATH, the likely explanation is that it doesn’t see the same $PATH as the shell, see [this issue](https://github.com/rust-lang/rust-analyzer/issues/1811). On Unix, running the editor from a shell or changing the .desktop file to set the environment should help.

**Comment by rikhuijzer** [comment]
You are absolutely right! Thanks. That's probably the issue.
