### ISSUE TITLE
VSCode: `runCommands`: check if rust-analyzer is running in `when` clause

### ISSUE THREAD

**Issue by marxin** [rust-lang/rust-analyzer#18002]
I'm using the following VSCode key binding for building, running, and testing a Rust project:

```
 {
        "key": "f7",
        "command": "runCommands",
        "args": {
            "commands": [
                {
                    "command": "workbench.action.terminal.sendSequence",
                    "args": {
                        "text": "cargo build\n"
                    },
                },
                "workbench.action.terminal.focus"
            ]
        },
        "when": "editorTextFocus && editorLangId == rust"
    },
```

What makes me unhappy is that `editorLangId == rust` only works if a `.rs` file is actively opened. The shortcut stops working if you open up a `Cargo.toml` file or any other non-Rust source code in a project.

The question is if one can check if `rust-analyzer` extension is running and use it in the `when` clause. That would be huge improvement to my shortcut settings.

Btw. thanks a lot for great LSP server for Rust!

**Comment by Veykril** [comment]
`inRustProject` ought to work I think, we seem to set that to true when activated

**Comment by marxin** [comment]
Cool, it works perfectly!
https://rust-analyzer.github.io/manual.html#special-when-clause-context-for-keybindings
