### ISSUE TITLE
how to get configuration for debugging?

### ISSUE THREAD

**Issue by jm-observer** [rust-lang/rust-analyzer#18001]
Hello, I'm facing an issue while improving the debugging functionality of the [Lapce](https://github.com/lapce/lapce) IDE.

I noticed that there is already a similar function implemented in TypeScript（#3441 #4366）. Is there a way to get these parameters using Rust or through the Language Server Protocol (LSP)?

**Comment by Veykril** [comment]
No, these things all live in the VSCode extension. The server has no knowledge of debugging

**Comment by jm-observer** [comment]
ok,thanks!
