### ISSUE TITLE
Proc-macro panicked: proc-macro server exited with signal: 6 

### ISSUE THREAD

**Issue by pi314ever** [rust-lang/rust-analyzer#18004]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) 2024-08-27, installed through Mason

**rustc version**: (eg. output of `rustc -V`) 1.75.0

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable) neovim v0.10.2

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`) 

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer)) `cargo.features = "all"`, `checkOnSave.command = "clippy"`

**code snippet to reproduce**: 
```rust
use tracing::instrument;

struct Test {}

impl Test {
  #[instrument(skip(self))] // proc-macro server exited with signal: 6 (SIGABRT) (core dumped)
  fn a(&self, b: usize, c: usize) {
     // Some things
    random_things = should_error; // No error here because obscured by proc-macro srever exit
  }
}
```

I have been encountering this bug while working on a project within a Docker environment that manually installs Rust and rust-analyzer, and I have not been able to figure out why. Any tips on how to diagnose this issue would be greatly appreciated.

**Comment by Veykril** [comment]
That snippet there doesn't even involve the proc-macro server so this is likely something odd with your setup, can't tell you what though unfortunately

**Comment by lnicola** [comment]
Signal 6 is SIGABRT, so some kind of `abort()`.

**Comment by pi314ever** [comment]
Sorry that was a bad example. I am seeing this a lot with functions with tracing:
```rs
struct Test {}
impl Test {
  #[instrument(skip(self))]
  fn a(&self, b, c) {
     // Some things
  }
}
```
This causes my setup to highlight all of the function under the proc-macro server error with exit code 6 or 11.

**Comment by pi314ever** [comment]
@Veykril I have updated the example errors I am encountering. Can you please look at this again?

**Comment by pi314ever** [comment]
Seems like this is only happening for Mason installed rust-analyzer and not [rustacean.nvim](https://github.com/mrcjkb/rustaceanvim)'s version. This may be a bug on Mason's integration?

**Comment by yuyang-ok** [comment]
I still have this issue . Is this problem solved???

![Image](https://github.com/user-attachments/assets/137a1eeb-d8fa-4491-8e79-3a74708ffa13)

**Comment by yuyang-ok** [comment]
@pi314ever I think I am not using mason installed `rust-analyzer`. I think I am using  `rust-analyzer` installed via `rustup`.

I am still have this issue.

**Comment by 39george** [comment]
Same issue
