### ISSUE TITLE
Allow finding all returns from the `->`

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-lang/rust-analyzer#18017]
r-a allows you to find all points where control-flow may leave the function by finding all references to `return` and the like. However, sometimes I am at the function header, and not at a `return`. It'd be nice if r-a could do the same when finding all references on the arrow `-> ReturnType`. That should be pretty trivial to implement.

**Comment by ChayimFriedman2** [comment]
Nevermind, it seems we can already do that on the `fn` keyword. That could use more documentation, though...

**Comment by Veykril** [comment]
This is documented in the highlight related feature	
```
// . if on a `return` or `fn` keyword, `?` character or `->` return type arrow, highlights all exit points for that context
```
