### ISSUE TITLE
Hide a specific trait in autocomplete

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust-analyzer#18024]
I love `color-eyre` but the `OwoColorize` trait adds a lot of noise to autocomplete.
![image](https://github.com/user-attachments/assets/5c079db3-9c3c-4ddc-af20-029f5c433cf2)

Could we get a way to hide some specific traits?
I'd personally also use it for `Any`

**Comment by lnicola** [comment]
Duplicate of #17477 and possibly others, too.
