### ISSUE TITLE
AVG detects trojan in rust analyzer on windows

### ISSUE THREAD

**Issue by fritol** [rust-lang/rust-analyzer#18030]
appeared today

![image](https://github.com/user-attachments/assets/346e648a-3627-4257-abc5-f70b0f76f880)
![image](https://github.com/user-attachments/assets/173d31db-070e-4717-b810-5a8647e2a9fe)

**Comment by lnicola** [comment]
That's a false positive, every antivirus has them. You can use virustotal.com, I suspect most AVs will find nothing. "IDP.ARES.Generic" is just "vibes".

AVG might have a way to report these, I don't know.
