### ISSUE TITLE
Reserved keywords in macros are highlighted as keywords

### ISSUE THREAD

**Issue by allan2** [rust-lang/rust-analyzer#18039]
RA 0.4.2095-standalone
rustc 1.82 nightly
VS Code 1.92.2

Reserved keywords in macros are highlighted as keywords rather than regular tokens when used in macros.

```rs
// working code
#[my_attr_macro(mut = true, override = true, foo = true)]
fn main() {
    my_macro!(
        mut = true,
        override = false,
        foo = true,
    );
}
```

![vs-code-screenshot.png](https://github.com/user-attachments/assets/36345111-c1d8-456b-a145-6920f23dd2e5)

```[tasklist]
### Tasks
```

**Comment by Veykril** [comment]
That sounds correct to me. These tokens are considered keywords in the language so they should be highlighted as such (unless their span is re-used for something else in the expansion)

**Comment by allan2** [comment]
That makes sense.

I switched to a different implementation of attribute parsing (syn 1 `AttributeArgs` to syn 2 `impl Parse`), which errors with ``error: expected identifier, found keyword `override` ``.

Even though a keyword could used as an identifier, I don't think RA can tell. And it was useful to have it highlighted for me.
