### ISSUE TITLE
Fill match arm assist should prefill binding names for tuple struct patterns

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18034]
For
```rs
pub enum SmolStrBuilder {
    Inline { len: usize, buf: [u8; INLINE_CAP] },
    Heap(String),
}
```
currently fills as 
```rs

        match value {
            SmolStrBuilder::Inline { len, buf } => todo!(),
            SmolStrBuilder::Heap(_) => todo!(),
        }
```
We can do better for the latter arm, for single field tuple structs/variants we should use the variant name I feel like: `SmolStrBuilder::Heap(heap)`, though that might turn odd with things like `Option`. A better one would probably be to just fill the names by their types, so SmolStrBuilder::Heap(string)` in this case (and for any arity of fields that is).

cc @roife might be a nice follow up for you given you basically did this for completions earlier :^)

**Comment by roife** [comment]
Perhaps we should introduce a conflict resolution mechanism for `suggest_name`. For example:

for `A(S, S, S)`, we want `A(s, s1, s2)` rather than `A(s, s, s)` or `A(s, s1, s11)` 🤣.

**Comment by Veykril** [comment]
We generally still need that yes
