### ISSUE TITLE
Enable cfg(rust_analyzer) when building proc-macros for use in RA

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust-analyzer#18069]
For the main IDE features, RA always considers the `rust_analyzer` cfg to be active, which can be super helpful for declarative macros that want to use small hacks to better integrate with RA.

It seems like the same is not true for proc-macros, i.e. when a proc-macro gets loaded by RA, that macro has not been built with `cfg(rust_analyzer)`. It would be super helpful if RA could build proc-macros with that cfg set such that proc-macros can change their output under RA. Obviously this could also be abused, but if you have malicious code in your dependencies, you generally already have a bigger problem.

Context: https://github.com/ruma/ruma/pull/1899

**Comment by Veykril** [comment]
We can't do that, this will cause rebuilds between r-a builds and non-r-a builds

**Comment by jplatte** [comment]
> We can't do that, this will cause rebuilds between r-a builds and non-r-a builds. 

Ah, so RA has cargo build the proc-macro dependencies as part of the regular `target/debug` tree? Would it not be possible to build them in a separate location, such that they don't influence the regular build?

> Additionally that cfg is meant solely for r-a semantic analysis so it would feel go against its use case having it affect actual cargo invocations

Hmm, I think you're misunderstanding. I don't want this to influence cargo invocations. I want this to influence what rust-analyzer reports about the generated code when _it_ runs the proc-macro. Or in this specific case, I want this to influence the output of the "expand macro recursively" helper.

**Comment by Veykril** [comment]
> Ah, so RA has cargo build the proc-macro dependencies as part of the regular `target/debug` tree? Would it not be possible to build them in a separate location, such that they don't influence the regular build?

Yes we use the same build dir by default to reduce build times and disk space used, it is possible to already tell r-a to use a different build dir via a config but the default is not going to change.

> Hmm, I think you're misunderstanding. I don't want this to influence (other) cargo invocations. I want this to influence what rust-analyzer reports about the generated code when it runs the proc-macro. Or in this specific case, I want this to influence the output of the "expand macro recursively" helper.

That does not sound like a cfg then, a cfg is compile time and so would need to affect the proc-macro build to change the generated code. I am a bit confused by your linked PR in general though, why would you want the expansion to differ in r-a.


Note that rebuilds will likewise occur with your feature idea with that linked PR

**Comment by jplatte** [comment]
> That does not sound like a cfg then, a cfg is compile time and so would need to affect the proc-macro build to change the generated code.

Yeah, I know. I want that, but _specifically_ for the version of the proc-macro that's loaded by RA. I want it to build a different version of the proc-macro from what's going to be used by regular `cargo` invocations.

> I am a bit confused by your linked PR in general though, why would you want the expansion to differ in r-a.

So we have hundrets of types that all need the same `#[cfg_attr(not(feature = "unstable-non-exhaustive")), non_exhaustive)]` plus a couple of derives plus a couple of derive helper attributes. Because this is a pain to write _and_ read, we basically packaged that combination of attributes up into an attribute macro (or two, actually).

One of those derives that the attribute macro expands to is our own.
We can't have the attribute do the work of the derive directly on stable because it's a huge PITA to handle all `cfg` and `cfg_attr`s on fields in the derive input. By delegating most of the codegen to a derive macro, we have the compiler expand all cfg's before the actual codegen logic.

But... from time to time you wanna debug our codegen, or maybe copy-paste it to create a manual implementation because the macro isn't general enough for everything. By far the most convenient solution for seeing proc-macro output is RA's "expand macro recursively" helper. But there's a problem: When you run it on our attribute, it just shows you the couple of derives and extra attributes that attribute macro expands to, not what our own derive macro outputs.

The new Cargo feature introduced in the linked PR works around this issue by using the nightly `TokenStream::expand_expr` to have the attribute macro do the cfg expansion itself, and call the derive logic itself. It's all a big hack, but it works!

Now there are alternatives here:

- have RA expand _all_ macros in the assist (or a new one), this would allow seeing all the macro output, but it would also clutter the output immensely due to serde in our case, it would also be extremely unhelpful in case there's stuff like `format!()` in the proc-macro output (this is a major reason why I strongly favor RA's current functionality over `cargo expand`)
- somehow allow the "expand macro recursively" helper to work _within_ the generated `[EXPANSION].rs`; this would be absolutely amazing but it seems very hard

**Comment by ChayimFriedman2** [comment]
proc-macros are not supposed to examine the cfgs they were built with anyway, rather they should check the cfgs cargo provides them with via [`env::var("CARGO_CFG_<cfg>")`](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts).

**Comment by jplatte** [comment]
That would not workable in this case even if it worked, as I need to use nightly-only functionality for this feature and the macro otherwise works on stable.

Also you linked to the cargo docs on build scripts. Those environment variables are not set for proc-macros and in general the compiler / rustc does not use environment variables to communicate with proc-macros.

**Comment by ChayimFriedman2** [comment]
> Those environment variables are not set for proc-macros and in general rustc does not use environment variables to communicate with proc-macros.

AFAIK they do.

**Comment by Veykril** [comment]
rust-analyzer isn't setting those env vars when running the proc-macros I believe (this is a bug, we just haven't implemented all cargo env vars that are being passed)

**Comment by Veykril** [comment]
>  When you run it on our attribute, it just shows you the couple of derives and extra attributes that attribute macro expands to, not what our own derive macro outputs.

Well, to be fair that's a tooling issue (r-a being the tooling), we should expand those / offer a way to expand **every kind of macros**. Right now I believe we only recursively expand the same kind, that is if invoked on an attribute, only attributes, derive only derives and bang only bangs.

Ah I see you went into that basically after

> Now there are alternatives here:

Both of those points are things I'd love to have (we even have an issue for those somewhere, probably multiple)


> Yup, that's not the end of the world though, as using it should be a very rare thing.

it would not be rare, it would occur everytime you start up rust-analyzer. Also if you use check on save it would happen on/after every save. Your change affects the entirey of r-a's analysis, not just the "expand" command.

**Comment by jplatte** [comment]
> rust-analyzer isn't setting those env vars when running the proc-macros I believe (this is a bug, we just haven't implemented all cargo env vars that are being passed)

This is not a bug, Cargo doesn't do it either:

![Screenshot_2024-09-08_110642](https://github.com/user-attachments/assets/bdcea684-99dd-4583-baff-a68f230b6bab)

> it would not be rare, it would occur everytime you start up rust-analyzer. Also if you use check on save it would happen on/after every save. Your change affects the entirey of r-a's analysis, not just the "expand" command.

Maybe you were talking about something different but what I meant would be rare is changing your `settings.json` to enable the `__internal_macro_expand` feature. Whenever it _is_ active of course every regular `cargo build` w/o the feature trashes RA's cache and vice versa.

Anyways, it sounds like the original feature request is not something you want to support? I can close this then.

**Comment by Veykril** [comment]
> This is not a bug, Cargo doesn't do it either:

Right, cargo couldn't do it in this case even 

> Anyways, it sounds like the original feature request is not something you want to support? I can close this then.

It's not, the r-a cfg is not meant for this
