### ISSUE TITLE
Performance issue in https://github.com/iosis-tech/swiftness

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/rust-analyzer#18071]
If you try to edit crates/air/src/layout/*/autogenerated.rs you'll find every edit takes more than 10 seconds to finish the cargo check

**Comment by Veykril** [comment]
If this is about `cargo check` its not a rust-analyzer issue

**Comment by GopherJ** [comment]
@Veykril what I mean is `checkOnSave` for diagnostic, not `cargo check`

**Comment by davidbarsky** [comment]
The `checkOnSave` diagnostics are sourced from `rustc` which, by default, come from `cargo check`. There's generally very little that we can do.
