### ISSUE TITLE
install-code argument passthrough

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-analyzer#1808]
I would like to do something like `cargo install-code -j1` but it does not seem to work:

````
error: Found argument '-j' which wasn't expected, or isn't valid in this context

USAGE:
    ra_tools install-ra [FLAGS]

For more information try --help
````

`cargo install-code -- -j 1 ` does not work either.

**Comment by matklad** [comment]
I feel like using the plumbing `cargo install --path crate/ra_lsp_server` command might be the right solution here

**Comment by kjeremy** [comment]
It would be nice to pass offline cargo flags so that npm doesn't try to redownload everything too.

**Comment by Veykril** [comment]
This is a rather old issue so this might be referencing non existent thinks now, but what exactly is this about? (I imagine this is pre `xtask` times?)

**Comment by bjorn3** [comment]
The xtask install command doesn't have support for this either.

**Comment by matklad** [comment]
That's about passing args to cargo/npm _through_ `cargo xtask install`. I think "not planned" is the right choice here -- we don't do any kind of magic in `cargo xtask install`, so, if the user needs full control, they should use the underlying `cargo install -p rust-analyzer` command.
