### ISSUE TITLE
check.workspace option no longer implies cargo check will always use --workspace flag

### ISSUE THREAD

**Issue by soooch** [rust-lang/rust-analyzer#18104]
This breaks configs with extra_args which assume `--workspace` will be in the check command when check.workspace is true. In my case, this means I can not use `--exclude` arguments in "extra_args" without flycheck failing.

this behavior was changed here: https://github.com/rust-lang/rust-analyzer/pull/17912/files#diff-532b0325efe572c4000020f9997a934629c3798d7a69ede6520f519417638d9aR376

A potential fix may be the addition of a new "workspace_extra_args" config option.

@alibektas @Veykril @mo8it 

**rust-analyzer version**: 0.3.2104-standalone

**rustc version**: 1.78

**editor or extension**: VSCode

**relevant settings**:

```json
{
    "rust-analyzer.cargo.extraArgs": [
        "--exclude",
        "some_crate",
    ],
    "rust-analyzer.check.workspace": true,
}
```

**Comment by soooch** [comment]
I can PR my suggested solution if that sounds like a reasonable solution.

**Comment by ChayimFriedman2** [comment]
An alternative will be to have a third option to `workspace` `"force"` that will always run cargo on the entire workspace.

**Comment by Veykril** [comment]
That would be a simple solution (for now, or permanently, time would tell) 👍
