### ISSUE TITLE
How to execute a command from a code lens

### ISSUE THREAD

**Issue by bstaletic** [rust-lang/rust-analyzer#18113]
I'm messing around with code lenses and wanted to try the "Run" code lens.
However, rust-analyzer is not an `executeCommandProvider` and rightfully rejects that request.
I must be missing something and my question is "what".

I can include the logs if you want me to.
rust-analyzer version is nightly-2024-06-11

**Comment by ChayimFriedman2** [comment]
Which editor?

**Comment by bstaletic** [comment]
Vim, with youcompleteme. I was rather asking about the protocol, not where to click in a certain editor.
I was expecting I could make rust-analyzer execute that `runSingle` command, but it seems I was wrong.
According to [commands.ts](https://github.com/rust-lang/rust-analyzer/blob/4221354a8fe90ea8218d3757d14735eac08d3e81/editors/code/src/commands.ts#L1142), seems like the intention is for clients to have server-specific knowledge.
That pretty much goes against the idea of having a standardized protocol.

I will close the issue, as did find the answer I was looking for.
