### ISSUE TITLE
textDocument/codeLens return empty

### ISSUE THREAD

**Issue by jm-observer** [rust-lang/rust-analyzer#18126]
i am using rust-analyzer on [Lapce](https://github.com/lapce/lapce). In the same project, the method "textDocument/codeLens" returns empty with the versions of rust-analyzer after 2024-07-29, while the previous versions returned "run" and "debug" options. Has there been a configuration change?

**Comment by ChayimFriedman2** [comment]
2024-07-09 is pretty old. Is that the last release it worked on? If not, can you find the most recent release it worked on?

**Comment by jm-observer** [comment]
The latest version also returns empty results. The most recent usable version is 2024-07-22.

**Comment by jm-observer** [comment]
Can we confirm that this is a bug?

**Comment by Veykril** [comment]
It likely is though I dont recall us changing anything relevant here

**Comment by jm-observer** [comment]
It seems this issue hasn't been fixed in version [2024-09-23](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-09-23)

**Comment by jm-observer** [comment]
I tested the latest version（`2024-09-30`）, and there's still no response, but VSCode works. So, could it be because Lapce interacts with rust-lang via standard input/output? Does VSCode also interact with rust-lang through standard input/output?

**Comment by jm-observer** [comment]
It works after adding these capabilities to the client's capabilities:

```
"experimental": {
        "commands": {
          "commands": [
            "rust-analyzer.runSingle",
            "rust-analyzer.debugSingle",
          ]
        }
      }
```
