### ISSUE TITLE
rust-analyzer unable to see some types in `zbus::fdo`

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18138]
https://github.com/dbus2/zbus/issues/671

**Comment by ChayimFriedman2** [comment]
Can't reproduce. Things are working fine to me (I didn't check on the linked commit but on HEAD).

**Comment by Veykril** [comment]
Looks like I linked a fork by accident

**Comment by zeenix** [comment]
> Can't reproduce. Things are working fine to me (I didn't check on the linked commit but on HEAD).

That actually part of the reproducer: i-e when using zbus prior to 4.0^ it worked fine.

^: Precisely pinpointing the exact commit that introduced this issue would a bit difficult since it'll require a long `git bisect` session with no automated reproducer combined with API breakages along the way.

**Comment by ChayimFriedman2** [comment]
> That actually part of the reproducer: i-e when using zbus prior to 4.0^ it worked fine.

Prior to, or after? Because I checked on HEAD, which should have the latest updates.

**Comment by Veykril** [comment]
Would be nice i you could link a commit that exhibits the problem then

**Comment by zeenix** [comment]
> Because I checked on HEAD, which should have the latest updates.

The latest HEAD of the corrected repo link main, or the main on my personal fork that @Veykril first linked by accident? The former seems stuck on prior to 4.0 so you should **not** be able to reproduce there but with latter you **should** be able to reproduce.

**Comment by zeenix** [comment]
> Would be nice if you could link a revision that exhibits the problem then

The latest main and also latest crates.io release.

**Comment by ChayimFriedman2** [comment]
> > Because I checked on HEAD, which should have the latest updates.
> 
> The latest HEAD of the corrected repo link main, or the main on my personal fork that [@Veykril](https://github.com/Veykril) first linked by accident? The latter seems stuck on prior to 4.0 so you should **not** be able to reproduce there but with former you **should** be able to reproduce.

The HEAD of the correct repo, not the fork.

**Comment by zeenix** [comment]
> > > Because I checked on HEAD, which should have the latest updates.
> > 
> > 
> > The latest HEAD of the corrected repo link main, or the main on my personal fork that [@Veykril](https://github.com/Veykril) first linked by accident? The latter seems stuck on prior to 4.0 so you should **not** be able to reproduce there but with former you **should** be able to reproduce.
> 
> The HEAD of the correct repo, not the fork.

Oh, that's very strange. Just to be sure a recent refactor in zbus didn't end up somehow "fixing" this, I created a new project here and as you can see in the attached screencast, auto-completion doesn't work for the method of the generated `DBusProxy` type, even though I'm using the latest HEAD as well (the `Cargo.toml` is visible in the beginning of the video).

https://github.com/user-attachments/assets/573ecc9e-e146-4d06-8440-59b65b6e6da4

**Comment by Veykril** [comment]
Can reproduce that, funny how we give the completion for `DBusProxy` but we aren't actually able to resolve it. The `#[proxy]` attribute fails to expand on the `DBus` trait for some reason but only when its used in the dependency

**Comment by ChayimFriedman2** [comment]
Ok, with `DBusProxy` I can reproduce (but not with the types from the original issue).

**Comment by zeenix** [comment]
> Can reproduce that, funny how we give the completion for `DBusProxy` but we aren't actually able to resolve it. The `#[proxy]` attribute fails to expand on the `DBus` trait for some reason but only when its used in the dependency

Just a shot in the dark but is it possible that `proxy` macro eating away its input trait (https://github.com/dbus2/zbus/issues/225), causes this somehow? 🤔 Although that's always been the case so it's unlikely.

**Comment by ChayimFriedman2** [comment]
If it expands to something, rust-analyzer should be able to see that something. It eating its input should not matter.

**Comment by ChayimFriedman2** [comment]
This is probably the same issue as #17630. This also has to do with a module shadowing the macro, and here too if I move the reexport of `proxy` at the crate root above the module declaration things start working correctly.

**Comment by ChayimFriedman2** [comment]
Update: I managed to minimize the problem:
```rust
mod foo {
    macro_rules! x {
        () => {
            pub struct Foo;
        };
    }
    pub(crate) use x as m;
}

mod bar {
    use crate::m;

    m!();

    fn qux() {
        Foo;
    }
}

mod m {}

use foo::m;
```
`Foo` in `qux()` is not resolved, because `m!()` is not expanded, because:

 a. In the same scope of `m` (`crate`), there is also a module with the same name.
 b. `m!()` is imported *after* its use (in `bar`). Specifically, it's the place of `m!()` relative to its usage that matters, not relative to the `m` module.

**Comment by ChayimFriedman2** [comment]
Ok, I nailed the problem, and I have a fix, but I need to check because it may prove too expensive...

**Comment by zeenix** [comment]
Awesome! Thanks so much @ChayimFriedman2 and @Veykril. 👍🙏
