### ISSUE TITLE
RA warns allowed lints that have comments

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-analyzer#18144]
![Image](https://github.com/user-attachments/assets/495a15e4-6526-432e-b5ca-66c37f39ed36)

Comments placed above the name of a lint make `#[allow(..)]` a NO-OP. IFAICT, this is a recent regression.

![Image](https://github.com/user-attachments/assets/c18dc815-9246-4978-91bc-9b0522d49b96)

**Comment by ChayimFriedman2** [comment]
Oh it's because of my rewrite of lints handling 🫢

I'll look at it. @rustbot claim
