### ISSUE TITLE
`r#const` sometimes does not match in declarative macros

### ISSUE THREAD

**Issue by DaniPopes** [rust-lang/rust-analyzer#18148]
**rust-analyzer version**: 0.3.2112-standalone

**rustc version**: rustc 1.83.0-nightly (0ee7cb5e3 2024-09-10)

**editor or extension**: VSCode 1.92.2

**relevant settings**: N/A

**repository link (if public, optional)**: N/A

**code snippet to reproduce**: 
```rust
pub fn r_hash_const() {
    let r#const = true;
    assert_eq!(r#const, true);
    //         ^^^^^^^ no rule matches input tokens

    // However, these work:
    assert!(r#const);
    assert!(r#const,);

    // Other keywords also work:
    let r#extern = true;
    assert_eq!(r#extern, true);
    let r#fn = true;
    assert_eq!(r#fn, true);
}
```

**Comment by ChayimFriedman2** [comment]
Hmm... That's probably because `expr_2021` doesn't match inline const, which starts with `const`.

**Comment by ChayimFriedman2** [comment]
I'll look at this.

@rustbot claim
