### ISSUE TITLE
rename print args not working on nightly

### ISSUE THREAD

**Issue by loynoir** [rust-lang/rust-analyzer#18150]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

rust-analyzer version: 1.80.0 (0514789 2024-07-21)

**rustc version**: (eg. output of `rustc -V`)

rustc 1.82.0-nightly (1f12b9b0f 2024-08-27)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)

vscode 1.93.1

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

channel = "nightly-2024-08-28"

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

https://github.com/rust-lang/rust/issues/130504

**code snippet to reproduce**: 

```rust
    let foo: i32 = 42;
    eprintln!("value={foo}");
```

```rust
    let bar: i32 = 42;
    eprintln!("value={foo}");
```

**Comment by ChayimFriedman2** [comment]
This is a pretty old rust-analyzer version. Can you check with a more recent one (the VSCode extension comes bundled with one by default)?

**Comment by loynoir** [comment]
Uninstall and restart dev container and reinstall and restart devcontainer, still not working on nightly.

RA v0.3.2112

rust-analyzer version: 1.82.0-nightly (1f12b9b 2024-08-27)

**Comment by ChayimFriedman2** [comment]
Cannot reproduce. Works fine for me. That's an old nightly too - can you upgrade to a more recent one?

**Comment by loynoir** [comment]
https://static.rust-lang.org/manifests.txt

Tested working

- non-nightly

- `channel = "nightly-2024-09-15"`

Tested not working

- `channel = "nightly-2024-08-28"`

**Comment by ChayimFriedman2** [comment]
[We support officially only the latest stable version](https://rust-analyzer.github.io/manual#toolchain). Recent nightlies might work, but especially old nightlies might as well not. So this is kind of expected.
