### ISSUE TITLE
rename "object safety" to "dyn compatibility"

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18185]
https://github.com/rust-lang/lang-team/issues/286

We have a diagnostic for this now, as well as a hover message that use object safety as the term, we should change that if this goes through.

**Comment by noahmbright** [comment]
Is this as simple as scrubbing the code base for "object_safety", "ObjectSafety", and what not and swapping with dyn_compatibility? I can take care of this if that's the case

**Comment by alibektas** [comment]
Almost. You can check https://github.com/rust-lang/rust-analyzer/tree/master/crates/hir-ty/src/object_safety and see which other parts refer to this part of the codebase change every reference, usage of words "Object Safety" etc. 

Do you want me to assign you to this issue?

**Comment by noahmbright** [comment]
@rustbot claim

Got it. I think between grep, the compiler and a reviewer I can get this taken care of. Hopefully the former 2 make it easy on the latter
