### ISSUE TITLE
Add a option of `Exclude Test` for `Show call hierarchy`

### ISSUE THREAD

**Issue by chenyukang** [rust-lang/rust-analyzer#18212]
When reading the source code of a project, `Show call hierarchy` is very useful tool to get the flow of code. But for a project with lots of test code, it's very hard to get the real flow, since we need to click reference one by one to take a look at the code:

![Image](https://github.com/user-attachments/assets/60d49f5c-cd94-46f3-8953-48e17909a0b4)

I notice we already have the option to exclude test code from references: https://github.com/rust-lang/rust-analyzer/pull/16441

Maybe we should also exclude test references when this option is enabled, now we need to add a new option?

**Comment by Veykril** [comment]
We should make it honor that same flag I think, adding an extra option for all these features doesn't sound too great

**Comment by chenyukang** [comment]
yeah, honor the current flag will be great. I'm not sure whether this will introduce performance issue since there are more checks compared with reference checks, I notice there are some performance benchmark data in https://github.com/rust-lang/rust-analyzer/pull/16441#issuecomment-1918517375. But since it's not enabled by default, maybe it is not a big deal.
