### ISSUE TITLE
Why did #15313 change the recommended settings for Kate in the manual?

### ISSUE THREAD

**Issue by thecnoNSMB** [rust-lang/rust-analyzer#18220]
Not everyone might want cache priming and automatic checking turned off, and the `rootIndicationFileNames` option might be helpful (because for some reason Kate doesn't use it by default?) I'm confused as to why this change was made this way.

**Comment by Veykril** [comment]
That is an example on how to change the configuration, not a recommendation for a configuration

**Comment by lnicola** [comment]
Every client is configured differently, and we'd like to have a sample snippet for as many of them as possible, either in the manual, or on the wiki. I think #15313 is explicit enough about this:

> To change rust-analyzer config options, start from the following example [...]
