### ISSUE TITLE
Nested angle brackets `<<<` are misidentified as a logical operator

### ISSUE THREAD

**Issue by maxwase** [rust-lang/rust-analyzer#18235]
**rust-analyzer version**: 0.4.2133-standalone
**rustc version**: rustc 1.81.0 (eeb90cda1 2024-09-04)

**editor or extension**: VSCode

**relevant settings**: 
```json
    "editor.semanticTokenColorCustomizations": {
        "enabled": true,
        "rules": {
            "operator": "#FFFFFF",
        }
    }
```

**code snippet to reproduce**: 
```rust
trait Assoc {
    type A;
}
struct Foo<T>(T);

impl<T> Assoc for Foo<T> {
    type A = ();
}

impl Assoc for () {
    type A = ();
}

fn left2<T>() -> Vec<<Foo<T> as Assoc>::A> {
    vec![]
}

fn left3<T>() -> Vec<<<Foo<T> as Assoc>::A as Assoc>::A> {
    vec![]
}

fn right2() -> Vec<Vec<()>> {
    vec![]
}
fn right3() -> Vec<Vec<Vec<()>>> {
    vec![]
}
```

All brackets in the snippet have `punctuation.brackets.angle.rust` as their semantic type, expect for the `left3`'s nested brackets, which are recognized as operator `keyword.operator.logical.rust`

![Image](https://github.com/user-attachments/assets/bcd3097d-3a23-433d-b9cc-9a099ea4b6c0)

Interestingly, `<<` and `>>>` do not cause problems

**Comment by Veykril** [comment]
Those are provided by vscode's text mate grammar, we don't ship that. You can enable:
```json

    "rust-analyzer.semanticHighlighting.punctuation.enable": true,
    "rust-analyzer.semanticHighlighting.punctuation.specialization.enable": true,
```
in your settings to get additional semantic highlighting tokens for punctuation which categorizes all of them as `angle`
