### ISSUE TITLE
Variables in const generic blocks have `unresolvedReference` as their semantic type

### ISSUE THREAD

**Issue by maxwase** [rust-lang/rust-analyzer#18236]
**rust-analyzer version**: 0.4.2133-standalone
**rustc version**: rustc 1.81.0 (eeb90cda1 2024-09-04)

**editor or extension**: VSCode

**relevant settings**: 
```json
    "editor.semanticTokenColorCustomizations": {
        "enabled": true,
        "rules": {
            "const": {
                "bold": true,
                "foreground": "#F0F080",
            },
            "variable": "#FFFFFF",
        }
    }
```

**code snippet to reproduce**: 
```rust
struct Foo<const G: usize>;

impl
    Foo<
        {
            const A: usize = 1;
            let a = A;

            if a > 1 as usize {
                A
            } else {
                0
            }
        },
    >
{
    fn foo() -> usize {
        const A: usize = 1;
        let a = A;

        if a > 1 as usize {
            A
        } else {
            0
        }
    }
}
```

Notice how both constant and variable (`a` and `A`) semantic types are determined correctly in the function, but not in the const generic block + type hints are not available
![Image](https://github.com/user-attachments/assets/6e4ea6fd-4a11-4c23-a556-9bed5ca5a1ba)

**Comment by ChayimFriedman2** [comment]
I don't think we lower const bodies yet, so we don't do inference for them and type analysis is not available.

**Comment by ChayimFriedman2** [comment]
Duplicate https://github.com/rust-lang/rust-analyzer/issues/7434 (also https://github.com/rust-lang/rust-analyzer/issues/8655).
