### ISSUE TITLE
Weird inlay hint for tuple struct

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust-analyzer#18259]
![Image](https://github.com/user-attachments/assets/41343247-4166-4239-8cf1-6403dddedb1a)

transcript:
```
    1 ▎   struct S(usize, usize);
    2 ▎   let s: extern "rust-call" S(usize, usize) -> S = S;
```

**Comment by ChayimFriedman2** [comment]
Technically this is not wrong. A tuple struct constructor is a function.

But otherwise, what type do you want it to show?

**Comment by lnicola** [comment]
`extern "rust-call"` does seem excessive (and probably confusing) here. I'd expect `fn(usize, usize) -> S` or `impl Fn(usize, usize) -> S`.

**Comment by flodiebold** [comment]
For 
```rust
fn foo() {}
let s = foo;
```
we just show `fn foo()`; `fn S(usize, usize) -> S` would probably be fine.
