### ISSUE TITLE
Feature req: Option to reduce quantity of syntax error red squiggles in blocks

### ISSUE THREAD

**Issue by dpkirchner** [rust-lang/rust-analyzer#18260]
I think it'd be nice to have a way to reduce how many red squiggles appear on a multi-line block of code that has a syntax error. IMO, ideally, rust-analyzer would emulate what `rustc` shows on the command line, where there's a red line to the left of the block instead of covering all of the code.

I'll share a somewhat contrived example using screenshots. Some background about this example: I'm in the middle of changing the return type of this function (on line 7), so the error is totally expected.

![Image](https://github.com/user-attachments/assets/40aed125-1a15-4272-81fe-d60eedb61a73)

All of that red is really distracting, especially when combined with the light gray type hints (which are also squiggled over).

Compare this to what `rustc` shows:

![Image](https://github.com/user-attachments/assets/c317d9e8-364e-4483-8f3f-8e53bc06e06d)

The red line starts at the top of the offending block (line 10) and extends to just below the end (line 25, the implied return), and is drawn to the left of the code. This is a lot less distracting and it's easier to see the code.

IMO, for the extension, it'd be preferable to draw a vertical red line from the start of the offending block to the end in the left gutter, sorta like in the `rustc` output, and leave the squiggles only on the line at the top of the block.

**Comment by ChayimFriedman2** [comment]
> IMO, for the extension, it'd be preferable to draw a vertical red line from the start of the offending block to the end in the left gutter, sorta like in the `rustc` output, and leave the squiggles only on the line at the top of the block.

I don't think LSP has a way to do that, and I'm not sure if VSCode has.

**Comment by dpkirchner** [comment]
> > IMO, for the extension, it'd be preferable to draw a vertical red line from the start of the offending block to the end in the left gutter, sorta like in the `rustc` output, and leave the squiggles only on the line at the top of the block.
> 
> I don't think LSP has a way to do that, and I'm not sure if VSCode has.

Perhaps it could just highlight the top and bottom line (optionally), and the first character in each intervening line? I dunno, dunno enough about vscode to say.

**Comment by flodiebold** [comment]
It's up to VSCode or in general the LSP client how to render the squiggles, especially since this is not really a Rust-specific issue. I'd suggest reporting this at VSCode.

**Comment by dpkirchner** [comment]
Ok, thanks for looking at it. Here's my workaround for now:

* Open user settings.json (ctrl-shift-P, type "user settings", choose the JSON)
* Add this:
```
    "workbench.colorCustomizations": {
        "editorError.foreground": "#00000000",
        "editorError.background": "#ff00002f",
    },
}
```

This results in an IMO more easy to parse style by replacing the squigglies entirely (and globally) with a subtle red background:
![Image](https://github.com/user-attachments/assets/d7efaaf6-f09f-4a84-a739-f2ecdca0ec0b)
