### ISSUE TITLE
rust-analyzer hangs with too many `#[test_case]`s

### ISSUE THREAD

**Issue by darichey** [rust-lang/rust-analyzer#18274]
**rust-analyzer version**: master

**code snippet to reproduce**: 
```rust
#[test_case]
#[test_case]
#[test_case]
#[test_case]
#[test_case]
#[test_case]
#[test_case]
#[test_case]
fn test() {}
```
rust-analyzer will hang while trying to analyze this file. I think it's exponential, so if it doesn't for you, just add more `#[test_case]` :)

**Comment by alibektas** [comment]
I am way over the recursion_limit as we speak, but I get no such behavior. 😄  Could you maybe share a recording where you restart the server and show how it hangs?

**Comment by alibektas** [comment]
and your rust-analyzer config would also be nice to see.

**Comment by darichey** [comment]
Sure! https://github.com/user-attachments/assets/be5d6316-2df1-482c-9aa8-129ea49222c0
As you can see, completion and inlay hints do not get responses.

I bisected to https://github.com/rust-lang/rust-analyzer/pull/18085

**Comment by darichey** [comment]
> Do you experience the same issue with #[test]?

Not by default, but if I remove the `expander.is_test()` condition so we always expand `#[test]` in the same place I added the check for `#[test_case]` in #18275, then I do experience the same behavior.
