### ISSUE TITLE
Private items are shown in completions for modules defined in bodies (e.g. in functions)

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust-analyzer#18287]
**rust-analyzer version**: `rust-analyzer version: 0.3.2137-standalone`
**rustc version**: `rustc 1.81.0 (eeb90cda1 2024-09-04)`
**editor or extension**:  VSCode v0.3.2137

<img src="https://github.com/user-attachments/assets/6d83f2be-d183-4912-9c51-9f4cca9b4513" width="300"/>

**code snippet to reproduce**: 
```rust
fn main() {
    mod nice_module {
        struct MyPrivateLife;
    }

    nice_module::
}
```

**Comment by dqkqd** [comment]
I'm not sure if I understand correctly, but checking whether `to_module` is a block module and breaking the loop if it isn't might solves this?

https://github.com/rust-lang/rust-analyzer/blob/3ddfb0da474bdf243a655a5d785de9b59c7f1397/crates/hir-def/src/visibility.rs#L140-L150

**Comment by ShoyuVanilla** [comment]
> I'm not sure if I understand correctly, but checking whether `to_module` is a block module and breaking the loop if it isn't might solves this?

@dqkqd I'm not sure cause I haven't started looking into this yet 😅
I just assigned myself to this because I'm dealing another namers/visibility issue now.
So, you can take this issue if you'd like 😄

**Comment by dqkqd** [comment]
>  So, you can take this issue if you'd like 😄

@ShoyuVanilla Sure, I'd love to
