### ISSUE TITLE
Impl blocks defined inside of `const _NAME: () = { /**/ };` are not resolved even though `const _: () = { /**/ };` works

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust-analyzer#18290]
**rust-analyzer version**: `rust-analyzer version: 0.3.2137-standalone`
**rustc version**: `rustc 1.81.0 (eeb90cda1 2024-09-04)`
**editor or extension**:  VSCode v0.3.2137

Notice how `.x1()` method call is highlighted in red. It's because RA can't resolve the symbol.
<img src="https://github.com/user-attachments/assets/dd99603d-4fd7-45d1-84cf-45d1334e2eaf" height="400"/>

What's perplexing is that merely changing the name of the constant to `_` fixes this:

<img src="https://github.com/user-attachments/assets/ac0ba24b-a1cb-4a9f-a11d-2bc4e9309ea5"  height="400"/>

**code snippet to reproduce**: 
```rust
fn main() {
    Bonnie::<()> {
        _phantom: PhantomData,
    }
    .x1();
}

trait State {}

const _IMPL: () = {
    impl State for () {}
};

struct Bonnie<S: State> {
    _phantom: PhantomData<S>,
}

impl<S: State> Bonnie<S> {
    fn x1(self) {
        todo!()
    }
}
```

**Comment by lnicola** [comment]
This is intentional, so we can skip parsing those, see also https://github.com/rust-lang/rfcs/blob/master/text/3373-avoid-nonlocal-definitions-in-fns.md.
