### ISSUE TITLE
Import suggestions do not take into account visibility

### ISSUE THREAD

**Issue by orlp** [rust-lang/rust-analyzer#18308]
I never had problems with this in the past, but suddenly rust-analyzer's import suggestions no longer take into account `pub` visibility. Unfortunately I don't have a minimal reproduction, but I do have a reproduction.

1. Clone `https://github.com/pola-rs/polars` (suggest `--depth 1`).
2. Edit file `crates/polars-expr/src/lib.rs`, add the following function:
  ```rust
fn foo() -> DataType {
    todo!()
}
```
3. Ask rust-analyzer to import `DataType` for you: ![Image](https://github.com/user-attachments/assets/b1e9fd53-a882-427b-be65-4d0f4b150dbf)
4. Suggestion is wrong, it's not visibile to us here, it suggests something else:
  ![Image](https://github.com/user-attachments/assets/f2c21473-8ae0-4008-ad6d-f30258cc2a63)
5. Suggestion is *still* wrong, it finally gets a public symbol:
  ![Image](https://github.com/user-attachments/assets/5fdfc58a-b24d-478a-8534-eeeacf90400b)

**rust-analyzer version**: rust-analyzer version: 0.4.2148-standalone (418c1365e 2024-10-15) 

**rustc version**: rustc 1.83.0-nightly (ed04567ba 2024-09-28)

**editor or extension**: VS Code

**repository link (if public, optional)**: https://github.com/polar-rs/polars

**Comment by ShoyuVanilla** [comment]
I'll try working on this
