### ISSUE TITLE
proc-macro panicked: proc-macro server did not respond with data

### ISSUE THREAD

**Issue by Faervan** [rust-lang/rust-analyzer#18319]
RA raises error:
`proc-macro panicked: proc-macro server did not respond with data: proc-macro server did not respond with data`![Image](https://github.com/user-attachments/assets/7f46e108-2b83-4c34-98ec-1562a0e393ad)

even though there is no error:
`cargo run` works fine, the derived implementation from the macro works
`cargo check` works fine

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
```
$ rust-analyzer -V
rust-analyzer 1.81.0 (eeb90cd 2024-09-04)
```

**rustc version**: (eg. output of `rustc -V`)
```
$ rustc -V
rustc 1.81.0 (eeb90cda1 2024-09-04)
```

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)
Neovim/[Mason](https://github.com/williamboman/mason.nvim), also observed in VSCode (rust-analyzer v0.3.2146)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
//

**repository link**:
[Where the error occurs](https://github.com/Faervan/yggdrasil/blob/development/crates/ysync/examples/as_bytes.rs)
[Proc macro crate](https://github.com/Faervan/yggdrasil/blob/development/crates/yserde_bytes/src/lib.rs)

**code snippet to reproduce**: 
I havn't been able to recreate the issue in a minimal example.

**Comment by Veykril** [comment]
Your proc-macro prints to stdout via `println`, that usually causes issues for rust-analyzer as it uses stdout to communicate with the server

**Comment by Faervan** [comment]
ohhh....thanks... this solved it indeed
