### ISSUE TITLE
Extension fails to start on latest nightly

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust-analyzer#18318]
The developer tools of vs code show the following:

```
console.ts:137 [Extension Host] /bin/sh: regel 1: rustc: opdracht niet gevonden
C @ console.ts:137
mainThreadExtensionService.ts:107 Activating extension 'rust-lang.rust-analyzer' failed: Command failed: rustc -V -v
/bin/sh: regel 1: rustc: opdracht niet gevonden
```

where "opdracht niet gevonden" is Dutch for "command not found".

It works fine with the latest stable version of the extension.

I suspect that https://github.com/rust-lang/rust-analyzer/pull/18281 caused this regression. cc @darichey

**Comment by bjorn3** [comment]
By the way I'm running vscode inside flatpak, but rust-analyzer automatically gets spawned outside of it by vscode afaik.

**Comment by darichey** [comment]
I agree https://github.com/rust-lang/rust-analyzer/pull/18281 could be related, but it's unclear how: the only commands it should affect are `rustup` and `rust-analyzer --version`.

FWIW, I can't repro. I also can't find where rust-analyzer is trying to run that command during activation.

**Comment by davidbarsky** [comment]
https://github.com/rust-lang/rust-analyzer/pull/18265 seems a little suspicious to me. especially since it's a regex + `exec`.

**Comment by davidbarsky** [comment]
I'll put up a PR with a fix, one moment.

**Comment by Veykril** [comment]
Oh my bad, I somehow overlooked that odd call there.

**Comment by davidbarsky** [comment]
no worries, i'm just doing a slight refactor right now to consolidate populating the symbol map.

**Comment by davidbarsky** [comment]
Opened https://github.com/rust-lang/rust-analyzer/pull/18320.
