### ISSUE TITLE
rust-analyzer analysis hangs up while mir building/evaluating in the standard library

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18326]
Since the newest stable release our CI hangs up on the linux runner.  https://github.com/rust-lang/rust-analyzer/actions/runs/11393691962/job/31702512392?pr=18305

**Comment by ChayimFriedman2** [comment]
What is the latest good PR?

**Comment by Veykril** [comment]
The problem is not a change on our side, 1.82 released yesterday and so we now run analysis stats against that, something in the standard library is causing us problems now (though its a bug in our code nevertheless, we shouldn't hang here). Also note this is not linux specific, its just that we run analysis-stats on linux only in PR CI

**Comment by Veykril** [comment]
(so with newest stable release I was referring to rust release, not rust-analyzer)

**Comment by ChayimFriedman2** [comment]
I've been running `analysis stats .` today with 1.82 on Windows with no problem (but not on linux, will check).

**Comment by Veykril** [comment]
You need to run it against the standard library, ci runs `target//debug/rust-analyzer analysis-stats --with-deps $(rustc --print sysroot)/lib/rustlib/src/rust/library/std`

**Comment by Veykril** [comment]
Right, this is the first release where the sysroot has a proper cargo workspace. EIther way we seem to not have `miri` set properly here, causing us to run a test gated behind `not(miri)`
