### ISSUE TITLE
Find all references excludes usage in macros

### ISSUE THREAD

**Issue by yellowred** [rust-lang/rust-analyzer#18321]
When finding all references of a const or a func, references inside macro_rules are excluded from the list. 
![Image](https://github.com/user-attachments/assets/937ffae7-27c9-4f7a-a94b-211b5c42ddac)
Happens in both VSCode and Helix. When I click Find References, I expect it to list the usage of the function in the macro `test_ra` as well, but it is skipped instead.

**rust-analyzer version**: rust-analyzer 1.78.0 (9b00956e 2024-04-29)

**rustc version**: rustc 1.78.0 (9b00956e5 2024-04-29)

**editor or extension**: Helix

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

**code snippet to reproduce**: 
File: ./foo.rs
```rust
use crate::{add10, A};

pub fn print_a() {
    println!("{}", A);
}

pub fn print_add() {
    println!("{}", add10());
}
```

File: ./main.rs
```rust
mod foo;

pub const A: u8 = 100;

pub fn add10() -> u8 {
    10
}

#[macro_export]
macro_rules! test_ra {
    ($e:expr) => {{
        let val = $e + A + add10();
        val
    }};
}

fn main() {
    println!("{}", test_ra!(1 + 2));
    foo::print_a();
}
```

**Comment by ChayimFriedman2** [comment]
This is known, see #7427, and is fundamentally hard to do with our current way to find usages.
