### ISSUE TITLE
r-a does not support `safe fn` in extern blocks

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18329]
https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html#safe-items-with-unsafe-extern we don't support this yet its stable now, funnily no one ever reported this it seems

**Comment by Veykril** [comment]
kind of implemented but not quite right https://github.com/rust-lang/rust-analyzer/issues/18352

**Comment by lnicola** [comment]
Anything left to do here?

**Comment by Veykril** [comment]
No this is fully covered now
