### ISSUE TITLE
Merge emitted inlayhints targetting the same ranges

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18346]
Our inlay hint infra currently emits a couple separate inlay hint objects that target the same text range. Thats a bit wasteful, we can easily merged them by turning them into parts of a single inlay hint object. This afaik also confuses zed right now where the order of these tends to get scrambled every now and then (tbf the lsp does not specify how a client should render these wrt to their order).

**Comment by listochkin** [comment]
Here's a related Zed issue: https://github.com/zed-industries/zed/issues/7928
