### ISSUE TITLE
Assist to derive `type alias = signature` for a function

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18343]
Given some function 
```rs
unsafe fn foo(param: u32) -> String { ... }
```
with the cursor on `foo` we should offer an assist that generates a type alias for the function's signature
```
type FooFn = unsafe fn(u32) -> String;
```

**Comment by Giga-Bowser** [comment]
> with the cursor on `foo` we should offer an assist that generates a type alias for the function's signature
> 
> ```
> type FooFn = unsafe fn(u32) -> String;
> ```

Any reason in particular not to use named params? As in:

```rs
type FooFn = unsafe fn(param: u32) -> String;
```
