### ISSUE TITLE
Hovering a type alias should render documentation of the aliased type if it lacks docs

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18344]
```rs
/// Docs for S
struct S;

type T = S;
```

Hovering `T` should yield the `Docs for S` documentation.

**Comment by ChayimFriedman2** [comment]
I wonder if we should also show the signature of the aliased item, or only its docs. E.g. the docs may refer to its name or type parameters which don't exist in the alias.

**Comment by dqkqd** [comment]
@ChayimFriedman2
Oh, I had oversimplified this, thinking just traversing upwards to find the docs would be sufficient.

So, in the snippet below, we should show `Docs for A` instead of `Docs for B` when hovering to `A`.
```rust
/// Docs for [`B`]
struct B;

type A = B;
```

By showing type aliases for type parameters, I think we should just keep as is, to avoid showing `u32` instead of `T` in the docs for `Box`?

```rust
type A = Box<u32>
```

**Comment by dqkqd** [comment]
Well, I found it rather hard if we need to rename the aliased type in the docs. Seem relate to #8242.

**Comment by ChayimFriedman2** [comment]
I don't think it's possible to rename the docs. Not every usage is a link, while not every same text is a reference, and modifying only some of the usages will be very confusing.

**Comment by dqkqd** [comment]
Sorry, I was misreading, I not familiar with the internal and the language yet.

So, we should just show the `Docs for B` here (maybe with the `pub struct B`) without `pub type A = B` ?

![Image](https://github.com/user-attachments/assets/5d6fbec0-18c3-4bc0-8623-a08c22ddae12)

**Comment by ChayimFriedman2** [comment]
No, we should definitely include `pub type A = B`. My question was whether we *also* need to include `pub struct B`.

**Comment by Veykril** [comment]
Why rename things? Just render the docs of the aliased thing, no need to overcomplicate this

**Comment by dqkqd** [comment]
Thank you, I'll try implementing this
