### ISSUE TITLE
hover for type with new `use<...>` captures syntax shows `{error}`

### ISSUE THREAD

**Issue by azdavis** [rust-lang/rust-analyzer#18357]
**rust-analyzer version**: rust-analyzer version: 0.3.2154-standalone (9323b5385 2024-10-20)

**rustc version**: rustc 1.82.0 (f6e511eec 2024-10-15)

**editor or extension**: VS Code v0.3.2154

**code snippet to reproduce**: 
```rust
fn foo(x: &()) -> impl Sized + use<'_> {
  x
}
```

![hover for ty with use captures causes error when displaying type](https://github.com/user-attachments/assets/839f6b73-a67b-4746-9f8f-cb89ac9d937a)

**Comment by Veykril** [comment]
These are currently unimplemented https://github.com/rust-analyzer/rust-analyzer/blob/9a94802814a20a14e4ac0fd14216213492be9237/crates/hir-def/src/hir/type_ref.rs#L383
