### ISSUE TITLE
Add/remove Some() or Ok() or Err() wrapper

### ISSUE THREAD

**Issue by adamchalmers** [rust-lang/rust-analyzer#18383]
I frequently find myself refactoring code and needing to either add or remove a `Some()` wrapper from an expression. Similar need for `Ok()` and `Err()`. It'd be great if Rust Analyzer had an action to add or remove these wrappers.

I can approximate this somewhat with macros of key sequences in my editor, but it'd be neat if RA could do it :)

**Comment by lnicola** [comment]
In some cases we offer these as diagnostic quick fixes:

```rust
let x: Option<i32>  = 42; // Wrap in Some
let x: i32 = Some(42); // no Unwrap available

let x: Result<i32, ()>  = 42; // Wrap in Ok
let x: i32 = Ok(42); // No Unwrap available
````
