### ISSUE TITLE
`#[test_log_macros::test]` reports unresolved macro `panic!()`

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18411]
```rs
#[test_log_macros::test]
//^^^^^^^^^^^^^ unresolved macro `panic!`
fn f() {}
```
with `test_log_macros = "0.2.14"`

**Comment by ChayimFriedman2** [comment]
Can't reproduce (Windows, VSCode).

**Comment by Veykril** [comment]
Hmm odd, I get this in the salsa tests https://github.com/salsa-rs/salsa/

**Comment by ChayimFriedman2** [comment]
[I don't see `test_log_macros` in salsa](https://github.com/search?q=repo%3Asalsa-rs%2Fsalsa%20test_log_macros&type=code).

**Comment by Veykril** [comment]
ah my bad, they are re-exported https://github.com/salsa-rs/salsa/blob/5eed7e90783b00e34f5fdf24486f1caadf86f69a/tests/accumulate-execution-order.rs#L8

**Comment by ChayimFriedman2** [comment]
Oh I can reproduce now: MCVE:
```rust
fn accumulate_execution_order() {
    mod init {
        pub fn init() {
            panic!();
        }
    }
}
```
I also get another error "no such associated item" on `push_logs::accumulated::<Log>(db)`.

**Comment by Veykril** [comment]
> I also get another error "no such associated item" on `push_logs::accumulated::<Log>(db)`.

That one is expected, see https://github.com/salsa-rs/salsa/issues/607
