### ISSUE TITLE
`prelude` unavailable in latest rust-analyzer releases

### ISSUE THREAD

**Issue by indietyp** [rust-lang/rust-analyzer#18423]
Since a couple of days, the prelude has been missing from my installation, a complete re-install via rustup, removing the `target` folder (either by deleting it or `cargo clean`), and clearing cargo cache all didn't help.

I did a tiny bit of dissecting, and the problem started appearing between `rust-analyzer 1.84.0-nightly (3ed6e3cc 2024-10-17)` and `rust-analyzer 1.84.0-nightly (e92993db 2024-10-18)`, using any rust-analyzer version prior to 2024-10-18 does not result in the issue.

The issue is that the prelude is seemingly missing, prelude types such as `Option` are not imported/shown. I've attached examples of what I mean.

This also propagates to macros such as `tracing`, where I am getting errors, such as: unresolved macro `line` (macro-error), see the picture below.

The logs seem to indicate that RA is stuck during some kind of resolution (the log has been uploaded as an LFS object into the regression repository).

**rust-analyzer version**: rust-analyzer 1.84.0-nightly (df4ca44d 2024-10-27)

**rustc version**: rustc 1.84.0-nightly (df4ca44d3 2024-10-27)

**editor or extension**: Zed, replicated in Zed Preview and VSCode

**relevant settings**: `RA_LOG=info`

**repository link**: https://github.com/indietyp/rust-analyzer-regressions/tree/prelude-missing, branch prelude missing

![Image](https://github.com/user-attachments/assets/6ed750cf-4934-4661-8cc8-d047f9fce6ea)
![Image](https://github.com/user-attachments/assets/3885ba96-050c-4af4-855c-a1dbd5acf122)
![Image](https://github.com/user-attachments/assets/3413a797-41d9-4928-9225-092219b124d1)

**Comment by Veykril** [comment]
This does indeed look like chalk hanging up, though we haven't done anything special here I think. Given the very new rustc version it might be some change in the standard library

**Comment by flodiebold** [comment]
Unresolved macros don't indicate Chalk though, do they 🤔 

The example project has a rust-toolchain.toml with specific components, I'm not sure whether that means rust-src will be included?

**Comment by Veykril** [comment]
> Unresolved macros don't indicate Chalk though, do they 🤔
> 
> The example project has a rust-toolchain.toml with specific components, I'm not sure whether that means rust-src will be included?

i was going off of the linked log (in the rep) but that might not even be relevant on a second look

**Comment by indietyp** [comment]
I just tried to explicitly add rust-src (it's being installed), no change.

```
info: syncing channel updates for 'nightly-2024-10-28-aarch64-apple-darwin'
info: latest update on 2024-10-28, rust version 1.84.0-nightly (df4ca44d3 2024-10-27)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'llvm-tools'
info: downloading component 'miri'
info: downloading component 'rust-analyzer'
info: downloading component 'rust-docs'
info: downloading component 'rust-src'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'llvm-tools'
info: installing component 'miri'
info: installing component 'rust-analyzer'
info: installing component 'rust-docs'
info: installing component 'rust-src'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
```

**Comment by indietyp** [comment]
> Unresolved macros don't indicate Chalk though, do they 🤔

but the problem during resolve is simply that `line!` (a macro that is in the prelude) couldn't be found. So it isn't really a macro error. Expansion errors out because it can't fine the `line` (and after that `file`) macro

**Comment by chrisp60** [comment]
I imagine this doesn't help much but I am also seeing similar / identical issues on neovim.

`:MasonInstall rust-analyzer@nightly`

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.84.0-nightly (df4ca44d3 2024-10-27)

I noticed the issue by `None` being linted as a false positive for `non_snake_case`, while hover info showing its path as `core::option::Option`. When messing with things I would also come across RA completely dropping requests with an error close to "server stopped request", but that part could be unrelated / my own configuration issues.

**Comment by Veykril** [comment]
Is this happening for older rust nightlies as well? (since both of you posted rustc 1.84.0-nightly (df4ca44d3 2024-10-27))

**Comment by indietyp** [comment]
I accidentally actually used `rust-analyzer 1.84.0-nightly (df4ca44d 2024-10-27)` on the toolchain of `2024-10-17`, and that seemed to work. This leads to me believe that _something_ in the std changed that makes chalk freak out.

Hope that helps!

**Comment by indietyp** [comment]
Using `cargo-bisect-rustc` I was able to pin down the commit (sadly not the unrolled commit) to https://github.com/rust-lang/rust/commit/db8043bb199705e72246ca43d4af1e9dbe7d55be.

This commit is the likely candidate where it all stopped working.

(The command I used was: `cargo-bisect-rustc --start=2024-10-17 --end=2024-10-28 --prompt --with-src --with-dev -c rust-analyzer`, then changing the toolchain each time, restarting RA and seeing if I get any hints / errors).

I was sadly not able to drill down further which commit is the culprit. I'll investigate further.

**Comment by indietyp** [comment]
My current hunch is that it has something to do with: https://github.com/rust-lang/rust/pull/131857, I enabled debug logs in VSCode and looked through it, and I found a bunch of repeating `CoerceUnsized`. Now I don't know if that is coincidence, or something - but might(?) be the reason. I am just guessing at this point^^

**Comment by lnicola** [comment]
The lockfile version bump also looks interesting, but it doesn't seem to cause problems in stable Cargo.

**Comment by Veykril** [comment]
That PR has no effect for us, it doesnt touch the std lib nor any compiler crates we use

**Comment by indietyp** [comment]
Okay, so, I got a bit desperate and removed a bunch of old cargo binaries, while doing so it turned out that my default toolchain (nightly) was way behind (1.77-nightly) updating the default toolchain to the newest one (2024-11-01) seems to have solved the problem. I do not know _how_ that solve the problem, and also don't understand how the default toolchain installed via rustup would influence RA.

Mysterious.
