### ISSUE TITLE
rust-analyzer interupts neovim while typing

### ISSUE THREAD

**Issue by vikulikov** [rust-lang/rust-analyzer#18434]
While typing in neovim rust-analyzer interrupts the editor with the error message 
`rust_analyzer: -32802: server cancelled the request`

![Image](https://github.com/user-attachments/assets/e25510e0-2e21-4909-863b-3b721c08631f)

**rust-analyzer version**: rust-analyzer 0.0.0 (3b3a87fe9 2024-10-27)

**rustc version**: rustc 1.82.0 (f6e511eec 2024-10-15)

**editor or extension**: neovim

**relevant settings**:
```lua
 settings = {
                ['rust-analyzer'] = {
                    server = { path = "/opt/homebrew/bin/rust-analyzer" },
                    assist = {
                        importMergeBehavior = "last",
                        importPrefix = "by_self",
                    },
                    files = {
                        excludeDirs = { "target" }
                    },
                    workspace = {
                        symbol = {
                            search = {
                                limit = 3000
                            }
                        }
                    },
                    procMacro = {
                        enable = true
                    },
                    diagnostics = {
                        enable = true,
                        disabled = { "unresolved-proc-macro" },
                        enableExperimental = true,
                    },
                    check = {
                        -- command = "clippy"
                    },
                    cargo = {
                        features = "all",
                        loadOutDirsFromCheck = true,
                    }

                },
            }
```

**Comment by lnicola** [comment]
I think this is a client issue, it should log those errors, but not pop them up. Which LSP plugin are you using?

**Comment by vikulikov** [comment]
Ok, thanks. Will try to figure this on nvim side. I use `lspconfig` for the configuration and `cmp_nvim_lsp` for capabilities

**Comment by gelfand** [comment]
Hello, have you fixed it?

**Comment by lnicola** [comment]
You should probably try https://github.com/mrcjkb/rustaceanvim instead.

**Comment by gelfand** [comment]
> You should probably try https://github.com/mrcjkb/rustaceanvim instead.

Same issue with it

**Comment by vikulikov** [comment]
> Hello, have you fixed it?
I've created an issue in [neovim repo](I've created an issue in neovim repo). @Jesse-Bakker suggested a workaround to ignore this error

**Comment by lnicola** [comment]
Might be worth fixing in `rustaceanvim`, then.

**Comment by lihe6666** [comment]
+1

**Comment by Veykril** [comment]
For the ones running into this, would be good to see if the release from Oct 30th fixed it, as that should contain https://github.com/rust-lang/rust-analyzer/pull/18432

**Comment by dr-kernel** [comment]
I have this problem as well.  Been fighting lots of RA issues lately (seems to be related to config with the latest release).  I'm also using rustaceanvim.  I reverted to `2024-10-14` and that's fixed the issue.  I've tried this one neovim `0.10.0` and `0.10.2_1`

**Comment by vikulikov** [comment]
I guess this issue can be closed as it is being fixed on the [neovim side](https://github.com/neovim/neovim/issues/30985). 
Just duplicating current [workaround](https://github.com/neovim/neovim/issues/30985#issuecomment-2447329525) to configure neovim to ignore such messages. Or `rust-analyzer` can be downgraded to `2024-10-14` version until next neovim version is released

**Comment by hanpham32** [comment]
I'm on Neovim 0.10.0 and still facing this problem. Downgrading `rust-analyzer` to `2024-10-14` helped.

2-cent tip :^)
```
:MasonUninstall rust-analyzer
:MasonInstall rust-analyzer@2024-10-14
```

**Comment by eikopf** [comment]
I also ran into this problem on v0.10.2, including with the referenced workaround in my config. In my case the solution was to remove `rust-analyzer` from mason entirely and let neovim find the version installed by `rustup`.
