### ISSUE TITLE
associated item defined inside fn unable to be found outside of fn it was defined in

### ISSUE THREAD

**Issue by jhgg** [rust-lang/rust-analyzer#18439]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) rust-analyzer version: 0.4.2159-standalone 

**rustc version**: (eg. output of `rustc -V`) rustc 1.81.0 (eeb90cda1 2024-09-04)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable) vscode

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

**code snippet to reproduce**: 
```rust
fn main() {
    hello::world();
    // E:  ^^^^^       no such associated item
}

struct hello {}
fn hello() {
    impl hello {
        pub fn world() {}
    }

    hello::world(); // this is fine.
}
```

---

I vaguely recall this being deliberate behavior, since r-a is not descending into function definitions to find impl's for use outside of that function, but I can't find an issue for it. 

This is minimized from salsa3's `salsa::tracked` [macro expansion](https://github.com/salsa-rs/salsa/blob/dfbe6d67f47c67387a649e71ebeea22c313d43bf/components/salsa-macro-rules/src/setup_tracked_fn.rs#L229-L245), which creates a struct that is named the same of the function, and defines an `impl` inside of it. I think salsa can probably move the impl defintion outside of the fn to make rust-analyzer work if this isn't solvable in rust-analyzer.

**Comment by ChayimFriedman2** [comment]
This is indeed deliberate, @Veykril said they have no intent of changing this behavior, and [salsa should be adapted](https://github.com/salsa-rs/salsa/issues/607). There is also a lint ([`non_local_definitions`](https://doc.rust-lang.org/stable/rustc/lints/listing/allowed-by-default.html#non-local-definitions)) in rustc that catch this cases (salsa allows it).
