### ISSUE TITLE
rust-analyzer silently download dependencies

### ISSUE THREAD

**Issue by Yuuki1578** [rust-lang/rust-analyzer#18455]
Does the rust-analyzer now need some dependencies to work with? When i use rust-analyzer at August 2024 or later that (before october, i dont know the version), it work just fine without internet connection. I use it now without internet connection and the hover output from editor looks like this:

![Image](https://github.com/user-attachments/assets/5618de5c-a552-4043-a2f8-7d8a90ded2d0)

I know that the `String` type is included in the prelude, but somehow rust-analyzer is unable to find the type.

And when i turn the internet connection on and restart the LSP inside the editor, rust-analyzer will download extra dependecies, like:

![Image](https://github.com/user-attachments/assets/008c5d32-5d2d-498e-af25-924bf06ce586)

**platform**: Termux aarch64 android

**rust-analyzer version**: 0.0.0

**rustc version**: rustc 1.82.0 (f6e511eec 2024-10-15) (built from a source tarball)

**editor or extension**: [Helix](https://www.helix-editor.com)

**code snippet to reproduce**: 
```bash
rust-analyzer # invoked by helix
```

**Comment by ChayimFriedman2** [comment]
I believe what changed is in rust, not in r-a, that stdlib has a proper Cargo project now so rust-analyzer can index it properly, which means it's downloading std's dependencies.

**Comment by lnicola** [comment]
We also run `rustup component add rust-src` if it's not available. I don't think it's such a big deal.
