### ISSUE TITLE
In VSCode, hovering over the String type does not bring up a documentation hover window.

### ISSUE THREAD

**Issue by trumansdo** [rust-lang/rust-analyzer#18489]
Using the latest VSCode and rust-analyzer on Windows 10, I have tried both the preview and release versions of rust-analyzer, and have reinstalled multiple versions of the toolchain using rustup, but none of these have worked.

**Comment by ShoyuVanilla** [comment]
Are other hoverings working?

**Comment by trumansdo** [comment]
> Are other hoverings working?

Yes, it appears that only the hover for Rust's built-in types is not showing the pop-up window.

**Comment by ShoyuVanilla** [comment]
I guess that `rust-src` may not be installed in your env. (or rust-analyzer fails to locate it)
Could you run `rust up component list` and check whether `rust-src` is listed there? If not, you can add it with `rustup component add rust-src` and the hovering will work

**Comment by trumansdo** [comment]
> I guess that `rust-src` may not have been installed in your env. (or rust-analyzer fails to locate it) Could you run `rust up component list` and check whether `rust-src` is listed there? If not, you can add it with `rustup component add rust-src` and the hovering will work

I found the reason, but I think it's strange. The cause is that I am in an internal network environment, and the proxy service configured by cargo failed. After I changed it, it worked normally. However, I still think this should be a problem. Why should the hover tips and jump of the source code depend on whether cargo is working properly?

**Comment by lnicola** [comment]
> . Why should the hover tips and jump of the source code depend on whether cargo is working properly?

They don't if you install `rust-src` properly. If you don't, we try to install it for you, but don't propagate the proxy settings from Code (https://github.com/rust-lang/rust-analyzer/issues/9448), so it fails.

**Comment by trumansdo** [comment]
> > . Why should the hover tips and jump of the source code depend on whether cargo is working properly?
> 
> They don't if you install `rust-src`, otherwise there's no source to jump to. If you don't, we try to install it for you, but don't propagate the proxy settings from Code ([#9448](https://github.com/rust-lang/rust-analyzer/issues/9448)), so it fails.

But I had install rust-src by rustup before this problem occured, and without using cargo to download. My rustup proxy settings is correct, just forget to set cargo proxy.
