### ISSUE TITLE
Not sure what's wrong in Cursor

### ISSUE THREAD

**Issue by alper** [rust-lang/rust-analyzer#18481]
I don't get any completions in Cursor. It's probably an issue with them but more in general any time I see a rust completion work, it feels like a happy accident more than something I can rely. on.

**Comment by lnicola** [comment]
![Image](https://github.com/user-attachments/assets/027a26eb-0a5a-441b-9987-64e440a10135)

Do completions work for other types like `String`?

**Comment by Wilfred** [comment]
I'm guessing the @alper means the Cursor editor, https://www.cursor.com/?

**Comment by lnicola** [comment]
Bah. So do you have `rust-src` installed?
