### ISSUE TITLE
There are some leftovers of the no-longer-existing "platform-intrinsic" ABI in RA

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#18491]
Grepping for `PlatformIntrinsic` and `platform-intrinsic` shows some results; this can all be removed -- that ABI does not exist any more.

**Comment by RalfJung** [comment]
Looks like that was in https://github.com/rust-lang/stdarch/commit/56087ea170d878a7a57b3a5725e0c00f5f5cad70, which probably propagated to the rustc repo shortly thereafter.

**Comment by RalfJung** [comment]
The Rust compiler itself removed support for them in https://github.com/rust-lang/rust/pull/121516, so at that point (Feb 27th, 2024) they were definitely gone from the standard library.

**Comment by Veykril** [comment]
Okay then its safe for us to remove
