### ISSUE TITLE
Function error underlining

### ISSUE THREAD

**Issue by oiyl** [rust-lang/rust-analyzer#18502]
When there is an error in a function (such as a mismatched type when the function isn't finished yet, or mismatched curly braces, etc.), the Rust Analyzer plugin underlines the entire function, which can be very distracting. I was wondering if there is a way to fix this. Many thanks to the maintainers and contributors of this extremely useful extension.

![Image](https://github.com/user-attachments/assets/f607ab62-c509-45dc-a967-ae68fa910c71)

**Comment by ChayimFriedman2** [comment]
I think this error is from rustc, not rust-analyzer, so I don't believe we can fix that.

**Comment by oiyl** [comment]
> I think this error is from rustc, not rust-analyzer, so I don't believe we can fix that.

oh, in that case that's my bad, thanks regardless.
to anybody else who maybe stumbles upon this, an acceptable workaround for me i just experimented with is 

```json
"workbench.colorCustomizations":{
    "editorError.foreground": "#00000000",
    "editorWarning.foreground": "#00000000"
    "editorInfo.foreground": "#00000000",
}
``` 

in settings.json

+ errorlens plugin 

![Image](https://github.com/user-attachments/assets/01608d27-5a1b-4c2e-a487-888ac505bef8)
