### ISSUE TITLE
Analyzer fails to detect new filename after altering casing twice via VSCode rename command

### ISSUE THREAD

**Issue by Shelim** [rust-lang/rust-analyzer#18516]
**rust-analyzer version**: 0.3.2180-standalone (30e71b609 2024-11-10)

**rustc version**: 1.84.0-nightly (1e4f10ba6 2024-10-29)

**editor or extension**: VS Code

Version: 1.95.0-insider
Commit: 38dc6ac5a771cc94bde1344722bb2d02c80096ea
Date: 2024-10-25T22:08:52.005Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

**relevant settings**: Windows 11 x64, other settings at default values

**repository link (if public, optional)**: N/A

**steps to reproduce**: 

1. Create a new library project with two files inside

`src/lib.rs`
`src/FOo.rs`

2. fill `src/lib.rs` with:

```rust
pub mod FOo;
```

// Note, at this step I realized a typo. Knowing Windows has problems with altering case only when changing filenames, I executed two changes:

3. Rename `src/FOo.rs` into `src/FOo2.rs` from within VS Code. Agree to Rust Analyzer refactoring
4. Rename `src/FOo2.rs` to `src/Foo.rs` from within VS Code. Agree to Rust Analyzer refactoring again

**Expected behaviour**

Rust analyzer should pickup new casing of the file

**Actual behaviour**

File content is grayed out. Context help shows `This file is not included anywhere in the module tree, so rust-analyzer can't offer IDE services.`. Applying Quick Fix attempts to put additional `mod FOo;` inside `src/lib.rs` despite reported file name being displayed correctly as `src/Foo.rs` both in-VSCode and in windows explorer

**Additional info**

- Restarting VS Code and purging `target` directory had no effect on the issue, and it is still observed.
- Attempted to reproduce it before submiting on fresh project has been successful. Above repro steps are enough to re-trigger problem with 3/3 attempts

**Comment by flodiebold** [comment]
This is a known VSCode bug; see #9947.
