### ISSUE TITLE
Map new nodes in replacement edits to their mutable equivalents in SyntaxEditor

### ISSUE THREAD

**Issue by DropDemBits** [rust-lang/rust-analyzer#18525]
`SyntaxEditor` should handle transform any node in an edit that reference the original syntax tree into their mutable equivalents, but seems like I forgot this case for the new nodes in replace edits 😅. For now it should be okay to use `clone_for_update` and add a fixme, and then we can remove those fixmes once `SyntaxEditor` is fixed.

_Originally posted by @DropDemBits in https://github.com/rust-lang/rust-analyzer/pull/18495#discussion_r1838996205_

**Comment by Giga-Bowser** [comment]
Would this also mean we can remove `clone_for_update` from methods in `syntax::ast::syntax_factory::constructors`, or should we only handle making mutable clones for nodes found in the `SyntaxEditor`'s original tree?
