### ISSUE TITLE
Autocompletion values change as you hover over them

### ISSUE THREAD

**Issue by CosmicSyntax** [rust-lang/rust-analyzer#18536]
**rust-analyzer version**: (ba56d9b9b5 2024-11-17)
**rustc version**: rustc 1.82.0 (f6e511eec 2024-10-15)

**editor or extension**: Neovim

The latest version of Rust-Analyzer is displaying some weird behavior with autocomplete.  When you hover over the values, they change.  As depicted below:

![Image](https://github.com/user-attachments/assets/78c7599c-4220-4a37-8722-49fc4b464851)

**Comment by DianQK** [comment]
Can you try to modify `cmp.select_next_item()` to `cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })`?

**Comment by yayakame** [comment]
> Can you try to modify `cmp.select_next_item()` to `cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })`?

I've been having the same issue for a while, the above fixed it for me.

**Comment by GloopShlugger** [comment]
having the same issue with Helix

**Comment by DianQK** [comment]
> having the same issue with Helix

Ha, I can also reproduce: After typing `pr`, wait for the autocomplete suggestions to appear, then press `i`. Once the new autocomplete suggestions appear, press Tab.

**Comment by CosmicSyntax** [comment]
> Can you try to modify `cmp.select_next_item()` to `cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })`?

I can also confirm this works for me as well. I'll go ahead and close this issue.  Thanks for all your help!

**Comment by tgross35** [comment]
I don't think this should have been closed - requiring a config update to avoid broken behavior doesn't seem right.

I opened https://github.com/rust-lang/rust-analyzer/issues/18547 before having seen this.

**Comment by jrmoulton** [comment]
This same issue exists in Helix

**Comment by night-kat** [comment]
i have the same issue in nvchad. for me i just did :MasonInstall ```rust-analyzer@2024-09-30```
to install an older version as a temp fix. i might try the fix suggested above
