### ISSUE TITLE
Certain traits cannot be auto-imported

### ISSUE THREAD

**Issue by Aloso** [rust-lang/rust-analyzer#18553]
**rust-analyzer version**: 0.3.2188

**rustc version**: rustc 1.84.0-nightly (a93c1718c 2024-10-24)

**editor or extension**: VSCodium

**code snippet to reproduce**: 
```rust
struct MyRange {}

impl PartialOrd<|CARET|> for MyRange {}
```

Pressing Ctrl-Space opens the autocomplete menu, und selecting the `PartialOrd` trait should auto-import it:

![Image](https://github.com/user-attachments/assets/c6d74c66-6b01-4cfd-b2b6-b688c9c7bc5f)

But when pressing Enter, nothing happens. It's the same when selecting any of the traits in this list, which appears to be hard-coded:

![Image](https://github.com/user-attachments/assets/b7b6d017-89dc-4086-9344-91bb1fd73943)

**Expected behavior**: Selecting a trait auto-imports it
**Actual behavior**: The trait is not auto-imported

**Comment by ChayimFriedman2** [comment]
`PartialOrd` is in the prelude, it doesn't need to be imported.
