### ISSUE TITLE
An option to disable auto parentheses insertion

### ISSUE THREAD

**Issue by DogLooksGood** [rust-lang/rust-analyzer#18579]
Currently auto parentheses insertion doesn't work well in some edge cases. The closing parentheses is not always inserted in the correct position(It might be impossible to achieve) and sometimes it results in an unbalanced situation. 

An option to disable the automatic parentheses insertion would be sweet.

**Comment by ChayimFriedman2** [comment]
I think the editor is responsible for that, not rust-analyzer.

**Comment by DogLooksGood** [comment]
@roife showed me, it's handled here.

https://github.com/rust-lang/rust-analyzer/blob/b65911d5eecfa562532549ef7e70e460eb042e2c/crates/ide/src/typing.rs#L103

**Comment by flodiebold** [comment]
Would be addressed by #18522.
