### ISSUE TITLE
problem with autocomplete function visibility & re-exports

### ISSUE THREAD

**Issue by redactedontop** [rust-lang/rust-analyzer#18582]
**rust-analyzer version**: 0.3.2196-standalone (327ab2958 2024-11-24)

**rustc version**: rustc 1.84.0-nightly (9b18a122f 2024-10-26)

**editor or extension**: VSCode; 0.3.2196

**code snippet to reproduce**: 
```rust
#[doc(hidden)]
#[macro_export]
macro_rules! dispatch {
    ($value:expr, $sinks:expr) => {
        for sink in $sinks {
            sink($value).await;
        }
    };
}

#[doc(inline)]
pub use dispatch; // NOT VISIBLE ON RUST-ANALYZER AUTOCOMPLETE
```

**Comment by redactedontop** [comment]
Updating nightly using rustup to see if it changes anything.

**Comment by redactedontop** [comment]
Nope, nada.

**Comment by ChayimFriedman2** [comment]
Works fine for me:
![Image](https://github.com/user-attachments/assets/9c64763f-4e22-462b-a0d5-17b423e478e6)

**Comment by redactedontop** [comment]
My issue, closing <3
