### ISSUE TITLE
Feature request: force use of a specific toolchain

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#18585]
When using RA in the rustc repo, a problem comes up when one adds `compiler/rustc_codegen_cranelift/Cargo.toml` to the `linkedProjects`: that folder contains a `rust-toolchain` file, and RA honors that file and then fails to load since I don't have that toolchain installed. It doesn't make a ton of sense for that one folder to use a different toolchain than the rest of the rustc workspace, so I'd like to avoid having to install even more different nightly versions of Rust, and just force the use of the `nightly` toolchain for everything. Would be nice if there was a setting for that. :)

**Comment by ChayimFriedman2** [comment]
I think you can do that by setting `"rust-analyzer.server.extraEnv": { "RUSTUP_TOOLCHAIN": "nightly" }`.

**Comment by RalfJung** [comment]
Yes that seems to work, amazing -- thanks. :-)
