### ISSUE TITLE
RA cannot resolve a trait implementation of a structure

### ISSUE THREAD

**Issue by pan93412** [rust-lang/rust-analyzer#18580]
rust-analyzer cannot resolve the import of the trait [`SeriesMethods`](https://docs.rs/polars/latest/polars/prelude/trait.SeriesMethods.html#method.value_counts):

![Image](https://github.com/user-attachments/assets/f6f8f2b6-8b21-4c95-90f9-7aec953a5c05)

This issue prevents rust-analyzer from finding the method `value_counts`:

![Image](https://github.com/user-attachments/assets/3e440c69-694e-4566-b2f2-9e9091b5fd86)

It might be related to #15243.

**rust-analyzer version**: 0.3.2196-standalone (327ab2958 2024-11-24)

**rustc version**: rustc 1.82.0 (f6e511eec 2024-10-15)

**editor or extension**: VS Code, 0.3.2196

**relevant settings**: N/A

**repository link (if public, optional)**: https://github.com/pan93412/aoc2024rs/blob/master/src/bin/polars_bug.rs

**code snippet to reproduce**: 

```toml
[dependencies]
polars = { version = "0.44.2", features = ["polars-ops"] }
```

```rust
use polars::prelude::*;

fn main() {
    let df = df!(
        "column_1" => [1, 2, 3, 4, 5],
        "column_4" => [5, 4, 3, 2, 1]
    ).unwrap();

    dbg!(df.column("column_1").unwrap().as_series().unwrap().value_counts(false, false, "counts".into(), false).unwrap());
}
```

---

Workaround: find the definition of `SeriesMethods`, and use it directly:

![Image](https://github.com/user-attachments/assets/8fad0c03-31a1-4047-ade2-4a555f91638a)

**Comment by usamoi** [comment]
minimal reproduce:

```rust
#![allow(unused_imports)]

pub mod fn_call {
    pub trait FnCall {
        fn fn_call(&self);
    }

    impl FnCall for () {
        fn fn_call(&self) {}
    }
}

pub mod reexport_2 {
    pub(self) use crate::reexport_1::*; // if you comment this line, ra could resolve `FnCall`
    pub use crate::reexport_1::*;
}

pub mod reexport_1 {
    pub use crate::fn_call::*;
}

// if you move `reexport_1` before `reexport_2`, ra could resolve `FnCall`

fn main() -> Result<(), Box<dyn std::error::Error>> {
    use reexport_2::*;
    let _f = <dyn FnCall>::fn_call; // ra cannot resolve `FnCall`, and resolves `fn_call` incorrectly
    Ok(())
}
```
