### ISSUE TITLE
VSCode pre-release extension automatically adding $0 when attempting to type a generic

### ISSUE THREAD

**Issue by Admiralfeb** [rust-lang/rust-analyzer#18624]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) 
0.4.2208-standalone

**rustc version**: (eg. output of `rustc -V`)
rustc 1.83.0 (90b35a623 2024-11-26)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)
VSCode v1.95.3. extension version: v0.4.2208

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**code snippet to reproduce**: 
```rust
// add your code here
variable_name::<$0>
```

When adding `::<` to a variable or function call, `$0>` is automatically added. This is only occurring in pre-release version of the extension at the moment. Shifting to stable resolves this issue.

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/18616
