### ISSUE TITLE
One Dark Pro fontStyle for Rust is displayed incorrectly

### ISSUE THREAD

**Issue by acathe** [rust-lang/rust-analyzer#18638]
**rust-analyzer version**: v0.3.2204

**rustc version**: v1.81.0

**editor or extension**: VSCode

**relevant settings**: Nothing has changed

**repository link (if public, optional)**: [One Dark Pro‘s Issue](https://github.com/Binaryify/OneDark-Pro/issues/835)

**code snippet to reproduce**:

```rust
struct temp;

#[allow(dead_code)]
impl temp {
    fn should_bold(&self, should_italic: i32) {
        let _ = should_italic;
    }

    fn should_bold_too(&mut self, should_italic_too: &mut i32) {
        //! but it's not bold

        let _ = should_italic_too; // but it's not italic
    }
}
```

参考 [One Dark Pro‘s Issue](https://github.com/Binaryify/OneDark-Pro/issues/835)。

After using rust-analyzer, the fontStyle for Rust is displayed incorrectly.

According to the design of One Dark Pro, function parameters should be italicized, but they are currently displayed in regular font.

<img width="516" alt="Screenshot 2024-12-09 05 55 18" src="https://github.com/user-attachments/assets/3621a63d-ec5c-41bb-b3f0-4ecc53ee1a1a">

When rust-analyzer cannot analyze the code, the code display is normal. You can create a temporary page using Command+N and then set it to Rust format. At this point, using the above code, mut is displayed correctly.

<img width="513" alt="Screenshot 2024-12-09 06 03 29" src="https://github.com/user-attachments/assets/0d227ace-c1ff-4358-93e8-8a1f12cda977">

It seems that the issue lies in rust-analyzer's handling of mut variables, which adds an underline to mut variables to prompt the developer. One Dark Pro seems unable to display these underlined texts correctly.

**Comment by Veykril** [comment]
> One Dark Pro seems unable to display these underlined texts correctly.

That sounds like a problem with the theme not rust-analyzer.
You can disable the underlining behavior via 
```toml
    "editor.semanticTokenColorCustomizations": {
        "rules": {
            "*.mutable:rust": {
                "fontStyle": ""
            },
        }
    },
```

**Comment by acathe** [comment]
Thank you for your response! I understand now.

Based on the performance, it indeed seems to be an issue with the Theme. I tried another theme and confirmed that the italic style can work together with the underline from ra.

The underline is a very useful marker, and I do not plan to disable it for now. I will continue to follow up on this issue in the One Dark Pro's issue tracker.

Thank you for your response.

**Comment by acathe** [comment]
I tried disabling the underline, but it didn’t resolve the issue. Now, I am attempting to adjust other options to make it visually consistent with One Dark Pro.
```
{
    "editor.semanticTokenColorCustomizations": {
        "rules": {
            "method:rust": {
                "bold": true
            },
            "parameter:rust": {
                "italic": true
            }
        }
    }
}
```
