### ISSUE TITLE
Extract into function should preserve existing parameter order

### ISSUE THREAD

**Issue by emilk** [rust-lang/rust-analyzer#18639]
### Problem
I often have a list of similar "context" parameters to my functions, and I try to be consistent with their order. For example:

```rs
fn foo_ui(ctx: &Context, ui: &mut Ui, foo: &Foo) {
    …
}

fn bar_ui(ctx: &Context, ui: &mut Ui, bar: &Bar, option: Option) {
    …
}
```

When calling "Extract to function" on some code, Rust analyzer ignores this parameter order and I often end up with functions where I need to manually rearrange the parameter order to my liking.

### Suggested solution 
When "Extract to function" decides the parameter order of the new function, it should use the following algorithm:

A) Categorize the arguments based on wether or not they were parameters to the already existing function
B) If yes, put them first, and in the same order as in the existing function
C) if no, put them last, in whatever order (I have no strong opinion here - can use same heuristic as the current code)

### Effect

``` rs
fn existing(a: A, b: B, c: C) {
    let x = 32;
    let y = 1.0;

    long_code_block_that_uses(x,b,a,y) // <--- call "Extract to function" on this code block
}
```

Results in ->

```rs
fn existing(a: A, b: B, c: C) {
    let x = 32;
    let y = 1.0;
    fun(a, b, x, y);
}

fn fun(a: A, b: B, x: i32, y: f32) {
    long_code_block_that_uses(x,b,a,y)
}
```

**Comment by roife** [comment]
Since we would lower params in order, can we sort `locals` by `binding_id` here?

https://github.com/rust-lang/rust-analyzer/blob/99a6ecd41e5e458b3f4c2142b29a80d77ecda248/crates/hir/src/lib.rs#L3622-L3626

**Comment by Veykril** [comment]
We could probably do that
