### ISSUE TITLE
LSP references cover `into` and `from`

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust-analyzer#18655]
Right now they don't really do much:

```rs
struct A;
struct B;
impl From<A> for B {
    fn from(_: A) -> B {
        B
    }
}

fn foo() -> B {
    A.into()
}
```

I would expect LSP references to show up in:
- A: Show the .into() call. It works for `B`
- from: show the .into() call, also show up in "LSP incoming calls"

I would also expect this to work on `?` after it's been desugared.

**Comment by roife** [comment]
We might need to implement #18316 first.

**Comment by Veykril** [comment]
That does not sound like something the references call should do to me, as raised https://github.com/rust-lang/rust-analyzer/issues/18316 would cover this more correctly.
