### ISSUE TITLE
How to configure rust-analyzer with rust toolchain 1.70.0 ?

### ISSUE THREAD

**Issue by MathieuSoysal** [rust-lang/rust-analyzer#18661]
Hello,

Currently I'm trying to develop in rust 1.70.0, but I have some trouble to configure rust-analyzer.

This is the error message that I got:

```log
2024-12-11T09:11:10.252147304Z ERROR Flycheck failed to run the following command: CommandHandle { program: "/usr/local/cargo/bin/cargo", arguments: ["check", "--workspace", "--message-format=json-diagnostic-rendered-ansi", "--manifest-path", "/workspaces/CodinGame_Rust_template/Cargo.toml", "--keep-going", "--all-targets"], current_dir: Some("/workspaces/CodinGame_Rust_template") }, error=Cargo watcher failed, the command produced no valid metadata (exit code: ExitStatus(unix_wait_status(25856))):
error: the `--keep-going` flag is unstable, and only available on the nightly channel of Cargo, but this is the `stable` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
See https://github.com/rust-lang/cargo/issues/10496 for more information about the `--keep-going` flag.
```

This is the GitHub repo :
https://github.com/MathieuSoysal/CodinGame_Rust_template

This is my dev environement:
https://github.com/MathieuSoysal/CodinGame_Rust_template/blob/main/.devcontainer/devcontainer.json

Can somebody help me to solve this issue ?

**Comment by lnicola** [comment]
We no longer support 1.70, do you have any particular reason to stay on 1.70?

**Comment by lnicola** [comment]
You can set `rust-analyzer.check.overrideCommand` and remove `--keep-going` from there, but it will still fail when building the proc macros and build scripts, which might matter for `time`, I guess. Or you can use an old r-a version, from before #17565, or even the one in the 1.70 stable toolchain.

**Comment by lnicola** [comment]
Ah, just remove `-keep-going` from both `rust-analyzer.check.overrideCommand` and  `rust-analyzer.cargo.buildScripts.overrideCommand`.
