### ISSUE TITLE
Add setting to always show status bar item in vscode

### ISSUE THREAD

**Issue by ju5tevg3niy** [rust-lang/rust-analyzer#18665]
Hello. Recent pull #18592 has changed the default behavior of the vscode's rust-lang.rust-analyzer extension to hide the status bar item unless certain types of files are open.

I believe it should have a setting to always show the status bar item. There might be multiple use cases to that, one of which is to know whether the server is running and start/stop it when needed (e.g. I don't need it all the time while vscode is open, but keeping it running wastes a significant portion of RAM (more than 1GiB even for a small project)), but opening a .rs/cargo.toml file every time to check it's status seems unnecessary.

Setting `rust-analyzer.statusBar.documentSelector` to `{"pattern": "**"}` doesn't work when no editors are open.

**Comment by Veykril** [comment]
Yes I agree, this is incredibly annoying actually, we should add a value to the config to have it be always shown (just like how setting it null hides it fully)
