### ISSUE TITLE
"Extract into constant / variable / static" improvements

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#18679]
* in some cases like #14886 (short string), we could use the string to name the constant or static instead of `key` / `KEY`
* I think the code tries to put the cursor on the new item, but it doesn't work for me:

![Image](https://github.com/user-attachments/assets/4aae10a0-84a9-4b87-b256-d875ecddc329)

![Image](https://github.com/user-attachments/assets/f26a586b-c8dc-428a-b79c-0a0595519c09)

CC @Giga-Bowser, #14886

**Comment by Giga-Bowser** [comment]
> * I think the code tries to put the cursor on the new item, but it doesn't work for me

Is this rust-analyzer running through one of the `launch.json` configurations like `Run Extension (Release Build)`? I seem to remember having some issues with placeholder snippets/tabstops when using those, and I meant to go back and investigate that at some point.

**Comment by lnicola** [comment]
No, I did `cargo xtask install` and restarted VS.

**Comment by Giga-Bowser** [comment]
After some careful `git bisect`ing, this bug was caused by the change made to `editors/code/src/client.ts` in bac0ed579f5474309686839d0691969d80b29783. @Veykril are we safe to revert that change?

**Comment by Veykril** [comment]
Oh no, I thought I've fixed that again. We should definitely revert that change, as it was an accident.
