### ISSUE TITLE
When an error is fixed but the remaining build takes a while, the error is shown in the editor for the entire build

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#18691]
This often happens when working  in rustc: I work in some crate early in the build chain. I make some mistake, RA shows the error inline in the editor. I fix that error and hit Ctrl-S, and now the next check build starts -- and it takes a minute to complete since it now has to build the rest of rustc. During that entire time, the error is still shown in the editor, even though it has long been fixed.

I feel like this behavior changed at some point in the last few months or so, but I can't say exactly when.

Ironically, if I make the build work but there are still warnings to be shown, then the error disappears immediately. Only if the build is entirely clean does the error stick around. That almost makes it tempting to deliberately introduce warnings just to get faster feedback on whether the errors are fixed...

What I would hope for is that either
- RA uses the progress information emitted by the check build to realize "the rustc_target crate has built successfully, I can remove all error annotations from that crate". (Or something similar. I don't know how RA decides to remove the errors when there are warnings, so maybe that system could be used.)
- Or if nothing like that is possible, remove the errors entirely when I hit Ctrl-S, and only add them back if they are still emitted. I think that's what used to happen though, so there's probably a reason why you changed this.

**rust-analyzer version**: rust-analyzer version: 0.3.2212-standalone [.../.vscode-oss/extensions/rust-lang.rust-analyzer-0.3.2212-linux-x64/server/rust-analyzer]

**rustc version**: (rustc bootstrap)

**editor or extension**: VSCodium Version: 1.93.1

**Comment by Veykril** [comment]
This should be tackled by https://github.com/rust-lang/rust-analyzer/pull/18332 (haven't reviewed the recent changes yet)
