### ISSUE TITLE
`proc-macro` server no longer supported for toolchains up to v1.76

### ISSUE THREAD

**Issue by benjamin-nw** [rust-lang/rust-analyzer#18705]
Hello,

We use the toolchain 1.74 for rust projects and after the latest update to version (0.3.2220) we got an error when starting the server:

> ERROR Failed to run proc-macro server from path /home/user/.rustup/toolchains/1.74-x86_64-unknown-linux-gnu/libexec/rust-analyzer-proc-macro-srv, error: Custom { kind: Other, error: "The version of the proc-macro server (2) in your Rust toolchain is too old and no longer supported by your rust-analyzer which requiresversion 4 or higher.\nThis will prevent proc-macro expansion from working. Please consider updating your toolchain or downgrading your rust-analyzer to ensure compatibility with your current toolchain." 

After a bit of research, I found this PR #18670 that contains the new error message and it says:
> internal: Drop proc-macro server support for ~1.66.0 and older toolchains

The error seems to come from this change, but the drop of support seems to go well beyond the 1.66 version. 

After some more testing, I was able to get the error up to v1.76.
>  ERROR Failed to run proc-macro server from path /home/user/.rustup/toolchains/1.76-x86_64-unknown-linux-gnu/libexec/rust-analyzer-proc-macro-srv, error: Custom { kind: Other, error: "The version of the proc-macro server (3) in your Rust toolchain is too old and no longer supported by your rust-analyzer which requiresversion 4 or higher.\nThis will prevent proc-macro expansion from working. Please consider updating your toolchain or downgrading your rust-analyzer to ensure compatibility with your current toolchain." }

This version was out in February of this year.

The argument in the PR was:
> That is toolchains older than ~20 months from today on where this version was released. Reason is to simplify the codebase, and we likely don't even support version that old due to other reasons anymore either

But the version 1.74 is a few months old and now unsupported with this PR.

Do you plan on keeping the server this way ? It could also be cool to have the `minimum supported rust toolchain` for a given version of the server.

## Steps to reproduce

 1. Install `rust-analyzer` `v0.3.2220` to your IDE (here I use VSCodium but any will do)
 2. Create a new project with cargo
     1. `cargo new test`
     2. `cd test`
     3.  `rustup override set 1.76`
 3. Open the project in your IDE
 4. The error pops up in the OUTPUT window

**Comment by Veykril** [comment]
Indeed, the version we dropped support for was implemented in https://github.com/rust-lang/rust-analyzer/pull/14572 which is april last year. So that change earliest appeared in stable rust ~3 months later than that (and likely longer as I think that mightve been the time where we didnt keep up with syncs (though 1.76 being the latest to hit this is surpising still, that does sound a bit later than I'd expect).

Either way I seem to have misread the date when I looked at the blame. I am not sure if we want to reverse that, as we don't really support more than a couple of last stable releases (and for 1.74 I assume more than just this is already broken in some capacity by current rust-analyzer). Generally I'd recommend to pin your rust-analyzer to some version when you are working with older toolchains like this (or use the toolchain provided `rust-analyzer` instead).

**Comment by benjamin-nw** [comment]
Thank you for the quick response,

> Generally I'd recommend to pin your rust-analyzer to some version

We'll do that for now. We plan on upgrading the compiler version but not in a near future.

> (or use the toolchain provided rust-analyzer instead)

I didn't know you could do that, will look into it, thanks !

**Comment by wfeii1980** [comment]
VSCode rust-analyzer 0.4.2222

```shell
2024-12-18T11:02:42.016391937+08:00 ERROR Failed to run proc-macro server from path /home/wii/.rustup/toolchains/1.75-x86_64-unknown-linux-gnu/libexec/rust-analyzer-proc-macro-srv, error: Custom { kind: Other, error: "The version of the proc-macro server (2) in your Rust toolchain is too old and no longer supported by your rust-analyzer which requiresversion 4 or higher.\nThis will prevent proc-macro expansion from working. Please consider updating your toolchain or downgrading your rust-analyzer to ensure compatibility with your current toolchain." }
[Error - 11:02:43] Server process exited with code 0.
```

Can you provide the ability to install specific versions of plugins

**Comment by manaljain6667** [comment]
I am running toolchain version 1.76.0 and facing the same issue,  what is the recommended steps to deal with this 

thanks

**Comment by Veykril** [comment]
> Generally I'd recommend to pin your rust-analyzer to some version when you are working with older toolchains like this (or use the toolchain provided `rust-analyzer` instead).

For VSCode you can install specific versions of the extension, or if you wanna use the rustup rust-analyzer you can point it to that serveer via the `rust-analyzer.server.path` config

**Comment by chriskrycho** [comment]
rust-analyzer *could* (and is in various contexts alleged to! But I do not see evidence of that being true in practice) resolve via the `rust-toolchain.toml`.

In VS Code, a per-project override to use the version managed by `rustup` looks like this (assuming the default setup on macOS; adjust appropriately to your own OS):

```jsonc
{
   "rust-analyzer.server.path": "/Users/chris/.cargo/bin/rust-analyzer"
}
```

In Zed, the same:

```jsonc
// Folder-specific settings
//
// For a full list of overridable settings, and general information on folder-specific settings,
// see the documentation: https://zed.dev/docs/configuring-zed#settings-files
{
  "lsp": {
    "rust-analyzer": {
      "binary": {
        "path": "/Users/chris/.cargo/bin/rust-analyzer"
      }
    }
  }
}
```

If you want to make `rust-analyzer` default to *always* doing that, you can set that config in the app-level settings instead. I do not necessarily recommend that, because it’s nice to get more features as `rust-analyzer` keeps improving, but it has the nice benefit of *not* breaking in situations like this one!

**Comment by Veykril** [comment]
> rust-analyzer could (and is in various contexts alleged to! But I do not see evidence of that being true in practice) resolve via the rust-toolchain.toml.

It already does honor toolchain overrides as long as they target the same folder as your cargo workspace resides in (that is where the corresponding Cargo.toml exists)

**Comment by davidbarsky** [comment]
> the override needs to specify the rust-analyzer component.

These are typically automatically generated, no? Maybe rustup should default to including rust-analyzer in the component list if it doesn't already?

**Comment by Veykril** [comment]
That seems like a very big ask, not everyone uses rust-analyzer.

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/18731 reverts this *temporarily* until we introduce #18730 to give a warning headsup for future (known) supported version drops (and to instruct users on what their options then are)

**Comment by chriskrycho** [comment]
> but to use the toolchain rust-analyzer, the override needs to specify the rust-analyzer component.

This is helpful; is it documented in the `rust-analyzer` somewhere? I did not find that anywhere in the docs when I searched just now, but very well may have missed it!

For reference, for folks reading along, see [this section of the rustup manual][rustup], which includes an example of `toolchain.components`:

[rustup]: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

```toml
[toolchain]
channel = "nightly-2020-07-10"
components = [ "rustfmt", "rustc-dev" ]
targets = [ "wasm32-unknown-unknown", "thumbv2-none-eabi" ]
profile = "minimal"
```

As documented [here](https://rust-lang.github.io/rustup/overrides.html#components), the `components` value specifies *additional* components to install, so I believe the relevant bit here would be to write something like this:

```toml
[toolchain]
channel = "1.75.0" # or some other pre-1.76 version
components = ["rust-analyzer"]
```

That being said, `rustup` obviously does *not* document what if any behavior `rust-analyzer` layers on top of that specification. As it stands I think *this thread* is the most likely place for someone to learn that!

**Comment by tanriol** [comment]
> > rust-analyzer could (and is in various contexts alleged to! But I do not see evidence of that being true in practice) resolve via the rust-toolchain.toml.
> 
> It already does honor toolchain overrides as long as they target the same folder as your cargo workspace resides in (that is where the corresponding Cargo.toml exists), but to use the toolchain rust-analyzer, the override needs to specify the rust-analyzer component.

@Veykril Could you please clarify whether "it does" here refers to the rust-analyzer binary or to the VSCode plugin? Does rust-analyzer integration for other editors than VSCode(-plugin-compatible) need to reimplement that logic?

**Comment by Veykril** [comment]
They do, given the client is responsible for spawning the server process (and hence picking the appropriate binary to execute). So yes, this is specifically a VSCode thing.
