### ISSUE TITLE
Poor completion in `tracing` crate macros

### ISSUE THREAD

**Issue by SludgePhD** [rust-lang/rust-analyzer#18719]
**rust-analyzer version**: 0.3.2220-standalone

**rustc version**: any recent

**editor or extension**: VSCode, but shouldn't matter

**relevant settings**: none

**repository link (if public, optional)**: https://github.com/tokio-rs/tracing

**code snippet to reproduce**: 
```rust
let variable = "test";
tracing::info!(var<|>);
tracing::info!(name = var<|>);
```

Requesting completions in the two places in the snippet above comes up empty, but this is a valid place to put the `variable` local, which tracing will then emit as an event.

```rust
let variable = "test";
tracing::info!("{}", va<|>);
```

In this snippet, the `info!` macro is used just like `log::info!` can be, except with the `log` crate, rust-analyzer *does* manage to provide proper completions.

A fix for these would be great, since `tracing` is heavily favored over `log` in large parts of the ecosystem (eg. the whole async ecosystem, and bevy uses it too).

**Comment by ChayimFriedman2** [comment]
Minimized:
```rust
macro_rules! helper {
    ($v:ident) => {};
}

macro_rules! m {
    ($v:ident) => {{
        helper!($v);
        $v
    }};
}

fn main() {
    let variable = "test";
    m!(v|);
}
```
