### ISSUE TITLE
Allow disable "Remove unnecessary async" quick fix

### ISSUE THREAD

**Issue by tgrushka** [rust-lang/rust-analyzer#18725]
Related issues: #13492, #14262

I am visually impaired and often do imports by double-hitting `ctrl`-`,` to just do the import.

Unfortunately, this "Remove unnecessary async" menu item has started showing up in my projects, and async is certainly not unnecessary on the function I'm about to write.

The unwanted side effect is that it removes async and fails to do the import, necessitating an undo and then a careful reading of the Quick Fix menu.

My I please be able to remove this feature entirely in the rust-analyzer settings?

At minimum, if my cursor is not on the async keyword itself, it should not even offer this option, especially if there's not a yellow clippy highlight on it. Then again, I'd just rather turn it off (everything just seems to be "too helpful" nowadays...).

I checked the code for this and there seems to be no check for such a preference,, or even if "unnecessary asyncs" are allowed in clippy (not that I know how to do that anyway...).

Thank you.

**Comment by Veykril** [comment]
Indeed the assist (it should be a quickfix but its actually not right now) should definitely only trigger on the async keyword. If it was a proper quickfix, that is a diagnostic then you could disable it via the settings.

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/18726 reduces the applicability of the assist to the async token for now

**Comment by ChayimFriedman2** [comment]
> it should be a quickfix but its actually not right now

Quickfix for what diagnostic? I mean, even Clippy does not warn on an unused async.

**Comment by Veykril** [comment]
Clippy not having it right now doesn't mean it never will. The phrasing of "unnecessary something" implies a lint to me hence why
