### ISSUE TITLE
`textDocument/implementation` on a variable should go to `impl` block(s) of its type

### ISSUE THREAD

**Issue by mawkler** [rust-lang/rust-analyzer#18721]
I couldn't find any discussion about this, but to me it makes sense if calling "go to implementation" on a variable returned all `impl` blocks for that variable's type.

Below is an example to illustrate. The cursor is on variable `foo` of type `Foo`. Doing `textDocument/implementation` would return the location of the two `impl` blocks for `Foo`:

```rust
struct Foo;

fn main() {
    let foo = Foo;
    //  ^ cursor is here, and we call `textDocument/implementation`...
}

impl Foo { // <- ...which returns this location...
    fn foo() {}
}

impl From<()> for Foo { // <- ...and this location
    fn from(value: ()) -> Self {
        Foo
    }
}
```

What do you say?

**Comment by mawkler** [comment]
I noticed now that doing `textDocument/implementation` on the _type name_ (`Foo`) does return both `impl` block locations. But what I'm suggesting is support for doing that on a _variable name_, which doesn't seem to currently exist.

**Comment by ChayimFriedman2** [comment]
I don't like this suggestion. When you hover over the variable, you can go to its type from there, and from the type you can find all implementations. That seems to be good enough for something that is not as commonly wanted as this.
