### ISSUE TITLE
declarative macro in `macro_rules!` cannot see any item outside

### ISSUE THREAD

**Issue by Arichy** [rust-lang/rust-analyzer#18733]
**rust-analyzer version**: 0.4.2225-standalone (a0d9dd861d 2024-12-20))

**rustc version**: 1.81.0 (eeb90cda1 2024-09-04)

**editor or extension**: VSCode

**relevant settings**: all by default

**code snippet to reproduce**: 
```rust
#[derive(Debug, Clone, PartialEq)]
pub enum RegisterSize {
    Bit8,
    Bit16,
    Bit32,
    Bit64,
}

#[derive(Debug, Clone)]
pub struct Register {
    name: &'static str,
    base: u8,
    size: RegisterSize,
    value: u64,
}

macro_rules! define_register_family {
    ($base: expr, $r64:ident, $r32:ident, $r16: ident, $r8:ident) => {
        pub const $r64: Register = Register {

        };
    };
}

define_register_family!(0, RAX, EAX, AX, AL);
```
I've defined `Register` above, but RA could not see it so I lost all type info of `Register`.

<img width="536" alt="Image" src="https://github.com/user-attachments/assets/906ff0c3-2cb3-4eb4-b3be-0e1a9a0c99b2" />

**Comment by ChayimFriedman2** [comment]
The name is resolved, but we don't produce IDE support inside macros currently.

**Comment by Veykril** [comment]
We likely won't in the future either, a macro is just a bunch of tokens without meaning. Invoking the macro gives them meaning in the context of the invocation. We could in theory do stuff with it when the macro has been invoked and consider all invocations but I don't think that is too useful as its gets more cluttered the more usages a macro has.

**Comment by ChayimFriedman2** [comment]
RustRover does this, and I think it's quite useful. I'm thinking of two options for how to do that: based on invocations, which I think is what RustRover does, or based on specially crafted speculative expansion. Either way I'm not planning to try implementing this until we have Salsa 3 db forking feature.

**Comment by Veykril** [comment]
Oh interesting, I did not know `RustRover` was doing this. In hindsight, I can see cases where this might be useful to have (it does remind me of https://rust-analyzer.github.io/blog/2020/03/30/macros-vs-rename.html a bit)
