### ISSUE TITLE
Assist to add `#[cfg(test)]` to `mod` definition

### ISSUE THREAD

**Issue by sbdchd** [rust-lang/rust-analyzer#18769]
My current workflow for adding a new test module is:

1. navigate to `lib.rs`
2. add `mod foo_test;` near the top
   ```rs
   mod foo_test;
   ```
3. add `#[cfg(test)]` above it
   ```rs
   #[cfg(test)]
   mod foo_test;
   ```

I think an assist option to add the `#[cfg(test)]` would be nice -- is it too specific?

**Comment by Veykril** [comment]
We have a completion snippet for this `tmod` (and then an assist that allows you to move an inline module `mod foo {}` into a `mod foo;` + create the corresponding file). An assist for this here sounds too niche/specific to me
