### ISSUE TITLE
Quote or escape the raw string correctly in popup

### ISSUE THREAD

**Issue by Jisu-Woniu** [rust-lang/rust-analyzer#18765]
Currently, the popup for raw string syntax uses the following code:

https://github.com/rust-lang/rust-analyzer/blob/1ce4de2585cb9802c4d5a99d1a904b11fdba9501/crates/ide/src/hover/render.rs#L709-L713

So `r#"A "quoted" string"#` will be rendered like this:

> value of literal: A "quoted" string

![Image](https://github.com/user-attachments/assets/3ca49a95-d0e3-4ae1-aafd-e650b2e9c39a)

However, when the code contains special characters in Markdown like `*` (which is common in regex), the popup is messed up.

For example, `r".*regex.*"` became:

> value of literal: .*regex.*

![Image](https://github.com/user-attachments/assets/fb0b5d75-b09f-4bee-a873-a851f05a742c)

With a proper quotation or escaping, this could be rendered as:

> value of literal: `.*regex.*`

> value of literal: .\*regex.\*  (Less preferable, since leading and trailing spaces are hard to distinguish.)

**Comment by dfireBird** [comment]
If we use codeblocks to display the value, we don't need to the escaping, since whatever inside codeblock will be rendered as is.

**Comment by Veykril** [comment]
what if the string contains backticks? We will need to do some form of escaping either way. That aside I don't mind I think

**Comment by Jisu-Woniu** [comment]
Another example in Zed, with backticks (ignore the clippy lint):

![Image](https://github.com/user-attachments/assets/feedd507-b159-4329-b827-b16d01736648)

**Comment by Jisu-Woniu** [comment]
When quoting strings with backquotes, as specified in [CommonMark spec](https://spec.commonmark.org/0.30/#example-338):

> Backslash escapes are never needed, because one can always choose a string of n backtick characters as delimiters, where the code does not contain any strings of exactly n backtick characters.

![spec](https://github.com/user-attachments/assets/eaccd24d-1312-424d-8626-1af638855660)
