### ISSUE TITLE
No `Fill struct fields` code action when `diagnostics.enable` is `false`

### ISSUE THREAD

**Issue by eval-exec** [rust-lang/rust-analyzer#18776]
**rust-analyzer version**: `rust-analyzer 0.4.2234-standalone`

**rustc version**: `rustc 1.81.0 (eeb90cda1 2024-09-04)`

**editor or extension**: Emacs 31.0.50, using lsp-mode

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

**code snippet to reproduce**: 
```rust
struct Dog {
    name: String,
    age: u8,
}

fn main() {
    Dog {
        // put cursot in here,
        // then call lsp-code-action to execute
        // the ""Fill struct fields" action   
        
    }
}
```
In above rust code, If I enable rust-analyzer's `lsp-rust-analyzer-diagnostics-enable` to `t`, let `diagnostics.enable` be `true`, then I have "fill struct" code action.
![Image](https://github.com/user-attachments/assets/1bf6b80f-d5cc-46f7-a616-24707309fcf8)

If I set `lsp-rust-analyzer-diagnostics-enable` to `nil`, restart lsp-workspace let `diagnostics.enable` be `false`, then I have no "fill struct" in lsp-execute-code-action.
![Image](https://github.com/user-attachments/assets/6a721b62-4ed2-4a49-a6a4-cee00c0146ed)

**Comment by ChayimFriedman2** [comment]
That's a diagnostic quick-fix (as it should be), so it won't appear if you have diagnostics disabled. Do you have a specific reason to turn off diagnostics?

**Comment by eval-exec** [comment]
> Do you have a specific reason to turn off diagnostics?

No specific reason, I don't want diagnostics to interrupt me when coding.

**Comment by lnicola** [comment]
Yeah, this doesn't really make sense. I'm not sure if your client could have a better UX, normally diagnostics shouldn't feel like an interruption.
