### ISSUE TITLE
Errors flash and disappear (RA crash) after 0.3.2220 version with "Server process exited with code 0"

### ISSUE THREAD

**Issue by tgrushka** [rust-lang/rust-analyzer#18781]
I've been using nightly and have noticed this for the past week or so.
Unfortunately, it also occurs in 0.3.2228 release version onwards.

This is a serious regression in nightly **and release 0.3.2228** and it's important to fix it before the next release.

When I downgrade to 0.3.2220, the problem goes away.

```
uname -a
Linux framework-mint 6.8.0-51-generic #52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

code-insiders --version
1.97.0-insider
89f808979a5151bd91324e65d4f7ab1b62896983
x64
```

Whenever working in code in any `#[cfg(test)]` blocks (and sometimes outside those blocks), rust-analyzer seems to crash 90% of the time when there's an error in my code that's not "very simple" (i.e. `let x: i32 = 3.5;`). There are no useful logs. The only output for "Rust Analyzer Language Server" is like this:

```
[Error - 4:14:38 PM] Server process exited with code 0.
```

EDIT: Also occurred with fresh install of VS Code Insiders with no other extensions/settings except rust-analyzer.

Screen recording (I am hitting Control-S several times to save; analyzer runs, displays the error for a frame or two, then disappears):
![Image](https://github.com/user-attachments/assets/799f3517-12cb-4f47-a4d6-006ff747816d)

Sample Rust code (this is **only an example**, it's not only this particular error):
(This is in a `#[cfg(test)]` module.)
```rs
impl TestResponse {
...
    pub async fn print(&mut self) {
        let response = self.response;
        todo!()
    }
...
}
```

```
cargo check --tests
...
error[E0507]: cannot move out of `self.response` which is behind a mutable reference
  --> api/src/test_helpers/test_response.rs:35:24
   |
35 |         let response = self.response;
   |                        ^^^^^^^^^^^^^ move occurs because `self.response` has type `Response<Body>`, which does not implement the `Copy` trait
...
```

Here's "Rust Analyzer Language Server Trace" output with `rust-analyzer.trace.server: "messages"` after Clear, Save, and error flashes briefly (a couple frames) and disappears:
<details>
<code>
[Trace - 4:21:34 PM] Sending request 'textDocument/formatting - (139)'.
[Trace - 4:21:34 PM] Received response 'textDocument/formatting - (139)' in 39ms.
[Trace - 4:21:34 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:21:34 PM] Received request 'window/workDoneProgress/create - (40)'.
[Trace - 4:21:34 PM] Sending response 'window/workDoneProgress/create - (40)'. Processing request took 0ms
[Trace - 4:21:34 PM] Received notification '$/progress'.
[Trace - 4:21:34 PM] Sending notification 'workspace/didChangeWatchedFiles'.
[Trace - 4:21:34 PM] Received notification '$/progress'.
[Trace - 4:21:34 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:21:34 PM] Received notification '$/progress'.
[Trace - 4:21:34 PM] Received notification '$/progress'.
[Trace - 4:21:34 PM] Received notification '$/progress'.
[Trace - 4:21:35 PM] Received notification '$/progress'.
[Trace - 4:21:35 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:21:35 PM] Sending request 'textDocument/codeAction - (140)'.
[Trace - 4:21:35 PM] Received response 'textDocument/codeAction - (140)' in 1ms.
[Trace - 4:21:35 PM] Sending request 'textDocument/codeLens - (141)'.
[Trace - 4:21:35 PM] Received response 'textDocument/codeLens - (141)' in 2ms.
</code>
</details>

Here's "Rust Analyzer Language Server Trace" output with `rust-analyzer.trace.server: "verbose"` after Clear, Save, and error flashes briefly (a couple frames) and disappears:
<details>
<code>
[Trace - 4:24:42 PM] Sending request 'textDocument/formatting - (162)'.
Params: {
    "textDocument": {
        "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs"
    },
    "options": {
        "tabSize": 4,
        "insertSpaces": true,
        "trimTrailingWhitespace": true,
        "insertFinalNewline": true
    }
}

[Trace - 4:24:42 PM] Received response 'textDocument/formatting - (162)' in 66ms.
No result returned.

[Trace - 4:24:42 PM] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs"
    }
}

[Trace - 4:24:42 PM] Received request 'window/workDoneProgress/create - (45)'.
Params: {
    "token": "rust-analyzer/flycheck/0"
}

[Trace - 4:24:42 PM] Sending response 'window/workDoneProgress/create - (45)'. Processing request took 0ms
No result returned.

[Trace - 4:24:42 PM] Received notification '$/progress'.
Params: {
    "token": "rust-analyzer/flycheck/0",
    "value": {
        "kind": "begin",
        "title": "cargo check",
        "cancellable": true
    }
}

[Trace - 4:24:42 PM] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {
    "changes": [
        {
            "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs",
            "type": 2
        },
        {
            "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs",
            "type": 2
        }
    ]
}

[Trace - 4:24:42 PM] Received notification '$/progress'.
Params: {
    "token": "rust-analyzer/flycheck/0",
    "value": {
        "kind": "report",
        "cancellable": true,
        "message": "api"
    }
}

[Trace - 4:24:42 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 34,
                    "character": 23
                },
                "end": {
                    "line": 34,
                    "character": 36
                }
            },
            "severity": 1,
            "code": "E0507",
            "codeDescription": {
                "href": "https://doc.rust-lang.org/error-index.html#E0507"
            },
            "source": "rustc",
            "message": "cannot move out of `self.response` which is behind a mutable reference\nmove occurs because `self.response` has type `Response<Body>`, which does not implement the `Copy` trait",
            "relatedInformation": [
                {
                    "location": {
                        "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs",
                        "range": {
                            "start": {
                                "line": 34,
                                "character": 23
                            },
                            "end": {
                                "line": 34,
                                "character": 23
                            }
                        }
                    },
                    "message": "consider borrowing here: `&`"
                }
            ],
            "data": {
                "rendered": "\u001b[0m\u001b[1m\u001b[38;5;9merror[E0507]\u001b[0m\u001b[0m\u001b[1m: cannot move out of `self.response` which is behind a mutable reference\u001b[0m\n\u001b[0m  \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m--> \u001b[0m\u001b[0mapi/src/test_helpers/test_response.rs:35:24\u001b[0m\n\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\n\u001b[0m\u001b[1m\u001b[38;5;12m35\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\u001b[0m \u001b[0m\u001b[0m        let response = self.response;\u001b[0m\n\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\u001b[0m                        \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;9m^^^^^^^^^^^^^\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;9mmove occurs because `self.response` has type `Response<Body>`, which does not implement the `Copy` trait\u001b[0m\n\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\n\u001b[0m\u001b[1m\u001b[38;5;14mhelp\u001b[0m\u001b[0m: consider borrowing here\u001b[0m\n\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\n\u001b[0m\u001b[1m\u001b[38;5;12m35\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m| \u001b[0m\u001b[0m        let response = \u001b[0m\u001b[0m\u001b[38;5;10m&\u001b[0m\u001b[0mself.response;\u001b[0m\n\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\u001b[0m                        \u001b[0m\u001b[0m\u001b[38;5;10m+\u001b[0m\n\n"
            }
        },
        {
            "range": {
                "start": {
                    "line": 34,
                    "character": 23
                },
                "end": {
                    "line": 34,
                    "character": 23
                }
            },
            "severity": 4,
            "code": "E0507",
            "codeDescription": {
                "href": "https://doc.rust-lang.org/error-index.html#E0507"
            },
            "source": "rustc",
            "message": "consider borrowing here: `&`",
            "relatedInformation": [
                {
                    "location": {
                        "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs",
                        "range": {
                            "start": {
                                "line": 34,
                                "character": 23
                            },
                            "end": {
                                "line": 34,
                                "character": 36
                            }
                        }
                    },
                    "message": "original diagnostic"
                }
            ]
        }
    ],
    "version": 282
}

[Trace - 4:24:42 PM] Received notification '$/progress'.
Params: {
    "token": "rust-analyzer/flycheck/0",
    "value": {
        "kind": "report",
        "cancellable": true,
        "message": "quick_dev"
    }
}

[Trace - 4:24:42 PM] Received notification '$/progress'.
Params: {
    "token": "rust-analyzer/flycheck/0",
    "value": {
        "kind": "report",
        "cancellable": true,
        "message": "api"
    }
}

[Trace - 4:24:42 PM] Received notification '$/progress'.
Params: {
    "token": "rust-analyzer/flycheck/0",
    "value": {
        "kind": "report",
        "cancellable": true,
        "message": "api"
    }
}

[Trace - 4:24:42 PM] Received notification '$/progress'.
Params: {
    "token": "rust-analyzer/flycheck/0",
    "value": {
        "kind": "end"
    }
}

[Trace - 4:24:42 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs",
    "diagnostics": [],
    "version": 282
}

[Trace - 4:24:43 PM] Sending request 'textDocument/codeAction - (163)'.
Params: {
    "textDocument": {
        "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs"
    },
    "range": {
        "start": {
            "line": 36,
            "character": 5
        },
        "end": {
            "line": 36,
            "character": 5
        }
    },
    "context": {
        "diagnostics": [],
        "triggerKind": 2
    }
}

[Trace - 4:24:43 PM] Received response 'textDocument/codeAction - (163)' in 2ms.
Result: []

[Trace - 4:24:43 PM] Sending request 'textDocument/codeLens - (164)'.
Params: {
    "textDocument": {
        "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs"
    }
}

[Trace - 4:24:43 PM] Received response 'textDocument/codeLens - (164)' in 1ms.
Result: [
    {
        "range": {
            "start": {
                "line": 7,
                "character": 11
            },
            "end": {
                "line": 7,
                "character": 23
            }
        },
        "data": {
            "version": 282,
            "kind": {
                "impls": {
                    "textDocument": {
                        "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs"
                    },
                    "position": {
                        "line": 7,
                        "character": 11
                    }
                }
            }
        }
    }
]

[Trace - 4:24:45 PM] Sending request 'textDocument/diagnostic - (165)'.
Params: {
    "textDocument": {
        "uri": "file:///home/tom/apps/a11y.doctor/api/src/routes/jobs/checkout_job.rs"
    },
    "previousResultId": "rust-analyzer"
}

[Trace - 4:24:45 PM] Received response 'textDocument/diagnostic - (165)' in 2ms.
Result: {
    "kind": "full",
    "resultId": "rust-analyzer",
    "items": []
}

[Trace - 4:24:45 PM] Sending request 'textDocument/diagnostic - (166)'.
Params: {
    "textDocument": {
        "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs"
    },
    "previousResultId": "rust-analyzer"
}

[Trace - 4:24:45 PM] Received response 'textDocument/diagnostic - (166)' in 1ms.
Result: {
    "kind": "full",
    "resultId": "rust-analyzer",
    "items": []
}

[Trace - 4:24:45 PM] Sending request 'textDocument/codeLens - (167)'.
Params: {
    "textDocument": {
        "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs"
    }
}

[Trace - 4:24:45 PM] Received response 'textDocument/codeLens - (167)' in 1ms.
Result: [
    {
        "range": {
            "start": {
                "line": 7,
                "character": 11
            },
            "end": {
                "line": 7,
                "character": 23
            }
        },
        "data": {
            "version": 282,
            "kind": {
                "impls": {
                    "textDocument": {
                        "uri": "file:///home/tom/apps/a11y.doctor/api/src/test_helpers/test_response.rs"
                    },
                    "position": {
                        "line": 7,
                        "character": 11
                    }
                }
            }
        }
    }
]

</code>
</details>

**Comment by Veykril** [comment]
The flickering diagnostics should be fixed by https://github.com/rust-lang/rust-analyzer/pull/18778, as for why the server exits for you I am not sure. Given your gif retains the inlay hints it seems like the server isn't exiting so I assume the logs you picked were misleading / stale (the server will exit if the extension unloads etc)

**Comment by isosphere** [comment]
I've also seen this "Server process excited with code 0" issue on 0.3.2253. My other symptoms on that version are a little different: I would get lints on the first restart of rust-analyzer, but then they would stop updating after that until I restarted it again. 

Downgrading to 0.3.2220 resolved the issue for me.

**Comment by kevinfaveri** [comment]
can confirm i have same error, mitigation by @isosphere solves the problem in vscode.
it seems like it slowdown the whole ide and then stop providing linting and making checks run on save extremely slow
rolling back solves this
im on rust version 1.86, which was a recent change i did and only thing that changed in the repo that could be causing it

**Comment by krishvishal** [comment]
I'm also facing the issue of `Server process exited with code 0.`. After a while the intellisense stops working and when I checked output tab near terminal I find the following trace.

```
Stopping server timed out
Server process exited with code 0.
```

I'd like to know if there is fix to this.

**Comment by rikhuijzer** [comment]
I can consistently reproduce on <https://github.com/modelcontextprotocol/rust-sdk> commit dffae27cf0ec2dd9e143c5f5a688f53ae8de9449. When I restart the rust-analyzer server it works, but then when I change something it immediately crashes on the second run. Tested on MacOS with Cursor and Version 0.3.2370, Server Version 0.3.2370-standalone (588948f267 2025-04-06), and Rust stable 1.85 and 1.86. I have not seen this issue on other projects.

The error is
```
[Error - 1:06:21 PM] Server process exited with code 0.
```

**Comment by rikhuijzer** [comment]
After lots of waiting and re-installing (Cursor/VSCode seems very slow for extension installs), this version seems to work now: Version 0.3.2137, Server Version 0.3.2137-standalone (2b750da1a 2024-10-06). Still with Rust 1.85.

**Comment by Veykril** [comment]
> [Error - 1:06:21 PM] Server process exited with code 0.

Note that 0 means success, so that is entirely unrelated. I believe VSCode tends to put out that message when you restart / manually stop the server due to how we shut the server down. In other words that log message can be ignored and is not related to any odd behavior you may be encountering.

**Comment by jmigual** [comment]
Hey, I'm at version 0.3.2571 and I'm still experiencing this issue. I tried reinstalling everything in VS Code but the error persists :/ 

Edit: I can confirm that this doesn't happen with version 0.3.2563

**Comment by ShoyuVanilla** [comment]
> Hey, I'm at version 0.3.2571 and I'm still experiencing this issue. I tried reinstalling everything in VS Code but the error persists :/
> 
> Edit: I can confirm that this doesn't happen with version 0.3.2563

Yes, but that's another issue https://github.com/rust-lang/rust-analyzer/issues/20427

**Comment by BartoszTrading** [comment]
Does Rust Analyzer use the Git repository in the workspace for anything? I started experiencing this issue right after initializing a Git repo and adding it as a submodule in another repo. This may be totally unrelated, but I just want to make sure.

**Comment by ShoyuVanilla** [comment]
> Does Rust Analyzer use the Git repository in the workspace for anything? I started experiencing this issue right after initializing a Git repo and adding it as a submodule in another repo. This may be totally unrelated, but I just want to make sure.

No, it doesn't. But your editors/editor-plugins/IDEs might use git information to locate the workspace root and pass it as `CWD` to rust-analyzer.
