### ISSUE TITLE
Autocomplete seems broken by a `LazyLock` + conditional crate paths

### ISSUE THREAD

**Issue by alice-i-cecile** [rust-lang/rust-analyzer#18798]
**rust-analyzer version**:  rust-analyzer 1.83.0 (90b35a6 2024-11-26)

**rustc version**: 1.83

**editor or extension**:  VsCode 

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**repository link (if public, optional)**:  https://github.com/bevyengine/bevy/commit/760d0a31003c70ed6017b2a70059a76d9b268425, which is the commit that broke this.

**code snippet to reproduce**: 
```rust
use bevy::prelude::*;

fn my_system(query: Query<&Transform>){
    for transform in query.iter(){
      // Autocomplete should show up here, showing the various fields etc.
       transform
   } 
}
```

First detected in https://github.com/bevyengine/bevy/issues/17004. We can probably work around this, but this seems to be an RA bug.

**Comment by ChayimFriedman2** [comment]
I'm trying to understand what's the role of the `LazyLock` here. Is it created in a bad state in which proc macros expand to something not completeable, then after edits becomes good?

**Comment by alice-i-cecile** [comment]
@mockersf @raldone01 may have better hypotheses than I do here about what's going on: https://github.com/bevyengine/bevy/pull/16766 was the offending PR.

**Comment by ChayimFriedman2** [comment]
I tried and I'm getting completions normally (Windows), both in 0.15.0 and in this commit.

**Comment by raldone01** [comment]
I can look at it in the new year but lazy lock should have nothing to do with it.

The changes made should have no impact on the code generated by the proc macros since no computed crate paths changed.

**Comment by ChayimFriedman2** [comment]
Indeed it does, because r-a analyzes all crates at once while rustc compiles one crate at a time. In general proc macros should not rely on external state, and their behavior if they do is non-guaranteed, even in rustc. So if this is the problem I believe it's working as intended.

**Comment by Veykril** [comment]
rust-analyzer caches proc-macro expansions unlike rustc. You generally cannot assume when and how often a proc-macro gets re-executed. Lik

**Comment by alice-i-cecile** [comment]
Awesome, thanks for the help and feedback :) I'm happy to call this an "us problem"; I hope this thread helps some poor soul years down the line.
