### ISSUE TITLE
Support distiguishing between "never used" and "refrenced but never used"

### ISSUE THREAD

**Issue by aquacash5** [rust-lang/rust-analyzer#18803]
It would be nice to distinguish between a function that is `never used` and a function is referenced but that is `never used`.

```rust
fn a() -> u32 { // referenced but never used
	1
}

fn b() -> u32 { // never used
	a()
}

fn c() -> u32 { // used
	2
}

fn main() {
	println!("{}", c());
}
```

This is not a problem, but it was confusing when I saw it.

**Comment by Veykril** [comment]
That is a rustc diagnostic so you probably want to file that in https://github.com/rust-lang/rust
