### ISSUE TITLE
Define: Go to definition, declaration, implementation, type definition

### ISSUE THREAD

**Issue by kjeremy** [rust-lang/rust-analyzer#2541]
The LSP (as of 3.15) supports go to definition, declaration, implementation and type definition.

What do these mean in a rust world? Does supporting all of the above features make sense? We should define what each of the above operations mean and figure out what makes sense for rust.

Context: https://github.com/rust-analyzer/rust-analyzer/pull/2538#issuecomment-565012848

**Comment by flodiebold** [comment]
Thinking out loud...

For a file module:
 - definition goes to the file
 - declaration goes to the `mod foo;`
 - implementation N/A or same as definition?
 - type definition N/A

For a variable, const or static:
 - definition goes to the `let/const/static foo`
 - declaration same
 - implementation N/A
 - type definition goes to the ... definition of the type

For a trait method (call or implementation):
 - declaration goes to the `fn foo` in the trait
 - definition same? or same as implementation?
 - implementation goes to the `fn foo` in the `impl` if we know it
 - type definition N/A

For an inherent method (call):
 - definition/declaration/implementation go to the `fn foo` in the `impl`
 - type definition N/A

**Comment by matklad** [comment]
>definition same? or same as implementation?

Same as implementation. You can unambigiously go from that to declaration, but not in the opposite direction.

IntelliJ Rust recently implemented a crazily neat feature where, when to you go to def for a method, it remembers the substitution, and subsequent goto defs take these substitutions into account.

Ie, goto def `92.to_string()` brings you to blanket impl of `ToString`  for display, and second goto there brings you to `imp Display for i32` :zap: :zap: :zap:

**Comment by tigregalis** [comment]
I'm using VS Code. I'm not sure if this is the right issue to ask. I expected _go to definition_ (F12) to go to the `fn foo` in the `impl`, but it goes to the `fn foo` in the `trait`. And _go to implementation_ (Ctrl+F12) goes nowhere. I don't see _go to declaration_.

> For a trait method (call or implementation):
> 
>   * declaration goes to the `fn foo` in the trait
> 
>   * definition same? or same as implementation?
> 
>   * implementation goes to the `fn foo` in the `impl` if we know it
> 
>   * type definition N/A

**Comment by flodiebold** [comment]
We don't have a way to find the trait implementation yet. There's e.g. #4558 for this, and it's mostly why this issue is still open as well.
