### ISSUE TITLE
Resolve missing imports automatically

### ISSUE THREAD

**Issue by Matelasse** [rust-lang/rust-analyzer#2918]
This is a small suggestion to expand on the great assist recently implemented by @SomeoneToIgnore  to automatically add imports on save. If stability and accuracy is concern, it could be made into an opt-in setting.

**Comment by jasonwilliams** [comment]
## Prior Art
This feature is pretty common in other languages and their language-servers.

### TypeScript (opt-in)
![image](https://res.cloudinary.com/dk1rn2kmf/image/upload/v1486523096/typescript-hero_vxxzuk.gif)

To switch this on you need to set
```json
  "[typescriptreact]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": true,
    }
  }
```

### vscode-go (on by default)
![image](https://user-images.githubusercontent.com/16890566/38472170-a2a0a1f2-3b30-11e8-944c-972a4ecdb535.gif)


Should rust-analyzer be respecting
```json
  "[rust]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": true,
      " source.fixAll": true,
    }
  }

?
```

**Comment by Veykril** [comment]
We do have completions that import for unknown items now so I believe this can be closed
