### ISSUE TITLE
Do not propose unstable features on autocomplete for stable toolchain

### ISSUE THREAD

**Issue by SomeoneToIgnore** [rust-lang/rust-analyzer#3020]
In the project with stable toolchain used, `Some(22).ex<|>` proposes `expect_none` [method](https://doc.rust-lang.org/std/option/enum.Option.html#method.expect_none) which is unstable currently.

![image](https://user-images.githubusercontent.com/2690773/73848680-3ea7c080-4831-11ea-9e80-7c5ac3a02a56.png)

I would expect RA not to propose unstable APIs when a stable toolchain is used.

**Comment by hecatia-elegua** [comment]
Could we put this behind some kind of setting?
Sometimes I search in completions to find a specific functionality and it happnes to be nightly-only. If I don't care about going nightly then, I do so. If I do care, I would want this setting.

Besides that, today we can easily discern feature-gated completions _if_ they have an example:
![example shows feature gate](https://user-images.githubusercontent.com/108802164/230457599-b76056cd-e4cf-49df-a507-f04e325ee99a.png)
