### ISSUE TITLE
Format on auto-saving doesn't work

### ISSUE THREAD

**Issue by djc** [rust-lang/rust-analyzer#3256]
I have `formatOnSave` enabled and `autoSave` set. Yet automatic saving does not seem to trigger formatting as manual saving does. Is this a rust-analyzer issue?

**Comment by Veetaha** [comment]
This is interesting, I don't know where this formatting comes at all... @matklad do you know where the Rust formatter comes from?

**Comment by zshift** [comment]
I just really started getting into rust, so excuse my ignorance. Same for vscode plugins.

I ran into `rustfmt` just a few min ago. It's installed with `rustup component add rustfmt`. 

Usage is `rustfmt [options] <file>`.

**Comment by blitzerr** [comment]
This isn't working for me either.

**Comment by tbmreza** [comment]
@blitzerr running `rustfmt` from the command line works for me. Have you tried overriding the default formatter?

1. Install https://marketplace.visualstudio.com/items?itemName=statiolake.vscode-rustfmt
2. Ctrl+Shift+P, Format Document With... Configure Default Formatter...
3. Format on save now works on single rs file.

**Comment by matthiaskrgr** [comment]
Had the same problem, had
`    "editor.formatOnSave": true,`
and 
`    "files.autoSave": "afterDelay",` but files did not get formatted.

I looked into my `settings.json` and found this
````
    "[rust]": {
        "editor.defaultFormatter": "rust-lang.rust"
    },
````
and removing this fixed the auto-formatting for me :)

**Comment by lnicola** [comment]
@djc, @blitzerr is this working for you now?

(Marking `S-actionable`, if you look at this in the future and the OP hasn't answered, ping me so we can close it.)

**Comment by djc** [comment]
No, this is still not working for me. I have `formatOnSave` set to `true`, `files.autoSave` set to `afterDelay` (300ms) but files are not getting formatted automatically. I don't have the `defaultFormatter` config that Matthias found.

**Comment by Veykril** [comment]
Actually, it seems that this is a vscode specific problem... https://github.com/microsoft/vscode/issues/45997
The docs for `formatOnSave` state:
```json
  // Format a file on save. A formatter must be available, the file must not be saved after delay, and the editor must not be shutting down.
  "editor.formatOnSave": false,
```

**Comment by zydxhs** [comment]
"formatOnSave" also does not work when VSCode opens symlinked project. The "Rust Analyzer Client" output error info is:

```
INFO [3/3/2022, 9:26:04 AM]: Using server binary at /home/zhuyadong/.vscode-server/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer
ERROR [3/3/2022, 9:26:04 AM]: Bootstrap error [Error: Failed to execute /home/zhuyadong/.vscode-server/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer --version
	at Xb (/home/zhuyadong/.vscode-server/extensions/matklad.rust-analyzer-0.2.956/out/main.js:85:2121)
	at async Bb (/home/zhuyadong/.vscode-server/extensions/matklad.rust-analyzer-0.2.956/out/main.js:84:3252)
	at async Vm (/home/zhuyadong/.vscode-server/extensions/matklad.rust-analyzer-0.2.956/out/main.js:84:3083)
	at async Promise.all (index 0)]
```

**Comment by lnicola** [comment]
@zydxhs that's probably #11558

**Comment by pinkponk** [comment]
I have had problems when the auto format simply stops working and for me it was because I was using too long module statements e.g I was using a function without importing it:
```egui::collapsing_header::CollapsingState::load_with_default_open()```
but had to instead do:
```
use egui::collapsing_header;
CollapsingState::load_with_default_open()
```
in order for the auto formater to come alive again. Might be similar issues for some of you so I thought I might write it here.

**Comment by lnicola** [comment]
@pinkponk when this happens, try `cargo fmt`. If it doesn't work, it's a `rustfmt` bug.

**Comment by MolotovCherry** [comment]
This wasn't working for me. After going through my settings, I found
`"editor.formatOnSaveMode": "modifications",`

I changed it to
`"editor.formatOnSaveMode": "file",`
And everything started working

**Comment by Rendez** [comment]
For me it was this setting that made it work:

```
"[rust]": {
    "editor.defaultFormatter": "rust-lang.rust-analyzer"
}
```

**Comment by Veykril** [comment]
There seem to be working workarounds here and as this i a client issue in the first place I'll go ahead and close this
