### ISSUE TITLE
Format string syntax

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#3419]
If IntelliJ [can do it](https://intellij-rust.github.io/assets/posts/changelog-117/format-macros-highlighting.png), so can we.

**Comment by bjorn3** [comment]
Syntax highlighting is implemented, but syntax errors in format strings aren't shown.

**Comment by DJMcNab** [comment]
Another thought would be to link to the specific `Display/Debug` implementation when go to definition is activated on `{}/{:?}` (using the same infrastructure from https://github.com/rust-analyzer/rust-analyzer/issues/4558)

**Comment by Milo123459** [comment]
I'm going to have a look into implementing this (hopefully!).

**Comment by Veykril** [comment]
Go ahead, feel free to reach out here/on zulip if you have any questions or need directions

**Comment by ChayimFriedman2** [comment]
Granted, format strings need special handling in many IDE features and break once a while, but is there still something to specifically track in this issue?

**Comment by lnicola** [comment]
I guess not. I'd love an assist to replace path expressions, though.
