### ISSUE TITLE
Parser support for type ascription

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rust-analyzer#3599]
The parser/grammar doesn't seem to support type ascription. I would expect type ascription to be parsed the "same" as "cast expressions", however I am not sure if type ascription would really be an expression.

Ref: https://rust-lang.github.io/rfcs/0803-type-ascription.html

**Comment by Veykril** [comment]
Type ascription will most likely be deprecated, https://github.com/rust-lang/rfcs/pull/3307
