### ISSUE TITLE
`cargo metadata`: error: failed to parse manifest

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/rust-analyzer#3709]
I see such message in log file:

```
[ERROR rust_analyzer::main_loop] loading workspace failed: Failed to read Cargo metadata from Cargo.toml file /home/evgeniy/.emacs.d/rust-playground/at-2020-03-24-193510/Cargo.toml
    
    Caused by:
        0: Failed to run `cargo metadata --manifest-path /home/evgeniy/.emacs.d/rust-playground/at-2020-03-24-193510/Cargo.toml`
        1: Error during execution of `cargo metadata`: error: failed to parse manifest at `/home/evgeniy/.emacs.d/rust-playground/at-2020-03-24-193510/Cargo.toml`
           
           Caused by:
             no targets specified in the manifest
             either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
           
```

Cargo.toml:
```toml
# snippet of code @ 2020-03-24 19:35:10

# === Rust Playground ===
# This snippet is in: ~/.emacs.d/rust-playground/at-2020-03-24-193510/

# Execute the snippet: C-c C-c
# Delete the snippet completely: C-c k
# Toggle between main.rs and Cargo.toml: C-c b

[package]
name = "foo"
version = "0.1.0"
authors = ["Rust Example <rust-snippet@example.com>"]
edition = "2018"

[dependencies]
```

This file works completly fine with `cargo` check|build|run etc.

I use 7c2cc85806b6b9104e9d614aa71f841fd3627596

**Comment by bjorn3** [comment]
Is `main.rs` located in the `src` directory?

**Comment by Dushistov** [comment]
@bjorn3 

Yes, https://github.com/grafov/rust-playground/blob/5a117781dcb66065bea7830dd73618008fc34949/rust-playground.el#L95

Two fiiles: Cargo.toml and src/main.rs

**Comment by bjorn3** [comment]
I just tried `cargo metadata --manifest-path /path/to/Cargo.toml` from some random directory for a random rust project and it worked fine for me. I don't use emacs though, so I can't test using `rust-playground`.

**Comment by Dushistov** [comment]
@bjorn3 

Looks like problem is how to create files.

It should be reproducible with such actions:

0. Create empty directory foo
1. Create `foo/Cargo.toml` the same as in https://github.com/rust-analyzer/rust-analyzer/issues/3709#issue-587105055
2. Open buffer with for `foo/src/main.rs`

at the step 2, rust-analyzer via emacs ask to choose project path, 
but `main.rs` don't yet saved to disk, and error "rise":

```
[ERROR rust_analyzer::main_loop] loading workspace failed: Failed to read Cargo metadata from Cargo.toml file /var/tmp/test1/Cargo.toml
    
    Caused by:
        0: Failed to run `cargo metadata --manifest-path /var/tmp/test1/Cargo.toml`
        1: Error during execution of `cargo metadata`: error: failed to parse manifest at `/var/tmp/test1/Cargo.toml`
           
           Caused by:
             no targets specified in the manifest
             either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
           
```

**Comment by bjorn3** [comment]
That is probably a bug in https://github.com/grafov/rust-playground.

**Comment by Dushistov** [comment]
@bjorn3 
> That is probably a bug in 

Why? I suppose this is completely unrelated to Emacs bug.
If you use any editor and create Cargo.toml + save it, and only then you try to create `main.rs`,
you should get the same error.

The problem is that after error: `loading workspace failed` rust-analyzer doesn't recover.
For example find-definition can not jump to `println!`, there are no warnings about unused variables and so on and so on.

**Comment by bjorn3** [comment]
The fact that `main.rs` is not written to the disk before it is opened is a bug in`rust-playground`. The fact that rust-analyzer doesn't recover, is because it doesn't know that writing a certain file to the disk will cause `cargo metadata` to succeed.

**Comment by Veykril** [comment]
This doesn't seem to be a r-a issue

**Comment by 002Daling** [comment]
Friend, I also encountered this kind of problem with you recently, I can't find a solution, if you solve it, can you share how to solve the problem

**Comment by nguyenhieuec** [comment]
Alternative issue and solution: You can also be faced with this error if you have copied Cargo.toml file to a parent folder of the crate.

source: https://stackoverflow.com/a/52332738/7562213
