### ISSUE TITLE
Assist idea: remove all unused imports from a file

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust-analyzer#3719]
Sometimes when refactoring large files into smaller files I end up with unused import statements between files. The compiler already knows which imports aren't being used, but I still need to manually go over them one-by-one to remove the unused imports.

It'd be fantastic if rust-analyzer had a way to act on this information to remove all unused imports from a file. This would remove a lot of manual work when refactoring larger files into smaller ones.

## Example

For reference, I'm currently mid-refactor of a file and everything marked in red is what I have to remove by hand. Sometimes I can remove an entire line. But other times I need to manually delete individual statements from a line.

Given the compiler already knows which statements aren't needed, it'd be fantastic if rust-analyzer could use that information to remove them in bulk.

![Screenshot 2020-03-25 16 12 21](https://user-images.githubusercontent.com/2467194/77552343-b39f8a00-6eb3-11ea-81af-d5645e24b057.png)

**Comment by matklad** [comment]
Yeah, this is super useful, but unfortunatelly is probably pretty far off in the future, as it requires precise (without errors) analysis.

**Comment by flodiebold** [comment]
We could maybe provide an assist that applies all these suggestions at once. It'd be kind of a hack though.

**Comment by maoueh** [comment]
What about removing unused imports if there is no more compilation errors? Would be a good improvement to do that task automatically, unless it's already available and I missed it.

**Comment by Lucretiel** [comment]
Don't we already have a "remove unused imports" assist? Would it be possible to collect them all into a single assist?

**Comment by Veykril** [comment]
We only show the fix it from rustc which only removes the single unused import it's annotating.

The proper fix here would be for us to emit our own unused import diagnostic whose fix annotation would offer to remove all unused imports in the file I'd say, as I don't think we can easily act on the rustc diagnostics in a grouped manner like this.

**Comment by zyansheep** [comment]
I have no idea how rust-analyzer works, but one thing that might be an easy bodge is to make a list of all the unused import spans returned by rustc, make sure they are sorted by position in file, and then filter out the spans. Not sure how easy it would be to filter out the braces though.
```rust
let string: String = current_working_file();
let spans: Vec<Range> = get_import_spans_from_rustc();
let cur = 0;
let new_string = string.chars().enumerate().filter(|(n, c)| { 
    let contains = spans[cur].contains(n)
    if n == spans[cur].end { cur += 1; }
    contains
}).collect::<String>()
```

**Comment by AndyJado** [comment]
may I say bump?

**Comment by matklad** [comment]
Let's close in favor of https://github.com/rust-lang/rust-analyzer/issues/5131
