### ISSUE TITLE
supprot  download Language server via proxy

### ISSUE THREAD

**Issue by s97712** [rust-lang/rust-analyzer#3736]

**Comment by edwin0cheng** [comment]
The API End point is defined in here: 

https://github.com/rust-analyzer/rust-analyzer/blob/20c110e57f24aa54154942ee40921e9129fbc595/editors/code/src/net.ts#L10

I think it is not hard to add a config to modify it.

**Comment by lnicola** [comment]
Is this still necessary? Code has `"http.proxySupport": "override"` by default, so it sounds like it should work if you set `http.proxy`.

> override: Enable proxy support for extensions, override request options

**Comment by Veykril** [comment]
we no longer download the server binary ourselves
