### ISSUE TITLE
Assist: Replace turbofish with explicit type

### ISSUE THREAD

**Issue by TimoFreiberg** [rust-lang/rust-analyzer#3737]
E.g.
```rust
let foo = (0..10).map(|x| x.to_string()).collect::<Vec<_>>();
```
->
```rust
let foo: Vec<_> = (0..10).map(|x| x.to_string()).collect();
```
This should probably only be offered if the turbofish is in the last method call of the chain, though.

**Comment by lnicola** [comment]
> This should probably only be offered if the turbofish is in the last method call of the chain, though.

This isn't as easy as it seems because the return type of `collect` doesn't need to match its type parameter. It only happens to be like this for `std::iter::Iterator::collect`.

**Comment by matklad** [comment]
Hm, I think this would be doable for collect? In fact, I wanted exactly this for astnode::cast earlier today. If the rhs or let is a method call with a turbo fish, and the return type of the call is it’s sole type parameter, we can use ascription instead.

https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.collect

**Comment by lnicola** [comment]
Yes, it's doable. I guess we could even do this in the "insert explicit type" assist.

**Comment by Veetaha** [comment]
Turbofish is not a bad syntax at all, this is quite a controversial assist.

**Comment by matklad** [comment]
Assist can’t be controversial by definition. It is not a diagnostic. I
generally prefer ascription to turbo fish, if applicable.

**Comment by TimoFreiberg** [comment]
> Turbofish is not a bad syntax at all, this is quite a controversial assist.

I wouldn't mind having an assist in the opposite direction as well!

**Comment by Veykril** [comment]
This has been implemented
