### ISSUE TITLE
ra_prof: use tracing?

### ISSUE THREAD

**Issue by kjeremy** [rust-lang/rust-analyzer#3794]
As seen on zulip: https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/tracing.20in.20chalk/near/192417961

https://github.com/davidbarsky/tracing-tree/

**Comment by bjorn3** [comment]
Another option would be `measureme` which is used by rustc.

**Comment by Veetaha** [comment]
Not sure if we can use it in Rust, but the flamegraph impl is here: https://github.com/jonhoo/inferno

**Comment by davidbarsky** [comment]
(Hi, I'm David!)

I think I speak for Eliza when I say we'd be super happy if you did end up using `tracing`! Beyond the `tracing-tree` library I wrote, @yaahc has been working on flamegraph/inferno integration with `tracing` here: https://github.com/tokio-rs/tracing/pull/631. I'll see what the status of that PR is and if it can be merged soon.

**Comment by yaahc** [comment]
just finished the fix with the thread_local so now it should give accurate samples for multiple threads now, I'll see if we can't get it merged today.

**Comment by lnicola** [comment]
@davidbarsky I think we can close this, right?
