### ISSUE TITLE
Feature request: Manual way to check for rust-analyser server update in vscode

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rust-analyzer#3886]
Sometimes it takes a while for the vscode extension to notice there's a rust analyzer update and download it.

I also would like the piece of mind that comes with the knowledge that there is definitely not a server update available. (If nothing else, "check for an update" is a thing when I hit a case where r-a behaves strangely).

As it is, I generally try opening a workspace and hoping it would have noticed with that if an update existed. This is kinda bad.

I could also add this if it's relatively easy, you point me in the right direction, and you'd accept the patch.

Also, sorry in advance if:

1. This is the wrong place to report this issue.
2. An issue exists exists already.
3. This functionality exists already (in which case, it would be nice if it were in the Cmd-Shift-P "Show All Commands" menu, which is where I was looking)
4. I'm fundamentally wrong about how some piece of this works or otherwise clearly confused.

**Comment by matklad** [comment]
The relevant code is here: https://github.com/rust-analyzer/rust-analyzer/blob/d89c189ad1efe87e54855e6488184d7a3825a534/editors/code/src/main.ts#L113-L243

It is rather tricky, by virtue of talking to external services and modifying global persistent state, but I would accept a patch that adds "check for rust-analyzer updates", if that is implemented in such a way that:

* it obviously doesn't break existing update workflow
* it is relatively simple to understand and maintain itself 

which, admittedly, are very subjective metrics :)

**Comment by Veykril** [comment]
no longer relvant
