### ISSUE TITLE
Known performance issues with completions on Windows?

### ISSUE THREAD

**Issue by dpathakj** [rust-lang/rust-analyzer#3973]
I'm trying rust-analyzer on a home Windows machine and have found that rust-analyzer seems slow to produce completions (3-5 seconds), at least when used via emacs and lsp-mode. From reading some other issues I don't think that's expected, but I don't know if many people are using Windows. I should also note that this happens every time I wait for a completion, not just the first time I open a file.

I'm able to reproduce this on even a simple Rust project. I'm using company as the completion source, but I see logs from rust-analyzer indicating an 'overly long loop turn', so I suspect my emacs setup is not the problem.

To isolate the issue I created a fresh Cargo project (no dependencies, no files other than main.rs) and saw that it still took several seconds between when I finished typing `some_fun` and when I got completions (`some_function()`). This is the main.rs I was using:

```rust
fn main() {
    some_function();
   some_fun // <-- at this point (and others), completion will take seconds
}

fn some_function() {
    println!(""); // tried removing this, no real change
}
```

I also see some logs from rust-analyzer's stderr that seem related, though the actual time I spend waiting as measured by a stopwatch may be as much as twice that (hard to measure). For example,

```
[ERROR rust_analyzer::main_loop] overly long loop turn: 1.6057318s
[ERROR rust_analyzer::main_loop] overly long loop turn: 1.9498836s
```

I'm using lsp-mode-20200413 and the rust-analyzer binary from https://github.com/rust-analyzer/rust-analyzer/releases/2020-04-13, though I initially installed from source and saw the same behavior.

**Comment by dpathakj** [comment]
I installed vscode and couldn't reproduce this slowness. Maybe it's the way different LSP plugins interact with rust-analyzer?

**Comment by matklad** [comment]
>[ERROR rust_analyzer::main_loop] overly long loop turn: 1.6057318s

Oh dear, this sounds like a awfully "fun" issue to debug. It seems client specific, but, also, we probably shouldn't have that long waits anyway... 

Wild guess: *could* it be the case that rust-analyzer runs with `RUST_BACKTRACE=1` somehow, when run from emacs? 

Don't really have ideas how to debug this, besides capturing the logs from client and server and figuring out what's different between emacs and vscode.

**Comment by flodiebold** [comment]
Is it possible that the main loop blocks if Emacs takes too long to read messages? :thinking:

**Comment by matklad** [comment]
Might be, we use sync channels for IO:
https://github.com/rust-analyzer/lsp-server/blob/5d21802fb581b271aaf40edf5abacb9ed284748a/src/stdio.rs#L12

**Comment by flodiebold** [comment]
Maybe we should measure that.

**Comment by lnicola** [comment]
@dpathakj do you still have this issue? I think emacs got better at JSON at some point.

**Comment by lnicola** [comment]
Closing, this isn't really actionable and OP switched to Zig :sweat_smile:.

**Comment by dpathakj** [comment]
OP meaning me? No, I didn't switch to Zig.

I think I solved my own issues by using [WSL2](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) when on Windows. That also had the benefit of dropping me into a familiar/sane CLI environment, filesystem, etc. There are other non-rust-analyzer-related performance issues I had on native Windows that also disappeared, IIRC. Emacs' native JSON, which you mention above, probably helped at some point. I'm not sure why I didn't reply to your earlier message; sorry about that.

If someone cared about this, the next step would probably be to try to reproduce on a native Windows setup - it's been 3 years, who knows if it's even still slow anymore.

**Comment by lnicola** [comment]
Okay, thanks for dropping in. Feel free to reopen or file a new issue it you run into problems again (but please not the emoji thing).
