### ISSUE TITLE
ra_proc_macro_srv pins serde_derive

### ISSUE THREAD

**Issue by kjeremy** [rust-lang/rust-analyzer#3993]
The tests for `ra_proc_macro_srv` depend on a specific version of `serde_derive`. We should figure out how to avoid this (or a process to upgrade `serde` where we know we aren't breaking the tests).

```toml
serde_derive = "=1.0.104"
```

This pins all of our serde-related crates.

**Comment by edwin0cheng** [comment]
Oh, we might choose to use another custom-derive crate that we didn't use in our deps. Any suggestions?

**Comment by lnicola** [comment]
It's not very clear to me what that test does, but can we either:

 - use a crate in the RA workspace instead, or
 - publish a `ra-proc-macro-test` crate to crates.io and use that instead?

**Comment by edwin0cheng** [comment]
My original idea is to use a complicated and popular custom macro crate for testing functionalities  of proc-macro expansion. The reason of `pinning` here is, the output of an expansion of macro depends on the implementation details of `serde-derive`, such that if they changed in the future version, we have to change the test fixture. 

Maybe we could publish a new crate for that but I dont' know it is worth the afford ?

**Comment by lnicola** [comment]
That makes sense, but on the other hand we don't run `analysis-stats` on other large crates during tests but rather rely on more targeted ones and a couple of "torture" tests.

It might be enough to use a simpler test showing that spawning the server and the serialization works, e.g. an identity proc macro or something like https://github.com/matklad/proc-caesar.

**Comment by kjeremy** [comment]
I just hit this again with #4971

**Comment by Veykril** [comment]
This is no longer the case
