### ISSUE TITLE
Errors inside of macros calls not showing

### ISSUE THREAD

**Issue by jntrnr** [rust-lang/rust-analyzer#4046]
I'm doing a bit of work inside a call of a macro, but I'm not seeing the errors pop up with rust-analyzer.

This used to work, though more recently it seems like it can no longer see errors that happen during compilation inside of the macro call (specifically here async_stream!)

**Comment by theli-ua** [comment]
I have recently started using async_stream and now I get similar. And I also see proc macro server panicking

**Comment by Veykril** [comment]
Can't reproduce this anymore.
