### ISSUE TITLE
Parameter hints make indentation hard to see

### ISSUE THREAD

**Issue by Emilgardis** [rust-lang/rust-analyzer#4079]
Consider following example.

```rust
#![allow(warnings)]
pub fn main() {
    let obvious_name = ();

    let _ = foo(
        obvious_name,
        long_function_name(),
        long_function_name(),
        long_function_name(),
        if true {
            long_function_name() 
        } else {
            ()
        },
        obvious_name,
    );
}

fn foo(
    obvious_name: (), b: (), long_argument_here: (), 
    d: (), beep_boop: (), obvious: ()) {todo!()}
fn long_function_name() -> () {todo!()}
```

rust-analyzer version: nightly (ec645f2) with `"rust-analyzer.inlayHints.parameterHints": true` displays this as

![Bad indentation](https://user-images.githubusercontent.com/1502855/79914068-e8582000-8424-11ea-96e8-5ba04d2e168f.png)

### The issue

Even though the code is properly indented, the hints make it very hard to determine if it really is so.  
Of course, if you allow yourself to disregard the syntax highlighting, you'll know that the indentation starts where the hint is.

I think an option to display parameter hints on the right side after `,` (or maybe before?) if we are identing in a tall argument style, copying behavior from the chaining hints, is a good way to solve this. Another way could possibly be to show it in the other indentation level if it fits, keeping the actual code correctly indented.

**Comment by Emilgardis** [comment]
The above approach of having hint on the right side would mess with chained function hints
(when they are shown)
![parameter and chained hints](https://user-images.githubusercontent.com/1502855/79916968-ea70ad80-8429-11ea-90af-1344a7d6b0b0.png)

Not sure how to go about this.

**Comment by Veetaha** [comment]
Maybe adding a newline after the inlay hint can help (though I am not sure that vscode decorations allow for adding newlines)
```rust
foo(
    param_name:
    val,
    param_name2:
    val2
);
```
or making it table-like:
```rust
foo(
    param_name:        val1,
    longer_param_name: val2
)
```
But I think people mostly ignore this imperfection, e.g. in lanugages with named parameters you don't indent function calls this way on a regular basis.

**Comment by matklad** [comment]
I would be strong -1 on newlines, jumping lines after analysis are bad. Postfix hints seem fine to add as a flag to me.

**Comment by aalhitennf** [comment]
could it just be same with chained functions, on the right side?  

```
foo(
    param, :type
    param2, :type
    param3, :type
)
```

**Comment by Emilgardis** [comment]
I'm closing this issue as the implementation is done by the the code client now.
