### ISSUE TITLE
Multiple vscode instances download rust-analyzer update at the same time

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust-analyzer#4469]
I just noticed that multiple vscode instances started at the same time (eg, if restoring a previous session) start downloading the updated analyzer executable at the same time. 

In addition to that, this can seemingly trigger some kind of rate limit, causing those downloads to slow to a crawl. (In this instance for me, they still haven't finished as of writing this issue.)

If possible, multiple running vscode instances should probably cooperate such that only one download is going on at the same time. This happens on a windows install of vscode.

**Comment by vsrs** [comment]
I'll have a go.

**Comment by Veykril** [comment]
No longer relevant since we don't download the server anymore
