### ISSUE TITLE
Errors not shown if error source cannot be resolved

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust-analyzer#4535]
I have a project which fails to build (and `cargo check` fails) but when I load it up in VS Code it shows no issues.

The logs from rust-analyzer show this:
> [ERROR rust_analyzer::main_loop] File with cargo diagnostic not found in VFS: [project-path]\<::rouille::router::router macros>

Clearly there's an issue with how `cargo check` is reporting the error location, but rust-analyzer should still show the error in the "problems" window even if it can't determine the source.

**Comment by lnicola** [comment]
Can you find a small example that reproduces this problem?

**Comment by Veykril** [comment]
This should report the errors now
