### ISSUE TITLE
Macros in parameter type position

### ISSUE THREAD

**Issue by Alxandr** [rust-lang/rust-analyzer#4577]
This might be a well know issue, but I didn't find anything by searching, so I figured I'd post it, and if it's a duplicate it can just be closed.

I'm using `macro_rules` quite a bit in my current project, and for the most part I'm really happy with how well rust-analyzer deals with it. Sure, there are some rough edges, but most of it I can work around with little to no problem (though tt munchers seem to slow things down quite a bit). Regardless, what I found today is that macro invocations in function parameter type positions does not seem to be something rust analyzer likes.

Example:
![image](https://user-images.githubusercontent.com/112334/82707671-ce586a00-9c7c-11ea-9dcf-3b3da3afdf34.png)

**Comment by matklad** [comment]
Hm, but what is the specific problem here? The popup seems correct to me (modulo horrific rendering, but that's code porblme: https://github.com/microsoft/vscode/issues/92174)

**Comment by Alxandr** [comment]
I would expect it to render not the macro invocation, but the actual type the macro invocation results in. I don't have this exact code in front om me, so I don't completely remember what the actual types are, but I do believe in this case it would be something like `impl Iterator<Item = LocalBind>` for the `binds`.

**Comment by matklad** [comment]
Hm, I am inclined to close with "work as designed". If there's a macro call in function definition, then that's how the signature is intended to look like. Presumably, `ast_ctor_param!(impVec<LocalBind>)` is exactly how this type should look to the programmer (otherwise, it would have been spelled out, instead of being generated by the macro). 

For peeking under the covers, there's "expand macro" action

**Comment by Alxandr** [comment]
The issue here is that my goal isn't to do `ast_ctor_param!(blah)`, I'm generating a bunch of code using a tt muncher macro. This makes the popup for the most part completely unhelpful in telling me what the parameter types are. A thing to note here is that the method itself is also a result of a macro invocation, and it's showing up just fine. Arguably, this is badly designed (from a usability perspective) on my part, but the only way I can see to work around this (and make using these generated `new` methods "IDE friendly") is to convert to a proc macro.

**Comment by Alxandr** [comment]
To clarify a bit more; the code above was generated from something that looked like this (unfortunately, the code has been rewritten since, so I can't find exactly what it looked like - but it should still illustrate the use-case):

```rust
ast_node! {
  pub struct LocalCoreExpr {
    binds: Vec<LocalBind>,
    rest: Box<CoreExpr>,
  }
}
```

This generated code like this (plus a bunch of other functions/impls):

```rust
pub struct LocalCoreExpr {
  binds: Vec<LocalBind>,
  rest: Box<CoreExpr>,
}

impl LocalCoreExpr {
  pub fn new(binds: impl IntoIterator<Item = LocalBind>, rest: impl Into<Box<CoreExpr>>) -> Self {
    LocalCoreExpr { binds, rest }
  }
}
```

**Comment by Veykril** [comment]
We do render the expanded type now as this moved away from AST to HIR
