### ISSUE TITLE
Remove inlay hint in diff views

### ISSUE THREAD

**Issue by jasonwilliams** [rust-lang/rust-analyzer#4608]
Using [Github Pull Requests plugin](https://code.visualstudio.com/blogs/2018/09/10/introducing-github-pullrequests) i open the diff view and have the inline hints being messed up.

I'm guessing the best solution is to not show hints in the diff view

**VSCode Version**
1.46 insiders

**RA Version**
v0.2.182

**Screenshot**
![image](https://user-images.githubusercontent.com/936006/82813184-78f2a780-9e8c-11ea-9870-b443a2198736.png)

It looks like this issue was brought up before so i don't know if there's some easy solution.
Similar to https://github.com/rust-analyzer/rust-analyzer/pull/3388

**Comment by Veetaha** [comment]
Thanks for the report, will try to look into this, the fix should be trivial.
In the meantime, if you are using nightly builds of `rust-analyzer`, you can try assigning a keyboard shortcut for turning off the inlay hints as demoed in this PR: #4601

**Comment by Veetaha** [comment]
Unfortunately the fix is non-trivial. The document scheme of Github PR extension diff view is `file` which basically means it is indistinctive from a regular rust source file.
![image](https://user-images.githubusercontent.com/36276403/82943999-2526b200-9fa3-11ea-8290-f080cf5631fb.png)

see #4625

**Comment by lnicola** [comment]
I think this is better now?

![image](https://user-images.githubusercontent.com/308347/158953991-b2fe23d6-1864-4249-8202-e2db2b2f733e.png)

The hints still show up in some cases, but they're not that annoying:

![image](https://user-images.githubusercontent.com/308347/158954335-171b2640-6990-4f3e-bf64-9ba5a05361e7.png)

@jasonwilliams can you please retest?

**Comment by Veykril** [comment]
I don't think this is something we can reasonably fix as we are not aware of diffs, if anything I feel like VSCode should allow to hide inlay-hints in the diff view
