### ISSUE TITLE
Better support for installing language server

### ISSUE THREAD

**Issue by johnmarkwayve** [rust-lang/rust-analyzer#4753]
How can I more reliably install the correct language server version, rather than having to catch the brief alert in vscode before it disappears? If I don't catch that alert to install the language server, rust analyzer seems to silently do nothing.

### Context

I do most of my development in docker containers using vscode's remote development in container feature. As such, my dockerfile manages installing rustup, cargo, rustc, clippy, etc. etc., while the `devcontainer.json` specifies to install the rust analyzer extension _after_ starting the container. For various reasons  (such as adding new native dependencies to the container), I regularly have to rebuild these containers -- thus reinstalling the rust analyzer extension.

As noted above, _every time_ I do this I seem to only have **one** chance to catch a small brief popup that suggests I install a specific language server. I have no idea how to (re)install the language server if I miss this, other than by rebuilding the container.

Versions: Ubuntu 18.04, vscode 1.45.1, every rust analyzer for at least the last month.

I figure I must be missing something, but I can't find any documentation or questions about this.

PS.
Rust analyzer is awesome, thank you all for making the ecosystem so much better

**Comment by lnicola** [comment]
Hmm, why not download the binary from GitHub when building the container?

**Comment by johnmarkwayve** [comment]
I know there are other ways to solve my specific situation (figure out which version to downloadi in the docerfile, mounted volumes etc.), but my more general point is that the documentation states "the plugin will prompt you to download the matching version" and it would be super useful if we could get this same functionality as a command in the palette rather than just having to catch the timed popup.

**Comment by lnicola** [comment]
There's also `rust-analyzer.updates.askBeforeDownload` which you can probably enable to get rid of the prompt. And I don't think we hide the notification, but rather Code hides it and you can bring it back by clicking on a bell icon in the status bar.

**Comment by mickaelistria** [comment]
In order to replace RLS by rust-analyzer in Eclipse Corrosion ( https://github.com/eclipse/corrosion/issues/315 ), we'd need a `rustup -c rust-analyzer`. Is this some other place where I can support this idea, or is this ticket enough (note that I personally have no Rust skill to deploy to achieve that, so lobbying is the best I can do at the moment)?

**Comment by bjorn3** [comment]
There is already the `rust-analyzer-preview` rustup component.

**Comment by lnicola** [comment]
I think there are a bunch of alternatives here and there's no need to do anything else. Just to be sure, I tested and the notification didn't go away after a couple of minutes. Even after I dismissed it, I could still click on the bell icon to show it:

![image](https://user-images.githubusercontent.com/308347/104881814-a4218e00-596a-11eb-9189-dc37968821c3.png)

**Comment by Veykril** [comment]
We no longer manage downloads ourselves, so this can be closed.
