### ISSUE TITLE
Add a note related to usage in Windows environment

### ISSUE THREAD

**Issue by abhijeetbhagat** [rust-lang/rust-analyzer#4870]
I have a Windows 10 Enterprise 1909 version. I installed the latest VS Code, Rust and rust-analyzer plugins. I also have the latest rust gnu and msvc toolchains. However, I have an older VC++ compiler (installed with VS 2013).

After several installation/uninstallation attempts, I just couldn't get the rust-analyzer plugin working and I kept getting this - `The Rust Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted`. I did not know where to look for the logs. So I downloaded the latest `rust-analyzer-windows.exe` from the releases and just double clicked to see if it ran. Unfortunately, I got this error - `The application was unable to start correctly (0xc00007b)` and this is why the rust-analyzer server was crashing.

A quick googling for `0xc00007b` hinted at installing the latest MSVC++ Redistributable package. I had an older version of this installed from the VS 2013 installation. 

After installing the latest redistributable package for VS 2015, 2017 and 2019 (both x86 and x64 versions to be on a safer side), the problem got resolved and rust-analyzer is now working fine.

This should help those who are trying to use rust-analyzer on Windows with an older/missing MSVC++ runtime and can't figure out what on earth is going on.

**Comment by matklad** [comment]
SHould go to this secion of manual: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/manual.adoc#rust-analyzer-language-server-binary
