### ISSUE TITLE
Memory leak with bad macro (infinite recursion?)

### ISSUE THREAD

**Issue by johnmarkwayve** [rust-lang/rust-analyzer#4923]
I know this error report will be sparse, I'm trying to get something done quickly and will update later when I have more time.

A quick heads-up that in vscode I got a monotonically increasing memory footprint and spinlocked CPU core because of the following badly formed macro:

```rust
let pid: i32 = 1234;
let status = psutil::process::Process::new(pid);
error!("child_not_running"; "status" => status.to_string(); "pid" => pid);
```

where `error!` is from `slog-scope` crate. The second `;` should have been a `,`.

**Comment by johnmarkwayve** [comment]
Analyser extension version v0.2.207
Recommended analyser installed by extension.

Vscode versions:
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:04.923Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-59-generic

Ubuntu 18.04

**Comment by lnicola** [comment]
@johnmarkwayve are you still seeing this? We've had a bunch of macro and parser fixes lately.

A way to reproduce it would be appreciated.

**Comment by lbrande** [comment]
I have a similar problem with the latest version of both rust-analyzer and vscode. The macro that causes the problem uses the "TT muncher" paradigm: https://danielkeep.github.io/tlborm/book/pat-incremental-tt-munchers.html. I believe it applies to all TT munchers but I've not verified that.

**Comment by lnicola** [comment]
@lbrande can you share a test case?

**Comment by lbrande** [comment]
I investigated the problem further today and it turns out it actually wasn't the macro that is causing the problem, I'll submit a new issue for the memory leak I'm having.
