### ISSUE TITLE
Nothing gets resolved in the bracket-lib crates

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#5051]
https://github.com/thebracket/bracket-lib/

![image](https://user-images.githubusercontent.com/308347/85676613-6f4ca180-b6cf-11ea-817d-08a413cb1456.png)

**Comment by flodiebold** [comment]
My guess it's related to all the conditional compilation in https://github.com/thebracket/bracket-lib/blob/master/bracket-terminal/src/hal/mod.rs.
