### ISSUE TITLE
writing closure function will result on invalid type data checking inside the closure

### ISSUE THREAD

**Issue by eisenhaus335** [rust-lang/rust-analyzer#5177]
when writing the code on closure its seems there is issue that its will break the parent variable type checking. you could see the "white" color that indicating type checking is broken
![image](https://user-images.githubusercontent.com/25275731/86265180-aea65100-bbed-11ea-9b24-5dacdd81a0a5.png)
But after the code is finish and there is no problem on closure. The type checking will show the description on hover and the color just fine
![image](https://user-images.githubusercontent.com/25275731/86265189-b239d800-bbed-11ea-81a4-da014b1e5d22.png)

**Comment by flodiebold** [comment]
That's probably because this is inside a macro call, which makes it much harder to deal with broken code.

**Comment by Veykril** [comment]
Closing this as macro parsing recovery is a more general problem
