### ISSUE TITLE
Proc macro definition lookup incorrect

### ISSUE THREAD

**Issue by jgarvin** [rust-lang/rust-analyzer#5182]
Cargo.toml:

```
[package]
name = "analyzer_bug"
version = "0.1.0"
authors = ["Joseph Garvin <joseph.h.garvin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.9.0"
serde = {version="1.0.111", features=["derive"]}
```

main.rs:

```
use derive_builder::Builder;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Serialize, Deserialize, Debug, Builder)]
pub struct Location {
    name: String,
    description: String,
    #[builder(setter(skip))]
    paths: HashMap<String, String>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    LocationBuilder::default()
        .name("Living room".into())
        .description("Where you watch TV".into())
        .build()?;
    Ok(())
}
```

If you lookup `LocationBuilder` it will jump to the `use std::collections::HashMap;` line. In a perfect world I'd get the expanded code in a new window, but failing that I'd expect it to at least point at the `#[derive...` line and failing that at the `use derive_builder::Builder;` line, but I can't think of any reason to attribute it to the std import. In other files I've seen it give the serde import instead.

**Comment by lnicola** [comment]
@jgarvin can you try this again? It seems to work for me.

**Comment by Sytten** [comment]
I tried using derive_builder today and it doesn't seem to be able to work with it.

**Comment by lnicola** [comment]
@Sytten can you post a test case? I'm not sure how the one your ran into differs from the one included here.

**Comment by Veykril** [comment]
Can't reproduce this, if this still occurs for someone please open a new issue with more information.
