### ISSUE TITLE
"Files: Exclude" setting doesn't work with "Click to show"

### ISSUE THREAD

**Issue by arturoc** [rust-lang/rust-analyzer#5187]
When clicking on a type it shows files from a `.history ` directory belonging to a local history vscode addon that saves a copy of files on every save for local backups.

I have the following settings in `Rust Analyzer > Files: Exclude`

![image](https://user-images.githubusercontent.com/48240/86340057-aa614e80-bc54-11ea-8f83-f4961d988b4f.png)

that look like:

```json
    "rust-analyzer.files.exclude": [
        ".history",
        ".history/**/*",
        ".history/**"
    ]
```

in settings.json.

But invariably clicking on a type to jump to it's definition usually jumps tp the files in `.history.

This seems to be a similar problem to: https://github.com/rust-analyzer/rust-analyzer/issues/3113 but that was before there was a setting to set from the gui and the key in my settings.json looks correct. I've tried with the key used in that issue but it appears to be deprecated since it appears greyed out in the file and it doesn't make any difference in any case:

![image](https://user-images.githubusercontent.com/48240/86340691-9a963a00-bc55-11ea-9239-6a331c5586cd.png)

I've also tried several combinations of wildcards in both configs in case it was that but it doesn't seem to make any difference

**Comment by matklad** [comment]
More generally, excludes are just broken at the moment, we need to re-install them some day, but this is somewhat low priority, as we are using the client watching anyway. Perhaps it makes sense to remove this code completely.

**Comment by arturoc** [comment]
yes i guess if it doesn't work it would be better to remove it, otherwise it can be really confusing. thanks
