### ISSUE TITLE
Error status bar item plays badly with blue color

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust-analyzer#5208]
Error status bar item plays badly with blue color (cc @matklad):
![image](https://user-images.githubusercontent.com/36276403/86479648-36f33600-bd55-11ea-9090-3894842bf4b0.png)

**Comment by lnicola** [comment]
Is that a custom theme? How did you make it blue?

**Comment by Veykril** [comment]
This is actually configurable via `notificationsErrorIcon.foreground` and `notificationsWarningIcon.foreground` so I believe we can close this?

**Comment by Veetaha** [comment]
That works, thanks!

**Comment by Veykril** [comment]
Headsup though, https://github.com/rust-lang/rust-analyzer/pull/12388 will change the color keys assuming we go through with that (which I think we should since these are status bar items)
