### ISSUE TITLE
Extract variable doesn't respect selection inside macro calls

### ISSUE THREAD

**Issue by TimoFreiberg** [rust-lang/rust-analyzer#5291]
Given
```rust
assert_eq!(|"Foo".to_lowercase()|, "foo");
```
"Extract into variable" should create the following:
```rust
let var_name = "Foo".to_lowercase();
assert_eq!(|var_name|, "foo");
```
, but it creates:
```rust
let var_name = assert_eq!("Foo".to_lowercase(), "foo");
```

**Comment by Veykril** [comment]
The assist no longer work in this position (as it is usually incorrect and we are lacking the means to figure out if we are selecting an expression or not currently)
