### ISSUE TITLE
Inlay Hint Is Missing

### ISSUE THREAD

**Issue by JosephTLyons** [rust-lang/rust-analyzer#5322]
macOS: 10.15.5
VS Code: 1.47.0
rust-analyzer package: 0.2.232

With the following code:

```rust
fn main() {
    let numbers: Vec<u32> = (1..=1000).collect();

    let even_numbers: Vec<u32> = numbers
        .into_iter()
        .filter(|x| x % 2 == 0)
        .filter(|x| x % 3 == 0)
        .filter(|x| x % 4 == 0)
        .filter(|x| x % 5 == 0)
        .filter(|x| x % 6 == 0)
        .filter(|x| x % 7 == 0)
        .collect();

    for number in &even_numbers {
        println!("{}", number);
    }
}
```

Analyzer seems to miss the inlay hint for the last `filter()` function:

<img width="661" alt="Screen Shot 2020-07-11 at 3 03 32 PM" src="https://user-images.githubusercontent.com/19867440/87231757-e2b90900-c387-11ea-998d-247b488ff4e3.png">

**Comment by flodiebold** [comment]
That might be running into the type size limit.

**Comment by Veykril** [comment]
This works fine now 
![image](https://user-images.githubusercontent.com/3757771/214582738-5e237f88-e900-4090-b54e-76128c518335.png)
