### ISSUE TITLE
Error on DMatrix::zeros(rows, cols)

### ISSUE THREAD

**Issue by vadixidav** [rust-lang/rust-analyzer#5441]
For me (on current weekly version), this version introduced a regression that causes [`DMatrix`](https://docs.rs/nalgebra/0.21.1/nalgebra/base/type.DMatrix.html) to be picked up incorrectly when using [`DMatrix::zeros()`](https://docs.rs/nalgebra/0.21.1/nalgebra/base/type.MatrixMN.html#method.zeros-3). It claims that there is no arguments:

![image](https://user-images.githubusercontent.com/12789579/87883524-f858af00-c9d5-11ea-9722-aa1ec150f1f4.png)

However, a `cargo check` passes just fine, and I am actually building and running this code currently as part of another program, so it is certain that it does work. In fact, the last version did not have this issue.

My suspicion is that it is incorrectly picking up the first [`Matrix::zeros()`](https://docs.rs/nalgebra/0.21.1/nalgebra/base/type.MatrixMN.html#method.zeros). Nalgebra has four definitions of `zeros()` on `Matrix`, each of which may be used depending on which dimensions are `Dynamic` or which impl `DimName`.

I will let everyone know if this issue goes away on Monday.

**Comment by vadixidav** [comment]
The issue still persists, even in the latest release from Monday (which I only installed today).

**Comment by OfficialURL** [comment]
This issue still persists. The following code compiles just fine, but rust-analyzer claims an argument mismatch.

```rust
fn main() {
    println!("{}", nalgebra::DMatrix::<i32>::zeros(3, 3));
}
```

**Comment by edwin0cheng** [comment]
Seem like this [macro invocation](https://github.com/dimforge/nalgebra/blob/9e625db5382c6eab5541afffe1003f1c512c1edb/src/base/construction.rs#L616) expanded incorrectly.

**Comment by edwin0cheng** [comment]
Wait, there is multiple version of implementation for `MatrixMN` ...

https://github.com/dimforge/nalgebra/blob/9e625db5382c6eab5541afffe1003f1c512c1edb/src/base/construction.rs

**Comment by vadixidav** [comment]
This is still occurring to this day. rust-analyzer still seems to be choosing the first implementation on MatrixMN, rather than choosing the correct implementation.

**Comment by flodiebold** [comment]
Yeah, that's what I meant by "we don't check trait bounds of the impl during method resolution" -- we currently only check the trait bounds after selecting the method, but we have to do a preliminary check before selecting it.
If we gave up on ambiguous methods, you're right that we wouldn't produce the false type-mismatch, but we'd produce a false method resolution error instead once we add that :sweat_smile: Both are fixes we should make though.

**Comment by flodiebold** [comment]
Related: #10481.

**Comment by xiaohk** [comment]
Having the same issue. Is there any workaround that I can use to suspend this error? Thanks!

**Comment by H-A-M-G-E-R** [comment]
rls has no false positives

**Comment by H-A-M-G-E-R** [comment]
when i go to definition of zeros(), it's something different

**Comment by H-A-M-G-E-R** [comment]
it points to
```
/// # Constructors of statically-sized vectors or statically-sized matrices
impl<T: Scalar, R: DimName, C: DimName> OMatrix<T, R, C>
where
    DefaultAllocator: Allocator<T, R, C>,
{
    // TODO: this is not very pretty. We could find a better call syntax.
    impl_constructors!(R, C;                         // Arguments for Matrix<T, ..., S>
    => R: DimName, => C: DimName; // Type parameters for impl<T, ..., S>
    R::name(), C::name();         // Arguments for `_generic` constructors.
    ); // Arguments for non-generic constructors.
}
```

**Comment by okaponta** [comment]
This issue seems to happen on all constructor or `DMatrix`

```rust
let dm1 = DMatrix::from_vec(2, 3, vec![0, 1, 2, 3, 4, 5]);
let dm2 = DMatrix::from_diagonal_element(2, 3, 5.0);
let dm3 = DMatrix::<f32>::identity(2, 3);
let dm4 = DMatrix::from_fn(2, 3, |i, j| i * 3 + j);
```

all is from official example, but it has `expected 1 argument, found 3` from rust-analyzer

**Comment by contagon** [comment]
I can still recreate this as well unfortunately. Let me know if you'd like more info.
