### ISSUE TITLE
Plugin ignores the vscode $PATH variable when searching for rust-analyzer

### ISSUE THREAD

**Issue by savannidgerinel** [rust-lang/rust-analyzer#5534]
The plugin uses a list of hard-coded paths to assume the location of the rust-analyzer executable. It should, first, look at the $PATH environment variable.

I launch vscode after I enable a nix shell environment that has rust, cargo, rust-src, and rust-analyzer installed in it. I do not want vscode to try to manage dependencies like this since they are very likely to conflict between projects.

![Screenshot from 2020-07-25 14-18-31](https://user-images.githubusercontent.com/8534888/88463596-e2d60000-ce81-11ea-9e0f-0cd350f9e953.png)
![Screenshot from 2020-07-25 14-18-41](https://user-images.githubusercontent.com/8534888/88463598-e5385a00-ce81-11ea-8292-e0cccad74e0c.png)

**Comment by lnicola** [comment]
Does it work if you set rust-analyzer.serverPath to rust-analyzer(-linux)?

**Comment by savannidgerinel** [comment]
No, same errors. However, I see that `rust-analyzer.serverPath` is dimmed, and vscode reports that the setting isn't known.

![Screenshot from 2020-07-27 12-47-14](https://user-images.githubusercontent.com/8534888/88568955-bea42b80-d007-11ea-8341-6f83a8c3d8af.png)

**Comment by lnicola** [comment]
You should set it to the name of the executable, which is either `rust-analyzer` or `rust-analyzer-linux`, depending on how you've acquired it (build from source or GitHub release).

Also, the setting is greyed out, probably because you're using the `vscode-rust` extension and not `rust-analzyer`. The `rust-analyzer` support in the former is not working great at the moment, so I recommend the latter.

**Comment by savannidgerinel** [comment]
I don't actually have `vscode-rust`, however, I do have `rust-lang.rust`... and `matklad.rust-analyzer` was disabled. The setting is recognized now that I've re-enabled it. However, the error message remains even with me providing the full path to the executable.

I've actually acquired rust-analyzer from a NixOS package, hence my original request that the plugin honor my PATH environment. And the very odd looking path in the first panel.

**Comment by savannidgerinel** [comment]
The only way I can make this work is for those times that I launch vscode from within an environment that chroots into a linux filesystem standard. In that environment, rust-analyzer is in `/usr/bin/rust-analyzer`.

**Comment by lnicola** [comment]
`"rust-analyzer.serverPath": "rust-analyzer"` normally runs the version from Code's `PATH` environment variable (which isn't necessarily the one your terminal uses unless you start Code from a terminal). But it might work differently on NixOS.

**Comment by savannidgerinel** [comment]
Huh. I do always launch vscode from a shell that has that path activated already. That's how I've been using Rust with VSCode for the last month. I guess that means we're both a little stumped at the moment. It's fine for work since I have to create a chroot environment for that project, anyway.

For my other projects I can switch to rls for now.

Or maybe I'll go back to using nvim and try rust-analyzer with it.

**Comment by lnicola** [comment]
I'm not sure how the Nix RLS is packaged, but there's also a `rust-analyzer` binary available in `rustup` (without the `rustup` shim, unfortunately). I'd try `strace`-ing Code, I suppose.

@matklad uses Nix IIRC and might have better advice.

**Comment by matklad** [comment]
For matklad.rust-analyzer, we don’t lookup rust-analyzer binary at all. Rather, either he plugin downloads it into the extension directory (default behavior) (and we do patchelf for nix) or we just launch whatever it is in the settings.json (here, OS honors the PATH).

I am not sure what the logic in the official Rust extension — it’s support for Rust-analyzer is preliminary atm.

> I don't actually have vscode-rust, however, I do have rust-lang.rust... and matklad.rust-analyzer was disabled. The setting is recognized now that I've re-enabled it. However, the error message remains even with me providing the full path to the executable

This seem to imply that the error is not from rust-analyzer’s extension? Try disabling rust-lang-Rust?
