### ISSUE TITLE
Failed to load workspace: synching channel updates

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust-analyzer#5661]
We should definitely handle the case when the opened workspace contains a `rust-toolchain` file with the specified version of rust which is not yet installed on the user laptop:
![image](https://user-images.githubusercontent.com/36276403/89239520-15aa9180-d602-11ea-8020-cb27ab33205d.png)

The reproduction is to create a hollo world project and put `rust-toolchain` file in it such that any invocation of `cargo` inside of that workspace starts downloading the required version of itself

**Comment by lnicola** [comment]
That usually happens when you're trying to install two toolchains at once (even different versions).

**Comment by Veykril** [comment]
As was said, this seems unrelated to just having a `rust-toolchain` file lying around.
