### ISSUE TITLE
No intellisense with argument snippet autocompletion

### ISSUE THREAD

**Issue by jiayihu** [rust-lang/rust-analyzer#5754]
If `rust-analyzer.completion.addCallArgumentSnippets` is enabled, the autocompleted argument doesn't provide intellisense and it doesn't suggest the variables for instance. You have to ESC from the snippet twice in order to have intellisense again but it's very frustrating.

Ideally the snippet shouldn't stop autocomplete, although I think it's a VSCode specific issue.

I made a short GIF showing the issue: [https://streamable.com/9ogir5](https://streamable.com/9ogir5)

**Comment by Veykril** [comment]
You can disable this behavior by setting `"editor.suggest.snippetsPreventQuickSuggestions": false` I believe
