### ISSUE TITLE
Feature request: "Structured Search" in VS Code

### ISSUE THREAD

**Issue by d4h0** [rust-lang/rust-analyzer#6026]
Hi,

At the moment the recently [merged "Structured Search"](https://github.com/rust-analyzer/rust-analyzer/pull/5154) is not available in the VS Code plugin (at least not via `shift-ctrl-p`, where "Structured Search Replace" is available.

It would be great if this feature could be activated.

**Comment by Veykril** [comment]
The command is available for me now
