### ISSUE TITLE
`use std::u16;` makes method resolution of inherent `u16` methods fail

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#6082]
Example:

```rust
use std::u16;

fn f() {
    u16::from_le_bytes([0,0]);
}
```

Go to definition does not work on `from_le_bytes`, but *will* work if the `use std::u16;` is commented out.

I'm not actually sure how this works in rustc. You'd think the module *would* shadow the primitive type since they both occupy the type namespace, but apparently not? Maybe I've discovered another bonus namespace?

**Comment by matklad** [comment]
Yeah, we already have some custom logic for builtins: 

* https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/hir_def/src/item_scope.rs#L65-L73

This probably needs a test and some more special-casing around here:

https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/hir_def/src/nameres/path_resolution.rs#L142-L159

**Comment by jonas-schievink** [comment]
`method_resolution.rs` test case for this:

```rust
#[test]
fn assoc_fn_shadowed_by_use() {
    check_types(
        r#"
//- /lib.rs crate:lib deps:core
use core::u16;

fn f() {
    let x = u16::from_le_bytes();
      x
    //^ u16
}

//- /core.rs crate:core

pub mod u16 {}

#[lang = "u16"]
impl u16 {
    pub fn from_le_bytes() -> Self { 0 }
}
        "#,
    )
}
```

**Comment by jonas-schievink** [comment]
Related rustc code: https://github.com/rust-lang/rust/blob/f913a4fe901d6aeb84941fa06c17916d4e6d1dd7/compiler/rustc_resolve/src/late.rs#L2145-L2163

**Comment by jonas-schievink** [comment]
This appears to be harder to implement than I thought: we must make sure the fallback only happens once all parent `DefMap`s are checked, because otherwise you'd be unable to override primitive types with your own, if a block is present (`shadowing_primitive_with_inner_items` starts failing).

The good news is that I think it would be sufficient to implement this in `resolver.rs`, since this does not affect early name resolution (imports cannot refer to associated items).
