### ISSUE TITLE
[VSCode] Option to choose where 'toggle inlay hints' setting is saved

### ISSUE THREAD

**Issue by oeed** [rust-lang/rust-analyzer#6316]
I'm using the 'toggle inlay hints' command from #4601 and love it. The only issue is it saves the setting to the workspace, which I have included in my Git repo, so every time I toggle Git sees a change. It is committed as it's intended to hold the shared settings and folders for the team for each specific target in the monorepo; so having personal settings in there isn't ideal.

I can see it's [currently hard coded here](https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/src/commands.ts#L249). I'd be quite happy to make a simple PR to add this option if open to the idea.

**Comment by SomeoneToIgnore** [comment]
I see that this is the only place we use the workspace, all other cases default to `undefined` and don't interfere with you workflow, don't they?

Current docs for the parameter are:
```
* @param configurationTarget The [configuration target](#ConfigurationTarget) or a boolean value.
         *    - If `true` updates [Global settings](#ConfigurationTarget.Global).
         *    - If `false` updates [Workspace settings](#ConfigurationTarget.Workspace).
         *    - If `undefined` or `null` updates to [Workspace folder settings](#ConfigurationTarget.WorkspaceFolder) if configuration is resource specific,
         *     otherwise to [Workspace settings](#ConfigurationTarget.Workspace).
```

so I wonder if we really need any configuration at all.

Anyway, the MR is welcome, thank you.

**Comment by oeed** [comment]
Oh interesting, do you know what is meant by "if configuration is resource specific"? Perhaps language specific? Although undefined/null only choses between workspace folder or workspace, not global.

I'll experiment with removing it, if that doesn't help I'll make a config for it and PR. Thanks

**Comment by lnicola** [comment]
@oed did you try that?

**Comment by lnicola** [comment]
The command was removed in #13215.
