### ISSUE TITLE
Long startup time and sometimes `cargo check` doesn't send progress

### ISSUE THREAD

**Issue by kjeremy** [rust-lang/rust-analyzer#6408]
I cloned https://github.com/graphprotocol/graph-node.git and opened it up in `rust-analyzer` before running any cargo commands. RA showed no progress output in vscode but my CPU fans spun up. That caused me to open up my task manager and I saw a lot of `rustc` processes. Eventually those went away (after about a minute), `cargo check...` popped up in vscode's status and then finally indexing started.

**Comment by lnicola** [comment]
If you have build script support enabled, you'll need to wait for an initial cargo build or check.

**Comment by kjeremy** [comment]
I don't see any build scripts in that repo. We can't have some sort of UI indicator for that?

**Comment by bjorn3** [comment]
Is this still a problem?

**Comment by Veykril** [comment]
We have progress reports for these things now to my knowledge
