### ISSUE TITLE
vs code extension: even if rust-analyzer server is manually downloaded on activate it is downloaded again 

### ISSUE THREAD

**Issue by SebastienDorgan** [rust-lang/rust-analyzer#6428]
I use code-sever 3.6.1 and rust-analyzer 0.2.360.
In a Dockerfile I install rust-analyzer using the cli and I download the server (version eae54b5)

 in the globalStorage
```bash
## Alternative Rust Language Server
RUN code-server --install-extension matklad.rust-analyzer
### Download and Install rus-analyzer binary
RUN mkdir -p /home/rustdev/.local/share/code-server/User/globalStorage/matklad.rust-analyzer/
RUN curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux -o /home/rustdev/.local/share/code-server/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux
RUN chmod u+x /home/rustdev/.local/share/code-server/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux
```
Nevertheless when the extension is activated, it downloads the server again even if it is stored in globalStorage.
I have inspected a little bit the code and if find something suspicious in the main.ts getServer function.
At line 307: const exists = await fs.stat(dest).then(() => true, () => false);
The existence of the server is checked, when I trace I see this line returns true which is ok
But line 312: if (state.serverVersion === config.package.version) return dest;
The condition is false because state.serverVersion is undefined and config.package.version === "0.2.360"
For me after checking the existence of the server the serverVersion of the state should be updated else state.serverVersion is always undefined and the line 312 is useless.

I attach my Dockerfile and my docker-compose.yaml to help you to reproduce.
[code-server.zip](https://github.com/rust-analyzer/rust-analyzer/files/5470383/code-server.zip)

**Comment by jonas-schievink** [comment]
I believe the download code is now deleted, so this can potentially be closed
