### ISSUE TITLE
Unresolved import for uom modules

### ISSUE THREAD

**Issue by bheisler** [rust-lang/rust-analyzer#6537]
Certain imports from the uom crate don't resolve in rust-analyzer, resulting in spurious "unresolved import" errors.

Minimal example: https://gist.github.com/bheisler/a45181a4fbff28a7ea3a1d09f6212787

This example produces unresolved imports on the first three imports (but not the fourth one) which rustc does not emit. It seems to fail to resolve the `uom::si::f64` module and everything inside it. Same goes for `uom::si::f32`.

Admittedly, uom makes extremely heavy use of `macro_rules!` macros, so it's understandable that rust-analyzer would struggle with this crate. Still, I thought it would be best to report it.

Additionally, rust-analyzer takes a long time to index the uom crate on startup. Again, not really that surprising - uom generates a _lot_ of code with macros - but if there's anything you folks can do to speed it up, that would be appreciated. If nothing else, the uom crate might make a good stress-test benchmark.

**Comment by flodiebold** [comment]
@bheisler is this still happening in current RA?

**Comment by lnicola** [comment]
It seems to work for me, but I need to reload the window after adding a git dependency (known issue?):

![image](https://user-images.githubusercontent.com/308347/102778612-9690dc80-439b-11eb-83ab-15bd7c1c1b21.png)

After "restart server" and saving the file:

![image](https://user-images.githubusercontent.com/308347/102778733-c9d36b80-439b-11eb-9d57-f293c8fd7599.png)

After "reload window":

![image](https://user-images.githubusercontent.com/308347/102778752-d0fa7980-439b-11eb-868e-4bfba1683d5f.png)

**Comment by bheisler** [comment]
I still see "unresolved import" errors in my actual code with the latest rust-analyzer, yes. I didn't re-check my minimal example, but I see no reason to expect them to behave differently.

**Comment by jonas-schievink** [comment]
This works fine for me now, is anyone still having this issue?

**Comment by bheisler** [comment]
When I open that project with v0.3.1123, it pops up a notification saying that `cargo check` failed. `cargo check` works for me on the command line. I checked the server logs and posted them here:

https://gist.github.com/bheisler/6c522c39c85bda29583b6b59f27fe449

I have no idea if that's at all related. However, go-to-definition on the `uom` types does work now and I don't see erroneous error markers, so perhaps that's a separate issue.

**Comment by Veykril** [comment]
> When I open that project with v0.3.1123, it pops up a notification saying that cargo check failed. cargo check works for me on the command line. I checked the server logs and posted them here:

You have the "async_futures, async_smol, async_std, async_tokio" features for your project enabled in your saveOnCheck settings but your project doesn't have those
