### ISSUE TITLE
'Find all references' hangs forever

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust-analyzer#6568]
It's also possible I just didn't wait long enough - I waited about 2 minutes.

Steps to replicate: print Alt+Shift+F12 or Shift+F12 on https://github.com/rust-lang/rust/blob/9b2b02a840f358bcadef5c3ae861d2852da20b3d/src/librustdoc/html/render/mod.rs#L1510.

**Comment by jyn514** [comment]
It should have at least caught https://github.com/rust-lang/rust/blob/9b2b02a840f358bcadef5c3ae861d2852da20b3d/src/librustdoc/html/render/mod.rs#L611.

**Comment by lnicola** [comment]
Does this still happen and/or does it work if you wait longer?

**Comment by aryan9600** [comment]
Hello @lnicola, I am also encountering something similar. I waited for around 3 mins without any result. 

Step: Perform the goto references action on https://github.com/linkerd/linkerd2-proxy/blob/main/linkerd/proxy/core/src/resolve.rs#L30.

The LSP server process never took up more than 3% of CPU

**Comment by Veykril** [comment]
This most likely hit a chalk hang so I am closing this since we have a few of those already.
