### ISSUE TITLE
skip configured feature flags in workspaces

### ISSUE THREAD

**Issue by drahnr** [rust-lang/rust-analyzer#6569]
I accidentally had added an explicit feature to the `user` panel of `vs-code`.

![image](https://user-images.githubusercontent.com/667047/99378595-e45f8400-28c7-11eb-9f21-2c9ade3a1488.png)

resulting in a quite confusing, known error popup when the `Cargo.toml` looks perfectly fine.

![image](https://user-images.githubusercontent.com/667047/99378766-1d97f400-28c8-11eb-8e89-f831032fabc7.png)

Expected behaviour: configured extra features are ignored for workspace only manifests.

**Comment by Veykril** [comment]
This seems like a user error to me, we should improve the error reporting here but that is somewhat blocked on VSCode still
