### ISSUE TITLE
Add Rename quick action for VSCode for modules due to different naming conventions

### ISSUE THREAD

**Issue by DesmondWillowbrook** [rust-lang/rust-analyzer#6611]
In particular, rust-analyzer notifies `rustc[non_snake)case]: convert the identifier to snake case` when naming a module with a non-snake case name.

It would be nice if it could provide a quick fix for this, i.e. could convert it for you when one selected a given quick action.

**Comment by DesmondWillowbrook** [comment]
Will be willing to implement this myself if someone points me in the right direction! As of now, I am unable to find the code responsible for generating quick actions.

**Comment by lnicola** [comment]
This is actually implemented -- just that it works for functions, but not modules:

![image](https://user-images.githubusercontent.com/308347/102750985-8b27bc00-436f-11eb-98f0-bed31cc9d98b.png)

The code is around here: https://github.com/rust-analyzer/rust-analyzer/blob/6615fda/crates/hir_ty/src/diagnostics/decl_check.rs.

**Comment by DesmondWillowbrook** [comment]
Checking now, it seems that the module rename assist works, though I can't find any mention of it in the `decl_check` file even at this point in time.

**Comment by lnicola** [comment]
> though I can't find any mention of it in the decl_check file even at this point in time

It's just [a dash away](https://github.com/rust-lang/rust-analyzer/blob/master/crates/hir-ty/src/diagnostics/decl_check.rs) :slightly_smiling_face:.
