### ISSUE TITLE
Setting rust-analyzer.rustcSource runs cargo check on the rustc source

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust-analyzer#6708]
This isn't done for the sysroot either, isn't necessary in the fast majority of the cases and requires unnecessary disk space and cpu usage.

**Comment by Veykril** [comment]
This shouldn't be the case anymore, as we run cargo check on a per workspace basis now, which shouldn't include the rustcsource, unless cargo includes it in workspace
