### ISSUE TITLE
VSCode: Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by alanhkarp** [rust-lang/rust-analyzer#6718]
I got this error several times in a row, then not for several weeks.  Today, I got the error every few minutes for about an hour.

![image](https://user-images.githubusercontent.com/9046515/101121463-126de500-35a5-11eb-9d86-e96f438fca20.png)

I'm including a screen shot because some of the text doesn't show up with copy/paste.  

I also posted an earlier occurrence on the Rust Language forum with information from the log.

**Comment by lnicola** [comment]
Does this still happen if you disable the other extensions?

Also note that `kalitaalexey.vscode-rust` is outdated (it predates the official extension) and you should use neither of those together with `rust-analyzer`.

**Comment by lnicola** [comment]
@alanhkarp did you try to disable the other extension?

**Comment by wyhaya** [comment]
@alanhkarp

I recently had this problem with `Visual Studio Code - Exploration`, and after disabling the `TOML Language Support` extension, the problem disappeared.

I didn't find this problem on stable versions of `Visual Studio Code`.

Are you using `Visual Studio Code - Exploration`?
