### ISSUE TITLE
function signature sometimes contains weird ?0.0 

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/rust-analyzer#6938]
This originally comes from: https://github.com/fannheyward/coc-rust-analyzer/issues/525

I found it's caused by RA: https://github.com/fannheyward/coc-rust-analyzer/issues/525#issuecomment-748294645 instead of client.

I can reproduce it with `mustache` library but it happens only a few times not always.

Any idea on this?

**Comment by GopherJ** [comment]
![Peek 2020-12-18 21-16](https://user-images.githubusercontent.com/33961674/102657640-4e44a500-4176-11eb-9757-9c75c9d4a301.gif)

**Comment by nyanpasu64** [comment]
I've seen this error here and there. I just found a simple code snippet where the function signature hint shows `?0.1` and `?0.2`.

```rust
fn callback(data: &[i16]) {
    data.iter().fold( [cursor here] )
}
```

![screenshot of ?0.1 and ?0.2](https://user-images.githubusercontent.com/913957/102660377-cb006080-412f-11eb-8e7b-5599fa7ec8d9.png)

Editor: vscodium 1.52.1, with rust-analyzer 0.2.416 (from vsixgallery, not the official marketplace).

**Comment by lnicola** [comment]
These are generic type parameters shown without names, probably as De Bruijn indices. We probably lose track of the names during inference.

I've also wondered how we display type parameters that are introduced elsewhere, but it's probably fine to print them directly:

![image](https://user-images.githubusercontent.com/308347/102684107-6cde8680-41de-11eb-9b74-b07c8555f0da.png)

**Comment by flodiebold** [comment]
Hmm, if we lost track of the names during inference, we should be seeing `{unknown}`, not De Bruijn indices. These indices are how we represent the signature in the `ty` / `callable_item_signature` queries; we should probably be applying some substitution to it before displaying it (either the actual one, or one with the original type parameter placeholders). I wonder whether this is a new bug, or just no-one noticed before :thinking:

**Comment by lnicola** [comment]
I think I've noticed it before.

**Comment by bjorn3** [comment]
Does this still happen?

**Comment by lnicola** [comment]
It seems we're now showing `{unknown}`:

![image](https://user-images.githubusercontent.com/308347/146034576-ff9ddb22-d5e1-4a0d-a303-01554fdac046.png)

**Comment by Veykril** [comment]
We could try and show the name of the generic type parameter I guess? Though in some cases I am not sure how helpful that would be if the type parameter comes from the impl since the user can't really know whether its a type param or not anyways(unless it has classic names like `T` etc).

**Comment by lnicola** [comment]
I think this can be closed now?

![image](https://github.com/user-attachments/assets/4fb6fde6-bafc-4912-8592-c48404f40837)

![image](https://github.com/user-attachments/assets/79cf672c-c4c1-4127-93e8-07c67193523c)
