### ISSUE TITLE
server hangs after a textDocument/didChange notification

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/rust-analyzer#7082]
Trace logs

<details>
	<summary>Details</summary>

```
[Trace - 6:52:46 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 8,
        "uri": "file:///home/cheng/Projects/Rust/tunnel-rs/tunnel/src/lib.rs"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 31,
                    "character": 0
                },
                "end": {
                    "line": 31,
                    "character": 0
                }
            },
            "rangeLength": 0,
            "text": "\n    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>\n    where\n        D: Deserializer<'de>;"
        }
    ]
}


[Trace - 6:52:46 PM] Sending notification '$/cancelRequest'.
Params: {
    "id": 36
}


[Trace - 6:52:46 PM] Sending request 'rust-analyzer/inlayHints - (38)'.
Params: {
    "textDocument": {
        "uri": "file:///home/cheng/Projects/Rust/tunnel-rs/tunnel/src/lib.rs"
    }
}


[Trace - 6:52:46 PM] Sending notification '$/cancelRequest'.
Params: {
    "id": 37
}


[Trace - 6:52:46 PM] Sending request 'rust-analyzer/inlayHints - (39)'.
Params: {
    "textDocument": {
        "uri": "file:///home/cheng/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.118/src/de/mod.rs"
    }
}


[Trace - 6:52:47 PM] Sending request 'textDocument/formatting - (40)'.
Params: {
    "textDocument": {
        "uri": "file:///home/cheng/Projects/Rust/tunnel-rs/tunnel/src/lib.rs"
    },
    "options": {
        "tabSize": 4,
        "insertSpaces": true
    }
}


[Trace - 6:52:48 PM] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///home/cheng/Projects/Rust/tunnel-rs/tunnel/src/lib.rs",
        "version": 8
    }
}


[Trace - 6:52:48 PM] Sending notification '$/cancelRequest'.
Params: {
    "id": 40
}


[Trace - 6:53:04 PM] Sending request 'textDocument/hover - (41)'.
Params: {
    "textDocument": {
        "uri": "file:///home/cheng/Projects/Rust/tunnel-rs/tunnel/src/lib.rs"
    },
    "position": {
        "line": 30,
        "character": 9
    }
}
```

</details>

**Comment by GopherJ** [comment]
I had this issue with neovim  + coc.nvim, I tried to reproduce it in vim & vscode but didn't succeed. The problem is

> after a textDocument/didSave notification, server hangs indefinitely

**Comment by lnicola** [comment]
Can you run `sudo strace -fp` with the PID of the hung `rust-analyzer` process (the main one, not the proc macro server)? I assume you're on Linux.

**Comment by GopherJ** [comment]
yes I'm on Linux, let me try it

**Comment by lnicola** [comment]
Make that `strace -s 2048 -fp ...`, I guess. If nothing else, it should show the LSP communication.

**Comment by GopherJ** [comment]
![Peek 2020-12-29 19-08](https://user-images.githubusercontent.com/33961674/103304665-82875380-4a09-11eb-80de-e7108397ae08.gif)

**Comment by GopherJ** [comment]
and the following is what it prints while calling `textDocument/hover`

![Peek 2020-12-29 19-13](https://user-images.githubusercontent.com/33961674/103304889-12c59880-4a0a-11eb-9625-695508e9c453.gif)

and this is what it shows the most
![image](https://user-images.githubusercontent.com/33961674/103304953-3983cf00-4a0a-11eb-9cc7-122e16721ca2.png)

**Comment by lnicola** [comment]
Hmm, maybe `strace -s 2048 -etrace=%file,%process,%desc` to filter out those, then do something in vim.

In that log, it looks like it's allocating and freeing memory in a loop. I've never seen it doing this.

**Comment by GopherJ** [comment]
@lnicola it's showing:

![image](https://user-images.githubusercontent.com/33961674/103305265-f4ac6800-4a0a-11eb-87ef-14888da1ef2d.png)

**Comment by lnicola** [comment]
So nothing happens when you do an action in Code (so that it receives a LSP message)? And I noticed you had two instances running, one probably older and stuck.

Also, you might know this, but you have a typo in `<TunnelAction as Serialize>::serialize()`: `clsoe`. Unfortunately, I don't think that what causes `rust-analyzer` to hang.

**Comment by lnicola** [comment]
> it's showing while I'm sending textDocument/hover

Oh, okay.

**Comment by GopherJ** [comment]
basically I don't have any response and coc.nvim reports `server connection lost`

**Comment by GopherJ** [comment]
If I send `textDocument/definition`, strace doesn't output anything

**Comment by lnicola** [comment]
I tried to install `coc.nvim`, but I think my previous LSP client somehow still runs.

**Comment by GopherJ** [comment]
all my stuffs are here: https://github.com/GopherJ/cfg/tree/master/coc

**Comment by lnicola** [comment]
Nope, I can't reproduce it https://asciinema.org/a/vCxxUwQhPIN4JFzidC0jvKnN8 :disappointed:

(and I'm bad at vim)

**Comment by GopherJ** [comment]
@lnicola it's not easy to reproduce, I can succeed around 3 out of 10

**Comment by lnicola** [comment]
Are you using any proc macros? Does it still happen if you disable those?

**Comment by lnicola** [comment]
Might as well attach a debugger to it. Untested:

```
sudo gdp -p <PID>
thread apply all bt
```

**Comment by GopherJ** [comment]
> Are you using any proc macros? Does it still happen if you disable those?

yes I'm using proc macros, I just tested it didn't help

**Comment by GopherJ** [comment]
> Might as well attach a debugger to it. Untested:
> 
> ```
> sudo gdb <PATH_TO_RA> -p <PID_OF_RA>
> thread apply all bt
> ```

I seems didn't succeed to attach:

```
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/cheng/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer...done.
Attaching to program: /home/cheng/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer, process 24195
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
warning: process 24195 is already traced by process 17752
ptrace: Operation not permitted.
(gdb) Quit
(gdb) q
```

**Comment by GopherJ** [comment]
I'm wondering how should I debug it? I would like to see some prints from rust-analyzer

**Comment by GopherJ** [comment]
ok I've found that I need to use debug mode of rust-analyzer, now I can see more traces, I'll provide you more info

**Comment by GopherJ** [comment]
@lnicola here you are
![Peek 2020-12-30 01-16](https://user-images.githubusercontent.com/33961674/103322077-f8f17900-4a3c-11eb-992b-cb341b2e4341.gif)

**Comment by GopherJ** [comment]
If I see the active thread (high cpu) of rust-analyzer, I can see it red socket symbols, I'm not sure what does it mean, but I assume it's not a good sign:

![image](https://user-images.githubusercontent.com/33961674/103322688-54246b00-4a3f-11eb-9490-20fc44bfb820.png)

**Comment by GopherJ** [comment]
actually I'm wrong, even if it was displayed as red. It doesn't seem to be broken connection,  I tested a working instance it's also red

![image](https://user-images.githubusercontent.com/33961674/103323508-699b9400-4a43-11eb-860e-79b88f81abf1.png)

**Comment by GopherJ** [comment]
@lnicola If I check carefully the gif, I can see the edit which caused this to happen is:


![image](https://user-images.githubusercontent.com/33961674/103358262-79ec5700-4ab5-11eb-9879-85475b6a31a8.png)

**Comment by Veykril** [comment]
Does this still happen for you?
