### ISSUE TITLE
Shadowed macro causes macro-error

### ISSUE THREAD

**Issue by vallentin** [rust-lang/rust-analyzer#7084]
The first `foo!(1);` uses to the subsequent shadowed `macro_rules! foo`. Causing ```expected leaf: `,` rust-analyzer(macro-error)```. Performing "Go to Definition" confirms this, as the cursor jumps to the second `macro_rules! foo`.

```rust
fn main() {
    macro_rules! foo {
        ($a:expr) => {};
    }

    foo!(1);

    macro_rules! foo {
        ($a:expr, $b:expr) => {};
    }

    foo!(1, 2);
}
```

![image](https://user-images.githubusercontent.com/17464404/104036440-b1ed4b80-51d3-11eb-9a5e-ef75d1dec742.png)

This issue must have been introduced lately, as a few weeks ago this was not an issue.

Issue exists on both stable and the latest nightly release:
- rust-analyzer version: 2020-12-28 (1d53075)
- rust-analyzer version: nightly (77ad203)

**Comment by edwin0cheng** [comment]
triage: I can't reproduce in current master 8584d2692. 

@vallentin Would you mind to try it again ?

**Comment by vallentin** [comment]
It still occurs on the latest releases. However, that's of course prior to 8584d269262e73aa7c3ebe25b1d61483375de267. Can I easily obtain a build, that doesn't require me building rust-analyzer? 😅

rust-analyzer version: 2021-01-04 (5b86ff3)
rust-analyzer version: nightly (a3e5dcc)

**Comment by lnicola** [comment]
@edwin0cheng https://github.com/rust-analyzer/rust-analyzer/commit/8584d269262e73aa7c3ebe25b1d61483375de267 isn't on `master`, you meant #7145.

@vallentin not really, you'd need to wait until tomorrow. Building isn't that hard, though.

**Comment by edwin0cheng** [comment]
Sorry, @lnicola is right and I meant #7145.

However, I tried a3e5dcc1 and 5b86ff3e,  I can't reproduce the errors, so ... What os and ra settings you are using ? 

> Also, that's a lovely issue report, I wish we had more of these.
Indeed

**Comment by vallentin** [comment]
It wasn't the difficulty, it's more that I'm expecting a clean build to take quite a bit of time.

I'm running Windows 10. I tested the above using only default settings, with the exception of `"rust-analyzer.updates.channel": "nightly"` to test the nightly release.

**Comment by flodiebold** [comment]
A clean release build takes about 5 minutes.

**Comment by vallentin** [comment]
Just under 3 minutes, nice. Alright, so I've just tried using #7145, i.e. [edwin0cheng/rust-analyzer](https://github.com/edwin0cheng/rust-analyzer). Sadly, the issue still persists.

Checking _"Show RA Version"_ show the expected commit. So I sadly don't think that fixes this issue.

rust-analyzer version: 2021-01-04 (be02ac9)

**Comment by vallentin** [comment]
Just under 3 minutes, nice. Alright, so I've just tried using #7145. Sadly, the issue still persists.

Checking _"Show RA Version"_ show the expected commit. So I sadly don't think that fixes this issue.

rust-analyzer version: 2021-01-04 (76f2b9d)

**Comment by flodiebold** [comment]
I can't reproduce the error in current master either, and changing the second macro definition to take just one argument *does* cause an error only in the second call; though it's worth noting that goto definition, hover etc. refer to the wrong macro for the first definition.

**Comment by vallentin** [comment]
Hmm, that's odd. I assume you aren't using Windows. However, I don't at all see how this would be affected by OS, so it's rather confusing.

Is there any more information I can provide?

-----

Here's step-by-step what I do to reproduce the issue (on Windows 10):

```shell
git clone https://github.com/rust-analyzer/rust-analyzer
cd rust-analyzer
cargo build --release
cp target/release/rust-analyzer.exe ~/AppData/Roaming/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-pc-windows-msvc.exe
```

Now we create a new project:

```shell
cd ..
cargo new foo
code foo
```

Then paste the following code in `src/main.rs`.

```rust
fn main() {
    macro_rules! foo {
        ($a:expr) => {};
    }

    foo!(1);

    macro_rules! foo {
        ($a:expr, $b:expr) => {};
    }

    foo!(1, 2);
}
```

Checking _"Show RA Version"_ correctly shows:

rust-analyzer version: 2021-01-04 (903d1f8)

-----

Here's a screenshot showing both the issue and the version:

![image](https://user-images.githubusercontent.com/17464404/104035165-1ad3c400-51d2-11eb-87c5-ac6cf3e84bbc.png)

**Comment by flodiebold** [comment]
Oh, putting all that code into `main` makes a big difference. Local definitions are mostly not supported yet.

**Comment by vallentin** [comment]
I literally just had the same thought pop into my head after commenting. Now I feel silly!

How come this worked previously?

**Comment by flodiebold** [comment]
It didn't, we just didn't emit those macro errors until recently.

**Comment by lnicola** [comment]
That's https://github.com/rust-analyzer/rust-analyzer/issues/1559.

**Comment by vallentin** [comment]
Is there any way to suppress that error?

I have a few files that are affected by this change. Which prevents any other errors from being detected.

**Comment by flodiebold** [comment]
You can add `"macro-error"` to the `rust-analyzer.diagnostics.disable` setting.

**Comment by vallentin** [comment]
Thanks!

The files where the issue occurs in conjunction are quite big. I'll look into making a MCVE, and post it if/when I'm able to.

**Comment by jonas-schievink** [comment]
Triage: Still happening, presumably because we don't really handle legacy macro scopes in `Resolver`

**Comment by lnicola** [comment]
This works now AFAICT.

**Comment by Veykril** [comment]
🤨 oh it does, but how? 😅
