### ISSUE TITLE
One-off crash with "invalid type: floating point `...`, expected u64"

### ISSUE THREAD

**Issue by cole-miller** [rust-lang/rust-analyzer#7129]
I encountered a one-off rust-analyzer crash while using the VSCode plugin and thought I'd share the error backtrace.

[rust_analyzer_error_log.txt](https://github.com/rust-analyzer/rust-analyzer/files/5759601/rust_analyzer_error_log.txt)

Feel free to close if this isn't actionable/useful. Thanks for your work on this project!

**Comment by lnicola** [comment]
That's a strange one:

```
thread 'main' panicked at 'Invalid request
Method: textDocument/codeAction
 error: invalid type: floating point `18446744073709552000`, expected u64', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.4.0/src/msg.rs:163:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429
   2: lsp_server::msg::Request::extract::{{closure}}
   3: lsp_server::msg::Request::extract
   4: rust_analyzer::dispatch::RequestDispatcher::on
   5: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
   6: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   7: rust_analyzer::main_loop::main_loop
   8: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

So we're getting a number which we can't deserialize to `u64`:

```
18446744073709552000
18446744073709551616 = u64::MAX
```

But I don't know what that might be.

**Comment by cole-miller** [comment]
Unsigned underflow from casting -384 to `u64`?

**Comment by lnicola** [comment]
It's not an underflow, Code sent us a number close, but larger than the upper limit of `u64`. Code uses floating-point numbers, of course, and large `u64` values will not even be representable there. So maybe it tried to send `-1`, but didn't manage to.

Next step would be to take a look at the `textDocument/codeAction` request and see what numbers are there.

**Comment by Veykril** [comment]
Closing until we find a reproducer
