### ISSUE TITLE
Unresolved import error for "ed25519_dalek::Keypair"

### ISSUE THREAD

**Issue by pmuens** [rust-lang/rust-analyzer#7243]
First of all: Thanks for creating `rust-analyzer`.

I'm using the VSCode extension version 0.2.449 and I'm running into the "rust-analyzer(unresolved-import)" issue which was already reported before.

I followed the advice to enable the following settings to no avail:

```json
{
  "rust-analyzer.cargo.loadOutDirsFromCheck": true,
  "rust-analyzer.procMacro.enable": true
}
```

Here's my full `settings.json` file (I've restarted VSCode as prompted after changing the extension settings):

```json
{
  "editor.tabSize": 4,
  "editor.formatOnSave": true,
  "editor.formatOnPaste": true,
  "editor.formatOnType": true,
  "files.insertFinalNewline": true,
  "files.trimTrailingWhitespace": true,
  "[rust]": {
    "editor.defaultFormatter": "matklad.rust-analyzer"
  },
  "rust-analyzer.cargo.loadOutDirsFromCheck": true,
  "rust-analyzer.procMacro.enable": true
}
```

Here's the code snippets which causes the error to pop up:

```rust
// Cargo.toml dependency: ed25519-dalek = "1.0.1"
use ed25519_dalek::Keypair; // <--
```

Let me know if you need anything else and thanks in advance for looking into this 👍

**Comment by Veykril** [comment]
The problem is this line https://docs.rs/ed25519-dalek/1.0.1/src/ed25519_dalek/lib.rs.html#238 I believe. Rust analyzer checks with `test` enabled so the entire crate looks empty to it.

**Comment by lnicola** [comment]
CC https://github.com/rust-analyzer/rust-analyzer/issues/7225

**Comment by jonas-schievink** [comment]
I guess what we *actually* want is to *disable* `test` when a crate is used as a dependency, but *enable* it when opening the crate in the editor (unless the user disables it there, as per #7225).

No idea if/how this would make sense to the user though.

**Comment by lnicola** [comment]
I suppose there's no chance of having something like "assume `--cfg test` while editing code gated by `#[cfg(test)]`, right?

**Comment by jonas-schievink** [comment]
That would actually be my preferred solution. Not sure how feasible it is to implement though.

**Comment by flodiebold** [comment]
I think both things you wrote are basically the same :smile: I.e. we need to have each crate (or at least each leaf crate) in a test and non-test version in the crate graph. Then hopefully the "assume `--cfg test` while editing code gated by `#[cfg(test)]`" would happen automatically as long as our "selecting the crate from the cursor position" logic is smart enough?

**Comment by mieubrisse** [comment]
Adding a datapoint that I'm getting the exact same error:
```
// Cargo.toml: ed25519-dalek = "1.0.1"
use ed25519_dalek::Keypair;
```

**Comment by jplatte** [comment]
dalek_ed25519 issue: https://github.com/dalek-cryptography/ed25519-dalek/issues/173

**Comment by jonas-schievink** [comment]
We should make this work by default

**Comment by matklad** [comment]
Hm, but why do we enable `test` for a crates.io dependency at all? We should do this only for workspace members, right?

**Comment by jonas-schievink** [comment]
Presumably to make IDE work when you browse unit tests

**Comment by bjorn3** [comment]
You rarely need to browse unit tests of a crates.io dependency.

**Comment by jplatte** [comment]
… and even then RA could only load the crate with `test` once you start browsing its source code. Wasn't something like this planned a while ago?

**Comment by zicklag** [comment]
If you want a quick fix that works right now you can add this to your VSCode settings file:

```json
"rust-analyzer.cargo.unsetTest": [
    "core",
    "ed25519-dalek"
  ],
```

This removes the `cfg(test)` flag from that crate while rust analyzer is building it. `core` probably isn't necessary for this specific issue. I can't remember why I had that in there, but it fixes it for me, and you can add any other crates that have similar problems to that list, too.

**Comment by g00nix** [comment]
Did anybody figure out the fix for neovim? I tried this but it doesn't work:
```lua
require'lspconfig'.rust_analyzer.setup({
    settings = {
        ["rust-analyzer"] = {
            cargo = {
              unsetTest = {
                  "core", "ed25519_dalek", "curve25519_dalek"
                }
            }
        }
    }
})
```

**Comment by flodiebold** [comment]
This works now.
