### ISSUE TITLE
Synchronize releases with updates to Rust repository submodule

### ISSUE THREAD

**Issue by tweksteen** [rust-lang/rust-analyzer#7282]
This was previously reported and fixed as a one-off in #5802. But the [git submodule reference](https://github.com/rust-lang/rust/tree/master/src/tools) used in the Rust repository is now 4 months behind the release in this repository. That is, the preview available via rustup is outdated. 

Would it be possible to add a step as part of the weekly release, to update the submodule reference in the main Rust repository? Or if weekly is too frequent, settle for a monthly update?

Thanks

**Comment by lnicola** [comment]
You might have already seen it, but https://github.com/rust-lang/rust/pull/80984 updates the RA submodule.

Ideally we'd make this happen automatically, though.

**Comment by tweksteen** [comment]
I wasn't, thanks for sharing the link.

Yes, automation would be best. It's also possible to have a manual step as part of the release process in the meantime (for instance, when writing down the ChangeLog).

**Comment by lnicola** [comment]
I think there's an `cargo xtask promote-release` subcommand, but I haven't tried it.

Unfortunately, this still doesn't guarantee timely updates. My PR has been open for 5 days and will probably take that much again to get merged.

**Comment by Veykril** [comment]
We are no longer a submodule of the rust repo but a subtree instead, I don't think automating that will work due to possible conflicts.
