### ISSUE TITLE
Finding all references to functions called `new` can take a long time

### ISSUE THREAD

**Issue by umanwizard** [rust-lang/rust-analyzer#7404]
Sorry for the Materialize dependency, but I think a large-ish codebase is probably necessary to repro this.

To repro:

1. Check out https://github.com/MaterializeInc/materialize
2. Navigate over `fn new` in `impl Locald` (as of this writing, it's in src/expr/src/id.rs:45
3. Find all references
4. Observe it taking about 60s.

Maybe since finding references involves filtering by a string first, the very common name is what makes things slow? Just a guess.

**Comment by lnicola** [comment]
Confirmed:

```
   80 textDocument/references             36873ms
```

Seems to burn CPU in `chalk` for some reason. The second "find all references" (on `GlobalId::is_system`) takes 63ms, though.

**Comment by matklad** [comment]
>Seems to burn CPU in chalk for some reason.

It basically type-checks the world (every function that has a `new` call) :D. To fix this, we need to double-check that we are using the correct scope here and don't, eg look in the stdlib. Then, we either need to come up with some sound optimization here (like looking for the struct at first), or to do something extra-clever and run the search on resolved code (which we might need for macros)... Let me draft an issue...

**Comment by alexkirsz** [comment]
We're frequently running into this in our codebase, which is about 230 crates large. Any method with a common-enough name like `new` or `map` will take in the dozens of seconds, sometimes minutes, to complete.

**Comment by Veykril** [comment]
This should have been hopefully improved by #17927
