### ISSUE TITLE
Multiple test codes with main function in SRC directory of cargo project cannot jump

### ISSUE THREAD

**Issue by liuhangyu** [rust-lang/rust-analyzer#7540]
Multiple test codes with main function in SRC directory of cargo project cannot jump

ls
Cargo.lock  Cargo.toml  src  target
liuhy@liuhy:~/learning/r-test/baselearn$ tree src/
src/
├── fn.rs
├── hash.rs
├── main.rs
├── move.rs
├── read_file.rs
├── string1.rs
├── string.rs
├── time2.rs
└── time.rs

0 directories, 9 files

**Comment by lnicola** [comment]
What do you mean by "cannot jump"?
