### ISSUE TITLE
Method auto-complete randomly doesn't work (jumps between three different behaviors)

### ISSUE THREAD

**Issue by kangalioo** [rust-lang/rust-analyzer#7560]
https://user-images.githubusercontent.com/21220820/106952730-c882b600-6731-11eb-9c85-7f6c14c2f138.mp4

As you can see in the video, when typing the first few characters of a method, three different things may happen, seemingly without no pattern:
1. rust-analyzer's nice method list pops up
2. VSCode's built-in autocomplete pops up
3. Nothing pops up

Through experimentation, I could identify what triggers each of the behaviors:
1. type all characters normally
2. type the first 2-3 characters rapidly
3. type the last 2-3 characters rapidly

This issue seems easy to reproduce, but here is a copy-and-pastable code just in case (I tested it in a blank project, it behaves the same)
```rust
fn trim_multiline(string: &str) -> &str {
    while string./*type "ends" here, in varying speeds*/
}
```

Versions:
- VSCode: 1.52.1
- rust-analyzer: v0.2.473
- OS: KDE Linux

If there is anything else I can provide to make the issue more clear, I'm happy to provide it

**Comment by SomeoneToIgnore** [comment]
Thank you for finding the time to record a video and experiment with it.

Most probably it's the same case as discussed in https://github.com/rust-analyzer/rust-analyzer/issues/7542
When zero completion input is done after `.` symbol, we might get slow when finding traits appropriate for importing.

I have a few ideas in the same issue on how to improve the situation, we also have an issue for benchmarks.
