### ISSUE TITLE
New command

### ISSUE THREAD

**Issue by Zenthae** [rust-lang/rust-analyzer#7612]
Feature :
Adding a command to open cargo doc

Why :
Lazy people (me) love to do less, so i'd like to know if it's possible to add a command so that i just have to `crtl+shift+p` > open doc
and it'll start the doc on the web. (execute `cargo doc --open` in a new terminal under the hood)

**Comment by lnicola** [comment]
Isn't this already available?

**Comment by Zenthae** [comment]
their is only a `open the doc under cursor` but not that handy, at least that what i feel

**Comment by lnicola** [comment]
Yes, and it works for both std items and external creates. Do you want one that opens the current crate docs? Current module? Item?

**Comment by Zenthae** [comment]
it depends on published docs, so it's not up to date when you use git versions

**Comment by Zenthae** [comment]
i'm trying to implement it myself, so i can make a pull request later, but i don't understand how to start the development mode of the extension,
i've read this https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/dev#launching-rust-analyzer but it doesn't help very much, so far i'm using the **Run Installed Extension** launch configuration from `launch.json`. it does start a new vscode session with only `rust-analyzer` enabled. (little warning btw: `rust-analyzer@0.4.0-dev: The engine "vscode" appears to be invalid.`)
but then here come the issue, how i'm supposed to test the extension since it doesn't activate by itself, 'cause of the following
```json
...
"activationEvents": [
        "onLanguage:rust",
        "onCommand:rust-analyzer.analyzerStatus",
        "onCommand:rust-analyzer.memoryUsage",
        "onCommand:rust-analyzer.reloadWorkspace",
        "workspaceContains:**/Cargo.toml"
    ],
...
```
but the new editor start with an empty file.

So what i'd like to know is, i'm starting the développement mode right, and if it is, how i'm supposed to test what i change since i can't activate the extension in dev mode.

**Comment by lnicola** [comment]
The extension should activate once you open a Rust project. I'm not sure if you need to do anything else to set up debugging.

**Comment by andrewbanchich** [comment]
@lnicola I'm looking for something like this myself. The current `open-external-docs` only opens the docs.rs based on a URL scheme. However, it doesn't work with crates not published to docs.rs. It would be extremely useful for it to compile local, private crate doc sites.

**Comment by zacps** [comment]
@andrewbanchich It should work with private sites as long as the crate correctly sets the [`html_root_url`](https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html#html_root_url)

**Comment by EliasHolzmann** [comment]
I'm not sure I understand the exact feature requested here, but if this is about adding a new command that opens local documentation instead of the web documentation: This is available via the old command since a few weeks ago, see #15728. This issue can therefore be closed, I believe.

**Comment by Veykril** [comment]
Indeed, if the local docs have been built, the previous command will open the local ones instead now, falling back to the web docs.
