### ISSUE TITLE
Extract into Function does not create a generic function with constraints when extracting generic code

### ISSUE THREAD

**Issue by gbutler69** [rust-lang/rust-analyzer#7636]
With the new "Extract into Function" code action that recently landed, although you can extract generic code, it does not make the new function generic (does not include the Generic parameters within brackets preceding the function name) and it does not include the generic constrains in the where clause. This makes the use of "Extract into Function" with generic code sub-optimal.

**Comment by lnicola** [comment]
Fixed in https://github.com/rust-lang/rust-analyzer/pull/12556.
