### ISSUE TITLE
User defined snippets/actions [dreaming...]

### ISSUE THREAD

**Issue by eulerdisk** [rust-lang/rust-analyzer#772]
[This is not a feature request or something, I just want to throw in some ideas]
Given that `ra` parses and analyses everything on the fly in the current project and all its dependencies, it would be relatively easy to do something like this:

```
// Somewhere in the code (in comments for example)
// you can define custom snippets, which will be parsed by RA
// which can then serve them in auto-completion.
// This could be a snippet called salsaqg for defining a simple query group

//@RA_SNIPPET_BEGIN[salsaqg, [names to import], [other params for RA]]
//#[salsa::query_group($0)]
//trait $1: salsa::Database {
//    fn input_string(&self, key: ()) -> Arc<String>;
//}
//...
//@RA_SNIPPET_END
```

The idea can be extended to assists or whatever.
This way project can define their own snippets for boilerplate stuff for example.

**Comment by matklad** [comment]
Yeah, I think we could do something like this! Probably not literally as comments in the code, but as a separate configuration file. I can see how this could be more powerful and useful than editor-provided snippets!

**Comment by Veykril** [comment]
The infra for this is implemented actually with basic custom completions (that can even import items now) so I think we can close this in favor of more feature improvement focused issues.
