### ISSUE TITLE
add .tar.gz in release instead of just .gz

### ISSUE THREAD

**Issue by prabirshrestha** [rust-lang/rust-analyzer#7747]
`tar` is standard way to ship most of the binaries. It is so popular that even Windows now ships with it. https://techcommunity.microsoft.com/t5/containers/tar-and-curl-come-to-windows/ba-p/382409

Is it possible to include `.tar.gz` for all platforms including linux/mac/windows.  This makes it easy for users to download and extract without any sudo permissions. 

https://github.com/mattn/vim-lsp-settings/pull/392

**Comment by flodiebold** [comment]
As @lnicola wrote on that issue, if you can unpack `.tar.gz`, you should be able to unpack `.gz`, since it's just a single compressed file as opposed to an archive. I don't know where sudo permissions would come into play.

**Comment by lnicola** [comment]
It looks like Windows comes with a version of `tar` that doesn't recognize `.gz`. Considering that anyone running `Vim` on Windows might already have MSYS or something similar, and since `rust-analyzer` is also available in `rustup`, I'm not sure we should add an extra release asset.

**Comment by Veykril** [comment]
no longer relevant
