### ISSUE TITLE
rust-analyzer.files.excludeDirs is not working

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#7755]
Unfortunately this didn't seem to help. I added `.rustwide` and `.rustwide-docker` to `rust-analyzer.files.excludeDirs` and reloaded VSCode, but RA is still using over 2 GB (when most other people were only seeing about 1.3 GB used).

_Originally posted by @jyn514 in https://github.com/rust-analyzer/rust-analyzer/issues/7451#issuecomment-778956579_

**Comment by matklad** [comment]
Some pointers to code:

https://github.com/rust-analyzer/rust-analyzer/blob/3926f60cb525592400018b0afb0c0553dabfdb32/crates/rust-analyzer/src/config.rs#L541-L550

https://github.com/rust-analyzer/rust-analyzer/blob/3926f60cb525592400018b0afb0c0553dabfdb32/crates/rust-analyzer/src/reload.rs#L262-L289

(I wonder if the above piece of code should handle `exclude`?)

https://github.com/rust-analyzer/rust-analyzer/blob/3926f60cb525592400018b0afb0c0553dabfdb32/crates/rust-analyzer/src/reload.rs#L441

https://github.com/rust-analyzer/rust-analyzer/blob/3926f60cb525592400018b0afb0c0553dabfdb32/crates/vfs/src/loader.rs#L29

And the place where actual exclusion is happening: 

https://github.com/rust-analyzer/rust-analyzer/blob/3926f60cb525592400018b0afb0c0553dabfdb32/crates/vfs-notify/src/lib.rs#L181

To fix this, I'd start with making a minimal example where we don't exclude things, and then adding   `eprintln!`s to the linked places in code.

**Comment by saveriomiroddi** [comment]
Doesn't work also for me; the documentation doesn't say much, so I'm not sure if I need to set the value in a specific way.

My project layour is:

```
.
├── breakout_example
├── resources -> ../resources/boing
├── src
```

inside `breakout_example` there is a `breakout.rs` file. I can't find any way to exclude it from `rust-analyzer` (I just need it the syntax highlight).

This is the related setting:

```
    "rust-analyzer.files.excludeDirs": [
      "**/breakout_example"
    ]
```

I think it should work, because that's the standard VSC definition. I've tried alternatives, but I couldn't find any way to exclude it.

**Comment by lnicola** [comment]
Not that I don't believe you, but can you say how you are testing? I'm asking because we set these up in a couple of places (file change notifications, file saves and something else too -- project load?).

**Comment by saveriomiroddi** [comment]
> Not that I don't believe you, but can you say how you are testing? I'm asking because we set these up in a couple of places (file change notifications, file saves and something else too -- project load?).
> 
> matklad's comment above about not handling exclusions seems relevant. That's the file watcher registration.

Hello! Thanks :) Let me create the simplest test case and I'll get back (tomorrow or the day after); hopefully, simplifying the current project will show more clearly where the problem is.

**Comment by saveriomiroddi** [comment]
It seems to be a more complex problem.

What I'm observing is (with the directory excluded):

- I open the file in VSC
- I close the VSC workspace
- I open the workspace
- the file is not marked with any error
- at some point during the RA indexing, the error is added to the file (`file not included in module tree`)
- I then close the file
- I reopen it
- *no more error!*
- I change the file with a permanent change, e.g. add `const PIZZA: i32 = 1;`, and save
- *the error appears again*

If I change the file with a change that is reverted by the autoformatter (e.g. add a space after the terminal `;` of a statement), the error does *not* appear again.

**Comment by saveriomiroddi** [comment]
> Not that I don't believe you, but can you say how you are testing? I'm asking because we set these up in a couple of places (file change notifications, file saves and something else too -- project load?).
> 
> matklad's comment above about not handling exclusions seems relevant. That's the file watcher registration.

Hello!

Here's a minimal test case:

```sh
cargo new mytest2
cd mytest2

mkdir excl
echo abc > excl/abc.rs

mkdir .vscode
cat > .vscode/settings.json << 'JSON'
{
  "rust-analyzer.files.excludeDirs": [
    "**/excl"
  ]
}
JSON

# after the first command, switch back to the terminal
code .
code excl/abc.rs
# now, in VSC, abc.rs shows the error
```

**Comment by anovs** [comment]
I have the same issue. I have a `blueprint-templates` folder at the root of my project that contains some files that serve as templates. These files include stuff like `{{ $myVar }}` that are meant to be replaced when a file is created, so they're full of errors. I tried every possible combinations in `"rust-analyzer.files.excludeDirs"`, but I can't seem to get rust-analyzer to ignore the folder.

**Comment by yukitaka13-1110** [comment]
Any update?

**Comment by jyn514** [comment]
@yukitaka13-1110 My understanding is someone still needs to investigate why this doesn't work: https://github.com/rust-analyzer/rust-analyzer/issues/7755#issuecomment-847266325

**Comment by Paveloom** [comment]
Seems to be especially relevant when developing Flatpak applications: see #8161.

**Comment by polyjitter** [comment]
Still dealing with this... still no way to do this? Also trying to work with flatpaks and makes autocompletion just not exist.

**Comment by Paveloom** [comment]
@polyjitter Do you use `flatpak-builder`? Ignoring the `.flatpak-builder` directory works for me:

```lua
-- A snippet from my Neovim config
-- <...>
server = {
    standalone = false,
    settings = {
      ["rust-analyzer"] = {
        files = {
          excludeDirs = { ".flatpak-builder" }
        },
		-- <...>
      },
    }
  },
-- <...>
```
