### ISSUE TITLE
Listing symbols does not see aliases

### ISSUE THREAD

**Issue by JDuchniewicz** [rust-lang/rust-analyzer#7938]
Issue from [coc-rust-analyzer](https://github.com/fannheyward/coc-rust-analyzer/issues/636)

The problem is best illustrated as such:

We have a `struct Vec3;` and a `use Vec3 as Color` statement.
When running `CocList -I symbols` and searching for `Vec3` it finds it just fine but does not resolve `Color`.

This is apparently a limitation of aliases and has been discussed in libs zullip recently. Relevant [issue](https://github.com/rust-lang/rust/issues/21903) in the language?

**Comment by jonas-schievink** [comment]
That's not a type alias, just a renamed import. What LSP API does `CocList -I symbols` use? `workspace/symbol`?

**Comment by JDuchniewicz** [comment]
Unfortunately, I am not able to find it with the codebase, maybe @fannheyward could help?

**Comment by fannheyward** [comment]
Yes, coc uses `workspace/symbol`, tested with VSCode + rust-analyzer, same results.
