### ISSUE TITLE
How to resolve »expected simple binding, found nested binding«-error

### ISSUE THREAD

**Issue by sivizius** [rust-lang/rust-analyzer#8004]
I get the error »expected simple binding, found nested binding SomeMacroVariable« on usage of an external macro, but `cargo build` compiles just fine. However, if the same macro is not in an external crate but just in a module, this error does not occur. How do I resolve this issue?

**Comment by flodiebold** [comment]
If it works with cargo, then it's a bug in rust-analyzer's macro expansion code. Can you provide the macro?
