### ISSUE TITLE
HirDisplay should display `impl Fn*` for closures when the target is SourceCode

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#8147]
After #8144 we error on displaying closures when the target is SourceCode to prevent panics from trying to use this output for `make::ty`, ideally we want to instead emit `impl Fn*` as thats the closest to a closure type we can get. For that we require more knowledge about what kind of closure we are dealing with though which is currently not something we have the analysis for.

**Comment by HKalbasi** [comment]
fixed in #14470
