### ISSUE TITLE
Employ some kind of fallback policy for `rust-analyzer.server.path` setting

### ISSUE THREAD

**Issue by EFanZh** [rust-lang/rust-analyzer#8160]
I use Visual Studio Code on both Linux and Windows for development, and I use settings sync provided by Visual Studio Code. I want to use the rust-analyzer binary provided by the system package manager on Linux, and the rust-analyzer binary downloaded by the rust-analyzer extension, but the settings sync function does not support different settings for different operating systems.

I hope there could be a fallback policy for the `rust-analyzer.server.path` setting, maybe something like:

- If `rust-analyzer.server.path` is `null`, the extension tries the server binary downloaded by the extension, if it does not work, fallback to `"rust-analyzer"` in the `Path` or `PATH` environment variable;
- If `rust-analyzer.server.path` is `"path-to-rust-analyzer-binary"`, the extension tries to use `path-to-rust-analyzer-binary` first, if it does not work, fallback to downloading the latest server binary.

It is possible to use workspace settings for different operating systems as a workaround, but I need to configure the setting for all projects on one platform. It is much more convenient to have a global settings for this.

**Comment by matklad** [comment]
It seems like the proper solution here is to implement host-dependent config on the VS Code side, so this is out of scope. If there's some simple work-around, we can merge it, but complex fallbacks do make me uneasy.

**Comment by matklad** [comment]
An interesting work-around would be to build rust-analyzer from source.

**Comment by lnicola** [comment]
Or to install it with `rustup` (we've been updating it more frequently lately). This does feel out of scope, and people will ask for every combination possible and then some, but silently switching from a binary in PATH to a downloaded one seems bad.

**Comment by Veykril** [comment]
Out of scope
