### ISSUE TITLE
Add: "show LSP logs" command

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust-analyzer#8233]
To get LSP logs in vscode, one needs to set a rather obscure setting: `"rust-analyzer.trace.server": "verbose"`. This should be a command which is discoverable via command palette. 

It should be implemented by the client, and in language agnostic way. The best way to arrive at that state though is to implement it ourselves and then poke editor's maintainers with "see what we have here! You should have this too". 

This is mostly client-side work:

* add command to package.json
* implement command in commands.ts by writing go the settings (not sure what's the best scope would be -- probably project-wide) and maybe opening the corresponding vscode view
* documenting it in the manual.adoc (preferably with equivalents for other editors)
* adjusting docs in `dev` folder if they mention logs.

**Comment by jjoeldaniel** [comment]
Hey @matklad , I'd like to work on this.
