### ISSUE TITLE
Cannot activate rust-analyzer on installation

### ISSUE THREAD

**Issue by Spiceyy** [rust-lang/rust-analyzer#8278]
When installing rust analyzer and installing the language server I get the following error: **Cannot activate rust-analyzer: command 'rust-analyzer.reload' already exists**

Rust extension is not installed, only rust-analyzer. Have tried reinstalling, the error always pops up after either restarting vsc or reinstalling the extension.

I am using the following toolchain installed via rustup:
**installed toolchains**
stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

**active toolchain**
stable-x86_64-pc-windows-msvc (default)
rustc 1.51.0 (2fd73fabe 2021-03-23)

**Comment by Veykril** [comment]
Are you still running into this?
