### ISSUE TITLE
"cyclic deps" on rust-lang/rust workspace

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust-analyzer#8330]
Steps to replicate:
1. Check out https://github.com/rust-lang/rust/commit/6beac7ada1af649615cafd2f2a83bff81a20b718
2. Open `src/librustdoc/clean/types.rs` and put the cursor on line 196 (`crate fn resolved_links`)
3. Press Ctrl+Shift+I ("Format document")

```
[ERROR project_model::workspace] cyclic deps: rustc_std_workspace_core(CrateId(1165)) -> core(CrateId(200))
[Error - 5:42:32 PM] Request textDocument/formatting failed.
  Message: Broken pipe (os error 32)
  Code: -32603
```

**Comment by SergioBenitez** [comment]
This is also happening with `rocket`. As a result, I am getting no diagnostic messages.

**Comment by edwin0cheng** [comment]
maybe #2414 ?

**Comment by Veykril** [comment]
Closing in favor of https://github.com/rust-lang/rust-analyzer/issues/14167
