### ISSUE TITLE
Reference completions are a bit too aggressive

### ISSUE THREAD

**Issue by Lucretiel** [rust-lang/rust-analyzer#8357]
When I go to complete this function:

```rust
fn poll(&mut self, value: &mut Context);

future.poll(&mut  )
//               ^ The point is here
```

I see these completions:

<img width="444" alt="Screen Shot 2021-04-05 at 3 41 17 PM" src="https://user-images.githubusercontent.com/1823405/113618634-f5feb980-9625-11eb-8957-bdf5694d15e9.png">

`&mut context` definitely seems like the one I want. However, when I select it, it doesn't seem to be aware that I already typed `&mut`, and inserts it again:

```rust
future.poll(&mut &mut context)
```

This completion should be sufficiently context-sensitive that it doesn't double up the `&mut` prefix.

**Comment by Veykril** [comment]
cc @JoshMcguigan
