### ISSUE TITLE
Type inference not working with impl Fn return value

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#8403]
```rust
fn match_literal() -> impl Fn(&str) -> () {
    |input| {}
}
```

Rider can tell that `input: &str`, but we can't.

**Comment by flodiebold** [comment]
Yeah, we don't really implement the handling of return-position impl trait inside the function. We'd need to replace the `impl Trait` by a new type variable and register an obligation that it should implement the trait. It's this FIXME:
https://github.com/rust-analyzer/rust-analyzer/blob/3191a93185b34c6deebca2aad0584d2840ad6d43/crates/hir_ty/src/infer.rs#L583
