### ISSUE TITLE
rust-analyzer failed to load workspace

### ISSUE THREAD

**Issue by lelongg** [rust-lang/rust-analyzer#8439]
Since today I systematically get this error when opening vscode on one of my project:

```
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/sisyphe/Projects/easymov/sultan/Cargo.toml, cargo 1.51.0 (43b129a20 2021-03-16): Failed to run `cargo metadata --manifest-path /home/sisyphe/Projects/easymov/sultan/Cargo.toml` in `/home/sisyphe/Projects/easymov/sultan`: `cargo metadata` exited with an error: error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `sccache rustc - --crate-name ___ --print=file-names --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 2)
  --- stderr
  error: Connection to server timed out
```

I can reproduce with rust-analyzer stable and nightly. 

I tried to delete rust-analyzer target folder as well as sscache cache folder but it did not work

**Comment by bjorn3** [comment]
This seems to be an sccache problem:

```
error: Connection to server timed out
```

Does running `cargo metadata` manually work?

**Comment by lelongg** [comment]
Yes it prints a whole bunch of json and exit successfully

**Comment by GopherJ** [comment]
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/33961674/119804080-9b415a00-bf12-11eb-98fa-e6749cc7ee34.png">

**Comment by GopherJ** [comment]
I always get this even for valid `Cargo.toml`

**Comment by GopherJ** [comment]
I have multiple crates in my workspace and this happens two frequently....

**Comment by knassar702** [comment]
same here

**Comment by bonsairobo** [comment]
Strangely, this is an old issue, but I only just started experiencing this. I've been using `rust-analyzer` with `sccache` successfully for about a month. Now it's failing while using `rust-analyzer` VSCode extension v0.3.1451. `cargo metadata` is working fine from the command line.

**Comment by Veykril** [comment]
What does your project structure look like (that is the folder you are opening in VScode)?

**Comment by bonsairobo** [comment]
@Veykril I'm fairly certain that the issue was some kind of invalid cached build target. I deleted my entire `sccache` directory as well as the `target` directories in my cargo workspaces and that fixed the issue.

**Comment by Veykril** [comment]
Let's close this then since OP also seemed to have sccache set up

**Comment by hangj** [comment]
> @Veykril I'm fairly certain that the issue was some kind of invalid cached build target. I deleted my entire `sccache` directory as well as the `target` directories in my cargo workspaces and that fixed the issue.

I run `cargo clean`, and the error is gone.
