### ISSUE TITLE
zoombie error

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/rust-analyzer#8652]
I use coc-rust-analyzer & rust-analyzer, sometimes I get zoombie errors, it often happens after undo an edit. I'm not sure how to reproduce this systematically. It influences a lot the user experience as I would need to restart the service or re-open the project.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/33961674/115977145-d06f2b00-a5a7-11eb-8cb0-558795e4f57c.png">

<img width="563" alt="image" src="https://user-images.githubusercontent.com/33961674/115977149-d5cc7580-a5a7-11eb-8f30-66488741eda6.png">

There is nothing wrong with the code and `cargo check` also pass, but it still gives errors. Any idea on how to fix this issue?

**Comment by GopherJ** [comment]
See also: https://github.com/fannheyward/coc-rust-analyzer/issues/658

**Comment by matklad** [comment]
This needs a minimal reproducible example
