### ISSUE TITLE
Loading metadata very slow (regression)

### ISSUE THREAD

**Issue by sander2** [rust-lang/rust-analyzer#8681]
Version 0.2.546 is the last version for me where loading metadata is nearly instant - it goes almost straight to indexing. Now (e.g. on 0.2.574) loading the metadata is taking forever - more than 5 minutes. This is on a fairly large Substrate-based project. Looking at the output of `top`, rustc and/or cc1plus are using all the CPU. 

I'll keep using the older version for now, because this issue is making rust-analyzer unusable for me

**Comment by lnicola** [comment]
Does it load faster after you run `cargo check`?

**Comment by flodiebold** [comment]
Also, how long does `cargo check` take? You might also try seeing what effect disabling the `cargo.useRustcWrapperForBuildScripts` setting has.
