### ISSUE TITLE
Replacing if-let with match can lead to match expression with non-exhaustive patterns

### ISSUE THREAD

**Issue by bpandreotti** [rust-lang/rust-analyzer#8690]
I tried using "replace with match" on the following examples:

```rust
let foo: Option<&[_]> = Some(&[0, 1, 2]);
if let Some([]) = foo {
    ()
} else {
    ()
}

let bar: Result<_, ()> = Ok(Some(1));
if let Ok(Some(_)) = bar {
    ()
} else {
    ()
}
```

And got this as a result:

```rust
let foo: Option<&[_]> = Some(&[0, 1, 2]);
match foo {
    Some([]) => (),
    None => (),
}

let bar: Result<_, ()> = Ok(Some(1));
match bar {
    Ok(Some(_)) => (),
    Err(_) => (),
}
```

For both cases, I expected the pattern in the second match arm to be the wildcard pattern `_`. This seems to only happen if the pattern in the if-let expression is a nested `Option` or `Result`.

**Comment by Veykril** [comment]
We are trying to be too smart here and only check the outer pattern for `Option/Result`, so we dont check whether the inner pattern is exhaustive or not here https://github.com/rust-analyzer/rust-analyzer/blob/80bee14e14f67f02746befff77a8a4bbfd3e5849/crates/ide_assists/src/handlers/replace_if_let_with_match.rs#L71-L78

**Comment by flodiebold** [comment]
Do we actually need the special handling for Option/Result? We could probably have some "make the alternative pattern as specific as possible" logic.

**Comment by Veykril** [comment]
Mmh, ye ideally we wouldn't special case Option and Result. We should be able to make this more general
