### ISSUE TITLE
Custom lib name not taken into account when showing documentation

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust-analyzer#8734]
![Screenshot_2021-05-05_192529](https://user-images.githubusercontent.com/951129/117183379-c6370300-add7-11eb-8a86-d7c98439aec8.png)

In this screenshot of the VSCode documentation popover for the `rust-s3` crate's `Bucket` type, the containing module is shown as being `rust_s3::bucket`. However, `rust-s3` actually overrides the library crate name to be just `s3`. This should be taken into account.

**Comment by jean-santos** [comment]
Apparently, this has been solved already, right?
Following is on my local machine while trying to reproduce the issue:
![image](https://user-images.githubusercontent.com/29334790/182856826-61b70911-fe30-4854-ab9d-729a8e184aac.png)

**Comment by jplatte** [comment]
Yeah, nice 🙂
