### ISSUE TITLE
Improve completion suggestions when in return expression position

### ISSUE THREAD

**Issue by djc** [rust-lang/rust-analyzer#8787]
Might be a known issue already, but would be nice to better prioritize possible completions here? Latest nightly on VS Code.

<img width="556" alt="Screen Shot 2021-05-09 at 22 54 19" src="https://user-images.githubusercontent.com/158471/117586631-b0984500-b119-11eb-9eba-5bbff763ed1a.png">

**Comment by djc** [comment]
Ctrl + Space doesn't seem like the right keyboard shortcut on Mac (and Cmd + Space is bound to something else). Can you tell me what I should be trying to invoke?

**Comment by lnicola** [comment]
![image](https://user-images.githubusercontent.com/308347/118466886-f356b000-b70b-11eb-8ba6-5703850ad39e.png)

It look slike Ctrl-Space is the correct shortcut.

**Comment by djc** [comment]
Okay, well, in that case, Ctrl-Space doesn't appear to be doing anything for me.

**Comment by Veykril** [comment]
We prioritize by expected type now
