### ISSUE TITLE
Inlay hints for function that returns trait type generic

### ISSUE THREAD

**Issue by karto** [rust-lang/rust-analyzer#8816]
My VSCode does not show type hints (and the wrong hint) when a function returns a generics from a trait type.

**With associated_types it shows unknown**
See the third last line
<img width="721" alt="inlay_hint_associated_types" src="https://user-images.githubusercontent.com/92929/118045216-e9355a00-b377-11eb-8d3e-438c666501da.png">
[inlay_hint_associated_types.rs.txt](https://github.com/rust-analyzer/rust-analyzer/files/6469114/inlay_hint_associated_types.rs.txt)

**With feature(generic_associated_types) it shows Foo**
See the third last line
<img width="597" alt="inlay_hint_generic_associated_types" src="https://user-images.githubusercontent.com/92929/118045260-f8b4a300-b377-11eb-9b4f-c2c76b56f255.png">
[inlay_hint_generic_associated_types.rs.txt](https://github.com/rust-analyzer/rust-analyzer/files/6469115/inlay_hint_generic_associated_types.rs.txt)

**Comment by Veykril** [comment]
So I think what's happening here is that we forget about the `where` predicates of the function when resolving the `A::Output` path. We are first resolving the `A` param, then we resolved the `Output` on that but at that point we are searching in the scope of `A`'s definition which causes us to only consider the predicates on the impl block.

This can be easily verified by moving the where clause from the function down to the impl, from:
```rust
impl<A> Bar<A> {
  fn pas(&self) -> A::Output where A: Adapter<String> { self.adapter.process("hello".to_string()) }
}
```
to
```rust
impl<A> Bar<A> where A: Adapter<String> {
  fn pas(&self) -> A::Output { self.adapter.process("hello".to_string()) }
}
```
This makes the inlay hints reappear.

I believe we are losing the information in here https://github.com/rust-analyzer/rust-analyzer/blob/312f1fe20a6a0a8e69834c66f51b9abc9db5e0ce/crates/hir_ty/src/lower.rs#L902 as this looks up the predicates from the given param id which has no relation to the function scope anymore.

**Comment by Veykril** [comment]
This works now
