### ISSUE TITLE
Proc macro calls in macro arguments are highlighted as function calls

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#8829]
The `defmt::debug!` calls in the `handler!` invocation are highlighted as if they are method calls. The ones below the `handler!` macro are highlighted correctly.

![screenshot-2021-05-13-22:30:50](https://user-images.githubusercontent.com/1786438/118183888-f2d3c600-b43a-11eb-818d-71371b1ac277.png)

**Comment by Veykril** [comment]
Is thsi still the case? Stuff around highlighting and tokenmapping has changed a bit since then

**Comment by jonas-schievink** [comment]
No, this looks correct now:

![Screenshot_20220815_170938](https://user-images.githubusercontent.com/1786438/184661941-255fbadb-b8f5-4ad3-a47e-44fdfbbf3119.png)
