### ISSUE TITLE
failed to discover workspace when running as a live share session guest

### ISSUE THREAD

**Issue by classabbyamp** [rust-lang/rust-analyzer#8844]
When running as a guest in a [live share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) session, rust-analyzer shows an error popup that it "failed to discover workspace". In the debug output, there is this message:

```
[ERROR rust_analyzer] failed to find any projects in [AbsPathBuf("/")]
```

The full trace log is here: [rust-analyzer_trace.log](https://github.com/rust-analyzer/rust-analyzer/files/6481695/rust-analyzer_trace.log)

Versions:
- Rust: 1.52.0
- rust-analyzer: 0.2.591
- Live share: 1.0.4272
- vscode: 1.56.2 and later
- OS: Arch Linux and Void Linux (but the live share host is Windows 10)

The same thing happened (with a different path in the error) going the other way, with the windows guest on linux host session.

**Comment by 0x5c** [comment]
From the windows side, the path is an arbitrary drive letter.

**Comment by bjorn3** [comment]
```
    "workspaceFolders": [
        {
            "uri": "vsls:/",
            "name": "least"
        }
    ]
```

This isn't going to work. Rust-analyzer needs to be able to read files outside of the control of the editor. This is necessary to for example run `cargo metadata` as it doesn't have vfs support and thus can't read any files straight from the editor through the language server protocol. Is there an option to run the language server on the live share host and pass the real location of the workspace?

**Comment by 0x5c** [comment]
That's weird, because the error happens on the visitor side, and the windows visitor gets a drive letter in the path even when the host is running linux, and vice-versa
The drive letter is also not the one where rust/rust-analyzer/etc is installed, but the one where VSCode is installed.

**Comment by classabbyamp** [comment]
> Is there an option to run the language server on the live share host and pass the real location of the workspace?

rust-analyzer is running on both the host and visitor already

**Comment by bjorn3** [comment]
Either the host's r-a needs to be passed through to the visitor or live share needs to report the actual location of the local mount of the project instead of `vsls:/` as location for the workspace.

**Comment by jonas-schievink** [comment]
Live Share only works with rust-analyzer when using Microsoft's official VS Code builds, it does not work with OSS builds or VS Codium. rust-analyzer does not have to be installed or enabled locally for this to work. If rust-analyzer *is* enabled locally, then you get the error popup (which can be ignored).

We should add this to the manual, and ideally figure out a way to not activate the local extension when running in a Live Share session.

**Comment by classabbyamp** [comment]
@jonas-schievink

> Live Share only works with rust-analyzer when using Microsoft's official VS Code builds

yes, this bug would not be possible if I wasn't using the official build

[this might help with solving this issue](https://docs.microsoft.com/en-ca/visualstudio/liveshare/reference/extensions#visual-studio-code-1)

**Comment by jonas-schievink** [comment]
With https://github.com/rust-lang/rust-analyzer/pull/13095 and https://github.com/rust-lang/rust-analyzer/pull/13097, the Live Share behavior should now be fixed
