### ISSUE TITLE
[rust-analyzer unresolved-macro-call] [E] unresolved macro `self::derive_resource!`

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust-analyzer#8883]
Hi,

 I have a block of code as below, and analyzer report something unknown.

I suspect it as some unknown issue (bug maybe) as it is similar to a question posted [there](https://stackoverflow.com/a/65223815/3949473).

```rust
#[macro_use]
extern crate tower_web;

use tower_web::ServiceBuilder;
...

#[derive(Debug, Extract)]
struct PlanRequest{
    text: String,
}

#[derive(Debug, Response)]
#[web(status = "200")]
struct PlanResponse{
    words: Vec<String>,
}

...
// warning below: [rust-analyzer unresolved-macro-call] [E] unresolved macro self::derive_resource!
impl_web! {
    impl NewPlan{
        #[post("/plan")]
        #[content_type("application/json")]
        fn plan(&self, body: PlanRequest) -> Result<PlanResponse, ()> {
            Ok(PlanResponse {
                int: self.cal(&body),
            })
        }
    }
}
...
```

**Comment by jonas-schievink** [comment]
Can you provide the source code needed to reproduce this? What crate provides `impl_web!`? Are the attributes procedural macros?

**Comment by lnicola** [comment]
It's from tower-web, which is no longer maintained.

**Comment by halldong** [comment]
@jonas-schievink yeah, it's from tower-web.
I have appended those related source code.

**Comment by jonas-schievink** [comment]
```rust
#[macro_export(local_inner_macros)]
macro_rules! impl_web {
    ($($t:tt)*) => {
        impl_web_clean_top_level!(() $($t)*);
        derive_resource!($($t)*);
    }
}
```

`derive_resource` is just a normal `#[proc_macro]`, so this might be a bug in `local_inner_macros` handling

**Comment by Veykril** [comment]
This now panics in proc-macro hack whose support is tracked in another issue
