### ISSUE TITLE
Panic on formatting

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust-analyzer#8894]
When saving on the latest nightly, I get the following error in the language server trace:

> thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', crates\hir_def\src\item_tree.rs:432:1

And the formatting step seems to hang forever.

**Comment by Diggsey** [comment]
After a moment, this message is also printed:
```
Panic context:
> 
version: 764241e38 2021-05-20 nightly
request: rust-analyzer/inlayHints InlayHintsParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "<full path to file in the current crate>",
            query: None,
            fragment: None,
        },
    },
}
```

**Comment by Diggsey** [comment]
The most recent stable version does not have the same issue.

**Comment by jonas-schievink** [comment]
Could you post a backtrace?

**Comment by matklad** [comment]
I wasn't able to reproduce this, so removing the label.

**Comment by lnicola** [comment]
Not really actionable, that panic still shows up in some cases, but others were fixed (e.g. #17789).
