### ISSUE TITLE
Collect interning statistics

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#8998]
It would be very easy to implement object counting for interned objects – unlike the existing `countme`-based statistics, this just requires a call to `DashMap::len()` when the count is fetched and so can be left enabled by default at no cost.

The difference between this number and what `countme` reports can also be used to track down non-interned instances that should be interned.

**Comment by mohsen-alizadeh** [comment]
@jonas-schievink How it is gonna work?

Following types have used `impl_internable!` macro which adds storage method on the type.


`
    crate::type_ref::TypeRef,
    crate::type_ref::TraitRef,
    crate::type_ref::TypeBound,
    crate::path::GenericArgs,
    generics::GenericParams,
  ModPath, attrs::AttrInput
    InternedWrapper<Vec<chalk_ir::VariableKind<Interner>>>,
    InternedWrapper<SmallVec<[GenericArg; 2]>>,
    InternedWrapper<chalk_ir::TyData<Interner>>,
    InternedWrapper<chalk_ir::LifetimeData<Interner>>,
    InternedWrapper<chalk_ir::ConstData<Interner>>,
    InternedWrapper<ConstScalar>,
    InternedWrapper<Vec<chalk_ir::CanonicalVarKind<Interner>>>,
    InternedWrapper<Vec<chalk_ir::ProgramClause<Interner>>>,
    InternedWrapper<Vec<chalk_ir::QuantifiedWhereClause<Interner>>>,
    InternedWrapper<Vec<chalk_ir::Variance>>,
  str
`
I see that I can run something like `str::storage().get().len()` to get the list of objects in Interned<str>.

Do we need to print each type separately in the status method?
Do I need to get add this list manually in status method and call each one's storage method or there are some better way?

**Comment by davidkurilla** [comment]
I'd like to work on this issue.

**Comment by noahmbright** [comment]
Is this still relevant? If it is and I knew where interning is done I can start looking into this

**Comment by Veykril** [comment]
Not really, we are removing most usages of the dashmap interning soon
