### ISSUE TITLE
[Semantic Tokens] unresolvedReference when should be constParameter

### ISSUE THREAD

**Issue by GrayJack** [rust-lang/rust-analyzer#9042]
RA version: d5f7b2e52a41a7d3b841f4d0e2225eb703f6a50a
rustc version: 1.52.0 and 1.54.0-nightly

When using the const generic parameter in an array type the const parameter receive the unresolvedReference token.

## Example

![image](https://user-images.githubusercontent.com/17973728/120038688-04d86b80-bfda-11eb-9b0c-3d900e0f19ac.png)

![image](https://user-images.githubusercontent.com/17973728/120038920-626cb800-bfda-11eb-8f22-5530af05a256.png)

![image](https://user-images.githubusercontent.com/17973728/120038814-36513700-bfda-11eb-8f97-7ff398077d30.png)

```rust
struct Test<const N: usize> {
    o: [u32; N],
}

fn test<const N: usize>() -> [u8; N] {
    let _b = [0; N];
    todo!()
}

fn test2<const N: usize>() -> Test<N> {
    todo!()
}
```

This may be related to  #8655 ?

**Comment by Veykril** [comment]
This works now with a workaround to fix the array case.
