### ISSUE TITLE
Support 2021 Edition `pat` matcher in `macro_rules`

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#9055]
When a macro is defined in an edition 2021 crate, the `:pat` matcher should match "`pattern_top`" instead of "`pattern_single`", which allows or-patterns. `:pat_param` will match "`pattern_single`" in all editions.

**Comment by jonas-schievink** [comment]
Since this requires knowing the crate edition in some rather annoying places, I'd like to wait with this until the edition-dependent lexer changes in https://github.com/rust-analyzer/rust-analyzer/issues/9056 are implemented upstream, since that might already give us the required info

**Comment by Veykril** [comment]
We should prioritize fixing this now, as this is being used by the `matches` macro soon, https://github.com/rust-lang/rust/pull/108829
