### ISSUE TITLE
Errors with large scopes are unreadable in Sublime Text

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust-analyzer#9074]
I suspect poor error display it's Sublime LSP's problem, but FYI, in case you could adjust the scope on the protocol level:

https://github.com/sublimelsp/LSP/issues/1709

**Comment by flodiebold** [comment]
AFAIK we have already reduced that diagnostic to the first line. Are you on a recent version?

**Comment by kornelski** [comment]
Oh, great! I forgot it needs manual updates.

There's also the same issue with large functions and `#[cfg]`. Could you also change it to the first line only?

**Comment by jonas-schievink** [comment]
The `#[cfg]` diagnostic intentionally covers the whole item because it lets clients gray out the entire item. It would look weird if that only included the attribute.

**Comment by kornelski** [comment]
I have optional features in my crate, and this marking makes it difficult to work on them. I would not want it to be grayed out. 

I don't think rust-analyzer should flag it, as long as the cfg syntax is valid and possible to match (i.e the feature exists in Cargo.toml, the platforms are supported by Rust). There's always going to be some conditional code that doesn't currently match.

**Comment by flodiebold** [comment]
You can disable the diagnostic using the `diagnostics.disabled` setting. It's not an error though; it's a hint, and VSCode displays it pretty unobtrusively. Sublime may be displaying it differently. It's worth knowing when code is disabled though, since no IDE features will work in it.

**Comment by Veykril** [comment]
Closing this as this is not an issue with rust-analyzer per se, and there is a way to get around it as described by the previous comment.
