### ISSUE TITLE
cargo check failed, failed to run build script

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/rust-analyzer#9096]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/33961674/120314533-ec37c080-c30d-11eb-8be4-9c5aa83cd31c.png">

rencently I received too many notifications like this, anyone has an idea on the meaning? I'm wondering if the error message be more clear?

**Comment by GopherJ** [comment]
it basically happens randomly on https://github.com/parallel-finance/parallel project

**Comment by GopherJ** [comment]
I tested it happens if the project has an error and doesn't compile yet.

**Comment by bjorn3** [comment]
Based on reading the source of substrate_wasm_builder it seems that it builds the current crate for wasm. If this fails, the build script for parallel-runtime will fail too. It is not possible to report build script fails inside the file that caused the failure, as this is unknown. For this reason build script fails are reported as notification. If these notifications were hidden, you wouldn't be able to see any error as a crate doesn't get compiled normally when it's build script would fail.

**Comment by GopherJ** [comment]
@bjorn3 I see, but I think we run into a case that when we are developing things, we don't care if the build script fails or not, I would prefer not seeing this

**Comment by bjorn3** [comment]
Rust-analyzer runs `cargo check` to show most errors. This runs the build script. There is no way to prevent it from running build scripts as the buils script output may be necessary to even succeed in a check build. You can disable check builds using `"rust-analyzer.checkOnSave.enabled": false`, but be aware that you will pretty much only see syntax errors inside the editor. For almost every other error rust-analyzer is dependent on errors reported by rustc.

**Comment by GopherJ** [comment]
@bjorn3 I understand, so is there a way to filter such errors? personally I think I don't need such notifications

**Comment by GopherJ** [comment]
hi @bjorn3 do you think this can be improved on rust-analyzer side? or shall I seek help from coc.nvim to disable all notifications. Currently this feature brings me too much difficulties on coding

**Comment by bjorn3** [comment]
The only thing that could be done would be to add an option to disable the notification.

**Comment by GopherJ** [comment]
@bjorn3 hi I'm wondering if this can be solved, I'm sorry that I didn't have enough knowlege on rust-analyzer's code, although I'd really like to help

**Comment by bjorn3** [comment]
I think adding this option should be easy. https://github.com/rust-analyzer/rust-analyzer/commit/a90b9a5872c9c916733816e1e0d8c95cb09bfcba#diff-779cb31c0defa0631d570725eb4ca124c0860d6ec07bb5b9deddc2dd34966315R221-R224 is an example of a new config option being added. "cargo check failed" is emitted from https://github.com/rust-analyzer/rust-analyzer/blob/7eb843b218b5e10b39a5171f5b9689ec6c2d71c3/crates/project_model/src/build_data.rs#L106 I think. I can't quickly find where it is called, but it is likely the caller that needs to be changed.

**Comment by GopherJ** [comment]
emm, it's really impossible to work with the following popup flies out every three seconds

<img width="540" alt="image" src="https://user-images.githubusercontent.com/33961674/125442599-41e9274b-d391-4617-aced-3e10143a9c3a.png">

I would really hope that me or someone else would be able to find time for a fix

**Comment by GopherJ** [comment]
besides it slows down `rust-analyzer` a lot

**Comment by GopherJ** [comment]
https://github.com/fannheyward/coc-rust-analyzer/commit/a4a378cf026f6f3dc2328bc182167411bcbbed5d

**Comment by Veykril** [comment]
The error should show the reason as to why this failed now.
