### ISSUE TITLE
missing sp_std::marker::PhantomData import item

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/rust-analyzer#9098]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/33961674/120322687-44bf8b80-c317-11eb-8217-40c9fa5ee334.png">

**Comment by GopherJ** [comment]
I'm working on a substrate project which needs to work in no_std environment, and std::marker::PhantomData is part of std, so substrate provide sp_std::marker::PhantomData, but it seems rust-analyzer cannot propose this import

**Comment by bjorn3** [comment]
The `std` feature of sp_std is enabled by default, which causes it to re-export std types. Maybe rust-analyzer looks through the re-export and tries to directly import the target?

**Comment by flodiebold** [comment]
Yep. We'll just propose the shortest / most direct path to an item, not all reexports.

**Comment by Veykril** [comment]
We should prefer non-std paths for conditional no_std crates nowadays
