### ISSUE TITLE
proc macro returned error: Failed to get file metadata

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust-analyzer#9162]
I've seen this one in multiple projects now, and I have no idea what might be triggering it. It looks like somebody else has run into this issue before, but closed it after one reply asking for clarification 🤷🏼 (#8573)

The issue is this: Sometimes, custom derive macros just fail to expand, with the following error (that for some reason spans the entire type declaration rather than just the derive macro usage):

```
proc macro returned error: Failed to get file metadata for /home/jplatte/code/matrix-rust-sdk/target/debug/deps/libthiserror_impl-72c334668a8c5fc8.so: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

In the example above it's `thiserror`, but I've seen this happen with serde as well.

I don't know how to further debug this since it seems to happen at random and reloading the language server fixes it temporarily.

**Comment by flodiebold** [comment]
Does the mentioned file exist? Maybe something is cleaning the target folder while rust-analyzer runs?

**Comment by jplatte** [comment]
It does exist:

```
% file /home/jplatte/code/matrix-rust-sdk/target/debug/deps/libthiserror_impl-72c334668a8c5fc8.so
/home/jplatte/code/matrix-rust-sdk/target/debug/deps/libthiserror_impl-72c334668a8c5fc8.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a3fb48a9491862a58eb35b7f74d2a92bebdb3f95, with debug_info, not stripped
```

**Comment by flodiebold** [comment]
It exists now, but is the problem happening right now?

**Comment by jplatte** [comment]
I don't have a timestamp for when the error originally popped up, but as you can see from the command output above, the file was ~14 minutes older than the issue creation timestamp, so I think it was present when the error appeared. I have now restarted RA in that workspace and am no longer seeing the error, but will look into that when it happens again.

**Comment by jplatte** [comment]
Just hit this issue again and this time, the file really doesn't exist.

**Comment by jplatte** [comment]
… which was a bit after `cargo clean`, now that I think about it.

**Comment by Veykril** [comment]
I also just ran into this after upgrading my toolchain and running cargo clean without closing my editor.

**Comment by ayyEve** [comment]
i got this after doing a cargo clean, and reloading RA from within vs-code did not resolve the issue (the file exists when reloading). however closing and reopening vs-code does seem to resolve the issue

**Comment by matiman** [comment]
> i got this after doing a cargo clean, and reloading RA from within vs-code did not resolve the issue (the file exists when reloading). however closing and reopening vs-code does seem to resolve the issue

this worked for me!

**Comment by spacecaterpillar** [comment]
Hey is there a better solution to this than closing/opening vscode? Still happening from time to time.

**Comment by spacecaterpillar** [comment]
It seems restarting the analyzer does it. For me, that was Restart Rust Analyzer.
