### ISSUE TITLE
`TraitImplsInDepsQuery` uses a lot of memory

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#9167]
I captured this memory profile yesterday after seeing that r-a was using over 2 GB on itself:

```
Per-query memory usage:
   254mb TraitImplsInDepsQuery
   106mb HygieneFrameQuery
    87mb FileItemTreeQuery
    72mb BodyQuery
    66mb TraitSolveQueryQuery (purge)
    65mb MacroArgTextQuery
    59mb BodyWithSourceMapQuery
```

Seems like `TraitImplsInDepsQuery` could be quite a bit smaller!

**Comment by klensy** [comment]
Last week RA started consuming a lot of memory (used on rust compiler workspace). Previously it used about 2 GB memory, now can easy be over 4Gb (RA's memory usage command in VSCode sadly clears memory and reports `0` everywhere)
```
Per-query memory usage:
      0b ParseQuery
      0b ParseQuery (deps)
      0b ParseQuery (purge)
      0b CrateGraphQuery
      0b CrateGraphQuery (deps)
      0b CrateGraphQuery (purge)
... etc
```
Can't catch exactly when memory start grow, as it not instant.

**Comment by jonas-schievink** [comment]
Please open another issue for that. It's probably not due to `TraitImplsInDepsQuery` since we haven't changed that recently.
