### ISSUE TITLE
Import/qualify trait `Deref` suggesting `lazy_static::__Deref` instead of `std::ops::Deref`

### ISSUE THREAD

**Issue by ThePuzzlemaker** [rust-lang/rust-analyzer#9197]
The code action to import/qualify a trait suggests `lazy_static::__Deref` instead of `std::ops::Deref` for just the name `Deref`.

To reproduce:
- Add lazy_static v1.4.0 to the `Cargo.toml` (Not sure if this happens on other versions)
- Create an impl block `impl Deref for Foo`.
- Press alt-period or whatever code action shortcut is set up while the cursor is over the `Deref` in the `impl Deref for Foo` block.
- `lazy_static::__Deref` is suggested instead of `std::ops::Deref`.

![image](https://user-images.githubusercontent.com/12666617/121467460-baae9d00-c97e-11eb-80cc-7e51dc5a135b.png)

Information:
IDE: VSCode
Plugin: matklad.rust-analyzer v0.2.621
rust-analyzer version: rust-analyzer 28e32fe40 2021-05-31 stable
Rust: 1.52.1

**Comment by lnicola** [comment]
CC #9113

**Comment by Veykril** [comment]
The problem here is that lazy_static reexports Deref with a doc hidden. We should ideally honor the `#[doc(hidden)]` attribute unless its hidden in the same crate we are importing from.
Minimal test case for autoimport that imports `__Deref`:
```rust
//- /main.rs crate:main deps:std,lazy_static
impl Deref$0 for () {}
//- /lazy_static.rs crate:lazy_static deps:core
#[doc(hidden)]
pub use core::ops::Deref as __Deref;
//- /std.rs crate:std deps:core
pub use core::ops;
//- /core.rs crate:core
pub mod ops {
    pub trait Deref {}
}
```
