### ISSUE TITLE
Parameter name inlay hint `mut` underline is offset by a couple of pixels in VS Code

### ISSUE THREAD

**Issue by Nufflee** [rust-lang/rust-analyzer#9225]
The parameter name inlay hint for function calls when a mutable variable is passed as a parameter, and is therefor underlined, is offset up by ~1 pixel and ~1 pixel thinner than the rest of the underline. This is obviously a nitpick but it's been bothering me a lot.

After a bit of Dev Tools debugging, it seems like the issue occurs because the inlay text has `font-size: smaller;` and the positioning and thickness of the underline is probably determined based on it. I don't know if this is something you can do anything about, and if not, we could open an upstream issue.

This is what it looks like:
![image](https://user-images.githubusercontent.com/19150550/121760311-592b3180-cb2a-11eb-99c2-0751ae0ed136.png)

And here's the code:
```rust
fn foo(a_parameter_name: i32) {}

fn main() {
    let mut argument = 123;

    foo(argument);
}
```

Edit: [you in fact are setting the `font-size: smaller;`](https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/src/inlay_hints.ts#L72) on parameter inlay hints so this should theoretically be fixable here.

**Comment by Nufflee** [comment]
After a bit more fiddling with Dev Tools, I propose the following solution:

Instead of setting a `text-decoration: underline;` [here](https://github.com/rust-analyzer/rust-analyzer/blob/1f1a1ce4f57076be38d18f0a6defddb9c690bb1c/crates/ide/src/syntax_highlighting/html.rs#L84) which is dependent on the font size and not easy to keep in-line with different font sizes, even if the former problem is fixed, we should instead do a `border-bottom: 2px solid;`. This is not an exactly visually analogous, but it's close enough. I'd appreciate anyone with better CSS skills to improve on this.

**Comment by lnicola** [comment]
(Belated) thanks for looking into this, but Code will soon™ have native support for inlay hints. When we switch to that, it's probably going to have a different set of bugs. I'm not even sure we can keep the `font-size: smaller` option.

**Comment by Veykril** [comment]
Fixed with the move to native inlay hints
