### ISSUE TITLE
Add manual trigger for nightly realase

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust-analyzer#9283]
At the moment, a nightly release can be started by pushing to the `trigger-nightly` branch. The reason for this is historical -- this functionality had been implemented before github actions added "trigger workflow manually" feature. We probably should switch to the manual triggers, so that a new release can be conveniently kicked directly from a PR. We need to verify that a manual trigger would still allow to trigger on arbitrary commit though.

**Comment by Veykril** [comment]
We actually have this now I believe?
