### ISSUE TITLE
Crash when loading from WSL with --verbose mode

### ISSUE THREAD

**Issue by jasonwilliams** [rust-lang/rust-analyzer#9298]
From parent issue: https://github.com/microsoft/vscode/issues/107062
VSCode v1.58.0-insider (system setup)
Rust Analyzer v0.2.637

I started to narrow this down to only-happening-on-rust-projects, then I looked at some extensions.
On further investigation it looks like the issue could be Rust Analyzer? I notice the crash happens once that kicks in. Not sure how its able to crash the whole of VSCode, ive not seen an extension do that but if you install that it should be reproducible.

In the video I click around and it stays interactive until Rust Analyzer shows the type information for the variables, at this point the crash happens. When I disable Rust Analyzer it doesn't crash.

https://user-images.githubusercontent.com/936006/122100929-a7328480-ce0b-11eb-8c2d-c8bf47ebb48c.mp4

**Comment by lnicola** [comment]
Is that WSL 1 or 2?

`--verbose` sounds like it makes Code log more to the console, but I don't see anything in your capture.

**Comment by jasonwilliams** [comment]
WSL 2

**Comment by jasonwilliams** [comment]
> `rust-analyzer` has no way of crashing Code.
> 
> On WSL 1 I would have suspected a file system-related bug, triggered by us reading the source files (including the sysroot) and setting up file watching. But on WSL 2 those shouldn't be a problem.

Please see the parent issue, if its a code problem you should take it up with them. Im just raising the bug

**Comment by lnicola** [comment]
VS Code is pretty crashy these days, but this can't be our fault.
