### ISSUE TITLE
Renaming a local does not rename it inside a `tracing::info!` invocation

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#9424]
Renaming the `foo` definition here does not rename the usage inside the macro.
```rust
let foo = 3;
tracing::info!("{}", foo);
```
RA seems to expand the macro just fine though with `Expand macro recursively`.

**Comment by SomeoneToIgnore** [comment]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/2690773/128676091-46ef5e44-b20d-4754-a818-53b998fff6a6.png">

Got a few examples that work and not.
Interesting, that tracing seems to be the only one of the println-like macros that do not work for me.

**Comment by Veykril** [comment]
So this apparently works now
