### ISSUE TITLE
Add "unnecessary else" diagnostic

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#9457]
```rust
if foo {
    return bar;
} else {
    do_something_else();
}
```
In this snippet the `else {}` block surrounding the `do_something_else()` call is unnecessary and can be omitted. We want to emit a weak diagnostic with a corresponding fixit for this.

Note that the same can apply for `continue` and `break` expressions here and not just `return`.

**Comment by iobtl** [comment]
Hello, I would like to try to tackle this issue. Could I get some further guidance on the actions to take? From a glance at the mentioned PR, would it be appropriate to create a new diagnostic under `ide_diagnostics` along with the action handler under `ide_assists`?

**Comment by Veykril** [comment]
I'm not too familiar with our `diagnostic` infra yet either but from what I can see, yes you want to add a new diagnostic under `ide_diagnostics`. That is also where you also will define the fixit action, `ide_assists` does not relate to diagnostics. You will also most likely have to touch the `hir/diagnostics.rs` part as you've noticed already.

It's probaby best if you just check out a few diagnostics, where they are constructed in the `hir` and then check how they work in the `ide_diagnostics` layers for now.

If you stumble upon more questions feel free to ask here or on the [zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer)

**Comment by iobtl** [comment]
Thanks! I will try to use that as a starting point for now.
