### ISSUE TITLE
Can't use break points and jump to some functions  in linkerd2-proxy with VSCode

### ISSUE THREAD

**Issue by tony612** [rust-lang/rust-analyzer#9538]
I have two problems when working with [linkerd2-proxy](https://github.com/linkerd/linkerd2-proxy):

### 1. Break points don't work

Steps:
1. Open `linkerd2-proxy` sub directory.
```
$ git clone https://github.com/linkerd/linkerd2-proxy.git
$ cd linkerd2-proxy
linkerd2-proxy $ LINKERD2_PROXY_IDENTITY_DISABLED=1 LINKERD2_PROXY_DESTINATION_SVC_ADDR="foo.bar:8080" code linkerd2-proxy/
```
2. Add a break point in [main.rs:31](https://github.com/linkerd/linkerd2-proxy/blob/79b133eff01db577a9cfe248accd29f749b8d78d/linkerd2-proxy/src/main.rs#L31)
![截屏2021-07-09 下午1 58 13](https://user-images.githubusercontent.com/1253659/125030376-a238bc00-e0bd-11eb-9f52-2aaad5389541.jpg)
3. Click the "Debug" above `main`.
4. Then in the TERMINAL, we can see output is printed but debugger doesn't pause at the break point
```
[     0.000709s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.001334s]  INFO ThreadId(01) linkerd_app_core::telemetry::process: System-level metrics are only supported on Linux
[     0.016562s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 127.0.0.1:4191
[     0.016594s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.016609s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.016621s]  INFO ThreadId(01) linkerd2_proxy: Tap DISABLED
[     0.016639s]  WARN ThreadId(01) linkerd2_proxy: Identity is DISABLED
[     0.016653s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via foo.bar:8080
```

I tried the official [vscode-rust](https://github.com/rust-lang/vscode-rust), it also doesn't work.

### 2. Can't jump to some functions

For example, in [this code](https://github.com/linkerd/linkerd2-proxy/blob/79b133eff01db577a9cfe248accd29f749b8d78d/linkerd/app/inbound/src/lib.rs#L148)

```
        let serve = async move {
            let stack =
                self.to_tcp_connect()       # works
                    .into_server(listen_addr.as_ref().port(), profiles, gateway);  # doesn't work
            let shutdown = self.runtime.drain.signaled();
            serve::serve(listen, stack, shutdown).await
        };
```
I can jump to `to_tcp_connect` but can't jump to `into_server`, which is defined at https://github.com/linkerd/linkerd2-proxy/blob/79b133eff01db577a9cfe248accd29f749b8d78d/linkerd/app/inbound/src/lib.rs#L208.

[vscode-rust](https://github.com/rust-lang/vscode-rust) works well for `into_server` jumping.

**Comment by lnicola** [comment]
For debugging issues, try a different debugger extension and maybe file an issue for it. There are a couple of them, and some of them may work better depending on your platform.

Go to definition on `into_server` works fine for me. Maybe it was fixed recently, or there's something else going on.

Of course, RLS is still more precise: the names highlighted in red below are unresolved, so "Go to definition" and type inference will not work for them:

![image](https://user-images.githubusercontent.com/308347/125032707-05fbbe80-e097-11eb-9ff7-131862a5d7ea.png)

![image](https://user-images.githubusercontent.com/308347/125032721-0a27dc00-e097-11eb-9af3-0f8bc8dfac65.png)

![image](https://user-images.githubusercontent.com/308347/125032741-0f852680-e097-11eb-958c-594e88696b74.png)

The `instrument` case might be worth looking into, for example.

**Comment by tony612** [comment]
@lnicola My issues solved! Thank you!

The first is because linkerd2-proxy sets `debug = false` in Cargo.toml.
The second issue is solved by using the nightly release.

But as you said, it seems functions after `instrument` can't be resolved.

**Comment by tony612** [comment]
I found all `.instrument(|_: &_|` can't work, but calls with explicit type annotation can work like [this code](https://github.com/linkerd/linkerd2-proxy/blob/e908293a8dbd0d80c719fdc36e3d4ba745eb0926/linkerd/app/inbound/src/lib.rs#L197):
```rust
            .instrument(|_: &_| debug_span!("tcp"))
            .push(svc::BoxNewService::layer())
            .check_new::<TcpEndpoint>();
```

I guess it's because the closure passed to `instrument`'s type is known until `check_new`. I don't know how rust-analyzer works, but it seems it doesn't handle this case well?

**Comment by lnicola** [comment]
Yeah, explicit type annotations will make it work.

Ideally we'd extract a minimized test case, I guess it doesn't seem too hard.
