### ISSUE TITLE
vscode: Inline Suggestions

### ISSUE THREAD

**Issue by kjeremy** [rust-lang/rust-analyzer#9544]
vscode 1.58.0 has a proposed api for "Inline Suggestions". It would be cool if we could use this (once finalized) with our completion for preferred items.

**Comment by jonas-schievink** [comment]
More info here: https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_58.md#inline-suggestions

**Comment by yume-chan** [comment]
Inline suggestion is mainly for multiline suggestions (which doesn't fit the suggestion widget).

With `"editor.suggest.preview": true`, suggestion preview automatically works for tranditional suggestion providers including TypeScript and JSON (other languages not tested).

![image](https://user-images.githubusercontent.com/1330321/128488530-077338a0-5b49-4560-b4e9-0710305a5e63.png)

But strangely, it doesn't work with rust-analyzer

![image](https://user-images.githubusercontent.com/1330321/128488756-1063cb60-4098-47ff-b8da-46937093908d.png)

**Comment by HKalbasi** [comment]
`"editor.suggest.preview": true` now works for me in vscode 1.73, even for multi line suggestions (like adding a function inside an `impl Trait`). Anything else remaining on this, or it can be closed?

**Comment by Veykril** [comment]
VSCode has a specific API for this, though I am not sure what the benefits of it are https://code.visualstudio.com/api/references/vscode-api#InlineCompletionItemProvider

**Comment by HKalbasi** [comment]
IIUC the difference is that inline suggestion doesn't show the traditional suggestion dialog (which we probably don't want) and it has different ui for switching and selecting, for example it uses `Alt + [` instead of arrow keys for switching between suggestions. I think it is intended to use when the suggestion dialog doesn't make sense (like for copilot suggestions)
