### ISSUE TITLE
Caches casing of filename

### ISSUE THREAD

**Issue by Elias-Graf** [rust-lang/rust-analyzer#9581]
I hope I'm at the correct repository here. Please redirect me if I'm wrong and feel free to close this. I would really like to get this fixed as it is quite an issue to not have linting as a rust beginner.

So I'm using the VSCode extension and somehow this is caching the casing of filenames. 

I have the following source structure:

```
treebuilder.rs
treebuilder
 - node.rs
```

I initially named the file "Node.rs" but then cargo complained that it should be snake case. I renamed the file to "node.rs". Now the linting is missing if I have `pub mod node;` in `treebuilder.rs`. The linting will only show up if I put `pub mod Node;` into the file.

The linting does not work:
![image](https://user-images.githubusercontent.com/46671625/125318973-a3c2e800-e33a-11eb-89fb-54d01d968c8c.png)

The linting works:
![image](https://user-images.githubusercontent.com/46671625/125319020-afaeaa00-e33a-11eb-9d32-c068759e12d2.png)

These are the module suggestions:
![image](https://user-images.githubusercontent.com/46671625/125319081-be955c80-e33a-11eb-96c3-49d320ede6e0.png)

And here the actual source structure:
![image](https://user-images.githubusercontent.com/46671625/125319131-c7862e00-e33a-11eb-8346-6a98be975983.png)

Restarting the rust-analyzer does not help. Restarting VSCode does not help.

- rust-analyzer version: fe0035888 2021-07-12 stable
- VSCode version 1.59.0-insider

**Comment by bjorn3** [comment]
> Restarting the rust-analyzer does not help. Restarting VSCode does not help.

Restarting rust-analyzer and VSCode clears all caches. Or rather rust-analyzer doesn't preserve any caches to the disk ever. It keeps everything in memory. Is there a type named `Node` defined somewhere? It is possible that you are seeing a completion for this type originating from VSCode.

**Comment by Elias-Graf** [comment]
Take a look at this.


![image](https://user-images.githubusercontent.com/46671625/125326799-b93c1000-e342-11eb-95d0-09f59bf7ffee.png)

![image](https://user-images.githubusercontent.com/46671625/125326829-c3f6a500-e342-11eb-9a39-1b7504992416.png)

Both suggestions still there after a restart of VSCode

**Comment by Elias-Graf** [comment]
@bjorn3 

Take a look at this.


![image](https://user-images.githubusercontent.com/46671625/125326799-b93c1000-e342-11eb-95d0-09f59bf7ffee.png)

![image](https://user-images.githubusercontent.com/46671625/125326829-c3f6a500-e342-11eb-9a39-1b7504992416.png)

Both suggestions still there after a restart of VSCode

**Comment by Elias-Graf** [comment]
@bjorn3 Okay so the issue also exists inside of the non-insider build of VSCode **BUT** restarting the language server or code does actually resolve the issue!

**Comment by Veykril** [comment]
This is caused by VSCode's caching which persists across session restarts, it caches the old filename on windows as it is case insensitive, r-a can't handle this though. To me this feels like a bug in VSCode, though iirc VSCode says it is not. There were some other issues about this matter here before as well.

**Comment by Elias-Graf** [comment]
@Veykril I wouldn't be so sure about that. I have been using VsCode for quite some time now, and have never experienced the issue in any other language (server). They presumably would also have that cache, no?

**Comment by Veykril** [comment]
They would and I imagine they do not care about the casing of file names hence why it is not a problem for them, we do care about them though, as rust is case sensitive in this regard when the filesystem is as well, to my knowledge. See https://github.com/rust-analyzer/rust-analyzer/issues/9947 where I dug into this matter a bit more before.

**Comment by Veykril** [comment]
Tracked in #9947

**Comment by ChainThemAll** [comment]
Hi, is there any solution to this problem so far?

**Comment by Veykril** [comment]
See https://github.com/rust-lang/rust-analyzer/issues/9947
