### ISSUE TITLE
recognize and support rust-script

### ISSUE THREAD

**Issue by gwpl** [rust-lang/rust-analyzer#9609]
Could you consider recognizing and supporting rust script files?
https://rust-script.org/

**Comment by bjorn3** [comment]
Rust script is for one off scripts. It allows you to write an entire program in a single file while still supporting arbitrary cargo dependencies. It is **not** a "language" that you can embed in an existing program like a game. It also doesn't make compilation any faster. You just write a regular cargo based project except that `Cargo.toml` is part of`main.rs` and you likely can't write the source in more than a single file.

**Comment by lnicola** [comment]
We could actually implement this and it would be useful for one-off scripts, since we already have two project model implementations.

On the other hand, we run `cargo metadata` for dependency resolution (among other things), so we would have to replicate most of the `rust-script` logic: extracting the `Cargo.toml` snippet and source code into a temporary project, then running `cargo metadata` here.

**Comment by bjorn3** [comment]
:facepalm: I thought this was on the Bevy repo, not the rust-analyzer repo. Please disregard my previous comment.

**Comment by gwpl** [comment]
Maybe there is possibility for two projects to collaborate to make it work? 
https://github.com/fornwall/rust-script/issues/26
e.g. rust-script to repackage/refactor some logic into libraries, that would match rust-analyzer for easy integration?

**Comment by lnicola** [comment]
I think there will always be the possibility of another took like that to show up, using a different syntax for dependencies.

**Comment by fornwall** [comment]
I'm happy to help out with discussing and implementing changes to rust-script that could help out with implementing support in rust-analyzer, whether that be adding library functionality, CLI options, or changing/removing functionality to present a leaner and more minimal script runner functionality in general.

> And then we'd also have to support other rust-script features like templates, and I'm pretty sure we shouldn't do that.

Agreed! Note that templates currently only works for snippets passed directly to rust-script  (as in `rust-script -t grabbag -e "mem::size_of::<Box<Read>>()"`), and not for script files. And that's probably good to avoid making script files non-portable. Specifying a path to a local crate may provide enough functionality for those who need it without tying it to some rust-script specific template. See https://github.com/fornwall/rust-script/issues/12.

**Comment by epage** [comment]
I'm assuming #15318 takes precedence over this?

Granted, right now the two systems are fairly related (though we haven't finalized how to embed manifests yet).  The main new thing is that `cargo +nightly -Zscript metadata --manifest-path foo.rs` now works.

**Comment by gwpl** [comment]
To me two are definitely related!
Thank you!

**Comment by gwpl** [comment]
To me two are definitely related!
Thank you!

**Comment by gwpl** [comment]
Just maybe for the context on importance - in light of adoption of LLMs (like OpenAI GPT-4 , LLaMA 2 , Starcoder...), tools that help them to work with Rust , I believe will help in Rust adoption in organizations (due to improving software economics).

Therefore my hypothesis is that it's way easier for models to operate on standalone files, where everything is in one file, self contained, and people to use it that way (e.g. copy&paste to/from chat interface).

Cross-linking:
Given that here is a thread on a topic about Rust script on openai forum:
https://community.openai.com/t/how-to-generate-modify-rust-scripts-sourcecode-with-openai-api/267190
in case you find topic related/engaging.

**Comment by MiSawa** [comment]
FYI, I've created [a language server for `rust-script`](https://github.com/MiSawa/rscls/) a while ago. It mostly just forwards request to rust-analyzer, except it invokes `rust-script --package (path of script)` to obtain the generated project directory and sets up `linkedProject` for the project. This definitely isn't a perfect solution, but works at least better than nothing until this/#15318 is done.

**Comment by Veykril** [comment]
Closing in favor of https://github.com/rust-lang/rust-analyzer/issues/15318
