### ISSUE TITLE
defaults seem unnecessarily intrusive

### ISSUE THREAD

**Issue by skondrashov** [rust-lang/rust-analyzer#9672]
The default settings on the vscode extension puts inlays, codelens, and underlines under some variables in the code by default, which moves lines around and feels very unwelcoming. It's not clear what these features are about if you haven't seen them before, and an option to disable the underlines is missing from the settings UI. It took way too much time for me to get to a point where I felt like my screen would display what I was writing. I'm not sure what I would suggest to make users aware of these features if they want to opt-in, but I feel like the current defaults are overwhelming.

Examples: 
![image](https://user-images.githubusercontent.com/12279291/126603255-18a50709-b850-47cb-a101-77445f6af69f.png)
![image](https://user-images.githubusercontent.com/12279291/126603165-fef2aaa8-a785-4a13-b217-ccfb4ae5d85b.png)
![image](https://user-images.githubusercontent.com/12279291/126603342-126ac7ce-e8b2-4ec4-bcc5-9acff4c45040.png)

**Comment by lnicola** [comment]
There's some docs in https://rust-analyzer.github.io/manual.html, but we should probably have some screenshots -- at least I can never remember which lens is which. The underline thing is documented at https://rust-analyzer.github.io/manual.html#semantic-style-customizations.

Generally, I think it's fine to enable them by default (a lot of users really like the lenses, and they're enabled in Code by default, too). Not only that, but it's better if you look up (or ask) how to disable a feature that to not know that it exists at all.

**Comment by flodiebold** [comment]
I'm curious, what do you mean by
> which moves lines around
?

**Comment by skondrashov** [comment]
I was hinting at a metric of the screen showing what I write, which inlays and codelens violate pretty harshly. In the case of underlining, it probably just needs to be added to the settings so it's not a hassle to disable. Of course I don't want to disable the concept of features, just like you don't think all features should be enabled by default.

**Comment by flodiebold** [comment]
I'm not a fan of codelens myself because they disrupt the text grid, but even apart from what lnicola wrote, they're a standard VSCode feature and we shouldn't go against VSCode's UX choices just because we might have a different opinion.

**Comment by flodiebold** [comment]
> just like you don't think all features should be enabled by default

Actually, we do think all features should be enabled by default, that's pretty much our policy.

**Comment by lnicola** [comment]
Those are inlay hints, not code lenses :smile:.

**Comment by flodiebold** [comment]
The first screenshot is a codelens.

The underlining marks mutable variables and mutable access; I think that's a feature of the theme and probably can't be disabled separately.

**Comment by skondrashov** [comment]
I was able to solve the underlining with some steps from #3358

**Comment by flodiebold** [comment]
That's probably something we could add to the hypothetical "How do I turn off X?" FAQ then.

**Comment by skondrashov** [comment]
I don't really understand these responses, but I guess I'm not thinking of what you're trying to achieve in the right way. I think that first install user experience suffers a lot if you don't consider which features make for a good first install user experience and disable features or provide options to disable the features that are a bad experience. RLS doesn't have either of these problems, and I was invited to try this extension as a replacement, there's a bunch of little happy icons of people who found that solution in the thread I linked, surely we should be able to start coding more or less as soon as we install the extension if it's going to be the only option in the future?

I appreciate that it's not easy to cover everything but this just makes me feel the RLS maintainers approach this the way I'm used to extensions being, I guess like the eslint extension since I come from web?

**Comment by lnicola** [comment]
> since I come from web

Note that inlay hints are coming to the TypeScript extension: https://github.com/microsoft/vscode/issues/16221#issuecomment-879538951 (and there's an example of reference lenses in the screenshot above).

**Comment by flodiebold** [comment]
You seem to just be presuming as a given that these features are a bad experience. We don't think so, otherwise we would implement them differently. Of course not everyone likes them, like you, but that's why you can turn them off. A feature that starts out disabled might as well not exist for most users.

Do you have any concrete examples of major features that start out disabled in other extensions? I'm actually not really convinced that this is common.

> RLS doesn't have either of these problems

RLS doesn't have any of these features.

**Comment by skondrashov** [comment]
To your point, not many other extensions have as many features as rust-analyzer, but there are several features in vscode itself that are disabled by default that I look for and enable, which is the experience I'm thinking back to I guess. I think that having to search for a setting online because it's not in the UI is an objectively bad experience, and I don't understand how to see that as a feature. I understand that disabling the feature means users will never find it, but if I am new to Rust I am worried enough about understanding what's going on to worry about my settings or how to read around text inserted into the code.

**Comment by flodiebold** [comment]
> I think that having to search for a setting online because it's not in the UI is an objectively bad experience, and I don't understand how to see that as a feature.

We're on the same page here, we do want it to be possible to configure everything, and I don't think we implied otherwise anywhere.

**Comment by skondrashov** [comment]
I understood "it is already documented" as meaning it didn't need to be in the settings, but yes we're on the same page. I understand your philosophy in enabling all features by default but there's value in a middle ground, and even your extension has several of those codelens/inlay options disabled, presumably because they reached somebody's threshold for being annoying or useless. Thanks for your work in maintaining the extension.

**Comment by flodiebold** [comment]
The references lenses are disabled for performance reasons. I don't think we have any disabled inlay hints.

**Comment by skondrashov** [comment]
I was thinking of the references hover, but yeah it would seem you do adhere to that philosophy.

**Comment by fee1-dead** [comment]
I personally think having these features enabled by default is better than leaving them disabled.

I know that people have different choices for how their editor should look like, but it seems easier for people who want them off to turn them off in the settings rather than the opposite. Especially for visuals: if you don't like them and it is on by default, you know that you want to turn it off. Someone who is unfamiliar with rust-analyzer might not know that the feature even existed if it is off by default.
