### ISSUE TITLE
Support doc links to associated functions on other structs

### ISSUE THREAD

**Issue by lf-** [rust-lang/rust-analyzer#9694]
```rust
struct F;
impl F {
    // expect to go here but it fails instead
    fn linkme() {}
}

/// See [`F::linkme`]
//           ^-- go to definition here
fn f1() {}
```

If I do the above go to definition, it doesn't find a target. `rustdoc` appears to compile it fine.

The example from #9617 linking to other things on the same top level item *does* work, it seems to just be linking to things from other top level items that's a trouble here.

Version: 5983d3745ac8490c1c2798fdc963aa9fc803dd03

**Comment by Filip-Tomasko** [comment]
The same thing still happens in 5342f47f4276641ddb5f0a5e08fb307742d6cdc4 (`v0.3.1123`)

E.g. with 
```rust
struct Foo {}
impl Foo {
    /// [Foo::baz()] - it links correctly in `cargo doc` but not in VSC!
    fn bar(self) {}

    /// [buzz] - linked properly in VSC and `cargo doc`
    fn baz(self) {}
}

fn buzz() {}
```

only `buzz()` is linked properly in VSC 
![image](https://user-images.githubusercontent.com/3923334/178338121-10b5b5b2-e6f9-4b00-b301-94760268e4fa.png)
while in the `rustdoc` generated docs both are linked correctly 
![image](https://user-images.githubusercontent.com/3923334/178338218-3725c18a-a307-4ceb-b040-d0cd2a30dde9.png)
