### ISSUE TITLE
Regression in v0.2.686:  `OUT_DIR` not set, enable "run build scripts" to fix

### ISSUE THREAD

**Issue by shikhar** [rust-lang/rust-analyzer#9720]
Repro: https://github.com/shikhar/bazel-tonic/tree/4a27fbf7fe15a26804a3eb5eb3f7b62dafa9fba4

![image](https://user-images.githubusercontent.com/74267/127425537-cfde2d8e-482c-49bd-a610-aec94b9871df.png)

The error does not make sense because that setting defaults to `true`.

The error is gone after after rolling back to the last release v0.2.678.

**Comment by jonas-schievink** [comment]
I cannot reproduce this on current master (8a6bac3fc8e426976d4d2ff37b80e1f8f82f1240) with Rust 1.53.0

**Comment by shikhar** [comment]
How do I try master? I switched to the nightly channel and still see this.

**Comment by jonas-schievink** [comment]
You can follow the instructions here: https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/dev#launching-rust-analyzer

Can you post the configuration picked up by the extension? It should be printed to the "Output" tab under "Rust Analyzer Client".

**Comment by shikhar** [comment]
Hmm, I can't reproduce this problem on another machine, so closing

**Comment by asaaki** [comment]
I have seen this issue right now myself, currently running RA nightly / 0.3.708 (VSC 1.59.0, Win10).
Have not a repro repo, but I have a suspicion:
The error happens when I work in a VSCode workspace with multiple folders/projects, but it does not happen when I open the project individually.

**Comment by chris-ricketts** [comment]
Same as @asaaki & @trentbb: discovered this when using bindgen in a worspace member crate.
[Made a reproduction repo with a minimal bindgen](https://github.com/chris-ricketts/ra-out-dir-workspace-repro)
`rust-analyzer --version`: `rust-analyzer 516eb40ba 2021-09-13 stable`
OS: Arch Linux x86_64 (5.14.2)
Editor: Neovim 0.5

**Comment by aliabuthahir** [comment]
same thing....
tonic = "0.6.1"
prost = "0.9.0"
+ rust analyzer

Any progress?

**Comment by Raz-Hemo** [comment]
Also running into this when opening a workspace with multiple crates on vscode remote ssh.

**Comment by h0ru5** [comment]
had the same effect on single-project workspace after deleting and rewriting build.rs
restarting vs code did solve.

**Comment by jkcoxson** [comment]
I am also running into this problem, with one folder open at a time and my whole workspace. Restarting VS Code has no effect.

**Comment by Veykril** [comment]
Meant to look into this, tried out @chris-ricketts repro but it works fine for me.
![image](https://user-images.githubusercontent.com/3757771/146928115-b70fd1d8-b7d7-40b2-b6ae-099adf9ad1e9.png)

So for those that still run into this we need a new reproduction it seems

**Comment by dxenonb** [comment]
For what it's worth, this is what I am running into:

I have a workspace with my game project (rust_voxel) and a renderer crate in the workspace

   1. (user error:) My game project was failing with this error for some bindgen generated bindings (OUT_DIR not set)
   1. (possibly this issue:) Yesterday, with `gl-generator`, RA was reporting errors on `use crate::gl::types::*;` (the )... Today that's not happening and everything looks fine (even before I fixed the issue above). The repro above still looks consistent with my setup but is not giving me the error today either 
 
I'm running things a little out of date and will update later (since everything is working right now):

 - rustc 1.57.0 (f1edd0429 2021-11-29)
 - ra d9b2291f5 2021-11-29 stable
 - VSCode 1.60.1

What I was doing to cause the first error:
  
> It turns out I had this in my build script:
> ```
>   let date = Command::new("date")
>           .arg("+%Y-%m-%d")
>           .output()
>   ```
>   
>   The only indication I found that RA was struggling was in the VS Code terminal:
> 
>   ```
>   [ERROR rust_analyzer::reload] failed to switch build data: rust-analyzer failed to run build scripts:
>   error: failed to run custom build command for `rust_voxel v0.1.0 (E:\Code\gitlab\rust_voxel)`
>   
>   Caused by:
>     process didn't exit successfully: `e:\Code\gitlab\rust_voxel\target\debug\build\rust_voxel-f1dd21816edff2bf\build-script-build` (exit code: 101)
>   ```
>   
>   Handling the `Result::Err` in my build script (cannot find the `date` command), the OUT_DIR issue is gone.

Perhaps others here have panics in their build scripts?

Not sure if this is a new issue or not. But  (n.b. you have to reload RA to get the `include!` macro to appear as an error - it looks like generated files linger in the VFS based on the extension's output)

This is a repro for how build script panics act (uncomment the panic in the build script):

https://github.com/dxenonb/ra-build-script-panic

**Comment by 35359595** [comment]
I have same issue with substrate [wasm builder](https://github.com/paritytech/substrate/blob/master/bin/node/runtime/build.rs) and wasm binary [inclusion macro](https://github.com/paritytech/substrate/blob/f57c6447af83a1706041d462ca290b4f2a1bac4f/bin/node/runtime/src/lib.rs#L101)

versions:
rustc 1.57.0-nightly (5b210643e 2021-10-11)
cargo 1.57.0-nightly (d56b42c54 2021-09-27)
rust-analyzer 7d6fcbc0b 2021-12-07 dev

MacOS 12.1

**Comment by ahicks92** [comment]
Saw this spuriously, and now Rust-analyzer is stuck with (copying as JSON in case it's more useful):

```
[{
	"resource": "/c:/projects/in_progress/ammo/protos/src/lib.rs",
	"owner": "rustc",
	"code": {
		"value": "macro-error",
		"target": {
			"$mid": 1,
			"external": "https://rust-analyzer.github.io/manual.html#macro-error",
			"path": "/manual.html",
			"scheme": "https",
			"authority": "rust-analyzer.github.io",
			"fragment": "macro-error"
		}
	},
	"severity": 8,
	"message": "failed to load file `c:\\projects\\in_progress\\ammo\\target\\debug\\build\\ammo_protos-ffd2ea0eb1b32fb8\\out/frontend.rs`",
	"source": "rust-analyzer",
	"startLineNumber": 10,
	"startColumn": 5,
	"endLineNumber": 10,
	"endColumn": 56
}]
```

Rust-analyzer is 0.2.853.

And the known-bad commit that the above error is from is here: https://github.com/audio-mmo/monorepo/commit/f227216f3550e9a4978dcb0aadfdb5e175705902

**Comment by Coronon** [comment]
Also facing this rn, is there any hotfix?

**Comment by bjorn3** [comment]
You can use `"rust-analyzer.diagnostics.disabled": ["macro-error"]` to disable presentation of the error. Which project do you get this error on by the way?

**Comment by Coronon** [comment]
From a freshly generated one using tonic. Interestingly, it works perfectly fine on windows, but not on ubuntu

**Comment by SHiftLin** [comment]
The same problem occurs

**Comment by GLodi** [comment]
If anyone is using Emacs with `lsp-mode`, a simple `M-x lsp-workspace-restart` seemed to do the trick.

**Comment by g0hl1n** [comment]
I'm facing the same issue in [neovim](https://github.com/neovim/neovim) with [rust-tools.nvim](https://github.com/simrat39/rust-tools.nvim) in default config.

rust-analyzer 4e72700e3 2022-02-28 stable
cargo 1.59.0 (49d8809dc 2022-02-10)
rustc 1.59.0 (9d1b2106e 2022-02-23)
NVIM v0.6.1
Fedora release 35 (Thirty Five)

**Comment by bjorn3** [comment]
Which project?

**Comment by keneek** [comment]
I've been having the same problem for a while, followed the link from @jonas-schievink [here](https://github.com/rust-analyzer/rust-analyzer/issues/9720#issuecomment-889859735).

Once I added this snippet below to `settings.json` for vs code it went away (for now).

```json
{
    "rust-analyzer.server.path": "rust-analyzer"
}
```

**Comment by oldgalileo** [comment]
Using the MacPorts rust-analyzer (https://ports.macports.org/port/rust-analyzer/details/) and running into the same issue, with a similar setup to @g0hl1n but running:
- cargo 1.56.0 (4ed5d137b 2021-10-04)
- rustc 1.56.1 (59eed8a2a 2021-11-01)
- NVIM v0.7.0-dev+1299-g773516365
- macOS 12.0.1

**Comment by Veykril** [comment]
#11960 added some better error reporting which should help with this. I am going to close this now as there is a ton of stale information in here. If you do run into this, please do open a new issue, with the `Rust Analyzer Language Server` log output and ideally a sample reproducer.

**Comment by TulioMeran** [comment]
Hi,

in my case the solution was install protobuf in my local machine, I use Mac so I run "brew install protobuf" after that I was complete the project and the error is done.

**Comment by gregpalaci** [comment]
https://github.com/tauri-apps/tauri/issues/8442 solved closing vs-code and reopen also maybe

**Comment by ZeeshanAhmadKhalil** [comment]
Restarting the VS code fixed the issue for me

**Comment by MolotovCherry** [comment]
I got this error today. For me it was simply due to the build script failing (no idea why this error showed up tho), but once I fixed the panic, it worked
