### ISSUE TITLE
"Find all references" not working on `#[async-trait]` trait

### ISSUE THREAD

**Issue by vorot93** [rust-lang/rust-analyzer#9754]
This is a serious regression in nightly and it's important to fix it before the next release.
@matklad, please take a look.

https://github.com/rust-ethereum/akula
branch ra-repro
`src/downloader/sentry_client_reactor.rs:55` - cannot find references to `new`, also `!!MISSING: command!!` above signature.

`src/downloader/sentry_client.rs:30` - cannot find references to, or implementations of trait.

**Comment by lnicola** [comment]
> `thread '<unnamed>' panicked at 'overflow depth reached'`

It's a chalk issue, and probably not a regression.

**Comment by lnicola** [comment]
CC https://github.com/rust-analyzer/rust-analyzer/issues/7817. Something like this might help:

```
"rust-analyzer.server.extraEnv": {
      "CHALK_OVERFLOW_DEPTH": 250
}
```

**Comment by vorot93** [comment]
@lnicola Can confirm that setting Chalk overflow depth works for first case.

I did report this as regression, because I didn't see any RA issues with this codebase before. Nevertheless, apologies if it's not a regression per se.

**Comment by lnicola** [comment]
The second issue is new (unreported), I suppose, but #7817 has plenty of people running into this with `tonic`.

We should at least increase the default overflow depth.

**Comment by matklad** [comment]
Unassigning myself: I've pinged chalk folks about the chalk specific issue. I can't repro the missing command one, let's wait if someone else hits it (the relevant code was changed in this release).

Thanks for tagging with nightly regression -- its better to over-tag then under-tag!
