### ISSUE TITLE
Clippy as command leads to no diagnostics

### ISSUE THREAD

**Issue by augustocdias** [rust-lang/rust-analyzer#9768]
If I set the setting `rust-analyzer.checkOnSave.command` to `clippy` I'm getting no diagnostics (on multi project workspaces) since last week's rust-analyzer update. Is this an issue with coc or rust-analyzer?

I could reproduce the issue on VSCode and NeoVim+Coc (https://github.com/fannheyward/coc-rust-analyzer/issues/833)

**Comment by equal-l2** [comment]
Any updates here?

**Comment by Leandros** [comment]
Same issue here, I get no diagnostics on a workspace project. Running `cargo clippy` manually works.

**Comment by tami5** [comment]
Same issue

**Comment by Veykril** [comment]
This needs a reproducer for us to be actionable, or at least some logs.

**Comment by fdelacruz** [comment]
Any updates on this issue?

**Comment by Leandros** [comment]
I can reproduce it easily. How can I get you some logs?

**Comment by Veykril** [comment]
On VSCode you can get the logs here ![grafik](https://user-images.githubusercontent.com/3757771/188868940-7529f51c-e9ca-4c06-8abb-43a3dbf86f41.png)

**Comment by Veykril** [comment]
Are people still running into this? We'd need to see a repro this reproduces on

**Comment by pattop** [comment]
Still happens for me.

**Comment by lnicola** [comment]
Closing, since there's not enough information to do anything about it.
