### ISSUE TITLE
Inlining a function call with const generics results in wrong code

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust-analyzer#9831]
Consider the following

```rust
fn n_to_m<const N: u8, const M: u8>() {
    for _ in N..M {}
}

fn main() {
    n_to_m::<0, 5>();
}
```

When expanding the `n_to_m` call in `main`, the result is

```rust
fn n_to_m<const N: u8, const M: u8>() {
    for _ in N..M {}
}

fn main() {
    for _ in N..M {};
}
```

This is objectively wrong. It should be `for _ in 0..5 {}` or an equivalent construct.

r-a version: 5664a2b0b 2021-08-09 stable. VS Code if it matters.

**Comment by Veykril** [comment]
This should also be problematic when inlining generic functions that use generic type paths in the body currently.

**Comment by Veykril** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/9842 fixes this for types, doing this for const generics is blocked(for now I think) on better const generics support.

**Comment by Veykril** [comment]
Yes this has been implemented
