### ISSUE TITLE
Exclude descendants of `#[doc(hidden)]` modules from auto-completions

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust-analyzer#9911]
`#[doc(hidden)]` items are usually internals APIs that is not intended for use. It would be nice if they can be excluded from auto-completion results for downstream crates.

For projects using stable rustc, it's also nice to exclude `#[unstable]` items too.

**Comment by lnicola** [comment]
We already exclude `#[doc(hidden)]` from completion _outside_ of the current crate. Not sure about `#[unstable]`, though.

**Comment by flodiebold** [comment]
Excluding unstable items is #3020.

**Comment by crlf0710** [comment]
@lnicola I've not sure whether i missed something, but this is what i got when i wrote a proc-macro today:
![image](https://user-images.githubusercontent.com/451806/129601621-1a6ab7e8-e318-484d-b2a2-d8ca4cf40229.png)

The `proc_macro::bridge` should definitely be excluded because `bridge` is `#[doc(hidden)]`

**Comment by kjeremy** [comment]
Can we give it a lower score instead of excluding it?

**Comment by lnicola** [comment]
I think we exclude hidden items, but not descendents of hidden modules.

**Comment by crlf0710** [comment]
Maybe it's worth add excluding descendents of hidden modules as an option, if not make it default behavior...

**Comment by lnicola** [comment]
No, it's a good idea, it was probably an oversight.

**Comment by jyn514** [comment]
FWIW I consider it a bug that doc(hidden) applies recursively, rustdoc should still show the items if they're re-exported to a module that's not hidden: https://github.com/rust-lang/rust/issues/59368

But I agree they should be hidden if they're not reexported.

**Comment by flodiebold** [comment]
Yeah, I don't think "Excluding descendants of `#[doc(hidden)]`" is exactly what we want -- but rather "Exclude auto-imports that include `#[doc(hidden)]` modules in the path".

**Comment by jplatte** [comment]
For the import quick-fix for unresolved symbols (specifically a macro in my case), no amount of `#[doc(hidden)]` (in the proc-macro crate, for the re-export site, for the enclosing module of the re-export site) seems to prevent RA from suggesting it as an import location. Does the existing logic for this only affect auto-completions, not the import quick-fix?

**Comment by Veykril** [comment]
Fixed in https://github.com/rust-lang/rust-analyzer/pull/15473
