### ISSUE TITLE
`safer-ffi` macros fail to resolve

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#9915]
It seems that we fail to resolve some of the macros in https://docs.rs/safer-ffi/0.0.6/safer_ffi/, even when the corresponding Cargo feature is enabled.

Enabling attribute macros makes this worse, since `#[ffi_export]` expands to a call to `::safer_ffi::__ffi_export__!`, which also doesn't resolve and then puts error markers all over the function.

**Comment by ro99** [comment]
Is there any workaround for this?

**Comment by Veykril** [comment]
Seems to work now
