### ISSUE TITLE
"Show implementations" display error

### ISSUE THREAD

**Issue by liby** [rust-lang/rust-analyzer#9926]
https://user-images.githubusercontent.com/38807139/129599376-82549267-f51d-4693-ab6c-987a8d566a59.mp4

**Comment by Veykril** [comment]
I think this happens for anything that has X amount of implementations or more where X seems to be somewhere around 200-300 🤔

**Comment by lnicola** [comment]
Code bug?

**Comment by Veykril** [comment]
I would believe so, this feels like we are hitting some arbitrary limit and I don't see where we would cause that.

**Comment by Veykril** [comment]
Does any other client implement hover actions?

**Comment by lnicola** [comment]
`coc-rust-analyzer` supposedly does, but I don't use it.

**Comment by Veykril** [comment]
Something else to note here is that hovering over `Clone` for example in RA takes a few seconds to actually show me the hover which I assume is due to us collecting all the impls, we might wanna take a look at that.

**Comment by liby** [comment]
@Veykril @lnicola 
So do you guys have any clue so far? Or do you need me to do anything?

**Comment by Veykril** [comment]
We assume this is an issue on the VSCode side, basically it looks like its failing to parse the link if its too long(that is, when there are too many implementations). Would be good to know if this happens in other editors as well that have this feature implemented.

**Comment by lnicola** [comment]
See https://github.com/rust-analyzer/rust-analyzer/issues/11742 for a slightly better test case.
