### ISSUE TITLE
Package does not have the feature 'foo'

### ISSUE THREAD

**Issue by alanhkarp** [rust-lang/rust-analyzer#9930]
I just cloned a git repository, and VSCode reports the error:

> rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file ... Package `bar` does not have the feature `foo`

I have another project open that does include that feature.  I asked for help on this problem on URLO on May 13 but didn't get a response.

The problem low priority because my workaround is to include the feature in Cargo.toml even though the project doesn't need it.  Even so, it is annoying.

**Comment by lnicola** [comment]
Does e.g. `cargo check --all-targets --all-features` work in that repository? It's a `cargo`, not a `rust-analyzer` error.

**Comment by alanhkarp** [comment]
The cargo check command on the command line reports no errors when that
feature is not included in the Cargo.toml, but I get the rust-analyzer
error in VSCode.  Does that mean it's not a cargo problem?

--------------
Alan Karp

**Comment by lnicola** [comment]
Can you share your project or a reduced version of it (you can remove all the code etc.)?

**Comment by alanhkarp** [comment]
https://github.com/dalnefre/ReActor is the one that needs no features.

--------------
Alan Karp

**Comment by lnicola** [comment]
Is there anything else I need to do, like making another project and adding a dependency to this one?

**Comment by alanhkarp** [comment]
There is no connection between this project and the one that needs the
feature.

I originally had
https://github.com/earthcomputing/CellAgent/tree/userspace-master/userspace/cellagent
running in VSCode.  I then added
https://github.com/earthcomputing/CellAgent/tree/userspace-master/userspace/actix_server
and got the problem.  It doesn't use any features, but I had to include
those from the first project.  I thought that maybe the connection between
the two projects was the reason.  I was shocked when the problem arose with
a completely independent repo.

If you need to look at my code, please promise not to laugh; it's my first
Rust program.

--------------
Alan Karp

**Comment by lnicola** [comment]
I'm afraid I could use a more detailed description of the problem.

> I have another project open that does include that feature.

Is that https://github.com/dalnefre/ReActor? It works fine for me. Or are you saying that it works as expected? In that case, it's fine.

> I originally had
https://github.com/earthcomputing/CellAgent/tree/userspace-master/userspace/cellagent running in VSCode.  I then added https://github.com/earthcomputing/CellAgent/tree/userspace-master/userspace/actix_server and got the problem.

Are you using a Code workspace? I opened their parent directory (`userspace`) and everything looks fine.

**Comment by alanhkarp** [comment]
ReActor gives me the error message unless I add api-old, simulator, and
webserver as features in its Cargo.toml.

I only open projects from their parent directories, so I don't have any
multi-root workspaces if that's what you mean.

--------------
Alan Karp

**Comment by alanhkarp** [comment]
After a break from Rust, I decided to learn wasm from the game of life tutorial.  I am getting the same problem on this new project.  The difference is that now I have time to investigate the problem further.  At this point, I'm not asking for a fix but for information to help me track down what I did wrong and how to undo it.  The code is on [github](https://github.com/alanhkarp/wasm-game-of-life). 

The Rust Analyzer Language Server log shows

> [ERROR rust_analyzer::lsp_utils] rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /Users/alan/Documents/wasm-game-of-life/Cargo.toml, Some(Version { major: 1, minor: 63, patch: 0 }): Failed to run `"cargo" "metadata" "--format-version" "1" "--features" "api-old, simulator, webserver" "--manifest-path" "/Users/alan/Documents/wasm-game-of-life/Cargo.toml" "--filter-platform" "x86_64-apple-darwin"`: `cargo metadata` exited with an error: error: Package `wasm-game-of-life v0.1.0 (/Users/alan/Documents/wasm-game-of-life)` does not have the feature `api-old` 

I have searched, but I can't find where the command 

> "cargo" "metadata" "--format-version" "1" "--features" "api-old, simulator, webserver" "--manifest-path" "/Users/alan/Documents/wasm-game-of-life/Cargo.toml" "--filter-platform" "x86_64-apple-darwin"`

command is coming from.  I tried overriding it by including

>   "rust-analyzer.cargo.buildScripts.overrideCommand": [
    "cargo check --quiet --workspace --message-format=json --all-targets",
    "cargo build --quiet --workspace --message-format=json --all-targets",
    "cargo run --quiet --workspace --message-format=json --all-targets",
    "cargo test --quiet --workspace --message-format=json --all-targets"
  ]

in settings.json, but that didn't change the result.

When I include the 3 features , I get a different error.

>[ERROR rust_analyzer::lsp_utils] failed to run build scripts

>Failed to run build scripts for /Users/alan/Documents/wasm-game-of-life: No such file or directory (os error 2)

>[ERROR rust_analyzer::lsp_utils] failed to run build scripts

>Failed to run build scripts for /Users/alan/Documents/wasm-game-of-life: No such file or directory (os error 2)

>[ERROR flycheck] Flycheck failed to run the following command: "cargo" "check" "--bin" "simulator" "--features" "api-old, simulator, webserver" "--message-format=json"
[ERROR rust_analyzer::lsp_utils] cargo check failed

>Cargo watcher failed, the command produced no valid metadata (exit code: ExitStatus(unix_wait_status(25856))):
error: no bin target named `simulator`

Notice that the check command refers to a binary that doesn't exist in this project.  My best bet is that the command is coming from metadata stored in the VSCode global environment, but I can't find it.

Any pointers for where to look would be greatly appreciated.

**Comment by alanhkarp** [comment]
I fixed the problem with a sledgehammer.  I completely uninstalled VSCode and all of its data following the instructions at https://linuxpip.org/uninstall-vscode-mac/.  I then re-installed VSCode and the Rust Analyzer.  Everything appears to be working as it should.
