### ISSUE TITLE
Infers the argument type of the closure function as `unknown`

### ISSUE THREAD

**Issue by liby** [rust-lang/rust-analyzer#9946]
Apologies if what I'm asking has a completely obvious solution, but I just can't see it.

The code that puzzles me is [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6f442bfedc2c31a7bc541cb09af0e1ab). It seems to be working well, but this will cause the argument of the closure function to be inferred as `&{unknown}`, is there any way to solve this other than manually marking the type?

![image](https://user-images.githubusercontent.com/38807139/129996816-da35f988-8214-4cc3-9850-cdc8704398b8.png)

Is this the expected behavior? Is it because the parameter is defined as generic, which leads to this behavior?

**Comment by jonas-schievink** [comment]
Reduced to:

```rust
struct Cacher<F, K, V>(F, K, V);

impl<F, K, V> Cacher<F, K, V>
where
    F: Fn(&K) -> V,
{
    fn new(_: F) -> Cacher<F, K, V> {
        loop {}
    }

    fn value(&mut self, _: K) -> &V {
        loop {}
    }
}

fn main() {
    let mut c = Cacher::new(|a| *a);

    let v2 = c.value(2);

    assert_eq!(*v2, 2);
}
```

Neither `c` nor `v2` get the correct type inferred, but rustc accepts this program.

**Comment by lowr** [comment]
This has since been fixed and we can correctly infer the types now (yay!). Closing as completed.
