### ISSUE TITLE
do not auto import with prefix-space for impl snippet.

### ISSUE THREAD

**Issue by sundar-h** [rust-lang/rust-analyzer#9958]
by hint `impl` for tab; I got
```
impl {space}{
{space}{space}{space}{space} // leader 4 space
}
```
by typing fmt, I wish get some suggestions like `fmt (use std::fmt)...`,   But nothing appeared,
When delete `impl` snippet to below.
```
impl {cursor} {space}{
// deleted leader 4 space
}
``` 
Or 
``` 
impl {cursor} {space}{
}
```
Or
```
impl {cursor} {space}{}
```
I got that tips expected when typed `fmt` in {cursor}
![image](https://user-images.githubusercontent.com/58337516/130206093-0dc376b3-65db-44df-a235-2e6506b94e65.png)

I tried also move cursor by tab to second postion, and then move back to first position, then typed fmt,  and then got suggestions to.
```
impl {} {
{}{}{}{}cursor
}
```

It looks like suggesstion does not work well with snippet with Tab Postition.

**Comment by Veykril** [comment]
You'll need to set `    "editor.suggest.snippetsPreventQuickSuggestions": false,` to prevent this from happening
