### ISSUE TITLE
Feature request: highlight function return when Propagating Errors and implicit return

### ISSUE THREAD

**Issue by wasd96040501** [rust-lang/rust-analyzer#9969]
``` rust
fn foo() -> u32 {
    ...
    1 + 1 (should highlight or has something indicating this will return)
}
```

**Comment by flodiebold** [comment]
We already highlight the last expression as an exit point when you hover the return arrow. I don't really see the point of highlighting all last expressions all the time? :thinking:

**Comment by lnicola** [comment]
Oh, I thought we somehow didn't in this case:

![image](https://user-images.githubusercontent.com/308347/130325904-a14cc767-67f0-4ff1-ba6c-64e5f4329425.png)

**Comment by wasd96040501** [comment]
![image](https://user-images.githubusercontent.com/14040068/130360934-82b0b49f-eaee-4bd4-aea8-c9a4ab302c16.png)
Thanks for your reply.

**Comment by Veykril** [comment]
I don't think we can support something like this(not without an extension at least, though VSCode also might not let us clientside). If I see this right goland collapses the line with the return and then annotates the preceding if statement with the return values. This would need proper support from the LSP.
